### ISSUE TITLE
[Linux] desktop file is lacking a Categories= entry

### ISSUE THREAD

**Issue by probonopd** [johannesjo/super-productivity#10]
The desktop file inside http://super-productivity.com/downloads/superProductivity-latest-x86_64.AppImage is lacking a `Categories=` entry in the `*.desktop` file.

According to the [menu spec](https://standards.freedesktop.org/menu-spec/latest/apa.html),

> By including one of the Main Categories in an application's desktop entry file, the application will be ensured that it will show up in a section of the application menu dedicated to this category. If multiple Main Categories are included in a single desktop entry file, the entry may appear more than once in the menu. 

Hence, please add at least one of the following in the `Categories=` key.

Main Category | Description | Notes
-- | -- | --
AudioVideo | Application for presenting, creating, or processing multimedia (audio/video) |  
Audio | An audio application | Desktop entry must include AudioVideo as well
Video | A video application | Desktop entry must include AudioVideo as well
Development | An application for development |  
Education | Educational software |  
Game | A game |  
Graphics | Application for viewing, creating, or processing graphics |  
Network | Network application such as a web browser |  
Office | An office type application |  
Science | Scientific software |  
Settings | Settings applications | Entries may appear in a separate menu or as part of a 		"Control Center"
System | System application, "System Tools" such as say a log viewer or network monitor |  
Utility | Small utility application, "Accessories"

In addition, you could specify one or more from the longer list of [Additional Categories](https://standards.freedesktop.org/menu-spec/latest/apas02.html).

Please test the result with `desktop-file-validate` and make sure it passes.

electron-builder offers native support for this since [v19.22.1](https://github.com/electron-userland/electron-builder/releases/tag/v19.22.1).

Reference: https://github.com/AppImage/AppImageHub/issues/2

**Comment by johannesjo** [comment]
Thank you very much for reporting! Would you be interested in providing a pull request for the issue?

**Comment by probonopd** [comment]
Sorry, I wouldn't even know where to start because I cannot find the desktop file to be edited in this repository. Probably it is generated by electron-builder, so updating to the latest electron-builder should do wonders.

**Comment by johannesjo** [comment]
No worries! Thanks for the detailed report! I'll look into it. Out of curiosity: are you using the tool on a regular basis? Would love to hear your thoughts about it!

**Comment by probonopd** [comment]
Actually I am building a directory of AppImages, https://github.com/AppImage/AppImageHub/ (hey, free advertising!) and don't really use the tool otherwise.

**Comment by johannesjo** [comment]
@probonopd: I Updated the build setup to include the category. Thanks again for reporting. Is there any more meta data you would add?

**Comment by probonopd** [comment]
Thank you @johannesjo. Please let me know once a new build including the change is available for download. If you would like to add more metadata, have a look at [AppStream metainfo files](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps) - if you put one into the `usr/share/metainfo` directory inside the AppImage, then AppImageHub will use information provided by it.

**Comment by johannesjo** [comment]
The change should be already available for download. Thanks again for your help!

**Comment by probonopd** [comment]
Sorry if I have to bug you again, but it seems it's still not working yet:
https://travis-ci.org/AppImage/appimage.github.io/builds/268054073#L569

Or am I doing something wrong?

**Comment by johannesjo** [comment]
Thanks for reporting. The desktop file for the deb installation works fine. Not sure if the app image file is correctly build. How do I extract the Meta Data?

**Comment by johannesjo** [comment]
Ok. I think the issue was that something went wrong with the upload. Hopefully it works now. Locally everything seems to be in place. Could you maybe check again?
