### ISSUE TITLE
FIxed Your Intro Video's Audio

### ISSUE THREAD

**Issue by Sp-cy** [johannesjo/super-productivity#1000]
Hi Johannes.
 Just wanted to let you know that i fixed your intro video's audio because it was very noisy. You can find the fixed audio here: 

``` 
https://github.com/Sp-cy/Super-Productivity-Intro-Video 
```

Let me know if you need help with future videos.

**Comment by johannesjo** [comment]
Hi there! Thank you very much! Not sure how to get this new track into the uploaded video on youtube.... :-D

**Comment by Sp-cy** [comment]
There should be a video Editor option in the YouTube video and a web app will load. You can add another audio track and maybe delete de past one... i think. 

Let me know if I could help you with future videos. I can't code so I rather contribute to open source with media.  **Thanks** for making this app and making it private and open source.

**Comment by johannesjo** [comment]
Thank you! I'll change the video later today.

**Comment by johannesjo** [comment]
That audio function is only for adding songs and sounds from the youtube lib. I think there is no build in way to add a new audio track. Seems like my only option is to edit this in a video editor (which will take a lot of time to do for me) and to reupload it, which will make me loose all comments and views. Thank you very much for your help again. Given all that I am fine with how the video is now. Might make sense to upload a complete new video at some point anyway.
