### ISSUE TITLE
Add startup possibility for windows

### ISSUE THREAD

**Issue by m-344** [johannesjo/super-productivity#1003]
Hi, I've installed _super productivity_ via windows (10) store. I cannot find the possibility to add it to startup: when searching for file location there isn't any option for this. I considered to install the app locally with _superProductivity-6.5.2.exe_ but windows defender gave me a warning _an unknown publisher_, so I didn't try this. Also the version in windows store is 6.5.0.

**Comment by johannesjo** [comment]
Hi there!

Does this answer your question: https://support.microsoft.com/en-us/windows/add-an-app-to-run-automatically-at-startup-in-windows-10-150da165-dcd9-7230-517b-cf3c295d89dd
?

**Comment by m-344** [comment]
That is what I exactly tried to do with your app. See: _when searching for file location there isn't any option for this._ in the first post.

![image](https://user-images.githubusercontent.com/53567819/112454598-25c1dd80-8d59-11eb-8a1d-859a947c6b87.png)

**Comment by johannesjo** [comment]
This is more of a windows user question, than one related to the app itself. I am not on windows, but maybe somebody else knows a solution? 

Meanwhile you probably will be able to find one, if you google for this specific problem (replacing "super productivity" with "app").

**Comment by gyuri-szing** [comment]
My solution was:

1. press windows+r (opens run dialog)
2. type shell:startup (opens startup folder)
3. Press start button (opens start menu)
4. Drag&drop Super Productivity to startup folder.

**Comment by johannesjo** [comment]
Thank you very much for sharing @gyuri-szing !

**Comment by gyuri-szing** [comment]
Welcome!

If you wish to put some efforts into this, I was digging around in [Strechly](https://github.com/hovancik/stretchly/blob/096f941b46e7be478c26394d269cb5715246a118/app/main.js#L1132), which is also open-source and electron based. It seems to use [this API](https://www.electronjs.org/docs/api/app#appsetloginitemsettingssettings-macos-windows) and it shows up on Settings/Startup in Win10. I am not a JS dev, but for you it might be relatively simple to implement something based on this function.
