### ISSUE TITLE
Completed tasks still show up the reminder.

### ISSUE THREAD

**Issue by j7j11** [johannesjo/super-productivity#1005]
### Your Environment

* Version used: superProductivity-Setup-6.5.2.exe
* Operating System and version: Windows 10

### Expected Behavior
Tasks already completed don't show the reminder, because they are already done.
### Current Behavior
Already completed tasks still show up the reminder.

Is this intended behaviour?

I apologize in advance if this is intented behaviour, because I thought otherwise.

**Comment by johannesjo** [comment]
Hi there! This is currently the intended behavior, though it might make sense to change it. What would you think is better:
A. Always delete reminders, when a task is marked as done
B. Show a dialog that asks "You're marking a task done that has a reminder scheduled. Do you want to remove the reminder?"

**Comment by j7j11** [comment]
Hi! I think the better option would be B, because some people might need the reminder for some random reason. That way you don't actually remove functionality, but still have a way to inform the users that the reminder is still on and ask if they want it removed.

Thank you for this software!

**Comment by johannesjo** [comment]
In the end I decided to implement A as B can be a bit tedious. Thanks for your input again!
