### ISSUE TITLE
Improve search by removing special characters

### ISSUE THREAD

**Issue by kerkenit** [johannesjo/super-productivity#1008]
## Problem Statement
I've a task names E-mail. I'm searching for email and it won't be found. I need to go back and type e-m and it will find the task.

## :grey_question: Possible Solution
When searching remove al special charters and spaces to match. I't already serving lowercase

## :arrow_heading_up: Describe alternatives you've considered
Replace ema for e-ma and it will find Email

## :heavy_plus_sign: Additional context
I'm searching in the filed when I forgot to start a task. 
<img width="637" alt="Schermafbeelding 11" src="https://user-images.githubusercontent.com/13370203/112813331-60d84f80-907e-11eb-922b-cd962ef23d5f.png">

**Comment by johannesjo** [comment]
Thanks for opening this up. The problem is, that this would render short syntax useless (which one might use to track to a new task). I also wouldn't rule out that someone wants to deliberately search for a special character.
