### ISSUE TITLE
Play/pause buttons order

### ISSUE THREAD

**Issue by Acsigen** [johannesjo/super-productivity#101]
## Your Environment

* Version used: 
* Operating System and version: Windows 7 X64
* Desktop Environment: 
* Browser Name and version: 

## Expected Behavior
Hit play button counter/task starts and display the pause button to indicate the next action
Hit pause button counter/task button stops and display the play button to indicate the next action

## Current Behavior
Press the pause button starts a task/timer
Press play button pauses a task/timer

## Steps to Reproduce (for bugs)
1. Press the pause button starts a task/timer
2. Press play button pauses a task/timer
3. This issue appears everywhere except indivitual task buttons and dropdown buttons from the top right corner
Task/timer active:
![button 2](https://user-images.githubusercontent.com/13287878/42933534-b03d1d3c-8b4d-11e8-8421-0caab63ead27.JPG)
![buttons](https://user-images.githubusercontent.com/13287878/42933535-b05a52f8-8b4d-11e8-9bc8-dbb2b4f90bd3.JPG)
Task/timer inactive:
![dropdown](https://user-images.githubusercontent.com/13287878/42933536-b07df6ae-8b4d-11e8-881c-514a3a978378.jpg)

**Comment by johannesjo** [comment]
Hey there! Thanks opening up this issue. I remember that I was struggeling with that question myself. Looking at it seperatly the given choices felt better how they're arranged now. But I agreee that consistency might be good.

**Comment by Acsigen** [comment]
In the dropdown menu I consider that there's no need for the play button to be displayed under the pause button (3rd image) because clicking the top button already works.
