### ISSUE TITLE
Android app quits as you press Android's back button + app reloads everything and throws you to Today.

### ISSUE THREAD

**Issue by phazec** [johannesjo/super-productivity#1012]
### Your Environment

* Version used:  apk, 12.0
* Operating System and version: OxygenOS 10.0.1 (OnePlus 5 stock)
* Desktop Environment: 
* Browser Name and version: 

### Expected Behavior
As you press Android's back button, the app should do the exact same thing, as when you stretch your hand to app's back button in the upper left corner. From main screen it should "quit" in an android sense.

### Current Behavior

Quits immediately as you press back. "Confirm before exiting the app" preference is set, but quits without confirmation. If you start from icon OR from last used apps list, it reloads and you're in "Today" screen again. 

### Steps to Reproduce (for bugs)

1. Edit some subtask's name (I did this)
2. Press Android's back button

**Comment by johannesjo** [comment]
Hi there! Thank you very much for opening this up! I'd also like to fix this and help would be greatly appreciated. This needs to be solved in the [Android repository of the app](https://github.com/johannesjo/super-productivity-android).

**Comment by ffcruz85** [comment]
I can report same is happening here. When I am in a sub menu, like settings, I would expect it to return to main screen. Maybe when in main screen, closing the app would be OK - the main issue for me is that it both closes the app AND quits tracking time, when I go back, pomodoro timer is reset and stopped. using overview button to get out of the app works fine though, keeps tracking time. I also have the "confirm before exiting setting enabled", which works on windows but not on android
OnePlus 7 Pro, Android 11

**Comment by mathisgauthey** [comment]
This was still relevant.

**Comment by zeufack** [comment]
is someone working on it ?

**Comment by johannesjo** [comment]
@zeufack no currently not. Help would be very much welcome!

**Comment by zeufack** [comment]
ok il will try to fix it

**Comment by johannesjo** [comment]
I spend a considerable amount of time on this myself, but was unable to work around it. Help from an experienced Android Dev (or just someone with a fresh perspective) would be very welcome!
