### ISSUE TITLE
Worklog Data Addition Suggestion 

### ISSUE THREAD

**Issue by MarcosSbarbati** [johannesjo/super-productivity#1019]
I find myself often exporting the data from the Worklog for a weekly analysis and I realized that the starting and ending times for each task are not the actual individual starting and ending times for those tasks. That based on the amount of time they were worked on. Instead, it gives a time range that I can't grasp on what measure it's making.  In other words, the starting and ending times that appear on the Worklog are not the actual starting and ending times that each individual task took based on the time of the day they were started and stopped/finished. It would be cool if it had an option to make a new data column that had the starting and ending times based on the time of the day for the amount of time worked on each task and when it was started and finished. Like if I want to go and eat lunch at 1 pm and I do it until 1:30pm, the data is recorded as Lunch, Start:1pm, End: 1:30 pm.
Sorry if this is not clear, English is not my first language. 
Also this app is the best alternative I could find that fits with my needs, and the exporting data option was the main reason why I switched to this one. Congratulations on the work!

**Comment by johannesjo** [comment]
Hey there! Thanks for opening this up! To limit the amount of data the time tracking model is a bit simplified (for performance reasons and to save disk space as well). There are no time periods saved, just the day and the amount of seconds worked.


```
export interface TaskCopy extends IssueFieldsForTask {
  id: string;
  projectId: string | null;
  title: string;

  subTaskIds: string[];
  timeSpentOnDay: TimeSpentOnDay;
  timeSpent: number;
  timeEstimate: number;

  created: number;
  isDone: boolean;
  doneOn: number | null;
  plannedAt: number | null;
  // remindCfg: TaskReminderOptionId;

  notes: string;

  parentId: string | null;
  reminderId: string | null;
  repeatCfgId: string | null;
  tagIds: string[];

  // attachments
  attachments: TaskAttachment[];

  // ui model
  // 0: show, 1: hide-done tasks, 2: hide all sub tasks
  _showSubTasksMode: ShowSubTasksMode;
}
````
