### ISSUE TITLE
[Feature]  Remember & Restore app's locations & size after reboot and re attach same monitor !

### ISSUE THREAD

**Issue by mtdoyaji** [johannesjo/super-productivity#102]
```
## Your Environment

* Version used:  1.10.45
* Operating System and version: Windows 10

## Expected Behavior

All app's behavior below, keep same after
-  rebooted.
-  same monitor re attached. (It's not common behavior in windows default apps)

Well working behavior :

User resize app's window size & close.
User open app. last window size restored.

If User has multiple monitor, app restore it's last location.
If User detach one of One's monitor, app restore It's position by nearest monitor edge.

If User re attach monitor just before detach, app restore It's location by monitor's (some kind of) Id


## Current Behavior

It's reset his position & location when reboot.

It's not restore his monitor location when re attach same monitor again.

**Comment by johannesjo** [comment]
Hey there, thanks for reporting. Imho this is more the responsibility of your OS. Currently I had to deal with a Windows machine at my last job and I remember that I was able to make it work somehow though I don't remember how exactly. Maybe have a look: 
https://www.google.de/search?q=windows+10+remember+window+position

**Comment by soheilred** [comment]
How about the app's font size? The initial font size a little bit too big to my eyes, and I need to reduce the font size every time that I open the app. Is there any way to fix this?

**Comment by johannesjo** [comment]
@soheilred yes there is. You can use Ctrl+Scrollwheel to zoom in and zoom out.

**Comment by soheilred** [comment]
That would be the shortcut to change the font size. But, I mean is there any way to set the font size, and the next time that the app is opened, it keeps the previous font size.
Or, I can put it in this way: the font size that the user has previously set has to be saved somewhere in the config files. If that size can be set to a fix value, which then the user is able to change, that is going to preserve the previous setting that the user has. Does that make sense?

**Comment by johannesjo** [comment]
@soheilred Would you maybe be willing to provide a pull request for that?

**Comment by soheilred** [comment]
@johannesjo I wish I could. But, I have never coded in Electron.

**Comment by johannesjo** [comment]
Alright. No problem :) I make the changes myself. Thanks for suggesting the changes.

**Comment by johannesjo** [comment]
Looks like the feature was already implemented, but there is a critical issue with electron:
https://github.com/electron/electron/issues/5708
I check if i can find a workaroud.

**Comment by soheilred** [comment]
@johannesjo Yes, you're right. Seems to be an open issue on the Electron side.
I did a quick search and found [this page](https://github.com/electron/electron/issues/1731).
Especially [this comment](https://github.com/electron/electron/issues/1731#issuecomment-104163088) was interesting.

**Comment by soheilred** [comment]
Based on what other people have suggested on the link, I think calling `app.exit` instead of `app.quit` should do the trick.

**Comment by johannesjo** [comment]
Problem is that it also that the locaStorage is always deleted completely (at least on my system with ubuntu 18.04) when I just click the close button. It only works when the app is closed from the daily summary.

**Comment by johannesjo** [comment]
I think I found a solution. Should be out available the edge channel in a bit.

**Comment by KonTy** [comment]
> Problem is that it also that the locaStorage is always deleted completely (at least on my system with ubuntu 18.04) when I just click the close button. It only works when the app is closed from the daily summary.

Ah that is why all my Tasks disappear. I thought I did something wrong. Turns out it is a bug. I lost 3 months worth of Tasks to this bug and since I don't sync with Google or Jira that's info lost forever :)

**Comment by johannesjo** [comment]
@KonTy if you use the electron version there are automatic backups to check for the data. The path of them should be printed out if you start the app from the command line.

Not sure if this is related to your issue though, because the bug doesn't seem to affect the IndexDB which the tasks are saved to.

**Comment by KonTy** [comment]
To be honest I don't have any details, I just came in one morning after a vacation actually, the app got upgraded automatically by the Microsoft Store. I launched it and all of my Tasks were gone. I shrugged it off and moved on.
