### ISSUE TITLE
Duplicate GitHub backlog entries created

### ISSUE THREAD

**Issue by askpatrickw** [johannesjo/super-productivity#1021]
### Your Environment

* Version used: Desktop Version 6.5.2 (6.5.2)
* Operating System and version: MacOS on M1 Mac Mini

### Expected Behavior
Each issue in my Repo should be in the backlog, once.

### Current Behavior
I have 7 issues in my repo.
I have 106 issues (dupes) in my backlog

### Steps to Reproduce (for bugs)
1. Setup GitHub key
2. Add Repo
3. Check all the boxes
4. Add user name

### Console Output
none found

### Error Log (Desktop only)
none found

**Comment by johannesjo** [comment]
Thanks for reporting this. I can confirm, that this happens occasionally.

**Comment by TvrtkoM** [comment]
19 issues on github, 793 entries in app. It's annoying. How can I clean up the database without affecting project logged hours etc.

**Comment by johannesjo** [comment]
@TvrtkoM could you maybe provide some additional context/logs? I haven't been able to pin down what is causing this exactly.

> How can I clean up the database without affecting project logged hours etc? It also seem to slow down my computer.

Not sure if this helpful: You can freely delete all git issues without time tracking data.

**Comment by wilbowma** [comment]
This seems to happen with the CalDAV backend too, which suggest it might not be provider-specific.

**Comment by johannesjo** [comment]
Thank you very much @Alexander-Linkov ! This was very helpful! I figured out what went wrong and will provide a fix with the upcoming release.
