### ISSUE TITLE
Add scheduling via @[optional: date]time

### ISSUE THREAD

**Issue by Batazai** [johannesjo/super-productivity#1024]
## Problem Statement

I want to schedule tasks when creating them. This saves time and it is consistent: Other information that is inherent to the task can be given when a task is created, the point in time when to do it is not (yet).

## :grey_question: Possible Solution

I imagine a @-tag. Imagine I have a meeting tomorrow at 2pm. I want to create a task for it and schedule it. Until now I create it via: `Meeting organise vaccinations +nocovid #urgent #germany`, click on additional Info and schedule it.

I'd like that if I add  `@2021-04-09/14:00` [unsure if this is the cleverest syntax] I want the task to be scheduled for April 09 2021 at 2pm current timezone. If I omit the date it should default to today: `@14:00 `should be equal to today: `@2021-04-08/14:00`.

## :arrow_heading_up: Describe alternatives you've considered

I have not considered an alternative

## :heavy_plus_sign: Additional context

I have look through the other feature requests and have not found it.
It's an awesome app. I love it.

**Comment by johannesjo** [comment]
Hi there! Thanks for opening this up! I am all for it! Help would be appreciated!

**Comment by vorpalvorpal** [comment]
Some thoughts on syntax for due dates. 

My intuition are that the following due dates are likely to be the most common:

- x hours from now
- x minutes from now
- Tomorrow morning
- 24 hours from now
- Next week
- Next month
- Next year

ISO 8601 provides the following datetime syntax: `YYYY-MM-DDThh:mm:ss`. This provides a good starting base, but requires too much to be typed quickly. My suggestion:

``` @(((YYYY-)MM-)DD)(.hh(:mm(:ss)))```

In what follows it is assumed that it is currently `2022-02-03T09:00:00`
**Dates**
- Where part of the date is missing it is filled in with the current value for the missing part. `@05` expands to `2022-02-05` and `@03-12` expands to `2022-03-12`
- +x adds x to current value. `@+1` becomes `2022-02-04`. `@+1-12` becomes `2022-03-12`
- If + is used, it replaces the need for a dash. So `@+1+1` is one month and a day from now but `@+1-+1` is not (it is one year and one day from now).
- +x can add more days/months than can be accommodated by the current month/year. So `@+13+40` (plus 13 months plus 40 days) becomes `2023-04-12`
- Levels can be skipped by just using dashes. In this case that level is filled with its current value. `@2024--` becomes `2024-02-03`. `@2024-+1` becomes `2024-02-04`

**Times**
- If times are left unspecified they are filled in by a default time set in the options. The default time is 9am. Using the default setting `@05` fully expands to `2022-02-05T09:00:00`
    + This can be overidden by specifying any part of the time (the dot by itself is sufficient). Thus `@+1` is tomorrow at 9am (or whatever the option is set as) whereas `@+1.` is exactly 24 hours from now.
- Days and hours are likely to be the two values that are most likely to be used by themselves, they are disambiguated by a `.`. So `@10` means the 10th of the current month, whereas `@.10` is 10am today. 
- If no date is specified it is assumed to be today. `@.13` expands to `2022-02-05T13:00:00`
- As with dates, if a level is skipped it is filled with its current value. `@.:30` is set to 30minutes from now ie `2022-02-03T09:30:00`
- As with dates, +x can be used to add time. 
    + Similarly to dates, the use of + replaces :
    + If more than 60 seconds/minutes or 24 hours are added then they add to the next unit. 
    + So `@.+26+100` (plus 26 hours and 100 minutes) becomes `2022-02-04T12:40:00`

**Remind at**
- 'Remind at' can be explicitly set using `@@` and then the same syntax as listed above.
- When 'Remind at' is not explicitly set, it is automatically set using settings from the options. The first setting is for tasks due on the same day as creation. This defaults to one hour before the due date (?). The second setting is for tasks due after the creation date. This defaults to 24 hours before the due date (?). These can be changed or entirely turned off based on needs.

**Syntax for the common use cases noted above.**

- x hours from now (where x = 2) 
    + `@.+2`
- x minutes from now (where x = 30)
    + `@.:+30`
- Tomorrow morning
    + `@+1`
- 24 hours from now
    + `@+1.`
- Next week
    + `@+7`
- Next month
    + `@+30` (thirty days from now)
    + `@+1-` (One calendar month, same day of month as today)
- Next year
    + `@+1--`

**Comment by johannesjo** [comment]
Thank you very much @vorpalvorpal ! Makes a lot of sense so far. Personally I could live with just the cases mentioned in the original description, and I am for keeping things simple in the first step, but I am not against having the options :)

**Comment by JonathanH-UK** [comment]
@johannesjo please can you reopen this?
I'm still hopeful that you might be able to implement this at some point.

I already sponsor this project but please let me know if there's a way I can help to financially sponsor this specific feature?

Thanks (und mit freundlichen Grüßen)
Jonathan

**Comment by aaylnx** [comment]
I'm just chiming in that this is still an excellent idea. Thanks for all of the great work @johannesjo!

**Comment by johannesjo** [comment]
Sorry! This somehow slipped under my radar. It's partly possible now, but not all ideas described above have been implemented.

**Comment by jcarroll** [comment]
> It's partly possible now, but not all ideas described above have been implemented. 
Sounds like it has been partially implemented.  Where can I please find documentaiton on how to use it? I'm looking for something more concise than this thread. I looked in the [docs folder](https://github.com/johannesjo/super-productivity/tree/master/docs) and [searched the Q&A](https://github.com/johannesjo/super-productivity/discussions/categories/q-a?discussions_q=category%3AQ%26A+time+format) and didn't find anything yet.

**Comment by johannesjo** [comment]
@jcarroll no documentation yet. But help with it would be much appreciated.
