### ISSUE TITLE
"Add time spent for other day" incorrectly uses value from another day

### ISSUE THREAD

**Issue by rbu** [johannesjo/super-productivity#1025]
### Your Environment
* Version used: 6.5.2 AppImage
* Operating System and version: Fedora Linux 33
* Desktop Environment: Gnome

### Expected Behavior
When I click "Add time for another day", enter a date and time, it should save the time as entered.

### Current Behavior
In some cases, the time from another date is being used.

### Steps to Reproduce (for bugs)
1. Create a task with time tracked 2 days ago and today.
2. Realize you forgot to track time on this task yesterday.
3. Click "Time Tracking", then "Add time spent for other day"
4. Enter date and time. Use keyboard to enter the time.
5. Mouse Click Save
6. See the time on that day is incorrect.

Re 3:
![image](https://user-images.githubusercontent.com/65913/114016666-5d597b00-986b-11eb-9bbb-b255258bffb1.png)

Re 4:
![image](https://user-images.githubusercontent.com/65913/114016730-6fd3b480-986b-11eb-8606-6214a8c396ef.png)

Re 5: 
![image](https://user-images.githubusercontent.com/65913/114016773-7b26e000-986b-11eb-8538-76cee4aadbd5.png)

Note the value is 1h 1m.

This is reproducable when I cancel, close Time Tracking and then "Add time..." again. When I simply *repeat* the addition steps without closing the window.

**Comment by johannesjo** [comment]
Thank you very much! I am able to reproduce this. Fortunately the value saved is correct (if you click save and reopen the dialog the correct value is shown). But we should fix this! This might be a good issue to fix by people new to the project. Help would be appreciated!
