### ISSUE TITLE
Make alternative/light systray icon

### ISSUE THREAD

**Issue by sergeevabc** [johannesjo/super-productivity#1027]
![](https://i1.imageban.ru/out/2021/04/10/801db46b6603ae7735dfcf57f515e431.png)

Windows 7, dark-themed taskbar with a few apps minimized to systray, Superproductivity included. I barely see the latter.

**Comment by johannesjo** [comment]
I am not too familiar with the windows 7 task bar to be honest. Do you think that always using the white icon instead fix the issue without creating new problems?

**Comment by JLuisGT** [comment]
Hi! This is also an issue on Linux Mint Cinnamon.
