### ISSUE TITLE
Remember window position

### ISSUE THREAD

**Issue by sergeevabc** [johannesjo/super-productivity#1028]
Window 7. 

Press <kbd>Win+←</kbd> or <kbd>Win+→</kbd> so that Superproductivity window takes up half of the screen.
Now minimize and then restore it, either by clicking tray icon or by pressing <kbd>Ctrl+Shift+X</kbd> (default combo).
Expected: to have window right where it was. Reality: it is somewhere in the center of the screen.

**Comment by johannesjo** [comment]
Hi there! This would be nice to have, even though I wouldn't consider this a bug myself.
