### ISSUE TITLE
[Question] How to run the app on iOS?

### ISSUE THREAD

**Issue by MrRaph** [johannesjo/super-productivity#103]
Hi,

Thanks a lot for this application, it's a big time saver for me !
Do you have any plan to make an iOS version of it ?

Thanks a lot, one more time !

**Comment by johannesjo** [comment]
Hey there. No there are no plans in this direction. Shouldn't be too difficult to make an cordova wrapper, but uploading to the store in addition to the money it costs (100$ per year when I last checked) just don't make it seem worth the effort. The app is open source though. If somebody wants to do it, the can.

Meanwhile you should be able to use almost all features from your mobile device via the  browser version. You might be also to able to install it as a PWA. You might wanna check the "But if there is no App Store, how do you install a PWA?" section on this page: https://medium.com/@firt/progressive-web-apps-on-ios-are-here-d00430dee3a7

If you try the latter, it would be could, if you report back, how it worked out for you.
