### ISSUE TITLE
Selecting multiple tasks

### ISSUE THREAD

**Issue by sergeevabc** [johannesjo/super-productivity#1030]
Err… I added a lot of tasks to Today. Now I want to sort them out to folders/projects.
Doing that one by one is too inconvenient. How do I select multiple tasks to drag further?

_Originally posted by @sergeevabc in https://github.com/johannesjo/super-productivity/discussions/758#discussioncomment-594636_

**Comment by johannesjo** [comment]
Thank you for opening this up! Currently there is no way to do this. #573
