### ISSUE TITLE
Uncaught TypeError: Cannot read property 'remote' of null

### ISSUE THREAD

**Issue by conradob** [johannesjo/super-productivity#1034]
### Your Environment

* Version used: 6.4.0-1
* Operating System and version: Arch Linux 5.11.13-arch1-1
* Desktop Environment: DWM
* Browser Name and version:

### Expected Behavior

The application should load properly

### Current Behavior

Application on infinite loading state

### Steps to Reproduce (for bugs)

1. Just open

### Console Output

```
main.b5dc275434365938ad8f.js:1 Uncaught TypeError: Cannot read property 'remote' of null
    at Module.zUnb (main.b5dc275434365938ad8f.js:1)
    at l (runtime.f8acce36d38b4573bc3e.js:1)
    at Object.0 (main.b5dc275434365938ad8f.js:1)
    at l (runtime.f8acce36d38b4573bc3e.js:1)
    at t (runtime.f8acce36d38b4573bc3e.js:1)
    at Array.r [as push] (runtime.f8acce36d38b4573bc3e.js:1)
    at main.b5dc275434365938ad8f.js:1
```
### Error Log (Desktop only)
The desktop errors are from 2020 and it's not relevant

![image](https://user-images.githubusercontent.com/1469697/114389603-17fbbd00-9b8d-11eb-9451-88c56f821c41.png)

**Comment by johannesjo** [comment]
Thank you very much for reporting. How do you setup electron on your system? Might be that you're using a newer version that doesn't expose the remote module in the same way.

**Comment by conradob** [comment]
Hi @johannesjo, thank you for your quick response. 
I'm installing it directly from the [Arch AUR packages repository ](https://aur.archlinux.org/packages/superproductivity/).

I found a [more up-to-date version](https://aur.archlinux.org/packages/superproductivity-bin/) (6.5.2-1), just installed it and it's working properly.

I believe we can close this issue, again, thanks for all your work.

**Comment by johannesjo** [comment]
Thank you!
