### ISSUE TITLE
[Feature request] Archiving projects

### ISSUE THREAD

**Issue by calvadosxo** [johannesjo/super-productivity#104]
Actually, the only way to manage the projects is to delete them.

It would be neat if we could archive them and fuse them! I have way too much projects that are finished, but I don't want to lose the useful data!

**Comment by johannesjo** [comment]
Hey there! I like the idea, especially the archiving one, as it also would be nice for the performance. Don't know when I will have the time though, as it's not a trivial feature. I'll keep you updated. Meanwhile Pull Requests are very welcome!

**Comment by fla15** [comment]
helpful Feature request.

**Comment by johannesjo** [comment]
So the feature is finally there. It will be available on the edge and candidate channels for the snap package or directly as download from the github page. 

Some beta testing would be highly appreciated!!! Take care to back up your data first, when doing so!

**Comment by johannesjo** [comment]
I'm pleased to announce that it is now also possible to export and import the data of a single project.
