### ISSUE TITLE
[Feature request] Store Attachments

### ISSUE THREAD

**Issue by susnick** [johannesjo/super-productivity#105]
It would be nice to be able to drag a file in to a task item, and it be saved to the Data Directory that Super Productivity uses.  I have found myself deleting files because i dont know what they are. if SP saved them it wouldnt be an issue.  Another Benefit is that I use SP as a portable applicaton. Since there currently is no way to specify a data directory, I use a symlink so I can keep all the data on my thumb drive and take to any computer.

**Comment by johannesjo** [comment]
Hi! Thanks for the suggestion. I agree that this would be a nice feature. Unfortunately I currently don't have the capacity to work on this, as I don't really need it myself and it's quite comlicated to implement, as there are a lot of things to consider. I'm of course open to Pull Requests for that feature :)
