### ISSUE TITLE
[Feature request] Close App setting

### ISSUE THREAD

**Issue by susnick** [johannesjo/super-productivity#106]
SP keeps running in the task bar after I close it. A default enabled setting would be preferred, so those who do not wish it to keep running could choose that option. And those who come to expect it are not left hanging.

**Comment by johannesjo** [comment]
Thanks for the suggestion. I look into it.

**Comment by johannesjo** [comment]
Should be available with the next update. Let me know if it works out for you.

**Comment by susnick** [comment]
This is working thanks.
