### ISSUE TITLE
Pomodoro timer lag

### ISSUE THREAD

**Issue by Acsigen** [johannesjo/super-productivity#107]
## Your Environment

* Version used: 1.10.52
* Operating System and version: Windows7 x64 also affects Ubuntu 18.04 x64
* Desktop Environment: Gnome
* Browser Name and version: Web version not affected

## Expected Behavior
- Set the pomodoro timer to 20m;
- The time spent on task should be 20m minus the time remained on pomodoro timer (for new tasks that I haven't worked on before);
- The pomodoro should actually count down 20m;

## Current Behavior
- Set the pomodoro timer to 20m;
- The time spent on task is not 20m minus the time remained on pomodoro timer (for new tasks that I haven't worked on before);
- The pomodoro actually counts slower than it should be, those 20m are longer;
- This happends only when the app is minimised or closed to tray.

## Steps to Reproduce (for bugs)
1. Set the pomodoro timer to 20m;
2. Start task;
3. Minimise or exit the app to tray;
4. Work on task;
5. The remained time (in the case of the screenshot attached) should be almost 5m not 13m;
![pomodoro issue](https://user-images.githubusercontent.com/13287878/44326051-27b9b680-a463-11e8-9baf-5510313f7f8d.png)

Update: I used my phone to find the lag of the pomodoro timer, when the phone reached the 13m10s the pomodoro timer was at 7m54s remained.

**Comment by johannesjo** [comment]
Thanks for reporting. I will investigate this, as soon as I have time.

**Comment by johannesjo** [comment]
Thanks for investigating so thoroughly. Hopefully this works now as intended with the next release.
