### ISSUE TITLE
Remove trailing slash from JIRA URL if found

### ISSUE THREAD

**Issue by msbentley** [johannesjo/super-productivity#108]
I've just started to use SP and so far it looks great! However, I did scratch my head for 20 minutes this morning when I tried to set up JIRA integration. I copied and pasted the base URL into SP, which included a trailing slash. This then messed up the integrated - eventually I looked in the console and saw that there was a double slash (//) in the API call which was messing things up. To avoid this in the future, it may be best to simply remove any trailing slashes? Thanks!

**Comment by johannesjo** [comment]
Good suggestion. Thanks. Will work on this as soon as I can.

**Comment by johannesjo** [comment]
Should be fixed now. Thanks for reporting again.
