### ISSUE TITLE
[Feature request] Reusing Tasks or sub-tasks

### ISSUE THREAD

**Issue by ErnestUTN** [johannesjo/super-productivity#109]
During the task creation, I would like the idea of being able to quickly reuse a task with its Estimated duration when I know I will be using it several times. I find myself retyping the same name over and over again. Multiple tasks would be great too.

Example: I should study 2 hs of Java and 1 hour of CSS every day for this entire month.

The feature should allow me to "design" a template or blueprint called Java of Estimated Duration of 2 h and another CSS of 1 h.
It could be some sort of drag and drop so that I quickly copy and paste (clone) the tasks from the template window into the Tasks for Today ( or tasks backlog).

Regards

PD: Your app is awesome!

**Comment by johannesjo** [comment]
Thanks for reporting. Did you know the short syntax? You can type `Java t2h` and it will create a task . For me personally that's much quicker done than clicking through some sort of interface. Maybe its possible to supply some sort of custom auto complete, where you can add your own strings. Not sure. What do you think?

**Comment by ErnestUTN** [comment]
Ah, I didn't know that short syntax.
Yes, if the class allows that (I guess it does) you could do that instead. mm let see.

You could implement the autocomplete feature maybe?
https://material.angularjs.org/latest/demo/autocomplete

**Comment by susnick** [comment]
Kind of related to this. How about reoccurring/scheduled tasks? Like every Monday add a certain task.

**Comment by johannesjo** [comment]
@susnick: There had been plans to implement such a feature (#48). Hard to get it right though. Personally I manage my scheduled stuff with a calendar and all the rest via super productivity. Would be interesting to hear your thoughts about it!
