### ISSUE TITLE
Done-backlog not saved

### ISSUE THREAD

**Issue by johnhorsema** [johannesjo/super-productivity#11]
Was using the [web version](http://super-productivity.com/app/#!/), but when I press 'Finish Your Workday', completed tasks disappear. They are not saved and I cannot view them at [Done Tasks Backlog](http://super-productivity.com/app/#!/done-tasks-backlog)

**Comment by johannesjo** [comment]
Thanks for reporting! Had a similar issue with a newly created project. Will try to look into it tomorrow!

**Comment by johannesjo** [comment]
I think it should work now. Thanks again for reporting! Lead me in the right direction!
