### ISSUE TITLE
[Feature request] WebDav sync or choose local folder storage

### ISSUE THREAD

**Issue by TobiasDev** [johannesjo/super-productivity#110]
I'd love if it would be possible to add a WebDav sync feature. I'm not using Google Drive, but have my own NextCloud instance that I can sync to that with WebDav, so if possible I would love this feature added.

If WebDav seems unnecessary difficult, just being able to decide the storage space for the project would be enough. That way I could choose where to store all data. Eg. put it in my NextCloud folder, Dropbox folder or wherever I want and just change the location to that depending on the computer I use. + I would be in control where all attachments are store. :) 

Another plus would be a ZenKit intigration, but not sure that is possible or not.

Thanks!

**Comment by johannesjo** [comment]
Hey there. Thanks for opening up this issue.While there currently it should be possible to set up syncing via the automatic sync feature (can be found in the settings). There you can specifiy a file which to sync your data to and then you can set up syncing via web dav for that file.

Let me know if that works out for you!

**Comment by TobiasDev** [comment]
Okay! I tried looking more into this, looks like I can't use syncing unless I somehow add an account to it. I tried making a shareable, editable file and added the link, but still didn't work with syncing.

**Comment by johannesjo** [comment]
To be honest, I think I only used Webdav, but I thought that something Dropbox-like should be possible (e.g.: https://apple.stackexchange.com/questions/49628/dropbox-like-client-for-macs-to-access-existing-ftp-webdav-cmis-storage). Direct integration would be nicer of course, but I don't know if it is possible to make a generic Integration, as the providers seem to have their own api specifications, and while I'm open for pull requests I have to say that I probably won't go through the hassle of providing an interface for every provider just by myself :)

**Comment by johannesjo** [comment]
@TobiasDev were you able to make it work for you?
