### ISSUE TITLE
customer management for projects

### ISSUE THREAD

**Issue by JanBoehme** [johannesjo/super-productivity#1110]
Hi,

I was thinking about how to track tasks/time spent working for different clients across projects. I'd like to be able to compile timesheets with billable hours for a client without having to go through all projects and sum everything up.

A solution would be to have a client/customer management feature and the possibility to assign projects (and maybe also standalone tasks) to a client/customer. 

On a task level I could do this via tags but having to add the tag to every single task is error prone as well as a little tedious.

Is something like this on the list or is it maybe missing for a reason?

thanks: jan.

**Comment by johannesjo** [comment]
Hi there! Thank you very much for the suggestion. It's a nice idea. As I am pretty busy with lots of other tasks and I currently don't need this myself, I probably won't work on this myself in the near future. But I am open for a discussion and would support anyone who wants to tackle the problem.
