### ISSUE TITLE
Error keeps popping up idb database connection is closed. and a popup with below error pops.

### ISSUE THREAD

**Issue by Labohkip81** [johannesjo/super-productivity#1116]
![Screenshot from 2021-04-26 08-31-20](https://user-images.githubusercontent.com/36964869/116033579-5ce22200-a66a-11eb-9aaf-7d0dbfdecb78.png)

### Your Environment

* Version used:6.5.2->
* Operating System and version: ubuntu 20.04
* Desktop Environment: 

### Current Behavior
Attached screenshot explains better

### Steps to Reproduce (for bugs)
- Project just freezes and shows error.

### Error Log (Desktop only)
! Please copy & report !

Error: Uncaught (in promise): Error: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing. Error: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing. at t. (file:///snap/superproductivity/1124/resources/app.asar/dist/main.bd2f00c6dd24cafa9ec8.js:1:2307582) at Generator.throw () at a (file:///snap/superproductivity/1124/resources/app.asar/dist/main.bd2f00c6dd24cafa9ec8.js:1:2306794) at l.invoke (file:///snap/superproductivity/1124/resources/app.asar/dist/polyfills.de25402c72ff0ad0d8f0.js:1:6594) at Object.onInvoke (file:///snap/superproductivity/1124/resources/app.asar/dist/main.bd2f00c6dd24cafa9ec8.js:1:1612571) at l.invoke (file:///snap/superproductivity/1124/resources/app.asar/dist/polyfills.de25402c72ff0ad0d8f0.js:1:6534) at i.run (file:///snap/superproductivity/1124/resources/app.asar/dist/polyfills.de25402c72ff0ad0d8f0.js:1:2006) at file:///snap/superproductivity/1124/resources/app.asar/dist/polyfills.de25402c72ff0ad0d8f0.js:1:16792 at l.invokeTask (file:///snap/superproductivity/1124/resources/app.asar/dist/polyfills.de25402c72ff0ad0d8f0.js:1:7212) at Object.onInvokeTask (file:///snap/superproductivity/1124/resources/app.asar/dist/main.bd2f00c6dd24cafa9ec8.js:1:1612387)
await (webpack:///src/app/core/persistence/database.service.ts:58:12)
Ur (file:///snap/superproductivity/1124/resources/app.asar/dist/main.bd2f00c6dd24cafa9ec8.js:1:2306794)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28553:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:371:51)
run (webpack:///node_modules/zone.js/dist/zone-evergreen.js:134:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1276:35)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:406:30)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28540:32)
META: SP6.5.2 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.5.2 Chrome/89.0.4389.128 Electron/12.0.5 Safari/537.36

**Comment by johannesjo** [comment]
Thank you very much for reporting this. Looks like a duplicate to #840 to me.

**Comment by Labohkip81** [comment]
Thanks much.
