### ISSUE TITLE
[Feature Request] pomodoro ticking sound

### ISSUE THREAD

**Issue by stuartro** [johannesjo/super-productivity#112]
Really beautiful app! Love the integration between Pomodoro and Jira!!! 

One (hopefully small) request: Any chance a ticking sound can be added?

**Comment by johannesjo** [comment]
Hello! Thanks for your feedback. Glad that you like the app! Adding a ticking sound should be no problem, I think. If I find some time, I might implement it during the weekend.

**Comment by johannesjo** [comment]
Hey there! I added the feature. It's not perfect due to how JavaScript intervals work, but it should do the job.

**Comment by stuartro** [comment]
Working great. Thank you
