### ISSUE TITLE
searching worklog tasks

### ISSUE THREAD

**Issue by realmrealm** [johannesjo/super-productivity#1125]
I found that old tasks are in the "Worklog" but is there any way to search them? It's not that important, but I sometimes have a need to look for a task that I did based on a keyword. 

examples: 
- "what was that thing we did for abcclient with email?"
- "when did we complete that task, was it in february or march?"

**Comment by johannesjo** [comment]
Hi there! Thanks for opening this. No there currently is not. #1032 #547
