### ISSUE TITLE
[Feature Request] Show Jira epic-name in task

### ISSUE THREAD

**Issue by stuartro** [johannesjo/super-productivity#113]
When adding tasks from Jira into (SP's) backlog it is difficult to know which Epic (in Jira) the issue is related to. I've taken to adding the epic name in each story's name (e.g. "some story name (EpicName)") just so that I can see/filter by epic within SP. Would be great if SP could show (perhaps an optional setting) Epic name (or Epic Link name) in tasks.

**Comment by johannesjo** [comment]
Thanks for the suggestion. I agree that this would be useful.

**Comment by johannesjo** [comment]
I digged a little into the subject. Seems like epics are saved as a custom field (https://stackoverflow.com/questions/24385644/jira-api-get-epic-for-issue). Which one is custom and, to complicate things further, might be subject to changes, so an implementation is not trivial and involves a lot of additional requests to the API. If there is a huge demand for this feature I'll probably implement it myself, but until then I put this on hold. 

I'm open for Pull Requests of course.

**Comment by johannesjo** [comment]
Btw.: What seems easier to implement are Components. Those have a fixed property on every issue.
