### ISSUE TITLE
"Working today" not reset after "Finish Day"

### ISSUE THREAD

**Issue by matbok** [johannesjo/super-productivity#1132]
### Environment
* Version used: 6.5.2
* Operating System and version: Windows 10

### Expected Behavior
When I click on "Finish Day", in order to start a new day (even if I forgo to do it at the end of the previous day, and I do it in the following morning, before starting a new job day) I'd expect the "Working today" counter to reset.

### Current Behavior
It does not reset, even if I finish the day, close the app and reopen it

### Steps to Reproduce (for bugs)
1. work for a day, and finish the day (without shutting down the app, bu just "resetting counters")
2. the next morning observe the counter is still the same as the day before
3. finish again the day, then shutting down the app, and reopen it
4. observe the counter is still the same as the day before

### Error Log (Desktop only)
no logs files found

**Comment by johannesjo** [comment]
Thanks for opening this up! Although this might be a bit confusing this is the correct behavior as working today takes the value from all tasks active in the list.

**Comment by matbok** [comment]
Ok, got it.
But, anyway, in the same condition of tasks, yesterday afternoon I closed the application, this morning I reopened it, and the working today counter was reset to 0 (I think this is a more correct behavior).
