### ISSUE TITLE
[Question] Where do distractions (entered in the Distraction popup) go to?

### ISSUE THREAD

**Issue by stuartro** [johannesjo/super-productivity#115]
Is there a way to see the distraction log after a pomodoro is completed? I'm guessing there probably is, but have been unable to find it so far. Apologies if this is a dumb / obvious question.

**Comment by stuartro** [comment]
Never mind - just found them (after closing work for the day)

**Comment by johannesjo** [comment]
There is. They are shown at the end of the day, when click "Finish Working" in the work view panel.
