### ISSUE TITLE
DAV sync error: TypeError: i.headers is undefined

### ISSUE THREAD

**Issue by nathan-sain** [johannesjo/super-productivity#1150]
### Your Environment

* Version used: Self hosted, Docker Container, 6.5.2
* Operating System and version: Ubuntu 18.04
* Desktop Environment: Ubuntu Gnome
* Browser Name and version: Firefox 88.0 64-bit

### Expected Behavior

Sync should happen without reporting error

### Current Behavior

An error is displayed, but the sync occurs. Sometimes sync is not logged as successful and a modal prompt to select data source is displayed on next sync.
The error displayed is "Unknown Upload Error (Settings Correct?). TypeError: i.headers is undefined"

### Steps to Reproduce (for bugs)
1. Setup WebDav Sync
2. See if error occurs

### Console Output
WebDAV ↑ Update Remote sync-provider.service.ts:366:19

true web-dav-api.service.ts:47:12

true web-dav-sync.service.ts:89:14

TypeError: i.headers is undefined
    uploadAppData web-dav-sync.service.ts:91
    a main.cc529609e1915c525b4d.js:1
    Angular 13
        invoke
        onInvoke
        invoke
        run
        P
        invokeTask
        onInvokeTask
        invokeTask
        runTask
        m
        invokeTask
        _
        k
web-dav-sync.service.ts:93:14
    uploadAppData web-dav-sync.service.ts:93
    a main.cc529609e1915c525b4d.js:1
    Angular 13
        invoke
        onInvoke
        invoke
        run
        P
        invokeTask
        onInvokeTask
        invokeTask
        runTask
        m
        invokeTask
        _
        k

WebDAV X Upload Request Error sync-provider.service.ts:366:19

sync(effect)..... I_FOCUS_THROTTLED sync.effects.ts:109:23

Object { filename: "/home-super.json", basename: "home-super.json", lastmod: "Fri, 30 Apr 2021 06:32:33 GMT", size: 12463, type: "file", etag: "&quot;ee834b31f78208c9610e71fefc35311e&quot;", mime: "application/json" }
​basename: "home-super.json"
​etag: "&quot;ee834b31f78208c9610e71fefc35311e&quot;"
​filename: "/home-super.json"
​lastmod: "Fri, 30 Apr 2021 06:32:33 GMT"
​mime: "application/json"
​size: 12463
​type: "file"
​<prototype>: Object { … }
web-dav-api.service.ts:67:12

Object { bookmark: {…}, note: {}, globalConfig: {…}, reminders: [], project: {…}, tag: {…}, simpleCounter: {…}, metric: {…}, improvement: {…}, obstruction: {…}, … }
web-dav-api.service.ts:79:12

Object { filename: "/home-super.json", basename: "home-super.json", lastmod: "Fri, 30 Apr 2021 06:32:33 GMT", size: 12463, type: "file", etag: "&quot;ee834b31f78208c9610e71fefc35311e&quot;", mime: "application/json" }
web-dav-api.service.ts:67:12

Object { local: 1619764322184, lastSync: 1619763750724, remote: 1619764322184 }
check-for-update.util.ts:57:10

Object { lastSync: 0, local: 571.46, remote: 571.46 }
 605.104 check-for-update.util.ts:66:10

WebDAV X Last Sync not up to date sync-provider.service.ts:366:19

### Error Log (Desktop only)
N/A I'm using web edition
. -->

**Comment by johannesjo** [comment]
Thank you very much for reporting this. Does this happen just once or is it reproduceable reliably?

**Comment by nathan-sain** [comment]
The "i.headers is undefined" error is triggered on each sync.

**Comment by elXames** [comment]
CH zu gu

**Comment by johannesjo** [comment]
I suppose this is fixed now. Please let me know if it isn't.
