### ISSUE TITLE
How do I download this software on Linux?

### ISSUE THREAD

**Issue by GitHubWhatsup** [johannesjo/super-productivity#1156]
I don't want to download it from Snap.
Which file should I download on GitHub if I am using Linux (Fedora)?
Do I need to enter any command after downloading the file?
Thanks.

**Comment by johannesjo** [comment]
Hey there! You should be able to use the appImage. If you not you can also convert the deb to a rpm file:
https://www.systutorials.com/how-to-install-deb-packages-on-fedora/

**Comment by johannesjo** [comment]
Also: For questions, please use the discussions page instead:
https://github.com/johannesjo/super-productivity/discussions

Issues are ment for feature requests and bug reports :)
