### ISSUE TITLE
Your data seems to be damaged ...

### ISSUE THREAD

**Issue by raot** [johannesjo/super-productivity#1160]
### Your Environment
Windows 10 Pro 20H2 19042.928
Super Productivity 6.5.2
Chrome Version 90.0.4430.93 (Offizieller Build) (64-Bit)

### Expected Behavior
A couple of times (10 times within the last 30 days), an error was reported upon startup (see screen shot below). In the beginning, I thought that I didn't close super-productivity properly the last evening. But now I started to make sure to shutdown properly, and the message keeps coming back. I did not find any data losses after startup, but still, it makes me feel insecure.

### Steps to Reproduce (for bugs)
So far, I didn't find the steps to reliably reproduce this bug.

### Error Log (Desktop only)
see attachment

![image](https://user-images.githubusercontent.com/5304545/116971203-824ddc00-acb9-11eb-974f-bf203e1f2e5e.png)
[main.log](https://github.com/johannesjo/super-productivity/files/6419519/main.log)

**Comment by johannesjo** [comment]
Thank you very much for reporting this. I try to have a look soon.

**Comment by johannesjo** [comment]
It would be super helpful if you could share a copy of your data to contact@super-productivity.com, so I can reproduce and debug this on my computer. You can create an export by navigating to "Settings" and then to "Import/Export".

**Comment by raot** [comment]
Unfortunately, or, luckily, it did not happen again so far, which is why I could not collect the data. I do so the next time it happens and let you know. Thank you for looking into my report.

**Comment by raot** [comment]
seems not to occur anymore

**Comment by raot** [comment]
I have submitted the details according to your instructions.

**Comment by johannesjo** [comment]
Sorry for the late reply, but somehow I was unable to find your data in my emails. It's possible that I might have deleted it from my spam folder. Could you maybe send it to me again?
