### ISSUE TITLE
Checklist for tasks

### ISSUE THREAD

**Issue by Rapha149** [johannesjo/super-productivity#1162]
## Problem Statement
I have a task with multiple sub tasks, but I want to do the sub tasks at the same time. So I can't use the sub tasks. In the description you can make a list but I can't check them. Additionally I don't like to have the description window open all the time.

## :grey_question: Possible Solution
Add a checklist option for tasks so you can tick a sub task when it's done but still have the timer for the whole task.

## :arrow_heading_up: Describe alternatives you've considered
You could use sub tasks but you can't use a timer for the parent task, then.

## :heavy_plus_sign: Additional context
Didn't found any, I'm sorry if I overlooked something.

**Comment by johannesjo** [comment]
Hi there! This is a very nice suggestion! I like it! This could solve #643 without all the complications. Thank you!

**Comment by Rapha149** [comment]
Nice to hear!

**Comment by Rapha149** [comment]
Yes, I would think that it's still relevant.

**Comment by Rapha149** [comment]
Still relevant ┬─┬ ノ( ゜-゜ノ)
