### ISSUE TITLE
I couldn't create shortcut for AppImage.

### ISSUE THREAD

**Issue by GitHubWhatsup** [johannesjo/super-productivity#1169]
OS: Fedora
I downloaded the AppImage.
I want to make it like a desktop app.
When I run the AppImage for the first time, your software doesn't prompt me to ‘install a desktop file’.
I follow [this guide](https://www.enovision.net/how-create-appimage-entries-menu-ubuntu), but it doesn't work. I couldn't search for the software like an app.
I saved the AppImage in /home/user/superProductivity-6.5.2.AppImage/

I created a .desktop in ~/.local/share/applications.

[Desktop Entry]
Name=Super-Productivity
Comment=A timer tracker
Exec=/home/user/superProductivity-6.5.2.AppImage/
Icon=/home/user/Super-Productivity.png/
Categories=Utility
Terminal=false
Type=Application

Thanks.

**Comment by johannesjo** [comment]
Please use the discussions tab for usage questions:
https://github.com/johannesjo/super-productivity/discussions
