### ISSUE TITLE
Idle time gets reseted right before submitting it 

### ISSUE THREAD

**Issue by debone** [johannesjo/super-productivity#118]
If you enter a break and get idle, when you will return, the click on the pop-up to "Go back to work" will reset the idle time and you end-up with the minimum time configured for getting idle (as it is added to the time idle)

![image](https://user-images.githubusercontent.com/763457/45269409-268e0f00-b48e-11e8-8126-7b3a0b11d445.png)

**Comment by johannesjo** [comment]
Just to be sure to get it right. What's the order of Dialogs? You first get the Pomodoro Break Dialog and afterwards the idle time Dialog appears or the other way round?

**Comment by debone** [comment]
First the Break Dialog and then the idle time. Yes, it's tricky. I researched a bit how to fix this issue myself and it was no obvious answer

**Comment by debone** [comment]
I tested it and it seems to work like a charm.

**Comment by johannesjo** [comment]
Glad to hear it. Thank you very much for verifying! I broke something else though. After I fix this I'll release a new version.
