### ISSUE TITLE
Backlog drag and drop is flaky when "Search backlog" has a query

### ISSUE THREAD

**Issue by debone** [johannesjo/super-productivity#119]
## Your Environment
* Version used: 1.10.56

## Expected Behavior
After searching my backlog, I want to drag a given issue to the "Tasks for Today"

## Current Behavior
The drag and drop behaviour is undetermined if there is a query on the search :(
I so far managed to: copy a task, to not be able to drag some, and even drag a task that was not in the list (filtered out). When trying to reproduce in a empty project I discovered that if you drag all the searched issues, the backlog actually is hidden and you can only get it back if you add a task back to it that matches the search, otherwise, no matter what you do, it will stay hidden.

## Steps to Reproduce (for bugs)
1. Create some tasks with similar names and other with totally different
2. Drag them to the backlog
3. Type a query that matches only some of them
4. Start dragging to the "Today tasks" and back
5. Eventually they break. I could not reproduce exactly the moment, and it's not about timing issues of dragging

## Console Output
After moving around some, it sometimes show the following error

```
TypeError: Cannot read property 'parentId' of undefined
    at Object.itemMoved (task-list-d.js:99)
    at ng-sortable.js:1048
    at Scope.$eval (angular.js:18838)
    at Scope.$apply (angular.js:18937)
    at HTMLDocument.dragEnd (ng-sortable.js:1042)
    at defaultHandlerWrapper (angular.js:3795)
    at HTMLDocument.eventHandler (angular.js:3783) undefined
(anonymous) @ angular.js:15018
```

**Comment by johannesjo** [comment]
My solution for now, is just to disable dropping while the search is active. I might rework the whole drag and drop system, hopefully there will be a better solution available then.
