### ISSUE TITLE
WebDAV service expects putFileContents to return AxiosReponse, but it returns Boolean

### ISSUE THREAD

**Issue by wilbowma** [johannesjo/super-productivity#1197]
There's a type error in this code. (Not sure why Type Script can't catch it :P).

In short, this line:

https://github.com/johannesjo/super-productivity/blob/3f321c18fcbc16267bbc23c3b7dcdee37daa2952/src/app/imex/sync/web-dav/web-dav-api.service.ts#L43

Claims to be returning an AxiosResponse, but its return value comes from putFileContents in the webdav library

https://github.com/johannesjo/super-productivity/blob/3f321c18fcbc16267bbc23c3b7dcdee37daa2952/src/app/imex/sync/web-dav/web-dav-api.service.ts#L51
https://github.com/johannesjo/super-productivity/blob/3f321c18fcbc16267bbc23c3b7dcdee37daa2952/src/app/imex/sync/web-dav/web-dav-api.service.ts#L53

which returns a Boolean:

https://github.com/perry-mitchell/webdav-client/blob/4248cd6c0c797dce4d95295f2bdc2380c289dcb4/source/operations/putFileContents.ts#L18

This causes some issues here, when the boolean is used as a response:
https://github.com/johannesjo/super-productivity/blob/3f321c18fcbc16267bbc23c3b7dcdee37daa2952/src/app/imex/sync/web-dav/web-dav-sync.service.ts#L98

**Comment by wilbowma** [comment]
Even if the response was returned, the header from the put cannot be expected to contain an etag:
http://www.webdav.org/specs/rfc4918.html#etag

Instead, after the put request, the sync service should probably follow up with a HEAD request to get the new etag if the put succeeded.

**Comment by johannesjo** [comment]
I think this is fixed now.
