### ISSUE TITLE
WebDAV sync always claims a remote conflict with some WebDAV servers (nginx)

### ISSUE THREAD

**Issue by wilbowma** [johannesjo/super-productivity#1199]
### Your Environment

* Version used: 3f321c18fcbc16267bbc23c3b7dcdee37daa2952
* Operating System and version: Linux 5.11.16-2-MANJARO #1 SMP PREEMPT Thu Apr 22 09:53:11 UTC 2021 x86_64 GNU/Linux

* Desktop Environment:  KDE

### Expected Behavior
WebDAV sync should work with WebDAV-compliant servers.

### Current Behavior
WebDAV sync fails with nginx, as the conflict resolution relies on the `etag` header being returned from `PROPFIND` (through getStat in the webdav client), but this header is not returned from `PROPFIND` at least on nginx. (This seems to be consistent with the WebDAV spec http://www.webdav.org/specs/rfc4918.html#rfc.section.9.1.3)

### Steps to Reproduce (for bugs)

1. Setup sync with a nginx webdav server
2. Wait
3. On any upload after an initial upload, the user is warned that the remote has been modified, although it hasn't been, and asked to resolve the conflict. The last sync date will by the 0 unix timestamp.

### Possible fix
I think one fix is to issue a `HEAD` request instead, which is both faster and should return a header with `etag`. I'll try to add this support to the webdav-client and test a fix.

**Comment by johannesjo** [comment]
Thanks again! I am closing this.
