### ISSUE TITLE
Urls to Jira Issues contain extra protocol entry

### ISSUE THREAD

**Issue by flyinbutrs** [johannesjo/super-productivity#12]
Clicking on this link:
![image](https://user-images.githubusercontent.com/1248221/31780176-f606c60e-b4c2-11e7-8b5a-37865100fe8b.png)

Takes me to this url:

```
https://https//project.example.com/browse/PL-379
```

**Comment by johannesjo** [comment]
Thank you very mich for reporting! I'll look into it tomorrow!

**Comment by johannesjo** [comment]
I looked into the code. There is not really a reason there why a second https would be added. Is the second https maybe already present in the data you get from jira? Also which OS and browser are you using?

I'll added a cleanup anyway and am publishing a new version at the moment. Could you check if it works for you?

**Comment by flyinbutrs** [comment]
OSX. Fix worked like charm! How does it pull that information from Jira? I wonder if our Jira instance is misconfigured.

**Comment by johannesjo** [comment]
It does so via it's own fork of jira-client. You can see what response you get, when you add a console.log here: https://github.com/johannesjo/super-productivity/blob/1fbcf30dc4652677b91a7c28b4d7882a5d13399f/electron/jira.js#L43
