### ISSUE TITLE
Pomodoro doesn't update it's time

### ISSUE THREAD

**Issue by RIGHTROAD** [johannesjo/super-productivity#120]
## Your Environment
* Version used: snap
* Operating System and version:Ubuntu 18.04 LTS
* Desktop Environment: GNOME

## Expected Behavior
The timer on the main window should be updated right away when changing the value of the work session duration in settings menu.

## Current Behavior
when changing the work session duration of the pomodoro timer, the main timer on the top right corner isn't updated until clicking on "Stop" button

**Comment by johannesjo** [comment]
Hey there! Thanks for reporting. I agree. Currently I'm working on a complete rewrite of the application, which also will probably change the pomodoro behavior.

**Comment by RIGHTROAD** [comment]
Happy to help, good luck with coding!

**Comment by johannesjo** [comment]
Should be fixed now. Thanks again!
