### ISSUE TITLE
First Day of Week is not honored in Worklog

### ISSUE THREAD

**Issue by askpatrickw** [johannesjo/super-productivity#1201]
### Your Environment
* MacOs Desktop Version

### Expected Behavior
In Settings, you can specify the first day of the week.
When you set this, the week should be from that day of the week to the preceding day.
If a week starts on Saturday, then a week is Saturday - Friday.

### Current Behavior
Project Worklog displays weeks starting on Monday (might be Sunday) despite that I have my First Day of Week set to Saturday.

**Comment by johannesjo** [comment]
Hi there! Thank you very much for opening this up! Currently The weekday setting has only a very limited effect. I personally don't need need it, but I gladly accept any PR dealing with this.

**Comment by askpatrickw** [comment]
If I knew javascript, I'd totally help with a PR. How about setting the help wanted tag?

**Comment by askpatrickw** [comment]
I quit using this... so I'll close.
