### ISSUE TITLE
High CPU usage even after closing the program

### ISSUE THREAD

**Issue by rchamorro** [johannesjo/super-productivity#1202]
### Your Environment
* Version used: 6.5.2, installed from Microsoft Store
* Operating System and version: Windows 10

### Expected Behavior
It does not use a lot of CPU and when I close the program the process closes and stops using CPU.

### Current Behavior
Super Productivity has a constant high CPU usage and even after closing the program it gets consuming CPU until I will the process.

This screenshot was made 15 minutes after closing super productivity.

![image](https://user-images.githubusercontent.com/86739/117707547-fb27c900-b1ce-11eb-820b-feaa3fb9e7d7.png)

### Steps to Reproduce (for bugs)
 It happens lots of times but not always. I don't know how to repeat it.

### Error Log (Desktop only)
on Windows: There was no directory for logs at %USERPROFILE%\AppData\Roaming\superProductivity
. -->

**Comment by johannesjo** [comment]
Thank you very much for reporting this! Could you maybe try the non-store standalone version? I'm really curious if the same happens there.

**Comment by rchamorro** [comment]
Ok! I will try with the non-store version.

**Comment by i-give-up** [comment]
Reproducible with the standalone version. Might have happened before but I only noticed this issue today. Issue seems to go away after I kill the high CPU-usage superProductivity process then launch the app again.

I will report back if I learn anything new about this issue.

App version: 6.5.2
OS: Windows 10 Version 2004

I can't find the log file mentioned in the bug report template: %USERPROFILE%\AppData\Roaming\superProductivity\log.log

**Comment by rchamorro** [comment]
Using the standalone version I has not happened to me in the last two days.

**Comment by s-maltsev** [comment]
The issue is observed on 7.13.2.
