### ISSUE TITLE
roboto-fontface package replaced by fontsource

### ISSUE THREAD

**Issue by wilbowma** [johannesjo/super-productivity#1205]
The roboto-fontface package has been deprecated:
https://github.com/choffmeister/roboto-fontface-bower
and replaced by:
https://github.com/fontsource/fontsource/tree/main/packages/roboto

**Comment by johannesjo** [comment]
Thanks for the info! I'll try to switch them out this Friday.

**Comment by johannesjo** [comment]
Should be resolved by 29a59207cb1f010627fb3ee7bfdc49c65c4de439

Thanks again!
