### ISSUE TITLE
Snap issue trying to install in openSuse Tumblweed

### ISSUE THREAD

**Issue by NumDeP** [johannesjo/super-productivity#1208]
### Your Environment
Operating System: openSUSE Tumbleweed 20210510
KDE Plasma Version: 5.21.5
KDE Frameworks Version: 5.82.0
Qt Version: 5.15.2
Kernel Version: 5.12.0-2-default
OS Type: 64-bit 

### Current Behavior & Console Output
So I followed the instruction as presented on the Snap store to download SP and all is okay up until I reach the following point and this it what it presents:

```
[sudo] password for root:
Failed to enable unit: Unit file snapd.apparmor.service does not exist.

@localhost:~> sudo systemctl start snapd
Job for snapd.service failed because the control process exited with error code.
See "systemctl status snapd.service" and "journalctl -xe" for details.

@localhost:~> sudo snap install superproductivity
error: cannot communicate with server: Post http://localhost/v2/snaps/superproductivity: dial unix /run/snapd.socket: connect: connection refused
```

### Expected Behavior
I think it's obvious :) I've used SP on openSuse Tumbleweed before 

### Steps to Reproduce (for bugs)
Does the error happen once or are you able to reproduce it reliably? Yes.  
1. Follow instruction to download for openSuse here - https://snapcraft.io/install/superproductivity/opensuse
  
## Miscellaneous Information:
- Just out of curiosity did you contemplate ever pushing SP on Flathub/Flatpak?
- Thank you for this application, I've only started using it a few weeks ago though I downloaded a while back and I like using it so thank you.
- Verify yourself for [Brave Rewards](https://creators.brave.com) so I can leave a Tip:)

**Comment by johannesjo** [comment]
Hey there! Thank you very much for reporting this. I fear that I won't be of much use in helping you with this issue, as it looks like it is something snap related and I don't know much about its inner workings :( But maybe somebody else can help?

There is an issue about flatpak: #25 Hopefully sometime in the feature this will be easy to implement.
