### ISSUE TITLE
Ubuntu / Debian Installation Warning

### ISSUE THREAD

**Issue by felixlberg** [johannesjo/super-productivity#121]
when i try to add super-productivity as to my /etc/apt/sources.list i get the following errors when use 
sudo apt update.

```
W: Skipping acquire of configured file 'super-productivity/i18n/Translation-en_US' as repository 'https://dl.bintray.com/johannesjo/super-productivity stable InRelease' doesn't have the component 'super-productivity' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'super-productivity/i18n/Translation-en' as repository 'https://dl.bintray.com/johannesjo/super-productivity stable InRelease' doesn't have the component 'super-productivity' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'super-productivity/dep11/Components-amd64.yml' as repository 'https://dl.bintray.com/johannesjo/super-productivity stable InRelease' doesn't have the component 'super-productivity' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'super-productivity/dep11/icons-48x48.tar' as repository 'https://dl.bintray.com/johannesjo/super-productivity stable InRelease' doesn't have the component 'super-productivity' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'super-productivity/dep11/icons-64x64.tar' as repository 'https://dl.bintray.com/johannesjo/super-productivity stable InRelease' doesn't have the component 'super-productivity' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'super-productivity/cnf/Commands-amd64' as repository 'https://dl.bintray.com/johannesjo/super-productivity stable InRelease' doesn't have the component 'super-productivity' (component misspelt in sources.list?)
```

This happens on several devices and i tested it with different versions of Ubuntu and its a little bit annoying in the update process. 

I've tried as well to create own sources.list file as `/etc/apt/sources.list.d/super-productivity.list` which i would recommend anyway because /etc/apt/sources.list should just carry vendor sources. But i get still these skipping warnings.

Is there any way to us your dep source without getting these warnings on Ubuntu. I've searched these issues but didn't found someone reports these problem already.... but anyway thx for this software its awesome

----
Best regards
Felix

**Comment by johannesjo** [comment]
Hey there! Thanks for reporting. I remember trying to fix this before, but delaying it, as it didn't seem that important and this side of things being always a real pain to figure out due to the long process required to test ;)

Currently I am working on a complete rewrite of the app. Once I am done there, I'll try to tackle this issue.

**Comment by felixlberg** [comment]
Hey thx for the reply... I just wanted to mention this, because i am heavily using custom themes on gnome and before the bug with passing the the user theme to an snap application isnt't fixed snap apps looking really ugly for me. So I always trying to use non snap version. 
If you need any help just tell me, I like this app really use it now since one year or something.

**Comment by johannesjo** [comment]
I'm always glad for help! Thank you! If you would knew how to adjust the electron o properly address this issue, this would be great! Apart from that I am spending a lot of time on the rewrite (https://github.com/johannesjo/sp2). If you're interested in working on that with me, a good first step would be just to check out the project and familiarize yourself with it. If you're not running away screaming we can talk and figure something out after that ;)

**Comment by felixlberg** [comment]
Yeah this looks nice!
Im worken currently as well on some nativescript+angular app (https://github.com/felixlberg/nativescript-app)
I will follow the documentation next days and generate some components and tell you the results.

**Comment by johannesjo** [comment]
Looking forward to that!

**Comment by felixlberg** [comment]
Hey sry for the late reply 

I've setup now sp2 successfully works really nice I will dig something deeper in your structure.

Nice work deffenitly

**Comment by johannesjo** [comment]
Thank you! 
I took the week off from work to finally make some progress :)

**Comment by johannesjo** [comment]
Not sure if the issue persisted to v2. Will close this for now.
