### ISSUE TITLE
Add option to not synchronize the sync interval

### ISSUE THREAD

**Issue by Rapha149** [johannesjo/super-productivity#1212]
## Problem Statement
I have superProductivity on my PC and on my mobile phone. I synced this via Dropbox. But on my pc which is longer on I want the sync delay at 20 minutes and on my mobile phone, because I sometimes close the app quickly, I want it at 1 minute. Unfortunately the sync process also synchronizes the sync interval so it's either 1 minute on my PC or 20 minutes on my mobilde phone.

## :grey_question: Possible Solution
Add an option to not sync the sync interval. Or even better: add options for what do you want to synchronize like tasks, notes, settings etc.

## :arrow_heading_up: Describe alternatives you've considered
I can't think of anything.

## :heavy_plus_sign: Additional context
I didn't know what to search for, I'm sorry if a feature request like this already exists.

**Comment by johannesjo** [comment]
Hey there! Thank you very much for opening this up! Would be nice to have this, but is not on top of my list tbh.

**Comment by Rapha149** [comment]
Yeah understandable because it's a little feature. But thank you for considering.
