### ISSUE TITLE
Manual synchronization

### ISSUE THREAD

**Issue by ravalos7** [johannesjo/super-productivity#1213]
When using Google Keep, they have a very useful functionality in the form of a button with a curved arrow, which allows you to manually synchronize the changes made in such a way that both desktop and mobile have the same information, but no one is being made. automatic synchronization every minute which slows down the work. So in this way when you finish occupying the application, you press the manual synchronization button and Voilá !!!! Thank you very much and congratulations for a great initiative, my deepest thanks !!

![imagen](https://user-images.githubusercontent.com/200305/118372200-66cab700-b57e-11eb-92b2-e26ae21cc828.png)

**Comment by johannesjo** [comment]
Hey there! Thank you very much for the suggestion! Makes a lot of sense to have this.

**Comment by johannesjo** [comment]
This is added for mobile now.
