### ISSUE TITLE
Tray icon not reporting the current task

### ISSUE THREAD

**Issue by matbok** [johannesjo/super-productivity#1223]
### Environment
* Version used: 6.5.2
* Operating System and version: Windows 10

### Expected Behavior
Having checked the following flag in the setting panel:
![image](https://user-images.githubusercontent.com/72856962/118975040-d45a5700-b973-11eb-966b-2ec2e6465112.png)
I would expect to see something related to the current task when I mouse-over or click the tray icon.

### Current Behavior
Actually, mousing-over the tray icon, nothing appears, and by right-clicking only this menu is hown:
![image](https://user-images.githubusercontent.com/72856962/118975288-2602e180-b974-11eb-96f9-0de865e889a2.png)

### Steps to Reproduce (for bugs)
1. start tracking a task
2. mouse-over / click on the tray icon

### Error Log (Desktop only)
no logs files found

**Comment by johannesjo** [comment]
Thank you very much for bringing this to my attention! Unfortunately showing the task title only works on mac and there the setting doesn't have any effect neither. I'll removing the setting.

**Comment by johannesjo** [comment]
Thinking about it, I decided to add the task title as a tooltip for non mac platforms, though this doesn't seem to work for gnome environments. We could also experiment with `tray.displayBalloon` (for windows only), but I currently  don't have a windows pc available to test this properly, so I would need help. Another option, as you suggested, would be adding the title to the menu itself. I am open for PRs dealing with this problem.
