### ISSUE TITLE
Can't restore from backup

### ISSUE THREAD

**Issue by ch4r1i3b** [johannesjo/super-productivity#1224]
### Your Environment

- Version used: snap 6.5.2
- Operating System and version: Ubuntu 20.04
- Desktop Environment: Gnome Shell
- Browser Name and version: Firefox 88.0.1

### Expected Behavior
First of all, I think superProductivity is awesome! Now, let's go to the issue:

SuperProductivity crashed, I had to reinstall it, when I ran it again, I saw that all my worklog dissappeared.
I confirmed that I have all the data daily backed-up in json files (projects, subprojects, tasks, date, times, etc.), nevertheless I don't know how to restore it.
 In Settings, I configured Automatic Backups. The help states: "Auto save all data to your app folder in order to have it ready in case something goes wrong." It would be great to know what to do in case something goes wrong.

### Current Behavior
I could not find the way to recover the data from the json backups.
That's it, if I reinstall superProductivity (in the same or in another machine), how can I restore my data from the backups?
Thanks!

**Comment by johannesjo** [comment]
Hey there! Were you able to solve the problem? If not this looks like a good question for the q&a section under discussions.

**Comment by ch4r1i3b** [comment]
Hi Johannes!Thanks for your quick response!No! I couldn't solve the problem, can you please tell me how can I access the Q&A seccion? I couldn't.Regards!
Carlos

    El jueves, 20 de mayo de 2021 13:33:24 ART, Johannes Millan ***@***.***> escribió:  
 
 


Hey there! Were you able to solve the problem? If not this looks like a good question for the q&a section under discussions.

**Comment by johannesjo** [comment]
Thank you!
