### ISSUE TITLE
Automatically add tasks scheduled for today to "Today" section

### ISSUE THREAD

**Issue by JLuisGT** [johannesjo/super-productivity#1230]
First thing's first. What a wonderful application.
It has many features that others offer in the premium plan, and more. It quickly became my go-to app for organizing tasks.

Now, the feature ...

## Problem Statement

I don't know if there is currently a way to achieve this and I haven't found it, but I think **tasks scheduled for a particular date should automatically be added to the "Today" section on that date**.

**Current behavior**: I need to review the Scheduled section and my main projects and manually add the tasks to Today.

Additionally, as a plus, it would be excellent if at startup the application showed a notification with the tasks scheduled for today, both in the desktop version and in the Android version.

## :grey_question: Possible Solution

At startup, the application should review the tasks scheduled for that day and add them to the Today section automatically

**Comment by johannesjo** [comment]
Hi there! Thank you very much for opening this up. In the most recent release candidate I added a button to add those tasks to your daily list (but only if you are in planning mode, which is triggered when you have no tasks on the list). This might alleviate the problem, though I agree that either adding those tasks automatically might be nice, too. The problem is, that a user might not want a task to show up until later, but currently every task with the today tag, will show up on the today's list. In case we want to automatically add tasks planned for today to the today list, I think we have to forgo that option. Not really sure what the smartest way is to deal with the whole situation tbh.

**Comment by JLuisGT** [comment]
Johannes.

First of all, thank you for your quick and attentive response. You are an inspiration to the free software community.



>  In the most recent release candidate I added a button to add those tasks to your daily list 

Do you mean the Sun-shaped button or is there a button in the new version that reviews all tasks and adds those scheduled for today to the Today section? If that's the case, I think it would be sufficient for my needs, especially if I can run that button automatically with crontab in some way, every day in the morning.


> (but only if you are in planning mode, which is triggered when you have no tasks on the list)

Is this planning mode in the documentation? I would like to read more about it. Since I adopted SuperProductivity with intensity and added a lot of tasks, so it has not happened that I do not have tasks in the list: D (Maybe it is something I should work on)



> The problem is, that a user might not want a task to show up until later, but currently every task with the today tag, will show up on the today's list. In case we want to automatically add tasks planned for today to the today list, I think we have to forgo that option (of removing tasks from the today list until scheduled). Not really sure what the smartest way is to deal with the whole situation tbh.

Any chance to add it as an option in the Today's Settings section? As I mentioned, a button that has this function and can be triggered automatically with some script would also be enough for me.

So, just to clarify, currently the application shows in the Today section only the tasks whose date and time are earlier than the current date and time or must necessarily be added to Today section by pressing the corresponding button (sun)? If it is the first option, it makes sense as a less cluttered approach, although in my case, I would prefer to have an overview with all my tasks for today. 

Thanks again for making free software such a wonderful application. I am sure that it will become the preferred option in Linux and a very tough competitor for other applications that charge for less functionality than this application offers (at least for my requirements).
Soon I will take the time to write an article to give greater diffusion to the application in Spanish (my mother tongue) and that more people can and support the project and benefit from this gem.

**Comment by johannesjo** [comment]
> Is this planning mode in the documentation? I would like to read more about it. Since I adopted SuperProductivity with intensity and added a lot of tasks, so it has not happened that I do not have tasks in the list: D (Maybe it is something I should work on)

Planning mode is triggered automatically when there are no undone tasks left any more in his list and the user clicks on "Add more". 
![Screenshot from 2021-05-25 11-04-03](https://user-images.githubusercontent.com/1456265/119470848-06d7cb80-bd49-11eb-8b43-2698ea45ac5d.png)
![Screenshot from 2021-05-25 11-04-28](https://user-images.githubusercontent.com/1456265/119470859-09d2bc00-bd49-11eb-9e71-3561bd71b1a4.png)


> Any chance to add it as an option in the Today's Settings section? As I mentioned, a button that has this function and can be triggered automatically with some script would also be enough for me.

Making this optional could be a good approach though I am still unsure what the best default behavior would be with this. I have to think about it.


> Soon I will take the time to write an article to give greater diffusion to the application in Spanish (my mother tongue) and that more people can and support the project and benefit from this gem.


Much appreciated! :)

**Comment by JLuisGT** [comment]
Oh, I think a button like that will be enough for me.
I'll be waiting that release ;)
