### ISSUE TITLE
Copy tasks from one project to another / Import tasks from Excel

### ISSUE THREAD

**Issue by jackuars89** [johannesjo/super-productivity#1233]
For me I have well defined tasks around 72 of them, and I would require these tasks to be copied to projects I create. How can I do this? Can you implement a feature to copy tasks from one project to other, or if we can import a set of tasks from an Excel file? Either way it would work.

**Comment by johannesjo** [comment]
Hi there! Both is currently not planned. The data format isn't too complicated and you might be able to write a script for this yourself. If you want to go down this road, I'd recommend starting with a simple project and just some tasks and then use the export functionality under settings. This should give you a basic template that should help you to proceed.

**Comment by johannesjo** [comment]
Probably related: #946

**Comment by johannesjo** [comment]
If he isn't interested, I am :)

**Comment by Paladiamors** [comment]
I'll make a repo and post it later today. can find out a way to have it join as a tool or be something stand alone :) 

It's pretty naieve at the moment but managed to work ok.

**Comment by Paladiamors** [comment]
I've pushed a rough cut of the code. It basically shows how to add new projects and tasks to the json file and can be adapted to whatever input that other people might have.

https://github.com/Paladiamors/superproductivity_editor

**Comment by johannesjo** [comment]
Thank you very much for sharing @Paladiamors !
