### ISSUE TITLE
Add list of tasks as subtasks

### ISSUE THREAD

**Issue by k4misiek** [johannesjo/super-productivity#124]
Hello, it is possible to add list of tasks separated with new lines at once?
I have for example 100 subtasks and I don't want to add one by one.

**Comment by johannesjo** [comment]
Hey there! Sorry for answering just now. I must have overlooked the email notification or deleted it by accident.

At the moment there is no feature to support that. You might be able to directly save your data to the storage via javascript using the console (Ctrl+Shift+I).
