### ISSUE TITLE
Nextcloud Sync with WebApp, WebDAV: No etag

### ISSUE THREAD

**Issue by stoically** [johannesjo/super-productivity#1246]
### Your Environment

- Version used: 7.0.0-rc16, latest from docker hub
- Operating System and version: Ubuntu 21.04
- Desktop Environment: Gnome3
- Browser Name and version: Firefox 88, Chromium 90.0.4430.212, Chrome 91.0.4472.77
- Nextcloud: 21.0.2
- Traefik CORS rules:

  ```
          traefik.http.middlewares.nextcloud-CORS.headers.accesscontrolallowcredentials: "true"
          traefik.http.middlewares.nextcloud-CORS.headers.accesscontrolallowmethods: "GET,OPTIONS,PUT,DELETE,HEAD,MOVE,PROPFIND"
          traefik.http.middlewares.nextcloud-CORS.headers.accesscontrolallowheaders: "authorization,content-type,user-agent"
          traefik.http.middlewares.nextcloud-CORS.headers.accesscontrolalloworiginlist: "https://super-productivity.{{ alternate_domain }}"
          traefik.http.middlewares.nextcloud-CORS.headers.accesscontrolmaxage: "100"
          traefik.http.middlewares.nextcloud-CORS.headers.addvaryheader: "true"
  ```

### Expected Behavior

WebDAV sync with Nextcloud works

### Current Behavior

WebDAV sync with Nextcloud fails with "WebDAV: No etag" alert box

### Steps to Reproduce (for bugs)

1. Configure WebDAV sync with Nextcloud in WebApp

### Console Output

```
Error: WebDAV: No etag
    getRevAndLastClientUpdate web-dav-sync.service.ts:45
    o main.6a7ffd93ec0e1a441e85.js:1
    Angular 21
    exports index.js:9
    C Angular
    exports index.js:9
    exports index.js:16
    Angular 24
    c main.6a7ffd93ec0e1a441e85.js:1
    C Angular
    c main.6a7ffd93ec0e1a441e85.js:1
    o main.6a7ffd93ec0e1a441e85.js:1
    Angular 12
web-dav-sync.service.ts:56:14
```

### Notes

It seems the issue is the `HEAD` request made by 

https://github.com/johannesjo/super-productivity/blob/b47875f4de8107d3e77f8db242eaf6ebc296cae4/src/app/imex/sync/web-dav/web-dav-api.service.ts#L84

which, if manually executed in the browser console, returns an empty `headers` object. While when copied as curl request it correctly returns the headers, as does the browser network tab which shows the correct headers, including etag as "response headers", really odd

No CORS error are visible, so CORS configuration seems to generally be fine

**Comment by johannesjo** [comment]
Thank you very much for reporting this. Looks like an issue with your server configuration, though this should likely be a warning rather than a full blown error, as sync should still work, just way less efficient.

**Comment by stoically** [comment]
You're right, haven't considered it might still work but it does :+1: It also asks on every sync whether to upload local to remote since no remote data was found - could this be problematic in terms of multiple devices syncing?

Also maybe any idea what might be wrong with the server configuration? Given CORS works and curl returns all response headers I'm a bit lost where to continue debugging :thinking:

**Comment by johannesjo** [comment]
> could this be problematic in terms of multiple devices syncing

It shouldn't. The missing etag just leads to the whole data being downloaded whenever sync is triggered rather than being able to quick check for changes before. Though currently with the error thrown, I can make no guarantees. I try to address this tomorrow.



> Given CORS works and curl returns all response headers I'm a bit lost where to continue debugging

[This thread](https://github.com/owncloud/client/issues/1291) might contain some contain some information. Otherwise I would google for "nextcloud no etag in response" or similar.

**Comment by johannesjo** [comment]
With the latest changes (not present in any release yet) this should work in more flexible manner.

**Comment by stoically** [comment]
Thanks for addressing this. Going by the commit this will still throw for me given that `headers` is completely empty. Hopefully I'll figure out what's causing it, though the linked thread mentions that curl and/or network tab also not responding with headers. In my case the browser network tab and curl both do have response headers including etag.
