### ISSUE TITLE
giving the user the abitily to chose where to Backup his tasks

### ISSUE THREAD

**Issue by mlaarebi** [johannesjo/super-productivity#1248]
It's clear from the title.

**Comment by johannesjo** [comment]
Thanks for opening this up. You can already do that by specifying  `--user-data-dir=/some-path/` though this will also change where everything else is saved.

**Comment by nichrishayes** [comment]
I'm going to second this enhancement request, with the understanding there is existing functionality with what I'd consider a fair workaround. I've played with the command-line option to specify but I think it's limited. Wish I developed in electron as I'd try to help take this contribution on, but not too familiar with the language or testing.

Ideally, it gets implemented similar to SN does here: https://github.com/standardnotes/desktop/blob/20ab45dda4246e71892d4ed192e85cc65da09d9e/app/javascripts/main/backupsManager.ts

A decent alternative would be it stores the most recent backup location and uses that as default until re-specified. So a user could run it from the command-line with --user-data-dir once to update the default location, and could open the app normally via double-click.

On macos, if it's helpful to others, my temp workaround was to - 
1) Make a shell script called "superProductivityO" with:
#!/usr/bin/env bash
/path/to/Applications/superProductivity.app/Contents/MacOS/superProductivity --user-data-dir=/path/to/preferred/backuplocation&
2) make a directory structure:
/path/to/Applications/superProductivityO.app/Contents/MacOS/
3) give exec permissions to everything in the new superProductivityO.app folder (via terminal, chmod +x /path/to/Applications/superProductivityO.app)

Thank you for developing this excellent app!
