### ISSUE TITLE
Integration with toogle or zapier

### ISSUE THREAD

**Issue by gustawdaniel** [johannesjo/super-productivity#125]
Hi.

I like your idea and this application looks grat. Are you planning to integration with

> https://toggl.com/app/

or 

> https://zapier.com/

**Comment by johannesjo** [comment]
Not at the moment, as I'm quite busy with the rewrite of the application  (https://github.com/johannesjo/sp2). If an integration is high on demand, I definitely would consider support for both of them.

**Comment by johannesjo** [comment]
While I probably won't build a toggl implementation I would suggest to use jira/git as a bridge for integrating the app.

I'm closing this, as I don't have high hopes that anybody else would work on this.
