### ISSUE TITLE
Add task text goes away if clicked off, can this be remedied to hold that text in a buffer?

### ISSUE THREAD

**Issue by HoaxParagon** [johannesjo/super-productivity#1251]
I looked through feature requests and couldn't find anything relating to this issue. If it's a dupe, ignore and slap my wrist please.

**Comment by johannesjo** [comment]
Hi there! What version are you using? This should be fixed with the latest I think.

**Comment by HoaxParagon** [comment]
This feature has been included. I restarted my computer and the update took hold. This issue is closed.

**Comment by johannesjo** [comment]
Thank you!!
