### ISSUE TITLE
[Feature]  Insert image and search all tasks

### ISSUE THREAD

**Issue by yulahuyed** [johannesjo/super-productivity#126]
- Sometimes we need to keep ideas in a image, and it will be useful if super-productivity 
supports to insert a image.
- After using a long time, it's hard to find a previous one from thousands of tasks and uncertain date.

**Comment by johannesjo** [comment]
Hey there! Thanks for the suggestions. Currently I am spending a lot of time on the next version of the app. Images are a planned feature (not as a task replacement, but as note type). Searching of all the tasks, also makes sense. Will take some time until I get there though.

**Comment by johannesjo** [comment]
Hi. Images can now be attached via drag and drop to a specific task. Let me know if this covers your use case.

**Comment by johannesjo** [comment]
It's now also possible to attach images as notes.

**Comment by johannesjo** [comment]
I experimented with searching quite a bit, but haven't found a satisfying solution so far as it clutters the ui a little bit too much for my taste (there is too much stuff to click as it is), so I won't add the feature for now. If more people are missing it, I might reconsider it though.  Thanks for your input.
