### ISSUE TITLE
Some kind of screen take over when time runs out

### ISSUE THREAD

**Issue by mjchetcuti** [johannesjo/super-productivity#1262]

**Comment by johannesjo** [comment]
?

**Comment by johannesjo** [comment]
No. For my personal needs this behavior hits the sweet spot, but I can see that this might be different for other people. I am open for (optionally) extending this by also sending a system notificaiton maybe. What do you think?

**Comment by mjchetcuti** [comment]
That would be amazing yes! Thank you :D

**Comment by m-kreis** [comment]
There are two timers that work like that (break reminder and idle reminder). They just focus the app. It would be great if there was an option to switch on and of this same behavior for the pomodoro timer.
@johannesjo Is this what you meant about system notification?

**Comment by johannesjo** [comment]
@m-kreis by system notification I mean these:
https://web-push-book.gauntface.com/demos/notification-examples/

**Comment by m-kreis** [comment]
But this is only for the browser? I'm using the desktop app. I would really be looking forward for the "focus app when pomodoro timer ran out" feature as i'm constantly missing my breaks. Or have i misunderstood your answer?

**Comment by johannesjo** [comment]
> But this is only for the browser? I'm using the desktop app.

No, but it will be the same for the electron app :)
