### ISSUE TITLE
bug when trying to export tasks

### ISSUE THREAD

**Issue by mlaarebi** [johannesjo/super-productivity#1265]
When trying to export my tasks from the settings, clicking on the button opens the file manager, not a save window. 

I'm using a linux dist with kde plasma.

**Comment by johannesjo** [comment]
Hi there! Data should be automatically saved to the download folder. Does this not work?

**Comment by mlaarebi** [comment]
> Hi there! Data should be automatically saved to the download folder. Does this not work?

It works, but what doesn't is (in the screenshot). 

when I click on the export button, it opens a file manager (or explorer).
![Screenshot_20210602_163729](https://user-images.githubusercontent.com/50870076/120510382-46458e00-c3c1-11eb-8c35-50ae4a557d14.png)

**Comment by johannesjo** [comment]
It should open the file manager in the download folder where the data can be found as super-productivity.json. Does it do that?

**Comment by mlaarebi** [comment]
> It should open the file manager in the download folder where the data can be found as super-productivity.json. Does it do that?

yes, it does. I'm sorry, I thought it would ask me where to save it first.

**Comment by johannesjo** [comment]
Alright, I am closing this then.
