### ISSUE TITLE
App not launching

### ISSUE THREAD

**Issue by Zmansi25** [johannesjo/super-productivity#127]
## Your Environment

* Version used:  1.10.56 latest release
* Operating System and version: Ubuntu 16.04
* Desktop Environment:  Linux

## Expected Behavior
 

I'm trying to run the app but the app is not launching though there are no errors. After doing npm start it says

> superProductivity@1.10.56 start /home/mansi/Documents/super-productivity-develop
> NODE_ENV=DEV electron ./electron/main.js

Starting in DEV Mode!!!
and the app is terminated. Haven't made any changes to code yet.

**Comment by johannesjo** [comment]
Hey! Thanks for reporting! Did you execute an npm install before starting the app?

**Comment by Zmansi25** [comment]
Hi Johannes,

Yes I did npm install. I think the issue is with this : 

```
let shouldQuitBecauseAppIsAnotherInstance = app.makeSingleInstance(() => {
  // the callback: only called only for first instance
  // we want to show it, when the other starts to try another
  if (mainWin) {
    showApp();

    if (mainWin.isMinimized()) {
      mainWin.restore();
    }

    mainWin.focus();
  }
});

if (shouldQuitBecauseAppIsAnotherInstance) {
  quitAppNow();
  return;
}
```
shouldQuitBecauseAppIsAnotherInstance is always true, the control is not going in the `app.makeSingleInstance() `

**Comment by johannesjo** [comment]
This usually means that there is another instance somewhere in the background. Not sure why it is not brought to the front though. Does pressing Ctrl+Shift+X do anything?

**Comment by Zmansi25** [comment]
No, nothing happens with Ctrl+Shift+X. Can't even see anything running in system monitor.

**Comment by johannesjo** [comment]
That's interesting. `app.makeSingleInstance()` is [an electron function](https://github.com/electron/electron/blob/2-0-x/docs/api/app.md#appmakesingleinstancecallback), with which I had never problems with so far. Not really sure why this isn't working in your case. What is the locally installed electron version (in the package-lock.json and if present, the global as well)?

**Comment by Zmansi25** [comment]
I've installed it locally , v2.0.14.

I changed the electron version to 3.0.7,and in main.js replaced `app.makeSingleInstance()` with  
`app.requestSingleInstanceLock()` and `app.on('second-instance', cb)` and strangely it works now.

Thanks for your time

**Comment by johannesjo** [comment]
That's great! Would you maybe willing to provide a PR with the changes you made (updating the electron version and adding the new syntax)? I would really appreciate it! :)
