### ISSUE TITLE
It keeps telling me to take a break when I already did. => Reset break timer when pomodoro break ends

### ISSUE THREAD

**Issue by GitHubWhatsup** [johannesjo/super-productivity#1271]
I repost this because I closed the previous one.

- Version used: superProductivity-7.0.0-rc16.x86_64.rpm
- Operating System and version: Fedora
- Desktop Environment: Gnome

### Current Behavior

- Pomodora Timer mode is on.

"Take a break! You have been working for 1h 6m without one. Go away from the computer! Take a short walk! Makes you more productive in the long run!"

**Comment by kwongtn** [comment]
Would ask if you could clarify on the following:
1. How did you indicate your "break" towards the program? Is it by stopping the timer or..?
2. Could you link to the previous issue? 

Thanks.

**Comment by GitHubWhatsup** [comment]
>     1. How did you indicate your "break" towards the program? Is it by stopping the timer or..?
> 
>   @johannesjo Pomodora Timer mode is on, so the timer stop itself every 20 minutes. I start the timer manually.
