### ISSUE TITLE
Let me choose a specific project as my homepage.

### ISSUE THREAD

**Issue by GitHubWhatsup** [johannesjo/super-productivity#1272]

**Comment by imashishks** [comment]
Just wanted to confirm if this issue means that should be some setting to make a project the default one to load when the app is started?

**Comment by johannesjo** [comment]
> Just wanted to confirm if this issue means that should be some setting to make a project the default one to load when the app is started?

@imashishks That's how I would understand this.

**Comment by GitHubWhatsup** [comment]
> Just wanted to confirm if this issue means that should be some setting to make a project the default one to load when the app is started?

Yes.
