### ISSUE TITLE
How to clear all data and start over?

### ISSUE THREAD

**Issue by Sgt-Miller** [johannesjo/super-productivity#1275]
Hi, I'm using the linux desktop client.   
Is there an option to delete all existing data? 
I want to start over.

**Comment by johannesjo** [comment]
Yes. You can do this by 
1. opening the devtools (Ctrl+Shift+i if you're on Linux or Windows). 
2. Then you need to navigate to the "Application" tab. 
3. Next you select "Storage" in the left hand menu.
4. Then you click "Clear site data"
5. Reload the app via "Ctrl+R"

![Screenshot from 2021-06-07 13-06-30](https://user-images.githubusercontent.com/1456265/121006554-4d89e480-c791-11eb-8e03-3a4960e5106a.png)

**Comment by Sgt-Miller** [comment]
Thanks that worked!

**Comment by johannesjo** [comment]
Ah btw. stuff like this is best not opened as an issue but rather as question on the discussions page:
https://github.com/johannesjo/super-productivity/discussions
