### ISSUE TITLE
Should delay main screen quotes until user decides 

### ISSUE THREAD

**Issue by NumDeP** [johannesjo/super-productivity#1284]
I feel like the person at the pictures when a quote or statement appears out of the blue for a brief period and I'm rushing to read it :)

Most of the time the quotes remain for milliseconds, literally; it would be nice if the quotes on startup remain there up until you move the mouse on the app.

Thanks

**Comment by johannesjo** [comment]
Hey there! That's an interesting suggestion! I am all for making this happen (though the user should be able to disable this behavior in the settings).

**Comment by NumDeP** [comment]
Not to sound rude but I don't see what need there is to make this a proper feature i.e making it part of settings. I like how simple settings is already. You've done such a brilliant job I don't think people would appreciate unnecessary clutter. You know what I mean?

Right now a user doesn't have a choice for disabling and enabling anything pertaining to startup, like the quotes - because it wasn't an issue, it isn't a huge issue. We just think it's a unique and inspiring part of Super Productivity without choice. Let users just figure it out naturally that once you move the mouse as soon as you hit/launch the application, that it will remain like that up until you move the mouse, though if you prefer to add a six, seven, eight second rule to it wouldn't bother me.

I'll let you figure it out seeing as we both want the same thing :)

**Comment by johannesjo** [comment]
You're absolutely right about the clutter, but personally I know that I would be very annoyed once I've read all the quotes a couple of times and I had to wait 7-8s extra every time :)

**Comment by NumDeP** [comment]
The movement of the mouse would immediately jump the quotes though, which is probably how a lot of users already use it by moving the mouse ASAP to the left of Projects, so the idea is that it should only remain so as long as you don't move the mouse, the time was just a suggestion so it doesn't remain forever and so a setting creation can be technically avoided:)

**Comment by johannesjo** [comment]
That's a good idea. We probably should also display a message to inform the user: "App loaded. Move the mouse/tap to get going" or something similar.

**Comment by NumDeP** [comment]
@johannesjo don't you think that would be obvious? I think people are naturally fidgety when they've got their palm on a mouse or fingers on a trackpad, a slight pause from them to read the quotes and slight movement from the mouse I figure they'd instantly tell that the mouse moves the quotes away. I doubt they'll think it's frozen.

**Comment by johannesjo** [comment]
> don't you think that would be obvious?

No I don't. Almost all loading screens I encountered in my life were shown as long as needed and disappeared by themselves once and mostly only when this was not the case any more (this is at least how it appeared to me ;)).  I am very fidgety, too, but I also saw people behave very differently.

**Comment by johannesjo** [comment]
@Fleker just recognized that the tagging of this issue was misleading. Sorry for that!

**Comment by NumDeP** [comment]
:)

**Comment by NumDeP** [comment]
Only commenting to keep it open :)

**Comment by giTran-s** [comment]
Yes, please allow more time to read the quote, it's faster than the blink of an eye! Thanks

**Comment by steve-biggs** [comment]
Yes, still relevant, keep open please.

I think a settings option to activate a "continue" button or similar would be best. Then we meet @NumDeP, @giTran-s and my objective of being able to read the tips, and @johannesjo objective of the default being a quick and automatic continuation from the splash screen, e.g. for new users. This way, there is no lag from an arbitrary X seconds delay that may be too long for some and too short for others, and users can just deactivate the option again when they've seen all the messages and get bored of them rather than getting annoyed at having to wiggle the mouse to move on.

Thanks. Great app BTW. I use it every day :)
