### ISSUE TITLE
Task removed from my day disappeared

### ISSUE THREAD

**Issue by joakimc** [johannesjo/super-productivity#1285]
I clicked the 'Remove from my day'-button on a task, and it disappeared from the today-list. I expected to find it in one of the projects, but it's not in any project or tag. Now it apparently disappeared from SP. I can still see the task in the worklog, but otherwise the task seems to be completely gone.

### Your Environment

- Version used: 7.0.1
- Operating System and version: MacOS

### Steps to Reproduce (for bugs)

This is not a good bug report, because I'm not able to reproduce it, but thought I should report it anyway.

**Comment by johannesjo** [comment]
Hi there! Thanks for opening this up. Is there a restore button next to the task in the worklog? If so, the task might just have been moved to the archive.

**Comment by joakimc** [comment]
Unfortunately no. Might be because it wasn't completed.

**Comment by johannesjo** [comment]
It would be great if you could share a copy of your data to contact@super-productivity.com (and also the name of the task), so I can debug this on my computer. You can create an export by navigating to "Settings" and then to "Import/Export".

**Comment by dahaupt** [comment]
@johannesjo I probably ran into the same issue. In my case the task appeared again after adding the task id to the JSON object `project.entities.{projectId}.taskIds`. The `projectId` within the task entity was always set.

**Comment by johannesjo** [comment]
Sorry, missed this. Is this still relevant. If so, a copy of your data would be needed.

**Comment by joakimc** [comment]
Hi, you can probably close this. I haven't tested the software in a while, and unfortunately I'm not allowed to share data related to my company's internal projects and activities.

**Comment by johannesjo** [comment]
Hey @joakimc you can use the "< >" button under settings/import/export. This way all data will be replaced with random strings (it's best to double check of course).
