### ISSUE TITLE
idle-time pop-up freeze the app till switch to another app

### ISSUE THREAD

**Issue by matbok** [johannesjo/super-productivity#1291]
### Environment
* Version used: 7.0.1
* Operating System and version: Windows 10

### Expected Behavior
When I leave the PC idle for 5 minutes, the App get the focus asking me how to track the last minutes. I would expect, as in the previous versions, that the app is responsive, allowing me to immediately click on the buttons of the pop-up.

### Current Behavior
When the app get the focus, it is frozen and there is no pop-up for idle time tracking, and I can't click on anything. I need to give the focus to another app, then coming back to super productivity. Now, the pop-up is visible and I'm able to manage the idle time.

### Steps to Reproduce (for bugs)
1. leave the PC idle for 5 mins
2. click on the APP cell in the start bar when it start signaling that you need to track some idle time
3. observe the frozen status and the absense of the pop-up
4. switch to another open application
5. come back to super productivity, observing that now everything's ok

### Error Log (Desktop only)
no logs files found

**Comment by johannesjo** [comment]
Hi there! Thanks for reporting this. I am unable to reproduce the issue. Are you using the windows store version or the setup exe?

**Comment by johannesjo** [comment]
That's what I tested. Hm very odd. I am unable to reproduce it, so I am not sure how to proceed with this...

**Comment by matbok** [comment]
don't worry, it was just to let you know. it could be not a problem of SuperProd but of something else on my PC, but it started just with the update from the 6.5.2 to the 7.0.1

**Comment by JustAPhrog** [comment]
Same here: 7.0.1 setup.exe

**Comment by codeling** [comment]
I think I'm also affected by this issue. For me it also helps to move the superproductivity window around, then its content updates again. To me it looks like a missing "update" call or something... will try to see if the log shows some more info

**Comment by codeling** [comment]
When the console is openend (Ctrl+Shift+i), the problem does not seem to happen. Instead I get nervous looking at the [persistence] messages triggered each second when a task is running ;)

**Comment by codeling** [comment]
This issue is still happening for me with 7.10.1
