### ISSUE TITLE
Scheduled item does not show up at app startup, only if containing project is shown

### ISSUE THREAD

**Issue by kosi2801** [johannesjo/super-productivity#1297]
### Your Environment

- Version used: 7.0.3 from Windows Store
- Operating System and version: Windows 10 Enterprise 1909

### Expected Behavior

When I open SuperProductivity tasks that are repeatedly scheduled (eg. every Mo-Fr.) should be automatically created and put into "Today".

### Current Behavior

When opening SuperProductivity repeatedly scheduled items (that are part of a project) do not get created.
Only when the containing project is selected/shown through the sidebar, the scheduled item gets created.

### Steps to Reproduce (for bugs)

(Item which is affected was created with older version of SuperProductivity, if that's important)

- Create a new project
- Create an item
- Edit item, set up "Repeat" on Mo-Fr
- Resolve item for today, close SuperProductivity
- on next day, open SuperProductivity again

### Console Output

Lots of output, but unsure w

### Error Log (Desktop only)

Unfortunately on my Windows computer the logfile is not at that location and I cannot locate my Roaming profile directory.
Hope that's not an issue :-(

**Comment by johannesjo** [comment]
Hi there! Thanks for opening this up! That's kind of intentional to avoid a couple of problems, though I agree that it isn't ideal.

**Comment by kavyadav** [comment]
I am facing the same issue. Is this a new feature here to stay?

**Comment by johannesjo** [comment]
> I am facing the same issue. Is this a new feature here to stay?

Not new, has been like this for quite some time now.

**Comment by kipwittchen** [comment]
I also started experiencing this a week or so ago. I preferred when repeating tasks were auto-generated on startup every morning. I have a couple repeating daily tasks that are not assigned to a project and even to have those pop up I have to click a random project and then go back to the Today screen.

**Comment by johannesjo** [comment]
@kipwittchen I don't remember changing anything regarding that. Could you pinpoint when this started happening?

**Comment by kipwittchen** [comment]
@johannesjo Based on the release schedule, I assume it started with version 7.

**Comment by JustAPhrog** [comment]
I have same problem - one task mon-fr showed when change tab (ex timeline). I use 7.0.1 from setup.exe on win10

**Comment by johannesjo** [comment]
Just a thought: Maybe you forgot to add the today tag in the config dialog?

![Screenshot from 2021-06-18 11-31-05](https://user-images.githubusercontent.com/1456265/122540352-d7a33a00-d028-11eb-8c3a-5ce86fffee06.png)

**Comment by kosi2801** [comment]
Hi Johannes,

Thanks for the hint, checked again to be sure but the "Today" tag is
properly present.

BR,
 Andreas

Johannes Millan ***@***.***> schrieb am Fr., 18. Juni 2021,
11:32:

**Comment by kipwittchen** [comment]
@johannesjo I checked and today is tagged. It looks just like your example except I also have Move task to bottom of list checked (which works properly):
![image](https://user-images.githubusercontent.com/11564093/122549828-eb3aaa80-d000-11eb-9d5a-e09a9bd9e60d.png)

This morning I tested the behavior with these steps:
Launched Super Productivity
All incomplete tasks are correctly still there but my repeating one (I check it complete at the end of every day) is not.
I click the three lines for menu in the top left and then a project.
Once on the project page, I get a hamburger notification that my task has been added to today (forgot to grab a screenshot)
Go back to the today screen and my task is again at the bottom.

Prior to version 7 (again, I'm assuming it was version 7 based on dates of releases), any tasks tagged Today would be added as soon as I launched super productivity.

Btw, I absolutely love this program. It's the first task manager I've actually kept using beyond the 1 month honeymoon period.

**Comment by johannesjo** [comment]
I think these are two separate issues, please correct me if I am wrong!
1. There are people that have problems with the point of time when repeating tasks are created (only after a list was deselected and then selected again (or the containing project is opened), which is intentional, but should be improved.
2. There are people having problems that tasks don't show up at all in the today list and only for the project list, even though the repeat config is configured to do so.

So my question to everyone would be if you are experiencing 1 or 2.

**Comment by johannesjo** [comment]
I adjusted 1. Please let me know if 2 is a problem for anyone.

**Comment by kipwittchen** [comment]
@johannesjo 2 is exactly what I'm experiencing. The task still is created in the correct place under today but isn't created until I go to a project list (doesn't matter which one).

**Comment by johannesjo** [comment]
@kipwittchen I suppose it's still possible to manually add the today tag, I'd assume. I have no idea what might be causing this. Code looks like it does what it should. When the repeat configuration is properly set in the dialog it should work. Maybe for now, you could give the latest updates a spin. Also re-creating the repeating task from scratch be worth trying out.

**Comment by kavyadav** [comment]
I am facing 2 as well. Tried recreating the repeating task from scratch but it still doesn't show up in the Today section on opening the app for the first time in the day, until I head over to the project containing the task.

**Comment by johannesjo** [comment]
7.1. is out now and hopefully addresses the issue. Please let me know if the issue still persists.

**Comment by JustAPhrog** [comment]
After app launch (upgraded to 7.1; setup.exe) my reccuring task showed without switching tab. Thanks! 🎉

**Comment by johannesjo** [comment]
Alright! Thank you! I am closing this then. Let me know, if there are still issues with it.
