### ISSUE TITLE
TaskBar: Make "indeterminate state for tasks with no time estimate" configurable

### ISSUE THREAD

**Issue by thetric** [johannesjo/super-productivity#1299]
## Problem Statement
https://github.com/johannesjo/super-productivity/pull/1273 (v7.0.2) introduced a new feature that shows the app's window's progress bar in indeterminate state for active tasks with no time estimate. 

## :grey_question: Possible Solution
I find this feature extremely distracting when the app is minimized to the task bar. I would suggest to make this behavior configurable (old behavior [default?] and new behavior).

## :arrow_heading_up: Describe alternatives you've considered
n/a

## :heavy_plus_sign: Additional context
n/a

**Comment by johannesjo** [comment]
Hi there! Thank you very much! Makes a lot of sense to me to make this optional (and maybe even opt in).

**Comment by kosi2801** [comment]
Not sure if I understand this issue correct, does it refer to the "Super Productivity" item in the Windows Taskbar always flashing as if an installation of some sorts is going on? (was just about to create an issue for this...)

If yes, then I'd second that this is extremely distracting and appeared really unexpected. On my Installation immediately after SuperProductivity it does not flash, but it starts at some point and never stops flashing anymore until I close the application (ie. it doesn't stop if no task is worked on).

**Comment by johannesjo** [comment]
@kwongtn ping (thought you might be interested in this discussion, too).

**Comment by thetric** [comment]
> Not sure if I understand this issue correct, does it refer to the "Super Productivity" item in the Windows Taskbar always flashing as if an installation of some sorts is going on?

@kosi2801 Yeah, that's what I mean

**Comment by kwongtn** [comment]
> @kwongtn ping (thought you might be interested in this discussion, too).

I temporarily removed the functionality a-la PR #1300 (Can I request an 'emergency' update, while I'm at it? )

As for toggle implementation, I'll do it at a later date, cause I've got finals coming up and I can't figure out some RxJS stuff (refer to PR) plus I won't really want this bug to keep affecting everyone 😅 

I'll try to implement toggle and state clearing for the taskbar notification once I've settled my finals and FYP 🙏

Very sorry everyone for the inconvenience again 😓

**Comment by johannesjo** [comment]
Thank you very much @kwongtn ! And no worries! Also: Good look for the exams! :)

**Comment by johannesjo** [comment]
FYI: I'll try to make a release later today.

**Comment by johannesjo** [comment]
I am closing this. Thanks for the quick help again @kwongtn !
