### ISSUE TITLE
JavaScript error in macOS version

### ISSUE THREAD

**Issue by Donkeyfish87** [johannesjo/super-productivity#13]
![image](https://user-images.githubusercontent.com/15643802/32154731-d76ed0b0-bd32-11e7-89ea-e32bd1a5d20d.png)

**Comment by johannesjo** [comment]
Thanks for reporting. I will check this.

**Comment by johannesjo** [comment]
I updated the binary. Could you please check again?

**Comment by Donkeyfish87** [comment]
Yup it's fixed. Opens fine now.

Thanks, I guess this can close
