### ISSUE TITLE
Show Subtasks inside additional info side bar

### ISSUE THREAD

**Issue by dilbertaz** [johannesjo/super-productivity#1301]
I have been using the subtasks option in the Show/Hide Additional Info recently and today they don't appear there, even for tasks with subtasks already.  I can right click and add that way still.

**Comment by johannesjo** [comment]
Hi there! I assume that you're using a desktop computer with a touch screen?  I removed the feature for those and it's only shown for touch only devices now. Do you think this should be changed back?

**Comment by dilbertaz** [comment]
I'm using desktop version on linux without a touchscreen.
That is a convenient place to manage subtasks and I would think at the
least it should be a user preference whether it is available or not.

**Comment by johannesjo** [comment]
Alright, I am leaving this open for discussion. Please upvote or downvote the original issue, if you like to see this.
