### ISSUE TITLE
Caldav subtasks shown as maintasks 

### ISSUE THREAD

**Issue by memen45** [johannesjo/super-productivity#1311]
### Your Environment
Super Productivity from Windows App Store 7.1.0 
Nextcloud 20.0.10

### Expected Behavior
caldav subtasks list as subtasks of their respective maintasks in e.g. the backlog or task overview of a project:

```
Main task
├── Sub task 1
├── Sub task 2
└── ...
Some huge task
├── Easy task
└── Another
```

### Current Behavior

caldav subtasks are listed as main tasks:
```
Easy task
Another
Sub task 1
...
Some huge task
Sub task 2
Main task
```

### Steps to Reproduce (for bugs)
- create new project
- setup caldav integration with existing calendar from nextcloud
- check all options - especially 'Automatically add uncompleted CalDav todos to your backlog'
- all tasks from the calendar are listed ignoring whether it is subtask or main task

I have read the issue regarding multi-level subtasks. In this case however, there is only two-level hierarchy: main tasks and one level of subtasks, so I think it should import just fine?

P.S.: Really like the project, have been looking for such a task-calendar link for a while, so lots of thanks for all the efforts!

**Comment by johannesjo** [comment]
Hi there! Thank you very much for opening this up! Currently any integration in super productivity treats any imported task as a main task. This allows to break down shared tasks further for you personally. While I see that it might be nice sometimes to have them show up as sub tasks of another task, this opens up a lot of potential complexity that I'd rather avoid, if it can be helped :) I am open for exploring this further (maybe it's simpler than I think), but I won't have any time for this in the near future myself.
