### ISSUE TITLE
Show timeline/calendar events when scheduling a task

### ISSUE THREAD

**Issue by memen45** [johannesjo/super-productivity#1313]
## Problem Statement
When scheduling a task, only an extended date/time picker is shown. However, sometimes I want to schedule in between two other tasks or in between meetings. The current schedule tasks window makes it easy to schedule 2 ten-minute tasks overlapping:
![image](https://user-images.githubusercontent.com/27782135/122787101-47c5f000-d2b5-11eb-9691-4984efb036aa.png)

## :grey_question: Possible Solution
It would be nice if the current Schedule task window could be extended to show the calendar events and scheduled meetings for the selected day/time. Simply add the timeline / scheduled / calendar overview for the selected date/time to the scheduling window e.g. on the right of the date/timepicker:
![image](https://user-images.githubusercontent.com/27782135/122787349-88256e00-d2b5-11eb-8435-e033e46ae1bb.png)

The current task could be shown as 'candidate scheduled' in the overview like:
<img src="https://user-images.githubusercontent.com/27782135/122788021-30d3cd80-d2b6-11eb-8c1c-0d729d4d5e96.png" width="300"/>
Additionally, the date/time picker could be preloaded with a date/time that actually fits the schedule and calendar events. This speeds up scheduling a lot, since now it is likely you can just press 'Schedule' without issue.

## :heavy_plus_sign: Additional context
Just some idea to make scheduling easier/faster and prevent overlapping of scheduled tasks. I already appreciate the app and its capabilities a lot and wanted to share some thoughts on some of the features. Hope it helps in moving the app forward and increase productivity with only minor changes.

**Comment by johannesjo** [comment]
Thank you very much for the detailed suggestion! I like it!  :) I'll PRs for implementing this.
