### ISSUE TITLE
Pomodoro timer display does not update

### ISSUE THREAD

**Issue by pixelious** [johannesjo/super-productivity#133]
* Version used: 2.0.1 (superProductivity-2.0.1.exe)
* Operating System and version: Win7

Settings/Pomodoro Settings

```json
"pomodoro":{"isEnabled":true,"duration":1500000,"breakDuration":300000,"longerBreakDuration":900000,"cyclesBeforeLongerBreak":4,"isStopTrackingOnBreak":true,"isStopTrackingOnLongBreak":true,"isManualContinue":true,"isPlaySound":false,"isPlayTick":false}
```

When starting to work on a task the timer display in the top right corner should start to count down.
Instead the initial time is displayed and does not get updated.

However the time spent on the task is updated correctly.

**Comment by johannesjo** [comment]
Thank you very much for reporting. I found the issue and will release a patch later today.

**Comment by johannesjo** [comment]
The new version is out. Please let me know if the issue persists.

**Comment by pixelious** [comment]
Does work now. Tested with 2.0.7.
Thank you very much!

**Comment by jeensg** [comment]
Got the same issue on linuxversion -- still on 2.0.1 (deb) -- can you update repo?
I got a couple of more bugs, but would like to try update 2.0.7 before reporting...

**Comment by johannesjo** [comment]
@jeensg the release should be out. You have to download it from the releases page. Due to reaching it's usage limits publishing debs to bintray is no more. As an alternative you could switch to the snap version.

**Comment by jeensg** [comment]
Thanks, will be using the release-page from now on. Is there a way to get informed on new releases?
btw: installing with snap, the xprintidle-package is missing (#92) too...

**Comment by johannesjo** [comment]
@jeensg unfortunately only the github page atm. A self updating app might be a feature for later though. I would have liked to continue using bintray, but its too much of a hassle and now I apparently would have to manually delete old releases to continue using it.

**Comment by jeensg** [comment]
yeah, I figured so, no problem, thanks for the work!
