### ISSUE TITLE
A calender integration within superproductivity

### ISSUE THREAD

**Issue by maitreyk** [johannesjo/super-productivity#1331]
I know a lot of people that want to switch to superproductivity but aren't able to do so because they don't have a visual reference for their future tasks. Now you could argue you have included this feature while scheduling a task but it is not modern looking, instead of showing the day, date, time, and the days left until you have to complete the scheduled task, you should integrate all these functions in a calendar type style. I have seen people heavily rely on that because they need to visually see on what date their task must be complete. It also helps them plan the day in a timely manner as their are time stamps. Please take apple calender for example, the way it functions is really intelligent. I and my friends will be glad to see the calendar feature and everything that comes with a calendar come to superproductivity, as this is my go-to application for uni work. Please don't confuse it and remove the scheduled section, I am just saying to add a calendar so that whatever is scheduled can be seen in a visually pleasing manner, as the normal day,date,time and number of days left is not modern looking, instead just integrate this in a calendar. 

I hope you understood my suggestion, me and my friends are eagerly waiting for this feature and have decided to make a github account to reach out to you and directly communicate out ideas to you. I know you are a busy person, a small confirmation about this feature will also help us a lot as we would not have to find alternatives, and would never like to because we really like superproductivity.

**Comment by johannesjo** [comment]
Hi there! Thank you very much for opening this up. I've been working on a calendar in the past and got pretty far with it, but found that the new timeline solves many things much better. Apart from fixed reoccurring events (those are supported with the timeline) and a handful of events, I find that planning more than a couple of days ahead rarely works anyway (though I understand that this might be different for different people).

And for calendar needs, a dedicated real calendar like google calendar or outlook works better in my opinion. What I have planned in the long run is to integrate different calendar providers for the timeline view, so it is possible to integrate your calendar of choice with the app.

**Comment by mitchellmorris** [comment]
I agree but I would like to see time entries as well in Apple Calendar.  Perhaps the most significant case for this IMHO is that power user like me latch on to the Apple Calendar to cross interface with other Apple apps.  The from there I can take all of the data and import it where I need.  

Also, maybe I'd like to report progress in real time( I don't but ), it would be cool to share my calendar and someone else be able to see where I am at.

Umm ... forgive me if the SP does this already.  I have no idea how CalDAV even works and every single mention of it is now starting give me anxiety.  All I have experienced with that SP says my settings are not valid but I am not see a username and password; I just copied the address. 

<img width="748" alt="image" src="https://user-images.githubusercontent.com/3805310/132107440-46470b2b-333b-47ad-87f9-ee47ec992c3a.png">

<img width="868" alt="image" src="https://user-images.githubusercontent.com/3805310/132107547-36074ae0-5527-4901-9eb9-1e62d1455286.png">
 
Also, thank-you for this super awesome solution and I am so thankful for your generosity sharing SP and I am grateful for all of the time you and other contributors have worked on edge cases to accommodate everyone else.

**Comment by johannesjo** [comment]
@mitchellmorris currently that's not possible. But I'm thinking about providing a calendar integration for the timeline view via ical (just showing them as a first step). Not sure if this would work with the apple calendar out of the box, but it might be a first step in that direction.

**Comment by sql-sith** [comment]
Including an iCal integration would be an awesome first step! If superProductivity allowed us to set alarms on those calendar events, I do believe I would fall over dead, just before jumping for joy. Among other platforms, iCal would allow all of us whose employers use Office 365 to see our calendars in the app - a big win for us, and maybe for SP too?
