### ISSUE TITLE
Top right play/pause button does not start/pause timer

### ISSUE THREAD

**Issue by pixelious** [johannesjo/super-productivity#134]
Version used: 2.0.1 (superProductivity-2.0.1.exe)
Operating System and version: Win7

The top right play/pause button does not start/pause the timer.
Starting the timer directly on a task does work and also toggles the global play/pause button.

**Comment by johannesjo** [comment]
Am I assuming correctly that this is only the case, when the pomodoro timer is activated?

**Comment by johannesjo** [comment]
The new version is out. Please let me know if the issue persists.

**Comment by pixelious** [comment]
Does work now. Tested with 2.0.7.
Thank you very much!
