### ISSUE TITLE
Repeatable tasks doesn't  show on Scheduled Section 

### ISSUE THREAD

**Issue by JLuisGT** [johannesjo/super-productivity#1341]
## Problem Statement
Repeatable tasks doesn't show on Scheduled Section automatically, I have to search them and add them to Today manually.

 ## :grey_question: Possible Solution
The corresponding days of the week, the task should appear in the Scheduled section

**Comment by johannesjo** [comment]
Thanks for the suggestion! Makes sense to me!

**Comment by JoseOlin** [comment]
Hi! I think this is indeed solved in the last versions! 
Thanks @johannesjo!

**Comment by johannesjo** [comment]
Not for the scheduled page, but personally I am almost never using it anyways these days :)

**Comment by JoseOlin** [comment]
Oh, I see.
Well, in the Today section it is enough for my needs.
