### ISSUE TITLE
[Feature] Pomodoro time reset

### ISSUE THREAD

**Issue by Acsigen** [johannesjo/super-productivity#135]
## Your Environment

* Version used: 2.04 deb 
* Operating System and version: Ubuntu 18.04 x64
* Desktop Environment:  Gnome 3.28.2
* Browser Name and version: 

## Expected Behavior

 I want to be able to reset the pomodoro timer. I work for some time on a task, I finish it and when I want to start another task, let's say an hour later, I want to be able to reset the pomodoro timer.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by johannesjo** [comment]
Thanks for opening up this issue. 

The feature should be out with the next release (should be out tomorrow morning). Let me know if it works out for you.
