### ISSUE TITLE
Pomodoro break time inverted

### ISSUE THREAD

**Issue by Acsigen** [johannesjo/super-productivity#136]
## Your Environment

* Version used: 2.04 deb
* Operating System and version: Ubuntu 18.04 x64
* Desktop Environment: Gnome 3.28.2 
* Browser Name and version: 

## Expected Behavior
After work time ended i should be prompted with a 5 minute break, the 4th break should be 15m long

## Current Behavior
With the values mentioned in "Steps to reproduce" the longer break is 5m and the short break is 15m

## Steps to Reproduce (for bugs)

1.Set short break time to 5m, long break time to 15m and set to start longer break after 4 sessions.

**Comment by johannesjo** [comment]
Thanks for reporting. It should hopefully be fixed with the next release (should be out tomorrow morning). Let me know if the fix worked for you.
