### ISSUE TITLE
Some weird translation in Chinese.

### ISSUE THREAD

**Issue by shincling** [johannesjo/super-productivity#1371]
### Discussed in https://github.com/johannesjo/super-productivity/discussions/1370

<div type='discussions-op-text'>

<sup>Originally posted by **shincling** July  8, 2021</sup>
Dear there, 
Recently, I began to use this awesome tool.
However, I found some translation is weird. 

Here I began to record some 

- https://github.com/johannesjo/super-productivity/blob/e4cd9a0662b0c8832f4577cab49d11ee8a94e047/src/assets/i18n/zh.json#L651
in chinse, we call the "parent (task)" as " 父（任务）" or " 上级（任务）”, so I recommend to use " 父任务“ here or a better option may be "上级“ .
BTW, the translation in https://github.com/johannesjo/super-productivity/blob/e4cd9a0662b0c8832f4577cab49d11ee8a94e047/src/assets/i18n/zh.json#L648 is reasonable.

- https://github.com/johannesjo/super-productivity/blob/e4cd9a0662b0c8832f4577cab49d11ee8a94e047/src/assets/i18n/zh.json#L1233
Actually, I feel the term "finish day" is hard to understand, especially after translating.  
I think "finish today" or " finish this day" maybe better? 

- https://github.com/johannesjo/super-productivity/blob/e4cd9a0662b0c8832f4577cab49d11ee8a94e047/src/assets/i18n/zh.json#L1186
"隐私策略“ is commonly used for "privacy policy".

- https://github.com/johannesjo/super-productivity/blob/e4cd9a0662b0c8832f4577cab49d11ee8a94e047/src/assets/i18n/zh.json#L1174
"导出项目” is much better.

Not fully checked, maybe will update later when I encounter it.

BTW, If you agree, I could help to make the PR.

Thanks again for this effective toolkit.</div>

**Comment by johannesjo** [comment]
Hey there! Thank you very much for checking this. I speak any Chinese (and need to rely on google translate) so a PR would be very welcome indeed!

**Comment by shincling** [comment]
I see, Johannes. I will check more, hope to send the PR this week.
