### ISSUE TITLE
[Feature] Notification sound when break ends

### ISSUE THREAD

**Issue by Acsigen** [johannesjo/super-productivity#138]
## Your Environment

* Version used: 2.04 deb 
* Operating System and version: Ubuntu 18.04 x64
* Desktop Environment: Gnome 3.28.2 
* Browser Name and version: 

## Expected Behavior
When the break ends it should play a sound just in case I am not near the computer so I know that the break is over, just like it does when the break starts.

## Current Behavior
Now, the sound is available only when the break starts.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by johannesjo** [comment]
Thanks for the suggestion. Makes probably sense to have this feature.

**Comment by Acsigen** [comment]
It still doesn't play a sound when the break ends (manually confirm starting next pomodoro session is checked). It plays only when the "Go back to work" or "Cancel" button is pressed.

**Comment by johannesjo** [comment]
Sorry, your reply somehow went under my radar. I will check this as soon as I can.

**Comment by johannesjo** [comment]
I just checked, and it seems to work fine. Could you check again? Maybe the settings weren't saved or something?

**Comment by Acsigen** [comment]
I am now on Windows 10 x64 with the latest version of the app and the problem is that the sound doesn't play if I have "Manually confirm starting next pomodoro session" enabled. When the option is disabled the so
und is actually from the pomodoro session start. I have attached a screenshot with my settings. This is available for web version too.
![ss 2019-03-05 191953](https://user-images.githubusercontent.com/13287878/53824058-c4fdb780-3f7b-11e9-8deb-ed39fab1f6b6.jpg)

**Comment by johannesjo** [comment]
I finally got it. The sound plays, but the session is only considered to be done, once you start working on the next session. Arguably not ideal. I try to think of something.

**Comment by johannesjo** [comment]
Should be fixed with the next release.
