### ISSUE TITLE
Due tasks popup improvementes

### ISSUE THREAD

**Issue by JoseOlin** [johannesjo/super-productivity#1380]
## Problem Statement

The **due tasks popup could have some improvements**, for example:

- In addition to the current three options (Dismiss, Snooze, and Add to Today), you might have a "**Mark as done" option**. Sometimes I finish a task and forget to mark it as finished, and it would be convenient to mark it in the popup instead of having to close it and go to the Today section.

- It would be more useful (in my case) if the **Snooze drop down had more options** (2 hours, 3 hours, 4 hours); since I usually schedule a day before and by default many tasks take their reminder at 9 AM.

- Sometimes, **tasks that you are already working on and tracking appears on the Due task popup**.
   + **Expected behavior**: The task that you are working on should not appear on the Due tasks popup.

- It would be useful if the Snooze button displayed a secondary popup window with today's Timeline, which would **allow assigning a time considering the currently scheduled tasks** OR if we had more options in the Timeline section to easily modify the time (as in the popup due task). 

As always, thanks in advance for this amazing app and the incredible developer support.

**Comment by johannesjo** [comment]
Thank you very much for opening this up. I generally agree that the dialog needs to be improved.

> It would be useful if the Snooze button displayed a secondary popup window with today's Timeline, which would allow assigning a time considering the currently scheduled tasks OR if we had more options in the Timeline section to easily modify the time (as in the popup due task).

This is a really nice suggestion.

**Comment by JoseOlin** [comment]
Still relevant, in my opinion.

Especially having some way to estimate the number of tasks in a day before scheduling another task for that day. It can be as simple as showing the **number of scheduled tasks on mouse over** or as elaborate as **showing the Timeline of that particular day on mouse over**, as a popup, which would also allow you to see what schedules are available.

In the case of the options for snooze, perhaps it would be enough that the **stepsize of the mouse scroll being 5 minutes** (always multiples of 5) and if you want more precision to click the arrows.

Getting **reminded of a completed task still happens to me from time to time**, so being able to mark it as done in the due task popup still seems relevant.

To avoid the reminder of the task in progress, what I do as a workaround is remove the reminder once I start the Pomodoro, so **maybe that particular one is no longer relevant**.

**Comment by JoseOlin** [comment]
Still relevant ;) IMHO
