### ISSUE TITLE
add new task directly after currently running task

### ISSUE THREAD

**Issue by gotjoshua** [johannesjo/super-productivity#1382]
## Problem Statement
if a task is running, then the toggle that was added for #1221  should choose between 
just after the current task and the bottom. (not the top and bottom as it does now)

## :grey_question: Possible Solutions
1. pass in the current running task to addTask
2. somehow gain access to another part in the state tree or the task service to check if there is a currently running task in the current context
3. duplicate or move the currentTaskId prop into the part of the state tree

## :heavy_plus_sign: Additional context
[This is a follow up](https://github.com/johannesjo/super-productivity/issues/1221#issuecomment-878195943), and a "nice to have" priority C enhancement.

**Comment by johannesjo** [comment]
Thank you for opening this up. As discussed, I am not a 100% sure that should be always the default behavior, though I am open for trying this out or providing it as an optional feature.

**Comment by gotjoshua** [comment]
just didn't want it to get lost...
lets see...
