### ISSUE TITLE
basic settings for tags open by default

### ISSUE THREAD

**Issue by gotjoshua** [johannesjo/super-productivity#1383]
## Problem Statement
both collapsibles are closed when one clicks to edit a tag

## :grey_question: Possible Solution
isExpanded true by default

**Comment by johannesjo** [comment]
Thanks for opening this up! I am for this particular change, but making isExpanded a default, would affect every config-section, so we rather might add something like `@Attribute expandedInitially` or `@Input isExpandedInitally` and apply that in the tag-setting-page.component.

https://stackoverflow.com/questions/48047767/how-angulars-attribute-decorator-works
https://angular.io/guide/inputs-outputs

**Comment by gotjoshua** [comment]
> might add something like `@Attribute expandedInitially` or `@Input isExpandedInitally` and apply that in the tag-setting-page.component.

sounds good to me!

i don't have extra bandwidth at the moment, but seems like a good strategy
