### ISSUE TITLE
Linking visual information to a task is a bit clunky

### ISSUE THREAD

**Issue by RobertoJBeltran** [johannesjo/super-productivity#1384]
I would like to be able to take a picture of a sketch or an inspiration in the real world and associate it with a task.

Ideally this would work on the mobile app. Maybe there could be an option to take a picture and that just opens the default camera app and links the new picture automatically somehow. I think reducing the friction here would make the app much more enjoyable

I'm seeing that you can link an image on desktop with the path. Maybe adding a file picker would be easier? Then at least you can use something like cheese and then pick the file

**Comment by johannesjo** [comment]
Hi there! Thanks for the suggestion. Makes sense to me, to add something like this. PRs are welcome!

**Comment by pmmontanari** [comment]
Was searching for this, for use on mobile. Taking pictures and inserting as attachment would be great.
