### ISSUE TITLE
Add Day pane from left side

### ISSUE THREAD

**Issue by jackuars89** [johannesjo/super-productivity#1389]
I have a lot of tasks to do on a day by day basis, however all tasks are only categorized by today. Can you please add a 'Day' pane on the left sidebar (e.g. Mon, Tue, Wed, Thu, Fri), so I can see what are the tasks that are coming up requiring my attention for the coming days.

**Comment by johannesjo** [comment]
Hey there! Thanks for opening this up. You can do this yourself by creating tags for each day. You can also use the shortsyntax to do so e.g.: `my task for #mo`.
