### ISSUE TITLE
Bug of estimate time with Sub-tasks

### ISSUE THREAD

**Issue by Kl4tch** [johannesjo/super-productivity#139]
Environment
* Version used: 2.0.7
* Desktop Environment: Linux Manjaro + Windows

## Expected Behavior
General Estimate time should't change after drag tasks. 

## Current Behavior
https://youtu.be/A3D7mmMVp-c

## Steps to Reproduce 
1. Create 1 simple task, and 1 task with sub-task(-s)
2. Set time to each task
3. Drag tasks

**Comment by johannesjo** [comment]
Thank you very much for reporting. I will check this as soon as I can.

**Comment by johannesjo** [comment]
Should be fixed with the new version. Thanks again-
