### ISSUE TITLE
Desktop app spins on jira sync to backlog with basic auth

### ISSUE THREAD

**Issue by aron425** [johannesjo/super-productivity#1393]
### Your Environment

Using latest release 7.3.3 on windows 10 pro 

### Expected Behavior

Adding jira defects to backlog using jql working

### Current Behavior
After testing credentials work in jira setup I verify the JQL query for the issues to sync to backlog works in JIRA and there are only 5 returned in the response.  However super pro just spins indefinitely when it is trying to pull remote data.  I can't tell what is going on from server side no access.

### Steps to Reproduce (for bugs)
1. set up basic auth for jira
2. verify test connection works
3. verify jql for backlog works on jira 
4. wait for app to sync with jira, observe spinning

JIRA_POLL_BACKLOG_CHANGES
jira-issue-map.util.ts:46 Uncaught TypeError: Cannot read property 'map' of undefined
    at Object.XR [as transform] (jira-issue-map.util.ts:46)
    at t._handleResponse (jira-api.service.ts:582)
    at EventEmitter.<anonymous> (jira-api.service.ts:103)
    at EventEmitter.emit (events.js:315)
    at Object.onMessage (electron/js2c/renderer_init.js:93)

### Error Log (Desktop only)

I don't have this ->  %USERPROFILE%\AppData\Roaming\superProductivity\logs\main.log

. -->

**Comment by johannesjo** [comment]
Hey there! Thanks for reporting! Looks like the response provided from the server doesn't match with what should be there. I improved the handling of the case and added some additional logging. Maybe you can try again with those changes, so we can dig a little deeper.

**Comment by aron425** [comment]
Ok it does bubble up the new error code you added briefly then is still spins on "loading remote data"

Same thing is in the network tab about cannot read property "map".  

This JIRA instance is one that my org may have modified with the help of atlassian for their needs so it may not be a vanilla response but the jql does work when I try it on the server.  Here is the footer on the UI
Atlassian Jira Project Management Software (v8.13.6#813006-sha1:c80b532:jira1n2prd)  About Jira  Report a problem



there's a main.log this all there is
[2021-07-21 15:14:11.689] [info]  { enabled: null, showDevTools: false, mode: 'bottom' }
[2021-07-21 15:14:12.614] [info]  Saving backups to C:\Users\A_Colichia\AppData\Roaming\superProductivity/backups
[2021-07-21 15:14:41.644] [info]  { enabled: null, showDevTools: false, mode: 'bottom' }
[2021-07-21 15:14:41.954] [info]  Saving backups to C:\Users\A_Colichia\AppData\Roaming\superProductivity/backups
[2021-07-21 15:14:43.346] [info]  No custom styles detected at C:\Users\A_Colichia\AppData\Roaming\superProductivity/styles.css

**Comment by johannesjo** [comment]
How does the actual response look like? You should be able to check it through the network tab.

If the response is really different from what it should be, than there is not much we can do on Super Productivity's side of things.

**Comment by aron425** [comment]
Sure, is there a way to stop / start the sync?  It seems to happen in the background I want to make sure I get the network log before it sends the request

**Comment by aron425** [comment]
There's nothing showing up in network activity actually

Here is what is on the console


﻿
electron/js2c/renderer_init.js:13 (electron) The remote module is deprecated. Use https://github.com/electron/remote instead.
task.reducer.ts:91 @ngrx/store/update-reducers 
Object
task.reducer.ts:91 @ngrx/effects/init 
Object
task.reducer.ts:91 @ngrx/store/update-reducers 
Object
app.component.ts:287 Persistence already allowed
app.component.ts:316 0 out of 358071 MiB used (0%)
zone.js:2561 13:21:00.075 › No custom styles detected at OMIT
model-version.ts:34 Migrating model "GlobalConfig" to version from undefined to 2.2003 
Object
model-version.ts:34 Migrating model "Improvement" to version from undefined to 1 
Object
model-version.ts:34 Migrating model "Obstruction" to version from undefined to 1 
Object
model-version.ts:34 Migrating model "Task Archive" to version from undefined to 3.3337 
Object
model-version.ts:34 Migrating model "TaskRepeat" to version from undefined to 1.1 
Object
model-version.ts:34 Migrating model "GlobalConfig" to version from undefined to 2.2003 
Object
model-version.ts:34 Migrating model "Improvement" to version from undefined to 1 
Object
model-version.ts:34 Migrating model "Obstruction" to version from undefined to 1 
Object
model-version.ts:34 Migrating model "Task Archive" to version from undefined to 3.3337 
Object
model-version.ts:34 Migrating model "TaskRepeat" to version from undefined to 1.1 
Object
is-valid-app-data.util.ts:42 
Object
model-version.ts:34 Migrating model "Tag" to version from undefined to 1 
Object
model-version.ts:34 Migrating model "SimpleCounter" to version from undefined to 2 
Object
task.reducer.ts:91 [SP_ALL] Load(import) all data 
Object
task.reducer.ts:91 [SP_ALL] All Data was loaded 
Object
migrate-metric.service.ts:37 Migrating Legacy Metric State to new model
migrate-metric.service.ts:38 metricMigration: 1 
Object
task.reducer.ts:91 [WorkContext] Set Active Work Context 
{activeId: "_P-K26zEE", activeType: "PROJECT", type: "[WorkContext] Set Active Work Context"}
task.reducer.ts:91 [Task] SetSelectedTask 
{id: null}
task.reducer.ts:91 [Note] Load Note State 
{state: {…}, type: "[Note] Load Note State"}
task.reducer.ts:91 [Bookmark] Load Bookmark State 
{state: {…}}
task.reducer.ts:91 [Project] Load Project related Data Success 
{projectId: "_P-K26zEE"}
task.reducer.ts:91 [Improvement] Clear Hidden Improvements 
Vm {type: "[Improvement] Clear Hidden Improvements"}
task.reducer.ts:91 [Improvement] Delete multiple Improvements 
{ids: Array(0)}
jira-issue.effects.ts:296 JIRA_POLL_BACKLOG_CHANGES
jira-api.service.ts:586 
{response: {…}, requestId: "search__POST__alIOEi2rB"}
jira-api.service.ts:587 
{requestInit: {…}, jiraCfg: {…}, transform: ƒ, resolve: ƒ, reject: ƒ, …}
jira-api.service.ts:588 TypeError: Cannot read property 'map' of undefined
    at Object.rF [as transform] (jira-issue-map.util.ts:46)
    at t._handleResponse (jira-api.service.ts:584)
    at EventEmitter.<anonymous> (jira-api.service.ts:103)
    at EventEmitter.emit (events.js:315)
    at Object.onMessage (electron/js2c/renderer_init.js:93)
﻿
​

**Comment by johannesjo** [comment]
Could you expand what is given under `{response: {…}, requestId: "search__POST__alIOEi2rB"}` ?

**Comment by aron425** [comment]
Here's more expanded


﻿
electron/js2c/renderer_init.js:13 (electron) The remote module is deprecated. Use https://github.com/electron/remote instead.
task.reducer.ts:91 @ngrx/store/update-reducers 
Object
task.reducer.ts:91 @ngrx/effects/init 
Object
task.reducer.ts:91 @ngrx/store/update-reducers 
Object
app.component.ts:287 Persistence already allowed
app.component.ts:316 0 out of 358056 MiB used (0%)
NO
model-version.ts:34 Migrating model "GlobalConfig" to version from undefined to 2.2003 
Object
model-version.ts:34 Migrating model "Improvement" to version from undefined to 1 
Object
model-version.ts:34 Migrating model "Obstruction" to version from undefined to 1 
Object
model-version.ts:34 Migrating model "Task Archive" to version from undefined to 3.3337 
Object
model-version.ts:34 Migrating model "TaskRepeat" to version from undefined to 1.1 
Object
model-version.ts:34 Migrating model "GlobalConfig" to version from undefined to 2.2003 
Object
model-version.ts:34 Migrating model "Improvement" to version from undefined to 1 
Object
model-version.ts:34 Migrating model "Obstruction" to version from undefined to 1 
Object
model-version.ts:34 Migrating model "Task Archive" to version from undefined to 3.3337 
Object
model-version.ts:34 Migrating model "TaskRepeat" to version from undefined to 1.1 
Object
is-valid-app-data.util.ts:42 
Object
d:
bookmark: {DEFAULT: undefined, _P-K26zEE: undefined}
globalConfig: {lang: {…}, misc: {…}, evaluation: {…}, idle: {…}, takeABreak: {…}, …}
improvement: {ids: Array(0), entities: {…}, hideDay: null, hiddenImprovementBannerItems: Array(0), __modelVersion: 1}
lastActiveTime: 1626898792717
lastLocalSyncModelChange: 1626898792717
metric: {ids: Array(0), entities: {…}, __modelVersion: 1}
note: {DEFAULT: undefined, _P-K26zEE: undefined}
obstruction: {ids: Array(0), entities: {…}, __modelVersion: 1}
project: {ids: Array(2), entities: {…}, __modelVersion: 5.2}
reminders: []
simpleCounter: {ids: Array(2), entities: {…}}
tag: {ids: Array(1), entities: {…}}
task: {ids: Array(0), entities: {…}, currentTaskId: null, selectedTaskId: null, taskAdditionalInfoTargetPanel: null, …}
taskArchive: {ids: Array(0), entities: {…}, __modelVersion: 3.3337}
taskRepeatCfg: {ids: Array(0), entities: {…}, __modelVersion: 1.1}
__proto__: Object
isValid: true
__proto__:
constructor: ƒ Object()
hasOwnProperty: ƒ hasOwnProperty()
isPrototypeOf: ƒ isPrototypeOf()
propertyIsEnumerable: ƒ propertyIsEnumerable()
toLocaleString: ƒ toLocaleString()
toString: ƒ ()
valueOf: ƒ valueOf()
__defineGetter__: ƒ __defineGetter__()
__defineSetter__: ƒ __defineSetter__()
__lookupGetter__: ƒ __lookupGetter__()
__lookupSetter__: ƒ __lookupSetter__()
get __proto__: ƒ __proto__()
set __proto__: ƒ __proto__()
model-version.ts:34 Migrating model "Tag" to version from undefined to 1 
Object
model-version.ts:34 Migrating model "SimpleCounter" to version from undefined to 2 
Object
task.reducer.ts:91 [SP_ALL] Load(import) all data 
Object
task.reducer.ts:91 [SP_ALL] All Data was loaded 
Object
migrate-metric.service.ts:37 Migrating Legacy Metric State to new model
migrate-metric.service.ts:38 metricMigration: 1 
Object
task.reducer.ts:91 [WorkContext] Set Active Work Context 
{activeId: "_P-K26zEE", activeType: "PROJECT", type: "[WorkContext] Set Active Work Context"}
activeId: "_P-K26zEE"
activeType: "PROJECT"
type: "[WorkContext] Set Active Work Context"
__proto__:
constructor: ƒ Object()
arguments: (...)
assign: ƒ assign()
caller: (...)
create: ƒ create()
defineProperties: ƒ defineProperties()
defineProperty: ƒ defineProperty()
entries: ƒ entries()
freeze: ƒ freeze()
fromEntries: ƒ fromEntries()
getOwnPropertyDescriptor: ƒ getOwnPropertyDescriptor()
getOwnPropertyDescriptors: ƒ getOwnPropertyDescriptors()
getOwnPropertyNames: ƒ getOwnPropertyNames()
getOwnPropertySymbols: ƒ getOwnPropertySymbols()
getPrototypeOf: ƒ getPrototypeOf()
is: ƒ is()
isExtensible: ƒ isExtensible()
isFrozen: ƒ isFrozen()
isSealed: ƒ isSealed()
keys: ƒ keys()
length: 1
name: "Object"
preventExtensions: ƒ preventExtensions()
prototype: {constructor: ƒ, __defineGetter__: ƒ, __defineSetter__: ƒ, hasOwnProperty: ƒ, __lookupGetter__: ƒ, …}
seal: ƒ seal()
setPrototypeOf: ƒ setPrototypeOf()
values: ƒ values()
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
hasOwnProperty: ƒ hasOwnProperty()
arguments: (...)
caller: (...)
length: 1
name: "hasOwnProperty"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
isPrototypeOf: ƒ isPrototypeOf()
arguments: (...)
caller: (...)
length: 1
name: "isPrototypeOf"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
propertyIsEnumerable: ƒ propertyIsEnumerable()
arguments: (...)
caller: (...)
length: 1
name: "propertyIsEnumerable"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
toLocaleString: ƒ toLocaleString()
arguments: (...)
caller: (...)
length: 0
name: "toLocaleString"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
toString: ƒ ()
valueOf: ƒ valueOf()
arguments: (...)
caller: (...)
length: 0
name: "valueOf"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
__defineGetter__: ƒ __defineGetter__()
arguments: (...)
caller: (...)
length: 2
name: "__defineGetter__"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
__defineSetter__: ƒ __defineSetter__()
arguments: (...)
caller: (...)
length: 2
name: "__defineSetter__"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
__lookupGetter__: ƒ __lookupGetter__()
arguments: (...)
caller: (...)
length: 1
name: "__lookupGetter__"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
__lookupSetter__: ƒ __lookupSetter__()
arguments: (...)
caller: (...)
length: 1
name: "__lookupSetter__"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
get __proto__: ƒ __proto__()
arguments: (...)
caller: (...)
length: 0
name: "get __proto__"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
set __proto__: ƒ __proto__()
arguments: (...)
caller: (...)
length: 1
name: "set __proto__"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
task.reducer.ts:91 [Task] SetSelectedTask 
{id: null}
id: null
__proto__: Object
task.reducer.ts:91 [Note] Load Note State 
{state: {…}, type: "[Note] Load Note State"}
state:
entities: {}
ids: []
__proto__: Object
type: "[Note] Load Note State"
__proto__:
constructor: ƒ Object()
hasOwnProperty: ƒ hasOwnProperty()
isPrototypeOf: ƒ isPrototypeOf()
propertyIsEnumerable: ƒ propertyIsEnumerable()
toLocaleString: ƒ toLocaleString()
toString: ƒ ()
valueOf: ƒ valueOf()
__defineGetter__: ƒ __defineGetter__()
__defineSetter__: ƒ __defineSetter__()
__lookupGetter__: ƒ __lookupGetter__()
__lookupSetter__: ƒ __lookupSetter__()
get __proto__: ƒ __proto__()
set __proto__: ƒ __proto__()
task.reducer.ts:91 [Bookmark] Load Bookmark State 
{state: {…}}
task.reducer.ts:91 [Project] Load Project related Data Success 
{projectId: "_P-K26zEE"}
task.reducer.ts:91 [Improvement] Clear Hidden Improvements 
Vm {type: "[Improvement] Clear Hidden Improvements"}
task.reducer.ts:91 [Improvement] Delete multiple Improvements 
{ids: Array(0)}
jira-issue.effects.ts:296 JIRA_POLL_BACKLOG_CHANGES
jira-api.service.ts:586 
{response: {…}, requestId: "search__POST__CbQ7NiO0o"}
requestId: "search__POST__CbQ7NiO0o"
response:
__proto__:
constructor: ƒ Object()
hasOwnProperty: ƒ hasOwnProperty()
isPrototypeOf: ƒ isPrototypeOf()
propertyIsEnumerable: ƒ propertyIsEnumerable()
toLocaleString: ƒ toLocaleString()
toString: ƒ ()
valueOf: ƒ valueOf()
__defineGetter__: ƒ __defineGetter__()
__defineSetter__: ƒ __defineSetter__()
__lookupGetter__: ƒ __lookupGetter__()
__lookupSetter__: ƒ __lookupSetter__()
get __proto__: ƒ __proto__()
set __proto__: ƒ __proto__()
__proto__:
constructor: ƒ Object()
hasOwnProperty: ƒ hasOwnProperty()
isPrototypeOf: ƒ isPrototypeOf()
propertyIsEnumerable: ƒ propertyIsEnumerable()
toLocaleString: ƒ toLocaleString()
toString: ƒ ()
valueOf: ƒ valueOf()
__defineGetter__: ƒ __defineGetter__()
__defineSetter__: ƒ __defineSetter__()
__lookupGetter__: ƒ __lookupGetter__()
__lookupSetter__: ƒ __lookupSetter__()
get __proto__: ƒ __proto__()
set __proto__: ƒ __proto__()
a-api.service.ts:587 
{requestInit: {…}, jiraCfg: {…}, transform: ƒ, resolve: ƒ, reject: ƒ, …}
jiraCfg: {isEnabled: true, _isBlockAccess: false, host: "no", userName: "NO", password: "NO", …}
reject: n=>{try{Z(e,t,n)}catch(o){Z(e,!1,o)}}
requestInit: {method: "POST", body: "{\"maxResults\":100,\"fields\":[\"assignee\",\"summary\",\"…nt in openSprints() AND resolution = Unresolved\"}", headers: {…}}
resolve: n=>{try{Z(e,t,n)}catch(o){Z(e,!1,o)}}
timeoutId: 129
transform: (t,e)=>t.response.issues.map(t=>aF(t,e))
__proto__: Object
jira-api.service.ts:588 TypeError: Cannot read property 'map' of undefined
    at Object.rF [as transform] (jira-issue-map.util.ts:46)
    at t._handleResponse (jira-api.service.ts:584)
    at EventEmitter.<anonymous> (jira-api.service.ts:103)
    at EventEmitter.emit (events.js:315)
    at Object.onMessage (electron/js2c/renderer_init.js:93)
