### ISSUE TITLE
Jira request failed: searchJira - [object Object]

### ISSUE THREAD

**Issue by guthab** [johannesjo/super-productivity#14]
I get this failure message after entering the Jira host URL, credentials and JQL.
The JQL is checked to be correct, so the only unclear point is whether the URL is entered and handled correctly ..?

      Host/Base URL:  **https://jira.xxxx.yyy:8443**

![screen shot 11-07-17 at 04 07 pm](https://user-images.githubusercontent.com/31131749/32498161-8a711e7a-c3d7-11e7-8448-5e80de0dd582.PNG)

**Comment by johannesjo** [comment]
Hello! Thanks for reporting the issue! Can you try opening the console (Ctrl+Shift+J) and click the "Test Credentials" Button again and see if there is some additional information to be gathered?

**Comment by guthab** [comment]
Hi and thanks for the prompt response. Yes, I'm on Windows. I repeated the test and saved the console log - does it help?
[-1510074180507.log](https://github.com/johannesjo/super-productivity/files/1450951/-1510074180507.log)

**Comment by johannesjo** [comment]
Thanks for the log file!

The issue seems to be that your jira server has a missing CA. I modified the app to allow such requests. Could you please check if it works for you with the latest release?

**Comment by guthab** [comment]
Works now - thanks!!
