### ISSUE TITLE
Minimize to tray doesn't work

### ISSUE THREAD

**Issue by jeensg** [johannesjo/super-productivity#140]
## Your Environment
* Version used: 2.0.7
* Operating System and version: Ubuntu 18.10 cosmic
* Desktop Environment: xubuntu-xfce
* Browser Name and version: 

## Expected Behavior
If closing program, it should minimize to tray. (option in misc-settings is enabled)

## Current Behavior
Program wants to close, asking for it -- option "Confirm before exiting the app" is checked and works

## Steps to Reproduce (for bugs)
1. install
2. go to settings, misc settings, check box "Minimize to tray instead of closing"
3. close program

## Console Output
Unfortunately not, Ctrl+Shift+J brings error: "TypeError: Cannot read property 'send' of undefined"

**Comment by johannesjo** [comment]
Thanks for opening up this issue. The feature has been removed. As an alternative, you can display a confirm dialog when closing the app.

**Comment by jeensg** [comment]
Oh, ok. If so, could you also:
- remove the tray icon
- remove the option in misc-settings?

The confirm-dialog I found, thanks.

**Comment by yamac-kurtulus** [comment]
Why was this removed? Just curious, I am looking for and experimenting with different productivity apps, and minimizing to tray is one of the main features for me, if it is due to a bug or something, could it be re-enabled again in the future? It's a shame, I liked this one.

**Comment by johannesjo** [comment]
@yamac-kurtulus I am open for re-adding this again. What makes it a bit tricky is that the handling needs to be different for all OS. Would you like to give it a go yourself?

**Comment by yamac-kurtulus** [comment]
@johannesjo I was thinking about it, if I can ever find any time these days. Then again I am not that familiar with js or ts :/ 

But I see your concerns, different OSes requiring different handlings.

**Comment by johannesjo** [comment]
In the first iteration of the app this also was a must have feature for me, but working with the app through the years I found that it was not adding much to my experience. Maybe you find the same to be true ;)

**Comment by yamac-kurtulus** [comment]
Maybe :) 

But I am mostly working with Windows these days, and I can imagine it could be tolerable on Mac or Linux, whose default concepts like workspaces could get rid of the taskbar icons. On Windows though, that's just too many taskbar icons man :D

**Comment by johannesjo** [comment]
Hehe. I understand... Maybe we can just re-introduce it for windows again?

**Comment by yamac-kurtulus** [comment]
That would be terrific, although are you sure you are open to features diverging among OSes?

I will try to take a look if I can find the chance. Would be a good chance to brush up on my js :)

**Comment by johannesjo** [comment]
I am! As you say: It's very different for mac and linux where the concept of minimize to tray is very rarely used, if  at all.
