### ISSUE TITLE
Change default directory for portable version

### ISSUE THREAD

**Issue by reelism** [johannesjo/super-productivity#1402]
## Problem Statement

It seems intended to be Portable, but there's no clear way to install it as. 

## :grey_question: Possible Solution

Ensure it's portable as either default, or add a setting to have it only create/refer to content in it's own dir.

> @johannesjo 
> 
> Probably makes sense to:
> 
> 1. Check whether the app is build as portable version
> 2. Then use a sub folder where the exe is stored, as default data folder.

**Comment by johannesjo** [comment]
You can specify the `--user-data-dir=xyz` param, when starting the app. Haven't been on windows in a while. Where do other portable apps store their data? Just in the same folder as the executable?

**Comment by reelism** [comment]
Yes, exactly.

I'm working with Ferdi portable right now, it sits: D:\MyApps\Ferdi\Ferdi-5.8.0.exe
App dir:  D:\MyApps\Ferdi\FerdiAppData

**Comment by johannesjo** [comment]
Alright! Thank you. PR's for this would be welcome!

**Comment by sakibarifin** [comment]
Any progress on making this app portable?
