### ISSUE TITLE
Google Drive Sync Error on initial setup

### ISSUE THREAD

**Issue by DoraTrix** [johannesjo/super-productivity#1405]
Just fresh installed 7.3.3 (never before used).  Tried to set up the sync settings, go through the auth process for GDrive, get the auth code, paste it into the app, then get this message -

Google Drive: Error while creating Sync file.  Token creation failed

System is Windows 10 Pro, build: 19042.1110

I am able to access Drive normally through the website.

**Comment by aripollak** [comment]
I ran into the same issue. I tried setting up sync from a browser, and realized it failed because I have Advanced Protection enabled on my Google account:

> Error 400: policy_enforced
> Advanced Protection prevented your Google Account from signing in. This security feature stops most non-Google apps and services from accessing your data to keep your account protected.

Maybe this could be fixed by switching to the app-specific data API? https://developers.google.com/drive/api/v3/appdata

**Comment by aripollak** [comment]
Oops, nevermind, this is a different issue with the desktop app that happens with another account without Advanced Protection too.

**Comment by DoraTrix** [comment]
Yep, this does seem like a dup of #1394, I'll try the 7.5.0 rc and close this if it works.
