### ISSUE TITLE
can't open console

### ISSUE THREAD

**Issue by jeensg** [johannesjo/super-productivity#141]
## Your Environment
* Version used: 2.0.7 deb
* Operating System and version: Ubunto 18.10
* Desktop Environment: xubuntu - xfce

## Expected Behavior
console can be opened

## Current Behavior
Console can't be opened.

## Steps to Reproduce (for bugs)
1. open program
2. press Ctrl+Shift+J
3. error: TypeError: Cannot read property 'send' of undefined

**Comment by johannesjo** [comment]
I forgot to document this somewhere. The console shortcut changed to Ctrl+Shift+i
