### ISSUE TITLE
jira-integration doesn't work properly

### ISSUE THREAD

**Issue by jeensg** [johannesjo/super-productivity#142]
## Your Environment
    * Version used: 2.0.7 deb
    * Operating System and version: Ubunto 18.10
    * Desktop Environment: xubuntu - xfce

## Expected Behavior
jira-integration works properly

## Current Behavior
it's hard to tell where the bottleneck is, some issues from jira appear, but the testing-ones assigned to me do not. When looking for one issue that I created for testing (HRS-41) the searching-bar appears but never stops working. When deleting certain letters again, it finds some of the issues, but not the ones assigned to my account nor the ones I'm looking for.

![bildschirmfoto_2019-02-08_21-42-35](https://user-images.githubusercontent.com/24763877/52505484-ecb36700-2beb-11e9-8c06-55cb69057014.png)

When I "+" an issue from jira (just picking randomly one, that is listed) it doesn't seem to be loaded, only sometimes with good luck ... often nothing happens after clicking on it.

When adding one issues from jira (if it's actually added), it only works after like 2-5 minutes correctly, meanwhile it doesn't show the content as shown in the screenshot.

![bildschirmfoto_2019-02-08_21-36-23](https://user-images.githubusercontent.com/24763877/52505485-ecb36700-2beb-11e9-98c0-e180a62d7f49.png)
The mentioned issues imported from jira was also already done, so it shouldn't be visible!?

How do I import all the issues? Or is it meant to be knowing the names of the issues? I didn't find a howto in order to check what should be possible.

## Steps to Reproduce (for bugs)
1. create api token
2. add jira-integration for a test-project
3. search for issues from jira

## Console Output
Console doesn't work right now unfortunately...

**Comment by johannesjo** [comment]
Hey thanks for opening up this issue. I need to dig a little deeper into this. There definitely seem to be some issues with the material autocomplete. What works for me is, that press the down arrow on my keyboard after a short while. The list is then updated. There is a half fix for this on the way. So hang on.

Also: The console shortcut changed to Ctrl+Shift+i ('Cmd+Alt+I' for mac)

**Comment by jeensg** [comment]
Ok, now I see it -- I can't search for numbers (e.g. there is an issue with number HRS-41, but it's not found by that number but with the actual name -- test superproductivity). That still now helps a lot.

Is there a way to directly see all the issues from jira, that are assigned to me with that account? I can check all the tickets from all the members, but that's too much if I do not know which are assigned directly to me...

**Comment by jeensg** [comment]
After starting a chosen jira-ticket, I cannot stop the time ... nore can mark it as done ... but time of the pomodoro keeps going. Can also not change project (which before stopped the pomodoro-time and counting of present task).

**Comment by jeensg** [comment]
Oh, and when choosing a kira-ticket and then click on the jira-link, after logging in there is the following message:
Oops, you've made a malformed request.
Often, clearing your browsers cache and restarting your browser will solve this problem.
If that doesn't work, please contact support.

**Comment by jeensg** [comment]
Well, found some more. Shall I open for every bug a ticket and tag it to jira?
(when I start now an issue from jira, pomodoro starts, but whole program crashes, can't do anything anymore and below there is an error: "Jira: something went wrong")

**Comment by johannesjo** [comment]
In general opening up a new ticket is the safe choice. This way others could see, if there is already a solution. And it's easier for Google to find that too.

**Comment by johannesjo** [comment]
> Is there a way to directly see all the issues from jira, that are assigned to me with that account?

What you can do is to automatically import all issues that are assigned to you. The default JQL works fine for me (`assignee = currentUser() AND sprint in openSprints() AND resolution = Unresolved ORDER BY updatedDate DESC`) but you can also change it to:
`assignee = currentUser()` to get _all_ issues assigned to you.

**Comment by johannesjo** [comment]
Am I assuming correctly that you have 3 different issues?

1. The search not working with issue keys
2. Some kind of error which breaks the app completely (I would need a little bit more info to fix this one)
3. And maybe related to 2 a request error (maybe a config issue, would need some more details about the error).

**Comment by jeensg** [comment]
> > Is there a way to directly see all the issues from jira, that are assigned to me with that account?
> 
> What you can do is to automatically import all issues that are assigned to you. The default JQL works fine for me (`assignee = currentUser() AND sprint in openSprints() AND resolution = Unresolved ORDER BY updatedDate DESC`) but you can also change it to:
> `assignee = currentUser()` to get _all_ issues assigned to you.

Ok. I got now a little more the whole idea of the integration, it's really cool :-) the missing parts I'd need I'll file lateron as a possible feature(-request). Thanks for now, but one little question before filing another bug report. With the assignee thing, I tried to only show the unresolved ones with `assignee = currentUser() AND resolution = Unresolved` but it also shows the ones marked as done. When I pull them up from the backlog, mark them as done and finish working, it's not shown anymore but kept the same in jira ... shall I report this as a bug too?

**Comment by johannesjo** [comment]
Generally I would recommend testing your jql on the jira pages search field. There are lots of options to configure your fields and it might very well happen that you have more issue stati or that have a different names for than expected.

I'm not sure if I understand your question correctly.  You need to enable transition handling in the settings to update the status on jira too. It's made this way, because the stati on Jira are completely configurable. To complicate things further it might also happen that there are different stati for different types of issues.

**Comment by jeensg** [comment]
Well, I will try that with the jira search.
At the end I did get, after just entering my credentials for jira, old issues in the backlog, that were marked as resolved in jira ... and I didn't get why. Maybe the `AND resolution = Unresolved` is simply not enough / the same as `Done` :-)

**Comment by johannesjo** [comment]
I'm closing this. Let me know if you have any further issues.
