### ISSUE TITLE
Bookmarks (Image, File and Command types)  do not work properly 

### ISSUE THREAD

**Issue by JLuisGT** [johannesjo/super-productivity#1420]
## Problem Statement

I find the bookmark feature very useful, however I have only managed to set url type bookmarks; **Image, File and command type Bookmarks do not work properly**.

For example, it would be useful to be able to open certain folders from superProductivity, however when defining them as File Bookmarks they do not open, and when defining them as Command type with
  
`nemo  "/path/to/Folder" `, being nemo my file explorer, it tells

`Error: Command failed: nemo "/path/to/Folder" /bin/sh: 1: nemo: not found`

When I run that command in a terminal it correctly opens the directory.

Likewise, the image type bookmarks do not show the image or open it when clicking.

Is this an issue with bookmarks or maybe I'm adding them in the wrong way?

## :heavy_plus_sign: Additional context

OS: Linux Mint 20.2
SuperProductivity Installed from Snap store

**Comment by johannesjo** [comment]
Thanks for opening this up. 

Normally I would expect this to work (and it does without problems on my machine) as there is nothing fancy going on. For files electrons `shell.openExternal` is used (https://www.electronjs.org/docs/api/shell) and for executing commands nodejs's `require('child_process').exec` Could you replicate this for different commands and file paths?

> Likewise, the image type bookmarks do not show the image or open it when clicking.

Could you maybe outline the exact scenario when they are not working? So far I had no problems.

**Comment by JLuisGT** [comment]
Interesting...


Defining a simple command bookmark, like:

`pwd > ~/commandOutput.txt`

It runs without error, however doesn't generate the file commandOutput.txt in _/home/userName/_ but in _/home/userName/snap/superproductivity/1304_, which is understandable considering that it is an application installed with snap, however


 Defining another bookmark command like `nemo ~` keeps generating the reported error.

`Error: Command failed: nemo ~ /bin/sh: 1: nemo: not found`

I thought it was a problem related to `/bin/sh` being a symbolic link to _/bin/dash_, instead of _/bin/bash_, but after updating the symbolic link to point to `/bin/bash` the problem persist.

I have checked the connections (`snap connections superproductivity`) and `superproductivity:home` is indeed included.

Running `nemo ~` in a terminal has the expected behavior, opening a file explorer in the user's home folder. 



I can try an installation from source code, however I found automatic updates very convenient. 

Thanks again for your quick responses.

**Comment by johannesjo** [comment]
That's interesting indeed. Not sure if that is what going on, but the limiting factor seems to be the snap sandboxing. I don't know how it works exactly, but from a certain perspective it makes sense to limit what is accessible by snap apps.

**Comment by JLuisGT** [comment]
I confirm it was a snap related issue

I downloaded and installed the .deb and it is working like a charm, opening directories, files and images like there is no tomorrow.

SuperProductivity only gets better and better

:D

**Comment by johannesjo** [comment]
I am very happy that it works now! Not sure what to do with the snap case, but maybe having the information available here is good enough for now. Thank you for digging into this! :)
