### ISSUE TITLE
The screenshot says it all (The button is not aligned)

### ISSUE THREAD

**Issue by Dumbledore-web** [johannesjo/super-productivity#1423]
![image](https://user-images.githubusercontent.com/70784752/127813153-1d454b26-1110-4089-bffd-fccdaece6876.png)

**Comment by johannesjo** [comment]
Thanks for opening this up!

**Comment by Mayank-MP05** [comment]
Let's see into what we can do The bug is at Settings > sync and export > import and export

**Comment by HoroTW** [comment]
@Mayank-MP05 I think you solved this with commit https://github.com/johannesjo/super-productivity/commit/a2db7f1d7c7138ee12e28109c5f2f84847153c6e so I guess this should be marked as solved?

**Comment by johannesjo** [comment]
@HoroTW  Yes, thank you!

And Thanks again @Mayank-MP05 for fixing this!
