### ISSUE TITLE
Automatic Music That Plays During Breaks

### ISSUE THREAD

**Issue by ckwakc** [johannesjo/super-productivity#1425]
Hello!

First, thank you so much for creating this application and making it free. Your program is absolutely wonderful and amazing.

I was wondering, would you be able to add a feature in an mp3 or mp4 will play automatically during breaks, please? Another pomodoro program has this as one of their features and it's brilliant. Thank you!

**Comment by AlexisPrel** [comment]
Out of pure curiosity, I am wondering why so many people are requesting this feature.
Why not simply keeping the .mp3 in your home directory and launch it yourself?

**Comment by antonio-hickey** [comment]
> Hi there! Thanks for the suggestion. I like it! PRs are welcome!
> 
> For reference this has been discussed before:
> #462

Sounds like fun I'm not super experienced with typescript but I'll attempt it, looking to give back to this project big fan of it. What kind of music would be best suited for the average user? or should it be user selected music? I'm personally a fan of chill/lofi hiphop beats like for example https://www.youtube.com/watch?v=BPVu5xaZk-4 which I will try to implement for my own forked version, but open to whatever the user's want. Maybe after I finish my version we can hold some type of vote for a default one?

**Comment by johannesjo** [comment]
> or should it be user selected music?

Definitely only the latter. I wouldn't want to ship any music files with the app.

**Comment by antonio-hickey** [comment]
> > or should it be user selected music?
> 
> Definitely only the latter. I wouldn't want to ship any music files with the app.
> 
> Looking forward to your PR! :)

Oh for sure, I was thinking of using the Youtube API, I just recently did something similar for a hobby project of mine (starter page / home page for my web browser) where it's playing audio from a livestream of music on youtube. I'm going to start looking into the codebase here this week, should I shoot you any questions here or is there a better way to contact you?

**Comment by johannesjo** [comment]
That's a nice idea! Not sure if this raises any legal issues. We might need to check this, though there is already a section about the google apis on the private policy page: https://super-productivity.com/private-policy/. 

Generally I'd lean into the direction to keep this feature as simple as possible, as it only applies to pomodoro which not everyone uses :)

I think the best place to discuss stuff related to this issue is here. If you have any further questions you can also use the contact@super-productivity.com address.

**Comment by ckwakc** [comment]
I was thinking that it would be awesome if users are able to select an audio file (.mp3 or mp4) that they own to play. Unfortunately, this is out of my limited programming skills.
