### ISSUE TITLE
Tag settings cannot be saved while time tracking

### ISSUE THREAD

**Issue by ffcruz85** [johannesjo/super-productivity#1428]
### Your Environment

- Version used:  7.5.0-rc.0 (Windows) and 7.3.3. (Android)
- Operating System and version: Windows 10 and Android 11
- Desktop Environment: none
- Browser Name and version: none

### Expected Behavior

I am tracking time for a task called "organize superproducvity projects/tasks" - I know, how meta. I edit tags to use in organizing my tasks, click save, and settings get saved

### Current Behavior

If time is being tracked, customizations on tags do not save. If you change color or icon and click save, it just reverts back. Actually, you don't even need to click save for it to revert. try editing the tag name while tracking time - it literally deletes newly typed characters after 1 second. Actually, maybe an important bit of info - If I type a character in name and click immediately after, before it gets deleted, it actually saves!
Happens on any tag, even if it is not used for the currently tracked task

### Steps to Reproduce (for bugs)

Can be reproduced reliably on both windows and android apps for me.

1. Start tracking time on any task
2. Click on settings for a tag in sidebar
3. Try to edit any aspect of the tag - name , icon, color - it gets deleted unless you click save within 1 second.

### Console Output

Kind of unable to find the right part of the console output, since it is refreshing every second as well

**Comment by johannesjo** [comment]
Thanks for reporting. I'll try to have a look this Friday.

**Comment by johannesjo** [comment]
Thank you again! Should be fixed now.

**Comment by ffcruz85** [comment]
Thank you so much @johannesjo ! I guess for PC I just install the next RC, and for Android just wait on a play store update?

**Comment by johannesjo** [comment]
> Thank you so much @johannesjo ! I guess for PC I just install the next RC, and for Android just wait on a play store update?

The android version should normally be automatically updated with the next full release. Just put it in the build pipeline. If there are no errors it should be available soon. :)
