### ISSUE TITLE
[Feature] Pause time AFTER break of promodo

### ISSUE THREAD

**Issue by Kl4tch** [johannesjo/super-productivity#143]
## Expected Behavior
Long promodo's break takes 15 min (example). I go out for 20-25 min. So, after promodo's 15min break it counts to task 5-10 min. 
It would be great if you add an option for pause task time AFTER finish promodo's break.  

## Current Behavior
After promodo's break it counts to task time, while I'm out.

## PS
Thanks for this complex great app

**Comment by johannesjo** [comment]
Thanks for reporting. I think the best way to solve this problem is setting the "Manually confirm starting next pomodoro session" option. Let me know if this works for you.

**Comment by Kl4tch** [comment]
Oh, sorry... Thanks for fast reply ))
