### ISSUE TITLE
WebDAV Nextcloud Error: 404

### ISSUE THREAD

**Issue by mareekkk** [johannesjo/super-productivity#1430]
### Your Environment

Super Productivity 7.3.3 on Windows 10
Nextcloud 22.0.0 running on Synology NAS

### Expected Behavior

Sync tasks.

### Current Behavior

Sync is not successful giving me a:
`Unknown Sync Error: Error: Invalid response: 404`

### Steps to Reproduce (for bugs)

Sync Provider: WebDAV
Base URL: `https://<www.myurl.com>/remote.php/dav `
Where calendar private link is: `https://<www.myurl.com>/remote.php/dav/calendars/<username>/personal/`

Sync File Path:
`personal`

I added:` app.super-productivity.com` in my **config.php**'s trusted domains and
`https://app.super-productivity.com` in **WebAppPassword**

### Error Log (Desktop only)
on Windows: %USERPROFILE%\AppData\Roaming\superProductivity\logs\main.log
_There is no superProductivity in this path._

I do not know if this is a bug of I might have just missed something.

**Comment by johannesjo** [comment]
Hi there! Thanks for reporting. Looks like a  misconfiguration at first glance. A 404 usually indicates that there is nothing found at the url being used. You might be able to find more information using the network tab (Ctrl+Shift+i and then click on "Network").

**Comment by mareekkk** [comment]
> Hi there! Thanks for reporting. Looks like a misconfiguration at first glance. A 404 usually indicates that there is nothing found at the url being used. You might be able to find more information using the network tab (Ctrl+Shift+i and then click on "Network").

Thank you, I ended up creating a directory and wrote the entire path.

**Comment by SunkenInTime** [comment]
> > Hi there! Thanks for reporting. Looks like a misconfiguration at first glance. A 404 usually indicates that there is nothing found at the url being used. You might be able to find more information using the network tab (Ctrl+Shift+i and then click on "Network").
> 
> Thank you, I ended up creating a directory and wrote the entire path.

How did you find the path of your folder?
