### ISSUE TITLE
Completing a Jira task from the today view does not prompt to update Jira work log times

### ISSUE THREAD

**Issue by logicbomb421** [johannesjo/super-productivity#1435]
### Your Environment

- Version used: 7.1.0
- Operating System and version: macOS 11.5.1
- Desktop Environment: 
- Browser Name and version: 

### Expected Behavior

Completing a Jira-linked task from the Jira-linked project in Super Productivity prompts the user to add time to the jira work log. Completing a Jira-linked task from _any_ view in SP should allow the same functionality.

### Current Behavior

Currently when completing a Jira-linked task from the today view, we only see the option to transition the issue, but not the box to log time back to Jira.

### Steps to Reproduce (for bugs)

1. Create a Jira-linked project and import some tasks
2. Completing a task in the project view will show a Jira work log modal
3. Completing a task in the today view will only show the transition modal.

### Console Output

None

### Error Log (Desktop only)

None

**Comment by johannesjo** [comment]
Thanks for reporting! I try to have look next Friday!

**Comment by johannesjo** [comment]
Sorry. Totally forgot about this one :/
