### ISSUE TITLE
[Feature] Hide pomodoro break timer dialog

### ISSUE THREAD

**Issue by Acsigen** [johannesjo/super-productivity#144]
## Your Environment

* Version used: 2.07 deb
* Operating System and version:Ubuntu 18.04 x64
* Desktop Environment: Gnome 3.28.2
* Browser Name and version: 

## Expected Behavior

Possibility to hide the break timer dialog, it was possible in 1.x version.

## Current Behavior

Unable to hide the break timer dialog.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by johannesjo** [comment]
Hey there! You can disable the break timer by disabling "Enable take a break reminder" under misc Settings. Or do you mean a button inside the snack message?

**Comment by Acsigen** [comment]
> Hey there! You can disable the break timer by disabling "Enable take a break reminder" under misc Settings. Or do you mean a button inside the snack message?

A button inside the snack message. I meant the Pomodoro Break timer.

**Comment by johannesjo** [comment]
Could you maybe explain the use case for this?

**Comment by Acsigen** [comment]
> Could you maybe explain the use case for this?

Quite often during the break I review my task list for a brief period of time to check my progress. At least that's how I do it.
