### ISSUE TITLE
Plain text approach [feature request]

### ISSUE THREAD

**Issue by mizhozan** [johannesjo/super-productivity#1446]
## Problem Statement
Superproductivity is a promising app, but it has to tackle many things in the many fronts at the same time. While plain-text strategy is very flexible, future proof and make focus the app on what matter most i.e. managment and visual feedback

## :grey_question: Possible Solution
I like to have the tasks and projects in plain text (e.g. markdown) files and folders respectively.

Each project would be a directory, each sub-project if any, would be a sub-directory and the tasks are simple markdown files. Any attachment can be simply ignored as they're not relevant to what super-productivity do. The app only needs the directory structure and content of md files (or any special plain text). I use vim and ranger quite extensively and it would be great to have a such a functionality and use superproductivity dealing with managing and visual feedbacks. The plaintext then could support any form of complicated description, comments, etc (e.g. math and figures).

### Interoperability with plain text strategy
The app could have at least a sync/export functionality which export the tasks and projects into plaintext/directory formats. However, as the user change the content of plain text with whatever he prefers (vscode, vim, emacs, notepad, etc) or rename the directory it would be sync back to the app presented as tasks and projects.

This also simplifies the syncing as well as I could put the directory in dropbox for example and sync all my todos and stuff across devices.

**Comment by johannesjo** [comment]
Thank you very much for sharing your thoughts. I like the idea and I am open for experimenting with it, but I probably won't find the time to work on something like this myself.

**Comment by mizhozan** [comment]
Thanks. Unfortunately I do not have experience with TS/JS programming but I might get back to this as a learning project.
