### ISSUE TITLE
Allow to change duration of a break (advanced break adjustments)

### ISSUE THREAD

**Issue by surli** [johannesjo/super-productivity#1451]
## Problem Statement
So I often got the following issue:
  - I'm going on lunch break
  - I come back later to resume my work
  - I completely forgot to start back the task
  - when switching to another task I see that Superproducivity popup says to log my time for the previous 4 hours

## :grey_question: Possible Solution

Best IMO would be to be able to split up the time spent in several tasks and/or breaks. In terms of UI, I imagine something where you'd have a text input and a "+" button next to it: if you press + you get another text input and you have another input to specify the time spent.

## :arrow_heading_up: Describe alternatives you've considered

Right now the only option I have is to register that as a break and then manually adjust the time spent on my previous task. But I messes up the "time spent on work before a break" and the global time spent on break (which might not be recorded actually?)

**Comment by johannesjo** [comment]
Thanks for opening this up! I agree that this should be a possibility for the user. I experimented with this before, but left things as they are, because I also didn't want to make the required interaction to complicated. But if somebody comes up with a good concept for a revamp of the idle dialog, I am all for changing it.

**Comment by AlexisPrel** [comment]
Wouldn't the following workflow mostly suits your need?
- Create a task "lunch /1h" scheduled to repeat every day at 13:00.
- Then you get notified as early as 14:00 if you forget.
- Adjust above settings based on your need.
- Delete task when you're back from lunch to keep it off your stats

Issues with this:
- having to delete a task every day
- the "time spent on work before a break" stat is still wrong

Suggested solutions:
- **either** consider breaks as "tasks" with built-in tag "break".
- **or** extend the timeline settings to specify a list of work intervals, e.g. "8:00-13:00 ; 14:00-18:00"

Collateral benefit (for both solutions):  the timeline view is improved because it does not place unscheduled tasks during your lunch break, or any other anticipated break.

**Comment by surli** [comment]
> Issues with this:
>  * having to delete a task every day
>  * the "time spent on work before a break" stat is still wrong

Also in my case, my schedule is not that specific: time of my lunch break mainly depends on what I'm working on, so it might change from one day to another. 

> either consider breaks as "tasks" with built-in tag "break" -> above workflow works without having to delete the task and with correct stats

I like this solution, especially since I'd like to also be able to have some stats about the break performed during a day. If each break creates a virtual task, then it's possible to add some other meta-data on them (e.g. "lunch break", "medical appointment" etc) so that I can have a follow up on what happened a particular day during the breaks, and stats are still good. 

Not a big fan of the other solution since I actually don't use timeline at all.

**Comment by johannesjo** [comment]
Thank you very much for your input! I think its clear, that the current way breaks are defined is a bit too fuzzy and that there should be a bit more control possible. But using tags or tasks doesn't feel right to me (yet?) and I also feel it's a good idea to not make it too technical (after all stressing yourself with correctly tracking your breaks, kind of defeats the purpose imho).

It would be super helpful to me, if you could provide me with your view on why and how tracking breaks could be useful. Maybe from there we can develop a good concept on how breaks should be handled within the app.

**Comment by surli** [comment]
> It would be super helpful to me, if you could provide me with your view on why and how tracking breaks could be useful.

So for me, my main interest for tracking my breaks is to be able to have a better understanding of what happened when I took a look on my past work log. There's at least 3 features that I'd want:
  1. being able to see the number of breaks (work breaks or not work breaks, with a color distinction probably) and their duration during a day: this might explain a lack of productivity if I've been interrupted several times, or on the contrary a lack of motivation leading me to taking lots of breaks
  2. being able to add meta-data on a specific break so that it appears specifically on my work log (not mixed with the other ones): for example, if I have to go for a medical appointment, I consider it's a break on my work, but I don't want to create a task for it and I think it would be helpful if I can see this specific break and its duration on my worklog 
  3. being able to edit the breaks on the sum up at the end of the day: either to add meta-data on the breaks, to change duration, or to switch them from work break to not work break. Ideally I don't want to have to think much about tagging my breaks when I come back to work, but I'd like to be able to do it when I finish my day. 

Also I see a 4th feature slightly unrelated that could be helpful for me, on the same idea than 3: being able to add a short note on a day when finishing it that would appear when opening it on the work log. Again here the idea is to get a bit more info about what happened that day.

**Comment by johannesjo** [comment]
@surli given from the use cases I would conclude that a making the current break counters (time and amount per day) editable could be good enough (although I admit that wouldn't cover everything you need), while keeping the concept brief and simple. This should be possible from the daily summary view (like it is for the work start and work end times) and via an optional button (opt in, as I don't want to clutter the ui for people who just want to manage their tasks). What do you think? 

For 2 just doing nothing (or selecting skip from the idle dialog) would be what I would do (or creating a task in a dedicated project for stuff like that as you say).

**Comment by johannesjo** [comment]
So I spent a little bit more time on this. I found that the break time itself, might not be to helpful. Instead I think that it's more about taking good breaks and to find out why they are good. Here is a rough concept I wrote down. Please share your thoughts on this! :)

# advanced & simple break tracking

## simple tracking

Mostly as is, but on a global level (currently breaks are saved for the currently active project which is not working well).

### Why

=> Simple indicator to quickly compare how much time was spent on breaks today and over time

### How

perDay:
amountOfBreaks
timeSpentOnBreaks

=> editable from daily summary
=> affected by advanced break tracking

## advanced tracking

### Why

To learn more about ones break taking patterns and possibly improve them.

### How

As on optional (opt-in) productivity feature, based around several UI elements:

#### Dialog

You took a break
How long did it last? => time
How was your break? =>  😀 😐 ☹️
Why was your break 😀? => free text

#### Button

Placed on the top right, next to the play button. Manually add a new break. Indicates the number of breaks and/or time for today.

(maybe) right click allows to edit past breaks? 

(maybe) speed dial to access Break Overview Page

#### Break Overview Page

Shows all breaks and their data sorted by 😀



#### Daily Summary "Breaks" Tab

Provides a quick glance at all of todays breaks.

#### Metric Page

Should contain a section to provide data over time. Maybe provide graphs to indicate relations between data.

#### Quick History Page

Show amount of 😀 😐 ☹️ breaks. Show amount of breaks and time spent on them.

**Comment by StiTof123** [comment]
@johannesjo as a follow up to request #1511, been reading through the other inputs above. and I don't think i have anything to add. thank you again for you hard work 

br 

Stian
