### ISSUE TITLE
Don't mark repeated tasks as "completed" when a new instance is created

### ISSUE THREAD

**Issue by MAX10541** [johannesjo/super-productivity#1459]
## Problem Statement

Currently, any incomplete repeat tasks are marked as "completed" when a new instance is created. This is creating some unexpected results and behavior for metrics and exports, as these tasks will show up as "completed" even though the user didn't actually complete them.

## :grey_question: Possible Solution

Mark the tasks as "archived" or something similar and remove them from the day. The "archive" feature in itself could be used elsewhere too by the user. For example: when he needs to remove a task, but not completely delete it. Bare in mind if this archive feature is implemented, the user will probably want to access the archive somehow.

## :arrow_heading_up: Describe alternatives you've considered

- Maybe don't create a new instance of the repeated task, and just keep the old one if it already exist (and incomplete).
- Another (probably the simplest) alternative is to keep marking them as completed, but add an extra flag internally to avoid including them in the metrics and exports.

**Comment by johannesjo** [comment]
Thanks for opening this up! Personally I prefer the current behavior (It's always possible to delete the task marked as done, if you don't want it to show up in your stats) to not doing anything which would be an alternative I would consider, if many people request this.

What I definitely wouldn't do is to add a new special state for this, as it would make things complicated both in terms of code and in how to communicate this to the user.

Additional feedback or ideas on this would be welcome.

**Comment by MAX10541** [comment]
If anyone is interested, I've created a new fork and added a simple "archive" feature. It's still work in progress, and there are a few missing things. It won't be an active fork, I just want to experiment a bit with this feature.
