### ISSUE TITLE
When starting jira-task, view in comments (and more) gets fuzzy

### ISSUE THREAD

**Issue by jeensg** [johannesjo/super-productivity#146]
## Your Environment
* Version used: 2.2.2 deb
* Operating System and version: Ubuntu 18.10
* Desktop Environment: xfce - xubuntu

## Expected Behavior
Optics stay the same when starting.

## Current Behavior
Gets fuzzy, see attachment.

![jira-integration_fuzzy](https://user-images.githubusercontent.com/24763877/52625153-a5113180-2eb0-11e9-831c-281a55a0599c.png)

When halting task again, everything looks normal:

![jira-integration_fuzzy_2](https://user-images.githubusercontent.com/24763877/52625409-38e2fd80-2eb1-11e9-9adc-d2f313b7551a.png)

## Steps to Reproduce (for bugs)
1. start task from jira

## Console Output
Didn't see anything except time starting to count secondswise.

**Comment by johannesjo** [comment]
This should be fixed. Please let me know if it isn't.
