### ISSUE TITLE
Could there be a shortcut for "Add to backlog" added?

### ISSUE THREAD

**Issue by psprint** [johannesjo/super-productivity#1466]
## Problem Statement

When I invoke adding task via keyboard and want to add to backlog, I need to reach the mouse to click the "+" icon (to switch to "Add to backlog" state).

## :grey_question: Possible Solution

A keyboard shortcut like Ctrl-B should be available to switch to/from "Add to backlog" state in the add task window.

## :arrow_heading_up: Describe alternatives you've considered

There could be also a direct shortcut that would bring the add task window directly in "Add to backlog" state.

## :heavy_plus_sign: Additional context

I like that superProductivity can be in 99% handled from keyboard and I'm using this super program this way.

**Comment by johannesjo** [comment]
That's a good suggestion! Thank you! Meanwhile you can press `Shift+A` and then `Ctrl+1` to achieve the same.

**Comment by psprint** [comment]
Yes, the Ctrl-1 shortcut is enough convenient, thanks! :)
