### ISSUE TITLE
Can not trigger context menu on web app

### ISSUE THREAD

**Issue by WantToLearnJapanese** [johannesjo/super-productivity#1467]
On android I can trigger context menu by long touch so that start specific timer.

But on iOS, I tried web and PWA version, long touch triggers selecting texts.

Is there any workaround to start sprcific todo on webapp or to trigger context menu?

**Comment by johannesjo** [comment]
Hey there! Unfortunately I have no ios device to test this on. The code for the longpress handling can be found here:
src/app/ui/longpress/longpress.component.ts

Not sure why it is not working on iOS.

**Comment by WantToLearnJapanese** [comment]
https://user-images.githubusercontent.com/88884927/130813920-e08deba9-115a-4a73-86a1-23410371797b.MOV

It seems the handler you mentioned is not called.

I think some text ui components without the user-select property are being selected.

**Comment by johannesjo** [comment]
Hey there! Thanks for checking. 
I made a new testing release, could you maybe check again?
https://test-app.super-productivity.com/

Turns out that the longpress directive wasn't even in use for the task component and only the (contextmenu) directive, which apparently doesn't work for ios for some reason.

What also [might be related is this](https://stackoverflow.com/questions/37913629/chrome-appears-to-ignore-user-select-in-a-contenteditable-div
) as the task titles all get that attribute.

**Comment by WantToLearnJapanese** [comment]
@johannesjo 

It does work!!!

Wow!

**Comment by johannesjo** [comment]
That's great to hear! Could you maybe do me another favor?
Could you try adding `* { -webkit-touch-callout: none; }` (needs to be applied to every element) if this works, that might be a much better fix performance wise.

**Comment by WantToLearnJapanese** [comment]
We are talking about "select text"? 

If so,
* `* { -webkit-touch-callout: none; }` seems to not work!
* `* { -webkit-user-select: none; }` seems to work!

**Comment by johannesjo** [comment]
> We are talking about "text selection"?

Does this also fix the context menu not opening up?

**Comment by WantToLearnJapanese** [comment]
> Does this also fix the context menu not opening up?

I could not check the context menu. I can't add that CSS on my side for iOS.

Can you push the codes fixed long-press for the context menu?

**Comment by WantToLearnJapanese** [comment]
> > We are talking about "text selection"?
> 
> Does this also fix the context menu not opening up?

Oh! 
I re-read your comment. 
Those CSS alone does not fix the problem.

**Comment by WantToLearnJapanese** [comment]
Issue seems to solved perfectly now. 
Let me close the issue.

**Comment by johannesjo** [comment]
Unfortunately I have to revert the fix for ios as it is causing issues when scrolling or dragging (it opens up sometimes) :/

**Comment by WantToLearnJapanese** [comment]
> Unfortunately I have to revert the fix for ios as it is causing issues when scrolling or dragging (it opens up sometimes) :/

T.T Are you saying you will cancel this commit? https://github.com/johannesjo/super-productivity/commit/f8b11af39bd1ec1e85cd7c915ee124ef8b2cf55c

**Comment by WantToLearnJapanese** [comment]
I think adding "touchmove" and "touchcanel" will fix the issue.

**Comment by johannesjo** [comment]
I also added an ios only longpress handler, so this shouldn't affect the other platforms as much.

**Comment by WantToLearnJapanese** [comment]
@johannesjo 
In the current version (says 7.5.2?, https://app.super-productivity.com), iOS Safari text select is not disabled so that I can't call the context menu, but calling context menu works fine on https://test-app.super-productivity.com.

I am reporting this since I am worried if I reported wrongly before. (I was using version 7.5.2 by self-hosted with CSS `* { -webkit-user-select: none;}`)

**Comment by johannesjo** [comment]
Thank you! I think I found a good solution now for both the problems.
