### ISSUE TITLE
app crashes when starting jira-task (on assigning it again to oneself) 

### ISSUE THREAD

**Issue by jeensg** [johannesjo/super-productivity#147]
## Your Environment
* Version used: 2.2.2 deb
* Operating System and version: Ubuntu 18.10
* Desktop Environment: xfce - xubuntu

## Expected Behavior
App doen's crash.

## Current Behavior
On starting a task, I'm always told to update 2 things:
1. Update status on jira. This works as expected, except that I actually would only like to be asked the first time starting the task, not after every 2min-brake.

![start-task](https://user-images.githubusercontent.com/24763877/52625919-5e243b80-2eb2-11e9-84b8-ca465131507b.png)

2. Update Assignee: after the first one it's said, that the task is not assigned to myself. I can Cancel that one and everything works fine. But when Updating, the whole app crashes. Pomodoro still counting in the upper right corner, but everything else (all the buttons and navigation) is not working anymore. (something it's also asked twice, whene I wait a little while)

![2nd-dialogue](https://user-images.githubusercontent.com/24763877/52626079-b78c6a80-2eb2-11e9-977e-a164ba67926b.png)

--> there is an error message at the bottom (it would be nice, if error messages wouldn't disappear without clicking :p 

![jira-error](https://user-images.githubusercontent.com/24763877/52626148-dc80dd80-2eb2-11e9-99ac-2d6d7a22aa32.png)

## Steps to Reproduce (for bugs)
1. start task
2. update assignee when asked

## Console Output
yes.

![jira-error_console](https://user-images.githubusercontent.com/24763877/52626185-ec002680-2eb2-11e9-9b56-94e47f9cc117.png)

**Comment by johannesjo** [comment]
Thanks for reporting. Could you expand the error object in the console? A Status Code Error usually indicates that you are performing an action which is not allowed for some reason.

**Comment by jeensg** [comment]
Sure :-) tell me if it's enough. I also could send you more and with all the data, but better not here...

![error](https://user-images.githubusercontent.com/24763877/52668288-78423600-2f13-11e9-86c6-1101aa741254.png)

**Comment by johannesjo** [comment]
Ah ok. If you use your email address as credential you must also define "assignee name to check for". Maybe I should restrict login to use the user name..

That the app crashes completely in this case is not good though...

**Comment by jeensg** [comment]
I got it. When I put my username it works exactly as supposed to be. Thanks.

**Comment by johannesjo** [comment]
This should be fixed. Please let me know if it isn't.
