### ISSUE TITLE
Feature: "Let me decide" button 

### ISSUE THREAD

**Issue by psprint** [johannesjo/super-productivity#1471]
## Problem Statement

I'm using SP for programming OpenSource projects. I have some ideas for features and bug fixes in the backlog and in projects. The "problem" is that having that much tasks makes it somewhat hard to choose one to engage.

## :grey_question: Possible Solution

Thus, the idea: "You decide" or "Let me decide" button, that would do nothing more than switching to some other, *random* task.

## :heavy_plus_sign: Additional context

I think that this feature would be useful to break activity stalls / decision crisis.

**Comment by johannesjo** [comment]
Hey there! Thanks for the suggestion! As this seems to be more of a special use case (personally I never run into the problem you describe), I wonder where to put such a button(?) without cluttering the UI for users who don't need it.
