### ISSUE TITLE
The latest CSS related commit broke on Samsung Internet on Android 

### ISSUE THREAD

**Issue by WantToLearnJapanese** [johannesjo/super-productivity#1474]
![Screenshot_20210829-204353_Samsung Internet](https://user-images.githubusercontent.com/88884927/131249238-d4fb44a0-eee9-4f98-b10a-8e577f7c786b.jpg)
I am not sure if you are interested in supporting Samsung Internet.

I report there is a CSS glitch with Samsung Internet on Android. 

Wikipedia says Samsung Internet occupies about 5.85% of usage on the mobile web browser, which ranks 3rd. (Chrome 63.06%, Safari 29.63%).

(I was a little surprised since they use Blink engine like other common web browsers. I encounter many performance glitches with Samsung Internet on other sites. It is ... bad to use, actually)

**Comment by johannesjo** [comment]
Thank you very much for opening this up!

**Comment by WantToLearnJapanese** [comment]
The issue disappeared after I clean all caches of the browser.

I am not sure what had caused the problem.

**Comment by johannesjo** [comment]
What was missing in the screenshot where the icons. Possibly something went wrong with the caching in that browser? Thanks for reporting back! I'm closing this, as it is likely unrelated to this app.
