### ISSUE TITLE
Could we have the "sync" button for desktop-web and Desktop-native versions?

### ISSUE THREAD

**Issue by WantToLearnJapanese** [johannesjo/super-productivity#1475]
## Problem Statement
I want to have a sync button as a mobile-web view has.
![image](https://user-images.githubusercontent.com/88884927/131250878-70fca83a-5172-4714-a970-c4ae8c1581ce.png)

## :grey_question: Possible Solution
Add "the sync" now button before the play button(▶) at the top-right.

## :arrow_heading_up: Describe alternatives you've considered
Hmm, I think we could add new sync behavior in addition to the current one (sync every x minute).
 * Sync every time whenever a user interacts.

## :heavy_plus_sign: Additional context
I like to switch from device to device, so I want to have the "sync now" button for desktop as the mobile-web version has.

**Comment by johannesjo** [comment]
We could add it as a opt in sync setting. PRs are welcome!

**Comment by WantToLearnJapanese** [comment]
> We could add it as a opt-in sync setting. PRs are welcome!

Thank you for your reply!

Related code link:

* https://github.com/johannesjo/super-productivity/blob/bf421fcac69cb3ca8cf14e75e722618e33616700/src/app/core-ui/main-header/main-header.component.html#L60
