### ISSUE TITLE
Links in jira are opened twice

### ISSUE THREAD

**Issue by jeensg** [johannesjo/super-productivity#148]
## Your Environment
* Version used: 2.2.2 deb
* Operating System and version: Ubuntu 18.10
* Desktop Environment: xfce - xubuntu

## Expected Behavior
When opening the connection to jira, it's only opened once.

## Current Behavior
When clicking on something, that'S linking to jira, it's opened twice

## Steps to Reproduce (for bugs)
1. click on something in sp, that's opening the jira-corresponding link in browser (e.g. "write a comment")

## Console Output
None.

**Comment by johannesjo** [comment]
Thanks for reporting. This should be fixed with latest release (and some of the previous ones ;)).
