### ISSUE TITLE
Shortcuts to projects?

### ISSUE THREAD

**Issue by psprint** [johannesjo/super-productivity#1489]
It would be great if there were a way to open all projects from keyboard. Say, via Alt+1…Alt+0? 1 (Alt+1) would open first project, 2 second, etc. Right now almost everything can be done from keyboard except for the problematic projects.

**Comment by johannesjo** [comment]
Hey there! Thanks for the suggestion! I like it. Alt+1... won't work for the browser version, but maybe we can make this a desktop app only feature.

**Comment by AlexisPrel** [comment]
If the only problem for non-desktop is the choice of key, you could make it so that Shift+P cycles through projects, consistent with others "Shift+..." shortcuts.

**Comment by psprint** [comment]
Hey,
what about the issue? Are project shortcuts possible?

**Comment by johannesjo** [comment]
Pull Requests are welcome for this!
