### ISSUE TITLE
new tasks in jira not added to sp backlog

### ISSUE THREAD

**Issue by jeensg** [johannesjo/super-productivity#149]
## Your Environment
* Version used: 2.2.2 deb
* Operating System and version: Ubuntu 18.10
* Desktop Environment: xfce - xubuntu

## Expected Behavior
When entering an issue in jira, backlog is updated.

## Current Behavior
When I add an issue in jira, I do find it by name when searching in the list if I start a new task. But actually it should be added to backlog.

## Steps to Reproduce (for bugs)
1. add task in jira (to backlog)
2. look in backlog in sp
3. it's not there (but listable when starting new task)

**Comment by johannesjo** [comment]
This depends on if and how you configured to automatically import issues to the backlog. 

There is a fixed interval set for when this should occur (once short after the project is loaded and then every 5 minutes). If you configured the JQL correctly, the issue should then be imported.

**Comment by jeensg** [comment]
I'm sorry, thanks for the advice. First it wasn't imported right away, and then I think I changed JQL back to including `AND sprint in openSprints()` which led to not import it, b/c I didn't add it to the sprint. My bad, sorry again. Works smoothly....

**Comment by johannesjo** [comment]
No problem at all. It's probably due to the lack of documentation. There definitely should be a guide on how to use the Jira Integration. Haven't found the time to write one though.
