### ISSUE TITLE
Monthly worklog export shows first day of the month as part of previous month

### ISSUE THREAD

**Issue by aripollak** [johannesjo/super-productivity#1490]
### Your Environment

- Version used: 7.5.2 from snap
- Operating System and version: Debian bullseye
- Desktop Environment: GNOME Shell 3.38.4
- Browser Name and version: 

### Expected Behavior

Tasks from September 1 should show up in the worklog for September

### Current Behavior

Tasks from September 1 are showing up in August

### Steps to Reproduce (for bugs)

1. Click on Today's Project Menu -> Worklog
2. Click on the up-right arrow next to August

![Screenshot from 2021-09-03 09-29-28](https://user-images.githubusercontent.com/451345/132013188-c2bd9869-416e-4fb9-b5cb-176845330c5a.png)

Note that my time zone is EDT (UTC-0500).

**Comment by johannesjo** [comment]
Thank you very much for reporting this!

**Comment by johannesjo** [comment]
Will be fixed with the next release. Thanks again!
