### ISSUE TITLE
Last project in project list can't be deleted if it was recently selected

### ISSUE THREAD

**Issue by jstwinkles** [johannesjo/super-productivity#1497]
### Your Environment

- Version used: superProductivity-Setup-7.5.2.exe
- Operating System and version: WIndows 10 Enterprise version 20H2 (OS build 19042.1052)

### Expected Behavior

I would expect the ability to delete any project that exists in the Projects list.

### Current Behavior

I can only delete a project if it isn't the most recently selected project in the Projects list.

### Steps to Reproduce

Assume the project list only contains Project A and Project B for this example

1. Select Project A under Projects on the left pane
2. Go to "Manage Projects" on the left pane
3. The trashcan icon is grayed out for Project A, but Project B can be deleted
4. Select Project B under Projects on the left pane
5. Go to "Manage Projects" on the left pane
6. The trashcan icon for Project A is now available, but the one for Project B is grayed out
7. Go to "Timeline" on the left pane
8. Go to "Manage Projects" on the left pane
9. Both Project A and Project B can now be deleted

**Comment by johannesjo** [comment]
Hey there! Thanks for opening this up.  This has some history (#581) but was never implemented. Makes definitely sense to allow for it though. PRs would be welcome!

**Comment by jstwinkles** [comment]
Hi, I'd be glad to look at potentially contributing PRs to the repo.  It looks like this is an electron app, right?  Just wondering what I'd need to research before trying to contribute.  Most of my experience is in embedded software & firmware, not high level stuff.

Loving the app so far btw!

**Comment by johannesjo** [comment]
Yes it's an electron app. If you're completely new to Frontend development this might be a lot to chew on. The most important technologies used are: electron, angular, typescript and rxjs. Not sure what the best way to start is. I myself would probably give the source code and [the development setup a try](https://github.com/johannesjo/super-productivity#running-the-development-server) just to see how far I would get in understanding the code. 

Glad to hear that you like the app :)
