### ISSUE TITLE
Icons are messed up offline in android app

### ISSUE THREAD

**Issue by sandorex** [johannesjo/super-productivity#1498]
### Your Environment

- Version used: 7.5.2 from Google Play store
- Operating System and version: Android 7.1
- Desktop Environment: 
- Browser Name and version: 

### Expected Behavior

Load normally

### Current Behavior
Loads and instead of some icons there is large text and basically unusable

<details>

![w23rfewfgeqfgq](https://user-images.githubusercontent.com/18004075/132106362-0fc8ffe3-e703-4cc7-9a61-3a2128860485.jpg)
</details>

It's same as #756 

### Steps to Reproduce (for bugs)

1. Open the app with internet turned off

<br>

**Note that it does work in browser and when installed as an app from a browser**

**Comment by johannesjo** [comment]
Thank you very much for reporting this! Usually the icons should be cached once and then be loaded from there. But whenever the cache is deleted (e.g. by some cleaner app or manually), the result is what you experienced.  There is the plan to change this and thankfully some qualified Android dev volunteered to help with it, but it might take some time until we get there.

**Comment by sandorex** [comment]
Im glad someone is working on this, fortunately there is the web app as an alternative until then

**Comment by sandorex** [comment]
I've changed my phone (Android 10 now) but now it won't load at all and says 'Web page at https://app.super-productivity.com could not be loaded because net:ERR_FAILED'

**Comment by johannesjo** [comment]
I suppose that you can open https://app.super-productivity.com/ normally in your phones browser, right? Is your phone connected to the internet? And if so is the app allowed internet access?

**Comment by sandorex** [comment]
I am sorry i was not clear enough in my last comment, it works fine when i have internet on but when internet is off it shows
> Web page at https://app.super-productivity.com could not be loaded because net:ERR_FAILED

The problem's a little different but the app is still unusable in offline mode which i use most often

**Comment by johannesjo** [comment]
@sandorex not sure what could be the issue here. Works fine on the devices I've tested. You need to load the app once while being online though.

**Comment by sandorex** [comment]
Ok now it works, what i think has happened is that for some reason it did not want to update, now it asked me do i want to download new version in the app and after clicking yes it's working fine even offline
So i am closing this now, probably the same thing that fixed #756 has fixed this
