### ISSUE TITLE
Feature: ability to choose whether tasks are added to the bottom or top of the list

### ISSUE THREAD

**Issue by QuentinGruber** [johannesjo/super-productivity#1499]
## Problem Statement

I'm always frustrated when i add a lot of new tasks to my list of the day and that my old tasks are then at the bottom of the list, in the end I end up never doing these tasks

## :grey_question: Possible Solution

It would be nice to have the choice of whether the new tasks are added to the bottom or top of the list, a misc option.

thx for reading and thx for this nice software that is super-productivity 😛

**Comment by johannesjo** [comment]
Hi there. Thanks for your suggestion. This is already possible.

![Screenshot from 2021-09-06 17-02-37](https://user-images.githubusercontent.com/1456265/132236323-9ff4f1b6-29d8-4d2d-8a2a-e2449b0b9ca3.png)

**Comment by QuentinGruber** [comment]
Oh thx @johannesjo i didn't saw that 😅
