### ISSUE TITLE
App crashes when reassigning hide application binding

### ISSUE THREAD

**Issue by VozMajal** [johannesjo/super-productivity#15]
The default value for this (on OS X) is `Ctrl+Shift+X` but when I tried to change it to `Command+Shift+X` 

1. Command was not recognized

2. After trying `Command+Shift+X` and then `Alt+Shift+X`, then putting `Ctrl+Shift+X` back in, the application crashed

**Comment by johannesjo** [comment]
Thank you very much for reporting! I'll try looking into it this Friday.

**Comment by johannesjo** [comment]
Ok this should be fixed now with the latest release. The error might still occur as long as you did not rebind the hotkey in question, but it should not appear again.
