### ISSUE TITLE
Missing library libxshmfence

### ISSUE THREAD

**Issue by khartahk** [johannesjo/super-productivity#1501]
### Your Environment

- Version used: snap `superproductivity 7.5.2 1360 latest/stable johannesjo`
- Operating System and version: Ubuntu 21.04
- Desktop Environment: Gnome 3.38.5

### Expected Behavior

The app should have oppened.

### Current Behavior

The app does not open and throws this error:
```
$ superproductivity
/snap/superproductivity/1360/superproductivity: error while loading shared libraries: libxshmfence.so.1: cannot open shared object file: No such file or directory
```

Perhaps a fix: https://stackoverflow.com/questions/66459579/heroku-rails-chrome-selenium-error-while-loading-shared-libraries-libxshmfence

Using `snap refresh superproductivity --channel=latest/edge --classic` works as expected. It installed `superproductivity 7.5.2 1373 latest/edge johannesjo`

**Comment by johannesjo** [comment]
Thank you for reporting. Never encountered this problem. What is the output of `snap version`?

**Comment by khartahk** [comment]
```$ snap version                                                  
snap    2.51.4
snapd   2.51.4
series  16
ubuntu  21.04
kernel  5.10.0-1044-oem```

**Comment by johannesjo** [comment]
Thanks! Does executing `sudo /sbin/ldconfig -v` fix the error (see: https://itsfoss.com/solve-open-shared-object-file-quick-tip/)?

This also seems to be related:
https://forum.snapcraft.io/t/error-while-loading-shared-libraries-libxshmfence-so-1-cannot-open-shared-object-file-no-such-file-or-directory/25874

**Comment by khartahk** [comment]
That's weird. I went and reinstalled the `1360` version from `latest/stable` now after I've updated to `latest/edge` and now `superproductivity` opens without an error.

**Comment by johannesjo** [comment]
Thanks for the update! I suppose that this is a snap problem rather than one of the app itself.

**Comment by khartahk** [comment]
I guess it is. Perhaps even restarting the computer would help in this case.
