### ISSUE TITLE
Convert to RPM with Alien still failing

### ISSUE THREAD

**Issue by Dan-Essin** [johannesjo/super-productivity#1504]
yes

tar xf alien_8.95.5.tar.xz
cd alien_8.95.5
run the perl Makefile.PL, etc., etc.
attempt a conversion

### Console Output

alien -r Termius.deb 
Warning: Skipping conversion of scripts in package termius-app: postinst postrm
Warning: Use the --scripts parameter to include the scripts.
Package build failed. Here's the log of the command (cd termius-app-7.20.1; rpmbuild --buildroot='/home/essin/Downloads/termius-app-7.20.1' -bb --target x86_64 'termius-app-7.20.1-2.spec'):
error: line 5: Empty tag: Summary:
Building target platforms: x86_64
Building for target x86_64

### Error Log (Desktop only)

can't find any logs

**Comment by johannesjo** [comment]
This doesn't sound like it is really a problem of this app. You should be able to download the rpm directly from here:
https://github.com/johannesjo/super-productivity/releases/download/v7.5.2/superProductivity-7.5.2.x86_64.rpm
