### ISSUE TITLE
Latest deb files

### ISSUE THREAD

**Issue by shamoi** [johannesjo/super-productivity#151]
I wonder if you could push the latest deb packages on the git page as we can only download the v2.3.0.

Thank you and keep up the good work.

**Comment by shamoi** [comment]
Nevermind, I learned how to do it and it produced the packages I needed.

**Comment by johannesjo** [comment]
I was changing quite a bit during the last weeks and I didn't want to publish something half backed and untested. Thus the delay.

**Comment by shamoi** [comment]
It's all good. This gave me the opportunity to learn about electron.
