### ISSUE TITLE
Quick history optionally display dates 

### ISSUE THREAD

**Issue by IanQS** [johannesjo/super-productivity#1512]
Hey there! Thank you so so much for this library. I've found it very useful in my day to day

## Problem Statement

I'd really like to be able to see the dates when viewing the quick history

![feature_req](https://user-images.githubusercontent.com/6968573/133467772-d4a68ae3-1d3e-4b85-9551-087696c6a58a.png)

## :grey_question: Possible Solution
I want to be able to see the dates. Right now, I have to do some relative calculations to the current date to get some rough idea of the week I'm looking for.

## :arrow_heading_up: Describe alternatives you've considered

None really. Other than doing it manually I suppose I could just write some script, but it seems like a feature that would be better in-app.

## :heavy_plus_sign: Additional context
NIL

**Comment by johannesjo** [comment]
Makes absolutely sense to implement this. Thanks for the suggestion. I'll have a look.

**Comment by johannesjo** [comment]
Should be available with the next release. Thanks again!
