### ISSUE TITLE
Difficult to select task in time tracking reminder

### ISSUE THREAD

**Issue by hanixer** [johannesjo/super-productivity#1514]
### Your Environment

- Version used: 7.5.2
- Operating System and version: Windows 8

### Expected Behavior

In task selecting dialog for time tracking reminder some task should be selected.

Alternatively the dialog should display a list of available tasks so that user can select a task by mouse.

### Current Behavior

No task is selected initially. I have to start writing the name of the task, and this can require switching keyboard language.

### Steps to Reproduce (for bugs)

1. Add some tasks.
2. Does not start tracking time.
3. Wait for 2 min.
4. Select "ADD TO TASK" in time tracking reminder.

**Comment by johannesjo** [comment]
Thanks for opening this up. Not sure if I quite understand this right, but the dialog that appears contains an input in which you can either select a task from the list of auto suggestions of existing tasks or create a new one. Given that there can be very many tasks selecting from a possibly long list of tasks doesn't seem very practical.

**Comment by hanixer** [comment]
Let me explain. When the dialog is shown, I can see the input, but the list of tasks is not shown when I click on the input. The list is shown only when I start typing the task name. It would be good if I can select a task without using keyboard, just with mouse.

**Comment by johannesjo** [comment]
Ok, thanks for the explanation. If there is a good way to do this without(!) affecting the current keyboard assisted flow, I would accept a PR for this. I
