### ISSUE TITLE
Make it  more CPU friendly when minimized to tray

### ISSUE THREAD

**Issue by gudata** [johannesjo/super-productivity#1515]
## Problem Statement
After start using the program my notebook starts the CPU fans. under the CPU utilization it is visible that it takes 3-10% CPU when the app is minimized in the system tray. This is on Desktop/Linux

## :grey_question: Possible Solution
Suspend all activity when paused and leave only the timers to tick.

**Comment by johannesjo** [comment]
Thanks for opening this up. If anybody has practical suggestions on how to improve this, I am all for it.
