### ISSUE TITLE
M1 Mac build? (Universal)

### ISSUE THREAD

**Issue by orphee-celui-qui-ne-sait-rien** [johannesjo/super-productivity#1516]
## Problem Statement

Hey will there be an M1 version anytime soon?

**Comment by johannesjo** [comment]
I would assume that you already can use the DMG provided on the download page. Isn't that the case?

**Comment by johannesjo** [comment]
Thanks for opening this up. I'll try to do this via electron builder, but I think that I won't dig into the subject myself too deep. So in case that doesn't work, help in figuring this out would be appreciated!

**Comment by johannesjo** [comment]
Could you maybe check the new build?
https://github.com/johannesjo/super-productivity/releases/tag/v7.6.0-rc.0
https://github.com/johannesjo/super-productivity/releases/download/v7.6.0-rc.0/superProductivity-7.6.0-rc.0-arm64.dmg

**Comment by orphee-celui-qui-ne-sait-rien** [comment]
Almost everything seems to be working fine, though I think that if I try to use the "backup" (I suppose is the data from the Intel app, but I don't really know...) That loop of errors begins. I could test some more on the weekend. 

https://user-images.githubusercontent.com/79347623/134274252-b4e1a02d-2371-4dad-bd87-2cf2cacd42f2.mov

**Comment by johannesjo** [comment]
Glad that it mostly works!  :D  I have no idea, what could have triggered the error. If you could reproduce it again, it would be super cool, if you could try to open the console and provide me with the logs from there.

**Comment by orphee-celui-qui-ne-sait-rien** [comment]
After I imported my data from the Intel app everything worked fine, there aren't any problems now, but I didn't check the console logs back then sorry. 😬

**Comment by johannesjo** [comment]
Alright! I am closing this then :)
