### ISSUE TITLE
System-wide shortcut for opening SuperProductivity isn't changed when updating settings

### ISSUE THREAD

**Issue by ThatRobVK** [johannesjo/super-productivity#152]
### Your Environment

* Version used: Snap: superproductivity 2.4.3 rev 146 tracking stable
* Operating System and version: Ubuntu 18.04
* Desktop Environment: Gnome 3.28.2
* Browser Name and version: n/a

### Expected Behavior

When I set a new global keyboard shortcut to focus SuperProductivity and save it, then I expect the old binding to stop working and the new binding to take effect.

### Current Behavior

After saving the new keyboard binding, the UI correctly shows the new binding, even after closing and re-opening Super Productivity. However the new binding doesn't work and the old binding still focuses Super Productivity.

### Steps to Reproduce (for bugs)

1. Open Super Productivity
2. Go to Settings -> Keyboard Shortcuts
3. Change the global binding to Show / Hide Super Productivity
4. Save the settings.
5. Change to a different window / workspace
6. Press the new keybinding -> nothing happens
7. Press the default keyboard binding Ctrl+Shift+X -> Super Productivity is focused.

### Console Output

No output from pressing either the new or the original key bindings.

### Error Log (Desktop only)

.config doesn't contain a folder superProductivity, so no log file present. (besides you shouldn't be logging to the config folder anyway?)

**Comment by johannesjo** [comment]
Thanks for reporting. I can confirm that this is an issue. I will work on it as soon as I can.

**Comment by johannesjo** [comment]
Should be fixed now. Please let me know if the issue persists for you.
