### ISSUE TITLE
dropbox authorization code: nothing happens AUR

### ISSUE THREAD

**Issue by jabbalaci** [johannesjo/super-productivity#1521]
SuperProductivity version: 7.5.2
Operating system: Manjaro Linux

When clicking on "Get Authorization Code" for Dropbox, nothing happens. The browser is not opened. SuperProductivity is launched in the terminal, but no debug info appears there.

Quick fix: show the URL, then I could open it manually. It may be just the button that doesn't work.

**Comment by johannesjo** [comment]
Thanks for opening this up! How did you install the app? Also what is shown if you inspect the button element (Ctrl+Shift+i to open the dev tools and then Ctrl+Shift+c and then click the button)?

**Comment by jabbalaci** [comment]
This Ctrl+Shift+c trick didn't really work for me but in the log I found these lines:

    api.dropboxapi.com/oauth2/token:1 Failed to load resource: the server responded with a status of 400 ()
    ...
    zone.js:2863 POST https://api.dropboxapi.com/oauth2/token 400

I installed the following AUR package:

```
2 aur/superproductivity-bin 7.5.2-1 (+9 1.83) (Installed)
    ToDo List / Time Tracker / Personal Jira Task Manager
```

**Comment by johannesjo** [comment]
Could you maybe test doing this [in a chromium based browser](https://app.super-productivity.com/#/tag/TODAY/tasks)? A 400 on the token url indicates that something went wrong while creating the auth url. So there is no url yet and that's why you can't click the button.

**Comment by jabbalaci** [comment]
Opening the chromium based browser you linked, the Dropbox button worked and my dropbox was opened in a new tab.

But I have a workaround. I chose a plain file, but its location is in my Dropbox. So it's still synchronized. Thanks for your help.

**Comment by johannesjo** [comment]
Thanks for checking. I assume that this has something to do with the arch version (though I don't really understand what). The arch version is not maintained by me, but someone else.

**Comment by alosarjos** [comment]
The AUR packaging process is pretty straightforward. Are we sure this isn't happening on Ubuntu or another Linux distro too?

**Comment by johannesjo** [comment]
@alosarjos thanks for checking in! :)

I've tested the snap, the appimage and the deb version and all work fine.

**Comment by alosarjos** [comment]
So I opened the app and clicked on the "Get Authorization Code" button for dropbox and it opened a dropbox page on my default browser, which I'm guessing it's the correct behaviour?

If that's the case maybe the issue comes from the config on @jabbalaci system not having correctly assinged a web browser to the mime-type?

**Comment by alosarjos** [comment]
@johannesjo From time to time I come here to see how things are if I remember, but don't be afraid to mention me whenever an arch issue pops ;)

**Comment by johannesjo** [comment]
> So I opened the app and clicked on the "Get Authorization Code" button for dropbox and it opened a dropbox page on my default browser, which I'm guessing it's the correct behaviour?

Yes it should be. 

> If that's the case maybe the issue comes from the config on @jabbalaci system not having correctly assinged a web browser to the mime-type?

That might be the case, but the 400 on the token request is weird. There is a pkce challenge generated that depends on the browser engines crypto feature. Is the arch linux version using its own browser/electron instance (as defined by the electron version) or does it hook itself onto the system browser somehow?

**Comment by alosarjos** [comment]
We are not using the system electron, but the embedded one so it should be the same as the Ubuntu deb. Again, on my Arch install it's working. So maybe @jabbalaci can provide some info on the arch install where it's failing? Default web browser, Desktop Environment and such...

**Comment by jabbalaci** [comment]
I just tried it and it works! The version was updated to 7.6.0 and now it works. When I click on the Dropbox button, the website opens and dropbox.com asks for permission. So this issue is solved.

**Comment by johannesjo** [comment]
I am glad that it works now (though still curious why it didn't before....). Thanks everybody! I am closing this.
