### ISSUE TITLE
copy URL to clipboard

### ISSUE THREAD

**Issue by jabbalaci** [johannesjo/super-productivity#1522]
## Problem Statement
I have a task and I attached a URL to it. When I show the attachments, an info panel appears on the right side. Moving the mouse on the URL attachment, 3 options appear: open URL, edit, and delete. Here I'd like to see a 4th option: copy URL to clipboard.

## Rationale

I use several web browsers, each for a specific task. When I click on open URL, then my main web browser will open this URL. However, if I use a different web browser at the moment, I would prefer to open the link there. The simplest way would be to copy the URL and then I'll open it manually in the browser in which I want.

Another use case: I want to send this URL to someone in an email. Then copying the URL would be the simplest solution.

## Workaround

A workaround solution would be to use the edit option and then copy the link without editing it. But it's more steps and when clicking on Edit, the URL is not highlighted by default. Here an easy fix would be to highlight the URL when clicking on Edit. Then Edit and Ctrl+c would do the trick.

**Comment by johannesjo** [comment]
Hey there! Thanks for opening this up. Copying to clipboard seems more like a special use case to me and I don't want to clutter the UI to be honest. But I am open for adding this via right click.

**Comment by jabbalaci** [comment]
Thanks, but not really necessary. I can do it via Editing. Some more clicks won't hurt.

**Comment by johannesjo** [comment]
I leave this open. If other people need this also, I am open for changing this.
