### ISSUE TITLE
GitLab tasks should be marked completed when the issue got closed on the server

### ISSUE THREAD

**Issue by jurgenhaas** [johannesjo/super-productivity#1524]
I have successfully linked my first GitLab project and receive all the tasks in the client. But they remain in the list of open tasks until I manually mark them as completed - even if they had been closed on the GitLab server. The client recognizes the status change but I wonder why it doesn't mark the task as completed then.

**Comment by johannesjo** [comment]
Thanks for opening this up! I am all for adding this and I made several preparations to add this. The rest api is a bit limited and there are certain rate limits so there isn't an endless amount of requests available. But maybe there is a way to batch request just the updates for the issues already on the list via the graphql api:
https://docs.gitlab.com/ee/api/graphql/

**Comment by jurgenhaas** [comment]
I do have a self-hosted GitLab instance and could give you a test account there without any rate limits, is that helps you for testing?

**Comment by johannesjo** [comment]
Thank you for the offer. If I need it, I get back to you.

**Comment by ishanarora** [comment]
> Unfortunately the rest api is a bit limited and there are certain rate limits so there isn't an endless amount of requests available, that's why only open issues are requested currently, so changes to closed ones would never appear.

Can't we make this behavious an option in the "Setup GitLab for Project", since the rate limits don't affect self-hosted instances?

**Comment by johannesjo** [comment]
> Can't we make this behavious an option in the "Setup GitLab for Project", since the rate limits don't affect self-hosted instances?

I am open for implementing this as optional (opt in) feature. PRs dealing with this are welcome.

**Comment by ishanarora** [comment]
@cbergmann might this be of interest to you?
