### ISSUE TITLE
Error: Invalid clock string

### ISSUE THREAD

**Issue by antonio-hickey** [johannesjo/super-productivity#1526]
### Steps to Reproduce

1. Not sure, had it minimized and came back to this error. I had just previously finished my
day in one of project's and switched to one of my other project's to start working on those tasks
and minimized it came back to the following error (see below)

### Stacktrace
```
Error: Invalid clock string
    at iq (file:///opt/superProductivity/resources/app.asar/dist/main.2169d5d12358f46feff8.js:1:2660861)
    at file:///opt/superProductivity/resources/app.asar/dist/main.2169d5d12358f46feff8.js:1:3321818
    at Array.forEach (<anonymous>)
    at e5 (file:///opt/superProductivity/resources/app.asar/dist/main.2169d5d12358f46feff8.js:1:3321697)
    at file:///opt/superProductivity/resources/app.asar/dist/main.2169d5d12358f46feff8.js:1:3337610
    at file:///opt/superProductivity/resources/app.asar/dist/main.2169d5d12358f46feff8.js:1:3337679
    at o.project (file:///opt/superProductivity/resources/app.asar/dist/main.2169d5d12358f46feff8.js:1:3338706)
    at o._next (file:///opt/superProductivity/resources/app.asar/dist/main.2169d5d12358f46feff8.js:1:1087618)
    at o.next (file:///opt/superProductivity/resources/app.asar/dist/main.2169d5d12358f46feff8.js:1:1075767)
    at a.debouncedNext (file:///opt/superProductivity/resources/app.asar/dist/main.2169d5d12358f46feff8.js:1:1085832)
```

### Meta Info
META: SP7.5.2 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.5.2 Chrome/91.0.4472.124 Electron/13.1.7 Safari/537.36

### Actions Before Error
```
1632100716867: [Persistence] Save to DB 
1632100716867: [Persistence] Save to DB 
1632100717830: [Task] Add time spent 
1632100717833: [Project] Update Work End 
1632100717845: [Tag] Update Work End for Tag 
1632100717851: [Persistence] Save to DB 
1632100717852: [Persistence] Save to DB 
1632100717852: [Persistence] Save to DB 
1632100718592: [Task] UnsetCurrentTask 
1632100719213: [Task] Update Task 
1632100719299: [Persistence] Save to DB 
1632100725438: [Task] Update Task 
1632100725443: [Persistence] Save to DB 
1632100727728: [Task] SetSelectedTask 
1632100739088: [Task] Move to archive 
1632100739110: [Persistence] Save to DB 
1632100739110: [Persistence] Save to DB 
1632100739111: [Persistence] Save to DB 
1632100739111: [Task] UnsetCurrentTask 
1632100739141: [Persistence] Save to DB 
1632100750200: [Layout] Toggle SideBar 
1632100752014: [Layout] Hide SideBar 
1632100756186: [Layout] Toggle SideBar 
1632100759075: [Layout] Hide SideBar 
1632100759088: [Layout] Hide SideBar 
1632100760536: [Layout] Toggle SideBar 
1632100763408: [Layout] Hide SideBar 
1632100763411: [WorkContext] Set Active Work Context 
1632100763424: [Task] SetSelectedTask 
1632100763440: [Layout] Hide SideBar
```

**Comment by johannesjo** [comment]
Thanks for reporting! I'll have a look!

**Comment by johannesjo** [comment]
Unfortunately, I wasn't able to find an obvious cause for this. The error thrown is from a helper function which is mainly used on the timeline page, but as you said, you have been on another project page. The function is used at two other places too, but it seems impossible that the error was thrown from there. 
 
Do you maybe have any additional information?

**Comment by antonio-hickey** [comment]
> Unfortunately, I wasn't able to find an obvious cause for this. The error thrown is from a helper function which is mainly used on the timeline page, but as you said, you have been on another project page. The function is used at two other places too, but it seems impossible that the error was thrown from there.
> 
> Do you maybe have any additional information?

Unfortunately not, I'm going to reinstall it and hopefully that solves it, It was working perfect for like a month. I really enjoy the application so hopefully it was just some error on my side.

**Comment by johannesjo** [comment]
Oh, you mean this happens on every startup? In this case it would be wonderful, if you maybe could share an export of your data to contact@super-productivity.com. You should be able to do so despite the error, if you navigate to settings and then Import/Export.

**Comment by antonio-hickey** [comment]
Yea when i first encountered this issue I was able to simply fix it by hitting the reload app button and everything was perfect until the next day when i finished my day again and then I was not able to get rid of it even after killing the process and restarting. I'll send it right now haven't reinstalled it yet so we are in luck.

**Comment by johannesjo** [comment]
I think I was able to fix the issue. Thank you very much for your help. The new release should be available on the slack edge channel shortly. If you don't want to use that release, you can also open up the file you send me and replace "21:00." with "21:00" and then import it again.
