### ISSUE TITLE
xprintidle does not work in snap package

### ISSUE THREAD

**Issue by endorama** [johannesjo/super-productivity#154]
### Your Environment

* Version used: 2.5.3 snap revision 170
* Operating System and version: Ubuntu 16.04.4
* Desktop Environment: Unity

### Expected Behavior

Idle checker works.

### Current Behavior

Idle checker error pop up is displayed.

### Steps to Reproduce (for bugs)
1. Install from snap
2. run it
3. install `xprintidle` system wide (`apt install ...`)
4. run it again, same result

### Console Output

no relevant console logs

### Error Log (Desktop only)

It seems that the error log for snap package is not in the mentioned location (` ~/.config/superProductivity/log.log`).

Anyway I had the same problem with the AppImage (that has been solved by installing `xprintidle` package) so I guess the error would be the same.

```
[2019-03-01 15:19:21.596] [error] Something went wrong with the idle checker. You need to install xprintidle. Error: Something went wrong with the idle checker. You need to install xprintidle.
    at Object.exports.errorHandler (/tmp/.mount_superPgm3GTb/resources/app.asar/electron/error-handler.js:10:18)
    at /tmp/.mount_superPgm3GTb/resources/app.asar/electron/get-idle-time.js:33:33
    at ChildProcess.exithandler (child_process.js:306:5)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:606:12)
```

I'm willing to help in debugging this, but I'm now sure if able.  
I looked at the Snapcraft docs about dependencies but are lacking. If someone can point me in the right direction I can try fixing this :)

Thanks for the project BTW, is super useful!

**Comment by johannesjo** [comment]
Thanks for reporting. The solution is easy fortunately. You just need to install xprintidle yourself via apt-get. 

Problem is that the snap dependency is not working correctly. I probably should document this somewhere :)

**Comment by endorama** [comment]
Thanks for the super quick response!

Unfortunately I do have it installed, but still the message appears.

>

**Comment by johannesjo** [comment]
Oh Sorry. Was reading this on my phone and didn't quite catch that. In this case I have to check :)

**Comment by johannesjo** [comment]
May I ask what the output of xprintidle is in the command line?

I would to automatically install xprintidle with the snap package, but adding any dependencies is killing the build:
https://github.com/electron-userland/electron-builder/issues/3677

**Comment by endorama** [comment]
```
$ xprintidle
42
```

So it is expected for the snap package to use the "host" `xprintidle` binary, correct?

Let me know if I can help more on this!

**Comment by johannesjo** [comment]
Ok that seems to be in order. 

Yes you're right. To be me this looks like Super Productivity doesn't have access to xprintidle for some reason. Not sure why to be honest. I will check this tomorrow.

**Comment by johannesjo** [comment]
The issue should hopefully be fixed now. I'll release a patch version soon. Please let me know if the issue persists or you discover any other.

**Comment by endorama** [comment]
I do not see the error anymore! Thanks for the quick fix!
