### ISSUE TITLE
Keep attachments on daily or reoccurring tasks.

### ISSUE THREAD

**Issue by NapAlot** [johannesjo/super-productivity#1541]
## Problem Statement
I have daily tasks that take some time to complete. They all have files locally or online, as well as websites. I use attachments to quickly navigate to these sources. It would be great for these attachments to stay on the reoccurring tasks.

## :grey_question: Possible Solution
Keep attachments linked to recurring tasks.

## :arrow_heading_up: Describe alternatives you've considered
I have tried to put them into the notes section, but for some files you have to call the application to open it locally example is: onenote:http://fileonline.contoso.com/file
excel:http://fileonline.contoso.com/file
or
onenote:C:\placeyourfilesare\file.file
excel:C:\placeyourfilesare\file.file

## :heavy_plus_sign: Additional context
While you can link to a website in the notes, you cant use system level calls "onenote:" or "exce:" etc. You can use a link that is shared in OneDrive, but some files don't need to be shared so ideally you would link to the file locally. Additionally this adds the overhead of opening through a browser that then wants us to validate etc. With the attachments you can do this all in 1 click. It works very well.

**Comment by johannesjo** [comment]
Hey there! Thanks for the suggestion! I am all for it. I would do it like it is done with the the other stuff like that, which is to add it as another input field for the task repeat config.

I also would love to make the onenote or excel links work (not sure if this is possible). Could you may open up a separate issue for this?

**Comment by NapAlot** [comment]
> Hey there! Thanks for the suggestion! I am all for it. I would do it like it is done with the the other stuff like that, which is to add it as another input field for the task repeat config.
> 
> I also would love to make the onenote or excel links work (not sure if this is possible). Could you may open up a separate issue for this?

The onenote / excel links work in the attachments. If the attachments will be attached on each reoccurrence there is no need to use the markdown description area. Microsoft TODO will do links in the title of the task. That could be a cool place to allow clicking. That or allow the attachments to be listed directly under the task.
![image](https://user-images.githubusercontent.com/53048509/134702670-992114f7-6494-44b5-9593-79af4e3f0862.png)

**Comment by johannesjo** [comment]
Ah alright. I wasn't aware that the onenote:https... links are already working.
