### ISSUE TITLE
Allow Pausing Pomodoro Breaks X Minutes

### ISSUE THREAD

**Issue by NapAlot** [johannesjo/super-productivity#1545]
## Problem Statement
I use the Pomodoro timers, I often find that before I can break I need a minute or 2 for documenting where I am for when I return.

## :grey_question: Possible Solution
I would like the ability to pause the break timer or say snooze 2 mins. The other option that would be great, maybe better, an option in settings, to "Manually confirm starting break timer." Then I could see it, go ok, 2 mins then ill pop to break. The issue I have is I often need 2 more mins then the break timer is now shorter.  Having to manually confirm it would allow having the "focus window" force you to recognize that you need to take a break, and decide to wait 2 more mins. Jumping back to timing the current task would be ideal as well.

Feature(s):

1. Manually confirm starting break timer
2. having a "delay X mins" on the break timer

## :arrow_heading_up: Describe alternatives you've considered
I have tried to rush to breaks, but this often causes things to slip through the cracks when I return.

## :heavy_plus_sign: Additional context
In the application "Focus TODO" they don't start the break until you click start break. This process was very good for my workflow. It would be great to have in SP, as its overall a superior application.

**Comment by johannesjo** [comment]
Hey there! Thanks for opening this up! I prefer the"Manually confirm starting pomodoro breaks" config option as it seems to be more straightforward. PRs are welcome! :)

**Comment by vancassa** [comment]
Hi @johannesjo may I try working on this?

**Comment by johannesjo** [comment]
@vancassa this would be great! Thanks for the offer! :)

**Comment by fluxus-collab** [comment]
> 1. Manually confirm starting break timer

Please add this. My pause starts, but i'm focused, so I'd like to delay it just a few minutes...but it's not possible. Even pause the pause is not possible.

It was possible with this application: https://github.com/gnome-pomodoro/gnome-pomodoro

The overall software is great, thank you very much for that work.
Have a nice day !
