### ISSUE TITLE
[JIRA & OpenProject] Finish day and push specific issue session rather than whole time tracked

### ISSUE THREAD

**Issue by Komediruzecki** [johannesjo/super-productivity#1547]
## Problem Statement
It is only possible to track time to Jira on finishing a task, and it calculates the time to log work for the whole task duration rather than the last instance.

## :grey_question: Possible Solution
When the task is being tracked for multiple work sessions, it would be great if super productivity will calculate only the last/current session and enter that into the work log (prompt to log work, i.e. maybe even option to subtract already logged time with time spent and use that value) rather than using all time spent on an issue.

So the requested behaviour would be:
1. Add possibility to open work log prompt on each pause of the task time tracking (not only when the issue transitions to done in Super Productivity) - this is in a manner similar to working on the issue multiple days and want to log work immediately after each day, but the issue itself is not done yet (this can be simulated to finish the issue in super productivity, log work from prompt and then reverting it back to not do - but this approach is manual and it messes the actual time spent on the issue for next day and overall populated time spent on the current session when log work prompt is opened)
2. Add possibility to calculate the populated time to log work as what is only the last session for this task (or at least already spent time on Jira - the time spent on this issue in super productivity)
3. Possibility to when clicking on Finish my day to log all work spent on issues to Jira (batch update), either with prompts or fully automatically 

## :arrow_heading_up: Describe alternatives you've considered
See in preferences if such options exist.
Using transition issue to done and then reverting it back to active.

## :heavy_plus_sign: Additional context
I am willing to implement this myself, if you guide me on how to do it, let me know if you need any more details.

**Comment by johannesjo** [comment]
Hi there! Thanks for opening this up! The calculation of the "last session" would get messy imho as there different ways to edit the time spent for Super Productivity and for Jira and both operate with different concepts (there are no sessions in super productivity, there is only time spent per day – however I think the problems would still exist even if the time models were actually the same). What is right and what is the last session might be obvious in some cases, but for others it is not. Rather than being sometimes right and sometimes confusing I'd prefer a solution that will never be surprising to the user. 

Thus I see the following options:
1. Use sub tasks each day. If as sub task takes longer than a day number them. This way you also get the satisfaction of marking something as done for good.
2. Offer a toggle button inside the time tracking Dialog that will only submit the time spent for today (the button might remember the last choice so it matches your personal style for subsequent dialogs).

Maybe there is more! I am for suggestions! :)

**Comment by Komediruzecki** [comment]
Hi, 

thanks for the detailed answer,

For 1. if you meant Jira subtasks etc. I would like to avoid it, even though tasks should be small enough so you could divide them at least by a day of work, most often than not, that is not the case.

For 2. That sounds great, if we could have per day time spent, then after the workday is over you commit only difference between when you started the task that day and when you ended it, not taking into account all previous days and their spent time.

I understand the complication with sessions, but don't you already have that in 'you are not tracking time last X minutes, what do you want to do with it?', this would be similar:

1. When I start time tracking on the Jira task, the timer is started for that day
2. When I stop the time tracking (either by setting the task as done or pausing it), the time tracker is stopped
3. In both scenarios, we could have a toggle that allows prompt for logging it into Jira

That would be a description of the session, I don't think you need to couple it with manually modifying time spent on the issue, and how it's handled is not really important, since, in that ideal situation, you would not modify it manually.

But I think 2. would do the best, for now, the most important thing is to get Jira time, get Super Productivity time spent, and subtract the two, meaning if you started the log for a new issue with no time spent, you would at the end of each day end up with the exact time spent in super productivity and logged into Jira.

**Comment by Komediruzecki** [comment]
It would also be superb if we could somehow turn off the 'Jira status update' dialogue on each session/time-track start, is this possible?

Didn't find any option for this in Jira project setup.

**Comment by paulius-sladkevicius** [comment]
My 2ct, I would like to mention the case (that really happens, but sometimes..) when you start working at 23:00 and finish the next day 1:00 and at that moment you need to log time on different days, but it could be natural that you get only 1h of work. I suppose a small workaround in such a situation would be good, could be manually set the date for which you can log and hours, so you can push that time entry.

**Comment by johannesjo** [comment]
Here is a little preview of the ui:

![Screenshot from 2021-09-28 23-19-55](https://user-images.githubusercontent.com/1456265/135167474-ad9c4ed5-2fe8-4694-8e7e-8659d28e78d6.png)


@paulius-sladkevicius not sure how to best deal with such a case tbh, but I try to thin of something.

**Comment by Komediruzecki** [comment]
Looks great,

Ability to set the default one from preferences? (or default is always last used one) would be great.

**Comment by johannesjo** [comment]
The idea is, that once you click an item from the menu, a little checkbox with "always use xyz as default" appears.

**Comment by johannesjo** [comment]
Should be ready with the next release. Let me know if this works out for you!

**Comment by paulius-sladkevicius** [comment]
> Should be ready with the next release. Let me know if this works out for you!

Great news! Let me know where I can test it out already.

**Comment by johannesjo** [comment]
The snap edge release just finished. Should be ready to test there :)
