### ISSUE TITLE
[JIRA] Turn off submit issue change in status prompt on start of task time track

### ISSUE THREAD

**Issue by Komediruzecki** [johannesjo/super-productivity#1549]
## Problem Statement
Each time a time tracking is started on Jira integrated issue, change status of the issue prompt pops out

## :grey_question: Possible Solution
Provide a preference to turn the prompt off

## :arrow_heading_up: Describe alternatives you've considered
Change properties in Advanced Jira setup - nothing worked.

**Comment by johannesjo** [comment]
Thanks for open this up! This is a feature and you can disable it by switching off transition handling in the Jira settings (or go for another option then always open dialog for "Status for starting task").

**Comment by Komediruzecki** [comment]
That is superb, found it, thanks!
