### ISSUE TITLE
Show associated project in worklog

### ISSUE THREAD

**Issue by m-kreis** [johannesjo/super-productivity#1564]
Problem:
In the worklog i can't see to which project a task belongs. Inside the project the naming of the task is clear but in the worklog without seeing the associated project it sometimes gets ambigous.

Solution:
Add the project to the listing in the backlog or provide a function to open the task (or link to the task), so one can see which task exactly it is.

**Comment by johannesjo** [comment]
Would be nice, but might be problematic in terms of space available. I am open to experiment with this though.
