### ISSUE TITLE
Broken task names selection from Worklog and Quick History

### ISSUE THREAD

**Issue by kadykov** [johannesjo/super-productivity#1573]
### Your Environment

- Version used: 7.6.0 from Microsoft Store 
- Operating System and version: Windows 10 x64
- Browser Name and version: Firefox 92.0.1 (64-bit)

### Expected Behavior

In the "Worklog" and "Quick History" windows, task names are selectable. A user could select and copy any task name or a bunch of task names and paste it into any external activity report program.

### Current Behavior

In the "Worklog" and "Quick History" windows, only time spent on a task is selectable. There is no way to copy task names from the selected date for activity reporting in an external application.

### Steps to Reproduce (for bugs)
1) Go to "Worklog" or "Quick History" windows (On the left-side panel, click three dots on the right of the "Today" item)
2) Click on any date to show all the tasks working on that day.
3) Try to select and copy any name of the task 

This behavior is valid in the desktop application and the web version.

**Comment by johannesjo** [comment]
Hi! Thanks for opening this up! This should be fixed!
