### ISSUE TITLE
CalDav Synchronization with Nextcloud not working

### ISSUE THREAD

**Issue by tubia** [johannesjo/super-productivity#1574]
### Your Environment

- Version used: superProductivity_7.6.0_amd64.deb
- Operating System and version: Linux Mint 20.2
- Desktop Environment:  Cinnamon
- Browser Name and version: 

### Expected Behavior

Adding a new project, selecting CalDav Sync, filling the base dav url, the Nextcloud user name and password and the calendar name should successfully show you the list of tasks.

### Current Behavior

Adding a new project, selecting CalDav Sync, filling the base dav url, the Nextcloud user name and password and the calendar name returns an error of failed synchronization.

### Steps to Reproduce (for bugs)

1. Add New Project
2. Select "Configure CalDav Integration"
3. Fill the fields: `baseURL`: "https://mycloud.example.org/remote.php/dav"; `CalDav resource`: "accademia" (in my case); user and password
4. Save
5. Click on the Sync button to check if the synchronization works

### Console Output

```console
Error: Not able to get rev for WebDAV
    at t._getRevFromMeta (web-dav-sync.service.ts:116)
    at t.<anonymous> (web-dav-sync.service.ts:48)
    at Generator.next (<anonymous>)
    at o (main.0726891bcbe9eeb4eb61.js:1)
    at l.invoke (zone.js:372)
    at Object.onInvoke (core.js:28672)
    at l.invoke (zone.js:371)
    at t.run (zone.js:134)
    at zone.js:1276
    at l.invokeTask (zone.js:406)
```

### Error Log (Desktop only)

```
[2021-10-09 14:30:03.002] [error] Frontend Error: { HANDLED_ERROR_PROP: 'Caldav: Error: CALENDAR NOT FOUND: accademia' } undefined
[2021-10-09 14:30:03.008] [error] Frontend Error Stack:
```

**Comment by tubia** [comment]
Dear @johannesjo thanks for your reply.

You are right, I tried in the beginning to set up the sync through the "Settings" -> "Sync" -.> "WebDav"

Now I disabled it and tried the CalDav path through the "Add New Project" -> "CalDav integration", but still no luck.

Do you have any suggestion on how to properly configure this?

**Comment by johannesjo** [comment]
I am not using the CalDAV integration myself unfortunately. I'd recommend trying to have a look at how others configured theirs, e.g.:

https://github.com/johannesjo/super-productivity/issues/1192
https://github.com/johannesjo/super-productivity/search?q=caldav&type=issues

`Caldav: Error: CALENDAR NOT FOUND: accademia` indicates to me, that there might be something wrong there. Maybe "accademia" is not the correct name, at least not in regards to it's public address.

**Comment by GalensGan** [comment]
@tubia  have you resolved the issue? I met a same error。
the metaData is:
![](https://s2.loli.net/2022/03/12/etNoulRkKzZ978Q.png)

**Comment by alacecho** [comment]
Hello!
Same issue for me. Debian testing with Appimage 7.10.1, and deb package.
Alex.

**Comment by krillin666** [comment]
I know this was done with Nextcloud in mind, however I can't setup this also for Vikunja using its caldav link

**Comment by tubia** [comment]
As a further reference, the new version continues not to work with CalDav integration. The overall sync with WebDav, accessible through the Settings, doesn't work either with Nextcloud.

I could also work myself on the issue if anyone of the dev team could point me where to look in the code.

**Comment by cloo** [comment]
Just a confirmation that the issue is still relevant.

**Comment by Petemir** [comment]
I have to say that this is working for me with the latest NextCloud and SuperProductivity versions.

How to configure:
* Create Project
* Select Caldav Integration
* Set the full calendar link as "Base URL": i.e., `https://your-nextcloud-instance.tld/remote.php/dav/calendars/$USERNAME/$CALENDARNAME/` - you can get this link from the NextCloud Tasks webview by right-clicking the project and selecting "Copy Private Link"
* Set the exact human-readable name of the resource (e.g., "Tasks", "Deck: Personal", as it appears on NextCloud's sidebar)
* Select whatever choices you want for the syncing
* Save and wait for the poll!

It would be nice to have a similar

**Comment by gitwas** [comment]
>     * Create Project
>     * Select Caldav Integration
>     * Set the full calendar link as "Base URL": i.e., `https://your-nextcloud-instance.tld/remote.php/dav/calendars/$USERNAME/$CALENDARNAME/` - you can get this link from the NextCloud Tasks webview by right-clicking the project and selecting "Copy Private Link"
>     * **_Set the exact human-readable name of the resource_** (e.g., "Tasks", "Deck: Personal", as it appears on NextCloud's sidebar)

For what it's worth, and in case anyone else is looking for answers to this problem, this worked for me.

Thanks!

**Comment by lgwapnitsky** [comment]
> > ```
> > * Create Project
> > * Select Caldav Integration
> > * Set the full calendar link as "Base URL": i.e., `https://your-nextcloud-instance.tld/remote.php/dav/calendars/$USERNAME/$CALENDARNAME/` - you can get this link from the NextCloud Tasks webview by right-clicking the project and selecting "Copy Private Link"
> > * **_Set the exact human-readable name of the resource_** (e.g., "Tasks", "Deck: Personal", as it appears on NextCloud's sidebar)
> > ```
> 
> For what it's worth, and in case anyone else is looking for answers to this problem, this worked for me.
> 
> Thanks!

Still failing for me
