### ISSUE TITLE
Webdav that works on pc doesn't work on android clients, keeps warning check console

### ISSUE THREAD

**Issue by LumenYoung** [johannesjo/super-productivity#1577]
### Your Environment

- Version used: newest from F-droid 7.6.0
- Operating System and version: android (some branch from Huawei)
- Desktop Environment:  
- Browser Name and version: 

### Expected Behavior
My sync url has successfully connected my laptop and my PC. I expect it to work the same on android.

The sync would be successful when I pressed manual sync button
### Current Behavior
It warns unexpected error and ask me to look at console

### Steps to Reproduce (for bugs)
1. Download the app from F-droid
2. Choose webdav as your sync method, and enter your sync path.

### Console Output
I tried but I cannot open console on android XD

**Comment by TangdizhiH** [comment]
It is worth mentioning that the problem has nothing to do with my sync cloud. Since I've tried to sync my data both on Nextcloud and Synology webdav server. Both configuration worked on my laptop. The error persists on Android so I assume it is a android client error. 

BTW, I'm a new comer to SP but I'm so impressed by the atheistic of SP interfaces. Thank you a lot to create such a wonderful productive tool!

**Comment by TangdizhiH** [comment]
I've also tested out Dropbox connection, which turns out the same error. Alas I cannot access the console on a android machine, otherwise I can help more about the problem diagnosis.

**Comment by TangdizhiH** [comment]
> Hello there! Thank you very much for reporting this! Tbh honest I am not very familiar with inner workings of fdroid, but I know that dropbox and the webdav integration works with the google play store verison of the app. Hopefully someone else can help with this?!
> 
> For the webdav sync you also need to consider that cross origin requets need to be allowed from the host app.super-productivity.com. Dropbox should work out of the box though.
> 
> Just for a quick test: Are you able to make dropbox work directly from your mobile browser from https://app.super-productivity.com/#/tag/TODAY/tasks ?

I've tested from the browser, try to connect to Dropbox. The same error occurs. I hope this could indicate the culprit.

**Comment by TangdizhiH** [comment]
> Well that's very weird. At least dropbox should work no problem. Is there some sort of firewall active on your phone?

No, I didn't encounter any problem of this sort on my Handy, I also checked the permission, allowed all its permission(only storage basically). So I'm also very confused why.

**Comment by johannesjo** [comment]
Can you please also check the dropbox sync from from your desktop browser?
https://app.super-productivity.com/

**Comment by TangdizhiH** [comment]
> Can you please also check the dropbox sync from from your desktop browser (just to rule out some configuration issue)? https://app.super-productivity.com/

Yes, It works on PC
