### ISSUE TITLE
Copy or duplicate entries

### ISSUE THREAD

**Issue by StewPedassle** [johannesjo/super-productivity#1579]
## Problem Statement

When creating a new regimen (e.g., an exercise plan), it is frustrating not to have a temporary template or just copy and paste an existing entry (particularly when they cannot be done as subtasks in a single recurring task)

## :grey_question: Possible Solution

Provide expected behavior of Ctrl+C/V and/or add an element to copy the user-facing existing properties (i.e., title, tags, repeat, e.g., but not parts that would cause conflict like "id")

## :arrow_heading_up: Describe alternatives you've considered

A single-entry export may be a quick implementation using mostly existing code, but would reduce UX.

## :heavy_plus_sign: Additional context

It seems there are a number of existing issues in here that are at least somewhat related:  

1. The repeating subtasks improvement mentioned in #948 
2. Export/import mentioned in #946

**Comment by johannesjo** [comment]
Thinking more about this I was wondering, what you'd expect to be copied. What about:
* sub tasks
* reminders
* time tracked to those tasks
* repeat config
* attachments
* notes

?

**Comment by StewPedassle** [comment]
Those are about all I can think of right now, provided that "time tracked"
would include estimated time. The use cases I was thinking of would be
similar to either templating or adding a batch of new tasks that share a
lot of attributes. So, even if an undesired attribute is copied, it would
be a minimal burden for me to change it.

One minor quality of life consideration would be with handling past times.
I see individually deleting each past time (*i.e.*, each individual date)
being a minor inconvenience.  Options to ease this would be to change the
existing "Time spent / Estimates" window to (1) provide "clear all time"
option or (2) have the top prior date entry appear in a constant position.
Currently, the frame resizes depending on entries (at least in the desktop
version I'm using) and distributes the entries evenly within the space, so
deleting them all requires moving the mouse each time you delete one
entry.  Putting the top at a constant position would allow someone to just
click multiple times without having to move the mouse between each click.

**Comment by Seabright22** [comment]
Just commenting to say I agree, it would be a great QoL feature to be able to copy/paste tasks and subtasks. 

A lot of what I do can be quite repetitive, but I still need to be able to track time to specfic parts of it. Being able to copy and paste a task, then rename parts of it, would be great to speed up filling in my days. Also thanks for the software, it's helped out my productivity so much!

**Comment by tchernienko** [comment]
Just my 2 cents here:
I just had to manually duplicate 8 tasks and their 7 subtasks each, so a template feature would have been definitely useful here.
The template would be attached to the project I guess but could be duplicatable to another one, or maybe add a template management menu/area/you-name-it.
A duplication feature would have done the trick as well.

Talking about duplication, kind of a pop-up menu allowing us to choose what task's data to duplicate (subtask, notes, etc) would be nice I think. Obviously the id must be different between the original and the duplicated task).
And for a better UX, what about keeping in memory the previously selected data copied to ease future duplication?

Very nice and very useful app! keep up the good work (love the "help I'm procrastinating!" section)!

Cheers
