### ISSUE TITLE
Error on tap of child task

### ISSUE THREAD

**Issue by davidyew** [johannesjo/super-productivity#1590]
Error: Uncaught (in promise): Error: Error: Cannot find focus elhandleError/<@https://app.super-productivity.com/main.eb1cb7759871775ef85b.js:1:3430585o@https://app.super-productivity.com/main.eb1cb7759871775ef85b.js:1:3427939invoke@https://app.super-productivity.com/polyfills.3f21005097f2d4ba8d4e.js:1:6534onInvoke@https://app.super-productivity.com/main.eb1cb7759871775ef85b.js:1:140387invoke@https://app.super-productivity.com/polyfills.3f21005097f2d4ba8d4e.js:1:6474run@https://app.super-productivity.com/polyfills.3f21005097f2d4ba8d4e.js:1:1933P/<@https://app.super-productivity.com/polyfills.3f21005097f2d4ba8d4e.js:1:16742invokeTask@https://app.super-productivity.com/polyfills.3f21005097f2d4ba8d4e.js:1:7152onInvokeTask@https://app.super-productivity.com/main.eb1cb7759871775ef85b.js:1:140203invokeTask@https://app.super-productivity.com/polyfills.3f21005097f2d4ba8d4e.js:1:7073runTask@https://app.super-productivity.com/polyfills.3f21005097f2d4ba8d4e.js:1:2548m@https://app.super-productivity.com/polyfills.3f21005097f2d4ba8d4e.js:1:9146invokeTask@https://app.super-productivity.com/polyfills.3f21005097f2d4ba8d4e.js:1:8231_@https://app.super-productivity.com/polyfills.3f21005097f2d4ba8d4e.js:1:20135k@https://app.super-productivity.com/polyfills.3f21005097f2d4ba8d4e.js:1:20381

### Steps to Reproduce

1. I had created subtasks.
2. I view the parent task. 
3. I set a schedule for the parent task
4. I tap child task

### Stacktrace
```
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1213:30)
makeResolver (webpack:///node_modules/zone.js/fesm2015/zone.js:1120:31)
toString (https://app.super-productivity.com/main.eb1cb7759871775ef85b.js:1:3427958)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.js:28672:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:371:51)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:134:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1276:35)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:30)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:28659:32)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:405:59)
task._transitionTo (webpack:///node_modules/zone.js/fesm2015/zone.js:178:46)
drainMicroTaskQueue (webpack:///node_modules/zone.js/fesm2015/zone.js:582:34)
task.zone.runTask (webpack:///node_modules/zone.js/fesm2015/zone.js:491:20)
callback (webpack:///node_modules/zone.js/fesm2015/zone.js:1600:13)
globalZoneAwareCallback (webpack:///node_modules/zone.js/fesm2015/zone.js:1626:27)
```

### Meta Info
META: SP7.6.0 Browser – en-SG – Linux aarch64 – Mozilla/5.0 (Android 10; Mobile; rv:93.0) Gecko/93.0 Firefox/93.0

### Actions Before Error
```
1634432746487: [Layout] Hide AddTaskBar 
1634432747362: [Task] SetSelectedTask 
1634432750329: [Task] Add SubTask 
1634432750336: [Persistence] Save to DB 
1634432751601: [Task] SetSelectedTask 
1634432773896: [Task] Update Task 
1634432773907: [Persistence] Save to DB 
1634432773931: [Task] SetSelectedTask 
1634432788028: [Task] Add SubTask 
1634432788038: [Persistence] Save to DB 
1634432789904: [Task] SetSelectedTask 
1634432804635: [Task] Update Task 
1634432804642: [Persistence] Save to DB 
1634432804658: [Task] SetSelectedTask 
1634432811101: [Task] Add SubTask 
1634432811106: [Persistence] Save to DB 
1634432812564: [Task] SetSelectedTask 
1634432841731: [Task] Update Task 
1634432841742: [Persistence] Save to DB 
1634432864076: [Task] SetSelectedTask (2) 
1634432866698: [Task] Toggle Show Sub Tasks 
1634432866704: [Persistence] Save to DB 
1634432868600: [Task] SetSelectedTask 
1634432894146: [Task] Schedule 
1634432894157: [Persistence] Save to DB (2) 
1634432894159: [Task] Update Task 
1634432894165: [Project] Auto Move Task from today to backlog 
1634432894196: [Persistence] Save to DB (2) 
1634432902814: [Task] Update Task Ui 
1634432902818: [Persistence] Save to DB
```

**Comment by johannesjo** [comment]
Looks like you're using firefox. I personally don't do any optimizations and fixes for FF since the app mainly runs on chromium based platforms. PRs are welcome however.
