### ISSUE TITLE
Track time remainder

### ISSUE THREAD

**Issue by Gontran08** [johannesjo/super-productivity#16]
Would it be possible to add a remainder when we forget to track our time ? I'm thinking of something similar to Toggl. I often forget to track my time.

Your application is awesome by the way. I'm a Linux user and it's by far more beautiful than the client provided by Toggl.

**Comment by johannesjo** [comment]
Hey there! I'm very happy to hear that you like the tool! I've been thinking about implementing reminders in general, but haven't made a decision yet, as this would bloat the ui a little further. Personally I rarely forget to to track the time, because it's starting to track automatically once I hit the play button on a task. If you're on GNOME the companion extension might be helpful:
https://github.com/johannesjo/gnome-shell-extension-super-productivity

**Comment by Gontran08** [comment]
Nice, I'll try it.

**Comment by johannesjo** [comment]
Let me know if that solves your problem, if not I'll think about a better solution.

**Comment by Gontran08** [comment]
I can't make it works using Ubuntu 17.10.

**Comment by Gontran08** [comment]
After running the command, the plugin is still not available in Gnome Tweak Tools so I can't enable it.

There is also a ` at the end of the command, is it normal ?

**Comment by johannesjo** [comment]
No, thanks for mentioning it. Does it work without the ` ?

**Comment by Gontran08** [comment]
No, it creates a strange behaviour and the command seems to not be executed properly.

**Comment by johannesjo** [comment]
Can you describe the strange behavior and post the output of the command?

**Comment by Gontran08** [comment]
The command works fine if I remove the `.
![capture d ecran de 2017-11-24 11-55-32](https://user-images.githubusercontent.com/7196461/33219093-7bfbc72a-d10e-11e7-8d74-c4837f1fb083.png)
But the plugin never show up in the Gnome Tweak Tool.
![capture d ecran de 2017-11-24 11-54-04](https://user-images.githubusercontent.com/7196461/33219040-3b0b04d8-d10e-11e7-806a-9e99715a2af7.png)

**Comment by johannesjo** [comment]
My bad. The command should actually be:
```
```
cd tmp
git clone git@github.com:johannesjo/gnome-shell-extension-super-productivity.git
mv gnome-shell-extension-super-productivity /home/$(whoami)/.local/share/gnome-shell/extensions/indicator@johannes.super-productivity.com
```

**Comment by johannesjo** [comment]
Closing this for now. Let me know if you have any further issues.
