### ISSUE TITLE
Feature Request: Milestones

### ISSUE THREAD

**Issue by TobiasDev** [johannesjo/super-productivity#160]
I love that I can have a project manager only locally, and that it supports Pomodoro, it makes me really happy. I was wondering though if you could add support for milestones. So I can add tasks into different milestones, to better plan my large projects.

**Comment by johannesjo** [comment]
Hey there! Thanks for taking your time to open up this issue. To be honest personally I don't have the need for such a feature at the moment, so I probably won't implement the feature myself. I'm always open for Pull Requests though.

**Comment by johannesjo** [comment]
I'm closing this for now as there is not much resonance so far.
