### ISSUE TITLE
create Github/Gitlab Markdown subtask as actual subtasks

### ISSUE THREAD

**Issue by BlackScorp** [johannesjo/super-productivity#1606]
## Problem Statement
Currently the main Project management is made in my case in github Projects, there i can transform tasks into issues with subtasks which are defined as markdown. I assumed that those subtask will be created in super productivity as subtasks as well.

## :grey_question: Possible Solution
Parse the body for markdown checkboxes and create subtasks based on this checkboxes

**Comment by BlackScorp** [comment]
Well it is actually nothing special

here you can an exmaple ticket which i converted from the Github Kanaban Board

https://github.com/Opentribes/Game/issues/2

the subtask are actually just markdown [x] or [] checkboxes 

since you already have a markdown parser in your code i assumed it will be just, detect a list from github/gitlab issue, check if there is a checkbox and create a subtask with the title of the checkbox

**Comment by fam4r** [comment]
I am interested in that feature too, I think it makes sense
