### ISSUE TITLE
Add shortsyntax for scheduling tasks

### ISSUE THREAD

**Issue by johannesjo** [johannesjo/super-productivity#1610]
As discussed here:
https://github.com/johannesjo/super-productivity/discussions/1604
-----

For the plannedAt vs remindAt - I'm very open-minded. Setting both to the same would probably be fine but perhaps there could be a new setting (either global or per-project) which sets the default time before plannedAt for 
reminders.

On the syntax, I personally like the use of '@' I'd be saying 'at time' but I know it's also freuqently used these days for tagging a person. The `todo.txt` approach is using `due:` but the granularity seems to be only date and not time.

Whether the special keyword is `@` or `due:` (or maybe `rem:` for remindAt?), I think it would be good to use ISO (almost) Formatted time myself (e.g. YYYY-MM-DD HH:mm)  with support for just 'HH:mm' for stuff today. Maybe a special keyword of 'tomorrow' as well?
It could be worth looking at something like [Chrono](https://github.com/wanasit/chrono) to parse human readable strings but this could get messy and overcomplcated. However in my experience date and time is just plain messy and we will very quickly need to consider things like expressing time in 12 hour as AM/PM vs the _proper_ way
So for example:
`Do something +myproject #tagIt @23:00`
`Another thing +bigproject @2021-10-31 09:15`
OR
`Etwas anders +BLAH #wichtig due:2021-12-01 10:00 rem: 45m`

Just ideas at the moment :-)

I can just about understand what the code it doing but I have very little experience with NodeJS and not even a new enough version of it for development at the moment. If I can find some time I might have a go, but I'm likely to be more useful for ideas and testing.

_Originally posted by @JonathanH-UK in https://github.com/johannesjo/super-productivity/discussions/1604#discussioncomment-1510856_

**Comment by Greg-Lim** [comment]
I like "due:"
<task> due:5day
<task> due:nextmon
<task> due:25apr     or     due:25[-/.,]04

**Comment by JonathanH-UK** [comment]
Definitely still interested in this one :+1: @johannesjo Please message me if I can help to sponsor it.

**Comment by JonathanH-UK** [comment]
Still relevant :pray:  :smile:

**Comment by johannesjo** [comment]
This is now possible via the `@` syntax and thanks to @LordJABA <3
