### ISSUE TITLE
Advanced break adjustments

### ISSUE THREAD

**Issue by johannesjo** [johannesjo/super-productivity#1617]
So I spent a little bit more time on this. I found that the break time itself, might not be to helpful. Instead I think that it's more about taking good breaks and to find out why they are good. Here is a rough concept I wrote down. Please share your thoughts on this! :)

# advanced & simple break tracking

## simple tracking

Mostly as is, but on a global level (currently breaks are saved for the currently active project which is not working well).

### Why

Simple indicator to quickly compare how much time was spent on breaks today and over time

### How

perDay:
amountOfBreaks
timeSpentOnBreaks

=> editable from daily summary
=> affected by advanced break tracking, if data is available

### Why

To learn more about ones break taking patterns and possibly improve them.

### How

As on optional (opt-in) productivity feature, based around several UI elements:

#### Dialog

You took a break
How long did it last? => time
How was your break? =>  😀 😐 ☹️
Why was your break 😀? => free text

#### Button

Placed on the top right, next to the play button. Manually add a new break. Indicates the number of breaks and/or time for today.

(maybe) right click allows to edit past breaks? 

(maybe) speed dial to access Break Overview Page

#### Break Overview Page

Shows all breaks and their data sorted by 😀

#### Daily Summary "Breaks" Tab

Provides a quick glance at all of todays breaks.

#### Metric Page

Should contain a section to provide data over time. Maybe provide graphs to indicate relations between data.

#### Quick History Page

Show amount of 😀 😐 ☹️ breaks. Show amount of breaks and time spent on them.

_Originally posted by @johannesjo in https://github.com/johannesjo/super-productivity/issues/1451#issuecomment-922323437_

**Comment by papernoise** [comment]
My two (highly subjective and personal) cent: I like to be reminded to take a break, but I don't use any of the statistical features. I don't really care how much time I spend on breaks, I just need something to remind me to take them

**Comment by johannesjo** [comment]
Same for me most of the time, but sometimes I struggle to actually stick to taking them and for these cases it might be good to have a tool to reflect on that, though I admit that the approach above might not be the only solution. Maybe it's rather something than can be dealt with from the daily evaluation and possibly it might be helpful to make that a little smoother instead :)
