### ISSUE TITLE
Application blurred on Wayland with HiDPI scale

### ISSUE THREAD

**Issue by renyuneyun** [johannesjo/super-productivity#1618]
### Your Environment

- Version used: 7.6.0 ([AUR package `superproductivity-bin`](https://aur.archlinux.org/packages/superproductivity-bin/))
- Operating System and version: archlinux on linux 5.10.75
- Desktop Environment: KDE Plasma 5
- Browser Name and version: N/A

### Expected Behavior

The application should not be blurred.

### Current Behavior

Everything is blurred: text, images (icons), etc. Looks like scaling from 100% to 200%, rather than natively supporting scaling on Wayland.
It works correctly on X11 with 200% scale, though.

### Steps to Reproduce (for bugs)

1. Start DE on Wayland sessions, with scale set to 200% (for HiDPI)
2. Start SuperProductivity

### Console Output

Not related

### Error Log (Desktop only)

Not related

**Comment by alosarjos** [comment]
@renyuneyun  It will probably launch it without window decorations because electron doesn't have support for them on wayland natively, but could you try launching the app like this:

`superproductivity --enable-features=UseOzonePlatform --ozone-platform=wayland`

And see if it looks ok at least? I don't have a HiDPI display to test, but with those flags it should run natively on Wayland instead of XWayland

**Comment by renyuneyun** [comment]
@alosarjos Thanks for the tip! It works on my side.
But there is one difference in the behaviour without the argument: mine has window decorations. Probably KDE/Plasma did something special. Anyway, that's minor difference.

However, it introduces a new issue: Fcitx doesn't work any more. It works on superproductivity without those arguments, and also on other Wayland applications (e.g. Dolphin, Firefox, etc). Maybe I should open another issue, but just in case there are immediate suggestions.

**Comment by alosarjos** [comment]
> @alosarjos Thanks for the tip! It works on my side. But there is one difference in the behaviour without the argument: mine has window decorations. Probably KDE/Plasma did something special. Anyway, that's minor difference.
> 
> However, it introduces a new issue: Fcitx doesn't work any more. It works on superproductivity without those arguments, and also on other Wayland applications (e.g. Dolphin, Firefox, etc). Maybe I should open another issue, but just in case there are immediate suggestions.

I'm glad that somehow worked.

The Window decoration works fone on Xorg or XWayland, but with those flags is still working for you?

For the Fcitx thing.... I didn't even know what it was. Seems to be some input framework for asian languages?
I can't help you there sorry.

**Comment by alosarjos** [comment]
Maybe you can try with? All I could do is bring some google results, but since I can't test it I don't think I can help much on the matter

`QT_IM_MODULE=fcitx superproductivity --enable-features=UseOzonePlatform --ozone-platform=wayland`

**Comment by renyuneyun** [comment]
> The Window decoration works fone on Xorg or XWayland, but with those flags is still working for you?

Yes, it always works, for Xorg, XWayland, and with those flags.

Regarding Fcitx, thanks anyway for the help. Yes, it's for Asian languages (Chinese in my case). The `QT_IM_MODULE` environment variable (and a few others) was set already, otherwise it won't work in the first place.
I did some brief searches, and none of the results helped me so far.
Anyway, thanks for your help!

**Comment by johannesjo** [comment]
Imho wayland is (still) not ready for prime time yet, so I'd recommend sticking with X for the time being :)

**Comment by renyuneyun** [comment]
@johannesjo I'm not sure if that is still the case now. As far as I know, DEs and distros are / have been switching to Wayland.

Gnome has been using Wayland as the default option for quite some time; KDE [plan to make "Wayland shine"](https://www.phoronix.com/scan.php?page=news_item&px=KDE-2022-Roadmap) in its roadmap for 2022.
Ubuntu started to ship with Wayland by default [since 21.04](https://www.omgubuntu.co.uk/2021/01/ubuntu-21-04-will-use-wayland-by-default); Fedora was [using Wayland by default since Fedora 25](https://docs.fedoraproject.org/en-US/quick-docs/configuring-xorg-as-default-gnome-session/) (in 2016; of course, probably because of Gnome).

And from personal experience, I experience some graphics bugs on X11, while they did not appear in Wayland. Of course, Wayland has its own issues on my machine...

**Comment by alosarjos** [comment]
The truth is that Wayland is pretty usable and pretty close to becoming
the default for most things desktop related.

But Electron support for Wayland is still a work in progress. As long as
Electron dependency updated from time to time, there isn't much to be done
on this specific app.
