### ISSUE TITLE
[Enhancement] Enable worklog export on a task/parent task level

### ISSUE THREAD

**Issue by theCalcaholic** [johannesjo/super-productivity#162]
It would be very useful to have the option to export the worklog a table of tasks (instead of grouping tasks by day).

This would make further analysis of the data more flexible.

**Comment by johannesjo** [comment]
Thanks for your input. Not quite sure what you mean by that unfortunately. Could you elaborate what you mean? You'd like to have a complete csv dump? Or something else?

**Comment by theCalcaholic** [comment]
Sure, let me give an example:

Currently, you get a list containing one day per row, e.g.

        Date;End;Worked;Titles
        2019-04-17;15:00;2h 30m;my ticket 1 | my ticket 2 | my ticket 3;

It would be nice to have a way of getting the data split by task, e.g.:

       Date;End;Worked;Titles
       2019-04-17;12:10;20m;my ticket 1
       2019-04-17;13:30;1h 20m;my ticket 2
       2019-04-17;15:00;1h 30m;my ticket 3

A possible implementation would be a "group by"-Dropdown menu in the export dialog with the options 'day' 'parent task' 'none'

**Comment by theCalcaholic** [comment]
Would you be open for a PR implementing this feature?

**Comment by johannesjo** [comment]
Yes! This would be great! :)

**Comment by theCalcaholic** [comment]
Alright, let me see what I can do :)

**Comment by johannesjo** [comment]
Thanks again for your effort! Very cool to have the feature on board!
