### ISSUE TITLE
[FR] Option to disable animation

### ISSUE THREAD

**Issue by mizzunet** [johannesjo/super-productivity#1620]
## Problem Statement

Sometimes, it feels better not to have animation, to feel everything instant.
## :grey_question: Possible Solution

An option in the settings to disable animations
## :arrow_heading_up: Describe alternatives you've considered

uhm, nothing
## :heavy_plus_sign: Additional context

Thank you very much for making such an awesome program )))

**Comment by 06000208** [comment]
I would appreciate this. Being able to disable animations, which are quite present throughout the app, is a common accessibility feature. Unsure if I'll have free time to do this myself, but if I can, I'll follow up to say that I'm working on it.

**Comment by nkrot** [comment]
@06000208 , how is it going? did you have chance to work on this amazing and definitely necessary feature?

**Comment by 06000208** [comment]
@nkrot Unfortunately no, I haven't, and I don't think I'm likely to do so. My apologies.

A possible temporary fix would be using this css with a usercss extension such as [stylus](https://add0n.com/stylus.html), but I haven't tested it.

```
* {
  transition: none !important;
  animation: none !important;
}
```

**Comment by johannesjo** [comment]
Ah yes, that is a good idea. If you're using the desktop version You can put this into the a new file called `styles.css` in the  user data folder of super productivity (different for every OS, but should be shown on the global settings page under automatic backups.

**Comment by johannesjo** [comment]
I added an option that allows to disable most animations. There still some left for angular material. PRs dealing with that are welcome.
