### ISSUE TITLE
pomodoro timer and normal timer button same time 

### ISSUE THREAD

**Issue by Eikosa** [johannesjo/super-productivity#1621]
It would be nice if the pomodoro timer and the normal timer could be at the menu same time

**Comment by lukas-conlance** [comment]
Hi 👋 
I think the proposal makes sense and would be useful for me (and probably others who use the pomodoro timer, too). The point is, i guess, that there are tasks which don't require a pomodoro timer (small/short tasks or tasks for meetings, which i use to plan my day, too). So it'd be nice to be able to use it if necessary, if not just simply track the time.

I'd be very happy to have this 🙂
