### ISSUE TITLE
Hiding completed task. 

### ISSUE THREAD

**Issue by kturan** [johannesjo/super-productivity#1625]
Hi, 
It could be convenient for user to have hide completed task option. 
Best,

**Comment by Noblepal** [comment]
I need this feature too, also not count completed tasks on the Today tag
![Screenshot_20220105_200338](https://user-images.githubusercontent.com/20543843/148258361-855def70-963e-4077-9090-f971d62d1c05.png)

**Comment by Seanmcn** [comment]
I'd also like this if possible!

**Comment by johannesjo** [comment]
I think we could simply use an accordion for this purpose (and possibly persist the choice to the local storage)

**Comment by nicola-lunghi** [comment]
I need this!!! I am forced to delete tasks to hide them!!!

**Comment by johannesjo** [comment]
> I need this!!! I am forced to delete tasks to hide them!!!

No, you don't have to delete them. You need to click "Finish day" and then "Save and go home" and all done tasks will disappear from the list.
