### ISSUE TITLE
Request to add CODE_OF_CONDUCT.md file

### ISSUE THREAD

**Issue by Jassi10000** [johannesjo/super-productivity#1631]
## Problem Statement

@johannesjo 
Sir  , I have opened this issue in reference to issue no . #1630 

To write a meaningful and professional github action , I need a CODE_OF_CONDUCT.md file which is currently lacking from the repository . Please assign me this issue so that I can add the CODE_OF_CONDUCT.md file and then proceed further to write a meaninful github action for the repository.

**Comment by Jassi10000** [comment]
@johannesjo Can you please assign me this , so that after merging I can go ahead with the gh action for this repo

**Comment by johannesjo** [comment]
Hey @Jassi10000 ! I don't quite understand how adding a CODE_OF_CONDUCT ist related to adding a github action. Could you maybe elaborate? Do you want to link it?

So far I didn't encounter any problems with bad behavior so I don't think this is necessary. There is a very short section in the CONTRIBUTING.md which is good enough I think:

```
### Code of conduct
Don't be a d***!
```

**Comment by Jassi10000** [comment]
No issues , sir if you don't want 
I will not put it 

Generally , other repo maintainers prefer this in github action to indicate to new contributors to repo , but anyways 
I respect your opinion , its good this way too 🤘

**Comment by johannesjo** [comment]
Thanks @Jassi10000 ! I think it is not needed at this time.
