### ISSUE TITLE
Error "Bad Request" on import task from jira

### ISSUE THREAD

**Issue by gregorwebmaster** [johannesjo/super-productivity#1632]
### Your Environment

Windows 11, 
desktop App v7.6.0

Jira cloud version

### Expected Behavior
i can import tasks from Jira

### Current Behavior

Error "Bad Request" on import task from jira

### Steps to Reproduce (for bugs)

1. Go to settings
2. enable Jira
3. put credentials with token
4. select  'use personal Acces Tocken ..."
5. set JQL filter: "assignee = currentUser()"
6. save settings

### Console Output

jira-api.service.ts:571 JIRA_RESPONSE_ERROR {error: Error: Bad Request
    at C:\Program Files\WindowsApps\53707johannesjo.SuperProductivity_7.6.0.0_x6…, requestId: "search__POST__ypZ76XuFx"} {requestInit: {…}, jiraCfg: {…}, transform: ƒ, resolve: ƒ, reject: ƒ, …}
_handleResponse @ jira-api.service.ts:571
(anonymous) @ jira-api.service.ts:103
emit @ events.js:315
onMessage @ electron/js2c/renderer_init.js:93
jira-api.service.ts:452 {error: Error: Bad Request
    at C:\Program Files\WindowsApps\53707johannesjo.SuperProductivity_7.6.0.0_x6…, requestId: "search__POST__ypZ76XuFx"}
jira-api.service.ts:453 Bad Request
global-error-handler.class.ts:36 GLOBAL_ERROR_HANDLER {HANDLED_ERROR_PROP: "Jira: Bad Request"}

**Comment by johannesjo** [comment]
Thanks for opening this up. Pull Requests dealing with this are welcome!

**Comment by agilare** [comment]
Hello,

In my Superproductivity desktop version 7.12.0 (on Windows 10) I encountered the same problem, with exactly the same configuration as @gregorwebmaster and result error "Bad Request"
My console : 
```
jira-api.service.ts:575 JIRA_RESPONSE_ERROR Object Object
_handleResponse @ jira-api.service.ts:575
jira-api.service.ts:452 Objecterror: Error: Bad Request
    at C:\Program Files\WindowsApps\53707johannesjo.SuperProductivity_7.12.0.0_x64__ch45amy23cdv6\app\resources\app.asar\electron\jira.js:42:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)requestId: "search__POST__236xYhnsrw-V1OGKljSSZ"[[Prototype]]: Object
jira-api.service.ts:453 Bad Request
global-error-handler.class.ts:33 GLOBAL_ERROR_HANDLER Object
(anonymous) @ global-error-handler.class.ts:33
persistence.service.ts:338 LOAD COMPLETE false
model-version.ts:36 [M] Migrating model "Improvement" to version from undefined to 1 {ids: Array(0), entities: {…}, hideDay: null, hiddenImprovementBannerItems: Array(0)}entities: {}hiddenImprovementBannerItems: []hideDay: nullids: [][[Prototype]]: Object
model-version.ts:36 [M] Migrating model "Obstruction" to version from undefined to 1 {ids: Array(0), entities: {…}}
```
