### ISSUE TITLE
Iphone styling issue

### ISSUE THREAD

**Issue by johannesjo** [johannesjo/super-productivity#1650]
![247E8C67-E23C-48E4-8B8F-DD59DE342021](https://user-images.githubusercontent.com/39505348/139952563-8d70df75-1817-43cb-a2ea-b33118166855.png)
When viewing a task on iPhone app the menu button overlaps the task description making the back button unusable. 
version 7.6.0
iOS 14.7.1

_Originally posted by @stephencork in https://github.com/johannesjo/super-productivity/discussions/1649_

**Comment by johannesjo** [comment]
PRs would be welcome!

**Comment by stephencork** [comment]
Here us a screen video of the issue. 
https://user-images.githubusercontent.com/39505348/141174664-c5c01e9b-8893-4ac8-b38d-b40dcbd25def.MOV

Have the menu layers been assigned the wrong movement function?

**Comment by johannesjo** [comment]
Thanks for the offer @stephencork ! I might take you up on it, as soon as I find the time to work on this. Meanwhile PRs are welcome!

**Comment by stephencork** [comment]
Hi Jo, 
    This issue is still current, when viewing a tasks page

https://user-images.githubusercontent.com/39505348/157981061-8d8ca5b9-8caf-4e49-92d9-a7df917e8d71.mov
![IMG_EB1C21815232-1](https://user-images.githubusercontent.com/39505348/157981565-add780a4-5964-471f-b9d2-77ba4092ca61.jpeg)

Super productivity app version 7.10.1 on Iphone SE version 15.3.1

**Comment by WantToLearnJapanese** [comment]
Where should I start digging to fix this?

**Comment by johannesjo** [comment]
We're using material icons, so googleing for something like that might help:
https://www.google.com/search?q=material+icons+not+rendering+on+i+phone&oq=material+icons+not+rendering+on+i+phone&aqs=chrome..69i57j0i22i30.5052j0j1&sourceid=chrome&ie=UTF-8
