### ISSUE TITLE
CORS Error on apache WebDAV server

### ISSUE THREAD

**Issue by Jayy001** [johannesjo/super-productivity#1651]
### Your Environment

- Version used: Latest docker version
- Operating System and version:
- Desktop Environment: Ubuntu 20 (Server)
- Browser Name and version: Chrome (Client)

### Expected Behavior

Should sync without any errors

### Current Behavior

Gives a CORS error when trying to connect, however, the OPTIONS request has a 200 response code.

### Steps to Reproduce (for bugs)

1. Setup apache web server (https://www.digitalocean.com/community/tutorials/how-to-install-the-apache-web-server-on-ubuntu-20-04)
2.  Setup DAV on apache (https://www.digitalocean.com/community/tutorials/how-to-configure-webdav-access-with-apache-on-ubuntu-20-04)
3. Connect to WebDAV sync server with super producitvity

### Console Output

Access to XMLHttpRequest at 'http://myip/my-sync-file.json' from origin 'http://myip.me' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

## Any other info

The other request (OPTIONS) to the my-sync-file.json works fine so I'm not really sure whats going on, I've also set up this as my apache config:

```
DavLockDB /usr/local/apache/var/DavLock

<VirtualHost *:3000>
    ServerAdmin webmaster@localhost
    ServerName domain
    ServerAlias domain
    DocumentRoot domain
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
    Alias /webdav /var/www/webdav

    <Directory /var/www/webdav>
        DAV On
        Header add Access-Control-Allow-Methods: "GET,POST,OPTIONS,DELETE,PUT"
        Header add Access-Control-Allow-Headers: "Content-Type"
        Header onsuccess unset Access-Control-Allow-Origin
        Header always set Access-Control-Allow-Origin "*"
        AuthType Digest
        AuthName "webdav"
        AuthUserFile /usr/local/apache/var/users.password
        Require valid-user
    </Directory>
</VirtualHost>
```

**Comment by johannesjo** [comment]
Hi there! Looks like a server configuration issue. As the message states: You need to allow cors access from your one domain to the other. Alternatively you can use the desktop version, where these cors checks are not executed.
