### ISSUE TITLE
Filter in a Project on Task which do NOT have a certain tag

### ISSUE THREAD

**Issue by yennor** [johannesjo/super-productivity#1657]
## Problem Statement
When I bill a task I mark it with the tag "Billed", so I now I've sent the bill to the customer.
But now it can happen that a project has dozens of tasks or even around 100, which get billed at different points of time. 
So it can be a bit annoying to find unbilled tasks. Or also on the global level, sometimes you forget to write bills. It would be great if you could just see all tasks which aren't billed yet on a global level, but also on a project level.

## :grey_question: Possible Solution
So it would be great if I could find inside a project (not only globally), all Tasks which do NOT have the tag "Billed". So I can bill them.
It would be even greater, if somehow it would be possible to show how much time in a project I've spend in total on all the task which are not "Billed". Since one of my customers wants me to send a bill after every 25 hours I've worked for him and one other gives me a certain budget, and if I cross that, he needs to ask management for more money.

## :arrow_heading_up: Describe alternatives you've considered
My solution with the tags are a bit awkward (especially since its also a bit cumbersome to edit tags). Obviously one could add besides the Completed/Not Completed Hook, also a "Billed" Hook, but I don't think the problem is that comon, that everybody want to see that hook.
Otherwise one could add a general solution, where users can choose tags, which they can activate/deactivate with a hook directly on the task.

**Comment by johannesjo** [comment]
Hey there! Thanks for opening this up. This is probably not trivial to implement, but I am open to evaluate this further.
