### ISSUE TITLE
2 pomodoro timers with 2 different durations

### ISSUE THREAD

**Issue by arrobeselias** [johannesjo/super-productivity#1659]
## Problem Statement
I do very different kind of work, study. Some tasks I perform very good with 1h pomodoro, others I need 1h30 etc. So I'm constantly changing the pomodoro timer on the settings

## :grey_question: Possible Solution
I think would be nice to add an option to add multiple pomodoro timers just like the simple couter features

## :arrow_heading_up: Describe alternatives you've considered
Also add the timer option on the simple counter

## :heavy_plus_sign: Additional context
...

**Comment by johannesjo** [comment]
Thank you very much for the suggestion! The use case feels a bit specific to me, but in case more people like to see this and someone is willing to provide a PR for this, I am open for implementing this.

**Comment by arrobeselias** [comment]
It's still is. Is a pain in the ass to change the pomodoro time bc I change
a subject bc there is stuffs I can go 2h straight and others I have to stop
every 25 minutes

Em ter, 8 de mar de 2022 22:57, github-actions[bot] <
***@***.***> escreveu:
