### ISSUE TITLE
Ability to split idle/untracked time between multiple tasks

### ISSUE THREAD

**Issue by pcmind** [johannesjo/super-productivity#1660]
## Problem Statement

I usually do a break or go to lunch without touching the app so when I come back, an idle dialog to track idle time is displayed. If I forget to deal with it right away and start working, later I want to split idle time between break and task(s). Usually what I do is **skip** or **break** that time, and edit tasks manually to add approximate time used on it.

This problem applies also to *untrack time* button (when no task is been tracked); to be able to split that time into multiple tasks instead of dismiss and adding it manually to each task. 

## :grey_question: Possible Solution

A solution would be to add a split button on both dialogs to split time between multiple tasks/breaks, then specifying task name and time for each part.

## :arrow_heading_up: Describe alternatives you've considered

The solution specified by #1451 does only considers **break** classification and this one on a way to split time more efficiently between tasks/breaks  but not change the way data is saved.

**Comment by johannesjo** [comment]
Thanks for the suggestion! Would be nice to have this, though I am not sure how this could be done elegantly ui wise.

**Comment by pcmind** [comment]
The ui part is also my issue because at least one time slot must not be a fixed one. I have been playing with it, but did not yet found a good result:

![anim](https://user-images.githubusercontent.com/1518154/141007725-fb31e769-6863-4c68-8820-473d5d790400.gif)

**Comment by johannesjo** [comment]
That's an impressive mockup! Thank you very much. Possibly we just stop the idle time once the split button is clicked?

**Comment by pcmind** [comment]
Stopping the clock would simplify greatly the UI because: only one way would be required to input task/breaks. But if we do so, after spliting part of total idle time, we won't be able to track remaining time on task X (the behavior that "TASK" button has nowadays). 
I we opt for a fixed time frame, the split button could even "SKIP" the idle time, close idle dialog and open a new one with the logic to split the last time that was present in idle dialog.

**Comment by johannesjo** [comment]
Thanks again for your input! This should be available with the next (edge) release. Please let me know what you think!

**Comment by pcmind** [comment]
I've just tested it from master and It is very nice. Thank you. Continue with the excellent work.

**Comment by johannesjo** [comment]
Thanks for testing! I am closing this then!
