### ISSUE TITLE
Error: Uncaught (in promise): Error: No in memory copy yet

### ISSUE THREAD

**Issue by Jogiio** [johannesjo/super-productivity#1661]
### Steps to Reproduce

1. Open the App
2. Bug Shown

### Console Output

Error: Uncaught (in promise): Error: No in memory copy yetError: No in memory copy yet    at t._updateInMemory (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.6.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.4297b2fe74deb2892f3c.js:1:1825353)    at t. (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.6.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.4297b2fe74deb2892f3c.js:1:1824524)    at Generator.next ()    at o (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.6.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.4297b2fe74deb2892f3c.js:1:1815342)    at l.invoke (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.6.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.abfdc861161db4a49294.js:1:6534)    at Object.onInvoke (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.6.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.4297b2fe74deb2892f3c.js:1:140387)    at l.invoke (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.6.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.abfdc861161db4a49294.js:1:6474)    at t.run (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.6.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.abfdc861161db4a49294.js:1:1933)    at file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.6.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.abfdc861161db4a49294.js:1:16742    at l.invokeTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.6.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.abfdc861161db4a49294.js:1:7152)

### Stacktrace
```
t._updateInMemory (webpack:///src/app/core/persistence/persistence.service.ts:786:12)
_updateInMemory (webpack:///src/app/core/persistence/persistence.service.ts:713:11)
toString (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.6.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.4297b2fe74deb2892f3c.js:1:1815342)
invoke (webpack:///node_modules/zone.js/fesm20
[main.log](https://github.com/johannesjo/super-productivity/files/7496818/main.log)
15/zone.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.js:28672:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:371:51)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:134:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1276:35)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:30)
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1213:30)
makeResolver (webpack:///node_modules/zone.js/fesm2015/zone.js:1120:16)
toString (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.6.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.4297b2fe74deb2892f3c.js:1:2466542)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.js:28672:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:371:51)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:134:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1276:35)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:30)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:28659:32)
```

### Meta Info
META: SP7.6.0 Electron – de – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.6.0 Chrome/91.0.4472.124 Electron/13.1.7 Safari/537.36

### Actions Before Error
```
1636370088110: [Idle] Set idle time 
1636370144636: [Idle] Trigger Idle (12) 
1636370148124: [Idle] Set idle time 
1636370204751: [Idle] Trigger Idle (12) 
1636370208104: [Idle] Set idle time 
1636370264870: [Idle] Trigger Idle (12) 
1636370268107: [Idle] Set idle time 
1636370324961: [Idle] Trigger Idle (12) 
1636370328111: [Idle] Set idle time 
1636370385085: [Idle] Trigger Idle (12) 
1636370388114: [Idle] Set idle time 
1636370445181: [Idle] Trigger Idle (12) 
1636370448118: [Idle] Set idle time 
1636370505233: [Idle] Trigger Idle (12) 
1636370508120: [Idle] Set idle time 
1636370565329: [Idle] Trigger Idle (12) 
1636370568121: [Idle] Set idle time 
1636370625392: [Idle] Trigger Idle (12) 
1636370628123: [Idle] Set idle time 
1636370685505: [Idle] Trigger Idle (12) 
1636370688125: [Idle] Set idle time 
1636370745641: [Idle] Trigger Idle (12) 
1636370748125: [Idle] Set idle time 
1636370780252: [Idle] Trigger Idle (7) 
1636372225117: [Idle] Set idle time (1442) 
1636372225949: [Layout] Hide SideBar 
1636372448169: [Idle] Set idle time (179) 
1636372449015: [Layout] Hide SideBar 
1636372750809: [Idle] Set idle time (301) 
1636372762646: [Persistence] Save to DB
```

**Comment by Jogiio** [comment]
#976 Seems the same.

**Comment by johannesjo** [comment]
Thank you very much for reporting! I am not sure if the underlying issue is fixed tbh but at least this particular error should not be possible anymore with v7.7.0. I think upgrading to it might we worth a shot!
