### ISSUE TITLE
Error: lastLocalSyncModelChange

### ISSUE THREAD

**Issue by Lastofthefirst** [johannesjo/super-productivity#1664]
### Steps to Reproduce

1. Download new dmg
2. Replace old  app with  new

(Sorry its incomplete, not alot of time right now, but the screen said copy and report XD)

### Error Log (Desktop only)
Copied from the screen:

this._saveForProjectIds (webpack:///src/app/core/persistence/persistence.service.ts:442:12)t.subTaskIds.forEach( (webpack:///src/app/imex/sync/is-valid-app-data.util.ts:275:9)constructor (webpack:///node_modules/zone.js/fesm2015/zone.js:1387:28)t.subTaskIds.forEach( (webpack:///src/app/imex/sync/is-valid-app-data.util.ts:275:9)data (webpack:///src/app/core/persistence/persistence.service.ts:418:23)this._dataRepairService.isRepairPossibleAndConfirmed (webpack:///src/app/core/data-init/data-init.service.ts:68:39)constructor (webpack:///src/app/core/data-init/data-init.service.ts:54:39)invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:25)
META: SP7.7.0 Electron – en-US – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.7.0 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Stacktrace
```
this._saveForProjectIds (webpack:///src/app/core/persistence/persistence.service.ts:442:12)
t.subTaskIds.forEach( (webpack:///src/app/imex/sync/is-valid-app-data.util.ts:275:9)
constructor (webpack:///node_modules/zone.js/fesm2015/zone.js:1387:28)
t.subTaskIds.forEach( (webpack:///src/app/imex/sync/is-valid-app-data.util.ts:275:9)
data (webpack:///src/app/core/persistence/persistence.service.ts:418:23)
this._dataRepairService.isRepairPossibleAndConfirmed (webpack:///src/app/core/data-init/data-init.service.ts:68:39)
constructor (webpack:///src/app/core/data-init/data-init.service.ts:54:39)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:25)
```

### Meta Info
META: SP7.7.0 Electron – en-US – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.7.0 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1636481151382: [SP_ALL] Load(import) all data 
1636481151387: [Persistence] Save to DB (12)
```

**Comment by Lastofthefirst** [comment]
But, all my data seems to be fine.

**Comment by johannesjo** [comment]
Hey there! Thank you very much for reporting this! I made some small adjustment for this to not occur anymore.
