### ISSUE TITLE
Multiple motivational image support

### ISSUE THREAD

**Issue by aripollak** [johannesjo/super-productivity#1667]
## Problem Statement

A single motivational image for the break reminder can get a little boring.

## :grey_question: Possible Solution

The ability to specify multiple image URLs, and have one chosen randomly at each break reminder; maybe the configuration could be an input text box with each URL separated by whitespace/newlines? 

## :arrow_heading_up: Describe alternatives you've considered

Manually changing it :smile: 

## :heavy_plus_sign: Additional context

I like how Workrave cycles through multiple exercise images; it's more motivating for me to do them that way.

**Comment by johannesjo** [comment]
Thanks for opening this up! That's a really cool suggestion! I like it! PRs are welcome!

**Comment by aripollak** [comment]
Still relevant.
