### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'title')

### ISSUE THREAD

**Issue by pdlourenco** [johannesjo/super-productivity#1668]
### Steps to Reproduce

1. Access worklog
2. Click on the arrow to expand the current week or current month
3. Error happens

### Console Output

https://privatepastebin.com/?d4159d7dac859a77#9f3SzzedHw5UNLsnHTnR5jAVawxJTstWZABKRKEcUW5B
![image](https://user-images.githubusercontent.com/26777347/141168259-d127f5ab-9570-41af-9917-12389b4f3005.png)
![image](https://user-images.githubusercontent.com/26777347/141168363-39974484-b283-4ae2-9ef1-54d5995cdeb6.png)

### Stacktrace
```
title (webpack:///src/app/features/worklog/worklog-export/worklog-export.util.ts:187:77)
getTaskFields (webpack:///src/app/features/worklog/worklog-export/worklog-export.util.ts:64:23)
data (webpack:///src/app/features/worklog/worklog-export/worklog-export.util.ts:33:31)
b._next (webpack:///src/app/features/worklog/worklog-export/worklog-export.component.ts:154:25)
__tryOrUnsub (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:183:15)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:122:21)
_next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:72:25)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)
notifyNext (webpack:///node_modules/rxjs/_esm2015/internal/observable/combineLatest.js:73:33)
_next (webpack:///node_modules/rxjs/_esm2015/internal/InnerSubscriber.js:11:20)
```

### Meta Info
META: SP7.7.0 Electron – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.7.0 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1636567030682: [Task] Add time spent 
1636567030683: [Project] Update Work End 
1636567030697: [Tag] Update Work End for Tag (2) 
1636567030705: [Persistence] Save to DB (4) 
1636567031792: [Task] Add time spent 
1636567031793: [Project] Update Work End 
1636567031805: [Tag] Update Work End for Tag (2) 
1636567031815: [Persistence] Save to DB (4) 
1636567032672: [Task] Add time spent 
1636567032673: [Project] Update Work End 
1636567032680: [Tag] Update Work End for Tag (2) 
1636567032687: [Persistence] Save to DB (4) 
1636567033661: [Task] Add time spent 
1636567033663: [Project] Update Work End 
1636567033669: [Tag] Update Work End for Tag (2) 
1636567033672: [Persistence] Save to DB (4) 
1636567034661: [Task] Add time spent 
1636567034661: [Project] Update Work End 
1636567034665: [Tag] Update Work End for Tag (2) 
1636567034668: [Persistence] Save to DB (4) 
1636567035662: [Task] Add time spent 
1636567035664: [Project] Update Work End 
1636567035675: [Tag] Update Work End for Tag (2) 
1636567035680: [Persistence] Save to DB (4) 
1636567036677: [Task] Add time spent 
1636567036677: [Project] Update Work End 
1636567036681: [Tag] Update Work End for Tag (2) 
1636567036684: [Persistence] Save to DB (4) 
1636567037156: [SP_ALL] Load(import) all data 
1636567037158: [SP_ALL] All Data was loaded
```

**Comment by johannesjo** [comment]
Hey there! Thank you very much for reporting this!

It might be that for some reason a bit of your data got into an invalid state that I didn't account for and that I can't reproduce. It would be great if you could share a copy of your data to contact@super-productivity.com, so I can debug this on my computer. You can create an export by navigating to "Settings" and then to "Import/Export" or you can use the "Export data" button from the error Dialog.

**Comment by johannesjo** [comment]
Thank you very much for helping out with your data. I was now able to pinpoint the problem. To solve your problem now, you can export your data again and then search for `      "2021-11-09": 0` and delete that line as well as the preceding comma and then re-import the data again.
