### ISSUE TITLE
Chrome-sandbox error can't start

### ISSUE THREAD

**Issue by servomekanism** [johannesjo/super-productivity#167]
The appImage binary (./superProductivity-2.6.1-x86_64.AppImage) can't start on my linux box.
It reports the following:
```
zenity, kdialog, Xdialog missing. Skipping /tmp/.mount_superPjindcV/AppRun.
[5875:0510/021957.574089:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_superPjindcV/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
```

**Comment by ArjenR** [comment]
Hi, I happened to run in to this one also. 

IIRC it is due to a new security option in Electron and user namespaces that needs to be enabled using `sysctl` in your kernel for this to be allowed.
`kernel.unprivileged_userns_clone=1`

**Comment by danielestevez** [comment]
It seems that workaround by @ArjenR or the solutions here https://github.com/electron/electron/issues/17972 do not work with snap installed app -> https://github.com/scratux/scratux/issues/1#issuecomment-488665831
Still trying to find a solution,,,,

**Comment by ArjenR** [comment]
I use the appimage. So if you cannot be without, perhaps downgrade to an ealier version or switch to appimage as workaround?

**Comment by danielestevez** [comment]
Never used appImage.
i won't downgrade just in case i get some data corruption :fearful: and for AppImage i guess it's the same problem, i cannot export my data and import to the AppImage version

**Comment by ArjenR** [comment]
The data is not stored inside the snap or appimage, but in your userprofile. 
`~/config/superProductivity/`
Just make a backup of that one to be sure there is no corruption.

**Comment by danielestevez** [comment]
btw i could open the snap version by running from the directory
/snap/superproductivity/current/superproductivity --no-sandbox

Now working in trying to recover my data

**Comment by johannesjo** [comment]
Thanks everybody for looking into it. Don't have my linux laptop with me, but downgrading electron might fix this. Can't say if this will have any side effects though. I will publish a pre release in a minute or so (candiate/edge channel for the snap version).

Would be really nice if someone could test this and report if the issue still persists.

**Comment by servomekanism** [comment]
version 2.6.3 works in my system! ;)

**Comment by thomasnordquist** [comment]
The initial comment provides a workaround to disable the sandbox for Linux builds.
https://github.com/electron-userland/electron-builder/issues/3872

**Comment by danielestevez** [comment]
Thanks @johannesjo !! I can confirm the snap version works in Ubuntu without the workaround of `kernel.unprivileged_userns_clone`
