### ISSUE TITLE
Work time of the day displayed wrongly.

### ISSUE THREAD

**Issue by TangdizhiH** [johannesjo/super-productivity#1675]
### Your Environment

Pop!_os 21.04 (ubuntu 21.04)

- Version used:  7.7 (also in 7.6)
- Operating System and version: Pop!_os 21.04
- Desktop Environment:  Gnome 3.38.5
- Browser Name and version: 

### Expected Behavior

The work time of the day should be correct.

### Current Behavior

The work time of the day would stuck at some where. I can tell that it is wrong and I can see the correct time from Today- Work diary (don't know if this is the correct translation in English).
For example the data from today 14th Nov.
The data displayed on main page:

![image](https://user-images.githubusercontent.com/45258158/141687125-3e775a77-10d4-42cf-9a85-13ba75c55183.png)

The data on Today - Work diary (the last row, 3h 18):

![image](https://user-images.githubusercontent.com/45258158/141687225-6f8170a2-17e5-4e80-8598-0234321cf3bd.png)

### Steps to Reproduce (for bugs)

Sorry I haven't figure out how this behavior was triggered.

**Comment by TangdizhiH** [comment]
I would like to provide more information if you need it and I've observed this behavior in the last two days.

**Comment by johannesjo** [comment]
Hey there! Thank you very much for reporting this!

Hey there! Thank you very much for reporting this!

It would be great if you could share a copy of your data to contact@super-productivity.com, so I can debug this on my computer. You can create an export by navigating to "Settings" and then to "Import/Export" or you can use the "Export data" button from the error Dialog.

Also: What is your timezone?

**Comment by TangdizhiH** [comment]
> Hey there! Thank you very much for reporting this!
> 
> It would be great if you could share a copy of your data to [contact@super-productivity.com](mailto:contact@super-productivity.com), so I can debug this on my computer. You can create an export by navigating to "Settings" and then to "Import/Export" or you can use the "Export data" button from the error Dialog.
> 
> Also: What is your timezone?

OK, I've sent it. Thank you for your work

**Comment by johannesjo** [comment]
I just checked your data and to me it seems like it is working as intended. There is a difference between the time shown in the worklog and the time on the task list view. The latter only shows the time worked on all tasks present in the current list. So tasks that are moved to the backlog or to the archive or got the today tag removed are not taken into consideration. Is this maybe in play here?

**Comment by TangdizhiH** [comment]
> I just checked your data and to me it seems like it is working as intended. There is a difference between the time shown in the worklog and the time on the task list view. The latter only shows the time worked on all tasks present in the current list. So tasks that are moved to the backlog or to the archive or got the today tag removed are not taken into consideration. Is this maybe in play here?

Oh, I see. So basically I should not remove the task from the day if I want the time to display corectly. Thank you for you patient check.
