### ISSUE TITLE
Feature Reaquest: Integration with Microsoft ToDo

### ISSUE THREAD

**Issue by KonTy** [johannesjo/super-productivity#168]
Have you thought about integrating with Microsoft ToDo? Microsoft ToDo is free and has some nice features. One in particular will work with Super Productivity very nicely. They basically have My Day concept.

 I imagine a workflow like this:

- You'd go through your lists in ToDo 
- move them to "My Day" which would become trackable tasks that you would track time for. 

On top of that there is already project there on GitHub that wraps Microsoft ToDo and written using Electron [klaussinani ao](https://github.com/search?q=klaussinani%2Fao) I think it's fate for these to projects to come together.

**Comment by johannesjo** [comment]
Thank you very much for the suggestion. To be honest I personally don't see the appeal in relying on two different ToDo applications. Microsoft ToDo is nice but Super Productivity is (imho) offering better options for  project oriented task management while it isn't on the same level for every day level simple tasks and the cleanness of UI. But maybe it's just me, as I don't actively use Microsoft ToDo. 

I'm open to Pull Requests on this matter – of course, but it should be done in a non intrusive way to not annoy anyone who is not using Microsoft ToDo. I would imagine that it is not an easy task to accomplish, as the models of boths are pretty likely very different from each other.

**Comment by KonTy** [comment]
Yeah, I see your point, I think if we added a couple of features then I would totally switch from Microsoft ToDo to this app. 
1. Sync using OneDrive
2. Day View (where I could add tasks from different projects and show them on one page so I don't have to switch projects to see my other tasks)
3. Hashtag view where if I add a #some-hashtag. to my tasks like (#randomization) I want to be able to get all tasks with that hashtag and see how much time I wasted.
4. A TreeView view where I can see  Projects, tasks and sub tasks in one view
5, Better time boxing features where it would tell me that I'm over the time allocated for this tasks and I should switch.
6. Better reminders
7. Ability to encrypt todo lists when pushed to OneDrive


It seems that adding these would be easier then integrating with Microsoft Todo.

**Comment by johannesjo** [comment]
Sorry for not answering earlier. I think that I might add support for all the things you're missing step by step, but these are big features, so it will take some time. 

Time Boxing is already a thing, you just need to activate it under "Misc Settings"

**Comment by KonTy** [comment]
Yeah to be honest I didn't expect an answer. I should start contributing myself. I'm still trying to wrap my head around some of the behavior of your app once I think I understand how it works I could start contributing. For example time boxing was not obvious to me that it existed :)

**Comment by johannesjo** [comment]
I can imagine :) I'm not a Designer and I don't have any data on how people use the app, so I'm always glad for ideas to improve the UI. 

Please let me know if you have any questions on how something works!

**Comment by johannesjo** [comment]
I'm closing this in favor of the other issues:
#163 #201 #159 

There is currently no encryption, but the data can be compressed now.
