### ISSUE TITLE
7.8.0 Can't find "Anmerkungen" anymore?

### ISSUE THREAD

**Issue by Heart1010** [johannesjo/super-productivity#1680]
Updated to v7.8.0 and now I can't find 'Anmerkungen' (bottom left) anymore?

![image](https://user-images.githubusercontent.com/1481680/142626339-dbee5bc2-6df4-499c-b90e-7f32e6d66ca4.png)

**Comment by johannesjo** [comment]
The feature has been changed and can now be found in the top right (or as is via the keyboard shortcut).
