### ISSUE TITLE
Notes gone after updating to 7.8.0

### ISSUE THREAD

**Issue by EngelPika32** [johannesjo/super-productivity#1682]
### Your Environment

- Version used: AUR, using yay:  `upgraded superproductivity-bin (7.7.0-1 -> 7.8.0-1)`
- Operating System and version: linux, arch-manjaro
- Desktop Environment:  XFCE
- Browser Name and version: 

### Expected Behavior

Finding all my notes in the top-right corner (new notes system/model using global instead of project-wide notes).
Though, I dunno whether I like that every note is global.

### Current Behavior

"There are currently no notes"

Checking the backups the notes are completely gone (→ migration issue and not a pure UI issue)

### Steps to Reproduce (for bugs)

1. have some projects with notes
2. close app
3. update (restart? Well, I did due to other updates)
4. open app, check notes

### Console Output

The only interesting part seems to be the migration, right?
Filtering for `[M]`: 
```
[M] Migrating model "Project" to version from 5.4 to 6.01 
Object
model-version.ts:34 [M] Migrating model "GlobalConfig" to version from 2.2005 to 2.2006 
Object
model-version.ts:34 [M] Migrating model "Project" to version from 5.4 to 6.01 
Object
model-version.ts:34 [M] Migrating model "Project" to version from 5.4 to 6.01 
Object
model-version.ts:34 [M] Migrating model "GlobalConfig" to version from 2.2005 to 2.2006 
Object
model-version.ts:34 [M] Migrating model "Project" to version from 5.4 to 6.01 
Object
model-version.ts:34 [M] Migrating model "Project" to version from 5.4 to 6.01 
Object
model-version.ts:34 [M] Migrating model "GlobalConfig" to version from 2.2005 to 2.2006 
Object
model-version.ts:34 [M] Migrating model "Project" to version from 5.4 to 6.01 
Object
model-version.ts:34 [M] Migrating model "GlobalConfig" to version from 2.2005 to 2.2006 
Object
model-version.ts:34 [M] Migrating model "GlobalConfig" to version from 2.2005 to 2.2006 
Object
model-version.ts:34 [M] Migrating model "GlobalConfig" to version from 2.2005 to 2.2006 
Object
model-version.ts:34 [M] Migrating model "GlobalConfig" to version from 2.2005 to 2.2006 
Object
model-version.ts:34 [M] Migrating model "GlobalConfig" to version from 2.2005 to 2.2006 
Object
```
Not sure, but one migration per model should be enough, right? :)

### Error Log (Desktop only)

(Adding only the logs of today; removed time, removed username)
```
[2021-11-19 ] [info]  { enabled: null, showDevTools: false, mode: 'bottom' }
[2021-11-19 ] [info]  Saving backups to /home/**USER**/.config/superProductivity/backups
[2021-11-19 ] [info]  No custom styles detected at /home/**USER**/.config/superProductivity/styles.css
[2021-11-19 ] [info]  close, isQuiting: undefined
[2021-11-19 ] [info]  close, isQuiting: true
[2021-11-19 ] [info]  { enabled: null, showDevTools: false, mode: 'bottom' }
[2021-11-19 ] [info]  Saving backups to /home/**USER**/.config/superProductivity/backups
[2021-11-19 ] [info]  No custom styles detected at /home/**USER**/.config/superProductivity/styles.css
```

**Comment by johannesjo** [comment]
Duplicate of https://github.com/johannesjo/super-productivity/issues/1680

**Comment by EngelPika32** [comment]
This is not a dup!

@johannesjo I think you got me wrong. All notes are completely gone! 
I checked the saved auto-backups for them and they do NOT exist in them after the update. They do exist in all previously created backups (before the update). Hence there is NO way for them to be shown in the app.
Or in other words, they were not migrated at all.

**Comment by johannesjo** [comment]
Oh

**Comment by johannesjo** [comment]
Oh! Thanks for the explanation. Are there any backups from before the update that you could send me and possibly from after too (to contact@super-productivity.com)? I'd really like to get to the bottom of this.

**Comment by EngelPika32** [comment]
The backups include my complete config and data (all my projects and tasks), right? I'd prefer not to, but if nothing helps, then I'll send you the backups…

- - - - 

As I needed my notes, I've imported one of the backups – and now they exist within the backups & the app again! 
Trying it before going a version back was worth it. I've only lost one day of records, but that's okay.

Here is the browser log (filtered for `[M]` again): 
```
model-version.ts:34 [M] Migrating model "GlobalConfig" to version from 2.2005 to 2.2006 
  {lang: {…}, misc: {…}, evaluation: {…}, idle: {…}, takeABreak: {…}, …}
is-legacy-app-data.util.ts:26 [M] LEGACY MODEL  => project 5.4 6.01
model-version.ts:34 [M] Migrating model "Project" to version from 5.4 to 6.01 
  {ids: Array(8), entities: {…}, __modelVersion: 5.4}
cross-model-migrations.ts:41 [M] Migrating Legacy Note State to new model
cross-model-migrations.ts:42 [M] noteMigration: undefined 
  {legacyNote: {…}}
cross-model-migrations.ts:56 [M] legacyNoteStateForProject 
  {ids: Array(2), entities: {…}}
cross-model-migrations.ts:59 [M] noteMigration: 
  {legacyNoteStateForProject: {…}}
cross-model-migrations.ts:56 [M] legacyNoteStateForProject 
  {ids: Array(1), entities: {…}}
cross-model-migrations.ts:59 [M] noteMigration: 
  {legacyNoteStateForProject: {…}}
cross-model-migrations.ts:56 [M] legacyNoteStateForProject 
  {ids: Array(1), entities: {…}}
cross-model-migrations.ts:59 [M] noteMigration: 
  {legacyNoteStateForProject: {…}}
2
cross-model-migrations.ts:56 [M] legacyNoteStateForProject undefined
cross-model-migrations.ts:56 [M] legacyNoteStateForProject 
  {ids: Array(1), entities: {…}}
cross-model-migrations.ts:59 [M] noteMigration: 
  {legacyNoteStateForProject: {…}}
cross-model-migrations.ts:56 [M] legacyNoteStateForProject 
  {ids: Array(1), entities: {…}}
cross-model-migrations.ts:59 [M] noteMigration: 
  {legacyNoteStateForProject: {…}}
cross-model-migrations.ts:56 [M] legacyNoteStateForProject 
  {ids: Array(1), entities: {…}}
cross-model-migrations.ts:59 [M] noteMigration: 
  {legacyNoteStateForProject: {…}}
cross-model-migrations.ts:74 [M] noteMigration: 
  {newNoteState: {…}, newProjectState: {…}}
```
As we can see, it triggered the migration functions. Hence I suspect the difference between the update and migrate-import functions for the cause of data loss. (Though, I'd have thought they are the same :woman_shrugging: )

Some related lines/functions from the logs:
· [is-legacy-app-data.util.ts#L26-L30](https://github.com/johannesjo/super-productivity/blob/0fba718a8037f126027b71ab8ced71525901c1d4/src/app/imex/sync/is-legacy-app-data.util.ts#L26-L30)
· [model-version.ts#L34-37](https://github.com/johannesjo/super-productivity/blob/0fba718a8037f126027b71ab8ced71525901c1d4/src/app/util/model-version.ts#L34-L37)
· [cross-model-migrations.ts#L41-L42](https://github.com/johannesjo/super-productivity/blob/0fba718a8037f126027b71ab8ced71525901c1d4/src/app/core/persistence/cross-model-migrations.ts#L41-L42)

I couldn't identify the exact problem yet *(I'm currently only navigating the files in gitHub and can't efficiently lookup function calls)*. 
I might clone the project later to investigate the function calls. 
But maybe you'll spot the issue now, as you know the project much better than me.

**Comment by johannesjo** [comment]
I totally understand. Here is a little (untested) JavaScript script to anonymize the data (probably should make this accessible from the app):

```
var dirtyDeepCopy = function (val) { return JSON.parse(JSON.stringify(val)); };
var i = 0;
var KEY_TO_REPLACE = [
    'username',
    'userName',
    'password',
    'token',
    'notes',
    'authCode',
    'accessToken',
    'host',
    'gitlabBaseUrl',
    'syncFilePath',
    'title',
    'originalImgPath',
    'path',
    'content',
];
var maskString = function (key, val, counter) {
    if (KEY_TO_REPLACE.includes(key) && val.length > 0) {
        return key + "__" + counter;
    }
    else {
        return val;
    }
};
var recurse = function (obj) {
    // eslint-disable-next-line guard-for-in
    for (var key in obj) {
        if (Object.prototype.hasOwnProperty.call(obj, key)) {
            var val = obj[key];
            if (Array.isArray(val)) {
                val.forEach(function (arrVal) {
                    if (typeof arrVal === 'object' && arrVal !== null) {
                        recurse(arrVal);
                    }
                });
            }
            else if (typeof val === 'object' && val !== null) {
                recurse(val);
            }
            else if (typeof val === 'string') {
                obj[key] = maskString(key, val, i);
            }
        }
        i++;
    }
};
var privacyExport = function (d) {
    var cpy = dirtyDeepCopy(d);
    recurse(cpy);
    return JSON.stringify(cpy);
};
```


You would need to read the files data as string and execute: 
```
var fs = require('fs');

var myStr = fs.readFileSync('./data-export-from-sp.json', encoding:'utf8', flag:'r'});
var myStrAsData = JSON.parse(myStr);
var result = privacyExport(myStrAsData);
console.log(result);
```

**Comment by johannesjo** [comment]
Thank you very much for digging into this @EngelPika32 . Looking at the logs you provided there are notes (7 notes for 6 different projects) migrated to the new model version. But they don't show up?

**Comment by EngelPika32** [comment]
> looking at the logs you provided there are notes (7 notes for 6 different projects) migrated to the new model version. But they don't show up?

Your talking about the logs in the message I sent today, right? – They do show up.

However, we have two different states to distinguish between: 
· The first one from last Friday: The state after updating SP and SP migrating automatically after startup (initial post; with logs).
· Then the second one from today, where I tried to import one of the backups. Which, thankfully, worked. *(I was going to revert the app a version back. But I thought, what should go wrong if I try to import one of the backups made before Friday, maybe it works. And as it worked, I didn't have to revert the version of SP.)*

The logs clearly show different behavior and different function calls, which should lead us to the source of the issue. 
One thing that is odd as well, is the repeated call to the same functions in the logs from Friday.

I couldn't get behind, which initial functions trigger a migration, as it can't be the same (due to different behavior), or, if it's the same, then the parameters differ for some reason. Maybe you have a clue?

And, as I restored a backup from before Friday, I lost the track record of Friday. ←To clarify which day I lost. *(Mentioned in my previous post).*

**Comment by johannesjo** [comment]
Thanks for the clarification. 

Most people (according to the snapcraft stats) have migrated to 7.8 by now, so a fix might come too late anyway unfortunately. For anyone encountering this, you might do the following to avoid data loss:

1. Before upgrading the app, make an export of your data.
2. After upgrading – if notes are lost – re-import that export

I am very sorry for the inconvenience this caused. :(

**Comment by mop999x** [comment]
I am on windows 10 on v7.8.0

Unsure if this is related, but I am seeing a issue where if I have a repeated task and another repeated task with sub tasks, and notes associated with it, and a repeated task is auto added to Today by the app vie trigger through time or day change after starting up the program again. all the sub task and the notes for the repeated task disappear from my  todays task but the sub task show up in timeline

**Comment by johannesjo** [comment]
Hi @mop999x ! No that's not related, as task notes are a different thing. Furthermore It looks to me like this is caused by a new repeated task instance being created, which is the intended behavior. Please have a look under [discussions](https://github.com/johannesjo/super-productivity/discussions) as this subject has come up several times.

**Comment by mop999x** [comment]
Gotcha, so at the moment sub tasks part of a parent repeated  task, have to be converted to parent task and repeated at least the current workflow, all related to issue [#948](https://github.com/johannesjo/super-productivity/issues/948)

great project by the way, really have gotten into productivity and efficiency using my time better because of this project.

thanks!!
