### ISSUE TITLE
[Feature Reaquest] Auto-switch theme in MacOS Mojave

### ISSUE THREAD

**Issue by Kl4tch** [johannesjo/super-productivity#169]
Electron has API for dark theme in MacOS mojave, it's so simple

https://youtu.be/Lp-K-kYQ7KE

Can you please support auto-switch theme mode please, like other apps?

**Comment by johannesjo** [comment]
The feature is implemented. Let me know if it works out for you.

**Comment by Kl4tch** [comment]
Hello, thanks for updates

**Comment by johannesjo** [comment]
#179 

It should work if you restart the app, but live switching doesn't work. I'll look into it.
