### ISSUE TITLE
Please use snap core20 instead of core18

### ISSUE THREAD

**Issue by ibrahemesam** [johannesjo/super-productivity#1690]
the snap pack of this app uses snap core18 which has a bug that make letters in text appear as empty rectangles as if there is no font ttf installed:
![image](https://user-images.githubusercontent.com/43931249/143453200-246bd9d1-4a0c-4b4d-80b9-bcb18366c304.png)
this bug happens in Manjaro Linux and Arch based distributions

**Comment by ibrahemesam** [comment]
.

**Comment by johannesjo** [comment]
Thanks for opening this up. Ideally this should possible via electron builder at some point:
https://github.com/electron-userland/electron-builder/issues/5257
Though it seems the issues is abandoned.
