### ISSUE TITLE
Tags shouldn't disappear from task when a tag is selected – consistent UI proposal

### ISSUE THREAD

**Issue by EngelPika32** [johannesjo/super-productivity#1691]
## Problem Statement

When I select a tag (from the sidebar/for filtering), then the selected tag isn't shown on the listed tasks anymore. This is very confusing, especially if you have some tags for the state of a (long) task. Sometimes I add the new state but forget to remove the old one.  I'm always confused about what I selected when I select one of these tags.

Additionally, order, color, and consistency matter for a11y. When you switch between some tags which share some tasks in common, then the UI for the tasks wraps around and the position of other tags changes as well.

## :grey_question: Possible Solution

Don't hide tags when filtering them / having one selected.

## :arrow_heading_up: Describe alternatives you've considered

Changing my workflow to ignore tasks filtering altogether and only work within the projects, but that defies the purpose of the filtering option. 

## :heavy_plus_sign: Additional context

Note: The listing of projects should NOT change. I haven't looked into the code, but I believe it could matter while implementing, hence I point this out. 
The listing of projects is consistent as they always appear at the start.

**Comment by johannesjo** [comment]
Thanks for opening this up. This is on purpose as I personally prefer it to be the way it is, as the tag would not add any additional information, but add unnecessary clutter. If enough other people prefer it differently I am open to switch things up.

**Comment by DKBurnsBresMed** [comment]
Hi All, I have noticed that this issue goes away if the window is more narrow. When the app is maximised, shift+D does nothing, and when it is smaller (e.g. left half of the screen) it works. 

Hopefully that helps!
