### ISSUE TITLE
Allow more sub-task levels

### ISSUE THREAD

**Issue by putzwasser** [johannesjo/super-productivity#1693]
## Problem Statement

I like to divide my tasks into multiple subtasks. Currently, super-productivity only allows one sublevel of tasks.
One sub-task might be to big to be actionable. Therefore, I'd like to sub-divide it again. I repeat this until my tasks are "super-actionable".

Example:

* Build feature XY
  * Refactor class Foo
    * Refactor function AhBeeCee
      * . . . 
    * Refactor method DeeEeeEff
      * Split function into two
      * Check stackoverflow topic `https://stackoverflow.com/xyz`
      * Create method 1
        * Write logic
        * Write documentation
        * Write unit tests
      * Create funtion 2
        * . . .
      * Create PR
    * . . .
  * . . .  

## :grey_question: Possible Solution

Allow subtasks in for as many levels a user like to have.

## :heavy_plus_sign: Additional context

Allowing to tag each subtask would allow adding individual sub-tasks to the "today" view. #1694

**Comment by johannesjo** [comment]
This is being discussed here: #643 (please upvote if you like to see the feature).
