### ISSUE TITLE
Allow tagging of subtasks

### ISSUE THREAD

**Issue by putzwasser** [johannesjo/super-productivity#1694]
## Problem Statement

Currently only main level tasks can be tagged. This leads to "pollution" of the tasks/today view, as the main-task and every sub-task gets added to the today view, if I only want to/can do a single sub-task in a working session.

Let's use David Allen's GTD method as an example:

He suggests to "tag" tasks according to the context. A main tasks, e.g. plan birthday party, has several sub-tasks. Each sub-task might have different contexts:

* Plan Birthday Party
  * Search cake recipe #computer
  * Book DJ #phone
  * Write and send out invitiations #desk

It's not possible to filter the sub-tasks based on their contexts without being able to tag them. Tagging the whole main-task with all three tags leads to pollution of the tag view.

Additionally, it is not possible to add sub-tasks to the "today" view without tagging them. Let's say I only can do the `Write and send out invitiations #desk` sub-task. I need to add the whole main-tasks to my "today" view. That makes "today" look very cluttered.

## :grey_question: Possible Solution

Allow individual tags for every sub-task.

## :heavy_plus_sign: Additional context

If a subtask gets added to the "today" view, it might be nice to display the parenting task as auto-generated tag in the today view. Similar to displaying the project holding the task in the today view.
If you add the feature of multiple subtask levels, it might be nice to display the hierarchy of parenting tasks. Similar to a "breadcrumb navigation" of a website. (#1693)

**Comment by johannesjo** [comment]
Hi there! Thanks for opening this up. This has been discussed here: #794

**Comment by serhumanos** [comment]
Hi, what happened with this? I think this feature is very usefull

**Comment by fccfc5d245c** [comment]
I'm with @putzwasser . If I could make only one feature request, it would be this, it is that important.

**Comment by johannesjo** [comment]
This feature will be included in the upcoming release.

**Comment by fccfc5d245c** [comment]
That's great! SP keeps getting better, thank you so much
