### ISSUE TITLE
app freezes when a due task appears while selecting a file to import

### ISSUE THREAD

**Issue by EngelPika32** [johannesjo/super-productivity#1698]
The app freezes when a due task appears while you're selecting a file to import.

### Your Environment

- Version used:  AUR, using yay – 7.8.0-1
- Operating System and version: linux, arch-manjaro
- Desktop Environment:  XFCE
- Browser Name and version: 

### Expected Behavior

Don't show any due tasks while selecting a file to import/stuff in other windows. (?).
Or being able to click it away.

### Current Behavior

The app becomes unresponsive. Due-task can't be clicked away.

### Steps to Reproduce (for bugs)

1. Import a backup from the past, then any due task between that backup and today is overdue.
2. Import another (different) backup. *(In my case, I noticed, that I imported the wrong one.)*
3. Tasks that are overdue should lead to the normal pop-up (while you're still selecting a file). This essentially blocks the UI.

Current workaround: Stop the app entirely; Open it again, and wait for the due task pop-up/notification to appear; Click away and then import again.

### Additional

Reference: comment in #1692 

If you're fast enough with selecting a file, then everything works fine.

**Comment by johannesjo** [comment]
Thanks for opening this up. This might be an arch only issue. At least I am not able to reproduce it on Ubuntu with gnome. If somebody has an idea how to fix this: PRs are welcome!
