### ISSUE TITLE
Cannot start time when we delete all subtasks

### ISSUE THREAD

**Issue by Gontran08** [johannesjo/super-productivity#17]
When we delete all subtasks from a task, we can no longer track our time without creating a subtask, even if the play button become available. I think that when there is no more subtask, then the play button should be working.

**Comment by johannesjo** [comment]
Hello! Thanks for reporting!

Can't really reproduce the issue though. Can you click the play button but nothing happens? Also: Are we talking about the web version (also which browser) or the desktop version (also which OS)?

**Comment by Gontran08** [comment]
Exactly, I can click the play button, but the timer doesn't start.
I'm using Ubuntu 17.10. I installed the application on my system using superProductivity_1.3.4_amd64.deb available in the "Releases" page.

**Comment by johannesjo** [comment]
Thanks. I'll look into it!

**Comment by johannesjo** [comment]
Ok this should be fixed with the next release (1.4.1). Thanks again for reporting!

**Comment by johannesjo** [comment]
Please reopen if the issue persists for you.

**Comment by Gontran08** [comment]
I tested with 1.4.2 and it works fine. Thanks!

**Comment by johannesjo** [comment]
Glad to hear that! Thanks for checking!
