### ISSUE TITLE
[Feature request] Version number in setting and changelog

### ISSUE THREAD

**Issue by Kl4tch** [johannesjo/super-productivity#170]
First, thanks again for this great app
It's not easy to track what you do. After 2 weeks of use version u forget what version you use. So, can you in settings place:
1) version of app (or how can I check it), link to page to last versions
2) link to changelog (or something like that), I want to fast get known about new features )
Not to open browser, find in github your app, then find changelog, then start finding what version I'm using :)

**Comment by johannesjo** [comment]
Thanks for the suggestion. I kept it simplistic for now, but I plan to make it a little bit more sophisticated in the future. Might be nice to showcase new features in a modal at startup for example.
