### ISSUE TITLE
Support undo last user action

### ISSUE THREAD

**Issue by ishanarora** [johannesjo/super-productivity#1705]
## Problem Statement

I'm always frustrated when I mistakenly click the "Remove from My Day" button or the "Mark as done" button on the Today page. In order to undo such an action I need to scroll through long lists to get to the task.

## :grey_question: Possible Solution

We could support a simple undo action by retaining the last user action in memory. On the interface we could have an undo button in the top-right row of buttons, and also use Ctrl+Z as keyboard shortcut.

**Comment by johannesjo** [comment]
That's a nice idea! I am all for it! PRs are welcome!
