### ISSUE TITLE
Better differentiate the time and date format

### ISSUE THREAD

**Issue by JoseOlin** [johannesjo/super-productivity#1736]
Any way to better differentiate the time and date format?
## Problem Statement

The 2.30 format is often confused with the time 2:30.

## :grey_question: Possible Solution

Something like 2/30 or 2-30 would be easier to differentiate, or better yet, for upcoming dates something like "Tom" (tomorrow), "In 2 days", "In 3 days", etc. 

## :arrow_heading_up: Describe alternatives you've considered

- Even putting the date format in bold might be enough. 
- Adding a Toggle sub task visivility level that only show tasks scheduled for today

**Comment by johannesjo** [comment]
Thanks for opening this up! Which places are you referring to? For the most part the date formatter just uses what is considered a default for your country.

**Comment by JoseOlin** [comment]
The reminders in the Today section (also in the Timeline section, but I only find it conflicting in the Today section)

For example, if I have subtasks scheduled for today, and other subtasks for other days, the similarity in the format makes them not easily distinguishable.

Ideally the subtasks that are not scheduled for that day I would prefer they did not appear on the Today section, to avoid overcrowding, but as a simpler alternative it would be enough for them to be easily identifiable that they do not have a reminder for today.

**Comment by johannesjo** [comment]
Not sure why this appears like this for you. 2.30 doesn't look right for sure :) 

I think this should be already fixed, but not is not released yet.

Here is the code:
https://github.com/johannesjo/super-productivity/blob/f1adc44afebe5e871f0991fb41541c8fac716147/src/app/ui/pipes/short-planned-at.pipe.ts

**Comment by johannesjo** [comment]
> Ideally the subtasks that are not scheduled for that day I would prefer they did not appear on the Today section, to avoid overcrowding, but as a simpler alternative it would be enough for them to be easily identifiable that they do not have a reminder for today.

Unfortunately that is not easy to change and personally I am ok with how things are now.

**Comment by JoseOlin** [comment]
What about adding a Toggle sub task visivility level that only show tasks scheduled for today?

**Comment by johannesjo** [comment]
> What about adding a Toggle sub task visivility level that only show tasks scheduled for today?

Maybe you can open up a new issue for this. I won't be able to work on this anytime soon (sooo much else to do), but maybe someone else wants to pick it up.

**Comment by JoseOlin** [comment]
OK. I open an issue.

Thank you for your always attentive and quick response.

**Comment by JoseOlin** [comment]
Is it okay if I close this issue to favor [issue 1740](https://github.com/johannesjo/super-productivity/issues/1740)?

**Comment by johannesjo** [comment]
Thank you very much! :)

**Comment by JoseOlin** [comment]
This has been fixed in version 7.8.1
Thanks!
