### ISSUE TITLE
Jira Request Error. Superproductivity isn't including the host in the request

### ISSUE THREAD

**Issue by Ghoughpteighbteau** [johannesjo/super-productivity#174]
### Your Environment
* Version used: latest master
* Operating System and version: Arch Linux
* Desktop Environment: XFCE

### Expected Behavior
Jira should link the tickets 

### Current Behavior
Fails to send the request

### Steps to Reproduce (for bugs)
I'm not sure if this is reproducable everywhere, but simply trying to enable the jira integration in the electron app seems to fail. More information in the console output

![log output](https://i.imgur.com/WQEZJs8.png)

**Comment by johannesjo** [comment]
May I ask how exactly the host url looks like (something in the form of `https://example.com:1234/maybe/a/path` should suffice)?

Mine looks like this `https://example-host.com`.

**Comment by Ghoughpteighbteau** [comment]
You mean as it's entered in the form? just as it is in clientRequest. lightship.atlassian.net 

![host field](https://i.imgur.com/ddBgXmi.png)

**Comment by johannesjo** [comment]
Normally just the host should work fine, but apparently there is something wrong with the code dealing with that case. I'll check it tomorrow. Thanks for reporting!!

**Comment by johannesjo** [comment]
Should be fixed. Please let me know if it isn't.
