### ISSUE TITLE
Adding a Toggle sub task visivility level that only show tasks scheduled for today

### ISSUE THREAD

**Issue by JoseOlin** [johannesjo/super-productivity#1740]
## Problem Statement

If a subtask is scheduled for Today the main task and all the subtasks are show in the Today section. 

## :grey_question: Possible Solution
Would be great if the **Toggle sub taks visibility** button had a level to **show only tasks scheduled for Today**, to keep the Today section cleaner. 

## :heavy_plus_sign: Additional context
Currently the levels are: 
- Pending and completed subtasks, 
- Only pending subtasks
- Working on subtask
- Hide all subtasks (show only the main task); 

The proposed levels are:
 - Pending and completed subtasks, 
- Only pending subtasks
- Scheduled for today subtaks
- Working on subtask
- Hide all subtasks (show only the main task); 

so adding a level probably doesn't require too much work (I hope).

**Comment by johannesjo** [comment]
Thank you!

**Comment by JoseOlin** [comment]
Just keeping the thread alive, I think this would be useful.

**Comment by JoseOlin** [comment]
Hi! Is this completed?

En qué versión está integrado? 

Thanks!
