### ISSUE TITLE
Improve project management

### ISSUE THREAD

**Issue by 06000208** [johannesjo/super-productivity#1741]
## Problem Statement

Hi, I just started using super productivity and I noticed some things that could be improved with how you interact with or manage projects in the UI.

Note that when I refer to a project's context menu, I'm talking about what's described in the UI as the "Project Menu", opened by the three dots icon next to a project's name in the sidebar and in the top left when you have a project selected.

- Having to navigate to Manage projects for operations like delete or rename isn't apparent at first
- As noted by https://github.com/johannesjo/super-productivity/issues/442#issuecomment-922270902, you can't delete a project if you have it selected. This isn't apparent to users in the Manage projects menu, and doesn't personally make much sense to me.
  - Clicking "Manage projects" visually brings you to a new menu, but this doesn't cause the last project you had open to be deselected, which is confusing behavior with it being represented as an item in the sidebar and compounds the above. Worth noting the "Scheduled" sidebar item does this as well.
- "Create projects" is a button, not a sidebar item, and has the same identity issue as Manage projects, but this is relatively minor.

## :grey_question: Possible Solution

- The operations available from the manage projects menu (rename, hide, and delete) should be available from a given project's context menus
- A project being selected/open shouldn't effect whether or not you can delete it
- In other comparable applications, such as Todoist, buttons like "Create Project" don't have to share a visual space or identity with items of the dropdown. The same could be done for the manage projects menu, such as with a gear icon.
  ![image](https://user-images.githubusercontent.com/52764066/144972775-256c45ef-6d45-4e8e-987e-99439b22e149.png)

I believe these changes would decrease some friction in the UI and make managing projects more intuitive.

## :arrow_heading_up: Describe alternatives you've considered

The same as above but without the last/third suggestion regarding the Create Project button would be enough. 

## :heavy_plus_sign: Additional context

This is tangentially related to #450 and #331, because the addition of an "archive project" functionality would warrent a context menu entry as well, which was already thought of and mentioned by https://github.com/johannesjo/super-productivity/issues/450#issuecomment-662438726.

**Comment by johannesjo** [comment]
Hey there! Thanks for opening this up! Adding "rename" and "delete" makes definitely sense to me. Not sure about hide, since users might be confused, how to show it again.

I like the "create project" layout you suggest. Only problem I see is, that the chevron for collapsibles is on the right at all other places, so I am not sure of switching things up is ideal.

The project deletion problem is tracked here:
#1497

**Comment by 06000208** [comment]
>Only problem I see is, that the chevron for collapsibles is on the right at all other places, so I am not sure of switching things up is ideal.

Yes, moving the chevron to the left would prompt moving all chevron for consistency. Or simply keeping it on the right, wheras it always remains the furthest button on the right.
