### ISSUE TITLE
A way to view and edit recurring tasks

### ISSUE THREAD

**Issue by MAX10541** [johannesjo/super-productivity#1746]
## Problem Statement

Currently, there is no way to view recurring tasks and edit them (unless they happen to be scheduled for today). I would love to have way to see them and edit them, and not have to wait for them to be scheduled in a few days to be able to do that.

## :grey_question: Possible Solution

Maybe view them in the "Timeline" or "Scheduled" pages? those pages were a bit misleading to me at first since they don't include repeated tasks. The tasks can be displayed only once with some extra info or icon to indicate that they are repeating on certain days (thus, no need to actually show them more than once in the timeline).
Alternatively, create a new section in those pages that shows the repeating tasks separately.

## :arrow_heading_up: Describe alternatives you've considered

The search functionality: make them appear when searching for them. The user can then directly edit/add to today. However, this will solve one part (editing a recurring task), but not the other (being able to view all of them).

## :heavy_plus_sign: Additional context

N/A

**Comment by johannesjo** [comment]
Hey there! Thank you very much for opening this up! Makes totally sense to me, to add something like this. I'd try to avoid adding another page, but maybe this can be part of the scheduled page with possibly a better title.

**Comment by johannesjo** [comment]
Just for the record: This has been implemented.
