### ISSUE TITLE
Airplane mode isn't covered by google sync

### ISSUE THREAD

**Issue by jpalczewski** [johannesjo/super-productivity#1748]
### Your Environment

- Version used:  7.8.0, Microsoft Store release
- Operating System and version: Win 11
- Desktop Environment: 
- Browser Name and version: 

### Expected Behavior
Program behaves as usual, despite sync that might start on next possible occasion.

### Current Behavior
![obraz](https://user-images.githubusercontent.com/4793526/145179193-3f904e70-29e5-4472-b2cc-7131df4c8d1c.png)

### Steps to Reproduce (for bugs)

1.Enable gdrive sync
2. Turn on airplane mode
3.Wait sync to be triggered.
4.

### Console Output
![obraz](https://user-images.githubusercontent.com/4793526/145179657-113aceaf-eaf4-4ff6-a231-7eecb10da640.png)

**Comment by johannesjo** [comment]
Thank you very much for opening this up!
