### ISSUE TITLE
GitHub bug report template and built-in report template are out of sync

### ISSUE THREAD

**Issue by jpalczewski** [johannesjo/super-productivity#1749]
### Your Environment

- Version used:  7.8.0 store/win(exe)
- Operating System and version:
- Desktop Environment: 
- Browser Name and version: 

### Expected Behavior
built-in report ability  doesn't cover last commits from github

https://github.com/johannesjo/super-productivity/blob/52d6ec740c76f686bde5ae09130bff70c2706f1f/src/app/core/error-handler/global-error-handler.util.ts
Report template generated in file above doesn't have that info:
https://github.com/johannesjo/super-productivity/commit/760166faf086a72a4e3e38342577f07ea09d507f 

It might increase rate of sent crash reports, because this possibility is also mentioned in app itself, so I thought that is worth to bring up

**Comment by johannesjo** [comment]
Hey there! Thank you for opening this up. 

Could you explain to me, what you mean by "built-in report ability doesn't cover last commits from github"?

**Comment by jpalczewski** [comment]
> Hey there! Thank you for opening this up.
> 
> Could you explain to me, what you mean by "built-in report ability doesn't cover last commits from github"?

I saw somewhere(tooltip of the PE button), the possibility of sending a crash log, but after reporting one I have forgotten the mail... So, I didn't know where to look at. Furthermore, I had scrolled through README, even read a privacy policy on your site, then I ended up with searching in source code to find what I saw - then, when I wanted to create another bug report, I saw that you mention it at the end of template of bug report on GitHub.

**Comment by johannesjo** [comment]
Ah alright I understand now. A good example is the current steady inflow of "cannot destructure property task of undefined" issues :)

At the same time, I'd like to make it as easy as possible to create an issue, if such an error occurs. It's the first time that so many issues were created on the same subject, but it is a bit annoying I admit :)
