### ISSUE TITLE
Schedule multiple tasks at a time

### ISSUE THREAD

**Issue by halloichbingunnar** [johannesjo/super-productivity#1755]
## Problem Statement

When planning my week, I often have to reschedule tasks. I vaguely schedule tasks a few weeks ahead, because I think then I could have the time and schedule them in my actual week planning, or, at least, to be reminded about their existence. But often I have to re-schedule them (maybe some new tasks came in in the meantime or just because of regular bad time management 🙃) 

It would be so great if I could select more than one at a time to schedule, as these tasks are mostly either interconnected or anyways just scheduled for future re-scheduling.

## :grey_question: Possible Solution

In my imagination, this could be done with a multi-select option (like selecting photos on a smartphone), but I guess it could be done otherwise as well :) 

## :arrow_heading_up: Describe alternatives you've considered

But the solution could be as well another workflow: Maybe there is another option to be reminded about future tasks without all the scheduling at all?

**Comment by johannesjo** [comment]
Hi Gunnar! :) Thanks for the suggestion! Makes absolute sense, to offer a way to do so, though I am yet unsure how the ui could look like. Generally it would be nice to edit multiple tasks at once. It's a bit tricky, since there are a lot of side effects to consider, but it is definitely on my personal wish-list, too.

So this is related: #573

**Comment by halloichbingunnar** [comment]
Whoops, I must have missed this same issue despite my try with the search function... Sorry! But it is great to heat that it's on the wishlist!🌟

UI-wise I could imagine e.g. a checkbox where the "drag" symbol is now. If that's too much visual clutter, I could imagine it being visible only when pressing shift, as this would be the intuitive action for me when I'd like to select multiple items.
