### ISSUE TITLE
Full sync of the task state not only task list

### ISSUE THREAD

**Issue by farynam** [johannesjo/super-productivity#1757]
## Problem Statement
I'm was trying to use super-productivity on two of my laptops and an android device. Task list are sync out of box which is good however after I have changed one of the tasks to "in execution state" the change was not propagated to the rest of my devices. It will be nice feature as the most of the users share this list through various devices.

## :grey_question: Possible Solution
Please add a full task state sync. It will require adding an functionality to save such metadata to a caldav. 

## :arrow_heading_up: Describe alternatives you've considered
I dont see many convenient alternatives here. Probably the closest one is to use some king nfs share to hold all of task related data and mount such a share as task dir. However this solutions requires pooling of this share so rather ugly way to solve this. Besides it requires a lot configuration from the user side.

## :heavy_plus_sign: Additional context
Not in my knowledge.

**Comment by johannesjo** [comment]
Not sure if I understand you correctly. You mean like a live sync, that when I enable tracking on one device, that it also enables tracking on another device?
