### ISSUE TITLE
Duplicated worklog in JIRA after marking a task as done

### ISSUE THREAD

**Issue by jac1013** [johannesjo/super-productivity#176]
### Your Environment
* Version used: superProductivity_2.7.4_amd64
* Operating System and version: Linux Mint 19
* Desktop Environment: Cinnamon

### Expected Behavior
* When marking a task as done and uploading the worklog onto JIRA those should only appear once and not twice, it seems like the application is making the request twice because I see the success message blinking and appearing twice.

* The worklog should only appear once in JIRA, also, I think worklogs in super productivity should be marked as "sync" that way if users mark the same task as done multiple times we only upload the worklogs that are NOT marked as "sync".

### Current Behavior
* Super productivity is creating duplicated worklogs in JIRA

### Steps to Reproduce (for bugs)
1. Have a JIRA integration working
2. Find a task of one of your projects.
3. Log some time into that task.
4. Mark it as done BUT set the status to TO DO again
5. You are prompted with the worklog that was created in this task. Proceed and save them into JIRA
6. Check the Worklogs in JIRA, you will notice that they appear twice.

**Comment by johannesjo** [comment]
Thank you very much for reporting. I'll look into it as soon as I can (maybe this Friday).

**Comment by johannesjo** [comment]
Hopefully this should be fixed with the next release. Please let me know if it works out for you.

**Comment by jac1013** [comment]
Hey @johannesjo this is fixed now, thank you very much!
