### ISSUE TITLE
Summarize monthly spent time by project

### ISSUE THREAD

**Issue by ced75** [johannesjo/super-productivity#1763]
Hi and thanks a lot for super-productivity, which is a very nice tool.

## Problem Statement
In worklog orptions, it is possible to group worklog entries by task./subtask, parent task, but not by project.

## :grey_question: Possible Solution
Would it be possible to add this entry (project) in worklog group by parameters?

Thanks in advance,
Cedric

**Comment by johannesjo** [comment]
Thanks for opening this up. PRs are welcome!

**Comment by ced75** [comment]
Still relevant.

**Comment by ced75** [comment]
Still relevant.

**Comment by ced75** [comment]
Still relevant.
