### ISSUE TITLE
Not able to edit task or subtask titles in web or desktop

### ISSUE THREAD

**Issue by devismi** [johannesjo/super-productivity#1765]
### Your Environment

- Version used: Desktop 7.8.1, Web 7.8.1
- Operating System and version: Windows 10 Enterprise 20H2 (64 bit)
- Desktop Environment: N/A
- Browser Name and version: Chrome version 96.0.4664.110 (64 bit)

### Expected Behavior

When a task or subtask title is clicked, or the "edit title" shortcut key is pressed while a task is selected, the title of that task or subtask should becomes highlighted and editable.

### Current Behavior

The actual behavior (which I first noticed approximately a month ago, likely following an update to SP or my own OS) is that when a task title is single-clicked the task title does _not_ become editable. Instead the task info bar appears and disappears on the right as if I were clicking the "speech bubble" icon instead of the task title. Pressing the shortcut key that is mapped to "editing task title" has no effect.  Sub-task titles are also uneditable, but there's an additional problem that when I create a new sub-task it automatically creates a blank task with no option to specify the task title initially. Since I also can't edit the sub-task's title, sub-tasks are now completely unusable for me. 
- **This behavior is identical across both the desktop app and the web app when used on my work computer**.
- I have tried uninstalling and reinstalling the desktop app with no change to this behavior.
- However, **both the web and desktop versions of the app work as expected _without_ the above-described bug on my home computer.** My home computer is running Windows 10 Pro 20H2, with the same version of the Chrome browser as my work computer (96.0.4664.110, 64 bit).  So this bug seems to only be associated with my work computer that runs Windows 10 Enterprise.

### Steps to Reproduce (for bugs)

Unfortunately, I'm not sure how to guarantee a reproduction of this bug. The obvious different between the computer where the bug consistently occurs and the computer where the bug does not seem to occur is the the former is running Windows 10 Enterprise and the latter is running Windows 10 Pro. I noted that there was a similar issue reported by others in November 2020 for an earlier version of SP that was closed without being resolved; those users were also using Windows 10 Enterprise on the computers that had the problem.

Here are my steps:

1. Install the 7.8.1 desktop app or open the web app in the Chrome browser, on a computer running Windows 10 Enterpise 20H2 (A Microsoft Surface Pro 4, to be specific!)
2. Create a task
3. Single-click on the task title. If the bug is happening the title will not become editable - instead, the tasks's info bar opens on the right side.
4. Pressing the shortcut key for "edit task title" will have no effect.
5. Right-clicking on a task and selecting "Add sub task" creates a blank sub-task that is not editable.

Tomorrow I will see if my co-worker can replicate the problem on their very similar work computer, also running Windows 10 Enterprise. I haven't generated any error logs to share.

Please let me know if anyone else is able to replicate this issue. I was successfully using SP on my work computer for several months before noting this issue, and I really love it - I hope there might be a way to resolve this. Happy to experiment more and offer any information that might be helpful.

**Comment by johannesjo** [comment]
Hey there! Thank you very much for reporting this! This is most likely related to your device having a mouse and a touchscreen. Could you maybe do me a favor and open up a console (Ctrl+Shift+i) once for the app and once in your main browser and test the return values of the following commands:
``` 
[
  'any-hover: hover',
  'any-hover: none',
  'pointer: fine',
  'pointer: coarse',
  'hover: hover',
  'hover: none',
].forEach((v) => {
  console.log(v, window.matchMedia('(' + v + ')').matches);
});
```

**Comment by johannesjo** [comment]
This should be fixed with the next release!Thank you for your help!

Please let me know if this issue persists regardless once the new version is released!
