### ISSUE TITLE
Improve performance for big projects

### ISSUE THREAD

**Issue by korvinko** [johannesjo/super-productivity#1766]
## Problem Statement

Slow rendering project pages with > 250 tasks. It takes ~ 3 seconds on my PC.

## :grey_question: Possible Solution

Use virtual scroll like this https://github.com/rintoj/ngx-virtual-scroller

## :arrow_heading_up: Describe alternatives you've considered

Use paging instead of rendering the whole list of tasks

**Comment by johannesjo** [comment]
Thanks for opening this up! Makes sense to improve this. Personally I deal with this by using the project backlogs and moving done tasks to the archive. Also helps to do a bit of housekeeping. 250 open tasks would make uncomfortable :D
