### ISSUE TITLE
Your data seems to be damaged ("{{valadityError}}").

### ISSUE THREAD

**Issue by sahu-ayush56** [johannesjo/super-productivity#1767]
I am getting above error when trying to import my data from file after updating to 7.8.1 version.
The data was exported before upgrading.
Any fixes that I can apply to the json file?

### Your Environment

- Version used:  7.8.1
- Operating System and version: Ubuntu 20.04.3 LTS

![image](https://user-images.githubusercontent.com/65887846/146549973-fcec30d0-ae66-4ac2-b723-07a5e77a8d32.png)

**Comment by sahu-ayush56** [comment]
![image](https://user-images.githubusercontent.com/65887846/146549917-f3638242-a2f7-4ad3-8d27-1f07892c81a8.png)

**Comment by johannesjo** [comment]
Hi there! Thanks for opening this up. Could you maybe post the console output (Ctrl+Shift+i)? 

Normally hitting ok, should automatically fix the problem.

**Comment by sahu-ayush56** [comment]
Thanks Console Output helped me which was ' Inconsistent entity state "note" ' so I changed the "note":{} to "note":{"ids":[],"entities":{},"todayOrder":[],"__modelVersion":1} and It worked !!

**Comment by johannesjo** [comment]
But the automatic fix did not work?

**Comment by sahu-ayush56** [comment]
No, I tried several times but everytime the app got stuck.

**Comment by johannesjo** [comment]
Do you by any chance have an export of the broken data somewhere? I'd like to take a look, what went wrong with the autofix script.

**Comment by sahu-ayush56** [comment]
Yes, I uploaded it here [https://drive.google.com/file/d/16mEQTai1FJFCVCb-5XRfTEFakP0BBlrV/view?usp=sharing]

**Comment by sahu-ayush56** [comment]
Yes, Here's the link [sp.json](https://drive.google.com/file/d/16mEQTai1FJFCVCb-5XRfTEFakP0BBlrV/view?usp=sharing)

**Comment by sahu-ayush56** [comment]
Sure, Here's the link [sp.json](https://drive.google.com/file/d/1bNpD6irHnunSZ6nbjZBufdaNe17xPLqC/view?usp=sharing)
I will notify here after accepting the request access.
```I have removed access token from the data```

**Comment by johannesjo** [comment]
Thank you very much!

**Comment by johannesjo** [comment]
Alternatively you can also send the data to contact@super-productivity.com.

**Comment by sahu-ayush56** [comment]
I have accepted the request access and Thank u ! for making this app.
