### ISSUE TITLE
Show & Focus/Hide Sidenav

### ISSUE THREAD

**Issue by intnick** [johannesjo/super-productivity#1768]
### Your Environment
Windows desktop app

- Version used: 7.8.7
- Operating System and version: Windows 10
- Desktop Environment: 
- Browser Name and version: 

### Expected Behavior
After we close the sidenav with the keyboard shortcut, and we hit the keyboard shortcut again, the SideNav should open

### Current Behavior
SideNav doesn't re-open

### Steps to Reproduce (for bugs)

1. Check what is your mapped keyboard shortcut (Shift+D is default)
2. Hit the keyboard shortcut, the sideNav goes away
3. Hit the keyboard shortcut again, the sideNav does not appear again and there is no way to get it back, you have to restart the app

**Comment by johannesjo** [comment]
Thanks for opening this up. I am unable to reproduce this. Did you try using another keyboard shortcut? Maybe there is some conflict? Apart from that: What is the console output (ctrl+shift+i)? Also: The app needs focus for the keyboard shortcut to work (just click at some empty space to do so).

**Comment by Petemir** [comment]
@johannesjo I am having a similar error. This only happens when I get to dismiss the sidebar by pressing the ESC key (it doesn't happen always). Then, I cannot get it back with the default shortcut, nor with any other that I may setup. The other shortcuts work correctly. The funny thing: if I open the developer's console, and I close it, most of the time I get the nav-bar back :) .

**Comment by idkhowisyourday** [comment]
> @johannesjo I am having a similar error. This only happens when I get to dismiss the sidebar by pressing the ESC key (it doesn't happen always). Then, I cannot get it back with the default shortcut, nor with any other that I may setup. The other shortcuts work correctly. The funny thing: if I open the developer's console, and I close it, most of the time I get the nav-bar back :) .

currently I am facing a similar issue as well, there are workarounds such as just dragging the window from fullscreen to windowed but i hope this can get resolved.

**Comment by argonarch** [comment]
a solution temporal is change variable NAV_ALWAYS_VISIBLE = 1200; to NAV_ALWAYS_VISIBLE = 2000; in src/app/core-ui/layout/layout.service.ts and compiler, with this you can control toggle sidenav with a button

**Comment by robinsrk** [comment]
Facing the same issue. I can only focus on sidenav with shortcut. Can't toggle sidenav with shortcut. And when i close the sidenav with esc key, i can't reopen with shortcut. Need to close and reopen the app
