### ISSUE TITLE
Can't open restored compressed file after it was reset

### ISSUE THREAD

**Issue by porkyneal** [johannesjo/super-productivity#1769]
So at somepoint, I got a cryptic question which i can no longer remember on one of my machines, I assume after an update. I thought I hit cancel. Now, I have an empty file that has synced through my Google Drive. I have restored the correct file, but it will not open on either machine.

I assume the file is compressed as it is not text.

I would like to figure out a way to restore these tasks.

Importing results in a not JSON error:

![image](https://user-images.githubusercontent.com/8297625/146696113-ac4216d1-aaa4-456a-8873-832064be12cb.png)

### Your Environment
- Version used: 7.8.1 (auto updated)
- Operating System and version: Win 10

### Expected Behavior

Load my tasks

### Current Behavior

I can't load an existing (compressed) file from google drive

### Steps to Reproduce (for bugs)

Unsure how this all happened

### Console Output

![image](https://user-images.githubusercontent.com/8297625/146696020-d4d8abc5-b261-4156-82f1-616fcc835c0a.png)

**Comment by johannesjo** [comment]
Hi there! Not sure if I understand the problem correctly, but an empty file can't be loaded. If you want to start fresh, I'd recommend deleting the file and create one from super productivity with a different name and use that one.

**Comment by porkyneal** [comment]
Maybe I was not clear, apologies.

I have a 49kb JSON file that has recorded my tasks for the last few months inside the app, it has all my recorded data and project information that I really need to get back.

I use two machines, so therefore sync through Google Drive. It has been working well for some time.

A week or so ago, a message on one of my machines popped up about being out of sync, I hit cancel, as I was unsure on what it was asking, and did not have time to resolve.

When I went to use the software again, all my tasks we're gone, on both machines.

I am now trying to restore the file, using previous version in google drive, but when I reset the app to use the new file, it keeps resetting to a blank position.

I would really like my data back, so that I can continue tracking my time. Many thanks,

Below console log, is selecting the 49KB file. It does not work, and resets the file (6kb).

![image](https://user-images.githubusercontent.com/8297625/146765791-cea34d5f-5471-4c70-9803-a4014ec50013.png)

**Comment by johannesjo** [comment]
Ah alright. Understood. Could you maybe send me the file, so I can have a look at it (contact@super-productivity.com)?

**Comment by porkyneal** [comment]
Thanks, will send it over now.

**Comment by johannesjo** [comment]
This can be closed right?

**Comment by porkyneal** [comment]
Yes, many thanks for your assistance.
