### ISSUE TITLE
Pomodoro minimized mode

### ISSUE THREAD

**Issue by cjdduarte** [johannesjo/super-productivity#1771]
I miss a pomodoro "mode". where you have only the watch. It would be possible?

[](url)
![pomodoro](https://user-images.githubusercontent.com/42243532/146905385-3e3eb3dd-5b39-452c-b04e-7c03f1f12edb.png)

**Comment by johannesjo** [comment]
Thanks for opening this up! What you already can do is to just make the window very small.
