### ISSUE TITLE
Error: Uncaught (in promise):

### ISSUE THREAD

**Issue by Houssem12-ai** [johannesjo/super-productivity#1776]
TypeError: Cannot read properties of undefined (reading 'config')TypeError: Cannot read properties of undefined (reading 'config')    at n. (file:///snap/superproductivity/1520/resources/app.asar/dist/main.eba06d3bcf1bd23b.js:1:3017089)    at Generator.next ()    at file:///snap/superproductivity/1520/resources/app.asar/dist/main.eba06d3bcf1bd23b.js:1:3016623    at new t (file:///snap/superproductivity/1520/resources/app.asar/dist/polyfills.bc7366b7ec378721.js:1:17768)    at kO (file:///snap/superproductivity/1520/resources/app.asar/dist/main.eba06d3bcf1bd23b.js:1:3016360)    at FileReader.s.onload (file:///snap/superproductivity/1520/resources/app.asar/dist/main.eba06d3bcf1bd23b.js:1:3016892)    at T.invoke (file:///snap/superproductivity/1520/resources/app.asar/dist/polyfills.bc7366b7ec378721.js:1:6511)    at Object.onInvoke (file:///snap/superproductivity/1520/resources/app.asar/dist/main.eba06d3bcf1bd23b.js:1:3767415)    at T.invoke (file:///snap/superproductivity/1520/resources/app.asar/dist/polyfills.bc7366b7ec378721.js:1:6451)    at I.runGuarded (file:///snap/superproductivity/1520/resources/app.asar/dist/polyfills.bc7366b7ec378721.js:1:2030)

### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
Array.isArray (webpack:///src/app/imex/file-imex/file-imex.component.ts:43:18)
recurse (webpack:///src/app/imex/file-imex/privacy-export.ts:56:24)
constructor (webpack:///node_modules/zone.js/fesm2015/zone.js:1387:28)
recurse (webpack:///src/app/imex/file-imex/privacy-export.ts:56:24)
constructor (webpack:///src/app/imex/file-imex/file-imex.component.ts:32:31)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/fesm2020/core.mjs:25476:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:371:51)
runGuarded (webpack:///node_modules/zone.js/fesm2015/zone.js:144:46)
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1213:30)
executor(makeResolver (webpack:///node_modules/zone.js/fesm2015/zone.js:1390:16)
recurse (webpack:///src/app/imex/file-imex/privacy-export.ts:56:24)
constructor (webpack:///src/app/imex/file-imex/file-imex.component.ts:32:31)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/fesm2020/core.mjs:25476:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:371:51)
runGuarded (webpack:///node_modules/zone.js/fesm2015/zone.js:144:46)
function (webpack:///node_modules/zone.js/fesm2015/zone.js:128:28)
```

### Meta Info
META: SP7.8.1 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.8.1 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1640532397810: [SP_ALL] Load(import) all data 
1640532397819: [SP_ALL] All Data was loaded 
1640532400846: [Layout] Toggle SideBar
```

**Comment by johannesjo** [comment]
Hey there! Thank you very much for reporting this!

It might be that for some reason a bit of your data got into an invalid state that I didn't account for and that I can't reproduce. It would be great if you could share a copy of your data to contact@super-productivity.com, so I can debug this on my computer. You can create an export by navigating to "Settings" and then to "Import/Export" or you can use the "Export data" button from the error Dialog.

**Comment by johannesjo** [comment]
Also this looks like a duplicate of #1775
