### ISSUE TITLE
[Bug] Auto-switch theme in macOS mojave doesn't work 

### ISSUE THREAD

**Issue by Kl4tch** [johannesjo/super-productivity#179]
Hello, thanks for updates
But for macOS Mojave it doesn't work
https://www.youtube.com/watch?v=3USEf8L_Xto&feature=youtu.be
Left - app on electron too

**Comment by johannesjo** [comment]
This should be hopefully fixed with the next release. Unfortunately I can't test it atm because I don't currently have a mac available.

**Comment by johannesjo** [comment]
Should be fixed, I assume. Please let me know if it isn't.
