### ISSUE TITLE
Improved note takeing

### ISSUE THREAD

**Issue by BenHerbst** [johannesjo/super-productivity#1794]
## Problem Statement
Notes are currently only simple text.

## :grey_question: Possible Solution
 Extend it to images, add todo items into notes etc.

## :arrow_heading_up: Describe alternatives you've considered
Todo projects and note taking projects.

## :heavy_plus_sign: Additional context
None.

**Comment by johannesjo** [comment]
Thank you very much for opening this up! You can already use markdown to do all that.

**Comment by BenHerbst** [comment]
Okay, that is cool, maybe make add a text label: You can use markdown here. An online tutorial for markdown: https://...

**Comment by johannesjo** [comment]
That is a good idea! Thanks!
