### ISSUE TITLE
Kanban view

### ISSUE THREAD

**Issue by BenHerbst** [johannesjo/super-productivity#1796]
## Problem Statement
Have to use todolist layout.

## :grey_question: Possible Solution
Add a kanban view to use the kanban technique. And an option to transform a todo project to a kanban one.

## :arrow_heading_up: Describe alternatives you've considered
Only kanban view.

## :heavy_plus_sign: Additional context
None.

**Comment by BenHerbst** [comment]
Didnt saw the existing issue.

**Comment by johannesjo** [comment]
#374
