### ISSUE TITLE
Drag-and-drop to Backlog area does not work for the 1st task

### ISSUE THREAD

**Issue by nkrot** [johannesjo/super-productivity#1799]
When I open Backlog area in a project and the backlog is empty and I try to move a task into backlog by dragging and dropping it, it does not work. However, if there is already a task in the backlog, then dragging and dropping works.

Looks like the only way to move a task to backlog is via context menu (right click and select menu item).

### Your Environment

- Version used: 7.9.1
- Operating System and version: Ubuntu 18.04
- Desktop Environment: MATE
- Browser Name and version: Firefox, 89.0

**Comment by johannesjo** [comment]
Thank you for opening this up! I'll have a look!

**Comment by johannesjo** [comment]
Thanks again! This should be fixed with the next release.
