### ISSUE TITLE
Cant sync with dropbox

### ISSUE THREAD

**Issue by BenHerbst** [johannesjo/super-productivity#1800]
### Your Environment

- Version used: 7.9.2
- Operating System and version: Android 11
- Desktop Environment: 
- Browser Name and version: 

### Expected Behavior

Snyc with dropbox works.

### Current Behavior

![IMG_20220105_142139.jpg](https://user-images.githubusercontent.com/83538916/148224617-43c5a221-dd2a-4555-8f75-7bf8369a18ec.jpg)

### Steps to Reproduce (for bugs)

1. Login with dropbox
2.press sync button

### Console Output

I post when I try at pc later

**Comment by johannesjo** [comment]
Thanks for reporting this! I am glad that it works now! I leave this open in case more people encounter the problem.

**Comment by johannesjo** [comment]
I was able to reproduce this issue now with a fresh account. Seems like that for some reason the dropbox api server response is a bit inconsistent for when the files are not yet created yet. I think I was able to fix the issue. Thank you very much for your help!
