### ISSUE TITLE
Error: Uncaught (in promise): Error: TypeError: Cannot read properties of null (reading 'isEnabled')Error: TypeError: Cannot read properties of null (reading 'isEnabled')    at n....

### ISSUE THREAD

**Issue by jeensg** [johannesjo/super-productivity#1802]
...(file:///snap/superproductivity/1545/resources/app.asar/dist/main.bb3078299280df47.js:1:2215712)    at Generator.next ()    at h (file:///snap/superproductivity/1545/resources/app.asar/dist/main.bb3078299280df47.js:1:2212784)    at T.invoke (file:///snap/superproductivity/1545/resources/app.asar/dist/polyfills.94238d1595150347.js:1:6575)    at Object.onInvoke (file:///snap/superproductivity/1545/resources/app.asar/dist/main.bb3078299280df47.js:1:3691849)    at T.invoke (file:///snap/superproductivity/1545/resources/app.asar/dist/polyfills.94238d1595150347.js:1:6515)    at I.run (file:///snap/superproductivity/1545/resources/app.asar/dist/polyfills.94238d1595150347.js:1:1971)    at file:///snap/superproductivity/1545/resources/app.asar/dist/polyfills.94238d1595150347.js:1:16768    at T.invokeTask (file:///snap/superproductivity/1545/resources/app.asar/dist/polyfills.94238d1595150347.js:1:7193)    at Object.onInvokeTask (file:///snap/superproductivity/1545/resources/app.asar/dist/main.bb3078299280df47.js:1:3691664)

### Steps to Reproduce
1. click through different projects
2. on 2 older projects this error occurs
3. although I can still navigate to other projects in the background
4.

### Console Output
​ @ngrx/store/init Object
​ @ngrx/store/update-reducers Object
​ @ngrx/effects/init Object
​ LOAD COMPLETE true
action-logger.reducer.ts:11 @ngrx/store/update-reducers Object
app.component.ts:277 Persistence already allowed
app.component.ts:306 2 out of 97612 MiB used (0%)
reminder.service.ts:92 loaded reminders from database Array(0)
model-version.ts:36 [M] Migrating model "GlobalConfig" to version from 2.2005 to 2.2006 Object
migrate-global-config.util.ts:111 EXTEND globalConfig misc isConfirmBeforeExitWithoutFinishDay true
migrate-global-config.util.ts:111 EXTEND globalConfig timeline calendarProviders Array(0)
model-version.ts:36 [M] Migrating model "SimpleCounter" to version from undefined to 2 Object
model-version.ts:36 [M] Migrating model "Improvement" to version from undefined to 1 Object
model-version.ts:36 [M] Migrating model "Obstruction" to version from undefined to 1 Object
model-version.ts:36 [M] Migrating model "TaskRepeat" to version from 1 to 1.3 Object
action-logger.reducer.ts:11 [SP_ALL] Load(import) all data Object
action-logger.reducer.ts:11 [SP_ALL] All Data was loaded Object
action-logger.reducer.ts:11 [WorkContext] Set Active Work Context Object
global-error-handler.class.ts:33 GLOBAL_ERROR_HANDLER TypeError: Cannot read properties of null (reading 'isEnabled')
    at cC (is-jira-enabled.util.ts:3)
    at jira-issue.effects.ts:258
    at m._next (filter.js:26)
    at m.next (Subscriber.js:49)
    at C.notifyNext (mergeMap.js:70)
    at m._next (innerSubscribe.js:10)
    at m.next (Subscriber.js:49)
    at pg._next (throwIfEmpty.js:24)
    at pg.next (Subscriber.js:49)
    at C._next (take.js:35)
(anonymous) @ global-error-handler.class.ts:33
(anonymous) @ global-error-handler.util.ts:227
t @ zone.js:1387
kH @ global-error-handler.util.ts:227
handleError @ global-error-handler.class.ts:29
(anonymous) @ ngrx-effects.mjs:161
error @ catchError.js:27
_error @ tap.js:56
error @ Subscriber.js:55
_error @ Subscriber.js:75
error @ Subscriber.js:55
_next @ filter.js:29
next @ Subscriber.js:49
notifyNext @ mergeMap.js:70
_next @ innerSubscribe.js:10
next @ Subscriber.js:49
_next @ throwIfEmpty.js:24
next @ Subscriber.js:49
_next @ take.js:35
next @ Subscriber.js:49
_next @ distinctUntilChanged.js:50
next @ Subscriber.js:49
_next @ map.js:35
next @ Subscriber.js:49
_subscribe @ BehaviorSubject.js:14
_trySubscribe @ Observable.js:42
_trySubscribe @ Subject.js:81
subscribe @ Observable.js:28
_subscribe @ Observable.js:76
subscribe @ Observable.js:27
call @ map.js:16
subscribe @ Observable.js:23
call @ distinctUntilChanged.js:11
subscribe @ Observable.js:23
call @ take.js:22
subscribe @ Observable.js:23
call @ throwIfEmpty.js:13
subscribe @ Observable.js:23
v @ innerSubscribe.js:67
_innerSub @ mergeMap.js:57
_tryNext @ mergeMap.js:51
_next @ mergeMap.js:34
next @ Subscriber.js:49
_next @ filter.js:33
next @ Subscriber.js:49
_next @ tap.js:46
next @ Subscriber.js:49
_next @ filter.js:33
next @ Subscriber.js:49
next @ Subject.js:39
(anonymous) @ ngrx-store.mjs:401
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
_tryNext @ scan.js:55
_next @ scan.js:42
next @ Subscriber.js:49
_next @ withLatestFrom.js:57
next @ Subscriber.js:49
observe @ Notification.js:20
dispatch @ observeOn.js:25
_execute @ AsyncAction.js:51
execute @ QueueAction.js:20
flush @ AsyncScheduler.js:33
schedule @ QueueAction.js:14
schedule @ Scheduler.js:7
schedule @ AsyncScheduler.js:21
scheduleMessage @ observeOn.js:30
_next @ observeOn.js:33
next @ Subscriber.js:49
next @ Subject.js:39
next @ BehaviorSubject.js:30
next @ ngrx-store.mjs:133
dispatch @ ngrx-store.mjs:446
_setActiveContext @ work-context.service.ts:445
(anonymous) @ work-context.service.ts:306
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
notifyNext @ mergeMap.js:70
_next @ innerSubscribe.js:10
next @ Subscriber.js:49
(anonymous) @ subscribeToArray.js:3
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
v @ innerSubscribe.js:67
_innerSub @ mergeMap.js:57
_tryNext @ mergeMap.js:51
_next @ mergeMap.js:34
next @ Subscriber.js:49
_next @ withLatestFrom.js:57
next @ Subscriber.js:49
_next @ filter.js:33
next @ Subscriber.js:49
next @ Subject.js:39
(anonymous) @ router.mjs:4802
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
notifyNext @ switchMap.js:66
_next @ innerSubscribe.js:10
next @ Subscriber.js:49
_next @ Subscriber.js:72
next @ Subscriber.js:49
_next @ Subscriber.js:72
next @ Subscriber.js:49
_next @ tap.js:46
next @ Subscriber.js:49
_next @ map.js:35
next @ Subscriber.js:49
_next @ tap.js:46
next @ Subscriber.js:49
_next @ map.js:35
next @ Subscriber.js:49
notifyNext @ switchMap.js:66
_next @ innerSubscribe.js:10
next @ Subscriber.js:49
_next @ map.js:35
next @ Subscriber.js:49
(anonymous) @ subscribeToArray.js:3
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
call @ map.js:16
subscribe @ Observable.js:23
v @ innerSubscribe.js:67
_innerSub @ switchMap.js:44
_next @ switchMap.js:34
next @ Subscriber.js:49
notifyNext @ switchMap.js:66
_next @ innerSubscribe.js:10
next @ Subscriber.js:49
_next @ map.js:35
next @ Subscriber.js:49
_next @ tap.js:46
next @ Subscriber.js:49
notifyNext @ switchMap.js:66
_next @ innerSubscribe.js:10
next @ Subscriber.js:49
_next @ tap.js:46
next @ Subscriber.js:49
notifyNext @ mergeMap.js:70
_next @ innerSubscribe.js:10
next @ Subscriber.js:49
notifyNext @ mergeMap.js:70
_next @ innerSubscribe.js:10
next @ Subscriber.js:49
(anonymous) @ subscribeToArray.js:3
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
v @ innerSubscribe.js:67
_innerSub @ mergeMap.js:57
_tryNext @ mergeMap.js:51
_next @ mergeMap.js:34
next @ Subscriber.js:49
_complete @ takeLast.js:52
complete @ Subscriber.js:61
_complete @ tap.js:66
complete @ Subscriber.js:61
_complete @ mergeMap.js:65
complete @ Subscriber.js:61
(anonymous) @ subscribeToArray.js:5
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
call @ mergeMap.js:19
subscribe @ Observable.js:23
call @ tap.js:16
subscribe @ Observable.js:23
call @ takeLast.js:22
subscribe @ Observable.js:23
call @ mergeMap.js:19
subscribe @ Observable.js:23
v @ innerSubscribe.js:67
_innerSub @ mergeMap.js:57
_tryNext @ mergeMap.js:51
_next @ mergeMap.js:34
next @ Subscriber.js:49
(anonymous) @ subscribeToArray.js:3
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
call @ mergeMap.js:19
subscribe @ Observable.js:23
call @ tap.js:16
subscribe @ Observable.js:23
v @ innerSubscribe.js:67
_innerSub @ switchMap.js:44
_next @ switchMap.js:34
next @ Subscriber.js:49
_next @ tap.js:46
next @ Subscriber.js:49
(anonymous) @ subscribeToArray.js:3
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
call @ tap.js:16
subscribe @ Observable.js:23
call @ switchMap.js:15
subscribe @ Observable.js:23
call @ tap.js:16
Show 170 more frames
action-logger.ts:42 Last actions before error: Array(30)
persistence.service.ts:338 LOAD COMPLETE false
global-error-handler.class.ts:33 GLOBAL_ERROR_HANDLER TypeError: Cannot read properties of null (reading 'isEnabled')
    at cC (is-jira-enabled.util.ts:3)
    at n.isEnabled (jira-common-interfaces.service.ts:40)
    at m.project (jira-common-interfaces.service.ts:29)
    at m._next (map.js:29)
    at m.next (Subscriber.js:49)
    at pg._next (throwIfEmpty.js:24)
    at pg.next (Subscriber.js:49)
    at C._next (take.js:35)
    at C.next (Subscriber.js:49)
    at m._next (distinctUntilChanged.js:50)
(anonymous) @ global-error-handler.class.ts:33
(anonymous) @ global-error-handler.util.ts:227
t @ zone.js:1387
kH @ global-error-handler.util.ts:227
handleError @ global-error-handler.class.ts:29
(anonymous) @ ngrx-effects.mjs:161
error @ catchError.js:27
notifyError @ innerSubscribe.js:45
_error @ innerSubscribe.js:13
error @ Subscriber.js:55
notifyError @ innerSubscribe.js:45
_error @ innerSubscribe.js:13
error @ Subscriber.js:55
_error @ Subscriber.js:75
error @ Subscriber.js:55
_next @ map.js:32
next @ Subscriber.js:49
_next @ throwIfEmpty.js:24
next @ Subscriber.js:49
_next @ take.js:35
next @ Subscriber.js:49
_next @ distinctUntilChanged.js:50
next @ Subscriber.js:49
_next @ map.js:35
next @ Subscriber.js:49
_subscribe @ BehaviorSubject.js:14
_trySubscribe @ Observable.js:42
_trySubscribe @ Subject.js:81
subscribe @ Observable.js:28
_subscribe @ Observable.js:76
subscribe @ Observable.js:27
call @ map.js:16
subscribe @ Observable.js:23
call @ distinctUntilChanged.js:11
subscribe @ Observable.js:23
call @ take.js:22
subscribe @ Observable.js:23
call @ throwIfEmpty.js:13
subscribe @ Observable.js:23
call @ map.js:16
subscribe @ Observable.js:23
call @ switchMap.js:15
subscribe @ Observable.js:23
v @ innerSubscribe.js:67
_innerSub @ mergeMap.js:57
_tryNext @ mergeMap.js:51
_next @ mergeMap.js:34
next @ Subscriber.js:49
(anonymous) @ subscribeToArray.js:3
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
call @ mergeMap.js:19
subscribe @ Observable.js:23
v @ innerSubscribe.js:67
_innerSub @ switchMap.js:44
_next @ switchMap.js:34
next @ Subscriber.js:49
_next @ filter.js:33
next @ Subscriber.js:49
notifyNext @ switchMap.js:66
_next @ innerSubscribe.js:10
next @ Subscriber.js:49
_next @ throwIfEmpty.js:24
next @ Subscriber.js:49
_next @ take.js:35
next @ Subscriber.js:49
_subscribe @ ReplaySubject.js:61
_trySubscribe @ Observable.js:42
_trySubscribe @ Subject.js:81
subscribe @ Observable.js:28
(anonymous) @ shareReplay.js:49
subscribe @ Observable.js:23
call @ take.js:22
subscribe @ Observable.js:23
call @ throwIfEmpty.js:13
subscribe @ Observable.js:23
v @ innerSubscribe.js:67
_innerSub @ switchMap.js:44
_next @ switchMap.js:34
next @ Subscriber.js:49
_next @ filter.js:33
next @ Subscriber.js:49
notifyNext @ switchMap.js:66
_next @ innerSubscribe.js:10
next @ Subscriber.js:49
_next @ throwIfEmpty.js:24
next @ Subscriber.js:49
_next @ take.js:35
next @ Subscriber.js:49
_subscribe @ ReplaySubject.js:61
_trySubscribe @ Observable.js:42
_trySubscribe @ Subject.js:81
subscribe @ Observable.js:28
(anonymous) @ shareReplay.js:49
subscribe @ Observable.js:23
call @ take.js:22
subscribe @ Observable.js:23
call @ throwIfEmpty.js:13
subscribe @ Observable.js:23
v @ innerSubscribe.js:67
_innerSub @ switchMap.js:44
_next @ switchMap.js:34
next @ Subscriber.js:49
notifyNext @ mergeMap.js:70
_next @ innerSubscribe.js:10
next @ Subscriber.js:49
_next @ filter.js:33
next @ Subscriber.js:49
next @ Subject.js:39
(anonymous) @ ngrx-store.mjs:401
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
_tryNext @ scan.js:55
_next @ scan.js:42
next @ Subscriber.js:49
_next @ withLatestFrom.js:57
next @ Subscriber.js:49
observe @ Notification.js:20
dispatch @ observeOn.js:25
_execute @ AsyncAction.js:51
execute @ QueueAction.js:20
flush @ AsyncScheduler.js:33
schedule @ QueueAction.js:14
schedule @ Scheduler.js:7
schedule @ AsyncScheduler.js:21
scheduleMessage @ observeOn.js:30
_next @ observeOn.js:33
next @ Subscriber.js:49
next @ Subject.js:39
next @ BehaviorSubject.js:30
next @ ngrx-store.mjs:133
dispatch @ ngrx-store.mjs:446
_setActiveContext @ work-context.service.ts:445
(anonymous) @ work-context.service.ts:306
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
notifyNext @ mergeMap.js:70
_next @ innerSubscribe.js:10
next @ Subscriber.js:49
(anonymous) @ subscribeToArray.js:3
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
v @ innerSubscribe.js:67
_innerSub @ mergeMap.js:57
_tryNext @ mergeMap.js:51
_next @ mergeMap.js:34
next @ Subscriber.js:49
_next @ withLatestFrom.js:57
next @ Subscriber.js:49
_next @ filter.js:33
next @ Subscriber.js:49
next @ Subject.js:39
(anonymous) @ router.mjs:4802
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
notifyNext @ switchMap.js:66
_next @ innerSubscribe.js:10
next @ Subscriber.js:49
_next @ Subscriber.js:72
next @ Subscriber.js:49
_next @ Subscriber.js:72
next @ Subscriber.js:49
_next @ tap.js:46
next @ Subscriber.js:49
_next @ map.js:35
next @ Subscriber.js:49
_next @ tap.js:46
next @ Subscriber.js:49
_next @ map.js:35
next @ Subscriber.js:49
notifyNext @ switchMap.js:66
_next @ innerSubscribe.js:10
next @ Subscriber.js:49
_next @ map.js:35
next @ Subscriber.js:49
(anonymous) @ subscribeToArray.js:3
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
call @ map.js:16
subscribe @ Observable.js:23
v @ innerSubscribe.js:67
_innerSub @ switchMap.js:44
_next @ switchMap.js:34
next @ Subscriber.js:49
notifyNext @ switchMap.js:66
_next @ innerSubscribe.js:10
next @ Subscriber.js:49
_next @ map.js:35
next @ Subscriber.js:49
_next @ tap.js:46
next @ Subscriber.js:49
notifyNext @ switchMap.js:66
_next @ innerSubscribe.js:10
next @ Subscriber.js:49
Show 170 more frames
action-logger.ts:42 Last actions before error: Array(30)
persistence.service.ts:338 LOAD COMPLETE false
action-logger.reducer.ts:11 [Task] SetSelectedTask Object
action-logger.reducer.ts:11 [Bookmark] Load Bookmark State Object
action-logger.reducer.ts:11 [Project] Load Project related Data Success Object
action-logger.reducer.ts:11 [Improvement] Clear Hidden Improvements Object
action-logger.reducer.ts:11 [Improvement] Delete multiple Improvements Object
model-version.ts:36 [M] Migrating model "GlobalConfig" to version from 2.2005 to 2.2006 Object
migrate-global-config.util.ts:111 EXTEND globalConfig misc isConfirmBeforeExitWithoutFinishDay true
migrate-global-config.util.ts:111 EXTEND globalConfig timeline calendarProviders Array(0)
model-version.ts:36 [M] Migrating model "SimpleCounter" to version from undefined to 2 Object
model-version.ts:36 [M] Migrating model "Improvement" to version from undefined to 1 Object
model-version.ts:36 [M] Migrating model "Obstruction" to version from undefined to 1 Object
model-version.ts:36 [M] Migrating model "TaskRepeat" to version from 1 to 1.3 Object
model-version.ts:36 [M] Migrating model "GlobalConfig" to version from 2.2005 to 2.2006 Object
migrate-global-config.util.ts:111 EXTEND globalConfig misc isConfirmBeforeExitWithoutFinishDay true
migrate-global-config.util.ts:111 EXTEND globalConfig timeline calendarProviders Array(0)
model-version.ts:36 [M] Migrating model "SimpleCounter" to version from undefined to 2 Object
model-version.ts:36 [M] Migrating model "Improvement" to version from undefined to 1 Object
model-version.ts:36 [M] Migrating model "Obstruction" to version from undefined to 1 Object
model-version.ts:36 [M] Migrating model "TaskRepeat" to version from 1 to 1.3 Object
global-error-handler.util.ts:115 Object
global-error-handler.class.ts:33 GLOBAL_ERROR_HANDLER Error: Uncaught (in promise): Error: TypeError: Cannot read properties of null (reading 'isEnabled')
Error: TypeError: Cannot read properties of null (reading 'isEnabled')
    at n.<anonymous> (global-error-handler.class.ts:60)
    at Generator.next (<anonymous>)
    at h (global-error-handler.util.ts:227)
    at T.invoke (zone.js:372)
    at Object.onInvoke (core.mjs:25450)
    at T.invoke (zone.js:371)
    at I.run (zone.js:134)
    at zone.js:1276
    at T.invokeTask (zone.js:406)
    at Object.onInvokeTask (core.mjs:25437)
    at G (zone.js:1213)
    at zone.js:1120
    at h (global-error-handler.util.ts:227)
    at T.invoke (zone.js:372)
    at Object.onInvoke (core.mjs:25450)
    at T.invoke (zone.js:371)
    at I.run (zone.js:134)
    at zone.js:1276
    at T.invokeTask (zone.js:406)
    at Object.onInvokeTask (core.mjs:25437)
(anonymous) @ global-error-handler.class.ts:33
(anonymous) @ global-error-handler.util.ts:227
t @ zone.js:1387
kH @ global-error-handler.util.ts:227
handleError @ global-error-handler.class.ts:29
next @ core.mjs:26008
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.mjs:22395
(anonymous) @ core.mjs:25476
invoke @ zone.js:372
run @ zone.js:134
runOutsideAngular @ core.mjs:25349
onHandleError @ core.mjs:25476
handleError @ zone.js:376
runGuarded @ zone.js:147
i.microtaskDrainDone @ zone.js:1074
L @ zone.js:589
invokeTask @ zone.js:491
S @ zone.js:1600
D @ zone.js:1626
action-logger.ts:42 Last actions before error: Array(30)
persistence.service.ts:338 LOAD COMPLETE false
global-error-handler.class.ts:33 GLOBAL_ERROR_HANDLER Error: Uncaught (in promise): Error: TypeError: Cannot read properties of null (reading 'isEnabled')
Error: TypeError: Cannot read properties of null (reading 'isEnabled')
    at n.<anonymous> (global-error-handler.class.ts:60)
    at Generator.next (<anonymous>)
    at h (global-error-handler.util.ts:227)
    at T.invoke (zone.js:372)
    at Object.onInvoke (core.mjs:25450)
    at T.invoke (zone.js:371)
    at I.run (zone.js:134)
    at zone.js:1276
    at T.invokeTask (zone.js:406)
    at Object.onInvokeTask (core.mjs:25437)
    at G (zone.js:1213)
    at zone.js:1120
    at h (global-error-handler.util.ts:227)
    at T.invoke (zone.js:372)
    at Object.onInvoke (core.mjs:25450)
    at T.invoke (zone.js:371)
    at I.run (zone.js:134)
    at zone.js:1276
    at T.invokeTask (zone.js:406)
    at Object.onInvokeTask (core.mjs:25437)
(anonymous) @ global-error-handler.class.ts:33
(anonymous) @ global-error-handler.util.ts:227
t @ zone.js:1387
kH @ global-error-handler.util.ts:227
handleError @ global-error-handler.class.ts:29
next @ core.mjs:26008
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.mjs:22395
(anonymous) @ core.mjs:25476
invoke @ zone.js:372
run @ zone.js:134
runOutsideAngular @ core.mjs:25349
onHandleError @ core.mjs:25476
handleError @ zone.js:376
runGuarded @ zone.js:147
i.microtaskDrainDone @ zone.js:1074
L @ zone.js:589
invokeTask @ zone.js:491
S @ zone.js:1600
D @ zone.js:1626
action-logger.ts:42 Last actions before error: Array(30)
persistence.service.ts:338 LOAD COMPLETE false
model-version.ts:36 [M] Migrating model "GlobalConfig" to version from 2.2005 to 2.2006 Object
migrate-global-config.util.ts:111 EXTEND globalConfig misc isConfirmBeforeExitWithoutFinishDay true
migrate-global-config.util.ts:111 EXTEND globalConfig timeline calendarProviders Array(0)
model-version.ts:36 [M] Migrating model "SimpleCounter" to version from undefined to 2 Object
model-version.ts:36 [M] Migrating model "Improvement" to version from undefined to 1 Object
model-version.ts:36 [M] Migrating model "Obstruction" to version from undefined to 1 Object
model-version.ts:36 [M] Migrating model "TaskRepeat" to version from 1 to 1.3 Object
model-version.ts:36 [M] Migrating model "GlobalConfig" to version from 2.2005 to 2.2006 Object
migrate-global-config.util.ts:111 EXTEND globalConfig misc isConfirmBeforeExitWithoutFinishDay true
migrate-global-config.util.ts:111 EXTEND globalConfig timeline calendarProviders Array(0)
model-version.ts:36 [M] Migrating model "SimpleCounter" to version from undefined to 2 Object
model-version.ts:36 [M] Migrating model "Improvement" to version from undefined to 1 Object
model-version.ts:36 [M] Migrating model "Obstruction" to version from undefined to 1 Object
model-version.ts:36 [M] Migrating model "TaskRepeat" to version from 1 to 1.3 Object
2zone.js:1063 Unhandled Promise rejection: Error: Uncaught (in promise): Error: TypeError: Cannot read properties of null (reading 'isEnabled')
Error: TypeError: Cannot read properties of null (reading 'isEnabled')
    at n.<anonymous> (file:///snap/superproductivity/1545/resources/app.asar/dist/main.bb3078299280df47.js:1:2215712)
    at Generator.next (<anonymous>)
    at h (file:///snap/superproductivity/1545/resources/app.asar/dist/main.bb3078299280df47.js:1:2212784)
    at T.invoke (file:///snap/superproductivity/1545/resources/app.asar/dist/polyfills.94238d1595150347.js:1:6575)
    at Object.onInvoke (file:///snap/superproductivity/1545/resources/app.asar/dist/main.bb3078299280df47.js:1:3691849)
    at T.invoke (file:///snap/superproductivity/1545/resources/app.asar/dist/polyfills.94238d1595150347.js:1:6515)
    at I.run (file:///snap/superproductivity/1545/resources/app.asar/dist/polyfills.94238d1595150347.js:1:1971)
    at file:///snap/superproductivity/1545/resources/app.asar/dist/polyfills.94238d1595150347.js:1:16768
    at T.invokeTask (file:///snap/superproductivity/1545/resources/app.asar/dist/polyfills.94238d1595150347.js:1:7193)
    at Object.onInvokeTask (file:///snap/superproductivity/1545/resources/app.asar/dist/main.bb3078299280df47.js:1:3691664) ; Zone: <root> ; Task: Promise.then ; Value: Error: Error: Uncaught (in promise): Error: TypeError: Cannot read properties of null (reading 'isEnabled')
Error: TypeError: Cannot read properties of null (reading 'isEnabled')
    at n.<anonymous> (global-error-handler.class.ts:60)
    at Generator.next (<anonymous>)
    at h (global-error-handler.util.ts:227)
    at T.invoke (zone.js:372)
    at Object.onInvoke (core.mjs:25450)
    at T.invoke (zone.js:371)
    at I.run (zone.js:134)
    at zone.js:1276
    at T.invokeTask (zone.js:406)
    at Object.onInvokeTask (core.mjs:25437)
    at n.<anonymous> (global-error-handler.class.ts:60)
    at Generator.next (<anonymous>)
    at h (global-error-handler.util.ts:227)
    at T.invoke (zone.js:372)
    at I.run (zone.js:134)
    at zone.js:1276
    at T.invokeTask (zone.js:406)
    at I.runTask (zone.js:178)
    at L (zone.js:582)
    at m.invokeTask [as invoke] (zone.js:491) Error: Error: Uncaught (in promise): Error: TypeError: Cannot read properties of null (reading 'isEnabled')
Error: TypeError: Cannot read properties of null (reading 'isEnabled')
    at n.<anonymous> (file:///snap/superproductivity/1545/resources/app.asar/dist/main.bb3078299280df47.js:1:2215712)
    at Generator.next (<anonymous>)
    at h (file:///snap/superproductivity/1545/resources/app.asar/dist/main.bb3078299280df47.js:1:2212784)
    at T.invoke (file:///snap/superproductivity/1545/resources/app.asar/dist/polyfills.94238d1595150347.js:1:6575)
    at Object.onInvoke (file:///snap/superproductivity/1545/resources/app.asar/dist/main.bb3078299280df47.js:1:3691849)
    at T.invoke (file:///snap/superproductivity/1545/resources/app.asar/dist/polyfills.94238d1595150347.js:1:6515)
    at I.run (file:///snap/superproductivity/1545/resources/app.asar/dist/polyfills.94238d1595150347.js:1:1971)
    at file:///snap/superproductivity/1545/resources/app.asar/dist/polyfills.94238d1595150347.js:1:16768
    at T.invokeTask (file:///snap/superproductivity/1545/resources/app.asar/dist/polyfills.94238d1595150347.js:1:7193)
    at Object.onInvokeTask (file:///snap/superproductivity/1545/resources/app.asar/dist/main.bb3078299280df47.js:1:3691664)
    at n.<anonymous> (file:///snap/superproductivity/1545/resources/app.asar/dist/main.bb3078299280df47.js:1:2215712)
    at Generator.next (<anonymous>)
    at h (file:///snap/superproductivity/1545/resources/app.asar/dist/main.bb3078299280df47.js:1:2212784)
    at T.invoke (file:///snap/superproductivity/1545/resources/app.asar/dist/polyfills.94238d1595150347.js:1:6575)
    at I.run (file:///snap/superproductivity/1545/resources/app.asar/dist/polyfills.94238d1595150347.js:1:1971)
    at file:///snap/superproductivity/1545/resources/app.asar/dist/polyfills.94238d1595150347.js:1:16768
    at T.invokeTask (file:///snap/superproductivity/1545/resources/app.asar/dist/polyfills.94238d1595150347.js:1:7193)
    at I.runTask (file:///snap/superproductivity/1545/resources/app.asar/dist/polyfills.94238d1595150347.js:1:2588)
    at L (file:///snap/superproductivity/1545/resources/app.asar/dist/polyfills.94238d1595150347.js:1:9191)
    at m.invokeTask [as invoke] (file:///snap/superproductivity/1545/resources/app.asar/dist/polyfills.94238d1595150347.js:1:8274)
i.onUnhandledError @ zone.js:1063
Z @ zone.js:1088
i.microtaskDrainDone @ zone.js:1082
L @ zone.js:589
invokeTask @ zone.js:491
S @ zone.js:1600
D @ zone.js:1626
action-logger.reducer.ts:11 [Layout] Hide SideBar Object

### Stacktrace
```
isHandledError (webpack:///src/app/core/error-handler/global-error-handler.class.ts:60:12)
h (webpack:///src/app/core/error-handler/global-error-handler.util.ts:227:37)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.mjs:25450:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:371:51)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:134:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1276:35)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:30)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.mjs:25437:32)
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1213:30)
makeResolver (webpack:///node_modules/zone.js/fesm2015/zone.js:1120:16)
h (webpack:///src/app/core/error-handler/global-error-handler.util.ts:227:37)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.mjs:25450:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:371:51)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:134:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1276:35)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:30)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.mjs:25437:32)
```

### Meta Info
META: SP7.9.2 Electron – de – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.9.2 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1641398840062: [Project] Load Project related Data Success 
1641398840063: [Improvement] Clear Hidden Improvements 
1641398840064: [Improvement] Delete multiple Improvements 
1641398841279: [WorkContext] Set Active Work Context 
1641398841299: [Task] SetSelectedTask 
1641398841417: [Bookmark] Load Bookmark State 
1641398841418: [Project] Load Project related Data Success 
1641398841419: [Improvement] Clear Hidden Improvements 
1641398841420: [Improvement] Delete multiple Improvements 
1641398843419: [WorkContext] Set Active Work Context 
1641398843436: [Task] SetSelectedTask 
1641398843483: [Bookmark] Load Bookmark State 
1641398843484: [Project] Load Project related Data Success 
1641398843485: [Improvement] Clear Hidden Improvements 
1641398843486: [Improvement] Delete multiple Improvements 
1641398844656: [WorkContext] Set Active Work Context 
1641398844683: [Task] SetSelectedTask 
1641398844736: [Bookmark] Load Bookmark State 
1641398844738: [Project] Load Project related Data Success 
1641398844739: [Improvement] Clear Hidden Improvements 
1641398844739: [Improvement] Delete multiple Improvements 
1641398847595: [Layout] Hide SideBar 
1641398864721: [SP_ALL] Load(import) all data 
1641398864736: [SP_ALL] All Data was loaded 
1641398864775: [WorkContext] Set Active Work Context 
1641398864821: [Task] SetSelectedTask 
1641398865364: [Bookmark] Load Bookmark State 
1641398865366: [Project] Load Project related Data Success 
1641398865368: [Improvement] Clear Hidden Improvements 
1641398865371: [Improvement] Delete multiple Improvements
```

**Comment by jeensg** [comment]
Ist this maybe a similar problem to #1775 / #

**Comment by johannesjo** [comment]
Thank you very much for opening this up! I try to have a look tomorrow.

**Comment by johannesjo** [comment]
Seems like a data migration has not been executed for the older projects for some reason.

It would be great if you could share a copy of your data to contact@super-productivity.com, so I can debug this on my computer and provide an automatic fix for this, if possible. You can create an export by navigating to "Settings" and then to "Import/Export" or you can use the "Export data" button from the error Dialog (there is also a button there which will anonymize the data before exporting).

**Comment by johannesjo** [comment]
Thank you very much! This should be fixed with the next release.
