### ISSUE TITLE
Translation information

### ISSUE THREAD

**Issue by milotype** [johannesjo/super-productivity#1812]
## Problem Statement
Currently, there is no information about localized/translated versions of the app on the website https://super-productivity.com/

## :grey_question: Possible Solution
Add a new section (`div`) in the website about localized/translated versions of the app. Something like:

`<h2>Use the app in your own language</h2><div>The app is translated into several languages already. You can help translating/improving translations at https://github.com/johannesjo/super-productivity/tree/master/src/assets/i18n</div>
`

Ideally include a non-english version of a screenshot for this new section (`div`).

**Comment by milotype** [comment]
IMO, it would be good, if there where some informations about translations. Either as suggested by me above, or in some other way.

**Comment by johannesjo** [comment]
Thanks for your suggestion! I would expect any serious app to have at least some internationalization. That's why it isn't mentioned anywhere. There is a section in the readme for contributing translations:
https://github.com/johannesjo/super-productivity#hearts-contributing

**Comment by milotype** [comment]
@johannesjo Yes, I've seen that information. IMO, it's something developers/programmers would notice. But this information is not directly noticable for (potential) users of the app. Standard application users need a direct information about translations of the app (or about the possibility to contribute translations). At the same time, you might get users to translate the app into their language …

BTW, did you ever consider to use a translation platform for translations? My favorite is [Weblate](https://weblate.org/), but there are other ones as well ... 

My problem is, that you make changes in the english `en.json` file without notice (at least I couldn't find them). Comparing the english and other language files is a very tedious process …

**Comment by milotype** [comment]
@johannesjo If you do decide to use a translation platform to translate the app, it would be great, if you'd also enable to translate the website content – ideally, the website would then automatically present the users' system or browsers language/locale, or you could implement a language menu on the website, so users can change the website's language into their own one.

I'm aware this is a lot of work and if you dont't like my ideas, that's OK by me ...
But if you do, that would be great!

Cheers,
Milo
