### ISSUE TITLE
Translation of Today

### ISSUE THREAD

**Issue by milotype** [johannesjo/super-productivity#1813]
### Your Environment

- Version used: 7.9.2
- Operating System and version: MacOS 10.11.6

### Expected Behavior
Title "Today" should translate into other languages

### Current Behavior
Title "Today" doens't translate into other languages

### Steps to Reproduce (for bugs)
Open the app. The title "Today" does not translate.

**Comment by johannesjo** [comment]
Thanks for opening this up! I agree! It's a bit tricky since, one can also edit the title of the today tag themselves, so maybe it makes sense to go for a placeholder default identifier and translate it as long its no other value.
