### ISSUE TITLE
I am receiving CORS errors when trying to use ICS in the web app

### ISSUE THREAD

**Issue by sql-sith** [johannesjo/super-productivity#1815]
### Your Environment

- Version used: web app
- Operating System and version: Ubuntu 20.04.3 LTS
- Desktop Environment: GNOME Shell 3.36.9
- Browser Name and version: Vivaldi 5.0.2497.32 64-bit Stable

### Expected Behavior

Configuring ICS for the Timeline works

### Current Behavior

Configuring ICS for the Timeline causes CORS-related errors

### Steps to Reproduce (for bugs)

1. Open Timeline settings in the web app.
2. Configure and ICS source. I have reproduced this using an Office 365 feed as well as one from Google Calendar.
3. Save the settings.
4. CORS-related errors will be seen in the developer console.

### Console Output

The console log file is attached.
[app.super-productivity.com-1641588283392.log](https://github.com/johannesjo/super-productivity/files/7831270/app.super-productivity.com-1641588283392.log)

**Comment by johannesjo** [comment]
That's expected for the web version (google controls which domains get access to the calendar). You need to use the desktop version to make it work.

**Comment by sql-sith** [comment]
I see. So I can make it work with a CORS extension or something like that. Sorry for the unneeded ticket but maybe somebody else will see this and it will save them some trouble. In case that happens, future person, you can do this. 

1. Go to the extension store for your browser
2. Find a well-reviewed extension that is supposed to add CORS headers for domains you specify, and install it
3. In the config for the extension, add the domain name of the ICS feed. For example, outlook.office365.com or calendar.google.com. Those are just examples - it should be whatever domain is in your ICS URL.

**Comment by johannesjo** [comment]
Thank you! Unblocking cors is a good idea. This definitely should  ideally be handled more gracefully within the app, but I am not sure if there is a generic way to do this.
