### ISSUE TITLE
Arm64?

### ISSUE THREAD

**Issue by rastacalavera** [johannesjo/super-productivity#1816]
I’ve played with this in the past and just saw the announcement you made on Reddit. Looking over the docker stuff it seems like it builds x86/amd64 only and no arm builds. Is that correct? If so, is an arm build maybe coming or would we have to make our own from the docker file?
Thanks for all you do!

**Comment by johannesjo** [comment]
Hi @rastacalavera ! Tbh the docker build hasn't been the main focus of attention so far, but I am a bit confused. What does the docker build have to do with the processor architecture? This should only come into play when building the desktop version. 

Apart from the mac m1 build there hasn't been any demand for an arm version of the app, but it should definitely be possible:
https://www.beekeeperstudio.io/blog/electron-apps-for-arm-and-raspberry-pi

**Comment by rastacalavera** [comment]
Hey thanks for the reply, this probably should be moved to the discussion section. I was thinking I could run the dev server on a pi4 and then use a desktop app or web client to connect to it. Maybe my understanding of that process is incomplete. When I ran the docker command this was the output
```
rastacalavera@pi4:~/SP/super-productivity$ docker run -d -p 8089:80 johannesjo/super-productivity:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
76e2d03d0a59660dbf3cf7205fa27eb1fff66eb9a1997e5579e166ff249e3fef
```

**Comment by 0xSh1v4** [comment]
I was also looking for ARM64 and then I found this arm64 supported image, https://hub.docker.com/r/haetsal90/super-productivity/tags and this one is working but has a version 7.5.x

**Comment by johannesjo** [comment]
Super Productivity works without a server database. Everything is stored on the client side, but can be synced via dropbox, google drive, webdav or simply to & from the file system. So running it from a rasberry pie might not make much sense (though of course putting some other sort of sync or private cloud server could work well).

**Comment by johannesjo** [comment]
> I was also looking for ARM64 and then I found this arm64 supported image, https://hub.docker.com/r/haetsal90/super-productivity/tags and this one is working but has a version 7.5.x and not the updated one. It would be great to have the arm64 build for every latest version also.

This doesn't come from me, so I am not sure if the source is trustworthy.

**Comment by rastacalavera** [comment]
> Super Productivity works without a server database. Everything is stored on the client side, but can be synced via dropbox, google drive, webdav or simply to & from the file system. 
Hmm. . So i guess my use case was that I wanted to use the app on my work computer where I can't install software. The webapp made sense for me but I wanted it hosted on my pi server rather than opening up [your hosted instance](https://app.super-productivity.com). I figured if I hosted my own, then i could use it remotely with my work computer and connect my linux clients as well but it sounds like it doesn't function how I imagined.

**Comment by 0xSh1v4** [comment]
> > I was also looking for ARM64 and then I found this arm64 supported image, https://hub.docker.com/r/haetsal90/super-productivity/tags and this one is working but has a version 7.5.x and not the updated one. It would be great to have the arm64 build for every latest version also.
> 
> This doesn't come from me, so I am not sure if the source is trustworthy.

Yeah makes sense. Does it also have a IOS app for iphone? I saw only Macos app. Would be nice to have ios app. so the sync would be more feasible.

**Comment by johannesjo** [comment]
> I figured if I hosted my own, then i could use it remotely with my work computer and connect my linux clients as well but it sounds like it doesn't function how I imagined.

You can still do all that, you just need to also handle data sync in some way. You can also use nextlcoud or something like that for example.

**Comment by johannesjo** [comment]
> Yeah makes sense. Does it also have a IOS app for iphone? I saw only Macos app. Would be nice to have ios app. so the sync would be more feasible.

There is no dedicated app for the IPhone but you can use the webapp there. If I am not mistaken you can also install it.

**Comment by dennysubke** [comment]
First, thank you for your work on Super Productivity—it's an excellent tool, and I truly appreciate your effort!

The Docker image still not support the arm64 architecture, which limits its use on devices like Raspberry Pi or ARM-based servers.

Would it be possible to provide an ARM-compatible version of the Docker image in the future? This would make the application more accessible to users running on ARM devices. If needed, I’d be happy to assist or test.

Thanks in advance for considering this!

**Comment by johannesjo** [comment]
Hey @dennysubke can you open up a new issue for this?

**Comment by dennysubke** [comment]
> Hey @dennysubke can you open up a new issue for this?

Hey Johannes,

Thank you for your quick response. I created the issue: https://github.com/johannesjo/super-productivity/issues/3694
