### ISSUE TITLE
Time logged against a GitLab task is not added to the task on GitLab itself

### ISSUE THREAD

**Issue by r0bbie** [johannesjo/super-productivity#1818]
Apologies I'm not sure if this is a potential bug (or I'm just doing something wrong!) or if it's a feature request, so please categorise accordingly 😅

I've recently discovered superProductivity and honestly I'm absolutely loving it and plan to use it as part of my workflow immediately. As a team we use a self-hosted GitLab installation for task/issue management, and superProductivity's GitLab installation seems really tight and is a big pro for sure.

The issue I'm having is that when I log time against a GitLab task in superProductivity, it does show the time logged above the GitLab summary in superProductivity, but it doesn't seem to be reporting it to GitLab itself. Is this a bug / issue with my setup, or is time tracking integration with GitLab just not implemented yet?

If this isn't yet implemented, this would be a really amazing feature for us to have. We log time against tasks on GitLab so the downside would be that I'd have to log the time twice if I'm using superProductivity for time tracking, either manually entering the time into GitLab web interface when a task is complete and time logged in superProductivity (copying/pasting across etc), or run two time tracking software simultaneously. At present we use [https://github.com/kriskbx/gitlab-time-tracker-taskbar](https://github.com/kriskbx/gitlab-time-tracker-taskbar) to track time on desktop, which does automatically report to Gitlab, but that's now unmaintained and also is _only_ for time tracking and not task management / personal to do list, so if superProductivity had this integration it would allow me to replace both gitlab-time-tracker-taskbar app and my to-do app with one app, which looks like it does a load of other stuff way better!

(and again if I am just doing something stupid here / missing how to get this working, apologies!)

**Comment by johannesjo** [comment]
Hi there! Thanks for opening this up! I also would like to see this, though I probably won't find the time to work on this myself (soo much other stuff to do...). The Jira and OpenProject provide an dialog that is used to submit the time to GitLab. The model is likely exactly the same and because Super Productivity's side of things is private and GitLab is public/shared with others, I think it makes sense to let the user decide, what exactly should be logged.

**Comment by r0bbie** [comment]
Great thanks! Can definitely see the logic in having it as an optional feature if people do want to submit their time to GitLab. I'll take a look at how this is implemented already for Jira and OpenProject then - theoretical if the flow is already there for those integrations, I assume this might not be too much work to implement..? (I may try and take a look at this soon if so!)

One other note on this - as you can also setup time estimates for tasks in GitLab, it would be great if those were also mirrored to / in sync with the estimates against tasks in superProductivity. Is that behaviour implemented already for Jira / OpenProject?

**Comment by johannesjo** [comment]
That's great to hear! Please, let me know if you have any questions!

> One other note on this - as you can also setup time estimates for tasks in GitLab, it would be great if those were also mirrored to / in sync with the estimates against tasks in superProductivity. Is that behaviour implemented already for Jira / OpenProject?

No this is not implemented, though I am open to offer an optional hook for this as well. I think the subject never came up, since in many software projects this happens in the sprint planning or similar.

**Comment by tunguskar** [comment]
I think this is the same I need. I want to send my /spend time to our gitlab instance when finished working on a task/ticket. As far as I can see. 

this one was the initial question from me. 

https://github.com/johannesjo/super-productivity/discussions/2342
