### ISSUE TITLE
Collpasing & Expanding Subtasks list

### ISSUE THREAD

**Issue by daya** [johannesjo/super-productivity#182]
Enhancement Request: It would be great to collapse and expand the sub task list specially when creating a TODO or planning your day

**Comment by johannesjo** [comment]
You mean like a button or something instead of the entry from the context menu (when clicking the three dots)?

**Comment by daya** [comment]
It could be either a button or an entry in context menu, ideally with a shortcut like Alt + "+" to expand and Alt + "-" to collapse.

**Comment by johannesjo** [comment]
Just to make sure that I understand you correctly. The existing functionality 

* the "Add sub task" button from the context menu/ 
* the keyboard shortcut for "add sub task" ("a" per default)
* +/- button on the left of the list, if there are sub tasks * using arrow left to collapse and arrow right to expand an existing list of sub tasks

Is not what you're looking for?

**Comment by daya** [comment]
@johannesjo yes you are right. The first 2 items already exist and next 2 items are needed.

**Comment by johannesjo** [comment]
The latter two also exist :)

**Comment by daya** [comment]
Indeed they do now that I see it, thanks.
