### ISSUE TITLE
Better contrast for modal dialog texts

### ISSUE THREAD

**Issue by danbst** [johannesjo/super-productivity#1820]
## Problem Statement

I have changed theme color for my project to shade of green. However this also changed text colors in modal dialogs (Time, Note Save, Add attachment, etc). Now these buttons are very hard to read (I'm using dark theme, but I guess it may happen on any theme).
![image](https://user-images.githubusercontent.com/743057/148661695-eef6c38d-3780-4f5f-95dc-0c6e6e296c15.png)

## :grey_question: Possible Solution

Perhaps Superproductivity should set background color for modal dialog based on contrast (https://github.com/bgrins/TinyColor#mostreadable, https://github.com/bgrins/TinyColor#color-modification)

## :arrow_heading_up: Describe alternatives you've considered

Alternative is not choose dark colors, only choose light colors. Maybe also restrict color palette in color picker dialog. But It seems that modal dialogs are the only problematic places.

Another alternative is not to apply theme to modal dialog texts.

**Comment by johannesjo** [comment]
Hey there! Thanks for opening this up. Unfortunately adjusting the dialog color is not a good solution as it might mess up the hierarchy of elements (things farther in front are more bright for the dark theme). There are several colors that might not work well, but I think it is ok to leave this to the user, as finding a smart way to restrict this is far from trivial.

**Comment by danbst** [comment]
Okay then. I'll choose theme colors more carefully then.
