### ISSUE TITLE
Cross-layout (keycode) hotkeys?

### ISSUE THREAD

**Issue by danbst** [johannesjo/super-productivity#1821]
## Problem Statement

I use Linux. I have two keyboard layouts: `en` and `uk`. I like the `a` and `Shift-A` hotkeys, however they are available only when I'm on `en` keyboard layout. When switching to `uk` they stop working, because now they are `ф` and `Ф` symbols.
## :grey_question: Possible Solution

Would be great to support hotkeys on KeyCode, not keysym. Or support two keysyms for each action

## :arrow_heading_up: Describe alternatives you've considered

Alternative is to use keysyms which are same on both layouts, like, numbers or F-keys. This is less ergonomic though

**Comment by johannesjo** [comment]
Thanks for opening this up! PRs dealing with this, would be very welcome!
