### ISSUE TITLE
adding notes to projects

### ISSUE THREAD

**Issue by abhyudaya63** [johannesjo/super-productivity#1823]
Some tasks require to be tracked daily but the usual solutions like Kanban board dont work because it is mostly text with not many things working in parallel. so instead of using note-taking service, I could just add text fields with tasks in the project. not text explaining task but along with it.

**Comment by abhyudaya63** [comment]
I didnt write this clearly. What I meant was building a project where you could just have a series of text fields. like a daily diary but for tracking any task you want. 
for ex: you want to experiment with taking 3 cups of coffee a day for 30 days and see how it affects your productivity. instead of using a note-taking app, wish I could do this inside SuperProductivity. The app could prompt me to fill the text field at any defined time. And after 30 days, I could review the data.

This is probably far from the intended purpose of the application. but what do you think?

**Comment by johannesjo** [comment]
Thanks for the suggestion! I generally like the idea. How about using repeated task for this?

**Comment by abhyudaya63** [comment]
cam you review the past text entries of the task?

**Comment by johannesjo** [comment]
@abhyudaya63 in theory yes, but it's not very comfortable to do this currently (I think there is already an open issue somewhere to improve this).

**Comment by abhyudaya63** [comment]
okay. it would do probably.
thank you! :smile:
