### ISSUE TITLE
Minimum width of webapp locks at 500px

### ISSUE THREAD

**Issue by Mindstormer619** [johannesjo/super-productivity#1824]
This is a minor issue, however it does cause me some considerable pain. On previous versions of the webapp, I could reduce the width of the window to a rather reasonable 420px, since I have the majority of my screen taken up by code/documentation in IDE windows etc. For some reason on the latest version it locks the minimum width to 500px, which is messing with my current window layout. Was this change intentional? I don't see any specific UI element taking up the extra room.

### Your Environment

- Version used: 7.9.2
- Operating System and version: Windows 10
- Desktop Environment: 
- Browser Name and version: Chrome 97.0

### Expected Behavior

Window width should be resizable to below 500px.

### Current Behavior

Window is unable to be resized to below 500px.

### Steps to Reproduce (for bugs)

1. Open webapp in a new Chrome window
2. Drag resize handle to reduce window width

**Comment by johannesjo** [comment]
Hey there! There is no limit the app specifies itself and I am also unable to reproduce this. Might be rather something with your chrome maybe?

**Comment by Mindstormer619** [comment]
To add a bit more detail -- I use Chrome's feature to install the webpage as an app locally in order to use it. The instance for which I reported the issue is my Chrome-based webapp version I use at work; I tried opening the same way on my local Edge browser in my home machine and I can see the exact same issue.

![image](https://user-images.githubusercontent.com/441849/148761834-df47368d-b1ba-43a9-9e31-4328886236cf.png)

The odd thing is that if I open it in Edge *directly* (as a regular browser tab) then it lets me go to a minimum of 480px width instead of 500.

**Comment by johannesjo** [comment]
@Mindstormer619 this is the browser behavior. Check any other webapp (e.g. https://github.com/hemanth/awesome-pwa) and the behavior will be the same.

**Comment by Mindstormer619** [comment]
Ah I see, thanks for looking into this Johannes! I think it was a Chrome update at my organization that caused this issue in that case (likely it was already in the stable channel for a while, and the org-wide update to Chrome happened later, which would explain why stable Edge already has the same issue). I can confirm on a couple of other webapps that the same issue is present, so it does seem to be something browser-side. I have no idea why Chrome/Chromium would limit PWAs to 500px min-width in an update, but that's what seems to have happened.

**Comment by johannesjo** [comment]
Yes, I agree. This is a bit weird indeed.
