### ISSUE TITLE
Ability to move a task to another project

### ISSUE THREAD

**Issue by daya** [johannesjo/super-productivity#184]
The potential of this app is huge. 

It just occurred to me that **_I can track everything_** that I do **_if I can capture the time spent_** in a new project (coz you know life happens). So when the app prompts "You have been idle" a feature allowing you to capture the time spent in a new project. Currently I cannot create a new project and if I do temporarily capture that time spent in a placeholder task in some project then there is no way to move that task to another project.

I can understand implementing such a functionality will break JIRA/Github integration, but its easy to disallow moving the task if its belongs to JIRA/Github.

**Comment by KonTy** [comment]
So basically you want an ability to move a task to a different Project?

**Comment by johannesjo** [comment]
Or would it be enough to allow tracking idle time to a (new or old) task on existing project?

**Comment by daya** [comment]
@KonTy yes that would be an effective solution.

@johannesjo no this won't work as it is limited to existing projects.

Now imagine there is a functionality which gives you a Time Spent report a Global Metrics (over a configurable time period) across all projects, that would be super amazing.

**Comment by johannesjo** [comment]
Space in the task context menu is a bit precious and I don't want to put too much functionality inside it. Any ideas for an alternative way to make this feature accessible?

**Comment by KonTy** [comment]
> Now imagine there is a functionality which gives you a Time Spent report a Global Metrics (over a configurable time period) across all projects, that would be super amazing.

Oh yeah showing graphs on tasks completed, procrastination rate, "out of box" tasks etc. I was holding those suggestions back, coz I know @johannesjo is very busy as it is, and it sounds like for cross project features the app will have to be re-architected. 

@johannesjo you know what might help is a simple setup guide where you could explain how to setup a dev environment step by step A-Z including debugging. For me the biggest obstacle into how to start contributing was I think the question of how to setup a dev environment. I'm sure I can figure it out but it will take time which I don't have but if you had step by step, I would just follow it without thinking and then start looking/debugging code when I get a minute here and there.

Also have you considered using VS Code as a main development IDE for this project?

**Comment by johannesjo** [comment]
> Now imagine there is a functionality which gives you a Time Spent report a Global Metrics (over a configurable time period) across all projects, that would be super amazing.
Maybe this is something for a  new feature request :) This should be doable i think, because the data would only be needed to be read, which is a lot less complicated.

@KonTy The Development setup is described in the readme, and pretty easy:
```
git clone https://github.com/johannesjo/sp2.git
cd super-productivity
yarn # or npm install
ng serve
```

But you're right, I should expand on that.

I think the IDE you use shouldn't matter much or are you missing anything specific?

**Comment by KonTy** [comment]
Yeah I saw those instructions but it is not enough for brainless installation where you just follow step by step. So yes expanding a little bit would help. Also how to debug things would help as well.

> I think the IDE you use shouldn't matter much or are you missing anything specific?
Let me think about this. I think IDE matters when you start talking about debugging and ease of adding code. Think about it this way, if we want to project to grow and want more people to contribute the developer environment setup instructions should be perfect. That way you team people to fish, spending  a little time upfront. Consider the fact that some people might know JS NodeJS or even TS but don't know how to setup/use Electron etc. Maybe I should spend an hour or two and document the whole setup process. 

Check this out I've always thought that TrinityCore guys have done the best job of documenting a setup process (I haven't see anyone do it better) not only they documented setup process thoroughly but they did it for each platform as well https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130076/Core+Installation

**Comment by daya** [comment]
> So basically you want an ability to move a task to a different Project?

@johannesjo yes, and the move of a task to another project should carry its time stats along. One other use case you can think about is re-categorization or converting a parent-task to a sub task or vice versa. When parent task is converted to a sub-task it will still carry its time stats along. This use case will be super helpful for re-categorization of a task into something more abstract.

**Comment by xantof** [comment]
Just discovered this app and this was the first thing I tried to do!
So +1 for this feature

Appreciative of your work!

**Comment by johannesjo** [comment]
Would it work for you, if there was a button to switch the project from the Dialog?

**Comment by daya** [comment]
@johannesjo Yes that would work too. Though in a bigger context the ability to move any task (except ones created in JIRA etc) to another project would be good to have even when not prompted by "You have been Idle" dialog i.e. on every task the right click menu should have that option.

**Comment by johannesjo** [comment]
The feature is available now in the master branch and should be downloadable with the next release. Please let me know if it works out for you.

**Comment by clarkdowding** [comment]
I'm doing a "trial migration" from Things 3 because I've finally fully adopted Linux as my full-time OS and need a Task Manager that I can run under Linux. 

So far I like what I'm seeing with Super Productivity. Thanks for the hard work on this great looking app.

I'm creating my *Projects* and realized I when I drag previously created tasks over to the list of projects and release the task on the project, it does not add to the *Project*. 

I think I'm missing something. This feature is in the production version, right?

**Comment by johannesjo** [comment]
@clarkdowding there is an open issue for this:
https://github.com/johannesjo/super-productivity/issues/810
