### ISSUE TITLE
Add the ability to pause and toggle time tracking for specific activity! (and not just to resume/pause the current task).

### ISSUE THREAD

**Issue by ahmedfarrag17** [johannesjo/super-productivity#1844]
I am using Macro Keyboards. And I think it would be so nice to **assign** a Keyboard Shortcut to start time tracking for a **Specific** task/activity (for ex. Office Work). And if I press the shortcut to start tracking a new task while the timer is going on (for a different task), then the timer automatically pauses in the current task and it resumes for the new chosen one (through its related keyboard shortcut).

This will save some time and prevent opening the Super Productivity Window. Just remember the shortcuts (or assign them to a single Macro Key) and it is done. (Every time I would sit down on my desktop and start working on PC, I press a key and it starts tracking! I want to do a different task, I press on its key and it starts counting for that task and pauses the first one). 

Of course, it would be nice to be notified not just with Sound feedback but with a pop-up notification from the side taskbar (on Windows).

Please consider it!!

Thank you!

**Comment by johannesjo** [comment]
Hey @ahmedfarrag17 ! Thanks for opening this up!
