### ISSUE TITLE
Sync File on Mobile

### ISSUE THREAD

**Issue by sylos** [johannesjo/super-productivity#1847]
## Problem Statement

I do not want to use dropbox or webdav to sync but I want to sync with my desktop app. I have and use syncthing for other apps on my phone for synchronization
## :grey_question: Possible Solution

Solution: Create a local file that will be tracked by syncthing to allow for synchronization across multiple platforms

**Comment by johannesjo** [comment]
Hey there! Thanks for opening this up! Yes, it would be great having this feature! Help would be much appreciated! #690

**Comment by diogomsfranco** [comment]
This would be a great feature! Its how I've been synchronizing my notes from obsidian between the desktop and mobile.

**Comment by ashutoshsaboo** [comment]
Still relevant

**Comment by diogomsfranco** [comment]
Still relevant

**Comment by fedehub** [comment]
Still relevant

**Comment by CavaleriOmar** [comment]
Still relevant!!!

**Comment by sunsoy** [comment]
Still relevant

**Comment by sunsoy** [comment]
#33

**Comment by sunsoy** [comment]
looks like solution is on the way early Feb

https://github.com/johannesjo/super-productivity-android/pull/33

**Comment by fraschm1998** [comment]
Still relevant

**Comment by ashutoshsaboo** [comment]
Still relevant

**Comment by CavaleriOmar** [comment]
> This issue has not received any updates in 90 days. Please comment, if this still relevant!

Still relevant
