### ISSUE TITLE
Older data not importing back into super-productivity

### ISSUE THREAD

**Issue by santiyounger** [johannesjo/super-productivity#1848]
Hey, I have some old data from a year ago in a .sjon file generated in dropbox by super-productivity

I tried to go to the web-app to import this .json file and I was shown this error:

Please let me know if there's anything I can do to access my data

Error: Uncaught (in promise): TypeError: Cannot convert undefined or null to objectTypeError: Cannot convert undefined or null to object    at Function.keys ()    at Qte (https://app.super-productivity.com/main.238c00783beb7ce6.js:1:960706)    at https://app.super-productivity.com/main.238c00783beb7ce6.js:1:960949    at Array.forEach ()    at https://app.super-productivity.com/main.238c00783beb7ce6.js:1:960932    at https://app.super-productivity.com/main.238c00783beb7ce6.js:1:960964    at n.repairData (https://app.super-productivity.com/main.238c00783beb7ce6.js:1:967464)    at n. (https://app.super-productivity.com/main.238c00783beb7ce6.js:1:1206130)    at Generator.next ()    at h (https://app.super-productivity.com/main.238c00783beb7ce6.js:1:1203562)

### Stacktrace
```
_resetEntityIdsFromObjects (webpack:///src/app/core/data-repair/data-repair.util.ts:229:16)
_fixEntityStates (webpack:///src/app/core/data-repair/data-repair.util.ts:44:16)
_fixEntityStates (webpack:///src/app/core/data-repair/data-repair.util.ts:43:20)
isDataRepairPossible (webpack:///src/app/core/data-repair/data-repair.util.ts:21:29)
constructor (webpack:///src/app/core/data-repair/data-repair.service.ts:16:22)
this._dataRepairService.isRepairPossibleAndConfirmed (webpack:///src/app/imex/sync/data-import.service.ts:117:48)
h (webpack:///src/app/features/reminder/reminder.service.ts:23:)
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1213:30)
makeResolver (webpack:///node_modules/zone.js/fesm2015/zone.js:1120:16)
recurse (webpack:///src/app/imex/file-imex/privacy-export.ts:56:24)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.mjs:25450:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:371:51)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:134:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1276:35)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:30)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.mjs:25437:32)
```

### Meta Info
META: SP7.9.2 Browser – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36

### Actions Before Error
```
1642456422738: [SP_ALL] Load(import) all data 
1642456422739: [SP_ALL] All Data was loaded 
1642456425490: [Layout] Toggle SideBar 
1642456512676: [Persistence] Save to DB (14) 
1642456512689: [SP_ALL] Load(import) all data 
1642456512696: [Persistence] Remove from DB 
1642456522438: [SP_ALL] Load(import) all data 
1642456522438: [SP_ALL] All Data was loaded 
1642456523754: [Layout] Toggle SideBar 
1642456533925: [Persistence] Save to DB
```

**Comment by johannesjo** [comment]
Hey there! Could you maybe send me a copy of that data to contact@super-productivity.com ?
