### ISSUE TITLE
How do you complete yesterday's tasks?

### ISSUE THREAD

**Issue by KonTy** [johannesjo/super-productivity#185]
I find myself forgetting to Finish my day quite often if could be because my last hour was a meeting or I got distracted but someone coming into my office and whatever. So basically I leave without "Finishing my day". What is the workflow I can use to "Finish" yesterdays' day when I get in the next day in the morning? Is it possible?

**Comment by johannesjo** [comment]
Thanks for the suggestion! Currently there is no workflow for this unfortunately, but I like the idea a lot, because this happens to me too quite often :) I will definitely work on this.

**Comment by KonTy** [comment]
This case I suggest being able to chose tasks with a checkbox and select a day that you want to finish. Because sometimes you can back from a weekend and it is not yesterday, it is 2 days ago :)

**Comment by johannesjo** [comment]
This would be also an approach. I thought more along the lines of opening the daily summary view again allowing you to make a ll the changes which are then tracked for the last active day.  To mark tasks as completed we could use the very right column of the "today" tab. The date of completion shouldn't matter too much anyway, as it ain't used for anything atm.

What do you think about it?

**Comment by KonTy** [comment]
That would work and if it is easier to implement then sure. I think "date completed" will matter more once we can get to report side of things. Looking at statistics is cool to see when I said I will complete a task vs when I actually completed. There are many cool graphs we can do with this.

**Comment by johannesjo** [comment]
I also wrote down some notes on this. Not really final yet:

### What to display:
* Daily Planner but without "Wait I forgot something" and "Take a moment to celebrate". 
* Instead we display "You forgot to finish your day X Days ago  or yesterday + Date
* Button will not be "Save and go home" but "Finish Day"
* Add a second button with "I don't acare"
* The week tab should probably be hidden

### When to display ??
Not really clear yet what sould trigger this...
* Should occur on project load, when ???

### Possiible indications for incomplete day:
* unarchived tasks that are done on another day than today
* we possibly need a completed model for tasks
* 

### Other
* A separate page will be needed very similar to the daily planner
* Make a new component for header and tabs and add flags for `isForToday` and `date`
* All components (evaluation sheet, today list, google sheet, etc) will need to be adjusted to allow for saving data for other days
* "Today" Tab needs to be renamed to "Tasks for Day"

**Comment by KonTy** [comment]
You know what  I just of man? I think it would be really beneficial for you to create a series of tutorials on how you intended to use the app. All of us have a lot of ideas but maybe we are missing the workflow that you have intended. For me the biggest categories are
1. In the morning when you come in how do you plan your day?
     For example I look at all tasks with due date for today. Some I push to tomorrow. some I push to next week. Some I add to My Day view. During planning it is important for me to be able to look at all the tasks across the Projects By Due date and by #hashtags. For example in Todoist #hashtags show up as "projects: in the project list. That way I could add hashtags list #waitingfor #next etc. If I send an email with a question to a team member I add a task and #waitingfor it. That way tomorrow morning during day planning I will see it and will make sure to ping that person. 
PS I think at some point the projects in your app will have to take a more center stage then they are right now. and be list in Todoist and MSTodo for example like here as a TreeView 
**https://get.todoist.help/hc/article_attachments/360000744525/Todoist_Productivity_View.png**

2. When my day is progressing I would like to be able to timebox tasks and get a desktop wide notification when I go over that time. Also ability to quickly push a task to tomorrow so that it will show up during planning tomorrow. 
3. In the evening it would be nice to have some stats but this is not important right now.

So that's sort of my routine in a nutshell I would like to know what is yours and it would be nice to see a tutorial. :)

**Comment by johannesjo** [comment]
Good idea. Thought about it before and might do it some time in the form of a video maybe. But atm there is so much other stuff to do. :)

**Comment by KonTy** [comment]
> Good idea. Thought about it before and might do it some time in the form of a video maybe. But atm there is so much other stuff to do. :)

Yeah true dat.

**Comment by johannesjo** [comment]
The feature is basically done. To activate it you need to work on a project (e.g. track time) and then close the app without clicking "Save and go home".

Let me know what you think :)
