### ISSUE TITLE
Allow to request JIRA when adding task from today's view

### ISSUE THREAD

**Issue by surli** [johannesjo/super-productivity#1850]
## Problem Statement

I'm often adding task from today's view, however I cannot add task synchronized with JIRA from there, I always need to go back to the project synchronized with JIRA and creates the task here.

## :grey_question: Possible Solution

Ideally I want JIRA to be requested when created the task from today's view. In my case it's easy because I only have a single project synchronized with a single JIRA. In case of multiple projects, I guess all the JIRAs should be requested and the UI should be probably be splitted to identify from which JIRA the proposed synchronized issue comes from, with a limitation. 

Maybe there's also a setting to add for today's view to select the actual JIRA we want to check from this view when adding issues. I'm perfectly fine if this feature is not available by default and needs to be enabled. 

## :arrow_heading_up: Describe alternatives you've considered

So right now I always switch back to the project view to create my task and then go back to the today's view.

![image](https://user-images.githubusercontent.com/1478232/150114971-1bfca268-fd27-46ae-a85f-a6208c4dbdb9.png)
![image](https://user-images.githubusercontent.com/1478232/150114989-feb9d85c-162c-406a-a1c2-cf75f05ea5e5.png)

**Comment by johannesjo** [comment]
Hi there! Thanks for opening this up! This use case is definitely something I'd like to see improved as well, but I am not yet sure in what way would be best to solve it.

**Comment by surli** [comment]
Note that I forgot to mention that I have a settings to use my only project as the default project when creating new task. Could be part of a solution to use that default project JIRA by default when this setting is enabled. To be used along with a solution to allow switching project when adding new task more easily.
