### ISSUE TITLE
Can not add a Recurrent Task to a project

### ISSUE THREAD

**Issue by nkrot** [johannesjo/super-productivity#1851]
I have noticed a difference in behaviour of normal tasks and recurrent tasks (those that are configured via Repeat): normal tasks can be added to a project (right click, choose "Add to project", choose project), meanwhile, recurrent tasks do not have such an option in the context menu. If this is intentional, what is the reasoning behind the decision?

It happened to me that I created a few recurrent tasks outside of any project and now would like to fix it. Of course, I can destroy the tasks and recreate them. But..

### Your Environment

-  Version used: 7.9.1 (deb)
-  Operating System and version: Ubuntu 18.04
-  Desktop Environment: MATE
-  Browser Name and version: Firefox 89.0

### Expected Behavior

I would like to be able to move a recurrent task to a project, using the same approach that works for normal tasks: right click, choose "add to project", ...

Thanks!

**Comment by johannesjo** [comment]
Hey there! Thanks for opening this up! Makes total sense to add something like this. PRs would be welcome!
