### ISSUE TITLE
Automatically switch "additional info" pane to clicked task

### ISSUE THREAD

**Issue by raphaelquast** [johannesjo/super-productivity#1852]
## Problem Statement

In general, I have the "additional info" pane open most of the time to quickly add reminders, descriptions etc.

An annoying thing however is that if I click on another task, the pane does not follow the highlighted task but it remains focused on the task where the `"show/hide additional info"` button was clicked (I'm at v7.9.2).

I know it's possible to switch the focus of the pane by clicking on the corresponding `"show/hide additional info"` button,
but I think it would be a lot better if the pane would automatically switch as soon one clicks on another task.

(also the location and symbol of the button that needs to be clicked is different if a "description" or "reminder" has been set or not)

Thanks!

## :grey_question: Possible Solution

I guess the description explains it well enough

**Comment by johannesjo** [comment]
Hi there! Thanks for opening this up. Did you know that you can use the right arrow key to open the side panel for the currently focused task?

Apart from that, I am open to implement this as optional behavior (opt in via setting).

**Comment by raphaelquast** [comment]
hey! thanks for mentioning this! I wasn't aware ... this makes navigating already a lot more convenient 😄  
(but I still think that my request would be nice to have)

**Comment by johannesjo** [comment]
I recently wrote an article about the shortcuts. Maybe you find more of use there :)

https://dev.to/johannesjo/getting-started-with-super-productivity-2791

**Comment by raphaelquast** [comment]
Hey, thanks! yep that was helpful...
how about adding this info to the README (it's where I would hope to find such info) 

... Here's what I mean:  #1855   
(it utilizes a collapsible section to avoid using up too much space)
