### ISSUE TITLE
Make the input-field for the default task-description multiline

### ISSUE THREAD

**Issue by raphaelquast** [johannesjo/super-productivity#1853]
## Problem Statement

Currently the size of the input-field for setting the default task-description is only 1 line... any chance of making this multiline?

(`settings` -> `misc settings` -> `Task description template`) 

... and another general comment... using a default task-description such as
 🔴 🔵 🟠 🟡 🟢 🟣 🟤  
helps a lot with creating nicely formatted descriptions...

**Comment by johannesjo** [comment]
Thanks for bringing this to my attention! Should be fixed with the next release!
