### ISSUE TITLE
Nothing happens when hovering a task on desktop apps in Windows 10

### ISSUE THREAD

**Issue by Ra0EL** [johannesjo/super-productivity#1857]
### Your Environment

- Version used: Desktop 7.9.2
- Operating System and version: Windows 10 20H2 19042.1237
- Hardware: Lenovo Thinkpad X1 Yoga Gen1 (touchscreen)

### Expected Behavior

Hovering a task should produce something (e.g. show 3 action buttons), according to video tutorial.

### Current Behavior

Nothing happens ; there is no way to:
- change focus on tasks in list
- know which task has current focus
- mark a task as completed
- use most of keyboard shortcuts

### Error Log (Desktop only)

Nothing relevant in logs.

### What I tried

I read [#1829](https://github.com/johannesjo/super-productivity/issues/1829), but issue persists even when touchscreen is disabled.
So, this workaround does not help, unfortunately.

Because of this, **Super-Productivity is hardly usable**.
Which is really a pity, knowing that I have tried soooo many other solutions for years, and yours seems to eventually answer all my needs and expectations.

What can you suggest ? Should I try a previous release ?
Long life !

**Comment by johannesjo** [comment]
Hey there! Could you please try the just released version v7.10.0?

**Comment by Ra0EL** [comment]
And… **FIXED !!!** :+1: thanks to v7.10.0.

Very reactive answer and issue definitely addressed. 
Many thanks and long life !
