### ISSUE TITLE
Schedule Overview

### ISSUE THREAD

**Issue by daya** [johannesjo/super-productivity#186]
short of duplicating the tasks in Calendar (for which integration is not available), How do I list all scheduled tasks along with dates and times across all projects? This list overview will give me an idea on how to plan my tomorrow or next week.

**Comment by KonTy** [comment]
Yes I don't believe this feature exists and there are a lot of suggestions like this one. Planning the day is not the strongest point of this app at the moment. Not only due dates but also people suggested #hashtag support for things like #waitingfor #next #tomorrow etc. We need ability to plan a day more effectively for sure.

**Comment by johannesjo** [comment]
Good suggestion. Makes a lot of sense to me.

**Comment by johannesjo** [comment]
The feature is developed and will be there with the next release. Beta Testing would be appreciated :)
