### ISSUE TITLE
Start minimized to tray

### ISSUE THREAD

**Issue by francois072** [johannesjo/super-productivity#1865]
## Problem Statement
When auto launching at login the app opens a window instead of minimizing to system tray.

## :grey_question: Possible Solution
Add a flag "--tray" to start the app in the system tray.

**Comment by johannesjo** [comment]
Thanks for opening this up! PRs are welcome!

**Comment by mizzunet** [comment]
[Ferdi](https://github.com/getferdi/ferdi) has similar feature and it's also Electron 

![image](https://user-images.githubusercontent.com/10193999/152628692-ab318587-1ec3-4bae-b896-e1f53ca359eb.png)

If someone managed to get it from there and added here. I'm not familiar with coding, I'll try to find the code lines for it

**Comment by francois072** [comment]
Yes, this is still relevant bot

**Comment by francois072** [comment]
Still relevant

**Comment by KAGEYAM4** [comment]
Anyplan of this getting implemented?
