### ISSUE TITLE
Error Integrating to JIRA

### ISSUE THREAD

**Issue by zynth17** [johannesjo/super-productivity#1870]
- Version used: 7.10
- Operating System and version: Windows 10 Version 10.0.19044 Build 19044
- Browser Name and version: Brave

### Expected Behavior

Can connect to JIRA

### Current Behavior

Got an error Jira: unexpected token < in JSON at position 9

### Steps to Reproduce (for bugs)

1. Create new task
2. set up integration to JIRA
3. Test credentials
4. see the error

### Error Log (Desktop only)
[Error Log](https://github.com/johannesjo/super-productivity/files/7932029/-1643100905020.log)

**Comment by zynth17** [comment]
just found someone posted the same issues #1869

**Comment by johannesjo** [comment]
Thanks for opening this up (this is the better place for the issue). 

Could you by any chance also provide the response from the request to jira. You can get it with the help of the network tab. You can access it by pressing ctrl+shift+i and then clicking network. There you have to search the jira request, in which context the error is thrown.

**Comment by vineet-suri** [comment]
Hey @johannesjo 
find the JIRA error from console -
![download](https://user-images.githubusercontent.com/49708329/150968737-af91c208-5345-41de-9d03-88b9e2509504.png)

**Comment by johannesjo** [comment]
@vineet-suri thanks, but that is not quite what I need. I am trying to find out what JSON is actually parsed. Maybe it ain't json at all, which would indicate some sort of configuration error (or your jira installation simply not allowing api access, which is rare but possible afaik).

**Comment by zynth17** [comment]
> @vineet-suri thanks, but that is not quite what I need. I am trying to find out what JSON is actually parsed. Maybe it ain't json at all, which would indicate some sort of configuration error (or your jira installation simply not allowing api access, which is rare but possible afaik).
> 
> Here is some more info on how to do it: https://developer.chrome.com/docs/devtools/network/

Hi, it does not have JIRA request at all. i think it doesnt even do the request to JIRA api at this point.

**Comment by zynth17** [comment]
i just notice, this happen because i enabled the option ```use personal token instead of password``` but i do use password. if i uncheck the option the error change to ```Blocked Jira Access to prevent being shut out```

**Comment by johannesjo** [comment]
@zynth17 yes, you're right of course (sorry got confused). I added some additional logging information (available in the master branch and with the next release). Would be great if you could try again and send me the additional info once it is out!

**Comment by johannesjo** [comment]
Could you expand the part inside response or somehow copy it and paste it here? There likely will be some error message inside of it.

**Comment by zynth17** [comment]
> Could you expand the part inside response or somehow copy it and paste it here? There likely will be some error message inside of it.

here, since the message is very long, it cannot be paste in here, so i send it in a txt file.
[error.txt](https://github.com/johannesjo/super-productivity/files/8007961/error.txt)

**Comment by johannesjo** [comment]
Thanks @zynth17 ! What's inside the txt is basically just a webpage, so I would conclude that the URL is somehow not properly set?

**Comment by zynth17** [comment]
> Thanks @zynth17 ! What's inside the txt is basically just a webpage, so I would conclude that the URL is somehow not properly set?

what is the proper url to set? i set it already but that's the response

**Comment by johannesjo** [comment]
@zynth17 that depends on your installation.
