### ISSUE TITLE
A JavaScript error occurred in the main process - Uncaught Exception Error: Failed to load image from path

### ISSUE THREAD

**Issue by nathanstaton** [johannesjo/super-productivity#1874]
### Your Environment

- Version used: 7.9.2
- Operating System and version: macOS Monterey 12.1 
- Browser Name and version: N/A

### Expected Behavior

Error should not appear after starting and stoping a task. 

### Current Behavior

When I start or stop a task I get this error message. 

A JavaScript error occurred in the main process

Uncaught Exception Error: Failed to load image from path ‘/Applications/Super Productivity.app/Contents/Resources/app.asar/electron/assets/icons/indicator/running-I.png’ at Object.setImage (<anonymous>) at setTrayIcon (/Applications/Super Productivity.app/Contents/Resources/app.asar/electron/indicator.js:133:12) at IpcMainImpl.<anonymous> (/Applications/Super Productivity.app/Contents/Resources/app.asar/electron/indicator.js:50:13) at IpcMainImpl.emit (event.js:388:22) at Object.<anonymous> (electron/js2c/browser_init.js:161:9959) at Object.emit (events.js:376:20)

### Steps to Reproduce (for bugs)

1. Start a task
2. Stop a task

### Console Output

N/A

### Error Log (Desktop only)

I could not find a log located on macOS: ~/Library/Logs/superProductivity/main.log

![Screen Shot 2022-01-26 at 12 15 31 PM](https://user-images.githubusercontent.com/55246715/151214776-e09eec5f-83a4-4348-b98f-d6c7cb2ff750.png)

**Comment by johannesjo** [comment]
Thank you very much for reporting this! Unfortunately I currently don't have a mac to properly debug this, so help and possibly a PR dealing with this, would be most welcome!

**Comment by totoroot** [comment]
I'm getting the same error dialogue on macOS, but it seems like it fails to load the stop icon.
I'm afraid I cannot really contribute in form of a PR, but thought I'd let you know that this is indeed an issue for more than one person.

```
Uncaught Exception:
Error: Failed to load image from path '/Applications/superProductivity.app/Contents/Resources/app.asar/electron/assets/icons/indicator/stopped-d.png'
at setTrayIcon (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/indicator.js:133:12)
at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/indicator.js:75:21
at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/get-settings.js:17:44
at Array.forEach (<anonymous>)
at IpcMainImpl.getSettingsCb (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/get-settings.js:17:13)
at IpcMainImpl.emit (events.js:376:20)
at Object.<anonymous> (electron/js2c/browser_init.js:161:9959)
at Object.emit (events.js:376:20)
```

**Comment by johannesjo** [comment]
I am unable to reproduce this. Did you try running the latest version (7.11.5)? Does the issue also occur there? How did you install the app (via the dmg or via the store or as a cask?
