### ISSUE TITLE
Missing string

### ISSUE THREAD

**Issue by milotype** [johannesjo/super-productivity#1888]
In the section "TAKE_A_BREAK", subitem "MESSAGE" the following english message appears in the app, but it is missing in the translation files, thus untranslated:
"You have been working for ${duration} without one. Go away from the computer! Take a short walk! Makes you more productive in the long run!"

**Comment by milotype** [comment]
MacOS X, superProductivity version 7.10.1

**Comment by johannesjo** [comment]
Thanks for opening this up! Makes a lot of sense to fix this. PRs are welcome!

**Comment by milotype** [comment]
I'm not a programmer and I couldn't find the string in the repository `johannesjo/super-productivity`:
`You have been working for ${duration} without one. Go away from the computer! Take a short walk! Makes you more productive in the long run!`

So I don't know how to help out.

**Comment by HendersonTyler** [comment]
I would like to have a crack at this one.

How do you get translations in the first place? Just using Google translate?

**Comment by johannesjo** [comment]
@HendersonTyler I am using babel translate and json files:
https://github.com/johannesjo/super-productivity/tree/master/src/assets/i18n

This is a bit more tricky than simply translating the string, since it's only the default one however. I'd suggest having a look on how it is done for the "Today" string which is also customizable.

**Comment by HendersonTyler** [comment]
@johannesjo I think this one might be a little tough for me. I've had a look at how Today is used, and with a switchMap etc. I don't have much experience with RXJS, so it might be best if someone with some more experience might be able to implement it. 

I do enjoy Angular, so I am happy if you want to tag me in some future tasks you think might be a bit easier.

**Comment by johannesjo** [comment]
Thank you @HendersonTyler ! Much appreciated!
