### ISSUE TITLE
'Every day' repeat config only repeats on weekdays

### ISSUE THREAD

**Issue by penn5** [johannesjo/super-productivity#1891]
### Your Environment

- Version used: 7.10.0 RPM
- Operating System and version: Fedora
- Desktop Environment: GNOME 41

### Expected Behavior

A task repeating every day should be scheduled every day

### Current Behavior

When a task is scheduled every day, it repeats only on weekdays

### Steps to Reproduce (for bugs)

1. Create a task
2. Schedule every day (not custom repeat config) at a fixed time
3. Go to timeline
4. Task is not scheduled at weekends
5. Change schedule to custom repeat config, every 1 days
6. Task is scheduled at weekends

**Comment by johannesjo** [comment]
Hi there! Thanks for opening this up! This should be fixed with 7.10.1.
