### ISSUE TITLE
[Feature] Add tags when creating tasks

### ISSUE THREAD

**Issue by dotarmin** [johannesjo/super-productivity#19]
Hii!

I would be really nice if it would be possible to have the opportunity to add tags for each task to categorise and sort/filter the tasks in the backlog.

Thanks!

/Armin

**Comment by johannesjo** [comment]
Hey there! Thanks for the suggestion. How would you integrate them into the UI?

**Comment by dotarmin** [comment]
> Hey there! Thanks for the suggestion. How would you integrate them into the UI?

Good question, let me come back to you! :)
