### ISSUE TITLE
Localize years format

### ISSUE THREAD

**Issue by milotype** [johannesjo/super-productivity#1901]
### Your Environment
- Version used: 7.10.1 (7.10.1)
- Operating System and version: MacOS 10.11.6

### Expected Behavior
Croatian language needs a period character after the year (they are ordinal numbers).

### Current Behavior
Currently in the Croatian version years do not (always) end with a period. When changing the year value, all year values do not have a period at the end.

### Steps to Reproduce (for bugs)
**screenshot:**
![localized cal 01](https://user-images.githubusercontent.com/43657314/152018537-c0129a72-68f8-49da-99c4-bb3d3a578ba4.png)

**Comment by johannesjo** [comment]
Thanks for opening this up!

**Comment by milotype** [comment]
This issue still exists in version 7.11.5

BTW, localized versions are also needed for the dates, not just the years. In Croatian both need to be treated as ordinal numbers.

**Comment by milotype** [comment]
This issue still exists in version 7.12.1 (7.12.1)
Operating System and version: MacOS 10.11.6

In general, all dates and years should be localized in the application ...
