### ISSUE TITLE
timeline should show repeatTask without a scheduled start time

### ISSUE THREAD

**Issue by EngelPika32** [johannesjo/super-productivity#1903]
## Problem Statement

Currently, repeatTasks are shown in the timeline as 'projections'. However, this only applies to those with a scheduled start time.
RepeatTasks without a start time ("all day task") aren't shown as 'projection'.

## :grey_question: Possible Solution

Show a projection where it fits with other repeat & scheduled tasks in the timeline. 
Take the 'limit task flow to specific work times' option into account. _(Essentially handling them the same way as scheduled tasks, except they are a projection.)_

## :arrow_heading_up: Describe alternatives you've considered

Ignore any other scheduled tasks and repeated tasks with start time, and just show a projection either at the start or end of the list/day. At least they are shown then.

## :heavy_plus_sign: Additional context

Just seems off to see all the scheduled & repeatTasks under the "Scheduled" section, but not all of them under the "Timeline" section.

**Comment by johannesjo** [comment]
Thanks for opening this up! I'd love to see them represented in a better way as well, but I found that this is a tough nut to crack with a lot of edge cases. :)

**Comment by EngelPika32** [comment]
Mmh, can we gather *(at least some)* edge cases together here?
It'd help to have a better look at what has to be taken care of (to crack this nut! :D)
