### ISSUE TITLE
Error: Invalid clock string

### ISSUE THREAD

**Issue by penn5** [johannesjo/super-productivity#1907]
### Steps to Reproduce
1. Set daily repeat config of a task to a single digit (e.g. "9")
2. The input form is validated and accepted when clicking submit
3. Upon submitting, this error appears.
4. If the app is reloaded, opening the task details also causes this error to reoccur

### Error Log (Desktop only)
Console output is adequate

### Console Output
Nothing beyond the stacktrace

### Stacktrace
```
isValidSplitTime (webpack:///src/app/util/get-date-time-from-clock-string.ts:10:10)
getDateTimeFromClockString (webpack:///src/app/features/tasks/task-additional-info/get-task-repeat-info-text.util.ts:12:8)
getTaskRepeatInfoText (webpack:///src/app/features/tasks/task-additional-info/task-additional-info.component.ts:130:36)
_next (webpack:///node_modules/rxjs/_esm2015/internal/operators/map.js:29:34)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)
this.destination.error (webpack:///node_modules/rxjs/_esm2015/internal/operators/distinctUntilChanged.js:50:29)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)
this.project.call (webpack:///node_modules/rxjs/_esm2015/internal/operators/map.js:35:25)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)
super._subscribe (webpack:///node_modules/rxjs/_esm2015/internal/BehaviorSubject.js:14:23)
```

### Meta Info
META: SP7.10.0 Electron – en-GB – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.10.0 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1644176140130: [WorkContext] Set Active Work Context 
1644176141806: [Task] SetSelectedTask (2) 
1644176141806: [Layout] Hide Notes 
1644176149472: [Task] SetSelectedTask 
1644176151911: [Task] Delete Task 
1644176151917: [Persistence] Save to DB (3) 
1644176151917: [Task] UnsetCurrentTask 
1644176151918: [Pomodoro] Pause Pomodoro 
1644176153017: [WorkContext] Set Active Work Context 
1644176153034: [Task] SetSelectedTask 
1644176153118: [Bookmark] Load Bookmark State 
1644176153120: [Project] Load Project related Data Success 
1644176153121: [Improvement] Clear Hidden Improvements 
1644176153123: [Improvement] Delete multiple Improvements 
1644176154079: [Layout] Show AddTaskBar 
1644176167174: [Task][Issue] Add Task 
1644176167179: [Persistence] Save to DB (2) 
1644176169163: [Layout] Hide AddTaskBar 
1644176172736: [Task] SetSelectedTask 
1644176172736: [Layout] Hide Notes 
1644176185659: [Task] Schedule 
1644176185660: [Persistence] Save to DB (2) 
1644176185661: [Task] Update Task 
1644176185662: [Project] Auto Move Task from today to backlog 
1644176185662: [Persistence] Save to DB (2) 
1644176192855: [TaskAttachment] Add TaskAttachment 
1644176192856: [Persistence] Save to DB 
1644176212257: [TaskRepeatCfg][Task] Add TaskRepeatCfg to Task 
1644176212259: [Persistence] Save to DB (2)
```

**Comment by ximemira** [comment]
@johannesjo 

I have the version 7.10.1. And i'm having still this error. 

It happens each time I open any repeat tasks, when I open the timeline and when I open the scheduled tasks. 

Error: Invalid clock string
isValidSplitTime (webpack:///src/app/util/get-date-time-from-clock-string.ts:10:10)allRepeatableTasksForDay.forEach( (webpack:///src/app/features/timeline/map-timeline-data/create-sorted-blocker-blocks.ts:70:20)createBlockerBlocksForScheduledRepeatProjections (webpack:///src/app/features/timeline/map-timeline-data/create-sorted-blocker-blocks.ts:66:29)createBlockerBlocksForScheduledRepeatProjections (webpack:///src/app/features/timeline/map-timeline-data/create-sorted-blocker-blocks.ts:28:7)scheduledTasks (webpack:///src/app/features/timeline/map-timeline-data/map-to-timeline-view-entries.ts:69:4)unPlanned (webpack:///src/app/features/timeline/timeline.component.ts:96:8)_next (webpack:///node_modules/rxjs/_esm2015/internal/operators/map.js:29:34)next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)this.clearDebounce (webpack:///node_modules/rxjs/_esm2015/internal/operators/debounceTime.js:40:29)

**Comment by johannesjo** [comment]
No wait actually I did :) Could you maybe provide me with a copy for your data (to contact@super-productivity.com)? There is also a privacy export option if you click on the "< >" button.
