### ISSUE TITLE
Notes panel enhancements

### ISSUE THREAD

**Issue by papernoise** [johannesjo/super-productivity#1908]
## Problem Statement
My notes are generally way too long for the current notes feature. This creates these super long text saussages, which are hard to navigate.

## :grey_question: Possible Solution
The simplest solution would be to add option to only show the first couple of lines of the note. The full note appears in a full-screen window (like the current "edit in fullscreen") when you click on it. No truncation for notes that are below a certain amount of characters.

## :arrow_heading_up: Describe alternatives you've considered
A more elaborate version of this would basically work like mosy Kanban apps. You add a title and description for notes, then the notes panel shows the title and optionally the initial part of the desciption. All note reading and editing happens in a full-screen window. 
There could also be two types of cards: quick note cards, for short bits of info, and then the ones described above for longer text.

## :heavy_plus_sign: Additional context
My notes can be anything from just quickly noting down something, saving ideas or tech specs. I often copy-paste still from email text and generally it's a lot of text.
Currently I handle everything with an external application (Typora), but it would be very handy to keep most of this stuff inside SP, since that's where the projects are being managed.

**Comment by johannesjo** [comment]
Hey @papernoise ! Thanks for opening this up :)

This is a problem indeed! There definitely needs to be some limit (possibly configurable). Also editing the notes in fullscreen (or at least a dialog) makes sense. I think, I have to play around with this a little, to see what feels best. I will give it a go tomorrow.

**Comment by johannesjo** [comment]
Hey there! Here comes the first draft:
https://test-app.super-productivity.com/

The logic is as follows: Everything longer than 320 chars is cut down to 160 chars and will open up fullscreen editing once clicked. I can see people complaining about not being able to view the note as parsed markdown, but maybe the editor itself could pimped to allow for that later on. 

Another alternative I could see work is scrollable notes (which were implemented at one point), but I think it's not ideal for very long notes in any case as you mention.

Let me know what you think!

**Comment by papernoise** [comment]
Hi! Thanks a lot for this!
I think it's a step in the right direction and yes I agree that proper markdown parsing would be essential to make this feature complete, basically clicking on the note would take you to full-screen preview mode (with markdown parsing), then clicking onto the text would get you into edit mode. The full-screen view then would need some means to get back to preview mode.
It would not be very different from how note editing/viewing works in the current version, just with more screen space.

Maybe it could be an extra button along with "cancel" and "save", titled "preview" or something like that.
Btw. I think the buttons could be easier to reach on top of the editor.

**Comment by papernoise** [comment]
When you mean inline, do you mean in the sidebar? I wouldn't have an issue with notes only being editable in the full-screen view. Since for me project notes tend to be more lenghty. Task notes are usually pretty short. So the sidebar would mostly be there to get an overview and quick access to all the notes.
But it would be interesting to hear other opinions as well.

Btw. for context. Right now I use Typora for notes, which is an excellent wysiwyg markdown editor.
I use the file-tree feature to navigate the various files. The file-tree is of coruse overkill here, but the file list Typora has could be an interesting reference:
https://typora.io/img/new/files.png

**Comment by johannesjo** [comment]
> When you mean inline, do you mean in the sidebar?

Yes, in place of the non full screen note item.

> I use the file-tree feature to navigate the various files. The file-tree is of coruse overkill here, but the file list Typora has could be an interesting reference:

Do you mean as  part of the full screen editor?

**Comment by papernoise** [comment]
> Do you mean as part of the full screen editor?
No I mean for the note list in the sidebar, which is already quite similar between the apps.

But to be more specific, the way I imagine things is roughly this:

## Option 1

### Start: user browsing notes (has just clicked on the notes icon to expand the sidebar

The sidebar shows the list of small **note cards** (markdown is pased), notes with more than 320char are tuncated
Clicking a note will open the full screen editor
The user has the option to **edit the card using the bottom right menu** (as in the current version)

From there's two possible options: the user can click the note or the edit button.

### case 1: user has clicked a note

The full screen window opens in **preview  mode**. Markdown is parsed, the user cannot edit the note.

### case 2: the user has clicked the edit option in the menu

In this case the full screen window opens in **edit mode**, the user can edit the note.

## Option 2

### Start: user browsing notes (has just clicked on the notes icon to expand the sidebar

The sidebar shows the list of small **note cards** (markdown is pased), notes with more than 320char are tuncated
Clicking a note will open the full screen editor **in preview mode**
We remove the **edit the card using the bottom right menu**

### The user has clicked a note

The full screen window opens in **preview  mode**. Markdown is parsed. 
Here I see two options then:
- Clicking into the note will take the user to edit more
- There's an **edit** button on the bottom.

### The user has entered edit more using one of the above actions

In this case the full screen window changes to **edit mode**, the user can edit the note.

if we use just a click on the whole window as a trigger to enter edit more, what happens once I press save?
Do I stay in the full screen window and this just changes to preview mode again?
In this case we'd also need a close button, which would also equal to the current cancel button.

Again more options…

### Option 1

I click on the note to edit, **save** to save it and go back to preview. Click **exit** any time to exit the note (saved or not)
But what if I exit the note without having saved?

### Option 2

I click on the note to edit, save is renamed to **preview** and toggles between edit and preview mode, clicking exit saves the note and exits the fullscreen window.

**Comment by johannesjo** [comment]
Hey @papernoise ! Based on what you said I figured, that it might be easier to just offer a button that allows to switch between the different view modes and to persist its last state.

Here is the latest update:
https://test-app.super-productivity.com/

**Comment by papernoise** [comment]
I like this! I think I would probably leave it in split screen mode most of the time, but it's nice to have the options.

It does not truncate the messages in the sidebar anymore.

**Comment by johannesjo** [comment]
> It does not truncate the messages in the sidebar anymore.

Possibly, you need to delete the cache and refresh the page again.

**Comment by papernoise** [comment]
Ahh you're right! Now it works.
Weird, because everything else was working as expected.

**Comment by johannesjo** [comment]
Alright! Thank you very much once more! :) Let me know if you have any other enhancement ideas!

Have a nice weekend!

**Comment by papernoise** [comment]
Thank you for your amazing work with SP!
