### ISSUE TITLE
Add desktop notification for exceeded time estimate

### ISSUE THREAD

**Issue by MSDDR** [johannesjo/super-productivity#191]
The pomodoro timer is nice but that workflow style doesn't suit me to well. Instead could we set timers for individual tasks (without break) and have the timer for the task notify us when the allotted time has passed. Also in addition can we get options to have the timer give us a desktop notification or a louder warning I keep missing it if I have music or a video playing in the background.

**Comment by johannesjo** [comment]
The feature is already kind of implemented. You can set a time estimate on task. If You then set the option "Notify when time estimate was exceeded" under Misc Settings on the Settings Page, you will be notified, once you exceed this estimate. Let me know if this works out for you.

**Comment by MSDDR** [comment]
I tried that setting out but just getting the "Time estimate exceeded for x" notification within the app itself isn't too helpful. Having a desktop notification or having the app popup and would be far more ideal.

**Comment by johannesjo** [comment]
I just checked and actually there should be a desktop notification. Could you provide a little more information on which version you are using and which OS you're on?

**Comment by KonTy** [comment]
Let me test this as well.

**Comment by KonTy** [comment]
Just tested it on my Win10 box did **not** get a system wide notification. I did get a bubble at the bottom of the app but no Windows Notification.

Operating System: Windows 10 Enterprise 64-bit (10.0, Build 17763)

**Comment by johannesjo** [comment]
Hm that's weird @KonTy thank you for testing this! Could you maybe debug the code on your system? The relevant bits are here:
https://github.com/johannesjo/super-productivity/blob/d2b153ccf9664ae6a950dcaea1934ecc5a769790/src/app/core/notify/notify.service.ts#L30-L54
And here:
https://github.com/johannesjo/super-productivity/blob/d2b153ccf9664ae6a950dcaea1934ecc5a769790/src/app/features/tasks/store/task.effects.ts#L444

**Comment by KonTy** [comment]
So I debugged it and everything looks fine. What I figured out is that it actually does create a notification but it is not shows by the system. If I click a notification history the notification is there. So what is happening is that it is raising a silent notification because my focus settings are set to only show notifications for Alarms. So I wonder if it is possible so raise an Alarm?
![Capture](https://user-images.githubusercontent.com/9524513/60299846-8604c080-98e2-11e9-98ab-f7d7709e1b9d.PNG)

**Comment by johannesjo** [comment]
@KonTy Thank you very much for digging into this!

I checked, but I'm afraid that afaik this is not possible at least not without a considerable amount of effort.

**Comment by KonTy** [comment]
> @KonTy Thank you very much for digging into this!
> I checked, but I'm afraid that afaik this is not possible at least not without a considerable amount of effort.

Perhaps we can add a link to the popup inside the app "Not seeing Desktop Notification?" and link it to a wiki how to disable Focus Mode in Windows. 

Another option is tg create a Window which would be Modal Top Most window just like email clients do it for reminders. And make it configurable weather to show it or not.

**Comment by johannesjo** [comment]
I go with a note about how to check your settings for now. Chances are, that some people don't want to see those notifications if they have configured their system like this.

**Comment by ignatmtn** [comment]
Hello! Your App is awesome. I want to see Windows notification, how can i make them turning on?
