### ISSUE TITLE
Repeating task not created

### ISSUE THREAD

**Issue by Ekleog** [johannesjo/super-productivity#1915]
Edit: Changing this issue to be a tracking issue for all circumstances where repeating tasks are currently not created:
- #1902 
- #1966 
- #1967 

-----

Original message

### Your Environment

- Version used: v7.10.1, NixOS package
- Operating System and version: NixOS 21.11
- Desktop Environment: Gnome

### Expected & Current Behavior

I started using Super Productivity 7.6 (on electron 13) on Wednesday. I created a few (10-15) repeated tasks, migrating them from my previous org-mode setup. i also completed them. I finished my day after midnight, and left Super Productivity running overnight.

On Thursday, to the best of my knowledge the repeated tasks were properly scheduled. On Thursday evening, I wanted to try out the ICS sync feature to have Super Productivity also be an interface for my meetings, so I upgraded to Super Productivity 7.10.1 (on electron 17). I tried out the feature (which deserves being marked as experimental I guess, but this is not the topic here :sweat_smile: ), finished my day before midnight, and left Super Productivity running overnight, with a few restarts in-between (including maybe one around midnight? I'm not sure).

Today, on Friday, I came back to Super Productivity to not see (all or any? not totally sure) the repeated tasks created. So I restarted it, thinking it probably needs a restart, and after the restart it asked me if it should schedule for today the repeated tasks. Except not all tasks that were scheduled on today were actually in the list it asked me to schedule: it is missing at least two that I can easily remember.

These two tasks are still in the “Repeated tasks” list with “Every day” repeat interval, so they were not lost. I tried restarting Super Productivity, as well as starting it from a terminal to get access to the logs, but there's nothing of notice there.

Relatedly, this seems somehow similar to the thing mentioned in the first paragraph of this comment, though the issue topic is something else: https://github.com/johannesjo/super-productivity/issues/1902#issuecomment-1030914644

I'm wondering if this maybe has something to do with the other issue, like full-day tasks being scheduled at midnight and so not being recreated if the app is not open at this exact point in time?

### Steps to Reproduce (for bugs)

Not sure how I can reproduce, as it's something that only happens once a day, but I'll let you know if some tasks don't repeat tomorrow again.

### Console Output
```
action-logger.reducer.ts:11 @ngrx/store/update-reducers 
Object
app.component.ts:278 Persistence already allowed
app.component.ts:307 4 out of 105423 MiB used (0%)
reminder.service.ts:89 loaded reminders from database 
Array(18)
model-version.ts:36 [M] Migrating model "SimpleCounter" to version from undefined to 2 
Object
model-version.ts:36 [M] Migrating model "Improvement" to version from undefined to 1 
Object
model-version.ts:36 [M] Migrating model "Obstruction" to version from undefined to 1 
Object
action-logger.reducer.ts:11 [SP_ALL] Load(import) all data 
Object
action-logger.reducer.ts:11 [SP_ALL] All Data was loaded 
Object
persistence.service.ts:338 LOAD COMPLETE false
model-version.ts:36 [M] Migrating model "SimpleCounter" to version from undefined to 2 
Object
model-version.ts:36 [M] Migrating model "Improvement" to version from undefined to 1 
Object
model-version.ts:36 [M] Migrating model "Obstruction" to version from undefined to 1 
Object
persistence.service.ts:338 LOAD COMPLETE false
model-version.ts:36 [M] Migrating model "SimpleCounter" to version from undefined to 2 
Object
model-version.ts:36 [M] Migrating model "Improvement" to version from undefined to 1 
Object
model-version.ts:36 [M] Migrating model "Obstruction" to version from undefined to 1 
Object
persistence.service.ts:338 LOAD COMPLETE false
model-version.ts:36 [M] Migrating model "SimpleCounter" to version from undefined to 2 
Object
model-version.ts:36 [M] Migrating model "Improvement" to version from undefined to 1 
Object
model-version.ts:36 [M] Migrating model "Obstruction" to version from undefined to 1 
Object
action-logger.reducer.ts:11 [Layout] Toggle SideBar 
Object
persistence.service.ts:338 LOAD COMPLETE false
model-version.ts:36 [M] Migrating model "SimpleCounter" to version from undefined to 2 
Object
model-version.ts:36 [M] Migrating model "Improvement" to version from undefined to 1 
Object
model-version.ts:36 [M] Migrating model "Obstruction" to version from undefined to 1 
Object
persistence.service.ts:338 LOAD COMPLETE false
model-version.ts:36 [M] Migrating model "SimpleCounter" to version from undefined to 2 
Object
model-version.ts:36 [M] Migrating model "Improvement" to version from undefined to 1 
Object
model-version.ts:36 [M] Migrating model "Obstruction" to version from undefined to 1 
Object
persistence.service.ts:338 LOAD COMPLETE false
model-version.ts:36 [M] Migrating model "SimpleCounter" to version from undefined to 2 
Object
model-version.ts:36 [M] Migrating model "Improvement" to version from undefined to 1 
Object
model-version.ts:36 [M] Migrating model "Obstruction" to version from undefined to 1 
Object
persistence.service.ts:338 LOAD COMPLETE false
model-version.ts:36 [M] Migrating model "SimpleCounter" to version from undefined to 2 
Object
model-version.ts:36 [M] Migrating model "Improvement" to version from undefined to 1 
Object
model-version.ts:36 [M] Migrating model "Obstruction" to version from undefined to 1 
Object
persistence.service.ts:338 LOAD COMPLETE false
model-version.ts:36 [M] Migrating model "SimpleCounter" to version from undefined to 2 
Object
model-version.ts:36 [M] Migrating model "Improvement" to version from undefined to 1 
Object
model-version.ts:36 [M] Migrating model "Obstruction" to version from undefined to 1 
Object
persistence.service.ts:338 LOAD COMPLETE false
model-version.ts:36 [M] Migrating model "SimpleCounter" to version from undefined to 2 
{ids: Array(2), entities: {…}}
model-version.ts:36 [M] Migrating model "Improvement" to version from undefined to 1 
{ids: Array(0), entities: {…}, hideDay: null, hiddenImprovementBannerItems: Array(0)}
model-version.ts:36 [M] Migrating model "Obstruction" to version from undefined to 1 
{ids: Array(0), entities: {…}
```

### Error Log (Desktop only)

Today's log plus yesterday's last log line:
 ```
[censored github http request failure log just before, to the best of my understanding related to the empty stack just below that is the last line of yesterday's logs]
[2022-02-10 22:24:08.741] [error] Frontend Error Stack:
[2022-02-11 10:35:11.231] [info]  close, isQuiting: undefined
[2022-02-11 10:35:11.234] [info]  Actions to wait for  [ 'FINISH_DAY_BEFORE_CLOSE_EFFECT' ]
[2022-02-11 10:35:11.236] [info]  BEFORE_CLOSE_DONE FINISH_DAY_BEFORE_CLOSE_EFFECT []
[2022-02-11 10:35:11.237] [info]  close, isQuiting: undefined
[2022-02-11 10:35:11.238] [info]  close, isQuiting: true
[2022-02-11 10:35:11.248] [info]  Quit after all windows being closed
[2022-02-11 10:35:16.518] [info]  { enabled: null, showDevTools: false, mode: 'bottom' }
[2022-02-11 10:35:16.620] [info]  Saving backups to /home/ekleog/.config/superProductivity/backups
[2022-02-11 10:35:17.325] [info]  No custom styles detected at /home/ekleog/.config/superProductivity/styles.css
[2022-02-11 10:36:41.106] [info]  close, isQuiting: undefined
[2022-02-11 10:36:41.118] [info]  Actions to wait for  [ 'FINISH_DAY_BEFORE_CLOSE_EFFECT' ]
[2022-02-11 10:36:47.305] [info]  BEFORE_CLOSE_DONE FINISH_DAY_BEFORE_CLOSE_EFFECT []
[2022-02-11 10:36:47.306] [info]  close, isQuiting: undefined
[2022-02-11 10:36:47.307] [info]  close, isQuiting: true
[2022-02-11 10:36:47.314] [info]  Quit after all windows being closed
[2022-02-11 10:36:50.933] [info]  { enabled: null, showDevTools: false, mode: 'bottom' }
[2022-02-11 10:36:51.047] [info]  Saving backups to /home/ekleog/.config/superProductivity/backups
[2022-02-11 10:36:51.786] [info]  No custom styles detected at /home/ekleog/.config/superProductivity/styles.css
[2022-02-11 10:56:24.001] [info]  close, isQuiting: undefined
[2022-02-11 10:56:24.003] [info]  Actions to wait for  [ 'FINISH_DAY_BEFORE_CLOSE_EFFECT' ]
[2022-02-11 10:56:25.722] [info]  BEFORE_CLOSE_DONE FINISH_DAY_BEFORE_CLOSE_EFFECT []
[2022-02-11 10:56:25.723] [info]  close, isQuiting: undefined
[2022-02-11 10:56:27.218] [info]  BEFORE_CLOSE_DONE FINISH_DAY_BEFORE_CLOSE_EFFECT []
[2022-02-11 10:56:27.219] [info]  close, isQuiting: undefined
[2022-02-11 10:56:27.264] [info]  close, isQuiting: true
[2022-02-11 10:56:27.265] [info]  close, isQuiting: true
[2022-02-11 10:56:27.282] [info]  Quit after all windows being closed
[2022-02-11 10:56:34.641] [info]  { enabled: null, showDevTools: false, mode: 'bottom' }
[2022-02-11 10:56:34.765] [info]  Saving backups to /home/ekleog/.config/superProductivity/backups
[2022-02-11 10:56:35.439] [info]  No custom styles detected at /home/ekleog/.config/superProductivity/styles.css
[2022-02-11 10:56:42.834] [info]  close, isQuiting: undefined
[2022-02-11 10:56:42.850] [info]  Actions to wait for  [ 'FINISH_DAY_BEFORE_CLOSE_EFFECT' ]
[2022-02-11 10:56:43.936] [info]  BEFORE_CLOSE_DONE FINISH_DAY_BEFORE_CLOSE_EFFECT []
[2022-02-11 10:56:43.937] [info]  close, isQuiting: undefined
[2022-02-11 10:56:43.938] [info]  close, isQuiting: true
[2022-02-11 10:56:43.944] [info]  Quit after all windows being closed
[2022-02-11 10:56:46.807] [info]  { enabled: null, showDevTools: false, mode: 'bottom' }
[2022-02-11 10:56:46.928] [info]  Saving backups to /home/ekleog/.config/superProductivity/backups
[2022-02-11 10:56:47.586] [info]  No custom styles detected at /home/ekleog/.config/superProductivity/styles.css
[2022-02-11 11:18:21.199] [info]  close, isQuiting: undefined
[2022-02-11 11:18:21.201] [info]  Actions to wait for  [ 'FINISH_DAY_BEFORE_CLOSE_EFFECT' ]
```

Is there anything I can do to help debugging this? As it's pretty problematic for me if repeated tasks were to be unreliably created, and Super Productivity as a whole seemed like an awesome piece of software!

**Comment by johannesjo** [comment]
Hey @Ekleog ! Thank you very much for opening this up! If a task is created or not is determined a couple of checks:
1. There was no instance already created on the same day
2. After app start, or when a context is selected where the task would appear (e.g. the project list for task's project, or the today list if a task is added to today).
3. The day is the correct day, determined by this code: 
https://github.com/johannesjo/super-productivity/blob/5c2206de6a1ea6d1e909fda589d527e5b356249a/src/app/features/task-repeat-cfg/store/task-repeat-cfg.reducer.ts#L80)

Either there already was already an instance created before, or there is an error in 3. We should be able to determine if 3 is the case by adding your data as unit test params in `task-repeat-cfg.reducer.spec.ts`.

**Comment by Ekleog** [comment]
Ok it's taken me a while but I think I've just been able to reproduce. I think the case where the user didn't click "finish day" at the end of the day.

So then basically the task is already present in the done list and doesn't get created as a new task, even if the "finish day" button is clicked at a few minutes past midnight.

Does this understanding make sense, and if so do you also think it's something that could be improved upon?

**Comment by Ekleog** [comment]
Hmm so I'll correct what I said: it seems like after a (computer crash-)restart the repeated tasks do appear, despite the fact that I had switched to another view and back to today's list before posting the message above… weird

**Comment by Ekleog** [comment]
Hmm so I'm not sure what “syncing is in progress” exactly means? If it's the progress bar at the bottom of the screen then I'm pretty sure I've tried switching out of the “today” screen and back in when the progress bar was not running, but on the other hand it's very possible the sync was not considered as “complete” because github answered something like “too many requests” (I'm not exactly sure why but it appears to be doing that pretty often, probably because I didn't add my github private token to super productivity — but I haven't had actual issues that I could guess were related to this)

So maybe the reason is that the github sync actually failed and this blocked creating the repeated tasks? It'd match what I lived just today, where there was no repeated tasks in the “done” task list, switching away and back to the “today” list didn't create the repeated tasks, but restarting super productivity completely solved the issue.

For other people hitting this issue, a workaround that has been working for me up to now is to just restart super productivity once a day after clicking “finished my day” instead of leaving it open while the computer is sleeping overnight.

**Comment by Ekleog** [comment]
I just found another way to reproduce, that's even a bit more surprising because it's action-at-a-distance:
1. do a normal day (number n), finishing after midnight
2. click "finish my day" after midnight (so technically in day n+1)
3. click "add all tasks planned for tomorrow" in the finished-day popup, this adds all the tasks planned not for the-day-after-a-sleep (still n+1) but for the-next-calendar-day (n+2, because we're already technically in n+1) [note: I hadn't noticed the first time because all my recurring tasks were daily, but this time I know it did add the tasks for day n+2]
4. do the-day-after-a-sleep (n+1) normally, finishing before midnight
5. the-next-calendar-day (so n+2), the recurring tasks will not be created because they had already been added in step 3

Overall… I'm not really sure how to best fix this. Here are my best thoughts:
- for the issue in https://github.com/johannesjo/super-productivity/issues/1915#issuecomment-1042808177, have a warning when trying to create a recurring task when there's already one present would make sense to fix the issue in, that allows force-creating the recurring task
- for the issue in this message, have a warning when clicking "add all tasks planned for tomorrow" in the first half of the day, that allows picking whether recurring tasks should be created or not yet and wait for tomorrow

Do these ideas make sense?

**Comment by johannesjo** [comment]
Thank you very much for digging into this! Makes sense to me what write!

About the new issue: I think the button should ideally switch to add all tasks planned for today, when the day changes.

About the original one: A confirmation dialog for the original could be a good option. So the user at least knows what's going on.

**Comment by Ekleog** [comment]
Thank you for your feedback! I've just opened tasks for each sub-issue, and transformed this task into a tracking issue that lists all the circumstances where one repeated task could end up not being created :)

**Comment by mohabbatman** [comment]
very relevant still
