### ISSUE TITLE
Make flash drive standalone version work

### ISSUE THREAD

**Issue by susnick** [johannesjo/super-productivity#192]
I am trying to specify the data location using commandline so i can keep my data on a portable thumb drive. I am using the version 2.7.8 exe running from my thumb drive and not the installed version. When I start via the commandline I do not get any information printed to the console.

Per the ReadMe "When starting the app via the command line the path to where emergency backups are saved is printed out to the command line. Just take away the /backup sub folder from the path and use the remaining path to sync via the cloud."

How can i specify the data location to make this truly portable?

**Comment by johannesjo** [comment]
Thanks for opening up this issue. Currently there is no way to specify a data, but it might be something we need to add. Haven't explored how well the flash drive version to be honest.

**Comment by susnick** [comment]
Well, you have my vote. Thats my only struggle with otherwise awesome software. When i move between different computers I dont have the same tasks.

**Comment by KonTy** [comment]
@susnick I know this might not work for everyone (including myself) but have you considered Google Drive Sync?

**Comment by johannesjo** [comment]
Just a quick update. This is unfortunately not as easy as I thought. It will take same time to get this working.

**Comment by johannesjo** [comment]
Ok I found a solution. Not super user friendly I admit, but it should work. You can now specify the data directory via a command line flag like this:
```
superProductivity 2.8.5.exe --user-data-dir=c:/test
```
Will be out with the next release.

Let me know if this works for you.

**Comment by susnick** [comment]
That would be perfect.

**Comment by johannesjo** [comment]
@susnick I made a release just for you ;)

**Comment by susnick** [comment]
You're the man! Works like a charm.
