### ISSUE TITLE
GitLab Integration : 404 when getting issue comments

### ISSUE THREAD

**Issue by stephdz** [johannesjo/super-productivity#1923]
I tried to use GitLab integration but I always get a 404 error when getting issue comments.

I checked the code and I think the problem is here :
https://github.com/johannesjo/super-productivity/blob/173510305c975873224c209f27ad767f82da64fc/src/app/features/issue/providers/gitlab/gitlab-api/gitlab-api.service.ts#L203-L208

`_sendPaginatedRequest` adds `&per_page=100&page=1` generating an invalid URL like this : `[...]/notes&per_page=100&page=1`. It should use a `?` before `per_page` if no parameter is present on the URL.

**Comment by johannesjo** [comment]
Thank you very much for digging into this! Would you maybe be willing to provide a PR for this yourself?

**Comment by stephdz** [comment]
Ok, I'll try to make a PR !
