### ISSUE TITLE
Task with two subtasks scheduled to tomorrow appears twice in the “today” list after clicking “add all tasks scheduled for tomorrow”

### ISSUE THREAD

**Issue by Ekleog** [johannesjo/super-productivity#1926]
Hey! Going to report another hitch I just noticed today while using Super Productivity. Before that, I want to say that despite the bugs I'm reporting, I really love this piece of software! To the best of my knowledge, while #1915 and #1902 are problematic in that I could end up missing tasks, this issue is only decorative and quite unlikely to trigger so it probably shouldn't be anywhere near high priority.

TLDR: despite my bug reports I still love Super Productivity, so thank you very much for all you do on this software!

### Your Environment

- Version used: nix package v7.10.1
- Operating System and version: NixOS 21.11
- Desktop Environment: Gnome

### Current Behavior

- Create a task
- Add two subtasks to it
- Schedule both subtasks for tomorrow
- Finish the day
- Click “add all tasks scheduled for tomorrow”
- Notice the task was added twice to the task list
- When clicking the “start tracking time” button on one of the subtasks it enables on both instances of the task, so it's probably not going to break all hell lose?

### Expected Behavior

The parent task should probably appear only once

**Comment by johannesjo** [comment]
Thank you very much for reporting! I'll try to have a look next Friday. Until then PR's are welcome :)
