### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'start')

### ISSUE THREAD

**Issue by Red1lagh** [johannesjo/super-productivity#1929]
### Steps to Reproduce

1. Open chronology interface

### Console Output

action-logger.reducer.ts:11 @ngrx/store/init Object
action-logger.reducer.ts:11 @ngrx/store/update-reducers Object
action-logger.reducer.ts:11 @ngrx/effects/init Object
persistence.service.ts:338 LOAD COMPLETE true
action-logger.reducer.ts:11 @ngrx/store/update-reducers Object
main.ts:23 Registering Service worker
app.component.ts:278 Persistence already allowed
app.component.ts:307 11 out of 109135 MiB used (0%)
reminder.service.ts:89 loaded reminders from database Array(0)
model-version.ts:36 [M] Migrating model "Improvement" to version from undefined to 1 Object
model-version.ts:36 [M] Migrating model "Obstruction" to version from undefined to 1 Object
action-logger.reducer.ts:11 [SP_ALL] Load(import) all data Object
action-logger.reducer.ts:11 [SP_ALL] All Data was loaded Object
initial-pwa-update-check.service.ts:19 ___________isServiceWorkerUpdateAvailable____________ false
sync.effects.ts:137 sync(effect)..... INITIAL_SYNC_TRIGGER
sync-provider.service.ts:169 Object
sync-provider.service.ts:477 GoogleDrive PRE1: ↔ Same Rev 8b96ea5253b083a012006871826dfaaf
persistence.service.ts:338 LOAD COMPLETE false
model-version.ts:36 [M] Migrating model "Improvement" to version from undefined to 1 Object
model-version.ts:36 [M] Migrating model "Obstruction" to version from undefined to 1 Object
sync-provider.service.ts:477 GoogleDrive PRE1: No local changes to sync
timeline.component.ts:131 icalEvents$ Array(1)
action-logger.reducer.ts:11 [WorkContext] Set Active Work Context Object
action-logger.reducer.ts:11 [Task] SetSelectedTask Object
map-to-timeline-view-entries.ts:46 mapToViewEntries Object Object
global-error-handler.class.ts:33 GLOBAL_ERROR_HANDLER TypeError: Cannot read properties of undefined (reading 'start')
    at map-to-timeline-view-entries.ts:185:50
    at m.project (timeline.component.ts:95:7)
    at m._next (map.js:29:35)
    at m.next (Subscriber.js:49:18)
    at y.debouncedNext (debounceTime.js:40:30)
    at g.A (debounceTime.js:53:16)
    at g._execute (AsyncAction.js:51:18)
    at g.execute (AsyncAction.js:39:28)
    at flush (AsyncScheduler.js:33:32)
    at S.<computed> (zone.js:2561:41)
(anonymous) @ global-error-handler.class.ts:33
action-logger.ts:42 Last actions before error: Array(30)
persistence.service.ts:338 LOAD COMPLETE false
model-version.ts:36 [M] Migrating model "Improvement" to version from undefined to 1 Object
model-version.ts:36 [M] Migrating model "Obstruction" to version from undefined to 1 Object
global-error-handler.util.ts:115 Object
zone.js:1063 Unhandled Promise rejection: TypeError: Cannot read properties of undefined (reading 'start') ; Zone: <root> ; Task: Promise.then ; Value: Error: TypeError: Cannot read properties of undefined (reading 'start')
    at n.<anonymous> (global-error-handler.class.ts:60:13)
    at Generator.next (<anonymous>)
    at h (global-error-handler.util.ts:227:38)
    at T.invoke (zone.js:372:26)
    at I.run (zone.js:134:43)
    at zone.js:1276:36
    at T.invokeTask (zone.js:406:31)
    at I.runTask (zone.js:178:47)
    at L (zone.js:582:35)
    at m.invokeTask [as invoke] (zone.js:491:21) Error: TypeError: Cannot read properties of undefined (reading 'start')
    at n.<anonymous> (https://app.super-productivity.com/main.041aa263f2e9b7fc.js:1:2243885)
    at Generator.next (<anonymous>)
    at h (https://app.super-productivity.com/main.041aa263f2e9b7fc.js:1:2240955)
    at T.invoke (https://app.super-productivity.com/polyfills.863cca7d8b9d1abd.js:1:6575)
    at I.run (https://app.super-productivity.com/polyfills.863cca7d8b9d1abd.js:1:1971)
    at https://app.super-productivity.com/polyfills.863cca7d8b9d1abd.js:1:16770
    at T.invokeTask (https://app.super-productivity.com/polyfills.863cca7d8b9d1abd.js:1:7193)
    at I.runTask (https://app.super-productivity.com/polyfills.863cca7d8b9d1abd.js:1:2588)
    at L (https://app.super-productivity.com/polyfills.863cca7d8b9d1abd.js:1:9191)
    at m.invokeTask [as invoke] (https://app.super-productivity.com/polyfills.863cca7d8b9d1abd.js:1:8274)
i.onUnhandledError @ zone.js:1063
apidata.googleusercontent.com/caldav/v2/radouanelaghrissi@gmail.com:1          Failed to load resource: the server responded with a status of 405 ()
timeline.component.ts:57 w6
(anonymous) @ timeline.component.ts:57
timeline.component.ts:131 icalEvents$ Array(1)
### Stacktrace
```
isSameDay (webpack:///src/app/features/timeline/map-timeline-data/map-to-timeline-view-entries.ts:185:49)
unPlanned (webpack:///src/app/features/timeline/timeline.component.ts:96:8)
_next (webpack:///node_modules/rxjs/_esm2015/internal/operators/map.js:29:34)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)
this.clearDebounce (webpack:///node_modules/rxjs/_esm2015/internal/operators/debounceTime.js:40:29)
dispatchNext (webpack:///node_modules/rxjs/_esm2015/internal/operators/debounceTime.js:53:15)
_execute (webpack:///node_modules/rxjs/_esm2015/internal/scheduler/AsyncAction.js:51:17)
execute (webpack:///node_modules/rxjs/_esm2015/internal/scheduler/AsyncAction.js:39:27)
action.execute (webpack:///node_modules/rxjs/_esm2015/internal/scheduler/AsyncScheduler.js:33:31)
timer (webpack:///node_modules/zone.js/fesm2015/zone.js:2561:40)
```

### Meta Info
META: SP7.10.1 Browser – fr-FR – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.105 Safari/537.36

### Actions Before Error
```
1645434711564: [Persistence] Save to DB (2) 
1645434712550: [Task] Add time spent 
1645434712551: [Tag] Update Work End for Tag 
1645434712565: [Persistence] Save to DB (2) 
1645434713550: [Task] Add time spent 
1645434713552: [Tag] Update Work End for Tag 
1645434713565: [Persistence] Save to DB (2) 
1645434714550: [Task] Add time spent 
1645434714551: [Tag] Update Work End for Tag 
1645434714564: [Persistence] Save to DB (2) 
1645434715491: [Task] Toggle start 
1645434715492: [Persistence] Save to DB 
1645434715492: [Task] UnsetCurrentTask 
1645434715493: [Pomodoro] Pause Pomodoro 
1645434717827: [Task] Update Task 
1645434717829: [Persistence] Save to DB 
1645434737647: [SP_ALL] Load(import) all data 
1645434737651: [SP_ALL] All Data was loaded 
1645434750955: [WorkContext] Set Active Work Context 
1645434750974: [Task] SetSelectedTask 
1645434756361: [SP_ALL] Load(import) all data 
1645434756364: [SP_ALL] All Data was loaded 
1645434756379: [WorkContext] Set Active Work Context 
1645434756387: [Task] SetSelectedTask 
1645434805184: [WorkContext] Set Active Work Context 
1645434805199: [Task] SetSelectedTask 
1645435824366: [SP_ALL] Load(import) all data 
1645435824369: [SP_ALL] All Data was loaded 
1645435828310: [WorkContext] Set Active Work Context 
1645435828333: [Task] SetSelectedTask
```

**Comment by johannesjo** [comment]
Hey there! Thank you very much for reporting this!

It might be that for some reason a bit of your data got into an invalid state that I didn't account for and that I can't reproduce. It would be great if you could share a copy of your data to contact@super-productivity.com, so I can debug this on my computer. You can create an export by navigating to "Settings" and then to "Import/Export" or you can use the "Export data" button from the error Dialog (there is also a button there which will anonymize the data before exporting).
