### ISSUE TITLE
Due tasks: Scheduled task re-appears in the list

### ISSUE THREAD

**Issue by halloichbingunnar** [johannesjo/super-productivity#1938]
### Your Environment

- Version used: 7.10.1
- Operating System and version: Win 10
- Browser Name and version: Desktop App

### Current Behavior

When re-scheduling a task on the "due tasks" list with a new date (not when "re-scheduling for tomorrow", though), after a few seconds it appears back on the list. When I click to re-schedule it again, the new and correct date is already displayed. 

### Expected Behavior

It shouldn't appear again :)

### Steps to Reproduce (for bugs)

Yes, it is happening every time.

**Comment by johannesjo** [comment]
Hey there! Thanks for opening this up. A few questions:
1. What do you mean by "due tasks list"?
2. On which list does the task re-appear?
3. Are you referring to tasks that have been moved to the backlog?
4. Where and how do you re-schedule the task?

**Comment by halloichbingunnar** [comment]
Haha, sorry, that was obviously very unclear -- I took a screenshot:
![Screenshot 2022-03-04 134538](https://user-images.githubusercontent.com/64837252/156766080-43307d0a-2f5a-4553-98ca-e2fbe8da0c57.jpg)

**Comment by johannesjo** [comment]
I am still not sure if I understand this correctly (I am most confused about the part where the task reappears), but maybe this explanation clears things up:

There is a difference between snoozing (doesn't change the time of the event) and re-scheduling/editing. Snoozing just changes the time of the reminder, but re-scheduling changes the time of the event itself.

Does this help?? :)

**Comment by halloichbingunnar** [comment]
Ok, sorry for being confusing! I'll try to explain differently step by step:
1. Due Tasks list pops up, because some tasks are due
2. I want to further shift one of the tasks, let's say to next wednesday, so I edit the time (as in the screenshot above)
3. I get back to the list of due tasks again. the task from step 2 is not listed anymore, because it isn't due anymore (because I just rescheduled it to next wedneday, obviously)
4. After a few seconds, the task from step 2 appears again in the list. 
5. I click "edit" again. Here, the due date is correct (next wednesday, as defined in step 2)
6. After confirming the time, the task is gone from Due Tasks -- now for real

Is that clearer now? :)

In the meantime, I realised that it is actually not happening everytime. When I opened up the issue, it was constantly happening for a week and it had happened before (so it didn't seem to be limited to the current version). With today's due tasks it was actually working fine. In the last days, I tried to find out when and why tasks re-appear, but I haven't found a clue yet... 

So: Sorry for opening this very unspecific and and confusing isssue! I suggest that I'll observe it for some time first and then get back to this thread. Maybe others may encounter the same problem and can contribute to it, too.

**Comment by johannesjo** [comment]
Thanks for your patience! :)

I think I understood the steps now, but I am still unable to reproduce this. With the "Due tasks list"  you mean the list inside the dialog if there have been multiple scheduled tasks at the same time, right?

I also found out (and fixed) that tasks are also removed from the list if editing the reminder is canceled. But since you mention that the time was updated for the task you edited and the due date is correct, this doesn't seem to be the problem here.

I will dig a bit further into the code. Might be there is some sort race condition here.

**Comment by johannesjo** [comment]
One more question:
What happens if you wait for a bit? Does the re-scheduled task disappear after some time?

**Comment by halloichbingunnar** [comment]
Thanks! I'll check the next time it happens! Interestingly, it hasn't happened for a while yet - so maybe it's not a top priority problem. I will observe it for the next weeks 😎 🕵🏻

**Comment by halloichbingunnar** [comment]
Ok, it happened again and this time I think I understood what happened - thanks to your explanation of the difference between snoozing and re-scheduling 🙃 

I rescheduled a task to another date, but the reminder (that was snoozed before) stayed – so I got reminded, even though the task was rescheduled. Maybe the combination of snoozing before rescheduling blocks the reminder from rescheduling, too? 

(Does that make sense? I feel like explaining it super complex again, haha)

**Comment by johannesjo** [comment]
Hey Gunnar! Thanks to your help I was now able to (hopefully) fix this. Seems like the reminders were never updated in case a reminder is edited that is technically already scheduled for the past. I'll try to publish a new release soon.

**Comment by halloichbingunnar** [comment]
Great! Thank you :)
