### ISSUE TITLE
Allow navigation and edition in archived tasks

### ISSUE THREAD

**Issue by surli** [johannesjo/super-productivity#1942]
## Problem Statement

In order to compute the total time spent on a specific sub-project, I want to apply a label on all tasks I worked on for this sub-project. I have not created a dedicated project in superproductivity for it, so those tasks are mixed up with tasks from the main project right now. 

## :grey_question: Possible Solution

Best option for me would be to be able to navigate on all my past tasks in the UI directly, possibly with some filtering by date or by keyword if that's doable. But that would be the cherry on the cake: my main request is to have a very simple UI allowing to scroll on all archived tasks.

## :arrow_heading_up: Describe alternatives you've considered

In order to do the time computation, I actually started by exported all my data in JSON, but it will take me some time to perform all the needed date/duration conversions, and to review which tasks I want to keep from the JSON directly. 
Would be nice to also have an export of the tasks only in CSV for faster operations.

**Comment by johannesjo** [comment]
Also possibly related: #614

**Comment by surli** [comment]
> Also possibly related: https://github.com/johannesjo/super-productivity/issues/614

Sounds related on the navigation aspect yes. However note that my primary need was to be able to edit my archived task to put a label on some of them. I updated the title in that way.

**Comment by mathisgauthey** [comment]
Hey there, I'm now using your app for my daily scheduling and would certainly need some way to edit older tasks tags for instance.
