### ISSUE TITLE
Evaluation not Working after finishing the day in German translation

### ISSUE THREAD

**Issue by hogismyspiritanimal** [johannesjo/super-productivity#1944]
When finishing the day with the button "FINISH DAY" I have the possibility to evaluate my day. This is currently not working in the German translation. The text and numer fields do not respond to my keyboard. The questions "How do you feel?" and "How efficient did you work?" are accessible via up/down buttons. I haven't tried other languages. In Standard/English it's working without any problems at all.

**Comment by johannesjo** [comment]
Hey there! Thanks for reporting this! I am unable to reproduce this. This only happens when you switched to German? And does this happen every time you try to reproduce this?
