### ISSUE TITLE
Sync settings are synced

### ISSUE THREAD

**Issue by penn5** [johannesjo/super-productivity#1951]
### Your Environment

- Version used: latest stable and master
- Operating System and version: all
- Desktop Environment: all
- Browser Name and version: all

### Expected Behavior

Settings relating to synchronisation are not included in the sync

### Current Behavior

Settings relating to synchronisation are included in the sync

### Steps to Reproduce (for bugs)

1. Set up synchronisation
2. Run a sync
3. Connect another computer to the same synced file, but instead of, for example, WebDAV, use a mapped network share as a LocalFile provider.
4. Settings are overwritten with the ones from the first computer when the first sync completes

Relates to #662

**Comment by johannesjo** [comment]
Thanks for reporting this!
