### ISSUE TITLE
A toggle to cause the 'actions menu' to be placed at the bottom of the screen instead of the top

### ISSUE THREAD

**Issue by incertoe** [johannesjo/super-productivity#1955]
main-header[_ngcontent-idu-c169] {
    position: fixed;
    z-index: 10;
    bottom: 0px;
    width: 100vw;
    background-color: black;
}

**Comment by johannesjo** [comment]
I live this open for discussion (please upvote if you like to see this). Meanwhile you might be able to achieve what you want by loading a custom stylesheet:
https://github.com/johannesjo/super-productivity#custom-themes-desktop-only
