### ISSUE TITLE
Not tracking time while on pomodoro break

### ISSUE THREAD

**Issue by tribly** [johannesjo/super-productivity#1957]
Today i forgot to start a new pomodoro session and the time didn't get tracked while being on break, even though the option `Stop time tracking for task on break` is disabled. So i guess this is a bug?

- Version used: 7.10.1
- Operating System and version: Arch Linux

### Expected Behavior

Time should be tracked when `Stop time tracking for task on break` is disabled.

### Current Behavior
Time isn't tracked when on break.

**Comment by nkrot** [comment]
may be related to https://github.com/johannesjo/super-productivity/issues/333

**Comment by tribly** [comment]
Still relevant.

**Comment by tribly** [comment]
Still relevant.
