### ISSUE TITLE
[FEATURE] Export task summary into CSV

### ISSUE THREAD

**Issue by KonTy** [johannesjo/super-productivity#196]
I've been using this app for about 1.5 months now and I really love it. By this time I think I figured out I can live without or found workarounds for all of the features that I wanted initially. The only feature I keep coming back to and I really regret it not having it is analysis. To me what good does a productivity tool do for you if you can't analyze how effective you are at producing features? 

@johannesjo you know how at the end of the day when you finish your day you show a little summary of time spent? It would be very useful to have a export button where you could chose an arbitrary time period and export all the tasks that were completed or started in that time period into a CSV file that way, we could import it into Excel and analyze it.

I'm thinking the following columns would be good to have in the CSV

PROJECT NAME
TASK NAME
Time Started
Time Finished
Due date
Estimate Time

**Comment by johannesjo** [comment]
Thanks for your suggestion! For my own needs I'm currently satisfied with metrics feature, but that doesn't mean that I'm against such feature. A button on the metrics page opening a modal with all those options you mentioned could be a good way to integrate it. Would you be interested in doing so yourself?

**Comment by KonTy** [comment]
In your opinion how much work/learning would this require? Also where would one start here?

**Comment by johannesjo** [comment]
That strongly depends on the existing knowledge ;) 

But I think the amount of effort is limited and on top of that the feature can (and should) be implemented in way that it is interconnected with just a few other parts of the app, so chances to break something else are slim. The most complicated part is probably getting all the data, but to keep it simple you just could use  `getComplete` form the `PersistenceService` ([check it here](https://github.com/johannesjo/super-productivity/blob/9b661dc6545d6e1a0dabb551c3c8800250dac60b/src/app/core/persistence/persistence.service.ts#L243)). That should give you all the data available from all projects with a single call. For CSV export and how to make a modal etc, you can  have a look [here](https://github.com/johannesjo/super-productivity/tree/master/src/app/features/simple-task-export)

**Comment by theCalcaholic** [comment]
Isn't this feature precisely what the export function does (except for the arbitrary time window maybe)?

**Comment by johannesjo** [comment]
@theCalcaholic now that you mention it, it seems to look this way. What might be missing atm is support for a list for all projects and a specified time frame mentioned in the request.

**Comment by johannesjo** [comment]
@KonTy does it work for you as is?

**Comment by KonTy** [comment]
@johannesjo sorry I was out of the loop for awhile. You know I was thinking about exporting into CSV from a analytical point of view meaning I want to analyze how I spend my time. (After all why have a productivity app if you can't analyze the effect of it on productivity). But then this weekend it dawned on me, you can also use this feature for Tracking the time for a small business. You know at least in US (not sure how it is in Europe) if you are freelancing or have a small business, You suppose to provide a break down of hours of what you did and how much time you spent on it. So this tool is PERFECT for it, the only thing that is missing is Export of selected projects in any given time.

This could be a gateway for a Pro version that you might be able to sell of Apple and Microsoft store and monetize your outstanding work! I would certainly buy that app.

**Comment by johannesjo** [comment]
Hey! There are a couple of options for exporting your data already in place (because like in the US some of my employers wanted some sort of worksheet, usually on a monthly or weekly basis):
* There is the export function for today on the daily summary
* There is the export function for the current week on the daily summary
* There are the export week, month and year functionalities under worklog with a lot of stuff to configure
* There is the export function to google sheets on a daily basis

Does neither of these fit your use case?

A server based hub to collect the tracking data for several people is an excellent Idea! I might work on that at some point. Currently I think the user base is too small for that. What already would kind of work for that is the google spreadsheet export.

**Comment by KonTy** [comment]
I agree about the server tracking thing. That's what I love about your app it doesn't need and backend services and can be standalone. Please keep it that way too. Personally I hate cloud services when I'm forced to use them for any feature, unless I choose to push them there myself proactively, like with your apps case, where I might choose to push it to Google.

As far as export features, I was not aware you have implemented them. I will install the new version immediately and test right away. I think this is awesome great job man. Appreciate your dedication to this very cool app.
