### ISSUE TITLE
Arrow up and down when creating new task

### ISSUE THREAD

**Issue by papernoise** [johannesjo/super-productivity#1962]
## Problem Statement / Possible Solution

A little enhancement idea on an existing feature, so I don't think this requires too much explanation.
I quite like that one can choose if the new task should be created on top or on the bottom of the list. I use it quite often.
To be more specific I mean this one:
![image](https://user-images.githubusercontent.com/1595523/158211571-0aa8e736-b431-4ad3-b313-ee9aed0f0eb8.png)

To make this even more useful, I suggest that the **up and down arrows** on the keyboard be used to toggle between the aforementioned settings. Of course up would be used to set to "add task on top" and down would set it to "add task on the bottom".
Bonus points for making this user-configurable in the settings.

**Comment by johannesjo** [comment]
Thanks for the suggestion. The up and down arrow keys are already used for selecting already existing tasks and issue tasks, so I'd rather not put more functions on them. You can currently change this by using `Ctrl+2` (and `Ctrl+1` for toggling add to backlog/today).
