### ISSUE TITLE
Switching to a TTY prevents idle time tracking

### ISSUE THREAD

**Issue by SymenTimmermans** [johannesjo/super-productivity#1965]
### Your Environment

- Version used: 7.10.1 (via Arch AUR package "aur/superproductivity-bin 7.10.1-1")
- Operating System and version: Arch Linux
- Desktop Environment: DWM window manager with GTK and LightDM.

### Expected Behavior

If I take a break, I switch to a TTY, usually by pressing [CTRL] [ALT] [F3].
Superproductivity should start registering "idle activity" (it did do this some versions before).
When I return to the graphical desktop session, I should be getting a popup asking me to register my idle time as either a task or a break. 

### Current Behavior

Instead, Superproductivity keeps tracking activity, and does not consider the user being idle.
What I now have to do is to stop the current activity, and subtract my idle time from the registered time manually.
This is tedious, and error-prone, because I don't always remember when my break started.

### Steps to Reproduce (for bugs)

1. Start time tracking on a task.
2. Switch to a TTY.
3. Wait at least 5 minutes (or for as long as you have specified in the setting "Trigger idle after X")
4. Switch back to the graphical desktop session.
5. Observe that "idle time" has not triggered.

**Comment by johannesjo** [comment]
Thanks for reporting this. Help would be welcome., though this seems to be possibly an OS error, since SP uses what electron offers as an interface which in turn only uses what chromium offers, which in turn uses the standard system api for this.
