### ISSUE TITLE
Gitlab integration is not working

### ISSUE THREAD

**Issue by ErezAmihud** [johannesjo/super-productivity#1970]
I have not found anyone that reported problems, so if anyone has a fix please comment it .

I created a project and connected it to a gitlab project/group, and I couldn't import any issues.
1. When using a gitlab project, when the app tries to get suggestions for issues it gets 404 when requesting notes (the request parameters are starting with & instead of ?).
2. When accessing a project inside group inside another group the requested url path is not correct, because all `/` are replaced with `%2f`.
3. when it does give me a suggestion (somehow in my server instance it works) when I try to add it, it raises a promise error.
4. Sometimes it can't get the issues - the request is sent and is fine but the gui is not updated

### Your Environment
I tried it on the website and on a personal server that I launched.

- Version used: master - 7.10.1

### Recreate (each number correlate to another issue)
1. Honestly I am not sure
2. make nested groups and an issue inside of that
3. use project that is inside a group
4. use a path to a project of the user that set the token, then try to create a new task - and wait for autocompletion

I will create a merge request to fix it later.

Edit:
apparently https://github.com/johannesjo/super-productivity/pull/1961 solved 1-3

**Comment by conradob** [comment]
@ErezAmihud this was fixed on https://github.com/johannesjo/super-productivity/pull/1961
I believe we just need a release from @johannesjo

**Comment by ErezAmihud** [comment]
> @ErezAmihud this was fixed on https://github.com/johannesjo/super-productivity/pull/1961
> I believe we just need a new release from @johannesjo 

A part of it was, but there is still the problem the there was a promise exception
I made a pr to fix it
