### ISSUE TITLE
Android circular button icons off-center

### ISSUE THREAD

**Issue by Braboware** [johannesjo/super-productivity#1975]
### Your Environment

Android 11
Samsung Galaxy S10+

### Expected Behavior
Not the biggest deal, but circular buttons should have the icon centered

### Current Behavior

Icons are ever so slightly off-center

### Steps to Reproduce (for bugs)

1. Install and open the android app

![Screenshot_20220321-210017_Super Productivity](https://user-images.githubusercontent.com/8632291/159389241-b352e7e4-ce9b-416b-b2c7-fe1924249c9d.jpg)
![Screenshot_20220321-210134_Super Productivity](https://user-images.githubusercontent.com/8632291/159389251-ebd250ab-699d-4c36-aeef-38654e358dd5.jpg)

**Comment by johannesjo** [comment]
PRs are welcome!
