### ISSUE TITLE
Random prompts to track tasks

### ISSUE THREAD

**Issue by abhyudaya63** [johannesjo/super-productivity#1978]
[https://github.com/tagtime/TagTime](url)
Tagtime seems to not be actively developed. but the concept has a lot of merit. and this could be used alongside SuperProd.
User is randomly prompted throughout the day on what they are doing right then thus forming a much clearer and honest picture of their daily schedule. also, this reduces the effort for tracking tasks and switching between them.

the prompt could have a dropdown menu or even keyboard shortcuts to quickly answer and continue with the activity.

**Comment by johannesjo** [comment]
Thanks for the suggestion. The standard time tracking concept of SP is very different, so I am honestly not sure how we could integrate this well tbh.

**Comment by abhyudaya63** [comment]
another service on the data of projects and tasks would be more feasible probably.

**Comment by Jazb** [comment]
I think than could be similar to [Daily](https://dailytimetracking.com/blog/time-tracking-without-using-timers)

**Comment by abhyudaya63** [comment]
Yes. but the prompt must be random to gauge good metrics.
although I will give this a try and would probably be more helpful than my current system :smile:
