### ISSUE TITLE
Working TIME SPENT FOR OTHER DAY not displayed properly (7.10.1)

### ISSUE THREAD

**Issue by MartinWegmann** [johannesjo/super-productivity#1985]
# Symptom

For a task I have used "**ADD TIME SPENT FOR ANOTHER DAY**". 
**In release 7.10.1** I observe that this is **not properly displayed any more**: 
Either date or the time is omited, compared to the display in former releases.

![image](https://user-images.githubusercontent.com/1507511/160769115-45866b8a-b8d9-4b18-a758-0c747dc36175.png)

![image](https://user-images.githubusercontent.com/1507511/160769248-87cc72d6-03b2-4d46-9cb5-b9bf1138a105.png)

.

Thanks for a correction here.
and thanks for your excellent software, Johannes.

Kind regards,
Martin

**Comment by johannesjo** [comment]
Thank you very much for reporting this! Should be fixed with the next release.

**Comment by johannesjo** [comment]
f

**Comment by MartinWegmann** [comment]
Confirmed. Yes, that's fixed with 7.11.2 .
👍🙏
