### ISSUE TITLE
Repeating Task - Date Picked is not reflected - Shows previous day instead

### ISSUE THREAD

**Issue by realmrealm** [johannesjo/super-productivity#1986]
### Your Environment

- Version used: Snap - 7.10.1
- Operating System and version: Arch - latest
- Desktop Environment: Gnome
- Browser Name and version: n/a

### Expected Behavior

When choosing a task and making it repeating you can choose "Monthly", and then choose a date. The task then shows that day next to the "Repeat" section. (You choose April 3rd, "Repeat" section shows "Monthly on the 3rd"

### Current Behavior

When you choose a date for repeating the task shows the prior day next to "Repeat". (You choose April 3rd, and then in the "Repeat" section it shows "Monthly on the 2th") - A further thing is that that everything is the "th" instead of using "rd" or "st" (1st, 2nd, 3rd, etc)

### Steps to Reproduce (for bugs)

1. Make a new task
2. Click the "Additional Info" button
3. Click the "Repeat" section
4. Change the "Repeat Config" dropdown to be "Custom repeat config"
5. Change "Repeat cycle" to be "Month"
6. Choose a "Start date", and then click the "SAVE" button.
7. Observe that next to the "Repeat" section it now says the day prior to the day you chose.

### Additional Info...

A video of it happening to illustrate: https://www.dropbox.com/s/fm5n2c9sja9ppkh/2022-03-30%2008-04-49.mp4?dl=0

**Comment by johannesjo** [comment]
Thank you very much for reporting this! Potentially this is already fixed. At least I am unable to reproduce this. I will make a new release shortly. Please let me know if the issue persists with it.
