### ISSUE TITLE
Add gitlab "scope" param  to openproject integration

### ISSUE THREAD

**Issue by hugaleno** [johannesjo/super-productivity#1989]
Users should be able to filter issues the same way they can on gitlab integration.
* All
* Created by me
*  Assigned to me

**Comment by hugaleno** [comment]
I think I can work on this on my spare time. Already did some research on openproject api and should be possible to achieve the same goal

**Comment by johannesjo** [comment]
Thanks for the offer @hugaleno! That would be great! Please let me know if you have any questions!

**Comment by hugaleno** [comment]
I think this is working fine. Any problem regarding this should be a new issue.
