### ISSUE TITLE
superProductivity snap fails to start on Fedora 30

### ISSUE THREAD

**Issue by barrel0luck** [johannesjo/super-productivity#199]
### Your Environment

* Version used: 
* Operating System and version: Fedora 30
* Desktop Environment:  GNOME 3.32
* Browser Name and version:  N/A

### Expected Behavior
 The app should open.

### Current Behavior
The app doesn't open.

### Steps to Reproduce (for bugs)

1. On Fedora 30 install snapd.
2. Install superProductivity.
3. Open superProductivity.

### Console Output

Trying to run superproductivity from console fails. There is no output.
### Error Log (Desktop only)

I can't find the log. Doesn't seem to be located at the given destination.

**Comment by johannesjo** [comment]
Thanks for reporting. Are you running wayland or xorg as a display manager? Ubuntu runs fine, but it seems that there might be a general problem for snaps on fedora :/

**Comment by barrel0luck** [comment]
Ah, I'm running the default wayland session. I can try the xorg session and report as well in a while. It's just that I can't log out right now. I'll update the xorg situation in a while.

**Comment by barrel0luck** [comment]
I tried the app on Xorg and it worked perfectly! It doesn't work on Wayland only then I guess! Apologies I did not think about that when writing the bug report!

**Comment by johannesjo** [comment]
@barrel0luck Don't be! It's good to know that the App is not working with Wayland, especially since more and more distros are shipping with Wayland as default display manager. I will investigate!

**Comment by johannesjo** [comment]
I think I fixed it it with the latest edge release also for wayland. Could you maybe be so kind to also check it on your machine?
```
sudo snap install --channel=edge superproductivity
```

**Comment by barrel0luck** [comment]
Works perfectly now! Thanks!
