### ISSUE TITLE
More keyboard shortcuts for keyboard-driven use

### ISSUE THREAD

**Issue by jefft** [johannesjo/super-productivity#2]
Shortcuts are glorious things, and you've made a good start on them. Having SP appear instantly with ctrl-shift-x is (IMHO) a killer feature.

May I suggest further:

- '?' anywhere should open a shortcut help page, as happens in github and Atlassian apps
- In the daily planner, it would be nice to be able to move up/down between tasks with 'j' and 'k' (and up-arrow and down-arrow), move tasks from/to the backlog with 'l' and 'h', and with toggle between Today and the Backlog with Tab.
- In general, shamelessly copy the GMail shortcuts.

**Comment by johannesjo** [comment]
I really love your suggestions! I will work on them as soon as I can. Btw. There is the currently undocumented  option to move the currently focused task up and down via Ctrl+Shift+up and Ctrl+Shift+down like you can do in the Jetbrains products with selected text.

**Comment by johannesjo** [comment]
I added a help function as well. Closing this for now. If you have any more ideas let me know!

**Comment by jefft** [comment]
Very nice, thanks!
