### ISSUE TITLE
Unable to close "yesterday's note for today"

### ISSUE THREAD

**Issue by maqp** [johannesjo/super-productivity#20]
Hi. The app looks really cool, but some issues really affect usability. 

**Version affected:** 1.3.4 (.deb)
**OS:** Ubuntu 17.10 (probably all)
**Current result:** Hitting the "REMOVE" button does nothing.
**Expected result:** Note disappears when pressing "REMOVE".

**Comment by johannesjo** [comment]
Thanks for reporting. I published a patch which should be available with version 1.4.2. Could you please check if it works for you?

**Comment by johannesjo** [comment]
I'm assuming that it does work now. Feel free to reopen, if it doesn't.
