### ISSUE TITLE
Local file sync on mobile

### ISSUE THREAD

**Issue by diogomsfranco** [johannesjo/super-productivity#2001]
Hi!

I was wondering if there are any plans to make it an option to use the filesystem as a sync option on mobile. (I think its already an option on the desktop app) For example, the app would generate a file that was saved on a certain location. If that file was to be synced in various devices all of them would showcase the same information in the app. This would make it easier for those using file-sync solutions like syncthing. 

Thank you so much and keep up the amazing work!

**Comment by johannesjo** [comment]
I assume we're talking about android? :)

**Comment by diogomsfranco** [comment]
Hello!

Yes android ahah. I've seen u already have some requests about this, sorry for adding a new one. D

**Comment by johannesjo** [comment]
No no that's alright. Probably makes sense to track this in a new issue anyway. :)

**Comment by diogomsfranco** [comment]
Do you think this would be a hard thing to implement?

**Comment by johannesjo** [comment]
> Do you think this would be a hard thing to implement?

Not for someone who is familiar with android development I think. If someone volunteers for the android part, I would offer to write the frontend interface part.

**Comment by zoli** [comment]
I will try to tackle this issue. It seems nobody else is working on it.

**Comment by quaintdev** [comment]
I think this would be an excellent addition to the app because then I can use syncthing and everything syncs up nicely!

**Comment by zoli** [comment]
> I think this would be an excellent addition to the app because then I can use syncthing and everything syncs up nicely!

Exactly I want this feature to use it with syncthing. And it is almost done, I will create a PR for it next week.

**Comment by scaramouche88** [comment]
Hi!
Quite a noob on synching here...   So If I understand the last merging on the topic, it's possible to synch a linux and an Android apps, right? (@zoli ? :) )

If yes, since I never used syncthing, can you explain how to do it? 
(an external tutorial might do the job, I like to learn new stuff by myself)

**Comment by zoli** [comment]
> it's possible to synch a linux and an Android apps, right?

Yes.

[Syncthing](https://syncthing.net/) is a tool (there are other tools for this purpose to) to sync folder or files between devices, you can checkout their website.
Most of Superproductivity data is saved in a single file, So if you sync that file between two devices (e.g android and desktop) with Syncthing then your Superproductivity on both devices will be closely on same state.

**Comment by scaramouche88** [comment]
Thanks.
I tried today but on the android app (both playstore and f-droid) there is no "localfile" option in the synch menu. Only Dropbox, GoogleDrive or WebDAV. Maybe the new release is not yet on those markets? Or I am doing something wrong?

**Comment by johannesjo** [comment]
Hey there @scaramouche88 ! The new version is stuck in the verification process atm. If you like you can test the new feature by compiling the android app yourself.

**Comment by kaibrune** [comment]
Any updates on this? Still stuck in the verification process? :D Would love to see the file sync option on mobile.

**Comment by s1dh** [comment]
Is there any ETA for the new release that adds the "local file " option feature  on Android app ?

**Comment by mathe00** [comment]
> Any updates on this? Still stuck in the verification process? :D Would love to see the file sync option on mobile.

I would also love this feature

**Comment by johannesjo** [comment]
We're currently stuck with google not allowing for the publication of the release. If anybody has an idea to make this feature work without the currently required permission, please let us know!!
https://github.com/johannesjo/super-productivity-android/issues/13
