### ISSUE TITLE
7.11.2 Prerelease / Windows :: High CPU load when timer is counting on a task

### ISSUE THREAD

**Issue by MartinWegmann** [johannesjo/super-productivity#2003]
Hello Johannes,

with version 7.11.2 I observe that the CPU load by Super Productivity reported in the Windows 10 Task Manager is "Moderate", "High" or "Very high", if  a timer is counting on a task. The CPU load is between 5% an even 18%. This happens even when the Super Productivity window is not active. When I stop counting on a task, the CPU load drops to "Very low".

Is something wrong here?
Thanks for checking the prerelase.
Martin
: )

### Your Environment

- Version used: 7.11.2
- Operating System and version: Windows 10
- Browser Name and version: I have installed the setup.exe.\
  Typing `navigator.useragent` in the console gives me: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.11.2 Chrome/98.0.4758.109 Electron/17.1.2 Safari/537.36'

### Expected Behavior

Very low CPU load if window is not active.

### Current Behavior

I observe that the CPU load by Super Productivity reported in the Windows 10 Task Manager is ranges from "Moderate" to "Very High", if  a timer is counting on a task. The CPU load is between 5% an even 18%. This happens even when the Super Productivity window is not active. When I stop counting on a task, the CPU load drops to "Very low". There are 4 threads indicated.

![image](https://user-images.githubusercontent.com/1507511/161936130-f21744f3-f695-47e2-823f-e87600741618.png)

### Steps to Reproduce (for bugs)

I can reproduce the problem reliably,
Closing and restart of Super Productivity does not help.

### Console Output

![image](https://user-images.githubusercontent.com/1507511/161936917-d1aed071-6d77-45fc-94f0-08369b2557bc.png)

### Error Log (Desktop only)

![image](https://user-images.githubusercontent.com/1507511/161937781-c2da87c8-8c4c-407e-a1fe-14aed1d73d15.png)

**Comment by wacomoto** [comment]
I have the same issue. Further, the user interface becomes unresponsive and janky. On stopping the timer, everything is smooth (as per previous versions).

**Comment by wacomoto** [comment]
Just confirming, rolling back to 7.10.1 resolves the issue.

**Comment by johannesjo** [comment]
Thanks for digging into this. I'd assume that the new electron version is responsible for this, since an update was made between 7.11 and 7.10. We might try updating electron to the next version 18.x. I won't get to it until next week Friday. But in case you might want to give it a shot, help would be welcome!

Probably related: #1678

**Comment by johannesjo** [comment]
I made several adjustments for 7.11.5. Please let me know if the new build improves the situation.

**Comment by MartinWegmann** [comment]
**Max CPU load** on my **older work PC with i7-6700 CPU** under version **7.11.5** is typically
< 15% if timer is running and Super Productivity is in focus.
< 10% if timer stopped and Super Productivity is in focus.
**< 6% if timer is running and Super Productivity is not in focus.**
< 2% if timer stopped and app is used.
<0,5% f timer is stopped and app not in focus
CPU Load reacts sensitively on mouse movements and deviates a lot.

So, yes the situation **did improve a lot with 7.11.5 compared to 7.11.2** . 
When using the app I do not recognize delays any more.

On my **new PC** with AMD Ryzen 5600 the **CPU load is always below 2%**. 
No problem there.

Thanks.
: )

**Comment by johannesjo** [comment]
I am leaving this open for now, in case someone has any additional improvement suggestions. Thanks everybody!

**Comment by wacomoto** [comment]
Looks to be fixed for me too. CPU usage back to 7.10.1 levels and no issues with the interface. Thanks :)

**Comment by s-maltsev** [comment]
I have 7.13.2 and still high CPU usage which makes my laptop to slow down and CPU fan is switched on permanently.
![image](https://github.com/johannesjo/super-productivity/assets/105911370/965465aa-a64f-4908-aee1-1a2afbb91bf9)

My laptop config is:
CPU: 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz   3.00 GHz
RAM: 8 GB
OS: Win 10 Pro (x64)
