### ISSUE TITLE
Add jira transition handling to openproject integrations

### ISSUE THREAD

**Issue by hugaleno** [johannesjo/super-productivity#2005]
## Problem Statement
I really want that on openproject, would be so helpful.
Add Jira transition handling to openproject integration.

## :grey_question: Possible Solution
When transitioning  between Play/Pause/Done have a option to change issue status on openproject, just like jira does.

## :heavy_plus_sign: Additional context

I think i can try to get it done

WDYT @johannesjo

**Comment by hugaleno** [comment]
Can you explain what exactly is this, it pulls from jira? Not sure if there is something similar on openproject..

![image](https://user-images.githubusercontent.com/6486234/162536800-75acfaed-e5f7-44ba-8a65-7e084c6225ad.png)

**Comment by johannesjo** [comment]
Thanks for opening this up! Would be nice to have this, I think! PRs are welcome!

**Comment by hugaleno** [comment]
I'm already working on this one, you can assign to me

**Comment by hugaleno** [comment]
This is already implemented.
