### ISSUE TITLE
Error when polling JIRA for updates

### ISSUE THREAD

**Issue by msbentley** [johannesjo/super-productivity#202]
When I click through JIRA issues in a project, when SP tries to reload I get the message:

"Jira: polling changes for issue"

and then a pop-up as in the screenshot, with the message:

TypeError: Cannot read property 'toISOString' of undefined

![Selection_019](https://user-images.githubusercontent.com/1671065/62685326-be5bec00-b9c2-11e9-81ca-63132afacfa3.png)

### Your Environment

* Version used: 2.10.3
* Operating System and version: ubuntu 18.04
* Desktop Environment: unity

### Error Log (Desktop only)

[log.log](https://github.com/johannesjo/super-productivity/files/3480498/log.log)

**Comment by johannesjo** [comment]
Thanks for reporting. I'll have a look!

**Comment by johannesjo** [comment]
Ok this is hopefully fixed with the next release. Thanks for reporting again!

**Comment by msbentley** [comment]
Fantastic, thanks - I'll git it a try when released and report back!

**Comment by msbentley** [comment]
Looks fixed in 2.10.7, many thanks!
