### ISSUE TITLE
Add an issue import button

### ISSUE THREAD

**Issue by fkohrt** [johannesjo/super-productivity#2022]
## Problem Statement

For some projects I collaborate with others via CalDav and/or GitLab issues. For these projects I usually don't create issues within Super Productivity but from the respective web service (i.e. GitLab or Nextcloud). But after adding them in the web I lack a way to quickly process them from within Super Productivity - the automatic import only happens periodically and the only way to trigger a manual import requires many clicks (re-enabling issue import in project settings).

## :grey_question: Possible Solution

A button that manually triggers issue import, e.g. _Check for new remote issues_ or _Sync now with remote issues_.

## :arrow_heading_up: Describe alternatives you've considered

- as described above: waiting for the automatic import or triggering manual import via re-enabling issue import in project settings
- new feature: when creating an issue from within Super Productivity it will also be added to GitLab and/or CalDav

**Comment by fkohrt** [comment]
I believe it is still relevant, but not urgent.

**Comment by fkohrt** [comment]
Same as before: I believe it is still relevant, but not urgent.

**Comment by fkohrt** [comment]
yes

**Comment by johannesjo** [comment]
PRs are welcome! I also would like to see this. Since UI space is limited, I picture a button inside the project context menu, a dialog after successfully configuring the issue integration for the first time or an additional button when the task list is empty.

**Comment by fkohrt** [comment]
still relevant

**Comment by RokeJulianLockhart** [comment]
> https://github.com/johannesjo/super-productivity/issues/2022#issuecomment-1868168427

@GitHub-Actions, reopen this issue. I was subscribed solely to issue closure.
