### ISSUE TITLE
Can someone please disable backgroundThrottling to prevent missed timers and notifications?

### ISSUE THREAD

**Issue by RationalFragile** [johannesjo/super-productivity#2028]
### Your Environment

- Version used: 7.10.1 (but probably all versions)
- Operating System and version: Windows 10 Pro (20H2)

### Expected Behavior
Get all notifications/sounds (idle, pomodoro, etc) in time.

### Current Behavior
Randomly, timers go into negative values and don't trigger notifications/sounds nor update the tray progress until you unminimize the window using the hotkey.
I think it might be because of `backgroundThrottling` mentioned in this stackoverflow answer: https://stackoverflow.com/a/59610324/12781687
I can't build the repo, so if someone could please add this to `electron/main-window.ts` for the next build, it would be great.
```
mainWindow = new BrowserWindow({
...
    webPreferences: {
...
        backgroundThrottling: false,
    },
});
```
From electron docs: 

> backgroundThrottling boolean (optional) - Whether to throttle animations and timers when the page becomes background. This also affects the [Page Visibility API](https://www.electronjs.org/docs/latest/api/browser-window#page-visibility). Defaults to true.

### Steps to Reproduce (for bugs)
1. Can't reproduce reliably, best chance is to let the timer run. And if you keep your ram full to 90% or so for a few minutes, you increase the chances of it staying unresponsive even after you no longer overload ram/cpu. (Kinda like chrome, so not sure this backgroundThrottling would totally fix it, but might help.)

**Comment by johannesjo** [comment]
Thanks for opening this up! I'll add this setting and it should be available for the next snap edge release (and for self compiled builds from the master branch). I hope there not to bad negative side effects (such as the increased resource usage), so feedback on this would be very welcome!

**Comment by RationalFragile** [comment]
Yes, this issue should be closed.
I couldn't wait 4 months for the release, so what I realized is that I can use the installer version of super productivity and then I would be able to extract the .asar and modify it directly; and that's what I did.

So I already tested it for a month or so and it solved the issue of missed timers. And didn't introduce any issues.
Anyway, thanks.

**Comment by RationalFragile** [comment]
Yes, this issue should be closed.
I couldn't wait 4 months for the release, so what I realized is that I can use the installer version of super productivity and then I would be able to extract the .asar and modify it directly; and that's what I did.

So I already tested it for a month or so and it solved the issue of missed timers. And didn't introduce any issues.
Anyway, thanks.
