### ISSUE TITLE
macOS title bar has no padding window controls and UI elements

### ISSUE THREAD

**Issue by mariobrostech** [johannesjo/super-productivity#2029]
### Your Environment

- Version used: v7.10.1, installed via Homebrew Cask
- Operating System and version: macOS 11.6.5 Big Sur

### Expected Behavior

I expected for there to be some padding between the macOS window controls and the rest of the UI elements, as per macOS design specifications. See the attached screenshot showing the padding in the stock Messages app as an example. There should be equal padding between the window borders and window controls.
<img width="322" alt="Screen Shot 2022-04-24 at 13 14 53" src="https://user-images.githubusercontent.com/17557442/164988406-c9d3c8e4-7621-4d84-98b6-2a923bd7402d.png">

### Current Behavior

The title bar doesn't contain any additional padding between the window controls and other UI elements. This doesn't conform to the macOS design specifications and makes the app look cluttered when compared to other native macOS apps. See the screenshot below, and compare it to the above screenshot to have an idea of what I mean.
<img width="322" alt="Screen Shot 2022-04-24 at 13 19 17" src="https://user-images.githubusercontent.com/17557442/164988432-29a1616f-8b71-406f-9d60-7417a17b974d.png">

### Steps to Reproduce (for bugs)

1. Install the superProductivity on a Mac running macOS 11 Big Sur or later.
2. Observe the mismatched spacing in the title bar when compared to other native and popular third-party apps.

### Console Output

This is not applicable, as this is purely a visual bug

**Comment by johannesjo** [comment]
Thanks for opening this up! PRs would be welcome for this!
