### ISSUE TITLE
Feature Add - Task Priority

### ISSUE THREAD

**Issue by Revulse** [johannesjo/super-productivity#203]
Would it be possible to add a way of selecting a priority for each task? Say each time you create a task, default priority is "Normal", then we can change to high or low and possibly add a slight color change overlaying the task within the task list. This would help understanding whats important at a glance.

For now I've basically created separate projects for low priority and high priority, but I'd rather not have to switch between projects to cycle through my tasks, I'd like to be able to view them all in one place with the different priority levels if possible. I know this sounds like a lot but it would be highly appreciated!

I would make an attempt to work on it myself but I'm not very fluent in programming.

**Comment by johannesjo** [comment]
Thanks for taking your time to open up this issue! There is currently a tag feature on the way #201. Maybe it could it could be used to fulfill the same the same purpose?

**Comment by Revulse** [comment]
Ahh yes, perfect.

**Comment by KonTy** [comment]
> Thanks for taking your time to open up this issue! There is currently a tag feature on the way #201. Maybe it could it could be used to fulfill the same the same purpose?

@Revulse Also you could just drag tasks up and down, that's what I do, the order is preserved and it is the best visual representation of priority since the most important item is at the top of your stack.

**Comment by lbtbs** [comment]
Tags and dragging are just workarounds – a proper priority feature listing tasks automatically is simply missing, and sorting tasks also by due date, created date... like e.g. Todoist has. AND kanban overview would be also nice.
