### ISSUE TITLE
Weird tray icon name

### ISSUE THREAD

**Issue by SepehrRasouli** [johannesjo/super-productivity#2032]
### Your Environment

- Version used: 7.11.5 .exe
- Operating System and version: Windows 10 64x

### Expected Behavior
I expected to see 'SuperProductivy' name or something like this, but what i only see is a string full of x
### Current Behavior
![Screenshot 2022-04-26 160200](https://user-images.githubusercontent.com/81516241/165290859-86fc3d4e-6e02-4a0c-bd53-ab9cc2a506b0.jpg)

### Steps to Reproduce (for bugs)
1. Start the app, make sure the app stays in the System Tray
2. Hover mouse pointer over SuperProductivity and wait a few seconds.

**Comment by johannesjo** [comment]
Thanks for opening this up! This should be fixed with the next release.
