### ISSUE TITLE
Snap superproductivity won't open despite clearing local data and recovering from google drive

### ISSUE THREAD

**Issue by robwithhair** [johannesjo/super-productivity#2033]
Restarted machine and superproductivity won't start.  Reinstalled and it opens but when I resync data from google drive it won't start again.

### Your Environment
Linux workstation-1 5.17.1-arch1-1 #1 SMP PREEMPT Mon, 28 Mar 2022 20:55:33 +0000 x86_64 GNU/Linux
using snap latest also tried edge branch
- Operating System and version: Arch updated daily
- Desktop Environment: KDE
- Browser Name and version: Not using web version

### Expected Behavior

Application launches

### Current Behavior

Application doesn't launch, no error.  No output when running from terminal.

### Steps to Reproduce (for bugs)

Only way I can think of is if I privately supply json config file.  Contains personal info so not able to post publically.

### Console Output

Won't start so no output
### Error Log (Desktop only)

no log generated

**Comment by hugaleno** [comment]
It maybe related with snapd bug
https://forum.snapcraft.io/t/certain-apps-wont-open/14929/21

The same problem happens to me and according to one of the posts on discussion above it may be related with symbolic links, which I have on my machine. On my friend's machine, that don't have symbolic links the problem doen'st occur.

**Comment by robwithhair** [comment]
There are no symlinks and installed from scratch.  It has been working fine for months, rather than failing on second launch.  It fails when my data is synced again.  Therefore must be related to data in the application.  Clean install has no problems.  Only way I can think to fix is to give a dev a copy of my data to identify what has corrupted or what character is messing it up etc.

**Comment by robwithhair** [comment]
Either way, some sort of error message should occur if it's a data issue, rather than a crash.  However oddly it works fine when I installed the Mac version and synced same file from google drive.

**Comment by robwithhair** [comment]
Was still experiencing issue so removed snap and installed arch version, which started ok.  Closing issue although not solved.
