### ISSUE TITLE
Enable to set start of day

### ISSUE THREAD

**Issue by zoli** [johannesjo/super-productivity#2035]
## Problem Statement
A calendar day is from 00:00:00 to 23:59:59 but a day for me is from for example 06:00:00 am to 02:00:00 am the next day until I go to sleep. But in super-productivity the day strictly ends at 23:59:59 and the timer, repeated tasks, etc gets restarted at that time. 
I want the 2 hour I work between 00:00 - 02:00 am on Thursday (by calendar) to get summed on the hours I worked on Wednesday not that part of it get to Thursday. I want If I have a repeated daily task That I managed to get it done on 01:00 am Thursday to again get added to my daily tasks on Thursday when I woke up Thursday morning.

## :grey_question: Possible Solution
My possible solution which I have got the idea from [Anki](https://apps.ankiweb.net/) is to have a setting which sets the time that a day starts for me and do the repeated tasks calculating daily time I work and etc based on that time.

**Comment by zoli** [comment]
BTW If this feature is acceptable I think I can my self work on it and make a pull request.

**Comment by zoli** [comment]
I'm working on this [here](https://github.com/zoli/super-productivity/tree/feat/2035-start-of-day) and I broke the issue to 3 steps:
1. The setting field
2. Recreating repeated tasks with due respect to start of next day setting
3. Calculating spent time with respect to start of next day setting
      - Sub task of 3 which is other time calculations in quick history, work log, etc

What I understand from what you said was about step 3:
> Time spent for tasks is only separated between dates (e.g. 10/10/2022: 2h, 10/11/2022: 1h), which should work in our favor, since we only have to adjust task.service.ts on line 197ff to also consider this setting.

After some digging I don't think just changing that line would resolve the issue. Because we (or at least I) want that the start of the day setting be respected on manually adding time spent for example in 00:30 am. I want to see my daily summary on maybe 1 am.  And changing just that line won't solve those I guess.
### getWorklogStr utility function
From what I understand `getWorklogStr` should change on near every place which its used without specific date param. My current idea is to add a `getWorklogStr` method on `work-context.service` which shifts the date n hours backward (regarding the start of day setting) and then passes the shifted date to `getWorklogStr` function (utility function).

Am I getting this right? Is there any better workaround?

**Comment by johannesjo** [comment]
`getWorkLogStr` is as you mention just an utility function, so I wouldn't put any application logic in it. But searching for its usages probably helps identifying most, if not all, areas that might need to be adjusted to consider the new setting (e.g. via modified getWorklogStr call as you suggest), which are:

* Daily Summary
* Simple Counters
* evaluation-sheet.component.ts
* idle.effects.ts
* The other metrics stuff
* Generally all time tracking related stuff (task, tags, project)

I am unsure about:
* The Jira and Open Project stuff (maybe easier to ignore it for now)
* global-time-tracking-interval.service.ts (we need to check for unwanted side effects)

Stuff that should be excluded is:
* repeating tasks (e.g. get-quick-settings-update.ts)
* dialog-time-estimate.component.ts


Not sure if there is a smarter way to do this, but I am afraid that this just _is_ a bit complicated...:)

**Comment by csamu** [comment]
I have the same problem.
My workday can range from 06:00 am to 03:00 am the next day.
But currently in Super Productivity, tasks statistics are split into two days if it goes beyond midnight.
I looked around but i couldn't find the settings.
