### ISSUE TITLE
'Confirm before exiting the app' does not work.

### ISSUE THREAD

**Issue by SepehrRasouli** [johannesjo/super-productivity#2036]
### Your Environment

- Version used: 7.11.5
- Operating System and version: Android 8.1.0
### Expected Behavior

Get prompted by a message to confirm exiting the app.

### Current Behavior

I don't get prompted by any kind of message.

### Steps to Reproduce (for bugs)
1. Go to super-productivity android app
2. Settings -> Misc Settings -> Check 'Confirm before exiting the app'
3. Try to exit the app, It will exit without any kind of confirmation.

**Comment by johannesjo** [comment]
Thanks for opening this up! This is currently not implemented for android (as it is not possible to do there).

**Comment by johannesjo** [comment]
Thanks for the suggestion. Does the app really close in the case? I think it just moves to the background?

**Comment by SepehrRasouli** [comment]
Yes, It does move to the background but sometimes when you're writing a task, you accidentally press the back button and it fully exists from the app. It would be really great if this problem gets solved.
