### ISSUE TITLE
Support Gitlab ToDo

### ISSUE THREAD

**Issue by viq** [johannesjo/super-productivity#2037]
## Problem Statement
Currently, to my understanding, only issues in projects on Gitlab get imported as tasks.
Gitlab also has ToDo category, where for example you can add Merge Requests to review. Currently those are not visible via the integration.

## :grey_question: Possible Solution

Import ToDo items as tasks.

## :arrow_heading_up: Describe alternatives you've considered

Alternatively, have an option to add MRs assigned and/or created as tasks.

**Comment by johannesjo** [comment]
Thanks for opening this up! PRs for this are welcome!

**Comment by Zeromika** [comment]
@johannesjo would you be open to a similar contribution for RSS feeds?

**Comment by johannesjo** [comment]
@Zeromika you mean an issue integration for RSS feeds?

**Comment by Zeromika** [comment]
> @Zeromika you mean an issue integration for RSS feeds?

Exactly, I am using this at work right now and have to do run a cron job that fetches the issues and inserts them to the local backup file and do a sync from there. With RSS feed if anyone has a similar workflow with me they should be able to quickly utilize without going through the approach I followed, as most issue trackers have a feed it will generalize super-productivity as well.

**Comment by johannesjo** [comment]
@Zeromika you can open up a separate issue you about this, if you like. Maybe someone picks it up. Personally I wouldn't need it.
