### ISSUE TITLE
"Write a comment" in Jira integration does nothing

### ISSUE THREAD

**Issue by viq** [johannesjo/super-productivity#2038]
### Your Environment

- Version used: 7.11.5 AppImage
- Operating System and version: Fedora 34
- Desktop Environment: i3
- Browser Name and version: Desktop App

### Expected Behavior

When clicking "Write a comment" button in a task integrated with Jira I expected either a text field to appear, or at least the issue to be opened in browser.

### Current Behavior

Nothing happens when clicking the button.

### Steps to Reproduce (for bugs)

1. Set up Jira integration
2. Add an issue with some comments as a task
3. Click "Write a comment" inside the app

### Console Output

There's no new output in Console when pressing the button.

### Error Log (Desktop only)

Logs from this application run, while trying to click the "Write a comment" button"
```
[2022-04-29 23:29:49.105] [info]  { enabled: null, showDevTools: false, mode: 'bottom' }
[2022-04-29 23:29:50.030] [info]  Saving backups to /home/user/.config/superProductivity/backups
[2022-04-29 23:29:52.711] [info]  No custom styles detected at /home/user/.config/superProductivity/styles.css
[2022-04-29 23:31:29.540] [info]  close, isQuiting: true
```

**Comment by viq** [comment]
Just to be clear, I don't mind it much, and having stuff synced from Jira is already nice :) But since there's a button, I assume it's expected to work, and I thought you might want to know that it doesn't ;)

**Comment by johannesjo** [comment]
Thanks for opening this up! Write a comment should usually open up the issue page in the browser. On Ubuntu this works fine, not sure why it doesn't on your machine...
