### ISSUE TITLE
Pomodoro settings, how do I add minutes, instead of hours?

### ISSUE THREAD

**Issue by TobiasDev** [johannesjo/super-productivity#204]
I have been trying to use the Pomodoro timer in the app, but I can't figure out how to set the work time to be 25min and short break 5min and long timer 15min. Whenever I try to write anything with minutes, or with 0 hours the line goes red and I can't save the settings.

Can anyone let me know what I'm doing wrong?

![image](https://user-images.githubusercontent.com/5912371/62948206-3e7bba80-bde4-11e9-991b-e11d4f006f24.png)

As you can see I have tried several different ways but the only one working is the full hour one.

**Comment by johannesjo** [comment]
Which version are you using?

**Comment by TobiasDev** [comment]
I believe latest: Super Productivity 2.10.6

**Comment by TobiasDev** [comment]
Seems to be fixed in 2.10.7. :)
