### ISSUE TITLE
website is offline for more than 24h

### ISSUE THREAD

**Issue by AndreaPravato** [johannesjo/super-productivity#205]
### Expected Behavior
http://super-productivity.com and app.super-productivity.com should have minimal downtime ideally

### Current Behavior
site and app are offline since 1-2 days ago

**Comment by johannesjo** [comment]
Thank you very much for letting me know. Seems like my webhoster messed up the server migration. :/ I'll look into it...

**Comment by johannesjo** [comment]
Should work again! Thanks once more!
