### ISSUE TITLE
Problem when repeating a taks

### ISSUE THREAD

**Issue by ronaldofas** [johannesjo/super-productivity#206]
The program crashes when i use the advanced option "repeat task"

Error:

"An error occurred
Please Report

Error: No component factory found for e. Did you add it to @NgModule.entryComponents?"

* Operating System and version: Windows 10

### Expected Behavior
Mark  the task to repeat over a number of times

### Current Behavior
The program crashes

### Steps to Reproduce (for bugs)
Create a task
Click on the tree dots button
Select the "Advanced" submenu
Select option "Repeat Task"

![superproductivity_error](https://user-images.githubusercontent.com/16448028/63180588-fa2b2d00-c024-11e9-99ad-6d665c928e0b.PNG)

**Comment by johannesjo** [comment]
Are you using one of the exe files to start the app, or are you using the store version?

**Comment by johannesjo** [comment]
Ok I think I found the issue. Thanks for reporting. Next release will be out shortly.

**Comment by johannesjo** [comment]
Release is out! Please let me know if the issue persists for you.
