### ISSUE TITLE
Can't launch an app

### ISSUE THREAD

**Issue by idopshik** [johannesjo/super-productivity#207]
### Your Environment

Version used: tried stable and edge. 
OS: Ubuntu 19.04 disco
Kernel: x86_64 Linux 5.0.0-25-generic
DE: XFCE
GTK Theme: Numix [GTK2]
Icon Theme: elementary-xfce-darker

### Current Behavior
When I choose superproductivity in launching menu - nothing happen.
if I try to launch it from console - got an error.

I've checked  /snap/superproductivity/337/ folder - there is no "data-dir" at all.
/usr/share/mime and /usr/share/mime-info -all files have read permission
And more strangely. I've got another pc with THE SAME DISTRO And after installing app there - got the same problem. And folder snap/superproductivity/337/ doesn't have "data folder" ether.
But on that other PC (it's actually a laptop) - different error. - Something like "GTK WARNING - cannot open display 0". 

### Console Output
Saving backups to /home/st/snap/superproductivity/337/.config/superProductivity/backups
{ enabled: null, showDevTools: false, mode: 'bottom' }

(superproductivity:1013): Gtk-WARNING **: 18:01:09.260: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /snap/superproductivity/337/data-dir/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)

### Error Log (Desktop only)
in folder ~/.config there is no superproductivity folder!

**Comment by johannesjo** [comment]
Thanks for reporting! I'll look into it tomorrow.

**Comment by johannesjo** [comment]
This might not be specific to superproductivity. Does this thread help by any chance:
https://www.reddit.com/r/voidlinux/comments/ayc03i/pixbuf_error_cant_open_gtk_applications_anymore/
?

**Comment by idopshik** [comment]
Bingo.
 I've searched and struggled hours before opening that issue. I knew the problem was in distro itself. 
The only strange thing was - all the other programs worked well. 
All these people trying to resolve "Could not load a pixbuf" or "Could not open display"- had problems with many other apps, not with only one. 
Anyway - problem tackled. Thx

**Comment by johannesjo** [comment]
Glad that you made it work!How did you fix your problem in the end?
