### ISSUE TITLE
Make fireworks on finish day page optional

### ISSUE THREAD

**Issue by wjadevries** [johannesjo/super-productivity#2073]
Hi, first of all: thanks for such a great simple (finally!) task and time manager!

But can you please make the  fireworks on the finish day page optional?
I know it's off when I disable animations, but I'd like to keep the smooth slide ins etc, but I hate the fireworks. It distracts me from the info on the page. 

Thanks!

BR, 

Wessel de Vries

**Comment by johannesjo** [comment]
Thanks for opening this up! PRs are welcome!
