### ISSUE TITLE
Sync shows no remote data while there is

### ISSUE THREAD

**Issue by wjadevries** [johannesjo/super-productivity#2075]
I opened the website on my iPad and got the message that there's no remote data, and if I wanted to upload from local.
There should be remote, but I pressed ok.
Now my stufff is gone. 

if I open the webpage saved to desktop on my iPad, I got the message:

Sync Warning: Dropbox date not up to date despite seemingly successful sync. (This might happen when: 1. You have conflict changes and decide to take the local version. 2. You open the other instance and also decide to use the local version.)

I synced to Google, not Dropbox. 
But the message remains after clicking ok.
And when I close the app (web to desktop) and reopen it, all's gone again.

**Comment by johannesjo** [comment]
Thanks for opening this up! Unfortunately I have no IPad available to fix this myself, so help with this would be welcome!
