### ISSUE TITLE
No remote data found. Upload local to Remote?

### ISSUE THREAD

**Issue by wjadevries** [johannesjo/super-productivity#2076]
On browsers (on my iPad and Samsung phone) I regularly get the message:

No remote data found. 
Upload local to Remote?

I use Google drive for syncing, and it worked a while (since installing on 3 devices this afternoon) but now I get this message every time I open the web page. 
I don't want to upload local, because my pc has synced the last time. 
what's wrong?

**Comment by Cyber-Syntax** [comment]
I get the same notification after waking my computer from suspend. I guess this is because the application cannot connect to webdav because it takes 10-30 seconds for the computer to connect to the internet after waking up from sleep.

**Comment by johannesjo** [comment]
@bencodesall you need to specify a file path rather than a folder. I understand that this is a bit confusing and that we should improve on that.

I am closing this since the original issue is about google drive, which is not supported any more.
