### ISSUE TITLE
sync doesn't work accross multiple devices

### ISSUE THREAD

**Issue by wjadevries** [johannesjo/super-productivity#2080]
I love the app, but sync just doesn't work.
I tried it with Google sync and Dropbox sync, but both always give the message that there's no remote file found and wants me to upload local to remote (from iPad or Samsung phone). 
When I do that and go to the app on another device (pc) I get the same message. 

All devices have been enabled for Google (or Dropbox which I also tried), but the message keeps appearing.
When I look into Google drive (or Dropbox), the json file is there. 
It looks like the app just doesn't see that. 

if this was solved I would be happy to donate, because I really love this.
But without it I can't plan my work properly when I'm not in the office.

**Comment by johannesjo** [comment]
Hi there! Thanks for opening this up! What devices are we talking about and how are you running the app (desktop? mobile? which OSs?) Do you maybe have multiple files with the same file name (also check the trash folder)? Might be that the app gets confused by that.
