### ISSUE TITLE
Screenshot at a specified time interval

### ISSUE THREAD

**Issue by keerah** [johannesjo/super-productivity#2088]
Hi and thanks for this great tool first
I would love if it could take screenshots at a specified time interval and save them into a specified folder while the tracking is in progress. 
Organizing screenshots into subfolder per project would be great.
I hope it's not too complicated feature, it can be useful not only for me personally.

**Comment by Dez1gner** [comment]
I'm interested in this feature as well

**Comment by johannesjo** [comment]
What is the use case? Not sure SP is the right tool for this :)
