### ISSUE TITLE
Time in app sync

### ISSUE THREAD

**Issue by 73794449** [johannesjo/super-productivity#2089]
## Problem Statement
The problem with synchronization when the time on different devices is "different". Linux and Windows have different principles for dealing with time, so I used one of the solutions to fix it. On Linux I have the correct time with the correct time zone, while on Windows I have the "correct time" but with the wrong time zone. For example, the correct time zone (UTC+2) and the time is 12:00. On Linux I have (UTC+2) and the time is 12:00, but on Windows I have (UTC+0) and the time is 12:00 too. So when I sync data from Windows to my phone (with the correct time and time zone), I get a message saying I'm syncing data from the future. Of course, this is not a big problem, but every time you click OK and force the synchronization is very annoying.

## :grey_question: Possible Solution
Manual time settings per device or force sync by default setting.

## :camera: Screenshot
![photo_2022-05-27_00-08-13](https://user-images.githubusercontent.com/54177174/170580722-877e2482-5742-4fed-aa17-0c6ba4d373ae.jpg)

**Comment by Nukiloco** [comment]
Is this still an issue with the modern versions of Super Productivity?

**Comment by johannesjo** [comment]
This can happen if you modify the timezone on your computer (effectively going to the past ;)). It's not really a bug, but we might offer the user a better way out, in case this happens.

**Comment by 73794449** [comment]
> This can happen if you modify the timezone on your computer (effectively going to the past ;)). It's not really a bug, but we might want offer the user a better way out, in case this happens.

Yes, I know that it is not something like bug, but when dualboot Windows-Linux, this is very distracting, on Linux I have correct time, on Windows incorrect timezone, but time is the same :) I solved it with syncing every time I boot to Windows or Linux(both with correct timezone), but syncing on Windows really don't fast and need internet connection.
