### ISSUE TITLE
Jira Settings are not repopulating

### ISSUE THREAD

**Issue by mwhobrey** [johannesjo/super-productivity#209]
### Your Environment
* Version used: 2.10.8 - Setup.exe
* Operating System and version: Windows 10 v. 1903 b. 18956.1000

### Expected Behavior
After enabling and entering in the Jira connection and query settings, they should be editable in the future and Jira should remain enabled.

### Current Behavior
Jira becomes disabled after leaving the settings screen. It is important to note that Jira continues to function even though the settings show it as disabled and there is no way to alter the JQL for issues.

### Steps to Reproduce (for bugs)
1. Enable Jira
2. Setup connection information
3. Save Jira settings
4. Go to project main page
5. Return to Settings
6. Click on Jira
7. Notice that Jira has again been turned off

### Console Output
No errors or relevant logs. All console output looked normal.
```javascript
{
  isAutoLogin: false
  isAutoSyncToRemote: false
  isCompressData: true
  isEnabled: false
  isLoadRemoteDataOnStartup: false
  isNotifyOnSync: false
  syncFileName: "SUPER_PRODUCTIVITY_SYNC.json"
  syncInterval: 60000 
  _backupDocId: null
  _lastSync: null
  __proto__: Object
}
```

### Error Log (Desktop only)
[log.log](https://github.com/johannesjo/super-productivity/files/3516766/log.log)

**Comment by johannesjo** [comment]
Thank you very much for reporting. I'm debugging right now. Definitely some weird behavior. Meanwhile you should be able to display the settings again, by selecting your current project from the project switcher menu again.

**Comment by johannesjo** [comment]
I think I fixed it. Will publish a patch release soon.

**Comment by johannesjo** [comment]
Release should be out now.
