### ISSUE TITLE
Menu bar icon does not update when automatically changing theme on MacOS 

### ISSUE THREAD

**Issue by 1ncend1ary** [johannesjo/super-productivity#2094]
### Your Environment

- Version used: 7.11.5 dmg
- Operating System and version: OSX 10.15.7
- Desktop Environment: –
- Browser Name and version: –

### Expected Behavior

See Steps to Reproduce.

### Current Behavior

See Steps to Reproduce.

### Steps to Reproduce (for bugs)

1. Select appearance: Auto under General settings 

<img width="426" alt="изображение" src="https://user-images.githubusercontent.com/45948348/171338412-90b9b1ae-b167-4a0f-b948-22bcfb1eb0ea.png">

2. Launch SuperProductivity

3. The menubar icon colors are as expected: black on white, white on black. 

<img width="79" alt="изображение" src="https://user-images.githubusercontent.com/45948348/171338789-6a01fe41-6b2c-4b4f-836d-b3a9241d7c63.png">
<img width="331" alt="изображение" src="https://user-images.githubusercontent.com/45948348/171338600-14ad1324-6aa5-43cd-8972-3e9af3239946.png">

4. Wait for theme to automatically change with time or change it manually under General settings (light to dark and vice versa)

5. The icon's color does not change, it turns to black on black. The text color, however, changes fine.

<img width="83" alt="изображение" src="https://user-images.githubusercontent.com/45948348/171338883-8546bc23-4fe5-44b6-9f65-b4d4307cf734.png">

This is how it looks without selection:
<img width="82" alt="изображение" src="https://user-images.githubusercontent.com/45948348/171339388-3ad26b2b-d4c4-4703-b446-018891783a8b.png">

<img width="323" alt="изображение" src="https://user-images.githubusercontent.com/45948348/171339035-2d2d6e82-5eba-44cf-80f1-1b4115efdfd4.png">

6. Close and open SuperProductivity
7. It works as expected
<img width="323" alt="изображение" src="https://user-images.githubusercontent.com/45948348/171339181-060db6c1-ebc8-4b47-ad52-8e41663e2baf.png">

### Console Output

–

### Error Log (Desktop only)

–

**Comment by johannesjo** [comment]
Thanks for opening this up! PRs are welcome!
