### ISSUE TITLE
Global link does not validate URL for user

### ISSUE THREAD

**Issue by maqp** [johannesjo/super-productivity#21]
**Version affected:** 1.3.4 (.deb)
**OS:** Ubuntu 17.10 (probably all)
**Current result:** Using identifier such as "google.com" does not work when clicking created link
**Expected result:** Application resolves missing "https://" or informs user the URL is invalid.

**Comment by johannesjo** [comment]
I added the feature. Now it should prepend `http://` to the url if not a valid url.
