### ISSUE TITLE
Error: Cannot load model. Version to load is newer than local (7.11.5)

### ISSUE THREAD

**Issue by aguscaba** [johannesjo/super-productivity#2105]
### Steps to Reproduce

I opened the android app, it got updated, after that i closed from phone and opened on pc (synchronization enabled) and it threw the mentioned error

1. Have SP 7.11.5.0 installed on windows with synchronization enabled and auto backup
2. Open the Android App from phone.
3. Accept the update request from phone (at the end of the update it was on 7.11.5).
4. Start working from phone, add some tasks and have them done
5. Exit the app from phone to start working from windows
6. Open the Windows SP App
7. Get the error: "Cannot load model. Version to load is newer than local. Please close the app and update your local productivity version first, before importing the data" which continues appearing.
![2022-06-02 09_33_07-Super Productivity](https://user-images.githubusercontent.com/67975/171654302-1720e78f-4ce0-4e61-a43e-04575df07f87.jpg)

### Stacktrace
```
Error: Cannot load model. Version to load is newer than local
    at _n (file:///C:/Users/FRCABALL/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0b14eb60dae60b557008.js:1:1333263)
    at zd (file:///C:/Users/FRCABALL/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0b14eb60dae60b557008.js:1:1510343)
    at file:///C:/Users/FRCABALL/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0b14eb60dae60b557008.js:1:1512207
    at file:///C:/Users/FRCABALL/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0b14eb60dae60b557008.js:1:184167
    at file:///C:/Users/FRCABALL/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0b14eb60dae60b557008.js:1:173718
    at file:///C:/Users/FRCABALL/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0b14eb60dae60b557008.js:1:172885
    at file:///C:/Users/FRCABALL/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0b14eb60dae60b557008.js:1:3627428
    at file:///C:/Users/FRCABALL/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0b14eb60dae60b557008.js:1:3625808
    at file:///C:/Users/FRCABALL/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0b14eb60dae60b557008.js:1:173172
    at o.X [as accumulator] (file:///C:/Users/FRCABALL/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0b14eb60dae60b557008.js:1:175383)
```

### Meta Info
META: SP7.6.0 Electron – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.6.0 Chrome/91.0.4472.124 Electron/13.1.7 Safari/537.36

### Actions Before Error
```
1654126479794: [Tag] Update Work End for Tag 
1654126479798: [Persistence] Save to DB (3) 
1654126480783: [Task] Add time spent 
1654126480785: [Project] Update Work End 
1654126480791: [Tag] Update Work End for Tag 
1654126480796: [Persistence] Save to DB (3) 
1654126481782: [Task] Add time spent 
1654126481785: [Project] Update Work End 
1654126481789: [Tag] Update Work End for Tag 
1654126481793: [Persistence] Save to DB (3) 
1654126482782: [Task] Add time spent 
1654126482783: [Project] Update Work End 
1654126482790: [Tag] Update Work End for Tag 
1654126482796: [Persistence] Save to DB (3) 
1654126483784: [Task] Add time spent 
1654126483787: [Project] Update Work End 
1654126483799: [Tag] Update Work End for Tag 
1654126483811: [Persistence] Save to DB (3) 
1654126484209: [Task] SetSelectedTask 
1654126484218: [Task] UnsetCurrentTask 
1654126484219: [Pomodoro] Pause Pomodoro 
1654126486717: [Task] Move to archive 
1654126486727: [Persistence] Save to DB (3) 
1654126486727: [Task] UnsetCurrentTask 
1654126486728: [Pomodoro] Pause Pomodoro 
1654126486781: [Persistence] Save to DB 
1654179534168: [SP_ALL] Load(import) all data 
1654179534174: [SP_ALL] All Data was loaded 
1654179535873: [Persistence] Save to DB (17) 
1654179535995: [SP_ALL] Load(import) all data
```

**Comment by aguscaba** [comment]
> Hm this is very odd! Could you maybe provide a data export (from the mobile app)? It might be that for some reason a bit of your data got into an invalid state that I didn't account for and that I can't reproduce. It would be great if you could share a copy of your data to [contact@super-productivity.com](mailto:contact@super-productivity.com), so I can debug this on my computer. You can create an export by navigating to "Settings" and then to "Import/Export" or you can use the "Export data" button from the error Dialog (there is also a button there which will anonymize the data before exporting).

Hey johannesjo thank you very much for taking time on it, I have a question please, from phone I cannot see the "Export data" button but from windows I cannot do anything because the mentioned error message is shown above all, I cannot get rid of it as it keeps appearing.

Could you please help me to get the data?

**Comment by johannesjo** [comment]
Hm that's weird. It should be there. You need to open the menu first (the burger icon on the top left), then you need to select "Settings" on the bottom left and then you need to scroll down to "Sync & Export", where you need to expand "Import/Export". There you should find the "Export Data" button.

**Comment by aguscaba** [comment]
> Hm that's weird. It should be there. You need to open the menu first (the burger icon on the top left), then you need to select "Settings" on the bottom left and then you need to scroll down to "Sync & Export", where you need to expand "Import/Export". There you should find the "Export Data" button.

In android the button doesn't seems to be there.
![Screenshot_20220603-132555_Super Productivity](https://user-images.githubusercontent.com/67975/171925429-5a2c5f79-903c-49fd-8962-2b405afa12d3.jpg)

**Comment by aguscaba** [comment]
> Hm that's weird. It should be there. You need to open the menu first (the burger icon on the top left), then you need to select "Settings" on the bottom left and then you need to scroll down to "Sync & Export", where you need to expand "Import/Export". There you should find the "Export Data" button.

Also @johannesjo is there any way to anonymize the Json file so that I can share it with you?

I got stuck only being able to use it from phone (but I usually try to let it away so I don't get distracted :( )

**Comment by johannesjo** [comment]
Hey @aguscaba ! I am very sorry, I got confused. Actually data export is currently disabled for the android version, since it is not working (it just wasn't for my mobiles android version, which was an older one).

You might be able to access the data directly from your sync providers file system. From there you might be able to import it again in the webapp (https://app.super-productivity.com) from where you can use the privacy data export  (which obfuscates all private data). In case importing and exporting works from the webapp, you might also be able to import that data in your windows app.

**Comment by aguscaba** [comment]
Hi, now I was able to export by deleting the local files within windows appdata folder and trying to resync, got below error:
![2022-06-20 12_18_29-Super Productivity](https://user-images.githubusercontent.com/67975/174651948-1117c8e0-1b8a-42c9-a08b-1aab0a11404c.jpg)

With below error:

```
Error: Cannot load model. Version to load is newer than local
_n (webpack:///src/app/util/model-version.ts:20:12)isMigrateModel (webpack:///src/app/features/project/migrate-projects-state.util.ts:19:7)migrateProjectState (webpack:///src/app/features/project/store/project.reducer.ts:82:8)function (webpack:///node_modules/@ngrx/store/fesm2015/ngrx-store.js:1358:25)createFeatureReducerFactory (webpack:///node_modules/@ngrx/store/fesm2015/ngrx-store.js:290:19)combination (webpack:///node_modules/@ngrx/store/fesm2015/ngrx-store.js:245:44)reducer (webpack:///src/app/root-store/meta/action-logger.reducer.ts:14:11)reducer (webpack:///src/app/root-store/meta/undo-task-delete.meta-reducer.ts:128:11)Array.isArray (webpack:///node_modules/@ngrx/store/fesm2015/ngrx-store.js:278:19)reduceState (webpack:///node_modules/@ngrx/store/fesm2015/ngrx-store.js:435:20)
```

Also clicked on the export data button from the above image ![2022-06-20 12_18_29-Super Productivity](https://user-images.githubusercontent.com/67975/174651948-1117c8e0-1b8a-42c9-a08b-1aab0a11404c.jpg), and sent the exported json to contact@super-productivity.com, I hope you can help, again thank you very much for your help.

**Comment by johannesjo** [comment]
Sorry for the very late reply. I was away and then on vacation and did not find any time to work on the project in between. Just checked my mails, but I was unable to find yours. Could you send it again to me by any chance?

**Comment by johannesjo** [comment]
Thank you! Unfortunately I am unable to reproduce the issue. Do you encounter this every time? Could you maybe try to import the file you send me or to export and then re-import the data again. The model versions  from your file (or a new export) should work no problem with the current SP version 7.11.5.
