### ISSUE TITLE
Keyboard Shortcuts Documentation

### ISSUE THREAD

**Issue by kylejrp** [johannesjo/super-productivity#211]
I love this software so far - great work!

I'm having difficulties finding the keyboard shortcuts. Are these documented anywhere? Is there any way to discover these shortcuts in the interface?

**Comment by kylejrp** [comment]
Hah, of course I find the shortcuts immediately after posting the issue. Sorry - didn't realize that they were in the settings!
![image](https://user-images.githubusercontent.com/6742479/64271281-e8d19400-cef1-11e9-8ce0-1ce878a35cbf.png)

**Comment by johannesjo** [comment]
No worries. I'm closing this. Let me know if you have any improvement suggestions!
