### ISSUE TITLE
App preventing logout or shutdown

### ISSUE THREAD

**Issue by kaibrune** [johannesjo/super-productivity#2110]
### Discussed in https://github.com/johannesjo/super-productivity/discussions/2083

<div type='discussions-op-text'>

<sup>Originally posted by **kaibrune** May 20, 2022</sup>
Hi togehter,
another thing I noticed is that the app hinders the shutdown or logout process on macOS Catalina and above. Somehow the system is not able to force quit the app, so the shutdown or logout process is not able to proceed. But weirdly there is no error from macOS which shows that one app is preventing the shutdown. Any else noticed this problem? Solution is to force quit the app via CMD+Q manually, then the shutdown or logout is working fine.</div>

**Comment by kaibrune** [comment]
![shutdown_blocker](https://user-images.githubusercontent.com/33369042/183888420-a68763f2-48d9-4837-8823-dc01e92a1519.png)

**Comment by sm8ps** [comment]
I have recently picked up SuperProductivity as my main tool for time tracking and I do love it. However, I have had several cases of unresponsive shutdown procedures. This time I could track it down a bit and realized that indeed SuperProductivity is the cause of this. The console (Dmesg?) reads:
```
[169448.585724] systemd-shutdown[1]: Waiting for process: 4981 (superproducti)
[169528.586039] systemd-shutdown[1]: Sending SIGKILL to remaining processes...
[169528.591399] systemd-shutdown[1]: Sending SIGKILL to PID 4981 (superproducti).
[169538.593322] systemd-shutdown[1]: Waiting for process: 4981 (superproducti)
```
Presumably, this cycles but I did not wait long enough but forcefully shut the machine down.

This all happens with SuperProductivity 7.13.2 installed from the Snap store on Kubuntu 23.04 and Linux kernel 6.2.0-27-generic. Let me know if I can help with troubleshooting in any ways. And many thanks @johannesjo for this great app!

**Comment by johannesjo** [comment]
Thanks for the input @sm8ps ! These things are hard to debug and I suspect this has not much to do with the app code itself, but with electron. Hopefully an update there will help.

**Comment by sm8ps** [comment]
Thank you for the quick response and the insight, @johannesjo! Say, do I need to get active myself as a user in order to upgrade electron or is this taken care of by the SuperProductivity app itself? I have no(de) idea of the whole JS-ecosystem.

**Comment by johannesjo** [comment]
No, there is nothing to be done on your behalf. I will make a new release with a new electron version soon. Hopefully this will fix it.

**Comment by sm8ps** [comment]
Great! I am looking forward to a new version and shall report on my tests about this issue here.
