### ISSUE TITLE
Suggestion - Distracting Website/App Blocker

### ISSUE THREAD

**Issue by jjackson107** [johannesjo/super-productivity#2113]
Hello,
I'd like to see an option built into Super Productivity to block a set list of websites or applications from being run for a user-defined period of time. This would probably be its own section under the "Productivity Helpers," but should also integrate into the Pomodoro Timer too (ex. "Block websites in your distraction list while there is an active Pomodoro timer"). Maybe there could also be some difficulty added to get around the block, like a confirmation window or preventing the window from being closed.

Some examples of apps I use are SelfControl, HyperFocus, or 1Focus (for MacOS).

Thanks for reading!

**Comment by johannesjo** [comment]
I think this is beyond the scope of the core app. A plugin might work for this though.
