### ISSUE TITLE
Adding it to AUR?

### ISSUE THREAD

**Issue by tiotrom** [johannesjo/super-productivity#212]
I was curious if you plan to add it to AUR. Cheers!

**Comment by johannesjo** [comment]
Hey there! Thanks for opening up this issue. 

To be honest, I have no experience with publishing to AUR and Deployment to PPA was a really huge pain in the *** while only a few people using it. So I'm open but a little hesitant.

Installing the snap package is not a valid option for you?

**Comment by tiotrom** [comment]
I use Arch...but please leave this open and I will try to help out with it ;) - I see you have an appimage version which should be quite easy to transform into AUR. We did so for Jitsi-Meet recently like so https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=jitsi-meet-electron

**Comment by johannesjo** [comment]
It would be great having the app available for arch without me having to care about it!! :D

I'll try to have a look at #213 tomorrow.

**Comment by tiotrom** [comment]
Ok I think it is already added... https://aur.archlinux.org/packages/superproductivity - interesting that I could not find it. It si great to see that!

**Comment by johannesjo** [comment]
Ah yes, now I remember. @Morganamilo maintains that (thanks again btw! :)).
 
Last update was quite a while ago though. Maybe there is a possibility to automate this somehow.

**Comment by tiotrom** [comment]
There is another version, git, https://aur.archlinux.org/packages/superproductivity-git - probably it takes the latest build from git, right? That's more automated as far as I understand.

**Comment by tiotrom** [comment]
Unfortunately none of the versions work....I reported them to their respective AUR pages...

**Comment by johannesjo** [comment]
Thank you!

Let's give @Morganamilo some time to respond. It might be better to work on an automated solution (travis is already configured) for the releases.

**Comment by johannesjo** [comment]
@tiotrom it seems like @Morganamilo is not responding. I've not experience with AUR whatsover. Would you maybe help me to prepare publishing my own package? The other 2 are not up to date and I really would like to automate the process.

**Comment by tiotrom** [comment]
Unfortunately I cannot :( - I don't have the technical ability to do it nor the time. I am very sorry...

**Comment by zajca** [comment]
Hi there is guide for publishing packages to aur https://wiki.archlinux.org/index.php/AUR_submission_guidelines
in the end it's just git repository.

Here is simple PKGBUILD file which I created. It will use deb package release. I did not try depends since I have lot of stuff in my PC and did not time to test this (it works on my computer, you know :D ).
```
pkgname=super-productivity
pkgver=2.13.14
pkgrel=1
pkgdesc='To Do List / Time Tracker with Jira Integration.'
arch=('x86_64')
url="http://super-productivity.com/"
license=('MIT')
# depends=('gtk2' 'libxss' 'gconf' 'nss' 'nspr' 'libnotify' 'libappindicator'
#     'libxtst' 'alsa-lib' 'xprintidle')
source=("${pkgname}_${pkgver}.tar.gz::https://github.com/johannesjo/super-productivity/releases/download/v${pkgver}/superProductivity_${pkgver}_amd64.deb")
md5sums=('6c1ab24314f250efaf3e6514d66eecd7')

package() {
    msg2 "Extracting the data.tar.xz..."
    bsdtar -xf data.tar.xz -C "$pkgdir/"
    mkdir "${pkgdir}"/usr/bin
    ln -s "${pkgdir}"/opt/superProductivity/superproductivity "${pkgdir}"/usr/bin/
    chmod +x "${pkgdir}"/usr/bin/superproductivity
}

```

**Comment by tiotrom** [comment]
@zajca Nice. Would you be able to post it to AUR?

**Comment by johannesjo** [comment]
Thank you @zajca. I look into it once I have a little bit more time on my hands (Makes sense to include this directly into the build process). Probably next weekend or so.

**Comment by johannesjo** [comment]
Wow I am already pretty annoyed by this. I can't get past their ridiculous captcha, because apparently my output from `LC_ALL=C pacman -V|sed -r 's#[0-9]+#fca#g'|md5sum|cut -c1-6` is not what they expect, most likely due to the output of `pacman -V` being different from what they expect.

**Comment by jackhistoria** [comment]
Maybe there are more people on Arch than you expect when this works since pacman and the AUR are real timesavers :) 
```
:: Proceed with installation? [Y/n] 
:: Retrieving packages...
error: failed retrieving file 'yarn-1.21.0-1-any.pkg.tar.xz' from mirror.neostrada.nl : The requested URL returned error: 404
error: failed retrieving file 'yarn-1.21.0-1-any.pkg.tar.xz' from ftp.snt.utwente.nl : The requested URL returned error: 404
error: failed retrieving file 'yarn-1.21.0-1-any.pkg.tar.xz' from ftp.nluug.nl : The requested URL returned error: 404
error: failed retrieving file 'yarn-1.21.0-1-any.pkg.tar.xz' from mirror.koddos.net : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (failed to retrieve some files)
Errors occurred, no packages were upgraded.
Error installing repo packages
```
I have the talent to bite through problems like this and succeed most of the time and since I would like to use this app in 2020 a lot along with arch at home and on my cloud server and would like to try and figure it out for you - else I would put a new AUR rep up and merge it afterwards - but that doesn't seem necessary. Let me know what you think and happy new year btw.

**Comment by jvalecillos** [comment]
I have updated the packages in **AUR** fixing the build for both of them:

https://aur.archlinux.org/packages/superproductivity/
https://aur.archlinux.org/packages/superproductivity-git/

But install the latest version (or the git version in the case of the later).

Go and be productive! :smile:

**Comment by johannesjo** [comment]
@jvalecillos that's great! Thank you very much!

**Comment by tiotrom** [comment]
Thank you sir! Much appreciated!

**Comment by madjoe** [comment]
> I have updated the packages in **AUR** fixing the build for both of them:
> 
> https://aur.archlinux.org/packages/superproductivity/
> https://aur.archlinux.org/packages/superproductivity-git/

@jvalecillos : Thanks for the contribution. Unfortunately, there's still an error whilst installing any of the packages from AUR:
https://hastebin.com/edinohujeb.coffeescript

**Comment by jvalecillos** [comment]
Thanks for the heads up @madjoe 

The issue happened because Arch uses the latest version of Electron and that was incompatible with the version `5.1.2` of the app. I have updated/fixed both packages now and bumped to the latest version (`5.4.2`). It should be fine now.

**Comment by johannesjo** [comment]
@jvalecillos oh alright. Should I give you a heads up when I am updating electron in the future?

**Comment by madjoe** [comment]
@jvalecillos: Thanks, it works now! :)

@johannesjo: Great app, I really like the overall look and feel of it.

**Comment by jvalecillos** [comment]
> @jvalecillos oh alright. Should I give you a heads up when I am updating electron in the future?

Only if you want, people can report issues in AUR website. I could have used the Electron version declared in the `package.json` and download it during build time, but I decided to use the one from the system (Arch) to speed up the build.

I'm subscribing to the notifications for releases so I can follow up. I think you can close the issue now @johannesjo.

**Comment by johannesjo** [comment]
@jvalecillos alright. Thank you for actively maintaining the AUR package! I appreciate it!
