### ISSUE TITLE
An option to add multiple timers with the pomodoro option

### ISSUE THREAD

**Issue by arrobeselias** [johannesjo/super-productivity#2121]
Hi, I'm reposting a feature request I made last year, I'm still struggling with this and it will totally change the game for me

I use Superproductivity mainly for study. It's an awsome way to keep track of the subjects I done and what is left. Also spliting the study hours for topics
When studying I like to go for 2h each topic. Then I choose a subject and start. So my flow is:

1. I read a book and annotate for 1h
2. Then I like to take a test for 30 minutes solving questions
3. Then I proceed to create anki cards for the subject (30 minutes)

I like to do anki reviews outside the hours studies, but I go for 20 minutes each topic (100 minutes)

So my problem is that despite superproductivity helped me a lot in my studies and procrastination issues I still have problems to split effectively the tasks and the time I want to work on them

### MY SUGGESTION

I think its a improvement the option to add multiple start buttons with different time so everyone set the best amount of time... Not sure if I'm the only that has this problem but some tasks gets me tired very fast than others. That's why I think would be great to have something like this

![Group 97](https://user-images.githubusercontent.com/93867154/173808286-cd76c60a-07cd-4a91-9688-fcce2e46b2d5.png)

**Comment by ximemira** [comment]
I could use that feature ! 👍
