### ISSUE TITLE
Not starting in Manjaro Gnome

### ISSUE THREAD

**Issue by tiotrom** [johannesjo/super-productivity#213]
I get this error:
```

[tio@tio-pc ~]$ '/home/tio/Applications/superProductivity-2.10.12_00000000000000000000000000000000.AppImage' 
qt5ct: using qt5ct plugin
[32566:0905/115242.858294:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_superPf4J36l/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)

```

**Comment by johannesjo** [comment]
Thanks for reporting. I will try updating electron. Hopefully that will fix the issue.

**Comment by KonTy** [comment]
I don't think updating to new electron will solve the problem though. This Linux distro is more restricted and the sandbox needs root privileges, Debian has the same issue AFAIK.

@tiotrom have you tried this?

<code>
sudo chown root chrome-sandbox

chmod 4755 chrome-sandbox
</code>

I think we need to do this, if we wanted to solve it for SuperProductivity and solve it during install
https://wiki.archlinux.org/index.php/Linux_Containers#Enable_support_to_run_unprivileged_containers_(optional)

**Comment by tiotrom** [comment]
It works now. Manjaro got a big update and now I see that it works....I know for example that they updated the electron to 6.0.7-1, though appimages should be self contained. In any case, it works now....interesting...

**Comment by johannesjo** [comment]
I'm closing this. Please let me know if you encounter any other issues.
