### ISSUE TITLE
Tooltips on windows desktop app.

### ISSUE THREAD

**Issue by WilliamDormer** [johannesjo/super-productivity#2130]
## Problem Statement

When trying to perform certain actions on the application (specifically the windows desktop, but I think this is universal) you cannot tell sometimes what the icon means. For example, when looking at the notes section, there is an icon of a sun. I have no clue what that does. There is no tooltip, and no confirmation when pressed as to what it does. This is a consistent pattern over multiple parts of the app as far as I can tell. 

## :grey_question: Possible Solution

A simple solution would be to have tooltips that indicate what it does when you hover over it. Alternatively, you could have some sort of toast message telling you what changed after toggling the icon. 

No further context is needed.

**Comment by WilliamDormer** [comment]
Now that I look further, it seems like this may be isolated to that particular spot in the program. But still needs a fix. (I also understand that the sun means add to your day lol)

**Comment by bytrangle** [comment]
@WilliamDormer Which icon of the app is not accompanied by text or tooltips? I couldn't find any, nor can I find a sun icon. But I'm using Mac version so not sure if that makes a difference.

**Comment by WilliamDormer** [comment]
Idk how else to describe it. In the notes section, there is the sun icon, and when you hover there is no tooltip. I think there is a good chance it is platform specific, but since it was a while ago I don't remember which platform I encountered this error on. Probably windows, but it could have been mac.
