### ISSUE TITLE
On task complete fill the spent time

### ISSUE THREAD

**Issue by zoli** [johannesjo/super-productivity#2133]
## Problem Statement
Personally I have some tasks that I won't track the time while doing it (e.g walking or running daily), But on creation of the task I made an evaluation that how much it will take. Currently when I'm marking the task as done If I want the time I spent on the task to count I should manually add the spent time.
I would like some sort of feature that it automatically adds the estimated time to the spent time on marking task as complete.

## :grey_question: Possible Solution
A checkbox option on the task to add the estimated time to spent time on marking it as complete

## :heavy_plus_sign: Additional context
This would specially suit (at least for me) for repeated daily or weekly routine tasks. Like running, reading, etc

P.S. I can and would like to implement this myself.

**Comment by johannesjo** [comment]
Thanks for the suggestion! That's a nice idea! Could you explain to me how the flow would look like? Is this a general option or is it just something for just special tasks?

**Comment by zoli** [comment]
> Could you explain to me how the flow would look like? Is this a general option or is it just something for just special tasks?

If we want to keep it simple, I Think it would be good to place it on task repeat config as a checkbox for example. Because we don't have specific task config currently and also I think the pain of adding the spent time manually is mostly for repeated tasks (at least for me it is) not for other single tasks.

**Comment by johannesjo** [comment]
Makes sense to me! Let's do it like this! PRs are welcome for this!

**Comment by zoli** [comment]
Relevant.

**Comment by zoli** [comment]
Relevant.
