### ISSUE TITLE
Feature Requestion: Please add an option "NEVER" to the  "**_remind at_**" section 

### ISSUE THREAD

**Issue by meximan** [johannesjo/super-productivity#2142]
How can I turn off reminders so I am not redirected to the app constantly (which breaks my focus on current tasks)?

I've already looked through the settings and turned off what I thought would fix this, but haven't figured it out. 

Possible Solution / Feature Requesti:
Please add an option "NEVER" to the  "**_remind at_**" section  so that I don't get these reminders while still being able to keep track of what time I usually start doing tasks. (The approximations help a lot and they don't need to be perfect for me.)

The current options are "when it starts, 5 minutes before it starts, 10 minutes.. 15 minutes.. 30 minutes.. 1 hour.." These aren't suitable for me and I'm sure other people feel the same way. Thank you for the one-of-a-kind, intuitive product!

**Comment by johannesjo** [comment]
Thanks for opening this up! Are we talking about the task schedule dialog that opens if you click "Schedule Task"? You can remove a reminder for these tasks by clicking on the little clock icon next to it and then in the dialog you click on the midle icon where there is a crossed out alarm clock. This should remove the reminder.

**Comment by bytrangle** [comment]
![schedule-task-dialog](https://user-images.githubusercontent.com/28924121/184100620-4575fc78-a811-41f2-bf5c-3153cd86e282.png)

Where is the little clock icon in the Schedule Task dialogue?

Anyway, it is not obvious how to remove the reminder. I think It would be helpful to add a "Don't remind option" to the dropdown list for "Remind at".

![remind-drop-down](https://user-images.githubusercontent.com/28924121/184101050-16c08357-65ed-42b5-b7b8-60ec32ac1326.png)
