### ISSUE TITLE
(bug) Forms with formly without translate

### ISSUE THREAD

**Issue by dennistobar** [johannesjo/super-productivity#215]
I've tried to apply the new translated strings into the dialogs, but formly doesn't applies the translated strings. 
As I see, the export of items in `project-forms-cfg.const.ts` exports the key of json strings but in `dialog-create-project.*` don't apply the translation.

* Version used: from sources, master commit
* Operating System and version: Fedora 30 and web version

### Expected Behavior
If I set the language other than English, the new project dialog and Theme setting would be translated into the new language

### Current Behavior
The dialogs aren't translated

### Steps to Reproduce (for bugs)
1. Set other language than English (in my case, Spanish)
2. Click on Settings (_Ajustes_ in Spanish)
3. See the Theme settings (see attached files)
![Captura de pantalla de 2019-09-11 09-59-16](https://user-images.githubusercontent.com/1218182/64699520-5134ee00-d47b-11e9-95ae-d0556150bf89.png)
![Captura de pantalla de 2019-09-11 09-59-10](https://user-images.githubusercontent.com/1218182/64699522-5134ee00-d47b-11e9-9c63-a0c0ae255546.png)

**Comment by johannesjo** [comment]
Thanks for reporting. I'll check this!

**Comment by johannesjo** [comment]
Ah ok. That's I haven't made a release yet. Your translations should be there with the next one

**Comment by johannesjo** [comment]
The next release will be out in a bit. You can download it from the edge channel:
```
sudo snap install --channel=beta superproductivity
```

**Comment by dennistobar** [comment]
mmmm.... I didn't see the changes in the current commit history on master (HEAD) about this issue. I don't tell about the translated string in #214, this issue is about the modal: the strings are translated in `es.json` but formly is not rendering them.

Anyway, I'll try to see the new changes on Monday.

Regards!

**Comment by johannesjo** [comment]
Yes. The translations were missing there. I added them. Now they should appear.

**Comment by dennistobar** [comment]
Thanks :)
