### ISSUE TITLE
Add the ability to make a new line on the task items

### ISSUE THREAD

**Issue by Nukiloco** [johannesjo/super-productivity#2151]
## Problem Statement

Currently for each of the items and sub items in my project. There seems to be no way for me to add in a new line to add a new line to the text of the tasks. So my task text currently wraps around.

## :grey_question: Possible Solution

A possible solution is to allow people to make a new line by using ``Shift + Enter``.

## :arrow_heading_up: Describe alternatives you've considered

None

## :heavy_plus_sign: Additional context

None

**Comment by johannesjo** [comment]
Hi there! This is intentional, but I leave this open for discussion in case others need this as well.

**Comment by rsmyst** [comment]
Personally, I don't particularly see the need in my use case for multi line tasks since i could just text wrap long tasks. 
But i can see how multiple lines would make the task itself look much more organized and easy to digest.
