### ISSUE TITLE
"Done on" date display in task description

### ISSUE THREAD

**Issue by Bbillyben** [johannesjo/super-productivity#2155]
## Problem Statement

The date where a task is marked as done is not displayed anywhere. 
It would be a great added value for the project follow up!

## :grey_question: Possible Solution

The information is available in the json in task description, input `"doneOn":'timestamps'`

It could be displayed in task description under "created on".

let me know if you need any more information.

**Comment by bytrangle** [comment]
Hi @Bbillyben , just want to confirm how I can get the JSOn for the task description? The only way I know is to export, which will generate a JSON file which contains the field `"doneOn": <timestamp>"`

**Comment by Bbillyben** [comment]
Hi @bytrangle 

I don't have any knwoledge about super-prod app, I've just open the exported json. 
But if the info is written in the json it should be available in the db (if there is any db...).

Anyway, if you can look into this I would be very grateful, I needed to find that date again today!
