### ISSUE TITLE
Configuration not carried over after update

### ISSUE THREAD

**Issue by kirawrath** [johannesjo/super-productivity#217]
Hello,
I have opened today superproductivity, to notice it has a new layout (thus I figured it was updated), however all my tasks, configs and everything else was gone.

I have reverted to the previous version, and now it is working as before, however now I can't export the configuration, due to an error that seems related to the rollback (thus, there are two bugs reported in this ticket).

### My Environment

* Version used: 2.10.12 to 2.12.3 (snap)
* Operating System and version: Ubuntu 16.04.6 LTS
* Desktop Environment: unity

### Steps to Reproduce (for bugs)
1. Create some tasks.
2. (maybe) finish the day to save your configs.
3. Close the app.
4. Update from 2.10.12 to 2.12.3 through snap.
5. Open it again.

I didn't try to reproduce myself, and the application was updated in the background without my interference, so maybe the steps are not exactly those.

### Rollback
```
$ snap list
Name               Version                     Rev   Tracking  Publisher   Notes
superproductivity  2.12.3                      388   stable    johannesjo  -
$ sudo snap revert superproductivity 
superproductivity reverted to 2.10.12
```
After reverting, this is the error I get in the terminal when running `superproductity`, and clicking the `Export Data` button. Seeing it referring to the revision `388` and `352` makes me think the rollback was not very successful (it should refer only to the `352` revision I suppose).
```
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /snap/superproductivity/352/gnome-platform/usr/share/icons/Humanity/status/16/image-missing.svg: Unable to load image-loading module: /snap/superproductivity/388/gnome-platform/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /snap/superproductivity/388/gnome-platform/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: cannot open shared object file: No such file or directory (gdk-pixbuf-error-quark, 5)
```

### Error Log (Desktop only)

```
$ find snap/superproductivity/ -name log.log
<nothing>
```

**Comment by kirawrath** [comment]
As for my issue, I am happy with just keep using the older version for the foreseeable future, I am a bit too busy to fix this at the moment. Thus I am not in need for assistance regarding this matter, I just wanted to report my issue so you can look into it if you wish, but you can also close it for all I care.

**Comment by johannesjo** [comment]
Alright then. Data loss is the worst case. Should never happen! Sorry for the trouble. If you run into this again and can share some insights later on it would be very much appreciated.

**Comment by kirawrath** [comment]
Hello Johannes,
snap is not allowing me to keep reverting to an older version, now I am forced to migrate my data.
I have tried your steps (which was essentially running `~/snap/superproductivity$ cp -r ./352/.config/superProductivity/backups 424/.config/superProductivity/`, however nothing changed.

I do have the backup files, and the data there seems fine, however I can't make the new version to read that. Any tips?

**Comment by johannesjo** [comment]
You should be able to import the backup file under settings Import/Export. This should normally work.

**Comment by kirawrath** [comment]
In my earlier comments I mentioned that this feature got broken with the update, the applications crashes when I hit Import or Export.

**Comment by johannesjo** [comment]
I would try the following:
1. backup complete `~/.config/superProductivity` folder just in case
2. Keep the most recent file from  `~/.config/superProductivity/backups` at hand
3. Delete app completely (including `~/.config/superProductivity`) and do a fresh install
4. Try to use the import functionality again with the most recent backup
5. If this fails try one of the earlier ones

If all of this doesn't work, it should at least throw some sort of error.

**Comment by kirawrath** [comment]
I followed your steps and now it works!
Maybe the trick was to copy the whole `superProductivity` rather than just the backup folder.
Thanks.

**Comment by johannesjo** [comment]
Glad that it works now!
