### ISSUE TITLE
Set focus mode on windows 10/11

### ISSUE THREAD

**Issue by nicola-lunghi** [johannesjo/super-productivity#2170]
Windows 10/11 has a focus mode.
Would be great if sp can set it automatically when working on a task and unset it on break

Thanks for this amazing software!!!!!

**Comment by johannesjo** [comment]
Pull Requests are welcome for this!

**Comment by nicola-lunghi** [comment]
Apparently is not documented
I found this
https://github.com/bitdisaster/windows-focus-assist
@riverar can you help?

**Comment by riverar** [comment]
@nicola-lunghi How can I help? What do you need me to do?

**Comment by bytrangle** [comment]
@nicola-lunghi Is there a module we can use to set Focus Assist in Windows? The module you gave seems to only read the status of Focus Assist.

**Comment by nicola-lunghi** [comment]
I've sent an email to @riverar waiting for a response on this :-) I'll keep you posted.
The current API seems only to be able to query the focus state.

**Comment by riverar** [comment]
`IQuietHoursSettings` has a property setting function entitled `ActiveQuietMomentProfile` that takes in a profile ID and should allow you to turn various profiles on/off. (https://withinrafael.com/2019/09/19/determine-if-your-app-is-in-a-focus-assist-profiles-priority-list/)

**Comment by Susexe** [comment]
@riverar @nicola-lunghi 

Hi, is Windows Focus / Do Not Disturb integration technically possible now? Windows seems to provide a `FocusSessionManager` API with `IsFocusActive`, `IsSupported`, `IsFocusActiveChanged`, `TryStartFocusSession()`, and `DeactivateFocus()`.
