### ISSUE TITLE
Mac binaries for version 2.12.3

### ISSUE THREAD

**Issue by suschizu** [johannesjo/super-productivity#218]
hey @johannesjo! Will there also be a .zip or .dmg download available for version 2.12.3?
Thanks :)

**Comment by johannesjo** [comment]
Thank you very much for pointing this out. They somehow got lost in the build process. Will check this later this evening.

**Comment by johannesjo** [comment]
Done! Thanks for the reminder!

**Comment by suschizu** [comment]
Great thanks!

I noticed another small thing: 

In the README -> Download & Install -> MacOS

homebrew-install: your casks name is superproductivity (no Uppercase)

So it should be this way:

brew cask install superproductivity

And your cask is well maintained :)

Best regards,

Brigitte
 

Designer & Developer @ CoreCode
CoreCode Ltd. | https://www.corecode.io/
Reg.#: C 78581 | VAT#: MT23896136
Villa Gauci, Mdina Rd., BZN 9031, Malta

**Comment by johannesjo** [comment]
Good catch! Thank you!

Thanks for the cask goes to @LouisStAmour. Wouldn't have thought about it myself :)
