### ISSUE TITLE
Do not display "Completed Tasks" / SLOW

### ISSUE THREAD

**Issue by guitarzero** [johannesjo/super-productivity#2192]
Hi
Thank you very much for this great project i have been using for about 2 years
I have now a lot of "completed tasks" and they make Super Productivy run VERY SLOWLY. I cannot use it anymore. I can try deleting "completed tasks" manually but it will take me ages.
Is it possible to hide these "completed tasks"
Is there a one-click button to remove all completed tasks ? 
Thanks

**Comment by johannesjo** [comment]
Hey there! There is not, but I am open to adding one (with double confirmation required). For now you can manually edit the export by removing everything from `taskArchive` so that it looks like this:
```
"taskArchive":{"ids":[],"entities":{},"currentTaskId":null,"selectedTaskId":null,"taskAdditionalInfoTargetPanel":"Default","lastCurrentTaskId":null,"isDataLoaded":false,"__modelVersion":3.3337}
```
