### ISSUE TITLE
[Feature] Allow reviewing distractions during break

### ISSUE THREAD

**Issue by maqp** [johannesjo/super-productivity#22]
More often than not, a distraction is something that only takes a few minutes to check. Could you add a checkbox to "What's distracting you" prompt, that when checked, displays the distraction during breaks?

**Comment by johannesjo** [comment]
Hey there! That's a neat idea! I like it! I'm not sure how to be sure that someone is really on break. Do you have any ideas?

**Comment by maqp** [comment]
Would having all the tasks paused constitute as a break? Also, if you're willing to integrate something like a pomodoro timer that has short and long breaks, having options to choose whether to display the distraction on short or long break would be really helpful.

**Comment by srihari93** [comment]
@maqp @johannesjo How can I view the saved distractions? I can use the button to add them. But, don't see how I can get back to them.

**Comment by johannesjo** [comment]
@srihari93 Distractions are currently shown at the daily summary (when you click "finish your work dy" on the work view).

**Comment by srihari93** [comment]
@johannesjo I see them now. Thank you.

**Comment by johannesjo** [comment]
I'll delay this feature until we have a pomodoro timer (#32). Without it, it is a little hard to determine if somebody is on a break.

**Comment by johannesjo** [comment]
The feature is available now, so I'm closing this.

**Comment by maqp** [comment]
Superb work! Thank you for all your effort!
