### ISSUE TITLE
Improved exporting for time keeping

### ISSUE THREAD

**Issue by 13hannes11** [johannesjo/super-productivity#2203]
## Problem Statement

I use the tool for exporting into a time reporting tool. I would like to be able to export a task where I have subtask and task as different columns.

I would like my exports to look like this

```
Date;Worked;Project Name;Task;Subtask;
2022-08-08;03:00;Project A;Testing;UI;
2022-08-08;02:00;Project A;Testing;Unit;
2022-08-08;03:00;Project B;Admin;Timesheet;

```

**Comment by johannesjo** [comment]
Thanks for opening this up! I am open for adding this as another option!
