### ISSUE TITLE
Request to Expand clickable area on a task to focus it

### ISSUE THREAD

**Issue by rsmyst** [johannesjo/super-productivity#2208]
## Problem Statement
Hello, this application is very nicely made but i have a few gripes. 
First of all, i would love if i can select a task without actually going into the renaming field. 
Often times, the focus in the application is taken away from the task when i click settings or some other menu button. To bring focus back to the task and use keyboard shortcuts on it, i am currently forced to click a very narrow border around each task. Otherwise it just triggers the rename field. 

## :grey_question: Possible Solution
An easy solution for this would be to make it so that clicking the leftmost part of a task i.e. , the reorder button, brings back focus to the task without going into renaming. Currently, clicking the button immediately enters the task into reordering mode without checking if the used it actually moving their cursor or not. 

## Some additional pictures:
An Unfocused task
![image](https://user-images.githubusercontent.com/30620767/186479578-2c71336f-4456-4c1b-92ea-6f98f6bc9aa2.png)

Result of Clicking even the empty space on the task name field. 
![image](https://user-images.githubusercontent.com/30620767/186480079-004dcc69-eb1b-45ce-a31b-fa7aaf085cc4.png)
It goes into renaming. maybe you can reduce the region where rename is triggered to a bit more than the task names' lengths. 

The blue regions mark the areas where i can click into to focus task than doing some other action. 
![image](https://user-images.githubusercontent.com/30620767/186479819-4fc82c75-2ff0-4b55-99be-bca248d13075.png)

fyi, the actual regions are a bit smaller because i couldn't draw thinner borders with my mouse haha. hope it was easy to understand.

**Comment by johannesjo** [comment]
Thanks for opening this up! Great suggestion! I am all for changing this up!

**Comment by johannesjo** [comment]
Thanks @davidzcode ! Let me know, if you have any questions! Ideally we solve this without any additional markup, because of the performance impact when there are many tasks. Also important to consider is how it looks when editing single line text, multiline text and in different screen sizes or a task with no text at all.

**Comment by davidzcode** [comment]
Hello guys, I have been working on it, and finally I decide to use the solution of @rsmyst and use reorder button for trigger focus.
What do you think?

https://user-images.githubusercontent.com/32526223/197330929-7ffed7a6-0100-43f7-b920-1418d488f3cf.mp4

**Comment by rsmyst** [comment]
> Hello guys, I have been working on it, and finally I decide to use the solution of @rsmyst and use reorder button for trigger focus. What do you think?
> 8dee0ba05ca325865f7c0db98b4d068d.mp4

Looks perfect. exactly how i imagined it. Just in case it was missed though, the reorder button disappears when the task is active AND cursor is being hovered over it. I assume you have taken that into consideration as well? Like when a task is active, there's a Play button in the place of reorder button. When hovering over this active task, the play button disappears. so I assume the click reorder area to focus will activate then?

**Comment by davidzcode** [comment]
I think is no problem, I have only noticed the play button disappear when cursor is hover it.

https://user-images.githubusercontent.com/32526223/197332632-f68a2b56-76bc-48a9-91a0-f31b524b637a.mp4

**Comment by johannesjo** [comment]
> I think is no problem, I have only noticed the play button disappear when cursor is hover it.

This should be fixed (PRs are  welcome)! Thanks for your input on this!

**Comment by rsmyst** [comment]
> > I think is no problem, I have only noticed the play button disappear when cursor is hover it.
> 
> This should be fixed (PRs are welcome)! Thanks for your input on this!

No I think this current way it works is just fine. i.e. i believe it should disappear on hovering over the active task. 
Thanks to @davidzcode for the fix. looking forward to the update.
