### ISSUE TITLE
Request for Natural Language Processing during task scheduling

### ISSUE THREAD

**Issue by rsmyst** [johannesjo/super-productivity#2209]
## Problem:
Currently, user is forced to:
1. Make task
2. Right click task
3. Click schedule
4. Schedule Task

It would be incredibly convinient if super productivity added a feature in the syntax of tasks during creation that allowed users to set due dates (scheduling) within the same line. Todoist does something very much like this and honestly probably saved me hours and hours of time. 
<html><body>

What you type: | What Todoist understands:
-- | --
today | Today (tod also works)
tomorrow | Tomorrow (tom also works)
next week | The next Monday by default (this can be changed in your Settings)
next month | 1st day of the next month
jan 27 | Jan 27 (27 jan, 27/1 also works)
01/27/2016 | January 27, 2016 (27/01/2016, 2016/01/27, 2016-01-27 also work)
27th | 27th day of the current month
mid January | January 15th
end of month | Last day of the current month
today at 10 | Today at 10am
tomorrow at 16:00 | Tomorrow at 4pm
Fri @ 7pm | Friday at 7pm (Friday @ 7pm, Fri at 7pm, Fri at 19:00 also work)
6pm | Today at 6pm (unless 6pm has passed, in which case tomorrow)
in 5 days | 5 days from today (+5 days also works)
in 3 weeks | 3 weeks from today
in 2 hours | 2 hours from now

</body>
</html>

I saw a similar issue raised a few years back but the issue auto closed before gaining traction. I hope this isn't too hard to implement. cheers,
if it wasn't clear by any chance, this is the thing i'm talking about. 
![image](https://user-images.githubusercontent.com/30620767/186482266-406c5c1f-5baa-4d13-a44f-170a3f294b3b.png)

This is how todoist has implemented it
![image](https://user-images.githubusercontent.com/30620767/186482675-a3b6f46d-91fa-4318-bd0f-4bf9de2507d0.png)

**Comment by johannesjo** [comment]
I am all for improving this, but probably won't find the time to dig into the subject myself.

**Comment by j0ma** [comment]
Just chiming in here as a Ph.D. student working on NLP and a new user of `super-productivity`: there are definitely date parsers out there (e.g. [alvinwan/timefhuman](https://github.com/alvinwan/timefhuman)), so it might not be necessary to implement this logic from scratch. Not aware of any libraries in TypeScript though 🫤

**Comment by bytrangle** [comment]
@j0ma I don't know much about NLP, but what do you think about this [date parser](https://github.com/wanasit/chrono) in Typescript?

**Comment by j0ma** [comment]
Interesting find! Seems like the [feature set](https://github.com/wanasit/chrono/blob/master/README.md) is pretty close to what OP wanted:
```
It is designed to handle most date/time format and extract information from any given text:

    Today, Tomorrow, Yesterday, Last Friday, etc
    17 August 2013 - 19 August 2013
    This Friday from 13:00 - 16.00
    5 days ago
    2 weeks from now
    Sat Aug 17 2013 18:40:39 GMT+0900 (JST)
    2014-11-30T08:15:30-05:30
```

Can't really say anything informative about integrating it to this project, but 1.2k stars and 10 years of development history (first commit in 2012!) certainly make it look promising.

**Comment by bobchao** [comment]
related issue: #1476

**Comment by rsmyst** [comment]
relevant. 
if it helps, 
relevant links:
https://todoist.com/help/articles/enabledisable-smart-date-recognition

https://www.ocpsoft.org/prettytime/nlp/ (date parser as well, was linked in NLP of a particular android task management app)
oh and MLKit

**Comment by johannesjo** [comment]
> Any updates? this is the only thing keeping me from switching over to super prod

This has been partly implemented. Further improvements are welcome of course.

**Comment by docnoe** [comment]
Hi, is there any documentation about which words are supported already
Thanks!

**Comment by johannesjo** [comment]
@docnoe currently there are no releases to the apple store since it takes a lot of effort and there are only a couple of downloads there each month anyway.
