### ISSUE TITLE
QA: Can this be proxied?

### ISSUE THREAD

**Issue by gerroon** [johannesjo/super-productivity#221]
Hi

 I am thinking to run the Docker version then  proxy it via Apache. is it possible?

**Comment by johannesjo** [comment]
Probably :) not much experience in this field. 

May I ask for the reason? It's just a static wep page in the end.

**Comment by gerroon** [comment]
I would like to access it from outside while password protecting it with Http auth.

**Comment by johannesjo** [comment]
Unfortunately this wouldn't be of much use. All data is stored client side and not saved to any server. You can set up syncing via google drive, but password protecting your data is not possible atm. This might be definitely something we should add in the future but for the time being my efforts are more focussed on the desktop version of the app. I am very open about suggestions though.

**Comment by gerroon** [comment]
Hi

I realize the client side storage. The reason I want to host it because so that it does not need to be installed. Some companies do not allow software installation. 

Ideally it would have been so nice if this  was a truely a self hosted application with some kind of backend database.

**Comment by johannesjo** [comment]
Yes I agree. It would be nice to have the option. It's definitely on the agenda to rework how the model is saved into much smaller chunks. If we got this, it should be possible to provide rest adapter of some sort. I'm a little afraid of reworking the model, as it is probably a lot of work and will likelybreak a lot of things. Has been on my to do list for quite some time now and I will likely do it at some point.

**Comment by KonTy** [comment]
> I'm a little afraid of reworking the model, as it is probably a lot of work and will likelybreak a lot of things. 

Haha a good reason to bump a major version of the app.
