### ISSUE TITLE
Words became an array of squares?

### ISSUE THREAD

**Issue by andresantacruz** [johannesjo/super-productivity#2216]
![image](https://user-images.githubusercontent.com/18551142/187808551-2ff4f58f-5378-48dd-9603-246d38aefc1f.png)

Installed the app some hours ago but didn't use it yet and in that occasion simply closed the app by the tray icon. Now, some hours later, tried to open the app to start using it and faced with the screen above. 

- Version used: Don't know the exact version, but just installed it via snapd.
- Operating System and version: Fedora 36
- Desktop Environment: Gnome 42
- Browser Name and version: Google Chrome (don't know the version)

### Expected Behavior

Expected to display English words in the app.

### Current Behavior

Words seems to become long squares.

### Can you reproduce this reliably?

No I don't think so.

### Console Output

![image](https://user-images.githubusercontent.com/18551142/187809321-ba9ac583-d1d3-4746-b2dd-37f62f2adeb7.png)

**Comment by ACalleros** [comment]
Any updates on this? I have the same problems

**Comment by johannesjo** [comment]
I am still unable to reproduce this, so not from side...

**Comment by hugaleno** [comment]
I pretty sure this is a snap problem. I had the same problem with postman and other apps installed using snap.
https://forum.snapcraft.io/t/snaps-show-squares-instead-of-fonts/18073/5
