### ISSUE TITLE
Detailed Log

### ISSUE THREAD

**Issue by colonwq1** [johannesjo/super-productivity#2223]
Hi,

first of all: I like using super-productivity very well.
For planning / logging my work it would help if I can see when I started / paused the timer for a project.
If it would be available in the reports / exports of the worklog would be very nice and enough for my need.

Hopefully it will be integrated to super-productivity. :)

Many thanks in advance.

Kind regards

**Comment by F3mic** [comment]
Hi,
I have the same thoughts.
It's much needed.
Regards
