### ISSUE TITLE
Webdav sync sync username and overwrites in a multi-device/user setup

### ISSUE THREAD

**Issue by lerra** [johannesjo/super-productivity#2238]
### Your Environment
Ubuntu 22.04 / Linux and latest version of the snap package
two android devices running android 12 and latest version of the app
Syncing towards a webdav server with separate usernames
### Expected Behavior
Syncing between should work and not touch username fields for sync, sync settings should be local settings.

### Current Behavior
When having user1,user2,user3 setup using webdav, username is included in the superproductivity json file and is loaded into superproductivity and overwrites the username value

### Steps to Reproduce (for bugs)

1. User1 syncs the file to webdav server
2. user2/3 syncs the file, user 2/3 gets the username1 value overwriten in sync settings (but not the password).
3. User2/3 syncs but gets an error from webdav server because the user1 have the wrong password.

### Can you reproduce this reliably?

Yes

### Console Output

No

**Comment by johannesjo** [comment]
Not sure this is a bug, since the app is intended to be used by the same user. I agree however that it would be better for these settings not be synced.

**Comment by lerra** [comment]
To give some background, it is the same user but i have device accounts
with different access in webdav but if that is the case and it will not get
fixed I will create a separate account only for super productivity. As long
as I know what you decide:)

It's been an annoying problem for three months that i finally figured out
the root cause:)

Big thanks for the project you built!

**Comment by johannesjo** [comment]
To be honest: I likely won't work on this myself anytime soon. But in case someone comes along with a PR, I promise to review and merge it as quickly as I can.
