### ISSUE TITLE
heating issue on ubuntu 22.04

### ISSUE THREAD

**Issue by Nidhin-mohan** [johannesjo/super-productivity#2241]
I am on ubuntu 22.04. after installing the app version system heating up

**Comment by johannesjo** [comment]
This could be caused by something completely unrelated. Are you sure this is caused by the app?What is shown on the System Monitor app if you only start this app and nothing else? Is there a high CPU usage indicated?

**Comment by Nidhin-mohan** [comment]
I removed the app  ,now using the  web app and  it's now working  fine I couldn't find any other issue . Let me check this once more today.
