### ISSUE TITLE
Task scheduled for tomorrow. When opening the Schedule dialogue, "Later Today" is highlighted.

### ISSUE THREAD

**Issue by bytrangle** [johannesjo/super-productivity#2247]
### Your Environment

- Version used:  7.11.5
- Operating System and version: macOS Montery version 12.5
- Desktop Environment:  N/A
- Browser Name and version:  N/A

### Expected Behavior

When scheduled a task for anytime after today, then open the Schedule dialogue again, Later Today shouldn't be highlighted.

### Current Behavior

Later Today is highlighted. This is confusing for users because they may be not sure if the scheduled time has been saved.

### Steps to Reproduce (for bugs)

1. Add a new task
2. Schedule it for tomorrow, at 10 am. Click the Schedule button to confirm it.
3. Hover over the task and click the icon "Edit Reminder".
4. In the popup, Later Today is highlighted.

In the example below, I expect the Tomorrow tab to be highlighted.

![task-scheduled-for-tomorrow-later-today-highlighted](https://user-images.githubusercontent.com/28924121/191061443-8182df42-201a-4d87-9aa6-e3736dda4a6a.gif)

### Can you reproduce this reliably?

Yes

**Comment by jaypey** [comment]
I can take this one!

**Comment by jaypey** [comment]
I believe this issue could be closed.
