### ISSUE TITLE
Jira: URL/link created/opened for inline links is wrong

### ISSUE THREAD

**Issue by rklec** [johannesjo/super-productivity#2257]
### Your Environment

- Version used: 7.12.0
- Operating System and version: Windows 10
- Browser Name and version: N/A

### Steps to Reproduce (for bugs)

Create a link of any kind in Jira.

Then click on that link in SuperProductvity (here click on "TEST-1031"):

![grafik](https://user-images.githubusercontent.com/71322635/192485701-647cb1cd-0678-4718-a13f-6a56a4321c3a.png)

### Expected Behavior

It should open https://[jira-host]browse/TEST-1031

### Current Behavior

If I click on TEST-1031 it redirects me to https://[jira-host]/browse/39819 instead of what is also written there, i.e. the correct URL https://[jira-host]browse/TEST-1031.

For some reason the other ways opening an issue seem to work, i.e.:
* the link at "summary" above works
* the context menu: "Open link in .... [text too long in German]" works.
* also the comment button works and redirects to the comment URL

### Can you reproduce this reliably?

Yes.

### Console Output
nothing related, only stuff like "Save to DB"

I searched for 39819 and TEST-1031 and could find nothing related.

### Error Log (Desktop only)

nothing related in logs

**Comment by rklec** [comment]
It is relevant, it is a bug after all...

**Comment by rklec** [comment]
Can this be reopened?`It is not fixed AFAIK. @johannesjo

**Comment by rklec** [comment]
Huh this is relevant? Unless it is fixed..

**Comment by johannesjo** [comment]
@rklec Not sure. I never was able to reproduce this myself... :/
