### ISSUE TITLE
Enabling Google Drive Sync gives me an error

### ISSUE THREAD

**Issue by Heart1010** [johannesjo/super-productivity#226]
### Your Environment

* Version used: Web App
* Operating System and version: Win10
* Desktop Environment: 
* Browser Name and version: Latest Chrome

### Expected Behavior
I've just found Super Productivity - great work!
When I want to use it in my browser there is no login. So this only works on that computer, correct?
But if I want to be able to see my tasks at work pc and at home pc how should I do it?
I thought I enable Googly Drive Sync but when I do this I get the followin error message
![image](https://user-images.githubusercontent.com/1481680/65872785-b34d8880-e381-11e9-8a19-c9751858c76b.png)

### Steps to Reproduce (for bugs)

1. Enable the switch to google drive sync
2. Click on my user/icon

**Comment by KonTy** [comment]
@johannesjo this brings up a good point have you been able to update the Windows Store app. I didn't get any Update notifications for the App since version 2.10.5 I believe from May 31st.

**Comment by johannesjo** [comment]
@Heart1010 I have a look at this. Thank you very much for reporting! Google changed some of their policies, so that's probably the reason why this appears.

**Comment by Heart1010** [comment]
@KonTy I tried it with the Web app, correct. There no google sync is possible (error above). Now I installed the github win setup exe and here I can enable Google Sync 👍 
_(Last version in Windows Store here is also the old may release)_

![image](https://user-images.githubusercontent.com/1481680/66021201-1b1ee300-e4ea-11e9-978c-06771c1e179d.png)

**Comment by KonTy** [comment]
> @KonTy I tried it with the Web app, correct. There no google sync is possible (error above). Now I installed the github win setup exe and here I can enable Google Sync 👍

Awesome I'm glad it worked just don't use the web app if possible, regular normal app gives you so much more freedom and more stable since more people are testing/using it.

**Comment by johannesjo** [comment]
The error message is unrelated to the web app this case. The error should be gone now.

**Comment by johannesjo** [comment]
Super vielen Dank. Ich habe die Nachricht angepasst. Das mit dem "Invalid Date" sollte nach einmaligem Update nicht mehr auftauchen.

**Comment by johannesjo** [comment]
Should be fixed I think.
