### ISSUE TITLE
Superproductivity for wear os

### ISSUE THREAD

**Issue by ximemira** [johannesjo/super-productivity#2263]
I’m a ux designer and researcher concerned with interoperability and privacy, so I use your app in on all my devices.
I got a smartwatch running wear os 2 and thought it’d be great if it too could sync with the app. I cannot imagine how complex this might be to implement. 
The use case : 

1. Use the phone / computer to create tasks and set the today list
2. Use the smartwatch for handling the pomodoro timer : to choose the task to work on then start, pause or stop it. 

Example : this app is similar to superproductivity, the screens of the watch show better the usecase :  https://play.google.com/store/apps/details?id=com.superelement.pomodoro&hl=en_CA&gl=US
![image](https://user-images.githubusercontent.com/37844004/192825078-fcdc3800-075c-47ac-9a07-7255b0bade08.png)

Thanks, cheers !

**Comment by therajat08** [comment]
Much needed feature

**Comment by ffcruz85** [comment]
I wish I could help on this one, it would be major for me

**Comment by dariaGirl** [comment]
Damn, if this could come to fitbit devices that'd be sweet.

**Comment by wokawoka** [comment]
That's the only thing I miss on this already great app
