### ISSUE TITLE
StartUp - DB INIT Error

### ISSUE THREAD

**Issue by elchinorris** [johannesjo/super-productivity#2265]
### Your Environment

- Version used: **Super Productivity 7.12.0**
- Operating System and version: **Windows 10 Pro**
- Desktop Environment:  **Windows Desktop**
- Browser Name and version:  **Desktop App**

### Expected Behavior

**The app had information and Tasks from two projects and between 100/200 tasks, most of them had been close.
At startup have to show all these data.**

### Current Behavior

**Error at Start Up with a notification message --- "DB INIT Error" and the app is empty without data , projects, tasks.....like a new installation.**

### Steps to Reproduce (for bugs)

1. L**aunch the app and these error occurs all the time.**

### Can you reproduce this reliably?
Always

### Error Log (Desktop only)

![DB-INIT-Error](https://user-images.githubusercontent.com/58030273/193214776-bdefb6ba-0832-430a-8a30-5c0908870302.png)

**Comment by savlakaran** [comment]
I faced the same issue on Linux after upgrading from 7.7 to 7.12. What worked for me was clearing the IndexedDB directory from the app's config directory (After backing up your data). Then on boot, restore your backup.

**Comment by gillesB** [comment]
*The following might be confusing as I wrote it down while trying out the different versions (MS Store, direct download). The horizontal lines mark a short leap in time.*

I am not sure if it is exactly the same error, but I get the same error message, after I installed (7.12.1) from the MS Store.
I am a non-admin user on a Windows 10 Enterprise.

---

After downloading and starting the .exe directly from the release page, the program starts as expected.

As I am a new user, I can not yet judge if everything works as expected. But at least I can see a background image on the direct download version.
Whereas the background of the MS Store version is black.

---

Well, it was black, if I start the MS Store version now. It shows the following exception.
![image](https://user-images.githubusercontent.com/1679281/215092877-d7e757ea-57a0-41b8-a272-d9241c2ffa37.png)

---

I restored the backup and now I can start the downloaded .exe and the MS Store version without an exception.

**Comment by x3rAx** [comment]
I had the same problem and I was able to "solve" it by renaming the folder where the settings are saved and then importing the latest automatic backup:

### On Linux

1. Go to your config directory:
   ```
   cd ~/.config
   ```

2. Rename the original settings folder:
   ```
   mv superProductivity superProductivity.bak
   ````

3. Create a new settings folder:
   ```
   mkdir superProductivity
   ```

4. Copy backups from old to new settings folder
   ```
   cp -ra superProductivity.bak/backups/ superProductivity/
   ```

5. Now start SuperProductivity and click "OK" in the popup that asks to restore the latest backup.


### On Windows (wild guess :wink:)

I guess the settings are located at `%appdata%/superProductivity/`.

1. Open an Explorer and type `%appdata%` in the location bar
2. Rename the `superProductivity` folder to `superProductivity.bak`
3. Create a new `superProductivity` folder
4. Copy the `backups` folder from the old to the new settings folder
5. Now start SuperProductivity and click "OK" in the popup that asks to restore the latest backup.

**Comment by x3rAx** [comment]
I had the same problem and I was able to "solve" it by renaming the folder where the settings are saved and then importing the latest automatic backup:

### On Linux

1. Go to your config directory:
   ```
   cd ~/.config
   ```

2. Rename the original settings folder:
   ```
   mv superProductivity superProductivity.bak
   ````

3. Create a new settings folder:
   ```
   mkdir superProductivity
   ```

4. Copy backups from old to new settings folder
   ```
   cp -ra superProductivity.bak/backups/ superProductivity/
   ```

5. Now start SuperProductivity and click "OK" in the popup that asks to restore the latest backup.


### On Windows (wild guess :wink:)

I guess the settings are located at `%appdata%/superProductivity/`.

1. Open an Explorer and type `%appdata%` in the location bar
2. Rename the `superProductivity` folder to `superProductivity.bak`
3. Create a new `superProductivity` folder
4. Copy the `backups` folder from the old to the new settings folder
5. Now start SuperProductivity and click "OK" in the popup that asks to restore the latest backup.

**Comment by gillesB** [comment]
@x3rAx Your Windows steps worked for me, except that I had to uninstall the MS Store Version first.
Unfortunately I did not do that after I reported my case on 27.01.

**Comment by johannesjo** [comment]
Thanks for your input! What might be helpful is the console output (you can get it by pressing ctrl+shift+i and navigating to the console tab). Maybe there is more information. Generally this error appears when the indexed adapter of the app is not able to initialize itself, which shouldn't happen unless there is some really funky stuff going on :)

**Comment by shiquimagno** [comment]
@x3rAx It work it really nice to windows also, thanks! ^^
