### ISSUE TITLE
Fix popup on mobile firefox

### ISSUE THREAD

**Issue by reinhart1010** [johannesjo/super-productivity#227]
Though installable as a PWA and Electron, It might be helpful to add a fullscreen toggle button on the app to enhance focus and avoid browser UI cluttering.

Personally, I am having an issue with using this in Firefox for Android in BlackBerry Q5 (BB10) that the Google Drive sync popup overfills the device viewport height which has been reduced by browser controls. (See screenshot)

![IMG_20191002_002127_946](https://user-images.githubusercontent.com/17312341/65984745-a082a300-e4aa-11e9-813f-640666ab7b28.jpg)

This might be a good first issue for Hacktoberfest.

**Comment by KonTy** [comment]
> Firefox for Android in BlackBerry Q5 (BB10) that the Google Drive sync popup overfills 
wow that's a mouth full :) life is so complicated these days. I wanna go back to the day when Windows was the only thing we cared about.

**Comment by johannesjo** [comment]
Thank you very much for opening this up! To be honest Firefox hasn't been a strong focus so far, as not too many people seem to use the wep app and those who do are likely to be using chrome followed by mobile chrome and safari. Nevertheless it might be good to have this fixed!

**Comment by johannesjo** [comment]
This should be fixed now. Thanks again!
