### ISSUE TITLE
Sound Notification for Idle Handling and Time Tracking Reminder

### ISSUE THREAD

**Issue by ffcruz85** [johannesjo/super-productivity#2276]
## Problem Statement

One of my biggest problems is sitting down to work, and getting off track with some small distraction before even opening superproductivity and starting a task.

## :grey_question: Possible Solution

Enable sound for the Idle Handling and/or Time Tracking reminder notifications.  For the UI, I would just add toggles for those in Settings>Sound under the existing checkbox for "Play sound when task is marked done".

In an ideal world for the ADHD afflicted, I would potentially add an option for that sound to repeat periodically. One potential way of doing that is using the existing configuration for time tracking/ idle handling reminder - say my time tracking reminder is 5 minutes. Play sound when notification first come up, play sound again every 5 minutes until I have acknowledged it. I guess that would have to be yet another setting, adding more complexity, so this part I am just throwing out there. I would be supper happy with just enabling sound on those already existing notifications, and having that, I could already set myself a second reminder by having different times configured for idle handling / time tracking reminder

## :arrow_heading_up: Describe alternatives you've considered

None I can think of

## :heavy_plus_sign: Additional context

Very easily distracted person, I need Super Productivity to poke me harder when I am not tracking time. Even be a little annoying if I so choose :)
Thanks @johannesjo for your work, it has already done wonders for me.

**Comment by johannesjo** [comment]
I'd also like to see this (as on optional featue)! PRs are welcome!
