### ISSUE TITLE
Microsoft ToDo Integration

### ISSUE THREAD

**Issue by johannesjo** [johannesjo/super-productivity#228]
While a complete sync might be impossible to pull off, as the MsTodos data model isn't capable of saving all the stuff Super Productivity does, it would be nice to make some lists syncable. The practical use case would be making your everyday general purpose to do list (Ms ToDo) available inside your working environment (Super Productivity).

Please upvote the issue if you want to see this happen.

**Comment by KonTy** [comment]
Here is a STUPID IDEA you can store extra metadata in a JSON format in the comment field. I definitely wouldn't mind that! I'm sure some people would but this could be an optional flag. I know it could make an app slower but that metadata could be parsed on  lazy thread there is no need to real time processing we are not saving lifes here :)

**Comment by johannesjo** [comment]
Yes I had the same stupid thought ;) this could be an option. I'll think about it!

**Comment by petkahl** [comment]
The beta API for ToDo now has openExtensions that look like they cover this: https://docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&tabs=http

Planner integration may be easy as well if this is implemented.

**Comment by johannesjo** [comment]
@petkahl thanks for sharing!

**Comment by johannesjo** [comment]
With the mobile app being available now I don't think an MSTodo integration makes much sense anymore.
