### ISSUE TITLE
Andoid sync with Nextcloud resulting in "504 Gateway Timeout"

### ISSUE THREAD

**Issue by mdietrich16** [johannesjo/super-productivity#2294]
I'm really sorry to bring this up again, I saw many problems like this and tried the proposed solutions there. This might be a problem with my setup, but I cant't figure it out myself and I'm not willing to give up because I love the app so much.

I have a home nextcloud server which is behind a VPN (WireGuard), so I can access it with my phone and tablet outside of the home network. My Windows tablet has the SP desktop app, just like my personal linux machine at home, which both work and sync successfully. But if I try to sync with my phone or in the browser, it does not work. I have already installed the webapppassword app for nextcloud and even set "*" as the allowed origins, so CORS "should" not be the problem, right?

### Your Environment

- Version used: 7.12.0 on Android from Google Play Store
- Operating System and version: Android 12 with OneUI 4.1
- Browser Name and version: N/A

### Expected Behavior

After setting up sync on Android, it should work and fetch the data from nextcloud, which is already synced with multiple desktop clients.

### Current Behavior

After setting the same configuration parameters for WebDAV sync as in the desktop applications and saving, at every try at syncing the Android app throws an error: "Unknown Sync Error: Error: Invalid response: 504 Gateway Timeout"

### Steps to Reproduce (for bugs)

Configuration settings:
Enable syncing: Yes
Enable compression: Yes
Sync Provider: WebDAV
Base URL: https://99.99.99.9/nextcloud/remote.php/dav/files/user/
    (IP address is the address of the nextcloud server in the VPN network)
Username: user
Password: ********************
    ( an application password given in nextcloud exactly for this purpose )
Sync File Path: Documents/superproductivity.json
    (file already exists)

1. Configure desktop clients with above settings, enable VPN tunnel and sync them with nextcloud.
2. Install webapppassword from the nextcloud app store.
3. Set either "*" or "https://app.superproductivity.com" as allowed domains in the webapppassword settings page.
4. Configure the Android app or the web app with exactly the same settings as the desktop apps
5. Enable VPN tunnel and try to sync
6. -> Error happens

### Can you reproduce this reliably?

I can reliably reproduce this in the Android app and in the web app.

### Console Output

N/A
Is there even a way to open the console on Android?

### Error Log (Desktop only)
N/A

This is a problem with either my nextcloud setup or the VPN right? To give additional info on the network, one desktop client is inside the home network, but also connects over the VPN network, the other desktop client is outside the home network, connecting over VPN as well. The Android phone is also outside the home network, connecting through the VPN tunnel. The nextcloud server has no reverse-proxy or anything like that.

**Comment by johannesjo** [comment]
Can't provide much input on this apart from 500+ errors usually suggesting something wrong with your server.

**Comment by ffcruz85** [comment]
I am just confirming I have the same issue, with my WebDAV running on a Synology NAS. Desktop app syncs fine, Android throws a 504

**Comment by ZenKyma** [comment]
I can confirm the same 504 Gateway Timeout Error when trying to sync from Android with my Nextcloud server. Linux and Windows sync just fine with the exact same configuration.

**Comment by jbin** [comment]
Exactly the same hiere

**Comment by fraschm1998** [comment]
Having the same issue but with the app connecting to my nextcloud which is behind a reverse proxy. Works perfectly on the desktop app but not mobile.

Getting:

```
web-dav-sync.service.ts:54 Error: Java exception was raised during method invocation
    at androidInterface.makeHttpRequestWrapped (android-interface.ts:223:24)
    at WebDavApiService.<anonymous> (web-dav-api.service.ts:108:29)
    at Generator.next (<anonymous>)
    at fulfilled (sync.module.ts:32:24)
    at _ZoneDelegate.invoke (zone.js:372:26)
    at Object.onInvoke (core.mjs:26356:33)
    at _ZoneDelegate.invoke (zone.js:371:52)
    at Zone.run (zone.js:134:43)
    at zone.js:1275:36
    at _ZoneDelegate.invokeTask (zone.js:406:31)
```

**Comment by aktaboot** [comment]
Same issue, only appearing on mobile, tried enabling CORS to no avail.
Server is on Nginx's webdav implementation

**Comment by kmantel** [comment]
Same problem, log error is `no user/password was provided for basic authentication`, using https://hub.docker.com/r/ugeek/webdav with success on desktop

**Comment by Marlon154** [comment]
A bit late but I found the error:
[CORS requests are block by Nextcloud](https://help.nextcloud.com/t/cors-requests-blocked-in-nextcloud-app/108884).
But you can enable them by installing [this Nextcloud App](https://apps.nextcloud.com/apps/webapppassword) and adding the URL from which you do the request.
