### ISSUE TITLE
[Feature] Implement global notes

### ISSUE THREAD

**Issue by trx0eth7** [johannesjo/super-productivity#2299]
## Problem Statement
From time to time I'd like to create a global note without creating a particular task and add information in any time.
Below I've tried to describe the features that I would like to have as end user:
1. Create a folder to notes. Possible, user can click on side-menu item "Notes" such as "Tags" and "Create new folder"
2. Create a note. Possible, user can choose folder and click "Create new note"
3. Add image, link, etc to particular note.
4. Create note reference in task (reverse)

For example:
My tasks:
1. task_1: "Read x book"
2. task_2: "Run data migration script to dev environment"
3. ....

My notes:
1. note_1: "Important notes from the x book"
2. note_2: "Steps data migration to any environment"
3. ......

My case:
I have repeatable meeting task with meeting minutes, I'd like to group notes by date instead of write all in task. 

## :grey_question: Possible way
Simple task with any description, but there is no way to structure information (many tasks or one with big description?)
Using another application, as like OneNote, but it is much more convenient to keep this in one application, also some applications aren't supported on unix os

**Comment by johannesjo** [comment]
I agree that the notes feature should be expanded on! There should be a dedicated full window view which allows for searching and filtering.
