### ISSUE TITLE
[Feature] Simplify synchronization of local clients

### ISSUE THREAD

**Issue by maqp** [johannesjo/super-productivity#23]
Not sticking everything into cloud is in fact a strong point for this application. Could you please allow the app to synchronize with other local clients, either over TLS encrypted connection, or 

1. Allow user to specify default location for .json files
1. Add Export button to work view that exports to default location
2. Add Import button to Daily planner, that imports the .json file from default location (instead of having to copy-paste the content).

This would make sync easy as "click export on client1, run rsync command, click import on client2".

**Comment by johannesjo** [comment]
Hello! That would be a cool feature. Personally I especially would like to sync my tasks to my phone. There are definitely plans to allow for synchronization of different sorts on of them being an optional cloud service. I've to admit though that the focus for now is to make the app a little bit more stable, before adding in major new features.

What you can do for now is to use the export functionality which is accessible through the settings. There you can make JSON exports of all your projects and reimport them in another instance.

**Comment by maqp** [comment]
I agree, and you're right about the priorities. I'll use the current import/export until you'll find the time to streamline the feature. Many thanks!

**Comment by johannesjo** [comment]
@maqp I added a new feature to include automatic backups. That gets you at least half the way there :)

I also though of a basic concept on how a generic sync interface could look like. Basically I would allow to specify a custom urls to post or get the complete application data. That's not an ideal solution, but at least a start.

I think that it would much better to use a real local and possibly database and maybe a socket interface to indicate data changes. Unfortunately all data logic is synchronous atm, so this would require a lot of adjustments.

**Comment by jupitus** [comment]
Is it possible to specify the location of the actual data files?  Then we could keep these files in our Dropbox-like folders and have them synced across devices without superProductivity connecting directly.

**Comment by johannesjo** [comment]
@jupitus For the backup file this is possible. But importing the data automatically from a file is a little bit more tricky. When syncing data there is always something that can go wrong and the app somehow needs to know that it changed. I'll try to think of a solution.

**Comment by johannesjo** [comment]
I added very rudimentary syncing support. The application will reload itself completely when an outside change occurs. You can check it out in v1.6.0. Probably not what you want, but it's a first step. You can enable this experimental feature via the settings.

**Comment by jupitus** [comment]
Many thanks for this.  Unfortunately, I'm now getting the "Object has been destroyed" bug (issue 29), so I can't test it.
Version 1.6.5; Ubuntu 16.04; Gnome shell

**Comment by johannesjo** [comment]
@jupitus #29 should be fixed now.

**Comment by johannesjo** [comment]
I'm happy to announce that there is a new syncing feature coming. You can now use GoogleDrive to sync different instances of the app. Running multiple instances at the same time is still not recommended (for that we would need a real web server).

You can check it out in the develop branch. I will release it, once I tested it some more in my daily workflow.

**Comment by johannesjo** [comment]
The feature os out now. Closing this.
