### ISSUE TITLE
JavaScript errors popping up semi-randomly: "Error: write EPIPE"

### ISSUE THREAD

**Issue by mdietrich16** [johannesjo/super-productivity#2300]
### Your Environment

- Version used: 7.12.0 installed from AUR (superproductivity-bin), also happens when built from source
- Operating System and version: Arch Linux
- Desktop Environment: Qtile
- Browser Name and version: N/A

### Expected Behavior

Well, no js errors.

### Current Behavior
Immediately after starting the app and actually before the window itself becomes visible, a JavaScript error message pops up saying:

> A JavaScript error occurred in the main process
> Uncaught Exception:
> Error: write EPIPE
>   at afterWriteDispatched (node:internal/stream_base_common:164:15)
>   at writeGeneric (node:internal/stream_base_commons:155:3)
>   ...
>   at console.log(node:internal/console/constructor:360:26)
>   at initBackupAdapter (/opt/superProductivity/resources/app.asar/electron/backup.js:14:13)
 
I can't really say when else this Error occurs other than always on start and close and sometimes (randomly?) during use, probably after UI updates. The exact stack trace varies at the end, but it is always "Error: write EPIPE". Also, the popup appears not only once but a lot of time it appears 4-8 times after one another.

### Steps to Reproduce (for bugs)

1. Start SuperProductivity via dmenu in Qtile
2. Error pops up
3. Close the program
4. Error pops up multiple times

### Can you reproduce this reliably?

Yes, the error pops up every time and I just click it away. However, when I start superProductivity in the terminal, the error does not appear!

### Console Output

No.

### Error Log (Desktop only)

[main.log](https://github.com/johannesjo/super-productivity/files/9814885/main.log)

**Comment by GeeteshMehto** [comment]
Hello sir, please assign this issue to me as i already worked on this kind of problem in past and has a great experience.

**Comment by johannesjo** [comment]
Thanks @GeeteshMehto ! Let me know if you have any questions!
