### ISSUE TITLE
Tab Autocompletion projects/tags...

### ISSUE THREAD

**Issue by Rudy-MS** [johannesjo/super-productivity#2304]
## Problem Statement
 

Not able to hit the tab key to autocomplete a project name and/or tag name.

## :grey_question: Possible Solution
 

1. ) Enter the name of the task,
2. ) Put the "+" sign to add it to an existing project/tag name. 
3. ) Type in the first few letters of the name of the project/tag.
4. ) Hit the tab key on the keyboard to auto complete the name. (something like what BASH auto completion does).  

## :arrow_heading_up: Describe alternatives you've considered

Tried looking for "tab completion" or "tab autocomplete" in open & closed issues....didn't seem to find anything.

## :heavy_plus_sign: Additional context

See https://www.youtube.com/watch?v=k5A12buZ8To for more info.

**Comment by Rudy-MS** [comment]
Please let me know if I can help out in adding this feature. Thank you!

**Comment by johannesjo** [comment]
Help would be welcome! Let me know if you have any questions!

**Comment by Rudy-MS** [comment]
@johannesjo My apologies...I'm not a coder sadly. I wash I was. 
I should of mentioned that earlier. :( 

I can post bugs and test updates like mad though. Documentation is something I would be willing to do so as well.

**Comment by KatrinIhler** [comment]
I would love to see this as well. Right now the suggested projects/tags at the bottom are just teasing me - I don't want to type the rest, dammit, I want to hit Tab and let the computer do the rest. :D
