### ISSUE TITLE
Google Drive sync OAuth flow broken

### ISSUE THREAD

**Issue by clin045** [johannesjo/super-productivity#2306]
### Your Environment

- Version used: 7.12.0
- Operating System and version: MacOS
- Browser Name and version: Chrome 106.0.5249.119 

### Expected Behavior

Clicking "Get Authorization Code" after enabling syncing should redirect to an OAuth page that will generate a token

### Current Behavior

400 invalid_request is thrown

<img width="449" alt="image" src="https://user-images.githubusercontent.com/7468898/198078109-55db7c2d-db0d-4835-9587-3ba4c96c3d49.png">

### Steps to Reproduce (for bugs)

1. Enable syncing for the first time
2. Select Google Drive
3. Click "Get Authorization Code"

### Can you reproduce this reliably?

This happens every time

**Comment by johannesjo** [comment]
Unfortunately google doesn't support this kind of authentication any more. Not sure if there is a path to migration. Help is wanted. If all fails, we need to remove google drive as sync provider.

**Comment by johannesjo** [comment]
https://developers.google.com/identity/protocols/oauth2/resources/oob-migration

**Comment by 0xcrypto** [comment]
@johannesjo did you considered implicit grant flow https://developers.google.com/identity/protocols/oauth2/javascript-implicit-flow

**Comment by johannesjo** [comment]
> @johannesjo did you considered implicit grant flow https://developers.google.com/identity/protocols/oauth2/javascript-implicit-flow

I would be alright with switching to this method. Probably won't find the time to work on this myself. PRs are welcome!

**Comment by SzilvasiPeter** [comment]
Hi, I encountered the same issue on my Ubuntu 22.04 machine. There is a workaround to solve the problem.

1. Switch to the dropbox synchronization provider on the mobile and web platforms.
2. Synchronize the data on each platform using dropbox.
3. Open a new browser tab in **incognito mode** (hopefully it will not block the access).
4. Switch the synchronization provider to GoogleDrive on each platform.

Note: If the web or mobile application does not create the `SUPER_PRODUCTIVITY_SYNC.json` then change the synchronization file name.

Unfortunately, I did not manage to come up with a workaround regards to the desktop application.

**Comment by johannesjo** [comment]
Unfortunately it seems like google is discontinuing the OOB authentication method (See: https://developers.google.com/identity/protocols/oauth2/resources/oob-migration?hl=en). Without it, it syncing via Google Drive is not possible. At least as far as I can see. I am open for ideas, if anyone has any! 

I will be removing Google Drive Support with the next release of Super Productivity. I am very sorry for this inconvenience. You can use Dropbox or Nextcloud as an alternative Sync-Provider.

**Comment by hugaleno** [comment]
Yeah, I took a look at the migration doc it seens like ist not possible right now to use google drive for it. All "migration solution" need the app to be connected to web somehow :'(

**Comment by johannesjo** [comment]
Google Drive support has now been removed. I am closing this.
