### ISSUE TITLE
[Feature] Scheduled tasks that get repeated on certain days, and end on the last day the user chooses.

### ISSUE THREAD

**Issue by Uppo9** [johannesjo/super-productivity#2328]
## Problem Statement

This type of feature would be useful for homework. Say for example, I had a essay to do, I could just schedule a temporary task that appears on days I want to work on the essay.

## :grey_question: Possible Solution
A button should open a calendar. The calendar should allow you to click on the days you want the scheduled task to be repeated on.

## :heavy_plus_sign: Additional context
The current thing I do for homework right now is kinda clunky. Whenever I'm done with a scheduled task for the day, I just schedule it for the next day. But I'm still not able to select certain days for the homework to be on.

**Comment by stilnat** [comment]
I was about to post an issue with the exact same feature request, that would be a great add to super productivity.

**Comment by timmillard** [comment]
This sounds like a good idea for students like myself - maybe a calendar-like interface would work well?
