### ISSUE TITLE
Is there a way to disable JIRA integration now?

### ISSUE THREAD

**Issue by danielestevez** [johannesjo/super-productivity#233]
I remember both JIRA and GH integrations could be disabled in previous versions but i cannot find the option now!

### Your Environment
* Version used: 2.12.3
* Operating System and version: Windows 10

**Comment by johannesjo** [comment]
When pressing the three little dots next to a project on your list, you get to the project settings. You can disable jira from there.

**Comment by danielestevez** [comment]
OMG., thanks, i couldn't see those! 
I expected those options in the 'Edit Project' pencil icon at the "Manage Projects" option

**Comment by johannesjo** [comment]
Yes this needs to be improved... :)
