### ISSUE TITLE
[Feature request] Export a list of all tasks in a project or tag

### ISSUE THREAD

**Issue by kulasbastian** [johannesjo/super-productivity#2333]
Hi!

It would be useful to be able to export a list of all undone tasks in a project, tag or for everything.
Better if there is an option to export CSV so that irrelevant data can be manually filtered out based on the need.

An example use case is giving this list to a supervisor as your planned tasks for the day, or as a list of all your pending tasks for a project.

Thanks!

**Comment by ChameleonRed** [comment]
Application is very good but data is close in application (or I do not know how to export).

Full project and task export will be welcome JSON, YAML or some typical task format.

This allow to import all data into other application.

Some import is also good in same interchange format (I do not need to import any special format).

User can write export from universal format to other formats if they need.

**Comment by johannesjo** [comment]
@ChameleonRed You can completely export the data as JSON under Settings Import/Export.
