### ISSUE TITLE
LocalFile Sync directory selection improvement

### ISSUE THREAD

**Issue by 42Willow** [johannesjo/super-productivity#2334]
## Problem Statement

Local File Sync requires a directory of the sync file to be inputted in this format: `<dir><filename>`

## :grey_question: Possible Solution

When you select the sync file path box it should open a window for saving the sync file, or a window to select a directory.

## :heavy_plus_sign: Additional context

![image](https://user-images.githubusercontent.com/70784752/200668073-a2b90d77-c11d-44f7-868c-8b112ca1d087.png)

**Comment by johannesjo** [comment]
Hey there! You need to select a file rather than a directory. The usability could of course be improved here.

**Comment by 42Willow** [comment]
> Hey there! You need to select a file rather than a directory. The usability could of course be improved here.

Which directory does the file need to be in?

**Comment by johannesjo** [comment]
> Which directory does the file need to be in?

Anywhere you want.

**Comment by 42Willow** [comment]
Yes but what do I enter into the box to get it to work? I keep getting the same error...

**Comment by stokito** [comment]
@johannesjo Could you please just make the Sync File Path by default as `super-productivity-backup.json`? This will make it easier to understand and change.

**Comment by stokito** [comment]
I think that it also would be great to set the file name as default for the webdav:
```patch
Subject: [PATCH] webdav backup: set default sync file name
---
===================================================================
diff --git a/src/app/features/config/default-global-config.const.ts b/src/app/features/config/default-global-config.const.ts
--- a/src/app/features/config/default-global-config.const.ts	(revision 0d06c83f26bbeed93f74ef101d84f018f07c5bf4)
+++ b/src/app/features/config/default-global-config.const.ts	(date 1684654548826)
@@ -153,7 +153,7 @@
       baseUrl: null,
       userName: null,
       password: null,
-      syncFilePath: null,
+      syncFilePath: 'super-productivity-sync.json',
     },
 
     localFileSync: {

```

**Comment by johannesjo** [comment]
Thanks @stokito ! will do so!

**Comment by 42Willow** [comment]
still relevant I think
