### ISSUE TITLE
Prompt to ensure exiting application without ending the day keeps reappearing when pressing cancel

### ISSUE THREAD

**Issue by sbaeurle** [johannesjo/super-productivity#2335]
Windows Store App -

- Version used:  v7.12.0 - appx bundle
- Operating System and version: Windows 10 Enterprise 1909

### Expected Behavior

- When exiting the app without finishing the day, a prompt should appear if this is the desired action.
- Pressing cancel should not exit the application and return to the normal application state

### Current Behavior

- Cancel takes you to the finish day screen (not specifically a bug)
- The cancel dialog keeps reappearing after a new task is created and while using the application (until you force a restart)

### Steps to Reproduce (for bugs)

1. Enable Exit Confirmation
2. Try to exit the application
3. Press cancel in the dialog
4. Create a new task/perform any action

### Can you reproduce this reliably?

Not entirely. Sometimes the add task dialog is locked as well. (Seems like not performing the finish day screen leaves some variables set)

**Comment by telepath** [comment]
I have the same issue.
Every time I click the "Remove from My Day" button, the message pops up, cancel drops me into the finish day screen.
Disabling "Confirm before exiting the app without finishing the day first" does not help.

**Comment by telepath** [comment]
after quitting and restarting the app, the issue is gone, but now I don't get the message even when the option is enabled and I quit without finishing the day.

**Comment by sbaeurle** [comment]
hey, the issue still persists on my side :) however I didn't find any time to perform some troubleshooting! however, It's not really an relevant issue, since exiting the application and restarting it leaves you in the desired state
