### ISSUE TITLE
400 (linux-desktop), 504 (web app) errors 

### ISSUE THREAD

**Issue by careverca** [johannesjo/super-productivity#2352]
### Arch linux

![image](https://user-images.githubusercontent.com/18376458/203723927-5b40f29d-e5cd-4ba9-9c13-d4ab51228651.png)
![image](https://user-images.githubusercontent.com/18376458/203724028-43d41d52-f3ed-4893-bec2-5b8b2f8216cf.png)
![image](https://user-images.githubusercontent.com/18376458/203724142-4b7e2671-53b2-4b10-bbd2-81d2cde84a3f.png)

- Version used: AUR package 7.12.0
- Operating System and version: arch linux 6.0.2
- Desktop Environment: i3wm
- Browser Name and version: brave

### Expected Behavior

Syncing normally 

### Current Behavior

When trying to sync, whether through Dropbox of Drive, I 400 error on desktop, 504 error on web app, 504 error on android. When I try to sync a local file, I get the EISDIR error (see screenshots)

### Steps to Reproduce (for bugs)
The errors pop up every time I try to sync with the data (or backup file) I normally used

1.
2.
3.
4.

### Console Output
![image](https://user-images.githubusercontent.com/18376458/203725439-c077a6c2-c6ab-43a2-a425-45e01ee4812e.png)

### Error Log (Desktop only)
(sent to your email)

**Comment by sk425** [comment]
Not sure this is app side, I'm getting the feeling dropbox removed support somehow

**Comment by careverca** [comment]
> I don't see the issue anymore... Please check your side @careverca

Me too! Thanks for your quick reaction!
