### ISSUE TITLE
Pomodoro break doesn't countdown, can't track break time

### ISSUE THREAD

**Issue by lhclack** [johannesjo/super-productivity#2357]
I searched for anything pomodoro related before reporting this, so please correct me if there is already the same issue logged

### Your Environment

- Version used: 7.12.0
- Operating System and version: Windows 10

### Expected Behavior

When pomodoro 25m timer is up, the option to start timing the 5m break should begin. My settings:

![2022-11-28 04_54_23-Super Productivity](https://user-images.githubusercontent.com/13540087/204260852-1ffff34b-5ae0-4323-8aa8-92adc820172a.png)

I expect an alarm to tell me my 25m are up and to give me an option to start the 5m timer when I'm ready. The 5m timer would go and an alarm to tell me 5m is up and give me the option to start the next 25m session when I'm ready

### Current Behavior

I get one alarm letting me know when to start my break. When I go to check and am ready to start the break, I see that my break is done with 5:00 on the screen and buttons that tell me "Start break" which doesn't do anything because it tells me my break is done. And up top where the timer is looks like if I click "play" it will start the break timer, instead it goes straight to the next pomodoro session (25m).

However, if on the pomodoro 25m timer, if I hover to see I have an option to skip that session. Clicking that auto starts the break session with an alarm saying to enjoy my break. If I were to give in to just doing things this way, it would probably show twice as many sessions as I've actually done and it would be nice to see accurately my session count

### Steps to Reproduce (for bugs)

1. begin pomodoro timer
2. let it run naturally (can't force next session by skipping this one)
3.
4.

### Can you reproduce this reliably?

Every time

### Console Output

I didn't see a way to do a true export of this to check all details, let me know if there is a better way to show this 

![2022-11-28 05_10_39-Super Productivity](https://user-images.githubusercontent.com/13540087/204263731-0a109491-fdc0-4440-bbb4-842ce1669bad.png)

**Comment by karol-be** [comment]
Same happens for me. The repro you've attached is correct, however I've recorded a repro before I've found your issue so I'll attach it anyways.
https://user-images.githubusercontent.com/10078424/224941103-97ec2e09-a52e-41ae-a46b-c7d55cec3135.mp4

**Comment by johannesjo** [comment]
https://user-images.githubusercontent.com/10078424/224941103-97ec2e09-a52e-41ae-a46b-c7d55cec3135.mp4

**Comment by stralx** [comment]
> 

The video posted above by @johannesjo, is exactly what I'm experiencing. Pomodoro working session ends and when manually starting the break, prompts automatically the end of break and the choice for a new working session. 
At first I thought it was subtracting the idle time for the break but it is not the case. I run Debian Linux 11, with Gnome 3.38.5

**Comment by dahaupt** [comment]
This issue is still relevant, I can reproduce it in the latest version.
