### ISSUE TITLE
When I add a recurring task containing subtasks; the subtasks doesn't repeat

### ISSUE THREAD

**Issue by Polonco** [johannesjo/super-productivity#2358]
### Your Environment
Web version
- Version used: 7.12.0

### Expected Behavior
When I set a recurring daily task containing subtasks I expect all the subtasks to repeat too.
i.e:
Task: clean the house
Repeat: weekly on Sunday
subtask1: do the laundry
subtask2: wash dishes
subtask3: clean the floor

I want to have the task "clean the house" and all the subtasks repeating every week on Sunday

### Current Behavior

Every Sunday I have the task repeated but it doesn't contain the subtasks.

**Comment by hugaleno** [comment]
Still relevant
