### ISSUE TITLE
Help - data rescue / save due to sync issue

### ISSUE THREAD

**Issue by martin-forum** [johannesjo/super-productivity#2370]
Hello all,

I have already reported in #2290 that I can not sync (dropbox) anymore - so all my data are on Android. 
Since approx 2 years I am using super productivity and it is great. Especially the UI, it is open source with encryption and support of multiple devices (sync). But the sync is broken for me - the second time in these two years - and I do not want to copy manually all my tasks to another app. 

Sadly, also my test to sync from desktop (debian fresh intall) with a local file are not working...

I am using an up-to-date android device and the current version of super productivity.

One question only:
==============
How can I export or where do I find my super productivity tasks on my Android device?

BR Martin

**Comment by lrq3000** [comment]
I would also like to know how to backup superproductivity data on Android and how to import it. Given replies elsewhere by the main dev, it seems only the desktop apps can do automatic backups, and I did not find the import/export menu on Android.
