### ISSUE TITLE
 continuing a task asks if I want to quit

### ISSUE THREAD

**Issue by cloo** [johannesjo/super-productivity#2371]
### Your Environment

- Version used:  7.12.0
- Operating System and version: Windows 11

### Expected Behavior

Button "Start tracking time" should start tracking time.

### Current Behavior

 Button "Start tracking time" causes exit dialog to appear.
![221204-125121](https://user-images.githubusercontent.com/651760/205490032-a49a0c3a-6bef-4444-9215-5dfa3d0c2815.gif)

### Steps to Reproduce (for bugs)

No idea, this was not happening before, but I could repeat it several times and record it.

### Can you reproduce this reliably?

No, it is not happening after restarting the app.

### Console Output

No errors, I guess I tried that too late.

### Error Log (Desktop only)

 attaching.
[main.log](https://github.com/johannesjo/super-productivity/files/10148475/main.log)

**Comment by johannesjo** [comment]
Please let me know if this happens again!
