### ISSUE TITLE
Holding backspace resulted in a bunch of tasks getting deleted

### ISSUE THREAD

**Issue by RZarifov** [johannesjo/super-productivity#2376]
### Discussed in https://github.com/johannesjo/super-productivity/discussions/2346

<div type='discussions-op-text'>

<sup>Originally posted by **Xeizzeth** November 16, 2022</sup>
And clicking "undo" button that appeared below didn't do anything.  
Luckily I sync via dropbox, and have two devices, so the crisis was averted by restoring previous version of the file.  
It'd be better to have confirmation dialogue for example for that specific case.  </div>

**Comment by cs50guy2** [comment]
I agree. It is very easy to delete a task by accident. There should be a confirmation dialog for deleting a task and also an option to disable the confirmation in the settings. When I started using this app, I would accidentally delete tasks multiple times when trying to modify the text of the task. Thankfully, I didn't run into any undo issues. In the meantime, I change the shortcut for deleting to ctrl+backspace. It would improve the ux if you could prevent accidental deletions by adding the confirmation dialog.

**Comment by johannesjo** [comment]
An configurable option for a confirmation dialog seems like a good solution to me. PRs are welcome!

**Comment by Xeizzeth** [comment]
It is relevamt lmao.
