### ISSUE TITLE
Adding a Pomodoro toggle

### ISSUE THREAD

**Issue by mr-tchoo** [johannesjo/super-productivity#2379]
## Problem Statement
When i'm planning my day, I have a bunch of tasks that I would still like to track but not with the Pomodoro timer, such as reading, buying croceries, etc.

## :grey_question: Possible Solution
Therefore I propose a button in the main-header component. That toggles the Pomodoro timer.
![super_productivity_pomodoro_toggle_on](https://user-images.githubusercontent.com/53568958/208240174-926a66ba-a5b7-45fe-83c6-cdbf74bae8ea.png)
![super_productivity_pomodoro_toggle_off](https://user-images.githubusercontent.com/53568958/208240173-9b059589-7d04-4813-b7d4-4bba208a1408.png)

## :arrow_heading_up: Describe alternatives you've considered
A better solution to me would be to have dedicated timers: 1 Pomodoro + 1 regular.

## Thanks:
Either way, thank for you @johannesjo and the volunteers working hard building this project.

**Comment by timmillard** [comment]
This sounds really useful, especially for me as a student. I frequently find myself needing to limit my time between work in this way.

**Comment by timmillard** [comment]
I'm happy to have a go at implementing something like this, if nobody else has already started :)

**Comment by johannesjo** [comment]
That would be great! Feel free to experiment with the concept to find the best way to achieve this. Not sure if the original proposal is technically possible tbh.

**Comment by igoragatti** [comment]
This would be particularly useful for me.

I have meetings vs task times and I want to track both, but meetings don't have to be pomodoro.

If I want to enable pomodoro I have to go to settings and enable/disable from there. If there was a hotkey or a toggle to enable/disable pomodoro it would be greatly appreciated
