### ISSUE TITLE
Add 'Saturday' to "Start of the week" option!

### ISSUE THREAD

**Issue by mojienjoyment** [johannesjo/super-productivity#2390]
I think it's clear. In our Country, **Sat** is the first day of the week. So pleae add this to "**Start of the week**" option!
I'm using Linux Desktop 7.12.0

by th way, Thanks for your great app.

**Comment by hugaleno** [comment]
It's not this ? You have to scroll down.
> Settings -> Misc Settings -> First day of the week

![image](https://user-images.githubusercontent.com/6486234/230795964-30feffbc-0eb4-47ec-a3ef-ef5ef90cafb2.png)

**Comment by mojienjoyment** [comment]
> It's not this ? You have to scroll down.
> 
> > Settings -> Misc Settings -> First day of the week
> 
> ![image](https://user-images.githubusercontent.com/6486234/230795964-30feffbc-0eb4-47ec-a3ef-ef5ef90cafb2.png)
Yes. I should scroll down

**Comment by hugaleno** [comment]
Alright then. You can close this @johannesjo
