### ISSUE TITLE
Time units

### ISSUE THREAD

**Issue by milotype** [johannesjo/super-productivity#2400]
## Problem Statement

1. Time values and units are not separated by a space (non-breaking space) character, which would be typographically correct.
2. Time unit for minutes should be "min", not "m" ("m" is the unit for meter).

## :grey_question: Possible Solution
1. Separate the time values and units ideally with a "Non-breaking space" character.
2. Change unit for minutes to "min", not "m" ("m" is the unit for meter).

## Screenshot
![time units](https://user-images.githubusercontent.com/43657314/210177598-7e93bf99-e95c-44d4-9c70-36451ddcdc72.png)

**Comment by milotype** [comment]
If you can tell me which files need to be changed, I could maybe make changes and send them as PR.

**Comment by johannesjo** [comment]
Hey there! Thanks for opening this up! I think I prefer the shorter version, as it is the same as the short syntax. Using the longer `min` etc. will also break the ui at many places. 

I leave this open. If many other people share your view, we can revisit this.

**Comment by milotype** [comment]
@johannesjo 
I **strongly** suggest to use "min" instead of "m".
As mentioned before "m" is the unit for meter, not for minutes, so "m" is **simply wrong**!
I don't think anybody else will comment on this issue ... but it would be so simple to change it! :-)
Breaking the UI is not a valid reason in my view. The UI should adapt to the context ...
