### ISSUE TITLE
Feature request: Pomodoro timer tray indicator

### ISSUE THREAD

**Issue by serovar** [johannesjo/super-productivity#241]
### Expected Behavior
When the pomodoro timer is used, it would be useful to have a tray indicator that showed the remaining time, and possibly would permit to control the timer itself (playing/pausing the timer, stopping it and skipping the session, like you can do from the main window).

### Current Behavior
When using the app we have a not very useful tray icon with the static tick symbol.

**Comment by johannesjo** [comment]
Hey there! Thanks for the suggestion. This was implemented at one point through a gnome shell extension. I'll try to get it running again!

**Comment by serovar** [comment]
Hopefully it could work with other DEs.

**Comment by arf1372** [comment]
> Hey there! Thanks for the suggestion. This was implemented at one point through a gnome shell extension. I'll try to get it running again!

@johannesjo Could you reference any of commits which include this feature?

**Comment by johannesjo** [comment]
I added this recently. What's missing are icons for the pause state. If somebody adds those, I gladly add them to the application.
