### ISSUE TITLE
All Projects view

### ISSUE THREAD

**Issue by grubbymediator** [johannesjo/super-productivity#2415]
## Problem Statement

Hello! Thank you for good work!
Recently I started using Super Productivity for everything, and now got quite a bunch of projects. So it takes a while every time to go through all personal and work-related projects to check for tasks to be "doned" or "todayed". And each time I miss something.
Also, it's always annoying by the end of the day to go through all the projects to check if there are any tasks done to "finish day" for these projects. Would be nice if I could finish the day for all projects with one click.
## :grey_question: Possible Solution
If we had the "All Projects" view showed all active tasks, this problem would be solved.
Also, having "finish day" button there, just like in project views, would save a lot of time spent on keeping it tidy.

For convenience, tasks can be color-coded with the color of the project.
Opening backlog on this view could show tasks from all projects that are currently in the backlog.

## :arrow_heading_up: Alternatives considered
The global "finish day" button could be done without implementing all projects view. and still be very useful.
Viewing tasks from multiple projects can be done with project groups or something, if "All Projects" is considered too cluttery.

**Comment by ishanarora** [comment]
Still relevant

**Comment by ishanarora** [comment]
Still relevant

**Comment by tmlmt** [comment]
1. I guess a "Today" view (which color-codes different projects) which wouldn't just show tasks for Today for all tasks, Do you agree?
2. Can't you already finish the day for all projects by clicking on "Finish Day" at the bottom of the Today view?
