### ISSUE TITLE
Timer stops before pomodoro break starts (when using manual break confirmation)

### ISSUE THREAD

**Issue by pd-leukert** [johannesjo/super-productivity#2423]
## Problem Statement
#2014 added the option to manually start the next pomodoro break whenever one is ready to do so. However, the timer for the task stops in the moment the break is suggested (usually after the 25 minutes). Since the user keeps working on the task until he starts the break it would be helpful to stop the timer only when the break actually begins.

## :grey_question: Possible Solution
Stop the timer only when the user confirms and starts the next break (as added in #2014)

## :arrow_heading_up: Describe alternatives you've considered
This feature could be added as an option, but I think starting the break on confirmation should be the default behavior.

## :heavy_plus_sign: Additional context
#2014

**Comment by renawi94** [comment]
Hi, I just discovered Super Productivity a few days ago when searching for just a simple pomodoro timer and I'm still amazed by how insanely perfect this app seems to be!!

Nevertheless this is the bug that just stroke me and I already thought that I'm not the first one who ran into it. So I'd like to to confirm it and affirm fixing it. Would make the app more close to perfect and certainly make me a sponsor

**Comment by pd-leukert** [comment]
Closed by #2739
