### ISSUE TITLE
Don't truncate Project name in main area unnecessarily

### ISSUE THREAD

**Issue by jmhickman** [johannesjo/super-productivity#2427]
## Problem Statement

The window should not truncate project titles if there is actually plenty of horizontal space to fully display the title

## :grey_question: Possible Solution

Only apply truncation if the window is so narrow that the title would collide with the top bar menu buttons

## :arrow_heading_up: Describe alternatives you've considered

Use the mouseover event to display the full title, either in the bar or as alt text

## :heavy_plus_sign: Additional context
![image](https://user-images.githubusercontent.com/6581761/215202429-116dd7e7-0896-4dff-b656-62b31ba04a67.png)

**Comment by johannesjo** [comment]
What OS, browser etc. are you on? Normally it should only truncate if there isn't enough space.

**Comment by jmhickman** [comment]
I'm using the application on Windows 11. Version is 7.12.1
