### ISSUE TITLE
Sync Error: One of the dates provided is from the future...

### ISSUE THREAD

**Issue by ivenpoker** [johannesjo/super-productivity#2431]
### Environment

- Version used: 7.12.1 snap
- Operating System and version: Ubuntu 20.04 LTS
- Desktop Environment: GNOME
- Browser Name and version: 

### Expected Behavior

Desktop app should sync flawlessly with Dropbox when updates are made locally and syncing is triggered manually or automatically

### Current Behavior

When an attempt is made to sync manually or automatically with some updates on task made locally, sync operation fails with message **"Sync Error: One of the dates provided is from the future..."**'

As a result, I'm prompted to reload remote data (loosing any location udpates!)

### Steps to Reproduce (for bugs)

1. Install version 7.12.1 on Ubuntu 20.04 LTS GNOME
2. Sync app with Dropbox under **"Settings"**
3. Perform an update on a task (e.g update a task name, create new task etc)
4. Attempt to sync manually or allow syncing to be triggered automatically on set time interval (mine was 1m)

### Can you reproduce this reliably?

I can reliably reproduce issue

### Console Output

![super-prod-sync-error-log](https://user-images.githubusercontent.com/16977081/215450701-db8d7336-2e46-445c-9c76-c949e9495099.png)

**Comment by johannesjo** [comment]
Hey there! Thanks for reporting! Did you do all this on the same computer? From the data it looks like the remote timestamp is a future date for some reason. The timestamp is determined on the machine that uploades the data.
