### ISSUE TITLE
Suggest about the progress bar in taskbar

### ISSUE THREAD

**Issue by luo-chuan** [johannesjo/super-productivity#2432]
![screenshot1](https://user-images.githubusercontent.com/33930736/215651867-69d8b717-831d-491f-9b9a-b1f1b9acd187.png)
The graph above is a screenshot of [Tomatolist](https://www.tomatolist.com/). I think there are three points worth learning.
1. Make a distinction between work and rest by different colors. For example, Tomatolist use red for work and green for rest.
2. Display the number of minutes remain near the icon, or display the number of minutes last if user do not use the tomato clock. It will save space of screen in this way.
3. On the basis of point 2, make the progress bar's direction left. In other word, the more the number of minutes remain, the longer the progress bar be. It will be more intuitive in this way.

**Comment by johannesjo** [comment]
I am all for it! PRs are welcome!
