### ISSUE TITLE
CalDAV integration with Baikal

### ISSUE THREAD

**Issue by mocsa** [johannesjo/super-productivity#2446]
### Your Environment

Super-Productivity 7.12.0 installed as Electron app on Win 10.
[Baikal 0.9.2](https://sabre.io/baikal/) installed in a local XAMPP installation.

### Expected Behavior

CalDav integration should be able to read tasks from Baikal calendar.

### Current Behavior

Error message. "CalDav: Request failed because of a client side network error"

### Steps to Reproduce (for bugs)

1. My calendar's URL is http://192.168.0.20/baikal/html/dav.php/calendars/myusername/default/
2. This URL works flawlessly everywhere. For example, in Thunderbird, in eM Client, in every Android calendar and tasks app via DavX5.
3. In Super-Productivity project settings I put http://192.168.0.50/baikal/html/dav.php in CalDav URL. I put default in CalDav resource.
4. Then I enter myusername in CalDav username and password in CalDav password.

### Can you reproduce this reliably?

Reproducible. Integration never worked.

### Console Output

If I open Electron debug console with CTRL+SHIFT+I, I see the following error in Console:
```
PROPFIND http://192.168.0.50/baikal/html/dav.php/ 401 (Unauthorized)
```

On the network tab I see a failed request for dav.php. The server's response is this:

```html
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>4.3.1</s:sabredav-version>
  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
  <s:message>No 'Authorization: Digest' header found. Either the client didn't send one, or the server is misconfigured. Login was needed for privilege: {DAV:}read on </s:message>
</d:error>
```

### Error Log (Desktop only)

Nothing relevant in the Log.

### Analysis

My Baikal installation is specifically configured for "Digest" authentication. This is what worked with the biggest number of CalDav clients. Is it possible that Super-Productivity cannot do this type of authentication?

**Comment by jonathanp0** [comment]
The code shows it is hardcoded to Basic authentication: https://github.com/johannesjo/super-productivity/blob/e0006ef7b0a0627264846c10c96f345435445dc8/src/app/features/issue/providers/caldav/caldav-client.service.ts

Can Baikal not be configured to allow both?

**Comment by mocsa** [comment]
As far as I can see, you have to decide on one type of authentication in the Baikal admin settings:

![image](https://user-images.githubusercontent.com/13969648/221853852-16c844e4-1cde-4240-8e25-42998e02f3a7.png)

**Comment by mocsa** [comment]
Still relevant

**Comment by mocsa** [comment]
Still relevant

**Comment by sunjam** [comment]
open please

**Comment by lifetraveler** [comment]
turn the auth type to 'Basic' can resolve it

**Comment by mocsa** [comment]
> turn the auth type to 'Basic' can resolve it

Yes, I know but I need Digest authentication for CalDav clients (for example Android). See my original post.

**Comment by anantone** [comment]
I also get the problem with Basic auth

**Comment by culinia** [comment]
I just found a solution which makes finally super-productivity work together with baikal via caldav as it should:

in baikal i choose as authentication method "apache"
and in super productivity you need to enter the caldav details as follows:

choose the appropriate project -> settings -> caldav -> 
switch to enabled and then enter the caldav properties as follows:

the caldav url must look like that: 

https://baikal.domain.org/dav.php/calendars/username/8d8871cf-5ecc-41d3-905a-489e70a98b84/

calendar name: the same cleartext name as it's shown in baikal

username and password configered as in baikal.
thats it. 

then click on the task overview page of that project and a few seconds later the tasks list shall be automatically loaded from your baikal server. thats how it did on my computer (linux mint 6).

now finally i can put this amazing program in real use and discover how much it can help me to boost my productivity! <3

**Comment by confestim** [comment]
If the fix that @culinia proposed doesn't work, check out the network tab in the developer console (Ctrl + Shift + I) and look at the issue. If it is something among the lines of "no data found for resource with identifier", you have to allow CORS on your server. 

In my case, running nginx/1.18.0, the issue was with fonts not loading. Adding the following snippet to my `/etc/nginx/sites-available/caldav.domain.org` solved the problem:

```
location ~* \.(eot|ttf|woff|woff2)$ {
    add_header Access-Control-Allow-Origin *;
}
```

**Comment by johannesjo** [comment]
> you have to allow CORS on your server

That should only be the case for the web version of super productivity.
