### ISSUE TITLE
Skip reminder for time-tracking tasks

### ISSUE THREAD

**Issue by mocsa** [johannesjo/super-productivity#2448]
## Problem Statement

* I have a scheduled task with an active reminder or with a snooze-d reminder.
* I start time-tracking for the task ahead of time or before the snooze-d reminder pops up again.
* While time-tracking is active, Super-Productivity pops up a reminder at the scheduled time or at the snooze-d time.

## Expected behavior

* Before displaying a reminder in the Electron window or in Windows Task Bar, Super-Productivity should check if the task is already tracking time.
* It makes no sense to remind me to do a task while I'm already doing it.

**Comment by johannesjo** [comment]
Makes sense also to me to now show the reminder in that case or to limit it to a simple snack!

**Comment by mocsa** [comment]
Still relevant

**Comment by mocsa** [comment]
Still relevant

**Comment by mocsa** [comment]
Still relevant
