### ISSUE TITLE
Accept longer project titles

### ISSUE THREAD

**Issue by anixsson** [johannesjo/super-productivity#2460]
## Problem Statement
Large screen problems...
1. Left sidebar is too small so project names can't be fully viewed. _(Subjective opinion that I think mirrors better usability for the app)_
2. Projectname title on the project page is too limited. _(Objective opinion, there is space there and it resize beautiful with the right content when minimized)_

## :grey_question: Possible Solution
1. If window width is larger then xxxpx increase sidebar to xxx%, alt. fix value in settings
**Note:** The additional information bar to the right spans perfectly! (Could be a good CTRL + C, CTRL + V situation)
2. If window width is larger then xxxpx increase title to xxx%, or let it decrease with the UI as it is today (remove max value)

## :arrow_heading_up: Describe alternatives you've considered
Alt. make it possible to add custom css in a form in the settings

## :heavy_plus_sign: Additional context
This is partly mentioned in issue #2427

### System
Using Github compiled (not appstore), MacOS 13+ (M1 2020 AIR)

**Comment by johannesjo** [comment]
Thanks for opening this up! I agree that we could improve on this, though a single larger menu size for wider screens might be enough imho. It's a menu and it should never exceed a certain size.
