### ISSUE TITLE
Do not track outside normal office hours

### ISSUE THREAD

**Issue by Petemir** [johannesjo/super-productivity#2462]
### Your Environment

- Version used: 7.12.0, App Image
- Operating System and version: Ubuntu 22.10
- Desktop Environment: KDE with i3wm
- Browser Name and version: N/A

### Expected Behavior

There is a setting that asks for the "Work Day Start" and "Work Day End" times. I would expect, then, than when I open my computer the next day, I would not get a message saying "You have not been tracking time for >14 hrs".

### Current Behavior

I get a message saying the next day saying I haven't been tracking anything since the previous day -- including night hours.

### Steps to Reproduce (for bugs)

1. Leave the app open during the night (although now that I saw [https://github.com/johannesjo/super-productivity/issues/2355](this), I may not do it anymore! :open_mouth: ), even suspending the computer
2. Open the computer the next day and be treated with a "you haven't been tracking your work during your sleep" message

### Can you reproduce this reliably?

Yes

### Console Output

N/A

### Error Log (Desktop only)

N/A

**Comment by johannesjo** [comment]
Hey hey! Work start/end are just for the timeline, but are not intended to affect other parts of the app.

**Comment by Petemir** [comment]
Hello! Thanks for the great app :). 

Ok, as I didn't see any explanation of the feature I assumed it was for the bug I stated, but in that case, I'll just close the ticket. Thanks!
