### ISSUE TITLE
New "Never" option for "Remind at" in Repeated tasks

### ISSUE THREAD

**Issue by mocsa** [johannesjo/super-productivity#2471]
## Problem Statement

I have "Repeated tasks" on the "Scheduled" tab which are automatically added to my task list every day. Some of them have a "Scheduled start time". The program forces me to select "Remind at" from a list which does not contain "Never".

I want my tasks to have a "Scheduled start time" because I want them to appear at a certain time on the "Timeline" tab. But I don't need a reminder.

Here is the dropdown list where I miss the "Never" option:
<img width="412" alt="image" src="https://user-images.githubusercontent.com/13969648/219712677-506ac08f-b3eb-4cb3-b155-68f4574898c4.png">

## :arrow_heading_up: Describe alternatives you've considered

I haven't found any alternatives in the program which could substitute the "Never" option.

## :heavy_plus_sign: Additional context

My problem is similar to #2142 which was closed for inactivity. But that Issue talked about tasks scheduled for only one day. My problem is about repeated tasks. However, the daily scheduling dialog would also benefit from a "Never" option.

**Comment by mocsa** [comment]
Still relevant

**Comment by mocsa** [comment]
Still relevant

**Comment by Jagdfalke** [comment]
Implemented by @saibottob . It should be available in the next version.
