### ISSUE TITLE
Feature Request: Focalboard integration

### ISSUE THREAD

**Issue by Cyber-Syntax** [johannesjo/super-productivity#2474]
## Problem Statement
- I always get frustrated when I write my task from the focalboard

## :grey_question: Possible Solution
- Focalboard integration

## :arrow_heading_up: Describe alternatives you've considered
- Kanban technic can be added. I find it very difficult to finish projects in SuperProductivity because for some reason the projects are getting bigger in my eyes. But I finish my tasks much faster with kanban board. 

- At the moment I can only use it for my repetitive tasks.

Priority: High

**Comment by Andrej730** [comment]
Agree that kanbaning task list helps making it less overwhelming.
What helped me a bit with that problem in super-productivity is organizing kind of vertical kanban.

![image](https://user-images.githubusercontent.com/9417531/219944574-2ac2d767-3478-4a33-b942-633d77f71818.png)

**Comment by Cyber-Syntax** [comment]
@Andrej730 But dealing with it all the time is a waste of time.

**Comment by johannesjo** [comment]
#374
