### ISSUE TITLE
Feature Request: Escape characters in task title

### ISSUE THREAD

**Issue by Andrej730** [johannesjo/super-productivity#2477]
It would be nice to have some option to escape special characters - most of the time I meet this issue when create tasks with hastag ids from github.

For example when I create task `example task #2254` the program creates task `example task` with tag `2254`. I know it's possbile to remove the tag and change the name after but I'd like to just escape this part to never create tag in first place.

As discussed in https://github.com/johannesjo/super-productivity/discussions/2406 it's not currently possible.

**Comment by bytrangle** [comment]
Yeah, I think this is a much needed feature. But I don't know how to develop it without introducing more complexity to the parsing job, which is already complicated. I'd suggest two things:

- Highlighting what is interpreted as tags in a task title. Users can click over it and it will be converted to the original string.
- Aslo display the tag under the task title, in the preview area. This part contains a three-vertical-dot icon (aka Kebab menu or More Options). Clicking on this icon will open two choices: Remove the tag (in case user enters the wrong tag) or convert the tag to the original string

Currently, the preview area is non-interactive and there is a lot of room to improve it.

![super-productivity-escaping-tags](https://user-images.githubusercontent.com/28924121/220052021-2d21fe90-4322-4e24-ba20-c6ac9b2b43fa.png)

**Comment by Andrej730** [comment]
Maybe it will possible as workaround to make parser ignore special symbols if they are space separated with the tag name?
![image](https://user-images.githubusercontent.com/9417531/220259647-a46479b5-0d37-4fff-a03f-5c9ee844fd80.png)

**Comment by bytrangle** [comment]
Interpreting "hashtag space name" as a shortcut for tags is more like a bug to me.

Adding option to treat hashtag just like a literal hashtag and not a trigger for adding tags is an enhancement.

Perhaps this issue can be broken into two issues.
