### ISSUE TITLE
Can not import the sync file downloaded from google drive

### ISSUE THREAD

**Issue by zheng95z** [johannesjo/super-productivity#2480]
### Your Environment

- Version used: latest on microsoft store
- Operating System and version: Windows 10
- Desktop Environment: Windows

### Expected Behavior

Import as expected

### Current Behavior

Invalid JSON. It seems like having a wrong encoding.

![image](https://user-images.githubusercontent.com/28353492/220205333-3875fe7f-1715-45f5-b7c1-a514a5f815ec.png)

**Comment by zheng95z** [comment]
Any ideas?

**Comment by johannesjo** [comment]
The sync file is not meant to be directly imported if compressed (only manual exports are). You can try to decompress manually by using the same code/lib as used by the app: `src/app/core/compression/lz.worker.ts`
