### ISSUE TITLE
Change project for repeating task

### ISSUE THREAD

**Issue by arnoudhgz** [johannesjo/super-productivity#2493]
## Problem Statement
When creating a new repeating task you can select a project, but you can't change it afterwards.

**Comment by bytrangle** [comment]
I thought you can right click on the task, and select "Move to project" from the context menu?

**Comment by arnoudhgz** [comment]
@bytrangle  yes that works for normal tasks, **but not** for scheduled tasks

**Comment by arnoudhgz** [comment]
@bytrangle  sorry for the confusing, I meant **repeating** tasks instead of scheduled.

**Comment by easlinger** [comment]
I would also love this feature!
