### ISSUE TITLE
SyntaxError: Expected ',' or '}' after property value in JSON at position 7990

### ISSUE THREAD

**Issue by afyonluoglu** [johannesjo/super-productivity#2501]
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
undefined
```

### Meta Info
META: SP7.12.2 Browser – tr-TR – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

### Actions Before Error
```
1664540138524: [Tag] Update Work End for Tag (2) 
1664540138525: [Persistence] Save to DB (3) 
1664540138945: [Tag] Update Break Time for Tag 
1664540138946: [Persistence] Save to DB 
1664540139522: [Task] Add time spent 
1664540139523: [Tag] Update Work End for Tag (2) 
1664540139524: [Persistence] Save to DB (3) 
1664540140522: [Task] Add time spent 
1664540140523: [Tag] Update Work End for Tag (2) 
1664540140524: [Persistence] Save to DB (3) 
1664540141523: [Task] Add time spent 
1664540141524: [Tag] Update Work End for Tag (2) 
1664540141525: [Persistence] Save to DB (3) 
1664540142523: [Task] Add time spent 
1664540142526: [Tag] Update Work End for Tag (2) 
1664540142526: [Persistence] Save to DB (3) 
1664540143523: [Task] Add time spent 
1664540143524: [Tag] Update Work End for Tag (2) 
1664540143525: [Persistence] Save to DB (3) 
1664540144523: [Task] Add time spent 
1664540144524: [Tag] Update Work End for Tag (2) 
1664540144525: [Persistence] Save to DB (3) 
1664540145522: [Task] Add time spent 
1664540145523: [Tag] Update Work End for Tag (2) 
1664540145524: [Persistence] Save to DB (3) 
1664540146522: [Task] Add time spent 
1664540146524: [Tag] Update Work End for Tag (2) 
1664540146525: [Persistence] Save to DB (3) 
1677842445299: [SP_ALL] Load(import) all data 
1677842445301: [SP_ALL] All Data was loaded
```

**Comment by afyonluoglu** [comment]
Every time i launched the app (web or desktop version), the error message appears immediately (even i tried to restart the PC)

**Comment by johannesjo** [comment]
Thanks for reporting and sorry for the inconvenience! An error slipped into the turkish translation file. If you can change language in the back you should be fine. A patch release is on the way.

**Comment by afyonluoglu** [comment]
*Dear Johannes*

Thank you for your effort. My language was English but i again changed to
English in web version. Same error appears. Please see the screen shot of
the web-interface in the attachment.

Best regards

*Dr. Mustafa AFYONLUOGLU*
UN Digital Economy Expert
Cyber Security, E-Governance and E-Government Senior Expert
EU Capacity Development Key Expert

*"Information multiplies as it is shared" (afyonluoglu.org
<http://afyonluoglu.org>)*
Linkedin: http://linkedin.com/in/afyonluoglu
Twitter: http://twitter.com/#!/afyonluoglu
F: https://www.facebook.com/afyonluoglu
W: https://afyonluoglu.org



Johannes Millan ***@***.***>, 6 Mar 2023 Pzt, 17:54 tarihinde
şunu yazdı:
