### ISSUE TITLE
7.13.1 quit unexpectedly (Mac arm64)

### ISSUE THREAD

**Issue by jab-ac** [johannesjo/super-productivity#2503]
I had 7.12.2 installed and running without issue. Updated this morning to 7.13.1 using the .dmg and when I started the app it quit unexpectedly and now I can’t recover it. Tried uninstall and rolling back to previous version, now it’s stuck in a quit loop as well. Tried running it in Safe Mode, no dice. It appears to be complete hosed and I’ve no clue what to do next. Any ideas?

**Comment by jab-ac** [comment]
Sorry, I submitted the report from mobile and didn't see the standard format for bug reports, here it is:

**Your Environment**

Version used: 7.13.1
Operating System and version: MacOS 13.2.1

**Expected Behavior**

Copy new version from .dmg to Applications folder and replace the existing file for v7.12.2, then double-clicked to open and app should start up with existing data and preferences no problem.

**Current Behavior**

Immediately after copying the new version over the old one and starting the app, I received a generic error like "superProductivity quit unexpectedly." and an attempt to Reopen or Ignore and start again just results in the same error in an endless loop. 
 
**Steps to Reproduce (for bugs)**

No idea on another system, but no matter what I do now it reproduces every time I try to run the app. I tried downloading the previous version 7.12.2 which was running fine this morning and copying that back over, same error. Tried deleting the app completely removing all files/folders with it using AppCleaner, then install and run clean, same error. Did this multiple times with different versions, all same error. Tried installing from homebrew, same error. Tried clean and install in MacOS Safe Mode, same error. I'm completely stumped, it's like the upgrade corrupted some underlying system dependency which I can't see in the logs. Please help!!

**Can you reproduce this reliably?**

Yes

Error Log (Desktop only)

EDIT:
[main.log](https://github.com/johannesjo/super-productivity/files/10903639/main.log)

**Comment by jab-ac** [comment]
I can also send you the Apple Problem Reports directly if needed, I grabbed copies and saved but hesitate to post here.

**Comment by jab-ac** [comment]
Quick update: b/c my entire workflow for multiple clients revolves around this app for tracking hours to Jira, I kept troubleshooting with additional older versions, here's the results:
- Previously I had tried rolling back to version 7.12.2-arm64 via multiple instal methods, but all failed. 
- I went further back to version 7.11.6-arm64, and it finally started up again. 
- Tried upgrading from there to 7.12.2-arm64 installing by .dmg / replace and it failed again, same error "superProducivity quit unexpectedly". 
- Tried 7.12.2-Intel build installing by .dmg / replace over existing non-working -arm64 build and it worked. 
- Uninstalled with AppCleaner and went back to 7.11.6-arm64 installing by .dmg and then upgraded to 7.12.1-arm64 installing by .dmg / replace and it works.

Now that I think about it, I'm not 100% certain if I was previously running 7.12.2 as stated in original issue report, or whether it was maybe 7.12.1, I just know for sure it was 7.12.something. But it seems like something isn't right with the arm64 build of recent versions, at least on my system.

**Comment by johannesjo** [comment]
Hey @jab-ac ! Sorry to hear your having problems. Thank you very much for digging into this! It would be interesting to see what the output is, when starting the app from a terminal. Apart from that the only possible error source for this is electron, but I was unable to find some related issue (surely someone else must have had this problem). I updated electron to the latest version. Hopefully this fixes the issue.

**Comment by LordShedy** [comment]
Hi,

I have the same problem. 

After upgrading to version 7.13.1, I cannot open it because it crashes on startup. 

I am attaching a screenshot of the crash and the error log.

![Screenshot 2023-03-07 at 15 21 44](https://user-images.githubusercontent.com/1622827/223449882-2108d8d1-354d-41ec-b37f-e5734eb3779d.png)
[error.log](https://github.com/johannesjo/super-productivity/files/10910329/error.log)

**Comment by jab-ac** [comment]
> Hey @jab-ac ! Sorry to hear your having problems. Thank you very much for digging into this! It would be interesting to see what the output is, when starting the app from a terminal. Apart from that the only possible error source for this is electron, but I was unable to find some related issue (surely someone else must have had this problem). I updated electron to the latest version. Hopefully this fixes the issue.

Glad to help, I love this app!! I also suspected something to do with Electron, when I get done for the day I'll try the latest build again and update accordingly. Thanks!

**Comment by thinktapper** [comment]
I also experienced this issue when upgrading to 7.12.2 last month. Downgraded to 7.12.1 to fix temporarily

**Comment by markusTraber** [comment]
Same here.

**Comment by vicmosin** [comment]
Any estimates when it gets fixed in brew? Maybe as a separate cask or something? I find installing it separately is a bit annoying especially when one has to update it in the future.

**Comment by johannesjo** [comment]
Unfortunately I don't have the required hardware to test this, so someone else would need to have a look at it. PRs are welcome!!

**Comment by johannesjo** [comment]
Thanks @vicmosin ! We still would need help to properly set this up with cask.

**Comment by vicmosin** [comment]
@johannesjo do you have any docs how it's currently done?

**Comment by johannesjo** [comment]
No sorry @vicmosin . I didn't even set it up myself. This might give a little bit of a pointer:
https://github.com/johannesjo/super-productivity/issues/373
`brew bump-cask-pr superproductivity --version x.xx.xx`
https://github.com/orgs/Homebrew/discussions/561

**Comment by eshack94** [comment]
@johannesjo I am experiencing the same issue with the most recent version, 7.13.2 (Mac arm64). I have an M1 Pro MacBook.

No issues with the Intel version. This bug is preventing me from using the software. It looks like there's a segfault somewhere.

**Comment by pattkrajnik** [comment]
Same situation here, arm64 version later 7.11.5 installed with brew fails at startup on Macbook Pro 2022. On Macbook Pro 2015 with every new version works just fine.

**Comment by nathanstaton** [comment]
Same happening for me, the only mac arm64 version that works is 7.11.6

**Comment by jab-ac** [comment]
@johannesjo I'm still using the old 7.12.1 which is the last version I could run without this Electron bug crashing the app. Any update on when this will be fixed so that we can move to a newer version? Thanks again for all your hard work, still a great project!!

**Comment by thetric** [comment]
Interesting. I have built a version using the following commands:

```bash
npm run buildAllElectron:noTests:prod 
CSC_IDENTITY_AUTO_DISCOVERY=false electron-builder --mac mas --config=build/electron-builder.mas.yaml -c.mac.identity=null
```

and started it via `./app-builds/mas-arm64/Super\ Productivity.app/Contents/MacOS/Super\ Productivity` without issues.

Source: current `master`
Hardware: MacBook Pro (Apple M2 Pro)

**Comment by thetric** [comment]
According to https://github.com/electron/electron/issues/35355#issuecomment-1227574710 it might be necessary to add an entitlement. The Electron docs currently do not include this information.

**Comment by johannesjo** [comment]
The entitlement configs are located under `./build`. Anybody maybe willing to give the adjustment a shot and see if it works ? Should be the `entitlements.mac.plist` for the dev build (`npm run localInstall:mac`), if I am not mistaken.

**Comment by jab-ac** [comment]
I would give it a shot if I knew how, sorry I can't be of more help. That said, I saw the new version 7.15.0 and figured I'd give try it to see if there's any change, but the same issue occurs.

**Comment by therealstein** [comment]
same issue with 
**superProductivity-7.15.0-arm64.dmg** on M1

**Comment by noname77** [comment]
hey,

thanks for this great tool @johannesjo 

I experienced the same issue on my m1 mac and thought I'll give it a go. beware of the long post, I just dumped stuff as I did stuff.

## Steps

- clone the repo
```bash
git clone https://github.com/johannesjo/super-productivity.git
cd super-productivity
git log

commit 70d6aaa8eb42e064a893deaf4d4525f35c13b9e5 (HEAD -> master, origin/master, origin/HEAD)
Author: ProfXmas <profxmas@pm.me>
Date:   Thu Nov 23 21:31:25 2023 -0500

    Add trductions to Misc and Sound
```
- install dependencies
```bash
npm i -g @angular/cli
npm i
```
- modify the `./build/entitlements.mac.plist` as per https://github.com/electron/electron/issues/35355#issuecomment-1227574710, i.e. add the `com.apple.security.cs.allow-jit` key and set it to `<true/>`
```nano
<dict>
	<key>com.apple.security.cs.allow-unsigned-executable-memory</key>
	<true/>
	<key>com.apple.security.cs.disable-library-validation</key>
	<true/>
	<key>com.apple.security.cs.allow-jit</key>
	<true/>
</dict>
```

- build for Mac with
```bash
npm run localInstall:mac
```

<details>
  <summary>got a missing `embedded.provisionprofile` missing issue</summary>

```
> superProductivity@7.15.0 removeWOFF1
> node ./tools/remove-woff.js


> superProductivity@7.15.0 electron:build
> tsc -p electron/tsconfig.electron.json


  • electron-builder  version=24.6.4 os=22.6.0
  • loaded configuration  file=<PATH_ROOT>super-productivity/electron-builder.yaml
  • writing effective config  file=app-builds/builder-effective-config.yaml
  • packaging       platform=darwin arch=arm64 electron=25.9.0 appOutDir=app-builds/mac-arm64
  • downloading     url=https://github.com/electron/electron/releases/download/v25.9.0/electron-v25.9.0-darwin-arm64.zip size=88 MB parts=8
  • downloaded      url=https://github.com/electron/electron/releases/download/v25.9.0/electron-v25.9.0-darwin-arm64.zip duration=1m23.54s
  • signing         file=app-builds/mac-arm64/superProductivity.app identityName=Apple Development: My Name (some_id) identityHash=1234_some_hash provisioningProfile=embedded.provisionprofile
  ⨯ Command failed: security cms -D -i embedded.provisionprofile
security: unable to open "embedded.provisionprofile" for reading: No such file or directory
  failedTask=build stackTrace=Error: Command failed: security cms -D -i embedded.provisionprofile
security: unable to open "embedded.provisionprofile" for reading: No such file or directory
                                                                                                                                                                     at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:511:28)
    at maybeClose (node:internal/child_process:1098:16)
    at Socket.<anonymous> (node:internal/child_process:456:11)
    at Socket.emit (node:events:511:28)
    at Pipe.<anonymous> (node:net:334:12)
From previous event:
    at processImmediate (node:internal/timers:478:21)
From previous event:
    at readDirectoryAndSign (<PATH_ROOT>super-productivity/node_modules/app-builder-lib/src/macPackager.ts:467:29)
    at MacPackager.signApp (<PATH_ROOT>super-productivity/node_modules/app-builder-lib/src/macPackager.ts:477:11)
    at MacPackager.doSignAfterPack (<PATH_ROOT>super-productivity/node_modules/app-builder-lib/src/platformPackager.ts:332:21)
    at MacPackager.doPack (<PATH_ROOT>super-productivity/node_modules/app-builder-lib/src/platformPackager.ts:317:7)
    at MacPackager.pack (<PATH_ROOT>super-productivity/node_modules/app-builder-lib/src/macPackager.ts:196:7)
    at Packager.doBuild (<PATH_ROOT>super-productivity/node_modules/app-builder-lib/src/packager.ts:442:9)
    at executeFinally (<PATH_ROOT>super-productivity/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (<PATH_ROOT>super-productivity/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (<PATH_ROOT>super-productivity/node_modules/app-builder-lib/src/packager.ts:337:12)
    at executeFinally (<PATH_ROOT>super-productivity/node_modules/builder-util/src/promise.ts:12:14)
```

</details>

- get the provision file as per [some medium post](https://jondot.medium.com/shipping-electron-apps-to-mac-app-store-with-electron-builder-e960d46148ec)

- retry Mac build with
```bash
npm run localInstall:mac
```

**SUCCESS** -> app built to `app-builds/superProductivity-7.15.0-arm64.dmg` and when copied to `Applications` it launches successfully. 

though there seems to be an issue with copying to target destination, probably parenthesis missing in the `cp` command:
```bash
cp: app-builds/mac/Super Productivity.app/: No such file or directory
```

## additional reference

when I did `brew install --cask superproductivity` and updated from 7.12.0 to 7.15.0:
```
==> Upgrading 1 outdated package:
superproductivity 7.12.0 -> 7.15.0
```

I started to get the crashes, so I downgraded back to 7.12.1 with
```bash
brew install --cask https://raw.githubusercontent.com/Homebrew/homebrew-cask/11cbe12a582d4d67f6e77ece3e882148443c4e8c/Casks/superproductivity.rb
```
which got the app working again

I then tried to download the 7.15.0 arm64 (7.15.0-arm64.dmg) version from [releases](https://github.com/johannesjo/super-productivity/releases/download/v7.15.0/superProductivity-7.15.0-arm64.dmg) and installing manually -> same result, the app crashes at startup

I then tried to build myself as described at the top of this post -> **SUCCESS**, app is launching

for the sake of completeness, I reverted the `jit` setting and built the app again -> it did't crash either (which also aligns with [this](https://github.com/johannesjo/super-productivity/issues/2503#issuecomment-1712009498) comment), so unfortunately not sure if the change is what's doing the job or is it the fact that its built on an apple silicon mac 🤷 

best,
wiktor

**Comment by therealstein** [comment]
> <key>com.apple.security.cs.allow-jit</key>
> 	<true/>
thad did the trick. on  m1 macbook

**Comment by therealstein** [comment]
@johannesjo, I just did the same as @noname77 recommended. All kudos go to him!

**Comment by johannesjo** [comment]
The new release is out! Please let me know if it works for you:
https://github.com/johannesjo/super-productivity/releases/tag/v7.15.1

**Comment by jab-ac** [comment]
Just downloaded the new version 7.15.1 and copied it over the old version 7.12.1 which I've been running since this bug became an issue. It now starts up without crashing and is running as I write this, will monitor and report any further issues, but this looks VERY promising! Thanks to all who contributed to the fix, cheers!!

**Comment by johannesjo** [comment]
> Is this change intentional? Maybe an artifact on my local system? Interested, but not overly concerned, just happy to be able to update to the latest versions. Thanks to all who contributed to the fix, cheers!!

Not that I would be aware of. Maybe it's some change on electrons side of things? SP uses the OSs progresss bar feature, so that  might be it. If you create a task with "Some task 30m/1h" and start it, does the bar change?

**Comment by jab-ac** [comment]
Ah ok, that definitely has something to do with it, when I start a timer on a task that bar fills up. Maybe this has always been there and I just never noticed? Not sure, but obv not related to the new/fix version. So thanks (again)!!

> > Is this change intentional? Maybe an artifact on my local system? Interested, but not overly concerned, just happy to be able to update to the latest versions. Thanks to all who contributed to the fix, cheers!!
> 
> Not that I would be aware of. Maybe it's some change on electrons side of things? SP uses the OSs progresss bar feature, so that might be it. If you create a task with "Some task 30m/1h" and start it, does the bar change?

**Comment by jab-ac** [comment]
> > The new release is out! Please let me know if it works for you: https://github.com/johannesjo/super-productivity/releases/tag/v7.15.1
> 
> It works on MacBook Pro M2 with Mac OS Sonoma Version 14.1.1 (23B81).
> 
> Really thank you for making the app work again with Mac OS! I couldn't find anything close to it's quality while being OSS.

I second this entire comment wholeheartedly!

**Comment by pattkrajnik** [comment]
Works as a charm on M1 now :) Thanks

**Comment by team-epk** [comment]
MacBook Air M1/Monterey - up to date and back in business. Thanks so much!

**Comment by johannesjo** [comment]
Great to hear it! Thank you very much everyone and special thanks again to @noname77 !

**Comment by noname77** [comment]
sorry I didn't get back earlier, but glad to see others jump in with answers  :)

just installed the latest version with brew and happily running, thanks @johannesjo for the release!

and tbh, id say credit goes to @thetric for pointing to the solution in here https://github.com/johannesjo/super-productivity/issues/2503#issuecomment-1712038852 and to Johannes for making it dead simple to build this beauty :)

re the progress bar in the dock, its been there for a while for me, at least since 7.12.0
