### ISSUE TITLE
Going into overtime (don't stop the timer)

### ISSUE THREAD

**Issue by mitgitumgekippt** [johannesjo/super-productivity#2504]
## Problem Statement

To put it shortly: I would like an option, that the timer continues to time after the pomodoro-interval is over.

While working with super-productivity, I often do work which I can't (or don't want to) stop after 25min. At the same time, it is not enough for another 25min. I don't want to skip pomodoro-timers, as they are a good metric for me for my productiviy of the day. 
It helps also for another problem: Sometimes windows puts super-productivty into the background it freezes the application until it is put into the foreground again. So I would see, how much I worked in overtime.

## :grey_question: Possible Solution

An option overtime in the "Pomodoro Timer" option or intigrating it automatically into "Manuelly confirm next pomodoro session". Maybe add into the "You seccessfully finished session X" popup window the overtime itself.

**Comment by johannesjo** [comment]
Makes sense to me! PRs are welcome!

**Comment by timmillard** [comment]
This kind of feature was mentioned as something useful to implement recently in discussion #2587
