### ISSUE TITLE
Windows setup files are missing for the last release

### ISSUE THREAD

**Issue by frainz-de** [johannesjo/super-productivity#2507]
### Your Environment

- Version used: 7.13.1 for Windows

### Expected Behavior

The release contains both the standalone executable and the installer.

### Current Behavior

The release contains only the standalone executable

### Steps to Reproduce (for bugs)

1. Visit https://github.com/johannesjo/super-productivity/releases/tag/v7.13.1
2. Observe that the release has fewer assets than the previous ones.

**Comment by johannesjo** [comment]
They should be still there.
