### ISSUE TITLE
"Working today" time decreases after finishing day

### ISSUE THREAD

**Issue by ThePatrykolus** [johannesjo/super-productivity#2509]
### Your Environment

- Version used: 7.13.1 
- Operating System and version: Windows 10 Home 64-bit
- Desktop Environment: 
- Browser Name and version:  google chrome i guess, it is session of google chrome

### Expected Behavior

When you click "Finish day" at "Today" tab, and then "Save and go home" your "Working today" time doesn't change.

### Current Behavior
When you click "Finish day" at "Today" tab, and then "Save and go home" your "Working today" time decreases, I guess it decreases by the amount of time of fully finished tasks.

However maybe there is some logic behind this behaviour that is just unclear for me - I would be grateful if somebody would explain it to me.  

### Steps to Reproduce (for bugs)

1. Create task, set "Time spent" to 1h for today for it.
2. Check out and note down the amount of time at "Working today"
3. Click "Finish day" and then "Save and go home"
4. Check out the amount of time at "Working today" again

### Can you reproduce this reliably?

Yup

**Comment by johannesjo** [comment]
This is because archived tasks are not considered atm.
