### ISSUE TITLE
Timeline: Tracked time should not disappear after the task is done

### ISSUE THREAD

**Issue by artyhedgehog** [johannesjo/super-productivity#2511]
### Your Environment

- Version used: 7.13.1, web (https://app.super-productivity.com) 
- Operating System and version: MacOS Monterey 12.4
- Desktop Environment: - 
- Browser Name and version: Opera 96.0.4693.50 (arm64) 

### Expected Behavior

The pomodoro timer session is still displayed in the timeline after its task is marked as done.

### Current Behavior

The pomodoro timer session is missing from the timeline.

### Steps to Reproduce (for bugs)

1. create a task in a project (not sure if a project is necessary)
2. mark the task as "today" (not sure if necessary)
3. do a pomodoro timer session on the task (didn't check with simple timer)
4. go to "Timeline"
5. => the pomodoro timer session is shown in the timeline
6. get back to the task
7. complete the task
8. return to "Timeline"

### Can you reproduce this reliably?

Reproduces reliably each time I complete a task.

### Console Output

```
[Task] Update Task {task: {…}, type: '[Task] Update Task'}
action-logger.reducer.ts:11 [Persistence] Save to DB {dbKey: 'task', data: {…}, type: '[Persistence] Save to DB'}
sync-trigger.service.ts:210 __trigger_sync__ task
map-to-timeline-view-entries.ts:46 mapToViewEntries {tasks: Array(6), currentId: null, scheduledTasks: Array(0), workStartEndCfg: {…}, now: 1678640920191} {asString: '{"tasks":[{"id":"Ha9HOgRm4Mdertyqlj-dq","projectId…":"10:00","endTime":"23:00"},"now":1678640920191}'}
```

**Comment by artyhedgehog** [comment]
I may possibly try to figure out the issue myself, as the project seems to have nice DX and is relative to my expertise, though I'm not positive I will do so soon or if I succeed.

**Comment by johannesjo** [comment]
Let me know if you have any questions!
