### ISSUE TITLE
Remove Jira Issues from Backlog if already done

### ISSUE THREAD

**Issue by gufertum** [johannesjo/super-productivity#2517]
## Problem Statement
If a jira issue is getting resolved (set to done) in jira, it still resides in the backlog in SP.

## :grey_question: Possible Solution
Detect resolved issues and remove them from the backlog when syncing

**Comment by stephanepechard** [comment]
It seems that the Backlog is not just 'synced' but also persisted locally and not updated properly. IMO, it should reflect the current state of the given JQL request but it seems it never gets refreshed accordingly. Then if you don't use the right request on the first time, you get polluted by many useless tickets that you cannot purge (or I don't know how to do it).
So I think this ticket could be broader and states that the Backlog should always reflect the JQL defined in the settings. What do you think?

**Comment by johannesjo** [comment]
@stephanepechard that would be great!

**Comment by stephanepechard** [comment]
Here you go: #2632
