### ISSUE TITLE
JIRA Integration not handling ports correctly

### ISSUE THREAD

**Issue by marcolussetti** [johannesjo/super-productivity#253]
### Your Environment

* Version used: 2.13.6 (Setup EXE)
* Operating System and version: Windows 10
* Desktop Environment: N/A
* Browser Name and version: N/A 

### Expected Behavior

The app connects to the specified JIRA endpoint with the specified credentials.

### Current Behavior

The uri is manupulated in a way as to make it impossible for the connection to be affected.

Using the following test inputs:
**Host:** `https://subdomain.domain.com:1234`
**Email / Username:** test
**Token / Password:** test2

Resulting uri:
```
"https://[subdomain.domain.com:1234]:1234/rest/api/latest/issue/picker"
```

### Steps to Reproduce (for bugs)

1. Enter above info into JIRA integration fields
2. Save
3. Attempt to populate transitions for instance

### Console Output

```
jira-api.service.ts:334 JIRA_RESPONSE_ERROR {error: {…}, requestId: "KbbbF5os"}error: cause: {code: "ENOTFOUND", errno: "ENOTFOUND", hostname: "subdomain.domain.com:1234", syscall: "getaddrinfo"}error: {code: "ENOTFOUND", errno: "ENOTFOUND", hostname: "subdomain.domain.com:1234", syscall: "getaddrinfo"}message: "Error: getaddrinfo ENOTFOUND subdomain.domain.com:1234"name: "RequestError"options: auth: {pass: "test2", user: "test"}followAllRedirects: truejson: truemethod: "GET"qs: {currentJQL: "", query: "ITM-2", showSubTaskParent: true, showSubTasks: true}rejectUnauthorized: falseresolveWithFullResponse: falsesimple: trueuri: "https://[subdomain.domain.com:1234]:1234/rest/api/latest/issue/picker"__proto__: Object__proto__: ObjectrequestId: "KbbbF5os"__proto__: Object {transform: ƒ, resolve: ƒ, reject: ƒ, requestMethod: "issuePicker", clientRequest: {…}, …}

```

**Comment by marcolussetti** [comment]
I have tested with a real endpoint that this problem occurrs, and that if the uri is formatted as provided by the user the endpoint is accessible.

**Comment by johannesjo** [comment]
Thanks for reporting. I'll look into it!

**Comment by johannesjo** [comment]
This should hopefully be fixed with the next release. Please let me know if it isn't.
