### ISSUE TITLE
Sidebar not resizing and overlapping content

### ISSUE THREAD

**Issue by halloichbingunnar** [johannesjo/super-productivity#2533]
### Your Environment

- Version used: 7.13.1
- Operating System and version: Win10

### Current Behavior

Since last update, the sidebar doesn't resize automatically and cannot be hidden as well, when screen is wide enough that it is automatically shown.

![Screenshot 2023-03-23 091951](https://user-images.githubusercontent.com/64837252/227143743-f864993e-e677-4d62-becb-1a670a48376f.jpg)

### Steps to Reproduce (for bugs)

Is there all the time :)

**Comment by johannesjo** [comment]
Not sure if I understand this correctly, but this has always (or at least for a long time) been the case to my knowledge.

**Comment by halloichbingunnar** [comment]
I am pretty sure this behaviour is (kinda) new. The problem is not that the sidebar is automatically shown, the problem is that it is too big and you cannot resize it…

**Comment by johannesjo** [comment]
Could you maybe provide another (fulll-window) screenshot? I get the idea, that I am not getting the full picture :)

**Comment by halloichbingunnar** [comment]
Sorry, took me a while to respond – here a screenshot from my mac: 

<img width="1567" alt="Bildschirmfoto 2023-04-03 um 09 31 02" src="https://user-images.githubusercontent.com/64837252/229441385-240c9e19-228e-4c76-9cc2-2013ddff20c2.png">

**Comment by johannesjo** [comment]
Thank you!! I was able to reproduce this. Just to make sure we're dealing with the same issue: This is cured by resizing the window horizontally a little bit, right?

**Comment by halloichbingunnar** [comment]
Yes, indeed!

**Comment by johannesjo** [comment]
Should be fixed with the upcoming release. Thank you!!
