### ISSUE TITLE
Gitlab Integration: Open in Browser uses wrong URL if project id is used

### ISSUE THREAD

**Issue by Blackclaws** [johannesjo/super-productivity#2543]
### Your Environment

- Version used: snap  7.13.1
- Operating System and version: Ubuntu 22.04
- Desktop Environment: Xfce

### Expected Behavior

Open Browser on a Gitlab Issue should bring you to the issue

### Current Behavior

Open Browser brings you to a 404 page on Gitlab

### Steps to Reproduce (for bugs)

1. Add a project with gitlab integration, making sure to just use the project id instead of the path
2. Add an issue
3. Right click open in browser, the url will use the project id instead of the project path which gitlab can't resolve

### Can you reproduce this reliably?

Yes

**Comment by johannesjo** [comment]
PRs are welcome!

**Comment by hugaleno** [comment]
@johannesjo  Pull request to resolve fix this. 
#2571
