### ISSUE TITLE
Version in Apple Appstore shown as being very old (3.14)

### ISSUE THREAD

**Issue by fthommen** [johannesjo/super-productivity#2547]
This is not a technial bug, but maybe an Apple Appstore release issue... On the releases page (current release being 7.13.1), the users are referred to the Apple Appstore for the macOS version  of Superproductivity. However in the Appstore, the version is displayed as being extremely old (version 3.14):

![image](https://user-images.githubusercontent.com/279232/228509768-a1db08af-2593-41f1-8e19-07379bbdcfad.png)

This could already hold some users off from installing from the Appstore. However when installed, effectively the version shows as 7.11.5:

<img width="291" alt="image" src="https://user-images.githubusercontent.com/279232/228510113-6c958737-5a97-4f9f-a5da-9f597b91d8e9.png">

which is still not the newest version, but much better than 3.14, but there is now auto-update option.

- Is this a problem of the Apple appstore?
- Would you rather recommend to install from the Appstore or better manually from the DMG files provided here

**Comment by johannesjo** [comment]
Hi there! That's because it is very old. Mac Os publishing has cost me a tremendous amount of time while there are currently only a handful of users. For now I recommend to use the dmg and install it from there.
