### ISSUE TITLE
Square icon in the Microsoft Store release

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [johannesjo/super-productivity#2549]
### Your Environment

- Version used: 7.13.1
- Operating System and version: Windows 10 22H2 Build 19045.2728

### Expected Behavior

Round icon without the ugly square frame. Note that the icon looks fine if you install super-productivity manually by using one of the EXEs in the github releases.

### Current Behavior

![2023-04-01 06_57_29-](https://user-images.githubusercontent.com/46269721/229279419-bcb574ed-cc49-482b-8362-4dc32de33eb5.png)

### Steps to Reproduce (for bugs)

1. Install super productivty through the Microsoft Store
2. Open it

### Can you reproduce this reliably?

yes

### Console Output

N/A

### Error Log (Desktop only)

N/A

**Comment by johannesjo** [comment]
PRs are welcome!

**Comment by Sumit4482** [comment]
Hello @johannesjo 
Can you assign it to me?
I will try to do this.

**Comment by edwinsamodra** [comment]
this PR is still open
