### ISSUE TITLE
Critical Error After Sleeping Computer

### ISSUE THREAD

**Issue by Henry-Keys** [johannesjo/super-productivity#256]
### Environment

* Version used: 2.13.6 snap
* Operating System and version: Elementary OS 5.0 Juno
* Desktop Environment: Pantheon

### Current Behavior
The stacktrace below popped up probably after i suspended the computer (sleep instead of shutdown). I tried to restart the application and still happens.

> Error: Uncaught (in promise): Error: Parameter "key" required Error: Parameter "key" required at e.instant (file:///snap/superproductivity/460/resources/app.asar/dist/main.35efc4b2fcbb91061685.js:1:86524) at e. (file:///snap/superproductivity/460/resources/app.asar/dist/main.35efc4b2fcbb91061685.js:1:461277) at file:///snap/superproductivity/460/resources/app.asar/dist/main.35efc4b2fcbb91061685.js:1:460760 at Object.next (file:///snap/superproductivity/460/resources/app.asar/dist/main.35efc4b2fcbb91061685.js:1:460865) at file:///snap/superproductivity/460/resources/app.asar/dist/main.35efc4b2fcbb91061685.js:1:459801 at new e (file:///snap/superproductivity/460/resources/app.asar/dist/polyfills.5e3d71f3ce7c13bd5811.js:1:16671) at d (file:///snap/superproductivity/460/resources/app.asar/dist/main.35efc4b2fcbb91061685.js:1:459575) at e.notify (file:///snap/superproductivity/460/resources/app.asar/dist/main.35efc4b2fcbb91061685.js:1:461143) at t._showNotification (file:///snap/superproductivity/460/resources/app.asar/dist/main.35efc4b2fcbb91061685.js:1:1300862) at d (file:///snap/superproductivity/460/resources/app.asar/dist/main.35efc4b2fcbb91061685.js:1:442195)
> Error: Uncaught (in promise): Error: Parameter "key" required Error: Parameter "key" required at e.instant (file:///snap/superproductivity/460/resources/app.asar/dist/main.35efc4b2fcbb91061685.js:1:86524) at e. (file:///snap/superproductivity/460/resources/app.asar/dist/main.35efc4b2fcbb91061685.js:1:461277) at file:///snap/superproductivity/460/resources/app.asar/dist/main.35efc4b2fcbb91061685.js:1:460760 at Object.next (file:///snap/superproductivity/460/resources/app.asar/dist/main.35efc4b2fcbb91061685.js:1:460865) at file:///snap/superproductivity/460/resources/app.asar/dist/main.35efc4b2fcbb91061685.js:1:459801 at new e (file:///snap/superproductivity/460/resources/app.asar/dist/polyfills.5e3d71f3ce7c13bd5811.js:1:16671) at d (file:///snap/superproductivity/460/resources/app.asar/dist/main.35efc4b2fcbb91061685.js:1:459575) at e.notify (file:///snap/superproductivity/460/resources/app.asar/dist/main.35efc4b2fcbb91061685.js:1:461143) at t._showNotification (file:///snap/superproductivity/460/resources/app.asar/dist/main.35efc4b2fcbb91061685.js:1:1300862) at d (file:///snap/superproductivity/460/resources/app.asar/dist/main.35efc4b2fcbb91061685.js:1:442195) at D (file:///snap/superproductivity/460/resources/app.asar/dist/polyfills.5e3d71f3ce7c13bd5811.js:1:15714) at D (file:///snap/superproductivity/460/resources/app.asar/dist/polyfills.5e3d71f3ce7c13bd5811.js:1:15270) at file:///snap/superproductivity/460/resources/app.asar/dist/polyfills.5e3d71f3ce7c13bd5811.js:1:16503 at t.invokeTask (file:///snap/superproductivity/460/resources/app.asar/dist/polyfills.5e3d71f3ce7c13bd5811.js:1:9963) at Object.onInvokeTask (file:///snap/superproductivity/460/resources/app.asar/dist/main.35efc4b2fcbb91061685.js:1:323553) at t.invokeTask (file:///snap/superproductivity/460/resources/app.asar/dist/polyfills.5e3d71f3ce7c13bd5811.js:1:9884) at e.runTask (file:///snap/superproductivity/460/resources/app.asar/dist/polyfills.5e3d71f3ce7c13bd5811.js:1:5145) at d (file:///snap/superproductivity/460/resources/app.asar/dist/polyfills.5e3d71f3ce7c13bd5811.js:1:12230) at e.invokeTask [as invoke] (file:///snap/superproductivity/460/resources/app.asar/dist/polyfills.5e3d71f3ce7c13bd5811.js:1:11075) at b (file:///snap/superproductivity/460/resources/app.asar/dist/polyfills.5e3d71f3ce7c13bd5811.js:1:24295)
> 

### Steps to Reproduce (for bugs)

1. Create a TODO List
2. Finish some tasks (but not all of them)
3. Click "Finish Day"
4. Sleep the computer

### Console Output
```javascript
global-error-handler.class.ts:77 GLOBAL_ERROR_HANDLER Error: Uncaught (in promise): Error: Parameter "key" required
Error: Parameter "key" required
    at e.instant (ngx-translate-core.js.pre-build-optimizer.js:1033)
    at e.<anonymous> (notify.service.ts:27)
    at notify.service.ts.pre-build-optimizer.js:42
    at Object.next (notify.service.ts.pre-build-optimizer.js:23)
    at notify.service.ts.pre-build-optimizer.js:17
    at new e (zone.js.pre-build-optimizer.js:931)
    at d (notify.service.ts.pre-build-optimizer.js:13)
    at e.notify (notify.service.ts.pre-build-optimizer.js:72)
    at t._showNotification (reminder.service.ts:157)
    at d (index.esm.js:67)
    at D (zone.js.pre-build-optimizer.js:852)
    at D (zone.js.pre-build-optimizer.js:809)
    at zone.js.pre-build-optimizer.js:913
    at t.invokeTask (zone.js.pre-build-optimizer.js:423)
    at Object.onInvokeTask (core.js.pre-build-optimizer.js:26246)
    at t.invokeTask (zone.js.pre-build-optimizer.js:422)
    at e.runTask (zone.js.pre-build-optimizer.js:195)
    at d (zone.js.pre-build-optimizer.js:601)
    at e.invokeTask [as invoke] (zone.js.pre-build-optimizer.js:502)
    at b (zone.js.pre-build-optimizer.js:1693)
e.handleError @ global-error-handler.class.ts:77
zone.js.pre-build-optimizer.js:199 Uncaught Error: Uncaught (in promise): Error: Parameter "key" required
Error: Parameter "key" required
    at e.instant (ngx-translate-core.js.pre-build-optimizer.js:1033)
    at e.<anonymous> (notify.service.ts:27)
    at notify.service.ts.pre-build-optimizer.js:42
    at Object.next (notify.service.ts.pre-build-optimizer.js:23)
    at notify.service.ts.pre-build-optimizer.js:17
    at new e (zone.js.pre-build-optimizer.js:931)
    at d (notify.service.ts.pre-build-optimizer.js:13)
    at e.notify (notify.service.ts.pre-build-optimizer.js:72)
    at t._showNotification (reminder.service.ts:157)
    at d (index.esm.js:67)
    at D (zone.js.pre-build-optimizer.js:852)
    at D (zone.js.pre-build-optimizer.js:809)
    at zone.js.pre-build-optimizer.js:913
    at t.invokeTask (zone.js.pre-build-optimizer.js:423)
    at Object.onInvokeTask (core.js.pre-build-optimizer.js:26246)
    at t.invokeTask (zone.js.pre-build-optimizer.js:422)
    at e.runTask (zone.js.pre-build-optimizer.js:195)
    at d (zone.js.pre-build-optimizer.js:601)
    at e.invokeTask [as invoke] (zone.js.pre-build-optimizer.js:502)
    at b (zone.js.pre-build-optimizer.js:1693)
```

### Error Log (Desktop only)
There's no superProductivity directory at this location: **~/.config**

**Comment by johannesjo** [comment]
Thank you very much for reporting. I'll look into it!

**Comment by johannesjo** [comment]
May I ask what language you are using?

**Comment by Henry-Keys** [comment]
> May I ask what language you are using? This seems to be related to the translation stuff somehow.
System language: English (US)
Keyboard language: English (US) and Portuguese (PT)

**Comment by Henry-Keys** [comment]
I can't replicate the bug unfortunately, but i'll keep trying and keep you posted.

**Comment by johannesjo** [comment]
Hm weird. With English it shouldn't be an issue. I released a new version. Please let me know if the issue reoccurs with that one.

**Comment by johannesjo** [comment]
I hope it's alright if I am closing this. Please let me know, if the error persists, or if you encounter any other problems.
