### ISSUE TITLE
Value based trackers

### ISSUE THREAD

**Issue by AriaMoradi** [johannesjo/super-productivity#2566]
## Problem Statement

I need to track things throughout the day and collect metrics from them, this can integrate with simple counters ane become a tracking section. 

## :grey_question: Possible Solution

A value based tracking has a title, a value type (string, number, fixed point number, time, etc) and then you can enter the value for today according to what type it is. 
## :arrow_heading_up: Describe alternatives you've considered

Tracking without a value type as a simpler version is also useful, in this situation the user can only input numbers

## :heavy_plus_sign: Additional context

Examples of what to track would be, tracking weight each day, how much I spent on junk food today, what type of clothing I wore today.

**Comment by timmillard** [comment]
I think this sounds like a useful feature to implement, could be useful for students like me who have to budget. Maybe the quantitative metrics gathered could be visualised and plotted graphically as time progresses to inspire productivity?

**Comment by AriaMoradi** [comment]
still relevant.
