### ISSUE TITLE
Error while login to google drive from snap version

### ISSUE THREAD

**Issue by gartorware** [johannesjo/super-productivity#258]
### Your Environment

* Version used: snap 2.13.9
* Operating System and version: Ubuntu 19.10
* Desktop Environment: gnome-shell
* Browser Name and version: --

### Expected Behavior
Google drive sync should allow login

### Current Behavior
Login to my google account get rejected because of not supported browser. Google message:

> You are trying to sign in from a browser or app that doesn't allow us to keep your account secure.
Try using a different browser.

Just tried the webapp version and it allows me to login successfully. Maybe related to electron embedded webview?

### Steps to Reproduce (for bugs)
1. Install snap app, either from snap store or from ubuntu software center
2. Go to Settings -> Sync via google drive and try to log in
3. Error!

### Console Output
No, since this is related to google oauth requirements.

### Error Log (Desktop only)
Error occurs in a new chrome popup window, not in the app itself.

**Comment by johannesjo** [comment]
Thanks for reporting. I will check this this Friday!

**Comment by johannesjo** [comment]
I just checked in on a vm with a fresh install. No such issue for me. Don't know... Can anybody else reproduce this?

**Comment by gartorware** [comment]
Weird, I can reproduce this every time. I have been reading. It seems like google blocks oauth requests made via embedded browsers. Is google oauth popup opening inside electron webview for you? Maybe this is related not to the app itself but to OS. I'm going to try it in windows and report back. (windows version is based on electron as well, right?)

**Comment by gartorware** [comment]
Just checked it. Same error on windows version. But... I have then tried with another google account and it's working! So is something related to google account... 

I'm going to check google security preferences in both accounts to find differences.

**Comment by gartorware** [comment]
Ok, managed to get it working changing the user agent. 

Steps to get it working:
1. Open login popup (clicking in Login button from Settings)
2. Inside that popup open Developer Tools (using the header toolbar)
3. Click on the menu button with three vertical dots
4. In the menu, choose More tools - Network conditions
5. In User agent section, disable the option Select automatically and select Chrome for Android
6. Reload popup (again using the header toolbar)
7. Login

Searching on the web there are a few users affected by this on last 2 months... Pretty weird that some accounts works but others doesn't... If this is really a rolling update maybe more users will be affected in the future.

This issue can be closed for me, but I let you decide if you want further investigate it. I'll be glad to help!

**Comment by johannesjo** [comment]
Thank you very much for digging into this! That's very helpful and I am quite happy that I didn't have to do all this research :) 

I will try setting the user agent to desktop chrome for the popup. Hopefully this fixes the issue.

**Comment by gartorware** [comment]
Hi, 
I can confirm that v2.13.14 is working now with my account. 

Thank you very much!

**Comment by johannesjo** [comment]
That's great! Thank you very much!

**Comment by josh83abc** [comment]
Hey guys! I am using NWJS and I have the same problem as this post. I was not able to fix it with userAgent though...

**Comment by jobbio** [comment]
I just ran into this issue with 6.3.3 on Windows 10

**Comment by UnmeshDeshpande** [comment]
Same issue on Ubuntu Budgie 20.04. It says the browser is not secure. Is there a way to open it through chrome or some other desktop?

**Comment by johannesjo** [comment]
There is a new issue to track progress on this:
https://github.com/johannesjo/super-productivity/issues/782

Seems like google changed something on their end again :-(
