### ISSUE TITLE
Lack of "saturday" in start of the week settings #bug

### ISSUE THREAD

**Issue by hamedkvs** [johannesjo/super-productivity#2581]
The title says it all: in the "settings > Misc Settings > First day of the week" all week days are present except for "Saturday" which is the first day of the week in some countries like Iran.

**Comment by AriaMoradi** [comment]
It is the last option in the list, you just have to scroll the list a little bit.

**Comment by johannesjo** [comment]
Not ideal that we have to scroll the list. A PR dealing with that would be welcome!
