### ISSUE TITLE
Break Reminder is not locking PC screen. Is it right?

### ISSUE THREAD

**Issue by nonMystery** [johannesjo/super-productivity#259]
Fedora 31, x64, Plasma, X11.

When I set reminder to 1min, for test porpose, it doesnt lock PC screen, it just show a notification. Is it right? It not supposed to lock PC screen for a while til timer gets the end?

**Comment by johannesjo** [comment]
The screen doesn't lock right away. It gives you some 30 seconds to react to the banner popping up. Does it still not show up, after this delay?

**Comment by nonMystery** [comment]
@johannesjo If i dont interact with  the popup, it still, but screen does not get locked. When I interact with the popup, both option, it disappear and reappear after some time. But the screen still unlocked.

**Comment by johannesjo** [comment]
Thank you! I will check this!

**Comment by nonMystery** [comment]
Ok. You wrote a really good software! I really thank you! You software is F. amazing!

**Comment by johannesjo** [comment]
@nonMystery that's great to hear. Please let me know, if you have any suggestions to improve it :)

**Comment by nonMystery** [comment]
@johannesjo It works really well on the newest version! Thanks! Have a great weekend!
