### ISSUE TITLE
Ending or minimizing selected applications during a work session 

### ISSUE THREAD

**Issue by BEST8OY** [johannesjo/super-productivity#2592]
## Problem Statement
Well, I get distracted by using other applications during a session I need to focus on something, so I need a force to stop me from this distraction :)

## :grey_question: Possible Solution
Adding applications and software to a blocklist to minimize or close (End task, Force close, ...) those applications during work sessions.

## :heavy_plus_sign: Additional context
An existing application with this functionality is this software [Cold Turkey](https://getcoldturkey.com/) but it's closed source and paid :)

**Comment by johannesjo** [comment]
Thanks for opening this up. I like the idea, but I think it's better suited to have its own dedicated application.

**Comment by BEST8OY** [comment]
It would have been nice if people could make extensions for Super productivity, but I guess it did not go that road so it's probably impossible right now to make the app modular.
Anyway, I close the issue.

**Comment by johannesjo** [comment]
Yes having some sort of extension system would be nice! :)
