### ISSUE TITLE
Repeated task to spawn when previous iteration is complete

### ISSUE THREAD

**Issue by drspleen** [johannesjo/super-productivity#2594]
Great program you guys have here, has just the right balance between simplicity and complexity to help my productivity without dragging me into  endless loops of boards and timelines.
## Problem Statement
One small thing that annoys me is upcoming "repeated" tasks don't show up in the scheduled tasks list until they spawn on the date they are set for. I want to see what future tasks are coming up including upcoming repeats. 

## :grey_question: Possible Solution
A simple solution would be to just have the next repeat spawn when the previous one is marked as done. 

## :arrow_heading_up: Describe alternatives you've considered
When creating a repeated task, there could be a few options on how to do it:
1. as above - that's probably the simplest for ongoing tasks. 
2. for time limited tasks (e.g. check this every other day for the expected duration of the project) it may give the option to spawn all tasks when you create it. 

## :heavy_plus_sign: Additional context
None.

**Comment by johannesjo** [comment]
This is to avoid many instances of a task being created at the same time, when a user hasn't used the app in a longer time. Maybe this can be improved by opening a special dialog for cases when there would be more than 1 repeated task instance created at the same time.

**Comment by drspleen** [comment]
Can you explain a bit more about the special dialog? I'm not sure I
understand. I didn't want more than one instance of any task to appear.

I just want the next instance to be visible in the scheduled/timeline
views. Helps with planning if I can see tasks coming up. Only needs to be
one instance.

**Comment by johannesjo** [comment]
Just figured that I misread your proposal. You'd like to spawn repeating tasks always when the previous instance is marked as done, right? Does that mean you want to spawn them no matter when it would be normally be scheduled to appear?

**Comment by drspleen** [comment]
I am realising I may have been mistaken in my proposal. Let me try and
break it down a bit better:

I have a number of repeating tasks at various time intervals.
I want to see when these tasks are going to come up, to help me when I am
planning my week/month ahead (using timeline or scheduled views).

I have had a few problems:
Only some of them seem to appear in the timeline view (as the greyed out
boxes), others just appear randomly
Sometimes they don't seem to spawn. This has caused me a bunch of issues
with tasks getting missed because they just hadn't spawned on the date, and
by the time I realise it is too late.

I think my initial idea was just treating this as a spawning issue. But the
more I have thought about it the more I think it is about being able to
visualise the repeating tasks and factor them into my planning.

Sorry, I hope this makes sense.

**Comment by johannesjo** [comment]
If the tasks don't appear in the timeline when they should then this might actually be a bug. Can you provide a bit more info on this?

Also sounds like this might be your main problem? Or is there something else?

**Comment by drspleen** [comment]
I have lots of repeating tasks - some weekly, some monthly, some
three monthly, some annually - and they use a variety of different configs
- though most common is the custom repeat config.

I only have one of them show up in the timeline - it has a custom repeat
config of Repeat every 2 weeks and it was ticked on Friday. - but it only
appears in the timeline twice. Then no more.

None of the rest of them seem to be showing up in the timeline, but I had
some spawn the other day, so they are there.

Sorry for the lack of info, but I am unable to tell what repeating tasks I
have active as I can't see them. So I can't explore what configs they're
using.

A few thoughts I had:
Its possible I set the first instance of the repeating task to occur in the
past (e.g. Every month on the first of the month starting 1 May 2023), I
wondered if this may have caused any issues?

**Comment by drspleen** [comment]
I should note - that when I say "only one appears in the timeline" that's
in the greyed out box. That links directly to the repeat config.

**Comment by johannesjo** [comment]
> Sorry for the lack of info, but I am unable to tell what repeating tasks I have active as I can't see them. So I can't explore what configs they're using.

Does that mean taht repeating tasks also don't show up on the scheduled page?

**Comment by johannesjo** [comment]
In any case. Maybe a data export would be helpful.

It would be great if you could share a copy of your data to contact@super-productivity.com, so I can debug this on my computer. You can create an export by navigating to "Settings" and then to "Import/Export" or you can use the "Export data" button from the error Dialog (there is also a button there which will anonymize the data before exporting).

**Comment by drspleen** [comment]
I had a look at it, and I think it's not relevant
