### ISSUE TITLE
Being able to edit the start/end time

### ISSUE THREAD

**Issue by Gontran08** [johannesjo/super-productivity#26]
## Your Environment

* Version used: 1.4.0
* Operating System and version: Ubuntu 17.10
* Desktop Environment: Gnome (default)

## Expected Behavior
It would be interesting to be able to see the start/end time for a task. I'm thinking about something similar to Toggl. I would like to know at which time I started/ended my task and be able to edit it. Example, if a forget to stop the timer before lunch, I would be able to set the end time to 12h00 and start the timer again without having to think how long I was gone. I personally don't need to list each time frames, but it could be useful to list them all.

## Current Behavior
Currently, we can only change the time spent, not the start/end time.

**Comment by johannesjo** [comment]
Thanks for the suggestion! Both values are already saved. It should be easy to add field to the time estimations dialog for example. What is much more complicated is manipulating the time spent on a task. Currently the data model is simplified to just track the total amount of time and the total amount of time spend on a particular day. But saving every single period you worked on a task would possibly generate a lot of data (and make the app slower) and also some edge cases I'd rather not want to deal with ;)

There is a feature already implemented though. If you're idle for 5 minutes, the app will ask you, if you want to track that time or not, once your back.

**Comment by Gontran08** [comment]
With my use case, I probabbly could use a subtask for each period. Would it be easier ?

**Comment by johannesjo** [comment]
Maybe I did not understand you correctly. What would you need the periods for? For the use case you described (forgetting to stop tracking time, which should be covered by the idle tracking from my point of view) or also for something else.

**Comment by Gontran08** [comment]
I'm not necessarily idle, I may be on an another project and forgot to change the timer. So I would like to be able to stop the timer, set the end time approximately and create a new task which I would set the start time with the same value.

Sorry if I'm not clear.

**Comment by johannesjo** [comment]
Thanks for the clarification! As mentioned before adding this feature would require a huge rewrite of lots of the logic (and it would slow down the application and there are lots of edge cases and also migration scenarios to think about). So I'm sorry to say that a feature like this is unlikely to be implemented any time soon.
