### ISSUE TITLE
Option for always on top during a session with a better UI

### ISSUE THREAD

**Issue by BEST8OY** [johannesjo/super-productivity#2607]
## Problem Statement
I want to have the time in front of me

## :grey_question: Possible Solution
Add option for always on top during a session with a better UI for smallest Super-Productivity display
Windows 11 Clock vs Super-Productivity
![Windows 11 Clock vs Super-Productivity](https://user-images.githubusercontent.com/70865987/236696486-8cdbc022-b9f1-4294-9330-786b3c8fd8c3.png)

**Comment by johannesjo** [comment]
I am open for adding this as an opt in feature!

**Comment by beewry** [comment]
Something like this would be **_huge_** for me. The mini-timer is the only reason that I use toggl.

I need to see my current task name and the time spent on my screen at all times to pull me back when I get distracted. Having this as an opt in feature would be fantastic.

**Comment by johannesjo** [comment]
Should be relatively straightforward to implement:
https://github.com/electron/electron/blob/main/docs/api/browser-window.md#winsetalwaysontopflag-level-relativelevel

Someone wants to give it a shot?

**Comment by jcrben** [comment]
Another idea to add to the list: integrate it into the Windows taskbar. I noticed https://github.com/leandrosa81/taskbar-monitor which uses https://github.com/dsafa/CSDeskBand - of course that opens up a lot of additional complexity and is Windows-specific.
