### ISSUE TITLE
Not able to find 12hr time format

### ISSUE THREAD

**Issue by Ansh4011** [johannesjo/super-productivity#2610]
### Your Environment

- Version used:  latest as of 10 may
- Operating System and version: windows 10 

### Expected Behavior

Not able to find 12hr time format anywhere in the settings, idk if this is a bug or a not yet implemented thing though I assume it's pretty basic, wasn't able to look for any relevant issue either. 
Thanks, have a good day!

**Comment by johannesjo** [comment]
Hey there! This should be dependant on your system settings. Do you have 12h format configured there?
