### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'start')

### ISSUE THREAD

**Issue by OthmanAbdelbaset** [johannesjo/super-productivity#2611]
### Steps to Reproduce

1.add calendar shareable link and save, that broke the app
2.
3.
4.

### Stacktrace
```
isSameDay (webpack:///src/app/features/timeline/map-timeline-data/map-to-timeline-view-entries.ts:185:49)
unPlanned (webpack:///src/app/features/timeline/timeline.component.ts:93:8)
_next (webpack:///node_modules/rxjs/_esm2015/internal/operators/map.js:29:34)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)
this.clearDebounce (webpack:///node_modules/rxjs/_esm2015/internal/operators/debounceTime.js:40:29)
dispatchNext (webpack:///node_modules/rxjs/_esm2015/internal/operators/debounceTime.js:53:15)
_execute (webpack:///node_modules/rxjs/_esm2015/internal/scheduler/AsyncAction.js:51:17)
execute (webpack:///node_modules/rxjs/_esm2015/internal/scheduler/AsyncAction.js:39:27)
action.execute (webpack:///node_modules/rxjs/_esm2015/internal/scheduler/AsyncScheduler.js:33:31)
timer (webpack:///node_modules/zone.js/fesm2015/zone.js:2561:40)
```

### Meta Info
META: SP7.11.5 Electron – en-GB – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.11.5 Chrome/100.0.4896.75 Electron/18.0.4 Safari/537.36

### Actions Before Error
```
1683735947570: [SP_ALL] Load(import) all data 
1683735947575: [SP_ALL] All Data was loaded 
1683735954062: [Layout] Toggle SideBar 
1683736162317: [Project] Add Project 
1683736162326: [Persistence] Save to DB 
1683736178013: [Project] Delete Project 
1683736178021: [Persistence] Save to DB 
1683736178021: [Persistence] Remove from DB 
1683736178054: [Task] Delete Tasks 
1683736178071: [Persistence] Save to DB (3) 
1683736180348: [WorkContext] Set Active Work Context 
1683736180350: [Task] SetSelectedTask 
1683736329516: [Global Config] Update Global Config Section 
1683736329554: [Persistence] Save to DB 
1683736343667: [SP_ALL] Load(import) all data 
1683736343671: [SP_ALL] All Data was loaded 
1683736343701: [WorkContext] Set Active Work Context 
1683736343703: [Task] SetSelectedTask
```

**Comment by johannesjo** [comment]
Thank you very much for reporting this! Unfortunately I am unable to reproduce this. Could you maybe help me with this. To do so I would need you to:
1. Start the app
2. Open up the console (Ctrl+Shift+i)
3. Navigate to the timeline
4. Scroll up the console just shortly before the error.
5. Copy the complete string behind `asString` as shown in the screenshot  
6. Send it to contact@super-productiviy.com via email

**BEWARE**: The string you send to me might contain personal data from your tasks or calendar! If you don't feel comfortable with this I can completely undestand.

![Screenshot from 2023-05-12 16-08-45](https://github.com/johannesjo/super-productivity/assets/1456265/ed4a8bcb-bf91-4cf9-8616-cb4c7670406b)
