### ISSUE TITLE
Could you please automate updates of the winget manifests alongside your releases?

### ISSUE THREAD

**Issue by exoosh** [johannesjo/super-productivity#2618]
## Problem Statement

I prefer using `winget` for installation and upgrading of software for Windows, whenever an application is available. Your application [is available](https://github.com/microsoft/winget-pkgs/tree/master/manifests/j/JohannesMillan/superProductivity/) -- albeit maintained by someone else. But the manifest seems to be updated manually. For now, I [created a PR to get 7.13.2 into `winget`](https://github.com/microsoft/winget-pkgs/pull/106907) _manually_.

One issue with your current releases is that -- yes the `latest.yml` exists and contains (Base64 encoded) SHA512 hashes -- it is time-consuming and error-prone to pick the hash values out of the `latest.yml`, decode them, then compare them against the downloaded file.

## :grey_question: Possible Solution

You could use [winget-releaser](https://github.com/vedantmgoyal2009/winget-releaser) to automate the creation of PRs whenever you release a new version. [This tool](https://bittu.eu.org/docs/wr-playground/) may be helpful, performing just a dry-run.

## :arrow_heading_up: Describe alternatives you've considered

Currently manual download, verification and installation is required. `winget search` does _not_ list the Microsoft Store entry (normally it should, however).

**Comment by exoosh** [comment]
Btw, the following values would have to be used [in the playground link](https://bittu.eu.org/docs/wr-playground/), if you want to try it:

* Identifier: `JohannesMillan.superProductivity`
* Installer Regex: `superProductivity-Setup-\d+\.\d+\.\d+(-arm64|-x64)?\.exe$`
* Repository: `johannesjo/super-productivity`

**Comment by johannesjo** [comment]
A PR would be great. 

Sorry, but there is already much more stuff to do than I can ever possibly handle. I have to prioritize. Thanks for your understanding.
