### ISSUE TITLE
Which Icons are avaible

### ISSUE THREAD

**Issue by AmphoMoronal** [johannesjo/super-productivity#2622]
## Problem Statement

In the Counter Section in the Settings you can set Icons which are displayed when you the Counter is toggled or not. But I don't know which Icon are available

## :grey_question: Possible Solution

Create a list of available Icons in your Webpage/GitHub/App

## :arrow_heading_up: Describe alternatives you've considered

Maybe enable to insert Emojis there or an popup menu which Icon/Emoji you can insert

**Comment by johannesjo** [comment]
The icons should be shown once you start typing the name. A full list can also be found here:
https://fonts.google.com/icons?icon.style=Rounded

**Comment by AmphoMoronal** [comment]
Thanks 👍🏼
