### ISSUE TITLE
Two way sync with OpenProject.

### ISSUE THREAD

**Issue by ckvtz** [johannesjo/super-productivity#2625]
## Problem Statement

Enable two way sync with OpenProject instance

## :grey_question: Possible Solution

Polling to update data both ways

## :arrow_heading_up: Describe alternatives you've considered

Manually updating Work packages updates in OpenProject

## :heavy_plus_sign: Additional context

None

**Comment by ckvtz** [comment]
Thank you for your response.

I did not mention it as a bug, rather suggested an enhancement to make it extremely useful tool to manage projects for those who use the a self hosted community version of OpenProject.

**Comment by beedell-roke** [comment]
> [`#issuecomment-1726761053`](https://github.com/johannesjo/super-productivity/issues/2625#issuecomment-1726761053)

It's relevant, @github-actions. Most people are solely subscribed to major issue events, though, so this stale system doesn't work.

**Comment by nixall1** [comment]
It would be truly useful to have synchronization between OpenProject’s tasks and projects. This way, OpenProject could serve as a hub for team management and an overall overview, while SuperProductivity could be used as a personal work tool for each team member
