### ISSUE TITLE
Snap! A critical error occurred...

### ISSUE THREAD

**Issue by sasogu** [johannesjo/super-productivity#263]
### Your Environment

* Version used: 
* Operating System and version:
* Desktop Environment: 
* Browser Name and version: 

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by johannesjo** [comment]
@sasogu thanks for reporting! Could you maybe provide a little bit more info?

**Comment by johannesjo** [comment]
Closed due to inactivity.
