### ISSUE TITLE
Cannot hover and select skip and stop timer

### ISSUE THREAD

**Issue by Mindstormer619** [johannesjo/super-productivity#264]
With the Pomodoro timer setting enabled, on the latest stable version I can no longer hover over the timer Play (▶️) button and select the Stop (⏹️) or Skip buttons. Previously they would remain on screen for a few seconds before collapsing back into the Play button, but now they collapse back _immediately_ upon moving the mouse away from the Play button. 

- **Version:** 3.0.1
- **Variant:** PWA on app.super-productivity.com
- **OS:** Windows 10
- **Browser:** Chrome v79.0 32-bit

**Comment by Jaimies** [comment]
Same issue here:
* **Version**: 3.0.3
* **Operating system** : Ubuntu 18.04.3
* **Desktop environment**: Gnome

**Comment by johannesjo** [comment]
Thanks for reporting! I look into it!

**Comment by johannesjo** [comment]
Should be fixed with 3.0.4

**Comment by Mindstormer619** [comment]
Can confirm. Thanks! :smile:
