### ISSUE TITLE
Format date as dd/mm

### ISSUE THREAD

**Issue by sabrinaweb** [johannesjo/super-productivity#2641]
## Problem Statement

Dear staff,
maybe someone has already asked that, but I can't find the issue. Is it possible to have an option to show dates in European format (dd/mm)? Or at least the month in letters rather than numbers? The American format is misleading foir me

**Comment by Nergatar** [comment]
This is a request that should improve the international users that is not using the US date format. As stated in the opening post, it's confusing.

**Comment by azzamsa** [comment]
Yes. It is hard for me to read the date time format. Should we open a new issue as this was closed?
