### ISSUE TITLE
Better visual organization

### ISSUE THREAD

**Issue by dmyna** [johannesjo/super-productivity#2656]
> I don't know if something like this has already been asked in pull requests because I couldn't find anything related, but here goes.

## Problem Statement
I use SuperProductivity for almost everything, but I miss some things.

The app is perfect when it comes to task organization, time management and task statistics. However, from my experience with it (I've been using it since 09/09/22 and evangelize its use to my friends, I practically became a fan lol) I end up noticing that when the use of simple tasks increases and I only work for various types of things — for example, I record practically all the tasks, even my sleep time and what I spent resting or preparing something, I always try to close the day with 24 hours spent and I monitor the types by tags — it ends up being "overloaded" in terms of visualization/interface.

I like to use the main (today) tab to orient myself through the day and know exactly what I have to do—thanks a lot for that, by the way. Thanks to the use of this app and other external things, I became an extremely productive and organized person :) — but since I have a lot of repetitive tasks (more than 20) and things that take less than 10 seconds to do, which are practically habits that I can't forget, this ends up weighing on the visualization.
Imagine your home tab with 25 tasks and you're just asking yourself "Fuck, what do I do?". You can even use features that exist — like automatic ordering based on numbers, which is something that I initially found very confusing and difficult to understand, but which later was a marvel for me — but every time you add something new or take something out, you have to rearrange several other numbers and go opening configuration by configuration. Shit, I can't add a new habit because it's hard work, it's discouraging... Or I can just not order it and leave it messy, which I ended up doing.

## :grey_question: Possible Solution

Anyway, being more exact and direct, I'll list some things that I think would make the application cleaner and much more efficient (even cerebrally speaking).

+ There should be graphical separators (for example, the behavior of the classic \<hr> tag) that can be added in the projects interface, tags and in the Today tab.

+ Being able to group tasks based on predefined configurations and dynamically (not only with a predefined configuration, but also "freely"). Ex: "I want to put the tasks that I demand all day and that only end at the end of the day in one place, so I'm going to create a folder and drag it inside it, perfect."

+ Some specific behaviors in bookmarks, so that it is possible to differentiate "continuous" tasks (of the whole day) from occasional and quick tasks (done in a moment), such as: "Did I create a folder for continuous tasks? special tag and they go to that folder automatically!"

And finally, there's something that I think probably other people have also suffered from, but this is outside of that visual context that I talked about in the whole pr, but functional.
Moving from one day to the next, the closing of the day ends up being “lost” when you forget to close at the end of the previous day. That is, I end up not evaluating myself because I forgot to close for the day, and doing that the next day at 6 am is impossible, as I would be closing on the second day and not the first...

Anyway, thank you very much for your attention and for creating this beautiful application that supports me every day. It would be perfect if I could contribute financially or even with code, but it's not within my current possibilities, although I really want to :(

**Comment by DevAles** [comment]
LGTM!
