### ISSUE TITLE
Simple timers: Show title on hover

### ISSUE THREAD

**Issue by q-wertz** [johannesjo/super-productivity#2660]
## Problem Statement
Currently one can only distinguish the simple timers by the symbol. When having quite some it might get hard to remember from the symbol it's exact meaning (there is not always a fitting symbol)

## :grey_question: Possible Solution
Show the `Title` of the timer when hovering over the icon.

**Comment by prabhjotlamba1655** [comment]
HI @johannesjo, I would like to work on this issue.

**Comment by johannesjo** [comment]
That's great to hear! Let me know if you have any questions!

**Comment by q-wertz** [comment]
:robot: beepboop

**Comment by rayolasr** [comment]
Hello @johannesjo ! I would like to start working on this issue. It would be my first github contribution :)
If I understand well, we are talking about this buttons, right?:
![superp-screenshot](https://github.com/johannesjo/super-productivity/assets/26779787/d1762f4f-87a1-47cf-a123-9b9a757bcb15)

**Comment by q-wertz** [comment]
Exactly :+1:

**Comment by rayolasr** [comment]
Hello @johannesjo!
I've already got the changes but don't know what to do next, first time contributing on GitHub xD

**Comment by johannesjo** [comment]
@rayolasr does this help:
https://docs.github.com/articles/creating-a-pull-request
?

**Comment by rayolasr** [comment]
Sure! I just thought I needed the issue to be assigned to me before doing a pull request.

**Comment by johannesjo** [comment]
> Sure! I just thought I needed the issue to be assigned to me before doing a pull request.

This is not necessary, but thanks for the hint :)

**Comment by q-wertz** [comment]
I think this was closed in #2966
