### ISSUE TITLE
[Feature Request] Make background color optional

### ISSUE THREAD

**Issue by tiagogala** [johannesjo/super-productivity#267]
### Current Behavior

Currently, when selecting a Primary Color for a project, some colors will keep the background of the application white, but others will give it some colorisation with a fade effect.

I find the background color very distracting and out of line from what I expect in an application. I end up using very pale colors as the project's primary color to avoid this issue.

### Expected Behavior

My expectation is to have a a checkbox on the project's theme tab where I can select between automatic background color or white (or dark-grey if using dark mode).

Thanks!

**Comment by johannesjo** [comment]
Hey there! Thanks for reporting. I agree that it would be good to have some options to customize the background (maybe even custom images) and to allow to disable for people who don't like it. It's on my todo list :)

**Comment by johannesjo** [comment]
This actually looks quite a bit nicer for the dark theme. Thanks for the suggestion again :)

**Comment by tiagogala** [comment]
Awesome! Thanks for the effort!
