### ISSUE TITLE
Repeating task is not creating every month (may other period of time).

### ISSUE THREAD

**Issue by ChameleonRed** [johannesjo/super-productivity#2670]
### Your Environment

- Version used: 7.13.2
- Desktop Environment: Windows
- Browser Name and version: 

### Expected Behavior

Repeated tasks should be recreate every 10 of month starting from 2022.
I see only repeated task on "schedule list" and nothing is recreated.

### Current Behavior

Nothing created for "scheduled" repeated tasks.

### Steps to Reproduce (for bugs)

1. Create task maybe.
2. Set custom schedule.
3. Wait forever ...
4.

### Can you reproduce this reliably?

I have task on list and it is now works.

### Console Output

Nothing special no errors.

### Error Log (Desktop only)

No errors.

**Comment by johannesjo** [comment]
Thanks for opening this up! Are you sure you opened the app on the day where the task was due for creation? You can also use the timeline ot see, when a repeating task would be created.
