### ISSUE TITLE
Missing "add sub-task" button

### ISSUE THREAD

**Issue by theCalcaholic** [johannesjo/super-productivity#268]
### Your Environment
* Version used: 3.0.5 snap
* Operating System and version: Ubuntu 18.04 LTS
* Desktop Environment: Gnome

I totally dig the new task menu (for scheduling tasks, editing notes and attachments and setting up repeatable tasks :heart: ). However, I can't find a way to add sub tasks anymore. Is this on purpose?

**Comment by astoeriko** [comment]
You can right-click on the task in the main task list. Then there should be an option "Add sub task".
Or you can still use keyboard shortcuts ("a" by default).

I was wondering how to delete a task after the change in the task menu until I found that there is a menu popping up when you right click tasks. ;-)

**Comment by johannesjo** [comment]
@theCalcaholic @astoeriko  does right clicking work out for you or do you think there should be a more obvious way to add sub tasks and to delete them?

**Comment by theCalcaholic** [comment]
Oh! :D No, if right clicking is the general UX approach, that's fine. I just didn't look for it.

**Comment by urnlahzer** [comment]
> [@theCalcaholic](https://github.com/theCalcaholic) [@astoeriko](https://github.com/astoeriko) does right clicking work out for you or do you think there should be a more obvious way to add sub tasks and to delete them?

Hi, I would love a sub-task button or some way to add them on mobile devices (i.e., browser windows).  Without a more obvious way, I can't seem to add them on mobile at all.

**Comment by johannesjo** [comment]
You can add them on mobile via context menu, that you can open up by longpressing a task.
