### ISSUE TITLE
Snap! A critical error occurred...

### ISSUE THREAD

**Issue by AdsonBatista** [johannesjo/super-productivity#269]
Snap! A critical error occurred...

! Please Report !

TypeError: undefined is not a constructor (evaluating 'new window.ResizeObserver((function(e){t.next(e[0].contentRect.width)}))')
observeWidth (webpack:///src/app/util/resize-observer-obs.ts:20:54)
_trySubscribe (webpack:///node_modules/rxjs/_esm5/internal/Observable.js.pre-build-optimizer.js:43:35)
toSubscriber (webpack:///node_modules/rxjs/_esm5/internal/Observable.js.pre-build-optimizer.js:29:35)
_innerSub (webpack:///node_modules/rxjs/_esm5/internal/operators/switchMap.js.pre-build-optimizer.js:51:51)
this.project (webpack:///node_modules/rxjs/_esm5/internal/operators/switchMap.js.pre-build-optimizer.js:41:23)
next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js.pre-build-optimizer.js:53:23)
this.destination.error (webpack:///node_modules/rxjs/_esm5/internal/operators/filter.js.pre-build-optimizer.js:38:34)
next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js.pre-build-optimizer.js:53:23)
observers.slice (webpack:///node_modules/rxjs/_esm5/internal/Subject.js.pre-build-optimizer.js:47:29)
_events.push (webpack:///node_modules/rxjs/_esm5/internal/ReplaySubject.js.pre-build-optimizer.js:39:35)
ViewChild (webpack:///src/app/ui/better-drawer/better-drawer-container/better-drawer-container.component.ts:57:27)
queryList.reset (webpack:///node_modules/@angular/core/fesm5/core.js.pre-build-optimizer.js:28667:26)
Services.setCurrentNode (webpack:///node_modules/@angular/core/fesm5/core.js.pre-build-optimizer.js:29722:40)
checkAndUpdateView (webpack:///node_modules/@angular/core/fesm5/core.js.pre-build-optimizer.js:29446:22)
execProjectedViewsAction (webpack:///node_modules/@angular/core/fesm5/core.js.pre-build-optimizer.js:29680:39)
execComponentViewsAction (webpack:///node_modules/@angular/core/fesm5/core.js.pre-build-optimizer.js:29622:27)
checkAndUpdateView (webpack:///node_modules/@angular/core/fesm5/core.js.pre-build-optimizer.js:29445:29)
execProjectedViewsAction (webpack:///node_modules/@angular/core/fesm5/core.js.pre-build-optimizer.js:29680:39)
execComponentViewsAction (webpack:///node_modules/@angular/core/fesm5/core.js.pre-build-optimizer.js:29622:27)
checkAndUpdateView (webpack:///node_modules/@angular/core/fesm5/core.js.pre-build-optimizer.js:29445:29)
META: Browser – pt-BR – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.4 Safari/605.1.15

**Comment by johannesjo** [comment]
Thank you very much for reporting. I look into it!

**Comment by johannesjo** [comment]
This should be fixed with the next release. Thanks again.
