### ISSUE TITLE
Add keyboard shortcut to "Trigger Sync Manually"

### ISSUE THREAD

**Issue by diegopds83** [johannesjo/super-productivity#2692]
## Problem Statement

I often change between Desktop and Android App (and vice versa). Even with 1m of **"Sync Interval"**, there is a risk of conflicting changes. And as I have a "keyboard-driven" profile (vim key bindings fan), it causes a small friction to use mouse or press `TAB` several times.

## :grey_question: Possible Solution

It would be great a keyboard shortcut for **"Trigger Sync Manually"**, `F5` or `Ctrl + S`, for example.

## :arrow_heading_up: Describe alternatives you've considered

`Shift + D `, ` Enter`, press and hold ` TAB` until focus at top screen buttons; then, press ` TAB` again three to five times and finally press ` Enter` on **"Trigger Sync Manually"** button.

## :heavy_plus_sign: Additional context

Related issue: https://github.com/johannesjo/super-productivity/issues/2689

**Comment by diegopds83** [comment]
> This issue has not received any updates in 90 days. Please comment, if this still relevant!

Still relevant.

**Comment by johannesjo** [comment]
This is implemented now.
