### ISSUE TITLE
App uses a ridiculous amount of  system memory on my Windows app

### ISSUE THREAD

**Issue by LeGrangeJ** [johannesjo/super-productivity#2703]
I have noticed that a ridiculous amount of memory is used by this app (about 8mb). This is not sustainable for me, as I am running simulations as well and use this app to keep track of my siimulations. 

- Version used: 7.13.12
- Operating System and version: Windows 11

- Browser Name and version: not applicable only using the desktop version

### Expected Behavior

Well, it shouldn't take more memory than call of duty.

### Current Behavior
uses 

### Can you reproduce this reliably?

jip just open the _app/1_

**Comment by johannesjo** [comment]
Thanks for reporting! Are you using the windows store version or the installer?

**Comment by alirahimifachr** [comment]
i'm using the last version of Windows Store with runnig timer.
Memory: 160MB-210MB
Disk: 0.1MB/s 

i guess, it's normal for Windows 11
