### ISSUE TITLE
Request for OneDrive and Microsoft Account Sync Integration

### ISSUE THREAD

**Issue by magge-faf** [johannesjo/super-productivity#2704]
I was pleasantly surprised by the app's features upon acquiring it from the Microsoft Store. 

However, I noticed that the absence of OneDrive or Microsoft account syncing was a bit disappointing. As a user frequently switching between PC and Laptop, I envisioned smoother experiences if such integration were available. Incorporating this functionality would eliminate the need for additional software like Dropbox, streamlining the process and enhancing user convenience.

I kindly request consideration for implementing this feature, which would undoubtedly enhance the app's overall usability and appeal to a wider user base in the Microsoft store.

Thank you very much

**Comment by johannesjo** [comment]
Looks like a duplicate of #2109
