### ISSUE TITLE
Text mistake.

### ISSUE THREAD

**Issue by IbrH** [johannesjo/super-productivity#271]
### Your Environment
* Version used: Latest snap version
* Operating System and version: Ubuntu 19.10
* Desktop Environment: GNOME
* Browser Name and version: (not web version)

### Expected Behavior
At the end of the day, it should say "Your work is done. Time to go home!"

### Current Behavior
It says "You work is done. Time to go home!"

### Steps to Reproduce (for bugs)
End day, then press save and go home.

**Comment by johannesjo** [comment]
Thank you! I'll fix this asap.
