### ISSUE TITLE
[FEATURE REQUEST] [keyboard shortcut] add shortcuts to move task to the top/bottom of the task list

### ISSUE THREAD

**Issue by nicola-lunghi** [johannesjo/super-productivity#2723]
in the keyboard shortcut there's only options to move a task Up and Down in List.
Add a shortcut to move a task on the top of the list or on the bottom to quickly reorganize Backlog and task list

![image](https://github.com/johannesjo/super-productivity/assets/25422924/dfdb3d3b-d8ba-4cc3-96ca-0d64f52e1f0b)

**Comment by OdyAsh** [comment]
Just to put some resolution to this for anyone who randomly stumbles on this issue: it's now implemented:

Navigate to Settings -> General tab -> Keyboard Shortcuts -> scroll down to "Tasks", then check this:

<img width="1132" height="922" alt="Image" src="https://github.com/user-attachments/assets/73fd989a-52ad-4390-91d3-a9a1bd4ad99e" />
