### ISSUE TITLE
Make available as Flatpak cause Snap crashes

### ISSUE THREAD

**Issue by l0wskilled** [johannesjo/super-productivity#2724]
## Problem Statement

Alot of snap apps crash for me and my colleagues who use laptops with amd cpus.
When the app opens a context menu, like the datepicker, the app crashes. This only happens with the snap version, not if I install it via a deb.

## :grey_question: Possible Solution

I had the same problem with slack and the slack flatpak works like a charm. So I wanted to know if it's possible to add it to flathub.

**Comment by johannesjo** [comment]
#25
