### ISSUE TITLE
Error pulling issues from Jira

### ISSUE THREAD

**Issue by VladRoscaDev** [johannesjo/super-productivity#273]
### Your Environment

* Version used: 3.0.7
* Operating System and version: Windows OS 17134.523
* Desktop Environment: Desktop environment
* Browser Name and version: -----

### Expected Behavior

After filling in all the data my issues should be pulled from jira.

### Current Behavior

After I fill in my credentials I click test credentials and I receive the message Login successful! Welcome {{user}}! that seems a bit weird.
I am using **Jira v7.0.11 in an offline environment (server)**, because the API may differ from version to version.
I run in Jira the JQL and indeed it is getting al of my issues. But when using the app at this method: mapToSearchResult, in jira-issue-map.util.ts the res.response is a html page containing the title, Board-JIRA, meta data, and all of jira plugins (looks like it's getting Jira's first page)
Also i ran debug on jira and couldn't seem to get any network trace of the app calling jira but no traffic was detected when searching for issues, maybe this would help me debug the process.
I can't seem to find any network traffic in the console, but i get the following message when i try searching for a task: "To prevent shut out from api, access has been blocked by Super Productivity. You should probably check you jira setting!"

### This is a separate problem that could be connected
Also when i try to press CTRL+SHIFT+J it says TypeError: Cannot read property 'send' of undefined.
The output on this one is TypeError: "Cannot read property 'send' of undefined"

### Steps to Reproduce (for bugs)

1. Go to settings,
2. fill in the data for jira integration
3. go to current project 
4. try adding an existing task from jira (searching)

### Steps to Reproduce the problem with the console(for bugs)

1. Press CTRL+SHIFT+J,

**Comment by johannesjo** [comment]
Thank you very much for reporting! I'll look into it as soon as I can!

**Comment by VladRoscaDev** [comment]
Hello, I dug deeper into this and it seems to be the problem of not putting https://jira.x.com**/jira**. This seems to be a problem of follow redirect. It all works now after i added /jira.
Great app!

**Comment by johannesjo** [comment]
@VladRoscaDev thanks for getting back to me another and sorry for not working on that myself yet. I got quite a lot on my plate currently and I struggle to find time for my OSS projects. 

Haven't encountered the adding "jira" part myself or otherwise so I assume that it is specific to your environment. The error message should definitely be more helpful than it currently is though.
