### ISSUE TITLE
After removing all subtasks, "+ 1 SUB TASKS" is still displayed under the task

### ISSUE THREAD

**Issue by probstlukas** [johannesjo/super-productivity#2732]
### Your Environment
- Version used: 7.13.2 (brew)
- Operating System and version: MacOS Ventura 13.4.1 (c) 

### Expected Behavior

When all subtasks of a task are removed, it should return to its initial state before subtasks were added. Maybe this behavior is intentional, but I don't understand why it should be. If I decided that I don't need subtasks anymore, the original layout should be restored.

### Current Behavior

Once all subtasks have been removed, it still shows "+ 1 SUB TASKS" in the area of the task.

### Steps to Reproduce (for bugs)

[Live example on Imgur](https://imgur.com/a/JoQZosU)

1. Create a new task
2. Add subtasks
3. Remove all subtasks again

### Can you reproduce this reliably?

I am able to reproduce this issue reliably and it's the same behaviour every time.

### Console Output

The box 'done-task-box ng-tns-c174-48 ng-trigger ng-trigger-expandFadeFast ng-star-inserted' should be gone after removing all subtasks.

**Comment by johannesjo** [comment]
You don't remove tasks by pressing on the minus icon which is only used to collapse the tasks. You delete by using right click and then choosing delete.
