### ISSUE TITLE
ical entries are shown twice on timeline

### ISSUE THREAD

**Issue by Jandalf-0** [johannesjo/super-productivity#2737]
* ubuntu 22.04
* installed super productivity via snap
* imported my google calendar via ical

In the timeline, 90% of the calendar entries appear twice.
![grafik](https://github.com/johannesjo/super-productivity/assets/142870233/3e3faa3b-9a0f-48ae-a371-ff78ace4da04)
It's not the case for all entries, but I don't see any system for which are affected and which aren't. Removing the ical source and adding it again doesn't fix it

**Comment by johannesjo** [comment]
I am unable to reproduce this unfortunately. Possibly there is something wrong here:
`src/app/features/timeline/ical/get-relevant-events-from-ical.ts`

**Comment by Jandalf-0** [comment]
my coding skills are on elementary school level....

However, are you sure that there needs to be a dedicated function for handling recurring events? I had a look into the .ics file and it looks like each event is in there separately, regardless of whether it's part of a series or not.

**Comment by johannesjo** [comment]
> However, are you sure that there needs to be a dedicated function for handling recurring events? I had a look into the .ics file and it looks like each event is in there separately, regardless of whether it's part of a series or not.

Maybe that is the issue. If you have multiple instances of an event it probably means that you edited them and they become a separate instance of the original recurring event. Could be that we're not probably accounting for that on SPs side of things.

**Comment by Jandalf-0** [comment]
I now see the same duplicate items in Thunderbird as well. So, it's not a problem of Super Productivity. → ticket closed

**Comment by kikorb** [comment]
Please don't close this issue it is still happenig to me. Maybe to others. When events are recurring and get removed they still appear in the UI. When they are edited they can appear multiple times:

![Image](https://github.com/user-attachments/assets/cf2d2620-d872-4c5b-bac9-eb6b02cf01eb)

![Image](https://github.com/user-attachments/assets/54b8958c-57fe-43b4-95dc-160d2cbb35ee)
