### ISSUE TITLE
Suggestions for GitHub while adding new tasks doesn't work

### ISSUE THREAD

**Issue by cuberleon** [johannesjo/super-productivity#2749]
### Your Environment

- Version used: 7.3.12 (just updated), used 7.3.11 most of the time
- Operating System and version: Windows 10 Pro 22H2

### Expected Behavior

When I type the title of a GitHub's issue, I see the suggestion to add it.

### Current Behavior

Consistently doesn't work now. However, it was getting broken in the past on the same version and starting to work again for unclear reason (probably unrelated to this).

### Steps to Reproduce (for bugs)

1. Create a test project and sync with GitHub `johannesjo/super-productivity`.
2. Try to add any issue
3. No suggestions

### Can you reproduce this reliably?

Yes

**Comment by cuberleon** [comment]
I think the problem is at this line https://github.com/johannesjo/super-productivity/blob/master/src/app/features/issue/providers/github/github-api.service.ts#L78. If I replace `encodeURIComponent` to `encodeURI`, suggestions work again.

**Comment by cuberleon** [comment]
Config: ![github_config](https://github.com/johannesjo/super-productivity/assets/12598936/f98c24b9-b236-423b-81bb-a88ffa361b74)

Suggestions broken (master): ![encodeURIComponent_suggestions_broken](https://github.com/johannesjo/super-productivity/assets/12598936/0a32072a-af6e-4269-8159-eabdc27dd7f5)

Suggestions work (`encodeURIComponent` replaced with `encodeURI`): ![encodeURI_suggestions_work](https://github.com/johannesjo/super-productivity/assets/12598936/a718d419-b8a5-4444-a7d8-fc21e0f55b99)

**Comment by johannesjo** [comment]
Thank you very much!
