### ISSUE TITLE
Keyboard shortcut for saving notes from full screen/expanded screen and short cut to expanded note editor. 

### ISSUE THREAD

**Issue by dbarkelew** [johannesjo/super-productivity#2759]
## Problem Statement

Needing to move my hands from the keyboard to expand the task description/note editor and again move my hand to the mouse to save the task notes. This breaks my flow. It also prevents me from adding additional function like adding my StreamDeck to do tasks for me which I have a lot of the app configured for.   

## :grey_question: Possible Solution

Add keyboard shortcuts to expand the task description/notes editor/preview and to save.

## :arrow_heading_up: Describe alternatives you've considered
 

A macro in StreamDeck to copy the description/notes into VSCode then copy them back with another macro. However, the return copy macro doesn't land properly and I have to use the mouse instead of achieving everything with a button push.

## :heavy_plus_sign: Additional context

When adding description/notes to a task the editor can be expanded to show a markdown preview as I type them. I would like a keyboard shortcut to save the notes from this preview editor page and a keyboard shortcut to expand into the description/note editor/preview. 

To help clarify, I don't mean the option shift+n which allows for notes to be added to the project level.

**Comment by nataliaqmc** [comment]
Hi @johannesjo, could I be assigned this issue to make the improvements necessary?

**Comment by johannesjo** [comment]
@nataliaqmc Thanks for the offer! Please let me know if you have any questions! :)
