### ISSUE TITLE
Logical error with the date displayed in time spent on a task

### ISSUE THREAD

**Issue by MostafaAmin07** [johannesjo/super-productivity#276]
### Your Environment

* Version used: 3.0.7
* Operating System and version: Windows 10, v1809

### Expected Behavior

When I start tracking time for a task when the language is set to English. then go to edit the time spent on that task from additional info.
A list of the days that I worked in shows except for the date of the day we are in. (That's the right behavior)
That should happen even if I change the language to Arabic.
and vice versa. 

### Current Behavior

The list of days shows the date of the day we are in.
That happens when The language selected is Arabic and the time tracing started while the language is English and vice versa.

### Steps to Reproduce (for bugs)

1. Select the English language.
2. Create a task in any project.
3. Start time tracking for the task for a while then pause it.
4. Select the Arabic language.
5. Go to that task and open the additional info then click to edit the time spent on the task.

### Console Output

There is no output

**Comment by MostafaAmin07** [comment]
These are some screens showing what happens.
![Bug1](https://user-images.githubusercontent.com/32510728/72100572-89feaa00-332b-11ea-96f4-ccdef743614e.png)

![Bug2](https://user-images.githubusercontent.com/32510728/72100573-89feaa00-332b-11ea-8610-56713776be43.png)

![Bug3](https://user-images.githubusercontent.com/32510728/72100574-89feaa00-332b-11ea-905f-b252af824d1d.png)

This is not the only problem that happens regarding dates related functionality.
But it is the easiest one to reproduce.

**Comment by johannesjo** [comment]
Good catch! Thank you very much! I am working on a patch.

**Comment by johannesjo** [comment]
Ugly issue... I naively assumed that
```
moment(date).locale('en').format('YYYY-MM-DD');
```
Would return the same on every system. Of course it doesn't....

I published a patch and also some automated migration scripts for the data. Hope this works smoothly. Could you check this for me with your data (don't forget to make a backup first)?

**Comment by MostafaAmin07** [comment]
Unfortunately, a critical error occurred in the migration.
![c-error](https://user-images.githubusercontent.com/32510728/72200327-ec9d9600-3450-11ea-99eb-5e7d95bd982c.png)

**Comment by MostafaAmin07** [comment]
I played around with moment and it seems like it can't parse Hindu-Arabic numerals.
So I tried a quick fix to that is converting the Hindu-Arabic numerals to Western-Arabic numerals before parsing them with moment like this.

```
const numberMap = {
  '١': '1',
  '٢': '2',
  '٣': '3',
  '٤': '4',
  '٥': '5',
  '٦': '6',
  '٧': '7',
  '٨': '8',
  '٩': '9',
  '٠': '0'
};

function replace(date : string): string {
  let  newDate : string = date;
  return newDate.replace(/[١٢٣٤٥٦٧٨٩٠]/g, function (match) {
    return numberMap[match];
  });
}
```

But there are 2 problems I can spot.
The project state migration doesn't run when importing a project from a file so imported data doesn't get updated.
The second one is a bit tricky. If a date exists twice one of them will be overwritten like this example.

```
"timeSpentOnDay": {
                        "٢٠١٩-١٢-٢٧": 1001,
                        "2020-01-02": 7010,
                        "2020-01-03": 4003,
                        "2020-01-09": 25000,
                        "٢٠٢٠-٠١-٠٩": 5001
                    },
                    "timeSpent": 42015,
```

the last 2 dates are the same day but when the migration runs it results in this
```
"timeSpentOnDay": {
                        "2019-12-27": 1001,
                        "2020-01-02": 7010,
                        "2020-01-03": 4003,
                        "2020-01-09": 5001
                    },
                    "timeSpent": 42015,
```

So it would be better if they add up instead of getting overwritten.

**Comment by johannesjo** [comment]
That's great work thank you! Would you maybe be willing to provide a PR for these adjustments for the migrate scripts for tasks and projects?

**Comment by MostafaAmin07** [comment]
Sure, I will.

**Comment by johannesjo** [comment]
Thank you very much! I'll try to add a similar thing for japenese, korean and chinese next week. We probably need it.

**Comment by johannesjo** [comment]
Hopefully this is fixed with one of the newer releases. Please let me know if you encounter any further issues with this.
