### ISSUE TITLE
Nextcloud sync failing

### ISSUE THREAD

**Issue by rk-kontur** [johannesjo/super-productivity#2762]
First post here. THANK YOU SO MUCH for this GREAT task manager I am justtrying out.
It really is a very cool app. I love that my data stays with me!!!!!!!!

I try setting p Nextcloud Webdav sync and there is nothing I can do, it seems:

This is my base URL:
http://mywebaddress.com/remote.php/dav/sync

apart from my web address, this is the file path to sync:

http://mywebaddress.com/remote.php/dav/sync/files/SuperProductivity/superproductivity.json

all puser credentials are ok, I copied them from my pw manager.

Is there someting I do in the wrong way?

THANKS so much for helping

**Comment by sm8ps** [comment]
Comparing my working solution to your settings, it would be  ...

- base-URL= http://mywebaddress.com/remote.php/dav/files/SuperProductivity (note the missing `sync/`)
- username = SuperProductivity (already included in the base-URL but compliant with note in SP-settings)
- filepath = superproductivity.json

I recall having some issue with CSRF-tokens that I believe I solved as described in #599. There are some hints about trouble-shooting; also look at the server logs. Please report back with your findings!
