### ISSUE TITLE
Increase duration for displaying motto of the day

### ISSUE THREAD

**Issue by sm8ps** [johannesjo/super-productivity#2764]
## Problem Statement
At start-up the app shows a motto which I find nice and interesting. However, I hardly ever get to finish reading it because it disappears when the app is ready.

## :grey_question: Possible Solution

Set a fixed duration or turn it into a message dialogue with confirmation by the user.

- Fixed duration may be cumbersome when in a hurry, so it should be some kind of toast message that is independent of the main app. Maybe too much effort for little benefit.
- Confirmation by the user may feel like another unnecessary click if one is not interested, so it should be made optional.

**Comment by johannesjo** [comment]
That's an interesting suggestion. I leave it open for discussion. Originally the "motto of the day" was just intended to be as a little bit more useful loading screen. But some people like it, so transforming it into a snack after load might be an interesting way to go about it.

**Comment by sm8ps** [comment]
I just noticed the enhancement with the new Snap release. Making it a snack is a brilliant solution, noticeable but still unobtrusive.
