### ISSUE TITLE
Custom day time range, day end hour

### ISSUE THREAD

**Issue by Nixellion** [johannesjo/super-productivity#277]
Hi!

I could not find a setting that's quite common in similar apps - custom day end hour. For now it counts a day as finished based on 00:00 to 23:59 I quess. 

My schedule is shifted forward in time, I wake up late and go to bed late, so my "day" is more like starts at 13:00 and ends at 04:00 roughly. This messes app's calculations up, as it starts counting time towards the next astrological day, though logically I'd like it to count it to my current 'logical' day, if that makes sense

**Comment by johannesjo** [comment]
Hey there! Thanks for opening this up! I agree that this would be nice and I want this feature as well.

**Comment by mbostanara** [comment]
That's my issue too. It would b great if such feature adds to the app.

**Comment by Nixellion** [comment]
> 
> 
> That's my issue too. It would b great if such feature adds to the app.

If interested, I went with Traggo for the time being instead. It does not have any restrictions whatsoever, just pure time tracking and tags and nothing else. Works great for my use case so far.
