### ISSUE TITLE
The dropdown menu fails to appear when clicking on the text field

### ISSUE THREAD

**Issue by 2gn** [johannesjo/super-productivity#2773]
## Problem Statement

Feature to always show dropdown menu when clicked on field in the dialog displayed when you click "ADD TO TASK" button.
![image](https://github.com/johannesjo/super-productivity/assets/101851090/406d21dd-0a92-45ed-80b6-b86066725683)

## Steps To Reproduce
1. Wait for more than 2 minutes until the banner appears
2. Click on "ADD TO TASK"
3. Click on the text field
4. It displays nothing, but when you type something in and delete what you've typed, the dropdown menu appears.

## :grey_question: Possible Solution

The menu displays correctly when I type something into the field. Maybe this should be triggered when clicked on the field, not when something was typed in.
![image](https://github.com/johannesjo/super-productivity/assets/101851090/86ea1cb3-915c-4f4d-bfec-8e4eb5215c74)
![image](https://github.com/johannesjo/super-productivity/assets/101851090/f9f40c48-b2ea-42d6-a111-f726b68a1943)

## :arrow_heading_up: Describe alternatives you've considered

It'd possibly be better if you could directly click on the task in the main menu to track untracked time to, without opening any dialog.

## :heavy_plus_sign: Additional context

My quick search in this project's issue did not reveal any similar issue.

**Comment by johannesjo** [comment]
Thanks for the suggestion. Honestly I prefer it the way it is, as the open dropdown would hide the buttons and rest of the UI behind it.

**Comment by 2gn** [comment]
> Thanks for the suggestion. Honestly I prefer it the way it is, as the open dropdown would hide the buttons and rest of the UI behind it.

I see. I did think it might be better though...

Thank you for replying nonetheless.
