### ISSUE TITLE
Clickable links for all protocol URIs (in description)

### ISSUE THREAD

**Issue by ishanarora** [johannesjo/super-productivity#2775]
## Problem Statement

Many desktop and mobile apps support their unique dedicated protocol prefixes for creating app specific URIs, e.g. for a specific note in a note taking app, or for a specific email thread in an email client.

When URIs are present in task description / notes, they appear clickable in the markdown rendering for only a small selection of web protocols, while all other URIs are not clickable.

## :grey_question: Possible Solution
 
Make all URI patterns clickable. Additionally, perhaps add a right-click context menu with options to open the URI link, and copying the URI.

## :arrow_heading_up: Describe alternatives you've considered

Enter the inline markdown editor, and select the URI text, copy it, and open the URI through a third-party program. It works but it's inefficient, and prone to error when selecting the URI text i.e. not super-productive :smiling_face_with_tear: 

## :heavy_plus_sign: Additional context

NA

**Comment by ishanarora** [comment]
:eyes:

**Comment by Jagdfalke** [comment]
What URI-patterns would you like to see added?

**Comment by ishanarora** [comment]
Ideally all valid URIs as defined in RFC 3986. The protocol shouldn't matter as the OS shell can be requested to open any valid `URI`. Valid use-cases include linking an email (`mid:` protocol) or a page in a personal knowledge management tool.

**Comment by johannesjo** [comment]
This will be out with the next release. Hopefully it doesn't cause any security problems.
