### ISSUE TITLE
Full calendar functionalities

### ISSUE THREAD

**Issue by master-of-m** [johannesjo/super-productivity#2777]
## Problem Statement

I don't get why to dos and calendar apps are never integrated, I am always frustrated when I have to keep the two different apps open at the same time and manually sync them.

## Possible Solution

Since this app already features an inherent calendar to keep track of the tasks it would be awesome if we had a monthly view of it where we could also insert "events" alongside tasks.

**Comment by johannesjo** [comment]
#2521
