### ISSUE TITLE
Sidebar gets hidden and can't be revealed again

### ISSUE THREAD

**Issue by tinoargentino** [johannesjo/super-productivity#2780]
### Your Environment

- Version used:  Version 7.11.5 (7.11.5)
- Operating System and version: macos Ventura
- Desktop Environment: 
- Browser Name and version: 

### Current Behavior

Sidebar gets hidden and can't be revealed again after focusing on it with keyboard shorcut and accidentally hitting esc

After hiding it, there's no way to bring it back (that i've found)

keyboard shorcut wont do it

only solution is to restart

### Steps to Reproduce (for bugs)

above

### Can you reproduce this reliably?

yes

**Comment by johannesjo** [comment]
Unfortunately I am unable to reproduce this. Steps I did to reproduce:
1. Hit Shift+D to show menu
2. Hit Escape to hide it
3. Hit Shift+D again to show menu again (pressing the menu button works too).

**Comment by tinoargentino** [comment]
weird! I’m still able to reproduce it consistently

I’m in mac, what's the menu button????

**Comment by johannesjo** [comment]
![Screenshot from 2023-09-18 17-52-57](https://github.com/johannesjo/super-productivity/assets/1456265/04dffc23-af25-4ef8-88f4-2d7acd46100d)

The burger icon (with the 3 bars on top of each other) next to "Today".

**Comment by tinoargentino** [comment]
just upgraded to 7.14.3 and I still don't have that hamburger as can be seen in icon

also, the macstore link gets me to v 7.11.5

![image](https://github.com/johannesjo/super-productivity/assets/6530884/c09373bf-da44-4f2c-93d7-a5929f587c3d)

**Comment by johannesjo** [comment]
If the app window is very large the burger icon is not shown and the menu should be visible at all times instead. 

Still unable to reproduce it though :/

**Comment by tinoargentino** [comment]
ok, now with the smaller window I was able to see the burger and bring back the menu! I don't know what to say about reproducing it tho! is there anything i can do to help?

**Comment by johannesjo** [comment]
Could you maybe make a little screen recording on what happens exactly? That would be great!

**Comment by tinoargentino** [comment]
here you go! i used the scheduled tab only to not share my tasks with the internet, but it's the same thing
https://github.com/johannesjo/super-productivity/assets/6530884/ced4628f-6685-4232-a989-5083b09bac27

**Comment by tinoargentino** [comment]
I used the scheduled view so as to not share my tasks, but it's the same

i updated to v 7.14, only difference is that now it seems i need to hit esc twice! good luck! with the hamburger fix I’m ok, you can close this if you want 


https://github.com/johannesjo/super-productivity/assets/6530884/51a5764f-8194-4932-8a65-8e9a3df808db

**Comment by johannesjo** [comment]
Thank you very much for the video!!! 
Very odd. Possibly a mac only issue. I'll try to have a look!
