### ISSUE TITLE
SuperProductivity doesn't stop tracking time when a pomodoro timer finishes

### ISSUE THREAD

**Issue by writeonlycode** [johannesjo/super-productivity#2781]
### Expected Behavior

When a pomodoro timer finishes, the app should stop tracking time.

### Current Behavior

When a pomodoro timer finishes, the app continues to track time.

### Steps to Reproduce (for bugs)

1. Start a pomodoro timer.
2. Wait for it to finish.
3. Do not start a new one.
4. Check that the time is still being tracked for the selected task.

### Can you reproduce this reliably?

Yes. It happens consistently.

**Comment by SiddiqAM1** [comment]
Hi , I think i am able to solve this issue

**Comment by writeonlycode** [comment]
@SiddiqAM1 Let me know if you need further information. I have a guess on what's going on: I have the "Stop time tracking for task on break" and "Manually confirm starting next break" checked. I think that since I don't start the break manually, the app doesn't detect the break, so it doesn't stop the time tracking.

Ironically enough, the app is actually doing what it says it's doing: it stops the timer when it enters a break, but if it doesn't enter the break state, then it doesn't stop the timer, even if the pomodoro session finished.

I suspect that a good idea would be to rename this option to something like "Stop time tracking when pomodoro finishes"? In this way, it cover the cases when the pomodoro finishes without entering a break as well the case in which it does enter a break.
