### ISSUE TITLE
[BUG] "API rate limit exceeded" error while creating new task.

### ISSUE THREAD

**Issue by Cyber-Syntax** [johannesjo/super-productivity#2782]
### Your Environment

- Version used: Appimage 7.13.2
- Operating System and version: fedora + pop_os
- Desktop Environment: i3wm 

### Expected Behavior

I think there is no need to make an API request when creating a task.

### Steps to Reproduce (for bugs)

1. Create a project with Github API.
2. Create a new task 
3. While writing a task, if it takes longer than 30 seconds, an error occurs.

### Can you reproduce this reliably?

I can reliably reproduce this issue.

### Console Output

![image](https://github.com/johannesjo/super-productivity/assets/115875369/7ae55fe2-e254-4214-8882-a7f2fed5d0b4)

### Error Log (Desktop only)

There is nothing on main.log related this issue.

**Comment by Cyber-Syntax** [comment]
I tested, the same error persists in 7.14.3 Appimage.

**Comment by johannesjo** [comment]
If you don't want to search github while using the add task bar you need to disable "Show issues from git as suggestions when adding new tasks" in your project's github settings.

**Comment by Cyber-Syntax** [comment]
Thanks, this solved the problem for me, but I think you should look at this when you have time because it's not good to exceed the API speed limit all the time when you try to look at issues in Git as suggestions.

**Comment by johannesjo** [comment]
For me personally this never happens, but you need to provide an API token. Otherwise githubs limits are very strict.
