### ISSUE TITLE
Sync Now button

### ISSUE THREAD

**Issue by anzenketh** [johannesjo/super-productivity#2786]
## Problem Statement
- At times I need to be able to switch from my desktop to my phone so I can not wait for the sync. 
- At time it may look like it is not updated. 
- I could not find the Sync Button that already exists. 

## :grey_question: Possible Solution
A button under Sync&Export that you can click that states Sync Now that preforms a sync before the interval. 

## :arrow_heading_up: Describe alternatives you've considered
- Waiting for the sync to happen
- Decreasing Sync time. 

## :heavy_plus_sign: Additional context
This would also be useful in testing out features. This currently why I am running into the issue.

**Comment by anzenketh** [comment]
This is already implemented. Needs to be Feedback.

**Comment by b2ag** [comment]
It is this button in the top right area of buttons, for people wondering.
![2023-10-02_14-37](https://github.com/johannesjo/super-productivity/assets/1616581/28e27b6f-efe9-487d-a0f8-e6a58b3de6ef)
