### ISSUE TITLE
Metrics Bug when switching between projects

### ISSUE THREAD

**Issue by DanteCoder** [johannesjo/super-productivity#2790]
### Environment

- Version used: 7.14.3, [Setup-x64.exe](https://github.com/johannesjo/super-productivity/releases/download/v7.14.3/superProductivity-Setup-7.14.3-x64.exe)
- Operating System and version: Windows 11 Pro, 22H2,  22621.2283.

### Expected Behavior

When having more than one project, the project metrics should be updated for each project.

### Current Behavior

After opening a project's metrics, and then clicking on another project's metrics, the previous metrics are shown.

### Steps to Reproduce
1. Click on the "Metrics" of a project.
2. Click on the "Metrics" of a different project.

https://github.com/johannesjo/super-productivity/assets/90792603/d17c08f3-8efa-4642-beaf-2d84bdf198ac

### Can you reproduce this reliably?

This issue is persistent.

### Console Output
0. Initial setup: Clicked on "Today" tab, then cleared the console.
1. Step: Clicked on "Metrics" of the first project.
Console output:
```
action-logger.reducer.ts:11 [WorkContext] Set Active Work Context {activeId: 'd9FRaRMxbFpTTD7y75wfw', activeType: 'PROJECT', type: '[WorkContext] Set Active Work Context'}
action-logger.reducer.ts:11 [Task] SetSelectedTask {id: null, type: '[Task] SetSelectedTask'}
action-logger.reducer.ts:11 [Bookmark] Load Bookmark State {state: {…}, type: '[Bookmark] Load Bookmark State'}
action-logger.reducer.ts:11 [Project] Load Project related Data Success {projectId: 'd9FRaRMxbFpTTD7y75wfw', type: '[Project] Load Project related Data Success'}
action-logger.reducer.ts:11 [Improvement] Clear Hidden Improvements {type: '[Improvement] Clear Hidden Improvements'}
action-logger.reducer.ts:11 [Improvement] Delete multiple Improvements {ids: Array(0), type: '[Improvement] Delete multiple Improvements'}
```
3. Step: Clicked on "Metrics" of the second project.
Console output:
```
action-logger.reducer.ts:11 [WorkContext] Set Active Work Context {activeId: '93P09knhCpGUjkXBzA2VG', activeType: 'PROJECT', type: '[WorkContext] Set Active Work Context'}
action-logger.reducer.ts:11 [Task] SetSelectedTask {id: null, type: '[Task] SetSelectedTask'}
action-logger.reducer.ts:11 [Bookmark] Load Bookmark State {state: {…}, type: '[Bookmark] Load Bookmark State'}
action-logger.reducer.ts:11 [Project] Load Project related Data Success {projectId: '93P09knhCpGUjkXBzA2VG', type: '[Project] Load Project related Data Success'}
action-logger.reducer.ts:11 [Improvement] Clear Hidden Improvements {type: '[Improvement] Clear Hidden Improvements'}
action-logger.reducer.ts:11 [Improvement] Delete multiple Improvements {ids: Array(0), type: '[Improvement] Delete multiple Improvements'}
```

**Comment by johannesjo** [comment]
I think this should be fixed :)
