### ISSUE TITLE
Task list scrolls to the top when finishing subtasks

### ISSUE THREAD

**Issue by frainz-de** [johannesjo/super-productivity#2795]
Something like this was reportet before but marked as stale in #2240. However, it massively disrupts my workflow, so here is a proper issue for it.

### Your Environment

- Version used: 7.14.3 amd64
- Operating System and version: Windows 10

### Expected Behavior

Clicking on the checkmark of a subtask marks it as done and just that.

### Current Behavior

The subtask is marked as done. In addition, the task list scrolls to the top

### Steps to Reproduce (for bugs)

1. Move a few tasks with subtask into a task list
2. Scroll to the bottom
3. Mark one of the subtasks as done
4. SP will scroll to the top

### Can you reproduce this reliably?

Yes, it happens every time.

### Error Log (Desktop only)

No relevant output.

**Comment by frainz-de** [comment]
The problem doesn't happen anymore in the current version. Thank you :)

**Comment by johannesjo** [comment]
This should be fixed with the next release.
