### ISSUE TITLE
Google Drive sync setup error

### ISSUE THREAD

**Issue by saravanaskanda** [johannesjo/super-productivity#2797]
### Mac os 

- Version used: 7.11.5 (7.11.5) .dmg installer
- Operating System and version: Mac OS X 13.6 (22G120)

### Expected Behavior

The sync token should be generated in the google.

### Current Behavior

Error 400: invalid_request
The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow migration guide linked in the developer docs below to migrate your app to an alternative method.
Request details: redirect_uri=urn:ietf:wg:oauth:2.0:oob

### Steps to Reproduce (for bugs)

1. Install using dmg installer
2. sign in to google in any browser
3. open superproductivity and in sync select google drive and click 'get authorization code'

**Comment by mrfrobinson** [comment]
Are you accessing via SSL or just http? Chrome may require the site to be https to work correctly.
