### ISSUE TITLE
Timer starts upon completion of another task

### ISSUE THREAD

**Issue by susnick** [johannesjo/super-productivity#28]
## Your Environment

* Version used: No clue it is not listed anywhere (feature maybe??)
* Operating System and version: Windows 10 Pro
* Desktop Environment: 
* Browser Name and version: 

## Expected Behavior

When completing a task on work view, it should not start timer on another item.

## Current Behavior

I have 2 items in the task list, neither are completed.  Neither timer is running. Click the checkbox to complete a task, and the remaining active task's timer starts.

## Steps to Reproduce (for bugs)

1.Add 2 tasks
2. Move to work view
3. complete one task

**Comment by johannesjo** [comment]
Thanks for reporting! Maybe it makes sense to make this behavior configurable.

**Comment by johannesjo** [comment]
I added a setting to make it configurable. Should be available in the the next release which I will make later today.
