### ISSUE TITLE
Improve Jira Time Tracking

### ISSUE THREAD

**Issue by VladRoscaDev** [johannesjo/super-productivity#280]
Hello, I noticed the following behavior:
**Fist suggestion:** When I mark as done my task and save the work log to Jira, the task goes to the done list.If i pull the task back up again to work on it, the work time should be reset to 0 but it continues from where it was left. It would be easier to manage the working sessions on that task. Also when i want to finish the task by using this approach the Started day of work should be changed to the current day. (If it is not clear I can provide more info).

**Second suggestion:** Also it would be a nice feature if you finish a task and move it to review, or done you should set the Remaining Time on the task in jira to 0.

**Comment by johannesjo** [comment]
Hey! Thanks for the suggestions. 

If I understood you correctly, I think that the first suggestion doesn't really mix well with all the internal time tracking going on, though I am open to make it an optional feature.

I like the the second suggestion. I'd also like to see this as a feature you can optionally enable/disable.
