### ISSUE TITLE
Integration with kanban vikunja.io

### ISSUE THREAD

**Issue by SiddharthManthan** [johannesjo/super-productivity#2807]
## Problem Statement
Currently super productivity does not have kanban and it will too much work to add one. But it will be nice to integrate it with existing kanban solutions

## :grey_question: Possible Solution
vikunja.io is a nice simple kanban that has api and a mobile app is in initial stages. It will be nice to have an integration with it. The integration will be similar to jira (I Think)

**Comment by SiddharthManthan** [comment]
I might implement it. Can you give me some pointers to how I can start ?

**Comment by johannesjo** [comment]
Hey hey :)

https://github.com/johannesjo/super-productivity#running-the-development-server
https://github.com/johannesjo/super-productivity/tree/master/src/app/features/issue/providers
