### ISSUE TITLE
Jira: "Relates To" link should use the key instead of the id in the url

### ISSUE THREAD

**Issue by TheCriticalPath** [johannesjo/super-productivity#2809]
### Your Environment
MacOS Sonoma 14.0
Apple M1 Max
64GB RAM

SuperProductivity
- Version used: 7.14.3
- Operating System and version: MacOS Sonoma 14.0

### Expected Behavior
The related jira tasks should use the task's key instead of the tasks id in the jira browse link.

### Current Behavior
The "relates to" or subtask link is currently https://<Jira url>/browse/{related task id}.  This results in a 404 style page on the Jira site which indicates that the project does not exist.  

Instead of using the related task id, the url should use the related task key.

### Steps to Reproduce (for bugs)

1. Create a Jira task and relate to another task.
2. Open the additional info for the task in Super Productivity and click on the relates to or sub task links.
3. Jira link is invalid, indicating the project does not exist.

### Can you reproduce this reliably?
Yes. Every time.

### Console Output
Nothing relevant in console 

### Error Log (Desktop only)
Nothing relevant in logs.

**Comment by johannesjo** [comment]
Haven't used Jira in a while to be honest, but as this worked for the Jira instances I were using. Another problem is that the issue key isn't (necessarily) unique so we would need to store this in an additional field for jira and implement some sepcial logic for it.

**Comment by johannesjo** [comment]
Just recognized that we're always using the key as issueId. So this should work well enough :) Thank you very much!
