### ISSUE TITLE
Allow for setting a reminder on repeating tasks

### ISSUE THREAD

**Issue by dandycheng** [johannesjo/super-productivity#281]
Repeated tasks are limited to the day of week, but there is no reminder for the specific time. Pomodoro only allows duration based reminder. It would be nice to have an alarm clock-like feature for repeated tasks.

**Comment by johannesjo** [comment]
Hey there! Thanks for opening this up. I'd also like to see this, even though I must admit, that it ain't on the very top of my personal todo list. I am open for PRs though!

**Comment by johannesjo** [comment]
Still relevant.

**Comment by johannesjo** [comment]
I am closing this in favor of: https://github.com/johannesjo/super-productivity/issues/948 (please upvote if you still like to see this).

Thank you very much for your input.
