### ISSUE TITLE
Incoherent state when cancelling break

### ISSUE THREAD

**Issue by ssalenik** [johannesjo/super-productivity#283]
### Your Environment

* Version used: snap stable 3.1.3 2020-01-17
* Operating System and version: ubuntu 19.04
* Desktop Environment: gnome 3

### Expected Behavior
In the middle of a pomodoro break.
Click cancel before its over.
Starts next session and keeps tracking time to the previously selected task. Or doesn't start next session and timer is stopped.

### Current Behavior
In the middle of a pomodoro break.
Click cancel before its over.
I get a notification that the next session has started and I see the timer counting down. However, the timer button is blue, not pink, and I can click "play" on it. Also no task is selected, so the time is not being counted towards any task nor towards the project.
The behaviour is correct if you click "skip".

Not clear to me if when you click "cancel" in the middle of a break what the actual behaviour should be (vs. skip break), but currently it seems to be in between two states. 

### Steps to Reproduce (for bugs)

See current behaviour.

**Comment by johannesjo** [comment]
Thanks for reporting! I'll try to check this tomorrow.

**Comment by johannesjo** [comment]
I think I fixed it. The button should read "close" and not "cancel" and only close the dialog. Not sure if the setup is ideal now, as I am currently not using the pomodoro timer myself. Please let me know if it works like this for you or if there should be some adjustments.

**Comment by ssalenik** [comment]
This makes sense to me. I'll give more feedback if I manage to build it from source, as for now I'm just using the snap package.

**Comment by johannesjo** [comment]
You could also try installing the new version from the edge channel:
```
 sudo snap install --channel=edge superproductivity
```

**Comment by ssalenik** [comment]
edge is only the latest release though (3.1.4), not HEAD

**Comment by johannesjo** [comment]
Should be head, if I'm not mistaken. It just gets the last release version as version number.

**Comment by ssalenik** [comment]
Oh, you're right. That's confusing.
Anyways, seems reasonable the way it is right now.
Only thing, I'm not 100% sure on this, but its possible that when the next session started it didn't make the notification sound. But maybe I just didn't hear it...

**Comment by johannesjo** [comment]
There is a Pomodoro Setting called `Play sound when break is done` if that one is not checked, then you will hear no sound after a break.
