### ISSUE TITLE
Security Issue: Code execution

### ISSUE THREAD

**Issue by xclow3n** [johannesjo/super-productivity#2837]
Hey,

There is a code execution in this application. I have tested this in the [latest version](https://github.com/johannesjo/super-productivity/releases/download/v7.14.3/superProductivity-7.14.3.AppImage) on Linux; since there is no "Security policy" for this project, where should I report it? It's not a good idea to share it here where anyone can view it.

Thanks

**Comment by xclow3n** [comment]
Apparently it's possible to achieve code execution on super productivity via a XSS

**Comment by johannesjo** [comment]
Thank you! You can report it directly to me:
contact@super-productivity.com

**Comment by xclow3n** [comment]
Hey, kindly check your mail :)

**Comment by johannesjo** [comment]
Thank you very much once more! This should be fixed now!
