### ISSUE TITLE
[Feature Request] - 'Send feedback' button

### ISSUE THREAD

**Issue by prabhanshu11** [johannesjo/super-productivity#284]
* Desktop Environment:  KDE 

### Expected Behavior

 There should be a feedback button with an option to upload screenshots or screencasts.

**Comment by johannesjo** [comment]
Hey there! Thanks for the suggestion! What issue did you encounter?

I generally like the idea, but I wouldn't put it very high in my priority list, as there is currently enough other stuff to work on.

**Comment by johannesjo** [comment]
Thanks again for the suggestion. I added this to the footer. This is not a real prominent "add feedback" button should be a good compromise between cluttering the UI and encouraging users to provide feedback.
