### ISSUE TITLE
Eisenhower Mode

### ISSUE THREAD

**Issue by looni01** [johannesjo/super-productivity#2841]
I was wondering if it's possible to implement an "Eisenhower Mode" (I made this little sketch as example)? :)

![Eisenhower Mode](https://github.com/johannesjo/super-productivity/assets/112870059/6e874cbf-0602-4580-8efd-9de2cd3b4406)

Even though you can already prioritize your tasks in SuperProductivity (by dragging them to the top or adding tags) I haven't found a way to see all tasks from all projects at once and then prioritize them. 
Since I have many projects, I often find myself struggling to keep track of the most important & most urgent tasks - I jump from project to project thinking about which task to do first and often lose sight of the overall Big Picture. 

The Eisenhower Matrix is a productivity concept that helps you view all of your tasks at once, and you can then prioritize them into the following four categories: 
A) Urgent & Important = Do it now (f.e. urgent deadlines)
B) Not Urgent & Important = Schedule (f.e. exercise)
C) Urgent & Not Important = Delegate (f.e. book vacation flight)
D) Not Urgent & Not important = Eliminate (f.e. time wasters)

I'm curious to know what you and the community think about that idea. :)

Thank you so much for developing this amazing app, I think it's really awesome and it already helped me and my friends so much!! :)

**Comment by johannesjo** [comment]
I use tags (a, b, c, d)  for this. Very easy to add via short syntax, e.g.:
```
Some important task #a 
Some important but non urgent task #b 
....
```

**Comment by johannesjo** [comment]
Btw. this should be rather a [discussion](https://github.com/johannesjo/super-productivity/discussions) than an issue.
