### ISSUE TITLE
Worklog Empty

### ISSUE THREAD

**Issue by paulwwarner** [johannesjo/super-productivity#2843]
### Your Environment

- Version used: superProductivity_7.7.0_amd64.deb
- Operating System and version: Ubuntu 18.04
- Desktop Environment: Gnome
- Browser Name and version: 

### Expected Behavior

I click on Super Productivity in the left menu bar, and select Worklog from the dropdown menu.  I should see a history of my worksessions for the current year.  If I select Quick History from the same dropdown list, I should see a summary of my history.

I saw the correct information yesterday.  Today it is gone!  The summary work history is still present next to each individual entry in my project lists.

### Current Behavior

All this worked fine yesterday, but today, for Quick History, I see "No data for current year."  For the Worklog, I see Time Spent Total: -

I see no information for my work history.  However, when I look at individual items in my project lists, they contain a time total on the right hand side.

### Steps to Reproduce (for bugs)

1.  Open the app
2.  Click Super Productivity
3.  From the right dropdown, select Worklog 
4.  No data is displayed.

### Can you reproduce this reliably?

I restarted my machine, and the empty field came up again.

### Console Output

model-version.ts:36 [M] Migrating model "TaskRepeat" to version from undefined to 1.43 
Object
persistence.service.ts:338 LOAD COMPLETE false
model-version.ts:36 [M] Migrating model "GlobalConfig" to version from 2.2009 to 2.203 
Object
migrate-global-config.util.ts:113 EXTEND globalConfig misc startOfNextDay 0
migrate-global-config.util.ts:113 EXTEND globalConfig pomodoro isManualContinueBreak false
model-version.ts:36 [M] Migrating model "SimpleCounter" to version from undefined to 2 
Object
model-version.ts:36 [M] Migrating model "Improvement" to version from undefined to 1 
Object
model-version.ts:36 [M] Migrating model "Obstruction" to version from undefined to 1 
Object
model-version.ts:36 [M] Migrating model "TaskRepeat" to version from undefined to 1.43 
Object
action-logger.reducer.ts:11 [WorkContext] Set Active Work Context 
Object
action-logger.reducer.ts:11 [Task] SetSelectedTask 
Object
quick-history.component.ts:36 worklogService.quickHistoryWeeks$ null
quick-history.component.ts:36 worklogService.quickHistoryWeeks$ null
quick-history.component.ts:36 worklogService.quickHistoryWeeks$ null
quick-history.component.ts:36 worklogService.quickHistoryWeeks$ 
Array(0)
quick-history.component.ts:36 worklogService.quickHistoryWeeks$ 
Array(0)
quick-history.component.ts:36 worklogService.quickHistoryWeeks$ 
Array(0)
action-logger.reducer.ts:11 [Bookmark] Load Bookmark State 
Object
action-logger.reducer.ts:11 [Project] Load Project related Data Success 
Object
action-logger.reducer.ts:11 [Improvement] Clear Hidden Improvements 
Object
action-logger.reducer.ts:11 [Improvement] Delete multiple Improvements 
Object
persistence.service.ts:338 LOAD COMPLETE false
model-version.ts:36 [M] Migrating model "GlobalConfig" to version from 2.2009 to 2.203 
Object
migrate-global-config.util.ts:113 EXTEND globalConfig misc startOfNextDay 0
migrate-global-config.util.ts:113 EXTEND globalConfig pomodoro isManualContinueBreak false
model-version.ts:36 [M] Migrating model "SimpleCounter" to version from undefined to 2 
Object
model-version.ts:36 [M] Migrating model "Improvement" to version from undefined to 1 
Object
model-version.ts:36 [M] Migrating model "Obstruction" to version from undefined to 1 
Object
model-version.ts:36 [M] Migrating model "TaskRepeat" to version from undefined to 1.43 
Object
persistence.service.ts:338 LOAD COMPLETE false
model-version.ts:36 [M] Migrating model "GlobalConfig" to version from 2.2009 to 2.203 
{lang: {…}, misc: {…}, evaluation: {…}, idle: {…}, takeABreak: {…}, …}
migrate-global-config.util.ts:113 EXTEND globalConfig misc startOfNextDay 0
migrate-global-config.util.ts:113 EXTEND globalConfig pomodoro isManualContinueBreak false
model-version.ts:36 [M] Migrating model "SimpleCounter" to version from undefined to 2 
{ids: Array(2), entities: {…}}
model-version.ts:36 [M] Migrating model "Improvement" to version from undefined to 1 
{ids: Array(0), entities: {…}, hideDay: null, hiddenImprovementBannerItems: Array(0)}
model-version.ts:36 [M] Migrating model "Obstruction" to version from undefined to 1 
{ids: Array(0), entities: {…}}
model-version.ts:36 [M] Migrating model "TaskRepeat" to version from undefined to 1.43 
{ids: Array(0), entities: {…}}
﻿

### Error Log (Desktop only)

The error log's last entry is in February, 2023!

[2022-11-12 22:05:06.974] [info]  Quit after all windows being closed
[2023-02-19 10:12:07.283] [info]  { enabled: null, showDevTools: false, mode: 'bottom' }
[2023-02-19 10:12:07.614] [info]  Saving backups to /home/pwarner/.config/superProductivity/backups
[2023-02-19 10:12:08.321] [info]  No custom styles detected at /home/pwarner/.config/superProductivity/styles.css
[2023-02-19 10:12:08.417] [info]  Error: Global Shortcut registration failed: Ctrl+Shift+X
    at Object.errorHandlerWithFrontendInform (/opt/superProductivity/resources/app.asar/electron/error-handler-with-frontend-inform.js:10:18)
    at /opt/superProductivity/resources/app.asar/electron/main.js:368:58
    at Array.forEach (<anonymous>)
    at registerShowAppShortCuts (/opt/superProductivity/resources/app.asar/electron/main.js:328:14)
    at IpcMainImpl.<anonymous> (/opt/superProductivity/resources/app.asar/electron/main.js:277:5)
    at IpcMainImpl.emit (events.js:376:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9959)
    at Object.emit (events.js:376:20)
[2023-02-19 10:12:08.417] [error] Global Shortcut registration failed: Ctrl+Shift+X Error: Global Shortcut registration failed: Ctrl+Shift+X
    at Object.errorHandlerWithFrontendInform (/opt/superProductivity/resources/app.asar/electron/error-handler-with-frontend-inform.js:10:18)
    at /opt/superProductivity/resources/app.asar/electron/main.js:368:58
    at Array.forEach (<anonymous>)
    at registerShowAppShortCuts (/opt/superProductivity/resources/app.asar/electron/main.js:328:14)

**Comment by johannesjo** [comment]
Thank you very much for opening this up! Testing this on my machine the worklog works just fine.

It might be that for some reason a bit of your data got into an invalid state that I didn't account for and that I can't reproduce. It would be great if you could share a copy of your data to contact@super-productivity.com, so I can debug this on my computer (and please let me know here, if you send something, as those mails quite often land in the spam folder). You can create an export by navigating to "Settings" and then to "Import/Export" or you can use the "Export data" button from the error Dialog (there is also a button there which will anonymize the data before exporting).
