### ISSUE TITLE
Button to sort the tasks by tag

### ISSUE THREAD

**Issue by guillaumesagnol** [johannesjo/super-productivity#2844]
## Problem Statement
We have the possibility to reorder the tasks by moving them by drag-and-drop, which is very convenient. However, I have the feeling that some kind of automatic sorting function is missing. Especially, I think it would be nice to have the ability to sort the tasks "by Tag". For example, I use the tags #P1, #P2, #P3 to indicate the priority level of my tasks and it would be practical to have a view in which the taks of any project are ordered accordingly.

## :grey_question: Possible Solution
The easiest-to-implement solution would probably be to have a button that orders the tasks in the same order as the tags are ordered in the left pannel. In the event where a task has multiple tags, I guess the "highest" tag should be taken into account, and the remaining tags could be used to "break tie" for the ordering. Whether tasks without tag should appear first or last could be a user-setting.

**Comment by franco-ruggeri** [comment]
This is still relevant and can also help #2920
