### ISSUE TITLE
Tags should not match spaces or generally be less sensitive to hashtags being used

### ISSUE THREAD

**Issue by rklec** [johannesjo/super-productivity#2856]
I wanted to make a task out of a Pluralsight title course, but this course contained the word `C#` which caused it to interpret everything following the hashtag as a tag.

### Your Environment

- Version used:  7.1.4.3 from Windows Installer
- Operating System and version: Windows 10
- Desktop Environment:  N/A
- Browser Name and version:  N/A

### Expected Behavior

> [Making Your C# 7 Code More Functional](https://app.pluralsight.com/courses/a9abb7dc-66d2-4881-91fe-52e836826577/table-of-contents)

It creates the tag "7 Code More Functional" on the task "Making Your C", which is quite fun, but not what I want.

![grafik](https://github.com/johannesjo/super-productivity/assets/71322635/bdbf5b11-f208-48aa-9608-bb6a42c9aaba)

Note it does this **even though" there is a space after the sharp (#) sign!

### Current Behavior

![grafik](https://github.com/johannesjo/super-productivity/assets/71322635/433dfb7a-5829-49a6-8e69-11423661d635)
![grafik](https://github.com/johannesjo/super-productivity/assets/71322635/8812bd45-6cf1-422f-8ca7-4a3086f93a08)

### Steps to Reproduce (for bugs)

Copy "[Making Your C# 7 Code More Functional](https://app.pluralsight.com/courses/a9abb7dc-66d2-4881-91fe-52e836826577/table-of-contents)" (maybe the HTML formatting matters, but I doubt it)

![grafik](https://github.com/johannesjo/super-productivity/assets/71322635/22cd0487-5328-49ae-8f15-34e920fb94a5)
![grafik](https://github.com/johannesjo/super-productivity/assets/71322635/d6c71aac-7ddc-44ab-ab2f-69e999b978b8)

### Can you reproduce this reliably?

Yes. 
Reproducible.

### Console Output

```
action-logger.reducer.ts:11 [Layout] Show AddTaskBar {type: '[Layout] Show AddTaskBar'}
action-logger.reducer.ts:11 [Task][Issue] Add Task {task: {…}, workContextId: 'uzWenZ18BHBh29v8tgq7h', workContextType: 'PROJECT', isAddToBacklog: false, isAddToBottom: false, …}isAddToBacklog: falseisAddToBottom: falsetask: {id: 'GjzCMSpXqcHeCHZc8GrBB', projectId: 'uzWenZ18BHBh29v8tgq7h', subTaskIds: Array(0), timeSpentOnDay: {…}, timeSpent: 0, …}type: "[Task][Issue] Add Task"workContextId: "uzWenZ18BHBh29v8tgq7h"workContextType: "PROJECT"[[Prototype]]: Object
task-related-model.effects.ts:193 shortSyntax {taskChanges: {…}, newTagTitles: Array(0), remindAt: null, projectId: undefined}newTagTitles: []projectId: undefinedremindAt: nulltaskChanges: {tagIds: Array(1), title: 'Making Your C'}[[Prototype]]: Object
action-logger.reducer.ts:11 [Persistence] Save to DB {dbKey: 'project', data: {…}, type: '[Persistence] Save to DB'}
action-logger.reducer.ts:11 [Persistence] Save to DB {dbKey: 'task', data: {…}, type: '[Persistence] Save to DB'}
action-logger.reducer.ts:11 [Task] Update Task {task: {…}, type: '[Task] Update Task'}
action-logger.reducer.ts:11 [Task] Update Task Tags {task: {…}, newTagIds: Array(1), oldTagIds: Array(0), type: '[Task] Update Task Tags'}
action-logger.reducer.ts:11 [Persistence] Save to DB {dbKey: 'task', data: {…}, type: '[Persistence] Save to DB'}
action-logger.reducer.ts:11 [Persistence] Save to DB {dbKey: 'tag', data: {…}, type: '[Persistence] Save to DB'}
action-logger.reducer.ts:11 [Persistence] Save to DB {dbKey: 'task', data: {…}, type: '[Persistence] Save to DB'}
action-logger.reducer.ts:11 [Layout] Hide AddTaskBar {type: '[Layout] Hide AddTaskBar'}type: "[Layout] Hide AddTaskBar"[[Prototype]]: Object
persistence.service.ts:338 LOAD COMPLETE false
model-version.ts:36 [M] Migrating model "GlobalConfig" to version from 2.203 to 2.303 {lang: {…}, misc: {…}, evaluation: {…}, idle: {…}, takeABreak: {…}, …}
migrate-global-config.util.ts:113 EXTEND globalConfig sound breakReminderSound null
```

Nothing relevant though.

### Error Log (Desktop only)

nothing relevant

**Comment by rklec** [comment]
Weird enough (but maybe good in my use case), if the tag is already created, it does not recreate it. Even if you then remove it, it seems to keep it now hmm...

**Comment by KatrinIhler** [comment]
Seconded! I'm always surprised when I paste a URL containing a # and the latter half of it just decides to be a tag instead. :D 

Also the possibility to escape a # to circumvent this behavior would be great. I sometimes reference issue numbers with #, which works well if it's the very first thing in the task title, but not if there's anything in front of it. I think I could get into the habit of escaping if such a thing existed...

**Comment by Jagdfalke** [comment]
The current version 8.0.1 handles tags more sensible. The above given sample text will not create a new tag anymore. 

Additionally, whenever a new tag is supposed to be created, Super Productivity will prompt you whether a new tag should be created.
