### ISSUE TITLE
Bug Report: Inability to Navigate Back to Deleted Tag's Page

### ISSUE THREAD

**Issue by mathe00** [johannesjo/super-productivity#2860]
### Your Environment

- Version used: 7.15.0
- Operating System and version: Manjaro Linux
- KDE Plasma Version: 5.27.9
- KDE Frameworks Version: 5.111.0
- Qt Version: 5.15.11
- Kernel Version: 6.5.11-1-MANJARO (64-bit)
- Graphic Platform: X11
- Processors: 8 × Intel® Core™ i7-9700 CPU @ 3.00GHz
- Memory: 15.6 GB RAM
- Graphics Processor: NV174
- Manufacturer: Micro-Star International Co., Ltd.
- Product Name: MS-7B51
- System Version: 1.0

### Expected Behavior

Upon deleting a tag, using the mouse's back button should navigate back to the previous page of the deleted tag without displaying an error.

### Current Behavior

After deleting a tag, using the mouse's back button does not navigate back to the page of the deleted tag. Instead, it displays a red error message. Here's the associated error code:

```
Error: Uncaught (in promise): Error: No tag CC6hKAjAkKIoDhez91hPK 
Error: No tag CC6hKAjAkKIoDhez91hPK at file:///tmp/.mount_superPWoZU5G/resources/app.asar/dist/main.69a7a59a6fd6ea5e.js:1:260606 ...
(META: SP7.15.0 Electron – fr – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.15.0 Chrome/114.0.5735.289 Electron/25.9.0 Safari/537.36)
```

### Steps to Reproduce (for bugs)

1. Open the application and navigate to the tag section.
2. Delete a tag by clicking on the delete button.
3. Use the mouse's back button to attempt to return to the deleted tag's page.
4. Observe the display of the error message mentioned above instead of navigating back to the tag's page.

### Can you reproduce this reliably?

Yes, this issue can be reproduced consistently by following the steps mentioned above.

### Console Output

No relevant output observed in the console.

### Error Log (Desktop only)

Error: Uncaught (in promise): Error: No tag CC6hKAjAkKIoDhez91hPK 
Error: No tag CC6hKAjAkKIoDhez91hPK at file:///tmp/.mount_superPWoZU5G/resources/app.asar/dist/main.69a7a59a6fd6ea5e.js:1:260606 ...
(META: SP7.15.0 Electron – fr – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.15.0 Chrome/114.0.5735.289 Electron/25.9.0 Safari/537.36)

**Comment by johannesjo** [comment]
Thank you very much! Will be fixed with the next release.
