### ISSUE TITLE
gamification mode

### ISSUE THREAD

**Issue by youtaprise** [johannesjo/super-productivity#2861]
Problem Statement:

I have motivation problems for my daily routines. The principle of gamification would be a good approach. My idea is this:

Possible Solution:

- Option with Gamification (on /off):
- While activated, you have a individual avatar with 4 attributes (name, level, experience-points & coins) -> The Avatar could be a .png file with a personal picture.
- Each Tasks has a difficulty level ( higher difficulty level = more coins & experience, after finishing the task)
- Once you have a certain number of experience points, you move up a level
- You can use the coins to give yourself rewards (watching a movie, gaming, etc. (a list with personal rewards and the cost for each one)
- Scheduled tasks that have not been completed will result in negative coins

The idea is to create something like habitica, but without all the buying stuff distraction. Just a simple overview of your progress to keeps you motivated. That's all.

**Comment by imotos** [comment]
The idea sounds really great. Can someone please take care of this? I would even pay for the feature
