### ISSUE TITLE
PUA.OSX.Adware on VirusTotal

### ISSUE THREAD

**Issue by dragonfire1119** [johannesjo/super-productivity#2865]
Starting with 7.14.3, VirusTotal is saying: `PUA.OSX.Adware`. 7.13.2 does not have `PUA.OSX.Adware` reported.

**Comment by johannesjo** [comment]
Thanks for letting us know! I'd appreciate if someone would contact them about the false positive.

**Comment by dragonfire1119** [comment]
> Thanks for letting us know! I'd appreciate if someone would contact them about the false positive.

You're welcome! Great work on the project. Maybe something has changed to trip a false positive?

**Comment by johannesjo** [comment]
> You're welcome! Great work on the project. Maybe something has changed to trip a false positive?

There is a new electron version used, but this would apply to many apps.
