### ISSUE TITLE
Wrong slash / in UNC path in Settings/Automatic backups

### ISSUE THREAD

**Issue by MaximFworks** [johannesjo/super-productivity#2869]
Windows 10 store version, authlogh it seems like i've seen it on exe-installer version in previous versions aslo.

Picture explains it all 
![aaaaaaa](https://github.com/johannesjo/super-productivity/assets/137869596/5ddcda4a-9edc-4cde-a40c-e0abc1719133)

**Comment by Sanket-Arekar** [comment]
I would like to work on this issue. Can you Please assign me this issue?
