### ISSUE TITLE
Service worker registration error

### ISSUE THREAD

**Issue by bytrangle** [johannesjo/super-productivity#2873]
### Your Environment

- Version used: Latest version from Master branch
- Operating System and version: Linux Mint
- Desktop Environment: 
- Browser Name and version: Firefox 108.0.1

### Current Behavior

When the app is bootstrapped, the service worker is registered according to src/main.ts

```
platformBrowserDynamic()
  .bootstrapModule(AppModule)
  .then(() => {
    if (
      'serviceWorker' in navigator &&
      (environment.production || environment.stage) &&
      !IS_ELECTRON
    ) {
      console.log('Registering Service worker');
      return navigator.serviceWorker.register('ngsw-worker.js');
  }
  .catch((err: any) => {
    console.log('Service Worker Registration Error');
    console.log(err);
  });
```
Looking at the console, there is an error with registering service worker and the `catch` clause is run. The error is:

TypeError: ServiceWorker script at http://localhost:4200/ngsw-worker.js for scope http://localhost:4200/ encountered an error during installation.

### Expected Behavior
If you register it, you expect it to be successful, correct?

The service worker not being installed also means that this code block in the NotifyService is skipped:

```
    const svcReg =
      this._isServiceWorkerAvailable() &&
      (await navigator.serviceWorker.getRegistration('ngsw-worker.js'));
    console.log({ svcReg })
    if (svcReg && svcReg.showNotification) {
      // service worker also seems to need to request permission...
      // @see: https://github.com/johannesjo/super-productivity/issues/408
      const per = await Notification.requestPermission();
      // not supported for basic notifications so we delete them
      if (per === 'granted') {
        await svcReg.showNotification(title, {
          icon: 'assets/icons/icon-128x128.png',
          vibrate: [100, 50, 100],
          silent: false,
          data: {
            dateOfArrival: Date.now(),
            primaryKey: 1,
          },
          ...options,
          body,
        });
      }
```

### Steps to Reproduce (for bugs)

1. In the terminal, run `npm run serveProd`. This is to ensure that we are in `production` environment and the app will register the service worker.
2. Open the app at `http://localhost:4200`.
3. Open the web console.
4. You should see an error for registering service worker.

### Can you reproduce this reliably?
Yes

### Console Output

![service-worker-installation-error](https://github.com/johannesjo/super-productivity/assets/28924121/0b36d1d8-683b-4fcf-bbb1-8ddab6f8fd60)

**Comment by bytrangle** [comment]
**Update**: I've discovered that the error was due to the `ngsw-worker.js` file not being generated. And service worker doesn't work with `ng serve` anyway, so I ran `npm run build`. The `ngsw-worker` file is not present in the `dist/` directory either.

It turns out that in the `angular.json` file,  you set `servviceWorker` to false for `production` mode. Is it the intention?

**Comment by johannesjo** [comment]
Service Worker is only run for web. If you Use `buildFrontend:prodWeb` everything should work fine.
