### ISSUE TITLE
Disable spell checking

### ISSUE THREAD

**Issue by imotos** [johannesjo/super-productivity#2874]
Problem Statement:

When I work with multiple languages, everything that doesn't correspond to the standard language is always highlighted in red, which is quite unpleasant and distracting while I'm writing.

Possible Solution:

Add a button to turn on and off

 Additional context:

I tried with bash-scripting, but that isn't what I am looking for. I would like a simple and easy way to turn it off without changing all applications at ones. Please Help:/

![Screenshot from 2023-11-25 12-52-03](https://github.com/johannesjo/super-productivity/assets/151948886/4c6e1d25-c5fd-4a79-a89f-fe021eb2500a)

**Comment by johannesjo** [comment]
PRs are welcome!
