### ISSUE TITLE
Google Drive iCal not working in Timeline view

### ISSUE THREAD

**Issue by mathisgauthey** [johannesjo/super-productivity#2886]
### Your Environment

Desktop : Windows 11 pro
Phone : Android 14 on a Pixel 7

### Expected Behavior

Adding calendar secret URL from google calendar should allow me to view calendar items on the timeline.

### Current Behavior

Nothing is shown on my timeline

### Steps to Reproduce (for bugs)

Use a google calendar iCal secret link to the .ics file and go to your timeline view. There is no calendar entry, just your planned tasks for the day.

### Console Output

```
icalEvents$ []length: 0[[Prototype]]: Array(0)at: ƒ at()concat: ƒ concat()constructor: ƒ Array()from: ƒ from()isArray: ƒ isArray()length: 1name: "Array"of: ƒ of()prototype: [constructor: ƒ, at: ƒ, concat: ƒ, copyWithin: ƒ, fill: ƒ, …]Symbol(Symbol.species): ƒ Array()Symbol(Symbol.species): ƒ Array()arguments: (...)caller: (...)[[Prototype]]: ƒ ()[[Scopes]]: Scopes[0]copyWithin: ƒ copyWithin()entries: ƒ entries()every: ƒ every()fill: ƒ fill()filter: ƒ filter()find: ƒ find()length: 1name: "find"arguments: (...)caller: (...)[[Prototype]]: ƒ ()[[Scopes]]: Scopes[0]findIndex: ƒ findIndex()findLast: ƒ findLast()findLastIndex: ƒ findLastIndex()flat: ƒ flat()flatMap: ƒ flatMap()forEach: ƒ forEach()includes: ƒ includes()indexOf: ƒ indexOf()join: ƒ join()keys: ƒ keys()lastIndexOf: ƒ lastIndexOf()length: 0map: ƒ map()pop: ƒ pop()push: ƒ push()reduce: ƒ reduce()reduceRight: ƒ reduceRight()reverse: ƒ reverse()shift: ƒ shift()slice: ƒ slice()some: ƒ some()sort: ƒ sort()splice: ƒ splice()toLocaleString: ƒ toLocaleString()toReversed: ƒ toReversed()toSorted: ƒ toSorted()toSpliced: ƒ toSpliced()toString: ƒ toString()unshift: ƒ unshift()values: ƒ values()with: ƒ with()Symbol(Symbol.iterator): ƒ values()Symbol(Symbol.unscopables): {at: true, copyWithin: true, entries: true, fill: true, find: true, …}[[Prototype]]: Object
```

It seems like he can't fetch any of the calendar.

### Error Log (Desktop only)

Not provided.

**Comment by mathisgauthey** [comment]
Gosh, found the issue : 

![image](https://github.com/johannesjo/super-productivity/assets/46576952/54b32d25-67c1-49db-86c0-d2333e043bf8)

Basically what happened was that the checkbox was "checked" with a `-` symbol, so little old me not paying enough attention got there thinking it was checked.

So I clicked, it went to a ✅, and now I can only have a blank 🔲 or a ✅.

I think it would be better if the first time you add a calendar it is a 🔲 instead of a sort of checkbox with a minus `-` inside.

So I keep the issue opened !

**Comment by Jagdfalke** [comment]
In the latest version (8.0.1) the calendar integration is enabled via a toggle switch and not by checkbox anymore.
