### ISSUE TITLE
Global system wide Show/Hide Super Productivity is broken in v7.15.0

### ISSUE THREAD

**Issue by kanunnikau** [johannesjo/super-productivity#2887]
Hello. I have just installed the latest version [7.15.0](https://github.com/johannesjo/super-productivity/releases/tag/v7.15.0) and the app ignored my "Show/Hide Super Productivity" shortcut.
Then I went to a bit older version (7.14.3) and it is working as expected.

### Your Environment

- Version used: [7.15.0](https://github.com/johannesjo/super-productivity/releases/tag/v7.15.0)
- Operating System and version: OpenSuse Tumbleweed
- Desktop Environment: KDE

App installed via rpm.

### Expected Behavior
My "Show/Hide Super Productivity" shortcut should toggle the window.

### Current Behavior

The shortcut doesn't do anything. Changing the shortcut doesn't help.

### Steps to Reproduce (for bugs)

Try to use a shortcut to "Show/Hide Super Productivity". It doesn't work.

### Can you reproduce this reliably?

Yes, the shortcut is just inactive in version 7.15.0.

### Error Log (Desktop only)

No errors.

**Comment by QThans** [comment]
same

**Comment by Looooong** [comment]
It's the same for me along with the `Toggle time tracking for last active task` shortcut as well.
+ Version used: [7.15.0](https://github.com/johannesjo/super-productivity/releases/tag/v7.15.0)
+ Operating System and version: Window 11 (build 22621.2715)

**Comment by diloquent** [comment]
It's the same for all system wide global shortcuts no matter what combination or if the window is focused or not, application wide shortcuts are working ok though.

- Version used: [7.15.0](https://github.com/johannesjo/super-productivity/releases/tag/v7.15.0)
- Operating System and version: Archlinux
- Desktop Environment: KDE

**Comment by Jagdfalke** [comment]
With the current version 8.0.1 shortcuts work as expected.
