### ISSUE TITLE
[Bug] Cannot scroll in Tasks View

### ISSUE THREAD

**Issue by Mindstormer619** [johannesjo/super-productivity#289]
- **Version:** 3.2.0
- **Variant:** PWA on app.super-productivity.com
- **OS:** Windows 10
- **Browser:** Chrome v80.0 32-bit 

Scrolling in the tasks view no longer works with the latest update. I don't see the vertical scroll bar, and scrolling with the mousewheel doesn't work either. 

Does not get fixed with resizing or restarting the app window. 

It works perfectly on other pages like Settings and Worklog. It's only a problem in the main tasks view. I can replicate this with the webapp on mobile as well.

**Comment by Mindstormer619** [comment]
Quick update: I just figured out that a quick workaround for this is to pull up the backlog pane from the bottom and send it back down. This makes the tasks window scrollable. Maybe it'll be helpful for debugging what's going on.

**Comment by johannesjo** [comment]
Thank you very much for reporting. I'll try to check this tomorrow.

**Comment by johannesjo** [comment]
I think I found a fix. Will publish a new version soon.

**Comment by Mindstormer619** [comment]
Thank you so much, this has been fixed as of your version following Feb 14. Forgot to close this issue :)
