### ISSUE TITLE
superProductivity v 7.15.0 quit unexpectedly on mac M1 (Sonoma) when installed using brew

### ISSUE THREAD

**Issue by marotron** [johannesjo/super-productivity#2898]
### Your Environment

- Version used: superProductivity-7.15.0-arm64.dmg (installed using brew)
- Operating System and version: macOS Sonoma 14.1.2 (23B92) on macbook air M1
- Desktop Environment: 
- Browser Name and version: 

### Expected Behavior

I expected it to open normally, after installation.
 
### Current Behavior
I normally use version 7.11.5 (7.11.5) installed from the webpage and it's worked but I have noticed it is an old version (2022) and that there is a newer version available. So I followed instruction from github and installed the new 7.15.0 version using brew. After successful (as I assume) installation:
```
$ brew install --cask superproductivity
==> Downloading https://github.com/johannesjo/super-productivity/releases/download/v7.15.0/superProductivity-7.15.0-arm64.dmg
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/78243781/0e896567-4aa4-4817-97eb-27af36323586?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CS
######################################################################################################################################################################################################### 100.0%
==> Installing Cask superproductivity
==> Moving App 'superProductivity.app' to '/Applications/superProductivity.app'
🍺  superproductivity was successfully installed!
```

I tried to run it, but it crashed while it was opening.

```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               superProductivity [72205]
Path:                  /Applications/superProductivity.app/Contents/MacOS/superProductivity
Identifier:            com.super-productivity.app
Version:               7.15.0 (7.15.0)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               502

Date/Time:             2023-12-04 10:55:36.3193 +0000
OS Version:            macOS 14.1.2 (23B92)
Report Version:        12
Anonymous UUID:        5C8885B5-237A-B91D-4B54-E4DD37D11755

Sleep/Wake UUID:       4C88F8B1-2A6D-4859-A4AB-743967A3E1E9

Time Awake Since Boot: 40000 seconds
Time Since Wake:       6810 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x000000010e2de64c

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [72205]
```
<img width="1112" alt="Screenshot 2023-12-04 at 11 22 37" src="https://github.com/johannesjo/super-productivity/assets/4615517/96893699-ad5a-4f17-ba74-2b1ebbbe8908">

*there is more data in the crash report, I am happy to share in private*

### Steps to Reproduce (for bugs)

1. Install version 7.15.0 on macbook M1 with Sonoma OS using brew `brew install --cask superproductivity`
2. Run the superproductivity app

### Can you reproduce this reliably?

Yes, every time I try to open it, it crashes.

**Comment by noname77** [comment]
hey again,

I want to report that I just updated my m1 Mac to Sonoma and also bumped superProductivity to 7.16.0 with `brew` today and all is running as expected

```bash
% sw_vers -productVersion           
14.1.2

% brew update
% brew upgrade
==> Upgrading 8 outdated packages:
superproductivity 7.12.1 -> 7.16.0
```
