### ISSUE TITLE
Object has been destroyed

### ISSUE THREAD

**Issue by johannesjo** [johannesjo/super-productivity#29]
@Atem18

## Your Environment
* Version used: 1.4.2 DEB
* Operating System and version: Debian Sid
* Desktop Environment: Gnome Shell
## Current Behavior

@johannesjo It's worse, application relaunch again and again with that error:
![screenshot from 2017-11-21 16-05-25](https://user-images.githubusercontent.com/2875254/33079437-dafa9566-ced5-11e7-8cf2-1c3e053bc06e.png)

Using the DEB package on Debian Sid with Gnome Shell
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by Atem18** [comment]
## Steps to Reproduce (for bugs)
1. Open application
2. Click on close button
3. Open application again
4. Does not open a new window and instead relaunch again and again with the error "Object has been destroyed" after clicking on button "OK".

**Comment by johannesjo** [comment]
I just tried installing it with the latest debian version. Everything runs fine. Could you maybe post what the output of the installation process is? Maybe something is going wrong there.

**Comment by johannesjo** [comment]
I'm assuming that this is fixed now with the latest version. Could you please check again?

**Comment by Atem18** [comment]
@johannesjo Same problem with the latest version : 1.6.3
![screenshot from 2017-11-30 10-00-13](https://user-images.githubusercontent.com/2875254/33422291-83c5d490-d5b5-11e7-8fba-bda6286d06c3.png)
![screenshot from 2017-11-30 10-00-27](https://user-images.githubusercontent.com/2875254/33422294-85b247de-d5b5-11e7-808c-50e6da6dd5dd.png)

**Comment by johannesjo** [comment]
@Atem18 that seems to be a bug with electrons `makeSingleInstance` that hopefully will go away in a later iteration of electron.

In the meantime I'll to to fix this by some dirty work around, which hopefully will work on your system.

Could you do me another favor and start the app from the command line twice once the next release is out? I'm curious what additional output is there.

**Comment by Atem18** [comment]
@johannesjo It does not crash, but when I click on the close button, it closes the window but the process is still here in CLI, so I have to to "ctrl-c" to relaunch it again.

**Comment by johannesjo** [comment]
Do you have the gnome shell extension installed?

**Comment by Atem18** [comment]
@johannesjo No

**Comment by johannesjo** [comment]
Ok I checked again. This should be fixed with the latest release. If you still have issues, please let me know!

**Comment by Atem18** [comment]
@johannesjo Perfect, works great !
