### ISSUE TITLE
Pomodoro timer does not respect option "Stop time tracking for task on break" when clicked

### ISSUE THREAD

**Issue by javierhb23** [johannesjo/super-productivity#2900]
### Your Environment

- Version used: v7.15.1
- Operating System and version: Archlinux
- Desktop Environment: KDE

### Expected Behavior

1. While on break and with the "Stop time tracking for task on break" option enabled, clicking the pomodoro timer should pause/resume the countdown.

2. (Not sure if this should go into another issue since it's related, and likely just an opinion) 
If pomodoro timer is paused while working, clicking "Skip" should ideally start counting down break time.

### Current Behavior

Timer does not stop, just toggles tracking the last active task.

### Steps to Reproduce (for bugs)

1. Start working on a task.
2. Pause the Pomodoro timer.
3. Click "Skip to the end of current Pomodoro session".
4. Click "Start/Stop tracking time".

### Can you reproduce this reliably?
Yes.

**Comment by Jagdfalke** [comment]
Probably related to #3088.
