### ISSUE TITLE
Windows | Is it only me or keyboard shortcut "toggle time tracking for last active task" does not work anymore

### ISSUE THREAD

**Issue by MaxITService** [johannesjo/super-productivity#2909]
- Version used: 7.16
- Operating System and version: Windows 10 and 11
- Desktop Environment: 
- Browser Name and version: 

### Expected Behavior

It paused/resumed the task, like press of a big round button does
### Current Behavior

No reaction
Seems like all system wide keyboard shortcuts do not work anymore. 

### Can you reproduce this reliably?

2 machines affected, with separate installs

### Console Output

attaching output, that happens on save, no output on key press combination
[console.log](https://github.com/johannesjo/super-productivity/files/13624578/console.log)
![Screenshot 2023-12-09 172934](https://github.com/johannesjo/super-productivity/assets/109969980/eab3ed52-31e6-4af1-bdd7-6a10a297bde4)

### Error Log (Desktop only)

Nothing related in error log.

**Comment by diloquent** [comment]
This is a known bug introduced in v7.15.0, see #2887
