### ISSUE TITLE
Backup path is broken on linux, plus automatic backup flag seems to be ignored

### ISSUE THREAD

**Issue by Mblakey** [johannesjo/super-productivity#2910]
Installed on linux through snap --edge channel 

Last slash before backup causes the folder to be saved in the home directory, is there no way to set the path in settings?

Also with automatic backups off, these backups are still being created?

![image](https://github.com/johannesjo/super-productivity/assets/78424742/7352be0c-b8eb-48f9-baab-49de4c8b0adc)

**Comment by Mblakey** [comment]
Closing as seen previous issue with commits fixing

**Comment by Mblakey** [comment]
issue #2869 has not seemed to have been fixed

**Comment by kushagra-xo** [comment]
can reproduce this, backup directory is now in $HOME

**Comment by jodyhoonstarr** [comment]
Confirmed as well. Good catch @kushagra-xo. Since installing 7.16.0 backups stopped appearing in `~/path/to/superProductivity\backups` and instead end up in a directory called `\backups` in $HOME.

Setup:
linux fedora 38
superproductivity v7.16.0
installed via packaged rpm

**Comment by k-nard** [comment]
I confirmed too. Same issue with AppImage. All backups are create in "$HOME/\backup".
Changing path or disabling configuration are totally ignored.

Setup:
openSUSE Leap 15.5
superproductivity v7.16.0
installed via AppImage

**Comment by q-wertz** [comment]
Not a Javascript developer but why not use https://nodejs.org/api/path.html#pathjoinpaths instead of trying to implement by oneself?

**Comment by Mblakey** [comment]
@q-wertz Agreed, would rather just have the option to set my own path rather then trying to make a universal option for all machines

**Comment by Emily3403** [comment]
It seams as if [this](https://github.com/johannesjo/super-productivity/commit/fb659ddf26f96d229b41027068c47c00ed70e824) recent commit broke the linux backup path. 

I think the issue it is that the `+` operator has higher precedence that the `==` operator.

From `electron/backup.ts`:
```typescript
let BACKUP_DIR =
  `${app.getPath('userData')}` + process.platform == 'linux' ||
  process.platform === 'darwin'
    ? `/`
    : `\\` + `backups`;
```

So it compares `/home/<user>/.config/superProductivity + process.platform` against `linux`.

**Comment by Mblakey** [comment]
@Emily3403 great find! Not a js developer here so was wondering if you also had any ideas why the automatic backup flag is being ignored? Regardless of the path being right or not

**Comment by Emily3403** [comment]
After the latest update 7.17.1, the issue seams fixed. I deleted the `\backups` directory and it did not get created again. Superproductivity also reports the correct backup path:
```
Saving backups to /home/emily/.config/superProductivity/backups
```
