### ISSUE TITLE
Make it easier to edit notes for scheduled events

### ISSUE THREAD

**Issue by KatrinIhler** [johannesjo/super-productivity#2932]
For me personally, it would be very helpful to be able to edit the description of a scheduled event in the Scheduled view directly. The ability to add notes to scheduled tasks is very helpful to gather questions or other agenda items for upcoming meetings, but currently doing so is a bit difficult:

Currently I go to the Scheduled view to find my scheduled event, add it to the Today view, edit the description and then kick it out of the Today view again. Of course I could also use the + to add it to the Today view, but the point remains that I can't get to the notes in the Scheduled view directly (or even see if a task has notes).

I'd be thrilled if the scheduled tasks in the Scheduled view also had the little "Show/Hide additional info" button for tasks.

**Comment by johannesjo** [comment]
I agree that this would be useful. Generally we need something like a dialog view of tasks which would also be useful for the worklog to view older tasks.

**Comment by KatrinIhler** [comment]
Still relevant!

**Comment by johannesjo** [comment]
Will be fixed with the next release.
