### ISSUE TITLE
See associated projects in worklog of Today

### ISSUE THREAD

**Issue by KatrinIhler** [johannesjo/super-productivity#2933]
I use projects to differentiate between work for different clients. At the end of the day, I enter all the time spent in my employer's time tracking system. 

However, some days I'm bad and only do this the next day, or even the day after that. In those cases, I use the worklog of Today to figure out where I spent my time, but the worklog only tells me the task, not the project/who it was for. Mostly I can guess correctly, but for more generic tasks I sometimes have to check by pulling the task back into To do, which is kind of annoying.

I am very happy with all the information that is displayed when finishing your day, but maybe we can get a bit more for those days where I have to look further into the past? :D

**Comment by johannesjo** [comment]
Thanks for opening this up. I agree that this would be useful information, both for the worklog, as well as the quick history.

**Comment by KatrinIhler** [comment]
Still relevant!
