### ISSUE TITLE
Schedule of task disappears when another tag is added

### ISSUE THREAD

**Issue by KatrinIhler** [johannesjo/super-productivity#2937]
I've noticed this a couple of times now, and this can lead to a meeting being missed if you don't double-check the schedule of the task.

To reproduce:
1. Create a task with at least one tag in the Today view
2. Schedule task for a time in the future
3. Add another tag to the task
4. The schedule immediately disappears and has to be recreated

This behavior persists consistently for me. There is no error in the console log. 

If you can't reproduce this error, please let me know and I will supply more information. :)

**Comment by johannesjo** [comment]
I am unable to reproduce this. Could you describe in a bit more detail what you are doing to make this happen? How do you schedule? What kind of tag are you adding (new one or existing one)? What is it's name? etc.

**Comment by Jagdfalke** [comment]
I've followed the exact steps that @KatrinIhler provided. I've used only existing tags and I've used the task dialogue to schedule the task. 

However, following the exact same steps right now, I am not able to reproduce the issue anymore. @KatrinIhler can you help out?

**Comment by Jagdfalke** [comment]
Okay, I got it. I can reproduce it again, if I right click the task to schedule it. This will directly trigger the schedule dialogue to appear. If I add another tag to the task after this, the scheduled time will disapper.

**Comment by johannesjo** [comment]
Still unable to reproduce this :( There should be some logs in the console starting with `shortSyntax`. Those should be helpful.

**Comment by Jagdfalke** [comment]
This is what it looks like in the console. I've only included the steps to schedule the task and add another tag to the task afterwards:
```
dialog-add-task-reminder.component.ts:163 false
dialog-add-task-reminder.component.ts:163 false
task.service.ts:762 1714114800000 1714114800000
task.service.ts:763 0
task.service.ts:764 {plannedAt: 1714114800000, remindCfg: 'AtStart'}
action-logger.reducer.ts:11 [Task] Schedule {task: {…}, plannedAt: 1714114800000, remindAt: 1714114800000, isMoveToBacklog: false, type: '[Task] Schedule'}
reminder.service.ts:231 saveReminders (2) [{…}, {…}]
action-logger.reducer.ts:11 [Persistence] Save to DB {dbKey: 'task', data: {…}, type: '[Persistence] Save to DB'}
action-logger.reducer.ts:11 [Persistence] Save to DB {dbKey: 'reminders', data: Array(2), type: '[Persistence] Save to DB'}
action-logger.reducer.ts:11 [Task] Update Task {task: {…}, type: '[Task] Update Task'}
action-logger.reducer.ts:11 [Persistence] Save to DB {dbKey: 'task', data: {…}, type: '[Persistence] Save to DB'}
action-logger.reducer.ts:11 [Task] Update Task {task: {…}, type: '[Task] Update Task'}
short-syntax.effects.ts:84 shortSyntax {taskChanges: {…}, newTagTitles: Array(0), remindAt: null, projectId: undefined}
action-logger.reducer.ts:11 [Persistence] Save to DB {dbKey: 'task', data: {…}, type: '[Persistence] Save to DB'}
action-logger.reducer.ts:11 [Task] Update Task {task: {…}, isIgnoreShortSyntax: true, type: '[Task] Update Task'}
action-logger.reducer.ts:11 [Task] Update Task Tags {task: {…}, newTagIds: Array(3), oldTagIds: Array(2), type: '[Task] Update Task Tags'}
action-logger.reducer.ts:11 [Persistence] Save to DB {dbKey: 'task', data: {…}, type: '[Persistence] Save to DB'}
action-logger.reducer.ts:11 [Persistence] Save to DB {dbKey: 'tag', data: {…}, type: '[Persistence] Save to DB'}
action-logger.reducer.ts:11 [Persistence] Save to DB {dbKey: 'task', data: {…}, type: '[Persistence] Save to DB'}
action-logger.reducer.ts:11 [Task] UnSchedule {id: '3K_CPd7Mo2qtZ9cfgnRUy', reminderId: 'TsqkZ7WUUJwB46VA6sNZW', isSkipToast: true, type: '[Task] UnSchedule'}
reminder.service.ts:231 saveReminders [{…}]
action-logger.reducer.ts:11 [Persistence] Save to DB {dbKey: 'task', data: {…}, type: '[Persistence] Save to DB'}
action-logger.reducer.ts:11 [Persistence] Save to DB {dbKey: 'reminders', data: Array(1), type: '[Persistence] Save to DB'}
action-logger.reducer.ts:11 [Task] Update Task {task: {…}, type: '[Task] Update Task'}
action-logger.reducer.ts:11 [Persistence] Save to DB {dbKey: 'task', data: {…}, type: '[Persistence] Save to DB'}
```

**Comment by johannesjo** [comment]
Finally was able to solve it. Problem was a special functionality that unschedules tasks if they get the today tag added and are scheduled for the default day start time on the current day. Thank you very much for your help @Jagdfalke !
