### ISSUE TITLE
Go back to work doesn't work

### ISSUE THREAD

**Issue by Acsigen** [johannesjo/super-productivity#294]
### Your Environment

* Version used: 4.0.0
* Operating System and version: Windows 10 x64 1909
* Desktop Environment: 
* Browser Name and version: 

### Expected Behavior
At the end of the break the "Go back to work button used to start the pomodoro timer on the last active task

### Current Behavior
Now nothing happends after the dialog dissapears

### Steps to Reproduce (for bugs)
1.Start task
2.Break arrives
3.Break ends
4.Press Go back to work button

**Comment by johannesjo** [comment]
Thank you very much for reporting! I'll have a look.

**Comment by johannesjo** [comment]
Can't reproduce this issue. Works fine with all the pomodoro settings I tested. What are your settings?

**Comment by Acsigen** [comment]
![image](https://user-images.githubusercontent.com/13287878/76342054-993bad00-6306-11ea-90fe-978739b51848.png)

**Comment by johannesjo** [comment]
Thank you! I am still unable to reproduce the issue. Works absolutely fine on my computer. Did you do anything else  in between the 4 steps? How do your tasks look like, especially the one you were tracking to before the break? And are you able to reproduce this consistently?

**Comment by Acsigen** [comment]
![test](https://user-images.githubusercontent.com/13287878/76677612-e22a8480-65d8-11ea-8d09-d39539bb0ebd.gif)

**Comment by johannesjo** [comment]
Thank you very  much! Very weird. Maybe it's windows specific, although I wouldn't know what could be a reason for that. I'll try to check this after I am through with stuff I am currently working on.

Another question: Are you a 100% sure the version is 4.0.0? Is that what is printed on the settings page?

**Comment by Acsigen** [comment]
Yes, I am 100% sure that it is 4.0.0. Maybe it is Windows, I updated it just before updating the app. But since the bug can't be reproduce I will close the issue because it might be just me.
![image](https://user-images.githubusercontent.com/13287878/76980033-5ea6c580-6941-11ea-9068-8cf061d4dcde.png)

**Comment by Acsigen** [comment]
Fixed in version 5.0.0

**Comment by johannesjo** [comment]
@Acsigen thanks for confirming.
