### ISSUE TITLE
Inconsistent Project Id, data repair unsuccessful

### ISSUE THREAD

**Issue by KatrinIhler** [johannesjo/super-productivity#2940]
I can't find my notes for this bug and this happened a while ago, but I hope this will still be helpful. I tried to reconstruct my findings as much as possible.

Somehow, I managed to to create an invalid state for my data where a task was associated with a certain project, but that project didn't contain that task in its task list, but instead a different project did. So the two directions of the relationship were inconsistent with each other. I think this happened when moving a task from one project to another, and somehow this was only done half-way.

This leads to the app no longer starting correctly because the data is invalid. Letting superproductivity fix this automatically wasn't successful either. 

As a workaround, I opened the developer tools to get to the error in the console (which I think occurred in the data validity check in `isAllTasksAvailableAndListConsistent`*), finding out the id of the affected task by setting a breakpoint at the spot that generated the error message, exporting the data as a json, editing that data manually to fix the project association, and then re-importing the data. 

*I think the relevant code bit for the error is around line 163 at
```
        } else if (task.projectId !== project.id) {
          isInconsistentProjectId = true;
          console.log('--------------------------------');
          console.log('tid', task.projectId, 'pid', project.id, { task, project });
          _validityError('Inconsistent task projectId');
        }
```

As far as I can tell from the cursory glance at the data repair code, currently a task is removed from the task list of a project if the project id doesn't match that project, but it isn't _added_ to the project it claims to belong to. It's technically not an orphaned task either, since it's part of a project's list, just not the right one. So there may be a gap here.

Hope this helps, and I swear I'm done now. Merry Christmas! :christmas_tree:

**Comment by KatrinIhler** [comment]
Update: Managed to reproduce! :tada: Creating a task with multiple projects with `sometask +project1 project2` leads to "Inconsistent task projectId" error when closing and opening SP. The repair attempt then actually fails with another error:

### Stacktrace

```
_resetEntityIdsFromObjects (webpack:///src/app/core/data-repair/data-repair.util.ts:229:16)
_fixEntityStates (webpack:///src/app/core/data-repair/data-repair.util.ts:44:16)
_fixEntityStates (webpack:///src/app/core/data-repair/data-repair.util.ts:43:20)
isDataRepairPossible (webpack:///src/app/core/data-repair/data-repair.util.ts:21:29)
constructor (webpack:///src/app/core/data-repair/data-repair.service.ts:16:22)
this._dataRepairService.isRepairPossibleAndConfirmed (webpack:///src/app/core/data-init/data-init.service.ts:52:50)
constructor (webpack:///src/app/core/data-init/data-init.service.ts:45:39)
```

### Meta Info
META: SP7.16.0 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.16.0 Chrome/114.0.5735.289 Electron/25.9.0 Safari/537.36

### Actions Before Error
```
1703169755981: [Layout] Hide Notes 
1703169759966: [Task] Update Task 
1703169759967: [Persistence] Save to DB 
1703169760056: [Layout] Show AddTaskBar 
1703169763266: [Task][Issue] Add Task 
1703169763267: [Persistence] Save to DB (2) 
1703169764826: [Layout] Hide AddTaskBar 
1703169768769: [Task] Update Task 
1703169768770: [Persistence] Save to DB 
1703169768836: [Layout] Show AddTaskBar 
1703169783411: [Task][Issue] Add Task 
1703169783413: [Persistence] Save to DB (2) 
1703169783413: [Task] Update Task 
1703169783414: [Task] Move tasks to other project 
1703169783415: [Task] Update Task Tags 
1703169783416: [Persistence] Save to DB (5) 
1703169784594: [Layout] Hide AddTaskBar 
1703169787386: [Task] Update Task Tags 
1703169787388: [Persistence] Save to DB (2) 
1703169840214: [Task] Update Task 
1703169840216: [Persistence] Save to DB 
1703169840216: [Task] Update Task 
1703169840219: [Task] Move tasks to other project 
1703169840222: [Persistence] Save to DB 
1703169840222: [Task] Update Task 
1703169840223: [Task] Move tasks to other project 
1703169840226: [Persistence] Save to DB (5) 
1703169843797: [Task] UnsetCurrentTask 
1703169843798: [SimpleCounter] Turn off all simple counters 
1703169849598: [FocusMode] Set focus session elapsed time
```

Obviously not something you should do anyway, but recovering from this is not so nice. :D Thank god I exported my data before trying this...

**Comment by johannesjo** [comment]
Thank you! The case you're describing should be fixed with the next release. The data repair script might need two attempts for everything to be fixed, but I am alright with it, since normally this shouldn't occur :)
