### ISSUE TITLE
Missing check for multiple instances, may be solution to "Very high battery usage #2904"

### ISSUE THREAD

**Issue by I-Anonymouse-I** [johannesjo/super-productivity#2942]
### Your Environment

- Version used: 7.16.0
- Operating System and version: Windows 11

### Expected Behavior

When SP is minimized (Window closed, but Icon in the hidden Icons list and you want to open your window by clicking the icon in the taskbar, the minimized Window comes to front and the process is working. when quitting SP with the hidden icons menu, no SP-process should be active.

### Current Behavior
The window comes to focus, but a new AC-Process starts in the background (visible in Taskmanager and using a lot of CPU and Battery (maybe cuz it cant access the files, cuz they are already open by the first process and thus sending a lot of errors...
When quitting SP, there is still an entry running...

### Steps to Reproduce (for bugs)

1.open SP and start tracking time
2.have setting "minimize when window is closed" enabled and close the window
3.open SP by using the pinned icon in taskbar/by normal start menu
4.close the window and close SP by using the hidden icons menu (right click and quit)
5.in taskmanager SP is still running and using CPU

### Can you reproduce this reliably?
yes

It is not a very urgent bug, you can also fix it by just always reopening the tab with the hidden icons menu, but that is very contra-intuitive.

**Comment by johannesjo** [comment]
I think this should be fixed now! Thank you  @I-Anonymouse-I for the input!
