### ISSUE TITLE
Allow tagging of subtasks

### ISSUE THREAD

**Issue by pdlourenco** [johannesjo/super-productivity#2946]
First of all, thank you very much for this excellent tool. I use Super Productivity everyday, mostly for time tracking, but I am starting to use it more for planning my days. 
In the course of the 2 years I've been using it, there were some minor issues that have since been solved brilliantly (e.g., the feature to split idle time, etc) - goes to show how attuned the Johannes is to the needs of the users.

## Problem Statement

For some of my projects, I use tasks as chunks of work that can take several days (or weeks) to complete, and which I then break down into more digestible subtasks spread throughout that time period. Since subtasks cannot be individually tagged (or Today-ed), I end up having these tasks in "Today" for ages, cluttering that view with several subtasks that I don't need to worry about in the present.

Another aspect is that a subtask could require very different categories of subtasks, for example:
* The main task is "Derive requirements". It has several subtasks
  * Meet with users
  * Share notes with experts
  * Write set of reqs.
  * etc

Ideally, if I want to check meetings I have to do, I would look at the "meeting" tag, but I would have to tag the major task instead.

## :grey_question: Possible Solution

Allow tagging of subtasks, including the "Today" tag. When in "Today" view, see only the subtasks marked as "Today" for a given task, unless the whole task is moved to the day.

## :arrow_heading_up: Describe alternatives you've considered

I've considered simply breaking down the large several-day-long tasks into other tasks instead of subtasks. That way all the features available for tasks can be used. For the example above, I would get
* Derive requirements: meet with users
* Derive requirements: share notes with experts
* etc

But, naturally, I lose the relationship between these tasks. This relates to another possible improvement: adding relationships between tasks as mentioned in #2173.

**Comment by johannesjo** [comment]
Thanks for opening this up! I also would like to see this even though the change is far from trivial.

**Comment by johannesjo** [comment]
This is now possible! :)
