### ISSUE TITLE
Total time is not the correct sum of tasks

### ISSUE THREAD

**Issue by pyrareae** [johannesjo/super-productivity#2948]
I recently came across a strange bug. The total time for the day jumped down to zero after recording about an hour or so, then went up to 15 minutes over the course of about another hour of recording. This has only happened once so far, but it's pretty disconcerting knowing there might be something under the hood eating away at my recorded time. The details for the tasks show a completely different time than what's shown in the total time. Also the time recorded in the tasks jumps to different values depending on if I'm hovering over the time entry.

### Your Environment

- Version used: SPA on Chrome
- Operating System and version: Windows 11
- Desktop Environment: n/a
- Browser Name and version: Google Chrome 120

### Expected Behavior

The total time should be the sum of all tasks recorded for that day.

### Current Behavior

Rarely the total time is a much smaller value than the actual sum of the tasks. Task time jumps around depending on mouse hover state.

### Steps to Reproduce (for bugs)

Unknown.

### Can you reproduce this reliably?

No

### Screencast of behavior

https://github.com/johannesjo/super-productivity/assets/15057106/df5aa387-bde5-431f-b16a-cb39ad48133d

https://github.com/johannesjo/super-productivity/assets/15057106/448dbf1b-4bf7-4a75-ac35-a5895fe7d839

**Comment by johannesjo** [comment]
Thank you very much for reporting! So far I've been unable to reproduce this.

**Comment by pyrareae** [comment]
I'm wondering if this may have happened from accidentally having multiple instances open at once corrupting the time entries if they might have both been recording. I'm not sure what you're using as a data store but I could see that being problematic. I try to avoid having multiple instances open but I am using a multi-monitor setup spanning multiple virtual desktops and it's easy to not realize if the app is already open sometimes!

This is a bit of an off-topic suggestion but I wonder if you might add some kind of cross-instance bus via a BroadcastChannel and ping for other running instances during startup, then bail out if there is a response.

**Comment by johannesjo** [comment]
> This is a bit of an off-topic suggestion but I wonder if you might add some kind of cross-instance bus via a BroadcastChannel and ping for other running instances during application startup, then bail out with a "there is already a running instance" type warning if there is a response from an already running instance.

Could you open up a new issue for this?

**Comment by pyrareae** [comment]
Okay, opened #2987
