### ISSUE TITLE
error

### ISSUE THREAD

**Issue by matthewdunngeon** [johannesjo/super-productivity#295]
### Your Environment

* Version used: 
* Operating System and version:
* Desktop Environment: 
* Browser Name and version: 

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by johannesjo** [comment]
Could you maybe provide a little bit more info?

**Comment by matthewdunngeon** [comment]
Hi there,
Actually didn't notice.
I was surfing for wsl Ubuntu configuration. Maybe using some keyboard
shortcut caused.
Browsers chrome and brave.
I think I've minimized super productivity on Taskbar.
When switching around windows, I saw developer extensions Chrome was
visible inside your app.

That is all I remember.
Hope it helps
Regards

10 Mar 2020 Sal 16:23 tarihinde Johannes Millan <notifications@github.com>
şunu yazdı:

**Comment by johannesjo** [comment]
Thanks for getting back to me. Unfortunately it's not really enough information to do anything, but I keep an eye open.

**Comment by matthewdunngeon** [comment]
Hi,

I think I found the problem for crash.

I pressed accidentally the F12 key to take a screenshot but super productivity has the focus. And web view interface triggered developer view. Eventually this caused your application to crash.

 

By bests

**Comment by johannesjo** [comment]
Thanks for getting back to me! Was there any output shown in the console?

**Comment by matthewdunngeon** [comment]
Hi Johannes,
I appreciate you for this application.
I'd like to suggest an idea for ticking sound.
There is an android app named
Pomodoro Timer Lite for Android

Google play link:
https://play.google.com/store/apps/details?id=com.tatkovlab.pomodorolite

This app's tick sound is very good, I mean it doesn't have distortion .
Would you consider a ticking sound like that?

My best
Keep healthy.

Ps. I want to make some suggestions later on about the application.
Nowadays trying to use effectively, give me some time to work on it.

>

**Comment by johannesjo** [comment]
I am open for changing it up. :) The sound would need to be completely open source and allow for being used in an application like this.

**Comment by johannesjo** [comment]
Closing this in favor of #180
