### ISSUE TITLE
App refuses to be closed in Mac OSX

### ISSUE THREAD

**Issue by jdelker** [johannesjo/super-productivity#296]
### Your Environment
* Version used: 4.0.0.1377 DMG package
* Operating System and version: Mac OSX 10.14 ("Mojave")

### Expected Behavior
The app should quit if
- when Quit is selected from the Titlebar's app menu
- when Quit is selected from the app's dock icon

### Current Behavior
Neither of above described methods does quit the app.
The only way to close the app regularly is using the window's top-left close button.

### Steps to Reproduce (for bugs)
1. Open app in Mac OSX.
2. Try to close app with the methods described above.

**Comment by johannesjo** [comment]
Thanks for reporting. I'll try to look into it as soon as I can.

**Comment by johannesjo** [comment]
Should be fixed with the next release. If the issue persists, please check if there is a popup opened by the app and if you have the "confirm before quit" option enabled in the global settings.
