### ISSUE TITLE
Install minimized to tray taskbar pin issue

### ISSUE THREAD

**Issue by mathisgauthey** [johannesjo/super-productivity#2964]
### Your Environment

- Version used: 7.17.2
- Operating System and version: Windows 11 Pro 22H2 22621.2861

### Expected Behavior

When using the Chocolatey package installation and the `minimized to tray` option, if I have SupProd pinned to my taskbar and I minimize it, I should be able to open it back using the taskbar icon.

### Current Behavior

Currently, I can only re-open it using the tray icon. Clicking on the pinned taskbar icon does nothing.

It worked using Microsoft Store install, but I prefer not to use it since I found Microsoft Store to be a pain.

### Steps to Reproduce (for bugs)

1. Install using Chocolatey
2. Activate the `Minimize to tray` option in the `Mist settings`
3. Pin the SupProd to the taskbar
4. Minimize
5. Try to open it using the taskbar icon
6. Fail miserably
7. Try using the icon in the tray
8. Succed and come back to the bug report

### Can you reproduce this reliably?

Yes.

### Console Output

None when trying.

### Error Log (Desktop only)

When using the minimize (`-` window icon) there is no log.

There is this one when using the cross `x` : `[2024-01-03 10:10:18.714] [info]  close, isQuiting: undefined`

### Related issues

- https://github.com/Xav83/chocolatey-packages/issues/23#issuecomment-1875028935

**Comment by johannesjo** [comment]
Don't think this is a bug. The issue doesn't appear when running the installer without chocaletey.

**Comment by johannesjo** [comment]
Can you reproduce this without using chocolatey?

**Comment by mathisgauthey** [comment]
> Can you reproduce this without using chocolatey?

I tried using Microsoft Store just now, I'm having the exact same issue, unfortunately. Maybe it is related to the changed done to counter the high CPU usage lately ?

**Comment by johannesjo** [comment]
> I tried using Microsoft Store just now, I'm having the exact same issue, unfortunately. Maybe it is related to the changes done to counter the high CPU usage lately ?

Possible, but unlikely, since nothing related changed apart from the new electron version maybe.

Here is the location of the relevant code in case someone wants to have a look:
`electron/indicator.ts`

**Comment by ItsIgnacioPortal** [comment]
Disable the "minimize to tray" setting if you wish to open super-productivity from the taskbar as well as from the tray-icon.

**Comment by mathisgauthey** [comment]
> Disable the "minimize to tray" setting if you wish to open super-productivity from the taskbar as well as from the tray-icon. Even with that setting disabled, super-productivity has a tray-icon that allows you to maximize it.

Thank you that's perfectly right. And it'll work as a workaround for now.

The only thing is that I'm using the `minimize to tray` option to **prevent accidental closure** and make them just minimize to tray. And I don't see why this should prevent me from opening back the app using my taskbar icon as well as the tray.

At least that's not the standard behavior as I have my important apps on my taskbar with some `minimize to tray` implementation and they all behave in the way I described.

**Comment by Jagdfalke** [comment]
I can confirm this behaviour with version 8.0.1 on Windows 10.
