### ISSUE TITLE
End - Start < Worked

### ISSUE THREAD

**Issue by simonschmeisser** [johannesjo/super-productivity#2967]
### Your Environment

- Version used: AppImage 7.17.2
- Operating System and version: Kubuntu 22.04
- Desktop Environment: KDE Plasma
- Browser Name and version: 

### Expected Behavior

I would expect for end - start to be greater than or equal to the time worked.

Ideally I would love to have a detailed view of when I worked on which project (ie with several entries per project each day)

### Current Behavior
![grafik](https://github.com/johannesjo/super-productivity/assets/372442/ffa2862d-16bf-4d11-9123-ead46a5dcabb)

After tracking another minute

![grafik](https://github.com/johannesjo/super-productivity/assets/372442/c318d3ac-c553-4106-944a-a59738a1a9e2)

### Steps to Reproduce (for bugs)

I worked on this ticket several times today and stopped in between. Also before the start time

### Can you reproduce this reliably?
I'll observe next week and comment here

**Comment by johannesjo** [comment]
start – end is the time of day you worked. So you started working at 14:48 and ended at 17:10

**Comment by simonschmeisser** [comment]
In the first screenshot it said I supposedly started working at 14:48 and finished at 16:48, which is exactly 2h. During that time I supposedly worked 2h 39m. In fact I "started working" (started SuperProductivity) before lunch, so 11:xy and worked on and off on this ticket.

**Comment by johannesjo** [comment]
Sorry, I misread the issue... Work Start is set when you first start tracking to a task and work end is set the last time time is tracked to a task. This is tracked separately for every project and tag. As far as I have tested this seems to work fine.
