### ISSUE TITLE
Subtasks of repeating tasks get deleted

### ISSUE THREAD

**Issue by Megafont** [johannesjo/super-productivity#2972]
If you create subtasks on a repeating task, the next day all subtasks are deleted.

This is very odd behavior, especially since the subtasks don't have the repeat section in their options page. I assume they are supposed to be automatically using the parent task's repeat settings, but instead are being treated as non-repeating.

Also, if you set a time estimate on repeat tasks, that has also been deleted when you open the app the next day.

**Comment by johannesjo** [comment]
Duplicate of #427
