### ISSUE TITLE
Add total worklog/metrics for every project

### ISSUE THREAD

**Issue by nicofirst1** [johannesjo/super-productivity#298]
It would be nice to have a total worklog/metrics in which you can see time spent for every project.

**Comment by johannesjo** [comment]
Thanks for the suggestion. I am working on it.

**Comment by jdelker** [comment]
There is one thing with the worklog generation, that bothers me. Maybe that can be taken into consideration with this task:

Currently, I'm generating single worklogs for every single (active) project at the end of the month.
Alone from that perspective, I really second the requirement from @nicofirst1 for consolidated (monthly) worklog of all (active) projects.
But for me there is another issue with the rounding of worked hours. I often fail to "finish the day" and by that loosing the chance to round the recorded times to e.g. full half hour intervals - at least that is my perception of the mechanics there.
The worklog generation gives me the option (again) to round the recorded times to some interval, which I constantly use to fix the previously missed roundings. However, that obviously only rounds time for the worklog display, which is ok, but absolutely not total is displayed for the sum of those rounded values. I literally have to use a calculator to sum that up by hand ;)

So, my message would be: Please provide a total row in the worklog report. For the single project, as well as the newly created "overall worklog".

(In case I totally missed the intended mechanics how this is supposed to work, please let me know ;) )

**Comment by johannesjo** [comment]
@jdelker could you please open up a new issue for this? That would make tracking and discussing easier :)

**Comment by johannesjo** [comment]
Still relevant.

**Comment by Rodeo-McCabe** [comment]
Commenting to link some relevant issues:

#771  
#520  
#730
