### ISSUE TITLE
Error: Project INBOX not found

### ISSUE THREAD

**Issue by yuraosn** [johannesjo/super-productivity#2981]
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
Error: Project INBOX not found
    at https://app.super-productivity.com/main.63765dab1008d0bc.js:1:321035
    at https://app.super-productivity.com/main.63765dab1008d0bc.js:1:4127125
    at $r (https://app.super-productivity.com/main.63765dab1008d0bc.js:1:4126645)
    at wn (https://app.super-productivity.com/main.63765dab1008d0bc.js:1:4127558)
    at https://app.super-productivity.com/main.63765dab1008d0bc.js:1:4127182
    at $r (https://app.super-productivity.com/main.63765dab1008d0bc.js:1:4126645)
    at v.project (https://app.super-productivity.com/main.63765dab1008d0bc.js:1:4125988)
    at v._next (https://app.super-productivity.com/main.63765dab1008d0bc.js:1:3812737)
    at v.next (https://app.super-productivity.com/main.63765dab1008d0bc.js:1:3800866)
    at Ne._subscribe (https://app.super-productivity.com/main.63765dab1008d0bc.js:1:3793621)
```

### Meta Info
META: SP7.17.2 Browser – ru – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.5993.714 YaBrowser/23.11.1.714 Yowser/2.5 Safari/537.36

### Actions Before Error
```
1705358900483: [FocusMode] Set focus session elapsed time 
1705358900646: [SP_ALL] Load(import) all data 
1705358900647: [SP_ALL] All Data was loaded 
1705358969784: [Persistence] Save to DB (14) 
1705358969880: [SP_ALL] Load(import) all data 
1705358969886: [Persistence] Remove from DB 
1705358983827: [FocusMode] Set focus session elapsed time 
1705358984073: [SP_ALL] Load(import) all data
```

**Comment by johannesjo** [comment]
Hey there! Thank you very much for reporting this!

It might be that for some reason a bit of your data got into an invalid state that I didn't account for and that I can't reproduce. It would be great if you could share a copy of your data to contact@super-productivity.com, so I can debug this on my computer (and please let me know here, if you send something, as those mails quite often land in the spam folder). You can create an export by navigating to "Settings" and then to "Import/Export" or you can use the "Export data" button from the error Dialog (there is also a button there which will anonymize the data before exporting).

**Comment by old-faraon** [comment]
Not the original poster but I do have the same problem I sent an email with the dump from the error log and the title 'Error: Project INBOX not found #2981'

**Comment by johannesjo** [comment]
Thank you very much! I checked your data and it seems like the error does not occur with the latest version. At least re - importing it fixes the issue. Maybe you can use this to fix the problem for your data?

**Comment by yuraosn** [comment]
Thank you
