### ISSUE TITLE
Prevent multiple instances

### ISSUE THREAD

**Issue by pyrareae** [johannesjo/super-productivity#2987]
## Problem Statement
Possible solution for #2942 

There is nothing stopping you from opening multiple instances of the spa/web-app, which in turn may lead to data corruption issues such as in #2948. 

## :grey_question: Possible Solution
It should be possible to query if there are any running instances via a BroadcastChannel message. We should be able to ping for any other running instances on startup and abort if we get a response from one.

Flow:

- Instance A starts up and pings "existingInstance" message and receives no reply.
- Instance A sets up a listener for "existingInstance" that just echos "pong" or something.
- Instance B starts up and pings for "existingInstance", and receives "pong" from instance A.
- Instance B warns the user there is already a running instance and shuts down.

## :arrow_heading_up: Describe alternatives you've considered
There are some other inter-window/tab communication techniques/apis but BroadcastChannel seems to be the most flexible. it would be possible for example set a cookie or local storage flag but that has issues such as a bad shutdown could leave it in a bad state.

## :heavy_plus_sign: Additional context
Related: #2942 
Related: #2948

**Comment by johannesjo** [comment]
This is working much better now. Closing this!
