### ISSUE TITLE
Checked Items/Checkboxes Not working

### ISSUE THREAD

**Issue by liluzibird** [johannesjo/super-productivity#2988]
### Your Environment

- Version used: Version 7.17.2 from AUR 
- Operating System and version: Arch Linux x86_64 Kernel 6.7.0-arch3-1
- Desktop Environment:  KDE
- Browser Name and version: All browsers (probably). I've tried on Firefox and Librewolf current versions.

### Expected Behavior

Should show check or unchecked marks in description if used proper `- [ x ]` or `- [  ]` syntax.
https://super-productivity.com/static/3e6df721bc73ad2ff365f227d9cc31f6/fcda8/subtask-3-level.png

![image](https://github.com/johannesjo/super-productivity/assets/57073805/50dfc256-6ab5-4187-88e3-1e3033983792)

### Current Behavior

Doesn't show check or unchecked marks in description if used proper `- [ x ]` or `- [  ]` syntax.

![image](https://github.com/johannesjo/super-productivity/assets/57073805/70caeb8b-0f5a-4f32-b450-9f6b12d65c63)

![image](https://github.com/johannesjo/super-productivity/assets/57073805/d3b663ed-64bc-4c3e-b652-893999540f6e)

### Steps to Reproduce (for bugs)

1. Make a task
2. In the description, write:
```
- [ ] Some item
- [x] Checked item
- [x] Another checked item
```
3. Exit out description and look at result

### Can you reproduce this reliably?

Yes, it will happen if you do it too

### Error Log (Desktop only)
No error. It's just a logic error, probably.

**Comment by johannesjo** [comment]
Would be nice to improve this! Thanks for opening this up!

**Comment by palmerusaf** [comment]
I works as expected on version 7.14.3 of the .deb build FWIW.

**Comment by palmerusaf** [comment]
I ran git bisect from 7.14.3 to 7.17.2 and it looks like commit 038fed6 introduced the regression.

**Comment by johannesjo** [comment]
Thank you very much @palmerusaf for digging into this! A fix will be available with the next release!
