### ISSUE TITLE
Bug Import File JSON

### ISSUE THREAD

**Issue by brgsx** [johannesjo/super-productivity#299]
### Your Environment

* Version used: 
* Operating System and version:
* Desktop Environment: 
* Browser Name and version: 

### Steps to Reproduce (for bugs)

1. Settings
2. Download JSON File from Gdrive
3. Import file to SP
4. Error

**Comment by johannesjo** [comment]
Thanks for reporting. Can you provide a little more info about the error? What does it state exactly?

**Comment by brgsx** [comment]
I recorded a video of the screen to facilitate:

[SP Error](https://send.firefox.com/download/dce903e1169e49af/#tw79sHfng6dS_1hLxTpKZw)

**Comment by johannesjo** [comment]
The link seems to be expired...

Also just recognized that my answer was not 100% clear: Generally downloading the file from google drive and importing it manually from the settings is not a valid strategy, never worked and currently there are no plans to change that. 

The way things should work are usually are:
1. Enable Google syncing in one App instance and upload the data via the dedicated button from the google settings,
2. Enable Google syncing with the same settings in another app instance and download the data via the dedicated button from the google settings.

OR
1. Go to the Import/Export section
2. Export
3. Import in another app instance
