### ISSUE TITLE
Touchscreen support desktop

### ISSUE THREAD

**Issue by rommeswi** [johannesjo/super-productivity#2993]
## Problem Statement
Currently there is almost no touchscreen support on the Linux desktop version.

## :grey_question: Possible Solution
Super-productivity should at least be able to handle tapping as "click" and dragging to "scroll".

## :arrow_heading_up: Describe alternatives you've considered
Possibly one could configure the system to handle touch input for this app as mouse input.

**Comment by johannesjo** [comment]
Thanks for opening this up. I don't see why any of the things you mentioned should not work. What OS, version etc. are you on?

**Comment by rommeswi** [comment]
On EndeavourOS it did not work but I just booted into Manjaro and there it is working indeed. This indicates that it is configuration related and can probably be closed. If I find out the reason why it is working on one system and not the other, I will post it here.
