### ISSUE TITLE
Show repeated task on Timeline view

### ISSUE THREAD

**Issue by ATM2022win11** [johannesjo/super-productivity#2995]
I would like to express my gratitude to Johannes for developing this app, especially since it's available for free.

My to-do list needs are simple - I only require a view of my daily schedule and some future tasks. I generally don't set specific times for the day, as long as I have a list of tasks to accomplish for the day.

I have a suggestion regarding the repeating tasks: It would be helpful if they appeared in the timeline view even if they are scheduled for the future. I have been using the app for only two days, so that's all the feedback I have for now.

Thank you very much, and keep up the good work!

**Comment by Jagdfalke** [comment]
> I would like to express my gratitude to Johannes for developing this app, especially since it's available for free.
> 
> My to-do list needs are simple - I only require a view of my daily schedule and some future tasks. I generally don't set specific times for the day, as long as I have a list of tasks to accomplish for the day.
> 
> I have a suggestion regarding the repeating tasks: It would be helpful if they appeared in the timeline view even if they are scheduled for the future. I have been using the app for only two days, so that's all the feedback I have for now.
> 
> Thank you very much, and keep up the good work!

Hi. This feature is already implemented. Future instances of repeated tasks are shown as white outlines in the timeline view:

![image](https://github.com/johannesjo/super-productivity/assets/17673417/11173645-ad97-4fc5-bcc2-b39558783238)
