### ISSUE TITLE
Not creating new project while creating task with + shortcut

### ISSUE THREAD

**Issue by salmanzego** [johannesjo/super-productivity#3001]
- Version used: 7.17.2
- Browser Name and version: Chrome Version 120.0.6099.227 (Official Build) (64-bit)

### Expected Behavior
Not creating new project while creating task with + shortcut

When creating task we can add the task to a certain project by using '+' followed by project name. But if we need to add the task to a new project which doesn't exist yet, it should create one and add the task to the project.

### Current Behavior

Currently it just creates a task like "Add functionality to cart page +LMS Project" , instead of creating the project LMS Project and add the "Add functionality to cart page" task to it.

### Steps to Reproduce (for bugs)

1. Create a task
2. Add it to a project that doesn't exist using '+' shortcut ( "Add functionality to cart page +LMS Project" )

Since the app predicts the project before typing full project name, considering using any other symbols at the end like a exclamatory (!) for creating new project (This is needed if the new project name is a subset of already existing one)

![issue_image](https://github.com/johannesjo/super-productivity/assets/72879267/39a326c4-dc13-4148-b0a9-4918749602ac)

here in the attachment, the task is not assigned to any project since "project one" didn't exist

**Comment by johannesjo** [comment]
This is (currently) the intended behavior. From my perspective unintentionally creating a project due to misspelling and having to type the complete project name rather than just the beginning outweighs the benefits such a change would have.

**Comment by salmanzego** [comment]
Yes I agree that. Would it be good if it creates the project only if an exclamatory mark is given at the end. In that way we can solve the issue of unintentionally creating projects and we can still have the benefit of auto project selection.

**Comment by mathe00** [comment]
I agree with the opinion of @salmanzego

**Comment by tempookian** [comment]
I think adding a project is usually more than just entering the name. You need to set up themes, etc. I'm in favor of the current behavior. It's really convenient for me now that I can just type two characters of the project name and get the whole name. However, as @salmanzego mentioned, one could think of a specific syntax to avoid accidentally creating random projects (what happens with new tags for me all the time 😁). In that case, if not too much additional effort, it would be great to see sth like:

> new project: new project name so far

**Comment by salmanzego** [comment]
@tempookian Yeah, a new syntax like

> task_name !new_project_name

or 

> task_name +new_project_name!

Which one would be good? 
@johannesjo Would there be any challenges while implementing this? If it doesn't have any big challenges to tackle while implementing this, I am happy to work on it.

**Comment by johannesjo** [comment]
@salmanzego that is great to hear!

I would go with `task_name +!new_project_name` since users might actually want to name their proejcts something like "Cool Project!!".

All the shortcut syntax stuff is unit tested, to not break stuff if new features like this one are added. So a PR would ideally include additionally ones for the new functionality. :)

**Comment by Jagdfalke** [comment]
@salmanzego are you working on this issue?

**Comment by salmanzego** [comment]
@Jagdfalke Not yet
