### ISSUE TITLE
Export Anonymized Data (PE) Includes Personal Info

### ISSUE THREAD

**Issue by tempookian** [johannesjo/super-productivity#3005]
### Your Environment

- Version used: 8.0.0.rc.0 (via `ng` and `npm`)   
- Operating System and version: Ubuntu 22.04.3 LTS
- Desktop Environment: i3wm
- Browser Name and version: 

### Current Behavior

- When an error occurs, I click on PE and the following information is not anonymized (`USERNAME` and `REPO`):

```json
"GITHUB": {
    "isEnabled": true,
    "repo": "USERNAME/REPO",
    "token": "token__234",
    "isSearchIssuesFromGithub": false,
    "isAutoPoll": false,
    "isAutoAddToBacklog": false,
    "filterUsername": "USERNAME",
    "filterIssuesAssignedToMe": true
}
```

### Steps to Reproduce (for bugs)

1. Follow steps mentioned in #3004
2. In the error window, click on PE
3. The personal information mentioned above appears in the json file

### Console Output 

- _Not relevant here_

### Error Log (Desktop only)

- _Not relevant_

Would be happy to provide any additional information if required. Feel free to let me know if I need to test anything!

**Comment by johannesjo** [comment]
Thank you very much for reporting! This will be fixed with the next release.  I am sorry for the inconvenience!

**Comment by tempookian** [comment]
> I am sorry for the inconvenience!

Thank you so much. superproductivity is nothing but convenience! 😊
