### ISSUE TITLE
Can´t download Android App

### ISSUE THREAD

**Issue by imotos** [johannesjo/super-productivity#3028]
Hello,
I tried to download the Android app on my phone but without any success.

The only message I get says : 
"Error, Something went wrong on our end, Please try again."

I've already tried downloading other apps and that's working.

I'm currently using Android 14
Please help.

**Comment by johannesjo** [comment]
Hey hey! I am unable to reproduce this behavior and from the description it seems that it's probably something. beyond my control anyway as it seems to be more of a google server issue. Maybe trying again later does indeed work?

**Comment by imotos** [comment]
With FDroid everything is working perfekt. Probably you are right it could be a Google server issue. 
Thanks for the fast response.
