### ISSUE TITLE
Be able to see a list of archived tasks?

### ISSUE THREAD

**Issue by Pixel8edstudios** [johannesjo/super-productivity#3029]
## Problem Statement
I'm really frustrated when I can't look through my archived tasks, and I can't just have a list of all of the tasks that have been archived.

## :grey_question: Possible Solution
Create a section in the UI where you can see a list of your archived tasks.

## :arrow_heading_up: Describe alternatives you've considered

None. I think this is probably the easiest and most forward idea.

## :heavy_plus_sign: Additional context

N/A

**Comment by Jagdfalke** [comment]
I would argue that this is already implememtend. There are two ways to access archived tasks, either through the quick history or through rhe worklog.

You can access both by clicking on the three dots next to the 'Today' tab:

![Screenshot_20240212-071559.png](https://github.com/johannesjo/super-productivity/assets/17673417/5fa9b716-6ce4-4cc2-9881-5178a2007798)

I prefer the quick history as it gives you a very concise list for each day, when you click on a day:

![Screenshot_20240212-073028.png](https://github.com/johannesjo/super-productivity/assets/17673417/a3b62e44-8a1e-467c-b3c2-b024dd68a1b2)
