### ISSUE TITLE
Global shortcuts using `Meta`/`Super` key don't work as expected

### ISSUE THREAD

**Issue by jwarkentin** [johannesjo/super-productivity#303]
**UPDATED**

### Your Environment

* Version used:  4.0.0 (snap)
* Operating System and version: Ubuntu Linux 19.10
* Desktop Environment:  Gnome
* Browser Name and version: 

### Expected Behavior

Shortcuts involving the `Meta`/`Super` key should work like any other shortcut.

### Current Behavior

All shortcuts involving the `Meta`/`Super` key ~~don't work~~ only work if the `Meta` key is held down while the last accelerator key is pressed a second time. For example, if the global show/hide shortcut is set to `Meta+a` it doesn't work to press `Meta+a->Meta+a` but it does work to press `Meta+a+a`.

### Steps to Reproduce (for bugs)

1. In the app settings set the show/hide shortcut to something using the `Meta` key such as `Meta+a`.
2. Click the "Save" button below
3. Try using the shortcut. No joy.

### Console Output

No output is produced from setting, saving or trying to trigger the shortcut

### Error Log (Desktop only)

No log file exists. I looked around the snap data path but there are just no log files.

**Comment by jwarkentin** [comment]
Updated after discovering that it sort of works, as long as the meta key is held down while pressing the accelerator twice.

**Comment by johannesjo** [comment]
I tested this and can confirm the issue. It seems to be an electron issue. Not really sure if we can do much on Super Productivity's side of things... :/

**Comment by johannesjo** [comment]
I just tested this and if I didn't misunderstand the issue it seems to be fixed now. I am closing this. Please let me know if this persists in one form or the other.
