### ISSUE TITLE
Language selection not scrollable

### ISSUE THREAD

**Issue by kitamiq** [johannesjo/super-productivity#3030]
### Your Environment

- Version used: 8.0.0 (F-Droid .apk)
- Operating System and version: Android 13

### Expected Behavior

When opening language selector in the Language section in Settings, I should be able to scroll the overlay select to get to the languages that don't fit on screen

### Current Behavior

The overlay languages selector has fixed position with no ability to scroll the list of options. That way, I cannot manually choose Chinese for example, or anything below Portugese, as the rest doesn't fit on my screen

### Steps to Reproduce (for bugs)

1. Install the Android app (from F-Droid in my case, but I believe that doesn't matter)
2. Go to Global Settings via the left menu
3. Expand "Language" section, then the "Please select a language" element
4. Try scrolling

### Can you reproduce this reliably?

Yes, on two Android devices

**Comment by Jagdfalke** [comment]
I can confirm this issue with 8.0.0 on both Android and Windows.

**Comment by q-wertz** [comment]
Can confirm on Linux in the electron app

**Comment by johannesjo** [comment]
I think this should be fixed now. The fix will be available with the next release.
