### ISSUE TITLE
New icon

### ISSUE THREAD

**Issue by solarlime** [johannesjo/super-productivity#3033]
Hi!

Thanks for your app; it really helps track my time. However, there's a small problem. I'm a Mac user, and I don't know if others face it, but... I don't like the current icon. In modern macOS it doesn't look harmonious. I've made another icon for myself. If you like it, I'll make a pull request (at least for icns).

<img width="350" alt="2024-02-13 20 09 54" src="https://github.com/johannesjo/super-productivity/assets/52582564/8fad4833-3e0d-4555-80b2-2ea012cc30f2">
<img width="350" alt="2024-02-13 20 13 49" src="https://github.com/johannesjo/super-productivity/assets/52582564/01e2d684-017a-4c58-9079-ff287968d994">

**Comment by johannesjo** [comment]
I am all for it! Thank you very much! Help with it would be welcome! We a) need a special icon file for mac and b) we need to use it automatically during the build process.
