### ISSUE TITLE
Eisenhower matrix

### ISSUE THREAD

**Issue by rommeswi** [johannesjo/super-productivity#3036]
## Problem Statement
It would be great if the tasks could be displayed in an Eisenhower matrix. Ideally, with drag-and-drop between the matrix cells. 

## :grey_question: Possible Solution
Provide a CSS option to display the tasks in a table. Sort tasks into the table cells via tags "important" and "urgent". Tags should be automatically created by dragging tasks into the corresponding row/column.

## :arrow_heading_up: Describe alternatives you've considered
Admittedly, this feature is a tall order. However, I find that manually creating tags is somewhat tedious in the current interface. Plus, there is not much value from the tags in the current version.

**Comment by Jagdfalke** [comment]
Please have a look at this discussion regarding the Eisenhower Matrix: https://github.com/johannesjo/super-productivity/discussions/2878

**Comment by rommeswi** [comment]
Sorry, I did not see this when searching the issues for Eisenhower. thanks!
