### ISSUE TITLE
Update Croatian translation

### ISSUE THREAD

**Issue by milotype** [johannesjo/super-productivity#3044]
Please update the Croatian translation file based on the current english file https://github.com/milotype/super-productivity/blob/update-croatian-translation-20240202/src/assets/i18n/en.json with the attached file bellow.

Currently I can't add/change files in my super-productivity fork due to my old MacOS 10.11.6/Firefox 78.15.0esr (64-bit). 

[hr.json](https://github.com/johannesjo/super-productivity/files/14349348/hr.json)

**Comment by johannesjo** [comment]
Thank you very much!
