### ISSUE TITLE
Desktop app isn't starting on Debian 12 (x86_64)

### ISSUE THREAD

**Issue by joergsteffens** [johannesjo/super-productivity#3045]
I wanted to test the desktop app of superproductivity. I've not used it before.

### Your Environment

- Version used: 8.0.0 (snap)
- Operating System and version: Debian GNU/Linux 12 (bookworm), x86_64
- Desktop Environment: gnome

### Expected Behavior

snap desktop app should start.

### Current Behavior

snap Desktop apps reports a library problem.

### Steps to Reproduce (for bugs)

```
$ sudo snap install superproductivity
superproductivity 8.0.0 from johannesjo installed
$ superproductivity 
mkdir: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.30' not found (required by libselinux.so.1)
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
```

### Can you reproduce this reliably?

yes

**Comment by joergsteffens** [comment]
Edge version is starting, so I guess the problem is already known and will soon be fixed in the stable release:
```
sudo snap refresh --channel=edge superproductivity
```

**Comment by johannesjo** [comment]
Thanks for reporting! It's weird because there should be no (relevant) differences in both versions. Can anybody confirm this on their machine?

**Comment by PurrProof** [comment]
May be not exactly related to this, but I'm facing behavior similar to #326, fixed via https://github.com/johannesjo/super-productivity/issues/326#issuecomment-1903622482
Debian 11, Superproductivity 8.0

**Comment by mwaterbu** [comment]
After a reboot, the only way I am able to get the Snap package to launch is running through the terminal. After it runs successfully once, I have no issues launching it again, until the next reboot. Haven't traced the error yet.

**Comment by mwaterbu** [comment]
The only issue I have now is that I have to launch it twice from the desktop shortcut file. The first time, it seems like it tries to launch and immediately closes, but if I try again, it's fine. Once it launches successfully, I don't need to double launch it again until I reboot.
