### ISSUE TITLE
Overly aggressive Pomodoro Timer

### ISSUE THREAD

**Issue by Noctran** [johannesjo/super-productivity#3053]
I'm not sure that I'm not just missing something, but I would like to use Super Productivity as a Task Manager with the Option to activate a Pomodoro Timer to work on some Tasks.

But as far as I can see either the Timer is always on and spams me with messages that I have been working x hours and that I should take a break only because the Program was open, so I could manage my Tasks.

I would rather have a Button on the Main Page that starts a Pomodoro Session and also deactivates it.
When deactivated, I would want the App to just be a Task tracker App.

**Comment by Jagdfalke** [comment]
Hm... I'm not sure if I fully understand. To me it looks like you are mixing up several features that work independently from each other. 

There is a feature called the break reminder. It will remind you to take a break if you have been working too long. If you don't want these reminders, just switch it off (this feature is switched on by default):

![image](https://github.com/johannesjo/super-productivity/assets/17673417/01f12eb7-53e6-471d-a32b-2fab0fff1ea4)

The Pomodoro Timer is switched off by default. There are several options you can change. In general it already works like you want it to.: 

![image](https://github.com/johannesjo/super-productivity/assets/17673417/3d434189-64fa-420c-8671-f8abf59487f1)

If you want to switch between using the Pomodoro Timer and general time tracking, you have to enable or disable the timer each time you want to switch.

**Comment by Noctran** [comment]
Ohhh, damn, totally missed that, sorry!

Thanks for your reply!

**Comment by Avispa** [comment]
Main issue here is "overley aggressive" (see title). Disableing it doesn't solve the issue since it is, when active, still overley agressive. (And I am not even tracking any time! Don't know how to satisfy the reminder than just closing the app -- or disable the option.)

Please re-open.
