### ISSUE TITLE
The system displays an alert-like dialog which superimposes over other applications when it cannot sync with the sync provider. 

### ISSUE THREAD

**Issue by HendrysTobar** [johannesjo/super-productivity#3058]
### Your Environment

- Version used:8.0.0
- Operating System and version: Windows 11
- Desktop Environment: N/A
- Browser Name and version: N/A

### Expected Behavior
The system should stop resyncing when there ir a Newtwork error. Or it should refrain from showin an alert-like dialog to display the situation as this is annoying.

### Current Behavior

The system displays an alert-like dialog which superimposes over other applications when it cannot sync with the sync provider. 
_Currently I have a connection in my workplace which cannot connect to dropbox, so SP fails to sync. It then shows an annoying dialog which superimposes over other apps interrupting work._

### Steps to Reproduce (for bugs)

1. Start SP in a system which cannot use or connect to dropbox
2. (previously it must have been connected to dropbox (e.g. through another network capable to do so))
3. Try to sync
4. The system tries to sync over and over, showing the dialogs and it is annoying and inconvenient.
![Dialog](https://github.com/johannesjo/super-productivity/assets/5922811/7f0dce88-6aee-4bd5-bf4a-7a7d4baff11c)

### Can you reproduce this reliably?

It can be reproduces reliably

### Error Log (Desktop only)

_I wasn't able to find the log (It's a Windows Store app, maybe that is why_

**Comment by HendrysTobar** [comment]
@johannesjo I am able to code the solution myself, if you give me some guidelines as to what to do.

**Comment by johannesjo** [comment]
If the dialog is shown it means that your sync is likely not properly configured. That is why the app is so pushy.  I agree that we should improve on this, though I am not sure yet what would be the best way to do so.
