### ISSUE TITLE
Add current keyboard shortcuts to app menu's

### ISSUE THREAD

**Issue by nicola-lunghi** [johannesjo/super-productivity#3063]
## Problem Statement

I always forget the keyboard shortcuts that I have assigned into the app. Currently the only way to see them is to go into settings and is pretty annoying.

## :grey_question: Possible Solution
One possible solution would be to add the keyboard shortcuts in the menu as most of windows applications do
Current right click menu:
![image](https://github.com/johannesjo/super-productivity/assets/25422924/d1873233-9ae0-4a21-b12e-f84661a94c0c)

I would like to have something similar to this:
![image](https://github.com/johannesjo/super-productivity/assets/25422924/bb0780e1-c2c1-40c0-ba72-80f7c5a81b35)
With the shortcuts on the right of the command

**Comment by johannesjo** [comment]
That is a wonderful suggestion! I am all for it!

**Comment by jere0500** [comment]
Hey there, 
I like this suggestion a lot and started looking into it. I got it partially working, it currently looks like this:
![image](https://github.com/johannesjo/super-productivity/assets/123008073/4e958815-bab6-4ece-9641-3351473f492d)

I am currently looking into which tooltips and submenus could get visible shortcuts.

**Comment by johannesjo** [comment]
This has been added now.
