### ISSUE TITLE
No 'SingletonCookie' file after installed by snap Ubuntu. 

### ISSUE THREAD

**Issue by AiDroopy** [johannesjo/super-productivity#3069]
* Application did not start after installation from "Ubuntu Software" App, (Snap Store) 
version:  8.0.0

* Uncaught Exception:
Error: ENOENT: no such file or directory, stat '/home/$USER/snap/superproductivity/current/.config/superProductivity/SingletonCookie'

* My solution was (can't see any side effects):
touch /home/$USER/snap/superproductivity/current/.config/superProductivity/SingletonCookie

**Comment by johannesjo** [comment]
Thanks for reporting and sharing your fix! So far I have been unable to reproduce this... :/

**Comment by AiDroopy** [comment]
No problem :) 
Thank you for the app! :) I really like the time estimation feature and comparing it to reality. That's the reason I didn't just tried just another one task app and wanted this one to work. 
Keep up the good work... 
I might wanna expand the estimation feature later :)

**Comment by johannesjo** [comment]
> I might wanna expand the estimation feature later :)

I am looking forward to hear your thoughts! :)

**Comment by JGPDev** [comment]
Excelent! Worked for me :)

**Comment by johannesjo** [comment]
Still unable to reproduce this, but there seem to be more people affected. Help would be very welcome with preventing this in the first place.
