### ISSUE TITLE
Your data seems to be damaged

### ISSUE THREAD

**Issue by Cyber-Syntax** [johannesjo/super-productivity#3073]
### Your Environment

- Version used: 8.0.1
- Operating System and version: Arch , fedora
- Desktop Environment: Qtile, i3wm, awesome
- Browser Name and version: 

### Current Behavior

Similar to #3059 but give for my P1 tag. I was able to open app and continue working without any errors and I haven't seen any data loss yet. I use that tag a lot and I don't want to lose things. 
Is there a solution to avoid losing data for now?
- I tried to find it that project by its ID and it seems I created some sub tasks to recurring task, and that probably cause issue. I deleted sub tasks and added time to direct recurring task. I am not sure if it solved the problem, but I didn't see any error after restarting.
- Task `c_Kcx7XJ6fO5MI2pMLD5U` if I am not wrong. It would be great if you told me that sub-task is in do-backup-for-cloud because I looked up for `timespentonday` and found only do-backup-for-cloud task on that day.
```
"title":"task_title_deleted_for_privacy_issues","notes":"",
"tagIds":["FEu9qjsHP2JtsXNmhg9Th","e_DPRk6bhtBjxVsGsnGmR"],
"parentId":null,"reminderId":null,"created":1709270092347,"repeatCfgId":"fwdiR3Ey5kC7MU4ZwFxY7","plannedAt":null,"_showSubTasksMode":2,
"attachments":[],"issueId":null,"issueProviderId":null,"issuePoints":null,"issueType":null,"issueAttachmentNr":null,"issueLastUpdated":null,"issueWasUpdated":null,"issueTimeTracked":null},
"W39P7SSMiSNW-B5yS7Ro3":{"id":"W39P7SSMiSNW-B5yS7Ro3",
"projectId":"cuSyGKNSEfXqQWU2hUMmW",

"subTaskIds":["c_Kcx7XJ6fO5MI2pMLD5U","6Jlt7vctUHDuNcEiJQjtj","Uhyg2XsJNiEQ3aqpCog1r","8wjTRJXyUFWafPnmqhh35"],
"timeSpentOnDay":{"2024-03-05":3819000},"timeSpent":3819000,"timeEstimate":600000,"isDone":true,"doneOn":1709646912258,

"title":"[Take 10 min] do-backup-for-cloud",
"notes":"",
"tagIds":["TODAY","FEu9qjsHP2JtsXNmhg9Th"],"parentId":null,"reminderId":null,"created":1709270092351,"repeatCfgId":"TNd7zwx7whbINTvwbQFby","plannedAt":null,"_showSubTasksMode":2,"attachments":[],"issueId":null,"issueProviderId":null,
"issuePoints":null,"issueType":null,"issueAttachmentNr":null,"issueLastUpdated":null,"issueWasUpdated":null,"issueTimeTracked":null},"YKiS
```

![image](https://github.com/johannesjo/super-productivity/assets/115875369/2c9aad67-f461-42bc-8c79-05a7db693bfd)

### Steps to Reproduce (for bugs)

1. Open superproductivity
2. Get error
3. Say ok
4. Continue using without visible error
5. Get same error every start.

### Can you reproduce this reliably?

I don't know how you can reproduce this behavior but I am consistently getting every start.
### Error Log (Desktop only)

```
[2024-03-06 00:23:22.515] [info]  close, isQuiting: true
[2024-03-06 10:10:05.329] [info]  { enabled: null, showDevTools: false, mode: 'bottom' }
[2024-03-06 10:10:05.994] [info]  Saving backups to /home/cyber-syntax/.config/superProductivity/backups
[2024-03-06 10:10:07.079] [info]  No custom styles detected at /home/cyber-syntax/.config/superProductivity/styles.css
[2024-03-06 10:41:48.190] [info]  close, isQuiting: undefined
[2024-03-06 10:41:48.195] [info]  Actions to wait for  [ 'SYNC_BEFORE_CLOSE_ID', 'FINISH_DAY_BEFORE_CLOSE_EFFECT' ]
[2024-03-06 10:41:49.392] [info]  BEFORE_CLOSE_DONE FINISH_DAY_BEFORE_CLOSE_EFFECT [ 'SYNC_BEFORE_CLOSE_ID' ]
[2024-03-06 10:41:52.116] [info]  BEFORE_CLOSE_DONE SYNC_BEFORE_CLOSE_ID []
[2024-03-06 10:41:52.116] [info]  close, isQuiting: undefined
[2024-03-06 10:41:52.117] [info]  close, isQuiting: true
[2024-03-06 10:41:52.188] [info]  Quit after all windows being closed
[2024-03-06 10:41:54.725] [info]  { enabled: null, showDevTools: false, mode: 'bottom' }
[2024-03-06 10:41:55.202] [info]  Saving backups to /home/cyber-syntax/.config/superProductivity/backups
[2024-03-06 10:41:56.280] [info]  No custom styles detected at /home/cyber-syntax/.config/superProductivity/styles.css
```

**Comment by johannesjo** [comment]
Hey there! Thank you very much for reporting this!

It would be great if you could share a copy of your data to contact@super-productivity.com, so I can debug this on my computer (and please let me know here, if you send something, as those mails quite often land in the spam folder). You can create an export by navigating to "Settings" and then to "Import/Export" or you can use the "Export data" button from the error Dialog (there is also a button there which will anonymize the data before exporting).

**Comment by Cyber-Syntax** [comment]
@johannesjo I was tried to export with anonymize export but it seems that not work for default task note. I send (mail subject include cyber-syntax) it anyway. I don't get same error anymore. It might be related what I did for solving.

**Comment by johannesjo** [comment]
Didn't find your mail. Hope i did not accidentally delete it :/

Would be great if you could send me the data export if the error happens again!

**Comment by Cyber-Syntax** [comment]
Apparently my solution worked. I don't get any error anymore. Therefore, I think you can't produce error with my data anymore.
 I started getting this error when I used p1 tag in subtasks of repetitive tasks. Maybe you can produce this manually. 
I don't have time to reproduce this error right now, but maybe I will when I have some free time..
