### ISSUE TITLE
Counters NOT CLICKABLE MacOS (works fine on Web app)

### ISSUE THREAD

**Issue by yarub123** [johannesjo/super-productivity#3075]
### Steps to Reproduce
1. Open up app
2. click counter
3. expect number to increase
4. Nothing registers
5. Right clicking it and manually inputting a number seems to work but not every time.

This element: `document.querySelector("body > app-root > mat-sidenav-container > mat-sidenav-content > header > main-header > div > nav > div.simple-counter-buttons-outer-wrapper.ng-tns-c124-4.ng-star-inserted")`

superProductivity 8.0.1 (2024)
MacOS 14.4 2020 intel

Appreciate you Johannes. Not a priority but just wanted to point this out. You're a wonderful human. Peace.

**Comment by sherlcok314159** [comment]
Same here. Tried all the mac versions.

**Comment by johannesjo** [comment]
This should be fixed now!
