### ISSUE TITLE
Narrow text area when editing note in fullscreen (Firefox)

### ISSUE THREAD

**Issue by fkohrt** [johannesjo/super-productivity#308]
Just discovered this app and I'm totally stunned! It combines so many eye candy features that often each make an app on their own, it's a pleasure to use it! Thank you for sharing this with the world!

I discovered a tiny bug that I want to report:

# Your Environment

* Version used: Web App 4.0.0
* Operating System and version: GNU/Linux 5.0.11
* Desktop Environment: Fedora 30
* Browser Name and version: Firefox 74.0

### Expected Behavior
I added a note in the sidebar:
![sidebar](https://user-images.githubusercontent.com/12914806/77318659-b6f91100-6d0d-11ea-9e3c-29220602ed8d.png)

When I click on _Edit in fullscreen_, I expect a text area spanning the whole window:

![expected](https://user-images.githubusercontent.com/12914806/77319123-91203c00-6d0e-11ea-9eaf-b07ff7f74775.png)

(Screenshot made with Chromium 79.0.3945.117)

### Current Behavior

When I click on _Edit in fullscreen_, I only see a narrow text area at the top, regardless of browser window size:

![fullscreen](https://user-images.githubusercontent.com/12914806/77319334-f70cc380-6d0e-11ea-8204-5fecdb766fb6.png)

### Steps to Reproduce (for bugs)

1. add a note
2. _Edit in fullscreen_

### Console Output

```
The Notification permission may only be requested from inside a short running user-generated event handler.
```

**Comment by johannesjo** [comment]
Hey there! Thanks for reporting. Glad that you like the app. As far as I can see, this error only occurs on ff. Currently I'm quite busy with other features & fixes, but a PR would be very welcome!

**Comment by fkohrt** [comment]
Alright, just wanted to be sure to have it tracked!

**Comment by johannesjo** [comment]
This should fixed now. Thanks again for reporting!
