### ISSUE TITLE
Shortcut: 'Show & Focus/Hide Sidenav' not working as expected

### ISSUE THREAD

**Issue by AngeloThys** [johannesjo/super-productivity#3084]
### Your Environment

- Version used: [AUR package: superproductivity-bin 8.0.1-1](https://aur.archlinux.org/packages/superproductivity-bin)
- Operating System and version: Arch Linux, systemd version: systemd 255 (255.4-2-arch)
- Desktop Environment: Hyprland
- Browser Name and version: N/A

### Expected Behavior

When pressing the related keybinding when:

#### A. Sidenav is not shown

Show and focus the sidenav.

#### B. Sidenav is shown

Hide the sidenav.

### Current Behavior

Sidenav is always shown.
When the keybind is used, sidenav gains focus. 
It does not hide the sidenav on second use.

### Steps to Reproduce (for bugs)

1.  Activate keybinding.
2. Focus sidenav.
3. Activate keybinding.
4. Nothing happens.

### Can you reproduce this reliably?

Yes. It happens consistently.

### Console Output

![image](https://github.com/johannesjo/super-productivity/assets/91565194/58c1ee02-efc2-48c6-ba75-6dc3bf80e062)

The first 2 *[layout]* outputs in the console are executed with the console closed, whilst the remaining are executed with the console open. **See edge case**

### Error Log (Desktop only)

Not provided.

### Edge case (?)

When performing the same steps with the console open (shift+ctrl+i), the keybinding for the shortcut: 'Show & Focus/Hide Sidenav' works as expected.

**Comment by johannesjo** [comment]
Hey there! When the app window is very wide the navigation is always shown.

**Comment by AngeloThys** [comment]
@johannesjo so it has to do with the screen being smaller when the console is open rather than an actual bug.
Good to know! Thanks
