### ISSUE TITLE
No way to start a Pomodoro break manually

### ISSUE THREAD

**Issue by 9z0** [johannesjo/super-productivity#3088]
### Your Environment

- Version used: 8.0.1
- Operating System and version: Win 10

### Steps to Reproduce (for bugs)

1. Enable Pomodoro
2. Wait until a session is finished. The pop up message of Start break/Skip break/Close should show.
3. Click close. Try to start the break

### Current Behavior

There isn't. Clicking Start/Pause button on the top right once does nothing I can see (it shows the coffee mug but it blue and the countdown doesn't start). Clicking again starts the next Pomodoro session.

### Expected Behavior

That clicking the start/pause button (or its global keyboard shortcut) should start the break.

### Can you reproduce this reliably?

Yes. This also happens

**Comment by Jagdfalke** [comment]
I can confirm this behaviour. 

As an additional note: In order to reproduce the behaviour, the Pomodoro timer needs end normally (by the time running out). Using the skip button immediately starts the break timer.

**Comment by 9z0** [comment]
Not stale
