### ISSUE TITLE
Unable to sync via Google Drive

### ISSUE THREAD

**Issue by peakgeek** [johannesjo/super-productivity#309]
### Your Environment

* Version used: Web App 4.0.0
* Operating System and version: Android 10
* Desktop Environment: N/A
* Browser Name and version: Brave 1.5.9, Chrome 80.0.3987.149, Firefox 68.6.0
### Expected Behavior
When clicking the "login" button in the Sync via Google Drive settings I would expect to see a login prompt

### Current Behavior
When clicking the "login" button in the Sync via Google Drive settings I just have a spinning wheel icon and never get an opportunity to authenticate my Google account.

### Steps to Reproduce (for bugs)
1. Open Super Productivity in mobile browser (Chrome, Brave, Firefox, etc)
2. Open settings menu
3. Click the Sync via Google Drive heading
4. (I've tried this requesting the desktop version of site, disabling pop-up blocking, and installing as a PWA with each of the mobile browsers listed and I haven't been able to authenticate my Google account in any scenario)

### Console Output
N/A
![signal-attachment-2020-03-23-104328](https://user-images.githubusercontent.com/3734060/77374596-baea5a80-6d30-11ea-8f2d-00644504fb71.jpeg)

**Comment by johannesjo** [comment]
Thanks for reporting. The error seems to be on googles side of things. Please have a look at #299 for more information.

**Comment by johannesjo** [comment]
I think I found a work around. A new release is on the way!

**Comment by AlanOrtega91** [comment]
@johannesjo first of all amazing app, I use it daily.
I also have this same issue while sync via Google Drive however it displays the window to select a google account and after selecting one it just goes back to showing "Login".

**Comment by tooxo** [comment]
Also having this issue on android.

**Comment by johannesjo** [comment]
@AlanOrtega91 & @tooxo 

Thanks for letting me now! Could you maybe open up a new issue with more detailed information? That would be very helpful!
