### ISSUE TITLE
Tray circle doesn't start at zero if Pomodoro is set to less than 20 minutes

### ISSUE THREAD

**Issue by 9z0** [johannesjo/super-productivity#3090]
### Your Environment

- Version used: 8.0.1
- Operating System and version: Win 10

### Steps to Reproduce (for bugs)

1. Settings: set Pomodoro length to 15 or 20 minutes
2. Close the app, reopen

### Expected Behavior

Tray circle should be "empty"

### Current Behavior

It shows a white segment as if a few minutes have passed.

### Can you reproduce this reliably?

Yes

**Comment by johannesjo** [comment]
Here is the relevant code: electron/indicator.ts

**Comment by 9z0** [comment]
Not stale
