### ISSUE TITLE
Long break dialog: option to take a short break instead

### ISSUE THREAD

**Issue by 9z0** [johannesjo/super-productivity#3092]
## Problem Statement

When I am in the zone, and I finished 4 Pomodoros, I am face with the options either to take the 15 minute break or skip it altogether.

## :grey_question: Possible Solution

I want to be able to take a short 5 minute break instead so that I don't cool off. Ideally, the long break is skipped forward (i.e. is suggested after the 5th Pomodoro instead.

## :arrow_heading_up: Describe alternatives you've considered

I have to set another timer to skip the remainder of the 15 minute break, but sometimes I forget.

**Comment by Jagdfalke** [comment]
I understand the request. However, this seems like an unusual suggestion for a Pomodoro timer. 

Might I suggest an alternative solution? You can use the settings to manually start Pomodoros and breaks. Additionally you can set the duration for the long break to the same duration as the short break. In this case, you can manually extend your break to 15 minutes at whichever Pomodoro you like.

**Comment by 9z0** [comment]
Thanks for the suggestion. I can make it work if my other suggestion (to add time to a session/break) is accepted 😉. I would set all breaks to 5 minutes and when the app notifies me of 4th/8th/... break I would add two 5-minute increments if I need a longer break!

At the same time, a button saying "Short break" shouldn't be confusing or difficult. 🤷‍♂️

Thanks
