### ISSUE TITLE
Goodtime style clear and editable sessions

### ISSUE THREAD

**Issue by 9z0** [johannesjo/super-productivity#3094]
## Problem Statement

I sometimes need to correct a session time. For example, I went to do something without pausing the app, so I need to set the last finished Pomodoro session to 20 minutes thus subtracting 5 minutes from the total task work time. Or maybe I need to remove the [factitious few hours](3093) from the work time. I would look for the work time segment measured in hours, 
## :grey_question: Possible Solution

[Goodtime](https://play.google.com/store/apps/details?id=com.apps.adrcotfas.goodtime) does this well. See the last screenshot.

## :arrow_heading_up: Describe alternatives you've considered

Quick history seems to allow editing the total work time for the day, so I can't remove the outlier session.

**Comment by Jagdfalke** [comment]
Maybe I don't fully understand your request. But you already can edit the time on each task you worked on, should your forget to stop the timer:

![Screenshot_20240321-213127.png](https://github.com/johannesjo/super-productivity/assets/17673417/35359c38-d2cd-4d3d-832a-c91c58b9944b)

**Comment by 9z0** [comment]
I meant editing individual Pomodoro sessions. In my example, I would be able to work around it (until you fix it) by removing only the hours-long session so that the total time is much closer to reality.

Allowing editing the whole work time in the day doesn't help much because I don't know exactly when I left the computer forgetting to finalize the work day in the app.

**Comment by 9z0** [comment]
#### Sorry I wasn't clear.

#### This is what I meant: a stats page showing a list of Pomodoros done, how long and when for each:

![](https://user-images.githubusercontent.com/46774/83064270-b8d3ad80-a08b-11ea-8e8c-3c2058ec4480.png)

#### When you open one of them to edit, it shows this where you can edit the duration or the start time among other variables.

![](https://github.com/johannesjo/super-productivity/assets/78097210/f554c5d3-c866-4671-a879-ff583c928bc3)

**Comment by 9z0** [comment]
Not stale and hopefully we'll see it soon
