### ISSUE TITLE
Button to add time to current Pomodoro session

### ISSUE THREAD

**Issue by 9z0** [johannesjo/super-productivity#3095]
## Problem Statement

Sometimes I am flowing, and I don't want interruptions or even a break.

## :grey_question: Possible Solution

A button to add increments of 5 minutes to the current session.

**Comment by Jagdfalke** [comment]
This is not how Pomodoros are supposed to work. The main point is to focus for a fixed interval and have a break afterwards. If you want to continue working, you could skip the break and start the next Pomodoro.

**Comment by 9z0** [comment]
Pomodoros can be adapted to individual needs and natures. Other Pomodoro apps like Goodtime allow it (by swiping up). It is not a major issue, though.

**Comment by Jagdfalke** [comment]
Sure, no one forces you to take a break when a Pomodoro ends. As I mentioned there is a way to continue working by skipping the break. That way you also remain flexible with your Pomodoros.
