### ISSUE TITLE
Option to manually refresh the backlog from JIRA

### ISSUE THREAD

**Issue by dflock** [johannesjo/super-productivity#31]
Currently not sure when/how often the local backlog is refreshed from JIRA - would be very nice to have an option to refresh manually.

**Comment by johannesjo** [comment]
Hello! The backlog should be refreshed every time you go the planning view so that's kind of a refresh button :)

Furthermore the already imported tasks should be checked for updates every 5 minutes.

**Comment by johannesjo** [comment]
I added a button anyway. Will be coming with the next release.
