### ISSUE TITLE
Crash when minimized

### ISSUE THREAD

**Issue by jlewczynski** [johannesjo/super-productivity#310]
### Your Environment
* Version used: 4.0.3, snap
* Operating System and version: Ubuntu 18.04.04
* Desktop Environment: Gnome

### Current Behavior
A task was clocked in, the app was minimized. While doing some other work the SuperProductivity app got the focus and showed a message with the stack trace attached.

[superproductivity-error-stacktrace.txt](https://github.com/johannesjo/super-productivity/files/4375293/superproductivity-error-stacktrace.txt)

**Comment by johannesjo** [comment]
Thanks for reporting. This is a duplicate of #236

**Comment by johannesjo** [comment]
https://github.com/localForage/localForage/issues/788
