### ISSUE TITLE
Advanced Options for terminal commands

### ISSUE THREAD

**Issue by pieshrimp95** [johannesjo/super-productivity#3103]
Super Productivity known as gui app, but why not to expand to terminal-executable commands?
It would be so useful if you want see logs or do autostart from terminal like:

```
superproductivity --help
```

Feature like debugging, option to allow start in tray, or show version of the app would be appreciated to be implemented in the app.

**Comment by johannesjo** [comment]
Thanks for the suggestion. I like the idea, since many developers are using the app. Probably won't find the time to work on it myself (as I don't need it myself), but PRs are welcome!
