### ISSUE TITLE
Adding Issues from Superproductivity to GitLab

### ISSUE THREAD

**Issue by vaskokj** [johannesjo/super-productivity#3108]
## Problem Statement
Adding Issues from Superproductivity to GitLab

Would like to be able to add Issues from SuperProductivity. Seems that the current implementation is "pull" only. I would like to be able to create a task in SuperProductivity and push it to GitLab as an issue.

https://github.com/johannesjo/super-productivity/issues/156#issuecomment-609768552

**Comment by johannesjo** [comment]
I think it would be nice to provide some sort of option to do this. More detailed suggestions on how this could work and PRs are welcome!
