### ISSUE TITLE
Forgot to close previous day: how to deal?

### ISSUE THREAD

**Issue by stefanoco** [johannesjo/super-productivity#311]
(this is a request for usage explanation) maybe I'm asking something obvious but I'm missing: is it possible to close "yesterday" in case I forgot to do it, or app left open across the night?

**Comment by stefanoco** [comment]
Ok I realized now that this might not be an issue: not "closing" yesterday has no effect, the time recorded will be tracked as per current day and no difference is produced. Waiting for any comment and then closing here.

**Comment by johannesjo** [comment]
Not really sure if I understood you correctly. By closing yesterday, do you mean hiding the banner with the "You forgot to finish your day..." notification?

**Comment by stefanoco** [comment]
I mean: sometimes at the end of the day I forget to click the "Finish day" buttom; I was wondering if the same can be done today for yesterday, but now I realized that this makes no sense because no special action is performed on the database by this action.

**Comment by johannesjo** [comment]
Ahh. Alright, thanks for the clarification :)

**Comment by ichbean** [comment]
Actually, that'd be awesome if such "Don't break the chain" functionality was implemented.

**Comment by stefanoco** [comment]
> Actually, that'd be awesome if such "Don't break the chain" functionality was implemented.

It might be not so useful: "Finish day" (as far as I understand) has the only meaning of "please add your comments about how the day has gone..." etc
