### ISSUE TITLE
Possible Typographical error 

### ISSUE THREAD

**Issue by theFairestOfAll** [johannesjo/super-productivity#3117]
![image](https://github.com/johannesjo/super-productivity/assets/43836981/d33ddb1a-46e9-4ea0-a90a-5ae406b4a87f)

Is this meant to be planing or is it supposed to be planning?

Thank you

**Comment by Jagdfalke** [comment]
Hi, this is a spelling error. 😀 I have already spotted it earlier last week and corrected it. It should correctly spell 'planning' in the next version.
