### ISSUE TITLE
Worklog and Quick History list tasks that have not been worked on

### ISSUE THREAD

**Issue by Jagdfalke** [johannesjo/super-productivity#3122]
### Your Environment

- Version used: 8.0.1
- Operating System and version: Windows 10 / Android 14
- Desktop Environment: Both desktop and mobile

### Expected Behavior

A task should only appear in the Worklog or Quick History when time has been tracked for the task or if it has been checked as completed. 

### Current Behavior

When you create a task and you don't track any time and don't mark ist as completed, it will still appear in the Worklog and Quick History on the day you created it. 

### Steps to Reproduce (for bugs)

1. Create a task and don't track any time:
![image](https://github.com/johannesjo/super-productivity/assets/17673417/3eb1e617-fcde-4710-a823-95b7ac493b6c)
2. Go to either Quick History or Worklog and drill down on the current day
3. The task will appear even though no time has been tracked:
 ![image](https://github.com/johannesjo/super-productivity/assets/17673417/a9e4e17f-8216-4418-8bc0-974fd176943d)

### Can you reproduce this reliably?

Yes, 100% of the time

**Comment by johannesjo** [comment]
Thanks for opening this up!

For the worklog this is necessary since otherwise there would be no way to restore these tasks and they will be just lost in the void. So I'd prefer not to change the behavior for those. 

For the quick history my suggestion would be as follows: We don't show tasks that have no time spent for the day, unless they have been marked as done on that day. What do you think @Jagdfalke ?

**Comment by johannesjo** [comment]
Imagine an archived undone sub task of a done task where you have some documents attached or some interesting notes. If we don't display it in the worklog somewhere, it is like it is never existed, just taking up disk space.

**Comment by Jagdfalke** [comment]
Alright, understood. But sub-tasks are still connected to their parent when the parent is marked as 'done', aren't they?

Wouldn't it be possible to add 'undone' sub-tasks to the worklog on the day when their parent was marked as 'done'? That way they wouldn't be lost and it makes more sense to display them on the day their parent was marked as 'done', implying that they are done as well.
