### ISSUE TITLE
Allow to specify Lunch break and show it on timeline

### ISSUE THREAD

**Issue by gerodp** [johannesjo/super-productivity#3125]
## Problem Statement

Currently, it's not possible to show the lunch break in the timeline. This causes that the timeline view and the task start times don't reflect the reality.

## :grey_question: Possible Solution
Allow to specify the lunch break in the Timeline configuration (e.g. from 13:00 to 14:00 ) and show it on the timeline for each day. Tasks that fall in between should be split.

## :arrow_heading_up: Describe alternatives you've considered
None

## :heavy_plus_sign: Additional context
N/A

**Comment by johannesjo** [comment]
Hey there! You can either create your lunchbreak as a repeatable task or you can add it to your calendar and import it into your timeline.

**Comment by gerodp** [comment]
Hi @johannesjo!

Thanks for your prompt reply.

Regarding adding lunchbreak as a repeatable task, I wouldn't like to mark breaks as tasks as it can pollute the statistics. For example, it will compute this as working time, am I right, or am I missing something?

As an alternative I though of adding a config to specify the lunch breaks so they'll show up in the timeline and tasks will be split accordingly. I can implement this and submit a PR but I'd like to read your opinion first.

Thanks in advance

**Comment by gerodp** [comment]
Hi @johannesjo,

I was wondering if you have any thoughts on that? As I said I can implement a PR for this feature.

Thanks

**Comment by Jagdfalke** [comment]
Hi @gerodp . Help is always welcome. If you are able to provide a PR with an implementation, I don't see a reason why not to. 

I assume you would implement it similar to the timeline work time feature? 

![image](https://github.com/johannesjo/super-productivity/assets/17673417/325c000d-2860-423e-93a0-4a810ff6f3f1)

**Comment by gerodp** [comment]
HI @Jagdfalke,

Exactly, my idea is to implement it like the work time feature.

BR

**Comment by nairboon** [comment]
i guess this issue can be closed now?
