### ISSUE TITLE
`Space` as a keyboad shortcut does not work

### ISSUE THREAD

**Issue by KAGEYAM4** [johannesjo/super-productivity#3130]
### Your Environment
- Version used: superproductivity-bin 8.0.1-1 (AUR)
- Operating System and version: Arch Linux x86_64  6.8.2-zen2-1-zen 
- Desktop Environment:  Hyprland & KDE 6

### Expected Behavior
`Space` as keyboad shortcut to `Start/Stop Task` does not work.

### Current Behavior
Suprer-productivity successfully registers the `Space` as keyboard shortcut, but when i try to use the shortcut nothing happens.

### Steps to Reproduce (for bugs)

1. Go into settings
2. Keyboad Shortcut
3. Assigne `Space` for `start/stop task`

### Can you reproduce this reliably?
Yes

### Console Output

There are no console output when i try the `Space` to `start/stop task` 
But there are console output when i assign `space` as `keyboard-shortcut`

### Error Log (Desktop only)
i checked the error logs, and as the time of writing, i tried to reproduce the bug and when i checked the error log, the last entry was 20mins ago.

**Comment by Jagdfalke** [comment]
Hm, to be honest, I'm a bit puzzled by your request. Did you notice that the shortcut works globally? This means, whenever you press the space bar (e.g. when typing this text), you start or end the time tracking. So assigning space as a shortcut is not the most feasible choice. 

Having written this, adding Space as a shortcut works for me using the desktop client. However, I cannot use Space in other applications anymore. I'd therefore argue towards not allowing Space as a shortcut in the first place.

**Comment by KAGEYAM4** [comment]
No, sorry i meant adding `space` key as a shortcut in ` Tasks >The following shortcuts apply for the currently selected task (selected via tab or mouse)` Section.

![image](https://github.com/johannesjo/super-productivity/assets/75798544/ff8562c0-560e-4f5e-9f33-643858b86047)

The applicatoin registers the `space` key successfully when assigning the shortcut, but it dosen't work after that.
