### ISSUE TITLE
Add Evolu as Sync Provider / Revisit Sync Data model

### ISSUE THREAD

**Issue by negue** [johannesjo/super-productivity#3139]
## Problem Statement
I recentely came across of [Evolu](https://www.evolu.dev/), it is an embedded SQLite Database, where each database entry is synched end to end encrypted to any other instance using your private key. You can host your own simple server or use Evolu's free one, maybe at some point there will be P2P as well, who knows what the features will bring :)

I thought I could try to add it, but it seems right now that the syncs are only based on "collect all data into one file and sync that one", Evolu can handle json files as a data column but I think it would be better to upgrade the sync provider to be able to handle each note/entry alone, then evolu could be used a bit more "normally" 😬  (and less data needed to change one item instead of a big json of all data ^^ )

**Comment by Jagdfalke** [comment]
I'm not sure if I understand Evolu correctly. But couldn't you just use local file as a sync option and automatically import that into Evolu?

**Comment by negue** [comment]
WebDAV/Dropbox are more File Based Storages, while evolu is more of a database that is sycned, that why using it as "only a json file to be synced" might waste at some point traffic if only 40 of 1000 items in that json are changed xD

If SyncProviders could get a more granular callbacks (instead of the whole json file) then I'd give it a try to add evolu myself^^ , but thats still above my knowledge how many files would need to be changed "just" for that

**Comment by johannesjo** [comment]
Thanks for the suggestion! Looks interesting! This would require a large scale migration. For that I need a lot of free time and I would need to be a bit more sure about Evolu, so some testing is required. It looks promising, but these kind of systems rarely come without drawbacks. Performance could be problematic for example. There could be bugs. Also development is done mainly by only one person. There is no guarantee that the project will be maintained in the future. But I promise to have a look, if tackle the subject again.
