### ISSUE TITLE
Template strings not correctly relaced when I snooze reminder in German localisation

### ISSUE THREAD

**Issue by rklec** [johannesjo/super-productivity#3147]
### Your Environment

- Version used:  8.0.5
- Operating System and version: Windows 10
- Desktop Environment:  N/A
- Browser Name and version:  N/A

### Expected Behavior

eplace the strings "title" and "start" with the values, likely there is a space too much.

### Current Behavior

![grafik](https://github.com/johannesjo/super-productivity/assets/71322635/191c498c-f297-4742-bb66-951b622e5882)

### Steps to Reproduce (for bugs)

Setup/use a reminder that pops up that you need to do sth.
Snooze in/for 10 min. e.g.

### Can you reproduce this reliably?

Not tested, but I guess

### Console Output

nothing relevant

### Error Log (Desktop only)

not relevant

**Comment by rklec** [comment]
I have created a PR to fix the immediate issue (there are many more broken strings), but maybe you can expand some unit tests or so catch issues like this? Or does the translation platform display a preview of possible content values?

**Comment by Jagdfalke** [comment]
Uh oh, this one is on me. I've completed the German translation for the current version 8.0.5. The translation tool does not have a preview for variable content. I tried to account for this manually but apparantly this slipped past my attention.

**Comment by rklec** [comment]
Which tool do you even use? [The contrib guide](https://github.com/johannesjo/super-productivity/blob/master/CONTRIBUTING.md) does not mention an online tool or so - maybe introducing such one (even syntax highlighting the parts could help), would help?

**Comment by johannesjo** [comment]
Thank you very much for the fix!
