### ISSUE TITLE
5.0.0 Windows Defender gives Trojan:Win32Bulta!rfn warning

### ISSUE THREAD

**Issue by gokomer** [johannesjo/super-productivity#315]
### Your Environment
* Version used: 5.0.0
* Operating System and version: Windows 10 Education 19041.153

### Expected Behavior
No virus warning from Windows Defender

### Current Behavior
Windows Defender warning for Trojan:Win32/Bulta!rfn

### Steps to Reproduce (for bugs)
1. Install superProductivity-Setup-5.0.0.exe
2. Windows Defender gives a warning.

![virus](https://user-images.githubusercontent.com/11593018/77688579-60136600-6fb1-11ea-922e-22bc42b8b98e.JPG)

**Comment by johannesjo** [comment]
Thanks for reporting. That is not cool at all... :/

**Comment by gokomer** [comment]
and this is Windows Defender database version

![database](https://user-images.githubusercontent.com/11593018/77688997-00698a80-6fb2-11ea-9bb4-daa0c07d4295.JPG)

**Comment by johannesjo** [comment]
Should be fixed by waiting. Hopefully.

https://github.com/electron-userland/electron-builder/issues/4793
