### ISSUE TITLE
Global Areas

### ISSUE THREAD

**Issue by kfosse13** [johannesjo/super-productivity#3151]
## Problem Statement
I would love it if we could create separate areas, like in Nirvana.

## :grey_question: Possible Solution
The areas feature would allow you to filter out any tasks/projects that do not fall under that specific area. Perhaps these could even be separated by work time (i.e. all work-related projects are visible from 9am-5pm, and all personal projects are visible the rest of the time).

## :arrow_heading_up: Describe alternatives you've considered
A possibly simpler solution would be to allow users to create custom project list drop-downs in the sidenav.

**Comment by Jagdfalke** [comment]
Isn't that something you could achieve with tags?

**Comment by kfosse13** [comment]
Sort of. That's my current solution, but I just have a lot of projects in a lot of different areas of life, and it can feel a little overwhelming to try and parse through. For me, being able to look only at projects from a specific area would be very helpful.

I like going through my list project-by-project to think through my next actionable steps (I try to adhere to the GTD methodology). There's a certain anxiety that comes with tags that I may have forgotten to tag a task, so I may be missing important steps.

Thank you for replying! I get that this may not be a priority for many people, but it might be helpful for anyone using GTD, and looking for a way to filter the Areas of Focus.
