### ISSUE TITLE
Sync error on opening app

### ISSUE THREAD

**Issue by one3711** [johannesjo/super-productivity#3157]
Every time I open SP, an error dialogue box says "Sync Error. last sync value is newer than local, which should never happen if you weren't manually manipulating the data!"
I am not doing anything with the data. I am innocent.

![Screenshot 2024-04-19 190401](https://github.com/johannesjo/super-productivity/assets/152137740/b1685e6c-f581-44b4-8a07-2f7778ffd0b2)

I have SP on Android but didn't open it there for a week.

**Comment by johannesjo** [comment]
> I am innocent.

Well well. We'll see about that xD

Can you maybe provide the logs that are written in this context (If you press Ctrl+Shift+I the console should appear)?

**Comment by one3711** [comment]
This time, a different popup asked me to delete remote data and keep local data. I clicked ok and the problem seems to be solved. 
By the way, I didn't understand your comment. (What are logs?)

**Comment by Jagdfalke** [comment]
>A logbook (a ship's logs or simply log) is a record of important events in the management, operation, and navigation of a ship. It is essential to traditional navigation, and must be filled in at least daily. [..] The term logbook has spread to a wide variety of [other usages](https://en.wikipedia.org/wiki/Logbook).
