### ISSUE TITLE
Super Productivity won'd start on ubuntu 22.04

### ISSUE THREAD

**Issue by sscrdj** [johannesjo/super-productivity#3159]
### Your Environment

- Version used: 
- Operating System and version:
- Desktop Environment: 
- Browser Name and version: 

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by sscrdj** [comment]
sorry for the snafu... my issue is that i installed the app on ubuntu 22.04 machine. On running the programme I am getting the following error 
------------------------------------------------------------
Detected legacy snap user data. Copying it over to common...
-------------------------------------------------------------
oldPath /home/shaily/snap/superproductivity/current/.config/superProductivity
newPath /home/shaily/snap/superproductivity/common/.config/superProductivity
isExistsOldPath true
isExistsNewPath false


A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT: no such file or directory, stat '/home/shaily/snap/superproductivity/current/.config/superProductivity/SingletonCookie'
    at Object.stat (node:internal/fs/sync:58:25)
    at statSync (node:fs:1669:17)
    at t.statSync (node:electron/js2c/node_init:2:5052)
    at /snap/superproductivity/1910/resources/app.asar/electron/start-app.js:97:50
    at Array.forEach (<anonymous>)
    at copyDir_1 (/snap/superproductivity/1910/resources/app.asar/electron/start-app.js:94:22)
    at startApp (/snap/superproductivity/1910/resources/app.asar/electron/start-app.js:109:13)
    at Object.<anonymous> (/snap/superproductivity/1910/resources/app.asar/electron/main.js:17:34)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)

(superproductivity:38567): Gtk-WARNING **: 23:25:24.133: Theme parsing error: gtk.css:1422:23: 'font-feature-settings' is not a valid property name

(superproductivity:38567): Gtk-WARNING **: 23:25:24.141: Theme parsing error: gtk.css:3308:25: 'font-feature-settings' is not a valid property name

(superproductivity:38567): Gtk-WARNING **: 23:25:24.143: Theme parsing error: gtk.css:3770:23: 'font-feature-settings' is not a valid property name

(superproductivity:38567): Gtk-WARNING **: 23:25:26.259: Theme parsing error: gtk.css:1422:23: 'font-feature-settings' is not a valid property name

(superproductivity:38567): Gtk-WARNING **: 23:25:26.271: Theme parsing error: gtk.css:3308:25: 'font-feature-settings' is not a valid property name

(superproductivity:38567): Gtk-WARNING **: 23:25:26.274: Theme parsing error: gtk.css:3770:23: 'font-feature-settings' is not a valid property name

The app does not start
Thanks in advance

**Comment by Jagdfalke** [comment]
What version of Super Productivity did you use?

**Comment by johannesjo** [comment]
Possibly related:
https://github.com/johannesjo/super-productivity/issues/3069
