### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by ryanjkemper** [johannesjo/super-productivity#3162]
### Steps to Reproduce

1. Click the 3 dots next to "Today" -> Click "Worklog"
2. Click the arrow pointing to the upper-right corner of certain week's or months where the issue is present
3. Receive the error message

Note: This only happens on select week/months within the Worklog where the issue occurs.  For example, the error occurs when trying to export "April" but not "March or Febuary".  The error also occurs when trying to export Week 4 (4/1 - 4/7), but not any of the other weeks in April.  So, there may be something wrong with a single task somewhere in Week 14?

### Meta Info
META: SP8.0.5 Browser – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0

### Stacktrace
```
map (webpack:///src/app/features/worklog/worklog-export/worklog-export.util.ts:204:14)
handleWorklogGroup (webpack:///src/app/features/worklog/worklog-export/worklog-export.util.ts:167:25)
handleWorklogGroup (webpack:///src/app/features/worklog/worklog-export/worklog-export.util.ts:165:37)
groupKeys (webpack:///src/app/features/worklog/worklog-export/worklog-export.util.ts:36:34)
subscribe( (webpack:///src/app/features/worklog/worklog-export/worklog-export.component.ts:154:25)
__tryOrUnsub (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:183:15)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:122:21)
_next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:72:25)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)
```

### Actions Before Error
```
1713907543958: [Tag] Update Advanced Config 
1713907544085: [Persistence] Save to DB 
1713907550343: [Tag] Update Advanced Config 
1713907550477: [Persistence] Save to DB 
1713907561710: [Tag] Update Advanced Config 
1713907561871: [Persistence] Save to DB 
1713907565457: [Tag] Update Advanced Config 
1713907565536: [Persistence] Save to DB 
1713907569904: [Tag] Update Advanced Config 
1713907570018: [Persistence] Save to DB 
1713907582831: [Tag] Update Advanced Config 
1713907582942: [Persistence] Save to DB 
1713907584311: [Tag] Update Advanced Config 
1713907584409: [Persistence] Save to DB 
1713907770177: [Tag] Update Advanced Config 
1713907770270: [Persistence] Save to DB 
1713907951594: [Tag] Update Advanced Config 
1713907951702: [Persistence] Save to DB 
1713908270602: [FocusMode] Set focus session elapsed time 
1713908270714: [SP_ALL] Load(import) all data 
1713908270717: [SP_ALL] All Data was loaded 
1713908275589: [FocusMode] Set focus session elapsed time 
1713908275698: [SP_ALL] Load(import) all data 
1713908275700: [SP_ALL] All Data was loaded 
1713908283658: [FocusMode] Set focus session elapsed time 
1713908283763: [SP_ALL] Load(import) all data 
1713908283765: [SP_ALL] All Data was loaded 
1713908466427: [FocusMode] Set focus session elapsed time 
1713908466546: [SP_ALL] Load(import) all data 
1713908466550: [SP_ALL] All Data was loaded
```

**Comment by johannesjo** [comment]
Hey there! Thank you very much for reporting this!

It might be that for some reason a bit of your data got into an invalid state that I didn't account for and that I can't reproduce. It would be great if you could share a copy of your data to contact@super-productivity.com, so I can debug this on my computer (and please let me know here, if you send something, as those mails quite often land in the spam folder). You can create an export by navigating to "Settings" and then to "Import/Export" or you can use the "Export data" button from the error Dialog (there is also a button there which will anonymize the data before exporting).
