### ISSUE TITLE
Force time tracking by setting max untracked time

### ISSUE THREAD

**Issue by Bonjour123** [johannesjo/super-productivity#3164]
## Problem Statement
A lot of times, when I install a time tracking app, I use it for a time, then loose the habit more and more until I don't use it anymore. 

## :grey_question: Possible Solution

I would love if there was a max untracked time, like for instance (15 min/4 hours) where untracked time is for short tasks, preparing workspaces, installing things, ...
If the untracked time exceeds this value, a full screen reminder would pop up every x seconds (could be 30s) until time tracking as been resumed. Could as well include the anti-procrastination button featured in the focus mode.
This feature should be started automatically at system startup.
Untracked time timer should start at screen unlocks.
Different anti-tampering techniques should be used, based on [Lock Me Out](https://play.google.com/store/apps/details?id=com.teqtic.lockmeout&hl=en&gl=US). For instance, sensitive settings can be changed only after a certain time:
To modify _Untracked time settings_, click the unlock button to initiate a x time countdown (for instance 4 hours), after which the settings page becomes accessible. Of course it would still be possible to kill the process, but it is possible to  make a hard-to-kill process (outside the scope of this project as it can be added independently) and moreover the user acknowledges that by killing the process, he is doing something against the purpose of superproductivity.

## :heavy_plus_sign: Additional context

This is really usefull the following scenarios:

- if you're going down in a rabbit hole. For instance, you planned to start a background music but you have been hijacked by youtube predatory algorithm and didn't noticed the time spent.
- you planned to perform a quick task which actually came out to be much longer than expected, this force you to document the task, which you didn't do at first since you though it was a very short task.
- you're not working and this forces you to document this as a break
- you finished a task and forgot to assign a new

**Comment by Jagdfalke** [comment]
Mmh you request seems to go a bit beyond, but basically Super Producitivity already has the feature you are requesting, the 'time tracking reminder':

![image](https://github.com/johannesjo/super-productivity/assets/17673417/cde5406f-44d8-4fcc-a16f-f94a562fa3cd)

Is you exceed the time given here, Super Productivity will display a banner that you have not been tracking time for x minutes. You are given the option to assign the untracked time to a task.
