### ISSUE TITLE
+ shortcut should not add task to hidden project

### ISSUE THREAD

**Issue by ImaCrea** [johannesjo/super-productivity#3165]
Hi there! Thanks for this great app, one of my favorite. Very effective and well thought.

Here's a pain point I just encountered. Given #2077 I guess this is a bug, hope I didn't misunderstand it. 🙏 

### Your Environment

- Version used: Mac App 8.0.5 (installed from DMG)
- Operating System and version: Mac 11.7.10

### Expected Behavior

When I use the "+" shortcut to add a task to a project, I should be recommended with project that are visible *only*.

### Current Behavior

Project are recommended when using "+" shortcut, regardless of their visibility. Hence the shortcut isn't efficient anymore if a visible project share some of its name with other hidden projects.

For example, let's say I had "project 1" done and therefore I hide it. Then I create "project 2". Typing "+p" (considering there's no other project starting with p) should directly add the task to the visible project, "project 2". Instead, at the moment, it goes into "project 1". Unless I fully type "+project 2" into the task, but then it's quiet frustrating and loses the value brought by the shortcut.

### Steps to Reproduce (for bugs)

1. Start typing a new task
2. Type +
3. See hidden projects showing

### Can you reproduce this reliably?

Yes.

**Comment by johannesjo** [comment]
I don't really consider this as a bug, but it might be a good change :)

**Comment by ImaCrea** [comment]
Alrighty, thanks @johannesjo !

**Comment by ImaCrea** [comment]
+1 🙏

**Comment by johannesjo** [comment]
Will be added with the next release!
