### ISSUE TITLE
Issue submitted via apport

### ISSUE THREAD

**Issue by anz2k** [johannesjo/super-productivity#3181]
**ProblemType**
Bug

**Date**
Mon May 13 06:59:30 2024

**CurrentDesktop**
ubuntu:GNOME

**ProcEnviron**
LANG=en_US.UTF-8
LC_ADDRESS=et_EE.UTF-8
LC_IDENTIFICATION=et_EE.UTF-8
LC_MEASUREMENT=et_EE.UTF-8
LC_MONETARY=et_EE.UTF-8
LC_NAME=et_EE.UTF-8
LC_NUMERIC=et_EE.UTF-8
LC_PAPER=et_EE.UTF-8
LC_TELEPHONE=et_EE.UTF-8
LC_TIME=et_EE.UTF-8
PATH=(custom, no user)
SHELL=/bin/bash
TERM=xterm-256color
XDG_RUNTIME_DIR=<set>

**DistroRelease**
Ubuntu 24.04

**Uname**
Linux 6.8.0-31-generic x86_64

**Architecture**
amd64

**Snap**
superproductivity 8.0.5 (latest/stable)

**SnapChanges**
ID   Status  Spawn                      Ready                      Summary
6    Done    2024-05-13T06:43:21+03:00  2024-05-13T06:45:59+03:00  Install "superproductivity" snap from "latest/stable" channel

**SnapConnections**
Interface                 Plug                               Slot                             Notes
audio-playback            superproductivity:audio-playback   :audio-playback                  -
browser-support           superproductivity:browser-support  :browser-support                 -
content[gnome-3-28-1804]  superproductivity:gnome-3-28-1804  gnome-3-28-1804:gnome-3-28-1804  -
content[gtk-3-themes]     superproductivity:gtk-3-themes     gtk-common-themes:gtk-3-themes   -
content[icon-themes]      superproductivity:icon-themes      gtk-common-themes:icon-themes    -
content[sound-themes]     superproductivity:sound-themes     gtk-common-themes:sound-themes   -
desktop                   superproductivity:desktop          :desktop                         -
desktop-legacy            superproductivity:desktop-legacy   :desktop-legacy                  -
gsettings                 superproductivity:gsettings        :gsettings                       -
home                      superproductivity:home             :home                            -
network                   superproductivity:network          :network                         -
opengl                    superproductivity:opengl           :opengl                          -
pulseaudio                superproductivity:pulseaudio       :pulseaudio                      -
unity7                    superproductivity:unity7           :unity7                          -
wayland                   superproductivity:wayland          :wayland                         -
x11                       superproductivity:x11              :x11                             -

**SnapInfo.superproductivity**
name:      superproductivity
summary:   Super Productivity – The advanced ToDo List and Productivity Tool
publisher: johannesjo
store-url: https://snapcraft.io/superproductivity
contact:   https://github.com/johannesjo/super-productivity
license:   unset
description: |
  **Personal Task Management with integrated Time Tracking**
  
  Efficiently manage your tasks and track the time spent on each one. Utilize
  timeboxing to maintain focus and prevent getting overwhelmed. Effortlessly
  generate timesheets and work summaries for comprehensive work
  documentation.
  
  
  **Seamless Integration with Jira, GitHub, GitLab, OpenProject & More**
  
  Stay updated with all crucial ticket changes without drowning in a sea of
  email notifications. Keep everything that matters to you at your
  fingertips, while effectively filtering out unnecessary information.
  
  
  **Take advantage of a variation of productivity helpers**
  
  Recognizing that everyone's work style and challenges vary, Super
  Productivity provides a range of customizable productivity tool. These
  include a Pomodoro timer, a focus mode, self-evaluation tools, and a break
  reminder.
  
  
  **Connect your Calendars**
  
  Import your calendar events as tasks whenever needed. Leverage the timeline
  feature for a swift, at-a-glance overview of your day.
  
  
  **Data Privacy and Ownership**
  
  The app does NOT collect any data and there are no user accounts or
  registration required. It's a free and open source and always will be.
commands:
  - superproductivity
snap-id:      wZo5sef6NuUKCW6DP83fJ6zIZyd5R1sA
tracking:     latest/stable
refresh-date: 2024-05-13T06:44:58+03:00
channels:
  latest/stable:    8.0.5 2024-04-12T17:23:05Z (1910) 95MB -
  latest/candidate: 8.0.5 2024-04-12T17:23:05Z (1910) 95MB -
  latest/beta:      ^                                      
  latest/edge:      8.0.5 2024-05-06T11:23:45Z (1922) 95MB -
installed:          8.0.5                      (1910) 95MB -

**SnapInfo.core20**
name:      core20
summary:   Runtime environment based on Ubuntu 20.04
publisher: Canonical**
store-url: https://snapcraft.io/core20
contact:   https://github.com/snapcore/core20/issues
license:   unset
description: |
  The base snap based on the Ubuntu 20.04 release.
type:         base
snap-id:      DLqre5XGLbDqg9jPtiAhRRjDuPVa5X1q
tracking:     latest/stable
refresh-date: 2024-05-13T06:44:13+03:00
channels:
  latest/stable:    20240227 2024-04-10T07:10:04Z (2264) 67MB -
  latest/candidate: 20240416 2024-05-08T12:30:07Z (2318) 67MB -
  latest/beta:      20240430 2024-05-08T16:30:06Z (2335) 67MB -
  latest/edge:      20240509 2024-05-10T08:08:10Z (2337) 67MB -
installed:          20240227                      (2264) 67MB base

**SnapInfo.gnome-3-28-1804**
name:      gnome-3-28-1804
summary:   Shared GNOME 3.28 runtime for Ubuntu 18.04
publisher: Canonical**
store-url: https://snapcraft.io/gnome-3-28-1804
contact:   https://gitlab.gnome.org/Community/Ubuntu/gnome-3-28-1804/issues
license:   unset
description: |
  This snap includes a GNOME 3.28 stack (the base libraries and desktop
  integration components) and shares it through the content interface.
snap-id:      TKv5Fm000l4XiUYJW9pjWHLkCPlDbIg1
tracking:     latest/stable
refresh-date: 2024-05-13T06:45:34+03:00
channels:
  latest/stable:    3.28.0-19-g98f9e67.98f9e67 2023-04-17T09:10:03Z (198) 172MB -
  latest/candidate: 3.28.0-19-g98f9e67.98f9e67 2023-04-11T14:18:35Z (198) 172MB -
  latest/beta:      ^                                                           
  latest/edge:      ^                                                           
installed:          3.28.0-19-g98f9e67.98f9e67                      (198) 172MB -

**SnapInfo.gtk-common-themes**
name:      gtk-common-themes
summary:   All the (common) themes
publisher: Canonical**
store-url: https://snapcraft.io/gtk-common-themes
license:   unset
description: |
  A snap that exports the GTK and icon themes used on various Linux distros.
snap-id:      jZLfBRzf1cYlYysIjD2bwSzNtngY0qit
tracking:     latest/stable/ubuntu-24.04
refresh-date: 2024-04-24T13:51:32+03:00
channels:
  latest/stable:    0.1-81-g442e511 2022-06-28T18:10:06Z (1535) 96MB -
  latest/candidate: 0.1-81-g442e511 2022-06-24T16:30:46Z (1535) 96MB -
  latest/beta:      0.1-81-g442e511 2022-06-24T16:30:46Z (1535) 96MB -
  latest/edge:      ^                                                
installed:          0.1-81-g442e511                      (1535) 96MB -

**SnapGitOwner**
johannesjo

**SnapGitName**
super-productivity

**CrashDB**
snap-github

**InstallationMedia**
Ubuntu 24.04 LTS "Noble Numbat" - Release amd64 (20240424)

**Tags**
noble wayland-session

**InstallationDate**
Installed on 2024-05-10 (3 days ago)

**UpgradeStatus**
No upgrade log present (probably fresh install)

**ProcVersionSignature**
Ubuntu 6.8.0-31.31-generic 6.8.1

**ProcCpuinfoMinimal**
processor	: 7
vendor_id	: GenuineIntel
cpu family	: 6
model		: 140
model name	: 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz
stepping	: 1
microcode	: 0xb6
cpu MHz		: 2045.223
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 3
cpu cores	: 4
apicid		: 7
initial apicid	: 7
fpu		: yes
fpu_exception	: yes
cpuid level	: 27
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l2 cdp_l2 ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves split_lock_detect user_shstk dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req vnmi avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid movdiri movdir64b fsrm avx512_vp2intersect md_clear ibt flush_l1d arch_capabilities
vmx flags	: vnmi preemption_timer posted_intr invvpid ept_x_only ept_ad ept_1gb flexpriority apicv tsc_offset vtpr mtf vapic ept vpid unrestricted_guest vapic_reg vid ple shadow_vmcs pml ept_mode_based_exec tsc_scaling
bugs		: spectre_v1 spectre_v2 spec_store_bypass swapgs eibrs_pbrsb gds bhi
bogomips	: 2995.20
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

**ApportVersion**
2.28.1-0ubuntu3

**CasperMD5CheckResult**
pass

**Comment by anz2k** [comment]
anz@anz-Latitude-5420:~$ superproductivity 
EXITING due to failed single instance lock

(superproductivity:14330): Gtk-WARNING **: 06:51:58.857: Theme parsing error: gtk.css:1413:23: 'font-feature-settings' is not a valid property name

(superproductivity:14330): Gtk-WARNING **: 06:51:58.860: Theme parsing error: gtk.css:3286:25: 'font-feature-settings' is not a valid property name

(superproductivity:14330): Gtk-WARNING **: 06:51:58.861: Theme parsing error: gtk.css:3748:23: 'font-feature-settings' is not a valid property name
libGL error: MESA-LOADER: failed to open iris (search paths /snap/superproductivity/1910/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast (search paths /snap/superproductivity/1910/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: swrast
[14406:0513/065158.956565:ERROR:angle_platform_impl.cc(44)] Display.cpp:1052 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1052 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[14406:0513/065158.956833:ERROR:gl_display.cc(515)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[14406:0513/065158.956890:ERROR:gl_display.cc(786)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[14406:0513/065158.958174:ERROR:angle_platform_impl.cc(44)] Display.cpp:1052 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1052 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[14406:0513/065158.958267:ERROR:gl_display.cc(515)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[14406:0513/065158.958315:ERROR:gl_display.cc(786)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[14406:0513/065158.958349:ERROR:gl_display.cc(820)] Initialization of all EGL display types failed.
[14406:0513/065158.958382:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[14406:0513/065158.961113:ERROR:angle_platform_impl.cc(44)] Display.cpp:1052 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1052 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[14406:0513/065158.961225:ERROR:gl_display.cc(515)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[14406:0513/065158.961251:ERROR:gl_display.cc(786)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[14406:0513/065158.962097:ERROR:angle_platform_impl.cc(44)] Display.cpp:1052 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1052 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[14406:0513/065158.962155:ERROR:gl_display.cc(515)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[14406:0513/065158.962181:ERROR:gl_display.cc(786)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[14406:0513/065158.962207:ERROR:gl_display.cc(820)] Initialization of all EGL display types failed.
[14406:0513/065158.962233:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[14406:0513/065158.966463:ERROR:viz_main_impl.cc(196)] Exiting GPU process due to errors during initialization
anz@anz-Latitude-5420:~$

**Comment by johannesjo** [comment]
Thank you very much for reporting this! Could you maybe provide a bit more info on what happened before the error occured?

**Comment by anz2k** [comment]
This issue can be closed. It was clean install of ubuntu 24.04, added my required applications and superproductivity didnt open. After reboot everything worked and I cant reproduce it anymore.
