### ISSUE TITLE
Issue adding task from Integrated Github project: Error Github Not Found

### ISSUE THREAD

**Issue by JamesZDonline** [johannesjo/super-productivity#3183]
### Your Environment
- Version used: 8.0.1
- Operating System and version: Windows 10 Education 22H2

### Expected Behavior
I have added a GitHub repo to my project. When I add a task (ctrl+shift+T) and start typing, an issue that I want from the GitHub pops up as an option. So far so good! 

Then I click that issue and get a toast message at the bottom that says Github: Not Found. 

Which seems strange, since it evidently found it to show me the option in the first place?

I expect it to add the issue as a task.

### Current Behavior

Gives me a Github not found error.

### Can you reproduce this reliably?

Every time I try

### Console Output

> 16:35:54.143 › Frontend Error: Error: Uncaught (in promise): Object: {"HANDLED_ERROR_PROP":"Github: Http failure response for https://api.github.com/repos/geopacha/dinov2_geopacha/issues/12: 404 OK"}
>     at xt (zone.js:1211:31)
>     at zone.js:1118:17
>     at zone.js:1134:33
>     at f (progress-spinner.mjs:294:7)
>     at U.invoke (zone.js:372:26)
>     at Object.onInvoke (core.mjs:26356:33)
>     at U.invoke (zone.js:371:52)
>     at it.run (zone.js:134:43)
>     at zone.js:1275:36
>     at U.invokeTask (zone.js:406:31) Error: Uncaught (in promise): Object: {"HANDLED_ERROR_PROP":"Github: Http failure response for https://api.github.com/repos/geopacha/dinov2_geopacha/issues/12: 404 OK"}
>     at xt (file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:16156)
>     at file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:15214
>     at file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:15322
>     at f (file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.2271e764c39109d8.js:1:1634474)
>     at U.invoke (file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:6670)
>     at Object.onInvoke (file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.2271e764c39109d8.js:1:4187380)
>     at U.invoke (file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:6609)
>     at it.run (file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:2010)
>     at file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:16980
>     at U.invokeTask (file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:7290)

### Error Log (Desktop only)

> [2024-05-14 16:32:34.381] [error] Frontend Error: Error: Uncaught (in promise): Object: {"HANDLED_ERROR_PROP":"Github: Http failure response for https://api.github.com/repos/geopacha/dinov2_geopacha/issues/12: 404 OK"}
>     at xt (file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:16156)
>     at file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:15214
>     at file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:15322
>     at f (file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.2271e764c39109d8.js:1:1634474)
>     at U.invoke (file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:6670)
>     at Object.onInvoke (file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.2271e764c39109d8.js:1:4187380)
>     at U.invoke (file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:6609)
>     at it.run (file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:2010)
>     at file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:16980
>     at U.invokeTask (file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:7290) Error: Uncaught (in promise): Object: {"HANDLED_ERROR_PROP":"Github: Http failure response for https://api.github.com/repos/geopacha/dinov2_geopacha/issues/12: 404 OK"}
>     at xt (file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:16156)
>     at file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:15214
>     at file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:15322
>     at f (file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.2271e764c39109d8.js:1:1634474)
>     at U.invoke (file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:6670)
>     at Object.onInvoke (file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.2271e764c39109d8.js:1:4187380)
>     at U.invoke (file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:6609)
>     at it.run (file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:2010)
>     at file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:16980
>     at U.invokeTask (file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:7290)
> [2024-05-14 16:32:34.384] [error] Frontend Error Stack: 
> [2024-05-14 16:35:54.143] [error] Frontend Error: Error: Uncaught (in promise): Object: {"HANDLED_ERROR_PROP":"Github: Http failure response for https://api.github.com/repos/geopacha/dinov2_geopacha/issues/12: 404 OK"}
>     at xt (file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:16156)
>     at file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:15214
>     at file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:15322
>     at f (file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.2271e764c39109d8.js:1:1634474)
>     at U.invoke (file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:6670)
>     at Object.onInvoke (file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.2271e764c39109d8.js:1:4187380)
>     at U.invoke (file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:6609)
>     at it.run (file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:2010)
>     at file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:16980
>     at U.invokeTask (file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:7290) Error: Uncaught (in promise): Object: {"HANDLED_ERROR_PROP":"Github: Http failure response for https://api.github.com/repos/geopacha/dinov2_geopacha/issues/12: 404 OK"}
>     at xt (file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:16156)
>     at file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:15214
>     at file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:15322
>     at f (file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.2271e764c39109d8.js:1:1634474)
>     at U.invoke (file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:6670)
>     at Object.onInvoke (file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.2271e764c39109d8.js:1:4187380)
>     at U.invoke (file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:6609)
>     at it.run (file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:2010)
>     at file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:16980
>     at U.invokeTask (file:///C:/Users/zimmejr1/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:7290)
> [2024-05-14 16:35:54.148] [error] Frontend Error Stack:

**Comment by JamesZDonline** [comment]
Added note. I toggled the "Automatically import unresolved issues" and now it periodically tells me that it can't find the repo.

Is it possible this is due to it being a private repo? Or a repo owned by an organization rather than myself?

**Comment by johannesjo** [comment]
Hey hey! Didn't encounter this myself with my private repositories (old school all access token), so my first guess would be that the access token does not have the proper permissions configured? What kind of token do you have configured?

**Comment by dahlmo** [comment]
I just encountered the same error message, but got it working by selecting more of the permissions for my PAT (Personal Access Token). I didn't want to give it _all_ permissions, so I started out assuming what it needed – but turns out it needed more. If there's some easy way of finding out what API calls are made, I could try to help out and expand the docs with what permissions are needed and not.

**Comment by johannesjo** [comment]
That's great to hear! :) There is already some doc:
https://github.com/johannesjo/super-productivity/blob/master/docs%2Fgithub-access-token-instructions.md

But there is room for improvement and I haven't found the time to link it from the app yet, but will try to do so tomorrow.
