### ISSUE TITLE
Alternative timeline visualization

### ISSUE THREAD

**Issue by fmos** [johannesjo/super-productivity#3184]
## Problem Statement

The timeline is unintuitive to grasp due to the nonlinear y-axis. Vertical distance is not proportional to time. 

## :grey_question: Possible Solution

Maybe an additional or alternative circular visualisation would help. 

This could be inspired by https://nautilus-omnibus.web.app/ (I'm not the author and don't know about any legal implications - perhaps they would be happy to see their idea spread). Here is a screenshot:

![grafik](https://github.com/johannesjo/super-productivity/assets/825364/61ff0138-4f29-4839-9ec8-e4b0dfe2a222)

## :arrow_heading_up: Describe alternatives you've considered

The obvious solution would be to render a linear vertical (y) axis on the timeline. However, either long tasks would cover the entire screen or short tasks would be unreadable. On the other hand, maybe that would also have the upside of incentivizing reasonable planning units (not too large blocks and not too much overhead).

## :heavy_plus_sign: Additional context

No aware of any related issues or discussions. The app linked above has further links for background.

**Comment by johannesjo** [comment]
Thanks for this interesting suggestion! I kind of like it, but since the implications of such a change seem huge   in scope and complicated I probably don't like it enough to work on it :)

Leaving this open for discussion, since  I am possibly overlooking some potential.
