### ISSUE TITLE
Enhance Worklog View: Add/Delete Tasks and Edit Time for Any Date

### ISSUE THREAD

**Issue by rokk4** [johannesjo/super-productivity#3187]
**Enhance Worklog View: Add/Delete Tasks and Edit Time for Any Date**

Firstly, thank you for this outstanding software. I have been using it daily for the past year, and it has greatly improved my productivity!

I really hope this is not a duplicate, but I was not able to find a similar issue.

## Problem Statement
While preparing the monthly report, I face challenges with the current functionality of the worklog. The monthly overview is only accessible in the worklog, but I am unable to delete or add tasks directly within this view. Additionally, tasks "without time" occasionally appear, requiring me to manually delete them from the JSON export and reimport (a separate issue).

This process forces me to constantly switch between the worklog overview and the task list to edit or add tasks for previous days, which is quite inefficient.

## :grey_question: Possible Solution
- Allow adding time to tasks for other dates directly within the worklog.
- Enable adding tasks for specific days directly within the worklog.
- Provide the option to delete tasks directly from the worklog.

## :arrow_heading_up: Alternatives Considered
- Allow adding time to tasks for older dates via the create task bar.
- Enable creating tasks with time for past dates via the task bar.

Thank you for considering these enhancements. Implementing them would significantly streamline the reporting process and improve overall usability. Your attention to this matter is greatly appreciated!

**Comment by wolframliermann** [comment]
Hello @johannesjo 

I frequently notice the next day that I forgot to book time entries or tasks – retrospective booking for previous days is currently not possible, which destroys the accuracy of my reports.

This exact feature from the issue would solve it:
- Add/edit tasks/time in the Worklog for any past date (e.g. "Task X yesterday 2h").
- Without direct DB access (JSON editing is risky with sync).

Questions:

1. Why is this feature currently not planned? (No labels/milestones visible – any technical/priority reasons?)
2. Are there workarounds (e.g. CLI/DB tool) or when do you plan to implement it?
3. I'd be happy to create a PR – what direction would you suggest?

Thanks for the great app – this would be a game changer for many workflows!

**Comment by wolframliermann** [comment]
# Worklog: Add, Delete, and Edit Tasks Directly

## Overview

Extension of the worklog to allow adding tasks directly for a specific date, deleting tasks, and editing time spent. This enables faster and more intuitive time tracking after the fact.

## Features

### 1. Add Task for Date

**Access:**
- "Add Task" button in the expanded day view of the worklog

**Dialog Functionality:**
- Input field for task title
- **Short Syntax Support:**
  - `+ProjectName` - Sets the project
  - `#Tagname` - Adds tags
  - `3h` or `1h 30m` - Sets time spent for the date (time spent, not estimate)
- Autocomplete suggestions for:
  - Projects (when typing `+`)
  - Tags (when typing `#`)
  - Existing tasks and issues
- Project selection via button (if not using short syntax)
- Tag selection via button (if not using short syntax)
- Display of selected tags below the input field
- Short syntax remains visible in the input field (not automatically removed)
- When saving, the cleaned text (without short syntax) is used as the title

**Example Input:**
```
+ProjectY #Development 3h Implement new feature
```

**Result:**
- Title: "Implement new feature"
- Project: "ProjectY"
- Tags: "Development"
- Time Spent: 3 hours for the selected date

### 2. Delete Task from Worklog

**Access:**
- Delete button (appears on hover over a task row)
- Confirmation dialog before deletion

**Functionality:**
- Completely deletes the task
- Automatically updates the worklog

### 3. Edit Time for Date

**Already Available:**
- Inline editing of time spent directly in the worklog table
- Works as intended

## UI/UX Details

### "Add Task for Date" Dialog

- **Title:** "Add task for [Date]"
- **Input Field:**
  - Styling identical to the main Add Task Bar
  - Autocomplete panel for suggestions
  - Mention support for projects and tags
- **Actions:**
  - Project button (with icon and name)
  - Tag button (with selected tags)
  - Estimate button (with selected time or is entered via short syntax)
  - Due button is hidden (not relevant for worklog)
- **Tags Display:**
  - Below the input field when tags are selected
  - Shows icons and names of tags
  - New tags (created via short syntax) are marked as "new"
- **Buttons:**
  - "Cancel" - Closes the dialog without changes
  - "Create" - Creates the task with all set values

### Worklog Table

- **Delete Button:**
  - Hidden by default
  - Appears on hover over a task row
  - Positioned in the Actions column before the spend time input field
  - Icon: `delete_outline`

- **Add Task Button:**
  - In the expanded day view
  - Positioned below the task list
  - Icon: `add`

## Technical Details

### Short Syntax Parsing

- Uses the existing `AddTaskBarParserService`
- Time is saved as `timeSpentOnDay` (not `timeEstimate`)
- Time is set for the dialog date (not for today)
- Project and tags are correctly extracted and assigned

### State Management

- Uses `AddTaskBarStateService` for consistent behavior
- State is initialized when opening the dialog
- Default project is set based on current work context

### Data Validation

- Title is required
- Project, tags, and time are optional
- Time is only saved if it's greater than 0

## Benefits

1. **Faster Entry:** Tasks can be created directly in the worklog without switching to the main screen
2. **Intuitive Usage:** Short syntax enables quick entry of all relevant information
3. **Consistency:** Uses the same components and services as the main Add Task Bar
4. **Flexibility:** Supports both short syntax and button-based selection

**Comment by johannesjo** [comment]
This has since been implemented. Thank you!
