### ISSUE TITLE
Unable to Write Name in SubTask or Change Name in Existing Task / Quick Actions do not show up on mouse over

### ISSUE THREAD

**Issue by DevCoDiscoveries** [johannesjo/super-productivity#3188]
### Steps to Reproduce

1. Add a task or subtask.
2. Try to change the name. Does not open text for editing. Only opens up the side menu.
3. Happening on my Android, Windows and Web versions. 

### Meta Info
META: SP8.0.5 Electron – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/8.0.5 Chrome/122.0.6261.156 Electron/29.2.0 Safari/537.36

**Comment by johannesjo** [comment]
Thanks for reporting. I am unable to reproduce this myself. Could you maybe provide a screenshot, to better explain what is hapening?
