### ISSUE TITLE
Gitlab Integration - Personal Access Token permission requirements

### ISSUE THREAD

**Issue by Rohaq** [johannesjo/super-productivity#3190]
As referenced in this thread: https://github.com/johannesjo/super-productivity/discussions/2714#discussioncomment-9490660

There's currently no documentation or guidance in the UI for what the minimum Access Token permissions required are for the Gitlab integration.

It's good security practice to restrict permissions on these access tokens, even for local applications, in order to mitigate any damage that could be done if they were ever leaked.

Could these permissions be determined, and added to documentation? I'd also suggest displaying these in the config UI in a future release.

Screenshot of available permissions on Gitlab.com:
![image](https://github.com/johannesjo/super-productivity/assets/246865/1b103918-dbd4-497d-bc7e-05a1af138928)

**Comment by Rohaq** [comment]
Link to the Gitlab Documentation on Access Token permissions:
https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html#personal-access-token-scopes

**Comment by Rohaq** [comment]
Gitlab also offers project level access tokens too. It's probably worth also including the project roles that the token might need too.

![image](https://github.com/johannesjo/super-productivity/assets/246865/29bf452e-b00d-4462-a596-876efee0e05a)

![image](https://github.com/johannesjo/super-productivity/assets/246865/242b0ada-1ddf-449a-8bef-bd6886a64398)

**Comment by johannesjo** [comment]
Makes sense to provide some documentation about this somewhere. Best place is probably somewhere here on github, so updates are easily accessible to everyone. Maybe `docs/github-access-token-instructions.md` is a good place. 

Help with putting these together would be much appreciated! Any volunteers? :)

**Comment by BanditsBacon** [comment]
@Rohaq The ability to use Project Access Token are limited on GitLab.com.  " On GitLab.com, you can use group access tokens if you have the Premium or Ultimate license tier" A pity. 

@johannesjo i would try to write a documentation. At the Moment i play a little bit with the scopes which are the "best" working.

**Comment by johannesjo** [comment]
Thank you @BanditsBacon !! This would be much appreciated!

**Comment by RokeJulianLockhart** [comment]
. https://github.com/johannesjo/super-productivity/issues/3190#event-15483836899

@Jagdfalke, has this been implemented?

**Comment by BanditsBacon** [comment]
> > [#3190 (comment)](https://github.com/johannesjo/super-productivity/issues/3190#event-15483836899)
> 
> @Jagdfalke, has this been implemented?

@RokeJulianLockhart Yeah it was only Documentation. And the Documentation is done and merged. so it's ok to close this Ticket.
