### ISSUE TITLE
[Bug] Wrong Time Parsing

### ISSUE THREAD

**Issue by StructSeeker** [johannesjo/super-productivity#3192]
![image](https://github.com/johannesjo/super-productivity/assets/136735368/14d455f6-ea03-4c50-ba1a-22a8690ce23a)
Note that my time zone is `+08:00`. And according to wiki:
> If no UTC relation information is given with a time representation, the time is assumed to be in local time.

**Comment by johannesjo** [comment]
We're using https://www.npmjs.com/package/chrono-node .

Best to fix the issue there, I think.
