### ISSUE TITLE
Wrong Task on Focus Mode

### ISSUE THREAD

**Issue by Tim676o** [johannesjo/super-productivity#3194]
### Your Environment

- Version used: Super Productivity 8.0.5
- Operating System and version: Windows 11, 23H2

### Expected Behavior

When I enter focus mode and choose one of my task, it should track time for that specific task.

### Current Behavior

It only tracks time on the first task, the one it showed up in the beginning before I type anything, no matter if I choose another.

### Can you reproduce this reliably?

Issue happens everytime I retry it, even when I close and restart the app.

### Console Output

No specific output

**Comment by johannesjo** [comment]
Should be fixed with the next release :)
