### ISSUE TITLE
Today -> Metrics Simple Counters graphs should show days with no entries

### ISSUE THREAD

**Issue by ryanjkemper** [johannesjo/super-productivity#3197]
## Problem Statement

When viewing the global metrics graphs, I have a simple counter that tracks some simple desk exercises that I like to do during my 5m pomodoro breaks.  Unfortunately, some days I don't get to them at all, and therefore have logged zero (0) ticks to this counter.  In the resulting graph, those days are completely missing from the X-axis, and days where I've logged one (1) count show as a flatline at the bottom of the graph.  See below screenshot:

![image](https://github.com/johannesjo/super-productivity/assets/19542705/6eb80f9f-70e3-42d2-9173-01feb8fb7e31)

## :grey_question: Possible Solution

Set the Y-axis of this graph to 0, and display either all days that I've logged time in SP, or simply all days so that way I can easily see which days I'm slacking on my excercises.

## :arrow_heading_up: Describe alternatives you've considered

I could try harder to be logging at least one exercise per day, although some days (like weekends) when I'm not working, I still wouldn't be logged into this computer and therefore wouldn't be able to see valleys in my desk excercises

## :heavy_plus_sign: Additional context

N/A

**Comment by johannesjo** [comment]
I agree that this could use some improvement. It probably would be good to also have some sort of navigation mechanism (maybe by month??) or way to limit the data displayed to a timespan.
