### ISSUE TITLE
[Feature] Add timer pomadoro 

### ISSUE THREAD

**Issue by GabrielRodriguesS** [johannesjo/super-productivity#32]
It would be very useful to add a methodology for time management. A widely used model is the pomarodo technique, this technique consists of working 20 to 30 minutes and stopping for 5 or 3 minutes, after four cycles a 15 minute break.

You can read more about the technique and its details here:
https://en.wikipedia.org/wiki/Pomodoro_Technique

And an example of a task list system that uses this technique:
https://pomodoro-tracker.com/

**Comment by johannesjo** [comment]
Thanks for taking your time to open up the issue. I will probably implement a feature like this in the near future.

**Comment by GabrielRodriguesS** [comment]
I wanted for it! 😌

**Comment by tloszabno** [comment]
I also wait for that feature. Tip from me: if this possible please make possible to configure time intervals in pomodoro.

**Comment by johannesjo** [comment]
Soooo. The feature is finally there (coming with release 1.7.0). It's quite a big one, so there might be some bugs left. Please let me know, if you like and what you would possibly improve.

I'm also planning a big related update for the gnome shell extension, but I'm not quite there yet.
