### ISSUE TITLE
Data lost when updating to 5.0.6

### ISSUE THREAD

**Issue by absort0** [johannesjo/super-productivity#320]
### Your Environment

* Version used: 5.0.6 snap 
* Operating System and version: Debian 10 Buster Kernel 4.19.98-1
* Desktop Environment: i3-gaps
* Browser Name and version: Desktop version

### Expected Behavior
I've been running __Super-Productivity__ for a few weeks now. Today when I opened it it said that there was a major update and that _"some migrations for your data are required"_. I clicked `ok`  expecting for it to try a migration or something, but the app just opened with any data in it. Is there a way to recover/import my data? At least part of it, I don't mind having to do some manual work either. I've tried importing data json data from `snap/superproductivity/current/.config/superProductivity/backups/`but it opens the same window stating that the migration is needed. 

### Current Behavior
Everything seems to be working fine, except that all data is gone. However is not possible to import backup data or db data.

### Steps to Reproduce (for bugs)
I don't have prior experience with Snap (installed it recently to try super-productivity) and it came as a surprise to me that updates appears to be automatic by default.
1. Update from version 4.x.x to 5.0.6 (automatically done by snap, it seems)
2. Open the app
3. Click the alert window confirming that there was a major update and that data might not be compatible (or something like it)

![2020-04-01_11:17:03_481x118_scrot](https://user-images.githubusercontent.com/43573853/78147804-628b1b00-740a-11ea-877f-bd43f08328c1.png)

ps: thanks for all your effort on the app, it is amazing. Congrats on the update also! :tada:

**Comment by johannesjo** [comment]
Thank you very much for reporting! I was afraid this might happen to someone. Sorry that it happened to you... But I am confident that we can fix it!

First question: Did you try expanding the project menu to the left? I sometimes forgot that after migrating. Maybe everything is still there?

**Comment by absort0** [comment]
Oof, it is all there. I feel very very embarrassed right now :sweat_smile: :1st_place_medal:. Sorry for taking your time.

**Comment by johannesjo** [comment]
No worries. It's not ideal that the first thing which greets you after this scary dialog is an empty list :)
