### ISSUE TITLE
Deleting or finishing tasks with tagged subtasks causes repairable corruption

### ISSUE THREAD

**Issue by AZeed18** [johannesjo/super-productivity#3205]
### Your Environment

- Version used: 8.0.5.0 (Microsoft Store)
- Operating System and version: Windows 10 22H2 (build 19045.4412)

### Expected Behavior

- Check a task where some of its subtasks have tags
- Finish the day
- No data corruption

### Current Behavior

- Check a task whose subtasks (at least one) have tags
- Finish the day
- This message pop up immediately and on every sync
![unable to get valid app data](https://github.com/johannesjo/super-productivity/assets/44865525/3a669a66-0b64-418a-a83f-66345734e897)

### Can you reproduce this reliably?

Yes, it always happens.

### Error Log (Desktop only)

%USERPROFILE%\AppData\Roaming\superProductivity\logs\main.log

No changes in log file

### Solution to Corruption

Get the task out of worklog

**Comment by AZeed18** [comment]
PS: This problem never happened, but now it happens everytime and does **NOT** get fixed by restoring task from backlog anymore

**Comment by johannesjo** [comment]
Thanks for reporting. Does this happen with the most recent version 8.0.7 as well?

**Comment by AZeed18** [comment]
Yes, the data still gets corrupted

**Comment by AZeed18** [comment]
Can you reproduce this?

**Comment by johannesjo** [comment]
> Can you reproduce this?

Yes! Thank you! I work on a fix!

**Comment by johannesjo** [comment]
Will be fixed with the next release (hopefully :))!

**Comment by AZeed18** [comment]
Thanks for trying! The problem still exists in 8.0.9 :(

**Comment by AZeed18** [comment]
It is worth noting that the problem got fixed when I ignored the corruption, made an export, imported it, then click ok here:

![image](https://github.com/johannesjo/super-productivity/assets/44865525/4d8b7fca-6073-42c7-8cf6-55419189791d)

**Comment by johannesjo** [comment]
> Thanks for trying! The problem still exists in 8.0.9 :(

Are you able to reproduce the issue again or is everything fine after applying the data repair?

**Comment by AZeed18** [comment]
So far, the issue is fixed and everything is fine!

I don't know why I needed to corrupt and repair though, maybe because I use another app to sync the sync file with another device

**Comment by johannesjo** [comment]
Then I am closing this! Please let me know, if there are additional problems!

**Comment by AZeed18** [comment]
The problem is not fixed, but I think I figured out what needs to be fixed...

**_Deleting_** tasks with tagged subtasks gives the same error and states that the deleted task ID (assumption) is missing from its tag, which gets fixed by repairing

Probably that's another issue since you fixed the same problem with **_archiving_**

**Comment by johannesjo** [comment]
@AZeed18 can you provide me with the exact steps required for reproducing this? I tried several variations but was unable to cause another error.

**Comment by AZeed18** [comment]
Just delete a task which has a tagged subtask or more:

![image](https://github.com/johannesjo/super-productivity/assets/44865525/d47252e0-1dde-46b9-b71b-b3e448629a27)

It is worth mentioning that going to the corrupted tag shows this fatal error:

![image](https://github.com/johannesjo/super-productivity/assets/44865525/1024bfc9-1af9-4be7-9d3b-ec56944c03f1)

**Comment by johannesjo** [comment]
Thank you very much once more! Hopefully was able to fix this! :) The fix will be included in the next release.

**Comment by AZeed18** [comment]
You're welcome! I will let you know if there are any issues.
