### ISSUE TITLE
Start application minimized to tray

### ISSUE THREAD

**Issue by Ataky-0** [johannesjo/super-productivity#3207]
## Problem Statement

I've recently found out there's no way of opening the application without the window popping up, to which i find essential for now, there has been already a issue related to this problem (#1865) which was eventually closed.

## ❔ Possible Solution

A flag ```--tray``` or a toggleable option inside _**Misc Settings**_ :)

**Comment by Ataky-0** [comment]
That's my first Issue ever, sorry if it's not allowed to revive closed issues this way..

**Comment by Jagdfalke** [comment]
Related #3103

**Comment by jm4R** [comment]
TIP: Clicking on tray icon when the app is not minimized should minimize it also. I want to be able to "take a quick look" by double click with that feature. Thanks!

**Comment by sagyas** [comment]
Hi @johannesjo, I added `isMinimizeToTrayOnStartup` property to configuration,
I think the best place to handle this property is on `main-window.ts` inside:
```
 mainWin.once('ready-to-show', () => { })
```
but calling `getSettings` doesn't get the correct settings.
So I saw the use of `GlobalConfigService` all over, however it's done via DI whereas `main-window.ts` is not a component therefore impossible.
Any suggestion so I can move forward with that?

**Comment by johannesjo** [comment]
> Any suggestion so I can move forward with that?

It's a bit complicated. Super Productivity's data is saved within the web context and not the electron context and getSettings(), which is used to get them from the electron layer, is only available once the app has been fully started. I see 2 options: 
1. We use the setting to trigger the minimize from the web layer once the app is fully loaded. We would need to add a new function to the `electronAPI.d.ts` and `preload.ts`
2. We save the setting for it at an additional place that electron can access on startup e.g. we write on the disk somewhere. This also would require some communication between the web and the electron layer via the bridge.

**Comment by Rishukumar-in** [comment]
still relevant

**Comment by anarchy1923** [comment]
Relevant for Snap and Flatpak - Ubuntu 22.04 LTS
