### ISSUE TITLE
App crash when I'am trying to create new task

### ISSUE THREAD

**Issue by alenIncorC** [johannesjo/super-productivity#321]
### Your Environment

* Version used: 
* Operating System and version:
* Desktop Environment: 
* Browser Name and version: 

### Steps to Reproduce (for bugs)

1. Add new task
2. Start typing upper lower case letters

**Comment by johannesjo** [comment]
Hey! Thanks for reporting! Could you provide a little bit more context? What is your current selected list? Are you using any of the issue providers (github, jira, gitlab)? What tasks did you have in your list? Does relóading the app help or does this happen every single time?

**Comment by johannesjo** [comment]
I am assuming this is fixed with the newest release. Could you please  confirm this?
