### ISSUE TITLE
Add "Today Remaining" in the projects view

### ISSUE THREAD

**Issue by chenw191** [johannesjo/super-productivity#3221]
I am organizing my work for the day using "Add to My Day" and "Remove from My Day," but I cannot directly see the time these tasks will take. I need to switch to the "Today View" to see this information. Could you add a "Today Remaining" section in the projects view? This way, I won't need to switch back and forth between the projects view and the today view.
![image](https://github.com/johannesjo/super-productivity/assets/12569902/6f5b0805-d743-4efa-80d3-f9690a123180)

Thank you very much for considering this feature request. I really appreciate your hard work and dedication to improving the tool!

**Comment by johannesjo** [comment]
That's a cool suggestion! Would you show the total of today or just for the single project? I'd prefer the latter I think.

**Comment by stavby** [comment]
@johannesjo I see @shafiahmed12 's PR on this issue was merged, so you can close the issue :)
