### ISSUE TITLE
Autocomplete Dropdown for Tag Selection When Adding New Task

### ISSUE THREAD

**Issue by bytrangle** [johannesjo/super-productivity#3224]
### Discussed in https://github.com/johannesjo/super-productivity/discussions/3041

<div type='discussions-op-text'>

<sup>Originally posted by **bytrangle** February 19, 2024</sup>
New versions of SP ask for confirmation of tag insertion. I suppose this is to take care of people who want to add the literal hashtag `#` and have no intention of adding tags to their tasks.

However, this could inadvertently add more steps to people who add a batch of tasks with tags 😅. How about opening a dropdown of existing tags when users type `#`. Then they can select the tag they want with arrow keys and Enter/mouse click.

https://github.com/johannesjo/super-productivity/assets/28924121/d59f9951-d3d1-47b1-84d7-57a91bbaa222

When user clicks outside the dropdown, that is seen a signal to use the literal hashtag.

https://github.com/johannesjo/super-productivity/assets/28924121/2fab0164-2d6a-4a05-aef4-03fae5c0e4e7

Of course, when back to the task add bar, SP will continue to parse the hashtag and interpret it as short syntax for adding tag, but we can stop it. If the user types another hashtag, that's a sign to add tag again. </div>

**Comment by johannesjo** [comment]
Thank you very much! That looks very cool!! There are some conflicts with the main branch since I recently did some huge changes to migrate to new versions of angular etc.. so sorry for that! :D If you want I can also take care of it.

**Comment by bytrangle** [comment]
Yes please and thank you very much 🙏. I don't envy anyone resolving Angular dependencies.

**Comment by johannesjo** [comment]
Alright! Will be on vacation next week, but I will do it the week after.
