### ISSUE TITLE
Google security misidentifies app as Windows Chrome

### ISSUE THREAD

**Issue by rotu** [johannesjo/super-productivity#324]
### Your Environment
* Version used: 5.0.7
* Operating System and version: Ubuntu Focal and macOS Catalina
* Desktop Environment: LightDM

### Expected Behavior
When I enable syncing via Google Drive, I receive a Google Security Alert identifying the client. 

### Current Behavior
The security alert misidentifies the client as Chrome on Windows (see screenshot) even when the program is running on Ubuntu or macOS.

![image](https://user-images.githubusercontent.com/119948/78375969-4070d480-7593-11ea-897b-3ac7e07833e4.png)

**Comment by johannesjo** [comment]
Thank you very much for letting us know.

**Comment by johannesjo** [comment]
I am closing this since it is not affecting the app in any negative way. If somebody knows a solution, please let me know.
