### ISSUE TITLE
A new task is created assigned to NO project at all.

### ISSUE THREAD

**Issue by generic-user** [johannesjo/super-productivity#325]
## Thanks
First, thanks for all the hard work, I really like the project. Keep up the good work. 🎉 🥇 

## The issue at hand
_Your issue may already be reported! Please search the issues before creating one._

--> Searched for [break timer; idle timer;  task not assign to a project], could not find an existing issue.
### My Environment

* Version used:  5.0.7
* Operating System and version: Win 10

### Expected Behavior

When idle time is detected, and you create a new task in the provided screen by clicking the break + task button. A new task is created assigned to the current project.

### Current Behavior

When idle time is detected, and you create a new task in the provided screen by clicking the break + task button. A new task is created assigned to __NO__ project at all.

#### Thoughts
When constructing a task, and no project is assigned an Exception should be thrown. As to my understanding there should never be a task which has not been assigned to a project.

### Steps to Reproduce (for bugs)

0. Make sure to start from the today view and start tracking a task.
1. Go Idle until screen pops up (to make this faster set idle timer to 1minute)
2. When on the idle screen create a new task and press task + break button
3. Now that new task is created, but it is not assigned to a project.
4. If you now click _remove task from day_, there is no way of finding the task.
5. If you the export the database to JSON, the task still exists, but the value of the task's projectId was not set.

#### JSON
In the JSON I copied and pasted from the export we can see a task has been created which was not assigned any project.

```JSON
"iskariN-f": {
                "id": "iskariN-f",
                "projectId": null, <-- HERE NULL -->
                "subTaskIds": [],
                "timeSpentOnDay": {
                    "2020-04-04": 41591944
                },
                "timeSpent": 41591944,
                "timeEstimate": 0,
                "isDone": false,
                "title": "TASK01",
                "notes": "",
                "tagIds": [],
                "parentId": null,
                "reminderId": null,
                "created": 1585985444042,
                "repeatCfgId": null,
                "_showSubTasksMode": 2,
                "attachments": [],
                "issueId": null,
                "issuePoints": null,
                "issueType": null,
                "issueAttachmentNr": null,
                "issueLastUpdated": null,
                "issueWasUpdated": null
            }
        }
```

### Console Output

No relevant console output was generated.

### Error Log (Desktop only)
[log.001.log](https://github.com/johannesjo/super-productivity/files/4430938/log.001.log)

**Comment by johannesjo** [comment]
Thank you very much for reporting. I have thought about the problem before, but as there are so many things to do, I decided to deal with it later. 

The intention in allowing tasks without a project, was to allow to quickly add tasks when you're on todays list or any other tag. 

The first (technical minded) solution which came to my mind was to add a project called "Without Project" or "Unsorted" or something similar. This might not be ideal neither as it unnecessarily throws more stuff to digest at new users. 

What do you think would be the ideal way to handle this?

**Comment by generic-user** [comment]
## What do I think?

Of course the problem could be solved taking multiple directions. I would think to implement something that would take a bare minimum of work.

The problem happens when we **click the remove from today** button.

![image](https://user-images.githubusercontent.com/1516035/78535779-069b0a80-77ed-11ea-88fd-9db365945330.png)

### Prevent the issue to start with

The easiest way to fix this is to disable the remove from my day button when a task has no project assigned to is. That way the task can't be thrown into oblivion. It is good solution, and requires a minimum of time/effort. It is a hard limitation though.

### When falling into the abyss

A second way to fix this is to enforce the user to select a project when the task is about to get removed from the today screen. This happens when we click the remove from today button.

When the user clicks the button, check if the task has a project assigned. If not, present the user with a list of project's to choose from. That way no tasks will get lost. The impact on the complexity of the project is light. Time needed to develop and support the new feature is small.

Anyway, I think u get the gist.

Thanks for your time, take care!

**Comment by johannesjo** [comment]
That makes a lot of sense! I will just remove the button for tasks without a project. Thank you very much!

**Comment by aksdb** [comment]
> The intention in allowing tasks without a project, was to allow to quickly add tasks when you're on todays list or any other tag.

Actually in this case I also miss the project (pre)selection. If I'm in a normal workday, nearly everything I do is for the same project. So when a new task pops up (support ticket, request of a colleague, whatever) I quickly click "+" to add the task and start with it. But it takes three more clicks to have it assigned to the project.

Two ideas from my side:
* Mark a project as "default". Everything you create will be created within that project then.
* Use something like "@<projectname" or "#<projectname>" when starting to type the task to assign it to that project. That way I can at least do it via keyboard :-) (and autocomplete should help as a shortcut)

**Comment by johannesjo** [comment]
@aksdb I agree. Working more and more with the new tag feature I also miss that quite a bit. Both ideas make a lot of sense though the second one will be very tricky to implement, but I try to implement the first suggestion as soon as I can.

In the meantime I added a shortcut for opening the menu to reassign to a project. You can also select a project in the list. This way all new tasks will be created under that project.

**Comment by johannesjo** [comment]
It's now possible to specify a default project under misc settings. The change will be available in the next release. Thank you @generic-user  and @aksdb  for your input.

I will revisit the adjustments to the add task bar and the short syntax at later point of time (I also want to add the same for tags), so I am closing this issue. But please** let me know if you encounter any issues with the new functionality.
