### ISSUE TITLE
Error multiple instances 

### ISSUE THREAD

**Issue by Fuhlano** [johannesjo/super-productivity#3253]
### Steps to Reproduce

1. Open the application 
2. Error!
3. Reinstall application 
4. Open the application 
5. Error again!

![Screenshot_20240708_200627_Super Productivity](https://github.com/johannesjo/super-productivity/assets/84086930/b9ab56ad-7c96-4b4d-a1a7-ec99d7a57d95)
![Screenshot_20240708_200621_Super Productivity](https://github.com/johannesjo/super-productivity/assets/84086930/61da84c7-7b3c-4fc0-92c7-0dbbbbc4ad63)

### Meta Info
META: SP8.0.10 Browser – en-US – Linux aarch64 – Mozilla/5.0 (Linux Android 5.0 SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Mobile Safari/537.36

**Comment by johannesjo** [comment]
Thanks for reporting! You are on android, right? I am aware of this issue and it will be fixed with v9

**Comment by Fuhlano** [comment]
Yes, it's Android. Thanks for the great job

**Comment by Starframe** [comment]
Was having the same issue and came here to report, found @johannesjo is already on it. Thank you for the speedy fix ;)
For anyone that has this issue and needs to use SuperProductivity until it is fixed, I found the following workaround:
1. Open SuperProductivity App.
2. Close Super Productivity app from phone's open apps view/ task manager.
3. Open Super Productivity App again.
The app will now work correctly until you fully close it once more or restart your device.

**Comment by Fuhlano** [comment]
Thanks @Starframe
