### ISSUE TITLE
App doesn't start after installation (snap)

### ISSUE THREAD

**Issue by herman-yulau** [johannesjo/super-productivity#326]
### Environment
* Version: 5.0.7 - 5.0.8;
* Operating System and version: Ubuntu 18.04;
* Desktop Environment: Gnome.

### Current Behavior
New fresh system Ubuntu 18.04. I just reinstalled whole my system on new SSD disk. Before I used that app in Ubuntu 18.04 as well and had no problems. 
Just installed app from edge channel 5.0.8 version and it didn't start. Okay, run `sudo snap remove --purge superproductivity` and installed stable version as `sudo snap install superproductivity`, but result was the same... I uninstalled it again and installed from 'Ubuntu software' app - nothing changed.
 Am I missing some dependencies?
Please, help! I need tracking! :)

### Steps to Reproduce
1. Fresh Ubuntu 18.04.
2. `sudo snap install superproductivity`
3. `superproductivity` from command line...
4. App doesn't start and there is no hanging in command line, a new line appears immediately. So it looks like app starts and exits, or crashes :) 

### Console Output
There are no console output or any logs files in dirs:
~/.config/superProductivity/log.log
~/snap/superproductivity/current/.config/superProductivity/log.log

**Comment by johannesjo** [comment]
Hey there! Thanks for reporting (and using the edge channel, which is I appreciate a lot :)). On my machine I have no issues, but I will test it on a virtual machine.

**Comment by johannesjo** [comment]
All works there as well. Another thing you can do is to try to starting the app from the command line. That should at least provide you with some output...

**Comment by herman-yulau** [comment]
> All works there as well. Another thing you can do is to try to starting the app from the command line. That should at least provide you with some output...

I've edited my original report (see p. 4). There is no information in the command line... =(
I also rebooted my system and nothing...

**Comment by johannesjo** [comment]
> Is there any required additional packages?

Not that I am aware of.

Are you able to start other apps installed via snap? 

That there is no output at all is strange.
What's the output of:
```
which superproductivity
```
and what's inside that path printed out (if any?). Does it look like a proper binary?

**Comment by herman-yulau** [comment]
> What's the output of:
> 
> ```
> which superproductivity
> ```
The output is:
`/snap/bin/superproductivity`.

```
/snap/bin$ ls -laF
total 8
drwxr-xr-x  2 root root 4096 Apr  4 16:10 ./
drwxr-xr-x 17 root root 4096 Apr  4 16:10 ../
lrwxrwxrwx  1 root root   13 Mar 28 19:51 canonical-livepatch -> /usr/bin/snap*
lrwxrwxrwx  1 root root   13 Mar 31 21:04 code -> /usr/bin/snap*
lrwxrwxrwx  1 root root   13 Mar 31 21:04 code.url-handler -> /usr/bin/snap*
lrwxrwxrwx  1 root root   13 Mar 30 11:04 gimp -> /usr/bin/snap*
lrwxrwxrwx  1 root root   13 Mar 29 19:52 gnome-calculator -> /usr/bin/snap*
lrwxrwxrwx  1 root root   13 Mar 29 19:52 gnome-characters -> /usr/bin/snap*
lrwxrwxrwx  1 root root   13 Mar 29 19:52 gnome-logs -> /usr/bin/snap*
lrwxrwxrwx  1 root root   13 Mar 29 19:52 gnome-system-monitor -> /usr/bin/snap*
lrwxrwxrwx  1 root root   13 Mar 30 10:44 skype -> /usr/bin/snap*
lrwxrwxrwx  1 root root   13 Apr  4 16:10 superproductivity -> /usr/bin/snap*
lrwxrwxrwx  1 root root   13 Mar 31 16:45 telegram-desktop -> /usr/bin/snap*
```
Yes, skype, telegram and others work fine.

**Comment by herman-yulau** [comment]
I'm able to run binary from path:
`/snap/superproductivity/567/superproductivity`.

And it works just fine!
But from the direct command in the command line and from apps menu it doesn't start.

**Comment by johannesjo** [comment]
What about the other snap apps located in the bin folder? Are you able to start them just fine?

**Comment by herman-yulau** [comment]
Yes, other apps start with no problems. Trying to figure out where this broken piece hides.
I did not upgrade my system. I installed new system on the new SSD.

**Comment by herman-yulau** [comment]
I haven't managed to fix this problem with snap. I am not familiar with snap very much and I've already spent enough time on it, so I uninstalled app and installed it again from .deb package downloaded from release page. And now it works fine. So the issue can be closed, if it is just my system problem. And thanks for quick help with this problem! And big thanks for this great app!

**Comment by johannesjo** [comment]
Alright then I close the issue.

**Comment by jessexoc** [comment]
I am seeing a very similar issue.

```
$ snap --version
snap    2.44.1
snapd   2.44.1
series  16
ubuntu  19.10
kernel  5.3.0-42-generic
```

```
$ which superproductivity
/snap/bin/superproductivity
```

No issue with other snap apps in `/snap/bin/`

I installed the current candidate version (5.0.11)

On first run after a fresh install, app opens.
After closing, on all subsequent runs, the app crashes on startup.

Running `superproductivity` crashes.
Running `/snap/superproductivity/current/superproductivity` directly works.

Let me know what other debugging steps would be helpful.

**Comment by johannesjo** [comment]
@jessexoc thanks for the additional info. I just tried to reproduce the issue in a fresh Ubuntu VM. No luck. 

Maybe you could provide your desktop environment? Also the logs when starting from the command line would be helpful. And maybe the info provided by `journalctl -f `while reproducing the issue could also help.

**Comment by jessexoc** [comment]
> Maybe you could provide your desktop environment?

Stock Ubuntu install.
DE: GNOME 3.34.1
WM: GNOME Shell

No logs to syslog / journalctl output when starting/crashing.

I thought strace might be helpful. So using strace on the snap install (using https://forum.snapcraft.io/t/stracing-snap-commands/1433)

```
$ sudo strace -u <username> -e '!select,pselect6,_newselect,clock_gettime,sigaltstack,gettid,gettimeofday,nanosleep' -f -D -vv -o ./output.trace /snap/bin/superproductivity
```

It looks like the crash happens from an illegal seek.

strace output (redacted username / file names)

```
28592 lstat("/home/<username>/Documents/<file1>.xlsx", {st_dev=makedev(0xfd, 0x1), st_ino=28445620, st_mode=S_IFREG|0644, st_nlink=1, st_uid=1000, st_gid=1000, st_blksize=4096, st_blocks=32, st_size=14173, st_atime=1580267850 /* 2020-01-29T14:17:30.127395888+1100 */, st_atime_nsec=127395888, st_mtime=1580267849 /* 2020-01-29T14:17:29.239394380+1100 */, st_mtime_nsec=239394380, st_ctime=1580267850 /* 2020-01-29T14:17:30.087395819+1100 */, st_ctime_nsec=87395819}) = 0
28592 lstat("/home/<username>/Documents/<file1>.xlsx", {st_dev=makedev(0xfd, 0x1), st_ino=28445620, st_mode=S_IFREG|0644, st_nlink=1, st_uid=1000, st_gid=1000, st_blksize=4096, st_blocks=32, st_size=14173, st_atime=1580267850 /* 2020-01-29T14:17:30.127395888+1100 */, st_atime_nsec=127395888, st_mtime=1580267849 /* 2020-01-29T14:17:29.239394380+1100 */, st_mtime_nsec=239394380, st_ctime=1580267850 /* 2020-01-29T14:17:30.087395819+1100 */, st_ctime_nsec=87395819}) = 0
28592 write(2, "mv: ", 4)               = 4
28592 write(2, "'/home/<username>/Documents/<file1>"..., 121) = 121
28592 write(2, "\n", 1)                 = 1
28592 lstat("/home/<username>/Documents/<file2>.ods", {st_dev=makedev(0xfd, 0x1), st_ino=28323169, st_mode=S_IFREG|0664, st_nlink=1, st_uid=1000, st_gid=1000, st_blksize=4096, st_blocks=56, st_size=24012, st_atime=1565672859 /* 2019-08-13T15:07:39.487180252+1000 */, st_atime_nsec=487180252, st_mtime=1551765751 /* 2019-03-05T17:02:31+1100 */, st_mtime_nsec=0, st_ctime=1558315771 /* 2019-05-20T11:29:31.103632085+1000 */, st_ctime_nsec=103632085}) = 0
28592 lstat("/home/<username>/Documents/<file2>.ods", {st_dev=makedev(0xfd, 0x1), st_ino=28323169, st_mode=S_IFREG|0664, st_nlink=1, st_uid=1000, st_gid=1000, st_blksize=4096, st_blocks=56, st_size=24012, st_atime=1565672859 /* 2019-08-13T15:07:39.487180252+1000 */, st_atime_nsec=487180252, st_mtime=1551765751 /* 2019-03-05T17:02:31+1100 */, st_mtime_nsec=0, st_ctime=1558315771 /* 2019-05-20T11:29:31.103632085+1000 */, st_ctime_nsec=103632085}) = 0
28592 write(2, "mv: ", 4)               = 4
28592 write(2, "'/home/<username>/Documents/<file2>"..., 103) = 103
28592 write(2, "\n", 1)                 = 1
28592 lseek(0, 0, SEEK_CUR)             = -1 ESPIPE (Illegal seek)
28592 close(0)                          = 0
28592 close(1)                          = 0
28592 close(2)                          = 0
28592 exit_group(1)                     = ?
28592 +++ exited with 1 +++
28512 <... wait4 resumed> [{WIFEXITED(s) && WEXITSTATUS(s) == 1}], 0, NULL) = 28592
28512 rt_sigaction(SIGINT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f2d2e3e4f20}, {sa_handler=0x55c5b607f160, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f2d2e3e4f20}, 8) = 0
28512 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
28512 --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=28592, si_uid=1000, si_status=1, si_utime=0, si_stime=1} ---
28512 wait4(-1, 0x7ffee9ddbc50, WNOHANG, NULL) = -1 ECHILD (No child processes)
28512 rt_sigreturn({mask=[]})           = 0
28512 rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
28512 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
28512 exit_group(1)                     = ?
28512 +++ exited with 1 +++
```

I don't know if that's helpful or not.

**Comment by johannesjo** [comment]
@jessexoc thank you. I did some googleling and my first conclusion was that this is some kind of permission error (as [lseek seems to be responsible for accessing files](http://man7.org/linux/man-pages/man2/lseek.2.html), when the app writes to the file system, but this shouldn't happen until it has launched as far as I know at least. 

There also was a bug with the snap some time ago for systems using wayland, but it's supposed to be fixed for some time...

 I'll give updating electron and electron-builder a shot. There was a (seemingly unrelated) snap bug recently. Hopefully that does something for us....

**Comment by herman-yulau** [comment]
Hi!
Here is a little update from me.
Installed new clean Ubuntu 20.04.
Installed app from 'Ubuntu Software' center from stable channel and right after installation it started just fine!
Closed app, rebooted system by `reboot` cmd in terminal.
And now app doesn't start...

**Comment by johannesjo** [comment]
@herman-yulau thank you. And there is no error output? That's super weird.

The update I made should be available in the edge channel now, but not yet in the published store version btw.

**Comment by herman-yulau** [comment]
Nope. No errors, no any output at all, no log files.

But I removed app with `sudo snap remove --purge  superproductivity` and installed it again, but from edge channel with:
```
sudo snap install --edge  superproductivity
superproductivity (edge) 5.0.13 from johannesjo installed
```
I launched app from command line and it started with output:
```
superproductivity
Saving backups to /home/herman/snap/superproductivity/594/.config/superProductivity/backups
{ enabled: null, showDevTools: false, mode: 'bottom' }
(node:9456) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:9456) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
```
Then I closed app by mouse clicking on the window cross. Started it again from terminal and nothing: no start, no output, no errors.
The only logs files I've found are:
~/snap/superproductivity/594/.config/superProductivity/Local Storage/leveldb/000003.log
~/snap/superproductivity/594/.config/superProductivity/IndexedDB/file__0.indexeddb.leveldb/000003.log
~/snap/superproductivity/594/.config/superProductivity/Session Storage/000003.log

Are you interested in them?

**Comment by johannesjo** [comment]
@herman-yulau no thank you. I will try to reproduce this once more, but this time with a completely fresh VM instance of vanilla Ubuntu 20.04.

**Comment by johannesjo** [comment]
No luck to reproduce it with a fresh VM neither. It works absolutely fine when installing it from the software center even after several restarts. I have absolutely no idea what could cause this :-(

**Comment by vsanchez** [comment]
Hi, the issue reported by @herman-yulau is still happening. I am in Kubuntu 23.10 running Wayland. When one installs the first time, it starts once correctly. There after it wont, without giving any answers... However, running the executable directly works. I.e. running /snap/bin/superproductivity wont start. However, running /snap/superproductivity/current/superproductivity works. 

Other programs in /snap/bin work (firefox) but others  (that look to be electron based, have the same problem). 

So it seems Electron related...

**Comment by Lameorc** [comment]
Hi, I wanted to try out the app and possibly (?) hit the same issue. I did get the app running eventually but I'm not sure what was the root cause, but maybe some of it will be of help... So here's what I did.

1. Installed from stable channel using snap
2. Launched using desktop entry, nothing poped-up.
3. Tried launching through shell with `superproductivity` got `EXITING due to failed single instance lock`
4. Checked htop, the app was there but I didn't find a way to display it.
5. Uninstalled. Reinstalled from stable
6. Ran using CLI, got JS exception about SingletonCookie not being found (sorry, I don't have the output anymore :()
   - old path got reported as present
   - new path got reported as missing (false)
7. Deleted the path which was mentioned as "culprit" I guess? This was `rm -rf ~/snap/superproductivity/current/.config/superProductivity/` for me.
8. App launched fine at this point.

Hopefully this is of some help, and sorry once again about the sub-par reproduction steps.

**Comment by mkungla** [comment]
Seems that it still happening. I am facing a same issue. Fixed by just removing config dir. (actually im not sure did i ever install it in this machine before or not, maybe `isExistsOldPath true` is set incorrectly some case, but not sure)

```
snap    2.61.1-0.fc39
snapd   2.61.1-0.fc39
series  16
fedora  39
kernel  6.6.13-200.fc39.x86_6
```

1. install 

```
sudo dnf install superproductivity
```
> superproductivity 7.17.2 from johannesjo installed

2. starting from gnome desktop failed

3. started from cli

```
which superproductivity
```
> /var/lib/snapd/snap/bin/superproductivity
`superproductivity`
> EXITING due to failed single instance lock
> Gtk-Message: 22:16:02.553: Failed to load module "pk-gtk-module"
> Gtk-Message: 22:16:02.555: Failed to load module "pk-gtk-module"
> /usr/share/libdrm/amdgpu.ids: No such file or directory



4. starting with full path app it starts with following output

 `/snap/superproductivity/current/superproductivity`
> Start app...
> › { enabled: null, showDevTools: false, mode: 'bottom' }
> MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete
> Saving backups to /home/mkungla/.config/superProductivity/backups
> Saving backups to /home/mkungla/.config/superProductivity/backups
> No custom styles detected at /home/mkungla/.config/superProductivity/styles.css
[440207:0201/221804.528909:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[440207:0201/221804.534261:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[440207:0201/221804.543714:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
> close, isQuiting: null
> Actions to wait for  [ 'FINISH_DAY_BEFORE_CLOSE_EFFECT' ]
> BEFORE_CLOSE_DONE FINISH_DAY_BEFORE_CLOSE_EFFECT []
> close, isQuiting: null
> close, isQuiting: true
> Quit after all windows being closed

*combined system logs*

```
systemd[4408]: Started app-gnome-superproductivity_superproductivity-439435.scope - Application launched by gnome-shell.
systemd[4408]: Started snap.superproductivity.superproductivity-137284cf-49c2-4d81-945a-65cf84a09458.scope.
audit[439489]: SECCOMP auid=1000 uid=1000 gid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=439489 comm="superproductivi" exe="/snap/superproductivity/1830/superproductivity" sig=0 arch=c000003e syscall=330 compat=0 ip=0x7f4391ae74e7 code=0x50000
audit[439488]: SECCOMP auid=1000 uid=1000 gid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=439488 comm="superproductivi" exe="/snap/superproductivity/1830/superproductivity" sig=0 arch=c000003e syscall=330 compat=0 ip=0x7ff04660e4e7 code=0x50000
superproductivity_superproductivity.desktop[439435]: EXITING due to failed single instance lock
superproductivity_superproductivity.desktop[439514]: /usr/share/libdrm/amdgpu.ids: No such file or directory
audit[439514]: SECCOMP auid=1000 uid=1000 gid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=439514 comm="superproductivi" exe="/snap/superproductivity/1830/superproductivity" sig=0 arch=c000003e syscall=203 compat=0 ip=0x7ff04b67ec7f code=0x50000
last line repeated 30 times
polkitd[2541]: Operator of unix-session:2 FAILED to authenticate to gain authorization for action io.snapcraft.snapd.manage for unix-process:436463:7036735 [snap install superproductivity] (owned by unix-user:mkungla)
sudo[436513]:  mkungla : TTY=pts/8 ; PWD=/home/mkungla ; USER=root ; COMMAND=/usr/bin/snap install superproductivity
snapd[436367]: api_snaps.go:424: Installing snap "superproductivity" revision unset
systemd[1]: Mounting var-lib-snapd-snap-superproductivity-1830.mount - Mount unit for superproductivity, revision 1830...
systemd[1]: Mounted var-lib-snapd-snap-superproductivity-1830.mount - Mount unit for superproductivity, revision 1830.
systemd[4408]: Started app-gnome-superproductivity_superproductivity-438878.scope - Application launched by gnome-shell.
systemd[4408]: Started snap.superproductivity.superproductivity-bb730160-d0bd-40f9-9bc3-6dcd6e15bdbd.scope.
audit[439046]: SECCOMP auid=1000 uid=1000 gid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=439046 comm="superproductivi" exe="/snap/superproductivity/1830/superproductivity" sig=0 arch=c000003e syscall=330 compat=0 ip=0x7fe79ea6b4e7 code=0x50000
audit[439047]: SECCOMP auid=1000 uid=1000 gid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=439047 comm="superproductivi" exe="/snap/superproductivity/1830/superproductivity" sig=0 arch=c000003e syscall=330 compat=0 ip=0x7f0254c104e7 code=0x50000
superproductivity_superproductivity.desktop[438878]: Start app...
superproductivity_superproductivity.desktop[438878]: -------------------------------------------------------------
superproductivity_superproductivity.desktop[438878]: Detected legacy snap user data. Copying it over to common...
superproductivity_superproductivity.desktop[438878]: -------------------------------------------------------------
superproductivity_superproductivity.desktop[438878]: oldPath /home/mkungla/snap/superproductivity/current/.config/superProductivity
superproductivity_superproductivity.desktop[438878]: newPath /home/mkungla/snap/superproductivity/common/.config/superProductivity
superproductivity_superproductivity.desktop[438878]: isExistsOldPath true
superproductivity_superproductivity.desktop[438878]: isExistsNewPath false
superproductivity_superproductivity.desktop[438878]: A JavaScript error occurred in the main process
superproductivity_superproductivity.desktop[438878]: Uncaught Exception:
superproductivity_superproductivity.desktop[438878]: Error: ENOENT: no such file or directory, stat '/home/mkungla/snap/superproductivity/current/.config/superProductivity/SingletonCookie'
superproductivity_superproductivity.desktop[438878]:     at statSync (node:fs:1690:3)
superproductivity_superproductivity.desktop[438878]:     at t.statSync (node:electron/js2c/asar_bundle:2:5064)
superproductivity_superproductivity.desktop[438878]:     at /snap/superproductivity/1830/resources/app.asar/electron/start-app.js:97:50
superproductivity_superproductivity.desktop[438878]:     at Array.forEach (<anonymous>)
superproductivity_superproductivity.desktop[438878]:     at copyDir_1 (/snap/superproductivity/1830/resources/app.asar/electron/start-app.js:94:22)
superproductivity_superproductivity.desktop[438878]:     at startApp (/snap/superproductivity/1830/resources/app.asar/electron/start-app.js:109:13)
superproductivity_superproductivity.desktop[438878]:     at Object.<anonymous> (/snap/superproductivity/1830/resources/app.asar/electron/main.js:17:34)
superproductivity_superproductivity.desktop[438878]:     at Module._compile (node:internal/modules/cjs/loader:1271:14)
superproductivity_superproductivity.desktop[438878]:     at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
superproductivity_superproductivity.desktop[438878]:     at Module.load (node:internal/modules/cjs/loader:1126:32)
superproductivity_superproductivity.desktop[439074]: /usr/share/libdrm/amdgpu.ids: No such file or directory
audit[439074]: SECCOMP auid=1000 uid=1000 gid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=439074 comm="superproductivi" exe="/snap/superproductivity/1830/superproductivity" sig=0 arch=c000003e syscall=203 compat=0 ip=0x7fe7a3adbc7f code=0x50000
last line repeated 30 times
superproductivity_superproductivity.desktop[439074]: Warning: vkCreateInstance: Found no drivers!
superproductivity_superproductivity.desktop[439074]: Warning: vkCreateInstance failed with VK_ERROR_INCOMPATIBLE_DRIVER
superproductivity_superproductivity.desktop[439074]:     at CheckVkSuccessImpl (../../third_party/dawn/src/dawn/native/vulkan/VulkanError.cpp:101)
superproductivity_superproductivity.desktop[439074]:     at CreateVkInstance (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:493)
superproductivity_superproductivity.desktop[439074]:     at Initialize (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:379)
superproductivity_superproductivity.desktop[439074]:     at Create (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:301)
superproductivity_superproductivity.desktop[439074]:     at operator() (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:556)
systemd[4408]: Started snap.superproductivity.superproductivity-4946792b-d53d-4521-af6b-3256088788f2.scope.
```

## removed config dir and app started after that normally

`rm -rf /home/mkungla/snap/superproductivity/current/.config/superProductivity`

```
systemd[4408]: Started app-gnome-superproductivity_superproductivity-443539.scope - Application launched by gnome-shell.
systemd[4408]: Started snap.superproductivity.superproductivity-ff258965-9524-46b3-8464-e1c3bcadbbaf.scope.
audit[443592]: SECCOMP auid=1000 uid=1000 gid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=443592 comm="superproductivi" exe="/snap/superproductivity/1830/superproductivity" sig=0 arch=c000003e syscall=330 compat=0 ip=0x7faf9b4d94e7 code=0x50000
audit[443593]: SECCOMP auid=1000 uid=1000 gid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=443593 comm="superproductivi" exe="/snap/superproductivity/1830/superproductivity" sig=0 arch=c000003e syscall=330 compat=0 ip=0x7f95c0a174e7 code=0x50000
superproductivity_superproductivity.desktop[443539]: Start app...
superproductivity_superproductivity.desktop[443539]: SNAP: common directory is used
uperproductivity_superproductivity.desktop[443539]: 22:58:54.987 › { enabled: null, showDevTools: false, mode: 'bottom' }
superproductivity_superproductivity.desktop[443539]: Saving backups to /home/mkungla/snap/superproductivity/1830/.config/superProductivity/backups
superproductivity_superproductivity.desktop[443539]: 22:58:55.123 › Saving backups to /home/mkungla/snap/superproductivity/1830/.config/superProductivity/backups
superproductivity_superproductivity.desktop[443622]: /usr/share/libdrm/amdgpu.ids: No such file or directory
audit[443622]: SECCOMP auid=1000 uid=1000 gid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=443622 comm="superproductivi" exe="/snap/superproductivity/1830/superproductivity" sig=0 arch=c000003e syscall=203 compat=0 ip=0x7fafa0549c7f code=0x50000
...
superproductivity_superproductivity.desktop[443539]: 22:58:57.464 › No custom styles detected at /home/mkungla/snap/superproductivity/common/.config/superProductivity/styles.css
superproductivity_superproductivity.desktop[443622]: [443622:0201/225857.475813:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
superproductivity_superproductivity.desktop[443622]: [443622:0201/225857.492545:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
superproductivity_superproductivity.desktop[443622]: [443622:0201/225903.635344:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
superproductivity_superproductivity.desktop[443539]: 22:59:23.475 › close, isQuiting: null
Feb 01 22:59:23 gogogo superproductivity_superproductivity.desktop[443539]: 22:59:23.478 › Actions to wait for  [ 'FINISH_DAY_BEFORE_CLOSE_EFFECT' ]
superproductivity_superproductivity.desktop[443539]: 22:59:23.480 › BEFORE_CLOSE_DONE FINISH_DAY_BEFORE_CLOSE_EFFECT []
superproductivity_superproductivity.desktop[443539]: 22:59:23.480 › close, isQuiting: null
superproductivity_superproductivity.desktop[443539]: 22:59:23.481 › close, isQuiting: true
superproductivity_superproductivity.desktop[443539]: 22:59:23.488 › Quit after all windows being closed
systemd[4408]: snap.superproductivity.superproductivity-ff258965-9524-46b3-8464-e1c3bcadbbaf.scope: Consumed 5.013s CPU time.
```

**Comment by johannesjo** [comment]
Sorry for the late reply. I am a little bit lost on where to continue with this, since I am not able to reproduce the issue myself. The main issue to me is this line:
```
Error: ENOENT: no such file or directory, stat '/home/pallab/snap/superproductivity/current/.config/superProductivity/SingletonCookie'
```

Which is likely some sort of electron issue.

Including this in the electron code might be a workaround:
```
const fs = require('fs');
const path = require('path');

const singletonCookiePath = path.join(process.env.HOME, 'snap/superproductivity/current/.config/superProductivity/SingletonCookie');

if (!fs.existsSync(singletonCookiePath)) {
  // Create the file if it doesn't exist
  fs.writeFileSync(singletonCookiePath, '');
}
```

But I am hesitant since it might not work on all systems.

Does somebody know how to help?

**Comment by johannesjo** [comment]
This might be fixed now. Can anybody confirm?
