### ISSUE TITLE
Snap and Android apps seem to no longer sync the same

### ISSUE THREAD

**Issue by TitaniumCoder477** [johannesjo/super-productivity#3263]
### Your Environment

Linux snap details: superproductivity  9.0.1                       1960   latest/stable  johannesjo
Android app details: 21.0 from the Play Store
Sync method: DropBox

### Expected Behavior

I make a change on my phone, sync it or wait for auto sync, and then when the snap version on my computer syncs, it pulls the changes. And vise versus.

### Current Behavior

Today the snap notified me that it needed to update.
I closed it, and it updated.
I reopened it, and I was provided with a message saying something about two files are in use going forward (as a new feature or improvement, not a discrepancy). I approved this, and everything appeared fine.
Then I noticed that the changes on my phone were no longer updating to the snap version via sync.
They both claim to be up-to-date with the version I have in DropBox, but they are clearly not.
Here are the files listed in DropBox:
![image](https://github.com/user-attachments/assets/6dac0a4d-c591-4634-a771-06c2a32cc72b)

### Steps to Reproduce (for bugs)

1. Make a change on app
2. Click sync on app
3. Click sync on snap version
4. Notice that change does not appear

### Can you reproduce this reliably?

Yes

### Console Output

NA

### Error Log (Desktop only)

The main.log file hasn't been updated since December 30, so doubtful it is going to be useful.

**Comment by nonameformr** [comment]
And me.

**Comment by nonameformr** [comment]
Update Windows app and all right )

**Comment by KPI01** [comment]
I've noticed the same issue. I am running the `.rpm` package on Fedora and when I want to retrieve my data it says that there is no data. I've been making some tests and the desktop app saves the configuration as 'sp-main.json' while the Android and web app uses the 'sp.json'.
The solution for my currently is use the web app in the browser and it syncs correctly

**Comment by TitaniumCoder477** [comment]
Sync between snap and Android app seems to be working again. The Android app prompted me for an update (inline, not via Play Store), and after updating sync was working again. I think I lost a couple tasks that were on the Android app, but until I remember them, I will assume they were not that important. :p

**Comment by johannesjo** [comment]
Unfortunately I can not role out the releases at exactly the same time, so these can of things can happen. Sorry for the inconvenience!! 

Does it work for everybody again?
