### ISSUE TITLE
Sync provider LocalFile's folder path unexpectedly changes without user input and causes synchronization to fail

### ISSUE THREAD

**Issue by Raindrac** [johannesjo/super-productivity#3268]
### Your Environment

- Version used: 9.0.3 (Linux .rpm) and 9.0.3 (Android .apk)
- Operating System and version: Linux and Android 11
- Desktop Environment: Gnome

### Expected Behavior

Local files synchronize successfully between Linux and Android.

### Current Behavior

Well, this is difficult to explain.

I set up Super Productivity to synchronize between devices using Super Productivity's LocalFile sync option and Syncthing to synchronize the folder between devices.

On Android, Super Productivity's LocalFile synchronization would save the database to "/Syncthing/Super Productivity/", while on 
Linux, Super Productivity's LocalFile synchronization would save the database to "/var/home/raindrop/Containers/Super-Productivity/Sync".

My Android app updated to 9.0.3 and synchronization immediately broke. When I looked into the folder structure, I found that LocalFile began saving the database to "/Syncthing/Super Productivity/storage/emulated/0/Syncthing/Super Productivity/" instead of "/Syncthing/Super Productivity/".

The sync folder path defined by LocalFile on Android was set to "/storage/emulated/0/Syncthing/Super Productivity/", if I recall correctly. I can't reproduce that specific issue again. I changed it back to "/Syncthing/Super Productivity/", then tried to synchronize with my Linux device. The newer database was on my Android device.

When it synchronized, it couldn't read the database's .json file. I can't remember the specific error, but it mentioned something about the remote database needing to be converted to a new version. When I attempted to convert it to the new version, Super Productivity throw out some more errors and fell back onto loading the backup, which was out of date.

So I updated my Linux .rpm to 9.0.3 and tried again. When I tried to synchronize, it worked! So I updated my task database with some new changes, went back to my Android device, and then found that it began failing to synchronize again.

My Android device was now saving the database to "/Syncthing/Super Productivity/var/home/raindrop/Containers/Super-Productivity/Sync" instead of "/Syncthing/Super Productivity/". When I went into the settings and checked what LocalFile's folder path was set to, the field sudenly contained "/var/home/raindrop/Containers/Super-Productivity/Sync"; that's the folder path that I set LocalFiles to use on Linux, not Android!

I changed the LocalFiles folder path to "/", which set it back to the root of "/Syncthing/Super Productivity/", the folder where I gave Super Productivity file access permissions to. Synchronization was fixed, and I made some more changes to my task database and then loaded up Super Productivity on Linux.

When I went back to my Linux device, it failed to synchronize. Upon looking at its LocalFile's folder path, it was set to "/". This caused it to output the following error when it attempted to sync:
![image](https://github.com/user-attachments/assets/1d07ab86-fdeb-497a-a9d4-c482daf650ee)

Note that "/" was the folder path that I assigned to the LocalFiles folder path on Android. Linux was attempting to use it, and because Super Productivity lacked file access to root, it outputted the aforementioned error.

I managed to work around the issue by changing my Syncthing settings and LocalFiles sync folder path to be identical for both devices.

### Steps to Reproduce (for bugs)
I'm unable to reproduce some of the original issues without the ability to rollback the update. But in the current position that I'm in, I can reproduce some issues with the following steps:
1. Set the LocalFile sync folder path to a different location on Android and Linux
2. Attempt to synchronize
3. Observe issues

### Can you reproduce this reliably?

Kind of. See above.

### Console Output

When attempting to sync again after the sync folder path on Linux changes to /, the following error is outputted to the console:
```
LocalFile X Upload Request Error retryIfPossibleOrWarnUser() Error: No rev returned from no error archive response
    at e.<anonymous> (sync-provider.service.ts:528:17)
    at Generator.next (<anonymous>)
    at k (chunk-OM4HSKZI.js:1:1464)
    at a.invoke (zone.js:331:158)
    at Object.onInvoke (core.mjs:15681:25)
    at a.invoke (zone.js:331:46)
    at b.run (zone.js:111:37)
    at zone.js:2366:30
    at a.invokeTask (zone.js:356:171)
    at Object.onInvokeTask (core.mjs:15670:25)
```

I'd attempt to reproduce the issue again to get some more logs, but now that I've got synchronization working again after an hour of trial and error, I'm hesitant to break it again 😟

But... if more logs are needed to fix the issue, let me know and I'll attempt to reproduce the issue again.

### Notes
This might be related to issue https://github.com/johannesjo/super-productivity/issues/3263.

**Comment by StructSeeker** [comment]
Experienced the simliar problem on android-windows sync. My android device's syncfile is also placed at the `originalsyncfolder/repeated_absolute_path/MAIN.json`

Also noted that windows localfile sync settings requires me to specify a file for sync whereas android requires me to specify a folder. Such inconsistency cause me have to set the path on windows to be `C:\Users\Username\Syncthing\Apps\SuperProductivity\syncdir\MAIN.json` on windows and `SDCardID/Syncthing\Apps\SuperProductivity\` (granted path) and `syncdir` (Sync folder path) on android.

**Comment by johannesjo** [comment]
Thank you very much for digging into this @StructSeeker ! This saved me a couple of hours :)

Can you maybe also open up a separate issues for the winget stuff and and the wrong messages on mobile? Not sure how to fix the winget issue though. I did not actively configure something to make SP available there.

**Comment by Raindrac** [comment]
I'm experiencing another sync-related issue at https://github.com/johannesjo/super-productivity/issues/3284 now, but thanks for the prompt fix of this one! 👍
