### ISSUE TITLE
Create integration for PiovtalTracker

### ISSUE THREAD

**Issue by hardyoyo** [johannesjo/super-productivity#327]
We use PivotalTracker at my workplace to manage stories/issues to work on. I'd love to be able to use Super Productivity to coordinate this work, but, an integration does not yet exist.

Pivotal has an API: https://www.pivotaltracker.com/help/api#top

**Comment by johannesjo** [comment]
An integration would be welcome. Would you like to give it a short yourself?

**Comment by hardyoyo** [comment]
I'd be willing to give it a shot, have any advice for a newbie? A good example from which to copy?

**Comment by johannesjo** [comment]
That's great to hear!

Most of the relevant stuff should be found here:

https://github.com/johannesjo/super-productivity/tree/master/src/app/features/issue

You can use one more multiple of the existing issue providers for a guideline on how to integrate it. Some of the stuff is pretty new, so there might be some rough edges.

https://github.com/johannesjo/super-productivity/tree/master/src/app/features/issue/providers

Let me know if you have any further questions!

**Comment by Eyad-dev** [comment]
hello im new to github and i want to know to know what is it for 

Is it for programming ?

is  it for helping people in doing some projects ?

I would like to know what is it for thank you.

**Comment by johannesjo** [comment]
@Eyad-dev  This is not the right place to get an answer to your question, but maybe this helps:
https://www.google.com/search?q=what+is+github&rlz=1C1CHBF_deDE881DE881&oq=what+is+github&aqs=chrome..69i57j0l7.2076j0j7&sourceid=chrome&ie=UTF-8

**Comment by bjerre3000** [comment]
> Thanks for opening this up. An integration would be welcome. Would you like to give it a short yourself?

**Comment by hardyoyo** [comment]
Still relevant, just don't have time to work this.
