### ISSUE TITLE
9.0.3 Release Bug with Sync

### ISSUE THREAD

**Issue by TheCoffeeHub1** [johannesjo/super-productivity#3273]
### Your Environment

- Version used: 
- Operating System and version: Windows
- Browser Name and version: Chrome

### Expected Behavior

I used to implement a tracking env on the some devices, syncing with Google Drive Link , and worked for months, yesterday the system cant recognize de path 
![image](https://github.com/user-attachments/assets/fa581039-6f50-4e71-b15e-738b12a310bb)

Use a Google Drive Folder to Syinc the data

1.
2.
3.
4.

### Console Output

![image](https://github.com/user-attachments/assets/45ae664b-4018-47ce-b7ea-df00655dafa1)

**Comment by johannesjo** [comment]
Was not able to reproduce this myself, so help with this issue would be welcome!
