### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'title')

### ISSUE THREAD

**Issue by thrabash** [johannesjo/super-productivity#3279]
### Steps to Reproduce

1.
2.
3.
4.

### Meta Info
META: SP9.0.3 Browser – es-ES – Linux aarch64 – Mozilla/5.0 (Linux Android 5.0 SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Mobile Safari/537.36

### Stacktrace
```
TypeError: Cannot read properties of undefined (reading 'title')
    at https://app.super-productivity.com/main-XULEE4CZ.js:157:60914
    at Array.map (<anonymous>)
    at P4.project (https://app.super-productivity.com/main-XULEE4CZ.js:157:60812)
    at P4._next (https://app.super-productivity.com/main-XULEE4CZ.js:79:20305)
    at P4.next (https://app.super-productivity.com/main-XULEE4CZ.js:79:2372)
    at N4.notifyNext (https://app.super-productivity.com/main-XULEE4CZ.js:79:22947)
    at KA._next (https://app.super-productivity.com/main-XULEE4CZ.js:79:20705)
    at KA.next (https://app.super-productivity.com/main-XULEE4CZ.js:79:2372)
    at h$._next (https://app.super-productivity.com/main-XULEE4CZ.js:79:38433)
    at h$.next (https://app.super-productivity.com/main-XULEE4CZ.js:79:2372)
```

### Actions Before Error
```
1721557272050: [Improvement] Delete multiple Improvements 
1721557272900: [Layout] Toggle SideBar 
1721557275597: [Layout] Hide SideBar 
1721557275628: [WorkContext] Set Active Work Context 
1721557275952: [Task] SetSelectedTask 
1721557276525: [Layout] Hide SideBar 
1721557276644: [Bookmark] Load Bookmark State 
1721557276647: [Project] Load Project related Data Success 
1721557276650: [Improvement] Clear Hidden Improvements 
1721557276652: [Improvement] Delete multiple Improvements 
1721557287411: [Layout] Toggle SideBar 
1721557292549: [Layout] Hide SideBar 
1721557292583: [WorkContext] Set Active Work Context 
1721557292818: [Task] SetSelectedTask 
1721557292937: [Layout] Hide SideBar 
1721557294013: [Layout] Toggle SideBar 
1721557300988: [Layout] Hide SideBar (2) 
1721557306505: [Project] Delete Project 
1721557306517: [Persistence] Save to DB 
1721557306521: [Persistence] Remove from DB 
1721557306582: [Task] Delete Tasks 
1721557306617: [Persistence] Save to DB (3) 
1721557309383: [Project] Delete Project 
1721557309390: [Persistence] Save to DB 
1721557309393: [Persistence] Remove from DB 
1721557309427: [Task] Delete Tasks 
1721557309452: [Persistence] Save to DB (3) 
1721557311407: [Project] Delete Project 
1721557311412: [Persistence] Save to DB 
1721557311413: [Persistence] Remove from DB
```

**Comment by johannesjo** [comment]
Hey there! Thanks for reporting! Can you provide a bit more input on what happened before the errorr?

**Comment by thrabash** [comment]
Hi. I was on the desktop app in Ubuntu Studio. I just deleted a project and the error message showed up immediately.

It had happened to me two or three months before in same circumstances; then I decided to recover a previous backup, but the issue popped up again when I tried to delete a project.

So I recovered again the backup and decided not to delete any project.

Hope It helps. I love SuperProductivity, it's a pleasure to give feedback. Hit me anytime

Regards.

-------- Mensaje original --------
El 22/7/24 8:59, Johannes Millan  ha escrito:

**Comment by johannesjo** [comment]
I am unable to reproduce this unfortunately. It would be great if you could share a copy of your data to contact@super-productivity.com, so I can debug this on my computer (and please let me know here, if you send something, as those mails quite often land in the spam folder). You can create an export by navigating to "Settings" and then to "Import/Export" or you can use the "Export data" button from the error Dialog (there is also a button there which will anonymize the data before exporting).

**Comment by thrabash** [comment]
Hi, I just sent an email to the adress. Sorry for the delay, hope it helps. Thank you very much!

**Comment by johannesjo** [comment]
Hey hey! Unfortunately I received no email from you. Could you maybe check again?

**Comment by johannesjo** [comment]
Thanks to your help, I was able to fix this from reoccurring. To work around this on your machine, you need to remove the note that belonged to the project that you deleted. Removing it via the little sun should be enough (even though the error dialog is shown, you should still be able to interact with the ui).

**Comment by johannesjo** [comment]
Please let me know if this  works for you! I can also repair your data manually if needed.

**Comment by thrabash** [comment]
The solution worked perfectly, everything is recovered and working properly. I am very grateful for your attention, Johannes. All the best!
