### ISSUE TITLE
Remove all datas

### ISSUE THREAD

**Issue by daryooosh** [johannesjo/super-productivity#328]
### Your Environment

* Version used: 3.2.4
* Operating System and version: windows 10
* Desktop Environment: 
* Browser Name and version: 

### Expected Behavior

Need a option to remove all datas (projects, worklog, metrics and ....).

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by johannesjo** [comment]
You can open up the dev tools by pressing Ctrl+Shift+I. There you can go to the "Aplication" tab and under "Clear storage" you can delete all data.

Also  3.2.4 is quite old. 5.0.7. is the last version. :)
