### ISSUE TITLE
Winget Version Problem

### ISSUE THREAD

**Issue by StructSeeker** [johannesjo/super-productivity#3282]
Currently there're two super-productivity (SP) available via winget:
```
> winget search "productivity"
Name                                        Id                               Version        Match             Source
---------------------------------------------------------------------------------------------------------------------
Super Productivity                          9NHFVG8361TW                     Unknown                          msstore
superProductivity                           JohannesMillan.superProductivity 8.0.10         Tag: productivity winget
```
Note that SP from winget source isn't up-to-date.

It's recommended to do the following:
1. add hints sync settings that the two SP sync to each other shall be of the same (at least main) version number.
2. one of the below
2.b remove the winget source SP from winget, leaving only the msstore source
2.c update the version of winget source

**Comment by johannesjo** [comment]
The winget release is not maintained by me. But I'd appreciate it if someone were to provide a PR to update Super Productivity:
https://github.com/microsoft/winget-pkgs/pulls

**Comment by ReenigneArcher** [comment]
You might consider updating the winget version automatically? This is what I do for one of ours. https://github.com/LizardByte/Sunshine/blob/1f2b541df63155e11b55d7956bd707e3d88f1adf/.github/workflows/update-winget-release.yml#L59-L68

https://github.com/vedantmgoyal9/winget-releaser
