### ISSUE TITLE
"Show App" when the .exe is called

### ISSUE THREAD

**Issue by softyoda** [johannesjo/super-productivity#3286]
Hi, i wish to open the windows via shortcut instead of having to go through all my taskbar icon, I found it more productive to do all with shortcut without having to go to my mouse that often.

I have a custom keyboard with custom shortcut and I put the shortcut of the app mapped to one of my keys, allowing me to open the app, unfortunately this behavior is not optimal as this work only once (if minimize to tray and start with os are enabled, to actually have them preloaded) if I call the .exe again, it simply does nothing.

Proposal solutions : 
- Have a new shortcut that would listen everywhere on the OS (not good as it's almost like a keylogger and it's not safe)
- Have a new api call from a .py or .bat or whatever that when executed, do exactly like the "Show app" button on icon-trail-right-click.
- Have a behavior directly in the .exe to "Show app" when reopening the app if it's already opened.

**Comment by UnconsciousBlaringHuman** [comment]
As a workaround, in case this doesn't get added, either start SP manually or have it start with Windows and then map the custom key to `Show/Hide Super Productivity` in the Global Shortcuts section, that's what I do.
