### ISSUE TITLE
When i try to increase the volume in the sound section it trowing some type error.

### ISSUE THREAD

**Issue by MelvinThankachan** [johannesjo/super-productivity#3287]
### Steps to Reproduce

1. Go to settings
2. Open Sound Section
3. Try to increase the voulume by dragging the level bar.
4. It thowing some type error

### Error Log (Desktop only)

TypeError: Cannot read properties of undefined (reading 'set')
isHandledError (file:///C:/Users/user/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/src/app/core/error-handler/global-error-handler.class.ts:45:12)B (file:///C:/Users/user/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/chunk-OM4HSKZI.js:1:1464)invoke (file:///C:/Users/user/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/node_modules/zone.js/fesm2015/zone.js:331:157)onInvoke (file:///C:/Users/user/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/node_modules/@angular/core/fesm2022/core.mjs:15681:24)invoke (file:///C:/Users/user/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/node_modules/zone.js/fesm2015/zone.js:331:45)run (file:///C:/Users/user/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/node_modules/zone.js/fesm2015/zone.js:111:36)zone.scheduleMicroTask(source, (file:///C:/Users/user/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/node_modules/zone.js/fesm2015/zone.js:2366:29)invokeTask (file:///C:/Users/user/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/node_modules/zone.js/fesm2015/zone.js:356:170)shouldBeIgnoredByZone (file:///C:/Users/user/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/node_modules/@angular/core/fesm2022/core.mjs:15670:24)
META: SP9.0.3 Electron – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/9.0.3 Chrome/122.0.6261.156 Electron/29.4.5 Safari/537.36

I am using windows 11, Brave browser.

**Comment by johannesjo** [comment]
That seems to be caused by the material component. Not sure there is much we can do from our side, since it also doesn't affect the  user experience, if I am not mistaken.

**Comment by BadBossy** [comment]
Yo! I've debugged the whole thing around formly and material. It's not a bug in material. it's more a problem in formly, they use the material13 package, which had an different api compared to now (material18 which you use).

the bug breaks the user experience, at least for me because it displays the error. my suggestion would be, to rewrite the Sound Config Area to a dedicated component or create a workaround just for that specific formly slider by using an number input directly.

@johannesjo let me know which one you are interested in and I do it :)

**Comment by MelvinThankachan** [comment]
We are currently experiencing issues specifically with adjusting sound levels using the dragging method. When sound levels are changed through direct input (clicking), no errors are observed.

To address this, one potential solution is to reimplement the sound level adjustment mechanism. Introducing visual indicators, such as dots representing each sound level, could greatly enhance the user experience. This approach would not only provide users with a clear understanding of the sound levels but also encourage them to use the click-to-select method more frequently, potentially reducing the incidence of dragging-related errors.

Additionally, it would be beneficial to thoroughly debug and resolve the issues associated with the dragging functionality or, alternatively, consider disabling the dragging feature until these issues are resolved.

**Comment by johannesjo** [comment]
@BadBossy Thank you very much!! 

 As there are currently no other formly sliders in the app, I am fine with both solutions. Whatever feels quicker and easier to maintain is probably a good choice I'd say. Maybe this would be extracting it into a non formly component, since it is less likely to break. But not sure :)

**Comment by BadBossy** [comment]
> @BadBossy Thank you very much!!
> 
> As there are currently no other formly sliders in the app, I am fine with both solutions. Whatever feels quicker and easier to maintain is probably a good choice I'd say. Maybe this would be extracting it into a non formly component, since it is less likely to break. But not sure :)

alright, i'm gonna work on it on the weekend to get a fix out :)
