### ISSUE TITLE
Found some tasks with the wrong project id after upgrade to 5 from 4.1

### ISSUE THREAD

**Issue by Jackymancs4** [johannesjo/super-productivity#329]
### Your Environment

* Version used: 5.0.7
* Operating System and version: MacOS 10.14.6 (18G2022)

### Expected Behavior
The app migrates completely the data without promting me to delete them.

### Current Behavior
I have currently 9 projects.
On entering the first one (only that one) the application spawns a a dialog:
`Nooo! We found some tasks with the wrong project id. It is strongly recommended to delete them to avoid further data corruption. Delete them now?`

After clicking `OK`, it proceeds to delete all the tasks in that project.

### Steps to Reproduce (for bugs)

1. Have version 4.1.1 with some projects.
2. Delete the app.
3. Replace it with version 5.0.7
4. Open the app and read the promt

### Console Output
[05_04_2020.log](https://github.com/johannesjo/super-productivity/files/4434355/05_04_2020.log)

### Error Log (Desktop only)
I checked it, there is nothing logged in this date.

### Note

Hello,
I'm having the little problem that is described upfront. It's not the end of the world but it still annoys me because of the (more or less) carefully crafted tasks I'm loosing. 

So if it happens to not be a problem with Super Productivity, or just some random corruption, can you give me some hints how to fix the backup file for proper import (I will provide a functioning 4.1.1 backup file on request).

Thank you very much.

**Comment by johannesjo** [comment]
Hi there! Very sorry, that you encountering this issue. Would you mind sharing the complete data with me privately on this email `jo at the-front-ent.de` ? 

I am assuming that this is happening due to some project ids being wrong. Generally every task and sub task of a project should also have its id assigned.

**Comment by Jackymancs4** [comment]
Thanks for the quick response!

> jo at the-front-ent.de

May I assume the address is `jo at the-front-end.de` ?

> I am assuming that this is happening due to some project ids being wrong. Generally every task and sub task of a project should also have its id assigned.

In your opinion, did I do something wrong or is it just a glitch?

**Comment by johannesjo** [comment]
> May I assume the address is jo at the-front-end.de ?

Yes! :)

> In your opinion, did I do something wrong or is it just a glitch?

You did not most likely not do anything wrong. I just think that it might have been possible to generate invalid data before without any repercussions for the old version of the application. 

I had a problem with my own data where some data got copied over from one project to another (which never should have been possible in the first place) leaving me with some tasks with the same id which effectively were overwritten. I thought this just was me. and that's why I didn't write special, possibly very complicated and thus error prone  migration script for this case. Maybe the same happened in your case?

**Comment by johannesjo** [comment]
Were you able to solve your issue?

**Comment by Jackymancs4** [comment]
> Were you able to solve your issue?

Nope, I just deleted the project altogether (as the prompt suggested) to avoid further corruption.

> [...] Maybe the same happened in your case?

Cannot confirm nor deny :) 

> Would you mind sharing the complete data with me privately on this email [...]

I sent it yesterday, can you confirm?

**Comment by johannesjo** [comment]
The whole project? Or just the tasks (as suggested and automatically executed by the dialog)? 

I didn't get any email. Did you send it to "jo   the-front-end.de"?

**Comment by Jackymancs4** [comment]
> The whole project? Or just the tasks (as suggested and automatically executed by the dialog)

First the task as suggested, but the project being now emptied is of no use to me and I deleted it, starting fresh with a new one. I still retain all the backups.

> I didn't get any email. Did you send it to "jo the-front-end.de"?

Technology is failing me more often the usual now..

<img width="656" alt="Schermata 2020-04-06 alle 15 50 23 2" src="https://user-images.githubusercontent.com/6209647/78565803-afae2900-781e-11ea-880d-697873c4b2e8.png">

This is the entry on thunderbird UI.

**Comment by johannesjo** [comment]
Ah alright. I was afraid for a moment that the message is misleading.

Weird. I got nothing in my inbox. But don't worry. If you found a solution and no other people are affected then I am fine with leaving things as they are.

**Comment by Jackymancs4** [comment]
> I was afraid for a moment that the message is misleading.

Not misleading, but surely a little scary. When I read `to avoid further data corruption.` I was unsure it was refering to the project data, **all** projects data, or even app data (with conseguent crash/instability).

> I got nothing in my inbox nor my spam folder.

I sent it again just because..

> If you found a solution and no other people are affected then I am fine with leaving things as they are.

If you could return the file back to me, fixed and importable, that would be a nice gift, but by any manner, don't spend to much time on it as I already moved on.
If not, feel free to close the issue at your will.

Thank very much for the project and the assistance!

**Comment by johannesjo** [comment]
Sorry. My bad. There was something wrong with my mail server...

I checked your file and it seems to be the same problem I had. Some of the task ids seem to be used in multiple projects at the same time. "44N1Tkmr4" "Blade of Agony game" exists in the default project as well as in another.  Not sure where it actually belongs...

It should be possible to write a script for each projects task state that replaces double ones with new ids, but I rather spend my time with something else to be honest ;)

**Comment by Jackymancs4** [comment]
> It should be possible to write a script for each projects task state that replaces double ones with new ids, but I rather spend my time with something else to be honest ;)

Please, no need! Now that I know where to look at and that it is just a duplication issue, I can fix it myself if I'll need it.

Thanks for taking a look! I consider my problem resolved.
