### ISSUE TITLE
Docker only has NGINX running

### ISSUE THREAD

**Issue by Sythelux** [johannesjo/super-productivity#3293]
### Your Environment

- Version used: docker
- Operating System and version: docker:latest, docker:master

### Expected Behavior

running 
`docker run -d -p 80:80 johannesjo/super-productivity:latest`
`docker run -d -p 80:80 johannesjo/super-productivity:master`

should pull the image and run it and then be accessible on localhost:80 and open the welcome screen. This is how it work in v8.0.10

![grafik](https://github.com/user-attachments/assets/2a160a99-7f61-4915-80d0-1df4fbd02668)

### Current Behavior

however, running latest and master greets me with "welcome to nginx" default screen

![grafik](https://github.com/user-attachments/assets/5a564635-e046-432e-b045-eeca11c0df1e)

### Steps to Reproduce (for bugs)

1. have docker
2. run docker run -d -p 80:80 `johannesjo/super-productivity:latest`
3. go to the http://localhost in your browser
4. you should see the default nginx screen instead of super productivity welcome screen.

**Comment by johannesjo** [comment]
Thanks for bringing this to my attention. Should be fixed and hopefully available soon.

**Comment by jayvenco** [comment]
Getting this issue right now as wel  (Latest and master) Only NGNX installed
