### ISSUE TITLE
Sync Bug in SuperProductivity 9.0.5

### ISSUE THREAD

**Issue by StructSeeker** [johannesjo/super-productivity#3295]
I am using syncthing and localfile to sync between windows and android and i have console error as follows:
<details>
<summary> Click to show pictures </summary>
 <img src="https://github.com/user-attachments/assets/f5536b12-141c-4ae9-b8e7-2590dc60ddcb" />
<img src="https://github.com/user-attachments/assets/13a66ea4-e17c-46e4-af2c-36ab58c6d79a" />
<img src="https://github.com/user-attachments/assets/ed5e66bf-517d-4c93-8e9a-bc5c13e9e9b4" />
<img src="https://github.com/user-attachments/assets/dba08aa2-9f5a-43ce-9d88-f28779dd1d79" />
<img src="https://github.com/user-attachments/assets/cc4f3630-b2ec-454c-9615-2b99f7710960" />

</details>
<details><summary> Error Log </summary>
<code>
persistence.service.ts:317 LOAD COMPLETE false
sync-provider.service.ts:229 {rev: '1721912222642', localRev: '1721911114256'}
persistence.service.ts:317 LOAD COMPLETE false
sync-provider.service.ts:930 LocalFile ↓ downloading main file
check-for-update.util.ts:69 {local: 1721911386781, lastSync: 1721910078408, remote: 1721912212031}
check-for-update.util.ts:81 {lastSync: 0, local: 1308.373, remote: 2133.623} 2279.827
check-for-update.util.ts:54 DATA DIVERGED: local < remote
sync-provider.service.ts:930 LocalFile ^--------^-------^
sync-provider.service.ts:930 LocalFile ⇎ X Diverged Data
sync-provider.service.ts:930 LocalFile Dialog => ↓ Update Local
sync-provider.service.ts:930 LocalFile Archive force update chosen. Downloading...
sync-provider.service.ts:930 LocalFile ↓ downloading archive file
sync-provider.service.ts:141 __error during sync__
sync-provider.service.ts:142 Error: Unable to parse remote data due to unknown reasons
    at e.<anonymous> (sync-provider.service.ts:903:11)
    at Generator.next (<anonymous>)
    at main-X2V3OSX7.js:1:1664
    at N (zone.js:2529:23)
    at Se (main-X2V3OSX7.js:1:1484)
    at e._decompressAndDecryptDataIfNeeded (sync-provider.service.ts:835:38)
    at e.<anonymous> (sync-provider.service.ts:446:24)
    at Generator.next (<anonymous>)
    at o (main-X2V3OSX7.js:1:1522)
    at a.invoke (zone.js:331:158)
(anonymous) @ sync-provider.service.ts:142
s @ main-X2V3OSX7.js:1
invoke @ zone.js:331
onInvoke @ core.mjs:15681
invoke @ zone.js:331
run @ zone.js:111
(anonymous) @ zone.js:2366
invokeTask @ zone.js:356
onInvokeTask @ core.mjs:15670
invokeTask @ zone.js:356
runTask @ zone.js:157
Z @ zone.js:527
Promise.then (async)
x @ zone.js:504
K @ zone.js:514
scheduleTask @ zone.js:348
onScheduleTask @ zone.js:257
scheduleTask @ zone.js:342
scheduleTask @ zone.js:196
scheduleMicroTask @ zone.js:215
i @ zone.js:2356
M @ zone.js:2297
(anonymous) @ zone.js:2216
(anonymous) @ zone.js:2231
Promise.then (async)
(anonymous) @ zone.js:2604
N @ zone.js:2529
Ge.p.then @ zone.js:2603
M @ zone.js:2262
resolve @ zone.js:2385
a @ main-X2V3OSX7.js:1
o @ main-X2V3OSX7.js:1
invoke @ zone.js:331
onInvoke @ core.mjs:15681
invoke @ zone.js:331
run @ zone.js:111
(anonymous) @ zone.js:2366
invokeTask @ zone.js:356
onInvokeTask @ core.mjs:15670
invokeTask @ zone.js:356
runTask @ zone.js:157
Z @ zone.js:527
invokeTask @ zone.js:436
_ @ zone.js:1054
x @ zone.js:1084
K @ zone.js:1115
IndexedDB (async)
(anonymous) @ index.js:107
(anonymous) @ index.js:212
(anonymous) @ main-X2V3OSX7.js:1
N @ zone.js:2529
Se @ main-X2V3OSX7.js:1
o @ index.js:202
(anonymous) @ indexed-db-adapter.service.ts:68
o @ main-X2V3OSX7.js:1
invoke @ zone.js:331
onInvoke @ core.mjs:15681
invoke @ zone.js:331
run @ zone.js:111
(anonymous) @ zone.js:2366
invokeTask @ zone.js:356
onInvokeTask @ core.mjs:15670
invokeTask @ zone.js:356
runTask @ zone.js:157
Z @ zone.js:527
invokeTask @ zone.js:436
E.useG.invoke @ zone.js:422
g.args.<computed> @ zone.js:1687
setTimeout (async)
c @ zone.js:1689
scheduleTask @ zone.js:346
onScheduleTask @ zone.js:257
scheduleTask @ zone.js:342
scheduleTask @ zone.js:196
scheduleMacroTask @ zone.js:218
Yn @ zone.js:647
(anonymous) @ zone.js:1727
n.<computed> @ zone.js:929
_waitForAnimationToComplete @ dialog.mjs:212
_startExitAnimation @ dialog.mjs:172
close @ dialog.mjs:391
close @ dialog-sync-conflict.component.ts:39
(anonymous) @ dialog-sync-conflict.component.html:38
oee @ core.mjs:25807
n @ core.mjs:25839
(anonymous) @ platform-browser.mjs:683
invokeTask @ zone.js:356
onInvokeTask @ core.mjs:15670
invokeTask @ zone.js:356
runTask @ zone.js:157
invokeTask @ zone.js:433
_ @ zone.js:1054
x @ zone.js:1084
K @ zone.js:1115
Show 80 more frames
Show less
persistence.service.ts:317 LOAD COMPLETE false
</code>
</details>

Step to reproduce:
1. delete all file in syncdir
2. On android, have SP to write current data to the remote.
3. Main.json is in syncdir (I clear all SP data and start a new android SP, archive.json wasn't in the syncdir)
4. Sync the syncdir to the windows
5. force windows SP use the remote data
6. The above error is generated

Similar issue happens when trying to sync windows data to android. But console log of android is unavailable.

**Comment by johannesjo** [comment]
Hey hey! What does the content of the file look like (the file is likely called ARCHIVE.json)? Is there anything in it?

There has been another bug with android file sync (#3297). So maybe this is related.

**Comment by StructSeeker** [comment]
> Hey hey! What does the content of the file look like (the file is likely called ARCHIVE.json)? Is there anything in it?嘿 嘿！文件的内容是什么样子的（该文件可能被称为 ARCHIVE.json）？里面有什么东西吗？
> 
> There has been another bug with android file sync (#3297). So maybe this is related.android 文件同步还存在另一个错误 （ #3297 ）。所以也许这是相关的。
Give me an email so that i can email the files to you.

**Comment by StructSeeker** [comment]
> Hey hey! What does the content of the file look like (the file is likely called ARCHIVE.json)? Is there anything in it?
> 
> There has been another bug with android file sync (#3297). So maybe this is related.

Give me your email and i shall give you the file.
![image](https://github.com/user-attachments/assets/9a330007-3f2b-43f4-9206-7d3e41dd97ab)
Note that it seems the Archive.json is not created when clicking the sync button. But created in the middlenight after i deleted it.

**Comment by johannesjo** [comment]
Not sure what is happening here. I added some extra logging. Could you be so kind, to check again with the newest edge release (should be available in 20 minutes or so)?

**Comment by StructSeeker** [comment]
@johannesjo I am glad to be helpful, where to install the 9.0.6?

**Comment by johannesjo** [comment]
The 9.0.6 is not out yet, but you could install the newest edge channel release via
`sudo snap install --channel=edge superproductivity`

**Comment by StructSeeker** [comment]
> The 9.0.6 is not out yet, but you could install the newest edge channel release via `sudo snap install --channel=edge superproductivity`

I am not using Graphical Linux, sorry i couldn't help on the matter.

**Comment by LeonelRFF** [comment]
> I am using syncthing and localfile to sync between windows and android and i have console error as follows:
> 
> Click to show pictures
> Error Log
> Step to reproduce:
> 
> 1. delete all file in syncdir
> 2. On android, have SP to write current data to the remote.
> 3. Main.json is in syncdir (I clear all SP data and start a new android SP, archive.json wasn't in the syncdir)
> 4. Sync the syncdir to the windows
> 5. force windows SP use the remote data
> 6. The above error is generated
> 
> Similar issue happens when trying to sync windows data to android. But console log of android is unavailable.

Hi, I'm new to coding, I have a similar problem with syncing local folders, I installed synthing with the corresponding super-productivity folders between my android and windows, but it doesn't work.
![image](https://github.com/user-attachments/assets/c8f04491-0c8f-40e4-a986-a2a75dfebecc)
![image](https://github.com/user-attachments/assets/297c9656-dd09-4bb7-bc79-5eeb9b03c613)

**Comment by StructSeeker** [comment]
> The 9.0.6 is not out yet, but you could install the newest edge channel release via `sudo snap install --channel=edge superproductivity`

Tried Windows-Android local file sync on 9.0.7, now it works well.
