### ISSUE TITLE
Android LocalFile Sync Errors

### ISSUE THREAD

**Issue by aaylnx** [johannesjo/super-productivity#3297]
### Your Environment

- Version used:  9.0.5
- Operating System and version: Android
- Desktop Environment: 
- Browser Name and version: 

### Expected Behavior

The sync function should be able to use LocalFile sync with the following Android directory: /storage/emulated/0/syncthing_shares/personal_cloud/super-productivity

### Current Behavior

When I try and sync I get the following error.

![01](https://github.com/user-attachments/assets/0945c37b-18bd-434c-b98c-39fe5647ca47)

I don't think I've ever had to grant that access to the root path before. Is that right?  Anyway, if I enable this, and then afterward drill down and specify the aformentioned directory as the directory I want to use for LocalFile sync, then I get the following error

![02](https://github.com/user-attachments/assets/16682973-9a45-4790-bccc-41f7cd7f2232)

If I agree to that, then I get the following error.

![03](https://github.com/user-attachments/assets/2ea692e1-7416-465d-b66b-898e10dcb9f5)

I am not even using the end to end encryption feature, so I don't know what this is all about. 

### Steps to Reproduce (for bugs)

1. Enable Syncing
2. Enable Compression
3. Select LocalFile as sync provider
4. Use /storage/emulated/0/syncthing_shares/personal_cloud/super-productivity as the path for local file sync.

After I updated to the latest version (not sure what version I was using before that), it happens every time.

### Can you reproduce this reliably?

It happens every time I try to enable Syncing using local file access.

**Comment by UnconsciousBlaringHuman** [comment]
I could be totally wrong, but I believe you are simply missing a forward slash `/` at the end and/or start of `super-productivity`. I got the same error before I added a slash (and only the slash) in the `Sync folder path *` box (the path in `Granted file access permission:` was the entire path already).

**Comment by aaylnx** [comment]
> I could be totally wrong, but I believe you are simply missing a forward slash `/` at the end and/or start of `super-productivity`. I got the same error before I added a slash (and only the slash) in the `Sync folder path *` box (the path in `Granted file access permission:` was the entire path already).

I wish that doesn't fix anything for me.

Also, the preexisting settings were working fine until the upgrade. Something has changed with the upgrade that has affected things. There seem to be a lot of other folks who are having various sync issues right now.

**Comment by johannesjo** [comment]
Thanks for reporting. Fix will be out with the next release!

**Comment by aaylnx** [comment]
> Thanks for reporting. Fix will be out with the next release!

Thank you!
