### ISSUE TITLE
Sync with compression on Linux desktop and on Android seem to be incompatible with each other

### ISSUE THREAD

**Issue by hkockerbeck** [johannesjo/super-productivity#3298]
### Your Environment

- Version used: Super Productivity 9.0.5 (Linux desktop), Super Productivity 21.0  (Android)
- Operating System and version: Ubuntu 22.04 LTS (Linux desktop), Android 10 (Android)
- Desktop Environment: Gnome 42.9 (Linux desktop)
- Browser Name and version: N/A

### Expected Behavior

I expect Super Productivity to successfully sync between the desktop app and the Android app, with WebDAV as the intermediate storage, with compression activated.

### Current Behavior

When sync compression is activated in the desktop and the Android app, the Android app can't read the sync data written by the desktop app (and probably vice versa, though I didn't specifically test that). When sync compression is deactivated on both sides, the sync is successful.

### Steps to Reproduce (for bugs)

1. Setup sync to the same WebDAV folder, in desktop app and Android app, with sync compression activated on both sides.
2. Sync local data from desktop app to WebDAV.
3. Try to sync data from WebDAV to Android app.
4. Android app doesn't recognize the sync data on WebDAV and offers to push local data to remote.

When the sync compression is deactivated on both sides, everything works

1. Setup sync on both sides with sync compression deactivated.
2. Sync local data from desktop app to WebDAV.
3. Try to sync data from WebDAV to Android app.
4. Sync is successful.

### Can you reproduce this reliably?

The issue happens reproduciably.

### Console Output

I'm not aware how to get to the console in the Android app.

### Error Log (Desktop only)

N/A

**Comment by johannesjo** [comment]
Thanks for reporting this! I think I was able to fix this. I will make a new patch release soon.
