### ISSUE TITLE
[Feature] Internationalization Interface

### ISSUE THREAD

**Issue by jingle0927** [johannesjo/super-productivity#33]

**Comment by johannesjo** [comment]
Hello! Thanks for reporting. This would be a bigger undertaking, as there is no internationalization interface yet, but I agree that it would be nice to have multi language support.

**Comment by jingle0927** [comment]
Thanks  I am come from [deepin](https://www.deepin.org/en)  

http://appstore.deepin.org/  push in  our  AppStore.

**Comment by johannesjo** [comment]
It would be great to be listed in your store! :+1:

**Comment by baram204** [comment]
+1. Internalization interface needed.

**Comment by johannesjo** [comment]
It's a big undertaking, I need to know that this is really in such a huge demand. If some more people +1 this thread I probably will start working on it.

**Comment by jpfleury** [comment]
+1 (French)

**Comment by johannesjo** [comment]
I added a basic interface for translations in a new branch: https://github.com/johannesjo/super-productivity/tree/feature/translation-interface

What's missing is most of the proper bindings for the translations (https://angular-translate.github.io/docs/#/guide) and the translations themselves. I really would appreciate some support on this one.

**Comment by jingle0927** [comment]
http://appstore.deepin.org/app/superproductivity   in deepin appstore

**Comment by amblyline** [comment]
I could help you translating to Polish. In Poland we have population of almost 40 mln. But... if quantity of highly organized Chinese people, spanish and portuguese speaking is not motivating you enough, then I'm afraid 40mln is nothing ;) Open the doors to them, they will help you grow this amazing app.

**Comment by johannesjo** [comment]
@amblyline it's not about motivation :) actually I've several branches with the feature lying around with the feature ready to go. I could either use a Technology which is a little bit outdated and potentially makes the app a bit slower or I could use one which will make the build 5mb bigger for every language I add, or could provide separate binaries for every language. 

The other problem is related on how to deploy the app. Currently I can make a release whenever I feel like it, but with multiple languages I would have to wait for the translations, which I really can't provide in a satisfying quality myself. 

So the question I couldn't bring myself to answer yet is wether it's worth to continually spent my time on this or if it is better to spend it on other areas such as bug fixes and new features. For now I think that the demand is simply not high enough, to justify spending my time with all the troubles involved.

**Comment by johannesjo** [comment]
I made a lot of progress. I even bought a copy of [babel edit](https://www.codeandweb.com/babeledit) to to easily add some google translations.

What's left to do is extracting the translations from the templates. I really would appreciate some help!!! It's not terribly complicated, but it's starting to annoy me as it is taking so much more time than anticipated.... :)

You can check the last couple of commits on how to do it. So any volunteers?

**Comment by johannesjo** [comment]
Puh! Feature is there and available in the snap edge channel. Please let me know what you think!
