### ISSUE TITLE
Gitlab 403 error when selecting an issue which is on todays list

### ISSUE THREAD

**Issue by tunguskar** [johannesjo/super-productivity#3300]
### Your Environment

- Version used: 9.0.5
- Operating System and version:  Windows 22H2

### Expected Behavior

When I select an issue (which was put on the todays list from gitlab) I want to see the ticket without an 403 error

### Current Behavior

I get this error:

![image](https://github.com/user-attachments/assets/f7ec2c45-4039-4cc4-b604-5dc5a1f99e4b)

### Steps to Reproduce (for bugs)

Just select the issue. But this worked already

### Can you reproduce this reliably?

yes

### Console Output

![image](https://github.com/user-attachments/assets/e700b9e4-44aa-4b0b-8e03-1222e1626ee9)

### Error Log (Desktop only)

This log is not really about the issue I think, a second step.

![image](https://github.com/user-attachments/assets/5283e2da-168a-4a7e-9d3a-014598909c00)

**Comment by tunguskar** [comment]
I have more information it looks like the link used is incorretct:

![image](https://github.com/user-attachments/assets/48f4b644-cb2c-423d-9e9e-6ddc66339c02)

my project is internal and I have setup the token.

for example this link gives the error  403:  
![image](https://github.com/user-attachments/assets/9bc5ccf3-a872-49c5-a463-68187fb45310)

if I use the iid it works

**Comment by johannesjo** [comment]
Thank you! I'll have a look!

**Comment by BanditsBacon** [comment]
Yeah after some digging and testing. This what i found and i think it's what @tunguskar wrote. 

The URL which throws the 403 error 
`https://gitlab.com/api/v4//issues/{ISSUEID}?page=1&per_page=100`

But issues are related to a particular project.  And in this Project the Issue has a iid: which is the issues project id. 
```
"id": 111111111,
      "iid": 1,
      "project_id": 1234567,
```

`https://gitlab.com/api/v4//issues/111111111?page=1&per_page=100` The response is 403

With the added Project (where the Issue belongs) and the global ID 
`https://gitlab.com/api/v4/projects/1234567/issues/111111111` The response is 404


The url which works 
`https://gitlab.com/api/v4/projects/1234567/issues/1`

**Comment by johannesjo** [comment]
Great job @BanditsBacon ! Would you maybe like to provide a PR for this! I'd much appreciate it!!

**Comment by BanditsBacon** [comment]
I'm not that familiar with Typescript but I can have a look at it. I wanted to do it anyway to implement Gitlab issues with Super later on :)

**Comment by johannesjo** [comment]
That is great to hear! Please let me know if you have any questions!

**Comment by johannesjo** [comment]
Hey @BanditsBacon how is it going? Can I assist you in some way? :)

**Comment by BanditsBacon** [comment]
> Hey @BanditsBacon how is it going? Can I assist you in some way? :)
 Hi @johannesjo sorry The last 2 weeks have been pretty hectic. So I only managed to get a small overview.
One question. Is there a reason why the URLs are assembled? For a gitlab issue, an array with links is provided by the API, which also returns the self url.

But yeah I hope next week I have a little bit more time

**Comment by johannesjo** [comment]
> One question. Is there a reason why the URLs are assembled?

I don't really know unfortunately. Most of the changes to the gitlab integration haven't been done by myself :(

**Comment by BanditsBacon** [comment]
Okay. I try to take a look this week. Is there anyway to contact you, like discord, or is this (issue comments) the preferred way?

**Comment by johannesjo** [comment]
Not using discord very much (only when gaming), so email would be ideal for me: contact@super-productivity.com

**Comment by johannesjo** [comment]
Did you send me an email already? haven't found anything in my inbox...

**Comment by BanditsBacon** [comment]
> Did you send me an email already? haven't found anything in my inbox...

no sry but now :)

**Comment by johannesjo** [comment]
I had a look at the feature and it seems like a lot of GitLab stuff is not working anymore. So I had the plan to throw out all advanced features like source and scope, that I don't quite understand (not using GitLab much myself currently) and to start fresh from there with a more basic, but working feature set.

Are you alright with this @d-r-e @hosseinkhaledi @cbergmann @BanditsBacon ?  Input and help with this would be very welcome!

**Comment by ngulden** [comment]
I'd love to have a working GitLab integration back.

I can't create any issue in SuperProductivity from GitLab anymore and have to manually copy and paste stuff. That's not how I expect an integration to work.

On console, I get the following message:

```
09:58:21.094 › Frontend Error: {
  HANDLED_ERROR_PROP: 'Gitlab: Http failure response for https://$GITLAB_FQDN/api/v4//issues/22629?page=1&per_page=100: 403 Forbidden'
} null
```

I use the Debian package for SuperProductivity 10.2.3.

I think my issue relates here.

**Comment by johannesjo** [comment]
This will be fixed with the next release.
