### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by huangulo** [johannesjo/super-productivity#3307]
### Steps to Reproduce
1. Installed docker version on aws ec2 x86
2. created a task with 2 tags
3. Started tracking for about 20 -30 min
4. Paused the task
5. got the error
![Screen Shot 2024-07-30 at 7 38 00 AM](https://github.com/user-attachments/assets/b108190f-2e97-4112-8832-0f9690d655c6)

### Console Output
RangeError: Maximum call stack size exceeded
canReportError (http://100.64.75.200:8130/node_modules/rxjs/_esm2015/internal/Observable.js:48:12)toSubscriber (http://100.64.75.200:8130/node_modules/rxjs/_esm2015/internal/Observable.js:28:136)call (http://100.64.75.200:8130/node_modules/rxjs/_esm2015/internal/operators/mergeMap.js:18:18)toSubscriber (http://100.64.75.200:8130/node_modules/rxjs/_esm2015/internal/Observable.js:26:26)call (http://100.64.75.200:8130/node_modules/rxjs/_esm2015/internal/operators/take.js:21:18)toSubscriber (http://100.64.75.200:8130/node_modules/rxjs/_esm2015/internal/Observable.js:26:26)call (http://100.64.75.200:8130/node_modules/rxjs/_esm2015/internal/operators/throwIfEmpty.js:13:18)toSubscriber (http://100.64.75.200:8130/node_modules/rxjs/_esm2015/internal/Observable.js:26:26)innerSubscribe (http://100.64.75.200:8130/node_modules/rxjs/_esm2015/internal/operators/takeUntil.js:14:20)toSubscriber (http://100.64.75.200:8130/node_modules/rxjs/_esm2015/internal/Observable.js:26:26)
META: SP9.0.7 Browser – en-US – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

### Meta Info
META: SP9.0.7 Browser – en-US – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

**Comment by johannesjo** [comment]
Can you reliably reproduce this and if so, could you please provide some more logs for it (when you open up the console via ctrl+shift+i there should be more)? I never encountered this before.
