### ISSUE TITLE
[Feature Request] Manually confirm starting next pomodoro break

### ISSUE THREAD

**Issue by kocisl** [johannesjo/super-productivity#333]
Hello @johannesjo ,

the app is overall great. Could you consider implementing a new feature "Manually confirm starting next pomodoro break" ? I tend to forget breaks, because the app is not focused when break starts (the beep sound is not enough). Also sometimes I want finish something and postpone break for a few minutes.

It could work same as current feature "Manually confirm starting next pomodoro session".

**Comment by johannesjo** [comment]
Hey there! Thanks for opening this up! I'm open to Pull Requests on this matter :)

**Comment by Dulkraw** [comment]
Hello @johannesjo ,

Just to second kosisl request and add something else,

I believe that it would be great to consider as well to add an option similar to "Focus to app window when reminder is active" when the pomodoro session finished something like "Focus to app window when the pomodoro session finished" 

![Cap3turar](https://user-images.githubusercontent.com/63562079/79079822-a0bbf080-7cce-11ea-8d0e-bf9ebabb844b.PNG)

With an option like that plus the "Manually confirm starting next pomodoro break"  I feel that it would be less likely for me and of other people to forget when they are on break time.

But overall your app works like a charm, thanks a lot for your efforts and best regards!

**Comment by tribly** [comment]
I'd really like to see this implemented, too. Manually starting breaks is way more convenient when you need to finish something in the current pomodoro.

Awesome software btw: Discovered it yesterday and immediately adopted it!

**Comment by nkrot** [comment]
I was about to ask for exactly the same when I found this description. thanks @kocisl fpr bringing this up.

I would like to have this feature as well as I tend to skip the breaks. And with "Manually confirm starting next pomodoro session" being on, i never press "back to work" (because I dont even see this dialog, as it is on another workspace) and have time untracked.

**Comment by jasyn** [comment]
@johannesjo It's in progress for now. I'll keep you posted!

**Comment by nkrot** [comment]
HI @jasyn . any progress on this feature?

I abandoned using super productivity (because its pomodoro timer is only partially usable) but will give SP a chance when this feature is implemented. hence my asking :)

**Comment by jasyn** [comment]
Hi, apparently life decided to be quite eventful lately. I also overestimated my knowledge of the Redux pattern. By the end of this week I should be able to open a PR. I'll eventually notify you if I'm unable to finish by then.

**Comment by jasyn** [comment]
Hi @johannesjo, this is my first Github pull request, please _don't_ go easy on me :)

**Comment by nitaicharan-webera** [comment]
I also would like to have this feature.
