### ISSUE TITLE
Two ways of enabling project backlog but only one of them works

### ISSUE THREAD

**Issue by sm8ps** [johannesjo/super-productivity#3330]
### Your Environment

- Version used: 9.0.6 (Snap)
- Operating System and version: Ubuntu 24.04
- Desktop Environment: KDE

### Expected Behavior

A) The project backlog can be activated from the project overview page ("Projektübersicht") when accessing the settings for individual projects and checking "Activate project backlog".

B) The same can be done by clicking on the three dots menu for an individual project in the side panel and selecting settings. Among the basic settings ("Grundeinstellungen") also is "Activate project backlog".

I expect both these setting to do what they say. Thus they should both result in the same effect. Furthermore their actions should be in sync with each other.

### Current Behavior

A) seems to do just nothing. Nor does it activate the backlog nor does it influence the setting from B).

B) does what it says. However it does not affect A).

So in effect, A) seems to be simply moot.

### Steps to Reproduce (for bugs)

Go through A) or B), respectively as described above. Happens reliably.

### Console Output

No warnings or error messages.

### Error Log (Desktop only)

Nothing relevant at all.

**Comment by johannesjo** [comment]
Thank you very much! A fix will be out with the next release!

**Comment by sm8ps** [comment]
Great, thanks for solving this issue so quickly and -- as always -- thanks for this great application!
