### ISSUE TITLE
Consistent language selection list

### ISSUE THREAD

**Issue by DimenDie** [johannesjo/super-productivity#3332]
Ensure that the language selection list remains the same for every language, as currently, the labels change when the language is switched.

Current Behavior:
The labels for languages change based on the selected language.

Expected Behavior:
The language selection list should display the same options regardless of the current language setting.

Current:
![Screenshot_1](https://github.com/user-attachments/assets/4bd0c84b-c082-4abe-8faa-a81b8a356c88)

Expected:
![Screenshot_2](https://github.com/user-attachments/assets/8697ab81-204e-4bed-bbd7-d6a7b18bb397)

If a monolingual person accidentally selects the wrong language, it would be difficult for them to find and revert to their native language. This can lead to a frustrating user experience.

**Comment by StDensity** [comment]
Hey @johannesjo I would love to work on this, can you tell me where to start?
