### ISSUE TITLE
403 Forbidden when syncing with GitLab

### ISSUE THREAD

**Issue by Nootaku** [johannesjo/super-productivity#3334]
### Steps to Reproduce

1. Link GitLab project and pull issues
2. Open task (=issue) additional info
3. GitLab pull results in 403 Forbidden

It is also unable to sync time (don't know if it is related)

### Error Log (Desktop only)

Seems to be linked to time sync.

```
[2024-08-09 14:34:43.662] [error] Frontend Error: {
  HANDLED_ERROR_PROP: 'Gitlab: Http failure response for https://gitlab.com/api/v4/projects/<project_name>/issues/151156482/time_stats: 404 OK'
} undefined
[2024-08-09 14:34:43.667] [error] Frontend Error Stack: 
```

### Console Output

```
GET https://gitlab.com/api/v4/issues/151155486?page=1&per_page=100 403 (Forbidden)
```
```
gitlab-api.service.ts:396 q0 {headers: i, status: 403, statusText: 'OK', url: 'https://gitlab.com/api/v4/issues/151155486?page=1&per_page=100', ok: false, …}
```

### Meta Info
Manjaro Linux Version 9.0.6 - SNAPD [source](https://snapcraft.io/install/superproductivity/manjaro)

**Comment by BanditsBacon** [comment]
It's the same like the #3300

**Comment by johannesjo** [comment]
Closing this as duplicate.
