### ISSUE TITLE
Overly aggressive reminder: "not been tracking time"

### ISSUE THREAD

**Issue by Avispa** [johannesjo/super-productivity#3335]
I want to use _superProductivity_ mainly as a task -- not time -- tracker; though time tracking may be a nice feature. However this aggressive pop-up is distracting and already annoying and I didn't even added a single task yet.

### Expected Behavior
Option do disable the reminder or _**bare minimum**_ respect when I click _Dismiss_ and don't bug me 2 minutes later again!

### Current Behavior
Every 2 minutes a `You have not been tracking time for ${X}m`

 (**Side note:** there is a space missing between the number and the time unit.)

### Steps to Reproduce (for bugs)
1. Scroll options for 2 minutes -- because you look for an option do disable that reminder.

### System
- Version used: 9.0.7 (latest at date of post)
- Operating System and version: Windows

**Comment by johannesjo** [comment]
You can already configure this to your liking under settings/time tracking reminder :) But I agree that the default should maybe be higher.
