### ISSUE TITLE
Auto-Save/-Update constantly steals focus

### ISSUE THREAD

**Issue by Avispa** [johannesjo/super-productivity#3336]
### Current Behavior
Not only steals focus for a moment **repeatedly** but also, when focus returns finally, puts cursor at the end of the line.

### Expected Behavior
Don't steal focus OR just make it a simple manual save button as like it is even on some other view(s) of the app.

### Steps to Reproduce (for bugs)
1. Go to Project settings.
2. Unfold _Theme_ tab.
3. Copy paste an URL
4. Try to change backslash to forward-slash or wise versa.

IMHO besides the obvious UX problem this notificiation shouldn't have been gained focus in the first place. Furthermore there is no need to update the settings every 1 second(s).

**Comment by johannesjo** [comment]
What version are you using? This should be fixed/improved upon in the newer releases.
