### ISSUE TITLE
Crashing when I delete any project.

### ISSUE THREAD

**Issue by D06E** [johannesjo/super-productivity#334]
Error: Uncaught (in promise): TypeError: Cannot read property 'ids' of null TypeError: Cannot read property 'ids' of null at t. (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_5.0.10.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.cfd129edbdae78597c9e.js:1:3246074) at file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_5.0.10.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.cfd129edbdae78597c9e.js:1:3236137 at Object.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_5.0.10.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.cfd129edbdae78597c9e.js:1:3236242) at a (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_5.0.10.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.cfd129edbdae78597c9e.js:1:3234979) at t.invoke (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_5.0.10.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.a2375273f96a7891a691.js:1:9294) at Object.onInvoke (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_5.0.10.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.cfd129edbdae78597c9e.js:1:1068113) at t.invoke (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_5.0.10.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.a2375273f96a7891a691.js:1:9234) at e.run (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_5.0.10.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.a2375273f96a7891a691.js:1:4394) at file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_5.0.10.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.a2375273f96a7891a691.js:1:16317 at t.invokeTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_5.0.10.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.a2375273f96a7891a691.js:1:9978)
archiveTaskIdsToDelete (webpack:///src/app/features/project/store/project.effects.ts:486:53)
Ur (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_5.0.10.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.cfd129edbdae78597c9e.js:1:3236137)
Ur (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_5.0.10.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.cfd129edbdae78597c9e.js:1:3236242)
Ur (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_5.0.10.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.cfd129edbdae78597c9e.js:1:3234979)
invoke (webpack:///node_modules/zone.js/dist/zone.js:386:29)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:27871:32)
invoke (webpack:///node_modules/zone.js/dist/zone.js:385:35)
run (webpack:///node_modules/zone.js/dist/zone.js:143:46)
zone.scheduleMicroTask (webpack:///node_modules/zone.js/dist/zone.js:891:37)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:421:34)
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone.js:832:38)
function (webpack:///node_modules/zone.js/dist/zone.js:739:20)
Ur (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_5.0.10.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.cfd129edbdae78597c9e.js:1:3234997)
invoke (webpack:///node_modules/zone.js/dist/zone.js:386:29)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:27871:32)
invoke (webpack:///node_modules/zone.js/dist/zone.js:385:35)
run (webpack:///node_modules/zone.js/dist/zone.js:143:46)
zone.scheduleMicroTask (webpack:///node_modules/zone.js/dist/zone.js:891:37)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:421:34)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:27859:32)
META: Electron – de – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.0.10 Chrome/80.0.3987.158 Electron/8.2.0 Safari/537.36

**Comment by johannesjo** [comment]
Thanks for reporting! I'll have a look!

**Comment by johannesjo** [comment]
I think I found the cause and a fix. Will be out with the next release. Thank you again and please let us know if the issue reoccurs!

**Comment by D06E** [comment]
Wow, that was quick, nice! Grüße nach Berlin!
