### ISSUE TITLE
Add Sparkle updater or similar for macOS version

### ISSUE THREAD

**Issue by unikitty37** [johannesjo/super-productivity#3345]
## Problem Statement

I have just launched the macOS version of superProductivity, and the about window says it is version 8.0.5. But version 9.0.7 was released two weeks ago.

Having to go to the website, download the .dmg, open it, quit superProductivity, drag the copy from the DMG to the Applications folder, confirm the overwrite, unmount the DMG, delete the DMG, and reopen superProductivity reduces my productivity. So does having to keep checking the website for new releases. 

## :grey_question: Possible Solution

If superProductivity used Sparkle, it would poll the release feed and pop up a window giving the version number and release notes each time there was a release (it supports preferences for only showing stable releases). The user can skip that release, dismiss the window and be reminded 24 hours later, or click Install Update. That downloads and unpacks the update and displays a confirmation dialog; when the user clicks the button on that dialog, it quits superProductivity, installs the update, relaunches superProductivity, and cleans up after itself.

## :arrow_heading_up: Describe alternatives you've considered

You can avoid having to manually check for new releases by subscribing to release emails on the project, but this also sends emails for alphas and betas as GitHub doesn't have a way to filter these out. The emails also get lost in the mass of _other_ emails — and the download and install steps are still manual.

## :heavy_plus_sign: Additional context

I'm not 100% sure if Sparkle supports Electron apps or is only for native Mac apps — but this is the kind of update workflow superProductivity should have, even if it doesn't use Sparkle.

**Comment by UsamaKarim** [comment]
You can use homebrew until update mechanism is added.
