### ISSUE TITLE
RPM Build for the latest release

### ISSUE THREAD

**Issue by intothebeans** [johannesjo/super-productivity#3358]
## Problem Statement

The main website for super productivity has a link to a non-existent RPM build for the latest release.

## :grey_question: Possible Solution

Add an RPM build to the latest release, or remove the broken link from the main website.
## :arrow_heading_up: Describe alternatives you've considered

Currently using an older version which does have an RPM build.

**Comment by johannesjo** [comment]
Should be fixed now.
