### ISSUE TITLE
Allow Multilevel Subtasks

### ISSUE THREAD

**Issue by sunnylake180** [johannesjo/super-productivity#3362]
## Problem Statement
Sometimes a subtask is large enough that I want to break it further into subtasks while retaining the original subtask.

## :grey_question: Possible Solution
Modify the addsubtasks so that it no longer enforces creating subtasks for only top level tasks and can create hierarchical lists.

## :arrow_heading_up: Describe alternatives you've considered
Adding subtasks at the same level increases the time estimate for the top level task, and so requires deleting the previous subtask in order to split it into multiple subtasks.  
## :heavy_plus_sign: Additional context
If someone more familiar with the code could provide a guide for how to make this change I may try to make a PR.

**Comment by johannesjo** [comment]
Closing this as duplicate.
