### ISSUE TITLE
Got it while increasing the notifications sound in iphone(web app)

### ISSUE THREAD

**Issue by manimaran990** [johannesjo/super-productivity#3370]
### Your Environment

- Version used: 
- Operating System and version:
- Desktop Environment: 
- Browser Name and version: 

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by johannesjo** [comment]
Thanks for reporting! I think this should be fixed with the next upcoming release. Please let me know if it isn't.
