### ISSUE TITLE
Tasks in Planner get lost

### ISSUE THREAD

**Issue by marcogeue** [johannesjo/super-productivity#3375]
### Your Environment

- Version used: Super Productivity 9.0.7 deb-package
- Operating System and version: Ubuntu 22.04
- Desktop Environment: Gnome

### Expected Behavior

I am testing the new Planner-feature, that I am generally enjoying a lot. I planned a few tasks for the next days and expected them to be saved for my next session. I planned them without a fixed time. So I dropped them in the top area where you see "No tasks" if it is empty. 

### Current Behavior

I experienced it now at least two times, that the planned tasks are lost when I open Super Productivity the next time. I shut down the program in the normal way by closing my day and getting sure that everything seems to be synced with my WebDav.
The tasks themselves are still there. So I can find them in the projects that they are related to. But they don't appear in the Planner anymore.

### Console Output

No Console Error

**Comment by johannesjo** [comment]
Hey hey! Do the tasks have a project assigned to them? And if so, can you find them in the project list?

**Comment by marcogeue** [comment]
Yes, I wrote that under 'Current Behaviour'. I had projects assigned to the tasks and they still appear in the project list - so they are not lost. Just not visible in the planner anymore.

**Comment by johannesjo** [comment]
> Yes, I wrote that under 'Current Behaviour'. I had projects assigned to the tasks and they still appear in the project list - so they are not lost. Just not visible in the planner anymore.

Ah sorry. Overread that part :) Do the tasks in the project list still have that little calendar icon with a date on it, when that happens?

I tried several scenarios, but was unable to reproduce this. Can you somehow reliably reproduce this with certain steps?

**Comment by johannesjo** [comment]
Also possibly related #3402

**Comment by marcogeue** [comment]
Thank you for your replies! 
The problem is not appearing anymore. Maybe after the last updates. All tasks stay in the planner-
I am enjoying the new features a lot! Thanks a lot @johannesjo
