### ISSUE TITLE
Error on project delete

### ISSUE THREAD

**Issue by xyn8935** [johannesjo/super-productivity#338]
### Your Environment

* Version used: 
* Operating System and version:
* Desktop Environment: 
* Browser Name and version: 

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by johannesjo** [comment]
Thank you very much! Could you give few more details?

**Comment by xyn8935** [comment]
every I delete my created project, it will throw a error, and superproductivity will exit,
my environment is
Ubuntu 19.10
Gnome 3.34
Do you need a screen record video?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Johannes Millan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月18日(星期六) 晚上9:12
收件人:&nbsp;"johannesjo/super-productivity"<super-productivity@noreply.github.com&gt;;
抄送:&nbsp;"¤火¤龙¤"<790466536@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [johannesjo/super-productivity] it remind me to report ,so I report it (#338)





 
Thank you very much! Could you give few more details?

**Comment by johannesjo** [comment]
I think I found the issue. The fix should be out with the next release. Thanks again!
