### ISSUE TITLE
RC versions not being handled by the AUR publish action

### ISSUE THREAD

**Issue by alosarjos** [johannesjo/super-productivity#3380]
Well, it's been a while since I helped with the AUR publishing action for Arch Linux :D

Looks like version 10.rc.0 was published and the code on the action didn't handle the rc part correctly, since it's only looking for numbers and dots.

To be honest I'm not 100% sure there won't be a problem versioning packages with this kind of custom naming (Not sure if Arch will handle correctly version 10 being newer than 10-rc.0) but I guess we can give it a try?

I will submit a PR to just grab whatever is set on the version field instead of looking just for numbers, since right now, the AUR installation is broken since it's looking for the 10.0.0 .deb file which doesn't exists.

If you go back to numbering without RCs, this PR should work just as fine as before. Just let me know if you decide to give a try to validate :D

Congrats on the 10.0 release!!!

**Comment by johannesjo** [comment]
Thank you very much @alosarjos ! Yes, I agree! Let's just try and adjust if necessary :)

**Comment by alosarjos** [comment]
Let me know if there is any issue :D
