### ISSUE TITLE
Where can I find tasks that were marked and completed and were cleaned from my screen after clicking on the 'FINISH DAY' btn?

### ISSUE THREAD

**Issue by Eyaltor** [johannesjo/super-productivity#339]
Questions:
Where can I find tasks that were marked and completed and were cleaned from my screen after clicking on the 'FINISH DAY' btn?

On another note - I really love the app and I use it daily. Thanks for this amazing community!

**Comment by johannesjo** [comment]
Hi! I am happy to hear that you like it! 

You can find under worklog which you can access by 
1. opening the menu (click on the burger icon)
2. hover over a project or tag (this includes "Today") where you worked on this task 
3. click on the 3 vertical dots to the right
4. click on worklog

Hope this answers your question!

**Comment by Eyaltor** [comment]
That helped, thanks!
