### ISSUE TITLE
UI is not optimised for tablets 

### ISSUE THREAD

**Issue by yerc** [johannesjo/super-productivity#3419]
### Steps to Reproduce

1.Install android app from F-droid in Samsung Galaxy Tab running One UI 6.1 then run app.
2.Icons, menu items are cut out although they seem to function normally.
![Screenshot_20240908_051934_Super Productivity](https://github.com/user-attachments/assets/28b26ab7-288d-4e1b-b60f-144c1c148371)
![Screenshot_20240908_052100_Super Productivity](https://github.com/user-attachments/assets/a65c1403-08de-4f87-a6e7-7e448efb3dc8)

The web app is not impacted by this issue.

**Comment by yerc** [comment]
Nevermind. Not an issue with the app, but caused by tablet display settings customisation

**Comment by Shahin-rmz** [comment]
Hello,
just wanted to thank for the app.
have the same issue regarding UI in Tablet. Else it works fine. Thanks

**Comment by johannesjo** [comment]
You're welcome @Shahin-rmz ! Probably also a configuration issue would be my first guess?

**Comment by Shahin-rmz** [comment]
> You're welcome @Shahin-rmz ! Probably also a configuration issue would be my first guess?

Not sure if I'm missing something in configs.
But whenever I want to close the focus window or go to settings in ablet, I should split the screen.
Tablet name: Lenovo Idea Tab


![Screenshot_20260316-133331.png](https://github.com/user-attachments/assets/40329310-44a2-4950-a4f5-e9632f2b257b)

**Comment by Shahin-rmz** [comment]
With last release of April the first Fdroid Channel, the problem has been solved. Thanks.

**Comment by johannesjo** [comment]
Thank you @Shahin-rmz !
