### ISSUE TITLE
Crash when minimized

### ISSUE THREAD

**Issue by MoizRed** [johannesjo/super-productivity#3423]
i dont know what happened but the latest update made the app crashes/closes everytime i minimize it .
system : ubuntu.

**Comment by MoizRed** [comment]
resolve ASAP pls.

**Comment by johannesjo** [comment]
There was an addition that probably caused this: 
https://github.com/johannesjo/super-productivity/pull/3394

@uinstinct can you maybe have a look?

**Comment by Puskchan** [comment]
I have a similar problem!

**Comment by suabo** [comment]
I have the same problem, please provide a fix or solution for this problem!

**Comment by suabo** [comment]
Thank you for the fix!

**Comment by Stardusstt** [comment]
same here

ver: 10.0.2
system : windows 11
