### ISSUE TITLE
App crashing when minimising

### ISSUE THREAD

**Issue by tgarul** [johannesjo/super-productivity#3431]
### Your Environment

- Version used: 10.0.2
- Operating System and version: windows 10

### Expected Behavior

App minimises to system tray 

### Current Behavior

App crashes

### Steps to Reproduce (for bugs)

Click the minimise button

### Can you reproduce this reliably?

Yes

**Comment by johannesjo** [comment]
Hey hey! This should be fixed with v10.0.4!
