### ISSUE TITLE
Undo delete attachment

### ISSUE THREAD

**Issue by rotu** [johannesjo/super-productivity#344]
### Your Environment
* Version used: 5.0.10
* Operating System and version: Ubuntu Focal
* Desktop Environment: LightDM
* Browser Name and version: N/A

### Expected Behavior
There should be a way to undo deleting an attachment. After deleting an attachment, maybe ctrl-z should restore the attachment.

### Current Behavior
Deleting an attachment is a one-click operation and there is no obvious way to undo it.

This may be part of a more general transaction log and undo feature. It makes sense to, e.g. allow undoing notes changes even after the user has tabbed out of the notes box.

**Comment by johannesjo** [comment]
Thank you for opening this up! Makes definitely sense to have that. Not sure when I will get to it, as there is lots of other stuff on the plate. In the meantime Pull Requests are welcome! 

A better Undo/Redo System would be pretty nice too. I experimented with that in the past, but decided to leave things as they are, as it was impacting performance by quite a bit.

**Comment by rotu** [comment]
I'm sure you're busy. This is a super awesome project with LOTS of amazing features! I'd love to give back, though I'm afraid I'm not able to do so right now.

**Comment by johannesjo** [comment]
No worries. I am sure I get to it at some point. :)
