### ISSUE TITLE
"Task complete" pitch adjusted even before completing any tasks

### ISSUE THREAD

**Issue by OctaveLarose** [johannesjo/super-productivity#3444]
### Your Environment

- Version used: snap 10.0.4
- Operating System and version: Ubuntu 22.04
- Desktop Environment: i3

### Expected Behavior
The pitch adjust to start off at 0 each day.

### Current Behavior

It seems to me that these days when I first finish a task during the day, the pitch when completing a task has already been set to some value, and the sound that plays is higher pitched than it should be. This takes away the satisfaction of completing many tasks in a day, since it quickly plays very high pitched sounds even when not so many tasks have been completed. 

It may be a feature, however? Or maybe just my imagination. I would be surprised if it was, however.

### Steps to Reproduce (for bugs)

1. Start the app 
2. Complete a task

### Can you reproduce this reliably?

It has happened every day for - I believe - a few weeks now.

**Comment by OctaveLarose** [comment]
I'm not sure... if it also considers done subtasks from previous days, then maybe! Would that be the intended behavior though?

**Comment by johannesjo** [comment]
Sub tasks is (although debatable ;)) but yeterday's tasks should not. Problem is that I am unable to reproduce this behavior. Could you maybe provide an (anonymousized, if you like)   export of your data, so i can check with that? You can send it to contact@super-productivity.com

**Comment by OctaveLarose** [comment]
Seems fine today, so I'm not sure I can reproduce my own error either! This is confusing. I'll see if it happens again, consider the issue in limbo for now..

**Comment by OctaveLarose** [comment]
It's been over a month and I still can't reproduce the behavior. I'm confused, but closing the issue!
