### ISSUE TITLE
Time Bug

### ISSUE THREAD

**Issue by StructSeeker** [johannesjo/super-productivity#3446]
2 The date display is wrong when time is not provided:
![Screenshot_20240912_103922_Super Productivity](https://github.com/user-attachments/assets/da842f0f-deac-47cf-baf3-9895aa5ae191)
Note 9/19 contrast 9/20

**Comment by johannesjo** [comment]
Did you install the latest update of the android app?

**Comment by StructSeeker** [comment]
> Did you install the latest update of the android app?

Yes, Currently 10.0.4

**Comment by johannesjo** [comment]
No i mean really the latest version from the play store. 10.0.4 refers only to the frontend (it is a bit complicated :)).

**Comment by StructSeeker** [comment]
> No i mean really the latest version from the play store. 10.0.4 refers only to the frontend (it is a bit complicated, and I should improve on that :)).

I have un-installed the F-Droid version and install the mist recent Google store version. The time now can be edited. I shall remove it from the issue. The date display problem still remains.

**Comment by johannesjo** [comment]
You're right. I fixed those too.
