### ISSUE TITLE
Tags in subtasks cannot be removed

### ISSUE THREAD

**Issue by franco-ruggeri** [johannesjo/super-productivity#3454]
Previously, it was possible to edit tags in subtasks by pressing the keyboard shortcut (G). Now, the keyboard shortcut opens the tags of the parent items. The result is that it is possible to add tags to subtasks (with the inline syntax) but not to remove them.

I don't know which version bump caused it, but the problem appeared recently.

### Your Environment

- Version used: 10.0.4
- Operating System and version: Web app (on macOS)
- Desktop Environment: Web app
- Browser Name and version: Safari 17.5

### Expected Behavior

Pressing the keyboard shortcut (G) on a subtask should open the subtask tags.

### Current Behavior

Pressing the keyboard shortcut (G) on a subtask opens the (parent) task tags.

### Steps to Reproduce (for bugs)

1. Create a task
2. Create a subtask
3. Add a tag to the subtask with the inline syntax
4. Press G while the focus is on the subtask

<img width="1309" alt="image" src="https://github.com/user-attachments/assets/87f05ac0-c34c-40e9-88b6-286fe0d5466f">

### Can you reproduce this reliably?

Yes.

**Comment by johannesjo** [comment]
Thanks for reporting! This will be included with the next release!
