### ISSUE TITLE
How to delete the headline.

### ISSUE THREAD

**Issue by Nu1i** [johannesjo/super-productivity#3455]
![image](https://github.com/user-attachments/assets/b297b592-7fa5-47ca-a989-058331f123af)
How to delete this ? I feel this very useless.

**Comment by johannesjo** [comment]
Currently you can't hide this. I suppose you are not using any estimates? Probably should hide the bar if there is no estimate or timespent at all.

**Comment by johannesjo** [comment]
Will be addressed with the next release.
