### ISSUE TITLE
"No remote data found. Upload local to Remote?" keeps popping up

### ISSUE THREAD

**Issue by dwiehoff** [johannesjo/super-productivity#3473]
## Your Environment

Version used: 10.0.4 (10.0.4)
Operating System and version: macOS Sonoma 14.6.1 (23G93)
Desktop Environment: i5 (2018)

## Expected Behavior

After setting sync settings up as follows, the app syncs all data with the local file without interruption/notifications.

<img width="587" alt="image" src="https://github.com/user-attachments/assets/9478b52d-e8c3-4c7a-a870-58a41185b2fc">

## Current Behavior

I get a popup every time the app attempts syncing, asking me if I want to upload local to remote.

<img width="321" alt="image" src="https://github.com/user-attachments/assets/7d4dd7e4-4606-47b4-93c2-eadf9ce5b47c">

## Steps to Reproduce (for bugs)

1. Start the app
2. Set sync settings as seen above
3. Restart app (or don't)
4. Wait for the app to sync

## Can you reproduce this reliably?

Just downloaded and setup the app, it keeps popping up. Even when restarting the app, this popup is the first thing I get to see.

**Comment by johannesjo** [comment]
Are you also on a mac @sweetman-zz ?

**Comment by johannesjo** [comment]
I think the problem is that there is no error shown, even though it should (I am working on a fix). For now setting a valid existing absolute folder path like `/home/your-user-name` should work.

**Comment by johannesjo** [comment]
I also improved the whole situation by providing a directory picker when there is no valid directory selected.
