### ISSUE TITLE
Javascript Error in Main Process- Windows

### ISSUE THREAD

**Issue by jasco1224** [johannesjo/super-productivity#35]
Javascript error message appears. Cannot edit,delete or switch between projects.

## Your Environment
* Versions used: 1.4.0 - 1.5.2
* Operating System and version: Windows 10 1607 (multiple computers)

## Expected Behavior
No errors appear after launching the product. Able to edit, delete and switch between projects. 

## Current Behavior
After launching the following error appears: 

A JavaScript error occurred in the main process
Uncaught Exception:
  TypeError: "file" argument must be a non-empty string
  at normalizeSpawnArguments (child_process.js:392:11)
  at exports.spawn (child_process.js:499:38)
  at Object.exports.execFile (child_process.js:220:15)
  at Object.module.(anonymous function) [as execFile] (ELECTRON_ASAR.js:200:20)
  at exports.exec (child_process.js:150:18)
  at childProcess.(anonymous function) (ELECTRON_ASAR.js:684:22)
  at module.exports
(C:\ Users\ sandstrj\AppData\ Locai\ Programs\ superProductivity\resources\ app.asar\ electr ... :3)
  at Timeout.trackTimeFn [as _on Timeout]
(C:\ Users\ sandstrj\AppData\ Locai\ Programs\ superProductivity\resources\ app.asar\ electr ... :3)
  at ontimeout (timers.js:469:11)
  at tryOnTimeout (timers.js:304:5)
  at Timer.listOnTimeout (timers.js:264:5)

## Steps to Reproduce (for bugs)
1. Launch the product

**Comment by johannesjo** [comment]
Thanks for reporting! I'll look into it!

jasco1224 <notifications@github.com> schrieb am Di., 28. Nov. 2017, 23:23:

**Comment by johannesjo** [comment]
Do you have automatic backups enabled (you can check this on the settings page)?

**Comment by dfcrosby** [comment]
I get the javascript error with automatic backups disabled (the default setting) and even after it is enabled.  This occurs even when I use the web app, export the data and then import it into the desktop app.  I am also on Win 10 v.1607 build 14393.1770 using super-productivity version 1.5.2
See insert.  
![jscript error](https://user-images.githubusercontent.com/7945112/33379824-2ac68e76-d4e7-11e7-8ac5-a3337057f0f8.png)

**Comment by johannesjo** [comment]
@dfcrosby thanks! That's very helpful in narrowing it down. I think I found the error. Currently there is no idle time tracking on windows platform (haven't figured out a way to do so yet). I publish a fixed version soon.

**Comment by dfcrosby** [comment]
I also note that the time tracking does not work.  I can click on the start time tracking (play) button and it changes to a pause button, but no time is recorded and no time tracking bar appears.

**Comment by jasco1224** [comment]
Thanks for looking into this issue.  I experience the issue on a fresh install so automatic backups would be disabled in that case. I'll wait for a new build, test and get back with you. Your help is much appreciated.

**Comment by johannesjo** [comment]
@dfcrosby I pulbished a new version. Hopefully that issue is then also fixed. If not: Could you please open a new issue about this?

**Comment by johannesjo** [comment]
https://github.com/johannesjo/super-productivity/releases

**Comment by jasco1224** [comment]
The error no longer appears so this issue seems to be fixed.  I'm still unable to switch between or delete projects that I create. I'll open another issue shortly. Thanks again.
