### ISSUE TITLE
 Frontend Error Stack: Error: TypeError: Cannot read property 'keyboard' of undefined

### ISSUE THREAD

**Issue by jsenciso** [johannesjo/super-productivity#350]
TypeError: Cannot read property 'keyboard' of undefined
e.call [as _tapNext] (file:///snap/superproductivity/596/resources/app.asar/dist/webpack:/src/app/features/config/store/global-config.effects.ts:67:74)
e._next (file:///snap/superproductivity/596/resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/operators/tap.js:45:27)
e.next (file:///snap/superproductivity/596/resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:53:18)
e._next (file:///snap/superproductivity/596/resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/operators/filter.js:38:30)
e.next (file:///snap/superproductivity/596/resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:53:18)
e._next (file:///snap/superproductivity/596/resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/operators/filter.js:38:30)
e.next (file:///snap/superproductivity/596/resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:53:18)
e.next (file:///snap/superproductivity/596/resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subject.js:47:25)
e.call [as _next] (file:///snap/superproductivity/596/resources/app.asar/dist/webpack:/node_modules/@ngrx/store/__ivy_ngcc__/fesm5/store.js:405:28)
e.__tryOrUnsub (file:///snap/superproductivity/596/resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:192:16)

**Comment by bonedaddy** [comment]
Getting the same issue as well

OS:

```
NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os
```

Version: 5.0.14

**Comment by johannesjo** [comment]
Thank you! Closing this in favor of #349
