### ISSUE TITLE
When scheduling a task for today with the option menu (right-click), it's not toggling the today state

### ISSUE THREAD

**Issue by panoramix360** [johannesjo/super-productivity#3518]
### Your Environment

- Version used: **10.0.9** 
- Operating System and version: **MacOS 14.6.1**

### Expected Behavior

When clicking on the `Schedule Today` after right clicking a task should toggle the `Today` state of a task.

### Current Behavior

Currently, the above is making the `Today` state stack on the task, I don't know if this was intended.

<img width="1008" alt="image" src="https://github.com/user-attachments/assets/11f791be-5134-446b-aa50-3e7b5af3b019">

### Steps to Reproduce (for bugs)

1. Create a simple task.
2. Right click on it.
3. Select the `Schedule Today` option
4. Select the `Schedule Today` option again to see that it doesn't toggle.

### Can you reproduce this reliably?

Yes.

**Comment by panoramix360** [comment]
If this was in fact not the intention, can I contribute and try to work on it?

**Comment by johannesjo** [comment]
That would be great @panoramix360 ! Thank you!
