### ISSUE TITLE
DropBox sync in 2 devices doesnt work

### ISSUE THREAD

**Issue by hadarbas** [johannesjo/super-productivity#3520]
### Steps to Reproduce

.i set dropbox sync on mac with the key.
used the same key on chrome browser on iPhone but it doesn't work. got the attached message.
how can I sync among the devices?

![image](https://github.com/user-attachments/asse
![370350472-b583fa7c-73ac-4d53-877b-2ef7fccf5ae7](https://github.com/user-attachments/assets/bd9933f2-54ee-4825-8e0e-db08ec005c45)
ts/f7c2d966-92fa-4b8d-b06b-670526e0e440)

Thread
https://github.com/johannesjo/super-productivity/discussions/3517

**Comment by hadarbas** [comment]
So how do I sync different devices?

**Comment by johannesjo** [comment]
You enable dropbox sync on both devices and enter the different codes you obtained from their websites through the dialog in super productivity.

**Comment by hadarbas** [comment]
Thanks, it worked.
