### ISSUE TITLE
How to connect to GitLab/GitHub issues

### ISSUE THREAD

**Issue by phellarv** [johannesjo/super-productivity#3523]
Hi,

I cannot find any documentation on how to do this, whatsoever.

If I have missed, then I apologise for the nagging.

regard
Per-Arne

**Comment by ChristianHuff-DEV** [comment]
There is some documentation [here](https://github.com/johannesjo/super-productivity/blob/master/docs/github-access-token-instructions.md). But it seems to be out-dated. The mentioned scope `api` for GitHub doesn't exist (anymore?). Neither for new nor classic tokens.
I therefore was also unable to integrate with GitHub.

**Comment by rommeswi** [comment]
You can only create a project and integrate with this particular project.
Indeed it would be desirable to be able to pull just all of your gitlab/github repos at once and not have to each time set up the integration manually.

**Comment by johannesjo** [comment]
@phellarv please use discussions for questions like these:
https://github.com/johannesjo/super-productivity/discussions

**Comment by beedell-roke** [comment]
https://github.com/johannesjo/super-productivity/issues/156#issuecomment-609768552 appears to demonstrate that solely importation is possible.
