### ISSUE TITLE
A Type Error, which urges me to report here

### ISSUE THREAD

**Issue by Sayinore** [johannesjo/super-productivity#353]
### Your Environment

* Version used: Web App 5.0.15
* Operating System and version: MS Win10
* Desktop Environment: 
* Browser Name and version: Mozilla Firefox 76.0

### Expected Behavior
Shows the very one of my projects properly, just what the app does for other projects

### Current Behavior
The lower layer of the page seems to be just working properly. However there is a msgbox overriding it and says:
`P/e< (https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1:5719)
P (https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1:5693)
67Y//s</e.prototype._next (https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1:102814)
FFOo/l</e.prototype.next (https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1:438587)
K9Ia/d</e.prototype.next (https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1:501479)
S5bw/l</e.prototype.nextInfiniteTimeWindow (https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1:935697)
next (https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1:1425076)
FFOo/d</e.prototype.__tryOrUnsub (https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1:440695)
FFOo/d</e.prototype.next (https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1:439840)
FFOo/l</e.prototype._next (https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1:438916)
FFOo/l</e.prototype.next (https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1:438587)
15JJ/d</e.prototype.notifyNext (https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1:34834)
rPjj/i</e.prototype._next (https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1:1562099)
FFOo/l</e.prototype.next (https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1:438587)
ad02/s</e.prototype._next (https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1:1212723)
FFOo/l</e.prototype.next (https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1:438587)
67Y//s</e.prototype._next (https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1:102912)
FFOo/l</e.prototype.next (https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1:438587)
26FU/a</e.prototype._subscribe (https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1:45188)
6blF/u</t.prototype._trySubscribe (https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1:108705)`
The msgbox is like this: ![The Msgbox](https://user-images.githubusercontent.com/11678293/80810618-d598d480-8bf6-11ea-8583-e43fbb8bf9c1.png)

### Steps to Reproduce (for bugs)

1. Open the very one of my projects.
2. Look at the screen.

### Console Output
`Task data not found for uCtw6iqgv main.708e94a41db9291af4bd.js:1:1445032
    o https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    x https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    x https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    p https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    memoized https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    ut https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    h https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    memoized https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    o https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _subscribe https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _trySubscribe https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _trySubscribe https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    subscribe https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _subscribe https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    subscribe https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    call https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    subscribe https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    call https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    subscribe https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    a https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _innerSub https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    nextInfiniteTimeWindow https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    __tryOrUnsub https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    nextInfiniteTimeWindow https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    __tryOrUnsub https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    notifyNext https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _subscribe https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _trySubscribe https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _trySubscribe https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    subscribe https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _subscribe https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    subscribe https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    call https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    subscribe https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    call https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    subscribe https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    call https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    subscribe https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    call https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    subscribe https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    a https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _innerSub https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    nextInfiniteTimeWindow https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    __tryOrUnsub https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    stateSubscription https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    __tryOrUnsub https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _tryNext https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    observe https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    dispatch https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _execute https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    execute https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    flush https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    schedule https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    schedule https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    schedule https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    scheduleMessage https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    dispatch https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _setActiveContext https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    s https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    s https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    X https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    t https://app.super-productivity.com/polyfills.7edae71eed3180374236.js:1
    X https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _setActiveContext https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    t https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    __tryOrUnsub https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    notifyNext https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    r https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _trySubscribe https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    subscribe https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    a https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _innerSub https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _tryNext https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    processNavigations https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    __tryOrUnsub https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    notifyNext https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    notifyNext https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    r https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _trySubscribe https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    subscribe https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    call https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    subscribe https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    a https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _innerSub https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    notifyNext https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    notifyNext https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    next https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _complete https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    complete https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _complete https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    complete https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _complete https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    complete https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    r https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    _trySubscribe https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    subscribe https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    call https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
    subscribe https://app.super-productivity.com/main.708e94a41db9291af4bd.js:1
` An incomplete screenshot: 
![firefox_N7yGMTVlW1](https://user-images.githubusercontent.com/11678293/80810856-4cce6880-8bf7-11ea-80ef-bdbbec2cfb74.png)

**Comment by Sayinore** [comment]
Well I am quite sorry for that. I just somehow created a null task (maybe through my frequently google disk syncing). And I found that if I open a project that worked well first and open the not working project second, the error would occur; while if I just directly open the not working one, the app would tell me to delete one null task and once I follow it, the app went normal again.
All in all, if someone sees this error, just **directly open your error-occuring project**. **Follow the guide** which tells you to delete one of the tasks. And you will get a wonderful smoothly-working, splendid, powerful, lovely SuperProductivity App again :).

**Comment by johannesjo** [comment]
Thank you very much for taking your time to report this! I have encountered this error myself before during development, but so far I haven't found the reason which leads to the lists info being out of sync with the data for the single tasks. I'll keep an eye open for now.
