### ISSUE TITLE
Please make the app portable. 

### ISSUE THREAD

**Issue by rgfx** [johannesjo/super-productivity#3553]
I no longer install app, my windows builds last longer this way.

**Comment by johannesjo** [comment]
This is already addressed:
https://github.com/johannesjo/super-productivity/releases/tag/v10.0.11
https://github.com/johannesjo/super-productivity/releases/download/v10.0.11/superProductivity-10.0.11.exe

(check the exe without the setup  suffix).

**Comment by rgfx** [comment]
This isn't truly portable as files get added to 

`C:\Users\[user]\AppData\Roaming\superProductivity`

I'll deal with it though, thank you.
