### ISSUE TITLE
[Feature Request] Azure DevOps Boards

### ISSUE THREAD

**Issue by FilBot3** [johannesjo/super-productivity#356]
# Feature Request

How hard or what would it take to make Super Productivity work with Azure DevOps Boards?

**Comment by johannesjo** [comment]
Hey! Thanks for opening this up. I think basic support should be pretty doable if there is an api to access everything. You can have a look [here](https://github.com/johannesjo/super-productivity/tree/master/src/app/features/issue/providers) to see how its done for the other issue providers. A simpler approach is used for github and gitlab while the jira integration allows for a little bit more complex interactions (e.g. such as worklogs).

Let me know if you have any questions.

**Comment by FilBot3** [comment]
I've been working with the REST API a little bit in Python, so I imagine this could be done up in NodeJS or Electron. I'll see what I can start learning about NodeJS or Electron to get that in there.

**Comment by FilBot3** [comment]
I've started a development thread on the [Spectrum Chat]{https://spectrum.chat/super-productivity/questions/development-beginner-questions~5d2333a9-2cd1-484d-9258-1a5abb521861} for this Feature Request as well. Just so we're not cluttering this thread.

**Comment by johannesjo** [comment]
I should mention that all the github and gitlab integration happens in the browser layer. So it's more basic web frontend development than node.js.

**Comment by FilBot3** [comment]
I guess I need to learn more about how to do Front-end Development then.

**Comment by johannesjo** [comment]
Please let me know if I can help you in any way.

**Comment by FilBot3** [comment]
Yeah, my learning of JavaScript and thus TypeScript is slow going. So, if someone else has the technical capability, that would be a huge boon to this request. As much as I want to use this tool with my work for Azure DevOps, I cannot.

**Comment by johannesjo** [comment]
The new feature can be tested here:
https://f316ea51.super-productivity-preview.pages.dev/#/tag/TODAY/tasks

Feedback would be very welcome!

**Comment by rklec** [comment]
Is there also a exe for testing with self-hosted instances? As I guess the web version has no access to it?

Some feedback already: the setup screen mentions "org" twice, it's a little unclear whether you really need it entered twice. And yes, I know URLs of Azure DevOps are annoyingly complicated.

https://learn.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-7.2#components-of-a-rest-api-requestresponse-pair mentions the "original" terms one may refer to:
> The request URI, in the following form: VERB https://{instance}[/{team-project}]/_apis[/{area}]/{resource}?api-version={version}
>
> *    instance: The Azure DevOps Services organization or TFS server you're sending the request to. They are structured as follows:
>      * Azure DevOps Services: dev.azure.com/{organization}
>      *  TFS: {server:port}/tfs/{collection} (the default port is 8080, and the value for collection should be DefaultCollection but can be any collection)


NotIce the default URL for the old TFS is `{server:port}/tfs/{collection}`  so by default somehow even more confusing.

<img width="586" height="256" alt="Image" src="https://github.com/user-attachments/assets/91858017-8d83-4869-be8f-255b6d065cd2" />

<img width="562" height="231" alt="Image" src="https://github.com/user-attachments/assets/3bffd10a-c7ad-4499-81b7-7e66970a7139" />

**Comment by rklec** [comment]
Okay no you indeed need to *duplicate* the "organisation" or you mean "team project" (as per the URL path above).

Also got a HTTP 400 error when trying to access the URL of a self-hosted instance (Azure DevOps Server 2022.2 (AzureDevopsServer_20250331.1)). URL: https://***ORGANISATION_URL_FROM_ABOVE***/_apis/connectionData?api-version=6.0

```json
{"$id":"1","innerException":null,"message":"The requested version \"6.0\" of the resource is under preview. The -preview flag must be supplied in the api-version for such requests. For example: \"6.0-preview\"","typeName":"Microsoft.VisualStudio.Services.WebApi.VssInvalidPreviewVersionException, Microsoft.VisualStudio.Services.WebApi","typeKey":"VssInvalidPreviewVersionException","errorCode":0,"eventId":3000}
```
<img width="543" height="350" alt="Image" src="https://github.com/user-attachments/assets/c4440f3c-afd1-4e2f-8792-b28b1944b801" />

As per https://learn.microsoft.com/en-us/azure/devops/integrate/concepts/rest-api-versioning?view=azure-devops#supported-versions and https://learn.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-7.2#api-and-tfs-version-mapping 2022 should support v6.0 in theory, but I have no idea, apparently it's anyway still in preview here?

**Comment by rklec** [comment]
Oka ytetsing turns out the `/_apis/connectionData` does only work:
* with `?api-version=1.0`
* or... with no API version at all provided (either leave the query parameter empty or do not provide it at all)

I guess maybe that single API is versioned and does not have a newer version?
