### ISSUE TITLE
Make shortsyntax configurable

### ISSUE THREAD

**Issue by johannesjo** [johannesjo/super-productivity#3560]
Would be cool to have a config section to configure which prefixes of the short syntax are active.

### Discussed in https://github.com/johannesjo/super-productivity/discussions/3551

<div type='discussions-op-text'>

<sup>Originally posted by **ugandacup** October  6, 2024</sup>
Hello,
since I recently did an update on the app I suffer a annoying problem:
When I create a new task, where I type "+", followed by any other character it is being moved into the inbox.
The default project for new tasks is set to "none".
How do I fix this?</div>

**Comment by stavby** [comment]
I can't recreate this, when I have the default project as none and create tasks in "Today", they don't enter any project, they only enter inbox when I write +i which I think is the wanted behavior.
Either way, I thought I'd add a toggle in settings to turn off the feature to add the task to a project by using +<project name>, what do you think?

**Comment by stavby** [comment]
Awesome, working on it, can you assign it to me please?

**Comment by stavby** [comment]
@johannesjo Yay my first PR was merged :)
You can close this issue now

**Comment by johannesjo** [comment]
Thank you! That's a great addition :)

**Comment by mathisgauthey** [comment]
Hey there, where can I configure the short syntax in the config ? @stavby 

Thanks for the feature !

**Comment by stavby** [comment]
Hi!
It's here in the settings, under misc:
![Screenshot_20250110_115440_Chrome](https://github.com/user-attachments/assets/e87cf4d6-7c4c-4416-ab8e-6eb1b1433e32)

**Comment by mathisgauthey** [comment]
Oh sorry I thought we were able to configure the character used, hence my question !

Thanks, I do have that all activated o/
