### ISSUE TITLE
Feature: Add Confirmation Dialog for Deletion Operations to Prevent Accidental Task Removal

### ISSUE THREAD

**Issue by jiongxuan** [johannesjo/super-productivity#3561]
## Problem Statement
Currently, when deleting a task—whether by pressing the Backspace key or performing a long press deletion—there is no secondary confirmation dialog. This lack of confirmation can lead to accidental deletions, which are irreversible.

## :grey_question: Possible Solution
Implement a confirmation dialog for deletion and other potentially destructive operations. Ideally, when a user attempts to delete a task, a popup should appear asking for confirmation before the action is finalized. 

Alternatively, allow the task to be deleted immediately but display a temporary notification (such as a snackbar) at the top of the screen that offers an option to undo the deletion.

## :arrow_heading_up: Describe alternatives you've considered
- **Undo Functionality:** Implementing an undo feature that allows users to revert deletions within a short time frame. However, this approach may require managing an operation cache, which could increase complexity.
- **Keyboard Shortcuts:** Providing alternative keyboard shortcuts for deletion that are less prone to accidental activation.
- **Deletion Safeguards:** Introducing safeguards such as requiring users to hold the Backspace key for a certain duration before a deletion is triggered.

## :heavy_plus_sign: Additional context
If implementing the confirmation dialog is feasible, I am willing to allocate time to develop this feature once the solution is confirmed. I believe adding this safeguard will enhance the user experience by preventing accidental loss of tasks. Open to discussing other potential solutions that may better address this issue.

**Comment by johannesjo** [comment]
Maybe we can make this configurable? Not sure. Personally I like the undo/snack approach that is currently implemented (that doesn't seem to be working for you???), but it is not working well for multiple deleted tasks, which we ideally should improve on.

Another option would be adding a trash can (that we only show if there are deleted tasks).

**Comment by jiongxuan** [comment]
@johannesjo  You're right!

I took another look and found the undo option—it was hiding at the bottom because I’m in full-screen mode. My bad for missing that earlier. 🤦‍♂️

I appreciate you considering the trash can idea, but I agree keeping things simple with the undo feature is the way to go. I’m going to go ahead and close this issue.

Thanks again for your help!
