### ISSUE TITLE
The pomodoro alarm doesn't work [bug]

### ISSUE THREAD

**Issue by Eyaltor** [johannesjo/super-productivity#357]
### Your Environment
Windows Chrome (both latest versions)
SuperPorducitvity version: 5.1.0

### Expected Behavior
It should be a ring at the end of the 25min session

### Current Behavior
No sounds and it automatically skips to the next 25min session

### Steps to Reproduce (for bugs)
1. Active Pomodoro option in the settings
2. Run 25min session

Note:
I think it's related to the version updates as it worked well a few days ago.

Screenshot attached.
![Pomodoro issue](https://user-images.githubusercontent.com/37452642/81042260-6520da80-8eb8-11ea-83e9-0f8aac3450eb.png)

Thanks!

**Comment by Eyaltor** [comment]
It's now working for some reason (very weird as I didn't change anything). Closing the bug

**Comment by johannesjo** [comment]
Thanks for reporting. Might be some rare race condition. Please let me know if it occurs again.
