### ISSUE TITLE
[Windows] App description too long in Task manager

### ISSUE THREAD

**Issue by anantoghosh** [johannesjo/super-productivity#3581]
I've updated from Super Productivity 9 to 10 and noticed the description used by windows, which is used in task manager and taskbar settings for the app is too long which I believe was not intentional.

In Task manager:
![image](https://github.com/user-attachments/assets/4bcc1770-311d-42ba-91e7-b435576d9d5c)

In Systray Icon Settings:
![image](https://github.com/user-attachments/assets/fc47d573-634f-463b-a9ce-74d7ff4ed6dc)

### Your Environment

- Version used: 10.0.11 via scoop
- Desktop Environment: Windows 11 23h2

### Expected Behavior

It used to be just "Super Productivity".

**Comment by johannesjo** [comment]
That's not ideal :D thanks for reporting!

**Comment by johannesjo** [comment]
Thank you very much @Rubal0990 !
