### ISSUE TITLE
Max indent 1: really?

### ISSUE THREAD

**Issue by mvtab** [johannesjo/super-productivity#3590]
## Problem Statement
Parent tasks can only have subtasks, and subtasks can't have further subtasks.
This makes it unfit to manage any kind of complex project or tasks.

## :grey_question: Possible Solution
Increase subtask indenting.

## :arrow_heading_up: Describe alternatives you've considered
Will just use another application until this is implemented here. 
All other features are pretty cool, but the problem described here is a **major** deal breaker.

**Comment by Jagdfalke** [comment]
You could use "Projects" to manage your actual projects. Then there's also the possibility to use tags.

**Comment by johannesjo** [comment]
Using notes, you also have infinite levels of additional subtasks:

```
- [ ] some sub task
- [ ] some other sub task
```
