### ISSUE TITLE
Cannot Start the App "TypeError: Cannot read property 'taskIds' of undefined"

### ISSUE THREAD

**Issue by NaveenAIFanatic** [johannesjo/super-productivity#361]
[log.log](https://github.com/johannesjo/super-productivity/files/4600137/log.log)

### Your Environment

* Version used: 
* Operating System and version: Windows
* Desktop Environment: Yes
* Browser Name and version: Desktop version

### Expected Behavior
Open the Application successfully.

### Current Behavior
Gives an error "TypeError: Cannot read property 'taskIds' of undefined"

### Steps to Reproduce (for bugs)

1. Added tasks to with daily reminders.
2. App started crashing automatically.

**Comment by johannesjo** [comment]
Thank you very much for reporting! May I ask if you are using the windows store version or the custom installer?

**Comment by NaveenAIFanatic** [comment]
I’m using the windows store version.

________________________________

**Comment by johannesjo** [comment]
Thank you! I'll check this.

**Comment by johannesjo** [comment]
Just checked. This should already be fixed with the latest release. Please let me know if it works for you with the latest version.
