### ISSUE TITLE
Crash when trying to select a date to add additionnal time

### ISSUE THREAD

**Issue by marcantoinem** [johannesjo/super-productivity#362]
### Your Environment

* Version used: 5.1.1  with deb and snap
* Operating System and version: KDE Neon Unstable
* Desktop Environment: KDE Plasma

### Expected Behavior
The app doesn't crash when I try to add time done before and I select a date.

### Current Behavior
The app crash on linux when choosing a date in add time spent for other day. Tried with deb and snap and it crash, but on the web it doesn't.

### Steps to Reproduce (for bugs)
1. Create a task
2. Right click and select Time Tracking.
3. Left click on add time spent for other day.
4. Left click on the calendar to choose time.

### Console Output
RangeError: Incorrect locale information provided
e.format (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/@angular/material/__ivy_ngcc__/fesm5/core.js:748:23)
t.periodButtonText (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/@angular/material/__ivy_ngcc__/fesm5/datepicker.js:1298:22)
templateFn (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/@angular/material/__ivy_ngcc__/fesm5/datepicker.js:1422:44)
executeTemplate (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:7706:9)
refreshView (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:7583:13)
refreshComponent (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:8739:9)
refreshChildComponents (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:7376:9)
refreshView (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:7629:13)
file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:8675:21
META: SP5.1.1 Electron – fr – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.1.1 Chrome/80.0.3987.163 Electron/8.2.3 Safari/537.36

**Comment by johannesjo** [comment]
Thank you very much for reporting. This should be fixed with v5.1.2.

**Comment by marcantoinem** [comment]
Perfect, I've tried v5.1.2 and it solves my problem

**Comment by marcantoinem** [comment]
On snap it doesn't app anymore by with the deb, it continue.

**Comment by johannesjo** [comment]
@marcantoinem I don't understand. Do you mean the issue persists when using the deb file??

**Comment by marcantoinem** [comment]
When I install the application with deb the fix doesn't work, but if it's installed with snap the fixes work.

**Comment by johannesjo** [comment]
Could you please check both of the versions (on the global settings page)? It's it 5.1.2 for the Deb as well?

**Comment by marcantoinem** [comment]
Yes if you want the new crash informations with the 5.1.2 deb
`RangeError: Incorrect locale information provided
e.format (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/@angular/material/__ivy_ngcc__/fesm5/core.js:748:23)
t._formatValue (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/@angular/material/__ivy_ngcc__/fesm5/datepicker.js:2615:39)
t._onBlur (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/@angular/material/__ivy_ngcc__/fesm5/datepicker.js:2608:18)
listenerFn (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/@angular/material/__ivy_ngcc__/fesm5/datepicker.js:2643:314)
executeListenerWithErrorHandling (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:15075:16)
eventHandler (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:15116:22)
HTMLInputElement.apply (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/@angular/platform-browser/__ivy_ngcc__/fesm5/platform-browser.js:615:36)
t.invokeTask (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:421:35)
Object.onInvokeTask (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28273:33)
META: SP5.1.2 Electron – fr – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.1.2 Chrome/80.0.3987.163 Electron/8.2.3 Safari/537.36`

**Comment by marcantoinem** [comment]
I know what's happening, the snap was working and not the deb, because the snap was isolated and had a different configuration that wasn't generated from 5.1.1. I tried the appimage that picked my data from 5.1.1 and it also crashed, so I removed all my data in .config and the one installed with deb and the one installed with appimage stopped to crash. Maybe some librairie that cause the crash are saved in config and doing the update don't update them because they already exist.

**Comment by marcantoinem** [comment]
If I use the application(adding task), even if the old data was deleted, after adding task, it continue to crash.

**Comment by johannesjo** [comment]
My guess would be that this has to do with the language selected. What's the selected language for your OS and what language is selected in the settings of super productivity? Is it both french? And does it work if you select another language?

**Comment by marcantoinem** [comment]
Both are in french and if I switch to english it works.

**Comment by johannesjo** [comment]
How about other languages?

Sorry, that I am asking so many questions, but I am unable to reproduce the issue so far.

**Comment by marcantoinem** [comment]
Whenever I switch langage (tried french and german) from default it's at this moment that it start to crash, but if I switch to english after it continue to crash.

**Comment by marcantoinem** [comment]
I've keep my system langage in french, I only switch the langage of the app.

**Comment by johannesjo** [comment]
I think I found the issue! Thank you very much for your help. 5.1.3. should solve this.

**Comment by marcantoinem** [comment]
Awesome, I just updated to 5.1.4 and it works great. You're so fast to update.
