### ISSUE TITLE
[Bug] Pomodoro timer slows down in background

### ISSUE THREAD

**Issue by EgorBakanov** [johannesjo/super-productivity#363]
### Environment
* Version used: 5.1.1.0
* Operating System and version: Windows 10 1909

### Expected Behavior
The Pomodoro timer should work the same in the foreground and background.

### Current Behavior
Currently, the timer slows down a lot when the application runs in the background.

### Steps to Reproduce
To show the bug, I created 2 tasks, set the pomodoro timer to 5m and run it in the foreground for the first task and in the background for the second. Results shown below. Other apps used during testing did not change.

![image](https://user-images.githubusercontent.com/33174871/81534578-78d5b080-9392-11ea-8f17-7a99e9ad8ada.png)

**Comment by johannesjo** [comment]
Good catch! Thank you very much for reporting. I'll try to think of a solution.

**Comment by glima34** [comment]
The pomodoro timer stops for me.
I believe this has some relation to resource exhaustion on the machine, making the timer process stop.
Interestingly the time tracked for the activities counts normally, so perhaps using the time tracker for the timer functionality is the way to go

**Comment by johannesjo** [comment]
@glima34 yes! You're right about this. The time tracking works with actual differences as defined by the system clock, but the pomodoro timer just work with regular timeouts/intervals, which will slow down when the system or the app is idle.

I am pretty busy with some other pretty big features atm. so Pull Requests would be welcome!

**Comment by johannesjo** [comment]
This should be fixed with the next release. Please let me know if it isn't.
