### ISSUE TITLE
Cyrillic letter 'б' breaks string in the day evaluation

### ISSUE THREAD

**Issue by nomare** [johannesjo/super-productivity#3640]
### Steps to Reproduce

1. Click Finish Day.
2. Switch to the 2. Evaluate tab.
3. In the What hindered your productivity field type the text"абв". (you should type, not copy this text)
4. As result there are 2 strings "а" and "в".

### Expected Result
There should be one string "абв".

### Reason for Problem
Cyrilic letter 'б' is located on the ',' key in the English keyboard layout. The problem is that the program does not analyze the current keyboard layout and breaks the line when pressing the 'б' key.

**Comment by panoramix360** [comment]
I believe I can help fixing this issue.

Just need to configure a russian keyboard layout on my Macos.

**Comment by johannesjo** [comment]
That would be great @panoramix360  !

**Comment by panoramix360** [comment]
@nomare 

I fixed the issue on my last PR, probably will be available on the next release!
