### ISSUE TITLE
[Feature request] ]Time log and visualized metrics missed

### ISSUE THREAD

**Issue by mbostanara** [johannesjo/super-productivity#365]
Hi,
Thank you for developing such a great application.

I was wondering if it is possible to add a part to the application in which we can see the hourly plan of the day. I mean at the end of the day, something like a daily calendar appears and shows the tasks I have worked on through the day by its hour.

Also, I was wondering if some kind of visualisations could be added to the app in which it shows daily, weekly, and monthly pie charts showing how much time consumed for each project.

Thank you again

**Comment by johannesjo** [comment]
Hey there! Nice to hear that you like the app and thank you very much for your suggestion. A similar feature (for the daily overview) was implemented in a earlier version, but never worked really well. The time tracking model is bit limited as it only records the day and the time spent, but not when that's the case. There are two reasons for this: 1. It drastically reduces the amount of memory and disk storage being used. 2. One would either have to have a much more complicated UI for quick edits of time spent or disallow this completely.

I'm pretty open about implementing this again within the limitations of the model.  But I am not sure what the best way would be to do it and if it makes sense as an approximation of what actually happend. Suggestions would be very welcome!

The second suggestion is nice and maybe also a good first issue. Would you mind opening a new ticket for it?

**Comment by mbostanara** [comment]
Hi, thank you for your kind and complete answer. I appreciate your great support.
Sure, I will open a new ticket for my next suggestion.

**Comment by johannesjo** [comment]
As this probably won't happen, I am closing this. Thanks again for the suggestion though!
