### ISSUE TITLE
The app is not loading (browser version)

### ISSUE THREAD

**Issue by estux** [johannesjo/super-productivity#3651]
### Your Environment

- Version used: actual web version (cannot tell the release version as it's not loading)
- Operating System and version: Windows 10
- Desktop Environment: 
- Browser Name and version: Firefox 132

### Expected Behavior

The app should load and I should see my projects and tasks there.

### Current Behavior

The app is stuck on the pulsating logo and showing only productivity tips. 
I'm afraid to have lost all the tasks 😱
I hope I can recover them in some way!

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Console Output

TypeError: i.sync.localFileSync is undefined
    UUe migrate-global-config.util.ts:223
    tN migrate-global-config.util.ts:28
    ur persistence.service.ts:422
    o main-DUZ4F2RX.js:1
    invoke zone.js:331
    run zone.js:111
    i zone.js:2366
    invokeTask zone.js:356
    runTask zone.js:157
    Z zone.js:527
    invokeTask zone.js:436
    _ zone.js:1054
    x zone.js:1084
    K zone.js:1115
zone.js:2165:18

Also I have a lot of "migrations" messages like this:
[M] Migrating model "Project" to version from 6.02 to 6.14 
Object { ids: (7) […], entities: {…}, __modelVersion: 6.02 }
model-version.ts:36:12

**Comment by johannesjo** [comment]
Have you used an older version before? Does deleting all data for `app.super-productivity.com` help?

**Comment by estux** [comment]
@johannesjo yes, I used older versions and every time the upgrade was smooth. What do you mean for deleting all data (I want to preserve the tasks and projects 🙏)?
Thank you

**Comment by johannesjo** [comment]
I understand :) I thought you might have been a new or returning user, because it seems some part of your data is messed up a little. Do you have any backups anywhere? Otherwise it is possible, but a bit tricky to access your data.

But I will provide a workaround for your problem with the next release that will allow you to access your data.

**Comment by johannesjo** [comment]
> Do you think the problem could be related to a (too much) big jump between versions?

Possibly, though a bit unlikely if you're using the browser version maybe? Not sure tbh.

**Comment by estux** [comment]
Maybe because it's some time I don't open the tab of Super Productivity. It's open on a pinned tab that I don't visit often lately so maybe that's the reason it didn't migrate from one version to the next one every time.

**Comment by estux** [comment]
> Does it work now with the latest relase?

@johannesjo Hello Johannes, now it works, thank you so much for your fast solution! 
In the browser console there are only 2 errors about reminders related to missing tasks:
"Missing reminder 6FSvD9o6v from task not existing"

I already exported the json as a backup. Now can I continue to use the app in the browser or should I do something else (like starting fresh and then importing)?
Thank you!

**Comment by johannesjo** [comment]
That should be no problem. The error with the reminders can happen under specific circumstances, but is nothing to worry about :)

**Comment by estux** [comment]
Ok, thank you Johannes! As long as it's working I think you can close this issue now.
