### ISSUE TITLE
Android and desktop apps do not talk to each other 

### ISSUE THREAD

**Issue by jchoneandonly** [johannesjo/super-productivity#3655]
### Your Environment: Pop os, windows, and android 14 on pixel 7 pro.

 it seems the android app uses a separate json file from the desktop apps and thus they can't sync at least via Dropbox. They both access the correct folder, but they each create their own json file.i believe the desktop one is sp.json and the android phone makes one called sp-main.json or something.

-

**Comment by johannesjo** [comment]
Looks like you're on an old version for desktop. If you upgrade to the latest, all should work.
