### ISSUE TITLE
Package version no longer on the artifacts

### ISSUE THREAD

**Issue by alosarjos** [johannesjo/super-productivity#3656]
AUR packaging is failing because it's expecting the package version to be in the name of the artifact. Release 10.1.0 is the first one with this change in the artifact files naming, is this intentional? If it is, I can prepare a MR to fix the AUR publishing.

**Comment by johannesjo** [comment]
Thanks for letting me know @alosarjos ! Yes, this is intentional, since this way I can link to the latest version much easier.
