### ISSUE TITLE
Projects with background images taken from online (https URIs) cannot be opened or modified when offline

### ISSUE THREAD

**Issue by Dox-Dev** [johannesjo/super-productivity#3657]
### Your Environment

- Version used: 10.1.0 
- Operating System and version: MIUI 12.0.6 (Android 11)
- Desktop Environment: N/A 
- Browser Name and version: N/A 

### Expected Behavior

I should be able to interact with my projects even when offline. If my background images were taken externally using some HTTPS link, I'd expect it to default back to a backgroundless-image (or give us the option of setting an alternative local image file). I could then continue to update my tasks and allow my changes to sync the next time I have access to the internet.

### Current Behavior

When I lose connection to the internet, whether or not the Super Productivity application is already open on my phone, I won't be able to interact with my projects that were set with HTTPS background images. The moment I try to press one of those projects in the sidebar drawer, the application suddenly crashes and I'm forced to restart the application. This is reproducible, and so long as there's no internet connection, the issue continues to persist. If no background image link was set in a project, the issue does not occur and I can proceed to use it as normal.

The only contact I can make with these affected projects are through the "Today", "Schedule", and "Planner" parts of the drawer. In "Today", I can make new tasks and place them under the affected projects just fine using short formatting. As for "Schedule" and "Planner", I can see tasks related to these affected projects (including ones I just made through the "Today" tab). 

### Steps to Reproduce (for bugs)

1. Create 1 project and add a valid HTTPS background image.
2. Either close the application or keep it turned on. Open the application again if it was closed.
3. Turn off access to the internet.
4. Switch to the newly created project.
5. The application should crash immediately after, not even attempting to load the project.

### Can you reproduce this reliably?

Yes, I can reliably reproduce this on my phone using the steps I laid down above. I had recently downloaded this application from the Google Play Store (and even updated it just to check), so I'm pretty sure the issue is still within the latest release.

### Console Output

I'm not sure how to do that on Android, sorry.

**Comment by johannesjo** [comment]
Thank you very much for bringing this to my attention. A fix is underway and will be available with the next release.
