### ISSUE TITLE
Internal error committing transaction on pomodoro start

### ISSUE THREAD

**Issue by level6sam** [johannesjo/super-productivity#367]
### Your Environment

* Version used: 
5.1.1

* Desktop Environment: 
Elementary OS: Hera 5.1.2

### Expected Behavior

The task should start the timer, it was in pomodoro mode

### Current Behavior

Was starting a task on the start button on the task and was greeted with an error log asking me to copy the contents
The app then reset itself to its newly installed state and I have lost all the tasks and projects 

### Steps to Reproduce (for bugs)

1. Clicked run (start timer on a task)
2.
3.
4.

### Console Output

Error: Uncaught (in promise): UnknownError: Internal error committing transaction.
resolvePromise (file:///snap/superproductivity/610/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:832:39)
apply (file:///snap/superproductivity/610/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:739:21)
apply (file:///snap/superproductivity/610/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:755:37)
t.invoke (file:///snap/superproductivity/610/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:386:30)
Object.onInvoke (file:///snap/superproductivity/610/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28285:33)
t.invoke (file:///snap/superproductivity/610/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:385:36)
e.run (file:///snap/superproductivity/610/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:143:47)
apply (file:///snap/superproductivity/610/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:891:38)
t.invokeTask (file:///snap/superproductivity/610/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:421:35)
Object.onInvokeTask (file:///snap/superproductivity/610/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28273:33)
META: SP5.1.1 Electron – en-GB – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.1.1 Chrome/80.0.3987.163 Electron/8.2.3 Safari/537.36

**Comment by johannesjo** [comment]
Thank your very much for reporting! I hope you were able to restore your data!

Is there any chance that your hard drive might be out of space? I encountered this error once under these circumstances.

**Comment by johannesjo** [comment]
Probably related #236

**Comment by johannesjo** [comment]
I am closing this in favor of #236.

**Comment by johannesjo** [comment]
There is a possible fix out now. Please follow the discussion on #236.
