### ISSUE TITLE
Request: Add Multi-Architecture (ARM64) Support for Docker Image

### ISSUE THREAD

**Issue by dennysubke** [johannesjo/super-productivity#3694]
## Problem Statement  

The Docker image for **Super Productivity** does not support the `arm64` architecture. This limits its usability on devices like Raspberry Pi or other ARM-based servers, making it challenging for users on such platforms to benefit from the application.  

## :grey_question: Possible Solution  

Provide an ARM-compatible version of the Docker image. Ideally, this should be released as a **Multi-Architecture Docker Image** and uploaded to **Docker Hub**. This would ensure that users on both `arm64` and `amd64` architectures can seamlessly pull and use the image.  

## :arrow_heading_up: Describe alternatives you've considered  

- Building a custom ARM-compatible image manually, but this requires additional effort and expertise from users.  
- Using alternative applications, which is not ideal since **Super Productivity** is a preferred tool for many users.  

## :heavy_plus_sign: Additional context  

ARM support would help a broader range of users, particularly those running on Raspberry Pi or similar ARM-based systems. I'd be happy to assist with testing or provide feedback to support the development of an ARM-compatible image.  
Uploading the image as a Multi-Architecture Image to **Docker Hub** would simplify accessibility for all users.

**Comment by LuBashQ** [comment]
I can have a look at multi arch builds; I will let you know when I have something 👀

**Comment by dennysubke** [comment]
> I can have a look at multi arch builds; I will let you know when I have something 👀

Thank you so much! 👍

**Comment by LuBashQ** [comment]
Hi again! I have added the multi-arch build and tested it myself using `act` and pushing it to my local DockerHub. You can try the images from [here](https://hub.docker.com/repository/docker/cristianlupascu/super-productivity/tags). Let me know if it works fine on the raspberry Pi, as I do not have one (though I tested the images on an arm64 MacBook) 😊

**Comment by dennysubke** [comment]
Hi @LuBashQ  Thanks for the update! I tested it on my Raspberry Pi, and it works perfectly! 🎉 Great job!

**Comment by LuBashQ** [comment]
Awesome! Great to hear 😁

**Comment by johannesjo** [comment]
@LuBashQ I rarely use docker, so I am not very familiar with the requirements here. How should we proceed with this?
