### ISSUE TITLE
Unable to Switch Between (or Delete) Projects

### ISSUE THREAD

**Issue by jasco1224** [johannesjo/super-productivity#37]
## Your Environment
* Operating System and version: Windows 10 1607
* Browser Name and version: Chrome 62

## Expected Behavior
Typically a check box is seen in the upper left corner of the UI. Clicking this brings up a pick list of projects.  

Clicking settings --> manage projects --> delete (trash can), deletes a project 

## Current Behavior
No check mark appears in the upper left of the UI. Although the empty space is clickable, nothing happens when it is clicked.

![image](https://user-images.githubusercontent.com/34076836/33387341-3ec307c6-d4ea-11e7-9fe4-f1e203f3dc20.png)

When managing projects, you can click on the trash cans but the project does not delete.

When creating a new project clicking save creates the project but does not close the dialog.

## Steps to Reproduce (for bugs)

1. Click the switch project area in the upper left of the UI
2. Click the trash can next to a project on the manage projects screeen 
3.
4.

**Comment by johannesjo** [comment]
Thank you fo reporting. I'll work on it, once I'm back from vacation :)

**Comment by Morganamilo** [comment]
I have this issue too using the deb on Linux 4.13.12

I would just like to expand this a bit:
- Saving current project as todo adds an entry to the list
- Create new project brings up a window to create a new project, clicking save adds an entry to the list but does not close the window
- Clicking save multiple times adds many identical entries to the list
- Deleting and switching projects does nothing at all
- When I restart the program it seems to have forgotten all saved projects

I would try to fix this myself but I think its a little too much for me, hope these details help.

**Comment by johannesjo** [comment]
Thanks! I think I found the problem. Publishing a patch soon.

**Comment by jasco1224** [comment]
1.6.8 fixes this issue. Thanks for the great work!
