### ISSUE TITLE
Export Worklog seperated with semicolon

### ISSUE THREAD

**Issue by TomMargrave** [johannesjo/super-productivity#370]
### Environment
* Version used: 5.14
* Operating System and version: Win 10
* Desktop Environment:  N/A
* Browser Name and version: N/A

### Expected Behavior
When exporting work log there should be setting to choose delimiter.  Current delimiter is semicolon and most csv file are comma.
Recommend option in the setting to choose delimiter.

### Current Behavior
Currently everything is exported with semicolon and Excel is defaulted to comma.

### Steps to Reproduce (for bugs)
1.  Select project
2.  Left click on the project settings (three stacked dots).
3.  Select "Worklog"
4.  Select and click on Month or week export button.
5.  Click on the "Save to File" button

### Console Output
None

### Error Log (Desktop only)
None

**Comment by johannesjo** [comment]
Thank you very much for reporting! I am pretty busy with other stuff myself currently, but Pull Reqeusts would be welcome.
