### ISSUE TITLE
Export Worklog Titles are repeating Titles

### ISSUE THREAD

**Issue by TomMargrave** [johannesjo/super-productivity#371]
**Environment**

    Version used: 5.14
    Operating System and version: Win 10
    Desktop Environment: N/A
    Browser Name and version: N/A

**Expected Behavior**
When exporting work log the header is displaying  "Titles"   twice when the columns "Parent Task Titles only" and "Titles and Sub Task Titles" are selected.  
Recommend  change the default header names to the following

"Parent Task Titles only"  to  Titles
"Titles and Sub Task Titles" to  Title-SubTask

**Current Behavior**

When exporting work log the header is displaying  "Titles"   twice when the columns "Parent Task Titles only" and "Titles and Sub Task Titles" are selected.  

1.    Select project
2.   Left click on the project settings (three stacked dots).
3.   Select "Worklog"
4.   Select and click on Month or week export button.
5.   Add columns
5.   Click on the "Save to File" button

**Console Output**
None

**Error Log (Desktop only)**
None

![image](https://user-images.githubusercontent.com/24830664/81994284-7d5dcb80-9615-11ea-8ea1-c99bf6ee4396.png)

**Comment by johannesjo** [comment]
Thank you for opening this up. While I don't have any strong feelings about this I would be ok with this adjustment. Would you like to provide a PR yourself? You should be able to find anything you need inside the `src/assets/i18n` folder.

**Comment by johannesjo** [comment]
I am closing this  due to inactivity.
