### ISSUE TITLE
Add short syntax for tags

### ISSUE THREAD

**Issue by level6sam** [johannesjo/super-productivity#372]
### Your Environment

* Version used: 5.1.4 snap, .exe
* Operating System and version: Ubuntu Bionic base, Windows 10
* Desktop Environment:  Elementary OS Hera 5.1.2
* Browser Name and version:  Firefox 76.01

### Expected Behavior

I have created two tags, placing the "#" before the word, then a blue highlight showed they had been created. I have not been able to do this since. 

### Current Behavior

Instead of creating a tag in the tag area, I create a task with #something which in black plain text 

### Steps to Reproduce (for bugs)

1. Try to add a task in a project in the new task bar or in an existing task
2.
3.
4.

**Comment by johannesjo** [comment]
Thanks for opening this up. I'll definitely add this at some point.

**Comment by smalltimer** [comment]
That is a great idea! It helps to assign priorities to the tasks and implement a GTD framework.

**Comment by johannesjo** [comment]
I finally added this feature. I could use some help with the testing. A pre-release (5.5.0) should be available soon.

**Comment by smalltimer** [comment]
That is awesome! I should be able to give it a go on the weekend and give you some feedback.

**Comment by smalltimer** [comment]
Hi, just tested it and there was some unexpected behaviour. When adding tags it seems the case of the tags matters, but in an inconsistent way.

As you know, I use only four main tags - A, B, C and D. When I input #B and #b, both are assigned to the tag 'B' (don't know if this is a desired feature as case-sensitivity in the tags might be good). However, this behaviour is not consistent. E.g., when I use #A the tag is detected, but when I use #a it is not. Here's a screenshot to explain. Tasks starting in lower case were input with a tag in lower case (#a, #b etc.) and those starting with upper case were input with a tag in upper case (so #A, #B etc.).

_Fig: Behaviour of tags_
![HashTags](https://user-images.githubusercontent.com/14436654/87862224-082cb080-c94e-11ea-8dae-be44b8dd5369.png)

Also, have you used todo.txt by any chance? It might be a nice feature if there were shortcuts to assign not only tags, but also project and (getting ambitious) a scheduled deadline (date or date+HHMMSS). In a todo.txt you'd typically write something like: 'task to be done +Project1 +Project2 @ Tag1 @ Tag2 Due:19/06/2020' and usually the program parses it to mean: add 'task to be done' to Project1 and Project2. Assign it the tags Tag1 and Tag2. And set the scheduled date as 19/06/2020. 

Thank you for all the hard work! I had written some code (C++) which can parse stuff like that. Let me know if it might be of some use and I can send it across. I am sure there are lots of todo.txt style parses out there though.

**Comment by johannesjo** [comment]
Thank you for the feedback! I have a look. 

Thank you also for the offer. If the C++ stuff works reliably well we could try to add it as a Wasm module. Always wanted to try that out. Alternatively, we can directly port the code to JavaScript which would make changing it and adding new stuff a little bit easier. 

We only need to add the syntax for time estimates. For dates, something like [sugar.js](https://sugarjs.com/) might nice as well.

**Comment by Heart1010** [comment]
Sorry to ask - but I'm relativly new to Super Productivity and wondering how to use/add tags in general:
- when I add a task I can type "#mytag" and this tag is created 👍 (this also works for tags with spaces (e.g. "#long tag")
But how is the workflow to use the existing tags?
Say I add another new task - how to add an existing tag to that tag?
- drag&drop from left panel directly to the task do not work
- typing # and the first, 2nd, 3rd... character from an existing tag don't show me a list of the tags so I can add them to this task
- independently from the # character I type in a task - I also can't find anything in the GUI to be able to add a tag to a task? Say I click on an existing task - how to add a tag :worried: ?
![image](https://user-images.githubusercontent.com/1481680/88035522-94072e00-cb42-11ea-9196-81b89c7f6593.png)

So at the moment I saw only the possibility to add an existing tag to a task by typing the "#long tag name" explicitly by hand in a task title.
_update: I just saw when I added a first tag to a task I can click on that task and now I get GUI to enter additional tag names etc - but how to do that when the task has no tag until now?_

_(using windows version v5.5.0)_

**Comment by johannesjo** [comment]
@Heart1010 This is not the right place to ask your question as the discussion here is about something else. Could please open up a new issue or ask it [here](https://spectrum.chat/super-productivity).

**Comment by johannesjo** [comment]
@smalltimer we're you able to find the C++ code? :)

**Comment by smalltimer** [comment]
@johannesjo Sorry, I just came back this Monday from a short break! I'll look for it. I had a command-line todo.txt client at some point (before I started using your app ;) ) and the parsing was implemented there. I'll send you an invite to the repo in a message.

**Comment by smalltimer** [comment]
@johannesjo Can't get to your email. My repo is private on gitlab so will need to invite you.

**Comment by johannesjo** [comment]
Does contact@super-productivity.com work?

**Comment by smalltimer** [comment]
Cool. Sent you an invite. Let me know if it works. Remember I am not an actual programmer (I merely use it as a tool in my work) so my code is probably very simple and non-optimal.

**Comment by johannesjo** [comment]
Thank you! I'll check it out once I have a little bit more time on my hands.

**Comment by johannesjo** [comment]
Somehow I wasn't able to get access. Not sure why...
This my gitlab profile: https://gitlab.com/johannesjo

**Comment by smalltimer** [comment]
Gotcha. Added you again. Hopefully will work this time around.

**Comment by johannesjo** [comment]
Now it works! Thank you!

**Comment by smalltimer** [comment]
Yay!!

**Comment by johannesjo** [comment]
I am closing this in favor of #487  as the short syntax for tags is basically done.
