### ISSUE TITLE
Error with new tags - Inconsistent task state

### ISSUE THREAD

**Issue by fiatphos** [johannesjo/super-productivity#3728]
### Your Environment

- Version used: 10.2.3 (downloaded Super-Productivity-Setup.exe from the website)
- Operating System and version: Windows 10 22H2
- Desktop Environment: 
- Browser Name and version: 

### Expected Behavior

When adding a new tag, it should appear in the list of tags added to the task. In the example below, the tag 'testing' was made previously, while the tag 'someNewTag3' is a new tag.

![image](https://github.com/user-attachments/assets/e7fd1211-2cca-4387-9e9d-b9121e9503bc)

As expected, a window appears which asks whether the new tag should be created. I choose the 'Create Tag' option.

![image](https://github.com/user-attachments/assets/98394e6b-5e40-4c5f-837e-2b98e32461af)

### Current Behavior

The task is created only with the new tag 'someNewTag3'

![image](https://github.com/user-attachments/assets/76169725-66da-4068-b110-957f470ef17e)

Also, now if I delete this new task, I am unable to sync anymore as I get an error:

"unknown Sync Error: Error: unable to get valid app data"

![image](https://github.com/user-attachments/assets/184f4e78-7886-4fa2-be04-6fa9bc1f06cf)

And then, if I close the app and open it again, I get the error:

"Your data seems to be damaged ("Inconsistent Task State: Missing task id ldUVSDFlcslyRmuf23Ii7 for Project/Tag testing"). Do you want to try to automatically fix it? This might result in partial data loss."

![image](https://github.com/user-attachments/assets/c5b1fcb6-7e23-40e2-9c66-73fedcb9d560)

### Steps to Reproduce (for bugs)

1. Create new task while adding an existing tag and a new tag.
2. Delete the newly created task.
3. Sync fails. Close app and re-open.
4. "Inconsistent task state"

### Can you reproduce this reliably?

Yes.

Thanks for the software. It helps me everyday.

**Comment by johannesjo** [comment]
A fix will be out with the next release. Thank you very much!

**Comment by fiatphos** [comment]
Problem is resolved as of v.11.0.0 of Super Productivity 👍
