### ISSUE TITLE
Improve cask deployment for Mac

### ISSUE THREAD

**Issue by johannesjo** [johannesjo/super-productivity#373]
This should now be possible via github actions. PRs are welcome!

~~Currently brew cask deployment needs to be triggered manually (by someone, doesn't seem to matter who). It would be really cool to have an automated solution for this, though it's a bit tricky as the script needs a Mac to run...~~

**Comment by johannesjo** [comment]
We can now use github actions for this.

**Comment by cwerner1** [comment]
This would be nice:)
Today I've manually updated the cask with 
`brew bump-cask-pr  superproductivity --version 7.7.0 `
https://github.com/Homebrew/homebrew-cask/pull/113900

**Comment by hd-deman** [comment]
brew cask still outdate 7.9.2

**Comment by johannesjo** [comment]
I have no mac available currently, but if someone executes `brew bump-cask-pr superproductivity --version 7.10.1` the app should be updated.

**Comment by cwerner1** [comment]
updated to 7.10.1 
https://github.com/Homebrew/homebrew-cask/pull/118758

**Comment by johannesjo** [comment]
Thank you  @cwerner1 !

**Comment by cwerner1** [comment]
updated to 7.11.5
https://github.com/Homebrew/homebrew-cask/pull/122784
