### ISSUE TITLE
Repeat Option for Weekdays

### ISSUE THREAD

**Issue by benedict-robinson** [johannesjo/super-productivity#3765]
## Problem Statement

This is a very small suggestion - not a problem - but when selecting a repeat configuration, I would like there to be an option for "Weekdays" that selects Mon-Fri, but not Sat/Sun. I know this can be achieved using custom settings, but I would like to add it as a default option in the menu.

## :grey_question: Possible Solution

A new option could be added in the repeat configuration dropdown (`<select>`) called "Weekdays." This would automatically select Mon-Fri, excluding the weekend (Sat/Sun).

## :heavy_plus_sign: Additional Context

No other context at the moment. I would love to attempt this feature as it would be my first open source contribution! :)

**Comment by benedict-robinson** [comment]
Apologies - I've just noticed it is there under Monday to Friday. Not sure how I missed this

**Comment by johannesjo** [comment]
No worries :)
