### ISSUE TITLE
Random Pomodoros

### ISSUE THREAD

**Issue by johannesjo** [johannesjo/super-productivity#377]
@CokeClarke suggested:
"
Hello everyone! I didn't figure it out how to contact you directly (by e-mail or message) so I'm posting a comment here. It is just a small suggestion for "superproductivity", maybe you like it, maybe you don't.- Would you like to consider the possibility if including "random pomodoros"? That is, pomodoros of random duration between 21 and 29 minutes (for example).- Would you like to consider the possibility of including a "random machine" for the breaks? That is, a really simple machine where you can indicate some activities that you would like to do during your breaks (yoga, twitter, facebook, stretching, walking, free-thinking, listen to a particular song, have a coffe, etc. etc), you create this list and then, at breaks, you run this random machine and it will give you one activity for your 5 minutes break.

This "introduction of randomness" greatly helps our brain through the motivations/rewards mechanism (the dopamine bomb). If you would like to discuss this idea furthermore, I'm looking forward to!

I got my inspiration from Dan Ariely's book "Predictably irrational", and this article.

Best!
"

**Comment by johannesjo** [comment]
Hey @CokeClarke! These are wonderful suggestions. I especially like the one with the random activities. Currently I am pretty busy with improving syncing but after that I will try to think of a way to include your suggestions.

**Comment by CokeClarke** [comment]
I'm glad you liked the idea @johannesjo! I have zero experience with GitHub, but if I can be of any help, I'm in. 

  Best!

**Comment by prat0088** [comment]
Random pomodoros would be great, especially for those times when you have a giant list of things and are overwhelmed by where to start.

**Comment by johannesjo** [comment]
I still like the idea :)

**Comment by CokeClarke** [comment]
I really like the idea, that's why I mentioned it to you guys. Besides, now
I'm completely sure that it has cognitive benefits (Behavioral Sciences).

  I would like to contribute but I'm not a developper, and my skills as a
programmer are reduced to my skills as a Data Scientist, no more.

   In any case, if I can help (may be with the UX/UI, a bit) just let me
know.


     Best



Jorge Andrés Clarke De la Cerda
PhD in Applied Sciences
