### ISSUE TITLE
Improve Safari iFrame Mac behaviour

### ISSUE THREAD

**Issue by kerkenit** [johannesjo/super-productivity#378]
### Your Environment

* Version used: webapp
* Operating System and version: Mac OS X 10.5.4
* Browser Name and version: Safari 13.1

### Expected Behavior
Trying to load the web app inside a iFrame

### Current Behavior
The web app to not opening

### Steps to Reproduce (for bugs)
Create a iFrame. Set the url to the web app. Load in Safari. On debian and Ubuntu it will load in Chrome correctly

### Console Output
Error: Uncaught (in promise): Error: SecurityError: IDBFactory.open() called in an invalid security context https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1973927 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1972146 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1971187 t@https://app.super-productivity.com/polyfills.6ab59e778f4fbac0fbfe.js:1:16541 w@https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1970947 t@https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1972432 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1974122 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1159491 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1157022 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1532366 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1159491 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1157022 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:3571834 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1159491 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1157022 map@[native code] https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1159491 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1157022 st@https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1107152 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1159491 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1157022 factory@https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1887159 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1159491 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1157022 forEach@[native code] https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1157901 e@https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1201151 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1202041 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1223606 onInvoke@https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1215364 https://app.super-productivity.com/polyfills.6ab59e778f4fbac0fbfe.js:1:4400 https://app.super-productivity.com/polyfills.6ab59e778f4fbac0fbfe.js:1:4400 https://app.super-productivity.com/polyfills.6ab59e778f4fbac0fbfe.js:1:16320 https://app.super-productivity.com/polyfills.6ab59e778f4fbac0fbfe.js:1:5067 b@https://app.super-productivity.com/polyfills.6ab59e778f4fbac0fbfe.js:1:12301 promiseReactionJob@[native code]
! Please copy & report !

Error: Uncaught (in promise): Error: SecurityError: IDBFactory.open() called in an invalid security context https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1973927 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1972146 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1971187 t@https://app.super-productivity.com/polyfills.6ab59e778f4fbac0fbfe.js:1:16541 w@https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1970947 t@https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1972432 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1974122 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1159491 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1157022 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1532366 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1159491 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1157022 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:3571834 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1159491 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1157022 map@[native code] https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1159491 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1157022 st@https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1107152 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1159491 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1157022 factory@https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1887159 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1159491 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1157022 forEach@[native code] https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1157901 e@https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1201151 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1202041 https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1223606 onInvoke@https://app.super-productivity.com/main.a9256453713435a6fe2e.js:1:1215364 https://app.super-productivity.com/polyfills.6ab59e778f4fbac0fbfe.js:1:4400 https://app.super-productivity.com/polyfills.6ab59e778f4fbac0fbfe.js:1:4400 https://app.super-productivity.com/polyfills.6ab59e778f4fbac0fbfe.js:1:16320 https://app.super-productivity.com/polyfills.6ab59e778f4fbac0fbfe.js:1:5067 b@https://app.super-productivity.com/polyfills.6ab59e778f4fbac0fbfe.js:1:12301 promiseReactionJob@[native code]
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone.js:832:48)
value.hasOwnProperty (webpack:///node_modules/zone.js/dist/zone.js:784:35)
zone.scheduleMicroTask (webpack:///node_modules/zone.js/dist/zone.js:894:35)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28122:43)
task._transitionTo (webpack:///node_modules/zone.js/dist/zone.js:188:61)
drainMicroTaskQueue (webpack:///node_modules/zone.js/dist/zone.js:601:46)
promiseReactionJob ([native code]::)
META: SP5.2.0 Browser – nl – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15

**Comment by johannesjo** [comment]
Thanks for opening this up. Safari is not on the list of browers I personally test on, because the majority of users use the desktop electron version and the majority of the web users use chrome.

If anybody would be willing to work on this, I'd be accepting Pull Requests though.

Not sure if the information here is correct, but it might not even be possible to make this work:
https://stackoverflow.com/questions/58861509/indexdb-in-iframe-safari
