### ISSUE TITLE
Local file sync on Android creating .txt extension. Breaking sync. 

### ISSUE THREAD

**Issue by resuser** [johannesjo/super-productivity#3782]
I searched for an existing issue and did not find anything. 

### Your Environment

Android 15
SuperProd version 11.0.0_L1A from Play Store

Windows 11
SuperProd version 11.0.2

local file sync using syncthing

### Expected Behavior

Windows and Android stay in sync. This has worked fine in the past.

### Current Behavior

Windows creates "MAIN.json" and "ARCHIVE.json" in the sync folder. Android creates "MAIN.json.txt" and "ARCHIVE.json.txt" in the sync folder. They do not sync since they are using different files. 

### Steps to Reproduce (for bugs)

I made sure I had the most recent versions on both Windows and Android. I tried disabling sync, restarting the application, and re-enabling sync. I also tried disabling compression. None of these steps helped.

**Comment by Delta-SC** [comment]
I'm having this exact same issue/behaviour.

Android 15
Superprod version 11.0.2 from the App Store

MacOS 15.0.1
Superprod version 11.0.2

local file sync using syncthing

**Comment by makeasnek** [comment]
Can confirm on Android 14 as well, latest version from playstore, also using syncthing

**Comment by johannesjo** [comment]
This will be fixed with the next release. Thanks for reporting!
