### ISSUE TITLE
Endless json.txt synchronization files

### ISSUE THREAD

**Issue by AZeed18** [johannesjo/super-productivity#3788]
### Your Environment

- Version used: 11.0.0
- Operating System and version: Android 13

### Expected Behavior

To synchronize using two `.json` files

### Current Behavior

Keeps creating `.json.txt` files (not `.json`), with additional files having a number to prevent overwriting

### Steps to Reproduce (for bugs)

1. Setup sync with LocalFile
2. While True: press ok when you see the following prompt: "No remote data found. Upload Local to Remote?"

### Can you reproduce this reliably?

For now, yes

Fixed it once by remove `txt` file extension

**Comment by johannesjo** [comment]
This should be fixed with the latest release.

**Comment by AZeed18** [comment]
It seems it is 👍
