### ISSUE TITLE
Issue after finish day

### ISSUE THREAD

**Issue by sdjrppl** [johannesjo/super-productivity#380]
### Your Environment

* Version used: snap
* Operating System and version: ubuntu 20.04 LTS
* Desktop Environment: linux
* Browser Name and version: 5.2.1

### Current Behavior

Finish day open popup error

### Steps to Reproduce (for bugs)

1. Finish day

### Console Output

![image](https://user-images.githubusercontent.com/17573664/83076346-42c04e00-a06d-11ea-8971-51d3c03545e1.png)
![image](https://user-images.githubusercontent.com/17573664/83076386-5c619580-a06d-11ea-977e-e4bbb28b03df.png)

**Comment by johannesjo** [comment]
Thank you very much for reporting: Does the error appear consistently or was it a one time thing?

**Comment by sdjrppl** [comment]
It was just one time

**Comment by johannesjo** [comment]
Ok Thank you. I'll have a look.

**Comment by GentleHedgehog** [comment]
I'm too..

`GLOBAL_ERROR_HANDLER TypeError: Cannot read property 'mood' of undefined
    at templateFn (webpack:/src/app/fea…t.component.html:17)
    at executeTemplate (webpack:/node_module…/fesm5/core.js:7706)
    at refreshView (webpack:/node_module…/fesm5/core.js:7583)
    at refreshComponent (webpack:/node_module…/fesm5/core.js:8739)
    at refreshChildComponents (webpack:/node_module…/fesm5/core.js:7376)
    at refreshView (webpack:/node_module…/fesm5/core.js:7629)
    at refreshDynamicEmbeddedViews (webpack:/node_module…/fesm5/core.js:8675)
    at refreshView (webpack:/node_module…/fesm5/core.js:7603)
    at refreshComponent (webpack:/node_module…/fesm5/core.js:8739)
    at webpack:/node_module…/fesm5/core.js:7376
main.b7cb82b….js:1 META: SP5.2.1 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.2.1 Chrome/80.0.3987.165 Electron/8.3.0 Safari/537.36
main.b7cb82b….js:1 GLOBAL_ERROR_HANDLER Error: TypeError: Cannot read property 'mood' of undefined
    at t.handleError (webpack:/src/app/cor…handler.class.ts:55)
    at apply (webpack:/node_module…fesm5/core.js:29249)
    at t.invoke (webpack:/node_module…js/dist/zone.js:386)
    at e.run (webpack:/node_module…js/dist/zone.js:143)
    at t.runOutsideAngular (webpack:/node_module…fesm5/core.js:28225)
    at tick (webpack:/node_module…fesm5/core.js:29249)
    at apply (webpack:/node_module…fesm5/core.js:29105)
    at t.invoke (webpack:/node_module…js/dist/zone.js:386)
    at Object.onInvoke (webpack:/node_module…fesm5/core.js:28285)
    at t.invoke (webpack:/node_module…js/dist/zone.js:385)
main.b7cb82b….js:1 META: SP5.2.1 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.2.1 Chrome/80.0.3987.165 Electron/8.3.0 Safari/537.36
webpack:/src/app/fea…et.component.html:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
main.b7cb82b….js:1 templateFn (file:///opt/superProductivity/resources/app.asar/dist/webpack:/src/app/features/metric/evaluation-sheet/evaluation-sheet.component.html:17:16)
executeTemplate (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:7706:9)
refreshView (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:7583:13)
refreshComponent (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:8739:9)
refreshChildComponents (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:7376:9)
refreshView (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:7629:13)
refreshDynamicEmbeddedViews (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:8675:21)
refreshView (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:7603:9)
refreshComponent (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:8739:9)
file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:7376:9
webpack:/node_module…c__/fesm5/core.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
polyfills.7edae71….js:1 Uncaught Error: Error: TypeError: Cannot read property 'mood' of undefined
    at t.handleError (webpack:/src/app/cor…handler.class.ts:55)
    at Object.next (webpack:/node_module…fesm5/core.js:28843)
    at e.call [as _next] (webpack:/node_module…fesm5/core.js:25652)
    at e.__tryOrUnsub (webpack:/node_module…l/Subscriber.js:192)
    at e.next (webpack:/node_module…l/Subscriber.js:130)
    at e._next (webpack:/node_module…al/Subscriber.js:76)
    at e.next (webpack:/node_module…al/Subscriber.js:53)
    at e.call (webpack:/node_module…ernal/Subject.js:47)
    at emit (webpack:/node_module…fesm5/core.js:25634)
    at webpack:/node_module…fesm5/core.js:28308
webpack:/src/app/cor…-handler.class.ts:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
main.b7cb82b….js:1 t.handleError (file:///opt/superProductivity/resources/app.asar/dist/webpack:/src/app/core/error-handler/global-error-handler.class.ts:55:13)
apply (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:29249:87)
t.invoke (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:386:30)
e.run (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:143:47)
t.runOutsideAngular (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28225:28)
tick (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:29249:24)
apply (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:29105:27)
t.invoke (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:386:30)
Object.onInvoke (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28285:33)
t.invoke (file:///opt/superProductivity/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:385:36)
webpack:/node_module…e.js/dist/zone.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
DevTools failed to parse SourceMap: file:///opt/superProductivity/resources/app.asar/dist/runtime.7d7e903….js.map
DevTools failed to parse SourceMap: file:///opt/superProductivity/resources/app.asar/dist/polyfills.7edae71….js.map
DevTools failed to parse SourceMap: file:///opt/superProductivity/resources/app.asar/dist/main.b7cb82b….js.map
DevTools failed to parse SourceMap: file:///opt/superProductivity/resources/app.asar/dist/lz.16083aa….worker.js.map
DevTools failed to parse SourceMap: file:///opt/superProductivity/resources/app.asar/dist/reminder.b87ed2e….worker.js.map
DevTools failed to parse SourceMap: file:///opt/superProductivity/resources/app.asar/dist/styles.23e2d95….css.map
main.b7cb82b….js:1 Migrating model to version from undefined to 1 
{lang: {…}, misc: {…}, evaluation: {…}, idle: {…}, takeABreak: {…}, …}
﻿
​`

**Comment by ingorichter** [comment]
Saw the same thing happening to me today. Finished the day and boom :-)

**Comment by johannesjo** [comment]
@GentleHedgehog @ingorichter  I hope this was only a one time thing to you too?

**Comment by GentleHedgehog** [comment]
@johannesjo It was my first working day, I installed 5.2.1 version from the deb package (Ubuntu 20.04, snap installation didn't work, could not started). It was a great experience and I had a lot of fun with superProductivity, but this error surprized me((. Today I created a couple of tasks end there is no error, but yesterday tasks produce error again.
Yesterday task list:
 
![Screenshot from 2020-06-04 13-50-56](https://user-images.githubusercontent.com/3767353/83748412-d0ea9480-a66a-11ea-95f3-3a6c65597575.png)

![Screenshot from 2020-06-04 13-54-23](https://user-images.githubusercontent.com/3767353/83748493-f4154400-a66a-11ea-993b-fe1c469727a4.png)

**Comment by johannesjo** [comment]
Thanks and sorry everybody. It didn't occur to me that this is happening only for projects (which, well, it should have :)). I publish a hotfix release shortly.

**Comment by GentleHedgehog** [comment]
@johannesjo , Thank you so much! I will wait for hotfix :)

**Comment by johannesjo** [comment]
The new release should be available now:
https://github.com/johannesjo/super-productivity/releases/tag/v5.2.3
