### ISSUE TITLE
translation is show error

### ISSUE THREAD

**Issue by QThans** [johannesjo/super-productivity#382]
![image](https://user-images.githubusercontent.com/18275400/83100044-818feb80-a0e1-11ea-98f2-3300821fb52f.png)

**Comment by johannesjo** [comment]
Sorry, I don't speak Chinese... Adjustments can be made here: https://github.com/johannesjo/super-productivity/blob/master/src/assets/i18n/zh.json

**Comment by QThans** [comment]
> Thanks for opening this up. And sorry, I don't speak Chinese... Adjustments can be made here: https://github.com/johannesjo/super-productivity/blob/master/src/assets/i18n/zh.json

zh.json is correct. but the software ui is display error

**Comment by johannesjo** [comment]
Im assuming that this is fixed with the latest Chinese updates. Please let me know if it isn't.
