### ISSUE TITLE
Error in Project Section

### ISSUE THREAD

**Issue by basaravia** [johannesjo/super-productivity#387]
### Your Environment

* Version used: 
* Operating System and version:
* Desktop Environment: 
* Browser Name and version: 

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Console Output
t.handleError (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/src/app/core/error-handler/global-error-handler.class.ts:55:13)
apply (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:29249:87)
t.invoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:386:30)
e.run (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:143:47)
t.runOutsideAngular (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28225:28)
tick (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:29249:24)
apply (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:29105:27)
t.invoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:386:30)
Object.onInvoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28285:33)
t.invoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:385:36)

**Comment by johannesjo** [comment]
Hi! Thanks for reporting! Could you provide a little bit more context by any chance?
