### ISSUE TITLE
Translation of Today menu item

### ISSUE THREAD

**Issue by kerkenit** [johannesjo/super-productivity#396]
### Your Environment

* Version used: DEV
* Operating System and version: Web
* Desktop Environment:  Mac
* Browser Name and version:  Safari

### Expected Behavior
Today in the menu should ben in Ducth: Vandaag

### Current Behavior
There is written: Today

### Steps to Reproduce (for bugs)

1. Run app
2. Change lange to Dutch (Nederlands)
3. See in the menu everything translated except: Today
4.

**Comment by johannesjo** [comment]
Thanks for opening this up. The reason for this ist, that the title is something the user can change. We could set an initial value based on the user language, but if this (let's say for a new user) is the wrong one, this could be annoying as well. Not sure what would be the best way to deal with it without making it overcomplicated. Suggestions (and PRs) would be welcome!

**Comment by kerkenit** [comment]
I didn't know It can be changed. ¿Close this issue?

**Comment by kerkenit** [comment]
<img width="208" alt="Schermafbeelding 6" src="https://user-images.githubusercontent.com/13370203/84390461-ed04ad80-abf7-11ea-9c1a-4db2c33344f5.png">

**Comment by johannesjo** [comment]
I would leave it open for now. Maybe somebody comes up with a good idea.
