### ISSUE TITLE
Allow http (not https) JIRA hosts

### ISSUE THREAD

**Issue by jefft** [johannesjo/super-productivity#4]
When configuring JIRA integration, one is currently prompted for 'Host'. SP is expecting something like 'localhost' or 'jira.mycompany.com'. In my case I enter 'redradish_jira.localhost'.

The problem is that SP then *assumes* https. My JIRA happens to run on http://redradish_jira.localhost inside the network, not https. If I enter Host: 'redradish_jira.localhost:80', then SP just tries to talk SSL on port 80 and breaks.

I think 'Host' should be replaced by 'Base URL', a well-known concept in JIRA-land. This is unambiguous, setting the scheme, port and URL prefix all at once.

**Comment by johannesjo** [comment]
Thanks! Good suggestion! I will implement that.

**Comment by johannesjo** [comment]
I'm assuming that this should work now. Let me know if it doesn't.
