### ISSUE TITLE
Time tracking does not work

### ISSUE THREAD

**Issue by dfcrosby** [johannesjo/super-productivity#40]
## Your Environment

* Version used: 1.6.3
* Operating System and version: Windows 10 1607 and 1709

## Expected Behavior
When you select the play button on a task in the Work View: 
1) the button should change to a pause button and task should turn green, 
2) the time tracking should start and the pop-up message at the bottom of the screen indicates that the task was started, and 
3) the time spent should increase and the green bar below the task should increase in length until you select the pause button.

## Current Behavior
Clicking on the play button does everything expected - it appears to be tracking time spent - HOWEVER, the time spent value does not increase and bar under the task does not extend.

## Steps to Reproduce (for bugs)

1. Select the Work View
2. Select the play button to start tracking
3. Wait longer than one minute to observe that the time spent does not increment.
4.

**Comment by johannesjo** [comment]
Thanks for reporting. I think I found the problem. Should be fixed with 1.6.7 hopefully.

**Comment by dfcrosby** [comment]
Thanks, @johannesjo.  I really like the app and would like to help more.  It would be very helpful to be able to run the app in portable mode (from a USB) - my employer does not like when I install programs on my office computer.  Also, it would be helpful to understand how the data is structured.  And, where is the data stored in Windows and on the WebApp.  Thanks.

**Comment by johannesjo** [comment]
@dfcrosby good suggestion. I'll try to publish a portable exe for version 1.6.8 (should be available later today).

**Comment by johannesjo** [comment]
@dfcrosby is your problem solved regarding this issue here?

**Comment by dfcrosby** [comment]
Thanks, @johannesjo.  The time tracking is working on the portable version.  When I get home, I will check the Windows versions.  I was using the webapp today and noted some issues with the time tracking but I will double check it now that you have made some changes.  Is there a way to check the version of the webapp that is running in my browser?  I would assume it gets updated, but not sure how exactly.  Thanks!

**Comment by dfcrosby** [comment]
Also, where is the data stored?  When I ran the portable version, it picked up some old data file.  I want to delete it so I can start with a clean install.  Thanks.

**Comment by johannesjo** [comment]
Date is stored in local storage. You can delete when you press Ctrl+Shift+J
and then delete it under the Application Tab.

David Crosby <notifications@github.com> schrieb am Do., 30. Nov. 2017 um
23:17 Uhr:

**Comment by dfcrosby** [comment]
Thank you, the time tracking is working on every platform I have it installed on - Win7 and Win10 and Web.
I am still unable to delete the data - when try to delete the data under Local Storage ("file://") it comes right back and when I go to "Clear Storage" under Application and select Clear site data, nothing happens.  Is there a file or folder I can delete and force it to start from a clean install?  Thanks.

**Comment by johannesjo** [comment]
Forgot to mention: you need to delete it and then reload the app right away (Ctrl+R).

**Comment by dfcrosby** [comment]
Thanks.  That works, but there should probably be a better way.  When I start the app it seems to pull data from some unknown source/location to populate the tasks.  The value of running portable is that I can use the app at multiple locations for different clients by using different data files.  The other problem is that from a privacy and security perspective, I should be able to take the data with me and not leave a copy behind on every machine I use.

**Comment by johannesjo** [comment]
Yes you make valid points. Maybe you can open up a new issue about this? I'm closing this, as the issue here is resolved.

**Comment by Morganamilo** [comment]
@dfcrosby The app stores data in `~/.config/superProductivity` on Linux and `%appdata%/superProductivity` on windows.

**Comment by dfcrosby** [comment]
Thank you @Morganamilo.  Unfortunately, I know nothing about javascript or electron.  I am starting to learn.  Where did you find this info?  Thanks, again.

**Comment by Morganamilo** [comment]
They're just common places to store config files. I took a guess and they were there.

**Comment by dfcrosby** [comment]
Thanks, @Morganamilo, do you know where the webapp stores the data?  I work primarily in windows using Chrome.  I have looked in chrome's folders and I can't seem to find it.  It is not the same place as the desktop app because they show different tasks.

**Comment by Morganamilo** [comment]
I'm not sure of that myself, my guess would be browser cookies and I'm not sure of an easy way to access those on disk. You might want to try using the import and export options instead.

**Comment by johannesjo** [comment]
@dfcrosby the app is currently mainly using the local storage for that. Honestly I've no idea how and where chrome stores that exactly. 

There is an experimental syncing feature in the latest version, which exports all data to json and reimports it, when there are any changes. You might wanna try it out.

**Comment by johannesjo** [comment]
@dfcrosby Because I recently had to work for a more restrictive employer I developed an extension for the web version, which let's you access Jira from there. Just wanted to let you know ;)
https://chrome.google.com/webstore/detail/super-productivity/ljkbjodfmekklcoibdnhahlaalhihmlb
