### ISSUE TITLE
Error: Uncaught (in promise): AbortError: The transaction was aborted, so the request cannot be fulfilled.

### ISSUE THREAD

**Issue by kevflanagan** [johannesjo/super-productivity#401]
META: SP5.3.4 Electron – en-GB – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.3.4 Chrome/80.0.3987.165 Electron/8.3.0 Safari/537.36

### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
resolvePromise (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:832:39)
file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:739:21
Ur (file:///snap/superproductivity/651/resources/app.asar/dist/main.05eca3ac60f95ea85f95.js:1:1539237)
t.invoke (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:386:30)
Object.onInvoke (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28134:33)
t.invoke (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:385:36)
e.run (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:143:47)
apply (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:891:38)
t.invokeTask (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:421:35)
Object.onInvokeTask (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28122:33)
```

**Comment by johannesjo** [comment]
Thank you very much. Could you maybe provide a little bit more inside on what happened before the error?

Common reasons for database issues like this are:
1. Running multiple instances of the app
2. Not enough disk space

**Comment by kevflanagan** [comment]
Unfortunately I can't add much. I was not running multiple instances and I
have a lot of disk space. I think it happened when I was trying to manually
edit the time for a task.

**Comment by johannesjo** [comment]
Have you been idle for while before doing this?

**Comment by kevflanagan** [comment]
I don't think so. It's happened a few times. I'll keep using it and let you
know if it happens again.

**Comment by johannesjo** [comment]
That would be great! Thank you. I really can use all the info I can get regarding this issue.

**Comment by johannesjo** [comment]
May I ask if you encountered this or a similar issue again? I am asking because I had the feeling that this might have gotten better with the most recent electron version (introduced with Super Productivity 5.6.5) as nobody has reported a similar issue after that.

**Comment by bloodpet** [comment]
I think i got the same error. Details in #542 -- should have checked for duplicate issues, my bad.

**Comment by johannesjo** [comment]
I added some advanced data repair/restore functionality, as a compromise as there is no way to fix this completely without replacing the database adapter, which is not trivial and likely to cause new issues on other fronts. I think this is acceptable, as the issue only occurs rarely. I am closing this, but please open up new issues, if you encounter this again. Thank you!
