### ISSUE TITLE
"Project Does Not Exist" when using Jira with multiple proeject

### ISSUE THREAD

**Issue by julopezc-acciona** [johannesjo/super-productivity#402]
### Your Environment

* Version used: snap edge (5.3.5)
* Operating System and version: Kubuntu 20.04
* Desktop Environment: KDE

### Expected Behavior
When I click in "Open in browser" on a JIRA task or "WRITE A COMMENT" on additional info, it should go to `<jira-base>/browse/JGC-342`, where JGC is the name of the project (i.e., all jira tickets are JGC-234, JGC-45, ...)

### Current Behavior
Instead it goes to `<jira-base>/browse/18595` and it shows an error: "Project Does Not Exist"
![image](https://user-images.githubusercontent.com/61837521/84675394-7ab00800-af2c-11ea-9cd8-48a029fa531a.png)

I think this is because there are multiple projects on the Jira I'm working on.

**Comment by johannesjo** [comment]
Thanks for reporting. Currently I am pretty busy with other issues on the project, but I'll get to it at some point. Meanwhile Pull Requests are welcome. If I understand this correctly adjusting the generated link to the issue should be enough:

https://github.com/johannesjo/super-productivity/blob/67322b9278fa94ee877385570f5fb62f1e6bb343/src/app/features/issue/providers/jira/jira-common-interfaces.service.ts#L103-L108

But this probably needs some testing.

**Comment by johannesjo** [comment]
I think this should be fixed now. @julopezc-acciona can you confirm this?

**Comment by julopezc-acciona** [comment]
On 6.0.1 is still going to `<jira-base>/browse/4455621` instead of `<jira-base>/browse/JGC-342`, do I have to switch on some option?

**Comment by johannesjo** [comment]
> do I have to switch on some option?

No, but this might only take effect for newly imported issues.

**Comment by julopezc-acciona** [comment]
Ok, it is working correctly with newly imported issues.
Thanks!

**Comment by johannesjo** [comment]
Thanks for letting me know!
