### ISSUE TITLE
"Adding to today" a scheduled sub-task results in duplicate as main-task 

### ISSUE THREAD

**Issue by halloichbingunnar** [johannesjo/super-productivity#404]
### Your Environment

* Version used: 5.3.5
* Operating System and version: Win 10

### Expected Behavior
When a scheduled sub-task is due, clicking on "Add to today" should result in tagging the whole task including the sub-task with "today".

### Current Behavior
When a scheduled sub-task is due, clicking on "Add to today" results in it is added as a singular main task without option to be moved again – but it also remains a sub-task. Both tasks seem to be the same, time tracking applies to both, if you delete one, both are gone (see screenshots). Task can't be moved in list position by drag and drop either.

![Anmerkung 2020-06-18 142633](https://user-images.githubusercontent.com/64837252/85020853-3eb9b480-b171-11ea-86ab-b194792b20ff.png)
![Anmerkung 2020-06-18 143645](https://user-images.githubusercontent.com/64837252/85020857-3feae180-b171-11ea-929f-1b9429c24fd9.png)

**Comment by johannesjo** [comment]
Hi Gunnar! Thank you. I try to provide a fix with the next release!

**Comment by johannesjo** [comment]
The fix should be available starting with version 4.0.0 (currently only available as pre release).
