### ISSUE TITLE
 alarmlive deployment From Project: "bq-portal" Task is due. Do you want to start working on it?  Error: Uncaught (in promise): TypeError: Failed to execute 'showNotification' on 'ServiceWorkerRegistration': 

### ISSUE THREAD

**Issue by sanoopuio** [johannesjo/super-productivity#408]
Error: Uncaught (in promise): TypeError: Failed to execute 'showNotification' on 'ServiceWorkerRegistration': No notification permission has been granted for this origin. TypeError: Failed to execute 'showNotification' on 'ServiceWorkerRegistration': No notification permission has been granted for this origin. at t. (https://app.super-productivity.com/main.7cbec4113bbb01b2d665.js:1:647669) at https://app.super-productivity.com/main.7cbec4113bbb01b2d665.js:1:646843 at Object.next (https://app.super-productivity.com/main.7cbec4113bbb01b2d665.js:1:646948) at a (https://app.super-productivity.com/main.7cbec4113bbb01b2d665.js:1:645686) at t.invoke (https://app.super-productivity.com/polyfills.6ab59e778f4fbac0fbfe.js:1:9294) at Object.onInvoke (https://app.super-productivity.com/main.7cbec4113bbb01b2d665.js:1:1230073) at t.invoke (https://app.super-productivity.com/polyfills.6ab59e778f4fbac0fbfe.js:1:9234) at e.run (https://app.super-productivity.com/polyfills.6ab59e778f4fbac0fbfe.js:1:4394) at https://app.super-productivity.com/polyfills.6ab59e778f4fbac0fbfe.js:1:16317 at t.invokeTask (https://app.super-productivity.com/polyfills.6ab59e778f4fbac0fbfe.js:1:9978)

Error: Uncaught (in promise): TypeError: Failed to execute 'showNotification' on 'ServiceWorkerRegistration': No notification permission has been granted for this origin. TypeError: Failed to execute 'showNotification' on 'ServiceWorkerRegistration': No notification permission has been granted for this origin. at t. (https://app.super-productivity.com/main.7cbec4113bbb01b2d665.js:1:647669) at https://app.super-productivity.com/main.7cbec4113bbb01b2d665.js:1:646843 at Object.next (https://app.super-productivity.com/main.7cbec4113bbb01b2d665.js:1:646948) at a (https://app.super-productivity.com/main.7cbec4113bbb01b2d665.js:1:645686) at t.invoke (https://app.super-productivity.com/polyfills.6ab59e778f4fbac0fbfe.js:1:9294) at Object.onInvoke (https://app.super-productivity.com/main.7cbec4113bbb01b2d665.js:1:1230073) at t.invoke (https://app.super-productivity.com/polyfills.6ab59e778f4fbac0fbfe.js:1:9234) at e.run (https://app.super-productivity.com/polyfills.6ab59e778f4fbac0fbfe.js:1:4394) at https://app.super-productivity.com/polyfills.6ab59e778f4fbac0fbfe.js:1:16317 at t.invokeTask (https://app.super-productivity.com/polyfills.6ab59e778f4fbac0fbfe.js:1:9978)
this._isServiceWorkerAvailable (webpack:///src/app/core/notify/notify.service.ts:36:19)
Ur (https://app.super-productivity.com/main.7cbec4113bbb01b2d665.js:1:646843)
Ur (https://app.super-productivity.com/main.7cbec4113bbb01b2d665.js:1:646948)
Ur (https://app.super-productivity.com/main.7cbec4113bbb01b2d665.js:1:645686)
invoke (webpack:///node_modules/zone.js/dist/zone.js:386:29)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28134:32)
invoke (webpack:///node_modules/zone.js/dist/zone.js:385:35)
run (webpack:///node_modules/zone.js/dist/zone.js:143:46)
zone.scheduleMicroTask (webpack:///node_modules/zone.js/dist/zone.js:891:37)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:421:34)
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone.js:832:38)
value.hasOwnProperty (webpack:///node_modules/zone.js/dist/zone.js:784:20)
zone.scheduleMicroTask (webpack:///node_modules/zone.js/dist/zone.js:894:20)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:421:34)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28122:32)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:420:39)
task._transitionTo (webpack:///node_modules/zone.js/dist/zone.js:188:50)
drainMicroTaskQueue (webpack:///node_modules/zone.js/dist/zone.js:601:38)
META: SP5.3.5 Browser – en – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36

**Comment by johannesjo** [comment]
Hi! Thanks for reporting. You seem to be using Safari. I currently don't focus on supporting Safari, but PRs would be welcome. I'd recommend using the app inside chrome or downloading the destkop version.

**Comment by sanoopuio** [comment]
It happend in chrome in mac os catalina. then i switched to safari and it was working fine in safari.
Now its working fine in chrome too

**Comment by johannesjo** [comment]
I think I found the issue. Thank you very much!
