### ISSUE TITLE
Fast foward button finishes task timer and break timer at once

### ISSUE THREAD

**Issue by HendrysTobar** [johannesjo/super-productivity#409]
I think something broke after closing issue #389 . The break timer does not go to -1 anymore, but now it has some weird behavior.
I always like to start with a 5min break before starting my work, so since there is not an option to start a break what I do is that I finish the current pomodoro timer, so it goes to a break.
However, currently, there is a bug,

### Your Environment

* Version used: 5.3.5

* Operating System and version: Windows 10
* Desktop Environment: 
* Browser Name and version: 

### Expected Behavior

When you are starting a day of work. and you press on the ->| button it should end the timer and start a 5min break. When playing the break the 5min timer should start.
![2020-06-22 16_24_12-Window](https://user-images.githubusercontent.com/5922811/85337078-69737800-b4a5-11ea-9212-93a3557921fb.png)

### Current Behavior

When pressing the ->| button it says 
![image](https://user-images.githubusercontent.com/5922811/85337165-99228000-b4a5-11ea-8162-747908649cff.png)

And you are not able to run the break timer, you have to start the task.
"

### Steps to Reproduce (for bugs)

1. Go to Today with some tasks added
2.Follow this pomodoro configuration:
![image](https://user-images.githubusercontent.com/5922811/85337267-c1aa7a00-b4a5-11ea-8c39-f09abd86afa7.png)

3. Do not start a task timer
4. Press the ->| button

**Comment by johannesjo** [comment]
Hi! :) Thanks for opening this up! Would you like to give it a shot yourself?

**Comment by HendrysTobar** [comment]
Sure! As I said via mail, it will take a while, but this'll be my first
challenge. 💪
