### ISSUE TITLE
Add tasks from command line interface

### ISSUE THREAD

**Issue by ytee** [johannesjo/super-productivity#413]
### Your Environment
* Version used:  5.4.0, Windows executable
* Operating System and version: Windows 10
* Desktop Environment: 
* Browser Name and version: 

### Expected Behavior

- Be able to add tasks from command line. It will help easily capture tasks with out leaving current application.
Lets say, I am using outlook / email client, I want to be able to add task from with-in outlook by writing a script to interact with superproductivity CLI.

- Drag and drop attachments on to the tasks

**Comment by johannesjo** [comment]
Thanks for opening this up.

A command line interface is already requested: https://github.com/johannesjo/super-productivity/issues/173

Drag and drop onto tasks should already work. Are you encountering an issue with that?
