### ISSUE TITLE
TypeError: Cannot read property 'projectId' of null

### ISSUE THREAD

**Issue by ilinei52** [johannesjo/super-productivity#415]
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
projectId (webpack:///src/app/features/project/store/project.effects.ts:340:55)
filter (webpack:///src/app/features/project/store/project.effects.ts:340:35)
_next (webpack:///node_modules/rxjs/_esm5/internal/operators/map.js:35:34)
next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:53:17)
_next (webpack:///node_modules/rxjs/_esm5/internal/operators/take.js:40:29)
next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:53:17)
subscriber.add (webpack:///node_modules/rxjs/_esm5/internal/ReplaySubject.js:67:27)
_trySubscribe (webpack:///node_modules/rxjs/_esm5/internal/Observable.js:43:24)
_trySubscribe (webpack:///node_modules/rxjs/_esm5/internal/Subject.js:89:50)
```

### Meta Info
META: SP5.4.2 Browser – en-US – Linux armv8l – Mozilla/5.0 (Linux; Android 9; SM-N960U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Mobile Safari/537.36

**Comment by johannesjo** [comment]
Thank you for opening this up! Could you provide a little more context? When did this start happening? Also: Could you by any chance provide me an export of your data? I am unable to reproduce this, but it seems to be related to (non serious) data corruption.

**Comment by ilinei52** [comment]
Sorry, after several synchronizations through Google Drive, the error no reproduce. I think, I can close this issue. You have a great application, I am sincerely thankful for your work.
