### ISSUE TITLE
Can't install it from AUR

### ISSUE THREAD

**Issue by madjoe** [johannesjo/super-productivity#416]
Hi! I couldn't install it from AUR, so I tried to install it through git.
Could you please provide steps necessary to properly uninstall it? Thanks.

### Your Environment

* Version used: 5.4.2
* Operating System and version: Linux Manjaro x64
* Desktop Environment: KDE Plasma
* Browser Name and version: Chromium 83.0.4103.97 Arch Linux

### Steps to Reproduce (for bugs)

1. `git clone https://github.com/johannesjo/super-productivity.git`
2. `cd super-productivity`
3. `npm install`
4. `npm install -g @angular/cli`

### Console Output

$ npm install -g @angular/cli
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN checkPermissions Missing write access to /usr/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

**Comment by johannesjo** [comment]
Hi! Generally your global node modules need to be writable to the current user to install angular-cli. See: https://stackoverflow.com/questions/16151018/npm-throws-error-without-sudo
The best solution for that depends on your setup.

After that you can try using the `yarn localInstall` command, which will only work however if your machine supports installing deb packages. 

There are definitely [ways to make AUR](https://github.com/johannesjo/super-productivity/issues/212) work, but unfortunately I can't help you with that as I neither have access nor the knowledge.

**Comment by madjoe** [comment]
Thanks. Would deleting the application's `git dir` be sufficient as a complete uninstall at this point, so I could try with the link you provided (AUR) - or are there any leftovers? Thanks. :)

**Comment by johannesjo** [comment]
Looking at the commands there should be no leftovers.
