### ISSUE TITLE
Error: Uncaught (in promise): UnknownError: Internal error committing transaction.

### ISSUE THREAD

**Issue by FuqiX** [johannesjo/super-productivity#418]
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
resolvePromise (file:///snap/superproductivity/673/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:832:39)
file:///snap/superproductivity/673/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:739:21
Ur (file:///snap/superproductivity/673/resources/app.asar/dist/main.dfed7263d15fcd0c7469.js:1:1716819)
t.invoke (file:///snap/superproductivity/673/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:386:30)
Object.onInvoke (file:///snap/superproductivity/673/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28134:33)
t.invoke (file:///snap/superproductivity/673/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:385:36)
e.run (file:///snap/superproductivity/673/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:143:47)
apply (file:///snap/superproductivity/673/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:891:38)
t.invokeTask (file:///snap/superproductivity/673/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:421:35)
Object.onInvokeTask (file:///snap/superproductivity/673/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28122:33)
```

### Meta Info
META: SP5.4.1 Electron – en-GB – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.4.1 Chrome/83.0.4103.104 Electron/9.0.4 Safari/537.36

**Comment by FuqiX** [comment]
Hello, I was in task mode and the program stopped working. Not sure what triggered this. But it happened several times, the program stopped working, when I did  nothing to the software

**Comment by johannesjo** [comment]
Thank you very much for reporting! Possible known causes for this are:
1. Not enough memory
2. Running multiple instances of the app.

Are you able to reproduce this consistently?

**Comment by johannesjo** [comment]
Thank you very much for reporting. Unfortunately the database itself (indexeddb seems to have some stability issues). I haven't found a good way to deal with that, so any suggestions and help are welcome.

**Comment by johannesjo** [comment]
May I ask if you encountered this or a similar issue again? I had the feeling that this has gotten better with the most recent electron version (introduced with Super Productivity 5.6.5).

**Comment by FuqiX** [comment]
Hi, Johannes. 

Thank you for following up. I haven't paid attention to this problem recently. I'll let you know if this happens again.

Best

**Comment by johannesjo** [comment]
I added some advanced data repair/restore functionality, as a compromise as there is no way to fix this completely without replacing the database adapter, which is not trivial and likely to cause new issues on other fronts. I think this is acceptable, as the issue only occurs rarely. I am closing this, but please open up new issues, if you encounter this again. Thank you!
