### ISSUE TITLE
Open in browser for task created from github issue doesn't work

### ISSUE THREAD

**Issue by nzjony** [johannesjo/super-productivity#422]
See the image, clicking the button doesn't work.

<img width="771" alt="Screenshot 2020-06-30 at 18 04 04" src="https://user-images.githubusercontent.com/2533428/86149379-2d22c600-bafc-11ea-8104-878ca74654ef.png">

### Your Environment
* Version used: 5.4.2
* Operating System and version: macOS 10.15.3

### Expected Behavior
I expect the PR to open in the default browser.

### Current Behavior
Nothing happens

### Steps to Reproduce (for bugs)
1. Setup github integration (note, I am looking at an repository which is part of my organisation: https://github.com/heremaps/harp.gl, not sure if that makes a difference).
2. Add a task from github
3. Right click on Task
4. Click Open in Browser

### Console Output
No output in the console.

**Comment by johannesjo** [comment]
Funny I currently have to work with here maps on my job :)

Thanks for opening this up. How did you set up the GitHub integration? I just tested it with your repository and it seems to work fine? Also is there any output in the console (Ctrl+Shift+i) when clicking "Open in browser"?

![Screenshot from 2020-06-30 23-50-02](https://user-images.githubusercontent.com/1456265/86180438-7559dc80-bb2c-11ea-9e50-d44741390a16.png)

**Comment by johannesjo** [comment]
Another possibility would be that this is a MacOs issue. I'll try to check this tomorrow.

**Comment by nzjony** [comment]
@johannesjo , TBH, I saw you had starred harp.gl and looked at your repos and thought I would give superproductivity a try, I was using TaskWarrior on the command line, because I liked its simplicity, but the integration with github you have is pretty awesome, so I want to give it a try, and I like the fact it is open source and in development.

I opened up the console with Cmd+Alt+i (it seems to be different on mac), but there is no console output when clicking "open in browser" unfortunately. Yes, I had set it up as you showed in the screen shot.

**Comment by johannesjo** [comment]
I think I fixed the issue. Thanks for reporting again! The fix should be out on the edge channel soon. Please let me know if it works out for you.

**Comment by johannesjo** [comment]
Äh I just remembered that there is no such thing as an edge channel for Mac :D 

Sorry. I provide a pre-release.

**Comment by nzjony** [comment]
Many thanks! Productivity++
