### ISSUE TITLE
Ability to store the data files on a network drive

### ISSUE THREAD

**Issue by ricosuave73** [johannesjo/super-productivity#423]
### Environment

* Version used: 5.4.2 .deb
* Operating System and version: Linux Mint 19.3
* Desktop Environment: Cinnamon 4.4.8

### Expected Behavior
When using superproductivity between computers in a local network, it would be nice to be able to specify the location of the data files. I work at home both on a laptop and a desktop. If I could specify the data files to be stored on my NAS drive, I could have the same data accessible from both computers.

### Current Behavior
Currently I haven't found a way to specify a specific storage location for the data files.

**Comment by johannesjo** [comment]
Hey there! Thanks for opening this up! This is currently possible via using the `--user-data-dir` param when starting super productivity. 
```
superproductivity --user-data-dir=/my/location/
```
Does this solve your issue?

**Comment by ricosuave73** [comment]
Thanks, this solves my problem.
