### ISSUE TITLE
Introduction for docker installation

### ISSUE THREAD

**Issue by fengwang** [johannesjo/super-productivity#424]
Maybe it is a good idea to add docker installation to the readme file:

typical commands could be:

```
git clone https://github.com/johannesjo/super-productivity.git && cd super-productivity
docker build -t super-productivity . 
docker  run -p 7788:80 --name super-productivity -d super-productivity
# browse http://127.0.0.1:7788
```

**Comment by johannesjo** [comment]
Thanks for opening this up! To be honest: I am pretty undecided about this as docker shouldn't be needed to run this and is in my humble opinion not the best way to run this app. Currently, it's just static Html after all.

**Comment by johannesjo** [comment]
Now available be here:
https://github.com/johannesjo/super-productivity#run-as-docker-container

Thank you very much again for taking the time to open this up.
