### ISSUE TITLE
Differentiate between reminders and notes

### ISSUE THREAD

**Issue by carlsen1996** [johannesjo/super-productivity#426]
Hi, great app! Been looking for a program like this for a long time.
I saw that the notes function are more similar to the reminders function in other productivity apps. How I see the notes function is more like noting down important URLs or commands that are useful for that project, where the reminders function are more like "remind me to send that E-mail in 2 hours". 
Would be wonderful to separate them as, in my opinion, they are quite different from each other and could better the work flow for some people.

If you need a more descriptive explanation, let me know or if you want me to give it a try I will try to make a pull request over the summer when i have time.

**Comment by johannesjo** [comment]
Hi there! Thank you very much for the suggestion and offering help. İ agree with you that separating notes from simple reminders might be a good idea. İn fact reworking notes in general is on my personal Todo list. 

I'm working full time now again and there is lots of other stuff which needs attention, so PR of yours would be very welcome and very much appreciated! 

Let me know if you need any help with this. We can also schedule an online meeting to discuss the details of the implementation.

**Comment by carlsen1996** [comment]
I must say that I jinxed the programming language, but this gives me an opportunity to learn typescript. So I will get back to it in a couple of weeks/months.

**Comment by johannesjo** [comment]
I am looking forward to that! Let's hope we can break the spell ;) Let me know if you have any questions!
