### ISSUE TITLE
Android App doesn't sync with Dropbox

### ISSUE THREAD

**Issue by halloichbingunnar** [johannesjo/super-productivity#429]
### Your Environment
* Version used: 5.4.2
* Operating System and version: Android 9, Samsung

### Current Behavior
After entering the Auth Code of Dropbox, clicking "Generate Token" creates a "Successful" message, but after saving the sync never happens. The token isn't displayed, too.

![20200703_140134](https://user-images.githubusercontent.com/64837252/86467532-d3a5db80-bd35-11ea-87df-c453e53c5cc9.jpg)

**Comment by johannesjo** [comment]
Thanks for opening this up. I look into it. As a quick side note: Normally everything should show up if you click save once more.

**Comment by halloichbingunnar** [comment]
i tried to make sure the bug isn't in front of the smartphone: i tried more than once with saving, also did a reinstall and tried again - still don't know how to get it syncing :)

**Comment by johannesjo** [comment]
One more question: Are you using the android app or the web app?

**Comment by halloichbingunnar** [comment]
The Android App. If I try in firefox mobile it works...

**Comment by johannesjo** [comment]
It might be that you need to delete the cached app data too. Normally this should work automatically, but maybe it doesn't on your case. The android version is still a little wonky, unfortunately...

**Comment by halloichbingunnar** [comment]
Thanks! I'll try and let you know what happened :)

**Comment by halloichbingunnar** [comment]
works! thank you!

**Comment by johannesjo** [comment]
I'm happy to hear that! Thank you for letting me know!

**Comment by freetoken-Tg1483** [comment]
Normally everything should automatically work. I found that when you turn on sync or transfer is turned on shareing  and you have good wifi you go into your files on this other site then open Dropbox add the file after that go to respective Dropbox settings open it and pull them out manually this will take some time to sync as well hope iwas helpful it was my first time.

**Comment by freetoken-Tg1483** [comment]
looks like your all set good luck.
