### ISSUE TITLE
Allow to comment on issues (Jira + Github) in app

### ISSUE THREAD

**Issue by rjshrjndrn** [johannesjo/super-productivity#435]
### Your Environment

* Version used: snap app version 5.4.3  
* Operating System and version: arch
* Desktop Environment: KDE 
* Browser Name and version: 

### Expected Behavior

When I click comment button on the jira task, it opens up a new browser window. Expectation was to have in-app comment.

### Steps to Reproduce (for bugs)

sorry, my screenshot doesn't have opening the browser, because it's in my other screen.
![superproductivity](https://user-images.githubusercontent.com/2563385/86553019-33cf9400-bf67-11ea-9c25-a6ac588ed922.gif)

**Comment by johannesjo** [comment]
Hey! Thanks for opening this up. This would be indeed a nice feature to have. I'd be happy to see a PR on this one. Personally I probably won't be able to work on this soon, as there other more pressing matters to attend first.

**Comment by johannesjo** [comment]
Also: Duplicate of #381
