### ISSUE TITLE
Improve GitLab  project path parsing

### ISSUE THREAD

**Issue by ishpartko** [johannesjo/super-productivity#438]
Hi, thank you for your project.

I have a nested project structure(there is a sub-project) and I did not understand at first how I should integrate it.

### Expected Behavior
Could we make the user interface more friendly? So that the user could simply insert a link of the repository to field and get a customized configuration of the application?

### Current Behavior
https://gitlab.com/help/api/README.md#namespaced-path-encoding
![изображение](https://user-images.githubusercontent.com/27618114/87020942-3b986e00-c1dd-11ea-9a9f-0ffb9756e2a1.png)

### Steps to Reproduce (for bugs)
It took me two hours to figure out how to integrate it all. 
1. Fork the repository
2. according to the keywords I found a place to integrate Gitlab. 
3. in the TS interface and the configuration example, I found that it should be a string and a pattern: `/^.+\%2F.+?$/i.`
4. looked at the endpoint API he's accessing.
5. looked at the documentation for this endpoint. 
6. started experimenting and got a good result in the pattern `projectName%2FsubProjectName%2FrepoName` looks like horror

**Comment by johannesjo** [comment]
Hey there! Thanks for opening this up. You're absolutely right. This should be improved! Would you maybe like to provide a Pull Request yourself? The relevant files can be found here: https://github.com/johannesjo/super-productivity/tree/master/src/app/features/issue/providers/gitlab

**Comment by johannesjo** [comment]
This is already fixed.
