### ISSUE TITLE
Window cant open once its minimize.

### ISSUE THREAD

**Issue by QuakeString** [johannesjo/super-productivity#44]
once I minimize SuperProductivity it cant reopen, means the window of SuperProductivity not visible, but I can see from system monitor its running, if I kill that process and again start SuperProductivity, its again start, but same thing will happen if I minimize it again. I try. -->

## Your Environment
I'm now on Kubuntu 17.10, 64bit, I have try before with Ubuntu 17.10, 64bit (default DE), on both of them same  result
* Version used: I try installation from snap, .deb & AppImage all of them have same problem, I tried 1.6.8, 1.6.7, 1.6.5
* Operating System and version: Kubuntu 17.10, KDE Frameworks Version 5.38.0, Qt Version 5.9.1, Kernel Version 4.13.0-17-generic 64bit
* Desktop Environment: <KDE Plasma 5.19.5>
* Browser Name and version: <Firefox Quantum>

## Current Behavior
Once I minimize SuperProductivity it cant reopen, means the window of SuperProductivity not visible, but I can see from system monitor its running, if I kill that process and again start SuperProductivity, its again start, but same thing will happen if I minimize it again.

## Steps to Reproduce (for bugs)
There is no step I found yet to reduce.

**Comment by Morganamilo** [comment]
Strange, I thought i fixed this in 1.6.0. Is there any error? can you try running it in the terminal and see if it prints an error there. Also does it re-open if you right click the tray icon and click open from there?

**Comment by QuakeString** [comment]
it doesn't show any error in terminal.

**Comment by Morganamilo** [comment]
Strange, I'm not sure what to make of that. You'll just have to wait for the real dev to take a look.

**Comment by johannesjo** [comment]
@QuakeString thanks for reporting. Sorry for the late reply. I was on vacation ;) The behavior was originally intended so you have a minimize to tray functionality. But I think it is not ideal and I remove it for the next release.

**Comment by johannesjo** [comment]
Closing this one. If that behavior still occurs in the next release, please let me know.

**Comment by QuakeString** [comment]
thanks, its fixed..
