### ISSUE TITLE
How to delete a project?

### ISSUE THREAD

**Issue by cabecaio** [johannesjo/super-productivity#442]
### Your Environment

* Version used: Super Productivity 5.4.3
* Operating System and version: Manjaro Linux
* Desktop Environment: KDE Plasma 5.18.5
* Resolution: 1920x1080

### Expected Behavior
I can not see an option for delete a project. I think the option can be hidding because of my resolution.

![image](https://user-images.githubusercontent.com/57970850/87216044-3ab52880-c312-11ea-9e3b-938d34367c43.png)

**Comment by johannesjo** [comment]
Hey there! You can delete projects from the "Manage Projects" page by clicking  the trash bin icon there.

**Comment by cabecaio** [comment]
ohh sorry!! I think I was tired yesterday when I started to test it. Sorry and thanks for attention and congratulations for great job!

**Comment by johannesjo** [comment]
No worries :)

**Comment by jabbalaci** [comment]
Note: I just noticed that you can delete a project only if this project is not active. The name of the active project appears in bold in the Project Manager.

**Comment by hced** [comment]
@johannesjo Is there no way to delete the default "Super Productivity" project? The trashcan icon is dimmed for me. I can only delete custom made projects.

**Comment by johannesjo** [comment]
@jabbalaci you can delete any project, but not if it is currently active.
