### ISSUE TITLE
[Feature] Ability to see all tasks across many projects in one list

### ISSUE THREAD

**Issue by drgerd** [johannesjo/super-productivity#444]
Hi, I start to use Super Productivity and find out it quite useful for me but, unfortunately, I have many projects and I need to have an ability to see all tasks from different projects, overall in one place to select which I will plan for today, to be able to focus on the important one first. Are there any plans for this or I mist some functionality?

**Comment by johannesjo** [comment]
Hi! Which version are you using? You can use either "Today" or a custom tag for this.

**Comment by drgerd** [comment]
5.4.2 for windows. 
About "Today" tag, I can't use that, and it is exactly my issue, I need "today" just for today but I have a huge list of tasks with different prioritization. I played around and found a way where I can create the tag "backlog" and mark all newly created tasks with "backlog" tag and now I can see all of them in one place. The only issue I have now that I need to manually set "backlog" tag for new tasks that I am creating. Is there any way to create tag automatically on task creation? I have seen such functionality in the Misc Settings section but for projects, and ("Automatically add today tag to worked on tasks").

**Comment by johannesjo** [comment]
Ah ok. I now understand your problem. I gotta think about this. It's likely to be very tricky to implement as the current system requires some sort of context (either a task or a project) to be active for all sorts of things. So we can't just use the existing task view, as many things might not work as expected and I am also not sure where to best put this in the menu (if at all). To be honest: If the demand isn't huge for this feature, I probably won't implement it any time soon. 

I'll leave this open. If somebody else wants to see this feature, please upvote @drgerd initial comment.

**Comment by drgerd** [comment]
I understand, thank you @johannesjo

**Comment by NPReport** [comment]
An option that automatically tags new tasks with #All would work for me.  It would help give the ability to see all of your tasks that are buried in your project list.  Another option could be to allow for a default "scheduled date" of today or tomorrow so that all tasks show up in the Scheduled list and could be viewed (and rescheduled) from there.

**Comment by johannesjo** [comment]
@NPReport that's an excellent suggestion! Being able to configure default tags makes a lot of sense!

**Comment by johannesjo** [comment]
I think I was able to complete the feature. I would, however, need your help testing it. It's available on this branch:
https://github.com/johannesjo/super-productivity/tree/feat/all-task-list

If you have trouble building the app for yourselves please let me know. Then I'll create a binary for you.

**Comment by NPReport** [comment]
Thanks for implementing this Johannes! I'd like to help test the feature.  Although my undergraduate studies (many years) ago was in Computing Science, I am very rusty - could you point me towards some instructions on how to build the app?

**Comment by johannesjo** [comment]
@NPReport: I would start with running the dev server and testing it out there.
https://github.com/johannesjo/super-productivity#running-the-development-server

If you want to install the version for real you can run `yarn localInstall` afterward on linux.

**Comment by johannesjo** [comment]
@drgerd @NPReport if this is to complicated to do, I can also provide a version for you.

**Comment by johannesjo** [comment]
Since nobody seems to care, I am closing this.
