### ISSUE TITLE
Cannot read property 'taskIds' of undefined

### ISSUE THREAD

**Issue by focusandebug** [johannesjo/super-productivity#447]
### Your Environment

* Version used: 
* Operating System and version:
* Desktop Environment: 
* Browser Name and version: 

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by johannesjo** [comment]
Hello! Could you provide a little bit more detail, please?

**Comment by nk-gears** [comment]
Tried multiple backups. Getting this error. Looks like the latest version has the issue?

Mine is MacOSX Sierra with SP version : Version 5.2.3 (5.2.3.1564)

![Screen Shot 2020-07-22 at 12 20 21 PM](https://user-images.githubusercontent.com/897323/88143977-c6359000-cc15-11ea-885e-6da17a70ee35.png)

**Comment by johannesjo** [comment]
Version 5.2.3 is not the latest one. 5.4.2 is. Could you please check with that one again?

**Comment by nk-gears** [comment]
Same Issue with the latest.[](url)
![Screen Shot 2020-08-05 at 9 55 32 PM](https://user-images.githubusercontent.com/897323/89438473-7ce15680-d766-11ea-885b-d3d92fd60649.png)

**Comment by johannesjo** [comment]
@nk-gears did you also try the [v5.5.4](https://github.com/johannesjo/super-productivity/releases/tag/v5.5.4). I believe the issue should be fixed there.

**Comment by nk-gears** [comment]
The issue happens only whenever I restore the old JSON. Looks like I need to recreate all the projects and tasks again. Is there a way to fix the JSON manually before I restore them?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by johannesjo** [comment]
@nk-gears would you mind sharing your data to contact@super-productivity.com? Then I'll attempt to fix your data.

**Comment by johannesjo** [comment]
@nk-gears were you able to solve your issue?

**Comment by nk-gears** [comment]
No worries. I switched back to a different App for my daily usage (todoist)

But still i can send you that JSON so that you can troubleshoot it

**Comment by johannesjo** [comment]
Thanks for letting me know and no I don't need the data. :)
