### ISSUE TITLE
[question] How does auto-update work?

### ISSUE THREAD

**Issue by Morganamilo** [johannesjo/super-productivity#45]
Looking at one of the latest commits it seems you added auto updating. I was wondering how this works, especially since the .deb installs the program into /opt which would require root to write to.

Also is there a way to check what version I am currently running? Normally I do this through the package manager but if the app were to auto-update the package manager would not know of a version increase.

**Comment by johannesjo** [comment]
Hey! I'm not sure about all the details neither. We're using [electron-updater](https://www.electron.build/auto-update). Seems like that it just doesn't trigger for deb files (where we would need a ppa), but should normally work for AppImages (although there currently is a bug that does prevent that from working: https://github.com/electron-userland/electron-builder/issues/2366#issuecomment-350659427).

**Comment by Morganamilo** [comment]
Alrighty, thanks for the info.
