### ISSUE TITLE
Chinese translation feels strange, do you need a pr?

### ISSUE THREAD

**Issue by PannenetsF** [johannesjo/super-productivity#451]
Hi, your app is excellent which is the best list I used in Linux! 

But the Chinese translation feels a little strange and even some zh-terms do not stand for what they should be in English. 

And I think I could help with it, so if you need this I will open a PR after the job is done.

**Comment by PannenetsF** [comment]
For example:
```
"UPDATE_MAIN_MODEL_NO_UPDATE": "No model update chosen. Please note that you either have to downgrade to the *last* version, if you do not want to perform the model upgrade.",
```

In the zh-ver, the *last* is translated to *lastest*.

**Comment by johannesjo** [comment]
Hi! Thanks for opening this up. I can imagine that the Chinese translation must be horrible. Help would be very much appreciated!!

As you already found out, you just would need to edit this file and to provide a PR with the changes made:
https://github.com/johannesjo/super-productivity/blob/master/src/assets/i18n/zh.json

**Comment by PannenetsF** [comment]
Hi, I have fix 420/1130 line of it. But I can't find entry of the 'backlog' at line 16 of https://github.com/johannesjo/super-productivity/blob/master/src/assets/i18n/{lang}.json .

```json
"BL": {
    "FROM_OTHER_PROJECTS": "From other Projects",
    "NO_TASKS": "There are currently no tasks in your backlog",
    "SCHEDULED": "Scheduled",
    "TITLE": "Backlog"
  },
```

Even I choose to create a backlog, the item will be attached to task. So could you tell me how the 'backlog' item effect the app ? Thanks!

![image](https://user-images.githubusercontent.com/45866836/88471348-09a43d00-cf3b-11ea-9316-e84f62d96b1c.png)

**Comment by johannesjo** [comment]
I just checked. It seems that these – apart from Bl.NO_TASKS which is displayed when opening a project backlog and there are no tasks – are leftover translations not being used anymore. I removed them.

**Comment by PannenetsF** [comment]
Done!
