### ISSUE TITLE
Error: TypeError: Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by danielestevez** [johannesjo/super-productivity#453]
It seems the new version just crashes on opening :(
The only option seems to be 'Reload App' which runs again into the problem so the app is unstable

### Steps to Reproduce

1. Start the application

### Stacktrace
```
isHandledError (webpack:///src/app/core/error-handler/global-error-handler.class.ts:53:12)
handleError (webpack:///node_modules/@angular/core/fesm5/core.js:9066:33)
listenerFn (webpack:///node_modules/@angular/core/fesm5/core.js:14938:8)
getComponentLViewByIndex (webpack:///node_modules/@angular/core/fesm5/core.js:14970:21)
function (webpack:///node_modules/@angular/platform-browser/fesm5/platform-browser.js:615:35)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:421:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm5/core.js:28122:32)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:420:39)
task._transitionTo (webpack:///node_modules/zone.js/dist/zone.js:188:50)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:503:37)
```

### Meta Info
META: SP5.5.1 Electron – en-GB – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.5.1 Chrome/83.0.4103.122 Electron/9.1.0 Safari/537.36

**Comment by johannesjo** [comment]
Thanks for letting me know. I check this asap!

**Comment by johannesjo** [comment]
I am unable to reproduce this. Is there a little more info in the console than that or in the error modal? Maybe if you wait a little bit? I am looking for other stacktrace values than:
```
handleError (webpack:///node_modules/@angular/core/fesm5/core.js:9066:33)
listenerFn (webpack:///node_modules/@angular/core/fesm5/core.js:14938:8)
getComponentLViewByIndex (webpack:///node_modules/@angular/core/fesm5/core.js:14970:21)
function (webpack:///node_modules/@angular/platform-browser/fesm5/platform-browser.js:615:35)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:421:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm5/core.js:28122:32)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:420:39)
task._transitionTo (webpack:///node_modules/zone.js/dist/zone.js:188:50)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:503:37)
```

Ideally, the referenced files have a `ts` at the end rather than `js`.

This might be related to your data. May I ask, what version you were using before the update?

**Comment by danielestevez** [comment]
Wow, it seems it was some kind of cache thing?

I'm not able to reproduce it again and i reloaded like 4 times before :shrug: 

Closing this for now unless it comes up again

**Comment by johannesjo** [comment]
Thank you for letting me know! I am glad that it works now!

**Comment by johannesjo** [comment]
@danielestevez seems like you're not the only one being affected by this. Would you by any chance be willing to share a copy of your backup data from before the update? You could send it to contact@super-productivity.com.

**Comment by danielestevez** [comment]
Sure! Actually i was trying to find some steps to reproduce and i found this:
* Anytime i hit Ctrl key when the window has focus i get the previous message: after closing it with the DevTools i can work 'normally' with the app and pressing Ctrl shows the next message in the console but lets me keep working (copy/paste and shortcuts involving the Ctrl key do not work however):
```
main.fd58362f53e9a5e6b70d.js:1 GLOBAL_ERROR_HANDLER Error: TypeError: Cannot read property 'includes' of undefined
    at t.handleError (main.fd58362f53e9a5e6b70d.js:1)
    at Yi (main.fd58362f53e9a5e6b70d.js:1)
    at _a (main.fd58362f53e9a5e6b70d.js:1)
    at i (main.fd58362f53e9a5e6b70d.js:1)
    at HTMLDocument.<anonymous> (main.fd58362f53e9a5e6b70d.js:1)
    at t.invokeTask (polyfills.aebe8ecc43d658291381.js:1)
    at Object.onInvokeTask (main.fd58362f53e9a5e6b70d.js:1)
    at t.invokeTask (polyfills.aebe8ecc43d658291381.js:1)
    at e.runTask (polyfills.aebe8ecc43d658291381.js:1)
    at e.invokeTask [as invoke] (polyfills.aebe8ecc43d658291381.js:1)
```
which i guess it's not that helpful (no .ts references)

Also somehow i was able to get a more meaningful error message but i'm not able to find steps to reproduce. I'll try to get it back and copy here :cry: 

About the backup Where could i get this backup data before the update? (i don't really know what version i had, it automatically upgrades)

**Comment by danielestevez** [comment]
Got that error message again (pressing Ctrl again with the focus on the error dialog). It makes references to TS code related to combo keys so i hope it helps

```
TypeError: Cannot read property 'includes' of undefined
checkKeyCombo (webpack:///src/app/util/check-key-combo.ts:7:34)
checkKeyCombo (webpack:///src/app/core-ui/shortcut/shortcut.service.ts:140:17)
HostListener (webpack:///src/app/app.component.ts:158:26)
webpack:///src/app/app.component.ts:58:13
executeListenerWithErrorHandling (webpack:///node_modules/@angular/core/fesm5/core.js:14935:15)
getComponentLViewByIndex (webpack:///node_modules/@angular/core/fesm5/core.js:14970:21)
function (webpack:///node_modules/@angular/platform-browser/fesm5/platform-browser.js:615:35)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:421:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm5/core.js:28122:32)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:420:39)
META: SP5.5.1 Electron – en-GB – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.5.1 Chrome/83.0.4103.122 Electron/9.1.0 Safari/537.36
```

**Comment by johannesjo** [comment]
Thank you @danielestevez !! This narrows it down!
