### ISSUE TITLE
Dropbox Error 409

### ISSUE THREAD

**Issue by papernoise** [johannesjo/super-productivity#459]
### Your Environment

* Version used: Desktop version 5.5.0
* Operating System and version:
* Desktop Environment:  MacOS 10.15.6 (Catalina)

### Expected Behavior
Add all the requested data to the dropbox settings page, activate sync. done.

### Current Behavior
Everything seems to work fine, I can click the link, got the Auth Code, pasted it in and enabled syncing.
Super Productivity shows up in the apps page on Dropbox, the Access Token is shown in the settings, the remote folder was created (but is empty).
After a minute or less SuperProductivity tells me that there was an error:
![dropbox-error](https://user-images.githubusercontent.com/1595523/88452915-ee65fe80-ce62-11ea-9480-4884695f5a62.jpg)

### Steps to Reproduce (for bugs)
1. Add all info to Dropbox sync page on Super Productivity and follow all the steps to add the app to Dropbox
2. Enable Syncing

### Error Log (Desktop only)
Nothing is shown in the log

**Comment by papernoise** [comment]
Oh wait. I thought I had the latest version, but looks like this was solved in 5.5.2. I guess you can delete this.

**Comment by M3X3M** [comment]
Getting exactly the same error now on 6.2.2 on arch and on Android too

**Comment by M3X3M** [comment]
Apparently the file creation bugged out on me. I deleted the folders in DropBox and added the auth key again and now it seems to work.

**Comment by johannesjo** [comment]
@M3X3M Thanks for letting me know. I am glad that it works now for you.
