### ISSUE TITLE
[Bug] Completing a task has annoying behaviour 

### ISSUE THREAD

**Issue by Morganamilo** [johannesjo/super-productivity#46]
## Your Environment

* Version used: 1.7.0.r0.g5089cc7-1
* Operating System and version: Linux 4.14.11
* Desktop Environment: i3

## Expected Behavior
Box is ticked and nothing else

## Current Behavior
When I complete a task and check the box from either daily planner or work view the next task is instantly started. If i am not already in work view it will move me there.

This is especially annoying when trying to tick off backlogged tasks as every time I tick one it keeps moving me to work view,

## Steps to Reproduce (for bugs)

1. Have at least 2 tasks 
2. Go to daily planner
3. Complete a task

**Comment by Morganamilo** [comment]
After more testing I discovered this also applies for sub-tasks when there is a remaining sub-task inside of the same main task.

**Comment by johannesjo** [comment]
Hey there. Thanks for reporting! There are two related settings:
* There is an option under 'Misc Settings'  to disable autostarting the next task.
* There is an option under 'Misc Settings - Pomodoro'  to disable going to work view when starting a task.

**Comment by Morganamilo** [comment]
Ah that would be my bad then. Did this option used to be broken? It never did this in 1.6.17 which is the version I just updated from.

**Comment by johannesjo** [comment]
It's not really related, so it should have worked like this before (if you had the option activated). But I never used it myself, so I'm not 100% sure.

**Comment by Morganamilo** [comment]
Okay then, no point on dwelling on past bugs. Thanks for fixing this so fast.
