### ISSUE TITLE
Error: Not in project context

### ISSUE THREAD

**Issue by NPReport** [johannesjo/super-productivity#466]
Thanks so much for the great tool. I am really enjoying using it and am just dutifully reporting this error.

This error was thrown when I pressed Shift-v (show/hide bookmarks) while in the "Today" list.  I assume that's because you intended project bookmarks to only be available when inside a project and not inside the Today list

(Separately, I spend most of my time in the Today list and it would be nice to have some generic bookmarks available there - but I can work around it by creating a Project called "Bookmarks" and putting my bookmarks there.)

Windows 10 App

Error: Not in project context.
isHandledError (webpack:///src/app/core/error-handler/global-error-handler.class.ts:53:12)
observable$.pipe(catchError(function (webpack:///node_modules/@ngrx/effects/fesm5/effects.js:161:25)
error (webpack:///node_modules/rxjs/_esm5/internal/operators/catchError.js:34:30)
this._tapError.call (webpack:///node_modules/rxjs/_esm5/internal/operators/tap.js:61:25)
error (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:59:17)
notifyError (webpack:///node_modules/rxjs/_esm5/internal/OuterSubscriber.js:13:25)
_error (webpack:///node_modules/rxjs/_esm5/internal/InnerSubscriber.js:18:20)
error (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:59:17)
_error (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:79:25)
error (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:59:17)

**Comment by johannesjo** [comment]
Thank you very much for reporting. I look into it.

**Comment by johannesjo** [comment]
This will be fixed with the next release. Thanks again!
