### ISSUE TITLE
Error: No tag

### ISSUE THREAD

**Issue by NPReport** [johannesjo/super-productivity#467]
Windows 10 App

(I created a tag associated to a single task, then I think I removed the tag from the task but it still showed in the list of tags in the sidebar.  I selected "delete tag" for the tag in the sidebar and it threw this error.

Error: No tag GdSxGTHCS
! Please copy & report !

Error: No tag GdSxGTHCS
webpack:///src/app/features/tag/store/tag.reducer.ts:45:12
memoize(function (webpack:///node_modules/@ngrx/store/fesm5/store.js:627:29)
isArgumentsChanged (webpack:///node_modules/@ngrx/store/fesm5/store.js:576:37)
selectors.map(function (webpack:///node_modules/@ngrx/store/fesm5/store.js:601:38)
defaultMemoize(function (webpack:///node_modules/@ngrx/store/fesm5/store.js:630:35)
isArgumentsChanged (webpack:///node_modules/@ngrx/store/fesm5/store.js:576:37)
source$.pipe(map(function (webpack:///node_modules/@ngrx/store/fesm5/store.js:513:66)
_next (webpack:///node_modules/rxjs/_esm5/internal/operators/map.js:35:34)
next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:53:17)
observers.slice (webpack:///node_modules/rxjs/_esm5/internal/Subject.js:47:24)

**Comment by johannesjo** [comment]
I think I found the cause of this. Am I assuming correctly that you were trying to delete the tag, while you had it selected in the menu?

**Comment by NPReport** [comment]
Yes, turns out that's the problem.  Deleting the tag while the tag is selected (i.e. the main screen is showing the list of tasks with that tag).  

Thanks again Johannes for the great tool.

Nathan

**Comment by johannesjo** [comment]
I am glad that you like it! :)
