### ISSUE TITLE
[Improvement] Time management Jira integration. Work on tasks not assigned to me.

### ISSUE THREAD

**Issue by laurenblackfox** [johannesjo/super-productivity#47]
## Your Environment

* Version used: 1.7.3-1
* Operating System and version: ArchLinux
* Desktop Environment: XFCE

## Behaviour
SP is set up to connect with Jira. Essentially, when starting a task using the play button. SP polls jira, and if the task is assigned to another person brings up a box which asks "Assign to yourself, or don't start task". This is not useful when multiple people are working on the same ticket. I'm a Senior Developer at my workplace, and while mentoring Juniors working on tickets, I need to assign my own time logs against tickets that they're working on. There needs to be a third option in this dialog to the effect of "Track time, but don't assign to myself."

**Comment by johannesjo** [comment]
Thanks for reporting! The suggestion makes a lot of sense! Would you care providing a pull request yourself? The implementation should be pretty straightforward.

**Comment by johannesjo** [comment]
You can find the related code here: https://github.com/johannesjo/super-productivity/blob/develop/app-src/scripts/main/global-services/jira-s.js

**Comment by laurenblackfox** [comment]
I can have a crack at it, sure. I think there's also a minor issue that would get in the way though. I've had it a couple of times where an issue is in my day list and not assigned to me, it repeatedly alerts me that the issue is assigned to someone else. I don't know if this is done as part of a regular poll to jira, but can be annoying to get an alert every few seconds. May be better as a config option?

**Comment by johannesjo** [comment]
Yes I agree. Personally I never had the case where I couldn't assign an issue to me on which I'm working. That's why the application doesn't deal with that at all. I will add an option for that tomorrow.

**Comment by johannesjo** [comment]
I added an option for that. So you should be good to go.

**Comment by laurenblackfox** [comment]
Legendary! I'll take a look at all this when I get back to work on Monday. :)

**Comment by johannesjo** [comment]
Excellent :)

**Comment by laurenblackfox** [comment]
Hi @johannesjo I've been supersuper busy with work lately so sorry I didn't get back to you sooner. I was unable to test, regrettably. Something up with my setup i suppose, so I'll not be able to look at it properly until it's released. Looking at the code changes, it appears to be exactly what I need. :) Much appreciated!

**Comment by johannesjo** [comment]
Hey there! The release should be out now.

**Comment by laurenblackfox** [comment]
That's awesome. Tested, works spot on. Noticed a couple unrelated issues while working today. Will create tickets for them when I have a few moments.

**Comment by johannesjo** [comment]
Glad that it works :)
