### ISSUE TITLE
[Jira Integration] No description in Additional Info

### ISSUE THREAD

**Issue by BaalEvan** [johannesjo/super-productivity#473]
### Your Environment

* Version used: 5.5.3
* Operating System and version: Windows 10, 1903
* Desktop Environment: 
* Browser Name and version: 

### Expected Behavior
I should be able to see Description in Additional info

### Current Behavior
I don't see Description perhaps because our jira is using custom field as description

There is Redacted exported 
[TUD-1321.txt](https://github.com/johannesjo/super-productivity/files/5012420/TUD-1321.txt)
XML for Issue in attachments.

**Comment by johannesjo** [comment]
I am pretty sure that the best way to solve this for you is adding support for #472, so I am closing this in favor of it.

The quickest way for you to make this work might be forking the project and editing `jira-issue-map.util.ts`
