### ISSUE TITLE
[Feature Request] Filter backlog from tag view

### ISSUE THREAD

**Issue by theCalcaholic** [johannesjo/super-productivity#475]
In order to effectively use both, the backlog and tag features, it would be great to be able to have the separation into active tasks and backlog available in the tag view as well.

Alternatively, a checkbox for showing the (tagged) tasks backlog would work for me too.

Use case: I'm actually rarely using the project's main view, but exclusively tag views when working. That way, I can concentrate more easily on the tasks concerning a single topic. It may be more relevant for me than for you, because I have many non-project tasks (as I understand, that you're a freelancer).

Another great improvement would be to be able to move sub tasks separately. Otherwise, very large parent tasks are still not really an option, because they will clutter my active tasks list for weeks or months and I can't prioritize (reorder) them individually. Therefore I usually fall back to mark sub tasks by their title (e.g. "parent -> sub task").

**Comment by johannesjo** [comment]
Hey! Thanks for the suggestions! I try to look into it. Not sure when I get to it though and how it might be implemented.

I think (if I understood the problem correctly) have the same problem with subtasks. How would you go about "moving them separately"?

**Comment by theCalcaholic** [comment]
It's actually not quite the same problem (and I probably should've created a separate issue for it).

For example, given I have a parent task with multiple subtasks, I want to be able to have all of the subtasks except for one in my backlog - because for me, the point of splitting tasks includes not working on all of them at once and if it's not in my backlog, I'm (supposed to) actively work on it. :)

Currently you can either have all of them in the backlog or all of them in the active tasks list - and they can't be reordered individually either.
