### ISSUE TITLE
[Feature Request] Add Reminders to Repeated Tasks

### ISSUE THREAD

**Issue by mohkamfer** [johannesjo/super-productivity#477]
Hey, this is the first contribution for this awesome project, I'm also a new user for this tool, but I've looked around and am positive it isn't included in Super Productivity.

**User Story**: Repeated Tasks feature is one of the main reasons I'm using this tool compared to countless other alternatives. It serves a good purpose of re-adding tasks everyday for the selected days. However, most of the time, this type of recurring tasks usually needs a reminder, and for people like me who like to do them in fixed times, it can sometimes be challenging to remember to do them at the appropriate time while you're busy working on other tasks or busy having a break. This is why reminders for repeated tasks is a feature that cannot be overlooked to achieve super productivity! :D

**The catch**, reminders for repeated tasks cannot have the full calendar widget that appears for normal tasks, since days are already pre-defined for such repeatable tasks. However, it'd only include a time, in hours and minutes, of when to remind the user about those tasks. Of course, the reminder would only happen for the tasks' selected days only.

**The future**, for now, given the amount of development being put into this tool, I'd say it's an overkill to set individual timers for each selected day, so my suggestion is having a general timer for each repeatable task, that reminds the user for each selected day. Consecutively, in the future, the fully customizable, per-day reminder-enabled repeated tasks feature could be implemented as a low priority supplement.

Thank you for reading, yours
  mohkamfer.

**Comment by johannesjo** [comment]
Thanks for opening this up. This is definitely something I'd like to see improved, even though it's not on top of my list.

**Comment by johannesjo** [comment]
Still relevant.

**Comment by johannesjo** [comment]
I am closing this in favor of: https://github.com/johannesjo/super-productivity/issues/948 (please upvote if you still like to see this).

Thank you very much for your input.
