### ISSUE TITLE
[Feature] Google Calendar Integration

### ISSUE THREAD

**Issue by thegayankalinga** [johannesjo/super-productivity#48]
## Your Environment

* Version used: AUR Updated to Newest as at today
* Operating System and version:Arch Linux (Manjaro) 
* Desktop Environment: KDE Plasma
* Browser Name and version: Chrome Newest to date

## Expected Behavior
Google Calendar Integration
So that i can see the google calendar(I have a calendar for my each projects) events  in the app
As well as I should be able to mark the tasks that need to go to google  calendar and then the system should sync to the google calendar.

## Current Behavior
No Google calendar integration

PS
I love this app. This is the  long overdue task manager application in the market 
Do the Mobile apps as well using progressive web app. So u will get the popularity.

Thanks 
Gayan

**Comment by johannesjo** [comment]
Hey there! Thanks for the suggestion! I'm happy to hear that you like the app!

This might be a nice addition. But could you give me an example how the syncing should work? 

What should be relatively easy to implement is just an iframe where you can load a custom url and pass the widget url to it .e.g.: `https://calendar.google.com/calendar/embed?src=your.user.name@gmail.com

**Comment by mmphego** [comment]
@johannesjo could you reopen the issue, I find it hard to keep track of my google calender and having it integrated to the app would be a great plus as I will be able to track which activity or project I need to focus on at specific times.

**Comment by johannesjo** [comment]
@mmphego could you give a a little more detailed example how this should work?

**Comment by mmphego** [comment]
Sorry for the late response, only saw this notification just now.

This made sense in my head, but could you add a feature such that as soon as you schedule your daily tasks google calendar gets updated as well?

Pretty much the same integration you have with GDrive sync backup - integrate Google Calendar API such that when you enter your schedule time this gets added to your calendar for tracking.


See the example below, 
![image](https://user-images.githubusercontent.com/7910856/73423170-fe79a700-4333-11ea-819b-477771667986.png)
 As soon as I save it, I would expect it to be synced to my calendar.

![image](https://user-images.githubusercontent.com/7910856/73423376-a42d1600-4334-11ea-89c5-2a3b6e4844e8.png)


Not sure if this makes sense.

**Comment by johannesjo** [comment]
@mmphego thanks for the explanation. Probably won't work on this myself, as I don't need it, but I am open about Pull Requests to make this an (optional) feature.

**Comment by theneo93** [comment]
Hello. I would like to integrate with Google calendar, but i do not understand how to do.
There any documentation or example for this?

**Comment by LunaVoid** [comment]
I'm also interested in this as well, the current implementation is a step forward but only has read ability of the gcal and not read write @theneo93 this will need to be done probably through https://developers.google.com/calendar/api/guides/overview. I know this is probably possible because todoist does the same thing. But I'm not sure how difficult of an endeavor it is.

**Comment by stefnotch** [comment]
@LunaVoid 
Could you open a new issue for that pretty please? And then link to this issue.

The reasoning is basically as an issue tracker grows, it becomes harder to keep track of everything. So a lot of devs reasonably end up not paying that much attention to closed issues anymore.

**Comment by LunaVoid** [comment]
> @LunaVoid 
> 
> Could you open a new issue for that pretty please? And then link to this issue.
> 
> 
> 
> The reasoning is basically as an issue tracker grows, it becomes harder to keep track of everything. So a lot of devs reasonably end up not paying that much attention to closed issues anymore.

Got it! The reason I didn't is because I'm kinda new to open source and I thought that because this was closed maybe it was not something they wanted to do. But sure I'll make it and link it!

**Comment by johannesjo** [comment]
FYI: In the next release there will be a much better integration of calendars coming. So I am considering this as done. Please let me know, if you have any feedback on the functionality (it's already available on the edge channel).
