### ISSUE TITLE
View what's done yesterday?

### ISSUE THREAD

**Issue by SjamonDaal** [johannesjo/super-productivity#484]
Is there any way to view what I've done yesterday? Just started using this app and finished my day but It removed the tasks that where finished today from the list. The next morning I need the list of tasks I've done yesterday.

**Comment by johannesjo** [comment]
Hey there! Welcome to the app! :) 

Please, let me know what you think or if you have improvement suggestions.

Yes, there is a way, to do so.

1. Open the menu by clicking the burger icon, if not open already.
2. Hover over "Today" or any Tag or Project you want to check.
3. Wait for the 3 dots to appear and click them
4. Select "Worklog"
5. Here you can select the day that you want to review and also do any kind of data export.

You can also check the "Week" tab on the finish day view.

**Comment by SjamonDaal** [comment]
Cool! Thanks for the info.
