### ISSUE TITLE
[Feature Request] Implementing Nestable

### ISSUE THREAD

**Issue by madjoe** [johannesjo/super-productivity#489]
Would be great to implement nested tasks. I've found an archived project here at GitHub that does pretty much most of the UI and it's quite intuitive and usable, but I'm sure there are some more up-to-date projects out there that do the same. I just started using Super Productivity for my projects and intuitively tried to find this feature. It would be quite handy.

jQuery / Zepto plugin: [Nestable Demo](http://dbushell.github.io/Nestable/)

**Comment by johannesjo** [comment]
Hey there! Thanks for the suggestion. Currently, I have no plan to add such a feature. Another layer would add a lot of complexity to some other features like the Jira work logs, to reminders, to time tracking general, but also on a UI-level. 

Personally, when I need subtasks for subtask, I convert the subtask to the main task. I also believe that they defeat the purpose of splitting your work into smaller chunks possibly leaving you working on some huge mega tasks instead.
