### ISSUE TITLE
Time being calculated when nothing is active

### ISSUE THREAD

**Issue by Revulse** [johannesjo/super-productivity#49]
I'm using Windows 10 Pro. Also using SuperProductivity v1.7.3.

I installed this application using the setup installer.

Expected Behavior:
When you click pause, it pauses.
Wait 5 minutes.
When you click Play, it starts from the time it left off.

Current Behavior:
When I click pause, it pauses.
I wait 5 minutes.
When I click Play again it adds those 5 minutes of being idle to the amount of time that I had left off at and continues counting from there.

Whatever amount of time that I have the application open for and do not press Play for any task, when I go to press play, that task's "Time Spent" value gets immediately changed to the amount of time that I've had the application open for. 

My workaround for this issue is that I have to create a task that I've named "Idle Task" and when I am not performing any tasks, I click Play on the "Idle Task" so that it's not counting in the background and going to add all of that time of being idle to the next task that I go to begin.

**Comment by mlafleche** [comment]
I have the same problem.  I am using Windows 10 also.
I tried the Install v1.7.3. and the portable exe v1.7.3. , same behaviour for both.

**Comment by johannesjo** [comment]
Thank you very much for reporting. I'll look into it tomorrow.

**Comment by johannesjo** [comment]
This will be fixed with the next release 1.7.4. Please report back if it doesn't fix the issue.

**Comment by Revulse** [comment]
Thank you for fixing the issue. It works for me now with version 1.7.4.
