### ISSUE TITLE
Memory consumption too high

### ISSUE THREAD

**Issue by makkasi** [johannesjo/super-productivity#493]
Memory consumption was too high this morning when I started my computer after hibernate. I opened the monitor tool and watched how with every second the superProductivity app increased its memory usage. I stoped it on about 11G of RAM.
version: 5.4.1

![productivity](https://user-images.githubusercontent.com/3597604/89756015-fae88900-dae9-11ea-9d77-4a01d1d2bc3b.png)

**Comment by johannesjo** [comment]
Thanks for opening this up. This is absurdly high. 

Did the memory usage stay at this level afterward or did it drop to a more normal level again?

**Comment by makkasi** [comment]
I stopped it since I was watching it growing from 10 500 till 11 000.

**Comment by johannesjo** [comment]
I tried to reproduce this, but I am unable to do so. There doesn't seem to be any obvious memory leak. Maybe it's an electron issue of some sort. I assume that there is not much I can do at the moment, but please let me know if the issue reappears!

**Comment by makkasi** [comment]
Yes of course. There is not much info in order to do anything on your side. If I see this again will try to make some memory snapshot. I don't know tool for this though. Thank you.

**Comment by makkasi** [comment]
Yes of course. There is not much info in order to do anything on your side. If I see this again will try to make some memory snapshot. I don't know tool for this though. Thank you.

**Comment by makkasi** [comment]
Hi again. I saw first high memory consumption.  Then I took snapshot of the memory. Then I opened the app and saw the clock frozen :). Then I minimized the app and opened it again and saw the clock updated (66 hours) and the memory consumption was back to normal.  


![productivity2](https://user-images.githubusercontent.com/3597604/90120208-29bd6400-dd63-11ea-89f3-e00347ef14f4.png)
![productivity1](https://user-images.githubusercontent.com/3597604/90120189-26c27380-dd63-11ea-9b8d-f1a4e33dba8a.png)

**Comment by makkasi** [comment]
Sorry , I did not want to close it. Reopening.

**Comment by makkasi** [comment]
Strange. It is not reopening.

**Comment by johannesjo** [comment]
Darn! For a moment I hoped the issue solved itself xD

Thanks for getting back to me! I've a suspicion what might be going on. Might be that the browser (electron) saves and then executes all missed interval handlers from the callstack at once (there is at least one every second when tracking time). Gotta do some research!

**Comment by johannesjo** [comment]
I found this:
https://stackoverflow.com/a/14840440/1574004

I'll try adjusting every setInterval function this way.

**Comment by johannesjo** [comment]
A fixed version will be available on the edge channel soon. Thank you very much again for digging into this. I hope that the changes will resolve the issue.

**Comment by johannesjo** [comment]
@makkasi sorry for bothering you again, but did you encounter this again with the most recent version?
