### ISSUE TITLE
[Bug] Timer in macOS menu bar does not update

### ISSUE THREAD

**Issue by KernelYoda** [johannesjo/super-productivity#494]
### Your Environment
* Version used: 5.4.3 (5.4.3.1638) via homebrew
* Operating System and version: macOS 10.14.6

### Expected Behavior
The timer in the menu bar button should get updated as time progresses.

### Current Behavior
The timer does not progress as time progresses. It only gets updated when manually pressing the "Start/stop tracking time" button within the desktop app, or when a break starts/ends.

<img width="767" alt="superProductivity_issue" src="https://user-images.githubusercontent.com/12196044/89863973-c697ca00-dbc8-11ea-9a39-564ff34a66a1.png">

_Mismatch between timer in menu bar and app._

**Comment by johannesjo** [comment]
I am removing this in favor of a progress-indicating icon. Thanks again for reporting this.
