### ISSUE TITLE
[Suggestion] Add toggle to display/hide task name in macOS menu bar

### ISSUE THREAD

**Issue by KernelYoda** [johannesjo/super-productivity#495]
### Your Environment
* Version used: 5.4.3 (5.4.3.1638) via homebrew
* Operating System and version: macOS 10.14.6

The app may provide a toggle option as part of its settings to show/hide task name in the menu bar.

Currently, the app takes a lot of screen estate in the menu bar. This makes other useful apps in the menu bar unreachable. Its not much of an issue on large monitors but it is on a laptop screen.

<img width="767" alt="superProductivity_issue" src="https://user-images.githubusercontent.com/12196044/89876246-05834b00-dbdc-11ea-8cd7-c43629b517e7.png">

_App in menu bar hides other icons making them unusable._

**Comment by johannesjo** [comment]
Thanks for opening this up! This should be a good issue to solve for people being completely new to the project.

**Comment by fuerst** [comment]
I propose the following:

1. Adding a new setting at General > Misc, called _Show current task in the tray / status menu (desktop only)_.
2. If setting is true the indicator string at _electron/indicator.ts_ will not be created.

Question for me is: how do I get access to the settings object from within indicator.js? I tried adding `ipcMain.on(IPC.TRANSFER_SETTINGS_TO_ELECTRON...)` and using getSettings() inside of `indicator.ts:initListeners()` but had no luck with it. Any help much appreciated!

**Comment by johannesjo** [comment]
@fuerst seems to me that this is broken:
https://github.com/johannesjo/super-productivity/blob/10f1ea5a68d2786d1190c7e8952b0b5c2d99d4dc/electron/get-settings.ts#L5-L10

`getSettings` is likely not provided with the right params from the `ipcMain.on` callback. I can have a look later today if you want.

**Comment by fuerst** [comment]
Would be nice, thank you!

**Comment by johannesjo** [comment]
@fuerst I just checked the following code:
```
setTimeout(() => {
  getSettings(mainWin, (settings) => {
    console.log(settings);
  });
}, 7000);
```
Seems to work fine. My suspicion from earlier today was wrong :) Did you maybe forget to pass the mainWindow? This is required for getSettings.

Sorry for the messy code for the electron part there btw.. Never found the time to clean it up...
