### ISSUE TITLE
Add setting to Git**b integration to only add assigned issues to backlog

### ISSUE THREAD

**Issue by sdruskat** [johannesjo/super-productivity#496]
### Your Environment

* Version used: 5.5.7
* Operating System and version: Win 10
* Desktop Environment: n/a
* Browser Name and version: n/a

### Expected Behavior

To focus on the tasks that I *actually* need to do, it'd help me to only see issues in GitHub/GitLab integrated projects' backlog which are actually assigned to me.

I appreciate that this may not be something that all users would want to have as default, therefore I think a setting in the respective project would be the right place to configure.

If this is switched on, I would only see issues/PRs assigned to my username in the backlog, so that I can pull them into Today.

### Current Behavior

All issues/PRs are listed to a project's backlog.

### Steps to Reproduce (for bugs)

n/a

### Console Output

n/a

### Error Log (Desktop only)

n/a

**Comment by johannesjo** [comment]
Thanks for opening this up. Makes a lot of sense to me. Currently, I am busy with other features, but I gladly accept any PR.

**Comment by sdruskat** [comment]
Great, thanks. I understand. I have little experience with JS, but if I can find the time I'd love to put some effort into this.

**Comment by johannesjo** [comment]
@sdruskat that's great to hear! Please let me know if you have any questions.

**Comment by b0c1** [comment]
What's is the plan, if the issue moved to another assignee? Remove to the backlog?

**Comment by johannesjo** [comment]
Well I assume @sdruskat is no interested in doing it anymore (right @sdruskat ?). So if somebody else wants to tackle this, I am all for it!!

**Comment by b0c1** [comment]
I already completed the filtered auto add. The question is what happened the backlog elements with assigned to nobody or later assigned to somebody?

**Comment by johannesjo** [comment]
Ah ok. Misunderstood your question. There currently is no mechanism for that for the Git* integrations. The jira integration checks once whenever you start tracking on a Jira Task if another user was assigned to the issue. Maybe this could be an addition for the Git* integrations as well? 

Personally I use Gitlab and Github only for version control and as a sort of bug tracker, as there is no currently no team which would require a more sophisticated approach, so this never popped up as a problem for me.

**Comment by b0c1** [comment]
In this case, what's the best way to remove the backlog tasks? I try to use ```taskService.removeMultipleMainTasks``` but it creates an inconsistent state on the project.

**Comment by sdruskat** [comment]
> Well I assume @sdruskat is no interested in doing it anymore (right @sdruskat ?). So if somebody else wants to tackle this, I am all for it!!

Still interested but have no time to spare atm, unfortunately, glad @b0c1 is picking this up.

**Comment by johannesjo** [comment]
> In this case, what's the best way to remove the backlog tasks? I try to use `taskService.removeMultipleMainTasks` but it creates an inconsistent state on the project.

If this creates an inconsistent state, than it is a bug. Usually this should be the way to go. Only alternative is using `remove` many times over. Could you elaborate in what way the state get's corrupted?
