### ISSUE TITLE
Fix delete a keyboard shortcut

### ISSUE THREAD

**Issue by theCalcaholic** [johannesjo/super-productivity#497]
Sorry for abusing the issue tracker for questions. I recently accidentally created a global keyboard shortcut and can't find a way to get rid of it.
I can reassign it, but don't find a way to delete it entirely. However, there must be a way, right? :)

**Comment by johannesjo** [comment]
No worries: That's currently the best place to ask things.

I thought that I had configured the Escape key to do that. That doesn't seem to work anymore, however.

**Comment by theCalcaholic** [comment]
Alright, thank you :+1:
