### ISSUE TITLE
Error when displaying backlog with mouse click on touchscreen device

### ISSUE THREAD

**Issue by fedba** [johannesjo/super-productivity#498]
I understand that this might be a fairly unique issue, but it's pretty annoying for me. So I'm hoping it's not a difficult thing to fix
Otherwise, this is a great app thanks for the work that's gone into it.

### Your Environment

* Version used: 5.5.2 installed via windows store
* Operating System and version: Windows 10,
* Browser Name and version: also happens on web version, Firefox

### Expected Behavior
When managing projects, clicking and dragging to show the backlog

### Current Behavior
Using a windows 10 tablet (Samsung Galaxy Tab Pro S in this case) with the keyboard disconnected (Issue doesn't happen if i have the keyboard attached)
I use barrier to forward mouse and keyboard to the tablet and use it like a second screen.
When clicking and dragging to display the backlog, Error displays on screen
This also happens when using the built in windows on screen mouse touchpad thing.

This doesn't happen if the keyboard is attached, so I'm guessing there is a setting somewhere where it is getting into a "tablet/touch" mode and breaks if it receives a click using a mouse cursor

currently to get around this i have to remember to use the touch screen to drag and display the backlog, i haven't run into the issue while doing anything else with the app. (or leave the table plugged into it's keyboard.

### Steps to Reproduce (for bugs)

1.using a windows tablet
2.Detach the keyboard
3.using barrier or the on screen touchpad click to show the backlog while managing projects.

### Console Output

onMove (webpack:///src/app/features/work-view/split/split.component.ts:111:35)
onMouseDown (webpack:///src/app/features/work-view/split/split.component.ts:88:36)
__tryOrUnsub (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:192:15)
next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:130:21)
_next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:76:25)
next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:53:17)
_next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:76:25)
next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:53:17)
handler (webpack:///node_modules/rxjs/_esm5/internal/observable/fromEvent.js:18:27)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:421:34)

META: SP5.5.2 Electron – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.5.2 Chrome/83.0.4103.122 Electron/9.1.0 Safari/537.36

### Error Log (Desktop only)
can't seem to locate the error log.

**Comment by johannesjo** [comment]
Hey there! Thanks for opening this up! Currently, I've more to do with this project that I can handle, but I am sure I get to it at some point. In the meantime, PRs are very welcome!

**Comment by fedba** [comment]
This does still happen.
I've just tested it again, now updated to version 6.3.3
Unfortunately I have not much new I can add to fixing this. In the meantime I've mostly just got used to it and try to remember to use touch when working via Barrier.
