### ISSUE TITLE
Android App: "Real" Notification for Promodoro Breaks

### ISSUE THREAD

**Issue by Yaavina** [johannesjo/super-productivity#506]
I'm using Super Productivity on my Android Smartphone. I also use a cheap fitness tracker with the "Notify and Fitness" Application.
It seems the Super Productivity Application doesen't send "real" smartphone notifications (like whatsapp messages, etc.), when a promodoro session is completed.  I suspect that's why my fitness tracker application doesen't notice the promodoro breaks and dosen't show anything on my watch.
Is it possible to implement a feature, so that the promodoro break timer shows up as a "real" smartphone notification, instead of just a sound in the Super Productivity Application?

In general it would be great to see the remaining promodoro-time in the android status bar or on the lock screen of my phone.

**Comment by johannesjo** [comment]
Sorry for the late reply. I've got this on my radar, but I am currently very busy with other stuff.

**Comment by ffcruz85** [comment]
@johannesjo sorry this is closed from being stale, but I would like to say this would be great, as I often use the app to track tasks that I am doing away from my PC (like chores around the house, for example, trying to get superproductivity to stop me from engaging in "productive procrastination" haha). I know you are busy, but maybe you could throw this back into the roadmap, even if long term?

**Comment by fcruz-ehr** [comment]
Just keeping the issue alive in case @johannesjo is still considering this in the future :)
