### ISSUE TITLE
"forgot to start timer" alert

### ISSUE THREAD

**Issue by papernoise** [johannesjo/super-productivity#507]
I find the idle alert timer very handy for when you forget to stop a timer and take a break. I use it all the time and it works really well! Well done. I was wondering if you had any plans for the other scenario: when somebody starts to work on a taks, but forgets to start the time. Right now it's a bit hard to backtrace your steps, maybe the application could also track when you have no timer running but are not idle? 

### Your Environment
* Operating System and version: MacOS Catalina

**Comment by johannesjo** [comment]
So I just wanted to start working on this, but then I thought it might be good to talk about the exact conditions when this banner shows up before implementing it. I'll outline some basic rules, please let me know if you got anything to add to this (and also if you don't :)):

The timer should start counting on:
- app start
- whenever there is no current task set for tracking time

The banner should be shown when:
- after X minutes without being idle and without tracking time 
- (maybe we can use the idle setting here + a little bit on top)

The banner should not be shown or hidden (and the timer be reset) when:
- idle is activated
- when time is tracked

**Comment by papernoise** [comment]
> I  thought it might be good to talk about the exact conditions when this banner shows up before implementing it

Absolutely!

I think your reasoning is solid! Though let me try to imagine some scenarios just to see if anything else comes up.

When the app starts there is four possible situations:
1. I click on a task and start working
2. I organize my tasks or perform other "householding" actions inside SP
3. I do nothing (sometimes I start the computer but then do things away from it, so it runs idle)
4. I start to work but did not start a timer

#3 is covered by the curent idle detection and that already works really well for me
#4 should be covered by the new "forgot timer" function

Then let's say I have a timer running and I stop it, I can then imagine these scenarios:
1. I start a new timer and work some more
2. switch to another task, but forget to start the timer
3. I move away from the computer, or do not use it for some time (maybe I'm taking a break, maybe I just need to do something that does not involve the computer).

Again #3 is covered by the idle timer, #2 would be a case for "forgot timer".

As far as I can see, everything I listed is covered by your conditions above!

**Comment by johannesjo** [comment]
Implemented and should be available in the current pre release.

**Comment by logesh810** [comment]
Hi @papernoise and @johannesjo — first of all, thank you so much for building and maintaining such a great productivity tool! Super Productivity has been incredibly helpful in my daily workflow 

I came across this issue (#507 – “forgot to start timer” alert) where this feature was discussed earlier. It looks like something similar might have been implemented recently, but I just wanted to confirm — is this feature available in version **16.0.0** on **Windows**?

If yes, could you please let me know how to enable or configure it?

Thanks again for all the effort and improvements you’ve put into this project!
