### ISSUE TITLE
Activity indication won't disappear when timer is stopped

### ISSUE THREAD

**Issue by papernoise** [johannesjo/super-productivity#508]
### Your Environment
* Version used: 5.5.7
* Operating System and version: MacOS 10.15.6
* Browser Name and version: Desktop version

### Expected Behavior
When I stop the timer I would expect the progress bar on the dock icon and the incation on the menu bar to disappear, this would give me a univocous feedback about there being or not a timer running.

### Current Behavior
When I stop the timer, both the progress bar on the dock icon and the indication on the menu bar stay in place unchanged.

### Steps to Reproduce (for bugs)
1. start a timer
2. stop the timer
3. notice that nothing changes on the icon and menu bar

**Comment by johannesjo** [comment]
This should be fixed with our latest efforts. I am closing this.
