### ISSUE TITLE
Break Reminder Popping Up After Being Disabled

### ISSUE THREAD

**Issue by Revulse** [johannesjo/super-productivity#51]
I'm running Windows 10 Pro x64. I am using SuperProductivity v1.7.4.

Expected Outcome:
1. I disabled "Enable take a break reminder"
2. I am working on a task for a while.
3. No break reminder should come up.

My Outcome:
1. I disabled "Enable take a break reminder"
2. I am working on a task for a while.
3. Break reminder comes up about every hour or so, pausing my task that I am currently working on.

**Comment by johannesjo** [comment]
Hmm this really shouldn't happen. Not really sure what the issue is, as I wasn't able to reproduce this behavior and the code doesn't indicate any chance that this might happen. As a dirty workaround you could enable the reminder, set the timer to a ridiculous amount and disable it again.

**Comment by Revulse** [comment]
Interesting, and thank you, I just set it for 10 hours.

**Comment by Revulse** [comment]
So I figured out that it is "Pomodoro" feature even though I had it disabled. I tried setting that work session to a 10 hour session and it won't change. The Pomodoro timer button at the top right hand corner of the application starts at an hour, even after killing the application and restarting it. So it seems that even though I hit the disable button for Pomodoro, it show's the settings disappear, but it doesn't seem like the settings are really being turned off.. or able to be modified. Maybe it's just my system that I have it installed on.. I'm not sure.

**Comment by johannesjo** [comment]
Thanks! I publish a new version soon.

**Comment by Revulse** [comment]
Hey, were you going to publish that new version?

**Comment by johannesjo** [comment]
Oh. I totally forgot to press the release button here in git. Out now ;)

**Comment by johannesjo** [comment]
Oh. I totally forgot to press the release button here in git. Out now ;)

**Comment by Revulse** [comment]
Haha, thank you.

**Comment by Revulse** [comment]
Works perfect.
