### ISSUE TITLE
Android App : 

### ISSUE THREAD

**Issue by SylvainSimplonGit** [johannesjo/super-productivity#510]
Unable for me to connect my Google Drive with the Android version v5.5.7. While everything works fine with the same account with the Windows version v5.5.7.
Is the functionality on Android working if so, it must be a bug?
I am available to test this functionality if needed.

For more details :
On Android v9
- I activate "Enable syncing via Google Drive" slider
- I click on "Login" button
- on the modal "Selectionner un compte" (french is my native language), I click on my google account
- a "black slider bar" is displayed from top to bottom and nothing else...
- The "Login" button is displayed again but not the buttons "Backup Now" and "Load from GDrive" as Windows version.

If you want more log, where can I find log on android ?

**Comment by SylvainSimplonGit** [comment]
I Try this with the same result  (=> a "black slider bar" is displayed from top to bottom and nothing else) :
1- clear cache and delete data of super prodictivity app
2- clear cache, delete data, unistall and reinstall with play store of super productivity

**Comment by SylvainSimplonGit** [comment]
My problem is the same as the issue #434. Is there a way to got log in android ?

**Comment by johannesjo** [comment]
@SylvainSimplonGit there is, but it is [kind of complicated to setup for non technical users](https://developers.google.com/web/tools/chrome-devtools/remote-debugging) and might not won't work with the PlayStore version. Probably makes sense to implement a solution for this :)

**Comment by SylvainSimplonGit** [comment]
If you have an apk with this functionnality, i can install it with the developper mode.

**Comment by johannesjo** [comment]
I am currently not on my computer, but would this also work:
https://github.com/johannesjo/super-productivity-android
?

**Comment by johannesjo** [comment]
[app-debug.zip](https://github.com/johannesjo/super-productivity/files/5125704/app-debug.zip)

**Comment by SylvainSimplonGit** [comment]
I downloaded the apk on my phone running Android v9.
In settings I emptied the cache and cleared the data then uninstalled Super Productivity v5.5.7.
I installed this apk from my phone.
In the settings, I can see the Super Productivity application in version 6.0.
But when I open the app I have a white screen and after long minutes I get a message:
```
Web page not available
Failed to load web page http://10.0.2.2:4200/
...
```

**Comment by johannesjo** [comment]
Oh sorry. I forgot that the dev app points to my dev server for the app frontend. I make a new release in a moment.

**Comment by johannesjo** [comment]
[app-debug.zip](https://github.com/johannesjo/super-productivity/files/5142709/app-debug.zip)

**Comment by SylvainSimplonGit** [comment]
Sorry, but with the new app-debug.apk, it's the same result :
```
Web page not available
Failed to load web page http://10.0.2.2:4200/
...
```

**Comment by johannesjo** [comment]
I am very sorry. Seems like I send you the old one again (I some assumed that the zip was generated by the build but it was the old one I created in the same folder before). This time it should be the right one.
[app-debug.zip](https://github.com/johannesjo/super-productivity/files/5145407/app-debug.zip)

**Comment by SylvainSimplonGit** [comment]
Great, with this version, the sync with Google drive is OK. 
Good job ! 👍

⁣Télécharger TypeApp pour Android ​

Le 29 août 2020 à 17:11, à 17:11, Johannes Millan <notifications@github.com> a écrit:

**Comment by johannesjo** [comment]
I am happy to hear that! I'll update the web app in a moment (which is used from the android app).

**Comment by johannesjo** [comment]
@SylvainSimplonGit one question if I may. Today I tried fixing the google drive integration again for #434. Does the store version also work for you or just the debug-apk?

**Comment by SylvainSimplonGit** [comment]
I have v5.6.5 on my Android phone which works fine. On the Play Store, I saw that it is v6 that was updated on June 22. No traces of the version you would have updated yesterday ...

**Comment by johannesjo** [comment]
@SylvainSimplonGit thank you! Then I am closing this.
