### ISSUE TITLE
Release Android app on f-droid (for people not using google service)

### ISSUE THREAD

**Issue by TobiasDev** [johannesjo/super-productivity#512]
I recently found out that there is an Android app in development now! Is there any chance we are going to see this added to f-droid?

**Comment by johannesjo** [comment]
Hey! Thanks for opening this up. I will give it a go. Doesn't [seem to be too complicated](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7243/diffs), though I don't know how `fdroid build` works. Do you have any experience with deploying to fdroid?

**Comment by TobiasDev** [comment]
Sorry, I haven't ever done an Android app. :( So not sure how it works.

**Comment by papernoise** [comment]
Chiming in to say that I would reallty welcome that as well. But unfortunately I have no idea how that works.
This would be the official guide btw. https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/
Basically it seems they make the APKs from the source, if I'm not mistaken.

**Comment by johannesjo** [comment]
I opened up a PR:
https://gitlab.com/fdroid/rfp/-/issues/1523

Let's see how it goes.

**Comment by njakes** [comment]
Can you add FDroid as a download on your main read me next to the Play Store link?

**Comment by johannesjo** [comment]
@njakes will do so! Thanks for the suggestion!
