### ISSUE TITLE
Google Drive With Hardware Token

### ISSUE THREAD

**Issue by johannesjo** [johannesjo/super-productivity#514]
I have problem syncing with Google drive as well. I have this on my Ubuntu and thought I might try to use in in my Windows machine too but it does have a problem.

With Ubuntu, it got stuck to the window where it says logging in to Google while on Windows it keeps saying that: GoogleApi: Failed to authenticate please try logging in again!

Things to note: 
With my Google account, I am using a Yubiko key to authenticate so this might be an issue too. I really like this app, I hope it can be fix, I dont want to use Dropbox for now.
![google](https://user-images.githubusercontent.com/11805713/91254074-afe69b00-e7a4-11ea-9b58-b10e78ec890e.png)

_Originally posted by @mareekkk in https://github.com/johannesjo/super-productivity/issues/502#issuecomment-680536323_

**Comment by johannesjo** [comment]
@mareekkk As I don't have a hardware token available, I need your help debugging this :)

Would you be capable of running a development version of the app yourself?

**Comment by mareekkk** [comment]
> @mareekkk As I don't have a hardware token available, I need your help debugging this :)
> 
> Would you be capable of running a development version of the app yourself? Otherwise, I will try to compile a version just for you. What OS are you on, if I may ask?

I am terribly sorry for the very delayed reply. I was out camping for a week. I can do all the testing for you. I am running Ubuntu 20.04.1 and Windows 10 so I could test the development version in these two OSes with my hardware key. Just let me know~
