### ISSUE TITLE
drag&drop to assign project

### ISSUE THREAD

**Issue by papernoise** [johannesjo/super-productivity#515]
### Your Environment
* Operating System and version: macOS Catalina (Desktop version)
* App version: 5.6.2

### Imagined Behavior
Here's another one of my UI ideas :)
what about enabling drag&drop for projects to quickly assign a task?
The reason I see this is a good idea, is based on the following workflow:

1. I check the individual projects to see which stuff I might have to do today and click on the "today" button
2. Move to the today page and start collecting tasks, writing down everything that comes to mind and by combing through email and mesages.
3. I sort these tasks into projects and remove from today everything I don't need to do right away
4. prioritize everything, do some cleaning up then start to work.

Now for this workflow it would be great if I could drag a task onto a project to assign it, without having to right-click and choose the project from the – usually long – list.
Of course dragging the project onto the task – like you do with labels in Gmail – would also be a solution.
Let me know if this makes any sense!

**Comment by johannesjo** [comment]
Hey there! Thanks for opening this up. I wanted to implement this for a long time, but I simply haven't found the time to do so...

**Comment by papernoise** [comment]
> Hey there! Thanks for opening this up. I wanted to implement this for a long time, but I simply haven't found the time to do so...

I have to admit that I had the suspicion that I was saying something pretty ovbious!

> As a workaround until then: The quickest way to reassign a project is to use the keyboard shortcut for it and to then select the project via the arrow keys.

Thanks a lot for the tip! Will definitely try that!

**Comment by nicola-lunghi** [comment]
+1 here
