### ISSUE TITLE
Logo Redesign

### ISSUE THREAD

**Issue by Leakbang** [johannesjo/super-productivity#519]
Hello @johannesjo 
Thank you for your awesome application. Love it :)
But I think your app could use some better logos. I designed these minimalistic logos. Feel free to use them in your application if you like them. Or if you'd want you can reach out to me and we can work on a finalized logo for your app :)
Description | Preview
------------ | -------------
Badge 50 x 50px | ![badge](https://i.imgur.com/685laBE.png)
Square tile 150 x 150px | ![medium](https://i.imgur.com/DrsOWfP.png)
Wide tile 310 x 150px | ![wide](https://i.imgur.com/nu1isc1.png)
Large tile 310 x 310px | ![large](https://i.imgur.com/eKHXCNM.png)

You can view the higher quality ones here:

**Square**: https://i.imgur.com/ctW8b21.png
**Wide**: https://i.imgur.com/DJV7Ewe.jpeg
**Large**: https://i.imgur.com/oAfOUWf.jpg

**Comment by johannesjo** [comment]
Hey there! Thank you very much! They look very good and I really like the colors! But I am also pretty happy with the current logo though. It's a bird against the sky, you know ;) I might revisit this later on at some point however.

You seem to have a knack for design. Do you have any other improvement suggestions for the app design itself maybe?

**Comment by Leakbang** [comment]
Yeah, so major complaints but some suggestions I have are:
* Make the dark mode toggle on with the system settings automatically 
* The productivity tips at the splash screen go away so quickly so, in my opinion, have them show up somewhere in the app itself (at the top or in the 'Help I'm procrastinating')
* Being able to set the color scheme or custom backgrounds would be a very welcome addition :)  

The overall UX is very fine but there are small things you can optimize here and there.
For example, the notes section is a bit awkwardly placed. Since it supports markdown, it would be a very useful feature if it was easier to access. I liked that in the older versions, the notes had their own dedicated section on the right sidebar. 
But more importantly, you should focus on the design consistency. For example, rounded corners. Right now some things are rounded and some aren't. 
But all in all, the design is very good :) no real complaints,  just nitpicks.

**Comment by johannesjo** [comment]
Thanks for the suggestions! I like all of them. 

Automatic dark theme styles should already work if you're on a mac (but I don't think it's possible yet for other OS).

I agree that the duration of the productivity tips might be a little too short sometimes. I didn't really see them as a feature and more as a more useful type of loading spinner.

Custom use stylesheets are something I wanted to implement for quite some time, but there is so much to do :)
