### ISSUE TITLE
[Feature Request] Global evaluation sheet

### ISSUE THREAD

**Issue by tetrahedon7** [johannesjo/super-productivity#520]
Project pages seem to have an evaluation sheet but the Today page doesn't. I found this odd because that sheet would be more appropriate in the Today page, that it, to be able to evaluate the day's productivity regardless of which project's tasks you completed. Could there be an option to enable it on the Today page?

OS: Windows 10, Android 10

**Comment by johannesjo** [comment]
Thank you very much for opening this up! I very much like the suggestion and will try to work on it as soon as I can. Meanwhile pull requests are welcome too of course!

**Comment by Rodeo-McCabe** [comment]
Commenting to link some relevant issues:

#771  
#298  
#730

**Comment by johannesjo** [comment]
So the feature just landed in the master branch (and the edge channel will follow shortly). I could use some help testing it. Especially if the migration of the old metric stuff works.

**Comment by Rodeo-McCabe** [comment]
Nice, thanks for working on this so quickly. I've just compiled the latest build and I'll be testing it over the next few days.

**Comment by johannesjo** [comment]
I'll make a new release today with the new feature! Thank you everybody for your help!
