### ISSUE TITLE
Error: TypeError: Cannot read property 'projectId' of null

### ISSUE THREAD

**Issue by tetrahedon7** [johannesjo/super-productivity#521]
Trying to open a certain project shows the following error:
![image](https://user-images.githubusercontent.com/69251025/92552583-a23e1480-f27e-11ea-92d6-131c9d14a9b6.png)

Trying to open the project's settings produces the same result.
I only faced this problem with one project. I had tried out the "Evaluation sheet" for only this project -- might have something to do with that.

Version: 5.6.5
OS: Windows 10

**Comment by johannesjo** [comment]
Hi there! What version of Super Productivity are you using?

**Comment by tetrahedon7** [comment]
> 
> 
> Hi there! What version of Super Productivity are you using?
version 5.6.5.

**Comment by johannesjo** [comment]
I think in this case I might need an export of your data for further debugging. If it is alright with you I would much appreciate it if you could send one to contact@super-productivity.com

**Comment by tetrahedon7** [comment]
i'm sorry, i actually reinstalled the application since i needed to be able to use it, and i am not at leisure at the moment to repeat the same steps to get that error again but i think if you do it you will get the same since it was the only thing different about that one project that gave error.

**Comment by johannesjo** [comment]
Just for your information: Usually, Super Productivity should be able to ramify this by itself when it happens. You just need to restart the app. Another option is using a backup from `~/.config/superProductivity/backups`. Please let me know if the issue occurs again!

I am closing this until then.
