### ISSUE TITLE
[minor feature request] Task time-tracking indication in tray icon

### ISSUE THREAD

**Issue by tetrahedon7** [johannesjo/super-productivity#527]
The global keyboard shortcut to pause/resume task time-tracking is pretty neat. However, its functionality is somewhat reduced by the fact that if someone keeps the app hidden (which again is easier to do due to the keyboard shortcut) there is no way to tell if the time-tracking is going on, other than opening the app. This could be fixed if there was some indication in the tray icon that time is being tracked, perhaps a coloured badge or a change of the icon colour/shape itself.

This is really minor but would be really cool if implemented. 😅 Thanks.

**Comment by johannesjo** [comment]
Thanks for opening this up. I'd like to see this feature as well.

**Comment by DenysYakubets** [comment]
Hi guys, you are doing a really lovely product. Thanks!

+1 @tetrahedon7. Also, maybe something like a simple "floating" window (or icon) on top of all windows with the current status (task name, time, status pause/in progress).

**Comment by aripollak** [comment]
I think this has been fixed with c9a4e8270b758e446fc44b4c87d83f64ef0167e3?

**Comment by johannesjo** [comment]
@aripollak yes you're right. Thank you!
