### ISSUE TITLE
Change setting for first day of week

### ISSUE THREAD

**Issue by jfnklstrm** [johannesjo/super-productivity#528]
When I use the web-app I have found that the first day of the week is set to sunday and that I cannot change that setting. It's a small thing but I forget about it so when I schedule things I tend to schedule them 1 day earlier than I want to because I am so used to monday being the first day of the week (this includes the date picker by the way). If this could be included in the settings I'd be really happy!

**Comment by johannesjo** [comment]
Thanks for opening this up. I'd like to see this feature as well.
