### ISSUE TITLE
"Select a task" dialog won't close with "X" button

### ISSUE THREAD

**Issue by Acsigen** [johannesjo/super-productivity#53]
## Your Environment
Windows 7 64-bit
Linux Mint 18.x 64-bit
Software version tested 1.7.5 and  1.7.4

## Expected Behavior
"Select a task" dialog should close with "X" button
## Current Behavior
"Select a task" dialog can be closed only with "ESC" key or proceed with the task

## Steps to Reproduce (for bugs)
1. Select Plan your day
2. Insert tasks
3. Select All Done! let's go to work
4. Select a task dialog appears
5. I want to close the dialog because I forgot to add a task
6. The dialog will close only with "ESC" key not with the "X" button from GUI

**Comment by johannesjo** [comment]
Thanks for reporting, I'll investigate. Probably just a missing binding.
