### ISSUE TITLE
[Feature Request] Encrypt Json Database export for sync

### ISSUE THREAD

**Issue by CristoJV** [johannesjo/super-productivity#530]
Up to my knowledge, synchronization exports the database to Google Drive or Dropbox. However this export mechanism is a plain json. I would recommend to insert the following form in the Sync & Export Database.

Toogle button "Enable Encryption" [Where the user selects if he wants to use encryption]
Password field "Secret Key" [Where the user insert the key]

Then use AES-256 encryption or Twofish (depending on libraries) to intermediate this process.

Posible error cases:
===================
Different encryption configurations in different devices.
-------------------------------------------------------------
**First device:**

1) The user enables encryption.
2) The user enables Dropbox.
3) The app syncs with Dropbox.

**Second device:**

4) The user disables encryption.
5) The user enables Dropbox. (same auth code)
6) The user founds an Encrypted version of the database

ERROR: (Could not recover data).

7) An error message shows up "This app has found an encrypted version for synchronization. Please enable encryption and insert your secret key"
8) The synchronization could be done

Different encryption configurations in different devices.
-------------------------------------------------------------
**First device:**

1) The user disables encryption.
2) The user enables Dropbox.
3) The app syncs with Dropbox.

**Second device:**

4) The user disables encryption.
5) The user enables Dropbox. (same auth code)
6) The user founds an standard version of the database

WARNING: Database is not encrypted

7) A warning message shows up "A plain version for synchronization is found. Please enable encryption in your other devices to enable synchronization"
8) Sync data
9) Encrypt data
10) Delete plain data (To avoid missmatchings)

**Comment by CristoJV** [comment]
I can work on this feature :smile:

**Comment by johannesjo** [comment]
Thank you for the detailed concept and the offer to work on this. That's really great and I would much appreciate it. If it is not complicating things too much, It would be lovely to have this available as a generic interface afterward, so we can use the same approach for Google Drive and WebDav (when it is finally implemented; see: #159).

I also would implement this as explicit opt-in, as usually, those things tend to cause some unexpected problems in the first round (at least they always do when I implement them ;)).

Please let me know if you need any help. I can also give you a quick introduction to the project via Jitsi if you like.

**Comment by johannesjo** [comment]
@CristoJV the new sync interface is ready. I think should be relatively straightforward to implement this for all sync providers. Are you still interested?

**Comment by Cerdtruir** [comment]
> This issue has not received any updates in 90 days. Please comment, if this still relevant!

Still relevant

**Comment by johannesjo** [comment]
ping @CristoJV

**Comment by Cerdtruir** [comment]
Still relevant

**Comment by johannesjo** [comment]
@CristoJV I suppose you won't work on this any time soon? :)

**Comment by ashutoshsaboo** [comment]
@johannesjo any plans to get this shipped sooner, it'd be very useful to have for sync? Looks like @CristoJV dropped the idea :(

**Comment by apertur** [comment]
Any updates on this? Is it possible to use Cryptomator with SP + Dropbox syncing?

**Comment by gcalfin** [comment]
Would like to see this feature implemented.  I like this app but have concerns about unencrypted personal todo info on public cloud services.

**Comment by ishanarora** [comment]
still relevant

**Comment by gcalfin** [comment]
Still relevant

**Comment by warhar** [comment]
Still relevant

**Comment by johannesjo** [comment]
I was able to add this feature just now. It is probably not super secure since I am using the password itself to create the salt (a big security no go for normal apps), but I am no expert and was not able to come up with a better solution, since everything with super productivity is publicly accessible and a salt would be difficult to hide.

Does someone have any advice how we might improve this? Here is the encryption code:

https://github.com/johannesjo/super-productivity/blob/master/src/app/imex/sync/encryption.ts

**Comment by ashutoshsaboo** [comment]
still relevant

**Comment by johannesjo** [comment]
The feature has been implemented, so I am closing this.
