### ISSUE TITLE
Sound when finishing task ignores enabled-setting, cannot be turned off

### ISSUE THREAD

**Issue by kosi2801** [johannesjo/super-productivity#534]
### Your Environment

* Version used: DEB, 5.7.0  (previous version was 5.5.2 and before that 5.4.3)
* Operating System and version: Linux Mint 20
* Desktop Environment: Cinnamon

### Expected Behavior
If setting "Sound / Play sound when task is marked done" is *not* checked, no sound should be played when a task is marked done

### Current Behavior
Sound is played, no matter the setting

### Steps to Reproduce (for bugs)
1. Turn off Setting in Sound section for "Play sound when task is marked done"
2. Save settings
3. Mark any task done (sound is played)

### Console Output

none

### Error Log (Desktop only)
none

**Comment by johannesjo** [comment]
Oh! This is annoying I suppose :) I  try to fix it ASAP!

**Comment by johannesjo** [comment]
This will be fixed with the next release!
