### ISSUE TITLE
Crash report (IPhone)

### ISSUE THREAD

**Issue by alexriabtsev** [johannesjo/super-productivity#535]
Unable to parse error string. Please see console error
https://app.super-productivity.com/main.bfe26d5f10b58e00fade.js:1:1913913
https://app.super-productivity.com/main.bfe26d5f10b58e00fade.js:1:576153
https://app.super-productivity.com/main.bfe26d5f10b58e00fade.js:1:575562
https://app.super-productivity.com/main.bfe26d5f10b58e00fade.js:1:574432
https://app.super-productivity.com/main.bfe26d5f10b58e00fade.js:1:574127
https://app.super-productivity.com/main.bfe26d5f10b58e00fade.js:1:574432
https://app.super-productivity.com/main.bfe26d5f10b58e00fade.js:1:574127
https://app.super-productivity.com/main.bfe26d5f10b58e00fade.js:1:574432
https://app.super-productivity.com/main.bfe26d5f10b58e00fade.js:1:574127
https://app.super-productivity.com/main.bfe26d5f10b58e00fade.js:1:2563970
https://app.super-productivity.com/main.bfe26d5f10b58e00fade.js:1:574127
https://app.super-productivity.com/main.bfe26d5f10b58e00fade.js:1:574432
https://app.super-productivity.com/main.bfe26d5f10b58e00fade.js:1:574127
https://app.super-productivity.com/main.bfe26d5f10b58e00fade.js:1:574432
https://app.super-productivity.com/main.bfe26d5f10b58e00fade.js:1:574127
https://app.super-productivity.com/main.bfe26d5f10b58e00fade.js:1:717667
https://app.super-productivity.com/main.bfe26d5f10b58e00fade.js:1:574432
https://app.super-productivity.com/main.bfe26d5f10b58e00fade.js:1:2574706
https://app.super-productivity.com/main.bfe26d5f10b58e00fade.js:1:574127
https://app.super-productivity.com/main.bfe26d5f10b58e00fade.js:1:574432
META: SP5.7.0 Browser – en-gb – iPhone – Mozilla/5.0 (iPhone; CPU iPhone OS 14_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Mobile/15E148 Safari/604.1

**Comment by johannesjo** [comment]
Thanks for reporting. I try to look into it.

**Comment by johannesjo** [comment]
Not sure what might be causing this, as there is no usable error message, but I planned to do some improvements for the IPhone in general shortly.

**Comment by alexriabtsev** [comment]
I had a bookmark on my home screen launching super-productivity. Now when I'm trying to open the bookmark (or visit app via Safari) I'm getting this error.
Maybe React Native app would be a solution?

**Comment by johannesjo** [comment]
A native app might be nice, but the project is big and complex enough as is... I also think that it is most useful on the desktop.

Could you maybe try to debug this with a connet using chrome via
chrome://inspect/#devices
?

**Comment by alexriabtsev** [comment]
> A native app might be nice, but the project is big and complex enough as is... I also think that it is most useful on the desktop.
> 
> Could you maybe try to debug this with a connected phone using chrome via
> chrome://inspect/#devices
> ?

sorry, Johannes :(
I have macbook pro and USB port for iPhone to conect.
