### ISSUE TITLE
Can't edit the name of the task

### ISSUE THREAD

**Issue by YangBa78** [johannesjo/super-productivity#536]
### Your Environment

* Version used: 
5.6.5
* Operating System and version:
Windows 10
* Desktop Environment: 
Desktop version
* Browser Name and version: 

### Expected Behavior

when I click the task, I should edit the name of the task. 

### Current Behavior

- After adding a new task, I can't rename the task.
- Can't name any subtasks.  

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by johannesjo** [comment]
Thanks for reporting. Unfortunately, I am unable to reprdoce this issue. Is there any output in the console (you can open it up by pressing Ctrl+Shift+i)?

**Comment by johannesjo** [comment]
@YangBa78 ping

**Comment by YangBa78** [comment]
I don't know, I just can't edit the name for any created task. Before updating to newer version, it works well. But I think update is automatic.

**Comment by YangBa78** [comment]
I pressed Ctrl+Shift+i. This is the screenshot, but I have no idea what's that about. 
![image](https://user-images.githubusercontent.com/65861171/96373206-f8815b80-1138-11eb-9118-1c1d3701af9b.png)

**Comment by johannesjo** [comment]
Are you using this inside your browser (if so, which one), the windows store version, or one of the exe files?

**Comment by YangBa78** [comment]
Oh...I forgot which version is my current use. It's probably windows store version. But I tried both before.

**Comment by johannesjo** [comment]
Hm I can't reproduce this with either version. Could you please try again with the latest version:
https://github.com/johannesjo/super-productivity/releases/download/v6.0.0-rc.4/superProductivity-Setup-6.0.0-rc.4.exe
?

**Comment by YangBa78** [comment]
I unstalled and installed the lastest version. It works. Thanks very much. I appreciate your help.

**Comment by johannesjo** [comment]
I am glad that it does. Please let me know, if you encounter any other problems.
