### ISSUE TITLE
Cannot connect against On-Premise Jira server

### ISSUE THREAD

**Issue by tangel0v** [johannesjo/super-productivity#537]
### Your Environment
- Version Used: snap version
- Operating System and Version: Ubuntu 20.04.
- Desktop Environment: Gnome 3.36.
- Connection throught VPN.

### Expected Behaviour
I am using a on-premise Jira server and I am trying to connect the application against the server. The server has configured a Single Sign On against our own Identity Provider. I should be able to login with my username and password but It didn't.

### Current Behaviour
When I tried to configure the application against my own Jira server I receive an error 500. If I change the user or password to a non valid one I received a 401 Unauthorized.

I have suppose there are some limitations in the way the app connects to Jira when using a federated authentication so I have tried to use "Wonky cookie mode" but I don't know which cookie or cookies I have to paste in the application. Is there more documentation to check on?

### Console Output
Jira Error Error Response ELECTRON:  Response {
  size: 0,
  timeout: 0,
  [Symbol(Body internals)]: {
    body: PassThrough {
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: true,
      allowHalfOpen: true,
      _transformState: [Object]
    },
    disturbed: false,
    error: null
  },
  [Symbol(Response internals)]: {
    url: 'https://jira.xxxxxx.xxxx/rest/api/latest/myself',
    status: 500,
    statusText: 'Internal Server Error',
    headers: Headers { [Symbol(map)]: [Object: null prototype] },
    counter: 0
  }
}
{"size":0,"timeout":0}

**Comment by johannesjo** [comment]
Thanks for opening this up. I'd recommend trying to access the Jira Rest API via PostWoman or curl, to find out if this is related to Super Productivity or not:
https://developer.atlassian.com/server/jira/platform/jira-rest-api-examples/

**Comment by tangel0v** [comment]
I have tested it and it seems that there is some trouble in the configuration on Jira Server. Otherwise, is there more information about how to use the Wonky cookie mode?

Thank you very much! With or without integration your tool is great to keep focus and organized.

**Comment by johannesjo** [comment]
What info are you missing?

![Screenshot from 2020-09-23 12-45-07](https://user-images.githubusercontent.com/1456265/94002814-b3b50f80-fd9a-11ea-89b5-29a995f47df2.png)

**Comment by tangel0v** [comment]
I cannot get any cookie like that in my server. It doesn't matter I won't want to bother you.

Thank you very much

**Comment by johannesjo** [comment]
This is weird. Are you using an older version of Jira? If you want to dig deeper into this, I'd recommend digging into how Jira handles the rest stuff for its own frontend. I don't know about older versions, but more recent ones tend to use the rest apis and there has to be some sort of authentication.

**Comment by tangel0v** [comment]
I am able to login getting the cookie in raw in another browser :P Thank you so much Johan.

**Comment by johannesjo** [comment]
I am glad to hear it! :) I am closing this then. Please let me know, if you encounter any other issues.
