### ISSUE TITLE
[Feature Request]Directory support for Cloud Storage

### ISSUE THREAD

**Issue by d4n3sh** [johannesjo/super-productivity#539]
Thank you for this awesome app :)

Environment:
* Version used:5.4.2
* Operating System and version: ArchLinux
* Desktop Environment: KDE Plasma
* Browser Name and version: Google Chrome Beta 86.0.4240.42

By default, the sync option will sync to the root directory of the selected cloud storage provider. I have a directory named "appdata" which I use to sync application data. I would like to sync the json file for SP into that directory. 

I tried specifying the path in the "Sync file name" field to "Appdata/SUPER_PRODUCTIVITY_SYNC.json" but that just created a file named "Appdata/SUPER_PRODUCTIVITY_SYNC.json" :)

Would be nice if it could translate the / into a directory. "GoogleDrive/Appdata/SUPER_PRODUCTIVITY_SYNC.json"

### Expected Behavior
Sync to Google Drive into a subdirectory. e.g. Path=Appdata/SUPER_PRODUCTIVITY_SYNC.json

### Current Behavior
Sync to the root directory of Google Drive e.g. Filename=Appdata/SUPER_PRODUCTIVITY_SYNC.json

**Comment by johannesjo** [comment]
Hey there! Thanks for opening this up. If somebody wants to take tackle this, I am all for it.
