### ISSUE TITLE
[Feature] Global Links, drag and drop

### ISSUE THREAD

**Issue by Revulse** [johannesjo/super-productivity#54]
I find the Global Links to be very useful. I was wondering if it would be possible to be able to move the links around by clicking and holding and moving to rearrange them. Also, is it possible to be able to create groups or drop down menus for some of the links?

**Comment by johannesjo** [comment]
Hey there! Thanks for your suggestions. I like them a lot. I might start working on then once I got more time on my hands, which could unfortunately take a little time. Meanwhile pull requests are very welcome!

**Comment by Revulse** [comment]
Alright, sounds good. If I think of anymore features from a user standpoint, I'll let you know.

And I understand that your busy lol. All is fine.

**Comment by johannesjo** [comment]
The feature will be finally there with the next release.

**Comment by Revulse** [comment]
> The feature will be finally there with the next release.

Awesome! Thank you.
