### ISSUE TITLE
Nextcloud integration

### ISSUE THREAD

**Issue by servingworlds** [johannesjo/super-productivity#540]
After listening to your interview on the Destination Linux podcast, I wanted to reach out and thank creator Johannes and the Super Productivity developer community for such a wonderful app!

https://m.youtube.com/watch?feature=youtu.be&v=aGqJEfGQznc

I would also love to chip in a dollar or two a month via Patreon or PayPal to support development.

My feature request is: please bundle the app and multi-user support into an Nextcloud 'app' package.

I would love to wean those I support off paid Todo services that are inferior to Super Productivity but need to reduce to entry cost. 

Element support has increased as a communications method now it is inside Nextcloud for the same reason and I strongly suggest you consider the same approach.

I, for one, will pay to support Super Productivity, and pay more for Nextcloud integration.

Thank you all for your work.

### Your Environment

* Version used: 
* Operating System and version:
* Desktop Environment: 
* Browser Name and version: 

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by aaylnx** [comment]
Nextcloud integration would be fantastic!

**Comment by espenbo** [comment]
Nextcloud integration would be fantastic!. And support on pinebook pro (arm) with Manjaro

**Comment by johannesjo** [comment]
Hey there everybody! Thanks for opening this up @servingworlds. I never used nextcloud myself, so I wonder if simple WebDav support is sufficient or if we would need to include some integration for nextcloud specifically.

**Comment by servingworlds** [comment]
I wish I could be of help integrating with Nextcloud. It's a big ask but I think it could drive adoption. I know you can integrate caldav and webdave with Nextcloud and do it myself through a foxx app (DavX5) but I'm guessing you'd need an official app hich may be more work than you have time/interest in (once again: if you set up a Patreon I'll chip in a buck or two a month to help!).

Nextcloud Developer Manual https://docs.nextcloud.com/server/19/developer_manual/
App Development index https://docs.nextcloud.com/server/19/developer_manual/app/index.html

**Comment by gotmax23** [comment]
Multi-user support and an app built into Nextcloud would be nice, but I think simple WebDAV sync would be sufficient. I don't use Google Drive or Dropbox, so this would be very helpful. Thanks!

**Comment by gotmax23** [comment]
Also there's an existing Nextcloud App that allows embedding any webpage. Anyone could embed the existing Super Productivity webapp into Nextcloud that way.

**Comment by johannesjo** [comment]
Just a quick update: I started working on this. Will take some time though...

Btw. if you want to donate a little something (much appreciated!) the ideal way to do so is GitHub sponsors. They will even match your contribution with the same amount making your contribution effectively worth twice as much:
https://github.com/sponsors/johannesjo

**Comment by aaylnx** [comment]
Wonderful. Signed up as a sponsor just a few minutes ago. Thanks.

**Comment by codeling** [comment]
@johannesjo thanks for your great work; I guess development on this takes place in the "feat/webdav" branch?
If it is in a shape were you would need somebody to test it, or maybe an account on a nextcloud server, I might be able to help!

**Comment by johannesjo** [comment]
Hey @codeling. Much appreciated! Currently, there is nothing to test as I am still busy with the groundwork, as I want to unify syncing behavior to make implementing a new provider easier. I'll get in touch once I am done.

**Comment by johannesjo** [comment]
I am closing this in favor of #159.

**Comment by johannesjo** [comment]
@codeling the feature is ready to test on this branch. Do you need any help to set up the project?
