### ISSUE TITLE
Cannot export to mounted USB on Ubuntu

### ISSUE THREAD

**Issue by sdruskat** [johannesjo/super-productivity#543]
Similar use case as #192, trying to save data to a USB stick for portability. 

### Your Environment

* Version used: 5.9.0 (snap version)
* Operating System and version: Ubuntu 20.04
* Desktop Environment: Gnome
* Browser Name and version: n/a

### Expected Behavior

It should be possible under Ubuntu to export data directly to a USB drive.

### Current Behavior

Trying to do *Settings* > *Import/Export* > 
*Export data*, then selecting the USB drive in question (which I can access from Nautilus and the command line), I get an error message "Error opening directory '/media/<user>/<drive-name>': Permission denied".

### Steps to Reproduce (for bugs)

1. Mount a USB drive on Ubuntu
2. Try to export

### Console Output

No.

### Error Log (Desktop only)

Log doesn't exist at `~/snap/superproductivity/current/.config/superProductivity/log.log`, there's one in `~/snap/superproductivity/current/.config/superProductivity/logs/main.log`, which is empty.

**Comment by sdruskat** [comment]
I have the feeling this could be to do with snaps being mounted, and perhaps not having rights beyond the snap runtime?

**Comment by sdruskat** [comment]
Can confirm that this isn't a problem with the .deb installed version, where the default backup is in `~/.config` rather than nested deep in `~/snap/.../current/...`.

**Comment by sdruskat** [comment]
In addition, when starting with `--user-data-dir=/media/<user>/<usb-name>/<arbitrary-directory>`, the directory is created, but `superproductivity doesn't start:

```bash
user@computer:~$ superproductivity --user-data-dir=/media/user/KINGSTON/bkup
Saving backups to /media/user/KINGSTON/bkup
Using custom directory for user data /media/user/KINGSTON/bkup
{ enabled: null, showDevTools: false, mode: 'bottom' }
user@computer:~$
```

**Comment by johannesjo** [comment]
Thanks for reporting! I'll try to have a look this Friday.

**Comment by sdruskat** [comment]
Thanks!

**Comment by johannesjo** [comment]
This is pretty much this issue here:
https://askubuntu.com/questions/1034030/how-to-get-access-to-usb-storage-from-an-application-installed-as-snap
See also:
https://github.com/electron-userland/electron-builder/issues/4150
https://github.com/electron-userland/electron-builder/issues/4252

I am a bit unsure if I should attempt to add the `removeable-media` support, as the only use case would be to export data there from the settings and I had problems with this in the past, leading to the snap not working at all.

I don't know... What do you think?

**Comment by sdruskat** [comment]
Sorry for the delay. I'm not sure either.

I think the use case is a valid one though: exchanging data between machines with different platforms, in cases where Google Drive/Dropbox aren't an option.

One other thing that may work for this use case would be background git pushing perhaps. I imagine it like this:

### Setup

User sets up git repo for backups, with token authentication (would need to check what the minimal rights would have to be for a repo).

### Flow

1. SP starts up:
  1. Check remote for updates
  2. Pull if necessary
  3. Sync UI
2. On each change set, do commit and push

There is opportunity for this to go wrong, e.g., with different CRLF across systems, etc., but I think it could be done if considered system-side rather than user-side.

Would take some thinking about the changesets you'd want to commit (e.g., time-based on some idle threshold, or content-based once a (atomic on some level) change has been completed (focus-loss on current element or something)).

What do you think?

**Comment by johannesjo** [comment]
Thanks for getting back to me. Not sure if I understand this correctly. Are you suggesting background git sync as another feature or is it an example of why we might want to add `removable-media` support?

**Comment by sdruskat** [comment]
The former, i.e., git sync as a new feature. Should I open a new issue for this?

**Comment by johannesjo** [comment]
> Should I open a new issue for this?

Generally yes, please. This makes it easier to keep the discussion focused on one topic at a time.

**Comment by sdruskat** [comment]
Of course, I agree. Feel free to close and I'll open a new one.

**Comment by ZenKyma** [comment]
I would still need the `removable-media` support for local file syncing.

Trying to make the android app sync via _Local File_+Nextcloud App together with the desktop app via _WebDAV_ formats the json files differently so they don't get recognized by the respective other. So I was about to switch over to _Local File_ Sync for Ubuntu as well, but snap can't write to the partition where my Nextcloud folder lies.

Would providing a flatpak package be another viable option maybe?

**Comment by ZenKyma** [comment]
I circumvented the problem by installing the app through the Play Store where the WebDAV upload works, so I am happy with my setup now.

But I guess it would be nice if _WebDAV_ and _Local File_ share the same formatting so they can be mutually synced. Should I open a new issue for that?

**Comment by johannesjo** [comment]
> But I guess it would be nice if _WebDAV_ and _Local File_ share the same formatting so they can be mutually synced. Should I open a new issue for that?

Yes please! I am a bit surprised that they differ to be honest. They both get passed the same data. Could you maybe elaborate on what the actual differences are?
