### ISSUE TITLE
App Crash on dismiss note

### ISSUE THREAD

**Issue by fernandochiquito** [johannesjo/super-productivity#544]
**ERROR:**

Error: Uncaught (in promise): TypeError: Cannot read property 'isDataImport' of undefinedTypeError: Cannot read property 'isDataImport' of undefined    at Object.save (file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:1806034)    at t. (file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:1426074)    at file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:1424395    at Object.next (file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:1424500)    at a (file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:1423238)    at t.invoke (file:///snap/superproductivity/755/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9307)    at Object.onInvoke (file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:476668)    at t.invoke (file:///snap/superproductivity/755/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9247)    at e.run (file:///snap/superproductivity/755/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:4407)    at file:///snap/superproductivity/755/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:16325

### **Steps to Reproduce**
1. Create more than one note with a reminder for some time in the future
2. Try to dismiss the note when the alert come out.
3. Some crash happen with the following code

### **Copy of the output**

Reunião inicial de trabalho
Tarefas concluídas
Transferir tarefas para o Super Productivity
alarmObservação
From Project

Grasso Grafica
Iniciar Primeiro relatório para entrega
Error: Uncaught (in promise): TypeError: Cannot read property 'isDataImport' of undefined TypeError: Cannot read property 'isDataImport' of undefined at Object.save (file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:1806034) at t. (file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:1426074) at file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:1424395 at Object.next (file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:1424500) at a (file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:1423238) at t.invoke (file:///snap/superproductivity/755/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9307) at Object.onInvoke (file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:476668) at t.invoke (file:///snap/superproductivity/755/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9247) at e.run (file:///snap/superproductivity/755/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:4407) at file:///snap/superproductivity/755/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:16325
! Please copy & report !

Error: Uncaught (in promise): TypeError: Cannot read property 'isDataImport' of undefined TypeError: Cannot read property 'isDataImport' of undefined at Object.save (file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:1806034) at t. (file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:1426074) at file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:1424395 at Object.next (file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:1424500) at a (file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:1423238) at t.invoke (file:///snap/superproductivity/755/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9307) at Object.onInvoke (file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:476668) at t.invoke (file:///snap/superproductivity/755/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9247) at e.run (file:///snap/superproductivity/755/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:4407) at file:///snap/superproductivity/755/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:16325
save (webpack:///src/app/core/persistence/persistence.service.ts:449:44)
this._persistenceService.note.load (webpack:///src/app/features/note/note.service.ts:89:47)
Ur (file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:1424395)
Ur (file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:1424500)
Ur (file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:1423238)
invoke (webpack:///node_modules/zone.js/dist/zone.js:386:29)
onInvoke (webpack:///node_modules/@angular/core/fesm5/core.js:28134:32)
invoke (webpack:///node_modules/zone.js/dist/zone.js:385:35)
run (webpack:///node_modules/zone.js/dist/zone.js:143:46)
zone.scheduleMicroTask (webpack:///node_modules/zone.js/dist/zone.js:891:37)
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone.js:832:38)
value.hasOwnProperty (webpack:///node_modules/zone.js/dist/zone.js:784:20)
zone.scheduleMicroTask (webpack:///node_modules/zone.js/dist/zone.js:894:20)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:421:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm5/core.js:28122:32)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:420:39)
task._transitionTo (webpack:///node_modules/zone.js/dist/zone.js:188:50)
drainMicroTaskQueue (webpack:///node_modules/zone.js/dist/zone.js:601:38)
META: SP5.6.5 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.6.5 Chrome/83.0.4103.122 Electron/9.1.1 Safari/537.36
Reload App

**Comment by fernandochiquito** [comment]
### **My Environment**
Version used: _5.6.5_ (from snap)
Operating System and version: *Fedora 32 (WorkStation Edition)* 
Desktop Environment: *Gnome 3.36.6*
Windowing System: *Wayland*

**Comment by johannesjo** [comment]
Thanks for reporting. This should be fixed with the latest release 5.9.0. Please let me know if not!
