### ISSUE TITLE
Search Feature?

### ISSUE THREAD

**Issue by aaylnx** [johannesjo/super-productivity#547]
I'm new to SP. I'm sorry if this is the wrong place to ask a question like this, but is there an ability to search within SP? If so, I am unable to locate it.  Thanks!

**Comment by johannesjo** [comment]
Thanks for opening this up. No, currently there is no such thing. Interestingly (to me at least ;)) I very rarely need this, but it probably makes sense to do this in one form or another.

**Comment by aaylnx** [comment]
Sure. I understand it's somewhat use case dependent. It's just a feature I'm used to from other task managers I've used. I'm sure you have a long list of feature requests, but if this one makes it on the list somehow, I'm betting it will prove useful for a number of users. In any event, thanks for all your work!

**Comment by tustinn** [comment]
+1 :-)

**Comment by privacy-advo** [comment]
First **Thank you !** for the amazing app.

I strongly support this request.

**Comment by IT-Tool** [comment]
+1

**Comment by IT-Tool** [comment]
+1

- It is easier to find the required task through search if there are many projects and tasks.
- It is also more convenient to find similar tasks through the search between all projects (if needed).
- And so on

**Comment by guitarzero** [comment]
Me too. I would love a "search all tasks" features. Even better, in the same way as Notational Velocity does, that is to say you start typing in a search box, and all tasks are being filtered out in real-time.

**Comment by aaylnx** [comment]
> Me too. I would love a "search all tasks" features. Even better, in the same way as Notational Velocity does, that is to say you start typing in a search box, and all tasks are being filtered out in real-time.

Indeed, that would be nice.

Definitely hoping that some search feature makes it in in the future.

**Comment by Rielyr** [comment]
Hello and thank you for your awesome work, i just found out about this app and looks very promising. I would definitely agree that a search bar and other filtering capabillities are a must for any medium to large project. Right now i'm just testing to see if i can make this my default productivity app, but i wouldn't migrate my hole backlog without this feature.

**Comment by aaylnx** [comment]
Since I made this request, it appears that tasks do show up if you start typing in the new task window, but only if those tasks have been put in a project. As a consequence, I tend to have tasks placed in projects now.

**Comment by privacy-advo** [comment]
> Since that time, it now appears that tasks do show up if you start typing in the new task window, but only if those tasks have been put in a project. 

Could you please explain in which section/window you are and which behaviour leads to a search. Thanks in advance

Already existing behaviour I'm aware of:
If you're in "Today" and "Add a new task", once you type you will be presented with auto completetion of the existing entries **limited to** entries in "Today". 
This does not apply to "Add new task" within projects.

I will try to describe the desired _real_ search feature:

**Comment by privacy-advo** [comment]
**Search:**
Ability to search for tasks (maybe also sub-tasks and notes) from a search field within all entries across all projects.

**Comment by johannesjo** [comment]
I suspect that we all agree that search should be improved beyond what is already provided. I think @aaylnx was just pointing out that there is something available that might help you a bit right now.

I will work on this as soon as I get the calendar update rolling, which definitely will take some time. I still don't have a clear defined concept on how to do it, so suggestions on this are welcome!

**Comment by privacy-advo** [comment]
Thank you for the fast response and supplying hope. ;)

Do you want technical input or ideas about the interface/functionality?

**Comment by johannesjo** [comment]
I thought mainly about interface/ functionality, but technical input is welcome as well!

**Comment by aaylnx** [comment]
> I suspect that we all agree that search should be improved beyond what is already provided. I think @aaylnx was just pointing out that there is something available that might help you a bit right now.
> 
> I will work on this as soon as I get the calendar update rolling, which definitely will take some time. I still don't have a clear defined concept on how to do it, so suggestions on this are welcome!

I'm very glad to hear that further work on this is planned.  Thanks so very much!

**Comment by yanjost** [comment]
An simple idea for a first implementation : make it a "jump to task" feature that does a fuzzy search like the one when adding time spent on a task

**Comment by donangel** [comment]
+1 for the feature! 
I imagine "Incremental Search" functionality as follows:

1. The user presses the "Incremental Search" shortcut. For example Cmd+I 
2. A popup appears, similar to what we have when we need to assign time to a task.
3. We start typing. The result is automatically filtered, matching all tasks, which contain the search term
4. The first match is focused by default. Arrow Down / Up moves the focus up/down. Pressing Enter closes the search box and jumps to the task, which was selected.

**Comment by johannesjo** [comment]
Thanks to @stkofler  we now good this :)

https://github.com/johannesjo/super-productivity/releases/tag/v7.1.0

**Comment by aaylnx** [comment]
> Thanks to @stkofler we now good this :)
> 
> https://github.com/johannesjo/super-productivity/releases/tag/v7.1.0

Well, as the one who first requested this feature, I'm thrilled.

However, I've tried it on three different device and I get the following error whenever I click on the magnifying glass.


> TypeError: Cannot read property 'icon' of undefined
> ! Please copy & report !
> 
> TypeError: Cannot read property 'icon' of undefined
> icon (webpack:///src/app/features/search-bar/search-bar.component.ts:117:29)
> _getContextIcon (webpack:///src/app/features/search-bar/search-bar.component.ts:104:18)
> constructor (webpack:///src/app/features/search-bar/search-bar.component.ts:93:17)
> _mapTasksToSearchItems (webpack:///src/app/features/search-bar/search-bar.component.ts:72:42)
> _next (webpack:///node_modules/rxjs/_esm2015/internal/operators/map.js:29:34)
> next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)
> _next (webpack:///node_modules/rxjs/_esm2015/internal/operators/withLatestFrom.js:57:33)
> next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)
> notifyNext (webpack:///node_modules/rxjs/_esm2015/internal/operators/switchMap.js:66:25)
> META: SP7.1.0 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.1.0 Chrome/89.0.4389.128 Electron/12.0.7 Safari/537.36


Anyone else having this problem?

**Comment by stkofler** [comment]
Thanks for trying this out and reporting this problem. 
To my understanding the issue starts here: 
`const context = task.projectId`
`    ? (projects.find((project) => project.id === task.projectId) as Project)`
`    : (tags.find((tag) => tag.id === task.tagIds[0]) as Tag);`

The error happens a couple of lines later where context.icon is called but context is undefined.

A quick fix would be to just check whether context is defined.

However there might be some inconsistencies in the dataset itself. Possible inconsistencies:
1. The task has a projectId but it cannot be found amongst the project list
2. The task does not have a projectId but neither a tag.
Afaik a task should always have either a project or at least one tag.

What do you think @johannesjo?

**Comment by johannesjo** [comment]
@stkofler yes, this looks like inconsistent data. @aaylnx  could you maybe send a data export to contact@super-productivity.com

**Comment by johannesjo** [comment]
@aaylnx Your issue seems to be reported here: #1325. I am closing this as the search feature now is implemented. Feedback in the form of improvement suggestions are of course welcome!
