### ISSUE TITLE
attachment image thumbnail preview does not display, shows title instead

### ISSUE THREAD

**Issue by tustinn** [johannesjo/super-productivity#549]
### Your Environment

* Version used: 
* Operating System and version:
* Desktop Environment: 
* Browser Name and version: 

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by tustinn** [comment]
thank you very much for this nice software!

**Comment by johannesjo** [comment]
Hey there! Thanks for opening this up. Could you please provide a little bit more info (what version did you use, what system are you on, what did you do exactly, etc.)?

**Comment by tustinn** [comment]
Windows 10
SP: 
![image](https://user-images.githubusercontent.com/23008966/94714022-638cfe80-0300-11eb-812f-0f105ee07726.png)


added attachment, shows title:

![image](https://user-images.githubusercontent.com/23008966/94713511-bca86280-02ff-11eb-9dd3-d11fe71fd906.png)

![image](https://user-images.githubusercontent.com/23008966/94713542-c7fb8e00-02ff-11eb-9ad3-2f2ce38f965d.png)


thank you.

**Comment by johannesjo** [comment]
Thanks! I try to check this, this Friday.

**Comment by johannesjo** [comment]
Fixed as discussed here:
https://github.com/electron/electron/issues/23757

**Comment by tustinn** [comment]
it worked, thanks!! :-)
