### ISSUE TITLE
Error: Uncaught (in promise): TypeError: Cannot read property 'task' of undefined

### ISSUE THREAD

**Issue by ahmedatefdev** [johannesjo/super-productivity#552]
### Steps to Reproduce

1.
2.
3.
4.

### Console Output

Error: Uncaught (in promise): TypeError: Cannot read property 'task' of undefined TypeError: Cannot read property 'task' of undefined at file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_5.9.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.a4e6246750af9eed78ce.js:1:37334 at Array.forEach () at file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_5.9.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.a4e6246750af9eed78ce.js:1:37246 at t.repairData (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_5.9.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.a4e6246750af9eed78ce.js:1:37344) at t. (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_5.9.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.a4e6246750af9eed78ce.js:1:3623607) at file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_5.9.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.a4e6246750af9eed78ce.js:1:3621614 at Object.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_5.9.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.a4e6246750af9eed78ce.js:1:3621719) at file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_5.9.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.a4e6246750af9eed78ce.js:1:3620654 at new t (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_5.9.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:16548) at yM (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_5.9.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.a4e6246750af9eed78ce.js:1:3620399)
key (webpack:///src/app/core/data-repair/data-repair.util.ts:21:48)
forEach (webpack:///src/app/core/data-repair/data-repair.util.ts:20:20)
dataIn (webpack:///src/app/core/data-repair/data-repair.service.ts:18:22)
this._dataRepairService.isRepairConfirmed (webpack:///src/app/imex/sync/data-import.service.ts:73:48)
Ur (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_5.9.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.a4e6246750af9eed78ce.js:1:3621614)
Ur (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_5.9.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.a4e6246750af9eed78ce.js:1:3621719)
Ur (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_5.9.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.a4e6246750af9eed78ce.js:1:3620654)
ZoneAwarePromise (webpack:///node_modules/zone.js/dist/zone.js:913:32)
Ur (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_5.9.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.a4e6246750af9eed78ce.js:1:3620399)
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone.js:832:38)
function (webpack:///node_modules/zone.js/dist/zone.js:739:20)
Ur (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_5.9.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.a4e6246750af9eed78ce.js:1:3620521)
invoke (webpack:///node_modules/zone.js/dist/zone.js:386:29)
onInvoke (webpack:///node_modules/@angular/core/fesm5/core.js:28134:32)
invoke (webpack:///node_modules/zone.js/dist/zone.js:385:35)
run (webpack:///node_modules/zone.js/dist/zone.js:143:46)
zone.scheduleMicroTask (webpack:///node_modules/zone.js/dist/zone.js:891:37)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:421:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm5/core.js:28122:32)
META: SP5.9.0 Electron – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.9.0 Chrome/85.0.4183.98 Electron/10.1.2 Safari/537.36
### Stacktrace
```
key (webpack:///src/app/core/data-repair/data-repair.util.ts:21:48)
forEach (webpack:///src/app/core/data-repair/data-repair.util.ts:20:20)
dataIn (webpack:///src/app/core/data-repair/data-repair.service.ts:18:22)
this._dataRepairService.isRepairConfirmed (webpack:///src/app/imex/sync/data-import.service.ts:73:48)
Ur (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_5.9.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.a4e6246750af9eed78ce.js:1:3621614)
Ur (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_5.9.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.a4e6246750af9eed78ce.js:1:3621719)
Ur (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_5.9.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.a4e6246750af9eed78ce.js:1:3620654)
ZoneAwarePromise (webpack:///node_modules/zone.js/dist/zone.js:913:32)
Ur (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_5.9.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.a4e6246750af9eed78ce.js:1:3620399)
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone.js:832:38)
function (webpack:///node_modules/zone.js/dist/zone.js:739:20)
Ur (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_5.9.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.a4e6246750af9eed78ce.js:1:3620521)
invoke (webpack:///node_modules/zone.js/dist/zone.js:386:29)
onInvoke (webpack:///node_modules/@angular/core/fesm5/core.js:28134:32)
invoke (webpack:///node_modules/zone.js/dist/zone.js:385:35)
run (webpack:///node_modules/zone.js/dist/zone.js:143:46)
zone.scheduleMicroTask (webpack:///node_modules/zone.js/dist/zone.js:891:37)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:421:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm5/core.js:28122:32)
```

### Meta Info
META: SP5.9.0 Electron – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.9.0 Chrome/85.0.4183.98 Electron/10.1.2 Safari/537.36

### Actions Before Error
```
1601411547092: [Task] Add time spent 
1601411547092: [Project] Update Work End 
1601411547092: [Tag] Update Work End for Tag 
1601411547107: [SimpleCounter] Increase SimpleCounter Counter Today 
1601411547352: [Task] Toggle start 
1601411547353: [Task] UnsetCurrentTask 
1601411547353: [Pomodoro] Pause Pomodoro 
1601411548017: [SimpleCounter] Toggle SimpleCounter Counter 
1601411552659: [Task] Update Task 
1601411558943: [Task] SetSelectedTask 
1601411561979: [Task] Move to archive 
1601411561984: [Task] UnsetCurrentTask 
1601411561984: [Pomodoro] Pause Pomodoro 
1601411562914: [GoogleDriveSync] Save For Sync 
1601411562914: [GoogleDriveSync] Save To Flow 
1601411563140: [GoogleDriveSync] Save To 
1601411564747: [GoogleDriveSync] Save To Success 
1601446141339: [SP_ALL] Load(import) all data 
1601446141411: [SP_ALL] All Data was loaded 
1601446141421: [WorkContext] Set Active Work Context 
1601446141458: [Task] SetSelectedTask 
1601446437851: [SP_ALL] Load(import) all data 
1601446437886: [SP_ALL] All Data was loaded 
1601446437894: [WorkContext] Set Active Work Context 
1601446437910: [Task] SetSelectedTask 
1601446806294: [Persistence] Remove from DB
```

**Comment by johannesjo** [comment]
Thank you very much for reporting. I look into it!

**Comment by johannesjo** [comment]
I improved the handling of this to make it more transparent to the user, but to me, it seems like, that the data you're trying to import (are syncing via GoogleDrive or Dropbox) is invalid. Some additional info would be very welcome. What happened before the error occured and How does the data look like you're trying to import on Google Drive (sending a copy of it to contact@super-productivity.com would be super helpful)?

**Comment by johannesjo** [comment]
@ahmedatefdev ping

**Comment by ahmedatefdev** [comment]
Sorry, I didn't see your comment until now
This happens when I update the app and it is open at the same time, It crashes and gives me this record but that hasn't happened again yet
Hope this clears it up for you
good luck

**Comment by johannesjo** [comment]
@ahmedatefdev thank you! I am closing this then. Please let me know if you encounter this or any other issue.
