### ISSUE TITLE
How to enable a dark tray icon

### ISSUE THREAD

**Issue by tuxflo** [johannesjo/super-productivity#554]
### Your Environment
* Version used: v5.9.0 appimage version
* Operating System and version: manjaro
* Desktop Environment: KDE plasma
* Browser Name and version: using the desktop version

### Expected Behavior
If I'm running a bright DE theme (default KDE Breeze) I expect to see a dark icon in the tray.

### Current Behavior
Tray icon is always white (I tried to change the color in the src code and rebuild the appimage but it didn't make a difference).
![image](https://user-images.githubusercontent.com/2816893/94677917-f8eabb80-031d-11eb-9a6d-2383b4e2a453.png)

### Steps to Reproduce (for bugs)
1. Just start the application :)

### Console Output
```
app-builds/superProductivity-5.9.0.AppImage
Saving backups to /home/fhennig/.config/superProductivity/backups
{ enabled: null, showDevTools: false, mode: 'bottom' }
```

**Comment by johannesjo** [comment]
Thanks for opening this up! This should be a good issue to solve for someone being new to the project.
