### ISSUE TITLE
Always on top

### ISSUE THREAD

**Issue by johannesjo** [johannesjo/super-productivity#556]
By Valentin:

Please implement an option for the timer to always be on top similar to YAPA-2 , see screenshot attached.

Also a way of choosing transparency would also be good, the idea is that it should always be on top of other things but still allow to see through the text of the app, I keep it in the bottom right corner and sometimes there are things that need to be clicked in that corner, so at least I can see there is some information behind.

I found a work around by scaling down the window and using Turbotop app to have it show over all other windows that I have open, but I have to go through several steps every time I reboot my computer. 

Bonus: Some options to scale the text would be good as I don’t have a high resolution screen on my laptop.

![8C3E3F9258BE4AD1958F489E84508DD2](https://user-images.githubusercontent.com/1456265/96619439-7d6da000-1306-11eb-85fe-501c72e0bc0d.png)

**Comment by himanshu2408** [comment]
Hi @johannesjo I don't see any screenshot, can you please check?

**Comment by johannesjo** [comment]
@himanshu2408 thanks for pointing that it out. I attached it.
