### ISSUE TITLE
Enabling idle time handling in the options

### ISSUE THREAD

**Issue by baram204** [johannesjo/super-productivity#56]
## Your Environment

* Version used:  windows 1.7.9
* Operating System and version: windows 10
* Desktop Environment: windows
* Browser Name and version: none

## Expected Behavior

When I start task and then go outside & return 1hr, I want to see task spend time 1hr.

whatever windows sleep or shutdown happend, spend time should calculated until I click stop button.

## Current Behavior

If shutdown computer, spend hour calculation also shutdown.

## Steps to Reproduce (for bugs)

1. start task
2. shutdown or sleep computer during 30 min
3. wake up it
4. then you'll see 30 min gone

**Comment by johannesjo** [comment]
Thanks for reporting! I'll look into to it this Friday. In the meantime enabling idle time handling in the options will probably help.
