### ISSUE TITLE
Wrong formating jira description

### ISSUE THREAD

**Issue by JustAPhrog** [johannesjo/super-productivity#561]
### Your Environment

* Version used: 5.9.0
* Operating System and version: win10 2004
* Desktop Environment: 
* Browser Name and version: 

### Expected Behavior

 '+' is not begin for underline. See jira description:
![image](https://user-images.githubusercontent.com/36739202/95049622-65810400-06ea-11eb-9433-fc65d766b293.png)

### Current Behavior

Description from Jira task is wrong formated (underline).
![image](https://user-images.githubusercontent.com/36739202/95049571-4c785300-06ea-11eb-9ed0-20ef8ff72741.png)

This is raw jira text:
```
Jako użytkownik Offer definiujący rabaty koncesyjne, po wgraniu pliku chciałbym, aby aplikacja:
 # Wyświetliła w tabeli z artykułami również:
 a) Nazwę art + wariant 
 b) liczbę szt w MU (gebi)
 c) cenę z maski głównej
 # Wyświetliła wszystkie numery Subsysy z poziomu artykułu MGB+var Subsysu z pliku (zgrupowane po MGB+var) i *sprawdziła czy w pliku był tylko jeden subsys z MGB+var* (wyświetlenie błędu: Cena podana na innym bundle'u)
 # Przeliczyła cenę z podanego Subsy na pozostałe subsysy z poziomu MGB+var zgodnie z Gebi.
 # Sprawdziła, czy wgrana plikiem lub przeliczona cena różni się więcej niż 10% od ceny z maski głównej i w takim przypadku wyświetliła cenę na czerwono (+sortowanie tych cen na górze)
 # Sprawdziła, czy cena koncesyjna (wgrana lub przeliczona) nie jest >= od ceny z maski głównej i wyświetla błąd: "Cena koncesyjna wyższa niż standardowa".
```

### Steps to Reproduce (for bugs)

1. Add task from jira

**Comment by johannesjo** [comment]
Thanks for reporting!

**Comment by rohanrk** [comment]
Hi! I'd love to work on this. Quick question. I cannot figure out how to make my JIRA integration work. I've tried links to the project, API links to get the project resource, etc. Which host link am I supposed to be using? Sorry for the confusion.

**Comment by johannesjo** [comment]
Hey @rohanrk. This depends on your Jira installation, so this might be different for every instance. Personally, I encountered two different paths that work:

https://my-instance.atlassian.net/
https://some-jira-url.com/jira

but mostly the base URL should be enough. What kind of paths did you try? What errors did you encounter for them?

**Comment by rohanrk** [comment]
Odd. I tried both urls and neither worked. They both cause a timeout. Looked into the source code and debugged and it looks like the networking objects are properly initialized. I'm supposed to put one of the urls, my email, and then the API key for the password correct?

**Comment by johannesjo** [comment]
> I'm supposed to put one of the urls, my email, and then the API key for the password correct?

Exactly!

Is there any console output? And what's the response to the requests (you might need to dig into electron/jira.ts for this)?

**Comment by rohanrk** [comment]
I don't think a response is generated because the api request times out.

**Comment by johannesjo** [comment]
@rohanrk yes this would be good. Maybe you can also check by using a test account from Atlassian: https://www.atlassian.com/de/software/jira/free ?
