### ISSUE TITLE
Crash when starting

### ISSUE THREAD

**Issue by dmp1ce** [johannesjo/super-productivity#563]
### Your Environment

* Snap version: `superproductivity        5.9.2                        803   latest/stable  johannesjo  -`
* Operating System and version: Arch Liux
* Desktop Environment: Gnome

### Expected Behavior
Application starts up.

### Current Behavior
Application crashes with a core dump.

```
$ superproductivity 
Saving backups to /home/david/snap/superproductivity/803/.config/superProductivity/backups
{ enabled: null, showDevTools: false, mode: 'bottom' }
Segmentation fault (core dumped)
```

### Steps to Reproduce (for bugs)

I'm not sure how I got to this state. The application started yesterday.

### Console Output

```
$ superproductivity 
Saving backups to /home/david/snap/superproductivity/803/.config/superProductivity/backups
{ enabled: null, showDevTools: false, mode: 'bottom' }
Segmentation fault (core dumped)
```

### Error Log (Desktop only)

I could not find log file.

**Comment by johannesjo** [comment]
Hi there! Thanks for reporting. Segmentation faults are notoriously hard to debug, so I have no clue why this might be happening. A couple of questions:

1. Did you update to a new version just before this happens?
2. Did you update anything snap related just before this happens?
3. Does this appear on every startup now?
4. Does uninstalling and reinstalling the app help?

I also recommend backing up your backups, just in case.

**Comment by dmp1ce** [comment]
1. I don't know if an update caused this because Snap packages are updated automatically I believe.
2. I did upgrade many packages last night. Snapd might have been one of them.
3. Yes, this error occurs on every start now.
4. I uninstalled with `snap remove superproductivity` and then installed with `snap install superproductivity` but I still get the same error on startup.

**Comment by johannesjo** [comment]
I tried to reproduce this on a fresh VM without success, unfortunately. One other thing you might try is purging the snap completely (after copying the backups someplace else!!) via `sudo apt autoremove --purge snapd`. You might also want to check the `~/.config/superProductivity` (not sure if it is the same location on arch) for any left-overs.

Also are you able to run any other snaps?

**Comment by dmp1ce** [comment]
I don't have apt installed but I was able to completely remove superproductivity with `snap remove --purge`. I still had the error though. Here is my output from the terminal.

```
david@bar:~/snap/superproductivity/current/.config/superProductivity$ superproductivity 
Saving backups to /home/david/snap/superproductivity/803/.config/superProductivity/backups
{ enabled: null, showDevTools: false, mode: 'bottom' }
Segmentation fault (core dumped)
139 david@bar:~/snap/superproductivity/current/.config/superProductivity$ snap remove --purge superproductivity
superproductivity removed
david@bar:~/snap/superproductivity/current/.config/superProductivity$ ls
ls: reading directory '.': No such file or directory
2 david@bar:~/snap/superproductivity/current/.config/superProductivity$ cd ~/snap/superproductivity/
david@bar:~/snap/superproductivity$ ls
current
david@bar:~/snap/superproductivity$ pwd
/home/david/snap/superproductivity
david@bar:~/snap/superproductivity$ snap install superproductivity
superproductivity 5.9.2 from johannesjo installed
david@bar:~/snap/superproductivity$ superproductivity
Saving backups to /home/david/snap/superproductivity/803/.config/superProductivity/backups
{ enabled: null, showDevTools: false, mode: 'bottom' }
The futex facility returned an unexpected error code.Aborted (core dumped)
134 david@bar:~/snap/superproductivity$ ls
803  common  current
david@bar:~/snap/superproductivity$ cd current
david@bar:~/snap/superproductivity/current$ ls
david@bar:~/snap/superproductivity/current$ cd ..
david@bar:~/snap/superproductivity$ ls
803  common  current
david@bar:~/snap/superproductivity$ pwd
/home/david/snap/superproductivity
david@bar:~/snap/superproductivity$ 
david@bar:~/snap/superproductivity$ 
david@bar:~/snap/superproductivity$ snap --version
snap    2.47-1
snapd   2.47-1
series  16
arch    -
kernel  5.4.69-1-lts
david@bar:~/snap/superproductivity$ 
```

**Comment by dmp1ce** [comment]
I tried `notepadqq` and `marsshooter` from the snapstore and they also had core dumps, so maybe there is a problem with my snap. I'll keep this issue updated once I learn more.

**Comment by johannesjo** [comment]
Thank you! I appreciate it!

**Comment by dmp1ce** [comment]
Still having issues. I updated to the snap candidate release. Here is my messages from dmesg:

```
[ 1340.674755] superproductivi[40434]: segfault at 208 ip 0000562c877cef43 sp 00007ffecdf7d640 error 4 in superproductivity[562c81969000+5f88000]                                                                                             
[ 1340.674760] Code: 55 41 54 53 50 83 7f 78 00 0f 85 a6 00 00 00 49 89 fe b9 01 00 00 00 31 c0 f0 0f b1 4f 78 85 c0 0f 85 8f 00 00 00 49 8b 46 08 <44> 8b a0 08 02 00 00 41 83 fc ff 74 0f 41 bf 01 00 00 00 4c 8d 2d                        
[ 1340.674821] audit: type=1701 audit(1602333286.536:306): auid=1000 uid=1000 gid=1000 ses=4 subj==snap.superproductivity.superproductivity (enforce) pid=40434 comm="superproductivi" exe="/snap/superproductivity/803/superproductivity" sig
=11 res=1
```

Sometimes I get a `The futex facility returned an unexpected error code.Aborted (core dumped)` message on the terminal instead of `Segmentation fault (core dumped)`.

**Comment by johannesjo** [comment]
Do the other snaps work now?

**Comment by dmp1ce** [comment]
It looks like it is a Gnome issue. https://forum.snapcraft.io/t/apps-wont-run-and-crash-on-gnome-wayland/20322/6

**Comment by johannesjo** [comment]
Thanks for the update!

**Comment by khartahk** [comment]
Any news on how to get the app back and running? I have the same issue and really need the data I have in the app for my work.

**Comment by johannesjo** [comment]
@khartahk Just a guess, but I'd assume that either downgrading snap or using a previous version of the kernel might do the trick.

**Comment by khartahk** [comment]
I'll try downgrading snap. The kernel is a bit more risky for me as I'm using Arch with ZFS and I really don't want to try that out atm. For now I'm using the web app as a replacement. The dropbox sync is working nicely with that.
Thank you

**Comment by johannesjo** [comment]
@khartahk please let us know how it works out if you downgrade the snap version.

**Comment by khartahk** [comment]
I've downgraded snapd to:
- 2.46.1-1
- 2.45.3.1-2

and did a: `sudo systemctl daemon-reload && sudo systemctl restart snapd.service`

and I still get:

```
Saving backups to /home/******/snap/superproductivity/803/.config/superProductivity/backups
{ enabled: null, showDevTools: false, mode: 'bottom' }
[1]    550446 segmentation fault (core dumped)  superproductivity
```

**Comment by dmp1ce** [comment]
I think Mutter broke snapd. We'll have to wait until snapd is working with the new Mutter, downgrade Mutter or use X. That's what I would suggest anyway. I'm going to try to get SuperProductivity with the AppImage or AUR for the time being.

**Comment by johannesjo** [comment]
Thanks for digging into this. Let's hope they fix this issue soon.

**Comment by dmp1ce** [comment]
The issue is fixed for me today on Arch Linux.
