### ISSUE TITLE
Wrong URL on button "Write comment" in jira

### ISSUE THREAD

**Issue by JustAPhrog** [johannesjo/super-productivity#566]
In jira we use ticket key (It's like "project_key" and number of incident in project like 'DNRPL-124') but now Its some number. 
Now: `<jira>/browse/1694873`
Shude be: `<jira>/browse/DNRPL-124`

Can you add some settings to choose which property is used to **comment incident**?

**Comment by johannesjo** [comment]
Hi there! Thanks for reporting. This should be fixed with the latest release for newly imported issues. Could you confirm this?

**Comment by JustAPhrog** [comment]
Oh yes! I install 5.9.10 and delete-add again and it works! **BTW: Awsome app!**
