### ISSUE TITLE
Windows app suddenly uses all the system memory, closing the app doesn't release them

### ISSUE THREAD

**Issue by Looooong** [johannesjo/super-productivity#567]
### Your Environment

* Version used: 5.9.9 
* Operating System and version: Windows 10 version 2004 build 19041.508
* Desktop Environment: 
* Browser Name and version: 

### Expected Behavior

There should be an option to really quit the app, release all the memory used by the app.

### Current Behavior

This is the first time I saw it suddenly consumed all the memory and disk usage. Closing the app doesn't release the memory. The app is instead moved to the background.

![Capture](https://user-images.githubusercontent.com/8206622/95348665-726b4680-08e8-11eb-8694-bb90b0d40d80.PNG)

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by johannesjo** [comment]
Thanks for reporting. This is weird. I never encountered this on windows before and I can't reproduce this.  Can you consistently reproduce the issue? And are you using the pen drive version or the setup.exe?`

**Comment by johannesjo** [comment]
Very likely related: #493

**Comment by Looooong** [comment]
I only experience this issue once yesterday. And I forgot to check the console before killing the app. So I don't know how to reproduce this issue. The features I used in the app yesterday are:
+ Start/stop tracking task using global hotkey.
+ Open/close the app using global hotkey.
+ Synchronize to Google Drive.
+ Track a task for 9.5 hours.
+ Modify spent time on task.

I think that you should work on the second problem, where is no mechanism to really kill the app, except for using Task Manager.

**Comment by Looooong** [comment]
If I close the app, either by clicking the X button or select Close via system tray, the app will go to the background process list, and the memory is not released at all.

I use the Windows Store version.

**Comment by johannesjo** [comment]
Ah thanks! That's interesting. Haven't tested the store version for this issue to be honest. I'll check what might be causing this.

**Comment by johannesjo** [comment]
The windows store version also closes fine in my tests. I found [this suggestion](https://github.com/electron/electron/issues/9862#issuecomment-311091761). If it doesn't fix the issue it might at least provide a little more insight, why this might be the case.

**Comment by johannesjo** [comment]
I'll make a new pre-release shortly ([available as a download here as version 5.9.15.](https://github.com/johannesjo/super-productivity/releases)). Could you check with it, if this still occurs?

**Comment by Looooong** [comment]
I have just taken a look at how the app is closed again. Under normal circumstance, the app is removed completely from the process list. So I guess that the memory problem back then prevented the app from closing fully.

**Comment by johannesjo** [comment]
Yes, it seems like it. I would very much appreciate it if you could keep an eye out on when this happens (if it happens again). I really can use all information I can get. There is also a little performance monitor included in the app. You can access it by opening up the dev tools (Ctrl+Shift+i), clicking the little three dots on the top right of the new window and then go to "More Tools/Performance Monitor".

**Comment by Looooong** [comment]
Sure, I will keep it in mind next time.

**Comment by thetric** [comment]
I encountered this closing bug under Linux too.

- Version: 5.9.15-SNAPSHOT, Commit 1d37e0a (based on PR https://github.com/johannesjo/super-productivity/pull/501)
- OS: Arch Linux (5.8.12-arch1-1), 64 bit

Repro:
- `yarn buildAllElectron:noTests:prod && electron-builder --linux`
- `./app-builds/superProductivity-5.9.15.AppImage`
- close the app

Can be reproduced without previous backups (no `.config/superProductivity` folder)

**Comment by johannesjo** [comment]
@thetric thanks! I'll try to check this tomorrow.

**Comment by johannesjo** [comment]
@thetric For 5.9.15 I think I broke it with 5e340ad. After 4f5212f I am unable to reproduce this for the AppImage. Could you please confirm if it is working for you with 4f5212f as well?

**Comment by thetric** [comment]
Looks good to me. The app is closed as expected

**Comment by HoaxParagon** [comment]
I just experienced this issue myself, all memory suddenly used up by the app. I only recently started using it last night and I didn't do anything out of the ordinary to cause it. I left it going for probably close to 8 or 9 hours and then my system acted sluggish and the program stopped responding. Once I terminated the app, the problem continued intermittently for 5 minutes, maybe less, then returned to normal once explorer stopped freaking out.
Screenshot included, shows 6 processes with over 27 Gb used.
App installed from Microsoft store on Windows 10, version 6.5.2.
![what_the_actual](https://user-images.githubusercontent.com/59360325/120108683-8e478500-c123-11eb-9a3b-4cc71cfcad29.png)

**Comment by johannesjo** [comment]
Thanks @HoaxParagon! Not sure how to best address this. I doubt that this is a Super Productivity issue, as it doesn't happen with the non store version. So I rather suspect electron or electron builder being responsible though I was unable to find any similar issues. Best solution for now is to use the setup exe instead.

**Comment by Looooong** [comment]
@johannesjo I think you should add a way to monitor the Window Store version. For example, have a trigger to notify user whenever the app exceed a certain amount of memory and a button to dump the memory or write console log to file when that happens, as new users, especially non-technical users, don't know about the existence of the console log and would close the app outright and cannot reproduce the issue again.

On the other hand, I have been using the app since the last time we discussed about this issue, and I faced no memory issue ever since.

**Comment by HoaxParagon** [comment]
@johannesjo 

OP said:
> * Track a task for 9.5 hours.

I also left the app going for around that length of time. Not a great sample size, I know, but could that bug have something to do with how long it's running? I didn't notice any leak leading up to the crash but I also wasn't paying attention to notice a slow leak. It did seem very sudden to me though, as if all at once some conditional broke and started flooding memory with objects.
Notice the other difference between my screenshot and his; the disk usage in mine is nothing to write home about.

I'm going to continue to use the app store version in hopes I find something definite out. I'm not sure what but if it happens again after 9 hours that may be a lead. Maybe an overflow on a seconds counter or something?

**Comment by Looooong** [comment]
@johannesjo Good news, I encountered the issue again. As I expected, the culprit is the renderer process. At the time of incident, I have multiple heavy apps open, and had been running SuperProductivity for more than 20 hours without powering off my computer. It had tracked multiple tasks for 8 hours long, and had tracked idle time for more than 10 hours. Here are screenshots and log:

[super_productivity.log](https://github.com/johannesjo/super-productivity/files/6619649/super_productivity.log)

![details](https://user-images.githubusercontent.com/8206622/121258608-52f24680-c8d9-11eb-8a48-52b8b0bcb394.PNG)

![processes](https://user-images.githubusercontent.com/8206622/121258613-54237380-c8d9-11eb-8e49-cc6b53fef9bc.PNG)

The bad news is, I couldn't take memory snapshot in time before the memory consumption went back to normal.

In the past, when monitoring the process, I noticed that the renderer process is the one that has tendency to grow memory usage, as high as 1.5GB. However, after some time, it will reduce its usage to around 300MB, and the cycle repeats. In this incident, the memory went as high as 8GB before returning to normal consumption.

**Comment by johannesjo** [comment]
Thank you very much for digging into this @Looooong 

we're still talking about the windows store version, richt?

**Comment by Looooong** [comment]
Yes, I'm using the Windows Store version 7.0.0.

**Comment by Looooong** [comment]
@johannesjo The issue is more severe than I thought. I haven't power off my computer since the last time I got this issue and updated to you. When I closed SuperProductivity using the `X` button on the windows, all the processes got removed except one. You guess it, it's the renderer process. It still remained in the background. After I was using my computer for awhile, it suddenly consumed all the remaining memory available to the system. That's when I realized it was there. When I opened the task manager, I saw that it consumed around 2.2GB memory, and there were 2 processes. When I went to the Details tab, I can only saw one process left, and its memory consumption went back to normal. And then, another issue is arising, it's consuming CPU power.

![Capture](https://user-images.githubusercontent.com/8206622/121393060-28a49580-c97a-11eb-92a7-063bfc7540b5.PNG)

**Comment by johannesjo** [comment]
@Looooong I opened up an electron builder issue. Could you please post your dump file there (I don't want to do it without your permission)?

**Comment by johannesjo** [comment]
Thank you! A thumbs up might also help :D

**Comment by vctls** [comment]
Not sure if it's the same issue, but I also have CPU problems with v7.12.0.  
SP spawns multiple child processes, which sometimes start consuming a lot of CPU.  
Some processes are not terminated when closing the app.
