### ISSUE TITLE
Selection of multiple tasks

### ISSUE THREAD

**Issue by HananoshikaYomaru** [johannesjo/super-productivity#573]
First, thanks developers for this amazing app. My productivity is boosted thanks to this app. But there are some UI issues that are kind of inconvenient. One of the biggest problem is that I cannot select multiple tasks at once and perform the same operation on them such as adding tags, note, or reminder. I wish there will be a multiple task selection function supported (or if it has already supported but I don't know, please let me know =]).

**Comment by johannesjo** [comment]
Thanks for opening this up. There is a lot of other stuff to do, so I won't be working on this by myself anytime soon, but I'd also like to see this at some point. If somebody wants to take this on, please get in touch so we can discuss the implementation details.
