### ISSUE TITLE
Weired artifacts flickering on the GUI

### ISSUE THREAD

**Issue by nicos68** [johannesjo/super-productivity#575]
* Version used: 5.9.2
* Operating System and version: Kubuntu 20.04
* Desktop Environment: KDE Plasma

### Current Behavior
When moving the mouse around some weird artifacts flicker above the GUI.

![image](https://user-images.githubusercontent.com/1062625/95691074-a1512780-0c1c-11eb-86ee-b7be5d3a063c.png)

**Comment by johannesjo** [comment]
Thanks for reporting this. Firefox is currently not a priority. But I gladly accept any PRs to deal with this, though this looks like an issue which might have nothing to do with the app.

**Comment by nicos68** [comment]
I have the issue on the app, not in the browser.

**Comment by johannesjo** [comment]
I thought you might have been using the web app cause you specified `Browser Name and version: Firefox 81`

**Comment by johannesjo** [comment]
Is the bug reliably reproducible? Do you have a 3D graphics card? Any clues what might be causing this? As I can't reproduce this myself, I need all the information I can get about this.

**Comment by nicos68** [comment]
It happens systematically. No clue why. Details about my hardware below.

https://nise.io/shaarli/?Goakkg

**Comment by johannesjo** [comment]
Thanks. This is pretty weird. I assume you never encountered any problems like this in regular chrome or chromium?

**Comment by johannesjo** [comment]
Does starting the app via
```
superproductivity --disable-gpu-driver-bug-workarounds --enable-native-gpu-memory-buffers
```
or
```
superproductivity --enable-native-gpu-memory-buffers
```
or
```
superproductivity --disable-gpu-driver-bug-workarounds
```
change anything?

**Comment by nicos68** [comment]
None of those options change anything.

**Comment by johannesjo** [comment]
Thanks for checking.

**Comment by johannesjo** [comment]
And how about:
```
superproductivity --disable-gpu
```
?

**Comment by johannesjo** [comment]
That's at least something. 

This is most likely an electron issue (#8127). There is nothing that I can do on my end for now :(

**Comment by nicos68** [comment]
Good to know. First time I see that and I use several electron apps.

**Comment by johannesjo** [comment]
As there currently is nothing more I can do, I am closing this. Hopefully, this fixes itself one way or the other.

**Comment by nicos68** [comment]
Hi,

I just launched the app today after months without using it and the issue is gone :).

**Comment by johannesjo** [comment]
Glad to hear it! :)
