### ISSUE TITLE
Time spent/estimates: date picker to choose a date for another day looks broken

### ISSUE THREAD

**Issue by thetric** [johannesjo/super-productivity#576]
### Your Environment

* Version used: 5.9.9 (Windows Store)
* Operating System and version: Windows 10 Enterprise, Version 1909 (Build 18363.1082)
* Desktop Environment: Windows
* Browser Name and version: n/a

### Expected Behavior
It should look like the Angular Material date picker:

![image](https://user-images.githubusercontent.com/19861998/95725606-2a497c80-0c78-11eb-94e5-49c83a0abefc.png)

### Current Behavior
The day picker does out of the modal dialog:
![image](https://user-images.githubusercontent.com/19861998/95723973-0f760880-0c76-11eb-9e23-986deaa640ab.png)

### Steps to Reproduce (for bugs)
1. Create a new task/use an existing one
2. open the additional info panel
3. edit the time and click on "add time spent for other day"
4. click on the date picker icon

### Console Output
Nothing in relation to the bug:
```
{}
main.5a62f0f816872b3b2a47.js:1 undefined
main.5a62f0f816872b3b2a47.js:1 0
main.5a62f0f816872b3b2a47.js:1 undefined
main.5a62f0f816872b3b2a47.js:1 0
main.5a62f0f816872b3b2a47.js:1 0
main.5a62f0f816872b3b2a47.js:1 0
main.5a62f0f816872b3b2a47.js:1 0
main.5a62f0f816872b3b2a47.js:1 0
main.5a62f0f816872b3b2a47.js:1 {}
main.5a62f0f816872b3b2a47.js:1 undefined
main.5a62f0f816872b3b2a47.js:1 0
main.5a62f0f816872b3b2a47.js:1 undefined
main.5a62f0f816872b3b2a47.js:1 0
main.5a62f0f816872b3b2a47.js:1 0
main.5a62f0f816872b3b2a47.js:1 0
```

### Error Log (Desktop only)
file not found

**Comment by johannesjo** [comment]
Thanks for opening this up! I can confirm this is an issue on all platforms.

**Comment by johannesjo** [comment]
This only occurs for the production build. I think this is an issue with angular material. I opened up an issue here:

https://github.com/angular/components/issues/20794

**Comment by johannesjo** [comment]
Should be fixed now.
