### ISSUE TITLE
Push new releases to the snap store

### ISSUE THREAD

**Issue by hackel** [johannesjo/super-productivity#58]
I installed super-productivity with snap, but the latest version in the store is 1.3.6.  I then found the snap file on your Github releases page.  This is not how snaps are meant to be distributed, because they are unsigned and require installation with "--dangerous", and won't receive automatic updates.  

Please add steps to your CI routine to push each new release to the snap store.  You could push automated releases to the "candidate" channel, and then manually promote them to "stable" whenever you feel it is warranted if that is a concern.

Thanks!

**Comment by johannesjo** [comment]
Hey there! Thanks for reporting! There is also a snap version maintained by @Morganamilo: https://aur.archlinux.org/packages/superproductivity/ 
I will have a look, why the snap pages are not distributed any more.

**Comment by Morganamilo** [comment]
My version is based on the deb. All it does is disassembly your deb and resembles it into an arch package.

**Comment by johannesjo** [comment]
@Morganamilo oh you're right. Sorry.

**Comment by johannesjo** [comment]
So I spend the whole day on getting automated deployments to run again without any luck. I'm glad for any help! For now I'll resort to manually updating the snaps.
