### ISSUE TITLE
Deleting Projects

### ISSUE THREAD

**Issue by rohanrk** [johannesjo/super-productivity#581]
I've noticed that in order to delete a project I'm on I have to go to the manage projects page and cannot delete the currently selected project (likely a safety mechanism). Since it already takes a few clicks to get to the delete state, should the app allow deleting current projects and default to something like the topmost project?

**Comment by johannesjo** [comment]
Hey there! thanks for opening this up. I am open to implementing this and I agree that it would be better to allow for this. There is a lot to do as is, however, so I am unlikely to get to it anytime in the near future, but a PR would be very welcome.
