### ISSUE TITLE
Softer, slower pomodoro tick

### ISSUE THREAD

**Issue by prat0088** [johannesjo/super-productivity#583]
## Problem Statement

When I enable the pomodoro ticking sound, it sounds like a jackhammer echoing in an empty room.  The tick is ~3 times per second and very aggressive. 

## :grey_question: Possible Solution 

I want a gentle tick that ticks once per second, like a kitchen timer or egg timer.  For example: https://commons.wikimedia.org/wiki/File:Clock_ticking.ogg

I can't think of anybody alive who would prefer the current tick to the .ogg file.  Would a quick solution be to swap out the current tick with the file above?

## :arrow_heading_up: Describe alternatives you've considered

I've considered not using the ticker.  Before I started pomodoro I thought it was a gimmick, but after trying pomodoro for a month I absolutely need that tick for it to be effective and keep me in work mode.

**Comment by johannesjo** [comment]
Thank you very much for opening this up.

As mentioned in #180: I would need help with this.

**Comment by prat0088** [comment]
@johannesjo as a first pass would you accept a PR that replaces the tick with a nicer version?  The "break done" blip also startled me just now.  Then I can follow up with adding an option and making them user-selectable.

**Comment by johannesjo** [comment]
@prat0088 yes this would be great! I am also all for making the defaults work better, before adding something customizable.


Sorry for stressing this so much, but before I can merge anything, we need to be safe on the legal side of things though, as it might get expensive if I'd publish something illegally.

**Comment by prat0088** [comment]
> @prat0088 yes this would be great! I am also all for making the defaults work better, before adding something customizable.

Cool, I'll see what I can find.

> Sorry for stressing this so much, but before I can merge anything, we need to be safe on the legal side of things though, as it might get expensive if I'd publish something illegally.

Yep of course : )
