### ISSUE TITLE
Pomodoro-based time estimates

### ISSUE THREAD

**Issue by prat0088** [johannesjo/super-productivity#584]
## Problem Statement

I want to estimate my tasks in Pomodoros

## :grey_question: Possible Solution 

There is already a toggle setting to enable pomodoro style timers.  I think there should be a top-level setting that enables pomodoro mode across the app.  The timer would change, and the time estimates would change too.  Perhaps the reporting as well, but that is less important to me at the moment

## :arrow_heading_up: Describe alternatives you've considered

Estimating tasks in 30m increments

## :heavy_plus_sign: Additional context

I came across this app because I was looking for a pomodoro app that allows me to make a task list, estimate it in pomodoros, and work on those tasks, and view my performance over time.

**Comment by johannesjo** [comment]
Thanks for opening up. I really like the general idea. 

Just a note: If we implement this, we need to make sure, that this doesn't interfere with people who don't use the Pomodoro timer. Personally, I only use it from time to time, when I am really not motivated to do something.

**Comment by johannesjo** [comment]
Not sure how to deal with the clickable ui part, but we could extend the short syntax with something like
```
my task title 2ps
```

**Comment by janLo** [comment]
I'd like this feature very much.

**Comment by johannesjo** [comment]
I think we need a little bit more detailed concept first on how to implement it (ideally, keeping it simple). And as mentioned above it should not affect users that don't use the pomodoro timer.
