### ISSUE TITLE
Count up when pomodoro is finished, manual start to break

### ISSUE THREAD

**Issue by prat0088** [johannesjo/super-productivity#585]
## Problem Statement

I'm really used to the way Focus Timer lets me configure things:

When a pomodoro finishes counting down, it starts counting up to show how much extra time you've worked.  Eg. -2 minutes -> + 3 minutes shows I've worked 3 minutes past the pomodoro.  Ticking continues.

I open the app and click "Finish / start break".  A break starts.  The timer on the break works the same way.

## :grey_question: Possible Solution 

See above

## :arrow_heading_up: Describe alternatives you've considered

I didn't see any other settings to accomplish this when I looked around

How big of a change do you think this would be?  What area of code should I look at?  I'm brand new to the project.

**Comment by johannesjo** [comment]
Thanks for opening this up. This should be doable with moderate complexity. PRs would be welcome! Do you think this should be the default behavior or should we make it optional?

**Comment by prat0088** [comment]
@johannesjo I think this should be default behavior.  It mirrors the actual situation: if you miss a timer you will still be working or on break, and the logged time won't be reflective of your actions.
