### ISSUE TITLE
Hover-over app icon to see current task being timed, and stop/pause/stop controls

### ISSUE THREAD

**Issue by prat0088** [johannesjo/super-productivity#586]
## Problem Statement

I want to be reminded what task I'm on, or quickly move from break to the next pomodoro.

## :grey_question: Possible Solution 

Hover over the app icon (task bar, not system tray) to reveal a nicely formatted card of the current task's title, the current timer time, and start/stop/pause buttons, like many media player apps have.

![image](https://user-images.githubusercontent.com/20519/96273566-7b6daf00-0f9d-11eb-84bd-bbf67ecaa7d6.png)

**Comment by johannesjo** [comment]
Thanks for opening this up! I would love to see this!

**Comment by AvroraPolnareff** [comment]
Hi, I want to help with this issue!

**Comment by johannesjo** [comment]
@AvroraPolnareff that's great news! Please let me know if you need any info to get started.
