### ISSUE TITLE
3 convenient changes and improvements recommendation

### ISSUE THREAD

**Issue by maxeron** [johannesjo/super-productivity#592]
First of all, thank you for creating this masterpiece and giving it away for free. This is the best thing ever for managing things. There is some problem that I hope you'd work on. 

Inconvenience 1 - Finish Day
The finish day 'feature' is really great, but since I worked until 1:00 AM, it's kinda doesn't really work. It would start tracking the next day (because it's after 12:00), and I wouldn't be able to go back to do the evaluation for the previous day. So my metrics are messed up and I can't use that feature properly. It would be nice if there's a way to turn off or prevent it from going to the next day after 12:00 AM.

Inconvenience 2 - Task and Subtask time tracking
If a task has subtasks, I couldn't track time for the whole task. I have subtasks that often takes around 10 minutes to do, and I would have to constantly track time for each subtask. It would be nice if I can just track time for the whole task.

Inconvenience 3 - Easier way to add tags
The least important change is maybe a way to add tags to too many tasks at the same time. I know that you can click on a tag and add there directly but then I would have to add the project. A way to select and do something like add tags would be really helpful.

Thank you for reading and for creating this software.

**Comment by johannesjo** [comment]
Hey there! Thank you very much for your feedback! I think the best place to discuss this is the new discussions board:
https://github.com/johannesjo/super-productivity/discussions?discussions_q=category%3AIdeas
