### ISSUE TITLE
Sync Error (last sync value newer than local)

### ISSUE THREAD

**Issue by mbostanara** [johannesjo/super-productivity#596]
### Your Environment

* Version used: Super Productivity 5.9.9
* Operating System and version: Windows 10 Enterprise

### Bug:
Whenever I open the program this error happens:
![image](https://user-images.githubusercontent.com/62683393/96391154-87f34100-1203-11eb-93d7-e36ef483006b.png)

However, I have not manually manipulated data.

**Comment by johannesjo** [comment]
Thank you very much for reporting. This can happen if the app closed (crashed?) in an unexpected manner before. May I ask how you are closing the app?

**Comment by mbostanara** [comment]
Thank you for your reply. I usually hibernate my computer and when I turn it on again this error happens (I do not close Super Productivity program everyday).

**Comment by johannesjo** [comment]
Thanks. That's interesting. I'll try to improve this.

Normally when you click ok and sync again the error should disappear, but that didn't work for you?

**Comment by mbostanara** [comment]
Thank you very much.
As far as I remember, when I press 'ok', then another prompt is shown that 'the online version is newer than the local version' [which I guess is not true, because the local version is the same as where I left it the previous date]. So, I do not press that button because It may affect my local data.

**Comment by johannesjo** [comment]
In this case, maybe you can make a local export of your data, just to be save. After that you import the remote data. If it's older than your local one, you can re-import the export. Things should, hopefully, run as expected afterwards.

**Comment by mbostanara** [comment]
I usually resolve the issue by pressing 'back up now' button in the 'sync with google drive' section of settings. But, next time I will try what you suggested. Thank you.

**Comment by johannesjo** [comment]
I think I fixed this (should be available with the current pre-release), hopefully without introducing any new problems :) Thanks again for bringing this to my attention!

**Comment by johannesjo** [comment]
And please let me know if you encounter any additional issues.
