### ISSUE TITLE
Sceenshots ?

### ISSUE THREAD

**Issue by shtefcs** [johannesjo/super-productivity#6]
Hi there,

Great app. Is there any plan and possibility to add screenshots ? Like on hubstaff, upwork time tracker with screenshots made on X minutes.

Peace!

**Comment by johannesjo** [comment]
Hi! Thanks for your post. Currently a feature like this is not implemented. I'm personally not a big fan of monitoring your employees like that (after all a work relation should be build on trust), but technically it should be definitely possible to implement this.

**Comment by shtefcs** [comment]
Hey @johannesjo  thanks for the reply mate.

You are right when looking from that perspective, but screenshots is not just about trust.

There are at least two case scenarios where the screenshots are handy:

- Like you said trust. As we are 99% remote team and new people joining us often, we need screenshots to check out developers time spent and compare with the results.

- Second case is when you already have built trust with developer, screenshots come handy to watch and track his progress.

Sometimes its enough to go and check the last 5h screenshots, and you can see what dev did or what problems he found out.

Technically, what would be the best path to take and create the screenshots features ?

Stefan, Peace!

**Comment by johannesjo** [comment]
You would need an OS specific implementation[ like it's being done for the idle time tracker](https://github.com/johannesjo/super-productivity/blob/develop/electron/idle.js). For Mac OS you could use `screencapture` for example. You also would need some way to transmit the data and to review it e.g. using a simple webserver.

**Comment by shtefcs** [comment]
Thanks for the support, we might try it or build our own from scratch.

**Comment by johannesjo** [comment]
@shtefcs tell me if you need any further help. In April I will have much more time on my hands to polish this app a little more. A simple plugin system is also on the list, so adding stuff like this will get easier :)

**Comment by shtefcs** [comment]
@johannesjo  that sound great, can you join our internal chat on https://chat.vanila.io and have chat when we are available.

**Comment by veeramarni** [comment]
@shtefcs checking if there is a plugin created for screenshots?

**Comment by shtefcs** [comment]
> @shtefcs checking if there is a plugin created for screenshots?

Hi. No, its not something we built. We ended using Toptal free tracker
