### ISSUE TITLE
Constant error popup

### ISSUE THREAD

**Issue by Morganamilo** [johannesjo/super-productivity#60]
## Your Environment

* Version used: 1.9.1-1
* Operating System and version: Linux 4.15.7-1-ARCH
* Desktop Environment: i3

## Expected Behavior

No error.

## Current Behavior

This error message constantly pops up:
![image](https://user-images.githubusercontent.com/16593899/37260827-3a59e6d2-258f-11e8-8ca3-ec9ec1407f3c.png)
Along with a spam of this in the console:
```
Error: Error: Command failed: xprintidle
/bin/sh: xprintidle: command not found

    at module.exports (/opt/superProductivity/resources/app.asar/electron/error-handler.js:6:18)
    at /opt/superProductivity/resources/app.asar/electron/get-idle-time.js:24:7
    at ChildProcess.exithandler (child_process.js:289:5)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12)
```
Now its pretty obvious whats wrong here I'm missing `xprintidle` In fact I installed it and the errors went away. Now I know you only support .deb distros and snaps so for my case It's my job to add this dependency for the version I maintain.

I did look into the .deb though and you don't list it as a dependency there either. I tested on Debian where `xprintidle` was not installed by default and got the same error.

So you should probably add that as a dependency and also I think a better error message is needed, without the console output I would have had no idea what the problem is. 

## Steps to Reproduce (for bugs)

1. Don't have `xprintidle` installed
2. Start SuperProductivity

**Comment by johannesjo** [comment]
Hey. Thanks for reporting this so quickly! Just curious that the error didn't turn up before. Did you switch Distros?

**Comment by Morganamilo** [comment]
Some same distro, I did boot up a Debian vm just to test though. My guess is its always been doing that error but until now it was just never printed out.

I checked it out and and this commit 300caf073a6e46d57d083a0a52f77e2172f3e1b9 seemed to cause it so I think my assumption was right.

**Comment by johannesjo** [comment]
Yes you're right. I added a workaround for the problem. It is possible to specify third party ressources, which would be even better, but after spending my whole weekend with the quirks of travis and electron builder this has to suffice for now :) 

Btw. would you like to become a contributor for this repository? Means that you could merge pull requests, put labels on issues, and I think you get full write access as well. You have supported me so well in the past time and it would be really great to have a second person being able to push out new releases in case somethings is seriously broken and I'm not available.

**Comment by Morganamilo** [comment]
Sure being added as a collaborator would be awesome thanks. I'm not too familiar with the code base though I'd still need your confirmation to merge any PRs. I'd be happy to help manage issues and all that though.

**Comment by johannesjo** [comment]
That's great to hear :) I'll add you in a sec!
