### ISSUE TITLE
Error: Uncaught (in promise): Error: No tag TODAYError: No tag TODAY

### ISSUE THREAD

**Issue by willhseitz** [johannesjo/super-productivity#600]
### Steps to Reproduce

1.

I have been loving with app for the last few months!
Unfortunately, I have been getting this error a few times in the last few weeks. Each time, I uninstall from the Windows store, reinstall, then resync with dropbox. All my data comes back, but within a few days/app restarts, the error comes back. I assume there's corrupted/bad data being saved back to dropbox that is breaking SP.
Also, selecting "Reload App" just shows a white screen. I have to focus kill to restart app.

![image](https://user-images.githubusercontent.com/17074342/96891593-aba1cb80-143d-11eb-9877-998dbb448347.png)

### Error Log (Desktop only)

`%USERPROFILE%\AppData\Roaming\superProductivity` does not exist on my install?

### Stacktrace
```
webpack:///src/app/features/tag/store/tag.reducer.ts:45:12
memoize(function (webpack:///node_modules/@ngrx/store/fesm5/store.js:627:29)
memoized (webpack:///node_modules/@ngrx/store/fesm5/store.js:569:38)
selectors.map(function (webpack:///node_modules/@ngrx/store/fesm5/store.js:601:38)
defaultMemoize(function (webpack:///node_modules/@ngrx/store/fesm5/store.js:630:35)
memoized (webpack:///node_modules/@ngrx/store/fesm5/store.js:569:38)
source$.pipe(map(function (webpack:///node_modules/@ngrx/store/fesm5/store.js:513:66)
_next (webpack:///node_modules/rxjs/_esm5/internal/operators/map.js:35:34)
next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:53:17)
_super.prototype._subscribe.call (webpack:///node_modules/rxjs/_esm5/internal/BehaviorSubject.js:22:23)
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone.js:832:38)
value.hasOwnProperty (webpack:///node_modules/zone.js/dist/zone.js:784:20)
zone.scheduleMicroTask (webpack:///node_modules/zone.js/dist/zone.js:894:20)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:421:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm5/core.js:28122:32)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:420:39)
task._transitionTo (webpack:///node_modules/zone.js/dist/zone.js:188:50)
drainMicroTaskQueue (webpack:///node_modules/zone.js/dist/zone.js:601:38)
```

### Meta Info
META: SP5.9.9 Electron – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.9.9 Chrome/85.0.4183.98 Electron/10.1.2 Safari/537.36

### Actions Before Error
```
1603329169906: [Persistence] Save to DB 
1603329169907: [Persistence] Save to DB 
1603329170904: [Task] Add time spent 
1603329170906: [Project] Update Work End 
1603329170907: [Tag] Update Work End for Tag 
1603329170913: [Persistence] Save to DB 
1603329170914: [Persistence] Save to DB 
1603329170914: [Persistence] Save to DB 
1603329171902: [Task] Add time spent 
1603329171904: [Project] Update Work End 
1603329171905: [Tag] Update Work End for Tag 
1603329171914: [Persistence] Save to DB 
1603329171915: [Persistence] Save to DB 
1603329171916: [Persistence] Save to DB 
1603329172399: [Task] SetSelectedTask 
1603329172413: [Task] UnsetCurrentTask 
1603329174717: [Task] Move to archive 
1603329174724: [Persistence] Save to DB 
1603329174724: [Persistence] Save to DB 
1603329174725: [Persistence] Save to DB 
1603329174725: [Task] UnsetCurrentTask 
1603329174775: [Persistence] Save to DB 
1603329181345: [Layout] Hide SideBar 
1603379031603: [SP_ALL] Load(import) all data 
1603379031635: [SP_ALL] All Data was loaded 
1603379031641: [WorkContext] Set Active Work Context 
1603379031653: [Task] SetSelectedTask 
1603379040769: [Task] UnsetCurrentTask 
1603379040770: [SimpleCounter] Turn off all simple counters 
1603379048382: [SP_ALL] All Data was loaded
```

**Comment by johannesjo** [comment]
Hello @willhseitz ! Thanks for reporting this! I am sorry to hear that you're having trouble with this. 

Normally the today tag should be recreated if missing automatically, but apparently, this doesn't work in your case. It's also very weird that it's getting lost in the first place. 

It would be great if you could share a copy of your data, ideally when this error occurs (technically you should be still able to navigate to the settings, even if the error modal occurs, though it might be a bit tricky to do so). 

Are both instances running from a windows store version? Or what is the second device you're using the app from?

You also might want to try out the latest release candidate. Several things regarding sync are improved there.

**Comment by willhseitz** [comment]
Hi @johannesjo,
My next steps were to re-sync to dropbox, then export all data, re-install, and import - hoping that the bad data was stuck in dropbox and maybe the export/import would fix it. In that process, the windows store version updated to the latest, and I am no longer having the issue for a few days. I'll check back after a few more days and let you know if there have been any more issues.
Thanks

**Comment by johannesjo** [comment]
@willhseitz thank you very much for reporting back! @asimove also seems to have the same issue. I assume that this is somehow related to the Microsoft Store version in particular. 

@asimove would you maybe willing to share an export of your data to contact@super-productivity.com , so might get the chance to reproduce this issue?

**Comment by asimove** [comment]
Sorry but pascal Bras and is the same person as asimove . Asimove is my
nickname

Pascal Bras
Avenue Notre Dame de Lourdes, 66
1090 Bruxelles
Phone: +3224286009
Mobile: +32492135309



Le mer. 28 oct. 2020 à 11:37, Johannes Millan <notifications@github.com> a
écrit :
