### ISSUE TITLE
Templates for repeating task + sub task

### ISSUE THREAD

**Issue by Jee-Bee** [johannesjo/super-productivity#606]
## Add template of multiple task with subtask

It would be great if it is possible to create templates. therefore it would me more easy to add task with same patterns that happens more over.  
example of a template:  
- name:maintask
  - name:subtask 1
  - name:subtask 2
  - name:subtask 3
  - name:subtask 4

every time the user add this pattern it add basically 1 main task with inside 4 sub tasks. this would speed up for certain repetitive checklists.

**Comment by johannesjo** [comment]
Thank you very much for your suggestion! 

I personally wouldn't need this feature and I am a little wary about the complexity this might add, but I am open about adding it if more people are requesting it.

**Comment by rastacalavera** [comment]
Sorry for bringing back an old issue but this is relevant to me! I don't think a template is something that I am looking for, but I have repetitive steps that must be done across many different types of projects. It would be nice to make the project once with all my tasks and then have the ability to copy and rename it. Theming can all stay the same, just would like the ability to make something once, then quickly copy it several times.
