### ISSUE TITLE
Hide specific projects from the project list

### ISSUE THREAD

**Issue by DatCSharpDev** [johannesjo/super-productivity#608]
## Problem Statement
When working on a long list of projects, Superproductivity seems to give no option to hide finished or postponed projects (in order to focus on a shorter list)

## :arrow_heading_up: Describe alternatives you've considered

1. Add "Hide project" to the project menu
![hide](https://user-images.githubusercontent.com/22214210/97161615-5c7dd280-177e-11eb-9c1f-4eb28f842a38.jpg)

2. Add "Show/hide hidden projects" to the project list, to show the full project list or hide projects marked as hidden
![toggle-hide](https://user-images.githubusercontent.com/22214210/97161636-630c4a00-177e-11eb-98d7-2373df12fa77.jpg)

**Comment by johannesjo** [comment]
Thank you very much for your suggestion! I'd also like to see this. I can't make any promises when I get to it though. Meanwhile PRs are welcome!
