### ISSUE TITLE
Invalid time format in list "Scheduled"

### ISSUE THREAD

**Issue by AlaricLightin** [johannesjo/super-productivity#609]
### Your Environment
* Version used: 5.9.9.0 (installed from Microsoft Store)
* Operating System and version: Windows 10, 1909

### Expected Behavior
I schedule a task to 19:00 and it is displayed in "Scheduled" list with time "19:00". All task in scheduled list are displayed in 24-hour format.

### Current Behavior
I schedule a task to 19:00 and it is displayed in "Scheduled" list with time "**7:00**". All task in scheduled list are displayed in 12-hour format (but without AM and PM suffixes).

**Comment by johannesjo** [comment]
Hey there! Thanks for opening this up! May I ask what your system language is set to?

**Comment by AlaricLightin** [comment]
System language (in Windows) is Russian. But in application I use English.

**Comment by johannesjo** [comment]
Thanks! Not sure how to best deal with that, to be honest. Maybe somebody more experienced with this can help?

**Comment by AlaricLightin** [comment]
It is still relevant. In version 6.3.0-0 the bug is present.

**Comment by AlaricLightin** [comment]
It is still relevant. In version 7.6.0 the bug is present.

**Comment by johannesjo** [comment]
May I ask what time zone you're in?

**Comment by AlaricLightin** [comment]
Europe/Moscow (UTC+3)

**Comment by AlaricLightin** [comment]
BTW I see this bug on Ubuntu Linux (20.04.3) with English system language too.

**Comment by johannesjo** [comment]
Should be fixed with the next release. Thank you very much for your help and patience!
