### ISSUE TITLE
Version in the play store is 7.0.7, but the latest here is 6.0.1. I hope it is not hacked (paranoia)

### ISSUE THREAD

**Issue by ranomier** [johannesjo/super-productivity#611]
### Your Environment

* Version used: play store 6.0.6 vs 7.0.7
* Operating System and version: android 9

### Expected Behavior
The version should match the released versions.

### Current Behavior
The versions do no match

### Steps to Reproduce (for bugs)

1. Find some way to see the current version on play store. Im using aurora app (play store replacement)

**Comment by johannesjo** [comment]
Hi there! hey there! The android version has a release number of its own (the current should be 7.0, you can check it here: https://github.com/johannesjo/super-productivity-android). The android version then loads the PWA which normally should have the same number as the latest release here (currently 6.0.1).

**Comment by ranomier** [comment]
Thank you for your answer. Much appreciated :)

:+1:
