### ISSUE TITLE
[Feature Request] Dockerfile

### ISSUE THREAD

**Issue by SelfhostedPro** [johannesjo/super-productivity#612]
Adding a dockerfile so users could host their own server would be very beneficial for enthusiasts and businesses. It should be fairly simple. If you are interested in this let me know and I'll see about throwing one together for you.

**Comment by johannesjo** [comment]
Hey there! There already is one:
https://github.com/johannesjo/super-productivity/blob/master/Dockerfile

I am happy for improvement suggestions of course!

**Comment by SelfhostedPro** [comment]
Ah, I didn't realize that. It may be a good idea to add a section on using docker to the readme. It may also be a good idea to setup a GitHub action to build and push to Dockerhub as well if you don't have any other automation doing this.

**Comment by johannesjo** [comment]
The reason why I am a little hesitant about it is that it's basically just static HTML with no backend. So docker feels like overkill, to be honest. I not sure, I don't use docker regularly. What do you think? Should I add it to Dockerhub anyway? How if at all should I communicate this?

**Comment by SelfhostedPro** [comment]
I think uploading to Dockerhub would be a good idea. If you look at my Yacht repo in the workflows you can see how I'm doing it. I would just specify that this is for the frontend only and give a basic instruction on the form of a docker run command and list environment variables and what they do (if you have any).

**Comment by johannesjo** [comment]
Thank you! Makes a lot of sense. 

I set up the dockerhub instance here:
https://hub.docker.com/r/johannesjo/super-productivity

Could you maybe also help me with the build instructions? I have no environment variables whatsoever (should I add some?).  I guess it's just `docker run johannesjo/super-productivity:latest` ?

Sorry for asking so many newbies questions. While I've used docker in the past I'm really not familiar with it at all.

**Comment by SelfhostedPro** [comment]
It would be `docker run -d -p 80:80 johannesjo/super-productivity:latest`

If you have settings and want to allow users to define them easily when starting up I would recommend adding environment variables. If not, they're not required. No worries as far as questions go. I get that it can be confusing. What are you using to build for Dockerhub?

**Comment by johannesjo** [comment]
Thank you @SelfhostedPro. I'll adjust the readme. Please let me know if you think anything should be improved.
