### ISSUE TITLE
Project column in Worklog Export

### ISSUE THREAD

**Issue by lapseofreason** [johannesjo/super-productivity#616]
## Problem Statement

While it is possible to export a monthly worklog for all projects from the daily view, it is not possible to distinguish which project a certain task belongs to. This makes it impossible to use the export for creating reports that distinguish by project. 

## :grey_question: Possible Solution

Add a "project" column to the list of available columns.

## :arrow_heading_up: Describe alternatives you've considered

A workaround would be to export every project separately, add a column and then combine the CSVs, but with many projects this can be tedious.

**Comment by johannesjo** [comment]
Hi there! Makes a lot of sense. Thank you very much for opening this up. I am all for it.

**Comment by trogit90** [comment]
Just checked out the tool, Johannesjo such an incredible job you have done! adding this feature tho would be amazing to keep track of different projects. Also if possible to add tags in the colums would help alot if people want to sort their tasks that way aswell.

**Comment by jdelker** [comment]
ping, keeping this alive - it is still wanted!
