### ISSUE TITLE
Add reading field for task creation date.

### ISSUE THREAD

**Issue by felocru** [johannesjo/super-productivity#617]
Hello, what possibility is there for the task creation date to be added. In my case, every week I have to report the hours of my tasks on another platform, but since I do not have a creation date, I do not remember what day I worked the task. So the solution I did was to manually put the date next to the task.

**Comment by johannesjo** [comment]
Hi there! The creation date is already saved. We just would need to display it somewhere. Any ideas where to put it? :)

**Comment by felocru** [comment]
Hello, thanks for considering. Maybe it could be next to the project name, or next to the estimate hours? What do you think is good?
![image](https://user-images.githubusercontent.com/11906313/97352925-f023d180-1858-11eb-959f-00ebfae0bdd4.png)

**Comment by johannesjo** [comment]
Thanks for the suggestion. I assume many users won't need that information, so I thought of a less prominent place :) I try to think of something!

**Comment by felocru** [comment]
Could there be an option in settings to show or not this field? Or it could also be visible in the task form

**Comment by johannesjo** [comment]
How about:
![localhost_4200_](https://user-images.githubusercontent.com/1456265/97359108-8a593900-189c-11eb-88aa-94605fab0dde.png)

@papernoise can I ask you for your opinion on this?

**Comment by felocru** [comment]
Fantastic, I think it's very good there.

**Comment by papernoise** [comment]
@johannesjo I think where you have put it above is perfect. Was about to suggest the same. As far as I understand it, it's more a reporting-related thing, not something one should necessarily see all the time, so it makes sense to display it there.

If one does need to see all the tasks and the relative dates, one can always use the worklog I think.

**Comment by johannesjo** [comment]
@papernoise thank you!

**Comment by johannesjo** [comment]
I added it. It should be available with the next release.
