### ISSUE TITLE
WebDAV Error 504 on the android app

### ISSUE THREAD

**Issue by stop5** [johannesjo/super-productivity#618]
### Your Environment

* Version used: Super Productivity Android 6.0.1
* Operating System and version: Linageos 17.1 (Android 10)
* WebDav Software: Nextcloud 19.0.4

### Expected Behavior
Syncing with my Nextcloud instance and load data from the working desktop instance

### Current Behavior
Sync with my cloud doesn't work on the android app. I get an Error "Request failed with status code 504". On the Server access logs there is no status code 504 reported and nearly all php-fpm threads are idle.
i have entered the credentials multiple times with copy and paste. i use the same credentials as the desktop instance

### Steps to Reproduce (for bugs)
0. install super productivity from the play store
1. enable syncing
2. sync provider: Webdav
3. base url: https://cloud.domain.example/remote.php/dav/files/username
4. username: username
5. password: password
6. sync file path: super_productivity.json

**Comment by johannesjo** [comment]
Thanks for reporting. I look into it.

**Comment by johannesjo** [comment]
Did you read this section:
"Experimental!! In order to make this work for mobile or the browser you need to disable or limit CORS for your Nextcloud instance, which can have negative security implications! Please refer to this thread for more information. Use at your own risk!" 
?
:)

Anyhow, I'm looking for a way to improve this.

**Comment by johannesjo** [comment]
You can make this work by whitelisting `https://app.super-productivity.com` via this nextcloud app: https://apps.nextcloud.com/apps/webapppassword

**Comment by johannesjo** [comment]
Please let me know if this works out for you.

**Comment by thesignal** [comment]
Hi, 
I came accross the same problem with the Android application. I'm syncing with my own nextcloud instance (20.0.0).
After whitelisting `https://app.super-productivity.com` as suggested by @johannesjo (thanks!) it's working.

**Comment by johannesjo** [comment]
Thank you @thesignal ! Glad that it works. I also updated the info text, as this was communicated badly by the app.

**Comment by zecamigo** [comment]
> You should be able to ake this work by whitelisting `https://app.super-productivity.com` via this nextcloud app: https://apps.nextcloud.com/apps/webapppassword

Sorry to ask why should I whitelist your website if I'm connecting to my personal NextCloud instance?

**Comment by johannesjo** [comment]
> Sorry to ask why should I whitelist your website if I'm connecting to my personal NextCloud instance?

This is only required for the mobile and the web app. The desktop version should indeed work fine without this step.
