### ISSUE TITLE
Create Project in offline mode

### ISSUE THREAD

**Issue by prsgh** [johannesjo/super-productivity#619]
while creating project when device is offline Project Name field doesn't accept input

**Comment by johannesjo** [comment]
Could you please elaborate? Offline shouldn't affect anything apart from third party issue providers and syncing.

**Comment by prsgh** [comment]
sorry
I try to reproduce the bug but I can't. But the details was when I start the app I have no internet connection and when I tried to create project title push up animation for Project name field wont work and it stuck and when I connected to internet the problem solved

**Comment by johannesjo** [comment]
Thanks for letting us know. I'd assume that this was some sort of weird hiccup, but not really an issue of the app. Please let me know if you encounter any other problems or this particular one again.
