### ISSUE TITLE
High CPU load

### ISSUE THREAD

**Issue by jkpubsrc** [johannesjo/super-productivity#621]
### Your Environment

* Version used: Latest stable snap
* Operating System and version: Ubuntu 16.04

### Current Behavior

After some time the application is running: Main snap process has 100% CPU load (= fully consumes 1 CPU). The load does not go down again. This behavior is reproducible.

### Error Log (Desktop only)
(Could not find any logs at the suggested path.)

**Comment by johannesjo** [comment]
Hey, thanks for reporting. Personally, I haven't encountered any problems with CPU usage. Could you provide a little bit more info on how to reproduce this? Also, a bit of info on your system might be helpful. What kind of CPU do you have and how much RAM?

**Comment by jkpubsrc** [comment]
Hi!

System: Intel i5-6600 quad core with 32 GByte of RAM. I don't think this could be the cause.

If I start the application it works fine. After some time the CPU load get's as high as described. I can't provide you with more details as I have no clue how the application works internally and what background activities there might be.

Last time I run it today I got a crash out of "nowhere": it was minimized and suddenly the application crashed with an error message, interrupting me in my work. Sorry, I did not store the error message. Might be related but might not, I don't know. It seems as there is definitively something going on in the background that causes a bit of trouble.

If it crashes again I'll provide you with more details. But I've no idea if this is related to the high-CPU-problem or something completely different.

**Comment by johannesjo** [comment]
I will test the snap in a Ubuntu VM for this behaviour. Maybe this has something to do with the relatively old Ubuntu version. 

Testing this with your data and settings might also help. It would be great if you could share a copy of an export of it to contact@super-productivity.com. You can create an export by navigating to "Settings" and then to "Import/Export".

**Comment by jkpubsrc** [comment]
> Maybe this has something to do with the relatively old Ubuntu version.

Yes, maybe, but I cannot tell: I'd like to update this system already for quite some time but had not yet the time to do this :-/ I will finally be able to do this in a view weeks, but likely not earlier.

I already tried to do an export of my data in order to see how the data structure would look like. Unfortunately exporting did not work: Your application caused just a standard directory window to open, not a save-file-dialog, so no data seems to have been saved. THIS might be related to me running an older version of Linux where some bugs might not have been fixed.

**Comment by johannesjo** [comment]
There is probably not much I can do for now, as I didn't find any obvious memory leak or something like this. If you notice anything which might help to get to the bottom of this, please let me know! Meanwhile, you might want to try using the deb version instead. I can also imagine that this somehow is related to an older snap version or something like that.

**Comment by jkpubsrc** [comment]
FYI: I just returned to my computer after about 4 hours and the result: No high CPU load. I can not tell what happened in the meanwhile, but right now: No error, no high CPU load.

I agree: Probably you can't do much at this time. That's why I would recommend: Close this issue for now. If I run again into problems, you can reopen it if necessary.

FYI: Actually I first tried to install the Debian version. Which failed: The 16.04 is simply too old for that. At some point I gave up as it seemed too complicated trying to compensate for this: That's why I tried to use the snap version. A more reasonable approach would be to upgrade my system first (as planned for the next weeks anyway). But I thought a 16.04 is a LTS so it should work - but in this specific situation it might not. At least problems like high CPU load are a bit strange. (I encountered a few other bugs as well, but did not report them yet as they were not that strange as a high CPU load.)

Are you using the 20.04 LTS? I had some problems with it the last time I installed it (on a different system) and ended up falling back to the 18.04.

Anyway: Thank you for your support!

**Comment by johannesjo** [comment]
Alright, I am closing this then :)

I agree that a LTS should work...

I am using 20.04 correct. I think I had some minor problems after upgrading from 18.04 to 20.04, but nothing which kept me busy for more than a couple of hours. 

Good Luck! Please let me know if there is anything else I can do.
