### ISSUE TITLE
Error: Trying to import project into web version of superproductivity 

### ISSUE THREAD

**Issue by jeffbelmiro** [johannesjo/super-productivity#623]
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
this._persistenceService.project.loadState (webpack:///src/app/features/project/project.service.ts:205:16)
Ur (https://app.super-productivity.com/main.2e71b6240367db6e355c.js:1:2807545)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:373:29)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.js:27488:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:55)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:135:46)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1274:39)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:407:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:27476:32)
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1215:38)
makeResolver (webpack:///node_modules/zone.js/fesm2015/zone.js:1118:20)
Ur (https://app.super-productivity.com/main.2e71b6240367db6e355c.js:1:2807563)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:373:29)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.js:27488:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:55)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:135:46)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1274:39)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:407:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:27476:32)
```

### Meta Info
META: SP6.0.1 Browser – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36

### Actions Before Error
```
1603892014019: [SP_ALL] Load(import) all data 
1603892014022: [SP_ALL] All Data was loaded 
1603892014032: [WorkContext] Set Active Work Context 
1603892014063: [Task] SetSelectedTask 
1603892029923: [Layout] Hide SideBar 
1603892055795: [Layout] Toggle SideBar 
1603892062887: [WorkContext] Set Active Work Context 
1603892062913: [Task] SetSelectedTask 
1603892063022: [Note] Load Note State 
1603892063026: [Bookmark] Load Bookmark State 
1603892063028: [Metric] Load Metric State 
1603892063031: [Improvement] Load Improvement State 
1603892063034: [Obstruction] Load Obstruction State 
1603892063036: [Project] Load Project related Data Success 
1603892063037: [Improvement] Clear Hidden Improvements 
1603892063038: [Improvement] Delete multiple Improvements
```

**Comment by jeffbelmiro** [comment]
Error: Uncaught (in promise): TypeError: Cannot read property 'entities' of undefined TypeError: Cannot read property 'entities' of undefined at t.i (https://app.super-productivity.com/main.2e71b6240367db6e355c.js:1:2807194) at i.next () at s (https://app.super-productivity.com/main.2e71b6240367db6e355c.js:1:2807545) at l.invoke (https://app.super-productivity.com/polyfills.250ebd3af63450554a58.js:1:6639) at Object.onInvoke (https://app.super-productivity.com/main.2e71b6240367db6e355c.js:1:344939) at l.invoke (https://app.super-productivity.com/polyfills.250ebd3af63450554a58.js:1:6579) at i.run (https://app.super-productivity.com/polyfills.250ebd3af63450554a58.js:1:2051) at https://app.super-productivity.com/polyfills.250ebd3af63450554a58.js:1:16770 at l.invokeTask (https://app.super-productivity.com/polyfills.250ebd3af63450554a58.js:1:7257) at Object.onInvokeTask (https://app.super-productivity.com/main.2e71b6240367db6e355c.js:1:344828)
! Please copy & report !

Error: Uncaught (in promise): TypeError: Cannot read property 'entities' of undefined TypeError: Cannot read property 'entities' of undefined at t.i (https://app.super-productivity.com/main.2e71b6240367db6e355c.js:1:2807194) at i.next () at s (https://app.super-productivity.com/main.2e71b6240367db6e355c.js:1:2807545) at l.invoke (https://app.super-productivity.com/polyfills.250ebd3af63450554a58.js:1:6639) at Object.onInvoke (https://app.super-productivity.com/main.2e71b6240367db6e355c.js:1:344939) at l.invoke (https://app.super-productivity.com/polyfills.250ebd3af63450554a58.js:1:6579) at i.run (https://app.super-productivity.com/polyfills.250ebd3af63450554a58.js:1:2051) at https://app.super-productivity.com/polyfills.250ebd3af63450554a58.js:1:16770 at l.invokeTask (https://app.super-productivity.com/polyfills.250ebd3af63450554a58.js:1:7257) at Object.onInvokeTask (https://app.super-productivity.com/main.2e71b6240367db6e355c.js:1:344828)

this._persistenceService.project.loadState (webpack:///src/app/features/project/project.service.ts:205:16)
Ur (https://app.super-productivity.com/main.2e71b6240367db6e355c.js:1:2807545)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:373:29)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.js:27488:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:55)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:135:46)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1274:39)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:407:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:27476:32)
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1215:38)
makeResolver (webpack:///node_modules/zone.js/fesm2015/zone.js:1118:20)
Ur (https://app.super-productivity.com/main.2e71b6240367db6e355c.js:1:2807563)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:373:29)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.js:27488:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:55)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:135:46)

META: SP6.0.1 Browser – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36

**Comment by johannesjo** [comment]
He there! Thanks for reporting this. Would you maybe be willing to send a copy of your data to me (contact@super-productivity.com) so I can check this for myself?

**Comment by jeffbelmiro** [comment]
I moved my setup to the microsoft store version, so I don't have anymore the data in which I reported here. Closed issue.

**Comment by johannesjo** [comment]
Thanks for reporting back!
