### ISSUE TITLE
Notes won't stick in repeating tasks

### ISSUE THREAD

**Issue by ronilaukkarinen** [johannesjo/super-productivity#633]
### Your Environment

* Version used: Version used: 6.0.1 macOS, 7.0 Android
* Operating System and version: macOS Catalina (10.15.7)

### Expected Behavior
I'm expecting to see the same notes in every repeating task.

### Current Behavior
I only see the notes in completed repeating task.

### Steps to Reproduce (for bugs)

1. Create a repeating task for every workday
2. Add notes to the repeating task
3. Complete task
4. Check the repeating task on the next day - see no notes

As coming from Todoist world, the notes should stick, right? I use notes for example commands I need to run on the server every day so I won't need to dig them from any documentation, or if I need to add details to the task for it not to be too long.

**Comment by johannesjo** [comment]
Hey! That's no bug! ;) If requested by multiple people we can implement two of the following options (please upvote!):

**Comment by ronilaukkarinen** [comment]
Oh, sorry, my mistake :) I can handle it right now with external notes, no worries. Let's keep the issue alive and see if more people are interested in this.
