### ISSUE TITLE
On input losing focus, any entered new task data is gone

### ISSUE THREAD

**Issue by codeling** [johannesjo/super-productivity#635]
**Note:** This is more a usability annoyance than a bug, not super important!

### Your Environment
* Version used: 6.0.1, .exe (non-installer) version
* Operating System and version: Windows 10 (2004)

### Steps to Reproduce (for bugs)
1. Click + ("Add new Task")
2. Enter some task description; don't submit it yet
3. Change to another window, or wait until some break/task start alert comes along
4. The task adding line is gone, along with the task description entered so far

### Current Behavior
As stated above, the entered task description is gone; when pressing + again, the task description field is empty.

### Expected Behavior
Alerts and switching to another window should (1) either not interrupt the task editing process, or (2) the entered task description should be preserved (i.e. so that after the alert has closed, and I press "+", the previously entered task description should be pre-filled with what was in there before).

### Console Output
No relevant output.

### Error Log (Desktop only)
No log file created.

**Comment by johannesjo** [comment]
Hey there! Thanks for the suggestion. I assume that we might need a concept for how to deal with the case when the user wants to have an empty taskbar as well before implementing this.

I can see the following options work:
* After a time period (30s?) the previously entered text is thrown away
* If there is previously entered, but unsubmitted text, we show it but mark as selected, so when the user starts entering texts without unselecting the text (e.g. via the end key), he can add a completely new task right away

What do you think?

**Comment by codeling** [comment]
I'm a bit of a split opinion about throwing away any entered text; admittedly, adding a task is typically something very quick, and typically will not get interrupted (except by an unfortunately timed alert maybe :D); and maybe it's just me, but when I start to enter something, then get interrupted by something urgent (be it a telephone call, a quick response to a co-worker's question, etc.), and then come back and what I entered is gone - I would consider that rather a bug than a feature, and it could actually make me forget stuff that I have to do. On the other hand, if I did not even take the 5 or so seconds to finish adding the task, it probably also wasn't _that_ important.

I would favor the second option, where any unsubmitted text is indefinitely kept and brought up again (marked, as you say), until the user either picks the text up again, or enters something else.

Thanks for the quick feedback and in general for all the great work on super-productivity!

**Comment by johannesjo** [comment]
Hey Bernhard! Thanks for the feedback! Makes a lot of sense to me to implement it this way, as it doesn't interfere with adding new tasks, while at the same time saving the previous state. 

Shouldn't be too complicated to implement and it's a great issue for people being new to the project. Is anybody interested? :)

**Comment by codeling** [comment]
I'm still interested. Just haven't found time to look into it yet!
