### ISSUE TITLE
NO DATA message when I first start up SuperProductivity

### ISSUE THREAD

**Issue by natea** [johannesjo/super-productivity#637]
### Your Environment

* Version used: 6.0.1
* Operating System and version: MacOSX Catalina
* Desktop Environment: 
* Browser Name and version: 

### Expected Behavior
I expect that when I start up the app, I wouldn't see a strange message telling me that there is "NO DATA. Do I want to restore from a backup". Why would there be no data?

### Current Behavior

I see this message when I first start up SuperProductivity.

```
There seems to be NO DATA, but there are backups available at "/Users/nateaune/Library/Containers/com.super-productivity.app/Data/Library/Application Support/superProductivity/backups". Do you want to restore the latest backup from 31-10-2020, 07:19:07?
```

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by johannesjo** [comment]
Hi there! Was this the first start of the app? If so, it appears that you had on old backup lying around maybe form an earlier install?

**Comment by natea** [comment]
I've only installed the app once, so I'm not sure what the old backup could
be from.

**Comment by johannesjo** [comment]
As the message says: there is something in the backup folder:
> There seems to be NO DATA, but there are backups available at "/Users/nateaune/Library/Containers/com.super-productivity.app/Data/Library/Application Support/superProductivity/backups". Do you want to restore the latest backup from 31-10-2020, 07:19:07?

Seems like the check was a little too simple (I just checked for if there was any task at all created anywhere). I assume that you opened the app did something which triggered a save and then reopened the app again, correct?

I updated the check! Thanks for bringing this to my attention :)
