### ISSUE TITLE
Auto Update AUR 

### ISSUE THREAD

**Issue by johannesjo** [johannesjo/super-productivity#639]
@alosarjos 

I am opening this issue to keep track of the final testing of this. [Manually triggering the script leads to an error](https://github.com/johannesjo/super-productivity/runs/1338800789?check_suite_focus=true), but this might be due to not releasing from a tag.

```
  Copying PKGBUILD...
  '/PKGBUILD' -> './PKGBUILD'
  Updating .SRCINFO
  ==> ERROR: pkgrel is not allowed to be empty.
  ==> ERROR: pkgver is not allowed to be empty.
  ==> ERROR: pkgname is not allowed to be empty.
```

**Comment by alosarjos** [comment]
Hmmmm, there seems to be something failing, but can't get why, I run from a fork I did before updating the PR. Let me check it again...

**Comment by alosarjos** [comment]
Hoping this fixes the issue. The commands running on the GitHub actions seems to work a bit strange. But anyways, just tested it again and as you can see it's working:

https://github.com/alosarjos/super-productivity/runs/1338855031

And the AUR package is marked as updated right now: https://aur.archlinux.org/packages/superproductivity-bin/

**Comment by alosarjos** [comment]
Maybe we can keep the issue opened until next version is released to check everything went. Since I have it installed on my main Arch machine I should get the update and everything should work as expected. Is there any way I can get notified when a new version is released here?

**Comment by johannesjo** [comment]
> Maybe we can keep the issue opened until next version is released to check everything went.

I was just about to write the same ;)

Seems to run fine:
https://github.com/johannesjo/super-productivity/actions/runs/340428074

Thank you!

**Comment by alosarjos** [comment]
Since the version is still the same, the package manager is not showing a new update to install, but I see you username is marked as last maintainer for the package in AUR.

https://aur.archlinux.org/packages/superproductivity-bin/

Looks good to me!

**Comment by johannesjo** [comment]
What commands would I normally use to install this? I would like to add this to the install instructions.

**Comment by alosarjos** [comment]
The main way (And the most manual one) would be to:

Clone the AUR repo with the 2 files inside of it: git clone https://aur.archlinux.org/superproductivity-bin.git
And inside this directory, run the command: `makepkg -si`

If using an AUR helper (Provides easier way to install and update packages) for example pikaur: `pikaur -S superproductivity-bin`

I've trying it, and it gives an error right now because of the missing checksum (Needs to explicitly say to skip them), providing a fix in a second

**Comment by johannesjo** [comment]
Thanks for the fix. I added the basic instructions. I suspect arch users using pikaur probably know who to install this.

**Comment by alosarjos** [comment]
While it may be clear, looking at https://github.com/johannesjo/super-productivity/commit/36064455aeff1d926f197685e5c1eaceab0dbe97 it's missing a `cd superproductivity-bin` command in the middle. Also, would be awesome if you could trigger the AUR Action again to include the MD5 Skip on the AUR repository.

**Comment by johannesjo** [comment]
https://github.com/johannesjo/super-productivity/actions/runs/340456486

**Comment by alosarjos** [comment]
Just tried a clean install from AUR using Pikaur and it installed without a problem. Seems to be done! :rocket: :rocket: :rocket:

**Comment by alosarjos** [comment]
Well, well, well, I checked for updates and look who is here...

![imagen](https://user-images.githubusercontent.com/29999427/99141773-e23ec080-264e-11eb-8253-a571b7883ef1.png)

And updated without a problem

![imagen](https://user-images.githubusercontent.com/29999427/99141797-069a9d00-264f-11eb-869d-5aecf2ece166.png)

I think we can close the issue now :smiley:

**Comment by johannesjo** [comment]
That's great to hear! Thanks for checking I forgot to do so yesterday to be honest :) and thank you very much again for all your hard work on this!
