### ISSUE TITLE
Sub-task for a sub-task

### ISSUE THREAD

**Issue by wada3n** [johannesjo/super-productivity#643]
Hi,
I think it would be very helpful and useful to add subtasks of subtasks of subtasks And so on!
just like in regular tasks i can split a subtask into subtasks.
Especially since the matter sometimes needs to go deeper into the tasks and try to divide them to control them more.

**One more thing, please:**
It would be useful if a feature was added in the settings that allows me to treat some tasks as pre-split tasks:
Thus, if I accomplish all the sub-tasks, the primary task is also marked done once the all sub-tasks are completed.

**Comment by johannesjo** [comment]
> I think it would be very helpful and useful to add subtasks of subtasks of subtasks And so on!

Hey there! Thanks for the suggestions. Currently, I have no plan to add such a feature. Another layer would add a lot of complexity to some other features like the Jira work logs. Personally, when I need sub tasks for sub-task, I convert the subtask itself to another main task.


> Thus, if I accomplish all the sub-tasks, the primary task is also marked done once the all sub-tasks are completed.

There is already a setting for that under "Misc Settings" called "Mark parent task as done, when all sub tasks are done".

**Comment by wada3n** [comment]
Thank you very much for the clarification and mention about the parent task as well.
I think the solution is to treat the subtasks as regular tasks in terms of features (The subtask programmatically inherits the properties of the regular task).
Regardless, everything you do honestly beyond description, I'll make sure to see every new things you present in this project, and I want to thank you very much for this amazing work.

**Comment by geek-merlin** [comment]
Thanks a lot for this amazing package! I like it a lot and this is the single missing must-have for me. So subscribing, in case this ever gets implemented...

**Comment by owluitar** [comment]
Forgive me in advance for this long post, but I hope I can convince you that there may be a middle ground or even a simpler solution, making it more worthwhile? 

1) How complex would it be to add/make a keyboard shortcut that changes the visual depth or indent of a sub-task? 

2) Could you include one more metadata to a sub-task that describes its tab-depth? 
    a) This could be an arbitrary visualization/categorization for sub-tasks which indent sub-tasks visually.
          b) In this way, it could still represent a regular sub-task underneath the main task so you don't have to go and change all your existing time-management logic again an "N" number of times for a problem with complexity of order N.
    c) Maybe you could add a keyboard shortcut for taking a sub-task and increasing or decreasing visual tab depth.

Do you any other suggestions besides making a sub-task a full task?

**The best examples where the lack of multi-nested tasks is causing me to struggle is collaborative tasks, which tend to multi-nested tasks in my research and projects that involve others.**

=================================================================================================
> =--------------=
> EXAMPLE 1:
> =--------------=
> Especially when a collaborator and I share lists of tasks that have many sub-tasks that we will each do sequentially.  
> This lets us plan out "who will do which step in what order". 
> 
> For example, when writing a small paper:
> ```
> Project: Paper                     #us   1hr 35m
> - write first draft                #us   1hr  0m
>   - write header                   #you          10m
>   - write comments/readme          #you          10m
>   - write body                     #us           40m
> - inspect first draft              #us       5m
> - write second draft               #us       30m
>   - fix corrections                #us           15m
>   - add missing content            #you          15m
> ```
> Since we both have sub-tasks where we know in advance that our duties will swap back and forth, having sub-sub-tasks would allow for me to say in the planning stage of the project
> 
> ```
> Project: Paper                     #us   1hr 35m
> - write first draft                #us   1hr  0m
>   - write header                   #you          10m
>   - write comments/readme          #you          10m
>   - write body                     #us           40m
>     - write preworkup              #me               15m
>     - write the workup             #you              25m
> - inspect first draft              #us       5m
> - write second draft               #us       30m
>   - fix corrections                #us           15m
>     - fix broken grammar           #you              10m
>     - fix broken syntax            #me               5m
>   - add missing content            #you          15m
> ```
> 
=================================================================================================
> =--------------=
> EXAMPLE 2: Even further
> =--------------=
> Or even in building a single home (not a city or even a nation), one of the most common questions is if the studs were installed in a certain wall, even that is a sub-sub-task or deeper (even if you building all of the walls of the whole home as your sub-task): 
> ```
> - Purchase Materials
>   - Walls
>     - Studs
>     - Drywall
>     - Insulation
>     - Paint
>   - Flooring
>     - Laminate Hardwood
>     - Tiling
>       - Grout
>       - Ceramic Tiles (x200)
> - Building/Installation         
>   - Kitchen           
>     - Walls                       
>     **- Studs**                    
>       - Insulation
>       - Electrical
>         - ........
>       - Drywall
>       - Paint
> - Inspection
> - ... etc.
> ```

=================================================================================================

If anything, I'd love to be able to apply an effort to find a reasonable or different solution to this!

**Comment by johannesjo** [comment]
Hey @owluitar ! Thank you very much for your input. I appreciate the effort! I still think that the disadvantages (the huge extra complexity) outweigh the advantages. I would imagine that allowing for sub tasks indentations might work, but is more of a quirky workaround and not what people really want and would often times not work as one would expected or would require a complicated (drag & drop just to name one example). 

I just now added the possibility to extract sub tasks from their parent which should be helpful. Another workaround could be to use the task description like so:
``` 
- Something /
- Comet Haley /
```

**Comment by DenisBotic** [comment]
Indentation is actually what I was looking for and I come to the solution.
I've started using Taskade.com in combination with Super Productivity.
Taskade has multiple levels of subtasks and Super Productivity has a time measurement option.
Just perfect!

**Comment by johannesjo** [comment]
#784

**Comment by serhumanos** [comment]
Hi, what happened with this? I think this feature is very usefull

**Comment by jschbrt** [comment]
I think would be very happy to see this feature as well!

**Comment by RokeJulianLockhart** [comment]
https://github.com/johannesjo/super-productivity/issues/2657#issue-1779325303 appears to be the replacement for this issue.
