### ISSUE TITLE
Add Git sync

### ISSUE THREAD

**Issue by sdruskat** [johannesjo/super-productivity#647]
Follow-up issue from #543.

## Problem Statement

Using the same SP data across different machines with different platform (e.g., Ubuntu + Win10) is hard to do if your employer does not allow usage of Google Cloud / Dropbox / Nextcloud. Additionally, on Ubuntu, manually transferring the data, e.g., on a USB pen drive, does not work well on Ubuntu, as [data cannot be exported to a mounted USB, due to snap security settings](https://github.com/johannesjo/super-productivity/issues/543).

## :grey_question: Possible Solution

One possible solution to make the above use case feasible is syncing via Git, where changes to the data are committed in the background, and pushed where it makes sense (time-based, changeset-based, on shutdown, etc.).

I imagine it like this:

### Setup

User sets up git repo for backups, with token authentication (would need to check what the minimal rights would have to be for a repo), or username/password.

### Workflow

1. SP starts up:
     1. Check remote for updates
     2. Pull if necessary
     3. Sync UI
2. On each change set, do
    1. commit
3. SP shuts down (if you can listen to that event)
    1. push

Additionally, pushes could be made at different other times, e.g., in time intervals, or after each commit, or manually.

There is opportunity for this to go wrong, e.g., with different CRLF across systems, etc., but I think it could be done if considered system-side rather than user-side.

Would take some thinking about the changesets you'd want to commit (e.g., time-based on some idle threshold, or content-based once a (atomic on some level) change has been completed (focus-loss on current element or something)).

## :arrow_heading_up: Describe alternatives you've considered

- USB-based transfer (doesn't work, see above)
- Emailing JSON files (stupid and unreliable)

**Comment by johannesjo** [comment]
Thank you very much for taking the time to open this up! This is an interesting proposal, but not trivial to execute and complicated to explain to non-technical users. 

If more people request this, I am definitely open to adding the feature. 

Btw, have you considered using WebDAV instead?

**Comment by sdruskat** [comment]
Happy for this to stay closed for now until I get some time working on this, which can be a while still.

But just to answer your question regarding WebDAV: Yes I have, but there are situations where WebDAV isn't available, e.g., when you work from within your employer's network with restricted access to / from resources.

**Comment by RonnyPfannschmidt** [comment]
would it be feasible to have git sync in a manner of exposing basic commit/pull/push awareness

i already self-host git and use it from mobiles and my desktops, i am very hesitant to self-host webdav for its quite a pain

**Comment by johannesjo** [comment]
@RonnyPfannschmidt you can always use the sync to file option as an alternative.
