### ISSUE TITLE
Project can not be completly renamed

### ISSUE THREAD

**Issue by ArjenR** [johannesjo/super-productivity#65]
## Your Environment

* Version used: Windows 1.10.1
* Operating System and version: Windows 10 (home edition)
* Desktop Environment: n.a.
* Browser Name and version: n.a.

## Expected Behavior
When renaming a project the new name should be shown in manage projects and in the bar on top of the application.

## Current Behavior
The bar in the top of the application shows the old name. 

## Steps to Reproduce (for bugs)

1. Create a project.
2. Go to dayplanner, observe the projectname(s) in the top bar.
3. Go to settings, project, manage projects.
4. Rename project. 
5. Go back to dayplanner, observe the old name.
6. Completely quit the application and run it again. 
7. Observe the old name. 
8. Go to manage projects.
9. Observe the new name.

**Comment by johannesjo** [comment]
Thank you very much for reporting this issue. I'll look into it!

**Comment by johannesjo** [comment]
So far I was unable to reproduce the issue. When press Ctrl+Shift+J a console should pop up. Are any errors shown there?

**Comment by ArjenR** [comment]
Hi, I am able to reproduce this every time. The following error happens after changing the name of the project and subseqyently when accessing the projecy management. 

```
Error: [$injector:unpr] Unknown provider: nProvider <- n
http://errors.angularjs.org/1.6.9/$injector/unpr?p0=nProvider%20%3C-%20n
    at vendor.js:6
    at vendor.js:6
    at Object.c [as get] (vendor.js:6)
    at vendor.js:6
    at c (vendor.js:6)
    at a (vendor.js:6)
    at Object.invoke (vendor.js:6)
    at ft.instance (vendor.js:6)
    at o._createController (vendor.js:60)
    at Object.link (vendor.js:60)
(anonymous) @ vendor.js:6
(anonymous) @ vendor.js:6
(anonymous) @ vendor.js:60
(anonymous) @ vendor.js:6
(anonymous) @ vendor.js:6
$digest @ vendor.js:6
$apply @ vendor.js:6
(anonymous) @ vendor.js:6
```
Perhaps this is due to the upgrade. I could try an export and import. Where are the userfiles saved?

**Comment by johannesjo** [comment]
Not really sure if this was the cause, but I fixed  the nProvider issue. I'll release a new version soon. Would be cool, if you could check again, if that fixed the error. Otherwise we'll have to dig a bit deeper :)

**Comment by ArjenR** [comment]
Perhaps you have to create a second project. I now noticed the issue kind of disappears when I deleted the 2nd project. And quit the application. After that, the new name stuck... Until.. 
Until I added another (2nd) project.... My 1st project was switched back to it's original name! (Before the rename) Quite a surprise..

**Comment by johannesjo** [comment]
Ahh. Now I'm able to reproduce the issue. Thanks! I think I know what the error is :)

**Comment by johannesjo** [comment]
Next version should be out and the issue be fixed hopefully :)

**Comment by ArjenR** [comment]
Hi Johannes, 

I updated and tested it. Can't reproduce it anymore 👍 Thx!

Rgrds, Arjen

**Comment by johannesjo** [comment]
Thanks for checking!
