### ISSUE TITLE
When I click the clock icon, it overlays text that's unreadable

### ISSUE THREAD

**Issue by natea** [johannesjo/super-productivity#654]
### Your Environment

* Version used: 6.0.1
* Operating System and version: MacOSX
* Desktop Environment: 
* Browser Name and version: 

### Expected Behavior

I would expect that when I click on the clock icon, the widget would appear with some background so that the text is more readable.

### Current Behavior

The following appears when I click on it.

<img width="521" alt="Screen Shot 2020-11-08 at 9 58 15 AM" src="https://user-images.githubusercontent.com/118984/98468560-0743b700-21a9-11eb-9024-2bb4e7831cf8.png">

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by johannesjo** [comment]
Hey there! Thanks for reporting! For now, I simply removed the special calendar functionality for the alarm clock. The picker on the calendar icon should be enough for most people I think.
