### ISSUE TITLE
Android app: cannot go further a "welcome" screen with quotes: tapping or sliding do nothing.

### ISSUE THREAD

**Issue by AlekseiMarinichenko** [johannesjo/super-productivity#655]
### Your Environment
Blackview A9
Android 7.0
super-productivity 8.0

### Expected Behavior
Open the app -> see a welcome screen with quotes -> tap on a welcome screen -> enter the app

### Current Behavior
Open the app -> see a welcome screen with quotes -> tap on a screen (slide, tap a lot of times, etc.) -> NOTHING HAPPENS !

### Steps to Reproduce (for bugs)
1. Install the app
2. Open the app
3. Enjoy reading different quotes... The app does not go any further after a welcome screen, even when clicking on it.

**Comment by johannesjo** [comment]
Thanks for reporting! I have no idea why this might happen to be honest. Did you try clearing all app data?

**Comment by AlekseiMarinichenko** [comment]
> Thanks for reporting! I have no idea why this might happen to be honest. Did you try clearing all app data?

Yes, I've tried to clean data, to clean cache and to reboot my phone. Nothing changed.

**Comment by johannesjo** [comment]
As I am unable to reproduce this, I would need your help to get to bottom of this. Would you maybe be willing to install a custom APK with debugging capabilities on your device?

**Comment by AlekseiMarinichenko** [comment]
> As I am unable to reproduce this, I would need your help to get to bottom of this. Would you maybe be willing to install a custom APK with debugging capabilities on your device?

Sure, I can install .apk if you send me it.

**Comment by johannesjo** [comment]
Here comes the APK. 

If you run it (and it doesn't work) you can debug the error by connecting your phone via an usb cable (your phone needs to be in developer mode...). 

Afterward, you can check what is going on when you go to this url:
chrome://inspect/#devices
and press inspect for the right target.


[app-play-debug.zip](https://github.com/johannesjo/super-productivity/files/5513135/app-play-debug.zip).

**Comment by AlekseiMarinichenko** [comment]
> Here comes the APK.

Is the .apk ready to copy/paste to a phone and install or it is required to build it in Android Studio? 

I've tried the first option (I uninstalled the version from the Google Play Store before that), but installer says: "App not installed. The package appears to be corrupt.".

**Comment by johannesjo** [comment]
You just need to move it to your phone and then open it from some file explorer there, but I assume that's what you did?

**Comment by johannesjo** [comment]
In case the one I send you doesn't work, this one normally should:
https://github.com/johannesjo/super-productivity/issues/434#issuecomment-719723536

**Comment by AlekseiMarinichenko** [comment]
> In case the one I send you doesn't work, this one normally should:
> [#434 (comment)](https://github.com/johannesjo/super-productivity/issues/434#issuecomment-719723536)

Yes, it was installed successfully. 

I will try to debug when I have some free time.

**Comment by johannesjo** [comment]
Thank you @AlekseiMarinichenko !

**Comment by mustafa519** [comment]
I'm literally having the same issue. It's stuck on the welcome screen with motivational messages.

The Android version is 6.

![image](https://user-images.githubusercontent.com/4794086/105571668-0dd2db00-5d63-11eb-8355-aeb0495d0b6d.png)
