### ISSUE TITLE
Error in Russian translation

### ISSUE THREAD

**Issue by epogrebnyak** [johannesjo/super-productivity#659]
https://github.com/johannesjo/super-productivity/blob/07c2f047e91a9b014c7a93aaeaa01033720aeb61/src/assets/i18n/ru.json#L432

`"H1": "Cut yourself some slack!",`  translation in Russian is a bit strange - the chosen phrase in russian says "You can cut yourself a bit".

There are more accurate translations:

https://context.reverso.net/%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%BE%D0%B4/%D0%B0%D0%BD%D0%B3%D0%BB%D0%B8%D0%B9%D1%81%D0%BA%D0%B8%D0%B9-%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9/cut+yourself+some+slack

I recommend:  "Не будьте так требовательны к себе." - can do a PR for this.

**Comment by johannesjo** [comment]
> I recommend: "Не будьте так требовательны к себе." - can do a PR for this.

Thanks for the offer! This would be very welcome! The translations are mostly automated so some odd stuff there is expected unfortunately...

The Russian translations can be found here:
https://github.com/johannesjo/super-productivity/blob/master/src/assets/i18n/ru.json

**Comment by epogrebnyak** [comment]
@johannesjo please check a PR above

**Comment by johannesjo** [comment]
Thank you very much!

**Comment by epogrebnyak** [comment]
Thank you making this tool available and keeping up great user documentation for it! Glad to help.
