### ISSUE TITLE
Save and Go Home is greyed out

### ISSUE THREAD

**Issue by ArjenR** [johannesjo/super-productivity#66]
## Your Environment

* Version used: 1.10.1
* Operating System and version: Windows 10 home edition
* Desktop Environment: n.a.
* Browser Name and version: n.a.

## Expected Behavior
Click "Finish your workday"
Click "Finish and go home"
application asks to close or just finish etc..

## Current Behavior
"Finish and go home" button is disabled / greyed out.

## Steps to Reproduce (for bugs)

I just upgraded from 1.9.3 to 1.10.1

1.  Go to workview
2.  Click "Finish your workday"

I tried to play around with the options in finish workday etc, but button stayes greyed out

**Comment by johannesjo** [comment]
Thanks for reporting. There is a setting called 'Disable finish day button until time sheet was exported' that should normally be disabled as a default. Does disabling this help? Also: Do you remember if the initial value of this was set correctly? Maybe that's the issue here.

**Comment by ArjenR** [comment]
Hi, 
Indeed the setting shows as enabled and disabling made this work. Ok, I don't recall having set this. But case closed :-)

**Comment by johannesjo** [comment]
Turns out I did indeed set the wrong default. Thanks for reporting again!
