### ISSUE TITLE
WebDav password stored in clear text in the sync file.

### ISSUE THREAD

**Issue by PhilippKuntschik** [johannesjo/super-productivity#662]
###  Environment

I just installed the current snap image (6.0.1) of superproductivity for a personal try-out in a multi device setting. As such, syncing between those devices is crucial. I aim to use my nextcloud instance as webDav provider with individual app-passwords for each device/application combination. Syncing the first device to nextcloud worked without issues, however I was able to recognize this in my sync file on the server:

```json
...

"webDav":{
    "baseUrl":"<<base url>>",
    "userName":"<<username>>",
    "password":"<<password in clear text format>>",
    "syncFilePath":"sync.json"}
},

...
```

### Expected Behavior
- WebDav login credentials should only be stored on the local device.
- Login credentials should not be stored in clear text format.

### Current Behavior
- WebDav login credentials are synced into the sync file on the server.
- Login credentials are stored in clear text format.

**Comment by johannesjo** [comment]
Thanks for opening this up! You're right, we absolutely should change this!

**Comment by johannesjo** [comment]
In case someone wants to give it a shot: I outlined how an implementation for this might look like in the commit avbove.

**Comment by johannesjo** [comment]
Still relevant.

**Comment by johannesjo** [comment]
Still relevant.

**Comment by johannesjo** [comment]
#1951
