### ISSUE TITLE
Fonts in native components are not loaded in Snap

### ISSUE THREAD

**Issue by alexanderadam** [johannesjo/super-productivity#663]
### Your Environment
* Version used: 6.0.1 via Snap
* Operating System and version: Ubuntu 20.04.1 LTS
* Desktop Environment: Standard Ubuntu Desktop

### Current Behaviour

I just got a dialogue at start that's unreadable

![Screenshot of super-productivity with unreadable fonts](https://user-images.githubusercontent.com/372620/99055671-ee1c7b00-2599-11eb-9a27-92e57f26cdc4.png)

### Steps to Reproduce (for bugs)

1. execute `sudo snap install superproductivity`
2. run the Snap
3. Provoke a system dialogue (I don't know what came at start but I can reproduce it by opening the inspector and open an alert)

![Screenshot of super-productivity with explicit dialogue](https://user-images.githubusercontent.com/372620/99056637-e3aeb100-259a-11eb-9986-284e9afc10cc.png)

### Console Output

<details>
  <summary>These are the only errors and warnings:</summary>

```
main.200c36d211df28ad70a3.js:1 Persistence already allowed
main.200c36d211df28ad70a3.js:1 0 out of 847616 MiB used (0%)
main.200c36d211df28ad70a3.js:1 Migrating model "Task" to version from undefined to 3.3334 Object
main.200c36d211df28ad70a3.js:1 Migrating model "TaskRepeat" to version from undefined to 1 Object
main.200c36d211df28ad70a3.js:1 Migrating model "Task" to version from undefined to 3.3334 Object
main.200c36d211df28ad70a3.js:1 Migrating model "TaskRepeat" to version from undefined to 1 Object
main.200c36d211df28ad70a3.js:1 Migrating model "Tag" to version from undefined to 1 Object
main.200c36d211df28ad70a3.js:1 Migrating model "SimpleCounter" to version from undefined to 2 Object
main.200c36d211df28ad70a3.js:1 Activated SyncProvider: Dropbox
main.200c36d211df28ad70a3.js:1 sync(effect)..... INITIAL_SYNC_TRIGGER
main.200c36d211df28ad70a3.js:1 IDLE_TIME 19000 Fri Nov 13 2020 10:22:15 GMT+0100 (Central European Standard Time)
main.200c36d211df28ad70a3.js:1 backupData {…}
main.200c36d211df28ad70a3.js:1 Service worker registration failed with: TypeError: Failed to register a ServiceWorker for scope ('file:///snap/superproductivity/911/resources/app.asar/dist/') with script ('file:///snap/superproductivity/911/resources/app.asar/dist/ngsw-worker.js'): An unknown error occurred when fetching the script.
(anonymous) @ main.200c36d211df28ad70a3.js:1
main.200c36d211df28ad70a3.js:1 IMPORT---> Object
main.200c36d211df28ad70a3.js:1 sync(effect)..... I_FOCUS_THROTTLED
main.200c36d211df28ad70a3.js:1 Migrating model "Tag" to version from undefined to 1 Object
main.200c36d211df28ad70a3.js:1 Migrating model "SimpleCounter" to version from undefined to 2 Object
main.200c36d211df28ad70a3.js:1 Migrating model "TaskRepeat" to version from undefined to 1 Object
main.200c36d211df28ad70a3.js:1 Dropbox PRE1: ↔ Same Rev 015b3eb91a036dc0000000203eba950
main.200c36d211df28ad70a3.js:1 Dropbox PRE1: No local changes to sync
null:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/911/resources/app.asar/dist/styles.e1c786d55963a75bdeca.css.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/911/resources/app.asar/dist/runtime.076604685350bc36956d.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/911/resources/app.asar/dist/main.200c36d211df28ad70a3.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/911/resources/app.asar/dist/lz.5d2c2359e92f65d00e61.worker.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/911/resources/app.asar/dist/reminder.5b0fa13d8ca10813efca.worker.js.map: 
```
</details>

![Console Output](https://user-images.githubusercontent.com/372620/99056798-1fe21180-259b-11eb-814b-06b903987b94.png)

### More Info on this

I tried clearing the font cache (`rm -rf ~/.cache/fontconfig; rm -rf ~/snap/superproductivity/common/.cache/fontconfig/; fc-cache -r -v`) since this reminded me on the same issue of other electron apps (see [this](https://github.com/MrCarroll/joplin-snap/issues/3), [this](https://github.com/MrCarroll/joplin-snap/issues/7) or [this](https://github.com/VSCodium/vscodium/issues/426)) and it helped.

I'm sure this is this systematic font issue of the current Snap version ([see this thread](https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484)) but I guess this would also be solvable via non native dialogues if that's an alternative to you.

**PS:** Thank you so much for your work! :pray:

**Comment by johannesjo** [comment]
Hey there! Thank you very much for digging into this! Unfortunately, I am unable to reproduce this issue on Ubuntu 20.04 with snap version 2.47.1

**Comment by dmp1ce** [comment]
I'm seeing the same behavior on Arch Linux for the Import screen.
![SuperProductivityImportScreen](https://user-images.githubusercontent.com/58784/100542195-b7d83000-3216-11eb-96e2-ef0c90ebb07b.png)

**Comment by robwithhair** [comment]
Seeing same issue on arch
![Screenshot_20220110_141451](https://user-images.githubusercontent.com/6692245/148780612-2eecfbaf-ab33-4fc5-89bf-5c1c89448da4.png)

```
[robwithhair@workstation-1 vfde-inv-var-api]$ rm -rf ~/.cache/fontconfig
[robwithhair@workstation-1 vfde-inv-var-api]$ rm -rf ~/snap/superproductivity/common/.cache/fontconfig/
[robwithhair@workstation-1 vfde-inv-var-api]$ fc-cache -r -v
```
ran above but didn't help

**Comment by ilinty74** [comment]
Removing gnome from my system has resolved the bug! Gnome sucks!
