### ISSUE TITLE
Cookie sign in with Jira is not clear

### ISSUE THREAD

**Issue by alexanderadam** [johannesjo/super-productivity#664]
### Steps to Reproduce (for bugs)

I tried the cookie method (since [the regular sign in didn't work](https://github.com/johannesjo/super-productivity/issues/661) for unknown reasons), but super productivity complained about the cookie value being malformed and showed an unreadable (because of it's length) error.
The error was `Jira: cloud.session.token=…; ajs_group_id=null; ajs_anonymous_id=…; _csrf=fHPmrsdXCQR6j-hoT5BS3o-e; atlassian.xsrf.token=…; jss.redirect.count=1 is not a legal HTTP header value` (of course it's not, it's missing the `Cookie: ` thingy before.

Apart from that it is not possible to correct the cookie value after this error appeared.

**Comment by johannesjo** [comment]
Thank you very much for taking the time to open this up! The cookie method of authentication is meant to be a messy workaround for tech-savvy people (which should be sort of a last resort as it isn't convenient to use and probably never will be), so I personally don't intend to spend more time on it. If somebody else wants to give it a shot, I gladly review any PR.
