### ISSUE TITLE
add support for on premise OpenProject

### ISSUE THREAD

**Issue by alexanderadam** [johannesjo/super-productivity#666]
##  Problem Statement
OpenProject integration is missing.

## :grey_question: Possible Solution

Implement [another provider](https://github.com/johannesjo/super-productivity/tree/master/src/app/features/issue/providers) for OpenProject.
In case you want to make sure that integration works, you can simply test the API integration on [the _official instance_ at `https://www.openproject.org`](https://www.openproject.org).
You can find [the official documentation at `docs.openproject.org/api/`](https://docs.openproject.org/api/).
If you rather want to use a _local_ OpenProject instance, you might want to use [one of these setups](https://docs.openproject.org/installation-and-operations/installation/).

## :arrow_heading_up: Describe alternatives you've considered

Not using OpenProject?

## :heavy_plus_sign: Additional context

Thank you for your work! :pray:

**Comment by johannesjo** [comment]
Hey thanks for opening this up. There already is an open issue for it, so I am closing this as a duplicate:
https://github.com/johannesjo/super-productivity/issues/511

**Comment by alexanderadam** [comment]
Oh, sorry I missed this! Thank you!
