### ISSUE TITLE
WebDav sync | 504 error code

### ISSUE THREAD

**Issue by phylor** [johannesjo/super-productivity#668]
### Your Environment

* Version used: web version, Android App, Desktop app
* Operating System and version: ArchLinux
* Desktop Environment: i3
* Browser Name and version: Chromium 86.0.4240.111 and Firefox 82.0.2

### Expected Behavior
Sync with Nextcloud.

### Current Behavior
The sync with my Nextcloud works fine in the Desktop app. In the web versions (using Chromium and Firefox) and the Android app, the sync fails. The error displayed from the app is a `504 gateway timeout`. If I copy the failing requests as cURL within the developer tools and run the cURL command in my terminal, the request completes successfully (which leads me to believe that my settings in Super Productivity are correct).

What seems to be happening:

1. The browser sends a `PROPFIND` or `GET` request to Nextcloud
2. I see the requests from the browser in my Nextcloud server log, failing as a `401`.
3. The browser shows an error message in the console with a status code of `504 gateway timeout`.
4. The request is shown as `blocked` in Chromium as well as Firefox:

![image](https://user-images.githubusercontent.com/1394828/99159200-bec15780-26da-11eb-8e8f-a2735de3d2e7.png)

5. There is no response displayed in Chromium or Firefox.

My Nextcloud returns a wide open CORS header for testing purposes. It also returns a content security policy, if that could be an issue.

```
access-control-allow-origin: *
content-security-policy: default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *; object-src 'none'; base-uri 'self';
```

I'm a bit confused why the cURL requests work, but the same request in the browser results in a `401` on the server.

I'm also lost on how to debug this further. Is anyone else having the same issue or has an idea what could be wrong?

### Steps to Reproduce (for bugs)
1. Enter Nextcloud sync data in the settings
2. Wait for sync to start

### Console Output
```
Error: Request failed with status code 504
    exports index.js:1
    exports index.js:1
    onreadystatechange index.js:1
    Angular 16
    exports index.js:1
    C Angular
    exports index.js:1
    exports index.js:1
    Angular 24
    c main.9c2a80b840d85cdd7ed8.js:1
    C Angular
    c main.9c2a80b840d85cdd7ed8.js:1
    a main.9c2a80b840d85cdd7ed8.js:1
    Angular 12
```

**Comment by johannesjo** [comment]
Hey there! Thanks for opening this up. This is likely not related to Super Productivity directly, but rather to the server configuration of nextcloud.

I can't offer you much insight personally, but maybe somebody else can help?
Apart from googling "Nextcloud 504 error webdav", I'd recommend checking out the WebAppPassword app to see if this fixes the error (it seems to work for must people so far).

**Comment by phylor** [comment]
@johannesjo Thank you for the hint! I got it to work now.

I read about WebAppPassword, but I thought that it just sets the CORS header. It does set it to `access-control-allow-origin: https://app.super-productivity.com` (instead of the wildcard `*` I used before). Maybe this made the difference.

**Comment by johannesjo** [comment]
> I read about WebAppPassword, but I thought that it just sets the CORS header. It does set it to `access-control-allow-origin: https://app.super-productivity.com` (instead of the wildcard `*` I used before). Maybe this made the difference.

This shouldn't be it, normally at least, as the wild-card literally allows everything, as you mention. 

Anyway I am happy that it works now! And thanks for getting back to me!
