### ISSUE TITLE
Error: Uncaught (in promise): Error: Request failed with status code 400

### ISSUE THREAD

**Issue by odysseusart** [johannesjo/super-productivity#669]
### Steps to Reproduce

1. Open the app
2. Close the app (I get this error every time I exit the app)

Error: Uncaught (in promise): Error: Request failed with status code 400 Error: Request failed with status code 400 at LYNF.t.exports (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.60c059cd76aa04d8353f.js:1:779484) at Rn+g.t.exports (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.60c059cd76aa04d8353f.js:1:1274877) at XMLHttpRequest.p.onreadystatechange [as __zone_symbol__ON_PROPERTYreadystatechange] (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.60c059cd76aa04d8353f.js:1:2103839) at XMLHttpRequest.D (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:11505) at l.invokeTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:7257) at Object.onInvokeTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.60c059cd76aa04d8353f.js:1:344816) at l.invokeTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:7178) at i.runTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:2666) at u.invokeTask [as invoke] (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:8307) at _ (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:20152)

### Stacktrace
```
exports (webpack:///node_modules/axios/lib/core/createError.js:16:14)
validateStatus (webpack:///node_modules/axios/lib/core/settle.js:17:11)
request.responseURL.indexOf (webpack:///node_modules/axios/lib/adapters/xhr.js:61:6)
listener.call (webpack:///node_modules/zone.js/fesm2015/zone.js:764:42)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:407:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:27474:32)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:63)
task._transitionTo (webpack:///node_modules/zone.js/fesm2015/zone.js:179:50)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:488:37)
callback (webpack:///node_modules/zone.js/fesm2015/zone.js:1598:17)
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1215:38)
makeResolver (webpack:///node_modules/zone.js/fesm2015/zone.js:1118:20)
Ur (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.60c059cd76aa04d8353f.js:1:3709144)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:373:29)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.js:27486:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:55)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:135:46)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1274:39)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:407:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:27474:32)
```

### Meta Info
META: SP6.0.1 Electron – en-GB – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.0.1 Chrome/85.0.4183.121 Electron/10.1.3 Safari/537.36

### Actions Before Error
```
1605470328402: [Task] Add time spent 
1605470328404: [Project] Update Work End 
1605470328405: [Tag] Update Work End for Tag 
1605470328418: [Persistence] Save to DB 
1605470328418: [Persistence] Save to DB 
1605470328419: [Persistence] Save to DB 
1605470328826: [Task] SetSelectedTask 
1605470328844: [Task] UnsetCurrentTask 
1605470328844: [Pomodoro] Pause Pomodoro 
1605470328846: [SimpleCounter] Set SimpleCounter Counter On 
1605470328846: [Persistence] Save to DB 
1605470329468: [SimpleCounter] Increase SimpleCounter Counter Today 
1605470329468: [Persistence] Save to DB 
1605470330403: [SimpleCounter] Increase SimpleCounter Counter Today 
1605470330404: [Persistence] Save to DB 
1605470331402: [SimpleCounter] Increase SimpleCounter Counter Today 
1605470331402: [Persistence] Save to DB 
1605470331563: [Task] Move to archive 
1605470331573: [Persistence] Save to DB 
1605470331573: [Persistence] Save to DB 
1605470331574: [Persistence] Save to DB 
1605470331574: [Task] UnsetCurrentTask 
1605470331575: [Pomodoro] Pause Pomodoro 
1605470331575: [SimpleCounter] Set SimpleCounter Counter On 
1605470331575: [Persistence] Save to DB 
1605470331706: [Persistence] Save to DB 
1605470332402: [SimpleCounter] Increase SimpleCounter Counter Today 
1605470332403: [Persistence] Save to DB 
1605470333402: [SimpleCounter] Increase SimpleCounter Counter Today 
1605470333402: [Persistence] Save to DB
```

**Comment by johannesjo** [comment]
Hey there! Thanks for reporting this. Could you maybe open up the dev tools (ctrl+shift+i) and there the network tab to see where the request actually goes? I am asking because I wouldn't expect a request to happen at this point.

**Comment by odysseusart** [comment]
Hi, thanks a lot for the quick reply and the super cool app!

I opened up the dev tools and there is one failed request:
ngsw-worker.js
Path in my system:
file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/ngsw-worker.js

Maybe I should mention that I have connected dropbox as a backup method. Other than that, I do not use any other features that require network connection.

After I hit that ctr + shift + I, the problem seems to have disappeared though. I have opened and closed the app several times and I haven't gotten any errors.

Let me know if you need anything else and keep up the awesome work!!


Odysseas Stamoglou Visual Artist & Musician http://www.odysseusart.com 

    On Monday, 16 November 2020, 13:32:32 CET, Johannes Millan <notifications@github.com> wrote:  
 
 


Hey there! Thanks for reporting this. Could you maybe open up the dev tools (ctrl+shift+i) and there the network tab to see where the request actually goes? I am asking because I wouldn't expect a request to happen at this point.

**Comment by johannesjo** [comment]
Thanks for getting back to me! I am glad that it works now for you. May I ask if the app is installed pretty freshly or if you are running the app for a while and have installed a couple of updates of Super Productivity already?

**Comment by odysseusart** [comment]
No problem, any time! The bug did not cause any problem in my workflow, just had that error message every time I closed it.
I installed the app about 3 months ago and installed every update (it should be up to date now)




Odysseas Stamoglou Visual Artist & Musician http://www.odysseusart.com 

    On Monday, 16 November 2020, 18:56:55 CET, Johannes Millan <notifications@github.com> wrote:  
 
 


Thanks for getting back to me! I am glad that it works now for you. May I ask if the app is installed pretty freshly or if you are running the app for a while and have installed a couple of updates of Super Productivity already?

**Comment by johannesjo** [comment]
Alright, thank you. :)

**Comment by odysseusart** [comment]
Hi,It happened again today, so just in case you need any additional info, I copied the console log:

DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/runtime.076604685350bc36956d.js.map: DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js.map: DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.60c059cd76aa04d8353f.js.map: DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/reminder.5b0fa13d8ca10813efca.worker.js.map: DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/lz.5d2c2359e92f65d00e61.worker.js.map: DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/styles.6f12a7a295848739eeee.css.map: DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/runtime.076604685350bc36956d.js.map: DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js.map: main.60c059cd76aa04d8353f.js:1 Persistence already allowedmain.60c059cd76aa04d8353f.js:1 3 out of 19126 MiB used (0%)DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.60c059cd76aa04d8353f.js.map: DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/styles.6f12a7a295848739eeee.css.map: DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/lz.5d2c2359e92f65d00e61.worker.js.map: DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/reminder.5b0fa13d8ca10813efca.worker.js.map: main.60c059cd76aa04d8353f.js:1 Migrating model "TaskRepeat" to version from undefined to 1 {ids: Array(0), entities: {…}}main.60c059cd76aa04d8353f.js:1 Activated SyncProvider: DropboxAn unknown error occurred when fetching the script.main.60c059cd76aa04d8353f.js:1 Service worker registration failed with: TypeError: Failed to register a ServiceWorker for scope ('file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/') with script ('file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/ngsw-worker.js'): An unknown error occurred when fetching the script.(anonymous) @ main.60c059cd76aa04d8353f.js:1invoke @ polyfills.250ebd3af63450554a58.js:1run @ polyfills.250ebd3af63450554a58.js:1(anonymous) @ polyfills.250ebd3af63450554a58.js:1invokeTask @ polyfills.250ebd3af63450554a58.js:1runTask @ polyfills.250ebd3af63450554a58.js:1m @ polyfills.250ebd3af63450554a58.js:1Promise.then (async)k @ polyfills.250ebd3af63450554a58.js:1scheduleTask @ polyfills.250ebd3af63450554a58.js:1scheduleTask @ polyfills.250ebd3af63450554a58.js:1scheduleMicroTask @ polyfills.250ebd3af63450554a58.js:1P @ polyfills.250ebd3af63450554a58.js:1Z @ polyfills.250ebd3af63450554a58.js:1(anonymous) @ polyfills.250ebd3af63450554a58.js:1Promise.then (async)(anonymous) @ polyfills.250ebd3af63450554a58.js:1C @ polyfills.250ebd3af63450554a58.js:1R.e.then @ polyfills.250ebd3af63450554a58.js:1(anonymous) @ main.60c059cd76aa04d8353f.js:1__tryOrUnsub @ main.60c059cd76aa04d8353f.js:1next @ main.60c059cd76aa04d8353f.js:1_next @ main.60c059cd76aa04d8353f.js:1next @ main.60c059cd76aa04d8353f.js:1_next @ main.60c059cd76aa04d8353f.js:1next @ main.60c059cd76aa04d8353f.js:1notifyNext @ main.60c059cd76aa04d8353f.js:1_next @ main.60c059cd76aa04d8353f.js:1next @ main.60c059cd76aa04d8353f.js:1observe @ main.60c059cd76aa04d8353f.js:1dispatch @ main.60c059cd76aa04d8353f.js:1_execute @ main.60c059cd76aa04d8353f.js:1execute @ main.60c059cd76aa04d8353f.js:1flush @ main.60c059cd76aa04d8353f.js:1invokeTask @ polyfills.250ebd3af63450554a58.js:1runTask @ polyfills.250ebd3af63450554a58.js:1invokeTask @ polyfills.250ebd3af63450554a58.js:1invoke @ polyfills.250ebd3af63450554a58.js:1n.args.<computed> @ polyfills.250ebd3af63450554a58.js:1setInterval (async)i @ polyfills.250ebd3af63450554a58.js:1scheduleTask @ polyfills.250ebd3af63450554a58.js:1scheduleTask @ polyfills.250ebd3af63450554a58.js:1scheduleMacroTask @ polyfills.250ebd3af63450554a58.js:1d @ polyfills.250ebd3af63450554a58.js:1(anonymous) @ polyfills.250ebd3af63450554a58.js:1s.<computed> @ polyfills.250ebd3af63450554a58.js:1requestAsyncId @ main.60c059cd76aa04d8353f.js:1schedule @ main.60c059cd76aa04d8353f.js:1schedule @ main.60c059cd76aa04d8353f.js:1schedule @ main.60c059cd76aa04d8353f.js:1_schedule @ main.60c059cd76aa04d8353f.js:1scheduleNotification @ main.60c059cd76aa04d8353f.js:1_next @ main.60c059cd76aa04d8353f.js:1next @ main.60c059cd76aa04d8353f.js:1(anonymous) @ main.60c059cd76aa04d8353f.js:1_trySubscribe @ main.60c059cd76aa04d8353f.js:1subscribe @ main.60c059cd76aa04d8353f.js:1call @ main.60c059cd76aa04d8353f.js:1subscribe @ main.60c059cd76aa04d8353f.js:1c @ main.60c059cd76aa04d8353f.js:1_innerSub @ main.60c059cd76aa04d8353f.js:1_tryNext @ main.60c059cd76aa04d8353f.js:1_next @ main.60c059cd76aa04d8353f.js:1next @ main.60c059cd76aa04d8353f.js:1(anonymous) @ main.60c059cd76aa04d8353f.js:1_trySubscribe @ main.60c059cd76aa04d8353f.js:1subscribe @ main.60c059cd76aa04d8353f.js:1call @ main.60c059cd76aa04d8353f.js:1subscribe @ main.60c059cd76aa04d8353f.js:1call @ main.60c059cd76aa04d8353f.js:1subscribe @ main.60c059cd76aa04d8353f.js:1(anonymous) @ main.60c059cd76aa04d8353f.js:1invoke @ polyfills.250ebd3af63450554a58.js:1run @ polyfills.250ebd3af63450554a58.js:1runOutsideAngular @ main.60c059cd76aa04d8353f.js:1(anonymous) @ main.60c059cd76aa04d8353f.js:1runInitializers @ main.60c059cd76aa04d8353f.js:1(anonymous) @ main.60c059cd76aa04d8353f.js:1(anonymous) @ main.60c059cd76aa04d8353f.js:1(anonymous) @ main.60c059cd76aa04d8353f.js:1invoke @ polyfills.250ebd3af63450554a58.js:1onInvoke @ main.60c059cd76aa04d8353f.js:1invoke @ polyfills.250ebd3af63450554a58.js:1run @ polyfills.250ebd3af63450554a58.js:1run @ main.60c059cd76aa04d8353f.js:1bootstrapModuleFactory @ main.60c059cd76aa04d8353f.js:1(anonymous) @ main.60c059cd76aa04d8353f.js:1invoke @ polyfills.250ebd3af63450554a58.js:1run @ polyfills.250ebd3af63450554a58.js:1(anonymous) @ polyfills.250ebd3af63450554a58.js:1invokeTask @ polyfills.250ebd3af63450554a58.js:1runTask @ polyfills.250ebd3af63450554a58.js:1m @ polyfills.250ebd3af63450554a58.js:1Promise.then (async)k @ polyfills.250ebd3af63450554a58.js:1scheduleTask @ polyfills.250ebd3af63450554a58.js:1scheduleTask @ polyfills.250ebd3af63450554a58.js:1scheduleMicroTask @ polyfills.250ebd3af63450554a58.js:1P @ polyfills.250ebd3af63450554a58.js:1then @ polyfills.250ebd3af63450554a58.js:1bootstrapModule @ main.60c059cd76aa04d8353f.js:1zUnb @ main.60c059cd76aa04d8353f.js:1l @ runtime.076604685350bc36956d.js:10 @ main.60c059cd76aa04d8353f.js:1l @ runtime.076604685350bc36956d.js:1t @ runtime.076604685350bc36956d.js:1r @ runtime.076604685350bc36956d.js:1(anonymous) @ main.60c059cd76aa04d8353f.js:1Show 54 more frames

Odysseas Stamoglou Visual Artist & Musician http://www.odysseusart.com 

    On Tuesday, 17 November 2020, 19:00:46 CET, Johannes Millan <notifications@github.com> wrote:  
 
 


Closed #669.

**Comment by johannesjo** [comment]
Thanks for letting me know!

**Comment by johannesjo** [comment]
Is this still relevant?

**Comment by odysseusart** [comment]
No, the issue has not appeared again. Thanks!
Odysseas Stamoglou Visual Artist & Musician http://www.odysseusart.com 

    On Thursday, 18 February 2021, 10:06:39 CET, Johannes Millan <notifications@github.com> wrote:  
 
 


Is this still relevant?

**Comment by johannesjo** [comment]
Thank you!
