### ISSUE TITLE
[Feature] Option to disable toast/popup message for sync.

### ISSUE THREAD

**Issue by ArjenR** [johannesjo/super-productivity#67]
## Your Environment

* Version used: v1.10.3
* Operating System and version: Windows 10
* Desktop Environment: n.a.
* Browser Name and version: n.a.

## Expected Behavior
Option to disable the Toast message(s) for syncing (to Google) in Backup and  Sync settings.

## Current Behavior
A toast message pops up for every sync. Since I have superproductivity on the side of a large screen, it breaks concentration.

**Comment by johannesjo** [comment]
Good suggestion! Thank you! I'll provide an option.

**Comment by johannesjo** [comment]
The feature should be available with the latest release.
