### ISSUE TITLE
'Show/hide additional info button' state freezes

### ISSUE THREAD

**Issue by javierfolcini** [johannesjo/super-productivity#674]
No issues found when searching for 'additional info'

### Your Environment
* Version used: snap 6.1.0 
* Operating System and version: Ubuntu 20.04 LTS
* Desktop Environment: GNOME 3

### Expected Behavior
Only one instance (task/sub-task) of the 'Show/hide additional info button' button should be active at the same time

### Current Behavior
I don't know how but several instances appear active. Could not reproduce it but I think it had to do with changing tags and moving to the tag view while that is open.

### Steps to Reproduce (for bugs)
Unfortunately I don't have steps to reproduce :/ 

### Console Output
One error:
Service worker registration failed with: TypeError: Failed to register a ServiceWorker for scope ('file:///snap/superproductivity/963/resources/app.asar/dist/') with script ('file:///snap/superproductivity/963/resources/app.asar/dist/ngsw-worker.js'): An unknown error occurred when fetching the script.

### Error Log (Desktop only)
no logs, checked both locations

**Comment by johannesjo** [comment]
Hey there! Thank you very much for taking the time to open this up! As you can imagine I am also unable to reproduce this, but it's good to know that this might be an issue in case it re-appears.

**Comment by javierfolcini** [comment]
Hey! I think I was able to reproduce it.
1. create two tasks
2. edit the notes for task 1
3. click in the notes button for task 2
3. then click in the notes button for task 2 again (to close it)

The notes side bar closes but the notes button for task 1 remains active

**Comment by johannesjo** [comment]
This might be a misunderstanding. If you're referring to this:
![Screenshot from 2020-11-19 18-34-29](https://user-images.githubusercontent.com/1456265/99702299-e414e380-2a95-11eb-9a0e-d19f4b561365.png)

The notes icon with a filled background is indicating that there are notes available for this task.

**Comment by javierfolcini** [comment]
MY GOSH! I can't believe I missed that! thank you very much johanes, for the quick answers and for super productivity, it's really a great tool
