### ISSUE TITLE
After open app from tray need to scroll empty area to see projects again (Linux).

### ISSUE THREAD

**Issue by IT-Tool** [johannesjo/super-productivity#677]
### Your Environment
* Version used: superProductivity_6.1.0_amd64.deb (installed for the first time).
* Operating System: Debian-based Parrot OS
* Desktop Environment: MATE 1.24.1

### Current Behavior
![202011](https://user-images.githubusercontent.com/53435741/99721805-a3be6100-2aa7-11eb-9d6b-05d5af3ee501.png)

### Steps to Reproduce
If the settings are the same as in screenshot.
![202011+](https://user-images.githubusercontent.com/53435741/99721911-c8b2d400-2aa7-11eb-94c1-d74dc795e1f4.png)

1. Open superProductivity app,
2. Open project (first one in my case),
3. Close window (not minimize),
4. Open from tray.

It looks like on the first screenshot (No project can be selected. You have to close and run the program again).

If you disable minimizing to tray (in the settings), this bug doesn't happen again.

### Error Log (Desktop only)
No log.log file

**Comment by johannesjo** [comment]
Thank you very much for reporting this! @tuxflo could you maybe have a look?

**Comment by tuxflo** [comment]
I'll take a look but it will take some time, probably at the weekend.
I just did an upgrade to version 6.1.0 (from 6.0.1) and I don't have the described issue.

**Comment by johannesjo** [comment]
Ah maybe this is just a misunderstanding. You can scroll the left menu if you are on a project list. The space below the menu is then used for project-specific notes.

**Comment by IT-Tool** [comment]
I tried to repeat my steps and I also did not reproduce this error. I started to look for the reason. And it turned out that yesterday I missed important points.
Now I have edited the main ticket (Steps to Reproduce).
And I was able to play it again even on another computer and OS with Linux Mint 19.3 XFCE

It turns out that when projects are not displayed (in the first screenshot) you can scroll this empty area to see projects again. But it is not quite obvious at the beginning why scrolling in empty areas must be so long :)

**Comment by johannesjo** [comment]
@IT-Tool alight :) can this be closed then?

**Comment by IT-Tool** [comment]
Can this empty space be shorter?
For example, you can scroll projects and notes, but why scroll Today and Scheduled "Folders"?

Because if you do not know about this feature of the app, then every time it is launched from the tray, you see an empty space that you need to scroll. This is not very convenient. Right?

**Comment by johannesjo** [comment]
Well, I intend to move the notes back to the right at some point which would make this problem disappear anyway. I would accept a PR improving this in the meantime.
