### ISSUE TITLE
[Praise]

### ISSUE THREAD

**Issue by bjonord** [johannesjo/super-productivity#68]
Also wanted to chime in and say that I really enjoy your application!

Thanks for all the hard work!

👋

**Comment by johannesjo** [comment]
Thank you very much! That's always great to hear :)

**Comment by kemexyz** [comment]
Will go ahead and say I love this application! Amazing work!

**Comment by jeensg** [comment]
Also thanks for this great application!

**Comment by debone** [comment]
I've been looking for years for something like Super Productivity. It's the best time tracker and task manager I've found and it's free. Great work.

**Comment by gossterrible** [comment]
Loving it, keep up the good work.

**Comment by servomekanism** [comment]
Thank you very much for this.
Awesome work!

**Comment by KonTy** [comment]
Let me pile on here are say yeah. Your app is so awesome it is very intuitive and low friction. Adding new Items is easy, tracking time, etc. It is awesome. Having global hotkeys is also awesome. I mean so many cool features.

**Comment by jtagliaf** [comment]
I just stumbled upon this app by total surprise and it just blows my mind how well crafted this app is! It combines everything i ever wanted in one app and the idea with finishing your workday and having a small recap is just the best !!! Thank you so much

**Comment by fiuzaB** [comment]
Thanks for all your hard work :)

**Comment by a4bits** [comment]
Thank you for this app! :-)

**Comment by netsatan** [comment]
Thank you for making this! Great job!

**Comment by johannesjo** [comment]
Thanks, everybody! That was really nice! :) I am closing this now.
