### ISSUE TITLE
Access to the description of completed tasks

### ISSUE THREAD

**Issue by IT-Tool** [johannesjo/super-productivity#684]
## Problem Statement
I often add description or links to the task notes. After I finish a task (the task goes to the archive and it's okay), after a while I may need:
- to see that text
- or copy a link (from the task description)
- Or double-check that I didn't miss anything.

But the task is no longer available. You can only find it in Project Worklog and then restore it.
![20201122](https://user-images.githubusercontent.com/53435741/99915373-3276ec00-2cfb-11eb-9efe-bd0a8b644b84.png)

But I don't want to restore anything. I just want to see a description of the completed tasks sometimes.

## :grey_question: Possible Solution
- It would be nice to be able to see the description of the tasks right in the Worklog list (Add another button (show description/note) next to restore task button).

**Comment by johannesjo** [comment]
Thank you very much for taking the time to open this up. Also makes a lot of sense to me. Don't know when I will get to it though. Meanwhile, PRs are welcome.
