### ISSUE TITLE
View the total number of tasks for each project (in the list of projects)

### ISSUE THREAD

**Issue by IT-Tool** [johannesjo/super-productivity#685]
## Problem Statement
I would like to see the total number of tasks for each project (in the list of projects) without opening the folder itself.
It will be visual/clear and convenient.
(for example)
![20201122 (copy)](https://user-images.githubusercontent.com/53435741/99916462-31958880-2d02-11eb-8068-1d739c904ca6.png)

## :grey_question: Possible Solution
(the number depends on the number of tasks in project)
![20201122](https://user-images.githubusercontent.com/53435741/99916466-38bc9680-2d02-11eb-9d08-fdbc399f80d6.png)

**Comment by johannesjo** [comment]
Thanks for the suggestion. Makes a lot of sense to add this. I'll work on this as soon as I have a bit more time on my hands.

**Comment by johannesjo** [comment]
This will be available with the next release. Thanks again for the suggestion!
