### ISSUE TITLE
Countdown Timer icon in the app header

### ISSUE THREAD

**Issue by IT-Tool** [johannesjo/super-productivity#686]
## Problem Statement
I found countdown timers very useful for me (more useful than just knowing the current time). When you can see how much time is left until the event (possibly a deadline), before the presentation or meeting today.
(just for example)
![20201123+](https://user-images.githubusercontent.com/53435741/99919069-06fffb80-2d13-11eb-876b-75ea791a5aa3.png)

## :grey_question: Possible Solution
I would like to see (on this panel) a live icon with timer (DD:HH:MM) to the closest event today.
![20201123-01](https://user-images.githubusercontent.com/53435741/99918589-cc489400-2d0f-11eb-97e4-977eab117723.png)

When you click on timer icon, you will see a list of other today timers.

For example you can put the Countdown timer settings in Productivity Helper section
![20201122-02](https://user-images.githubusercontent.com/53435741/99918607-f26e3400-2d0f-11eb-9f61-07738c0eb29a.png)

This is enough to configure the timer:

- Timer title
- Start date+time
- End date+time
- Repeat (off/on) - Repetition units (every minute/hour/day/week/month/year).
- Seconds (hide/show)

## :heavy_plus_sign: How can this be used?

- To understand how many tasks I can take and make it before the event starts.
- And in the process to know how much time I have left to finish.
- Sometimes it can help to avoid wasting time and focus on the task.

**Comment by johannesjo** [comment]
Hey there! Thanks for the suggestion! I can imagine this as an extension of the simple counters. In addition to the already existing types `StopWatch` and `ClickCounter` we could add the type `Countdown`. Should be doable by people new to the project, too, which is always nice :)

**Comment by alebricio** [comment]
Hi @johannesjo! This is a great feature. If it's okay, I would like to work on it starting today :)

**Comment by johannesjo** [comment]
Hey @alebricio! That's great to hear!! Please let me know if I can help you with that! If needed, I can give you a short introduction on how the hole simple counter feature is currently intended to work.
