### ISSUE TITLE
Error: Uncaught (in promise): Error: No task foundError: No task found

### ISSUE THREAD

**Issue by ntlghb** [johannesjo/super-productivity#689]
### Steps to Reproduce

1. open app on the desktop
2.get the 'your data seems to be damaged, do you want to restore it' pop up --> click yes
3.error
4.

### Console Output

Error: Uncaught (in promise): Error: No task foundError: No task found    at file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:2819284    at Array.forEach ()    at file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:2819232    at Array.forEach ()    at file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:2818941    at file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:2819444    at t.repairData (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:2820650)    at t.i (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:2821975)    at i.next ()    at s (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:2822128)
### Stacktrace
```
projectItem.backlogTaskIds.forEach (webpack:///src/app/core/data-repair/data-repair.util.ts:276:18)
Error (webpack:///src/app/core/data-repair/data-repair.util.ts:273:35)
projectIds.includes (webpack:///src/app/core/data-repair/data-repair.util.ts:254:5)
isDataRepairPossible (webpack:///src/app/core/data-repair/data-repair.util.ts:25:38)
constructor (webpack:///src/app/core/data-repair/data-repair.service.ts:19:22)
this._dataRepairService.isRepairPossibleAndConfirmed (webpack:///src/app/core/data-init/data-init.service.ts:58:50)
Ur (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:2822128)
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1215:38)
value.hasOwnProperty (webpack:///node_modules/zone.js/fesm2015/zone.js:1165:20)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1277:20)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:407:34)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:27476:32)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:63)
task._transitionTo (webpack:///node_modules/zone.js/fesm2015/zone.js:179:50)
drainMicroTaskQueue (webpack:///node_modules/zone.js/fesm2015/zone.js:583:38)
```

### Meta Info
META: SP6.1.1 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.1.1 Chrome/85.0.4183.121 Electron/10.1.5 Safari/537.36

### Actions Before Error
```
1605608424542: [Project] Update Work End 
1605608424544: [Tag] Update Work End for Tag 
1605608424557: [Persistence] Save to DB 
1605608424558: [Persistence] Save to DB 
1605608424559: [Persistence] Save to DB 
1605608425538: [Task] Add time spent 
1605608425542: [Project] Update Work End 
1605608425543: [Tag] Update Work End for Tag 
1605608425556: [Persistence] Save to DB 
1605608425557: [Persistence] Save to DB 
1605608425558: [Persistence] Save to DB 
1605608426538: [Task] Add time spent 
1605608426541: [Project] Update Work End 
1605608426543: [Tag] Update Work End for Tag 
1605608426556: [Persistence] Save to DB 
1605608426557: [Persistence] Save to DB 
1605608426558: [Persistence] Save to DB 
1605608427538: [Task] Add time spent 
1605608427542: [Project] Update Work End 
1605608427544: [Tag] Update Work End for Tag 
1605608427560: [Persistence] Save to DB 
1605608427561: [Persistence] Save to DB 
1605608427561: [Persistence] Save to DB 
1605608428538: [Task] Add time spent 
1605608428543: [Project] Update Work End 
1605608428545: [Tag] Update Work End for Tag 
1605608428561: [Persistence] Save to DB 
1605608428563: [Persistence] Save to DB 
1605608428564: [Persistence] Save to DB 
1605608428993: [Task] UnsetCurrentTask
```

**Comment by johannesjo** [comment]
Thank you very much for taking the time to open this up. I look into it!

**Comment by IT-Tool** [comment]
@ntlghb Can you keep only one title line? There is no need to make such long title :)

**Comment by johannesjo** [comment]
@ntlghb  It looks like that for some reason a bit of your data got into an invalid state that I didn't account for and that I can't reproduce. It would be great if you could share a copy of your data to contact@super-productivity.com, so I can debug this on my computer. You can create an export by navigating to "Settings" and then to "Import/Export". 

If the error occurs on startup, you might still be able to go there, though it might be a bit tricky to navigate around the modal. If not you might be able to find the latest data in the folder for automatic backups.

**Comment by johannesjo** [comment]
This should be fixed now, I suppose.
