### ISSUE TITLE
Tasks in other projects get replaced

### ISSUE THREAD

**Issue by cobbinaloic** [johannesjo/super-productivity#69]
## Your Environment

* Version used: v1.9.4 installed using sudo apt-get install superproductivity
* Operating System and version: Maui Linux 17.06
* Desktop Environment: KDE Plasma version 5.10.02
* Browser Name and version: na

## Expected Behavior
Tasks and subtasks on other projects should not be replaced by the project I am currently running.

## Current Behavior
I created 2 different projects, each having different tasks and subtasks. Let's just say project 1 and project 2.

I switch to project 1 and start the time. Once I am done with project 1, I decide to switch to project 2 only to find that all the tasks I created there have been replaced by those on project 1. I have tested this problem a second time and it confirms the bug. Anytime I start working with project 1, all the tasks I created on project 2 are replace with those in project 1.

## Steps to Reproduce (for bugs)
1. Create a project called project 1
2. Create a second project called project 2

3. Under Project 1 create a task called A
4. Under task A create 3 subtasks called A1, A2 and A3 respectively. Include estimated time for each subtasks

5. Under Project 2 create a task called B
6. Under task B create 3 subtasks called B1, B2, and B3 respectively. Include estimated time for each subtasks

7. Go back to project 1 and start the timer for subtask A1.
8. After 1 or 2 minutes, stop the timer.
9. Switch back to Project 2

You will notice that subtasks B1, B2 and B3 will have been replaced by A1, A2 and A3

**Comment by johannesjo** [comment]
That looks like a major bug. Thank you very much for taking the time to document the issue. So far I'm unable to reproduce the behavior consistently, but I will dig into it.

**Comment by johannesjo** [comment]
Oh wrong issue number for the second commit... Release should be out now. Could you please check again then with the latest version (1.10.4), if the issue is resolved for you as well?

**Comment by cobbinaloic** [comment]
I just tested the latest release and the problem is gone. Thank you so much
