### ISSUE TITLE
add sync provider through local files

### ISSUE THREAD

**Issue by da-sti** [johannesjo/super-productivity#690]
## Problem Statement
Moving in different countries including some where internet is quite restricted, I tend to use the cloud as few as possible and solution that are simple and robust.
I'm very happy with 2 combos : keepassXC+syncthing and Jopling+Syncthing, my notes and my passwords are in sync in all my devices with just the combinaison of those softwares and it's very usefull.
I've read that some people achive that with seafiles.

## :grey_question: Possible Solution
Joplin has a file syncing : it uses a sperate folder and drops files in it (https://joplinapp.org/spec/sync_lock/)
KeepassXC does that with database and merges the cached database with the db written on files (it's more reliable)

## :arrow_heading_up: Describe alternatives you've considered
For now I use Jopin that has task lists but it's not focussed on tasks as super productivity

**Comment by johannesjo** [comment]
Hey there! Thank you very much for taking the time to open this up. Makes a lot of sense to me and should be straightforward to implement for the desktop version (we could use Dropbox as a template and simply replace the API stuff with a simple flat file storage). The only real problem I see is that it might be confusing for some people that this will likely only work with the desktop version of the app and NOT the mobile or web variants. There [might be a path](https://web.dev/file-system-access) for those too, but I have my doubts that it will work as intended.

If anybody wants to tackle this, please let me know!

**Comment by da-sti** [comment]
I can not help on you doubts if this could be confusing : the first time I saw that feature in Joplin and I immediately though about syncthing that could do the sync job in the background and I just pointed both of them to the same directory.

Here's what it looks like in Joplin's desktop app 

![image](https://user-images.githubusercontent.com/22189964/100319586-d7930c80-2ffa-11eb-919e-82c8172145e6.png)

and in Joplin's android app

![image](https://user-images.githubusercontent.com/22189964/100320179-c8608e80-2ffb-11eb-8e8f-836269ee0534.png)

I hope someone will have the time and skills to taccle this one, I have to admit that being able to sync your datas from different devices/OS/networks without any cloud is quite amazing to me :-)

**Comment by asbiot** [comment]
I switched from Hamster to superproductivity because the syncing of the former is bad. So far I love SP and its many features. It is exactly what I need. 
However, I must +1 this thread asking for local file system syncing! If I were inclined to trust an online provider like Google or Dropbox with my (unencrypted) data, then I could use pretty web apps like Toggl or Clockify. I don't trust them and thus use an encrypted file share that encrypts my data locally before syncing it to my other devices (e.g. laptop, work, home). 
I would love it, if you could mirror the Google sync and simply provide a file-on-disc that I can then sync using any other tool. Ideally it would update the file on event/change of the tasks. I don't need it to sync the minutes while I am working – once I change a task or close the programme would be enough for me.
Unfortunately my expertise is insufficient to code the desired feature myself. I can only plead for someone to do so, please!

**Comment by asbiot** [comment]
### Proposal: a (quick ?) and dirty solution
- Add an option that sets a timer on the "automatic backups", as the folder with the backups can be synced. User can choose the time interval to be e.g. 1 minute.
- On program start, check if the current state of internal data is newer or older than the last automatic backup. If it is older, then ask the user if he wishes to "import" the last backup.
  - [optional] create a backup of the state-at-startup before overwriting it with the last automatic backup, just in case something goes wrong.

**Comment by johannesjo** [comment]
I haven't really explored that myself, but have you tried specifying the `--user-data-dir` flag [as described in this discussion](https://github.com/johannesjo/super-productivity/discussions/683#discussioncomment-141414)?

**Comment by asbiot** [comment]
> I haven't really explored that myself, but have you tried specifying the `--user-data-dir` flag [as described in this discussion](https://github.com/johannesjo/super-productivity/discussions/683#discussioncomment-141414)?

Yes, I have tried that. It allows me to put the entire working directory into my synced directory. However, the database file quickly has a syncing conflict, as the conflict resolution on blobs and (sql) DB files is bad. That is not a working solution for me. 

Instead, I replaced the backup directory on the standard path with a soft-link to a directory in my encrypted sync directory (I am running linux on all my main devices). In this way I am only "messing" with the backup files and not the normal data of the program. I am currently trying to import the automatic backup whenever I switch devices but it is not the most elegant solution. I will try this for a while and report back on how well it works.

**Comment by johannesjo** [comment]
Alright! Thanks for the explanation!

**Comment by nm17** [comment]
@johannesjo Any updates on this? I want to use it with Synching.

**Comment by toolonely** [comment]
I would like as well to see this feature implemented with higher priority than fixing the WebDAV support over NextCloud and WsgiDAV. I have installed syncthing and the process was super easy compared to NextCloud. If both the desktop app and the mobile app will have support for filesystem sync, a la Joplin, as requested above, I'll be happy to pick it as sync option.

**Comment by lerra** [comment]
+1 on this one, would love to see a directory syncing option and same for android, I use a solution that syncs my folders between my devices to be able to access it both from mobile but also from multiple machines without using any cloud services

Btw, high five, you have done a great job with super productivity!

**Comment by REMjn832** [comment]
I want to +1 this too! 
I just came across as SP as a longtime todo.txt user (Joplin). But I do not trust granting full permissions to the app to use Google Sync, and would rather me chose my sync platform in the background, and specify the file location in SP. Just like others have said, is the way Joplin works.

Thanks for the great app! Once sync is resolved, I am hoping to make SP my one and only task management app! :)

**Comment by johannesjo** [comment]
If you like to see this happening, please upvote the original issue! :)

**Comment by aaylnx** [comment]
+1 This would really be a wonderful feature.

**Comment by nm17** [comment]
Still relevant to this day

**Comment by johannesjo** [comment]
I am happy to announce that the feature should be available with the next (pre-) release. Let me know if you have any feedback.

**Comment by aaylnx** [comment]
> I am happy to announce that the feature should be available with the next (pre-) release. Let me know if you have any feedback.

Wonderful! Thanks!

**Comment by tukusejssirs** [comment]
> I am happy to announce that the feature should be available with the next (pre-) release. Let me know if you have any feedback.

Will this work on Android too? :wink:

**Comment by johannesjo** [comment]
> Will this work on Android too? 😉

No :) just desktop for now. Pull requests are welcome though!

**Comment by Mustang-ssc** [comment]
Would love to see this implemented in the Android app too.

It is a simple feature (not badly intended: not speaking on the complexity and time consumption) that would hugely complete the experience for some of us using services to locally sync files, such as Syncthing.

**Comment by aaylnx** [comment]
The Android app for Obsidian puts all of it's files, including configs, in the Documents folder. If there were an option simply to store things there, then Syncthing could just sync the folders. This is what I use for Obsidian.

BTW, where are the files for SP stored on Android? I have a path to /storage/emulated/0/Android/data/com.superproductivity.superproductivity, but there's nothing there. Perhaps if I could find the right location, I could just sync it myself using Syncthing.

**Comment by Cerdtruir** [comment]
still relevant

**Comment by virtos** [comment]
Android version of a local file sync is sorely missing.

**Comment by Toffanelly** [comment]
+1 Very important feature

**Comment by bepolymathe** [comment]
Any news about local file sync or import .json feature ?
