### ISSUE TITLE
Option for completed tasks

### ISSUE THREAD

**Issue by ronilaukkarinen** [johannesjo/super-productivity#691]
## Problem Statement
When tasks are completed they are always visible in the main view. I'd like to start a discussion about separate options for example archiving individual completed tasks instead them always being visible after completion. What happens to them? Should we just delete them after completing? Is there a way to resolve them?

Right now I have hundreds of tasks under "Completed tasks" title.
Another issue is that if I want to restore task to production, I need to go through the task list and search the last completed task from the bottom.

## :grey_question: Possible Solution

Add option to "Archive task" or some other approach to clean up the completed tasks without deleting them.

## :arrow_heading_up: Describe alternatives you've considered

Currently no alternatives in mind.

## :heavy_plus_sign: Additional context

Didn't find any other references to this issue by quick lookup.

**Comment by IT-Tool** [comment]
As far as I can understand, maybe this issue can be solved this way?

Now there are 2 duplicate buttons.
![Screenshot at 2020-11-24](https://user-images.githubusercontent.com/53435741/100111983-a08bf200-2e66-11eb-980d-742f15199522.png)

Maybe one of them can be used to hide some completed tasks?
![Screenshot at 2020-11-24+](https://user-images.githubusercontent.com/53435741/100112042-b4375880-2e66-11eb-8eef-172b5404bf46.png)


And hidden tasks still will be in the project's WorkLog.

**Comment by ronilaukkarinen** [comment]
Nice suggestion! Indeed, no need for duplicate buttons.

**Comment by johannesjo** [comment]
Thank you very much for taking the time to open this up. The current flow is intended to work like this:

1. User marks tasks as done
2. User clicks "Finish Day" and has some time to reflect on what has been done (btw. this can be done separately for different projects)
3. User clicks "Save & go home" => all done tasks are moved to the task archive

While I am not strictly against adding more options to do so, I am a bit hesitant as I'd like to keep the UI as decluttered as possible (and it's a bit cluttered at some places already, unfortunately).

If more people need this we could also consider adding this as an optional feature.

**Comment by ronilaukkarinen** [comment]
I have obviously missed option 3 "Save & go home" completely as my task list looks like this...
 
![Screen-Shot-2020-11-25-07-43-01 63](https://user-images.githubusercontent.com/1534150/100187960-dde99180-2ef1-11eb-8be3-6f0080fa3656.png)

**Comment by IT-Tool** [comment]
@johannesjo ﻿Thank you for the explanation, I like the way the program works.
(I remembered my first experience) if you use the program for the first time, it seems a bit unusual (so I put off starting using it for a while). But when you understand it's logic, you start to like it.

Conclusion:
* Maybe it's needed to add a simple one-page tutorial explaining the workflow (how to use the program) when new user first time run it?
* Or just add an unobtrusive hint when there are a lot of tasks in the list and the Finish Day button is not visible.

For example:
* suggest moving the tasks to the archive,
* if you get a positive answer,
* scroll to the Finish Day button.

**Comment by johannesjo** [comment]
@IT-Tool thanks! The conclusions make a lot of sense! There [already is an issue for a guided tour](https://github.com/johannesjo/super-productivity/issues/223) but currently I doubt that I will ever get to it myself, as there is so much other stuff to do.

This leaves displaying some hint as an alternative. I am not sure yet, what the best way would be to display this without cluttering the UI and annoying users that already know about this. Any additional ideas on how and when to display it?

**Comment by ronilaukkarinen** [comment]
For me the problem was that I never realized the finish button is in the bottom. It could be before the list or even in the top right corner to be more noticeable? Just an idea. The tutorial would solve this as well.

**Comment by johannesjo** [comment]
@ronilaukkarinen I remember putting it deliberately at the bottom, so one is less likely to forget checking the tasks or the evaluation sheet before closing the app which otherwise happens very quickly if the first thing you see is the button. It's also a bit weird if you check the UI below and have to scroll up again. 

Introducing two buttons could also be an option here, but would raise some problems of its own. Eg. if there are a low number of tasks it would be weird to have two buttons with the same functionality nearby – very hard to figure out some sweet spots here for different screen sizes, etc. 

I also thought about using a floating button but that would hide some information in the table, which could be less ideal if the user has a small screen or window size.

Any other ideas maybe?

So far I think a tutorial might be the best option. @papernoise may I ask your opinion about the subject?

**Comment by ronilaukkarinen** [comment]
@johannesjo Good points. I vote for the tutorial. You can dismiss the original feature request in this issue. 👍

**Comment by johannesjo** [comment]
Still relevant, I'd say.
