### ISSUE TITLE
Keyboard accessibility: Collapse opened panels on Esc-key

### ISSUE THREAD

**Issue by ronilaukkarinen** [johannesjo/super-productivity#692]
I would like to issue some basic accessibility and usability things. The main thing that would be useful for us seeing people as well is to be able to close menus by pressing ESC key. There are two menus so this is a bit of a challenge. There are at least three options in what should happen when pressing ESC:

1. Collapse the menu that has been opened last
2. Collapse all the menus at the same time
3. Collapse the menu that has focus

To have ESC function is more accessible than not having it as it currently is but the MOST accessible way is to use option 3 with conditions. If there is no focus on any of the menus or dialogs, use option 1. Closing all menus with one key is the worst option from these and should be effective if nothing else can be used.

There might be other accssibility issues but these are the first that bug me. What do you think?

**Comment by johannesjo** [comment]
Thank you very much for taking the time to open this up. Makes a lot of sense to add this. There are a couple of different places where this needs to be added. I gladly accept any PRs dealing with this. This can happen in different smaller PRs as well as there might be very different solutions required.
