### ISSUE TITLE
Super Productivity shows that I'm being offline although I'm definitely online

### ISSUE THREAD

**Issue by alexanderadam** [johannesjo/super-productivity#694]
### Your Environment

* Version used: Snap, 6.1.1
* Operating System and version: Ubuntu 20.04.1
* Desktop Environment: Ubuntu standard (Gnome)

### Expected Behaviour
Everything should work

### Current Behaviour
It claims to be offline
![You are disconnected from the internet. Syncing and requesting issue provider data will not work.](https://user-images.githubusercontent.com/372620/100235986-5caff000-2f2d-11eb-9ca2-6e9249a07a41.gif)

### Steps to Reproduce (for bugs)

1. I guess I started it when I _was_ offline, but I went online later on.

**Comment by johannesjo** [comment]
Thank you very much for taking the time to open this up. I also encountered this. This is due to the offline event not being a 100% reliable. To fix this we could introduce periodically checking this.
