### ISSUE TITLE
Fix iOS styling issues

### ISSUE THREAD

**Issue by johannesjo** [johannesjo/super-productivity#695]
I found two related problems when creating and selecting a task:
The first is that once the task to edit is selected, when returning to the start menu it is not possible, because the option of "today" collides with the option of "new task".
The second is that the pwa does not notify me of any reminder when the scheduled time for a certain task arrives :(

Here are some gifs I made for a better reference:

![gif-maker-min compress](https://user-images.githubusercontent.com/74876254/100175202-8ddbe200-2e93-11eb-87b0-4ed655a0c47b.gif)

![1gif-maker](https://user-images.githubusercontent.com/74876254/100175441-faef7780-2e93-11eb-9b7c-ed06db9cc696.gif)

_Originally posted by @userad-ia in https://github.com/johannesjo/super-productivity/discussions/682#discussioncomment-138175_

**Comment by jpitman1010** [comment]
Would it help to use js to hide visibility of new task when menu button is clicked and when collapsed it unhides?

**Comment by johannesjo** [comment]
@jpitman1010 I don't think that this will be necessary. There should be fix with CSS only possible.

**Comment by jpitman1010** [comment]
Do you want the new task to still show just not show under the menu?  That is possible with CSS, just want to clarify first though. :)

**Comment by johannesjo** [comment]
@jpitman1010 is this still relevant?

**Comment by WantToLearnJapanese** [comment]
This issue still persists on the latest version.

**Comment by WantToLearnJapanese** [comment]
![image](https://user-images.githubusercontent.com/88884927/132834302-894b2940-33ee-4e11-9b69-35b62624409a.png)
https://github.com/johannesjo/super-productivity/search?q=translate3d

Are these be relevant?

**Comment by johannesjo** [comment]
No I don't think so.
