### ISSUE TITLE
Link GitLab group

### ISSUE THREAD

**Issue by Lunik** [johannesjo/super-productivity#697]
## Problem Statement

Actually, the GitLab integration support only `projects`.
However GitLab integration should also propose to add GitLab `group` since there are also `issues`. Also, group `issues` concatenate all subprojects `issues` wich can be handy is the application is splitted in multiple GitLab projects.

## :grey_question: Possible Solution

Implementation of GitLab `groups` in the GitLab integration.

**Comment by johannesjo** [comment]
Thanks for opening this up. Makes a lot of sense. I gladly accept any PRs dealing with this.

**Comment by janLo** [comment]
This should be quite simple: just find out if the given namespace is a group or a project and then select the correct issue api.
I want this feature as well and would look into it but cannot promise on any timeframe.

**Comment by conradob** [comment]
@johannesjo @cbergmann this was solved on https://github.com/johannesjo/super-productivity/pull/1560 
right?

**Comment by johannesjo** [comment]
Thanks @conradob ! I am closing this then.
