### ISSUE TITLE
GitLab Merge Request

### ISSUE THREAD

**Issue by Lunik** [johannesjo/super-productivity#698]
## Problem Statement

GitLab integration should allow to create tasks from GitLab `merge requests`.
Also, this should support GitLab `groups` like spécified in #697

## :grey_question: Possible Solution

Handle GitLab `merge requests` as source for creating tasks.

**Comment by johannesjo** [comment]
Thanks for opening this up. Makes a lot of sense. I gladly accept any PRs dealing with this.

**Comment by janLo** [comment]
Just leaving this here for future reference:

* https://docs.gitlab.com/ee/api/merge_requests.html
* https://docs.gitlab.com/ee/api/todos.html

I'd like to have this too and would like to look into it but I cannot promise on any timeframe.
