### ISSUE TITLE
[Feature] Option to be notified when time spent reaches estimated duration

### ISSUE THREAD

**Issue by cobbinaloic** [johannesjo/super-productivity#70]
## Your Environment

* Version used: v1.9.4 installed using sudo apt-get install superproductivity
* Operating System and version: Maui Linux 17.06
* Desktop Environment: KDE Plasma version 5.10.02
* Browser Name and version: na

## Expected Behavior
Once the time spent on a task or a subtask reaches the estimated duration, a window should popup notifying me about that.

## Current Behavior
Once the time spent on a task or a subtask reaches the estimated duration, I do not get any notification.

**Comment by johannesjo** [comment]
This should also be available in the latest version. Let me know if you think it could be improved.

**Comment by cobbinaloic** [comment]
Hi Johannesjo. To me it does not look that the enhancement is available in version 1.10.4. Are you talking about the next release or this current one.

**Comment by johannesjo** [comment]
The Feature should be there in 1.10.4. You have to enable it under Misc Settings. People tend to get annoyed by notifications, so I made it disabled as a default setting :)

**Comment by cobbinaloic** [comment]
Sorry, I missed that setting. I just tried again and It is working just fine. Thank you very much. I like the way it keeps reminding me over and over again as time passes by that I have exceeded the estimated time.
