### ISSUE TITLE
Cannot paste HEX color on mac app

### ISSUE THREAD

**Issue by ronilaukkarinen** [johannesjo/super-productivity#705]
### Your Environment

* Version used: git-7f0914a
* Operating System and version: macOS Catalina 10.15.7
* Desktop Environment: macOS

### Expected Behavior
Should be able to copy and paste color.

### Current Behavior
Nothing happens when cmd+v is pressed on field. Currently need to memorize HEX and type manually.

### Steps to Reproduce (for bugs)

1. Copy some color hex you like, for example #02a555, ensure it's on the clipboard
2. Go to Create Project
3. Click theme color, click to times R G B to change it to hex
4. Focus color field and press Cmd + V

Circled in this screenshot:

![Screen-Shot-2020-12-01-09-51-08](https://user-images.githubusercontent.com/1534150/100712256-2229d580-33bb-11eb-837b-63d0da805aff.png)

**Comment by johannesjo** [comment]
Thank you very much for taking the time to open this up. Unfortunately, this is a [quirk by the native picker component](https://stackoverflow.com/questions/11167281/webkit-css-to-control-the-box-around-the-color-in-an-inputtype-color). The only way to fix this, is to replace the picker with a custom variant. Unless we provide a much better cross-platform solution, I don't think that is worth going through so much trouble and the extra resource cost.

**Comment by ronilaukkarinen** [comment]
Ah, ok, that's understandable. Let's leave the issue open if someone knows a solution or wants to contribute. 👍
