### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by nicola-lunghi** [johannesjo/super-productivity#706]
Would be nice to have some documentation on the website with a link from the app!!!

Nice app btw!!!

Cheers,
Nick

**Comment by johannesjo** [comment]
It's very unlikely that I will ever get to this (not to speak of keeping it up to date), but I agree that it might be nice to have a bit more documentation. I gladly accept any help I can get.

**Comment by JustAPhrog** [comment]
@johannesjo I think I can help you but how you plan to do it?

**Comment by nicola-lunghi** [comment]
I think if you create a wiki here then it could be updated with merge requests

@johannesjo  @JustAPhrog

**Comment by johannesjo** [comment]
A wiki makes sense. I create one here.

I haven't really thought about what to put into a documentation. It probably doesn't make sense to describe every feature. You probably have a much better perspective on what information would be most useful. What information have you been missing?

**Comment by johannesjo** [comment]
https://github.com/johannesjo/super-productivity/wiki

**Comment by JustAPhrog** [comment]
I think some **installation section** (how to, flags for user-dir, etc.) will be good. Maybe **getting started** section? It can be sth like @johannesjo article with some updates (screenshots). What else?

**Comment by johannesjo** [comment]
Makes all a lot of sesne!

**Comment by yanjost** [comment]
Some help on setting up the JIRA integration would be nice. Once I understand how to make it work, I would happily contribute :)

**Comment by johannesjo** [comment]
@yanjost what problems are you having exactly? I'd appreciate it if you could submit your question here:
https://github.com/johannesjo/super-productivity/discussions?discussions_q=category%3AQ%26A

**Comment by Volapyl** [comment]
Hey @johannesjo, I am completely new to contributing to other projects, but I might want to have a look at making a few smaller pages for some of the information I would have liked to have in the wiki.
How would I get started on making pages? 
I wonder if there is some security setting that does not allow other people to make pages in the wiki or how do we contribute?

Some of the pages I would have wished was there would be some less obvious stuff, like how the icons for the counters work/a list of the text keys for them.

**Comment by johannesjo** [comment]
@Volapyl this is excellent news! Thank you very much for the offer! There are two places for documentation (apart from the app itself, which sometimes could make a lot of sense):
There is [the wiki](https://github.com/johannesjo/super-productivity/wiki) and the [Q&A section](https://github.com/johannesjo/super-productivity/discussions/categories/q-a) 

I must admit that I don't have much experience with it, but the wiki should be accessible by everyone (until something goes wrong :D).

**Comment by yanjost** [comment]
> @yanjost what problems are you having exactly? I'd appreciate it if you could submit your question here:
> [johannesjo/super-productivity/discussions?discussions_q=category%3AQ%26A](https://github.com/johannesjo/super-productivity/discussions?discussions_q=category%3AQ%26A)

What's missing in the docs is a step-by-step guide to setup JIRA sync and also the limitations.
BTW the initial JQL query has to be modified for it to work for me.
And also I don't understand what the second JQL query is used for and how to fill it.
This is the kind of info for which  a small help site or wiki would be useful.

**Comment by johannesjo** [comment]
> And also I don't understand what the second JQL query is used for and how to fill it.

One is used for auto-importing issues to the backlog, the other is used to limit the search in the add task bar.

I agree that the issue integrations are the part that might confuse new users the most.

**Comment by stephencork** [comment]
As an SP user, with limited coding and git experience, I am keen to get involved by adding to the wiki documentation. It would be good to have a guide on how to contribute to the wiki. I tried the edit button but Githubs says I need to be on a branch... Ok, how do I do that? 
Ideas for wiki pages: 
- link a discussion thread to the wiki to allow contributors to discuss wiki setup. 
- guidance on how to make your first wiki contribution. 
- Best practice for writing wiki pages. What kind of workflow will we use? 
- list of key features that we will create documentation pages for eg 
   - What does the blu bar mean on the application icon on IOS   
- List of versions and key changes.
- list of know issues to be included in the next version (maybe a link to an issue board?) 

Might be worth adding the wiki to the way to contribute.md and highlight it for non-coders?.

**Comment by johannesjo** [comment]
@stephencork Thanks for your suggestions! Makes all a lot of sense to me! However to be honest: I don't expect a lot of different people contributing to the wiki so maybe we should focus on the most important things as a first step. This is intensified by the fact that the wiki is only useful if it is up to date and there are regular changes to the app. For you personally, what would be the most important thing which could use some explanation?

**Comment by omartan** [comment]
I don't mind helping it out as I'm a user and with technical background.

Though on this topic, can anyone tell me if it's possible to just sync Jira stories/issues that's assigned to me and how do I get to to that?

**Comment by johannesjo** [comment]
Hi  @omartan ! Thank you very much for your offer. Your question is probably best asked here:
https://github.com/johannesjo/super-productivity/discussions/categories/q-a
