### ISSUE TITLE
[Bug]Short syntax doesn't work

### ISSUE THREAD

**Issue by heliocarbex** [johannesjo/super-productivity#71]
## Your Environment
* Version used: 1.10.4 (desktop)
* Operating System and version: Windows 10
* Browser Name and version: 65.0.3325.181 (official) 64 bits

## Expected Behavior
When I digit "Task 1 t:30m" (without quotes), it should appears:
![image](https://user-images.githubusercontent.com/249042/38136872-b4621a46-33f7-11e8-93a0-ecf96a49eade.png)

## Current Behavior
I digited "Task 1 t:30m" and it shows (without time set):
![image](https://user-images.githubusercontent.com/249042/38136845-7b31f0d4-33f7-11e8-8e5d-403c9ff18010.png)

**Comment by johannesjo** [comment]
It's t30m actually :)

**Comment by johannesjo** [comment]
Oh I just realized that the description text is wrong. The prefixed is supposed to be `t` not `t:`. Thanks for making me aware of that!
