### ISSUE TITLE
Error: end the day

### ISSUE THREAD

**Issue by odysseusart** [johannesjo/super-productivity#714]
### Steps to Reproduce

1. Open app
2. Press 'end the day'
3.
4.

I realized that this error appears only when I exit the app this way. Closing the window conventionally does not produce any error that I can see. Hope this helps :)

### Console Output

Error: Uncaught (in promise): Error: Request failed with status code 400 Error: Request failed with status code 400 at LYNF.t.exports (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.1.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.2bd4dc2828b5398d8a67.js:1:778596) at Rn+g.t.exports (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.1.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.2bd4dc2828b5398d8a67.js:1:1274359) at XMLHttpRequest.p.onreadystatechange [as __zone_symbol__ON_PROPERTYreadystatechange] (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.1.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.2bd4dc2828b5398d8a67.js:1:2103434) at XMLHttpRequest.D (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.1.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:11505) at l.invokeTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.1.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:7257) at Object.onInvokeTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.1.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.2bd4dc2828b5398d8a67.js:1:343673) at l.invokeTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.1.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:7178) at i.runTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.1.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:2666) at u.invokeTask [as invoke] (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.1.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:8307) at _ (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.1.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:20152)
exports (webpack:///node_modules/axios/lib/core/createError.js:16:14)
validateStatus (webpack:///node_modules/axios/lib/core/settle.js:17:11)
request.responseURL.indexOf (webpack:///node_modules/axios/lib/adapters/xhr.js:61:6)
listener.call (webpack:///node_modules/zone.js/fesm2015/zone.js:764:42)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:407:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:27476:32)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:63)
task._transitionTo (webpack:///node_modules/zone.js/fesm2015/zone.js:179:50)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:488:37)
callback (webpack:///node_modules/zone.js/fesm2015/zone.js:1598:17)
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1215:38)
makeResolver (webpack:///node_modules/zone.js/fesm2015/zone.js:1118:20)
Ur (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.1.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.2bd4dc2828b5398d8a67.js:1:3721367)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:373:29)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.js:27488:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:55)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:135:46)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1274:39)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:407:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:27476:32)
META: SP6.1.0 Electron – en-GB – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.1.0 Chrome/85.0.4183.121 Electron/10.1.5 Safari/537.36

### Stacktrace
```
exports (webpack:///node_modules/axios/lib/core/createError.js:16:14)
validateStatus (webpack:///node_modules/axios/lib/core/settle.js:17:11)
request.responseURL.indexOf (webpack:///node_modules/axios/lib/adapters/xhr.js:61:6)
listener.call (webpack:///node_modules/zone.js/fesm2015/zone.js:764:42)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:407:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:27476:32)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:63)
task._transitionTo (webpack:///node_modules/zone.js/fesm2015/zone.js:179:50)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:488:37)
callback (webpack:///node_modules/zone.js/fesm2015/zone.js:1598:17)
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1215:38)
makeResolver (webpack:///node_modules/zone.js/fesm2015/zone.js:1118:20)
Ur (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.1.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.2bd4dc2828b5398d8a67.js:1:3721367)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:373:29)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.js:27488:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:55)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:135:46)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1274:39)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:407:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:27476:32)
```

### Meta Info
META: SP6.1.0 Electron – en-GB – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.1.0 Chrome/85.0.4183.121 Electron/10.1.5 Safari/537.36

### Actions Before Error
```
1606938577195: [Persistence] Save to DB 
1606938578173: [SimpleCounter] Increase SimpleCounter Counter Today 
1606938578174: [Persistence] Save to DB 
1606938579173: [SimpleCounter] Increase SimpleCounter Counter Today 
1606938579175: [Persistence] Save to DB 
1606938580171: [SimpleCounter] Increase SimpleCounter Counter Today 
1606938580173: [Persistence] Save to DB 
1606938580810: [Task] SetSelectedTask 
1606938581485: [SimpleCounter] Increase SimpleCounter Counter Today 
1606938581486: [Persistence] Save to DB 
1606938582173: [SimpleCounter] Increase SimpleCounter Counter Today 
1606938582174: [Persistence] Save to DB 
1606938583172: [SimpleCounter] Increase SimpleCounter Counter Today 
1606938583173: [Persistence] Save to DB 
1606938584172: [SimpleCounter] Increase SimpleCounter Counter Today 
1606938584173: [Persistence] Save to DB 
1606938584935: [Task] Move to archive 
1606938584937: [Persistence] Save to DB 
1606938584937: [Task] UnsetCurrentTask 
1606938584938: [Pomodoro] Pause Pomodoro 
1606938584938: [SimpleCounter] Set SimpleCounter Counter On 
1606938584938: [Persistence] Save to DB 
1606938585171: [SimpleCounter] Increase SimpleCounter Counter Today 
1606938585172: [Persistence] Save to DB 
1606938586171: [SimpleCounter] Increase SimpleCounter Counter Today 
1606938586172: [Persistence] Save to DB 
1606938587170: [SimpleCounter] Increase SimpleCounter Counter Today 
1606938587171: [Persistence] Save to DB 
1606938588173: [SimpleCounter] Increase SimpleCounter Counter Today 
1606938588176: [Persistence] Save to DB
```

**Comment by johannesjo** [comment]
Thank you very much for taking the time to open this up. Do you have some sort of syncing setup?

**Comment by odysseusart** [comment]
Yes, I am using dropbox. I set this up when I first installed the app several months ago, but the issue appeared sometime within the last two months or so - I cannot say exactly when.
Odysseas Stamoglou Visual Artist & Musician http://www.odysseusart.com 

    On Thursday, 3 December 2020, 19:05:11 CET, Johannes Millan <notifications@github.com> wrote:  
 
 


Thank you very much for taking the time to open this up. Do you have some sort of syncing setup?

**Comment by johannesjo** [comment]
Can you maybe try to create a fresh access token for dropbox from the settings?

**Comment by odysseusart** [comment]
Yes! That solved the problem, thanks!
Odysseas Stamoglou Visual Artist & Musician http://www.odysseusart.com 

    On Thursday, 3 December 2020, 19:30:49 CET, Johannes Millan <notifications@github.com> wrote:  
 
 


Can you maybe try to create a fresh access token for dropbox from the settings?

**Comment by johannesjo** [comment]
Im glad that it works now :)
