### ISSUE TITLE
Flickering triangle and crash

### ISSUE THREAD

**Issue by Moltenbrown** [johannesjo/super-productivity#716]
I'm using a computer running Ubuntu 20.04 with a RX580 graphics card using proprietary amd drivers. When I start Super Productivity, there is a flickering in the top left corner that forms a white triangle. This happens on and off as I continue using the program. After using it for at least 2 hours, it will suddenly crash, taking every other program I currently am working on with it. 

This doesn't happen on my laptop that's also running Ubuntu 20.04 but has Nvidia graphics.

**Comment by johannesjo** [comment]
Thank you very much for taking the time to open this up. I am unable to reproduce this nor do I have an idea how to fix it apart from maybe an electron update. Maybe this is related: https://github.com/electron/electron/issues/9413 ?

**Comment by Moltenbrown** [comment]
It’s not quite that but it’s along that vein.  I’ll take a video and send
it to you.

**Comment by johannesjo** [comment]
Thank you!

**Comment by Moltenbrown** [comment]
Most of the time, it’s white instead of grey but the behavior is the same.
