### ISSUE TITLE
Time Sheet Export Doubles Total Hours

### ISSUE THREAD

**Issue by tractionDave** [johannesjo/super-productivity#72]
## Your Environment

* Version used: 1.10.4 
* Operating System and version: macOS 10.13.3 
* Desktop Environment: 
* Browser Name and version: 

## Expected Behavior
When exporting to google sheets the {totalTime} should match the hours worked 

## Current Behavior
When exporting to google sheets the {totalTime} doubles the hours worked 
If I worked 1hr it exports 2hr if I work 4hr it exports 8hr

## Steps to Reproduce (for bugs)

1. Completed a set of tasks over an hour of time
2. Click finish your workday
3. Export to time sheet
4. add {totalTime} to one of the data sets

**Comment by johannesjo** [comment]
Should be fixed with next version. Thanks for reporting!
