### ISSUE TITLE
[Bug] Bookmarks can take too much screen space

### ISSUE THREAD

**Issue by EgorBakanov** [johannesjo/super-productivity#722]
### Environment
* Version used: 6.1.2
* Operating System and version: Android 10

### Expected Behavior
Bookmarks shouldn't take so much space on screen or at least should be scrollable.

### Current Behavior

<details>
  <summary>Screenshot</summary>

  ![Screenshot_20201205-215122_Super Productivity](https://user-images.githubusercontent.com/33174871/101247485-8991ad80-374c-11eb-9591-a480afede03e.jpg)

</details>

**Comment by johannesjo** [comment]
Thanks for reporting this. Makes sense to adjust this, though I'm not yet sure what the best approach is. Maybe we need to experiment a bit with this.
