### ISSUE TITLE
[FEATURE] Google tasks integration

### ISSUE THREAD

**Issue by Gvanderl** [johannesjo/super-productivity#723]
Hi,

I just discovered this app and I'm loving it so far. I've also been using Google tasks for a long time and I feel it would make the adoption painless if there was a Google tasks integration. This way I'm not giving up anything by switching, such as cross device compatibility or calendar integration, and I can keep the same workflow. This would also work well with Ubuntu's integration of Google Tasks in the default "To Do" app. 

The [google tasks API ](https://developers.google.com/tasks/reference/rest/?apix=true) should work for this usage. Hopefully this is possible.

**Comment by johannesjo** [comment]
Hey there! Thanks for opening this up. I am all for it but probably won't find the time to work on this myself. I gladly assist anyone who wants to give it a shot.

**Comment by Gvanderl** [comment]
Sounds good, I'll give it a go when I get the time.
