### ISSUE TITLE
App menubar icon too similar to Nextcloud's

### ISSUE THREAD

**Issue by ronilaukkarinen** [johannesjo/super-productivity#725]
Very often I mistakely think Nextcloud is superProductivity and vice verca because of the icon. Here's the screenshot:

<img width="244" alt="Screen-Shot-2020-12-07-11-43-02 46" src="https://user-images.githubusercontent.com/1534150/101335187-877d3b00-3881-11eb-9cf7-ac9fce4db5ac.png">

Can we do something about this?

**Comment by johannesjo** [comment]
Yes! We can replace it with the default app icon, which according to my girlfriend looks like the Rexona logo but I don't care :)

@papernoise you spent quite some time designing this. Would it be alright with you if we'd replace the icon with the default app icon?
