### ISSUE TITLE
[Feature] Add a "due date" option

### ISSUE THREAD

**Issue by budinero** [johannesjo/super-productivity#726]
It would be interesting to have the possibility to select select the due date in some task. It is different to "Schedule task": "Due date" is the date when the task must be finished, while "Schedule task" seems more appropriate to define the beginning of a task. 

A calendar to show tasks with scheduled and due dates will be interesting to.

**Comment by johannesjo** [comment]
Thanks for opening this up. Looks like a duplicate of #405 to me.

**Comment by budinero** [comment]
Thanks, did not find it in a quick search. Upvoted.
