### ISSUE TITLE
Improve consistency: "Move task to backlog until scheduled" missing from tagged task

### ISSUE THREAD

**Issue by ronilaukkarinen** [johannesjo/super-productivity#728]
In Today view when I schedule a task that is in a project the "Move task to backlog until scheduled" option is there and is automatically checked so the task will disappear from today view like it should, I like that. However if task is not in any projectsbut it has tag(s), the option "Move task to backlog until scheduled" is not there and the task will not go away after scheduling it. I have to manually right click task and select the crosed sun icon "Remove from My Day" to achieve the same than with project tasks.

Is there a reason for this inconsistent behaviour? I'd like tagged tasks to behave the same than project tasks in this situation.

**Comment by johannesjo** [comment]
Hey there!  You're talking about tasks that have an additional tag on top of the today tag, right? As you mention one reason for this is, that there are no backlogs for tags (#475). Another is that this would be "Remove from today list" rather than "Move task to backlog until scheduled" and it would only be available if there are any other tags at al (which might be confusing again)l. Personally, I have no clear preference for how this should be handled, but I am open to adjusting this if someone wants to give it a shot.

**Comment by ronilaukkarinen** [comment]
Right. "Remove from today list" sounds good. I'm used to the behaviour that if I schedule the task for later and not today it will instantly disappear from today view automatically and only pop back up when it's time for it. After all I won't do it today anyway so why show it. I'm sure you agree it's not logical to have it in Today view when it's not today's task. That's all.

**Comment by johannesjo** [comment]
Makes sense. Personally, my tasks always have a project, so I never run into this. Just out of interest and to better understand how the app is used: What are you using these projectless tasks for?

**Comment by ronilaukkarinen** [comment]
Mostly one-time things that I like to group in _some way_ but they are not part of any project. These tags can be "Errands", "Marketing", "Company development" or that contain for example answering to emails or for a lack of a English word those "extra" tasks you have to find time for like bugfixes or check ups here or there, again not part of any actual project or if they are there won't be enough tasks in the future so that creating a project for them would make any sense (I try to avoid creating projects that don't ever again have any tasks in them). I hope this clarifyes more about the use case!

**Comment by johannesjo** [comment]
Thanks for the explanation! I use a placeholder for these things called "Daily" which is assigned per default. Maybe this could also work for you until someone tackles this?
