### ISSUE TITLE
Where can I find the icon options for Simple Counter

### ISSUE THREAD

**Issue by osacn** [johannesjo/super-productivity#729]
Awesome project! 

Was creating as `simple counter` which works great, but I can't find the list of icons to choose from... Is that available somewhere?
Ideally it would be a dropdown where I could select. Happy to try to work on that if that's a good idea...

**Comment by johannesjo** [comment]
Hi there! Please use the [Q&A Section](https://github.com/johannesjo/super-productivity/discussions?discussions_q=category%3AQ%26A) for these types of questions.
