### ISSUE TITLE
Productivity Log

### ISSUE THREAD

**Issue by obizbu** [johannesjo/super-productivity#730]
## Problem Statement

I love this app. But I find myself wanting to track progress, not just plan for future activity. So if i have a task to do documentation, and a subtask to document a specific feature, I'd like to be able to say "I completed the outline", "I made a video script" "I recorded a tutorial" etc. Of course, I could do this by just changing the way I model tasks, but for me that's less than ideal.

## :grey_question: Possible Solution

The app already lets me input notes. But instead of notes, if I could enter 'log updates' similar to how I might enter comments on a task, that would help me better track my progress, and help me reflect later on what I did, and how I could improve. So the experience in-app would just be to go to the task or sub task and 'add update' comment that would be timestamped.
This could also be interesting, because the app could challenge the user every 10 minutes or so "what have you done so far" to make sure the user is being productive and not wasting time (even if they're not distracted) and be accountable for what they're actually achieving. 
At the end of the day you could also get a report to see all that you achieved, especially per the time worked. 
Also - for tasks that cross over into different days, this would effectively serve as a 'journal' of what you've done.

## :arrow_heading_up: Describe alternatives you've considered

Like I said, this could be done by just using subtasks to model that, but it limits how I use the app. SUre, if there were infinite nested tasks allowed, maybe that would work easier, but I think having 'updates' would be a smoother user experience.

**Comment by johannesjo** [comment]
Hey there! Thanks for taking the time to open this up. It's an interesting suggestion. Personally, I wouldn't need this for my workflow, but I leave this open for further discussion.
