### ISSUE TITLE
HTTP Proxy support for syncing

### ISSUE THREAD

**Issue by jdelker** [johannesjo/super-productivity#732]
## Problem Statement

In a network where Internet access is only available via HTTP-Proxy, syncing with Nextcloud fails, because SP obviously doesn't use system proxy, and neither offers an option to configure a proxy in the app (desktop version).

## :grey_question: Possible Solution
Either use system proxy (preferred option), or add configuration parameter for HTTP Proxy setting.

**Comment by johannesjo** [comment]
Hey there! Thanks for opening this up. Could you try if using this flag works:
https://github.com/electron/electron/blob/master/docs/api/command-line-switches.md#--proxy-serveraddressport
