### ISSUE TITLE
Show specific project list on startup

### ISSUE THREAD

**Issue by martinlanton** [johannesjo/super-productivity#734]
Hi!

I couldn't find the information, so forgive me if this has been asked before.

Is there a way to use a default project instead of the "Today" board when opening the app?
I've got a bunch of projects and I'd love to have the app just open on a specific project by default (ideally I'd love to have it open a specific project depending on the day of the week), instead of having it on the "Today" board, which we then need to populate (whereas the other projects are already populated).

Thanks in advance!
Martin

**Comment by papernoise** [comment]
No I don't think there is. I can't see it in the settings. You can only set a default project for new tasks.

**Comment by johannesjo** [comment]
Hey there! That's currently not possible, but I am open to adding this feature if someone wants to tackle this.

**Comment by martinlanton** [comment]
> No I don't think there is. I can't see it in the settings. You can only set a default project for new tasks.

That's what I thought, I did see the same about the default project for tasks, but nothing else. Thanks!

> Hey there! That's currently not possible, but I am open to adding this feature if someone wants to tackle this.

I would love to do it, unfortunately I don't think I'm at that level yet ^^ I can only write some gibberish in python ^^'
