### ISSUE TITLE
Support sync via OneDrive

### ISSUE THREAD

**Issue by joonro** [johannesjo/super-productivity#735]
## Problem Statement
Thanks for the great app. It would be great if OneDrive could be added as another sync option.

**Comment by donangel** [comment]
Can't you use OneDrive's ability to be connected via WebDAV?

Just one example: https://www.reddit.com/r/pop_os/comments/ccmdvz/how_can_i_configure_webdav_for_onedrive/

**Comment by joonro** [comment]
Thanks for the suggestion. I followed instructions [here](https://docs.microsoft.com/en-us/archive/blogs/robert_mcmurray/using-the-webdav-redirector-with-onedrive-part-1-standard-security), but I'm getting 404 error fron super-productivity.

**Comment by johannesjo** [comment]
Looks like a configuration issue. Unfortunately, I am not using One Drive so I can't give any advice. :-(

**Comment by joonro** [comment]
I see- I will report back if I find a successful configuration. Thanks!

**Comment by johannesjo** [comment]
> I see- I will report back if I find a successful configuration. Thanks!

That would be great! Thank you!

**Comment by joonro** [comment]
By the way, since it seems super-productivity uses a json file for data, would it be possible to add a functionality to sync via file system? Then a user can choose whatever syncing tool to sync. Sorry for the multiple questions!

**Comment by johannesjo** [comment]
> By the way, since it seems super-productivity uses a json file for data, would it be possible to add a functionality to sync via file system?

That's not really the case. Please refer to this issue (which might be what you want):
https://github.com/johannesjo/super-productivity/issues/690
