### ISSUE TITLE
IndexedDB INIT Error and InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.

### ISSUE THREAD

**Issue by Scroogeee** [johannesjo/super-productivity#737]
### Your Environment

* Version used: Web version
* Operating System and version: macOS Mojave 10.14.6
* Browser Name and version: Mozilla Firefox 84.0 (64-Bit)

### Expected Behavior
The website should open.

### Current Behavior
I get an error alert. If I close it, it pops up again.
After clicking ok a couple of times, I get a big error.

### Steps to Reproduce (for bugs)

1. Go to https://app.super-productivity.com/
2. Be patient and click ok on all alerts

### Console Output

I get the alert "IndexedDB INIT Error" multiple times.
Then I get:
<img width="1204" alt="Bildschirmfoto 2020-12-20 um 00 50 41" src="https://user-images.githubusercontent.com/30441849/102701983-84108900-425d-11eb-9a75-a5b39e916fe8.png">

**Comment by johannesjo** [comment]
Thank you very much for opening this up. Firefox is not a top priority as Chromium based browsers are the main target platform, but if somebody knows an easy fix, please let me know!

**Comment by fkohrt** [comment]
@Scroogeee I also had this issue but with Firefox 84.0.1 it's gone. Maybe check again?

**Comment by Scroogeee** [comment]
> @Scroogeee I also had this issue but with Firefox 84.0.1 it's gone. Maybe check again?

I can confirm the issue for Firefox 85.0

**Comment by fkohrt** [comment]
> @Scroogeee I also had this issue but with Firefox 84.0.1 it's gone. Maybe check again?

@Scroogeee Yeah, I previously might have loaded an older app version from the cache. Doesn't work for me as well (FF 85).

**Comment by fkohrt** [comment]
@Scroogeee @johannesjo I believe this can be resolved by using a fresh Firefox profile, see webcompat/web-bugs#68223

**Comment by Scroogeee** [comment]
> @Scroogeee @johannesjo I believe this can be resolved by using a fresh Firefox profile, see [webcompat/web-bugs#68223](https://github.com/webcompat/web-bugs/issues/68223)

Resolved with a fresh chrome instance without private mode. Didn't try with non-incognito firefox though.

**Comment by fkohrt** [comment]
> Resolved with a fresh chrome instance

I think Chromium always worked, or at least I'm not aware of any IndexedDB related issues with Chromium. But the great news is that it should now work with Firefox as well. So i suggest closing this issue unless you encounter the problem again.

**Comment by Scroogeee** [comment]
How can I turn off the private-only browsing mode for firefox?

**Comment by fkohrt** [comment]
Depending on why you are automatically using the private mode, the relevant setting might be under Preferences > Privacy & Security > History > Use custom settings for history > Always use private browsing mode. Uncheck it and restart Firefox.

Relevant Mozilla Support page: [Private Browsing - Use Firefox without saving history](https://support.mozilla.org/en-US/kb/private-browsing-use-firefox-without-history#w_can-i-set-firefox-to-always-use-private-browsing)

**Comment by Scroogeee** [comment]
Doesn't happen with private mode disabled
