### ISSUE TITLE
a shortcut to create scheduled tasks

### ISSUE THREAD

**Issue by FuqiX** [johannesjo/super-productivity#739]
## Problem Statement
I use super productivity as my weekly task planner and I use task scheduling a lot. Currently, there is syntax for adding labels, projects and time estimation when creating a task. However, there is no syntax for scheduling tasks.

## :grey_question: Possible Solution
![Screenshot_2020-12-22_15-40-39](https://user-images.githubusercontent.com/54043294/102906173-2900b100-446c-11eb-9cd8-f51cbdce5a3b.png)
I hope to be able to add task scheduling info using text. For example 

when creating a new task, I can use:
> some tasks +projectA #someTag 0m/1h due:Tuesday 9:00

or 
> some tasks +projectA #someTag 0m/1h on:next Friday

Which schedules the task to Tuesday 9:00/next friday.

## :arrow_heading_up: Describe alternatives you've considered
The alternative solution is to click and select the schedule. but it's not very convenient when creating a large amount of tasks.

## :heavy_plus_sign: Additional context
I've seen similar functionality in task warrior. See documentation [here](https://taskwarrior.org/docs/using_dates.html)

**Comment by johannesjo** [comment]
Thanks for the suggestion. I gladly accept a PR if someone would be willing to tackle this. Personally I deal with this by creating the task and then pressing "S" for schedule. Here you can select what you need via the arrow keys..

**Comment by JLuisGT** [comment]
Is this already implemented? 

I also think it would be useful :)

**Comment by johannesjo** [comment]
@JLuisGT no :)
