### ISSUE TITLE
Tray icon does not really work with dark themes

### ISSUE THREAD

**Issue by javierfolcini** [johannesjo/super-productivity#741]
### Your Environment
* Version used: 6.3.0.0 snap
* Operating System and version: Ubuntu 20.04 LTS
* Desktop Environment: Gnome (standard theme)

### Expected Behavior
Tray icon should be visible even with dark gnome panel (standard)

### Current Behavior
Tray icon is not visible with dark gnome panel (standard)
![imagen](https://user-images.githubusercontent.com/54267441/102990982-9ec25680-4518-11eb-800a-0664539fe05d.png)

### Steps to Reproduce (for bugs)
1. set up environment
2. run superproductivity
3. turn on tray icon

### Notes
Researched a bit and snaps currently don't have a way of dynamically changing the icon depending on the desktop's colour scheme. If you think this is worth changing you should use a colour that works for both dark and light backgrounds. Perhaps someone with some design knowledge can provide better insight.

**Comment by johannesjo** [comment]
Hi there! Thank you very much for digging into this! Currently I am pretty busy with the new calendar feature, but I gladly review any PRs dealing with this. As you say: Ideally this should be fixed on snaps side of things.

**Comment by mkpaz** [comment]
Same here, did some investigations. This is not a snap problem (I use AppImage). SP uses [`nativeTheme.shouldUseDarkColors`](https://github.com/johannesjo/super-productivity/blob/1d6862694d6d866e9bf9b4f782cdfc430ff1f73e/electron/indicator.ts#L55) prop to determine which icon (light or dark) variant to show. In Gnome 3 this prop value is only _true_ when dark **window theme** is set to use, but top panel color doesn't depend on window theme, it depends on **Gnome Shell theme**.

![image](https://user-images.githubusercontent.com/25181998/103439112-ae961500-4c53-11eb-912f-056b0a4677aa.png)

There's the problem, one can use light window theme  for apps and dark shell theme for desktop (this is actually default). I believe `shouldUseDarkColors` is only intended to determine dark mode for application itself, not for tray. Does it work on Windows? Win 10 defaults is black panel and light window theme too.

There's also relevant [issue](https://github.com/electron/electron/issues/25478) in electron bug tracker. Seems like [Template Image](https://www.electronjs.org/docs/api/native-image#template-image) is the way to go for MacOS. As for other OS / DE, there's no such API, so it either should be an additional code check for any particular DE or maybe an additional CLI key? What do you think?

**Comment by johannesjo** [comment]
Thanks for digging into this @mkpaz!!! My personal opinion is that ideally Ubuntu/Gnome should support this in a similar fashion as Mac OS!! :) There are no good reasons to for mixing things up here and to rant just a little bit: The theme system is unnecessarily Frankensteinish. If there is a smart workaround for Linux DEs I am open for adding it, but I'd like to avoid complicated and OS specific solutions as much as possible. Not exactly sure how I made it work on my system, but it is possible by fiddling with your theme settings.

**Comment by mkpaz** [comment]
@johannesjo You're probably right, but I don't think Gnome (or any other Linux DE) will support template images anytime soon. I also agree that possible solution shouldn't be too complex and hardcoding preferences for any specific environment isn't the best option. Sadly, there's nothing smart one could do with that situation, because Electrons `nativeTheme` is only wrapper around Chromiums [nativeTheme](https://chromium.googlesource.com/chromium/src/+/master/ui/native_theme/native_theme.h) and Chromium doesn't need or care about tray support for obvious reasons. So, it's either changing icons colors that would be suitable for both light and dark tray or code tweaks. I'd suggest to add compatibility CLI arg, smth like `--compat.forceDarkTray`. Unlike OS specific solutions it has zero maintenance cost Would accept such PR?

**Comment by johannesjo** [comment]
> I'd suggest to add compatibility CLI arg, smth like `--compat.forceDarkTray`. Unlike OS specific solutions it has zero maintenance cost Would you accept such PR?

That's a very good suggestion. Makes sense to me and a PR would be very welcome!
