### ISSUE TITLE
Evaluation sheet not being shown regardless of setting

### ISSUE THREAD

**Issue by javierfolcini** [johannesjo/super-productivity#742]
### Your Environment
* Version used: 6.3.0.0 snap
* Operating System and version: Ubuntu 20.04 LTS
* Desktop Environment: Gnome (standard theme)

### Expected Behavior
Evaluation sheet should be shown after clicking on 'FINISH DAY' button if 'Hide evaluation sheet on daily summary' is not ticked under 'Evaluation & Metrics' settings.

### Current Behavior
Evaluation sheet is not shown after clicking on 'FINISH DAY' button even though 'Hide evaluation sheet on daily summary' is not ticked under 'Evaluation & Metrics' settings.

![imagen](https://user-images.githubusercontent.com/54267441/102991910-7b001000-451a-11eb-823c-06db9ed3f773.png)

### Steps to Reproduce (for bugs)
1. set up environment
2. run superproductivity
3. finish day

### Console Output
![imagen](https://user-images.githubusercontent.com/54267441/102992560-b64f0e80-451b-11eb-93f8-f111b7f9fe2d.png)

### Error Log (Desktop only)
Fresh install, nothing

### Notes 
I tried deleting the snap and even any residual files that may remain. I also tried saving and closing before testing, changing the value and saving, etc.

**Comment by johannesjo** [comment]
Hey there! The evaluation sheet is currently only shown for projects. This is likely to change in the however: #520

**Comment by javierfolcini** [comment]
ahhhhhhhh, that's odd, thanks!

**Comment by johannesjo** [comment]
> that's odd, thanks!

Yes I agree. It's like this due to historic reasons (everything was project centered back then) rather than a conscious design choice :)

Unfortunately that also means that it isn't too easy to do this.
