### ISSUE TITLE
iOS/Android App?

### ISSUE THREAD

**Issue by creepinson** [johannesjo/super-productivity#745]
Can you make an android/ios app for this? I see that there is a macos verson but not a ios one :(

Really nice app overall, I love that it has gdrive sync and a break timer :D

**Comment by creepinson** [comment]
Oops, didn't see the other issues beforehand and I just installed the PWA and it seems to be working although the ui isnt perfect.

**Comment by creepinson** [comment]
Welp, I can't sync to google drive because it says it requires a sync file and I don't know where to put it.

**Comment by johannesjo** [comment]
Hello! Could you please ask your question here:
https://github.com/johannesjo/super-productivity/discussions

Thank you!
