### ISSUE TITLE
Search Feature for Tasks

### ISSUE THREAD

**Issue by PaulWegmann** [johannesjo/super-productivity#748]
Hello,

I wondered whether it is possible to search through all of my created tasks.

Keep up the good work! I am amazed by your project and enjoy it a lot.
Also, is it possible to donate without becoming a monthly sponsor?

Thanks

**Comment by johannesjo** [comment]
Hey there! Thanks for opening this up #547

**Comment by donangel** [comment]
I imagine "Incremental Search" functionality as follows:

The user presses the "Incremental Search" shortcut. For example Cmd+I
A popup appears, similar to what we have when we need to assign time to a task.
We start typing. The result is automatically filtered, matching all tasks, which contain the search term
The first match is focused by default. Arrow Down / Up moves the focus up/down. Pressing Enter closes the search box and jumps to the task, which was selected.

**Comment by johannesjo** [comment]
Thanks for your input!
