### ISSUE TITLE
Pomodoro breaks unexpectedly stop

### ISSUE THREAD

**Issue by AforemetionedAffirmation** [johannesjo/super-productivity#753]
### Your Environment
* Operating System and version: Windows 10 10.0.19041

### Expected Behavior
The program should count a 5 minutes break.
The program should count a 20 minutes break.

### Current Behavior
All of the sudden after maybe a couple of minutes it says that that the break is over and I should go back to work.
It is a bit difficult to tell of this error when it's time for the 5 minute break but it's pretty obvious on a 20 minute break.

It doesn't happen every time. I think there's a connection between this error and the fact that sometimes I skip breaks.

### Console Output
<img width="392" alt="Screenshot 1" src="https://user-images.githubusercontent.com/76708161/103250149-24139400-497b-11eb-8bc7-46e8e452bcda.png">
(no idea if this is helpful or not)

**Comment by johannesjo** [comment]
Hi there! Thanks for opening this up! I gladly review any PR if someone wants to give fixing this a shot.
