### ISSUE TITLE
Move task counter on the right side of tag name

### ISSUE THREAD

**Issue by mkpaz** [johannesjo/super-productivity#754]
## Problem Statement

Currently, task counter overlaps tag (and Today) icons. It leads to the following consequences. Icon itself is indistinguishable and looks pretty ugly. Task counter font size is too low, which creates a problem for the people with impaired eye vision. There is no much sense in icon if it's not visible, well, at least most of it.

![2020-12-31_10-20](https://user-images.githubusercontent.com/25181998/103397912-be2e3480-4b53-11eb-808f-ff7d47fdf481.png)

## :grey_question: Possible Solution

Move counter on the right side, e.g like Todoist

![image](https://user-images.githubusercontent.com/25181998/103398122-b753f180-4b54-11eb-9e8e-71defb31926d.png)

**Comment by johannesjo** [comment]
Thank you very much for the suggestion. I have been struggling to find the best approach for this and the current implementation certainly isn't perfect. I very much like your suggestion (also coloring the project/tag icons seems nice).
