### ISSUE TITLE
Icons in offline mode

### ISSUE THREAD

**Issue by Gjum** [johannesjo/super-productivity#756]
The browser app works well enough offline, but the icons show as their name text instead of actual icons, which is very disorienting.

### Your Environment
* Version used: https://app.super-productivity.com/ with runtime.076604685350bc36956d.js / main.8f76fc2db3a580c13601.js
* Operating System and version: Arch Linux 5.8.14 x86_64
* Desktop Environment: i3
* Browser Name and version: Chromium 86.0.4240.111 (Official Build) Arch Linux (64-bit)

### Expected Behavior
After installing the website as a browser app, the icons should display when being offline.

### Current Behavior
The icons show as large cut-off text of their names, sometimes rotated, instead of as icons.

![top right](https://user-images.githubusercontent.com/2612164/103460960-021f6600-4d1b-11eb-9938-f69631100564.png)
![bottom right](https://user-images.githubusercontent.com/2612164/103460964-05b2ed00-4d1b-11eb-99a1-6c9e00190f28.png)

### Steps to Reproduce (for bugs)
1. visit https://app.super-productivity.com/
2. install browser app
3. go offline
4. reload app

### Console Output

```
main.8f76fc2db3a580c13601.js:1 Initial Dialog Error
main.8f76fc2db3a580c13601.js:1 w {headers: h, status: 0, statusText: "Unknown Error", url: "https://app.super-productivity.com/news.json?ngsw-bypass=true&no-cache=1609601942552", ok: false, …}
polyfills.250ebd3af63450554a58.js:1 GET https://app.super-productivity.com/news.json?ngsw-bypass=true&no-cache=1609601942552 net::ERR_NAME_NOT_RESOLVED
inject.js:372 GET https://app.super-productivity.com/favicon.ico net::ERR_NAME_NOT_RESOLVED
styles.792c93fecd771c46543e.css:1 GET https://app.super-productivity.com/MaterialIcons-Regular.cff684e59ffb052d72cb.woff2 net::ERR_ABORTED 504 (Gateway Timeout)
/#/tag/TODAY/tasks:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://app.super-productivity.com/MaterialIcons-Regular.83bebaf37c09c7e1c3ee.woff
styles.792c93fecd771c46543e.css:1 GET https://app.super-productivity.com/MaterialIcons-Regular.83bebaf37c09c7e1c3ee.woff net::ERR_ABORTED 504 (Gateway Timeout)
/#/tag/TODAY/tasks:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://app.super-productivity.com/MaterialIcons-Regular.5e7382c63da0098d634a.ttf
styles.792c93fecd771c46543e.css:1 GET https://app.super-productivity.com/MaterialIcons-Regular.5e7382c63da0098d634a.ttf net::ERR_ABORTED 504 (Gateway Timeout)
```

### Error Log (Desktop only)
N/A (browser)

**Comment by johannesjo** [comment]
Hey there! Thanks for opening this up. Makes a lot of sense to adjust this and should be pretty straightforward too.

**Comment by sandorex** [comment]
I have this as well and makes it quite unusable as an app

**Comment by Gjum** [comment]
looks like offline icons are working now, thanks.

**Comment by johannesjo** [comment]
Yes, this should be fixed with the latest version.
