### ISSUE TITLE
Adding worklog to Jira is converting starts to Zulu time

### ISSUE THREAD

**Issue by cufiler** [johannesjo/super-productivity#757]
### Your Environment
* Version used: 6.3.2
* Operating System and version: MacOs 11.1
* Browser Name and version: Application
* Using Jira server 8.10
### Expected Behavior
The started time of a worklog should be expressed in local time.

### Current Behavior
When I add a worklog to Jira the dialog window that shows worked time, started and comment... shows the started time at Greenwich TimeZone.
For instance, if you add a new subtask to a task imported from Jira and called it "new subtask created at 10:00" (+01:00, in my case), start this subtask and mark as done a few minutes after. The dialog window will show that subtask started at 09:00 because it converts '...10:00+01:00' to '...09:00Z' and removes tailing 'Z'.

### Steps to Reproduce (for bugs)
1. Configure Project to open dialog when task and subtask is done
2. Start a subtask
3. Mark it as done, dialog opens showing a Started date using Greenwich timezone

Digging into code, I think the problem (if there is one) is in src/app/features/issue/providers/jira/jira-view-components/dialog-jira-add-worklog/dialog-jira-add-worklog.component.ts

Original code convert timestamp to Z timezone (using toISOString() )
```javascript
  private _convertTimestamp(timestamp: number): string {
    const date = new Date(timestamp);
    date.setSeconds(0, 0);
    const isoStr = date.toISOString();
    return isoStr.substring(0, isoStr.length - 1);
  }
```

I think it can be resolved using moment.
```javascript
  private _convertTimestamp(timestamp: number): string {
    const date = moment(timestamp);
    const isoStr = date.seconds(0).local().format();
    return isoStr.substring(0, 19);
  }
```

**Comment by johannesjo** [comment]
Thank you very much for digging into this! To be honest I always tend to get somewhat confused when it comes to handling timezones. As you found the fix already, would you mind opening up a PR with it? That would be very welcome!

**Comment by johannesjo** [comment]
Thanks again for your help!
