### ISSUE TITLE
Using automatic sync to file  makes the application unresponsive

### ISSUE THREAD

**Issue by ArjenR** [johannesjo/super-productivity#76]
## Your Environment

* Version used: 1.10.12
* Operating System and version: WIndows 10
* Desktop Environment: na
* Browser Name and version: na

## Expected Behavior
Enable autosync to file and set the location to a local folder (which later is to be replicated by Nextcloud)
Disable auto backup to Google drive
Disable auto authenticate
Revoke auto authenticate.
Application behaves normal and will sync to local file, to sync to Nextcloud.

## Current Behavior
After createing the sync file:
Application starts to refresh itself continuosly. Console shows no errors. Verbose mode some yellow warning flash, but it is a bit too fast. Application just reloads and reloads.

The only way to recover is to rename the folder in which the sync.json file resides.

## Steps to Reproduce (for bugs)

1. Enable expermimental sync
2. Set a path like C:\synfolder\subfolder'\
3. Wait or restart the application and watch the application flash.
4. Kill using taskmanager
5. Rename subfolder
6. Start super productivity again.
7. Disable autosync.

**Comment by johannesjo** [comment]
Thanks for reporting. I think I found the issue and I'll provide a patched version with a workaround soon. I will need to spend some more time to make this feature fully functional again though.

**Comment by johannesjo** [comment]
@ArjenR Could you please check if the issue is solved for you now?

**Comment by ArjenR** [comment]
@johannesjo  Sure, no problem. I will have to wait for packages (will switch from snap to appimage, since those are generated from the build), I am afraid I don't have time to build from source / follow HEAD.

**Comment by johannesjo** [comment]
The updates should be available via snap as well this time :)

**Comment by ArjenR** [comment]
Hi Johannes. 
 I have been testing, but not much.

I am using nextcloud for syncing. I am under the impression that the sync is incomplete.  I had some issues in getting the 2nd (linux) client to start to sync at all/ I expected it to start reading the sync.json file when configuring the location and restarting the client. But it did not. 

I pasted the contect in the import and then changed the path for sync.json and got it to sync.

What I observe is that it does not get the last update whether a task is ready or the time spent. This could be the time window for Nextcloud. This needs some more testing. 

Can you tell me how it is intended to setup the sync, would I start from scratch on the 2nd client?

**Comment by johannesjo** [comment]
Thanks for getting back to me and your efforts to evaluate the issue. 

Sync is quite a young feature so setting it up for the first time is not as easy as it should be. What you do is start the new instance and then configure automatic sync there. From there it should always pull the complete data in the sync.json and load it to the app. There is no complex merging logic or something of the sort. 

Reloads are not done any more, so after a message pops up, the data should be there. The sync.json normally should be a 1:1 copy of the localStorage, so maybe that's a good starting point for debugging. There are some properties which are not saved to the local storage, but the task data should be there.

Syncing is done every 10 seconds. You should find most of logic here:
super-productivity/app-src/scripts/main/global-services/local-sync-s.js
