### ISSUE TITLE
Can't delete one of my projects

### ISSUE THREAD

**Issue by RichStone** [johannesjo/super-productivity#761]
For some reason the delete Icon is grayed out for me and I can't click on it to delete one of my projects: 

![image](https://user-images.githubusercontent.com/15954169/103559673-cf11d980-4eb6-11eb-9df6-898856b343e1.png)

**Comment by johannesjo** [comment]
Thanks for opening this up. Currently it's not possible to delete the currently active project. See #581

**Comment by johannesjo** [comment]
f
