### ISSUE TITLE
Optional Periodic Confirmation/Reminder of the Engagement in Running Task

### ISSUE THREAD

**Issue by avramach** [johannesjo/super-productivity#765]
## Problem Statement
For the hardcore procrastinator ,after starting a task ,there is a tendency to drift off into non-productive web browsing.
Especially in desktop setups where browsers or other  full screen apps are utilized due to which no indication of the running task timer comes to the individuals attention, only for regret later of wasted time.
Inorder to remind the individual to get back to work that matters,suggesting a periodic pop up which asks for confirmation of the user if the task is still on going.

## :grey_question: Possible Solution
Onscreen pop up ,with description of current running task ,time spent and Task in progress ->confirmation buttons "Yes", "No", which pops up at configurable periodic intervals. 

## :arrow_heading_up: Describe alternatives you've considered
Each Tasks to be split to periodic intervals and max time limit set during task creation

## :heavy_plus_sign: Additional context
#405

**Comment by johannesjo** [comment]
Hey there! I am open for accepting PRs on this. Imho it should be disabled by default and would need to be activated through the settings.
