### ISSUE TITLE
Add option to allow auto-unfolding of the Projects folder on the sidebar 

### ISSUE THREAD

**Issue by therealgorgan** [johannesjo/super-productivity#767]
## Problem Statement
Every time a sync occurs, the page refreshes and then the Projects list is folded again. I have to unfold it every time. 
![image](https://user-images.githubusercontent.com/33201476/103760293-82bfba00-4fda-11eb-930f-718f6066486d.png)

## :grey_question: Possible Solution

Would be nice if the state of the fold/unfold persists through a refresh

## :arrow_heading_up: Describe alternatives you've considered
Another option might be to add an option auto-unfold on-load 

## :heavy_plus_sign: Additional context
Thank you for your consideration! Love the app so far. 👍

**Comment by johannesjo** [comment]
Makes sense! Maybe - as a more simplistic solution - we can also just persist it's last state through application restarts using localStorage. Should be pretty straightforward to implement I think.

**Comment by therealgorgan** [comment]
Sounds good, thanks for considering!
