### ISSUE TITLE
Won't start in Fedora (QubesOS)

### ISSUE THREAD

**Issue by aorjql** [johannesjo/super-productivity#768]
Hello,
I installed Super Productivity in Qubes OS into the Fedora 32 Template VM.
I have also installed qubes-snapd-helper and snapd.

Super Productivity runs correctly in the Fedora 32 Template VM. However, when trying to launch it from an App VM derived from this template, the app just won't launch, whether I'm trying to launch it from the terminal or the Qubes app shortcuts. There's no error message.

What can I do?

Thank you.

**Comment by johannesjo** [comment]
I have no experience with QubesOS so I am afraid, that I have no idea what might be causing this. Might be that QubesOS just doesn't like electron apps? But I would be surprised if there isn't a way to launch the app somehow. You also might wanna try running `journalctl -f` before trying to start the app. There should be at least some output.

**Comment by aorjql** [comment]
Thank you. As I mentioned, I manage to run the app on the Fedora 32 Template VM, but not in VM derived from that. I assume the problem comes from the way Qubes manages persistence across VMs derived from templates. Here is the output of the command you suggest running:

[2213]: applications/superproductivity_superproductivity.desktop not found in /home/user/.local/share:/home/user/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop
Jan 06 16:56:09 Finances systemd[1454]: Starting Mark boot as successful...
Jan 06 16:56:09 Finances systemd[1454]: grub-boot-success.service: Succeeded.
Jan 06 16:56:09 Finances systemd[1454]: Finished Mark boot as successful.
Jan 06 16:56:23 Finances xdg-desktop-por[2012]: Failed to get application states: GDBus.Error:org.freedesktop.portal.Error.Failed: Could not get window list
^C
