### ISSUE TITLE
Zip file missing from 1.10.13 release

### ISSUE THREAD

**Issue by LouisStAmour** [johannesjo/super-productivity#77]
I went to go update the homebrew cask again, and it failed because the mac zip file was missing. The primary reason folks used disk images was to match legacy distribution models, which always distributed files on disk, and you'd insert the disk and have to drag-and-drop the app's icon from the disk to a shortcut for the Applications folder.

Since then, Mac distribution has flipped. Most apps I can think of download themselves as zip files (which can auto-unzip in Safari). and when run from downloads, the better apps will copy themselves into the Applications folder or will show a warning that they run best from /Applications rather than ~/Downloads. For example: https://github.com/potionfactory/LetsMove

**Comment by johannesjo** [comment]
Thank you very much for reporting and taking your time to update the cask. Not sure what happend there. Electron Builder is unreliable at times unfortunately :(

I'm working on some bigger patches for the sync process at the moment. Once I'm done with that, I'll publish a new update and this time I will double check if the zip is present or not.

**Comment by johannesjo** [comment]
I published a new version. The mac zip is present this time :)
