### ISSUE TITLE
Duplicate tasks when set to repeat

### ISSUE THREAD

**Issue by aspieln3r** [johannesjo/super-productivity#770]
### Your Environment

* Version used: 6.1.2-1
* Operating System and version: arch linux
* Desktop Environment: xfce

### Expected Behavior

When setting some tasks as repeating in a project, if I couldnt finish the task in a day, when I open the app next day, there should be only one entry of that task. I'm using repeating tasks to remind me of some tasks that I plan to do eveyday, like revising subjects on that day's timetable. But if I fail to do that one day, there shouldn't be two entries of the same task next day. 
### Current Behavior

Currently, if I set a task to repeat everyday and couldnt finish the task one day, and open the app next day, there will be two entries of the same task in the task list of that project

### Steps to Reproduce

1.make a project and add tasks
2.set a task to repeat everyday
3.finish day without finishing that task
4.open app on next day and there will be two entries of the same task

Whats the correct way to use superproductivity for chores? If I make a repeating task, its not adding them to 'today' section automatically so that I'll get reminded to do it. I have to manually go to a project and check for any repeating task that I have to do today. Am I using it wrong? Is there a way to see all the repeating tasks that are set to happen today anywhere?

**Comment by aspieln3r** [comment]
@johannesjo Should I change it from bug report format to a new feature request for improved chores support?

**Comment by johannesjo** [comment]
Hey there! Thanks for opening this up. Personally I think the current behavior is more predictable than what you suggest. A repeatable task is created when you open the app on the day for which it was configured for. An old instance might be it's yesterdays counterpart, of which the user just forgot to set it on done or it actually wasn't in which case the user should decide what to do with it. I agree that it is maybe not completely ideal neither. I might be wrong too of course, so I am leaving this open for discussion.

**Comment by aspieln3r** [comment]
Aside from that, is there a way to view all repeating tasks that was set to happen today in a place?

**Comment by johannesjo** [comment]
> @johannesjo Should I change it from bug report format to a new feature request for improved chores support?

I think it's fine this way. Thank you.



> Aside from that, is there a way to view all repeating tasks that was set to happen today in a place?

Currently not, but I am working on a new and very sexy calendar feature. This might not make it to the first iteration, but is definitely something that makes a lot of sense to have. 

> Like a feature to automatically add them to the 'today' section.

You can already do that by going to the repeat config dialog and adding the "Today" tag there.
