### ISSUE TITLE
[Feature] Consider making Finish Day feature optional

### ISSUE THREAD

**Issue by mkpaz** [johannesjo/super-productivity#771]
## Problem Statement

As much I love time tracking function I simply can't use Finish Day feature. It just won't fit my workflow. I'm setting up tasks for the day on morning and just start working. I like having work log to remember my earlier achievements sometimes, but reflexing on daily basis? Nope. Sadly this feature absolutely mandatory. By that I mean that application punishes me for not using it. While I'm using SP my every day starts from manually removing Today tag from the tasks I've completed yesterday. You have no idea how annoying is that :-(  I don't know why, but Finish Day button doesn't remove earlier completed tasks from Today view.

Seriously speaking, I have no idea what this feature is supposed to do, because it's not even documented. It doesn't ask any confirmation. Like "Hey man, this action of yours will lead to X, Y, Z. Are you sure?" What if I finish the day twice? Thrice? What if don't remember did I already finished it or not. There's no indication for that. How I'm supposed to finish the previous day if I got no notifications or banners? How I'm supposed to know what days have been finished and what haven't been? What if I've already finished the previous day, but done some more tasks later on that day and want set them as completed on the next day?

It's tricky to implement such a feature right. But what I know is that I don't like to be punished for not following feature I don't like to follow. 

## :grey_question: Possible Solution

Setting up Today tag seems like a mistake. No other service I know do that. They all just set due date (schedule task for today) and today tasks are just tasks filtered by current date. Then if user clicks on Finish Day button you could just show him tasks filtered by completed date and the amount of time spent to each of that tasks. So Finish Day should just display work log for the one single day - yesterday. This way one could use it and one couldn't, because when finish day button just leads to log it will do no harm. 

I'd also love to see this button removed from project view. It should be either made global or stick to the Today page.

**Comment by Rodeo-McCabe** [comment]
I agree the feature needs work. I also have a gripe with the Today tag. If you didn't know, there is a setting to stop the Today tag from being automatically added to new tasks, which saved me some frustration.

>I'd also love to see this button removed from project view. It should be either made global or stick to the Today page.

Definitely agree it should be global. I typically work on more than one project in a day, and I also have various tasks that are not part of a project but are organized by tags. As it is now, I have to go to each project and tag that I worked on and click Finish Day on each of them. That means I also have to do a separate evaluation for each one, which means a lot of repetition and redundant data. Furthermore, you cannot see metrics for tags, they are only tracked by project. All of this amounts to flawed data, and it makes it impossible to see how I'm doing over the whole day, let alone the past week or month.

I think making the Finish Day feature global, along with metrics, would solve all these problems.

**Comment by johannesjo** [comment]
Thanks for your input @Rodeo-McCabe I totally agree that we should make finish day and everything related a global feature.

**Comment by johannesjo** [comment]
FYI: Finish day is now a global feature.

**Comment by Rodeo-McCabe** [comment]
Wonderful, thanks! I've not used the software for a while, but I'm looking forward to testing this.
