### ISSUE TITLE
Gitlab issue url wrong

### ISSUE THREAD

**Issue by b0c1** [johannesjo/super-productivity#772]
### Your Environment

* Version used: master branch
* Operating System and version: windows 10
* Desktop Environment: 
* Browser Name and version: firefox

### Expected Behavior
open gitlab issue in the browser

### Current Behavior
Gitlab issue link wrong when the project id set.

### Steps to Reproduce (for bugs)
1. Set project ID instead of url
2. Fetch Gitlab issues to backlog 
3. open browser

**Comment by johannesjo** [comment]
Thanks again for your help!  :)
