### ISSUE TITLE
Can't find evalutation sheet

### ISSUE THREAD

**Issue by PaulWegmann** [johannesjo/super-productivity#774]
Hello,

On some previews and pages there was said to be some evaluation sheet. In the settings there is also the option to hide the evalution sheet on daily summary.
However, I have disabled this option and haven't seen the evalution sheet in my daily summary.
Is this a bug?
I am using version 6.3.3.

Thanks

**Comment by johannesjo** [comment]
Hi there! Thanks for the question. Best place to ask something would be the discussions page (https://github.com/johannesjo/super-productivity/discussions). This way it's easier for other people to find.

To give you a quick answer: The evaluation sheet is currently only available on a project level and per project basis. So you need to select a project and once there you can see the Evaluation sheet on the "Finish day" page. 

I intent to make this a global feature instead, once I find the time to do so :)
