### ISSUE TITLE
Output to CSV

### ISSUE THREAD

**Issue by mbostanara** [johannesjo/super-productivity#777]
Hello,

As I would like to analyze all of my time tracking data for last year, I need to export the program data to a CSV file with the following columns:
1. task
2. project
3. date
4. duration

I was wondering if getting such output is possible in Super Productivity? If not, would you guide me how can I convert the current .Json output to the data table CSV format I mentioned?

Thank you

**Comment by johannesjo** [comment]
Hi there this is more of a question. Could you ask it in the discussion section please?
https://github.com/johannesjo/super-productivity/discussions/categories/q-a

**Comment by mbostanara** [comment]
Hi there,
Thank you for your reply and sorry that I asked it here. I managed to find a way to export time tracking data monthly (from 'worklog' menu). However, I could not include the project name of each task, which I fixed it manually for now.

Thanks

**Comment by johannesjo** [comment]
No worries and thanks for the extra effort of posting the question under the q&a section!
