### ISSUE TITLE
Improve handling of desktop devices with touch

### ISSUE THREAD

**Issue by WveedeeTee** [johannesjo/super-productivity#778]
This seems to be a Windows problem.

I am new to this whole thing, but I want to learn. So I tried troubleshooting, all I could figure out is that this is an issue in Windows. On Linux (PopOS) I can change the Task description after creating it. In windows I cannot. The issue shows up in the Microsoft store version and in the browser in Windows. 
It was temporarily fixed with the recent update, but is broke again after a restart.

**Comment by johannesjo** [comment]
Thanks for opening this up! Could you maybe elaborate a little what you mean by "task description" and "does not work"?

**Comment by WveedeeTee** [comment]
![superproductivity](https://user-images.githubusercontent.com/77270358/104699161-9a9de900-5712-11eb-82ba-8643c70ce7f2.png)
The title "Persoonlijke Administratie\" cannot be changed. In linux when you hover over it the cursor changes and I can type a new title. This does not always work..

**Comment by johannesjo** [comment]
I am unable to reproduce this on Windows as well... What version of the app and Windows are you using? You also need to click the task to edit it, but I suppose that is what you are doing.

**Comment by WveedeeTee** [comment]
6.1.2, although it works now. I am thouroughly confused, it is only
sometimes broken. If it happens again I shal re-open the issue.

Thanks for your help and congratulations on a very usefull program.

**Comment by johannesjo** [comment]
I am glad that it works now for you! Pretty weird indeed! Maybe you can gather some more information by looking at the console output (which can be evoked via Ctrl+Shift+i) the next time this happens?

**Comment by AminTaheri23** [comment]
I have this issue too. I installed the newest version, 6.33, and the issue remains. I couldn't find any solution. 
I have Windows 10 Home edition (I have a touchscreen)

I found a hack to alleviate the problem. You can resize the window to a vertical rectangle, and the application arranges the UI to match a mobile-like version. (Or you can activate mobile view from the dev tools). Then after clicking on a task. You can change the title by clicking on it. 
![image](https://user-images.githubusercontent.com/30533823/106781038-d961f780-665d-11eb-88c9-1f5685068422.png)

**Comment by johannesjo** [comment]
The touchscreen part explains it! The current logic checks whether it is on a touch device and handles the UI like it is on mobile.

**Comment by AminTaheri23** [comment]
I think that the desktop UI should be the same as the mobile UI. 

My point is how frequently an end-user is going to edit the title of a task?  I suppose it is not that often. So editing the title can be in the additional details of the task and not in the main window. (perhaps in a more visible way. The end-user should not spend time discovering the UI as I did in the past 30 mins 😅😅. I recommend adding a header for the title in the description like **Title:** SOP so it is more visible to the user)

**Comment by johannesjo** [comment]
@AminTaheri23 thanks for the feedback. Personally I quite often edit the task titles, but I usually use the enter key so it isn't much of an issue. As a quick fix, I'll try to make the task title visible for desktop touch devices too, but in the long run we need a better solution.

**Comment by AminTaheri23** [comment]
Happy to help. On Feb 5, 2021 12:07, Johannes Millan <notifications@github.com> wrote:
@AminTaheri23 thanks for the feedback. Personally I quite often edit the task titles, but I usually use the enter key so it isn't much of an issue. As a quick fix, I'll try to make the task title visible for desktop touch devices too, but in the long run we need a better solution.
