### ISSUE TITLE
Snap release stuck at 1.10.9

### ISSUE THREAD

**Issue by ArjenR** [johannesjo/super-productivity#78]
## Your Environment

* Version used: 1.10.9
* Operating System and version: Solus 3.999
* Desktop Environment: Budgie 10.4
* Browser Name and version: na

## Expected Behavior
run # sudo snap refresh
and have the latest super-productivity
to be able to use/test sync using  nextcloud
## Current Behavior
snap is still at 1.10.9

$ snap info superproductivity
name:      superproductivity
summary:   superProductivity
publisher: johannesjo
contact:   https://github.com/johannesjo/super-productivity
description: |
  Personal Task Management App to help you with your daily struggle with JIRA
  etc.
snap-id: wZo5sef6NuUKCW6DP83fJ6zIZyd5R1sA
commands:
  - superproductivity
tracking:    stable
installed:   1.10.9 (67) 103MB -
refreshed:   2018-04-06 19:51:27 +0200 CEST
channels:                
  stable:    1.10.9 (67) 103MB -
  candidate: 1.10.9 (67) 103MB -
  beta:      1.10.9 (67) 103MB -
  edge:      1.10.9 (67) 103MB -

**Comment by johannesjo** [comment]
Thanks for reporting this. Somehow the automatic deployment for this is not reliable. Sometimes it works, sometimes not. I'll provide a manual update.
