### ISSUE TITLE
GoogleDrive Sync Provider - Couldn't sign you in

### ISSUE THREAD

**Issue by jobbio** [johannesjo/super-productivity#782]
* Version used:  exe
* Operating System and version: Windows 10 20H2

### Current Behavior

Selecting Sync Provider GoogleDrive launches the Google Login page in a separate window. Entering any email address takes you to a page with the following text:
Couldn't sign you in
This browser or app may not be secure.
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.

### Steps to Reproduce (for bugs)

1. Expand sync in the settings menu
2. Choose GoogleDrive as the sync provider
3. Press Save
4. Enter e-mail address in the popup window

### Console Output

Because a cookie's SameSite attribute was not set or is invalid, it defaults to SameSite=Lax, which will prevents the cookie from being set in a cross-site context in a future version of the browser. This behavior protects user data from accidentally leaking to third parties and cross-site request forgery.

Resolve this issue by updating the attributes of the cookie:
Specify SameSite=None and Secure if the cookie is intended to be set in cross-site contexts. Note that only cookies sent over HTTPS may use the Secure attribute.
Specify SameSite=Strict or SameSite=Lax if the cookie should not be set by cross-site requests

affected resource 1 cookie - CheckConnectionTempCookie873 - accounts.youtube.com/accounts 

### Error Log (Desktop only)

[2021-01-12 16:03:51.534] [error] Frontend Error: { HANDLED_ERROR_PROP: 'GD File creation: [object Object]' } undefined
[2021-01-12 16:03:51.546] [error] Frontend Error Stack: 
[2021-01-12 16:04:22.570] [error] Frontend Error: { HANDLED_ERROR_PROP: 'GD File creation: [object Object]' } undefined
[2021-01-12 16:04:22.576] [error] Frontend Error Stack: 
[2021-01-12 16:04:49.368] [error] Frontend Error: { HANDLED_ERROR_PROP: 'GD File creation: [object Object]' } undefined
[2021-01-12 16:04:49.372] [error] Frontend Error Stack: 
[2021-01-12 16:06:53.611] [error] Frontend Error: { HANDLED_ERROR_PROP: 'GD File creation: [object Object]' } undefined
[2021-01-12 16:06:53.626] [error] Frontend Error Stack: 
[2021-01-12 16:09:08.434] [error] Frontend Error: { HANDLED_ERROR_PROP: 'GD File creation: [object Object]' } undefined
[2021-01-12 16:09:08.437] [error] Frontend Error Stack: 
[2021-01-12 16:12:34.662] [error] Frontend Error: { HANDLED_ERROR_PROP: 'GD File creation: [object Object]' } undefined
[2021-01-12 16:12:34.683] [error] Frontend Error Stack: 
[2021-01-12 16:18:44.628] [error] Frontend Error: { HANDLED_ERROR_PROP: 'GD File creation: [object Object]' } undefined
[2021-01-12 16:18:44.634] [error] Frontend Error Stack: 
[2021-01-12 16:20:22.865] [error] Frontend Error: { HANDLED_ERROR_PROP: 'GD File creation: [object Object]' } undefined
[2021-01-12 16:20:22.889] [error] Frontend Error Stack:

**Comment by prajjwald** [comment]
Just learned about this program today and installed in on elementary OS Hera, I have the same issue.

**Comment by johannesjo** [comment]
Thanks for reporting this! I'll try to check this later this week. Meanwhile I suggest to use Dropbox instead, if that is an option for you.

**Comment by The-Compiler** [comment]
FWIW this is most likely related to: [Google Developers Blog: Guidance to developers affected by our effort to block less secure browsers and applications](https://developers.googleblog.com/2020/08/guidance-for-our-effort-to-block-less-secure-browser-and-apps.html)

**Comment by johannesjo** [comment]
@The-Compiler yes, you're most likely right. Having a look at [this module](https://www.npmjs.com/package/google-auth-library) will probably be helpful. If somebody else wants to have a look in the meantime (I probably won't make it before the weekend), I am all for it!

**Comment by cgrinea** [comment]
Same issue on Linux (Arch). I tried again after logging in Google Drive from a browser but the window generated by SuperProductivity gave the same message: "Couldn't sign you in".
I then installed the mobile (android) app and generated the .json file from a mobile phone, but it can be accessed only from the phone.
Moreover, when trying to close the Desktop application with Finish Day - Save and Go Home - Shutdown, I get an error message: "GoogleApi: No file id specified"
Other than that, it looks amazing and I'm really looking forward to using it on several devices.

**Comment by johannesjo** [comment]
Quick update: I haven't forgotten about the issue. It's just that I am super busy these days. I hope I find some time this Friday.

**Comment by cgrinea** [comment]
Hi
Today I did a Backup on the Android version, downloaded the SUPER_PRODUCTIVITY_SYNC.json file from Google Drive onto a laptop and tried to Import the file into the laptop version (Archlinux). I don't have any programming knowledge, and I don't know whether what I did was the proper way to do it or not, but I got a big red alert "! Please copy & report !"

Maybe it helps.


[Cannot read property 'config' of undefined TypeError.txt](https://github.com/johannesjo/super-productivity/files/5878758/Cannot.read.property.config.of.undefined.TypeError.txt)

**Comment by johannesjo** [comment]
@cgrinea no the data is slightly different, so this won't work.There is some additional meta data in the file on google drive.

**Comment by johannesjo** [comment]
So after spending another couple of hours on this I found a solution that would, but at this point I am asking myself if it is really worth the ongoing trouble. The google stuff requires a lot of platform specific code and sophisticated solutions and this is not the first time I had to deal with some changes to their policies and it is not the first time that did cost me **a lot** of time. Personally I am using Dropbox now anyway.

Before making a decision either way I'd like to get some opinions on this from the people being affected by this. Do you think it's worth to support Google Drive rather than spending my time on more useful stuff?

**Comment by prajjwald** [comment]
Thank you for following up on this @johannesjo .  I'm also using dropbox, and it works perfectly for me.

I think it is not worth supporting Google Drive as opposed to possibly more useful stuff (for example encryption support).  I'm basing this on your mention of a constantly changing API and platform specific code requirements, as well as changes to their policies.

In the long term - if there was a possibility of an embedded google drive app (like draw.io) - then it would become somewhat worth it, but that would be a low priority item that can always be something that is looked into optionally only when there aren't local app features in the pipeline IMO.

**Comment by JCurtisRMIT** [comment]
Wonderful app! Discovered today, exploring sync across all my devices for it and ran into this also (Ubuntu 18.04)

**Comment by fftux** [comment]
Does supporting integration with Google Drive help with the potential for future Google Calendar integration?  If so, then I would like to see the Google integration piece.  If these are completely separate, then I wouldn't work about it.

**Comment by johannesjo** [comment]
@fftux that's a very good point! Thank you! I need to investigate this.

**Comment by ajcool2k** [comment]
I personally stumbled across this project because it offers a way to sync. Haven't used it in the past so I won't push you either way. But since you asked for input. Having a working sync for google makes more sense to me in comparison to dropbox. I guess the user audience running dropbox is just a slice of the google user base.

I'd try this app out for productivity if it could sync with google correctly, but then again, you shouldn't just do it for a stranger ;-)

**Comment by johannesjo** [comment]
@ajcool2k thanks! You also make some very valid points.

**Comment by nunojsa** [comment]
Hi, I just stumbled against this issue. Personally I would like to see google drive supported. I was also using dropbox with my password manager (keepass2). However, as I was installing it on different machines, I found out that dropbox actually as a limit of places where you can use (if you don't a premium account). For me that was a killer thing that made move to google drive (using `rclone`)...

**Comment by johannesjo** [comment]
This was an unpleasant experience for the most part, but it seems to work again now :D Thanks for all your input!

Any volunteers for testing this?  :)

**Comment by ajcool2k** [comment]
![IMG_0157](https://user-images.githubusercontent.com/23473452/107114837-3e3d6d80-6869-11eb-9d96-62dfa48e02e4.jpg)

Works like a charm on my system. Cheers!

**Comment by johannesjo** [comment]
@ajcool2k thank you very much for testing! I am glad that it works. The feature should be available in the edge channel now. Let me know if you encounter any quirks.

**Comment by ximemira** [comment]
Hi, 
I think this problem is back, I have just updated super productivity SuperProductivity 
Version used: 7.12 dmg downloaded directly from github
Operating System and version: Mac os Ventura 13.0 (22A380)
I tried opening the link on firefox and on safari, with the same result. 

The new version didn’t recognize my local backup file so I had to redo the sync settings to get it back, though : 
![image](https://user-images.githubusercontent.com/37844004/200635481-852d963a-b5b1-48d3-82e3-4069a002fead.png)

From google more info :
> Access blocked: Third-party app is using an unsupported OAuth method 
> Error 400: invalid_request
The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow migration guide linked in the developer docs below to migrate your app to an alternative method.
Request details: redirect_uri=urn:ietf:wg:oauth:2.0:oob
[Related developer documentation](https://developers.google.com/identity/protocols/oauth2/resources/oob-migration)
> If your app uses the Loopback IP Address method for iOS, Android, and Chrome app OAuth client types or the Out-Of-Band method for any client type, you’ll need to migrate to a more secure alternative method. For detailed instructions, check the [Out-Of-Band (OOO) flow migration guide](https://developers.google.com/identity/protocols/oauth2/resources/oob-migration) and [Loopback IP Address flow migration guide](https://developers.google.com/identity/protocols/oauth2/resources/loopback-migration).

Thanks for the amazing app, sorry Google is such a pain...

**Comment by ZakCodes** [comment]
I'm having the same problem as you @ximemira. However, it doesn't seem to be the same thing as what is described in this issue. If I were you, I would create a separate issue for it. Maybe you could reference this issue in case it's related.

**Comment by johannesjo** [comment]
Sounds good @ZakCodes !
