### ISSUE TITLE
Chrome extension redirects to wrong url

### ISSUE THREAD

**Issue by jbrongtr** [johannesjo/super-productivity#789]
### Your Environment

* Version used: 0.5.1
* Operating System and version: Centos7 Chrome Version 87.0.4280.66 (Official Build) (64-bit) 
* Desktop Environment: Centos7 GNOME
* Browser Name and version: Chrome Version 87.0.4280.66 (Official Build) (64-bit) 

### Expected Behavior

Clicking on the extension icon should open up https://app.super-productivity.com/

### Current Behavior

Clicking on the extenstion icon opens https://super-productivity.com/app

### Steps to Reproduce (for bugs)

1. Install extenstion from chrome web store
2. click on Super Productivity icon
3.
4.

### Error Log (Desktop only)
Nginx 404 not found

**Comment by johannesjo** [comment]
Thanks for opening this up. This should already be fixed I think, but i think the version is not rolled out yet. I try to deal with it later today.

**Comment by jbrongtr** [comment]
No worries, just wanted to ensure it was on your radar. No rush!

Awesome app btw

**Comment by jbrongtr** [comment]
Updating to 0.5.2 fixed the issue. /close
