### ISSUE TITLE
RQ: Include task descriptions in worklog export

### ISSUE THREAD

**Issue by and0m** [johannesjo/super-productivity#795]
## Problem Statement
It would be helpful to include the description of the task as part of the worklog columns

## :grey_question: Possible Solution
Include another column that takes values from the description field of tasks and adds it to the worklog row for the corresponding task

## :arrow_heading_up: Describe alternatives you've considered
--

## :heavy_plus_sign: Additional context
--

**Comment by johannesjo** [comment]
This should be pretty straighforward to implement and I don't see a reason not to. If somebody wants to tackle this, please let me know!
