### ISSUE TITLE
I get an error on the startup

### ISSUE THREAD

**Issue by Warmuser** [johannesjo/super-productivity#80]
Hi, I installed the super-productivity app as snapd file and I started the application, then I encountered a message error for the missing "xprintidle". So, I enabled the xprintidle by these command "dnf copr enable alonid/xprintidle". After, I restarted the super-productivity app and I get the same message error on the startup view. Why? I'm on Fedora 27 KDE with the latest updates.

**Comment by johannesjo** [comment]
Thanks for reporting. I will check this.

**Comment by Warmuser** [comment]
I installed the app  thanks to the snapd package, anyway I encountered also some conflicting problem with kwin. Because, When I try to use these app, sometimes kwin crash and I have to restart it, I don't have nothing opened, ony the super-productivity app. Thanks :)

**Comment by johannesjo** [comment]
I think the xprintidle problem is probably due to the app not being able to execute it due to some rights or path issues. I don't know, it's probably not much help to you, but I modfied the idle handler to only show the error once.

**Comment by Warmuser** [comment]
Ok, Thanks anyway! :)
