### ISSUE TITLE
Feature request: add integration with fossil

### ISSUE THREAD

**Issue by toolonely** [johannesjo/super-productivity#800]
## Problem Statement

Integration with [fossil](https://github.com/johannesjo/super-productivity)

Fossil is a version control system that stores the repos in an sqlite database (they share the same author). It is a single binary that can also work as server and expose a web interface. It has built-in issues, called tickets, hence the feature request. It also has a [JSON API](https://fossil-scm.org/home/doc/trunk/www/json-api/index.md) but I never worked with it.

Even for a non-programming project, if one wanted to make use of issues, it would be much simpler to use the tickets of fossil than spend more time deploying a giant beast like GitLab/Jira locally.

**Comment by johannesjo** [comment]
Hey there! Thanks for the suggestion. If anybody wants to tackle this: Please let me know!
