### ISSUE TITLE
Error: Uncaught (in promise)

### ISSUE THREAD

**Issue by mhkh8367** [johannesjo/super-productivity#801]
timer
You have not been tracking time for 2m
Global Settings

Toggle Dark Mode
Productivity Helper
Sync & Export
Enable Syncing
1m
Sync Interval
Dropbox	
 Sync Provider *
Please open the following link and copy the auth code provided there into the the input field.

https://www.dropbox.com/oauth2/authorize?response_type=code

YdbxEevI3GwAAAAAAAAGbNMUFAYndwKuSYFP2C7T9uU
Auth Code
SddApf0ai1QAAAAAAAAAAecv-imGkArQaEzPZ5NBrIJUua61CJvtVCbIZRkDSAEW
Access Token (generated from Auth Code)
Super Productivity 6.3.3 – Private Policy – Provide Feedback
Help I'm procrastinating!
Start/Stop tracking time
Add new Task
Go to task list
Project Settings
Show/Hide Bookmarks
Error: Uncaught (in promise): Error: No correct localLastSync given null Error: No correct localLastSync given null at e. (file:///C:/Users/M96F1~1.HOS/AppData/Local/Temp/1mcQkx4tEHIGfPfMHRY9Uz5KKHQ/resources/app.asar/dist/main.b83c45f4961784900db8.js:1:3529083) at Generator.next () at file:///C:/Users/M96F1~1.HOS/AppData/Local/Temp/1mcQkx4tEHIGfPfMHRY9Uz5KKHQ/resources/app.asar/dist/main.b83c45f4961784900db8.js:1:3522405 at new C (file:///C:/Users/M96F1~1.HOS/AppData/Local/Temp/1mcQkx4tEHIGfPfMHRY9Uz5KKHQ/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:17831) at fE (file:///C:/Users/M96F1~1.HOS/AppData/Local/Temp/1mcQkx4tEHIGfPfMHRY9Uz5KKHQ/resources/app.asar/dist/main.b83c45f4961784900db8.js:1:3522150) at e._setLocalRevAndLastSync (file:///C:/Users/M96F1~1.HOS/AppData/Local/Temp/1mcQkx4tEHIGfPfMHRY9Uz5KKHQ/resources/app.asar/dist/main.b83c45f4961784900db8.js:1:3528965) at e. (file:///C:/Users/M96F1~1.HOS/AppData/Local/Temp/1mcQkx4tEHIGfPfMHRY9Uz5KKHQ/resources/app.asar/dist/main.b83c45f4961784900db8.js:1:3528132) at Generator.next () at a (file:///C:/Users/M96F1~1.HOS/AppData/Local/Temp/1mcQkx4tEHIGfPfMHRY9Uz5KKHQ/resources/app.asar/dist/main.b83c45f4961784900db8.js:1:3522207) at l.invoke (file:///C:/Users/M96F1~1.HOS/AppData/Local/Temp/1mcQkx4tEHIGfPfMHRY9Uz5KKHQ/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6572)
! Please copy & report !

Error: Uncaught (in promise): Error: No correct localLastSync given null Error: No correct localLastSync given null at e. (file:///C:/Users/M96F1~1.HOS/AppData/Local/Temp/1mcQkx4tEHIGfPfMHRY9Uz5KKHQ/resources/app.asar/dist/main.b83c45f4961784900db8.js:1:3529083) at Generator.next () at file:///C:/Users/M96F1~1.HOS/AppData/Local/Temp/1mcQkx4tEHIGfPfMHRY9Uz5KKHQ/resources/app.asar/dist/main.b83c45f4961784900db8.js:1:3522405 at new C (file:///C:/Users/M96F1~1.HOS/AppData/Local/Temp/1mcQkx4tEHIGfPfMHRY9Uz5KKHQ/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:17831) at fE (file:///C:/Users/M96F1~1.HOS/AppData/Local/Temp/1mcQkx4tEHIGfPfMHRY9Uz5KKHQ/resources/app.asar/dist/main.b83c45f4961784900db8.js:1:3522150) at e._setLocalRevAndLastSync (file:///C:/Users/M96F1~1.HOS/AppData/Local/Temp/1mcQkx4tEHIGfPfMHRY9Uz5KKHQ/resources/app.asar/dist/main.b83c45f4961784900db8.js:1:3528965) at e. (file:///C:/Users/M96F1~1.HOS/AppData/Local/Temp/1mcQkx4tEHIGfPfMHRY9Uz5KKHQ/resources/app.asar/dist/main.b83c45f4961784900db8.js:1:3528132) at Generator.next () at a (file:///C:/Users/M96F1~1.HOS/AppData/Local/Temp/1mcQkx4tEHIGfPfMHRY9Uz5KKHQ/resources/app.asar/dist/main.b83c45f4961784900db8.js:1:3522207) at l.invoke (file:///C:/Users/M96F1~1.HOS/AppData/Local/Temp/1mcQkx4tEHIGfPfMHRY9Uz5KKHQ/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6572)
typeof (webpack:///src/app/imex/sync/sync-provider.service.ts:289:12)
Ur (file:///C:/Users/M96F1~1.HOS/AppData/Local/Temp/1mcQkx4tEHIGfPfMHRY9Uz5KKHQ/resources/app.asar/dist/main.b83c45f4961784900db8.js:1:3522405)
constructor (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1383:28)
Ur (file:///C:/Users/M96F1~1.HOS/AppData/Local/Temp/1mcQkx4tEHIGfPfMHRY9Uz5KKHQ/resources/app.asar/dist/main.b83c45f4961784900db8.js:1:3522150)
Ur (file:///C:/Users/M96F1~1.HOS/AppData/Local/Temp/1mcQkx4tEHIGfPfMHRY9Uz5KKHQ/resources/app.asar/dist/main.b83c45f4961784900db8.js:1:3528965)
isValidAppData (webpack:///src/app/imex/sync/sync-provider.service.ts:243:11)
Ur (file:///C:/Users/M96F1~1.HOS/AppData/Local/Temp/1mcQkx4tEHIGfPfMHRY9Uz5KKHQ/resources/app.asar/dist/main.b83c45f4961784900db8.js:1:3522207)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1209:30)
executor(makeResolver (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1386:16)
Ur (file:///C:/Users/M96F1~1.HOS/AppData/Local/Temp/1mcQkx4tEHIGfPfMHRY9Uz5KKHQ/resources/app.asar/dist/main.b83c45f4961784900db8.js:1:3522150)
Ur (file:///C:/Users/M96F1~1.HOS/AppData/Local/Temp/1mcQkx4tEHIGfPfMHRY9Uz5KKHQ/resources/app.asar/dist/main.b83c45f4961784900db8.js:1:3528965)
isValidAppData (webpack:///src/app/imex/sync/sync-provider.service.ts:243:11)
Ur (file:///C:/Users/M96F1~1.HOS/AppData/Local/Temp/1mcQkx4tEHIGfPfMHRY9Uz5KKHQ/resources/app.asar/dist/main.b83c45f4961784900db8.js:1:3522207)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.js:28281:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:367:51)
META: SP6.3.3 Electron – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.3.3 Chrome/85.0.4183.121 Electron/10.2.0 Safari/537.36
Reload App

**Comment by johannesjo** [comment]
Thanks for reporting. Could you maybe provide a little bit more context?

**Comment by mhkh8367** [comment]
That has happened when I enabled sync by dropbox.
when I returned to desktop app after settings, this error occurred and
wanted me to send you that issue on GitHub
I was all I knew about it.
By the way it works fine now.

**Comment by johannesjo** [comment]
I am glad that it works now. Thanks for the info. Please let me know if this happens again!

**Comment by mhkh8367** [comment]
Ok I will comment if possible
