### ISSUE TITLE
Add support for WsgiDAV

### ISSUE THREAD

**Issue by toolonely** [johannesjo/super-productivity#802]
### Your Environment
* Version used: Super Productivity for Android, version 7.0 / Super Productivity for desktop, version 6.3.3 (the AppImage)
* Operating System: MIUI 12.0.5, Android 10 / Slackware64-14.2 Linux

### Expected Behavior
WebDAV sync settings form must have optional user/password fields

### Current Behavior
WebDAV sync settings form has mandatory user/password fields

I am not using NextCloud for syncing over WebDAV, I am using [WsgiDAV](https://github.com/mar10/wsgidav). As shown in the first example in its README, by default it runs in anonymous mode: read/write access to root, no need to pass an user/password when logging. I am sure it works, because I tested it with Joplin just yesterday. Super Productivity won't let me do that, Save button stays inactive because user and password form fields are mandatory and can't be left empty. Please make the fields optional.

Edit: added info about the desktop version. because the bug is present there as well.

**Comment by johannesjo** [comment]
Hi there! Thanks for bringing this to my attention. I'll change it.

**Comment by johannesjo** [comment]
I just had a quick look. While the change should theoretically be straightforward, I don't have the infrastructure in place to test it. Would you maybe give it a shot yourself? 

The important bits are located in these two files:
```
src/app/imex/sync/web-dav/web-dav-api.service.ts
src/app/features/config/form-cfgs/sync-form.const.ts
```

**Comment by toolonely** [comment]
Unfortunately I'm in an even worse situation:

- pretty much zero knowledge about NodeJS/JavaScript, so I wouldn't know what to change in second file
- zero knowledge about WebDAV, so I wouldn't know what to change in first file
- zero knowledge about how to compile the desktop and mobile versions from source
- zero knowledge about how to produce the final AppImage, and, as I understand, an .apk file, which would be possible to install directly rather than through an app store (I notice that GitHub provides no .apk file in Releases)

My option to test and report back are to wait for the next release and try the updated AppImage for desktop. As well, wait for an update of the mobile version in the Google app store, update and test. Alternatively, if you could fix the bug and produce test versions of the AppImage and the .apk file, and host them somewhere, I can download them and test if they work with WsgiDAV.

**Comment by johannesjo** [comment]
Alright, no worries. Officially there is no support for WsgiDAV, so it's maybe not surprising that it doesn't work. I am pretty swammed with issues and other stuff, but I leave this open for people to upvote or even work on.

**Comment by toolonely** [comment]
I have some small good news and some bad news.

The good news is that I've read the WsgiDAV docs a little and I found a way to run it so it expects users to enter a password, even when not using PAM (which is present almost everywhere, but still not everywhere).

It is possible to run WsgiDAV like this:

    $ wsgidav --host=0.0.0.0 --port=80 --root=ROOTDIR

and with the following config with default name `wsgidav.yaml`:

    http_authenticator:
        domain_controller: null  # Same as wsgidav.dc.simple_dc.SimpleDomainController
        accept_basic: true  # Pass false to prevent sending clear text passwords
        accept_digest: true
        default_to_digest: true

    simple_dc:
        user_mapping:
            "*":
                "user":
                    password: "password"

Then WsgiDAV will expect the following auth:

    user: user
    password: password

The good news is that the desktop SU successfully syncs with such settings. The mobile client doesn't (should I open another bug about it?).

The bad news is that I have no options for the mobile client to sync at all, right? Because import/export doesn't work in the mobile client either. I found at least https://github.com/johannesjo/super-productivity/issues/746

Or is there any other option to bring updated data to the mobile client from either the desktop client or the WebDAV sync directory until these problems will be fixed? Like manually copying the database from the desktop client onto the phone? Where does the mobile client keep its database, if this would work?

**Comment by johannesjo** [comment]
> Or is there any other option to bring updated data to the mobile client from either the desktop client or the WebDAV sync directory until these problems will be fixed?

I am not sure what you mean by that. WebDAV syncing seems to work fine. You just have to configure it for both instances of the app.

**Comment by toolonely** [comment]
> WebDAV syncing seems to work fine.

Do you mean that WebDAV works for you with a NextCloud instance, or that you actually tried with the mobile app and WsgiDAV and the mobile app actually synced successfully? Because the mobile app doesn't sync here.

> You just have to configure it for both instances of the app.

Yes. I have WsgiDAV configured just like in the example above, so a remote user has to authenticate with username:password. I have the desktop app and the mobile app configured exactly the same in settings. The desktop app syncs fine, albeit a bit slow, but it's ok. The mobile app doesn't. When I hit the save button, for some reason it tries to contact the webapp on the official site. And then displays a connection error message. I've got screens.

I got screens. This is what happens in the mobile app after I fill the WebDAV settings, enable the sync checkbox and hit the Save button:

![1](https://user-images.githubusercontent.com/77091000/104850575-94696180-58f8-11eb-9539-5bc3fd97520a.jpg)

If I press either CANCEL or OK buttons on that white dialog, this is what happens next:

![2](https://user-images.githubusercontent.com/77091000/104850603-b531b700-58f8-11eb-889f-ad69be4cfde1.jpg)

Syncing doesn't happen at all. According to the WsgiDAV log, the mobile app doesn't even try to connect to it.

I repeat again that I don't think it's a problem of WsgiDAV. Joplin syncs fine to it, both the desktop app and  the mobile app. Perhaps you could have a look at Joplin's codebase and see what does it to differently.
