### ISSUE TITLE
TypeError: ServiceWorker script at https://app.super-productivity.com/ngsw-worker.js for scope https://app.super-productivity.com/ encountered an error during installation.

### ISSUE THREAD

**Issue by jakobkappel** [johannesjo/super-productivity#804]
### Steps to Reproduce
1. App crashed when another tab was in focus, so I'm afraid I can't supply more info.

### Console Output
Last actions before error: 
Array(30) [ "1610710248566: [Metric] Load Metric State", "1610710248575: [Improvement] Load Improvement State", "1610710248659: [Obstruction] Load Obstruction State", "1610710248665: [Project] Load Project related Data Success", "1610710248667: [Improvement] Clear Hidden Improvements", "1610710248694: [Improvement] Delete multiple Improvements", "1610790685114: [SP_ALL] Load(import) all data", "1610790685118: [SP_ALL] All Data was loaded", "1610790685129: [WorkContext] Set Active Work Context", "1610790685276: [Task] SetSelectedTask", … ]
action-logger.ts:29:10

Unhandled Promise rejection: TypeError: ServiceWorker script at https://app.super-productivity.com/ngsw-worker.js for scope https://app.super-productivity.com/ encountered an error during installation. ; Zone: <root> ; Task: Promise.then ; Value: Error: TypeError: ServiceWorker script at https://app.super-productivity.com/ngsw-worker.js for scope https://app.super-productivity.com/ encountered an error during installation.
    handleError global-error-handler.class.ts:54
    Angular 7
 handleError@https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:3841436
Sa/</</</<@https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:2621459
invoke@https://app.super-productivity.com/polyfills.bbc1c0564b6a5d42ba73.js:1:6572
run@https://app.super-productivity.com/polyfills.bbc1c0564b6a5d42ba73.js:1:1984
P/<@https://app.super-productivity.com/polyfills.bbc1c0564b6a5d42ba73.js:1:16758
invokeTask@https://app.super-productivity.com/polyfills.bbc1c0564b6a5d42ba73.js:1:7190
runTask@https://app.super-productivity.com/polyfills.bbc1c0564b6a5d42ba73.js:1:2599
m@https://app.super-productivity.com/polyfills.bbc1c0564b6a5d42ba73.js:1:9184
zone-evergreen.js:1059:24

Error without stack TypeError: ServiceWorker script at https://app.super-productivity.com/ngsw-worker.js for scope https://app.super-productivity.com/ encountered an error during installation. global-error-handler.util.ts:27:12

### Meta Info
META: SP6.3.3 Browser – da – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:86.0) Gecko/20100101 Firefox/86.0

### Actions Before Error
```
1610656472139: [Metric] Load Metric State 
1610656472150: [Improvement] Load Improvement State 
1610656472163: [Obstruction] Load Obstruction State 
1610656472166: [Project] Load Project related Data Success 
1610656472167: [Improvement] Clear Hidden Improvements 
1610656472168: [Improvement] Delete multiple Improvements 
1610710246909: [SP_ALL] Load(import) all data 
1610710246937: [SP_ALL] All Data was loaded 
1610710246948: [WorkContext] Set Active Work Context 
1610710247025: [Task] SetSelectedTask 
1610710248545: [Note] Load Note State 
1610710248556: [Bookmark] Load Bookmark State 
1610710248566: [Metric] Load Metric State 
1610710248575: [Improvement] Load Improvement State 
1610710248659: [Obstruction] Load Obstruction State 
1610710248665: [Project] Load Project related Data Success 
1610710248667: [Improvement] Clear Hidden Improvements 
1610710248694: [Improvement] Delete multiple Improvements 
1610790685114: [SP_ALL] Load(import) all data 
1610790685118: [SP_ALL] All Data was loaded 
1610790685129: [WorkContext] Set Active Work Context 
1610790685276: [Task] SetSelectedTask 
1610790686673: [Note] Load Note State 
1610790686683: [Bookmark] Load Bookmark State 
1610790686691: [Metric] Load Metric State 
1610790686700: [Improvement] Load Improvement State 
1610790686716: [Obstruction] Load Obstruction State 
1610790686723: [Project] Load Project related Data Success 
1610790686725: [Improvement] Clear Hidden Improvements 
1610790686727: [Improvement] Delete multiple Improvements
```

**Comment by johannesjo** [comment]
Hi there! You are using firefox right? Unfortunately this isn't very high on my priority list as most users are on chromium in one way or the other, but I gladly accept PRs dealing with this.
