### ISSUE TITLE
Keeps displaying sync error dialogs when offline

### ISSUE THREAD

**Issue by zecamigo** [johannesjo/super-productivity#805]
* Version used: Snap 6.1.1
* Operating System and version: Ubuntu 20.04.1 LTS
* Desktop Environment: Gnome

### Expected Behavior
Should be silent about sync errors or display an unobtrusive sign when offline

### Current Behavior
"No remote data found. Upload local to remote" dialog keeps popping up.

### Steps to Reproduce (for bugs)
1. Install snap pack
2. Set up with remote service (Nextcloud)
3. Go into airplane mode
4. Wait for sync message "No remote data found. Upload local to remote"
5. Click cancel
6. Get "Unknown Sync Error: Error: Network error"
7. Another "No remote data found. Upload local to remote" dialog
8. Click cancel again

This will keep popping up at sync interval.

Let me know if you need logs please

**Comment by johannesjo** [comment]
Thanks for reporting this! I'll try to look into it once I have a bit more time on my hands. Meanwhile PR's dealing with this are very welcome.
