### ISSUE TITLE
Blurry font on task name edit mode

### ISSUE THREAD

**Issue by Acsigen** [johannesjo/super-productivity#81]
## Your Environment

* Version used: 1.10.20
* Operating System and version: Windows 7 x64
* Desktop Environment: 
* Browser Name and version: Google Chrome 66

## Expected Behavior
While editing the name of a task the font should be clear

## Current Behavior
While editing the name of a task the font is blurry (availabe for web and standalone version in daily planner and work view)
![capture](https://user-images.githubusercontent.com/13287878/39740384-0b7f4532-529e-11e8-8ede-97f61d0d2c88.png)

## Steps to Reproduce (for bugs)

1. Create a task(font is clear here), edit the task name(the font is blurry)

**Comment by johannesjo** [comment]
Thanks for reporting. I'll try to find a solution for this.

**Comment by johannesjo** [comment]
Should be fixed (hopefully). I'm building a new release atm. Should be out in a bit.

**Comment by Acsigen** [comment]
Fixed with version 1.10.31
