### ISSUE TITLE
TypeError: Cannot read property 'isDone' of null

### ISSUE THREAD

**Issue by tpaixao** [johannesjo/super-productivity#811]
### Steps to Reproduce

1. Add task to empty project
2. mark task as complete
3. delete task

got: 
TypeError: Cannot read property 'subTasks' of null
isDone (webpack:///src/app/features/work-context/work-context.util.ts:21:14)
filter (webpack:///src/app/features/work-context/work-context.util.ts:20:31)
_next (webpack:///node_modules/rxjs/_esm2015/internal/operators/map.js:29:34)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)
observers.slice (webpack:///node_modules/rxjs/_esm2015/internal/Subject.js:39:24)
_events.push (webpack:///node_modules/rxjs/_esm2015/internal/ReplaySubject.js:31:14)
next (webpack:///node_modules/rxjs/_esm2015/internal/operators/shareReplay.js:31:38)
__tryOrUnsub (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:183:15)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:122:21)
META: SP6.3.3 Electron – en-GB – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.3.3 Chrome/85.0.4183.121 Electron/10.2.0 Safari/537.36

### Console Output
main.6f53c89a169e8f6cfecd.js:1 Task data not found for umAIZJmRw
s @ main.6f53c89a169e8f6cfecd.js:1
main.6f53c89a169e8f6cfecd.js:1 GLOBAL_ERROR_HANDLER TypeError: Cannot read property 'subTasks' of null
    at main.6f53c89a169e8f6cfecd.js:1
    at Array.forEach (<anonymous>)
    at c (main.6f53c89a169e8f6cfecd.js:1)
    at a.project (main.6f53c89a169e8f6cfecd.js:1)
    at a._next (main.6f53c89a169e8f6cfecd.js:1)
    at a.next (main.6f53c89a169e8f6cfecd.js:1)
    at l.next (main.6f53c89a169e8f6cfecd.js:1)
    at l.nextInfiniteTimeWindow (main.6f53c89a169e8f6cfecd.js:1)
    at Object.next (main.6f53c89a169e8f6cfecd.js:1)
    at d.__tryOrUnsub (main.6f53c89a169e8f6cfecd.js:1)
handleError @ main.6f53c89a169e8f6cfecd.js:1
main.6f53c89a169e8f6cfecd.js:1 Last actions before error: Array(30)
main.6f53c89a169e8f6cfecd.js:1 GLOBAL_ERROR_HANDLER TypeError: Cannot read property 'isDone' of null
    at main.6f53c89a169e8f6cfecd.js:1
    at Array.filter (<anonymous>)
    at a.L [as project] (main.6f53c89a169e8f6cfecd.js:1)
    at a._next (main.6f53c89a169e8f6cfecd.js:1)
    at a.next (main.6f53c89a169e8f6cfecd.js:1)
    at l.next (main.6f53c89a169e8f6cfecd.js:1)
    at l.nextInfiniteTimeWindow (main.6f53c89a169e8f6cfecd.js:1)
    at Object.next (main.6f53c89a169e8f6cfecd.js:1)
    at d.__tryOrUnsub (main.6f53c89a169e8f6cfecd.js:1)
    at d.next (main.6f53c89a169e8f6cfecd.js:1)
handleError @ main.6f53c89a169e8f6cfecd.js:1
main.6f53c89a169e8f6cfecd.js:1 Last actions before error: Array(30)
polyfills.bbc1c0564b6a5d42ba73.js:1 Uncaught Error: TypeError: Cannot read property 'isDone' of null
    at e.handleError (main.6f53c89a169e8f6cfecd.js:1)
    at Object.next (main.6f53c89a169e8f6cfecd.js:1)
    at d.i [as _next] (main.6f53c89a169e8f6cfecd.js:1)
    at d.__tryOrUnsub (main.6f53c89a169e8f6cfecd.js:1)
    at d.next (main.6f53c89a169e8f6cfecd.js:1)
    at l._next (main.6f53c89a169e8f6cfecd.js:1)
    at l.next (main.6f53c89a169e8f6cfecd.js:1)
    at Uc.next (main.6f53c89a169e8f6cfecd.js:1)
    at Uc.emit (main.6f53c89a169e8f6cfecd.js:1)
    at main.6f53c89a169e8f6cfecd.js:1
### Stacktrace
```
isDone (webpack:///src/app/features/work-context/work-context.util.ts:21:14)
filter (webpack:///src/app/features/work-context/work-context.util.ts:20:31)
_next (webpack:///node_modules/rxjs/_esm2015/internal/operators/map.js:29:34)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)
observers.slice (webpack:///node_modules/rxjs/_esm2015/internal/Subject.js:39:24)
_events.push (webpack:///node_modules/rxjs/_esm2015/internal/ReplaySubject.js:31:14)
next (webpack:///node_modules/rxjs/_esm2015/internal/operators/shareReplay.js:31:38)
__tryOrUnsub (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:183:15)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:122:21)
```

### Meta Info
META: SP6.3.3 Electron – en-GB – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.3.3 Chrome/85.0.4183.121 Electron/10.2.0 Safari/537.36

### Actions Before Error
```
1611064605814: [Persistence] Save to DB 
1611064605814: [Persistence] Save to DB 
1611064605815: [Persistence] Save to DB 
1611064605815: [Persistence] Save to DB 
1611064606797: [Task] Add time spent 
1611064606801: [Project] Update Work End 
1611064606816: [Tag] Update Work End for Tag 
1611064606817: [Tag] Update Work End for Tag 
1611064606818: [Persistence] Save to DB 
1611064606818: [Persistence] Save to DB 
1611064606819: [Persistence] Save to DB 
1611064606819: [Persistence] Save to DB 
1611064607713: [Task] Toggle start 
1611064607716: [Persistence] Save to DB 
1611064607717: [Task] UnsetCurrentTask 
1611064622706: [WorkContext] Set Active Work Context 
1611064622721: [Task] SetSelectedTask 
1611064635310: [Task] Update Task 
1611064635747: [Persistence] Save to DB 
1611064641535: [WorkContext] Set Active Work Context 
1611064641553: [Task] SetSelectedTask 
1611064641626: [Note] Load Note State 
1611064641628: [Bookmark] Load Bookmark State 
1611064641630: [Metric] Load Metric State 
1611064641632: [Improvement] Load Improvement State 
1611064641643: [Obstruction] Load Obstruction State 
1611064641644: [Project] Load Project related Data Success 
1611064641644: [Improvement] Clear Hidden Improvements 
1611064641645: [Improvement] Delete multiple Improvements 
1611064645721: [Task] Delete Task
```

**Comment by johannesjo** [comment]
Hi there! Thank you very much for opening this up! I am unable to reproduce the issue however. Are you able to reproduce this yourself reliably?

**Comment by tpaixao** [comment]
Hi! Hmm, I also seem to not to be able to reproduce it... I was just testing the app, that happened, and I followed instructions to report it.. Not sure what happened though. Sorry for the false alarm (although it did happen, just not sure how to reproduce it). and thanks for the cool app!

**Comment by johannesjo** [comment]
No worries. It's very helpful that you reported this! This might have been caused by some sort of race condition, which just happens very very rarely, but definitely to look out for.

**Comment by tpaixao** [comment]
If it helps, this happened on a fresh instalation.
