### ISSUE TITLE
InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

### ISSUE THREAD

**Issue by marcinkoziej** [johannesjo/super-productivity#816]
### Steps to Reproduce
1. Running a task using pomodoro, this just happened

### Error Log (Desktop only)
Usually, you can find it here:
on Linux:
- I use super Producitvity from snap, can't find this log.log file!

Error reported is: 

Error: Uncaught (in promise): InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.    at Proxy.n (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:2356345)    at Proxy.s (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:2357427)    at t. (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:2365767)    at Generator.next ()    at a (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:2365105)    at l.invoke (file:///snap/superproductivity/969/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:6639)    at Object.onInvoke (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:1543328)    at l.invoke (file:///snap/superproductivity/969/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:6579)    at i.run (file:///snap/superproductivity/969/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:2051)    at file:///snap/superproductivity/969/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:16770
### Stacktrace
```
function (webpack:///node_modules/idb/build/esm/wrap-idb-value.js:150:25)
function (webpack:///node_modules/idb/build/esm/index.js:65:24)
constructor (webpack:///src/app/core/persistence/database.service.ts:49:49)
Ur (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:2365105)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:373:29)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:27488:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:55)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:135:46)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1274:39)
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1215:38)
makeResolver (webpack:///node_modules/zone.js/fesm2015/zone.js:1118:20)
Ur (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:1389281)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:373:29)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:27488:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:55)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:135:46)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1274:39)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:407:34)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:27476:32)
```

### Meta Info
META: SP6.1.1 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.1.1 Chrome/85.0.4183.121 Electron/10.1.5 Safari/537.36

### Actions Before Error
```
1611154062759: [Task] Add time spent 
1611154062760: [Project] Update Work End 
1611154062761: [Tag] Update Work End for Tag 
1611154062768: [Persistence] Save to DB 
1611154062769: [Persistence] Save to DB 
1611154062769: [Persistence] Save to DB 
1611154063759: [Task] Add time spent 
1611154063760: [Project] Update Work End 
1611154063760: [Tag] Update Work End for Tag 
1611154063765: [Persistence] Save to DB 
1611154063766: [Persistence] Save to DB 
1611154063766: [Persistence] Save to DB 
1611154064759: [Task] Add time spent 
1611154064760: [Project] Update Work End 
1611154064761: [Tag] Update Work End for Tag 
1611154064766: [Persistence] Save to DB 
1611154064766: [Persistence] Save to DB 
1611154064766: [Persistence] Save to DB 
1611154065759: [Task] Add time spent 
1611154065760: [Project] Update Work End 
1611154065762: [Tag] Update Work End for Tag 
1611154065769: [Persistence] Save to DB 
1611154065770: [Persistence] Save to DB 
1611154065770: [Persistence] Save to DB 
1611154069425: [Task] Add time spent 
1611154069427: [Project] Update Work End 
1611154069430: [Tag] Update Work End for Tag 
1611154069438: [Persistence] Save to DB 
1611154069439: [Persistence] Save to DB 
1611154069439: [Persistence] Save to DB
```

**Comment by johannesjo** [comment]
Thank you very much for reporting this. Did this happen more than once? And have you been running low on disk space by any chance?

**Comment by johannesjo** [comment]
Looking at #828 it seems likely to me that this is caused by your disk being full for some reason.

**Comment by johannesjo** [comment]
Are you by any chance all using the snap version @Fazzke @marcinkoziej @gibbsoft?

**Comment by gibbsoft** [comment]
Yes, using the snap Johannes...
```
Name               Version  Rev   Tracking       Publisher   Notes
superproductivity  6.3.3    1004  latest/stable  johannesjo  -
```

**Comment by johannesjo** [comment]
This should be fixed with the current release.
