### ISSUE TITLE
Cal Integration

### ISSUE THREAD

**Issue by esetera** [johannesjo/super-productivity#82]
hi

Great app! I'm sure you have considered it but I am wondering about calendar integration. It would be awesome to schedule tasks on a cal and have them synced via caldav (for example). This way I could see blocked out time for scheduled tasks on my shared cal.

**Comment by johannesjo** [comment]
Hey there! Thanks for opening up this issue. I like your suggestion. Syncing would be a little complicated to implement, because the data models are not really compatible and it would be hard to figure out a good ux. What I can imagine however, is a simple export to Cal function.l maybe in the time estimate dialog.

Would interesting to hear your thoughts about this one. How would you ideally like to work this?

**Comment by esetera** [comment]
hey. Interesting idea....export to ical could work very well. Exporting live would be pretty useful. I guess the app would need to know the timezone of the env. 
Ideally, from a workflow point of view, I would like to be able to block out a time on the cal in SP. This would be for the time I will work on my daily tasks. If that was exported then I could import into my cal app so I dont schedule other things at the same time... if it was exported via FTP then I could actually share it with others...

I#m not sure if that fits with your workflow...

**Comment by johannesjo** [comment]
I'm pretty open to everything really, as long as the UI doesn't get too bloated for users that don't need the feature. So putting this into the time estimation dialog might be a good compromise. 

I'm not sure though, when or if I'll be able to implement such a feature myself. Not really needing it for myself and having a lot more pressing issues on my plate (mainly performance and stability of this app), I probably won't be able to implement this anytime soon. But I happily accept Pull Requests for the issue and assist with questions that might a occur.

**Comment by mtelias2** [comment]
Any upates about this integration??
