### ISSUE TITLE
Persist last time for schedule

### ISSUE THREAD

**Issue by toolonely** [johannesjo/super-productivity#822]
Desktop version 6.3.3 running on Linux

I work on a task. I know I won't finish it today. I schedule it for tomorrow. In the opening dialog, the time is set to 9:00AM. I change that value and schedule the task. I repeat the same for another task. The time is set to 9:00AM again. I'd prefer that instead the program saves the time if I change it and makes it the new default for future tasks that I will want to schedule. Obviously, I want this in the mobile app as well.

**Comment by johannesjo** [comment]
Hey there! Thanks for opening this up! Probably makes sense to add this as an optional (but enabled per default, because I like it :)) feature.

**Comment by toolonely** [comment]
Up to you if you want to add a whole setting to toggle this behavior. I was thinking that people who want 9:00AM to stay the default behavior for tasks could still be happy if the changed default gets saved: it makes sense to assume that those people are using SU for work in the office, that starts at 9:00AM, so most if not all their tasks for the current day start at that hour. If an exception happens, the workflow for them will be like this:

- they shedule the uncommon task first. I call it uncommon because its schedule time is not 9:00AM, let it be 10:00AM. Without a setting SU will save 10:00AM as the default for all future tasks
- they shedule any regular task next. They change the schedule time back to 9:00AM. It gets saved again.
- for all future regular tasks SU works like it does now before any change related to this

This is very different: schedule time gets changed only twice by hand, as opposite to now, when I have to schedule 20+ tasks and need to change the schedule time by hand for each of them from the default 9:00AM.

So just making SO remember the last schedule time and making it the default for all future schedules requires less changes to the code. But it will come at the expense of slightly inconveniencing the users who are currently happy with the default behavior, whenever they would need to add a task with another schedule time (since they are happy with the default 9:00AM, we  can assume this doesn't happen often).

Adding a new option will make everyone happy, but will require a bit more coding. I'm really not against this if you prefer this approach. I have no problem setting a checkbox in Settings.

**Comment by johannesjo** [comment]
Makes a lot of sense what you are writing. What just came to my mind:
How to deal with scheduling multiple days in advance? This should probably be saved as well. But what if time moved on to the next day? What would be your expectation for this case?

**Comment by toolonely** [comment]
> How to deal with scheduling multiple days in advance? This should probably be saved as well. But what if time moved on to the next day? What would be your expectation for this case?

Frankly, I don't know. Because I have never met such a situation. I know very well that thinking only hypothetically about these things is very error prone - a lot of details get missed.

My situation with just the time is the result of a practical need - the inconvenience happened to me in practice and the use case is quite simple in terms of branching: it's either save the changed default time as new default, or not. And you proposed adding a setting to control this behavior. That's why it looks clearer. Scheduling multiple days in advance with different times for each is more branches, this may require a group brainstorming so more SP users would be required to speak up about their vision on the issue.

PS: I have no idea why I named SP (Super Productivity) SU, then SO above, I'll edit the post to fix it.
