### ISSUE TITLE
[Feature] Possibility to change date format

### ISSUE THREAD

**Issue by Acsigen** [johannesjo/super-productivity#83]
## Your Environment

* Version used: 1.10.38
* Operating System and version: Windows 7 x64

## Expected Behavior

As an European I wish I could be able to select the date format to dd/mm/yyyy when entering worked time for another date.
## Current Behavior

Currently the date format for the area mentioned before  is mm/dd/yyyy
## Steps to Reproduce (for bugs)

1. On a already created task add worked time for another date
2. Only one date format available

**Comment by johannesjo** [comment]
Hey! Thanks for reporting. I'm a little busy atm. But I'd like to see this functionality too. Would you maybe be willing to give the feature a shot yourself?
