### ISSUE TITLE
JQL query for limiting search result has no effect

### ISSUE THREAD

**Issue by naraesk** [johannesjo/super-productivity#833]
### Your Environment

* Version used: 6.3.3
* Operating System and version: Arch Linux (5.10.9-arch1-1)
* Desktop Environment: KDE Plasma 5.20

### Expected Behavior

When adding a new task and enabled JIRA integration, only tasks that match the JQL for limiting search results should appear in the auto suggestion

### Current Behavior

The auto suggestion contains a lot of tasks, that do not match the JQL for limiting search results.

### Steps to Reproduce (for bugs)

1. Enable Jira integration (used Jira v8.13.1)
2. I've testet the following JQL queries for limiting search results
* `assignee = currentUser() AND sprint in openSprints()`
* `assignee = myActualUsername AND sprint in openSprints()`
* `reviewer = currentUser() AND sprint in openSprints()`
3. Open the project and type in the "Add task" field

**Comment by johannesjo** [comment]
Thanks for reporting this! I try to check it this Friday!

**Comment by johannesjo** [comment]
Sorry for taking my time. I think I found the problem. I will provide a fix as soon as possible.
