### ISSUE TITLE
Time tracking for parent task with subtasks

### ISSUE THREAD

**Issue by maxeron** [johannesjo/super-productivity#834]
## Problem Statement
- I use subtasks for remembering what to do, and these tasks can be 10-15m short, which means I have to constantly start another subtask repeatedly and it's inconvenient

## :grey_question: Possible Solution
- Able to track time for parent task. The time tracked will be displayed in bracket next to the total time. 
- E.g. 3h 15m (30m)
- 3h 15m is the total time tracked, including the parent task. The 30m indicate how much time is tracked on the parent task.

## :heavy_plus_sign: Additional context
Problem Example
Let's say I have chores. Here's what the task would look like.
Chores
- Clean floor
- Wipe windows
- Take off trash
- Clean fan
- Wash dish
It's a bit inconvenient to have to come back and track one by one when they took little time. And sure, I could just have the parent task without the subtasks, but sometimes I forget what to do. I would like to be able to check what I've done and see what I haven't done, and I would also sometime track time on subtasks that takes a long time to finish. 

A different approach would be to just use the description to list things I want to do. But that's not really what it's for and it's bothersome to check what things I need to do.

Hope this helps clarify the problem.

**Comment by johannesjo** [comment]
Thanks for opening this up. Personally I like the way it is, but I can see this happening as an optional feature, if somebody wants to tackle this.
