### ISSUE TITLE
Can not use shortcut for showing project notes

### ISSUE THREAD

**Issue by phuoc-insignia** [johannesjo/super-productivity#838]
### Your Environment

* Version used: 6.3.3
* Operating System and version: MacOs Catalina 10.15.7
* Desktop Environment: Mac
* Browser Name and version: Desktop

### Expected Behavior
The app should show the project note view

### Current Behavior
Not showing at all

### Steps to Reproduce (for bugs)

1. Navigate to project view
2. Try to press default shortcut for showing note (Shift + n)
3. Nothing showed up
4. Try to change the shortcut to ctr + n
5. Repeat step 1 -> 3

### Console Output
No error founded

**Comment by phuoc-insignia** [comment]
seems the show backlog shortcut does not work either

**Comment by johannesjo** [comment]
Hi there! Thanks for opening this up. This is not a bug, but the rather the current limitations of the notes feature (changes are already planned, but will take some time). Notes are only saved on a project level, so the shortcuts are only working if you have a project selected in the left hand menu.
