### ISSUE TITLE
Error: No first tag

### ISSUE THREAD

**Issue by abhyudaya63** [johannesjo/super-productivity#843]
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
this._projectService.getByIdOnce$(projectId).toPromise (webpack:///src/app/features/tasks/add-task-bar/add-task-bar.component.ts:294:14)
Ur (file:///snap/superproductivity/1004/resources/app.asar/dist/main.839fd4a6fbc40d5fd73d.js:1:3061082)
constructor (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1383:28)
Ur (file:///snap/superproductivity/1004/resources/app.asar/dist/main.839fd4a6fbc40d5fd73d.js:1:3060827)
Ur (file:///snap/superproductivity/1004/resources/app.asar/dist/main.839fd4a6fbc40d5fd73d.js:1:3069588)
_getCtxForTaskSuggestion (webpack:///src/app/features/tasks/add-task-bar/add-task-bar.component.ts:354:29)
map (webpack:///src/app/features/tasks/add-task-bar/add-task-bar.component.ts:352:27)
_next (webpack:///node_modules/rxjs/_esm2015/internal/operators/switchMap.js:28:26)
```

### Meta Info
META: SP6.3.3 Electron – en-GB – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.3.3 Chrome/85.0.4183.121 Electron/10.2.0 Safari/537.36

### Actions Before Error
```
1611922887808: [Task] Update Task 
1611922887809: [Persistence] Save to DB 
1611922891347: [Task] SetSelectedTask 
1611922903198: [Task] SetSelectedTask 
1611922915446: [TaskRepeatCfg][Task] Add TaskRepeatCfg to Task 
1611922915448: [Persistence] Save to DB 
1611922915448: [Task] Remove reminder 
1611922915449: [Persistence] Save to DB 
1611922915449: [Persistence] Save to DB 
1611922915449: [Persistence] Save to DB 
1611922915449: [Task] Update Task 
1611922915450: [Persistence] Save to DB 
1611922918212: [Task] Update Task 
1611922918506: [Persistence] Save to DB 
1611922921538: [Task] SetSelectedTask 
1611922961934: [Task] SetSelectedTask 
1611922970670: [Task] SetSelectedTask 
1611922986425: [Task] SetSelectedTask 
1611923002966: [Task] Update Task 
1611923002967: [Persistence] Save to DB 
1611923007437: [Task] SetSelectedTask 
1611923009648: [Task] Update Task 
1611923009653: [Persistence] Save to DB 
1611923016372: [Layout] Show AddTaskBar 
1611923027666: [Layout] Hide AddTaskBar 
1611923033468: [SP_ALL] Load(import) all data 
1611923033470: [SP_ALL] All Data was loaded 
1611923033476: [WorkContext] Set Active Work Context 
1611923033496: [Task] SetSelectedTask 
1611923037230: [Layout] Show AddTaskBar
```

**Comment by johannesjo** [comment]
Hi there! Thanks for opening this up. Could you maybe provide a little bit more context? When did this happen. Did it happen just once or multiple times etc.?

**Comment by abhyudaya63** [comment]
this happened multiple times when trying to add a task.
The problem persisted till I restarted the application. Now it works fine.

**Comment by johannesjo** [comment]
Alright! Thanks for letting me know!

**Comment by abhyudaya63** [comment]
It is happening again and there seems to be a problem with certain letters when adding a task.
I cannot have a task named 'Day' or 'Start'. I already had 'Day End' so it must have worked fine before.

**Comment by johannesjo** [comment]
Hm this is weird. I am unable to reproduce this also. Could you provide me with the exact steps how to reproduce this? 
Hey there! Thank you very much for reporting this!

It might also be that your data got into an invalid state that I didn't account for and that I can't reproduce. Hence it would be great if you could share a copy of your data to contact@super-productivity.com, so I can debug this on my computer. You can create an export by navigating to "Settings" and then to "Import/Export".

**Comment by johannesjo** [comment]
Thanks for your data. What happened is that you created a repeating task that neither belonged to a project nor did it belong to a task and this lead to the error. If you send me your current data again, I can fix it for you. If you want to fix it for yourself you can open the export file with a text editor and search for all tasks that have `"projectId": null` and an empty tagIds array (`"tagIds": []`) and replace `"tagIds": []` with `"tagIds": ["TODAY"]`. Be sure to make an extra copy if you attempt this.
