### ISSUE TITLE
Convert to RPM with Alien failing 

### ISSUE THREAD

**Issue by theunclemez** [johannesjo/super-productivity#844]
### Your Environment
* Version used: 6.3.3
* Operating System and version: Opensuse tumbleweed latest
* Desktop Environment: Gnome 3.38.3

### Expected Behavior
alien should be able to convert the .deb provided here with ease

### Current Behavior
Using alien to convert .deb to .rpm but it is not working and failing ever and ever.

### Steps to Reproduce (for bugs)
Open terminal into cloned folder or different folder where .deb file have been saved and do:
`sudo alien --to-rpm --scripts superProductivity_6.3.3_amd64.deb `

### Console Output
```
sudo alien --to-rpm --scripts superProductivity_6.3.3_amd64.deb 
Package build failed. Here's the log of the command (cd superproductivity-6.3.3; rpmbuild --buildroot='/home/theunclemez/Public/superproductivity-bin/superproductivity-6.3.3' -bb --target x86_64 'superproductivity-6.3.3-2.spec'):
error: line 5: Empty tag: Summary:
Building target platforms: x86_64
Building for target x86_64
```

**Comment by johannesjo** [comment]
Thanks for opening this up, but this is a working deb. I would argue that this is rather an issue of alien, but not Super Productivity.

**Comment by NumDeP** [comment]
Hi @johannesjo I'm on the latest `7.0.0-rc13` release as I downloaded the .rpm file. I was just wondering if this issue is now redundant because I'm assuming you package the .rpm file now?

So it can be closed?

**Comment by johannesjo** [comment]
Thanks for bringing this to my attention! I am closing this! Always a good feeling. One down 168 issues to go :D
