### ISSUE TITLE
Several Issues with the new git integration

### ISSUE THREAD

**Issue by johannesjo** [johannesjo/super-productivity#845]
@b0c1 

I've been pretty swamped lately so apologies that I just now found the time to have a closer look at the changes.

Unfortunately there are several issues I encountered with the [PR you made](https://github.com/johannesjo/super-productivity/pull/776) .

1. First of all the GitHub Integration is not usable without an api token anymore, as otherwise the user can't be determined.
2. There is no option anymore to autimport all unresolved issues. When it comes to the github integration I would think that this is the desirable behavior for 90% of all repositories as they are smaller projects with only a single or a handful of owners and only a couple of issues. E.g. this project is my biggest one. Still I usually don't bother with assigning issues to myself and I have to look at all the issues anyway.
3. The removing part is a bit problematic, as it might remove issues that have been already worked on or sub tasks or what not. Tasks with notes, timeSpent, timeEstimate, isDone, tags or a reminder should never be removed.
4. The removing part might also wrongfully remove issues, because we only ever get 100 issues at once from the github api (we could try to get more but there will always be limits, as there are rate limits and we can never be sure to get all the issues). 
5. Something similar is true for the gitlab api. 
6. In terms of caching there might be ways to work with what the Rest APIs got to offer. But trust me, this is a complex topic we should tackle on it's own and not as part of some other changes.

I will revert the changes for now. I would love for all the stuff to be added again, if your still up for the challenge. If you are I would greatly appreciate it, if we would cut the changes into smaller bits this time as this would make it a lot easier to review and discuss them.

**Comment by nunojsa** [comment]
Hi,

I was going though this and I would like to add some comments. Would it make sense for a task to be automatically removed if the the issue is closed on github (or gitlab)? I was expecting that to happen but I realized that it doesn't...

I was also surprised to see that PRs are also imported. Maybe a setting for this would be a nice to have as for me, I'm not really interested in seeing PRs. PR is already the ending part of a task :smile: 

Thanks!
