### ISSUE TITLE
504 errors with Webdav sync

### ISSUE THREAD

**Issue by personaaleatoria** [johannesjo/super-productivity#846]
I'm trying to use superproductivity with Koofr.eu on all my devices. I'm also using Koofr cloud storage for some other Webdav applications.

I was able to connect to Koofr with the desktop superproductivity app but not through the android app.

I have followed their instructions at their documentation about [webdav services](https://koofr.eu/help/koofr_with_webdav/how-do-i-connect-a-service-to-koofr-through-webdav/) but without success for the android app.

I'm using superproductivity 6.3.3 on android 10.

Sync settings:

[x] Enable syncing
* Sync interval: 1m (for tests) 
* Base url: `https://app.koofr.net`
* Username: >My koofr email<
* Password: >My Koofr application password<
* Sync File path: `/dav/Koofr/my/custom/file.json`

file.json already exists from my tests with the desktop app.

 When I save the settings and wait I get the following message:

`The page at "https://app.super-productivity.com" says: no remote data found. Upload local to Remote?`

Which is not correct because the file exists from the desktop sync.

If I click OK I see the errors pop up:

`Unknown Sync Error: Error: Request failed with status code of 504`
`Unknown Upload Error: (Settings correct?): Error: Request failed with status code 504.`

I contacted Koofr support and we verified credentials (the info I am using above is correct according to them) but we couldn't make it work and they advised me to contact superproductivity team as they thought the error might not be on their end.

**Comment by johannesjo** [comment]
Hi there thanks for opening this up. This looks more like a question to me. Could you maybe reopen it on the q&a section? I gladly try to help you there:
https://github.com/johannesjo/super-productivity/discussions/categories/q-a
