### ISSUE TITLE
May I request a .apk format for Android users on Github?

### ISSUE THREAD

**Issue by Barak123748596** [johannesjo/super-productivity#848]
You see, Huawei is banned from using Google Services. So would you like to upload a .apk format for Chinese users to install?

**Comment by johannesjo** [comment]
Hi there! You can download the app from here:
https://github.com/johannesjo/super-productivity-android/releases/tag/v7.0
Or here:
https://f-droid.org/en/packages/com.superproductivity.superproductivity/
