### ISSUE TITLE
Use estimated time in planning mode

### ISSUE THREAD

**Issue by user2334280** [johannesjo/super-productivity#85]
Currently, in planning mode, the total time shown is the total planned time, even if some (sub)tasks have been finished or worked on already. This is confusing when planning the day, because it shows a much higher time count than the actual remaining time. In the screenshot below you can see how it shows 5 hours for today, where there actually only 2 left.

(The same goes for the backlog, which shows 6,35 hours, where there's only 1 left) 

Preferred behavior: showing the same estimate remaining in planning mode as in working mode. 

(I'm on 1.10.38.473)

![schermafbeelding 2018-06-03 om 09 37 39](https://user-images.githubusercontent.com/39873394/40884327-cb0abb02-6711-11e8-9507-e9e6d4ddb3d4.png)

**Comment by johannesjo** [comment]
Hey there! Thanks for reporting! I agree. This should be fixed. I'll have a look.

**Comment by johannesjo** [comment]
This should be fixed with the next release.

**Comment by user2334280** [comment]
Cool! Thanks for the quick response. I'm currently seriously getting into web programming and I'm planning on getting into javascript soon (and checking out Electron on the way). So I hope I'll be able to start contributing in a few months.

**Comment by johannesjo** [comment]
Oh. That's cool to hear! My advice, if I may give some: start with a little fun vanilla js project of your own, imho that's the best way to learn!
