### ISSUE TITLE
apt throws error while updating

### ISSUE THREAD

**Issue by jeensg** [johannesjo/super-productivity#86]
## Your Environment
* Version used: 1.10.40-483, debian-ubuntu repository
* Operating System and version: ubuntu 18.04 bionic
* Desktop Environment: xubuntu
* Browser Name and version: --

## Expected Behavior
When updating sources, apt shouldn't throw errors.

## Current Behavior
W: Das Laden der konfigurierten Datei »super-productivity/i18n/Translation-de_DE« wird übersprungen, da das Depot »https://dl.bintray.com/johannesjo/super-productivity stable InRelease« die Komponente »super-productivity« nicht enthält. (Schreibfehler bei der Angabe der Komponente in sources.list?)
W: Das Laden der konfigurierten Datei »super-productivity/i18n/Translation-en« wird übersprungen, da das Depot »https://dl.bintray.com/johannesjo/super-productivity stable InRelease« die Komponente »super-productivity« nicht enthält. (Schreibfehler bei der Angabe der Komponente in sources.list?)
W: Das Laden der konfigurierten Datei »super-productivity/i18n/Translation-de« wird übersprungen, da das Depot »https://dl.bintray.com/johannesjo/super-productivity stable InRelease« die Komponente »super-productivity« nicht enthält. (Schreibfehler bei der Angabe der Komponente in sources.list?)
W: Das Laden der konfigurierten Datei »super-productivity/dep11/Components-amd64.yml« wird übersprungen, da das Depot »https://dl.bintray.com/johannesjo/super-productivity stable InRelease« die Komponente »super-productivity« nicht enthält. (Schreibfehler bei der Angabe der Komponente in sources.list?)
W: Das Laden der konfigurierten Datei »super-productivity/dep11/icons-48x48.tar« wird übersprungen, da das Depot »https://dl.bintray.com/johannesjo/super-productivity stable InRelease« die Komponente »super-productivity« nicht enthält. (Schreibfehler bei der Angabe der Komponente in sources.list?)
W: Das Laden der konfigurierten Datei »super-productivity/dep11/icons-64x64.tar« wird übersprungen, da das Depot »https://dl.bintray.com/johannesjo/super-productivity stable InRelease« die Komponente »super-productivity« nicht enthält. (Schreibfehler bei der Angabe der Komponente in sources.list?)
W: Das Laden der konfigurierten Datei »super-productivity/cnf/Commands-amd64« wird übersprungen, da das Depot »https://dl.bintray.com/johannesjo/super-productivity stable InRelease« die Komponente »super-productivity« nicht enthält. (Schreibfehler bei der Angabe der Komponente in sources.list?)

## Steps to Reproduce (for bugs)
1. echo "deb https://dl.bintray.com/johannesjo/super-productivity stable super-productivity" | sudo tee -a /etc/apt/sources.list.d/productivity.list
2. wget -O - https://bintray.com/user/downloadSubjectPublicKey\?username\=bintray | sudo apt-key add -
3. sudo apt update

**Comment by johannesjo** [comment]
Thank you very much for reporting. I'm currently on vacation, so I won't be able to properly reproduce this here (only got access to a macbook air here). I'll try rebuilding for now, but I won't be able to properly check until I'm back.

**Comment by johannesjo** [comment]
I digged a little into this and it seems to be a problem on either bintrays or electron builders end. It's not beautiful but the package should still install. I'll update electron builder and publish a new version. Hopefully this will fix it otherwise I might put this on hold for while as problems with publishing are really painful to fix (take a long time to build and upload the package) and possibly out of my hands anyway. I rather spent my time on something that feels productive ;)

**Comment by jeensg** [comment]
Installed 1.10.45-497 but error persists. I understand why putting it on hold, it's possible to install, yes, the other bugs would be nicer to be fixed :-)

**Comment by jeensg** [comment]
Update: with cosmic cuttlefish (ubuntu 18.10) this error is gone :-)
