### ISSUE TITLE
Erroneous grammar in https://app.super-productivity.com/#/config

### ISSUE THREAD

**Issue by pivic** [johannesjo/super-productivity#864]
### Expected Behavior
At the bottom of https://app.super-productivity.com/#/config see text named 'Privacy policy' or 'Privacy Policy'.

### Current Behavior
Text reads 'Private Policy':

![image](https://user-images.githubusercontent.com/7044495/106711698-2c08c880-65f8-11eb-85a6-db6b16a12c2e.png)

### Steps to Reproduce (for bugs)

1. Go to https://app.super-productivity.com/#/config.
2. Scroll to the bottom of the page.
3. Read what the line at the bottom says.

**Comment by johannesjo** [comment]
All these years I thought it's private policy, but privacy policy makes a lot more sense xD

Thank you!
