### ISSUE TITLE
I disabled all reminders it still shows popups "You have been idle for:"

### ISSUE THREAD

**Issue by gerroon** [johannesjo/super-productivity#869]
### Your Environment

* Version used:  6.3.3
* Operating System and version: Debian, .deb

### Expected Behavior
I disabled all the notifications so I do not want to be bothered with any po ups opr notifications

### Current Behavior
It keeps showing me the "You have been idle for"

### Steps to Reproduce (for bugs)
Settings - > disable all notifcations/reminders related settings - > save

**Comment by johannesjo** [comment]
Hi there! Not sure where you disabled all notifications (to my knowledge there is no such setting) but all settings regarding the idle handling can be found under "Idle Handling" in the settings.
