### ISSUE TITLE
Background image caching

### ISSUE THREAD

**Issue by aspieln3r** [johannesjo/super-productivity#876]
## Problem Statement
when setting a background image on web version using a url, the image has to be reloaded everytime a project is opened. It takes a bit of time to load the image and there is a visible lag. 

## :grey_question: Possible Solution
Cache images locally

**Comment by aspieln3r** [comment]
.

**Comment by johannesjo** [comment]
In theory this should work now, though I've to admit, that I haven''t tested it.
