### ISSUE TITLE
Github Action for publishing AUR failed

### ISSUE THREAD

**Issue by johannesjo** [johannesjo/super-productivity#877]
Not sure what happened. The error message is:
```
error: failed to initialize alpm library
```
https://github.com/johannesjo/super-productivity/runs/1850082672?check_suite_focus=true

 Could you maybe have a look, if you find the time @alosarjos ?

**Comment by alosarjos** [comment]
Hmmm, I've checked it, but seems to be failing on the GitHub actions side of things. I would try relaunching the action, to check if it was something temporal. If it happens again, maybe we should fill an issue on :

https://github.com/KSXGitHub/github-actions-deploy-aur

**Comment by johannesjo** [comment]
Thank you for looking into it! I'll already restarted it a couple of times, but I try again tomorrow.

**Comment by alosarjos** [comment]
Let's give another shot tomorrow, I will keep an eye in case I see something related to this.

**Comment by sickcodes** [comment]
We are also getting the same error on a different project building Docker images from archlinux:latest:

`https://github.com/sickcodes/Docker-OSX/issues/144`

Bug is related to glibc and is featured here:

https://bbs.archlinux.org/viewtopic.php?id=263379

https://bugs.archlinux.org/task/69563

**Comment by johannesjo** [comment]
Thanks for sharing @sickcodes !

**Comment by sickcodes** [comment]
hub.docker.com said they will update when they've rolled out the following PR which has already been merged:

https://github.com/opencontainers/runc/pull/2750

**Comment by alosarjos** [comment]
A user already reported that the AUR version is outdated. 

At least that means that this package has some active users on Arch 😅😅😅

**Comment by johannesjo** [comment]
Still failing: https://github.com/johannesjo/super-productivity/actions/runs/545608520

**Comment by alosarjos** [comment]
> Still failing: https://github.com/johannesjo/super-productivity/actions/runs/545608520

AFAIK The fix is done and merged but not deployed. Hoping this is just a matter of waiting and then relaunching.

If you want I can push manually the update to AUR later

**Comment by johannesjo** [comment]
Ah alright! Thanks for the explanation!

**Comment by alosarjos** [comment]
I'm guessing this kind of changes could take a few days getting deployed because of all the things they will have to test before. When I arrive at home I'll try to upgrade the AUR and tell you.

**Comment by alosarjos** [comment]
I have updated manually  the AUR package to 6.4.0

**Comment by johannesjo** [comment]
Thanks @alosarjos !

**Comment by sickcodes** [comment]
@MrBenFTW fixed it temporarily for us using this:

https://github.com/sickcodes/Docker-OSX/pull/150

**Comment by johannesjo** [comment]
Thanks for sharing   @sickcodes . Let's use it If this isn't fixed with the next release.

**Comment by sickcodes** [comment]
No problem!

We're using it, among these folks (and more):

https://github.com/lxqt/lxqt-panel/pull/1562

https://github.com/zocker-160/aur-builder/commit/1c66e2e5518a207499766c7f0bba119ef0e30a58

https://github.com/qutebrowser/qutebrowser/commit/478e4de7bd1f26bebdcdc166d5369b2b5142c3e2

**Comment by alosarjos** [comment]
Do we have any news on this?

**Comment by johannesjo** [comment]
Still failing!
https://github.com/johannesjo/super-productivity/runs/1968743680?check_suite_focus=true

**Comment by alosarjos** [comment]
Until it gets fixed, you can ping me here whenever you update the package
and I'll update it manually on AUR

**Comment by johannesjo** [comment]
Thanks @alosarjos ! I will do so!

**Comment by alosarjos** [comment]
I was just checking around, and looks like the action is still failing?

**Comment by alosarjos** [comment]
Oh, it actually worked! 

I misread with another superproductivity versions on AUR. I guess we can close this issue then?

**Comment by johannesjo** [comment]
Looks like it! Thanks for checking! I am closing this then.
