### ISSUE TITLE
Is there an existing way to include time estimate in task creation text?

### ISSUE THREAD

**Issue by blahah** [johannesjo/super-productivity#88]
Not an issue report, but I couldn't find another place to ask this question:

Is there an existing feature that allows me to include the time estimate for a task in the text when creating it inside the app interface?

I read through all the help screens I thought would be relevant but couldn't find an answer. Thanks for this fantastic application and all your hard work.

**Comment by johannesjo** [comment]
Hey there! Yes there is. It's called Short Syntax and you might need to enable it via the Settings. When enabled you can type something like `My task t2h` to create a task with an estimate of 2 hours time.

**Comment by blahah** [comment]
Aha! Thank you, I now see it in the settings and the help for that pane.
