### ISSUE TITLE
Add issue link to task when importing issues from Github

### ISSUE THREAD

**Issue by blahah** [johannesjo/super-productivity#89]
Feature request:

When importing issues from Github, add a link to the Github URL for the issue to the task, so it is easy to move to the context of that issue, see the discussion, etc.

**Comment by johannesjo** [comment]
Hi! The github url should already be available via the Github icon left of the task title.

**Comment by blahah** [comment]
Aha! Thank you for explaining. This was not at all obvious to me - would it also make sense to add it as a link to the task, like any other link would be created?

**Comment by johannesjo** [comment]
That's not a bad idea. Thanks for suggesting it!

**Comment by johannesjo** [comment]
Should be implemented now and available with the next release.
