### ISSUE TITLE
Make text translatable 

### ISSUE THREAD

**Issue by mrtngrsbch** [johannesjo/super-productivity#892]
## Problem Statement
I see a message in EN in my ES interface and I can't find the translation string.

![imagen](https://user-images.githubusercontent.com/693328/107562587-c780d700-6bbe-11eb-94e0-50ac2995fe9d.png)

## :grey_question: Possible Solution
Add string in /master/src/assets/i18n/*.json

## :arrow_heading_up: Describe alternatives you've considered
I do not know

## :heavy_plus_sign: Additional context

Version 6.4.0
MacOS 10.15.7

**Comment by johannesjo** [comment]
There is no good solution for these user editable strings yet (another example would be the "Today" list), but you can edit it under settings/productivity helper/break reminder.

**Comment by mrtngrsbch** [comment]
cool!
It's not a big deal to edit the string if you have another translation method.

I am new and very happy with this app and would like to create more issues, but seeing the existing queue I would not want to overload it.

best

**Comment by johannesjo** [comment]
> I am new and very happy with this app and would like to create more issues, but seeing the existing queue I would not want to overload it.

There sure is a lot going on atm. :D But if you think you got something please don't hesitate to open up some issues. It might take some time for me to respond though.
