### ISSUE TITLE
Show undone tasks rather than all tasks in left hand menu

### ISSUE THREAD

**Issue by dv0zn3r** [johannesjo/super-productivity#895]
### Your Environment

* Version used: 6.4.0 (6.4.0)
* Operating System and version: MacOS Big Sur 11.2, Android 9

### Expected Behavior

If I complete the task in Today's mode, I expect the counter on the left to change and represent only unfinished task.

### Current Behavior

The counter does not change after completing the task in Today's mode.

### Steps to Reproduce (for bugs)

1. Add the task on Today's list.
2. Complete the task on Today' list.
3. Look at the counter on the left.

**Comment by johannesjo** [comment]
Hi there! The number on the left shows all the tasks (and in addition for projects all the tasks in the backlog). Might make sense to change this though.

**Comment by johannesjo** [comment]
While I would very much prefer to only have the undone tasks being counted, we should check the performance  impact of adjusting this as it should be a bit more demanding than the current implementation.

PRs are welcome!
