### ISSUE TITLE
[BUG] After pressing couple of times escape button, the left sidebar items dissapeared

### ISSUE THREAD

**Issue by dodalovic** [johannesjo/super-productivity#896]
* `Pop OS 20.10`

After pressing couple of times escape button, the left-hand side navbar dissapeared, and only **Today** was left: 

![image](https://user-images.githubusercontent.com/6358061/107639876-c65cb200-6c71-11eb-856e-8600bd8adaed.png)

![image](https://user-images.githubusercontent.com/6358061/107640112-15a2e280-6c72-11eb-8452-d94373d915e6.png)

**Comment by johannesjo** [comment]
Thanks for reporting.
