### ISSUE TITLE
[BUG] Wrong value for today's worklog

### ISSUE THREAD

**Issue by dodalovic** [johannesjo/super-productivity#897]
In the **worklog view** for today:

![image](https://user-images.githubusercontent.com/6358061/107664665-f5345180-6c8c-11eb-95ec-2b3f54742619.png)

there is one item (out of total 6) kind of cached, that doesn't belong there:

It has some weird `-`, as duration:

![image](https://user-images.githubusercontent.com/6358061/107665463-be127000-6c8d-11eb-8882-88bc27f8c713.png)

Is there anything I can do to kick it out somehow?

Thanks!

**Comment by johannesjo** [comment]
These tasks should be those marked done on a day, but have no time spent at all. It's intentional that they show up, because otherwise they would be lost in the void.
