### ISSUE TITLE
[FEATURE REQUEST] Collapse completed tasks

### ISSUE THREAD

**Issue by plamkas** [johannesjo/super-productivity#898]
Hello, is it possible to make the completed tasks collapsable? Even though it is nice to see how much was already done it could be somehow distracting sometimes.

**Comment by johannesjo** [comment]
That's a good idea. Thanks! I've to think about the best UI for this. Do you have a suggestion for it?

**Comment by plamkas** [comment]
Thanks for the swift reply.
I you ask me, you can use the same concept as for the backlog. Placing a second "half-circle" at the bottom with some suitable icon (checkmark?) within. Click on it and the completed tasks show up.

P.S. Thanks for this great piece of software! Discovered it just a couple of days ago and already enjoying it a lot.
