### ISSUE TITLE
Quit doesn't work.

### ISSUE THREAD

**Issue by jeensg** [johannesjo/super-productivity#90]
## Your Environment
* Version used: 1.10.42-489, debian-ubuntu repository
* Operating System and version: ubuntu 18.04 bionic
* Desktop Environment: xubuntu
* Browser Name and version: --

## Expected Behavior
When I try to quit the program, it should quit :-)

## Current Behavior
When I try to quit the program, the problems start :-) First of all, it doesn't quit, but stays open. Furthermore it's then not possible to minimize the program to tray (x on the above right corner for quitting to tray -- minimize and maximize-buttons still work).
After all I have to kill the process, since stopping it doesn't work neither.
That's when I probably loose my saved work, since with a nex start, all Donetasks are gone ... 

## Steps to Reproduce (for bugs)
1. Start program.
2. Try to quit it.

**Comment by johannesjo** [comment]
Very likely related to #91

**Comment by jeensg** [comment]
I suppose so. Somehow the app can't be closed correctly in general. Maybe it's better to go on here for better title (better than #90) :-) is it somehow possible check other errors on starting app? Temrinal isn't saying nothing neither on starting app from there. Closing doesn't work neither then ...

**Comment by johannesjo** [comment]
I'm assuming that this is probably related to the close to tray code and xubuntu (I'm running gnome and only rarely test the other DEs to be honest). I will have to set up a VM to check this behavior properly. That there is no error nowhere printed is suprprising.

**Comment by johannesjo** [comment]
Hm just checked on a fresh xubuntu install (18.04). All works as expected. Do you have Google Drive Syncing enabled?

**Comment by jeensg** [comment]
Hey, I rarely changed setup after install. Don't have Gdrive enabled ... think I only set up automatic backup every day. Will try installing in a fresh environment also, let's see (maybe it's because of my general setup of xubuntu, don't know what it could be). Will report back.
