### ISSUE TITLE
Tasks Disappear after "Finish Day"

### ISSUE THREAD

**Issue by mrcomptech** [johannesjo/super-productivity#901]
OS Name	Microsoft Windows 10 Pro
Version	10.0.18363 Build 18363
System Type	x64-based PC
Processor	Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz, 2601 Mhz, 4 Core(s), 8 Logical Processor(s)

Installed SP using Windows Store.

### Expected Behavior
This just happened yesterday (2021-02-12) and similarly the day before. 
After a cycle of :
    click "Ready to Work", 
    set tasks for today, 
    perform tasks, 
    tasks not worked on today are unset so only tasks on which time was spent are left on the "Today !!!" screen,
    click "Finish Day" --> "Save and Go Home" --> "No just clear the tasks" --> summary report is shown

### Current Behavior
ALL tasks on which time had been recorded have been removed from the program after "Finish Day", no entries can be found so they did not get moved into another category. So, now in order to repeat those tasks for today (they were already set to repeat on  Mon - Sat) they must be re-entered from scratch.

Even though I have already 'Finished the Day' the "Today !!!" screen still has the "Finish Day" button and no "Ready to Work" button ---- until I restart the program. Then there is a "Ready to Work" button and no "Finish Day" button which is normal. But the completed tasks are gone as in no where to be found within the categories. Only the tasks that had NOT been performed yesterday are still there today. The day __before__ yesterday a very similar thing happened except that after restarting SP the missing tasks were back. But yesterday they did not reappear - I'm very discouraged, I don't want to have to re-enter all the tasks every day. That's not Super Productive.

### Steps to Reproduce (for bugs)

I won't find out until I setup all new tasks as best i can remember and then perform those tasks today.

### Console Output

Didn't realize this was a feature, all I can do is check next time, but no error message was displayed when this occurred.

### Error Log (Desktop only)
There is no SuperProductivity directory in %USERPROFILE%\AppData\Roaming\superProductivity 
and so there is no log.log file.
. -->

**Comment by mrcomptech** [comment]
I have now confirmed this problem - that when clicking the checkmark to denote a task as done for today and then click "Finish Day" the tasks are removed from the program.

I just had a thought that maybe I shouldn't be clicking the checkmark at the end of the day for a task that I want to do tomorrow, but instead only click "Finish Day". I am now thinking this is probably the case. But how is the end user supposed to know this without documentation?

I have confirmed that I have been using the app incorrectly and that at the end of the day, the user should only click "Finish Day" if the task is going to be performed on a later day at some point in the future and should only click the checkmark if the task is to be finished today AND removed from the tasks listed under a category. - "Its OK, O know where I am, I know where I am" - Batty from FernGully: The Last Rainforest

**Comment by mrcomptech** [comment]
I have confirmed that I have been using the app incorrectly and that at the end of the day, the user should only click "Finish Day" if the task is going to be performed on a later day at some point in the future and should only click the checkmark if the task is to be finished today AND removed from the tasks listed under a category. - "Its OK, O know where I am, I know where I am" - Batty from FernGully: The Last Rainforest

**Comment by johannesjo** [comment]
Hi there! Thank you very much for opening this up! If you mark tasks as done (excluding sub tasks, which are handled together with their parent) and click "Finish day" those tasks are copied to the task archive, which can be accessed hovering over the project/tag name clicking the three little dots and selecting "Worklog". From there you can still edit the time spent or restore them from the archive to work on them again.
