### ISSUE TITLE
Program startup "Tips" - display longer or add a close button.

### ISSUE THREAD

**Issue by mrcomptech** [johannesjo/super-productivity#902]
There is not enough time to read the start of day "Tips". At program startup, on Windows 10, they are on the screen for less than a second, that is not enough time to glimpse more than the first three words. Display of tips needs option button to select to show or hide tips on startup and a button for close and/or next tip.
Thanks

**Comment by johannesjo** [comment]
Thanks for opening this up! The tips are ment to be just a fancy loading screen and if the app happens to start very quickly you are one of the lucky ones. Enabling sync should make the startup slower and display the tips longer. There is only a limited number of them and they are not translated (the translation mechanics are not ready at that point), so they're of limited use to people that don't know English, thus I am not sure if we should add an extra delay to allow to read them or what would be the ideal way to deal with all this. What do you think?

**Comment by mrcomptech** [comment]
I understand and agree that this is not a significant issue.
