### ISSUE TITLE
Habitica to-do integration

### ISSUE THREAD

**Issue by N-Upchurch** [johannesjo/super-productivity#904]
Hi there, I use Habitica to stay motivated, but I never use it as a task manager, because it lacks a simple todo-focused interface. Habitica integration would be incredibly useful in super-productivity - just an option to enter api key and user ID in settings and then have tasks automatically added to todos in Habitica would be amazing.

**Comment by johannesjo** [comment]
Thanks for opening this up! Any volunteers for this? :)

**Comment by N-Upchurch** [comment]
Of course, it occurs to me that completed tasks should also complete the to-do in Habitica.
