### ISSUE TITLE
Error: Uncaught (in promise): Error: Request failed with status code 400

### ISSUE THREAD

**Issue by ludivn** [johannesjo/super-productivity#907]
Hello,

I've been using SuperProductivity for a few days now, and I really like it! But everytime I try to end my day by clicking on the button, there is this error window:

> 
> Error: Uncaught (in promise): Error: Request failed with status code 400 Error: Request failed with status code 400 at LYNF.e.exports (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.4.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.11bce23b86ad07ade3d1.js:1:829611) at Rn+g.e.exports (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.4.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.11bce23b86ad07ade3d1.js:1:1327378) at XMLHttpRequest.p.onreadystatechange [as __zone_symbol__ON_PROPERTYreadystatechange] (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.4.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.11bce23b86ad07ade3d1.js:1:2142253) at XMLHttpRequest.D (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.4.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:11438) at l.invokeTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.4.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:7190) at Object.onInvokeTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.4.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.11bce23b86ad07ade3d1.js:1:384270) at l.invokeTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.4.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:7111) at i.runTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.4.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:2599) at u.invokeTask [as invoke] (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.4.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:8240) at _ (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.4.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:20167)
> ! Please copy & report !

> exports (webpack:///node_modules/axios/lib/core/createError.js:16:14)
> validateStatus (webpack:///node_modules/axios/lib/core/settle.js:17:11)
> request.responseURL.indexOf (webpack:///node_modules/axios/lib/adapters/xhr.js:62:6)
> listener.call (webpack:///node_modules/zone.js/dist/zone-evergreen.js:759:38)
> invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:402:30)
> onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:28499:32)
> invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:401:59)
> task._transitionTo (webpack:///node_modules/zone.js/dist/zone-evergreen.js:174:46)
> invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:483:33)
> callback (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1596:13)
> scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1209:30)
> makeResolver (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1116:16)
> Ur (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.4.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.11bce23b86ad07ade3d1.js:1:3718897)
> invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
> onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.js:28512:32)
> invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:367:51)
> run (webpack:///node_modules/zone.js/dist/zone-evergreen.js:130:42)
> zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1272:35)
> invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:402:30)
> onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:28499:32)

![image](https://user-images.githubusercontent.com/78969477/108128276-c7944180-70ac-11eb-88df-775a186d9e15.png)

Errors as shown by the console:
![image](https://user-images.githubusercontent.com/78969477/108127922-45a41880-70ac-11eb-99d0-e9a7fa14de97.png)
![image](https://user-images.githubusercontent.com/78969477/108127955-56ed2500-70ac-11eb-9d28-cb2fbccc9c4e.png)
![image](https://user-images.githubusercontent.com/78969477/108127987-640a1400-70ac-11eb-9e27-a3a705739b6e.png)

Other informations:
- First I installed the app via the GitHub exe file. Everything was ok except for this Error 400. So tried to download it from the Windows store but that didn't solve the problem.
- My pc runs on Windows 64
- Superproductivity version : 6.4.0

I hope someone will tell me what's happening... (I do have a few ideas, but I'm a total noob in programming so I had better wait for the pros...).

Thank you for your help!

**Comment by johannesjo** [comment]
Thanks for opening this up. It looks like that syncing via dropbox is somehow misconfigured. But this should never crash the application... Could you maybe share your Sync configuration (of course not with the actual credentials, but some placeholder) so I can investiagte?

**Comment by ludivn** [comment]
I'm not sure this are the informations you want me to share:

In super productivity sync settings, syncing is enabled, and I've put the authorisation code generated by Dropbox. Sync interval set by default on 1m.
In dropbox, I checked that super productivity was part of the authorized app. I've got a folder with a .json file.

That's for the basic info...

Please let me know what information precisely I should share with you, and where to seek them.

I'm planning on switching to WebDav as Dropbox may be the source of the problem. But maybye I should stay so you could fix a potential bug in the app? 

In any case, thanks you for your help!

**Comment by johannesjo** [comment]
Thanks for getting back to me! I am really not sure what is causing this and for me personally dropbox sync runs fine. So please just switch if you have the option. I would love however to try a data export (also created from the settings page) of yours with my own dropbox account. Would you maybe we willing to share one with me (I totally understand, if you don't)? If so you can send it to contact@super-productivity.com.

**Comment by johannesjo** [comment]
Hi there! With the help of your data I was able to improve the error handling for the particular problem.

If you haven't changed the sync provider and still want to use Dropbox if possible: It seems like you just forgot one step. You need click "GENERATE TOKEN" after you copied the auth code from the dropbox website. Only then the authentication will work.

Thank you very much for helping me out! Please let me know if you have any further issues!
