### ISSUE TITLE
backtick highlighting for strings in tasks and subtasks

### ISSUE THREAD

**Issue by JCurtisRMIT** [johannesjo/super-productivity#909]
just a simple FR

I find it helps to visually parse the lists in other list management software

**Comment by johannesjo** [comment]
Hi there! Could you provide a little bit more info? I am not quite sure what you mean by this.

**Comment by JCurtisRMIT** [comment]
sure thing: here is some `highlighting` using the `backtick` character

here it is on its own `

**Comment by johannesjo** [comment]
Ok thanks. If we implement this it might need to be at the cost of editing text where clicked, because of technical limitations, which I am not a big fan of. If somebody can think of a workaround for this, please let me know!
