### ISSUE TITLE
Safe and go home doesn't quit program.

### ISSUE THREAD

**Issue by jeensg** [johannesjo/super-productivity#91]
## Your Environment
* Version used: 1.10.42-489, debian-ubuntu repository
* Operating System and version: ubuntu 18.04 bionic
* Desktop Environment: xfce - xubuntu
* Browser Name and version: --

## Expected Behavior
When I finish my day, "Safe and go home" should close the programm or do something else but the thing it is doing right now.

## Current Behavior
When I finish my day, "Safe and go home" leaves a glowing sun with unicorn in the middle flashing on my screen. It's not possible to close (to tray)/quit the programm as described in the other issue before.  I do also can go on working, when I click somewhere just before the new is coming again (like 1s sun, 0,5s time click before new sun flashes). Anyway, it's possible then to go on, but closing doesn'T work. So I have to kill it and restart it, when needed. Sometimes it's also possible, that Done-Backlog is cleared :-( couldn't reproduce the missing done-backlog till right now, maybe it was also in version before...

## Steps to Reproduce (for bugs)
1. Start.
2. Add task, start it and end it.
3. Finish working, Safe and Go home, Aye Aye Shut down.

**Comment by johannesjo** [comment]
Hey there! Thank you very much for reporting! Is the console showing any errors (you can open it via `Ctrl+Shift+J`)?

**Comment by jeensg** [comment]
I had a look into console and it's not saying anything. In verbose filter there are some other errors while using other buttons (violations about responsiveness), but on clicking "Aye Aye Shut down" it's not reporting anything.

**Comment by johannesjo** [comment]
Closing this in favor of #90
