### ISSUE TITLE
add option to set start time (schedule) for a recurring (repeating) task

### ISSUE THREAD

**Issue by rafaelnp** [johannesjo/super-productivity#910]
## Problem Statement

It would be helful to be able to set a start time for a recurring  task (like a weekly meeting).
So far, it is possible to either schedule a task for one time (date and time), or to set a task to repeat (say every Tuesday).

My environment:
* Operating System: Arch Linux and Windows 10
* Super PRoductivity version: 6.4.0 (Desktop)

## :grey_question: Possible Solution

Please consider adding the option to schedule (set the start time) for a recurrent (repeat) task.

**Comment by johannesjo** [comment]
Hi there! Thanks for opening this up. This is related to #281 Maybe we can somehow find a concept that allows for both.

**Comment by rafaelnp** [comment]
@johannesjo Thanks for the quick reply.  I am not sure if the following statement from #281 means the same:

>  if Pomodoro only allows duration based reminder. It would be nice to have an alarm clock-like feature for repeated tasks.

What I suggested, can be detailed  in the following use case for a new task:
1. Title: meeting with customer X
2. When: every Monday
3. Time: at 15:00
4. Duration (optional): 1 hour

What is still missing it the ability to set the task start time. IMHO, a reminder would be showing a pop-up window X minutes before the task (in this case meeting) starts. I hope I could clarify what I meant in my original post. :-)

**Comment by johannesjo** [comment]
I am closing this in favor of: https://github.com/johannesjo/super-productivity/issues/948 (please upvote if you still like to see this).

Thank you very much for your input.
