### ISSUE TITLE
The time spent for "Today" is incorrect - Time spent on "Today" page shows accumulative time not just time for today.

### ISSUE THREAD

**Issue by mrcomptech** [johannesjo/super-productivity#915]
I'm not sure if this is an issue or if I am incorrect in the behavior I expect.

### Your Environment

* Version used: 6.4.0
* Operating System and version: Windows 10 (10.0.18363)
* Desktop Environment: n/a
* Browser Name and version: Firefox 78.7.1esr (64-bit)

### Expected Behavior
After having added tasks and/or sub tasks, and some tasks get worked on that day while others don't, at the end of the day when I click on "Finish Day" and and 'aye aye shutdown', after restarting the app the next day I expect the time spent on the tasks for today to be reset, but it still shows the total time spent on the tasks so far.

The time spent for "Today" is incorrect

### Current Behavior
After 'aye aye shutdown' and restarting the app the next day the total time spent on each task is still on the 'Today' screen.

### Steps to Reproduce (for bugs)
This happens on the second day of use and every day there after.

### Console Output
none

### Error Log (Desktop only)
n/a

**Comment by johannesjo** [comment]
Thanks for opening this up. I try to check this, once I find some time.

**Comment by mrcomptech** [comment]
I have also noticed that what may be an additional symptom.
The only way I have found to cause the "Finish Day" button to disappear and for the "Ready to Work" button to appear on the "Today" page is to click the task button that removes from "Today" icon (the sun icon with a line through it) from each task that is listed on "Today". Then after clicking the "Finish Day" button on the "Today" page and then click "Save and Go Home" and "Aye Aye! Shutdown", when the program is started up the "Today" page will display the "Ready to Work" button. But any projects that have time assigned to them (as displayed on the right side of the task) will __NOT__ show "Ready to Work" __AND__ will still show "Finish Day". Even if I clear all the time assigned to a task and close out the day w/ restarting the program that project page will still show the "Finish Day" button and not the "Ready to Work" button.

**Comment by hellgheast** [comment]
I confirm having the same issue on Mac OS (10.1.3) on Version 6.4.0

**Comment by johannesjo** [comment]
Thanks everybody. I am super busy these days as I am moving to a new flat. I get to it as soon as I can. Meanwhile PRs fixing this are welcome!

**Comment by johannesjo** [comment]
@mrcomptech this looks like another issue to me. Can please open up a new one for this?

**Comment by johannesjo** [comment]
About the original problem: The counter is intended to show the total amount of time spent on a certain day for all tasks in a list. There is no reset if you click on finish day. It's open for debate if this is the best value to display, but that's what it currently should show.

**Comment by mrcomptech** [comment]
About the original problem:

Showing " the total amount of time spent on a certain day for all tasks in a list" is not the problem, or at least that is not what I am referring to. 

I am referring to the amount of time displayed for a __single__ task performed __today__, as in the main page labeled "Today". If I spend multiple hours on multiple days a specific task __before__ today the accumulated time is be shown on the __"Today"__ page with the time spent __today__ also included in accumulated time. But there doesn't seem to be any convenient way to know how much time I spent on this specific task __today__.

It makes sense for the time spent on any one task to accumulate for reporting purposes over the course of the project. But I do not currently see any value in knowing __today__ , how much time I spent on the specific task for the past two weeks, without also knowing how much time I have spent on the task to day.

A huge part of time tracking is time management. If I have to be away from the office for 4 out of 10 hours today and I still have several different tasks to perform today at the office, it is much easier to prioritize tasks by knowing how much time to spend on the specific tasks to be performed today. After spending 4 hours on one task I may need to spend my remaining time on other tasks that must be worked on today.  If I can quickly and easily see how much time I spend on a specific task so far today then I am better able to manage today's time in the office. 

I am going to uninstall SP and remove all SP data and then reinstall SP and try again to see if I am misreading the information or if my understanding is in error and after a few days I will update this ticket.

I apologize if the use of the double underscores is annoying, that is not my intent. Their use is only intended to emphasize the distinction between daily time and accumulated time.

I am retraining myself to become a full-stack developer and have installed GitHub Desktop and downloaded SP workspace. I have been studying your code but unfortunately my programming understanding is currently very limited. But, I do hope to learn from your work as well as am hopeful I will be able to contribute to your project.

**Comment by johannesjo** [comment]
Thanks for your patience and the explanation! I think understand the problem now!  

The point of reference for this is estimate vs. time spent for any given task. Tasks are estimated in total so for the "1h/2h" it would be confusing to display "15m/2h" one day and "45m/2h" the next day. This way of writing things allows for effective time boxing and other features such as the warning about exceeding estimates are linked to this as well. 

This being said, I understand your point, but rather than a bug I would consider this as a possible enhancement for which we need a new concept, ideally one that doesn't break/inhibit the usefulness of how things are done now. This could be a global setting switch, or some kind of context switch, some additional info to show on hover or something completely different. 

My personal workaround for this, if I ever encounter this to be a problem, which doesn't happen often, is to create a version 2 of a task for another day. So one day I might work on "Refactoring 1" and the next day I create a task "Refactoring 2". I admit that this doesn't look like the ideal solution for this. 

If you got some ideas on how to better deal with the problem, please let me know!!

**Comment by mrcomptech** [comment]
This is not about estimated time vs actual time spent.
Yesterday I removed and reinstalled SP,  added projects and tasks.
I assigned no time estimates to any task or project.
I clicked "Ready to Work" and recorded time.
At the end of the day I clicked "Finish Day".
Today, before tracking any time, the time displayed on the "Today" page is the time I spent yesterday and all time estimates are marked as a minus sign ( - ). So today one of the time displays for a task is "5h 51m / - ".

What time should I expect to see on the tasks for today?
I am expecting that the only time I should see on the "Today" page is time I spend on the task for today.

Also, I checked the Chrom console log and found these errors:

DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.4.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/styles.7ed065e4b08df49f6d6d.css.map: 

DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.4.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/lz.4032bbfae8ed49675219.worker.js.map: 

DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.4.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/reminder.ce132bbfd6c00fa9679e.worker.js.map: 

DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.4.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/runtime.f8acce36d38b4573bc3e.js.map: 

DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.4.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js.map: 

DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.4.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.11bce23b86ad07ade3d1.js.map:

**Comment by mrcomptech** [comment]
I tried logging in to my desktop PC as an administrator but would have to perform an additional installation since the app was not found using the search feature of the start menu.

**Comment by mrcomptech** [comment]
It would seem that, other than the errors in the console log which didn't seem to be effecting performance, the problem was my assumption of how such a program should  work. In __my limited view__ how much time I spend on specific tasks __today__ is more important than how much time I spent on these tasks over weeks or months.

It is just my opinion that time show on the "Today" page should show time spent __today__ and not accumulated time. That is not intuitive, __from my point of view__. I can see daily time in the work log as well as accumulated time. I would prefer being able to quickly and easily see how much time I am spending on a task __today__ on the "Today" page as I believe this makes prioritizing today's work more manageable and from a UXP perspective is more intuitive. 

Maybe this is something that could be changed/set in the settings by the user, so a feature request perhaps ?

In working with a development version that is v6.5 while the production version is 6.5, it occurred to me that what was happening before, that being the time displayed being accumulated time vs time spent today stemmed from how I was previously using SP. At first I assumed tasks that tasks which were going to be performed on a daily or weekly manner would be repeating tasks. Which is how I have normally worked over the past 30 years. 

But now I'm thinking that because, at first, I was using repeating tasks it wasn't clear, intuitive, to me that doing so would automatically generate another item on the Today page when I selected it for work "Today". And that I would have to manually archive that specific task after the end of the day. The tasks in the project were growing with each day the task was repeated.

So it would seem that my "issue" was really a matter of preference.

Thanks for being so patient with me. :)

**Comment by johannesjo** [comment]
@mrcomptech thank you very much for your input! It's always valuable to get an inside in how different people approach the app and definitely not everything is communicated as clearly as it should be, and there is a lot of room for improvements. :)

I also agree with you that it might be nice to make this configurable, though I probably won't find the time to work on this myself.
