### ISSUE TITLE
electron needs package xprintidle

### ISSUE THREAD

**Issue by jeensg** [johannesjo/super-productivity#92]
## Your Environment
* Version used: 1.10.42-489, debian-ubuntu repository
* Operating System and version: ubuntu 18.04 bionic
* Desktop Environment: xfce - xubuntu

## Expected Behavior
If installing and starting, there is no error.
If possible, include package xprintidle in dependencies.

## Current Behavior
When I install the programm and start it, electron throws an error: "Missing ...., need to install xprintidle". After installing, error is gone.

## Steps to Reproduce (for bugs)
1. Install from Repo.
2. Start.
3. sudo apt install xprintidle
4. works.

**Comment by johannesjo** [comment]
This should be fixed now. Thanks for reporting!
