### ISSUE TITLE
Idle timeout gets triggered when working with keyboard only in vim

### ISSUE THREAD

**Issue by ssalenik** [johannesjo/super-productivity#922]
### Your Environment

* Version used: 6.4.0 snap
* Operating System and version: Ubuntu 20.10
* Desktop Environment: Gnome

### Expected Behavior
No idle dialog when working with keyboard only in vim in terminal

### Current Behavior
Working in vim in terminal, I get the idle dialog

### Steps to Reproduce (for bugs)

1. Open up terminal
2. Open vim, start typing and don't use the mouse
3. You have been idle dialog pops up after 5 mins of step 2

**Comment by johannesjo** [comment]
Thank you very much for opening this up! The best place to address this is probably the main [electron repository](https://github.com/electron/electron) as this this is most likely a problem with `powerMonitor.getSystemIdleTime()`.

**Comment by ssalenik** [comment]
Filed an electron bug... in the meantime maybe it would be possible to replace the native API with something like: https://github.com/bithavoc/node-desktop-idle

I could give it a try...

**Comment by ssalenik** [comment]
Hum, I tried using `desktop-idle`, but I get the same result:
https://github.com/ssalenik/super-productivity/commit/991654280d23722a1dcdbe38e23ace51bef092d8

I wonder if the bug is a change in behaviour / bug in how the idle time is calculated on the system in this case...

**Comment by ssalenik** [comment]
Oh, I just remembered I'm using Wayland. `desktop-idle` uses the `idle` count given by `XScreenSaver`... I wonder if it just doesn't work like it should in Wayland...

**Comment by johannesjo** [comment]
Thank you very much @ssalenik . I would suspect that this might be very well the case. It's also not the first problem I encountered with Wayland. I got very frustrated when I tried to make  [lwsm](https://github.com/johannesjo/linux-window-session-manager) work with it :)
