### ISSUE TITLE
Syncing conflict

### ISSUE THREAD

**Issue by dodalovic** [johannesjo/super-productivity#927]
Pop OS Linux 20.10

Latest Super-productivity

Wasn't touching my Google drive backed file, but got the following:

![image](https://user-images.githubusercontent.com/6358061/108986691-b3df7100-7692-11eb-90f4-8eb6f1e88745.png)

Not sure 🤔

**Comment by johannesjo** [comment]
Thanks for reporting this. If this just happened once It's possible that for some reason the data got synced, but that the app didn't get the info (due to a failing response maybe??). Not sure.. We should keep an eye out! If this happens more often than there is very likely something amiss.

**Comment by wilbowma** [comment]
I'm getting this issue a bunch, although my Last Sync time appears to be a default value (looks like a 0-value timestamp).

Seems to be accompanied by the following error:
```
web-dav-sync.service.ts:100 TypeError: Cannot read property 'etag' of undefined
    at WebDavSyncService.<anonymous> (main.js:31836)
    at Generator.next (<anonymous>)
    at fulfilled (main.js:31747)
    at ZoneDelegate.invoke (polyfills.js:475)
    at Object.onInvoke (vendor.js:55346)
    at ZoneDelegate.invoke (polyfills.js:474)
    at Zone.run (polyfills.js:237)
    at polyfills.js:1379
    at ZoneDelegate.invokeTask (polyfills.js:509)
    at Object.onInvokeTask (vendor.js:55333)
```

**Comment by johannesjo** [comment]
This can be closed, right?

**Comment by wilbowma** [comment]
I think it was fixed by https://github.com/johannesjo/super-productivity/pull/1200

**Comment by johannesjo** [comment]
Thank you!
