### ISSUE TITLE
Done-Tasks-Backlog is cleared on switching projects

### ISSUE THREAD

**Issue by jeensg** [johannesjo/super-productivity#93]
## Your Environment
* Version used: 1.10.42-489, debian-ubuntu repository
* Operating System and version: ubuntu 18.04 bionic
* Desktop Environment: xfce - xubuntu

## Expected Behavior
Done-Backlog isn't cleared, only when done by user.

## Current Behavior
When I change projects, done-backlog is cleared for other project.

## Steps to Reproduce (for bugs)
1. create task in one project
2. start working and finish task (done)
3. Finish Working (clear done tasks and move to Done-Backlog), Save and go home (just clear the tasks)
4. Go to done-backlog --> done task is there
5. change project (will be in done-Backlog too)
6. go back to first project (will be in done-backlog also) --> Done-Tasks-Backlog is empty

**Comment by johannesjo** [comment]
Hey thanks for reporting! Just came back from vacation. Will check all this, as soon as I can.

**Comment by johannesjo** [comment]
Oh that's bad. I can confirm that this is an issue. I will work on a fix asap.

**Comment by jeensg** [comment]
Installed version 1.10.45-497 and confirm that Done-Task-Backlog stays alive :-) Thanks!

**Comment by johannesjo** [comment]
Thanks for checking! :)
