### ISSUE TITLE
Reddit post in the README got deleted

### ISSUE THREAD

**Issue by D4N** [johannesjo/super-productivity#933]
This is more of a FYI, that the [reddit post](https://www.reddit.com/r/selfhosted/comments/by7bcu/super_productivity_is_an_open_source_todo_list/?ref=readnext) linked in the README got deleted (and the user that submitted it no longer exists). Not sure if you want to remove it or keep it around? Thus feel free to close this at your convenience.

**Comment by johannesjo** [comment]
Thank you! I'll remove it!

**Comment by D4N** [comment]
Thanks!
