### ISSUE TITLE
Can't enter the Cyrillic symbol "б" in the tag name

### ISSUE THREAD

**Issue by justausernamenothingspecial** [johannesjo/super-productivity#934]
### Your Environment
* Version used: 6.3.3
* Operating System and version: Windows 10 v.1903

### Expected Behavior
You can add a tag name that contains Cyrillic symbol "б" (unicode 4031), for example the word "Обучение".

### Current Behavior
If you try to enter a small character "б" in the tag name, it just closing this tag. For example if you input tag name "Обучение" it just adds tag "О" on pressing "б" key.

### Steps to Reproduce (for bugs)
1. Add any task.
2. Right click on the created task and select "Edit Tags".
3. Try to add any word containing the Cyrillic character "б".

### Error Log (Desktop only)
There is no "superProductivity" subfolder in my \AppData\Roaming\ folder.

### Additional Information
If I write word with this symbol in another app and then copy-paste it to the tag name field it adds without any difficulties, so problem appears only for keyboard input of this symbol. Also, problem appears only on a tag name, if you use symbol in task or project name it enters without any difficulties too.

P.S. It's not a critical bug, I just noticed it when adding my tasks and I decided to report it.

**Comment by johannesjo** [comment]
Thank you very much for opening this up! PRs would be welcome on this! :)
