### ISSUE TITLE
add possibility to select project when creating a new task

### ISSUE THREAD

**Issue by raot** [johannesjo/super-productivity#935]
## Problem Statement
I work a lot on different projects. So when I create a new task, currently the task gets assigned to my default project (which is "no project") and then it goes to the top of my list (which usually today). Then, the task is hidden because the add new task still displays, which confused me at the beginning since I thouhgt there were no task created. Then I click to close the add new task dialog, right-click on the new task to assign the correct task. All of this could have been done in one step, which I'd appreciate a lot.

## :grey_question: Possible Solution
Show the project in the add new task dialog (default project is selected), so one can change the selection to another project before saving the new task.

**Comment by johannesjo** [comment]
Hi there! Thanks for opening this up! 
> the new task to assign the correct task

project?

You can do this much more quickly by using the short syntax. If you have project called "fun" you can do this:
```
Some task +f
```
and the app will create a task called "Some task" and assign it to the project "fun".

**Comment by raot** [comment]
great, works fine! thank you.
