### ISSUE TITLE
"Did you forgot to close off your day?"

### ISSUE THREAD

**Issue by stephencork** [johannesjo/super-productivity#936]
Really enjoying the program on my Mac for my daily workflow. I have a suggestion for improvement that could fix a possible bug. There are a lot of open issues and I could not see one that discusses this. 

## Problem Statement
I often forget to close down the app at the end of the day. I start the next morning and am presented with "you have been away for 9hrs" etc. I can click skip or break or task but it does not seem to register as it will pop back up in 5 minutes saying that I have still been away for that length of time. It is also not clear if there are issues with time tracking if I was not to close off at the end of my day. 

## :grey_question: Possible Solution
Maybe would be good to have a point in time eg 8 am where timers stop and a new day is declared? maybe a popup that says did you forget to log off yesterday? The idle timer is not generally visible until it pops up. maybe have a way to see the idle timer(s) and adjust its values or reset.   

## :arrow_heading_up: Describe alternatives you've considered
I generally have found quitting the program will kill the timers and allow me to start a new day. 

## :heavy_plus_sign: Additional context
There have been a couple of times where there seem to be 2 or more timers going tracking my time away.

**Comment by johannesjo** [comment]
Hey there! Thanks for opening this up. I have to think about this. The proposed solution with resetting them might cause issues for people working/ being idle in exactly that time frame. Making the idle time visible might be an option though I have to say that I personally would find it a bit unnerving to be always aware of that :D
