### ISSUE TITLE
Nextcloud app as data endpoint with group and project based time tracking and sharing

### ISSUE THREAD

**Issue by menelic** [johannesjo/super-productivity#938]
## Problem Statement

Nextcloud can be used to sync Super Productivity data (here is hoping for #914 - would it be possible to sponsor the implementation of such specific issues that could serve as building blocks towards the main feature request I am submitting here?), but would also be great as data endpoint  - this could also enable project and group based time tracking of several contributors/employers/group members. There is a rudimentary NC app with an API:

https://github.com/te-online/timemanager/issues/8

A mobile app is in development - maybe this also provides an interesting solution for "submitting" client side data: 

https://gitlab.com/joleaf/nc-timemanager-mobile-app

**Comment by johannesjo** [comment]
Thanks for opening this up! I'll investigate ;)
