### ISSUE TITLE
Break Reminder coming up tho break was never left

### ISSUE THREAD

**Issue by Nightreaver** [johannesjo/super-productivity#939]
### Your Environment
* Version used: Microsoft Store Version 6.4.0
* Operating System and version: Windows 10

### Expected Behavior
While I am still on the break that I didn't cancel - the reminder should not come up as I am still having the break.

### Current Behavior
I started my task and and after 25 min the pomodoro timer came up. I left for long break and the window is still open.
![image](https://user-images.githubusercontent.com/3270156/109705846-96069480-7bdb-11eb-960d-fbe6dcb0fd49.png)
To my expectation, I am currently having a break - still - but the Break reminder keeps coming up with "Take a break, you re working for 4h straight"

![image](https://user-images.githubusercontent.com/3270156/109706549-6f952900-7bdc-11eb-93ed-f6d873d22f0e.png)

### Steps to Reproduce (for bugs)

1. start working on a task an enable pomodoro timer
2. wait for the break pop and let the break time run out
3. wait further and do not click "close" or "back to work!" 
4. see the popup coming up after some time (as i wasn't on my desk idk how long it takes for the first reminder to come up)

**Comment by johannesjo** [comment]
Hey there! Thanks for opening this up! Makes a lot of sense to make the two features work better together. It's a bit tricky and I am pretty swarmed with other issues, but I gladly review any PR dealing with this.

**Comment by johannesjo** [comment]
Hey there! I implemented a simple solution, that resets the break timer any time a pomodoro session or break is started. This is a bit simplified and ignores break skipping, but the features don't make too much sense in combination anyway imho.

**Comment by rommeswi** [comment]
Perhaps the break reminder should also be disabled while the break popup "Countdown + Come back in 5 minutes" is open. I find the break reminder useful if one overextends a pomodoro session.
