### ISSUE TITLE
Jira issue XXX is assigned to another user

### ISSUE THREAD

**Issue by Jc-L** [johannesjo/super-productivity#94]
When the user used for the JIRA connection is different from the assignee in the JQL query, you have incorrect messages "Jira issue XXX is assigned to another user" popping up.

I use this setup because we use strong authentication on JIRA, except for some web-services login. So a web-service login does the request for my login.

**Comment by johannesjo** [comment]
Hey there! Thanks for reporting. I made the assignee name to check configurable, so you can use another name than the login user.

**Comment by Jc-L** [comment]
:+1: 4 hours from bug report to commit... It is even better than coding by myself ! Thanks for such an efficiency. And if you intend to code other stuff for productivity, I have some ideas ;-) (like a generic Zotero-like for storing document and notes-taking app, allowing for generic doc properties).

Thanks again for this great piece of software !
