### ISSUE TITLE
Repeat once ~ days/ weeks Feature

### ISSUE THREAD

**Issue by tiberiuiurco** [johannesjo/super-productivity#943]
Hello.
Personally I am using another Time Tracking Service even though Super Productivity has a nice and minimalistic view.
Why do I do that? 
Well, I would love to use Super Productivity, but the lack of the Repeat features would actually make my productivity lower. I have daily tasks that come once in 2 weeks in a certain day and I am really dependant on this.

Could you, please, work on the Task Repeating System so that you can repeat tasks once ~ days/ weeks? 
And also a good idea would be to make tasks start in a day and end in another day ( selected by the user ). 

Thank you!

**Comment by menelic** [comment]
There already is a repeat functionality:
![image](https://user-images.githubusercontent.com/5934115/110120802-ce65c880-7dbd-11eb-90d8-0df17fe8fd90.png)

**Comment by tiberiuiurco** [comment]
> There already is a repeat functionality - and this issue discusses how to improve it #187
> ![image](https://user-images.githubusercontent.com/5934115/110120922-f9e8b300-7dbd-11eb-923c-8d3ce6472348.png)

Please, read my post carefully. I said that I would like a feature that can make my tasks repeat once ~ weeks. ( improvement of Repeat System )
In my uni schedule, some courses take place in a day once 2 weeks. Also I have work projects tasks that should be done as above. 
I would really love to see this implemented. 

Thank you for your reply!

**Comment by johannesjo** [comment]
Thanks for opening this up (and thanks @menelic for chipping in with an answer! I am spending a loooot of time answering github issues these days and help is much appreciated).

I am sure there already is an issue open for this somewhere. I agree that we should allow for more complex options when it comes to repeating tasks, though I can't make any promises when I will get to improve this.

**Comment by menelic** [comment]
I added the reference to the open issue #187  where further improvements to the repeat functionality are actively discussed. The idea was to redirect the discussion there to make it more productive by having all ideas gathered in one place and avoiding duplicate debate. @tiberiuiurco kindly check the issue, you will see what I mean.

**Comment by johannesjo** [comment]
Thanks @menelic ! I am closing this in favor of #187.
