### ISSUE TITLE
Ex- and Import Projects and Tasks as Templates (without time tracking data)

### ISSUE THREAD

**Issue by menelic** [johannesjo/super-productivity#946]
## Problem Statement
To make Super Productivity more readily usable in teams, it would be great if projects and tasks could be ex- and imported as templates, that is without the time data. This way, it would be possible for one team member to create a project specific template and have all other team members import it instead of every one having to recreate the structure for themselves. The unified projects and tasks would ease the collation of time spent on projects by all team members.

This would also be a milestone on the way to #938 .

Even a simple implementation that works only when Super Productivity is first set up (because it overrides all SP data) would already be helpful. Of course it would be ideal if such template import were possible in such a way that new projects and tasks were added o existing ones, preserving existing time trackking data.

For our specific use case, publishing a version of Super Productivity that implements  #626 would be a viable altervative - especially if this woudl enable importation of tasks and sub-tasks as well as projects via carddav.

**Comment by johannesjo** [comment]
Thanks for opening this up! Could you maybe give an example of what kind of data you'd like to share between users? In it's current form Super Productivity never handles anything interpersonal itself directly, but leaves this task to various issue providers. As this would be a new concept, I am wondering if there might be a better way handle this problem.

This being said, I have no problems with adding an option to export projects without time tracking data as part of re-introducing project archiving: #906 #450 #331.

**Comment by menelic** [comment]
Thanks for the quick follow-up! Let me sketch a scenario that will hopefully illustrate the use case: A team is embarking on two new projects - they want to use Super Productivity for project-specific time tracking. To easily onboard every team member, the project lead creates the projects with a set of tasks and sub-tasks in SP and exports them without any time tracking data (so that for example the time she has logged in the task "SP on-boarding" is not exported and not imported in team members' SP instances). Team members who have previously worked with SP do not loose their prior data, the new projects and tasks are just added and ready to use. IMHO, implementing this would require the following spec:

* a project/task/sub-task template format for SP
  - ability to export projects/tasks/sub-tasks as templates ie without time tracking data
  - ability to import these templates without overriding pee-existing SP data
 
This would also be a necessary milestone feature and  building block towards  a dash where time tracking of several team members can be collated on a per-project basis ( #925 or with Nextcloud as data endpint #938) because collation is not feasible if team members name the same task differently because they have to set it um in SP individually.

**Comment by johannesjo** [comment]
Thanks for your reply! While I still have no problem with implementing this, this would imho not help with the progression of 938.

Ideally I'd like to stick with the pattern that everything team based is not handled by Super Productivity as it works more as task management client. Changing that would raise a lot of conceptual problems starting with the problem that clients would need to start talking to each other, which apart from fancy, complicated and data intensive p2p stuff would always require a server anyway. Thus everything team based needs to be handled by some sort of task provider such as, the  CalDAV integration or Jira or maybe a custom provider specifically written to suit your needs. 

A limitation to that approach would be that sub tasks can currently never be issue tasks (connected to some sort of task provider). It's possible to change that, but complicated (technically and again also conceptually) so if not essential, I would not put this on the road map to a MVP.

**Comment by menelic** [comment]
Thanks - I do understand the skepticism regarding needless complexity. But in this case I d say the request can be implemented in a far simpler way: There is absolutely no need for fancy p2p connectivity or many-to-many communication to ensure template ex-and import can work for the above use case. None of the steps in the above use-case need to be automated or rely on SP clients syncing among themselves. It sufficient if the ex- and import is done manually or via a one-to-many communication relay such as the CalDAV, where again there is no need to submit new tasks back to the CalDAv provider via SP.

No sub tasks via CalDAV is fine as long as there is a way to ex- and import them as templetes in some way - though of course it would be great if it would be possible at some point to create tasks and subtasks in CalDAV (eg Deck) and have SP ingest them as such.

**Comment by johannesjo** [comment]
Ah alright! Sorry for the misunderstanding! I was thrown off a bit  because you considered this to be a step on the road to 938. 

I am working on a concept on how to get there. I'll give you an update once I get there.
