### ISSUE TITLE
Error: Uncaught (in promise): UnknownError: Connection is closing.

### ISSUE THREAD

**Issue by viktor-strukov** [johannesjo/super-productivity#951]
### Steps to Reproduce

1. Having opened for the first time.
2. Got a lot of stuff opened on Ubuntu 20.04, up to freezing screen.
3. Closing apps one by one (Super productivity closed by Alt+F4 normally, vscode's subprocesses ended from System Monitor)
4. Reopened some apps like Firefox Browser
5. Tried to reopen Super productivity, pressed "start" for one of the existing tasks and got this error.

Thank you for the app!

### Console Output

[Persistence] Save to DB Object Object
main.a276ef2d735aa2fdb6d1.js:1 [Task] Add time spent Object Object
main.a276ef2d735aa2fdb6d1.js:1 [Project] Update Work End Object Object
main.a276ef2d735aa2fdb6d1.js:1 [Tag] Update Work End for Tag Object Object
main.a276ef2d735aa2fdb6d1.js:1 [Persistence] Save to DB Object Object
main.a276ef2d735aa2fdb6d1.js:1 [Persistence] Save to DB Object Object
main.a276ef2d735aa2fdb6d1.js:1 [Persistence] Save to DB Object Object
main.a276ef2d735aa2fdb6d1.js:1 [Task] Add time spent Object Object
main.a276ef2d735aa2fdb6d1.js:1 [Project] Update Work End Object Object
main.a276ef2d735aa2fdb6d1.js:1 [Tag] Update Work End for Tag Object Object
main.a276ef2d735aa2fdb6d1.js:1 [Persistence] Save to DB Object Object
main.a276ef2d735aa2fdb6d1.js:1 [Persistence] Save to DB Object Object
main.a276ef2d735aa2fdb6d1.js:1 [Persistence] Save to DB Object Object
main.a276ef2d735aa2fdb6d1.js:1 [Task] Add time spent Object Object
main.a276ef2d735aa2fdb6d1.js:1 [Project] Update Work End Object Object
main.a276ef2d735aa2fdb6d1.js:1 [Tag] Update Work End for Tag Object Object
main.a276ef2d735aa2fdb6d1.js:1 [Persistence] Save to DB Object Object
main.a276ef2d735aa2fdb6d1.js:1 [Persistence] Save to DB Object Object
main.a276ef2d735aa2fdb6d1.js:1 [Persistence] Save to DB Object Object
main.a276ef2d735aa2fdb6d1.js:1 GLOBAL_ERROR_HANDLER Error: Uncaught (in promise): UnknownError: Connection is closing.
    at Z (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at polyfills.bbc1c0564b6a5d42ba73.js:1
    at IDBTransaction.s (main.a276ef2d735aa2fdb6d1.js:1)
    at l.invokeTask (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at Object.onInvokeTask (main.a276ef2d735aa2fdb6d1.js:1)
    at l.invokeTask (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at i.runTask (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at u.invokeTask [as invoke] (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at _ (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at IDBTransaction.k (polyfills.bbc1c0564b6a5d42ba73.js:1)
handleError @ main.a276ef2d735aa2fdb6d1.js:1
main.a276ef2d735aa2fdb6d1.js:1 Last actions before error: Array(30)
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/1030/resources/app.asar/dist/runtime.f8acce36d38b4573bc3e.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/1030/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/1030/resources/app.asar/dist/main.a276ef2d735aa2fdb6d1.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/1030/resources/app.asar/dist/reminder.ce132bbfd6c00fa9679e.worker.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/1030/resources/app.asar/dist/lz.4032bbfae8ed49675219.worker.js.map: 
main.a276ef2d735aa2fdb6d1.js:1 [Task] Add time spent {task: {…}, date: "2021-03-06", duration: 10933} {ids: Array(21), entities: {…}, currentTaskId: "amrMDdocL", selectedTaskId: null, taskAdditionalInfoTargetPanel: null, …}
main.a276ef2d735aa2fdb6d1.js:1 [Project] Update Work End {id: "xD8YxOI4a", date: "2021-03-06", newVal: 1615043451964} {ids: Array(21), entities: {…}, currentTaskId: "amrMDdocL", selectedTaskId: null, taskAdditionalInfoTargetPanel: null, …}
main.a276ef2d735aa2fdb6d1.js:1 [Tag] Update Work End for Tag {id: "TODAY", date: "2021-03-06", newVal: 1615043451964, type: "[Tag] Update Work End for Tag"} {ids: Array(21), entities: {…}, currentTaskId: "amrMDdocL", selectedTaskId: null, taskAdditionalInfoTargetPanel: null, …}
main.a276ef2d735aa2fdb6d1.js:1 [Persistence] Save to DB {dbKey: "task", data: {…}, type: "[Persistence] Save to DB"} {ids: Array(21), entities: {…}, currentTaskId: "amrMDdocL", selectedTaskId: null, taskAdditionalInfoTargetPanel: null, …}
main.a276ef2d735aa2fdb6d1.js:1 [Persistence] Save to DB {dbKey: "project", data: {…}, type: "[Persistence] Save to DB"} {ids: Array(21), entities: {…}, currentTaskId: "amrMDdocL", selectedTaskId: null, taskAdditionalInfoTargetPanel: null, …}
main.a276ef2d735aa2fdb6d1.js:1 [Persistence] Save to DB {dbKey: "tag", data: {…}, type: "[Persistence] Save to DB"} {ids: Array(21), entities: {…}, currentTaskId: "amrMDdocL", selectedTaskId: null, taskAdditionalInfoTargetPanel: null, …}
polyfills.bbc1c0564b6a5d42ba73.js:1 Uncaught Error: Error: Uncaught (in promise): UnknownError: Connection is closing.
    at e.handleError (main.a276ef2d735aa2fdb6d1.js:1)
    at Object.next (main.a276ef2d735aa2fdb6d1.js:1)
    at d.i [as _next] (main.a276ef2d735aa2fdb6d1.js:1)
    at d.__tryOrUnsub (main.a276ef2d735aa2fdb6d1.js:1)
    at d.next (main.a276ef2d735aa2fdb6d1.js:1)
    at l._next (main.a276ef2d735aa2fdb6d1.js:1)
    at l.next (main.a276ef2d735aa2fdb6d1.js:1)
    at Fh.next (main.a276ef2d735aa2fdb6d1.js:1)
    at Fh.emit (main.a276ef2d735aa2fdb6d1.js:1)
    at main.a276ef2d735aa2fdb6d1.js:1
runTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
invokeTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
invoke @ polyfills.bbc1c0564b6a5d42ba73.js:1
n.args.<computed> @ polyfills.bbc1c0564b6a5d42ba73.js:1
main.a276ef2d735aa2fdb6d1.js:1 [Task] Add time spent {task: {…}, date: "2021-03-06", duration: 328} {ids: Array(21), entities: {…}, currentTaskId: "amrMDdocL", selectedTaskId: null, taskAdditionalInfoTargetPanel: null, …}
main.a276ef2d735aa2fdb6d1.js:1 [Project] Update Work End {id: "xD8YxOI4a", date: "2021-03-06", newVal: 1615043452292} {ids: Array(21), entities: {…}, currentTaskId: "amrMDdocL", selectedTaskId: null, taskAdditionalInfoTargetPanel: null, …}
main.a276ef2d735aa2fdb6d1.js:1 [Tag] Update Work End for Tag {id: "TODAY", date: "2021-03-06", newVal: 1615043452292, type: "[Tag] Update Work End for Tag"} {ids: Array(21), entities: {…}, currentTaskId: "amrMDdocL", selectedTaskId: null, taskAdditionalInfoTargetPanel: null, …}
main.a276ef2d735aa2fdb6d1.js:1 [Persistence] Save to DB {dbKey: "task", data: {…}, type: "[Persistence] Save to DB"} {ids: Array(21), entities: {…}, currentTaskId: "amrMDdocL", selectedTaskId: null, taskAdditionalInfoTargetPanel: null, …}
main.a276ef2d735aa2fdb6d1.js:1 [Persistence] Save to DB {dbKey: "project", data: {…}, type: "[Persistence] Save to DB"} {ids: Array(21), entities: {…}, currentTaskId: "amrMDdocL", selectedTaskId: null, taskAdditionalInfoTargetPanel: null, …}
main.a276ef2d735aa2fdb6d1.js:1 [Persistence] Save to DB {dbKey: "tag", data: {…}, type: "[Persistence] Save to DB"} {ids: Array(21), entities: {…}, currentTaskId: "amrMDdocL", selectedTaskId: null, taskAdditionalInfoTargetPanel: null, …}
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/1030/resources/app.asar/dist/styles.17459155b437e272b9db.css.map: 
main.a276ef2d735aa2fdb6d1.js:1 GLOBAL_ERROR_HANDLER DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at Proxy.n (file:///snap/superproductivity/1030/resources/app.asar/dist/main.a276ef2d735aa2fdb6d1.js:1:2396084)
    at Proxy.s (file:///snap/superproductivity/1030/resources/app.asar/dist/main.a276ef2d735aa2fdb6d1.js:1:2397166)
    at e.<anonymous> (file:///snap/superproductivity/1030/resources/app.asar/dist/main.a276ef2d735aa2fdb6d1.js:1:2405512)
    at Generator.next (<anonymous>)
    at a (file:///snap/superproductivity/1030/resources/app.asar/dist/main.a276ef2d735aa2fdb6d1.js:1:2404850)
    at l.invoke (file:///snap/superproductivity/1030/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6572)
    at Object.onInvoke (file:///snap/superproductivity/1030/resources/app.asar/dist/main.a276ef2d735aa2fdb6d1.js:1:1603753)
    at l.invoke (file:///snap/superproductivity/1030/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6512)
    at i.run (file:///snap/superproductivity/1030/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:1984)
    at file:///snap/superproductivity/1030/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:16758
handleError @ main.a276ef2d735aa2fdb6d1.js:1
(anonymous) @ main.a276ef2d735aa2fdb6d1.js:1
error @ main.a276ef2d735aa2fdb6d1.js:1
notifyError @ main.a276ef2d735aa2fdb6d1.js:1
_error @ main.a276ef2d735aa2fdb6d1.js:1
error @ main.a276ef2d735aa2fdb6d1.js:1
notifyError @ main.a276ef2d735aa2fdb6d1.js:1
_error @ main.a276ef2d735aa2fdb6d1.js:1
error @ main.a276ef2d735aa2fdb6d1.js:1
(anonymous) @ main.a276ef2d735aa2fdb6d1.js:1
invoke @ polyfills.bbc1c0564b6a5d42ba73.js:1
onInvoke @ main.a276ef2d735aa2fdb6d1.js:1
invoke @ polyfills.bbc1c0564b6a5d42ba73.js:1
run @ polyfills.bbc1c0564b6a5d42ba73.js:1
(anonymous) @ polyfills.bbc1c0564b6a5d42ba73.js:1
invokeTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
onInvokeTask @ main.a276ef2d735aa2fdb6d1.js:1
invokeTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
runTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
m @ polyfills.bbc1c0564b6a5d42ba73.js:1
Promise.then (async)
k @ polyfills.bbc1c0564b6a5d42ba73.js:1
scheduleTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
onScheduleTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
scheduleTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
scheduleTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
scheduleMicroTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
P @ polyfills.bbc1c0564b6a5d42ba73.js:1
Z @ polyfills.bbc1c0564b6a5d42ba73.js:1
(anonymous) @ polyfills.bbc1c0564b6a5d42ba73.js:1
Promise.then (async)
(anonymous) @ polyfills.bbc1c0564b6a5d42ba73.js:1
C @ polyfills.bbc1c0564b6a5d42ba73.js:1
R.e.then @ polyfills.bbc1c0564b6a5d42ba73.js:1
Z @ polyfills.bbc1c0564b6a5d42ba73.js:1
(anonymous) @ polyfills.bbc1c0564b6a5d42ba73.js:1
(anonymous) @ main.a276ef2d735aa2fdb6d1.js:1
C @ polyfills.bbc1c0564b6a5d42ba73.js:1
c @ main.a276ef2d735aa2fdb6d1.js:1
a @ main.a276ef2d735aa2fdb6d1.js:1
invoke @ polyfills.bbc1c0564b6a5d42ba73.js:1
onInvoke @ main.a276ef2d735aa2fdb6d1.js:1
invoke @ polyfills.bbc1c0564b6a5d42ba73.js:1
run @ polyfills.bbc1c0564b6a5d42ba73.js:1
(anonymous) @ polyfills.bbc1c0564b6a5d42ba73.js:1
invokeTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
onInvokeTask @ main.a276ef2d735aa2fdb6d1.js:1
invokeTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
runTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
m @ polyfills.bbc1c0564b6a5d42ba73.js:1
invokeTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
invoke @ polyfills.bbc1c0564b6a5d42ba73.js:1
n.args.<computed> @ polyfills.bbc1c0564b6a5d42ba73.js:1
setTimeout (async)
i @ polyfills.bbc1c0564b6a5d42ba73.js:1
scheduleTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
onScheduleTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
scheduleTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
scheduleTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
scheduleMacroTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
d @ polyfills.bbc1c0564b6a5d42ba73.js:1
(anonymous) @ polyfills.bbc1c0564b6a5d42ba73.js:1
s.<computed> @ polyfills.bbc1c0564b6a5d42ba73.js:1
(anonymous) @ main.a276ef2d735aa2fdb6d1.js:1
C @ polyfills.bbc1c0564b6a5d42ba73.js:1
(anonymous) @ main.a276ef2d735aa2fdb6d1.js:1
(anonymous) @ main.a276ef2d735aa2fdb6d1.js:1
(anonymous) @ main.a276ef2d735aa2fdb6d1.js:1
i @ main.a276ef2d735aa2fdb6d1.js:1
invoke @ polyfills.bbc1c0564b6a5d42ba73.js:1
onInvoke @ main.a276ef2d735aa2fdb6d1.js:1
invoke @ polyfills.bbc1c0564b6a5d42ba73.js:1
run @ polyfills.bbc1c0564b6a5d42ba73.js:1
(anonymous) @ polyfills.bbc1c0564b6a5d42ba73.js:1
invokeTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
onInvokeTask @ main.a276ef2d735aa2fdb6d1.js:1
invokeTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
runTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
m @ polyfills.bbc1c0564b6a5d42ba73.js:1
Promise.then (async)
k @ polyfills.bbc1c0564b6a5d42ba73.js:1
scheduleTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
onScheduleTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
scheduleTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
scheduleTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
scheduleMicroTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
P @ polyfills.bbc1c0564b6a5d42ba73.js:1
Z @ polyfills.bbc1c0564b6a5d42ba73.js:1
(anonymous) @ polyfills.bbc1c0564b6a5d42ba73.js:1
Promise.then (async)
(anonymous) @ polyfills.bbc1c0564b6a5d42ba73.js:1
C @ polyfills.bbc1c0564b6a5d42ba73.js:1
R.e.then @ polyfills.bbc1c0564b6a5d42ba73.js:1
Z @ polyfills.bbc1c0564b6a5d42ba73.js:1
(anonymous) @ polyfills.bbc1c0564b6a5d42ba73.js:1
(anonymous) @ main.a276ef2d735aa2fdb6d1.js:1
C @ polyfills.bbc1c0564b6a5d42ba73.js:1
c @ main.a276ef2d735aa2fdb6d1.js:1
a @ main.a276ef2d735aa2fdb6d1.js:1
invoke @ polyfills.bbc1c0564b6a5d42ba73.js:1
onInvoke @ main.a276ef2d735aa2fdb6d1.js:1
invoke @ polyfills.bbc1c0564b6a5d42ba73.js:1
run @ polyfills.bbc1c0564b6a5d42ba73.js:1
(anonymous) @ polyfills.bbc1c0564b6a5d42ba73.js:1
invokeTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
onInvokeTask @ main.a276ef2d735aa2fdb6d1.js:1
invokeTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
runTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
m @ polyfills.bbc1c0564b6a5d42ba73.js:1
invokeTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
invoke @ polyfills.bbc1c0564b6a5d42ba73.js:1
n.args.<computed> @ polyfills.bbc1c0564b6a5d42ba73.js:1
setTimeout (async)
i @ polyfills.bbc1c0564b6a5d42ba73.js:1
scheduleTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
onScheduleTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
scheduleTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
scheduleTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
scheduleMacroTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
d @ polyfills.bbc1c0564b6a5d42ba73.js:1
(anonymous) @ polyfills.bbc1c0564b6a5d42ba73.js:1
s.<computed> @ polyfills.bbc1c0564b6a5d42ba73.js:1
(anonymous) @ main.a276ef2d735aa2fdb6d1.js:1
C @ polyfills.bbc1c0564b6a5d42ba73.js:1
(anonymous) @ main.a276ef2d735aa2fdb6d1.js:1
(anonymous) @ main.a276ef2d735aa2fdb6d1.js:1
(anonymous) @ main.a276ef2d735aa2fdb6d1.js:1
i @ main.a276ef2d735aa2fdb6d1.js:1
invoke @ polyfills.bbc1c0564b6a5d42ba73.js:1
onInvoke @ main.a276ef2d735aa2fdb6d1.js:1
invoke @ polyfills.bbc1c0564b6a5d42ba73.js:1
run @ polyfills.bbc1c0564b6a5d42ba73.js:1
(anonymous) @ polyfills.bbc1c0564b6a5d42ba73.js:1
invokeTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
onInvokeTask @ main.a276ef2d735aa2fdb6d1.js:1
invokeTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
runTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
m @ polyfills.bbc1c0564b6a5d42ba73.js:1
Promise.then (async)
k @ polyfills.bbc1c0564b6a5d42ba73.js:1
scheduleTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
onScheduleTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
scheduleTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
scheduleTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
scheduleMicroTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
P @ polyfills.bbc1c0564b6a5d42ba73.js:1
Z @ polyfills.bbc1c0564b6a5d42ba73.js:1
(anonymous) @ polyfills.bbc1c0564b6a5d42ba73.js:1
Promise.then (async)
(anonymous) @ polyfills.bbc1c0564b6a5d42ba73.js:1
C @ polyfills.bbc1c0564b6a5d42ba73.js:1
R.e.then @ polyfills.bbc1c0564b6a5d42ba73.js:1
Z @ polyfills.bbc1c0564b6a5d42ba73.js:1
(anonymous) @ polyfills.bbc1c0564b6a5d42ba73.js:1
(anonymous) @ main.a276ef2d735aa2fdb6d1.js:1
C @ polyfills.bbc1c0564b6a5d42ba73.js:1
c @ main.a276ef2d735aa2fdb6d1.js:1
a @ main.a276ef2d735aa2fdb6d1.js:1
invoke @ polyfills.bbc1c0564b6a5d42ba73.js:1
onInvoke @ main.a276ef2d735aa2fdb6d1.js:1
invoke @ polyfills.bbc1c0564b6a5d42ba73.js:1
run @ polyfills.bbc1c0564b6a5d42ba73.js:1
(anonymous) @ polyfills.bbc1c0564b6a5d42ba73.js:1
invokeTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
onInvokeTask @ main.a276ef2d735aa2fdb6d1.js:1
invokeTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
runTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
m @ polyfills.bbc1c0564b6a5d42ba73.js:1
invokeTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
invoke @ polyfills.bbc1c0564b6a5d42ba73.js:1
n.args.<computed> @ polyfills.bbc1c0564b6a5d42ba73.js:1
setTimeout (async)
i @ polyfills.bbc1c0564b6a5d42ba73.js:1
scheduleTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
onScheduleTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
scheduleTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
scheduleTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
scheduleMacroTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
d @ polyfills.bbc1c0564b6a5d42ba73.js:1
(anonymous) @ polyfills.bbc1c0564b6a5d42ba73.js:1
s.<computed> @ polyfills.bbc1c0564b6a5d42ba73.js:1
(anonymous) @ main.a276ef2d735aa2fdb6d1.js:1
C @ polyfills.bbc1c0564b6a5d42ba73.js:1
(anonymous) @ main.a276ef2d735aa2fdb6d1.js:1
(anonymous) @ main.a276ef2d735aa2fdb6d1.js:1
(anonymous) @ main.a276ef2d735aa2fdb6d1.js:1
i @ main.a276ef2d735aa2fdb6d1.js:1
invoke @ polyfills.bbc1c0564b6a5d42ba73.js:1
onInvoke @ main.a276ef2d735aa2fdb6d1.js:1
invoke @ polyfills.bbc1c0564b6a5d42ba73.js:1
run @ polyfills.bbc1c0564b6a5d42ba73.js:1
(anonymous) @ polyfills.bbc1c0564b6a5d42ba73.js:1
invokeTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
onInvokeTask @ main.a276ef2d735aa2fdb6d1.js:1
invokeTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
runTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
m @ polyfills.bbc1c0564b6a5d42ba73.js:1
Promise.then (async)
k @ polyfills.bbc1c0564b6a5d42ba73.js:1
scheduleTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
onScheduleTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
scheduleTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
scheduleTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
scheduleMicroTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
P @ polyfills.bbc1c0564b6a5d42ba73.js:1
Z @ polyfills.bbc1c0564b6a5d42ba73.js:1
(anonymous) @ polyfills.bbc1c0564b6a5d42ba73.js:1
Promise.then (async)
(anonymous) @ polyfills.bbc1c0564b6a5d42ba73.js:1
C @ polyfills.bbc1c0564b6a5d42ba73.js:1
R.e.then @ polyfills.bbc1c0564b6a5d42ba73.js:1
Z @ polyfills.bbc1c0564b6a5d42ba73.js:1
(anonymous) @ polyfills.bbc1c0564b6a5d42ba73.js:1
(anonymous) @ main.a276ef2d735aa2fdb6d1.js:1
C @ polyfills.bbc1c0564b6a5d42ba73.js:1
c @ main.a276ef2d735aa2fdb6d1.js:1
a @ main.a276ef2d735aa2fdb6d1.js:1
invoke @ polyfills.bbc1c0564b6a5d42ba73.js:1
onInvoke @ main.a276ef2d735aa2fdb6d1.js:1
invoke @ polyfills.bbc1c0564b6a5d42ba73.js:1
run @ polyfills.bbc1c0564b6a5d42ba73.js:1
(anonymous) @ polyfills.bbc1c0564b6a5d42ba73.js:1
invokeTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
onInvokeTask @ main.a276ef2d735aa2fdb6d1.js:1
invokeTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
runTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
m @ polyfills.bbc1c0564b6a5d42ba73.js:1
invokeTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
invoke @ polyfills.bbc1c0564b6a5d42ba73.js:1
n.args.<computed> @ polyfills.bbc1c0564b6a5d42ba73.js:1
main.a276ef2d735aa2fdb6d1.js:1 Last actions before error: (30) ["1615043439029: [Task] Add time spent", "1615043439032: [Project] Update Work End", "1615043439039: [Tag] Update Work End for Tag", "1615043439040: [Persistence] Save to DB", "1615043439040: [Persistence] Save to DB", "1615043439041: [Persistence] Save to DB", "1615043440029: [Task] Add time spent", "1615043440031: [Project] Update Work End", "1615043440040: [Tag] Update Work End for Tag", "1615043440041: [Persistence] Save to DB", "1615043440042: [Persistence] Save to DB", "1615043440043: [Persistence] Save to DB", "1615043441029: [Task] Add time spent", "1615043441030: [Project] Update Work End", "1615043441036: [Tag] Update Work End for Tag", "1615043441037: [Persistence] Save to DB", "1615043441037: [Persistence] Save to DB", "1615043441037: [Persistence] Save to DB", "1615043451962: [Task] Add time spent", "1615043451964: [Project] Update Work End", "1615043451970: [Tag] Update Work End for Tag", "1615043451971: [Persistence] Save to DB", "1615043451972: [Persistence] Save to DB", "1615043451972: [Persistence] Save to DB", "1615043452290: [Task] Add time spent", "1615043452292: [Project] Update Work End", "1615043452326: [Tag] Update Work End for Tag", "1615043452328: [Persistence] Save to DB", "1615043452330: [Persistence] Save to DB", "1615043452332: [Persistence] Save to DB"]
### Stacktrace
```
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1209:30)
makeResolver (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1116:16)
error (webpack:///node_modules/idb/build/esm/wrap-idb-value.js:77:12)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:402:30)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28499:32)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:401:59)
task._transitionTo (webpack:///node_modules/zone.js/dist/zone-evergreen.js:174:46)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:483:33)
callback (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1596:13)
globalZoneAwareCallback (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1622:16)
```

### Meta Info
META: SP6.4.0 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.4.0 Chrome/85.0.4183.121 Electron/10.3.1 Safari/537.36

### Actions Before Error
```
1615043439029: [Task] Add time spent 
1615043439032: [Project] Update Work End 
1615043439039: [Tag] Update Work End for Tag 
1615043439040: [Persistence] Save to DB 
1615043439040: [Persistence] Save to DB 
1615043439041: [Persistence] Save to DB 
1615043440029: [Task] Add time spent 
1615043440031: [Project] Update Work End 
1615043440040: [Tag] Update Work End for Tag 
1615043440041: [Persistence] Save to DB 
1615043440042: [Persistence] Save to DB 
1615043440043: [Persistence] Save to DB 
1615043441029: [Task] Add time spent 
1615043441030: [Project] Update Work End 
1615043441036: [Tag] Update Work End for Tag 
1615043441037: [Persistence] Save to DB 
1615043441037: [Persistence] Save to DB 
1615043441037: [Persistence] Save to DB 
1615043451962: [Task] Add time spent 
1615043451964: [Project] Update Work End 
1615043451970: [Tag] Update Work End for Tag 
1615043451971: [Persistence] Save to DB 
1615043451972: [Persistence] Save to DB 
1615043451972: [Persistence] Save to DB 
1615043452290: [Task] Add time spent 
1615043452292: [Project] Update Work End 
1615043452326: [Tag] Update Work End for Tag 
1615043452328: [Persistence] Save to DB 
1615043452330: [Persistence] Save to DB 
1615043452332: [Persistence] Save to DB
```

**Comment by johannesjo** [comment]
Thanks for opening this up. I hope this will be solved for good with one of the future chromium/electron versions.

**Comment by viktor-strukov** [comment]
Thanks! Great app, may be this bug was caused just by overloading the OS for several days without rebooting, having frozen mouse (no reaction on clicking), but Alt+F4 helped to unload the system and then to cleanup the rest stuff (from vscode).

**Comment by johannesjo** [comment]
A possible cause for this might be also disk space (I encountered it myself, when some app was flooding my system logs uncontrollably). Would be nice to have some better error handling for this, but this would require checking disk space regularly which is not ideal neither...
