### ISSUE TITLE
CalDavSync with Nextcloud Deck does not work

### ISSUE THREAD

**Issue by menelic** [johannesjo/super-productivity#952]
### Your Environment

* Version used: 
SP 6.5.0 snap installedform candidate channel 

* Operating System and version:
Ubuntu 16.04
* Desktop Environment: 
Unity

### Expected Behavior
After entering the base dav url, the Nextcloud user name and password as well as the calendar name, creating a task with a similar name as a deck task should offer the selection of the pre-existing task

### Current Behavior
SP cannot access the Deck tasks, even if the basic connection to the calendar works (see logs below) the tasks from the calendar are not offered for auto-complete when creating a new task. There is however a never-ending spinner indicating a search: 

![image](https://user-images.githubusercontent.com/5934115/110216618-5b894a00-7eb0-11eb-869b-02508b689c9a.png)

### Steps to Reproduce (for bugs)

1. create new project in SP for use with Nextcloud Deck tasks
2. provide CardDav links and login data
3.  create new task in project
4. Deck tasks are not offered for use in SP

### Error Log (Desktop only)

[error] Frontend Error: {
  HANDLED_ERROR_PROP: "Caldav: TypeError: Cannot read property 'toUnixTime' of null"
} undefined

btw: adding the alternative calendar name derived from the private link as described here https://github.com/johannesjo/super-productivity/issues/626#issuecomment-782863856  does not work, it does however produce a different error:

[error] Frontend Error: {
  HANDLED_ERROR_PROP: 'Caldav: Error: CALENDAR NOT FOUND: app-generated--deck--board-43'
} undefined

So it seems in the first instance, with the plain name from the calendar list, SP finds it but cannot access the tasks for some other reason?

To ease usability here, it would be great if:
* there could be a "check connection" option when setting up the CalDav connection
* all tasks harvested from the calendar could be listed for selection (though this of course might already be the case if the connection works?)

@janLo thanks for implementing this - any hints about what I could do differently to make this work?

**Comment by janLo** [comment]
I'd naturally suspect a cors issue (which would be a server configuration issue). EspeciallY if cors errors seem to silently fail and not get given to the application to handle them. You can debug the requests easily with the developer tools. 

The Check-Connection button would be indeed a good option.

**Comment by menelic** [comment]
thanks for the swift reply - unfortunately 

> You can debug the requests easily with the developer tools.

I cannot do that _easily_ as I am not a programmer. However you are able to provide a quick how-to I will definitely try to get the info, data or test results needed to fix this. If this refers to Nextcloud, server side developer tools that would however be more difficult as I d have to pass the request on.

**Comment by janLo** [comment]
How do you use the app? Do you use the web version, she desktop version or a mobile app? Cors is an issue on web and mobile but should not on the desktop.

If cors is the issue you should get it working by asking the administrator of your nextxloud instance to install and configure an app called WebAppPassword.

If you experience this with the desktop app then we need to look further into this.

**Comment by menelic** [comment]
I am using the desktop app, a snap install on Ubuntu 16.04

>Your Environment

 >   Version used:
 >   SP 6.5.0 snap installed form candidate channel

>   Operating System and version:
>   Ubuntu 16.04

>    Desktop Environment:
>    Unity

so...let me know what I can do so we can investigate further. I have created a test deck on NC, the cards are properly displayed in NC tasks so the CalDAV data should be there. As explained above, login via SP CalDAV seems to work as far as I can tell

**Comment by janLo** [comment]
Ok, sorry, it seems I missed half of the report. I'm only having the GitHub mobile app here. Can you press ctrl-shift-i and see if the developer tools show up. Then reproduce the error and see if there is a stacktrace in the console that leads to something.

I will try to reproduce it myself although so far I haven't had any problems.

**Comment by menelic** [comment]
I do not know if this is a stacktrace (searching for "stacktrace" in the developer tools console did not turn up anything) but the developer tools listed one error and "issues pertaining to the operations. there is a specific Caldav error message and specific caldav info in the issues pertaining to cookies as well, I have pasted screenshots of both below:

![image](https://user-images.githubusercontent.com/5934115/110395527-96d17780-806e-11eb-9f08-01b841c7b20f.png)


  | handleError | @ | main.c2e649c….js:1
-- | -- | -- | --
  | (anonymous) | @ | main.c2e649c….js:1
  | error | @ | main.c2e649c….js:1
  | notifyError | @ | main.c2e649c….js:1
  | _error | @ | main.c2e649c….js:1
  | error | @ | main.c2e649c….js:1
  | notifyError | @ | main.c2e649c….js:1
  | _error | @ | main.c2e649c….js:1
  | error | @ | main.c2e649c….js:1
  | _error | @ | main.c2e649c….js:1
  | error | @ | main.c2e649c….js:1
  | notifyError | @ | main.c2e649c….js:1
  | _error | @ | main.c2e649c….js:1
  | error | @ | main.c2e649c….js:1
  | notifyError | @ | main.c2e649c….js:1
  | _error | @ | main.c2e649c….js:1
  | error | @ | main.c2e649c….js:1
  | (anonymous) | @ | main.c2e649c….js:1
  | _trySubscribe | @ | main.c2e649c….js:1
  | subscribe | @ | main.c2e649c….js:1
  | c | @ | main.c2e649c….js:1
  | error | @ | main.c2e649c….js:1
  | (anonymous) | @ | main.c2e649c….js:1
  | invoke | @ | polyfills.bbc1c05….js:1
  | onInvoke | @ | main.c2e649c….js:1
  | invoke | @ | polyfills.bbc1c05….js:1
  | run | @ | polyfills.bbc1c05….js:1
  | (anonymous) | @ | polyfills.bbc1c05….js:1
  | invokeTask | @ | polyfills.bbc1c05….js:1
  | onInvokeTask | @ | main.c2e649c….js:1
  | invokeTask | @ | polyfills.bbc1c05….js:1
  | runTask | @ | polyfills.bbc1c05….js:1
  | m | @ | polyfills.bbc1c05….js:1
  | invokeTask | @ | polyfills.bbc1c05….js:1
  | _ | @ | polyfills.bbc1c05….js:1
  | k | @ | polyfills.bbc1c05….js:1

Here is the info on the issues:

![image](https://user-images.githubusercontent.com/5934115/110396114-b2894d80-806f-11eb-8ac4-0042b19112d4.png)

**Comment by janLo** [comment]
It seems that it was a mistake to rely on the last-modified timestamp to detect task changes. The deck-app-integration does not always set this field. I'll change it to use a hashed version of the etag value.

**Comment by menelic** [comment]
This works - having installed the edge snap (which can be installed along side any other release channel using the[ snap parallel installs feature](https://snapcraft.io/docs/parallel-installs)) , deck tasks are offered for autocompletion, tags and description from deck are also downloaded. Deck description field content is displayed in the CALDav side tab as well. I believe it is a good thing that there is a separate description field in SP for more personal notes - but given the duplication of names maybe description could be re-named "task notes" or "about this task". Here is hoping for further integration:

-  seeing that list titles are imported it would be great if the actual lists could be imported as well, preferably as sub-tasks.
- tasks marked as completed in SP  should register as such in Deck, maybe there could be an option or a syntax in SP to move them to other deck stacks if there are "done/completed" stacks.

![deck sp test succes with edge channel - description](https://user-images.githubusercontent.com/5934115/111075205-25b71780-84e7-11eb-94f8-e15bf0edd555.png)

**Comment by janLo** [comment]
Thank you for your feedback. 

Your suggestions you da very helpful. It would probably be best if you open separate issues for these so that they can be considered one at a time.

Regarding the completion status: that's actually implemented for caldav tasks. I think the problem here is that the deck-caldav-integration on the Nextcloud side is somewhat limited. The same is true for the list handling.

It might be necessary to use the deck API directly instead if interfacing via the caldav integration for this. Another alternative is to ask the deck maintainer to expose this via their caldav interface.

Also I don't know if im not sure how well the caldav task nesting can be projected to sp subtasks, as caldav in theory allows arbitrary levels of nesting where each task on each level is just a normal task with optionally a parent task set.

**Comment by johannesjo** [comment]
Thanks for your input on this! A separate issue for this would be good (this one is already considered done and closed). I also reached out to @juliushaertl . Maybe he can help us with this.
