### ISSUE TITLE
Error: Uncaught (in promise): Error: UnknownError: Internal error opening backing store for indexedDB.open

### ISSUE THREAD

**Issue by bhupesh-sf** [johannesjo/super-productivity#955]
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
alert (webpack:///src/app/core/persistence/database.service.ts:89:12)
Ur (file:///snap/superproductivity/1030/resources/app.asar/dist/main.a276ef2d735aa2fdb6d1.js:1:2404901)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28512:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:367:51)
run (webpack:///node_modules/zone.js/dist/zone-evergreen.js:130:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1272:35)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:402:30)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28499:32)
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1209:30)
value.hasOwnProperty (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1163:16)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1275:16)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:402:30)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28499:32)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:401:59)
task._transitionTo (webpack:///node_modules/zone.js/dist/zone-evergreen.js:174:46)
drainMicroTaskQueue (webpack:///node_modules/zone.js/dist/zone-evergreen.js:578:34)
task.zone.runTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:487:20)
callback (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1596:13)
```

### Meta Info
META: SP6.4.0 Electron – en-GB – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.4.0 Chrome/85.0.4183.121 Electron/10.3.1 Safari/537.36

### Actions Before Error
```
1615182592056: [Project] Update Work End 
1615182592057: [Tag] Update Work End for Tag 
1615182592062: [Persistence] Save to DB 
1615182592063: [Persistence] Save to DB 
1615182592063: [Persistence] Save to DB 
1615182593055: [Task] Add time spent 
1615182593056: [Project] Update Work End 
1615182593057: [Tag] Update Work End for Tag 
1615182593065: [Persistence] Save to DB 
1615182593065: [Persistence] Save to DB 
1615182593066: [Persistence] Save to DB 
1615182594056: [Task] Add time spent 
1615182594060: [Project] Update Work End 
1615182594062: [Tag] Update Work End for Tag 
1615182594079: [Persistence] Save to DB 
1615182594080: [Persistence] Save to DB 
1615182594081: [Persistence] Save to DB 
1615182595055: [Task] Add time spent 
1615182595056: [Project] Update Work End 
1615182595057: [Tag] Update Work End for Tag 
1615182595063: [Persistence] Save to DB 
1615182595063: [Persistence] Save to DB 
1615182595064: [Persistence] Save to DB 
1615182598400: [Task] Add time spent 
1615182598402: [Project] Update Work End 
1615182598403: [Tag] Update Work End for Tag 
1615182598411: [Persistence] Save to DB 
1615182598412: [Persistence] Save to DB 
1615182598413: [Persistence] Save to DB 
1615182598433: [Layout] Hide SideBar
```

Error: Uncaught (in promise): Error: UnknownError: Internal error opening backing store for indexedDB.open. at e. (file:///snap/superproductivity/1030/resources/app.asar/dist/main.a276ef2d735aa2fdb6d1.js:1:2406595)    at Generator.throw ()    at o (file:///snap/superproductivity/1030/resources/app.asar/dist/main.a276ef2d735aa2fdb6d1.js:1:2404901)    at l.invoke (file:///snap/superproductivity/1030/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6572)    at Object.onInvoke (file:///snap/superproductivity/1030/resources/app.asar/dist/main.a276ef2d735aa2fdb6d1.js:1:1603753)    at l.invoke (file:///snap/superproductivity/1030/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6512)    at i.run (file:///snap/superproductivity/1030/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:1984)    at file:///snap/superproductivity/1030/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:16758    at l.invokeTask (file:///snap/superproductivity/1030/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:7190)    at Object.onInvokeTask (file:///snap/superproductivity/1030/resources/app.asar/dist/main.a276ef2d735aa2fdb6d1.js:1:1603569)

**Comment by johannesjo** [comment]
Thank you very much for reporting this (and sorry for the lat reply). Theoretically this should be fixed with one of the next electron/chromium releases) so there might not be much we can do now unfortunately.
