### ISSUE TITLE
Break Reminder Popping Up Pretty Often, If One Does Not Provide A Value Letting The App Knows When To Remind You

### ISSUE THREAD

**Issue by tra38** [johannesjo/super-productivity#96]
## Your Environment
* Version used: 1.10.45, used the superProductivity-1.10.45.exe file located on the Releases page
* Operating System and version: Windows 7

## Expected Behavior
When I "enable take a break reminder", and I do not provide an actual time limit for when I actually do need a reminder, I expect a reasonable default value to be filled in instead.

## Current Behavior
I get alerts every minute asking me to take a break. Every so often, I get a message like "Take a break! You have been working for 1s without one." Even if I enter into the app and press "I Already Took One!" button, this resets the timer only temporarily, and then a few seconds later, I get another message reminding me to take a break.

There is a textbook called "Remind when I work longer than X without a break". If you type in a possible number into the textbox, and then erase it, then you see the textbox highlighted in red, indicating an error. But the application will still continue even if you see that red highlight, so the value appears to be optional. If you exit the settings page and returns, the red highlighting goes away as well.

## Steps to Reproduce (for bugs)
1. Go into settings.
2. Click on the Misc. Settings tab.
3. Click on "Enable take a break reminder".
4. Do not fill in the "Remind when I worked longer than X without break". If you do have a value there, delete it.
5. Start the timer.
6. Enjoy seeing reminders about breaks.

Users could avoid the issue by providing a value in the textbox (so the application knows not to bug them about breaks).

## Console Output
"mdInput messages show animation called on invalid messagge element: JQLite(1) [an array containing one element: md-input-container.ng-scope.md-blue-theme-theme ]"

I've seen this message appear multiple times when I'm testing out what happens when you type in and  erase values in the "Remind when I worked longer than X without a break" textbox. This seems to indicate when red highlighting gets applied.

**Comment by johannesjo** [comment]
Thanks for reporting. Makes a lot of sense. Will implement this as soon as I can.

**Comment by johannesjo** [comment]
Should be fixed now. Thanks for reporting again.
