### ISSUE TITLE
update from 6.4.0 to 6.5.0 not possible with microsoft store

### ISSUE THREAD

**Issue by raot** [johannesjo/super-productivity#961]
### Your Environment
Windows 10, Super Productivity 6.4.0

### Expected Behavior
I installed Super Productivity 6.4.0 on my windows box using microsoft store. Now I noticed that 6.5.0 is out and wanted to upgrade. Opening microsoft store offers me the possibilty to install on my other pcs but not to upgrade my current pc.

Going to Microsoft Store - two options available: Start and ...
![image](https://user-images.githubusercontent.com/5304545/110444472-5816de00-80bd-11eb-82b0-2839679d2e96.png)

second option: install on other computers:
![image](https://user-images.githubusercontent.com/5304545/110444725-a88e3b80-80bd-11eb-9411-9289c8627156.png)

![image](https://user-images.githubusercontent.com/5304545/110444839-c5c30a00-80bd-11eb-8c96-53a233d71089.png)

Update option is missing.

**Comment by johannesjo** [comment]
Hi there! Thanks for opening this up! The store build usually needs a bit longer as it needs to be greenlit by MS.
