### ISSUE TITLE
Browser default

### ISSUE THREAD

**Issue by emsellem** [johannesjo/super-productivity#969]
Fantastic App. Amazing job and integration.

One thing: I couldn't find a way to change the browser default (opening Firefox while I would like a new Chrome Tab when clicking on a URL bookmark). Will try to see if I can find it, but in case you have a quick shortcut for that.

thanks again for the amazing work.

**Comment by johannesjo** [comment]
Hi there! Thanks for opening this up! The app should use the default system browser. Do you want to use a different browser than that?

**Comment by emsellem** [comment]
Thanks. Well actually my default browser is Chrome. So I guess somewhere it is not defined properly (on my side?).

I am using KUbuntu 20.04. So I guess the problem is on my side (it works well with other Apps, but maybe there is still a default Firefox setting somewhere).

I'll dig in further. Thanks!
