### ISSUE TITLE
Integration for private github repos

### ISSUE THREAD

**Issue by cameronhr** [johannesjo/super-productivity#97]
## Your Environment
* Version used: v1.10.45
* Operating System and version: ubuntu 16.04
* Desktop Environment: gnome
* Browser Name and version: n/a

## Expected Behavior

* Would be great to be able to provide the app with my GitHub credentials to allow it to listen for issues in a private repository

## Current Behavior
* When a private repo is included in the "Git Integration" section of Project Specific Settings, nothing occurs

**Comment by Fusion** [comment]
Hi. Why was this closed? Was it implemented? Thanks!

**Comment by johannesjo** [comment]
No it wasn't. But here hasn't been any activity for quite a long time. :)

**Comment by johannesjo** [comment]
Also this is kind of related: #188

**Comment by schiavone1** [comment]
This would be a very useful feature!

**Comment by MostafaAmin07** [comment]
I looked into this and I understand what it needs to be implemented.
The user needs to create an access token in GitHub then input this token in the application.
This token will be used in the HttpHeaders for every request made to the API.

One access token is all that is needed to access all your private repos, but I can think of a reason to have a separate access token for each repo.
@johannesjo I will make a PR for it and let you updated with what I did.

**Comment by johannesjo** [comment]
@MostafaAmin07 That's really great! Please let me know if I can assist you in any way!

It might be even useful to have that for GitHub users without private repos, as it would allow us to improve the user experience without the danger of hitting that api limit all the time. But that's for the future!
