### ISSUE TITLE
[Feature] Add tags to projects

### ISSUE THREAD

**Issue by danimesq** [johannesjo/super-productivity#972]

**Comment by johannesjo** [comment]
Thanks for opening this up. This is currently not planned, but if a lot of people request this (please upvote the original issue), then I might change my mind.

**Comment by DaniellMesquita** [comment]
That would be very useful for organizing/sorting out your projects.

**Comment by topoescobar** [comment]
A very necessary implementation for the use that I give to the app, I like to separate all the projects into large categories, (study, work and hobbies) and in general a project always has the same label.
