### ISSUE TITLE
[Feature] Automatically add all GitHub/GitLab issues as tasks of a integrated project

### ISSUE THREAD

**Issue by danimesq** [johannesjo/super-productivity#973]
Would like if they loaded but didn't.

![Screenshot from 2021-03-12 22-08-35](https://user-images.githubusercontent.com/6765277/111013779-862b4500-837f-11eb-9ad1-bc7d6829715a.png)

**Comment by johannesjo** [comment]
Sorry, this slipped under my radar for some unknown reason. Unless there is a very limited amount of issues, I recommend adding issues as needed, as every issue is polled for changes, when the list it is on is selected.
