### ISSUE TITLE
[Feature] Ask to add a new task also as a GitHub/GitLab issue on the project

### ISSUE THREAD

**Issue by danimesq** [johannesjo/super-productivity#974]

**Comment by DaniellMesquita** [comment]
When adding an new task to an project synced with GitHub, ask to also add as an issue to GitHub (or GitLab, or both). If not online, add the issue offline for later syncing.

**Comment by johannesjo** [comment]
Thanks for opening this up. Would be nice to have this optionally available. PRs welcome.
