### ISSUE TITLE
Error: Uncaught (in promise): Error: No in memory copy yet

### ISSUE THREAD

**Issue by ishwarvh** [johannesjo/super-productivity#976]
### Steps to Reproduce

Procrastination
Procrastination is an emotion regulation problem, not a time management problem.

Error: No in memory copy yet
! Please copy & report !

Error: No in memory copy yet
_updateInMemory (webpack:///src/app/core/persistence/persistence.service.ts:596:12)
_saveToDb (webpack:///src/app/core/persistence/persistence.service.ts:545:11)
Ur (file:///snap/superproductivity/1044/resources/app.asar/dist/main.c2e649cce333ff00c62f.js:1:1706873)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28535:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:367:51)
run (webpack:///node_modules/zone.js/dist/zone-evergreen.js:130:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1272:35)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:402:30)
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1209:30)
value.hasOwnProperty (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1163:16)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1275:16)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:402:30)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28522:32)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:401:59)
task._transitionTo (webpack:///node_modules/zone.js/dist/zone-evergreen.js:174:46)
drainMicroTaskQueue (webpack:///node_modules/zone.js/dist/zone-evergreen.js:578:34)
META: SP6.5.0 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.5.0 Chrome/85.0.4183.121 Electron/10.3.1 Safari/537.36
Reload App

### Stacktrace
```
_updateInMemory (webpack:///src/app/core/persistence/persistence.service.ts:596:12)
_saveToDb (webpack:///src/app/core/persistence/persistence.service.ts:545:11)
Ur (file:///snap/superproductivity/1044/resources/app.asar/dist/main.c2e649cce333ff00c62f.js:1:1706873)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28535:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:367:51)
run (webpack:///node_modules/zone.js/dist/zone-evergreen.js:130:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1272:35)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:402:30)
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1209:30)
value.hasOwnProperty (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1163:16)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1275:16)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:402:30)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28522:32)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:401:59)
task._transitionTo (webpack:///node_modules/zone.js/dist/zone-evergreen.js:174:46)
drainMicroTaskQueue (webpack:///node_modules/zone.js/dist/zone-evergreen.js:578:34)
```

### Meta Info
META: SP6.5.0 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.5.0 Chrome/85.0.4183.121 Electron/10.3.1 Safari/537.36

### Actions Before Error
```
1615672879426: [Persistence] Save to DB 
1615672879426: [Persistence] Save to DB 
1615672879427: [Persistence] Save to DB 
1615672879427: [Persistence] Save to DB 
1615672879427: [Persistence] Save to DB 
1615672879427: [Persistence] Save to DB 
1615672879427: [Persistence] Save to DB 
1615672879428: [Persistence] Save to DB
```

**Comment by johannesjo** [comment]
Thank you very much for reporting this!
