### ISSUE TITLE
[Feature] tag docker images with release versions 

### ISSUE THREAD

**Issue by meyca** [johannesjo/super-productivity#977]
## Problem Statement
Using the docker setup allows a self-hosted use of this super cool productivity app. However, the currently available tags on docker hub are "latest" and "candidate" only. If there is a glitch in master there is no easy way to revert to a previous version.

## :grey_question: Possible Solution
Include docker images into the release process AND tag the images uploaded to docker hub according to the release.

## :heavy_plus_sign: Additional context
The current latest image of the container does not open in my browsers (latest Firefox and Chrome on Ubuntu) but stays on the loading page. The canditate (BTW: that's a typo) image opens as usual.

**Comment by johannesjo** [comment]
Hey there! Thanks for opening this up! I agree that this makes a lot of sense! Any volunteers to help with that?

Also: May I ask what kind of error is shown in the browser console for the latest build?

**Comment by meyca** [comment]
Just managed to setup a local test environment and reproduce the error with "latest" (docker digest: sha256:a8954f97f5de[...]) from Docker hub. Regarding the browser console, here is what I found. And I have no idea why the logs differ so much between browsers.
Chrome: 
![grafik](https://user-images.githubusercontent.com/408161/111215902-fb8f5380-85d3-11eb-9434-748ea8f13519.png)

Firefox
![grafik](https://user-images.githubusercontent.com/408161/111216627-ecf56c00-85d4-11eb-8904-3e0a4a11fdab.png)

**Comment by meyca** [comment]
Regarding help I plan to fork this repo and play around with Github actions (https://docs.github.com/en/actions/guides/publishing-docker-images) and - if I am lucky - file a PR. 

Do you currently build and upload docker images manually?

**Comment by johannesjo** [comment]
Hi @meyca! Thanks for the offer. Much appreciated! 

There is no release process for the docker image. Ideally I'd like to keep things as simple as possible. :)

**Comment by meyca** [comment]
What is the use of the existing Dockerfile? Tests in there are commented out and .github/workflows contain tests. How do you currently release the image <https://hub.docker.com/r/johannesjo/super-productivity>? Anything I can build upon?

**Comment by johannesjo** [comment]
I use the automated build feature form https://hub.docker.com/

![Screenshot from 2021-03-21 16-37-11](https://user-images.githubusercontent.com/1456265/111910953-c2d3fc00-8a63-11eb-8466-7afc725979a9.png)
