### ISSUE TITLE
Error: No first tag

### ISSUE THREAD

**Issue by nicolopinci** [johannesjo/super-productivity#987]
### Steps to Reproduce

1. In the desktop app, in a day that has already started, you want to add a new acivity
2. Press on the + button on top
3. Start typing something
4. You get this error only sometimes, depending on what you are typing, but I observe that I get the error always with the same words
5. With the same words, initially I did not get the error
6. Note: if I keep typing while the error is shown, I can add the activity anyway

### Stacktrace
```
this._projectService.getByIdOnce$(projectId).toPromise (webpack:///src/app/features/tasks/add-task-bar/add-task-bar.component.ts:296:14)
Ur (file:///snap/superproductivity/1044/resources/app.asar/dist/main.c2e649cce333ff00c62f.js:1:3406306)
constructor (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1383:28)
Ur (file:///snap/superproductivity/1044/resources/app.asar/dist/main.c2e649cce333ff00c62f.js:1:3406051)
Ur (file:///snap/superproductivity/1044/resources/app.asar/dist/main.c2e649cce333ff00c62f.js:1:3414812)
_getCtxForTaskSuggestion (webpack:///src/app/features/tasks/add-task-bar/add-task-bar.component.ts:356:29)
map (webpack:///src/app/features/tasks/add-task-bar/add-task-bar.component.ts:354:27)
_next (webpack:///node_modules/rxjs/_esm2015/internal/operators/switchMap.js:28:26)
```

### Meta Info
META: SP6.5.0 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.5.0 Chrome/85.0.4183.121 Electron/10.3.1 Safari/537.36

### Actions Before Error
```
1616246171686: [Persistence] Save to DB 
1616246172815: [Layout] Hide AddTaskBar 
1616246176847: [Task] SetSelectedTask 
1616246198415: [Task] Update Task 
1616246198418: [Persistence] Save to DB 
1616246198439: [Task] Update Task 
1616246198442: [Persistence] Save to DB 
1616246203491: [Task] Update Task 
1616246203494: [Persistence] Save to DB 
1616246203525: [Task] Update Task 
1616246203529: [Persistence] Save to DB 
1616246207830: [Task] Update Task 
1616246207857: [Persistence] Save to DB 
1616246207911: [Task] Update Task 
1616246207916: [Persistence] Save to DB 
1616246214366: [Task] Update Task 
1616246214392: [Persistence] Save to DB 
1616246214421: [Task] Update Task 
1616246214427: [Persistence] Save to DB 
1616246216887: [Task] Update Task 
1616246216895: [Persistence] Save to DB 
1616246219572: [Task] SetSelectedTask 
1616256381807: [Layout] Show AddTaskBar 
1616256391165: [Task][Issue] Add Task 
1616256391206: [Persistence] Save to DB 
1616256391207: [Persistence] Save to DB 
1616256391556: [Task] Update Task 
1616256391559: [Persistence] Save to DB 
1616256392501: [Layout] Hide AddTaskBar 
1616260205515: [Layout] Show AddTaskBar
```

**Comment by johannesjo** [comment]
Hey there! Thank you very much for reporting this! I never experienced this myself and I am unable to reproduce this. 


> * You get this error only sometimes, depending on what you are typing, but I observe that I get the error always with the same words

May I ask, what those words are?

It might also be that for some reason a bit of your data got into an invalid state that I didn't account for and that I can't reproduce. It might be helpful if you could share a copy of your data to contact@super-productivity.com, so I can debug this on my computer. You can create an export by navigating to "Settings" and then to "Import/Export".

**Comment by nicolopinci** [comment]
Thank you for having created this application! I don't remember all of
them, but today the problems were with "NAN" and "DB2". And Maybe it could
be useful to know that when I try with superstrings of these words starting
with another letter there is no problem (ex. CNAN is fine), even if later I
edit the word to the one I wanted in the first place. Anyway, I can share
alle the data with you!
Thank you very much also for your dedication and your time.
Best,
Nicolò

Il giorno sab 20 mar 2021 alle ore 20:18 Johannes Millan <
***@***.***> ha scritto:

**Comment by johannesjo** [comment]
Thank you very much for the data! I was able to find the cause of the issue, which were some orphaned tasks (without neither tag or project id). I added this case to the automatic data repair scripts. A new release should be available on the edge channel soon, which should allow you to fix your data.

**Comment by nicolopinci** [comment]
Thank you!

________________________________
Da: Johannes Millan ***@***.***>
Inviato: sabato 20 marzo 2021 22:03
A: johannesjo/super-productivity
Cc: Nicolò Pinciroli; Author
Oggetto: Re: [johannesjo/super-productivity] Error: No first tag (#987)


Thank you very much for the data! I was able to find the cause of the issue, which were some orphaned tasks (without neither tag or project id). I added this case to the automatic data repair scripts. A new release should be available on the edge channel soon, which should allow you to fix your data.
