### ISSUE TITLE
Uncaught ReferenceError: assignment to undeclared variable ICAL if using docker image

### ISSUE THREAD

**Issue by meyca** [johannesjo/super-productivity#989]
### Your Environment
* Version used: Docker-build master (commit: 8dc6cbc / 6.5.2)
* Operating System and version: dockerfile: from nginx:1-alpine
* Desktop Environment: XUbuntu 20.04
* Browser Name and version: Firefox 86

### Expected Behavior
SuperProductivity opens after initial load. 

### Current Behavior
The initial startup screen stays and the app does not open.

### Steps to Reproduce (for bugs)
1. use docker nginx-distribution and open the app in the browser

### Console Output
Uncaught ReferenceError: assignment to undeclared variable ICAL
    UeCU ical.js:11
    Webpack 20

Is this related to <https://github.com/mozilla-comm/ical.js/issues/449> and <https://github.com/mozilla-comm/ical.js/pull/450>?

**Comment by meyca** [comment]
#977

**Comment by johannesjo** [comment]
Thanks for opening this up!
