### ISSUE TITLE
Keyboard Shortcut Mouseovers

### ISSUE THREAD

**Issue by Quincunx271** [johannesjo/super-productivity#991]
## Problem Statement
I constantly forget the keyboard shortcuts, but I want to learn them to make it faster for me to use the app.

## :grey_question: Possible Solution

Add the keyboard shortcut to the mouseover text of all clickable action elements that have keyboard shortcuts. I have seen this idea before in RTS games, but rarely in other contexts.

## :arrow_heading_up: Describe alternatives you've considered

VSCode has a "do everything" shortcut in which you can search for the action you wish to take. In short, Ctrl+Shift+P opens the "command palette", from which you can choose an action, and if a keyboard shortcut is set for that action, the command palette will also tell you what the keyboard shortcut is. This solution would work too, and could possibly be superior due to aiding discoverability.

**Comment by johannesjo** [comment]
Hi there! Thanks for the suggestion! I like the idea. Apart from the task list itself where it could have a negative performance impact if done poorly I am open to this. PRs would be welcome.

**Comment by johannesjo** [comment]
Better in terms of potential performance impact would be a quick overlay with all shortcuts. Maybe this is the better solution here, because of performance and because it is easier to maintain, though less elegant and than what you propose.

**Comment by Quincunx271** [comment]
Yes, I would still love this feature, but other things in my life have had higher priority, especially because I'm not familiar with the languages, frameworks, and general ecosystems that this tool uses.

**Comment by fred-sab** [comment]
I would also find this feature very useful, either showing the shortcuts on mouseover, or with an easily accessible overlay (e.g. like gmail with "shift-?").

**Comment by js402882** [comment]
I really like the way some web and desktop apps do it - a shortcut (its usually something like <Shift>?) to display shortcuts overview. Example from GMail web app

![image](https://user-images.githubusercontent.com/4029505/145373788-7458b1a4-3d4d-40e6-9bfc-800b433c6fe5.png)

Some others do it the same - ProtonMail web app, Vimium browser plugin, ...

**Comment by johannesjo** [comment]
PRs for this are welcome!

**Comment by tmlmt** [comment]
Hey @johannesjo et al., as a new user I've also been facing this issue: not knowing (yet?) the shortcuts by heart, I feel a bit frustrated, and it took me a while to find out that the list of shortcuts were in the many settings menus. 

> EDIT: My mistake. Just checked the code and it is already done this way and seems to work without problems. So showing the shortcuts should be doable.

I understand from your comment here Johannes that you basically say we can add the shortcut in the hover text, right? 
For instance, adding ` (i)` at the end of the following tooltip? 
![image](https://github.com/johannesjo/super-productivity/assets/10244927/007011fc-b4dd-43d9-94ae-7fb7381bcf36)

I can try to help if you agree on the development.

**Comment by johannesjo** [comment]
@tmlmt that's great news! Thank you!

As mentioned above, we should try to keep an eye on the performance impact when implementing this. So I think it is important to test the impact of this on different actions (initial render time, reorder, marking a task as done) with a lot of tasks in the list (maybe around 200) to see if there are noticeable differences.
