### ISSUE TITLE
Adding Italian Translation

### ISSUE THREAD

**Issue by tiziodcaio** [johannesjo/super-productivity#996]
If you leave me the english text strings, I would translate them in Italian

**Comment by johannesjo** [comment]
Hi there! Thank you very much for the offer! 

All translation files can be found here:
https://github.com/johannesjo/super-productivity/tree/master/src/assets/i18n
en.json is the source and it.json is for Italian.

**Comment by tiziodcaio** [comment]
Due to a lot of problems, I don't know if I will have time to finish the project.

**Comment by johannesjo** [comment]
No worries! :)

**Comment by tiziodcaio** [comment]
In case I will make me alive again
