### ISSUE TITLE
Error: Uncaught (in promise): Error: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase'

### ISSUE THREAD

**Issue by a4bits** [johannesjo/super-productivity#998]
sometimes while working I get this error, it tells me to reload app

Error: Uncaught (in promise): Error: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing. Error: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing. at t. (file:///snap/superproductivity/1061/resources/app.asar/dist/main.a12b0909ceb50cdaf7c3.js:1:2685296) at Generator.throw () at o (file:///snap/superproductivity/1061/resources/app.asar/dist/main.a12b0909ceb50cdaf7c3.js:1:2684500) at l.invoke (file:///snap/superproductivity/1061/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6572) at Object.onInvoke (file:///snap/superproductivity/1061/resources/app.asar/dist/main.a12b0909ceb50cdaf7c3.js:1:1903087) at l.invoke (file:///snap/superproductivity/1061/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6512) at i.run (file:///snap/superproductivity/1061/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:1984) at file:///snap/superproductivity/1061/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:16758 at l.invokeTask (file:///snap/superproductivity/1061/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:7190) at Object.onInvokeTask (file:///snap/superproductivity/1061/resources/app.asar/dist/main.a12b0909ceb50cdaf7c3.js:1:1902903)
await (webpack:///src/app/core/persistence/database.service.ts:58:12)
Ur (file:///snap/superproductivity/1061/resources/app.asar/dist/main.a12b0909ceb50cdaf7c3.js:1:2684500)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28535:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:367:51)
run (webpack:///node_modules/zone.js/dist/zone-evergreen.js:130:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1272:35)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:402:30)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28522:32)

META: SP6.5.2 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.5.2 Chrome/85.0.4183.121 Electron/10.3.1 Safari/537.36

**Comment by johannesjo** [comment]
Thank you very much for reporting this. Probably related #816
